### ISSUE TITLE
Fix assembly reference resolution in .Cosmos project

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#10]
Visually, the project references are unresolved (yellow exclamation mark). Compilation however works.

**Comment by kant2002** [comment]
Looks like we have this issue only when referencing projects within solution folders. I.e. when C#/F#/VB.NET project is inside solution folder, then warning message is displayed.
Error is in the Managed Package Framework which is not handling this case correctly.

**Comment by mterwoord** [comment]
But seems the MPF is a bunch of source files we include. We should be able to trace and fix it?

**Comment by kant2002** [comment]
This issue with fix described here.
https://mpfproj11.codeplex.com/workitem/1466

Will apply fix from that workitem to our project.

**Comment by mterwoord** [comment]
Could you also see in https://mpfproj12.codeplex.com/ if there's anything we miss?
