### ISSUE TITLE
Need to rename main.map to CosmosGraphicSubsystem.map manully

### ISSUE THREAD

**Issue by prepare** [CosmosOS/Cosmos#1001]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Building + Run CosmosGraphicSubsystem project from source, VS2017 15.7.4, Win7 x64.

#### Expected Behaviour - What do you think that should happen?

1. Build system should generate CosmosGraphicSubsystem.map

and 

2. VS2017 debug should stop at a specific break point.

#### Actual Behaviour - What unexpectedly happens?

1.  Build system generates _main.map_

and VS2017 build says it need  CosmosGraphicSubsystem.map

![cosmos_4](https://user-images.githubusercontent.com/7447159/42230225-9c4ef6e8-7f12-11e8-9440-2c9dee24d516.png)

_pic 1: main.map file is auto inserted after 1st build, no CosmosGraphicSubsystem.map_

So I need to rename main.map to CosmosGraphicSubsystem.map
and Run again.

![cosmos_5](https://user-images.githubusercontent.com/7447159/42230391-15c8e182-7f13-11e8-81d2-ced30f1650ea.png)

_pic 2: rename it manually to CosmosGraphicSubsystem.map, build+run =>pass_

---

2.  VS2017 debugger dose not stop at a given break point.

#### Reproduction - How did you get this error to appear?

 I build the CosmosGraphicSubsystem 
  

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev Kit
Cosmos from git clone , master branch
IL2CPU from git clone , master branch
X# from git clone , master branch

**Comment by fanoI** [comment]
Thanks for the analysis of the bug!
Do you want to try to fix it too? Probably is a line change in the project files...

**Comment by prepare** [comment]
Yes. I want to.

But I'm very new to the build system.

so please guide me

:)

**Comment by fanoI** [comment]
Effectively neither me know how msbuild wrks well... @jp2masa says that probably the modification should be done here: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Build.Tasks/build/Cosmos.Build.targets#L187

**Comment by prepare** [comment]
@fanoI : 
 
please visit this => https://github.com/PaintLab/PixelFarm/issues/31 too

:)
