### ISSUE TITLE
devkit not installing

### ISSUE THREAD

**Issue by bluethefoxyt** [CosmosOS/Cosmos#1002]
the install of the devkit

it should install the devkit into VS2017

it doesn't install the devkit and proceeds to show errors

run the installer (install-VS2017.bat)

version: latest download(i dont know the version number)

the error i get

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU and XSharp is installed.
Visual Studio 15.5+ is installed.
Visual Studio Workloads not found.

========================================
    Error
========================================

System.InvalidOperationException: Cannot set Owner property to a Window that has not been shown previously.
   at System.Windows.Window.set_Owner(Window value)
   at Cosmos.Build.Builder.Services.DialogService`2.ShowDialog(TViewModel viewModel)
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by jp2masa** [comment]
Try swapping these lines: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Build.Builder/App.xaml.cs#L86-L87.

**Comment by bluethefoxyt** [comment]
@jp2masa it hangs on this window
![image](https://user-images.githubusercontent.com/21036927/42345879-b619682e-8098-11e8-96f4-0ce9bf2d81ce.png)

**Comment by jp2masa** [comment]
Are you sure it's hanging? It's probably running the VS installer on the background.

**Comment by bluethefoxyt** [comment]
@jp2masa yes it is hanging and it doesn't start the VS installer ive looked in task manager and nothing had showed up that even remotely relates to visual studio sorry if im sounding angry im not trying to be

**Comment by bluethefoxyt** [comment]
@jp2masa it shows for a second then closes

**Comment by bluethefoxyt** [comment]
@jp2masa are you sure you dont need me to modify more code

**Comment by jp2masa** [comment]
Check if there's some error reported in the main window. Also try clicking on "Cancel".

**Comment by jp2masa** [comment]
Also, are you running on 32-bit or 64-bit Windows?

**Comment by bluethefoxyt** [comment]
@jp2masa  im running 64bit windows
and i then get this error when canceling

========================================
    Builder Log
========================================


========================================
    Checking Dependencies
========================================

Repos: IL2CPU and XSharp is installed.
Visual Studio 15.5+ is installed.
Visual Studio Workloads not found.


========================================
    Error
========================================

System.Exception: Dependency installation failed! Dependency name: Visual Studio Workloads
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by jp2masa** [comment]
It seems that the VS installer docs are wrong. Try removing the "--wait" switch here: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Build.Builder/Dependencies/VisualStudioWorkloadsDependency.cs#L44.

**Comment by bluethefoxyt** [comment]
@jp2masa it shows the vs installer then after abit closes the vs installer at random then gets stuck on the same thing

**Comment by jp2masa** [comment]
I think I know what's happening... It's waiting for user input, but it shouldn't. You can just press "Cancel" I think.

**Comment by bluethefoxyt** [comment]
@jp2masa nothing happens when pressing cancel

**Comment by bluethefoxyt** [comment]
is frozen completely

**Comment by jp2masa** [comment]
Are you using latest master?

**Comment by bluethefoxyt** [comment]
@jp2masa is working now so i can now close this issue

**Comment by AndyGarcia2004** [comment]
what was the solution?
