### ISSUE TITLE
Do you have a plan for 'Process' or 'Executable' program ? 

### ISSUE THREAD

**Issue by prepare** [CosmosOS/Cosmos#1004]
Do you have a plan for 'Process' or 'Executable' program ? 

(eg.  like other '.exe' app for Windows. , and OS load my exe later)

**Comment by valentinbreiz** [comment]
Do you have a mail or something to send you a dm?

**Comment by prepare** [comment]
I always  check GitHub notification messages (about 1-2 times per hour)

---

my email: => wintercoredev [at] gmail.com 

But I don't use it frequently. ( I open about 1-2 times per week.)

No other direct message (dm) :) 

---

**Comment by zarlo** [comment]
@prepare come over to our gitter https://gitter.im/CosmosOS

**Comment by fanoI** [comment]
In future Cosmos will support managed portable executable as was done in the Net Framework (but for now neither Net Core is able to create them) or something as "dotnet run xxx.dll".

But it is yet no time to think of this really we need to concentrate on IL2CPU, on having all BCL working (excluded System.Thread) and so on...

**Comment by prepare** [comment]
@fanoI , Thank you the project's vision.

**Comment by Nik300** [comment]
@prepare idk if you still here, but i recently came up with a provisory solution to that, [MSE](https://github.com/Nik300/ManagedSoftwareExecutionCosmos/).
If you still wish to try doing something like an external executable, this can definitely help.

oh and also come on [gitter](https://gitter.im/CosmosOS/Cosmos)
