### ISSUE TITLE
add image drawing

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#1006]
how can i draw an image to the screen?

**Comment by fanoI** [comment]
You create a Bitmap (from file for example) using the Canvas Bitmap class then to draw it on screen you will use DrawImage().

**Comment by furesoft** [comment]
there is no Canvas Bitmap class?

**Comment by fanoI** [comment]
Yes there is: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Graphics/Bitmap.cs

You can create the Bitmap from a Byte Array as done in the demo or you can read it from a file:
https://github.com/CosmosOS/Cosmos/blob/master/Demos/CosmosGraphicSubsystem/Kernel.cs#23

using the ctor that takes a String path or the one that take an already opened FileStream as you wish.

**Comment by fanoI** [comment]
You must use the DevKit the UserKit is too much old.
