### ISSUE TITLE
VS2017 Create new project error and project templates not showing up

### ISSUE THREAD

**Issue by dotcomboom** [CosmosOS/Cosmos#1008]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio templates

#### Expected Behaviour - What do you think that should happen?
Templates for C# and VB.NET operating systems showing up in the create new project dialog and when you search for them in the start page

#### Actual Behaviour - What unexpectedly happens?
Create new project dialog refusing to open, and the templates not showing up when I searched for them
![image](https://user-images.githubusercontent.com/38927017/42782508-c7ec7d60-890e-11e8-975a-487d991fc105.png)

#### Reproduction - How did you get this error to appear?
Not 100% sure but my VS2017 install is at `D:\Visual Studio 2017 Community` instead of the default path.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20170928; VS2017 Community is 15.5.4

**Comment by jp2masa** [comment]
> Create new project dialog refusing to open, and the templates not showing up when I searched for them

If the new project dialog is refusing to open, how are you searching for the templates? The VS installation is probably corrupted.

**Comment by dotcomboom** [comment]
By searching for them, I meant the textbox above the recent templates.
![image](https://user-images.githubusercontent.com/38927017/42784616-69190c34-8915-11e8-9b9b-e5560aae6297.png)

I think the create new project dialog did work before installing the userkit, but it could just be a mistake on my part.
