### ISSUE TITLE
MSBuild not found during installation

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#1010]
So I got a new computer and tried to install Cosmos on it but when I run install-VS2017.bat it says I don't have MSBuild installed. How would I download this so the error goes away?

**Comment by jp2masa** [comment]
Do you have Visual Studio 2017 installed?

**Comment by FlamingBurrito15** [comment]
yes i do have visual studio 2017 installed

**Comment by quajak** [comment]
Were you able to resolve this issue? Is this related to https://github.com/CosmosOS/Cosmos/issues/994?

**Comment by FlamingBurrito15** [comment]
Well I don't have the laptop no more so I will just close this thread
