### ISSUE TITLE
Filesystem bug: Directories corruption

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1011]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File system

#### Expected Behaviour - What do you think that should happen?
Create directories in the right location.

#### Actual Behaviour - What unexpectedly happens?
It corrupts other directories.

![photo_2018-07-22_20-42-26](https://user-images.githubusercontent.com/18724279/43048909-c287c18c-8def-11e8-9ab8-281b9bcccf08.jpg)

![photo_2018-07-22_20-42-46](https://user-images.githubusercontent.com/18724279/43048912-ccf45338-8def-11e8-9ce4-325b113cf627.jpg)

#### Reproduction - How did you get this error to appear?
using: Directory.CreateDirectory(Kernel.current_directory + dir);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Last commits (Cosmos: 4a801eb167b7fab9b39d54a4cc9e6eb3ecb9dee6, IL2CPU: b4315d1f0585b3ebcc37f920bd0fc84ca6a5e88e, XSharp: 41f8ef655f4dda6589976eb37602ff50b3c9ddea)

**Comment by fanoI** [comment]
I do not understand how our FAT test can pass at this point... we surely test Directory.CreateDirectory() doing Directory.Exists() after...

My is in what you use to do "ls"? Directory.GetFileSystemEntries() or DirectoryInfo.GetFileSystemInfos()?

**Comment by valentinbreiz** [comment]
foreach (string dir in Directory.GetDirectories(directory)) and foreach (string file in Directory.GetFiles(directory))

**Comment by charlesbetros** [comment]
Is this still an issue? Does current directory end in \ ? You should probably use a Path.Combine instead of string concat.
