### ISSUE TITLE
F# Cosmos

### ISSUE THREAD

**Issue by parallaxbeta** [CosmosOS/Cosmos#102]
Cosmos is playing up (ie refusing) to make a F#-based operating system. I have installed the latest version, restarted my computer, and tried to create a new project. There is 'a migration error'. So I unzip the template folder manually and open that. It works fine, apart from the module being called $safeprojectname$. I rename the modules, and run it. It's a dll. So I try and hunt down the compiler. The closest I get is turning it into a console window and trying to access Cosmos.Compiler, before it notifies me that, in fact, it doesn not exist. I then look through "C:\Users\(username)\AppData\Roaming\Cosmos User Kit" and find "Cosmos.Deploy.USB.exe". After experimentation, it requires an .obj file. I assume this is not a Wavefront 3D file, so I search "obj" in the "C:\Users\(username)\AppData\Roaming\Cosmos User Kit" directory. "objdump.exe" comes up. I try it with a "-?" flag, and I get usage. I need one parameter, so I pick the first one ("-a") and try it with the dll of my project.

 I get told what it's called.

This is where I gave up.

Is there something wrong with Cosmos, how I'm doing it, or am I intensely stupid?

**Comment by ARMmaster17** [comment]
If I understand your post correctly, you compiled an F# Cosmos project with the build profile set to 'USB', it encountered an error as documented here: #89. Then you tried finding the obj file it was requesting, when you came across objdump.exe?

Short answer: USB support is broken. We're working on it. Try the ISO method or PXE if you have a spare NIC and PC (or VM).

**Comment by parallaxbeta** [comment]
I didn't even get to 'compiling' it. My dll exists, but I cannot turn it into an OS.

**Comment by ARMmaster17** [comment]
So the *YourProjectName*Boot project is not compiling? When you "compile" the second project, it turns your DLL into a bootable OS.

**Comment by ARMmaster17** [comment]
BTW, F# is not officially supported yet. This may be the source of the problem. @mterwoord, can you confirm this?

**Comment by parallaxbeta** [comment]
*YourProjectName*Boot doesn't exist. I have one project, which I have manually named. Is it possible for you to make an example project that I can cannibalise?

**Comment by ARMmaster17** [comment]
@parallaxbeta Unfortunately, I cannot as I do not have the required modules to create F# programs in my installation of Visual Studio. I'll see what I can do.

**Comment by parallaxbeta** [comment]
Fixed it!

I copied the F# project from the template into a C# solution. I deleted the C# project, and referenced the F# to the Cosmos project. It works!

**Comment by Arawn-Davies** [comment]
is it that when creating an F# OS that a .Cosmos project isn't created? looks like it may be an easy fix
