### ISSUE TITLE
COSMOS Is Installed But NO Project Templates

### ISSUE THREAD

**Issue by BurakYeniceri** [CosmosOS/Cosmos#1030]
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest user kit version

Problem:
I can't see project templates. Userkit is installed but there's still no templates. I updated VS2017. It's latest version. Workloads are installed but still doesn't exists. Please help me!

**Comment by jp2masa** [comment]
Try installing the extension from `%appdata%\Cosmos User Kit\VSIX\Cosmos.VS.ProjectSystem.vsix`.
