### ISSUE TITLE
Cosmos.targets was not found

### ISSUE THREAD

**Issue by AZERTY5030** [CosmosOS/Cosmos#1032]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creating a Project

#### Expected Behaviour - What do you think that should happen?
Directed to the CS file with no errors

#### Actual Behaviour - What unexpectedly happens?
An error with:
![errorcosmos](https://user-images.githubusercontent.com/23745480/44950081-e33bfc80-ae0c-11e8-83f9-bf7e1e651832.PNG) shows up

#### Reproduction - How did you get this error to appear?
Installing the Userkit on another account? I dont know if you can really replicate it, it just happens on my PC.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, and the latest version on the website-

**Comment by AZERTY5030** [comment]
I forgot to mention: Im using the C# project template.

**Comment by jp2masa** [comment]
Maybe Cosmos was installed to the wrong folder... Is this the first installation of the User Kit? Also, did you change the installation folder?

**Comment by AZERTY5030** [comment]
I have installed it twice, and I have installed it at the default folder

**Comment by jp2masa** [comment]
Does the `%appdata%\Cosmos User Kit\` folder exist?

**Comment by AZERTY5030** [comment]
No.

**Comment by jp2masa** [comment]
Did you install it in a different account?

**Comment by AZERTY5030** [comment]
I installed it on another account (riley) that is adminasrator.

**Comment by jp2masa** [comment]
Then you can only use Cosmos on that account I think.

**Comment by AZERTY5030** [comment]
Oh.

**Comment by AZERTY5030** [comment]
Multiple users use the computer though; Im not the only one on there

**Comment by AZERTY5030** [comment]
I accessed another account and went to its AppData and I found the Cosmos User Kit.
