### ISSUE TITLE
Build.sIn error and Error

### ISSUE THREAD

**Issue by ItZskyler** [CosmosOS/Cosmos#1033]
========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU and XSharp is installed.
Visual Studio 15.8+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - XSharp.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\skyle\Desktop\XSharp\XSharp.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 57.34 ms for C:\Users\skyle\Desktop\XSharp\source\SpruceDebugger\SpruceDebugger.csproj.
  Restore completed in 57.25 ms for C:\Users\skyle\Desktop\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 57.44 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 1.52 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Build\XSharp.Build.csproj.
  Restore completed in 13.78 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Compiler\XSharp.Compiler.csproj.
  Restore completed in 97.84 ms for C:\Users\skyle\Desktop\XSharp\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 57.45 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Compiler.Tasks\XSharp.Compiler.Tasks.csproj.
  Restore completed in 32.23 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.ProjectSystem\XSharp.ProjectSystem.csproj.
  Restore completed in 2.35 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.VS\XSharp.VS.csproj.
  Restore completed in 1.06 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 20.92 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Sdk\XSharp.Sdk.csproj.
  Restore completed in 56.86 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Launch\XSharp.Launch.csproj.
  Restore completed in 1.75 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 8.61 ms for C:\Users\skyle\Desktop\XSharp\tests\XSharp.Tests\XSharp.Tests.csproj.
  Restore completed in 22.73 ms for C:\Users\skyle\Desktop\XSharp\tests\XSharp.Launch.Tests\XSharp.Launch.Tests.csproj.

========================================
    Restore - IL2CPU.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\skyle\Desktop\IL2CPU\IL2CPU.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 54.77 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 52.05 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 52.1 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 0.68 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 77.28 ms for C:\Users\skyle\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 2.07 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 1.07 ms for C:\Users\skyle\Desktop\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 0.77 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 0.72 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 3.31 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 20.63 ms for C:\Users\skyle\Desktop\IL2CPU\tests\IL2CPU.Compiler.Tests\IL2CPU.Compiler.Tests.csproj.
  Restore completed in 27.43 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU\IL2CPU.csproj.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\skyle\Desktop\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 54.06 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 55.94 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 59.97 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj.
  Restore completed in 60.23 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 0.72 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 0.82 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 3.03 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 5.51 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 3.49 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 25.71 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 1.01 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 1.56 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 3.44 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 0.58 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 1.31 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 1.2 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 2.62 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 2.99 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 2.05 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 5.06 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 6.18 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 6.6 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 0.82 ms for C:\Users\skyle\Desktop\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 7.83 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 2.75 ms for C:\Users\skyle\Desktop\Cosmos\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 8.45 ms for C:\Users\skyle\Desktop\Cosmos\Tools\NASM\NASM.csproj.
  Restore completed in 1.65 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 0.89 ms for C:\Users\skyle\Desktop\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 25.38 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 3.9 ms for C:\Users\skyle\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 4.46 ms for C:\Users\skyle\Desktop\IL2CPU\source\IL2CPU\IL2CPU.csproj.
  Restore completed in 0.93 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 0.63 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 0.99 ms for C:\Users\skyle\Desktop\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 5.7 ms for C:\Users\skyle\Desktop\XSharp\source\VSPropertyPages\VSPropertyPages.csproj.

========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\skyle\Desktop\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\skyle\Desktop\Cosmos\Build\VSIP" /p:DeployExtension=False
  Cosmos.Build.Common -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Debug.Common -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Deploy.Pixie -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Deploy.Pixie.exe
  IL2CPU.Debug.Symbols -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\IL2CPU.Debug.Symbols.dll
  VSPropertyPages -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\VSPropertyPages.dll
  Cosmos.Build.MSBuild -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Build.MSBuild.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Cosmos.Core.DebugStub -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Core.DebugStub.dll
  Cosmos.Debug.GDB -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.VS.ProjectSystem -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.VS.ProjectSystem.dll
  Cosmos.Debug.Kernel -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.dll
  IL2CPU.API -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\IL2CPU.API.dll
  Cosmos.Deploy.USB -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Core -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Core.dll
  XSharp.Assembler -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\XSharp.Assembler.dll
  Cosmos.Common -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Common.dll
  XSharp.x86 -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\XSharp.x86.dll
  Spruce -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Spruce.dll
  XSharp -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\XSharp.dll
  Restore completed in 57.63 ms for C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Cosmos.IL2CPU -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.IL2CPU.dll
  Cosmos.Debug.HyperVServer -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\skyle\Desktop\Cosmos\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.TestRunner.TestController -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.TestRunner.TestController.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\skyle\Desktop\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows_njuvm2fq_wpftmp.csproj]
  Cosmos.Debug.HyperVServer -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  IL2CPU -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\IL2CPU.dll
  NASM -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\NASM.dll
  Cosmos.Debug.Hosts -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.HAL2 -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.Core_Plugs -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Core_Plugs.dll
  TheRingMaster -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\TheRingMaster.dll
  Cosmos.Core_Asm -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Core_Asm.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  Cosmos.Build.Tasks -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.System2 -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.System2_Plugs.dll
  Cosmos.VS.ProjectSystem -> C:\Users\skyle\Desktop\Cosmos\Build\VSIP\Cosmos.VS.ProjectSystem.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by quajak** [comment]
I think the problem is that you do not have .NET Framework 4.7.1 installed, as it states in the log
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. 
```
