### ISSUE TITLE
Error while invoking IL2CPU

### ISSUE THREAD

**Issue by AZERTY5030** [CosmosOS/Cosmos#1034]
#### Area of Cosmos - What area of Cosmos are we dealing with?
C# compiling

#### Expected Behaviour - What do you think that should happen?
Redirected to the VMware Workstation menu

#### Actual Behaviour - What unexpectedly happens?
The error "Error while invoking IL2CPU" occurs

#### Reproduction - How did you get this error to appear?
I dont know.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Userkit Download.

Here is all of my code:
``using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.HAL;

namespace Sentram2
{
    public class Kernel: Sys.Kernel
    {

        string currentUser = "root";

        void DoCMD(string CMD)
        {
            string CMDFourLetter = CMD.Substring(0, 4);
            string CMDArguement = CMD.Substring(5);

            if (CMDFourLetter == "ECHO")
            {
                Console.Write(CMDArguement);
            }
            if(CMDFourLetter == "NEWL")
            {
                Console.WriteLine("");
            }
        }

        protected override void BeforeRun()
        {
            Console.Clear();
            Console.WriteLine("SENTRAM");
        }

        protected override void Run()
        {
            Console.Title = "Sentram";
            Console.Write(currentUser + "> ");
            var input = Console.ReadLine();
            Console.WriteLine("Invalid Command:" + input + ". Please check if this is valid or find an alternative.");
        }
    }
}``

(for some reason the formatting is incorrect)

**Comment by AZERTY5030** [comment]
Nevermind, I've changed some of my code and IL2CPU is still not working.

### Code
`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.HAL;

namespace Sentram2
{
    public class Kernel: Sys.Kernel
    {
        string currentUser = "root";

        void DoCMD(string CMD)
        {
            string CMDFourLetter = CMD.Substring(0, 4);
            var CMDArguement = CMD.Substring(5);

            if (CMDFourLetter == "ECHO")
            {
                Console.WriteLine(CMDArguement);
            }
            if(CMDFourLetter == "NEWL")
            {
                Console.WriteLine("");
            }
            if(CMDFourLetter == "")
            {
                Console.Beep(5, 5);
                
            }
        }

        protected override void BeforeRun()
        {
            Console.Clear();
            Console.WriteLine("SENTRAM");

            Console.WriteLine("Sentram HDD Initialization");
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
        }

        protected override void Run()
        {
            Console.Write(currentUser + "> ");
            var input = Console.ReadLine();
            DoCMD(input);
        }
    }
}
`

### Output
`1>------ Build started: Project: Sentram2, Configuration: Debug Any CPU ------
1>Kernel.cs(13,9,13,15): error CS1519: Invalid token 'string' in class, struct, or interface member declaration
1>Done building project "Sentram2.csproj" -- FAILED.
2>------ Build started: Project: Sentram2Boot, Configuration: Debug Any CPU ------
2>		Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Sentram2Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\netstandard1.5\Sentram2.dll" 
2>C:\Users\riley\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>		Executing command line "C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Sentram2Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\netstandard1.5\Sentram2.dll" 
2>		Working directory = 'C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\'
2>		Loaded : DebugEnabled
2>		Loaded : StackCorruptionDetectionEnabled
2>		Loaded : DebugMode
2>		Loaded : StackCorruptionDetectionLevel
2>		Loaded : TraceAssemblies
2>		Loaded : DebugCom
2>		Loaded : UseNAsm
2>		Loaded : OutputFilename
2>		Loaded : EnableLogging
2>		Loaded : EmitDebugSymbols
2>		Loaded : IgnoreDebugStubAttribute
2>		Loaded : References
2>		Loaded : AdditionalSearchDirs
2>		Loaded : AdditionalReferences
2>		Executing IL2CPU on assembly
2>		Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  Interop+mincore.Beep(System.Int32, System.Int32).
2>		 Called from :
2>		System.ConsolePal::Void Beep()
2>		System.Console::Void Beep()
2>		Sentram2.Kernel::Void BeforeRun()
2>		Cosmos.System.Kernel::Void BeforeRun()
2>		   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>		   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>		   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>		   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>		Loaded assemblies: 
2>		C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>		C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>		C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>		C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Cosmos.System.Plugs.dll
2>		C:\Users\riley\source\repos\Sentram2\Sentram2\bin\Debug\net462\Sentram2.dll
2>		Errorred
2>		IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>		IL2CPU task took 00:00:04.1405259
2>Done building project "Sentram2Boot.Cosmos" -- FAILED.
2>
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by AZERTY5030** [comment]
I have Net 3.5 installed too.

**Comment by quajak** [comment]
You are using `Console.Beep`, which is not implemented in the current User Kit. If you want to use `Console.Beep`, use the DevKit, or wait for the next User Kit release, which should be soon.

**Comment by AZERTY5030** [comment]
Thanks.
