### ISSUE TITLE
OS loop after changing console color

### ISSUE THREAD

**Issue by ZenooxP** [CosmosOS/Cosmos#1035]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Console

#### Expected Behaviour - What do you think that should happen?
Change color of foreground or background

#### Actual Behaviour - What unexpectedly happens?
A loop where the debugger just says "Really before run" and "Really after run"

#### Reproduction - How did you get this error to appear?
Just change the foreground or background color of the console

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest user kit release

**Comment by jp2masa** [comment]
The `Run` method is called in a loop, you should block it if you don't want it to loop.
