### ISSUE TITLE
Compiler trying to access C:/Users/Adminasrator

### ISSUE THREAD

**Issue by AZERTY5030** [CosmosOS/Cosmos#1036]
#### Area of Cosmos - What area of Cosmos are we dealing with?
C# Compiling

#### Expected Behaviour - What do you think that should happen?
the ISO file is built

#### Actual Behaviour - What unexpectedly happens?
Error while invoking IL2CPU, or it tries to access an Administrator account which doesn't exist

#### Reproduction - How did you get this error to appear?
I don't know.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Userkit.

Anyways, here was the actual console log
`1>------ Build started: Project: Karnale, Configuration: Debug Any CPU ------
1>Kernel.cs(135,30,135,37): warning CS0649: Field 'Kernel.invoker' is never assigned to, and will always have its default value null
1>softwareLayout.cs(11,30,11,37): warning CS0169: The field 'softwareLayout_windowInstance.invoker' is never used
1>Kernel.cs(18,27,18,29): warning CS0649: Field 'KernelInvoke.EX' is never assigned to, and will always have its default value null
1>Kernel.cs(131,27,131,29): warning CS0649: Field 'Kernel.EX' is never assigned to, and will always have its default value null
1>kpanic.cs(26,30,26,37): warning CS0169: The field 'Kpanic.invoker' is never used
1>resize.cs(17,30,17,37): warning CS0649: Field 'resize_WindowInstance.invoker' is never assigned to, and will always have its default value null
1>Kernel.cs(132,22,132,26): warning CS0649: Field 'Kernel.root' is never assigned to, and will always have its default value null
1>kpanic.cs(20,19,20,25): warning CS0169: The field 'ExceptionDefiner.except' is never used
1>Karnale -> C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\netstandard1.5\Karnale.dll
1>Done building project "Karnale.csproj".
2>------ Build started: Project: KarnaleBoot, Configuration: Debug Any CPU ------
2>		Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\net462\iso\compile\net462\KarnaleBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\netstandard1.5\Karnale.dll" 
2>C:\Users\riley\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>		Executing command line "C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\net462\iso\compile\net462\KarnaleBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\netstandard1.5\Karnale.dll" 
2>		Working directory = 'C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\net462\iso\compile\net462\'
2>		Loaded : DebugEnabled
2>		Loaded : StackCorruptionDetectionEnabled
2>		Loaded : DebugMode
2>		Loaded : StackCorruptionDetectionLevel
2>		Loaded : TraceAssemblies
2>		Loaded : DebugCom
2>		Loaded : UseNAsm
2>		Loaded : OutputFilename
2>		Loaded : EnableLogging
2>		Loaded : EmitDebugSymbols
2>		Loaded : IgnoreDebugStubAttribute
2>		Loaded : References
2>		Loaded : AdditionalSearchDirs
2>		Loaded : AdditionalReferences
2>		Executing IL2CPU on assembly
2>		Error: Exception: System.IO.FileNotFoundException: Could not load file or assembly 'UserSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
2>		File name: 'UserSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
2>		   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
2>		   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
2>		   at System.Reflection.RtFieldInfo.get_FieldType()
2>		   at Cosmos.IL2CPU.ILOpCodes.OpField.DoInitStackAnalysis(MethodBase aMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpField.cs:line 80
2>		   at Cosmos.IL2CPU.ILOpCode.InitStackAnalysis(MethodBase aMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 302
2>		   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILReader.cs:line 410
2>		   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 565
2>		   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>		   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>		   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>		Loaded assemblies: 
2>		C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
2>		C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>		C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>		C:\Users\Jonathan Langdale\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>		C:\Users\riley\source\repos\Karnale\Karnale\bin\Debug\netstandard1.5\Karnale.dll
2>		Errorred
2>		IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>		IL2CPU task took 00:00:07.3014154
2>Done building project "KarnaleBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
========== Build: 1 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
`

**Comment by Project-Magenta** [comment]
It is because Cosmos is installed in that directory.

**Comment by jp2masa** [comment]
This is a bug with project references I think, it should work fine in the latest Dev Kit.

**Comment by AZERTY5030** [comment]
Will I have to rewrite my code if I use the Dev Kit?

**Comment by Project-Magenta** [comment]
no

**Comment by Project-Magenta** [comment]
same code
