### ISSUE TITLE
Issue when creating folder (or when getting them)

### ISSUE THREAD

**Issue by Shiigehiro** [CosmosOS/Cosmos#1038]
### Area of Cosmos - What area of Cosmos are we dealing with?
File System

### Expected Behaviour - What do you think that should happen?
Folders should be created only where I asked when i do 
`Directory.CreateDirectory($"{Kernel.currentDirectory}{path}");`

### Actual Behaviour - What unexpectedly happens?
For example, i create a folder in 0:\Users\, and i name it "cosmos"
The folder is created, but
1st problem: if i go in 0:\etc\, "cosmos" is here too.
2nd problem, if i go in 0:\Users\cosmos or in 0:\etc\cosmos, "cosmos is here too infinitely.

#### mkdir command: 
```cs
public static void _Create(string value)
{
    Directory.CreateDirectory($"{Kernel.currentDirectory}{value}");
}
```

#### ls command:
```cs
public static void _Show()
{
    foreach (string directory in Directory.GetDirectories(Kernel.currentDirectory))
    {
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(directory + "\t");
        Console.ForegroundColor = ConsoleColor.White;
    }
}
```

#### cd command:
```cs
public static void _Move(string directory)
{
	try
	{
		if (directory == null || directory == "")
		{
			Console.WriteLine($"You are on : {Kernel.currentDirectory}");
		}
		else if (directory == "/")
		{
			Directory.SetCurrentDirectory(Kernel.currentDirectory);
			Kernel.currentDirectory = @"0:\";
		}
		else if (directory == "..")
		{ 
			Directory.SetCurrentDirectory(Kernel.currentDirectory);
			Kernel.currentDirectory = Directory.GetParent(Kernel.currentDirectory).FullName + @"\";
		}
		else if (Directory.Exists(Kernel.currentDirectory + directory))
		{
			Directory.SetCurrentDirectory(Kernel.currentDirectory);
			Kernel.currentDirectory += directory + @"\";
		}
		else
		{
			Console.ForegroundColor = ConsoleColor.Red;
			Console.WriteLine("This directory doesn't exist");
			Console.ForegroundColor = ConsoleColor.White;
		}
	}
	catch (Exception e)
	{
		Console.ForegroundColor = ConsoleColor.Red;
		Console.WriteLine(e.Message);
		Console.ForegroundColor = ConsoleColor.White;
	}
}
```

### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using Userkit_20170928, i have trying Aura-OS and the same thing happened.

Thanks you

**Comment by zarlo** [comment]
have you Initiated the FAT driver

**Comment by Shiigehiro** [comment]
Yes i had, but it's solved now, i installed DevKit and it work, it's strange
