### ISSUE TITLE
Can't uninstall UserKit

### ISSUE THREAD

**Issue by pshah123** [CosmosOS/Cosmos#104]
I switched from DevKit to UserKit thinking it might be better (did not read obviously), and now I can't get rid of userkit to install devkit. When I try to uninstall, this happens:
"Runtime Error at (36,380):
An error occurred while unregistering Cosmos from Visual Studio!"

Any help? Is there a manual uninstall?

**Comment by ARMmaster17** [comment]
Just go ahead an install the UserKit. Installing the UserKit is the same process as installing a new recompiled DevKit. It will automatically overwrite the existing files and resolve registration with Visual Studio. The uninstaller crashing on newer operating systems is a known issue. Hope this helps!

-----------------------------------------------------
If this post answers your question, remember to click 'close issue'.
