### ISSUE TITLE
Cosmos - how to access to the internet

### ISSUE THREAD

**Issue by lammaurice034** [CosmosOS/Cosmos#1040]
Cosmos - how to browse the net

I have absolute no idea how to do this. I don't know how to connect to the internet or display a webpage or interact with the website.

Any solutions?
Thanks

**Comment by fanoI** [comment]
We are working on the TCP stack but you are yet really at low level a lot of time will have to pass before we could display a web page.

**Comment by 365Tito** [comment]
Displaying a webpage? I think you have to make a basic HTML reader for that... from scratch.

**Comment by fanoI** [comment]
Well if you want a textual browser probably the C# HTML classes could work already... but I think our friend was thinking of a GUI browser as "Firefox".

**Comment by RMuskovets** [comment]
if we have tcp classes:
1. connect
2. send HTTP response
3. use C# HTML classes to parse the page
4. show by your way!

**Comment by dilan-omer** [comment]
once connections are possible, how likely is it to build a browser over the OS if we can use chromium as the engine and built an actual browser around it in .NET?
