### ISSUE TITLE
unexpected exception during attach vmware not found in cosmos on microsoft .net

### ISSUE THREAD

**Issue by Escapist70** [CosmosOS/Cosmos#1042]
#### Actual Behaviour - What unexpectedly happens?
it should echo my keyboard

#### Reproduction - How did you get this error to appear?
by debugging cosmos os on Microsoft.Net

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit
Copyright © 2007-2017, The Cosmos Project

**Comment by vahin** [comment]
@jp2masa How do we set it to use QEMU?

**Comment by quajak** [comment]
Qemu support is currently WIP. You can still launch it in qemu if you disable debug and start qemu yourself using the iso
