### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by FoxCampagna** [CosmosOS/Cosmos#1044]
Hi,

When I try to install the latest version of the devkit, this error appears:
![cattura](https://user-images.githubusercontent.com/33520177/45885881-e09f4800-bdb7-11e8-8ec1-55629e77d2ec.PNG)

**Comment by zarlo** [comment]
do you have .net 4.7.1 installed

**Comment by FoxCampagna** [comment]
no, I have installed versions ranging from 4 to 7

**Comment by zarlo** [comment]
you need 4.7.1

**Comment by FoxCampagna** [comment]
i try to install 4.7.1 but installer give at me the same error

**Comment by FoxCampagna** [comment]
I solved, the second problem, I was wrong to rename the folder and I do not increase it
