### ISSUE TITLE
How do I build a cosmos os into a iso file on Userkit

### ISSUE THREAD

**Issue by TheMasterOfC** [CosmosOS/Cosmos#1046]
How do I build a cosmos os into a iso file on Userkit

**Comment by zarlo** [comment]
you just need to build the project

**Comment by VahezCoder** [comment]
I did !  I wont work!

**Comment by zarlo** [comment]
do you get an error in the build log

**Comment by VahezCoder** [comment]
no

**Comment by sjmulder** [comment]
What files are in `bin\Debug\netcoreapp2.0\cosmos`?

**Comment by VahezCoder** [comment]
Sorry for not responding for a long time I eventually uninstalled the user kit and trying to install the dev kit

**Comment by VahezCoder** [comment]
Thank you for all your help. If I get This problem once again(I Might) I will Tell You guy RIGHT on this post Thank You

**Comment by creeperpower** [comment]
maybe you need a later version
