### ISSUE TITLE
Cosmos Kernel Lib VS2017 does not launch Cosmos

### ISSUE THREAD

**Issue by sevsev9** [CosmosOS/Cosmos#1055]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio 2017
All Required Dependencies installed.
#### Expected Behaviour - What do you think that should happen?
By pressing f5 it should start VMWare with the OS.

#### Actual Behaviour - What unexpectedly happens?
Instead this appears:
![image](https://user-images.githubusercontent.com/19306904/46676302-889e7900-cbe0-11e8-8f1b-6b9d9d9bd062.png)

Also there is no *project_name*Boot in the Solution Explorer.
![image](https://user-images.githubusercontent.com/19306904/46676466-e16e1180-cbe0-11e8-9543-557a727597e7.png)

But in the Menu Cosmos Appears:
![image](https://user-images.githubusercontent.com/19306904/46676530-0498c100-cbe1-11e8-8943-f6490beb807b.png)

#### Reproduction - How did you get this error to appear?
I tried it on 2 separate Machines and got the same error on both. Simply Installed VS2017 with that version of the User Kit for VS17 and created a new Project.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

UserKit Version: 20170928 for VS2017

## Edit:
I tried Installing the DevKit on both machines. There it doesn't even install it in any way although it writes completed. (I did run the install-VS2017.bat)

**Comment by sevsev9** [comment]
I tried to install it on VS2015 via the DevKit but neither did it work there. What am i doing wrong?

**Comment by sevsev9** [comment]
I just tried it. Anyways it doesn't work in VS17.

**Comment by zarlo** [comment]
o and project_nameBoo is nolonger needed
