### ISSUE TITLE
Does not boot if there is no IDE Secondary Master (VirtualBox)

### ISSUE THREAD

**Issue by RoboBurned** [CosmosOS/Cosmos#1056]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IDE controller driver

#### Expected Behaviour - What do you think that should happen?
System should boot up if there is no Secondary Master IDE device.

#### Actual Behaviour - What unexpectedly happens?
Messages appears
ATA Primary Master0.bin... OK
ATA Secondary Master
System hangs

#### Reproduction - How did you get this error to appear?
Create a sample project (Cosmos Kernel)
Disable debugging.
Build ISO file.
Create a VM in VirtualBox.
There should be one IDE controller with one device of type CDROM attached as Primary Master with ISO inserted in it.
There should be no Secondary Master IDE devices.
Start the VM.
System hangs trying to find secondary master device.
If I add second CDROM with no disk inserted to IDE controller and set it as secondary master then system boots up correctly.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using CosmosUserKit-20181010-vs2017.exe
![vm settings](https://user-images.githubusercontent.com/14316268/46808263-fda6b580-cd7c-11e8-822f-9b568e96689b.png)

![nosecondarymaster](https://user-images.githubusercontent.com/14316268/46808120-9e48a580-cd7c-11e8-9e5a-0f52fc5ec3b4.png)

**Comment by valentinbreiz** [comment]
Change IDE to SATA Controller it will works

**Comment by RoboBurned** [comment]
I can confirm, SATA Controller works fine with only one CDROM attached.

**Comment by valentinbreiz** [comment]
@RoboBurned #1057 should fix it too

**Comment by sjmulder** [comment]
@RoboBurned thanks for the great issue report, let me reproduce and narrow down the issue with ease.
