### ISSUE TITLE
Key board is not working

### ISSUE THREAD

**Issue by theprogram2** [CosmosOS/Cosmos#1058]
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit

**Comment by quajak** [comment]
How is it not working? What are you doing right now?

**Comment by theprogram2** [comment]
there is my code:

string command = System.Console.ReadLine();
                    switch (command)
                    {
                        case "shutdown":
                            {
                                Sys.Power.Shutdown();
                                break;
                            }
                        case "help":
                            {
                                System.Console.WriteLine("shutdown / restart - shuts down os / restarts os");
                                System.Console.WriteLine("about - Know about IOS ");
                                System.Console.WriteLine("ipconfig - network info");
                                break;
                            }
                        case "about":
                            {
                                System.Console.WriteLine("os" + config.version);
                                break;
                            }
                        case "reboot":
                            {
                                Sys.Power.Reboot();
                                break;
                            }
                        case "ipconfig":
                            {
                                System.Console.WriteLine("COMMING SOON: ipconfig");
                                break;
                            }
                        default:
                            {
                                System.Console.WriteLine("No such command");
                                command = null; break;
                            }

**Comment by quajak** [comment]
How is the keyboard not working? Is it Console.ReadLine(); not giving the correct output?

**Comment by theprogram2** [comment]
No, am testing it on my laptop and it does not work.
