### ISSUE TITLE
Error: "System.ArgumentException" in IL2CPU

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1059]
#### Area of Cosmos - What area of Cosmos are we dealing with?

IL2CPU

#### Expected Behaviour - What do you think that should happen?

Build the OS successfully

#### Actual Behaviour - What unexpectedly happens?

System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.	

#### Reproduction - How did you get this error to appear?

I added some code that handled text file I/O

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest UserKit, IL2CPU

**Comment by sudopigeek** [comment]
Here is the error screenshot:

![error](https://user-images.githubusercontent.com/37987178/46926412-845dcb80-cfe5-11e8-83e2-fb931dd2ee14.jpg)

**Comment by fanoI** [comment]
What is specifically the code you added?

**Comment by sudopigeek** [comment]
var user = File.Open(@"0:\\USER.txt", FileMode.OpenOrCreate, FileAccess.ReadWrite);
            if (new FileInfo(@"0:\\USER.txt").Length == 0)
            {
                StreamWriter writer = new StreamWriter(@"0:\\USER.txt");
                //write user credentials to file:
                writer.WriteLine("Username:");
                writer.WriteLine("user");
                writer.WriteLine("Password:");
                writer.WriteLine("cosmos");
            }

**Comment by sudopigeek** [comment]
string usercode = File.ReadLines("USER.txt").Skip(1).Take(2).First();
string passcode = File.ReadLines("USER.txt").Skip(3).Take(4).First();

**Comment by sudopigeek** [comment]
System.IO.Directory.CreateDirectory(@"0:\\" + dirname);

**Comment by sudopigeek** [comment]
That was my latest additions.  I also tried to comment out some of it line by line but it still gave the error.

**Comment by sudopigeek** [comment]
I can't believe it.  I found the problem.  Apparently, the the code that I posted above that defined the string usercode and passcode gave the error.

Although I found the problem, I don't know how I can "get around" it.  The purpose of that code was to get specific lines from USER.txt and set them as the usercode and passcode strings.  Is there a possible alternative?

**Comment by fanoI** [comment]
File.ReadLines("USER.txt").Skip(1).Take(2).First();

is using LINQ that is yet not supported in Cosmos, you should simply write it as procedural code, a foreach() and using String.SubString() or String.Split() inside it.

**Comment by sudopigeek** [comment]
Could you give me an example?
