### ISSUE TITLE
Error whilst installing DevKit

### ISSUE THREAD

**Issue by CMadian1998** [CosmosOS/Cosmos#1061]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installation

#### Expected Behaviour - What do you think that should happen?
The program should finish installing correctly

#### Actual Behaviour - What unexpectedly happens?
Installer gets stuck on installing the IL2CPU repo

#### Reproduction - How did you get this error to appear?
Just install

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devKit

**Comment by quajak** [comment]
Did you download the IL2CPU repo?
