### ISSUE TITLE
ISO Build Error:  The system cannot find the file specified

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1062]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Cosmos

#### Expected Behaviour - What do you think that should happen?

Cosmos builds ISO

#### Actual Behaviour - What unexpectedly happens?

Error:  The system cannot find the file specified

#### Reproduction - How did you get this error to appear?

set Cosmos Build option to "ISO" instead of "VMWare"

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Newest Userkit, Cosmos

===================================================================

Here is the error:

![error2](https://user-images.githubusercontent.com/37987178/47044985-85f2d500-d146-11e8-9e1b-ae27dd13ac8e.jpg)

Cosmos seems to build it successfully until the very end.  It says "Done building project in the "Output" tab, and then it shows the error message when it should open the folder containing the ISO.

**Comment by sudopigeek** [comment]
NOTE:

My end result is to build a ISO **without** the "Waiting for debugger" screen.

**Comment by fanoI** [comment]
It works without disabling debugger?

**Comment by sudopigeek** [comment]
Yes.  I unchecked "Enable debug" is the project's Properties page, built the ISO by pressing F5, and had VMWare boot it.  The above screenshot is the output.  But if I check "Enable debug", then when I build and boot the ISO, it stays at the "Waiting for Debugger" screen.

**Comment by asiawin** [comment]
The reason is, either you've had disabled the debug option in the configuration or you've set ISO in the configuration.
Solution: 
      for 1st reason:-
             Create a new Virtualbox virtual machine.
             Set the disk image to the iso image where your iso image is.
             Run the iso image.
      For 2nd reason:-
             Set the configuration to VMware (see [ how to edit the configuration in COSMOS C#] )(http://codebasha.cf/cosmos/how-to-edit-config/)

Hope this will be helpful to you
For more tips and tricks, visit [ codebasha.cf](http://codebasha.cf/)

**Comment by CoolJim** [comment]
I have the same problem. My solution (albeit temporary) was to disable debug and compile using VMWare, which creates an ISO file somewhere in the `bin` directory. I then just copy that ISO file.

**Comment by asiawin** [comment]
Sorry, but I'm not making operating systems with COSMOS anymore. I have another project called [Cadex OS](https://github.com/OpenCreeck/Cadex-OS-Official). Go and check it out!
