### ISSUE TITLE
Ring and RingAttribute not found (DevKit)

### ISSUE THREAD

**Issue by VisualTuber** [CosmosOS/Cosmos#1064]
I just installed the latest devkit of cosmos, i have all the libraries installed and visualstudio says that ring and ringattribute are not found, i also can't find out how to work with this new project system, since the only option i can find is the cosmos kernel option.
My code:
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Cosmos.Common;

[assembly: AssemblyCopyright("Copyright ©  2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: Ring(Ring.System)] <- error
[assembly: ComVisible(false)]
[assembly: Guid("04642d31-fe89-414f-a7e3-20195d2640e7")]

**Comment by jp2masa** [comment]
There are no rings in the Dev Kit. They will return for Gen 3, as an option which is enabled by default, but I recommend you still follow the rings structure, as you'll have good separation of concepts, which means it's easier to maintain and also less bugs.

**Comment by VisualTuber** [comment]
Alright, but how will i use rings now? I wanna start coding my OS right now.

**Comment by jp2masa** [comment]
Rings were disabled for now, you can just code the OS as usual. I recommend following the rings conventions, but you don't need to.

**Comment by VisualTuber** [comment]
Okay, another unrelated question, i can't add mouse support, the mouse class is not found, and the iogroup mouse doesn't have the x and y values

**Comment by VisualTuber** [comment]
nvm
