### ISSUE TITLE
Can't add a reference

### ISSUE THREAD

**Issue by gertpert** [CosmosOS/Cosmos#1067]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Can't add a reference.

#### Expected Behaviour - What do you think that should happen?
that i can add references and that the references shows

#### Actual Behaviour - What unexpectedly happens?
older versions you can add references.

#### Reproduction - How did you get this error to appear?
i wanted to add a reference but there where no reference showing.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
i use the newest Cosmos = CosmosUserKit-20181010-vs2017

**Comment by jp2masa** [comment]
Can you be more specific? What kind of references are you trying to add?
