### ISSUE TITLE
Boot "exceptions"

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1068]
I built an ISO of my OS in Visual Studio 2017 using the newest UserKit, and had VMWare boot the ISO that I made.  Unfortunately, it hardly gets going when it lists several exceptions, none of which I know how to fix:
![error](https://user-images.githubusercontent.com/37987178/47275842-baf89080-d567-11e8-9170-8c09b21e0cae.JPG)
Any suggestions?

**Comment by fanoI** [comment]
Copy of https://github.com/CosmosOS/Cosmos/issues/1069
