### ISSUE TITLE
Booting Cosmos "Exceptions"

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1069]
I built an ISO of my OS in Visual Studio 2017 using the newest UserKit, and had VMWare boot the ISO that I made.  Unfortunately, it hardly gets going when it lists several exceptions, none of which I know how to fix:
![error](https://user-images.githubusercontent.com/37987178/47275842-baf89080-d567-11e8-9170-8c09b21e0cae.JPG)
Any suggestions?

**Comment by fanoI** [comment]
Two things:

1. Are you using the normal Cosmos .vmdk image or an empty one?
2. Are you initializing Cosmos VFS correctly? See here for an example: https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.Fat/Kernel.cs#26

**Comment by fanoI** [comment]
Please ensure to have inizialized Cosmos VFS https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.Fat/Kernel.cs#26
