### ISSUE TITLE
Console colors are not working

### ISSUE THREAD

**Issue by zdimension** [CosmosOS/Cosmos#107]
On the latest userkit (and devkit, I tried both), the Console.ForegroundColor and BackgroundColor properties are broken.
If I change their value, it doesn't change anything, it stays white on black.

**Comment by mterwoord** [comment]
After setting the value, you need to write something to the console. Did you try that?

**Comment by zdimension** [comment]
... Of course, I tried defining it and then writing text but as I said it stays white on black.

**Comment by zdimension** [comment]
But I noticed that if I take the code from TextScreen.cs 
```csharp
Cosmos.Core.IOGroup.TextScreen IO = Cosmos.Core.Global.BaseIOGroups.TextScreen;
MemoryBlock08 mRAM = IO.Memory.Bytes;
var xScreenOffset = (UInt32)((0 + 0 * 80) * 2);
mRAM[xScreenOffset] = (byte)'@';
mRAM[xScreenOffset + 1] = 0xF0;
```
(I've changed the char to @, the color to black-on-white and x;y to 0)
Then it works.
So I think the Console.ForegroundColor and BackgroundColor code doesn't call TextScreen.SetColors, maybe it's a bug?

**Comment by zdimension** [comment]
Erm I think I've found what causes this...
When I call Console.ForegroundColor = XXX,
it calls ConsoleImpl.set_ForegroundColor(XXX)
then it calls **Cosmos.HAL.Global.TextScreen**.SetColors(XXX, mBackground)
BUT
when I call Console.WriteLine(YYY)
it calls ConsoleImpl.WriteLine(YYY)
which calls Cosmos.System.Global.Console that is defined by **another TextScreen** thing.
So Console.WriteLine and Console.ForegroundColor doesn't appear to point to the same TextScreen object so the Color property isn't changed.
(sorry for my bad english and bad explanation, I'm french)
And if you look at Cosmos.System.Console.cs, you can see
```csharp
protected HAL.TextScreenBase mText;
```
But if you look at a previous release of Cosmos where the Console.ForegroundColor was working, for example the 92560, you can see
```csharp
protected Hardware.TextScreen mText = Hardware.Global.TextScreen;
```
Maybe changing mText from the Global TextScreen, to another TextScree defined in constructor caused this bug?

**Comment by mterwoord** [comment]
We made a new abstraction (TextScreenBase), to allow redirecting the console.
This shouldn't mean the colors don't work anymore. However, most likely bug snug in. 

The mText field is initialized on startup, but can later on be replaced. Are you on devkit? If so, can you try and edit the replacement to copy the colors from old instance to new instance?

**Comment by zdimension** [comment]
What I don't understand is why Console.WriteLine and Console.ForegroundColor doesn't point to the same TextScren or TextScreenBase object...
The thing I would do is replace the Console field by a property with ``` public Console Console { get { return new Console(Cosmos.HAL.Global.TextScreen); } } ```.

**Comment by mterwoord** [comment]
Like I said, we need the current logic which lets us replace the console implementation. What probably happens, is that during kernel initialization, the instance gets replaced and the colors aren't copied from the old to the new instance..

**Comment by zdimension** [comment]
No.. You can keep your current implementation and everything but what I don't understand is why Console.WriteLine and Console.ForegroundColor doesn't point to the same TextScren object...
The problem is Console.ForegroundColor change the color of X and Console.WriteLine writes text to Y.
So when it writes text to Y it keeps white-on-black color.

**Comment by mterwoord** [comment]
I';m starting to see what you mean. Not all plugs have been adjusted to use the GetConsole method. maybe you could make a PR to fix that?

**Comment by zdimension** [comment]
I think a good thing to do is add ForegroundColor and BackgroundColor fields to the Console class so that the set_ForegroungColor and set_BackgroundColor methods could work.
For the pull request, I don't exactly know how I am supposed to do that...
But if you want, I can modify the Console.cs class and the ConsoleImpl.cs class and send them to you (pastebin or something like that)
(sry for bad english)

**Comment by mterwoord** [comment]
For pull requests, please read up on:
https://help.github.com/articles/fork-a-repo
and 
https://help.github.com/articles/using-pull-requests/

**Comment by zdimension** [comment]
Just a little question, this is not the first time I download Cosmos source code, but I always have an error "Invalid Number" in DebugInfo.cs at line 34 for this ```public const long AssemblerDebugSymbolsRange = 0xL;```
What is ```0xL``` ?
Isn't it supposed to be 0x0L ?

**Comment by mterwoord** [comment]
Might be a bug in that particular version, but it seems to me you're using an older version then. Are you working on a fork?

**Comment by zdimension** [comment]
I just cloned the repository using the GitHub app, but I got this error every time I downloaded the source.
But just for information, what is 0xL supposed to mean ?

**Comment by mterwoord** [comment]
It means long value of 0.

**Comment by zdimension** [comment]
Strange. I would write it 0L or 0x0L...
But I'm working on the Console Color thing.

**Comment by mterwoord** [comment]
Might be a bug in that particular version, but it seems to me you're using an older version then. Are you working on a fork?

**Comment by zdimension** [comment]
I made the pull request!
