### ISSUE TITLE
Cosmos Boot Exceptions

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1070]
I built an ISO of my OS in Visual Studio 2017 using the newest UserKit, and had VMWare boot the ISO that I made.  Unfortunately, it hardly gets going when it lists several exceptions, none of which I know how to fix:
![error](https://user-images.githubusercontent.com/37987178/47275842-baf89080-d567-11e8-9170-8c09b21e0cae.JPG)
Any suggestions?

**Comment by fanoI** [comment]
Are you sure to have initialized Cosmo VFS? See here for example:
https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.Fat/Kernel.cs#L26

**Comment by sudopigeek** [comment]
I put "public static CosmosVFS FS = new CosmosVFS();" before the BeforeRun() method and placed "Sys.FileSystem.VFS.VFSManager.RegisterVFS(FS);" in the BeforeRun() method.

**Comment by 365Tito** [comment]
Here's a question @sudopigeek , do you use the original filesystem.vmdk or some new virtual HDD.
If you're using a new file, make sure to format it to FAT32 before running COSMOS on it. You can use bootable GParted on a VM to format your VMDK.

**Comment by sudopigeek** [comment]
I am pretty sure that I am using Filesystem.vmdk because VMWare has complained about it before.

**Comment by fanoI** [comment]
Probably should work as you have done too but try to do this exactly as done in: https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.Fat/Kernel.cs#L26
