### ISSUE TITLE
Devkit build error:  "System.Exception: The process failed to execute!"

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1071]
I have been trying to build and install the Devkit for quite a while, and none of my attempts have been successful.  I always get stuck when Cosmos is at "Build - Build.sln".  I have tried to change the directory that the files are in, so that they are like this:
        C:\Users\[user]\DEVKIT\source\Cosmos
        C:\Users\[user]\DEVKIT\source\IL2CPU
        C:\Users\[user]\DEVKIT\source\XSharp

I then went to the Windows command prompt and entered "install-VS2017.bat -NOCLEAN".  It has no problem whatsoever until here:
![devkit error](https://user-images.githubusercontent.com/37987178/47542406-1a211280-d892-11e8-835e-a29513647bf4.JPG)
Any tips or suggestions? (I am using the newest clone of Cosmos, IL2CPU, and XSharp)

**Comment by quajak** [comment]
Could you post a pastebin with the entire log please?
