### ISSUE TITLE
Can't add method to KeyboardBase.OnKeyPressed

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#1073]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Handling events (in KeyboardBase)

#### Expected Behaviour - What do you think that should happen?
It should build and add the method to the eventhandler.

#### Actual Behaviour - What unexpectedly happens?
The project doesn't build and gives the following error:

> Description: Exception: System.Exception:
> Project: UmbraOS
> File: IL2CPU
> Line: 1	

#### Reproduction - How did you get this error to appear?
I used 'Global.GetKeyboardDevices()' to add a method to the 'OnKeyPressed' event of all the devices.

> foreach(KeyboardBase keyboard in Global.GetKeyboardDevices())
> {
>     keyboard.OnKeyPressed += HandleKeypress;
>     Keyboards.Add(keyboard);
> }

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using the latest devkit (Date: 2018-10-29)

**Comment by BL9** [comment]
Uhm... You'll have to wait until sunday for that, I'm at my other place right now and I'm having some problems with my pc here.

**Comment by sjmulder** [comment]
Repro:

    using Cosmos.HAL;

    public class Kernel : Cosmos.System.Kernel
    {
        protected override void Run()
        {
            foreach (var keyboard in Global.GetKeyboardDevices())
                keyboard.OnKeyPressed += HandleKeypress;
        }

        void HandleKeypress(byte ScanCode, bool Released)
        {

        }
    }

Build output:

    1>------ Build started: Project: Cosmos1073, Configuration: Debug Any CPU ------
    1>Cosmos1073 -> C:\Users\s.mulder\source\repos\Cosmos1073\Cosmos1073\bin\Debug\netcoreapp2.0\cosmos\Cosmos1073.dll
    1>Message: Executing IL2CPU on assembly
    1>Message: Kernel Base: Cosmos.System.Kernel
    1>Message: Checking target assembly: C:\Users\s.mulder\source\repos\Cosmos1073\Cosmos1073\bin\Debug\netcoreapp2.0\cosmos\Cosmos1073.dll
    1>IL2CPU : error : Exception: System.Exception:
    1>Native code encountered, plug required.
    1>  DO NOT REPORT THIS AS A BUG.
    1>  Please see http://www.gocosmos.org/docs/plugs/missing/
    1>  Need plug for: System.MulticastDelegate  System.Delegate.InternalAllocLike(System.Delegate).
    1>  Called from :
    1>System.MulticastDelegate::System.MulticastDelegate NewMulticastDelegate(System.Object[], Int32, Boolean)
    1>System.MulticastDelegate::System.Delegate CombineImpl(System.Delegate)
    1>System.Delegate::System.Delegate CombineImpl(System.Delegate)
    1>
    1>
    1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 616
    1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 769
    1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 263
    1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
    1>IL2CPU task took 00:00:01.9874384
    1>Done building project "Cosmos1073.csproj" -- FAILED.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

(How is a required plug not a bug btw?)

**Comment by BL9** [comment]
What I don't understand about this is the fact that this works for the MouseBase but not KeyboardBase:

> foreach (MouseBase Mouse in Global.GetMouseDevices())
            {
                Mouse.OnMouseChanged = HandleMouse;
                Mouses.Add(Mouse);
            }

**Comment by quajak** [comment]
The difference is set `Mouse.OnMouseChanged = HandleMouse;` vs add `keyboard.OnKeyPressed += HandleKeypress;`. The second is not supported right now, as a plugs are missing
