### ISSUE TITLE
Visual Studio 2017 Migration Error

### ISSUE THREAD

**Issue by manamster** [CosmosOS/Cosmos#1074]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Project Creation

#### Expected Behaviour - What do you think that should happen?
It should open it up as a new project with a premade c# script

#### Actual Behaviour - What unexpectedly happens?
the operation could not be completed the project file c:\users\source\repos\cosmoskernel/cosmoskernel\cosmoskernal.csproj cannot be migrated

#### Reproduction - How did you get this error to appear?
by going to make a new project and selecting Cosmos Kernal under Visual C#

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit .exe

**Comment by manamster** [comment]
i got it fixed

**Comment by manamster** [comment]
srry

**Comment by sjmulder** [comment]
> i got it fixed

Can you tell us how? Just in case someone happens to come across this searching for a similar problem, and so things can perhaps be changed to prevent this issue from happening in the first place.

**Comment by manamster** [comment]
I just uninstalled visual studio then I uninstalled cosmos then I uninstalled the .NET NDP462-DevPack from microsoft then reinstalled visual studio then the devpack then cosmos in that order
