### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by manamster** [CosmosOS/Cosmos#1075]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling the Kernal

#### Expected Behaviour - What do you think that should happen?
It should pull up the ISO builder

#### Actual Behaviour - What unexpectedly happens?
![assertion failed_ abort quit retry debug ignore continue 10_30_2018 2_54_46 pm](https://user-images.githubusercontent.com/34355662/47728015-be9caf00-dc1a-11e8-9829-b96ce5845afc.png)
![cosmoskernel1 - microsoft visual studio 10_30_2018 2_54_53 pm](https://user-images.githubusercontent.com/34355662/47728017-c0667280-dc1a-11e8-9592-3e565b69e7d1.png)

#### Reproduction - How did you get this error to appear?
by trying to compile it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user kit because im new

**Comment by jp2masa** [comment]
You need to install VMware or use other profile. You can change the profile in the project properties.
