### ISSUE TITLE
CGS will not work

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#1078]
```
    Canvas c;
    protected override void BeforeRun()
    {

        var fs = new Sys.FileSystem.CosmosVFS();
        Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
        Console.Clear();
        c = FullScreenCanvas.GetFullScreenCanvas();
        c.Mode = new Mode(800,600, ColorDepth.ColorDepth32);
        c.Clear(Color.Black);
    }

    protected override void Run()
    {
        Pen p = new Pen(Color.White);
        for (int i = 0; i < 800; i++)
        {
            for (int j = 0; j < 600; j++)
            {
                c.DrawPoint(p, i, j);
            }
        }
    }

```

This code causes some CPU exceptions during runtime.

![](https://files.gitter.im/CosmosOS/Cosmos/cObM/ScreenShot-119.jpg)

![](https://files.gitter.im/CosmosOS/Cosmos/f8Rk/ScreenShot-121.jpg)

**Comment by fanoI** [comment]
It is the code in Run that causes the issue?

**Comment by fanoI** [comment]
More informations regarding this issue: this happens on the last DevKit, there were changes that apparently seemed only aesthetical in this PR  #1065.
Maybe IL2CPU has problems with automatic properties? Or with IReadOnlyList?
