### ISSUE TITLE
Boot Exception: Argument Out of Range

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1079]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Cosmos

#### Expected Behaviour - What do you think that should happen?

the OS to boot successfully

#### Actual Behaviour - What unexpectedly happens?

Exception: Argument out of range

#### Reproduction - How did you get this error to appear?

using System.IO functions

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

UserKit, Cosmos

Here is the error:
![snapshot - 1](https://user-images.githubusercontent.com/37987178/47964641-be712a80-dff1-11e8-9e04-f5c0c12a0153.png)

After some investigating, I found the code that was causing the error, but I don't know how I can fix it:

string[] user_name = { "user" };
            File.Create(@"0:\Username.txt");
            using (StreamWriter fs = new StreamWriter(@"0:\Username.txt"))
            {
                foreach (string line in user_name)
                {
                    fs.WriteLine(line);
                }
            }

**Comment by fanoI** [comment]
In theory it should work as you have written. But looking at the documentation of the StreamWriter(String) ctor it seems it will create the file when it does not exists already. So can you try to change your code in this
way?

using (StreamWriter fs = new StreamWriter(@"0:\Username.txt"))
{
foreach (string line in user_name)
{
fs.WriteLine(line);
}
}
