### ISSUE TITLE
Unboxing of struct with managed fields does not work

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#1082]
#### Area of Cosmos - What area of Cosmos are we dealing with?
BCL tests

#### Expected Behaviour - What do you think that should happen?
The field 'desc' should be read correctly

#### Actual Behaviour - What unexpectedly happens?
This is written on the Console:

> 09:30:15.640903         Error: Stackcorruption occurred at: 0x020D9675
09:30:15.674870         Msg: Core dump:
09:30:15.680402         Msg: EAX = 0x020D9602 EBX = 0x0204FFCC ECX = 0x00000000 EDX = 0x023E0000
09:30:15.680892         Msg: EDI = 0x02050870 ESI = 0x023ECEF0
09:30:15.682653         Msg: EBP = 0x02050868 ESP = 0x0205086C EIP = 0x02050870
09:30:15.686629         Msg:
09:30:15.696377         Msg: Call stack:
09:30:15.707717         Msg:
09:30:15.711489         Msg: at 0x020C6D0E
09:30:15.712143         Msg: at 0x020B279A
09:30:15.713745         Msg: at 0x022E61DB

#### Reproduction - How did you get this error to appear?

Define this structure:

```cs
        private struct Values
        {
            public string desc;
            public Encoding encoding;

            public Values(string desc, Encoding encoding)
            {
                this.desc = desc;
                this.encoding = encoding;
            }
        }
```

and then use it in this way:

```cs
        private void TestBoxingAndUnboxingValues()
        {
            object xValBoxed = new Values("UTF-8", new UTF8Encoding());

            Assert.IsTrue(((Values)xValBoxed).desc == "UTF-8", "Boxing and then Unboxing Values does not work");
        }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Last devKit

**Comment by quajak** [comment]
Seems to be fixed
