### ISSUE TITLE
Devkit Build - Build.sln

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#1088]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building Devkit

#### Expected Behaviour - What do you think that should happen?
Build Build.sln

#### Actual Behaviour - What unexpectedly happens?
Gives error.
The error:
https://pastebin.com/qdh8EC0V

#### Reproduction - How did you get this error to appear?
Run the devkit builder.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit (Updated a day ago)

**Comment by jp2masa** [comment]
You need to install the .NET Framework 4.7.1 Developer Pack (https://www.microsoft.com/en-us/download/details.aspx?id=56119).

**Comment by GtaMasterYT** [comment]
I already downloaded it though.

**Comment by GtaMasterYT** [comment]
![image](https://user-images.githubusercontent.com/18405555/48973947-aa7d7f00-f019-11e8-83ce-630d2dcf5a4b.png)

**Comment by GtaMasterYT** [comment]
I restarted the install and it worked.
