### ISSUE TITLE
ExtractMapFromElfFile task failed unexpectedly.

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#1089]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building OS

#### Expected Behaviour - What do you think that should happen?
to build

#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/18405555/48974198-2c23db80-f01f-11e8-8105-8f78f418f03e.png)

#### Reproduction - How did you get this error to appear?
I used build solution. Just installed Cosmos Devkit. VS2017 opened 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Most Latest Devkit

**Comment by GtaMasterYT** [comment]
It works except I got a few warnings, I don't know what they mean.
![image](https://user-images.githubusercontent.com/18405555/48994158-b9def400-f10f-11e8-9fc1-0208be82cf0a.png)

**Comment by jp2masa** [comment]
They can be ignored.

**Comment by GtaMasterYT** [comment]
Okay, since they can be ignored I will close this. Thanks!
