### ISSUE TITLE
Value cannot be null aPath

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#1091]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running OS.

#### Expected Behaviour - What do you think that should happen?
Bring me to First Run prompt I made. aka run OS.

#### Actual Behaviour - What unexpectedly happens?
Errors out with this
![image](https://user-images.githubusercontent.com/18405555/49188771-f5f59d00-f339-11e8-8974-d1554dc0a6e9.png)

Code:
https://pastebin.com/raw/6CBaFrYJ

Also, How do you do networking?

#### Reproduction - How did you get this error to appear?
I ran the OS in Virtual Box.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit commit 1f72b95 (Commit in the last issue I was told to use)

**Comment by fanoI** [comment]
VirtualBox is not officially supported, please use VmWare or Bochs.

**Comment by GtaMasterYT** [comment]
![image](https://user-images.githubusercontent.com/18405555/49321872-74884100-f4d8-11e8-8d51-e71fc29981e6.png)
I used VMware and got the same result.

**Comment by charlesbetros** [comment]
Do you have a disk with a fat12/16/32 partition attached to the vm? The image shows "No partition found.". My guess is when virtual file system tries to build a full path it can't because there aren't any partitions to get the root path (0:\, 1:\) from.

**Comment by GtaMasterYT** [comment]
is there a way to format in Cosmos?
I found CosmosVFS.Format but its pretty confusing.

**Comment by GtaMasterYT** [comment]
Quick update. It worked in Debug mode but VS crashed when I close the OS. If I just build the ISO image and run it in VMWare it doesnt work.

**Comment by Mcilie** [comment]
Yeah Im having the same issue. Im getting the idea that cosmos only really works inside vmware and VS when debugging. Please, I would really love for my Cosmos based Os to run on hardware one day.
thanks,

**Comment by GtaMasterYT** [comment]
Any more updates? No partitions using ISO.

**Comment by AdhithAdhi** [comment]
Still nothing that bad. without a partition how we can create a os
