### ISSUE TITLE
Network Simple Ping

### ISSUE THREAD

**Issue by ErwinsExpertise** [CosmosOS/Cosmos#1093]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Networking

#### Expected Behaviour - What do you think that should happen?
Should send ping request

#### Actual Behaviour - What unexpectedly happens?
Recieve NullReferenceException

#### Reproduction - How did you get this error to appear?

 public void newClient()
        {
            try
            {
                UdpClient uClient = new UdpClient();

                var ip = new Cosmos.System.Network.IPv4.Address(127, 0, 0, 1);
                var host = new Cosmos.System.Network.IPv4.EndPoint(ip, 80);
                byte[] payload = Encoding.ASCII.GetBytes("abcdefghijklmnopqrstuvwabcdefghi");

                try
                {
                    uClient.Connect(ip, 80);
                    uClient.Send(payload, ip, 80);
                    uClient.Receive(ref host);
                    Console.WriteLine("Connected!");
                    uClient = null;
                }
                catch (NullReferenceException e) 
                {
                    Console.WriteLine("Connection Failed");
                    Console.WriteLine(e.Message);
                }

            }
            catch
            {
                Console.WriteLine("Connection Failed");
            }

        }//end newClient

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest user kit

**Comment by GtaMasterYT** [comment]
I don't think UDP is done. I heard it was TCP being worked on not UDP.

**Comment by GtaMasterYT** [comment]
It works for me find. The problem might be that you are using the user kit. I am using the dev kit and it works.

**Comment by ErwinsExpertise** [comment]
> It works for me fine. The problem might be that you are using the user kit. I am using the dev kit and it works.

Installed the latest devkit, same issue.

**Comment by valentinbreiz** [comment]
@ErwinsExpertise are you using the UdpClient class from Cosmos or from the .NET framework?

**Comment by valentinbreiz** [comment]
Ok. Are you sure you are using a machine with an AMD PCNETII card ?
VMWare and Virtual Box support this card, if you are on VMWare you must check if it's a bridged connection in vm's settings.

**Comment by quajak** [comment]
Networking has received a major update. If this issue still exists please open a new issue.
