### ISSUE TITLE
COSMOS - How can I create a GUI? I can't find the way the other tutorials say to delete the "HardwareBoot" or whatever they call it in their tutorials.

### ISSUE THREAD

**Issue by celoufran** [CosmosOS/Cosmos#1094]

**Comment by fanoI** [comment]
You have the starting blocks here: https://www.gocosmos.org/docs/cosmos-graphic-subsystem.
The next pass is simply using CGS to create a GUI (buttons, dialogs, etc...) but none had yet done this, if you want you can try to this.
