### ISSUE TITLE
Waiting for debugger connection will not go away.

### ISSUE THREAD

**Issue by Verticalfile30** [CosmosOS/Cosmos#1096]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creating an iso

#### Expected Behaviour - What do you think that should happen?
Iso should be Created, when run on VirtualBox, Cosmos should not wait for a debugger connection. OS should run as usual.

#### Actual Behaviour - What unexpectedly happens?
When inserted in virtualbox, Cosmos waits for a debugger connection

#### Reproduction - How did you get this error to appear?
I set the profile to ISO image, in COSMOS properties, I set the Configuration from Active (Debug) to Release, Built Solution and inserted ISO image to VirtualBox. Then error occured. 
Note: I noticed that every build, the configuration would reset itself back from Release to Active (Debug).

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using the Latest Cosmos User kit (20181010) for Visual Studio 2017.

**Comment by mterwoord** [comment]
Have you disabled the debugger in the project settings?

**Comment by Verticalfile30** [comment]
Yes, I have changed the configuration to release in the Cosmos project settings.

**Comment by mterwoord** [comment]
You need to change settings on the cosmos property page.


Op do 13 dec. 2018 om 15:16 schreef Vert Simon <notifications@github.com>:

**Comment by Wumpee** [comment]
@mterwoord where can I find the COSMOS property page?

**Comment by KironDevCoder** [comment]
@mterwoord how do I do that?

**Comment by TFTWPhoenix** [comment]
To disable the "Waiting for Debugger Connection" screen, right click your project click properties go to the DEBUG tab under Cosmos, and uncheck enable remote debugging.

**Comment by sayaPintar** [comment]
this issues Was solved?

**Comment by euginee23** [comment]
> To disable the "Waiting for Debugger Connection" screen, right click your project click properties go to the DEBUG tab under Cosmos, and uncheck enable remote debugging.

this one worked.
