### ISSUE TITLE
PS/2 controller not supported

### ISSUE THREAD

**Issue by louis-e** [CosmosOS/Cosmos#1097]
#### Area of Cosmos - What area of Cosmos are we dealing with?
When I make a iso build and when i boot it.

#### Expected Behaviour - What do you think that should happen?
It should start without that error.

#### Actual Behaviour - What unexpectedly happens?
When I start it, after one second there's coming a message ((PS/2 Device) PS/2 controller not supported)

#### Reproduction - How did you get this error to appear?
It happens when I boot it from an USB flash drive on my computer. I also tried it on an old laptop: This error appears at the first start, but everything worked for the second start. When I start it in vmware, it works!

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit, Cosmos (I do not know exactly)

**Comment by zarlo** [comment]
can we get the PC specs

**Comment by louis-e** [comment]
AMD Ryzen 5 2400G with Radeon Vega Graphics
MSI B450M Bazooka
8GB DDR4 Ram

**Comment by zarlo** [comment]
cosmos is intell x86 only right now

**Comment by louis-e** [comment]
Oh okay, thanks for your help. Will AMD be integrated?

**Comment by jp2masa** [comment]
I don't believe the problem here is the CPU, the PS/2 controller currently has some problems on real hardware, there's a branch with some work to fix it.

**Comment by louis-e** [comment]
Okay thanks a lot!

**Comment by fy1vo51** [comment]
Maybe if there's any PS/2 devices like keyboard or mouse that connected to the computer, try to unplug and remove it. It should be resolved.

**Comment by louis-e** [comment]
Hi there, thank you for answering on my issue. But back then, 599 days ago, that also didn't worked. But now I don't need it anymore! :)

Thank you anyway!

**Comment by CronobotTech** [comment]
Hi there, nothing works for me,  I have tried disconnecting all PS/2 devices as well...for some reason it works on VMWare but not on real hardware.... Any suggestions?

**Comment by louis-e** [comment]
Can you try it on another hardware device? I can't remember exactly but I think then, when I had the problem, it worked on another device.

**Comment by Wolfsurge** [comment]
I know that this thread is two years old, but do you remember / know anything that might fix it? I really want to know, I've been having this issue, and I don't have anywhere else to test it.

**Comment by louis-e** [comment]
I think I wasn't actually able to fix it, but like I said, it worked perfectly fine on another device. 

Did that work for you?
> Maybe if there's any PS/2 devices like keyboard or mouse that connected to the computer, try to unplug and remove it. It should be resolved.

**Comment by Kludgy** [comment]
Is there any chance this will be integrated with user packages?

Would be useful to achieve compatibility for quick sharing with in-browser emulators like https://copy.sh/v86/.

**Comment by MishaTY** [comment]
@Kludgy It will be added to the user kit, once .net 5 gets merged.
