### ISSUE TITLE
Keyboard not working correctly

### ISSUE THREAD

**Issue by Starman0620** [CosmosOS/Cosmos#1098]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Actual OS \\ Input

#### Expected Behaviour - What do you think that should happen?
Keyboard works properly

#### Actual Behaviour - What unexpectedly happens?
My keyboard in cosmos appears to not be in qwerty so it is registering the wrong keys

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User

Whenever I use the keyboard the keys are all mapped incorrectly, for example A is Enter and alongside this whenever I press a key it registers it as two presses. When I run my OS in VMWare this issue is non existent, when I run it on my two laptops the keyboard straight up doesn't work. I have yet to try it on my main PC though

**Comment by fanoI** [comment]
A question your laptop keyboard is qwerty / US layout keyboard?

**Comment by Derpy-Canadian** [comment]
> A question your laptop keyboard is qwerty / US layout keyboard?

Sorry, forgot to respond. Yes it is QWERTY\US

**Comment by bumboo001** [comment]
Hello I have same issue, 
When I create bootable USB with rufus.A is enter but other keys does nothing at most cases. I tried it on my old laptop HP elitebook 2530p. I tried it on far better computer and on it works fine what to do? has cosmos some minimum requiments to run on some device?
I tried virtualbox because my old pc can't run vmware and keys was fine.

**Comment by josealissonbr** [comment]
Here I have the problem, in VMWare it works well, when booting from the pendrive the keyboard does not work.

**Comment by quajak** [comment]
Please open a new issue

**Comment by slavekrouta** [comment]
I also have the same issue using PS/2 keyboard.
