### ISSUE TITLE
Trying to install Devkit: "System.Exception: The process failed to execute!".

### ISSUE THREAD

**Issue by KrasnotR** [CosmosOS/Cosmos#1100]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building the Devkit.

#### Expected Behaviour - What do you think that should happen?
It should build the devkit with no errors.

#### Actual Behaviour - What unexpectedly happens?
Doesn't build. [THE LOG](https://hastebin.com/oxijopadul)

#### Reproduction - How did you get this error to appear?
no idea

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit. 29b9940. Using the "install-VS2019.bat".

**Comment by jp2masa** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3054,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\Krasno\Documents\DEVKIT\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]

This is not the first time someone's having this issue... No idea how to fix that issue for everyone, we'll probably remove that file anyway, for now you can try doing this: https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o.

**Comment by KrasnotR** [comment]
I've gone to the file "Cosmos\source\Cosmos.VS.ProjectSystem\ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx" and Unlocked it, seems to have worked. 
Thank you.
