### ISSUE TITLE
Memory managment using Span<T>, Memory<T> and ReadOnlySpan<T>, ReadOnlyMemory<T>

### ISSUE THREAD

**Issue by grahamehorner** [CosmosOS/Cosmos#1101]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.Core has a number of areas where memory calls are unsafe, these could be replaced with the new .NET core Span<>, Memory<> features to simplify the code and reduce potential issues when handling pointers.

The above .NET core features are highly optimised and this should also increase performance and well as stability

> 
> Span<T> and Memory<T> enables a uniform way to access contiguous memory, regardless how the memory is allocated. It is very helpful for native development scenarios, as well as high performance scenarios. Especially, you will gain significant performance improvements while using span types to work with strings. It is a very nice feature innovated in C# 7.2.
> NOTE: To use this feature, you will need to use Visual Studio 2017.5 and language version 7.2 or latest.

**Comment by jp2masa** [comment]
We are working on that, and the first step is almost done (upgrading to .NET Core 2.1, #1099).
