### ISSUE TITLE
DirectoryEntry error

### ISSUE THREAD

**Issue by adamstenbaek** [CosmosOS/Cosmos#1103]
I am trying to do `fs.DeleteDirectory("0:\\TEST");` but it says it has to be a `'Cosmos.System.FileSystem.Listing.DirectoryEntry'`, what is a DirectoryEntry, i have tried Sysem.Reflection.PortableExecutable.DirectoryEntry, that did not work.

**Comment by fanoI** [comment]
You should simple use the System.IO method directly, the Cosmos.System.FileSystem are not mean to be called directly.
So you must enable filesystem in the kernel BeforeRun method in this way:

```cs
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```

then to delete a directory you can use Directory.Delete().
