### ISSUE TITLE
File creation error: aFirstCluster

### ISSUE THREAD

**Issue by hackerncoder** [CosmosOS/Cosmos#1104]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FileSystem

#### Expected Behaviour - What do you think that should happen?
The file is going to be created

#### Actual Behaviour - What unexpectedly happens?
It doesn't get created and I get the error message: `Exception occurred: Specified argument was out of range of valid values
Parameter name: aFirstCluster`

#### Reproduction - How did you get this error to appear?
Trying to create a file using both File.create and fs.CreateFile

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit 
Dev kit, master 29b9940

**Comment by CaydendW** [comment]
I am very sorry I was late, and I'm not sure this will help much by if you're using a Virtual Machine to run the OS try change the hard drive controller from IDE to SATA or SCSI. It doesn't work on IDE controller. That was what fixed my issue. Hope this helps!
