### ISSUE TITLE
Plug usage

### ISSUE THREAD

**Issue by strgoose** [CosmosOS/Cosmos#1105]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Plugs

#### Expected Behaviour - What do you think that should happen?
I'm getting an error :

```
Need plug for: System.Net.Sockets.SocketError  Interop+Winsock.WSAStartup(System.Int16, &Interop+Winsock+WSAData).
Called from :
System.Net.NameResolutionPal::Void EnsureSocketsAreInitialized()
System.Net.Dns::System.String GetHostName()
CosmosKernel1.IPPlug::System.String hn()
```
So I create a class and a Plug accordingly:
```
[Plug(Target = typeof(global::System.Net.Sockets.SocketError))]
    class IPPlug
    {
        public static string hn()
        {
            return Dns.GetHostName();
        }
        public static string addr()
        {
            return Dns.GetHostEntry(hn()).AddressList[0].ToString();
        }
    }
```

#### Actual Behaviour - What unexpectedly happens?
I'm still getting an error.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit.

**Comment by MishaTY** [comment]
You can learn how to use networking here: https://cosmosos.github.io/articles/Kernel/Network.html

Also, plugs will not work in your kernel.
