### ISSUE TITLE
eror  Visual Studio Workloads not found.

### ISSUE THREAD

**Issue by DRACA123** [CosmosOS/Cosmos#1106]
========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads not found.

========================================
    Error
========================================

System.Exception: Dependency installation failed! Dependency name: Visual Studio Workloads
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

![cosmos kit builder 8 1 2019 16_57_05](https://user-images.githubusercontent.com/46491415/50838416-a2c62f80-1366-11e9-9eb0-ded751f1cf3d.png)

**Comment by DRACA123** [comment]
![cosmos kit builder 8 1 2019 17_04_27](https://user-images.githubusercontent.com/46491415/50838765-7bbc2d80-1367-11e9-8b97-f214c6d61e4f.png)

**Comment by DRACA123** [comment]
![c__windows_system32_cmd exe 8 1 2019 21_58_26](https://user-images.githubusercontent.com/46491415/50855525-bbe3d600-1390-11e9-9ec0-4001ae4b7a55.png)

**Comment by adamstenbaek** [comment]
Have you insured you have Visual Studio 2017 installed, .NET Core Tools and .NET Framework 4.6.2 Developer Pack?

**Comment by DRACA123** [comment]
yes

**Comment by DRACA123** [comment]
![cosmos kit builder 10 1 2019 15_06_48](https://user-images.githubusercontent.com/46491415/50973358-5f4bfc80-14f1-11e9-8813-226c6fcc7e06.png)

**Comment by DRACA123** [comment]
![cosmos kit builder 10 1 2019 16_56_14](https://user-images.githubusercontent.com/46491415/50976471-b7d2c800-14f8-11e9-8cbd-7e6fcc7773a0.png)

**Comment by adamstenbaek** [comment]
There is a Windows "security" feature that makes some files locked, can you paste the log on Pastebin and give a link?
