### ISSUE TITLE
cannot use Mouse #COSMOS OS

### ISSUE THREAD

**Issue by chathurax** [CosmosOS/Cosmos#1107]
Cannot  use  Mouse.Initialize(320,200); Method!!!!!!!!!!!!
Error:
Exception: System.ArgumentOutOfRangeException: Token 0x0a000095 is not valid in the scope of module Cosmos.Hardware.dll.

**Comment by RICKASHEYE** [comment]
why not 
Mouse mouse = new Mouse();
just that and pull data from it i assume

**Comment by Flabtrap** [comment]
i did
Mouse mouse = new Mouse();
mouse.Initialize(320, 200);
but it steel not working..

**Comment by jeuxjeux20** [comment]
A method that works is:
```cs
MouseManager.ScreenWidth = columnsCount;
MouseManager.ScreenHeight = rowsCount;
```
where `columnsCount` and `rowsCount` are the number of columns and rows, like 320 and 200. 
You can then use  `MouseManager.X` and `MouseManager.Y`
