### ISSUE TITLE
Why does it say 'Cosmos.Build.Builder\bin Debug\net471\Cosmos.Build.Builder. exe 'not in the new version?

### ISSUE THREAD

**Issue by AlonsSoft** [CosmosOS/Cosmos#1111]

**Comment by AlonsSoft** [comment]
I was reminded when opening the installation of BAT program. Who can answer that?

**Comment by jp2masa** [comment]
Do you have the .NET Core SDK installed?

**Comment by NinjaPaimen** [comment]
I don't know, but i know how to fix it.

Go to Cosmos.Build.Builder\bin\Debug\. There should be folder named net472. Rename it to net471 and run the install .bat again.

**Comment by charlesbetros** [comment]
If this is still an issue let us know.
