### ISSUE TITLE
Cosmos Devkit wont install stuck on Installing Visual Studio Workloads

### ISSUE THREAD

**Issue by RICKASHEYE** [CosmosOS/Cosmos#1112]
#### Area of Cosmos - What area of Cosmos are we dealing with?
The Devkit installer install-vs2017.bat on visual studio 15.9

#### Expected Behaviour - What do you think that should happen?
complete

#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/10345394/51312396-ec192c00-1a96-11e9-987b-6c5402930083.png)

the visual studio installer appears untill 64% then it closes in the task manager but the cosmos installer continues on this image above

![image](https://user-images.githubusercontent.com/10345394/51313057-60080400-1a98-11e9-878d-dfe746466dd9.png)

ends up like this a few commits back (i did try the latest version) and end up with the same error when pressing the X button on the window with the message under Actual Behaviour
#### Reproduction - How did you get this error to appear?
started installing

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
i Was using the dev kit the latest from this date

**Comment by KrasnotR** [comment]
Do you have "Visual Studio extension development" and ".NET Core cross-platform development" installed?

**Comment by RICKASHEYE** [comment]
"Visual Studio extension development" wasnt installed ".NET Core cross-platform development" was already thanks
