### ISSUE TITLE
Attempting to call method via reflection, getting Arg_NotImplemented exception

### ISSUE THREAD

**Issue by spkellydev** [CosmosOS/Cosmos#1113]
I haven't been writing C# for that long, but I thought a Cosmos CLI would be fun. I'm trying to keep the code dry, and not have a thousand switch cases so I opted for reflection. Any idea where I'm going wrong? I can get the method calls to work outside of Cosmos in regular console apps / .NET core

#### Area of Cosmos - What area of Cosmos are we dealing with?
Reflection, Arg_NotImplementedException

#### Expected Behaviour - What do you think that should happen?
I believe the method should be called via Reflection. I made a small fiddle highlighting successful code running outside of Cosmos which throws an error inside of Cosmos. I'm attempting to call a method via a string provided by the command line. https://dotnetfiddle.net/9CTXmE

#### Actual Behaviour - What unexpectedly happens?
Exception is thrown.

#### Reproduction - How did you get this error to appear?
input : ls

From `Kernal.cs`
```
string input = Prompt.ReadLine();
                    if (input.Length > 0)
                    {
                        ProcessManager.Process(input);
                    }
                    Prompt.PS();
```
In `ProcessManager.cs`
```
/** .....
*/
 switch(args[0]) {
  ...
             default: {
                        try
                        {
                            Prompt.FindCommandByName(splitInput);
                            return;
                        }
                        catch (Exception e)
                        {
                            Prompt.WriteLine(e.Message);
                        }
                        Prompt.WriteLine("Could not find command");
                        break;
            }
 }
```
`Prompt.cs`
```
namespace SkellOS.Skell.Shell
{
    public class Prompt
    {
        static Prompt()
        {
            PS();
        }
        public static void PS()
        {
            Console.Write("skell$ ");
        }

        public static void Clear()
        {
            Console.Clear();
        }

        public static string ReadLine()
        {
            return Console.ReadLine();
        }

        public static void WriteLine(string result)
        {
            Console.WriteLine(result);
        }

        public static void FindCommandByName(string[] args)
        {
            Type type = typeof(Command);
            MethodInfo method = type.GetMethod(args[0].ToUpper());
            Command c = new Command(args);
            string result = (string)method.Invoke(c, null);
            WriteLine(result);
        }
    }
}
public class Command
{
    private string[] args;
    public Command(string[] vargs) { args = vargs; }
    public string LS() { return "LS called"; }
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit -- CosmosUserKit-20181010-vs2017.exe

**Comment by Project-Magenta** [comment]
I don't think that Cosmos supports reflection. Try using a dictionary.

**Comment by fanoI** [comment]
Yes reflection is yet not supported.
