### ISSUE TITLE
System.Exception: After interpreting stack types, nothing changed

### ISSUE THREAD

**Issue by Oasis1819** [CosmosOS/Cosmos#1114]
```
Dim A As Integer = 0
A = A + 1
Console.WriteLine(A.ToString())
```

I expected the above code to print '1' but it does not work, the language I use is Visual Basic, and I get the following error when trying to debug.

**Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1CosmosKernel1KernelRun': System.Exception: After interpreting stack types, nothing changed! (First instruction needing types = IL_0050: Add_Ovf)	CosmosKernel1	C:\Users\MyNickname\source\repos\CosmosKernel1\CosmosKernel1\IL2CPU	1**	

Is there any good way to solve this problem?
In addition, operation codes such as 'Variable1 + Variable2' did not work

Or is it that you can not do this basic operation?
I need your help. :(

**Comment by Oasis1819** [comment]
Okay, I'll try the developer kit, if so, will it be available in the user version in the future?

**Comment by fanoI** [comment]
Obviously yes, on the next release of the UserKit!

**Comment by Oasis1819** [comment]
Thanks to everyone, I'll wait for a later release version or install a developer version!
