### ISSUE TITLE
Cosmos drawing mouse

### ISSUE THREAD

**Issue by Flabtrap** [CosmosOS/Cosmos#1115]
I GOT ERROR IN COSMOS.. can you guys help me
so i try to make mouse and i just type
Mouse mouse = new Mouse();
and
mouse.Initialize(320, 200);
but it shows 
'Initialize' accepting a first argument of type 'Mouse' could be found (are you missing a using directive or an assembly reference?)
what should i do?
and here is my code
using System.Text;
using Sys = Cosmos.System;
using Cosmos.Core.IOGroup;
using Cosmos.HAL;

namespace CosmosKernel5
{
    public class Kernel : Sys.Kernel
    {
        VGAScreen screen;
        Mouse mouse;
        protected override void BeforeRun()
        {
            screen = new VGAScreen();
            screen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
            screen.Clear(15);
            mouse = new Mouse();
            mouse.Initialize(320, 200);
        }

        protected override void Run()
        {
            screen.Clear(15);
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y, 0);
            screen.SetPixel320x200x8((uint)mouse.X - 1, (uint)mouse.Y, 0);
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y - 1, 0);
            screen.SetPixel320x200x8((uint)mouse.X - 2, (uint)mouse.Y, 0);
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y - 2, 0);
        }
    }
}

**Comment by Flabtrap** [comment]
and i can make initialize like this
Mouse[,] mouse = new Mouse[320, 200];
but screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y, 0); this one's X and Y is steel have error..

**Comment by KrasnotR** [comment]
you could just use a class like this 
```csharp
using Cosmos.System.Graphics;
using CMouse = Cosmos.System.MouseManager;

public static class MouseManagerEx
{
    public static Point ToPoint() => new Point((int)CMouse.X, (int)CMouse.Y);

    public static void SetDimensions(Mode mode)
    {
        CMouse.ScreenHeight = (uint)mode.Rows;
        CMouse.ScreenWidth = (uint)mode.Columns;
    }
}
```
