### ISSUE TITLE
ATA device doesn't work

### ISSUE THREAD

**Issue by SamyoFox** [CosmosOS/Cosmos#1117]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FileSystem

#### Expected Behaviour - What do you think that should happen?
Read the file system

#### Actual Behaviour - What unexpectedly happens?
It says 'ATA device with speclevel ATAPI found, which is not supported yet!' 
when I'm trying the default Run option in Visual Studio 2017 for Cosmos

#### Reproduction - How did you get this error to appear?
idk

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20181010-vs2017

**Comment by fanoI** [comment]
This is not really an error ATAPI is the CD/DVD Rom that is not yet supported, the HDD should be recognized and working.
Do you inizialied Cosmos VFS correctly?

See here:
https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem
