### ISSUE TITLE
[Question] ARMv5TE support

### ISSUE THREAD

**Issue by MLXProjects** [CosmosOS/Cosmos#1121]
How could I help to bring this OS to the ARMv5TE platform? 
My idea is run this from an embedded device (PocketPC) so i can make it more useful.

**Comment by fanoI** [comment]
Do you know ARM assembly?
The first thing to do will be to create a version of X# (A#?) that could generate ARM asm... the problem is that X# is yet not completely finished.

Probably a more "interesting" target will be the RasberryPI.

**Comment by MLXProjects** [comment]
No, at the moment i don't know ARM assembly.
Oh, so i'll wait until X# is more stable/finished before to do anything!
Also, yes, the R Pi could be more useful and interesting target, but start with ARMv5TE support could make easier to support ARMv7 than make it backwards compatible from v7, i think.

**Comment by Project-Magenta** [comment]
I know some ARM assembly

**Comment by dilan-omer** [comment]
So as let me get this straight. X# is the basis for COSMOS right? And currently X# is x86 assembly only? So when we can make a build of COSMOS where X# is Arm Assembly instead of x86 assembly, we can port a COSMOS-based OS onto an Arm system (or a Rasp. Pi for that matter) right? Seems like something I could possibly try to get my hands around.

**Comment by zarlo** [comment]
more or less, some plugs might need to be changed too

**Comment by Project-Magenta** [comment]
true dat

**Comment by dilan-omer** [comment]
So it definitely seems doable. Might give it a try soon

**Comment by dilan-omer** [comment]
Never mind, just saw how big it is. Not as doable as I might have thought, still might give it a go or contribute

**Comment by Project-Magenta** [comment]
I can help
