### ISSUE TITLE
.NET Core not detected

### ISSUE THREAD

**Issue by KironDevCoder** [CosmosOS/Cosmos#1123]
======================
Checking Prerequisites
======================

Check if User Kit Installer is already running.
Checking if Visual Studio is running.
Checking if Builder is already running.
Checking for .NET Core
Checking for Visual Studio Extension Tools
Checking for Inno Setup
Checking for Inno Preprocessor

=====
Error
=====

.NET Core not detected.

I installed both .NET Core SDK and .NET Core Runtime from https://dotnet.microsoft.com/download but I still get this error, how do I fix this? I am using Visual Studio Community 2017 on Windows 10 64 bits

**Comment by Project-Magenta** [comment]
Install the .net core workload in VS

**Comment by KironDevCoder** [comment]
You mean .NET Core Runtime in Induvidual components right? That doesn't work

**Comment by Project-Magenta** [comment]
No I mean the workload

**Comment by KironDevCoder** [comment]
Now I get errors compiling Cosmos when installing, around 5712 errors

**Comment by Project-Magenta** [comment]
Screenshot?

**Comment by KironDevCoder** [comment]
Sorry I can't take a screenshot of it but it ends with

Console returned exit code. (0x00000001)
   bij Cosmos.Build.Installer.Task.StartConsole(String aExe, String aParams) in E:\KironOS Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\Task.cs:regel 115
   bij Cosmos.Build.Builder.CosmosTask.MSBuild(String aSlnFile, String aBuildCfg) in E:\KironOS Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\CosmosTask.cs:regel 121
   bij Cosmos.Build.Builder.CosmosTask.CompileCosmos() in E:\KironOS Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\CosmosTask.cs:regel 329
   bij Cosmos.Build.Builder.CosmosTask.DoRun() in E:\KironOS Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\CosmosTask.cs:regel 85
   bij Cosmos.Build.Installer.Task.Run() in E:\KironOS Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\Task.cs:regel 19

and while compiling I saw some errors which has to do with the reference System

**Comment by quajak** [comment]
Could you paste the entire error log in a pastebin?

**Comment by KironDevCoder** [comment]
no the it's too big for pastebin

**Comment by MLXProjects** [comment]
Have you tried removing the space at the folder's name? (KironOS Cosmos)
Stupid but may work.
If not, open the VS Installer (should be at start menu) and check if you selected ".NET Core Workload" or something like that. Also, you can make a text file, paste the log in it and upload it to any site (i use ge.tt/)

**Comment by KironDevCoder** [comment]
If I didn't have .NET Core workload then I Cosmos would give me the error: .NET Core not detected (which I got in the beginning)

**Comment by KironDevCoder** [comment]
Error log: http://ge.tt/3aB61hu2

**Comment by KironDevCoder** [comment]
Still getting same error, any1 has good idea?

**Comment by Project-Magenta** [comment]
it looks like the package restore isn't happening

**Comment by Project-Magenta** [comment]
I wonder why

**Comment by KironDevCoder** [comment]
I do get this as output when I open install-VS2017.bat

Running NuGet restore
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
All packages listed in packages.config are already installed.
Looking for MSBuild
Build started 1-3-2019 16:17:49.
     1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
     1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (1) is building "E:\KironOS_Cosmos\Cosmos-netcore\source\
       Cosmos.Build.Installer\Cosmos.Build.Installer.csproj" (3) on node 2 (default targets).
     3>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
       o the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         Cosmos.Build.Installer -> E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\bin\Debug\Cosmos.Buil
         d.Installer.dll
     3>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\Cosmos.Build.Installer.csp
       roj" (default targets).
     1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (1) is building "E:\KironOS_Cosmos\Cosmos-netcore\source\
       Cosmos.Build.Builder\Cosmos.Build.Builder.csproj" (2) on node 1 (default targets).
     2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.t
       argets(2110,5): warning MSB3270: There was a mismatch between the processor architecture of the project being bu
       ilt "MSIL" and the processor architecture of the reference "Interop.TaskScheduler", "x86". This mismatch may cau
       se runtime failures. Please consider changing the targeted processor architecture of your project through the Co
       nfiguration Manager so as to align the processor architectures between your project and references, or take a de
       pendency on references with a processor architecture that matches the targeted processor architecture of your pr
       oject. [E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj]
     2>MainResourcesGeneration:
       Skipping target "MainResourcesGeneration" because all output files are up-to-date with respect to the input file
       s.
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
       o the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       _CopyFilesMarkedCopyLocal:
         Touching "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\obj\Debug\Cosmos.Build.Builder.csproj.C
         opyComplete".
       _CopyAppConfigFile:
       Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         Cosmos.Build.Builder -> E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\bin\Debug\Cosmos.Build.Bu
         ilder.exe
     2>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj"
        (default targets).
     1>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (default targets).

Build succeeded.

       "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (default target) (1) ->
       "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj" (default target) (2)
       ->
       (ResolveAssemblyReferences target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion
       .targets(2110,5): warning MSB3270: There was a mismatch between the processor architecture of the project being
       built "MSIL" and the processor architecture of the reference "Interop.TaskScheduler", "x86". This mismatch may c
       ause runtime failures. Please consider changing the targeted processor architecture of your project through the
       Configuration Manager so as to align the processor architectures between your project and references, or take a
       dependency on references with a processor architecture that matches the targeted processor architecture of your
       project. [E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj]

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.98

**Comment by KironDevCoder** [comment]
I do get this when I open install-VS2017.bat:

	Running NuGet restore
	MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
	All packages listed in packages.config are already installed.
	Looking for MSBuild
	Build started 1-3-2019 16:17:49.
		 1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" on node 1 (default targets).
		 1>ValidateSolutionConfiguration:
			 Building solution configuration "Debug|Any CPU".
		 1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (1) is building "E:\KironOS_Cosmos\Cosmos-netcore\source\
		   Cosmos.Build.Installer\Cosmos.Build.Installer.csproj" (3) on node 2 (default targets).
		 3>GenerateTargetFrameworkMonikerAttribute:
		   Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
		   o the input files.
		   CoreCompile:
		   Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
		   CopyFilesToOutputDirectory:
			 Cosmos.Build.Installer -> E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\bin\Debug\Cosmos.Buil
			 d.Installer.dll
		 3>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Installer\Cosmos.Build.Installer.csp
		   roj" (default targets).
		 1>Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (1) is building "E:\KironOS_Cosmos\Cosmos-netcore\source\
		   Cosmos.Build.Builder\Cosmos.Build.Builder.csproj" (2) on node 1 (default targets).
		 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.t
		   argets(2110,5): warning MSB3270: There was a mismatch between the processor architecture of the project being bu
		   ilt "MSIL" and the processor architecture of the reference "Interop.TaskScheduler", "x86". This mismatch may cau
		   se runtime failures. Please consider changing the targeted processor architecture of your project through the Co
		   nfiguration Manager so as to align the processor architectures between your project and references, or take a de
		   pendency on references with a processor architecture that matches the targeted processor architecture of your pr
		   oject. [E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj]
		 2>MainResourcesGeneration:
		   Skipping target "MainResourcesGeneration" because all output files are up-to-date with respect to the input file
		   s.
		   GenerateTargetFrameworkMonikerAttribute:
		   Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
		   o the input files.
		   CoreCompile:
		   Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
		   _CopyFilesMarkedCopyLocal:
			 Touching "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\obj\Debug\Cosmos.Build.Builder.csproj.C
			 opyComplete".
		   _CopyAppConfigFile:
		   Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
		   CopyFilesToOutputDirectory:
			 Cosmos.Build.Builder -> E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\bin\Debug\Cosmos.Build.Bu
			 ilder.exe
		 2>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj"
			(default targets).
		 1>Done Building Project "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (default targets).

	Build succeeded.

		   "E:\KironOS_Cosmos\Cosmos-netcore\Builder.sln" (default target) (1) ->
		   "E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj" (default target) (2)
		   ->
		   (ResolveAssemblyReferences target) ->
			 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion
		   .targets(2110,5): warning MSB3270: There was a mismatch between the processor architecture of the project being
		   built "MSIL" and the processor architecture of the reference "Interop.TaskScheduler", "x86". This mismatch may c
		   ause runtime failures. Please consider changing the targeted processor architecture of your project through the
		   Configuration Manager so as to align the processor architectures between your project and references, or take a
		   dependency on references with a processor architecture that matches the targeted processor architecture of your
		   project. [E:\KironOS_Cosmos\Cosmos-netcore\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj]

		1 Warning(s)
		0 Error(s)

	Time Elapsed 00:00:02.98

**Comment by KironDevCoder** [comment]
My .NET SDK isn't supporting .NET Core 2.2 which might cause the errors with System not found.

**Comment by KironDevCoder** [comment]
"My .NET SDK isn't supporting .NET Core 2.2 which might cause the errors with System not found." How do I get this to work?

**Comment by Project-Magenta** [comment]
download .net core 2.2???

**Comment by KironDevCoder** [comment]
I can't in Visual Studio Installer and from https://dotnet.microsoft.com/download/dotnet-core/2.2 both installing SDK and Runtime didn't work

**Comment by zarlo** [comment]
@KironDevCoder you you have .net 4.7(.2) installed too

**Comment by KironDevCoder** [comment]
I already had .NET Framework 4.7.2 installed

**Comment by KironDevCoder** [comment]
Do I need 4.6.2 instead? If so, how do I uninstall .NET Framework 4.7.2 first?

**Comment by Project-Magenta** [comment]
no

**Comment by KironDevCoder** [comment]
But then it doesn't work

**Comment by KironDevCoder** [comment]
Ok uhm... when I create a new .NET Core Console Application in VS 2017 and I target framework .NET Core 1.1 (which isn't done automatically apparently) I also get System not found but a minute later it goes away but when I launch it it crashes?!

"It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found."

**Comment by Project-Magenta** [comment]
your .net is botched

**Comment by KironDevCoder** [comment]
and... what now?

**Comment by KironDevCoder** [comment]
how do I fix .NET?

**Comment by KironDevCoder** [comment]
Guys? Hello? Do I need to make another issue for my botched .NET?

**Comment by adamstenbaek** [comment]
Try uninstalling Visual Studio, All core SDK and Runtime and everything else that might cause this issue, then install them, one at a time.

**Comment by KironDevCoder** [comment]
STFU ADAM! Uninstalling .NET SDKs and Runtimes broke my wifi adapter and I had to reset my computer >:C

**Comment by Project-Magenta** [comment]
OH NO

**Comment by adamstenbaek** [comment]
I am very sorry about the problem my suggestion has caused. But we all make mistakes, and I now know for the next time that this suggestion can cause problems.
