### ISSUE TITLE
ATAPI device doesn't work even though not using file system

### ISSUE THREAD

**Issue by Mcilie** [CosmosOS/Cosmos#1125]
#### Area of Cosmos - What area of Cosmos are we dealing with?
dealing with sample code. I modified the template 
heres my kernel class

` public class Kernel : Sys.Kernel
    {
        int sum(int x, int y) {
            return x + y;
        }
        protected override void BeforeRun()
        {
            Console.WriteLine("Welcome to MathOS, enter 2 numbers to see their sum!");
        }

        protected override void Run()
        {
            try
            {

                Console.Write("A: ");
                int a = Convert.ToInt32(Console.ReadLine());
                Console.Write("B: ");
                int b = Convert.ToInt32(Console.ReadLine());
                Console.WriteLine(sum(a, b));
            }
            catch {
                Console.WriteLine("oops");
            }

        }
    }`
#### Expected Behaviour - What do you think that should happen?
OS shouldn't crash. Ive searched up this error and apparently it has to do with the file system though im not even using files.

#### Actual Behaviour - What unexpectedly happens?
It crashes, complains about a null pointer and this error appears in the output
`Setting FirstDataLookupTable to 
0x02259409
FirstDataLookupTable was set to 
0x02259409
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA device with speclevel ATAPI found, which is not supported yet!
Done initializing Cosmos.HAL.Global
KeyboardManager.AddKeyboard
Cls
Before Run
Run
Not yet stopped
Really before Run
KeyboardManager.HandleScanCode
Number of keys: 
0x00000058
KeyboardManager.HandleScanCode
KeyboardManager.HandleScanCode
Number of keys: 
0x00000058
KeyboardManager.HandleScanCode
KeyboardManager.HandleScanCode
Number of keys: 
0x00000058
KeyboardManager.HandleScanCode
KeyboardManager.HandleScanCode
Number of keys: 
0x00000058
The program '' has exited with code 0 (0x0).`

#### Reproduction - How did you get this error to appear?
running my code

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest user kit, vs2017 latest update.

**Comment by quajak** [comment]
What is the null pointer error? The log you posted does not include any error.

**Comment by RICKASHEYE** [comment]
do not worry about it some general C# is not supported i assume like for example Random in C# doesn't work correctly or at all

**Comment by Mcilie** [comment]
im guessing its convert.toint32
