### ISSUE TITLE
Are there plugs for .NET Core 3 UI?

### ISSUE THREAD

**Issue by CatGirlsAreLife** [CosmosOS/Cosmos#1127]
I am thinking of making a OS, However I would like for some parts of it to be designed in the Windows Forms or WPF designer. As such are there or is there a easy way for me to plug these windows only parts of .NET Core 3 so my OS can work with any applications that target Windows Forms or WPF. I also wonder how cosmos can work with the 100% unmanaged ``git`` program (the unix version), ``vi`` or ``vim``, ``gcc``, ``clang``, or any other unmanaged program I would like to be able to run that is compiled in the ELF32/ELF64 format (depending on if it is a 32 or 64 bit cpu).

While I want the OS to be complete C#, I use a lot of command-line applications like ``git`` a lot.

Unless I have to somehow port these applications to C# too which would make it much harder to maintain and keep up to date with https://github.com/git/git.git commit-to-commit?

**Comment by zarlo** [comment]
cosmos is only .net core 2.1 (for now) and i dont know if will we ever use .net core 3 UI as we are working on our own UI system

**Comment by CatGirlsAreLife** [comment]
ok, so basically build in a sandbox system to the OS for unmanaged programs. Ok, that could work too.
