### ISSUE TITLE
ATA doesn't work nicely with ATAPI

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#113]
The bug crashes Bochs, and most likely real hardware.

**Comment by Geramy** [comment]
case 0x24: // READ SECTORS EXT
        case 0x29: // READ MULTIPLE EXT
          lba48 = 1;
        case 0x20: // READ SECTORS, with retries
        case 0x21: // READ SECTORS, without retries
        case 0xC4: // READ MULTIPLE SECTORS
          /* update sector_no, always points to current sector
           * after each sector is read to buffer, DRQ bit set and issue IRQ
           * if interrupt handler transfers all data words into main memory,
           * and more sectors to read, then set BSY bit again, clear DRQ and
           * read next sector into buffer
           * sector count of 0 means 256 sectors
           */

          if (!BX_SELECTED_IS_HD(channel)) {
            BX_INFO(("ata%d-%d: read sectors issued to non-disk",

**Comment by mterwoord** [comment]
The bug doesn't have to do with bochs, but most likely just that bochs' ATA configuration was different than VMware. Probablyu all CD-drives give this bug.

We're postponing this for a bit..

**Comment by CSharpLover** [comment]
Is the bug fixed?
Can we use real hardware now?

**Comment by ARMmaster17** [comment]
@CSharpLover, issue is still present. We're making progress though.

**Comment by CSharpLover** [comment]
By BIOS has a switch between ATA and Compatiability mode.
@ARMmaster17, thanks for your help. Can switching Compatiability mode from ATA in my BIOS work?

**Comment by mterwoord** [comment]
@CSharpLover Doubt it. That most of the time has to do with RAID and stuff.
