### ISSUE TITLE
Unable to go from CGS back to Text Mode

### ISSUE THREAD

**Issue by RICKASHEYE** [CosmosOS/Cosmos#1130]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Graphics Subsystem

#### Expected Behaviour - What do you think that should happen?
To go back to Console

#### Actual Behaviour - What unexpectedly happens?
Unknown function to do so

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit using https://github.com/CosmosOS/Cosmos/pull/1124 also is this merged yet?

**Comment by quajak** [comment]
This is currently not implemented and as discussed in https://github.com/CosmosOS/Cosmos/issues/601 might stay this way.
