### ISSUE TITLE
Runtime error at 1:321 when installing User Kit

### ISSUE THREAD

**Issue by The14thPingSpoofer** [CosmosOS/Cosmos#1131]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installing User Kit 20181010.

#### Expected Behaviour - What do you think that should happen?
A window should pop up that lets me install Cosmos.

#### Actual Behaviour - What unexpectedly happens?
A window pops up that says: "Runtime error (at 1:321):
SWbemLocator: Неправильное пространство имен" ("Неправильное пространство имен" = "Invalid namespace").

#### Reproduction - How did you get this error to appear?
I downloaded "CosmosUserKit-20181010-vs2017.exe" from gocosmos.org, opened it, it asked for intallation language and then this error window popped up. Also I have Windows 8.1 x86, Visual Studio 2017 v15.9.3.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit 20181010.

**Comment by adamstenbaek** [comment]
Do you have:
1. VS2017 Workload: .NET Core Tools
2. (.NET Framework 4.6.2 Developer Pack)[https://www.microsoft.com/en-us/download/details.aspx?id=53321]
