### ISSUE TITLE
General installation issue 

### ISSUE THREAD

**Issue by LukasSevc** [CosmosOS/Cosmos#1132]
#### Area of Cosmos - What area of Cosmos are we dealing with?

compile

#### Expected Behaviour - What do you think that should happen?

It must compile well

#### Actual Behaviour - What unexpectedly happens?

When I press start button in vs 17 ( latest update) it show me error that startup project isn’t 
set or it can’t run it ( cosmos os kernel project ) when I set it it throws same error. Than when I have selected VMware ( 15 ) machine and I build it ( because I can’t normally press start ) it doesn’t do anything -> it makes a iso which when I try to boot it only displays  “waiting for debugger”. When I select ISO and build or rebuild it make another ISO which when I boot it only once boot normally. Quite often it displays “waiting for debugger”
 ( after build and rebuild ) and sometimes VMware shows “ booting  { name of OS } ... 
( on next line ) bootable file not found. ( on next line ) boot:  “ ( too after build and rebuild )

#### Reproduction - How did you get this error to appear?

I don’t know

**Comment by VisualDevelopment** [comment]
Use the latest devkit

**Comment by LukasSevc** [comment]
I tried it ( now I have vs 19 ), i ran "install vs 19.bat" as administrator and when it ran cosmos kit builder i got this error: 
========================================
    Builder Log
========================================


========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.


========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Skipping project "C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Skipping project "C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Restore completed in 50.22 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 51.87 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 51.18 ms for C:\Users\Administrator\Downloads\Cosmos-master\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 56.93 ms for C:\Users\Administrator\Downloads\Cosmos-master\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 1.67 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 21.12 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 7.71 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 24.52 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 25.23 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 1.23 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 19.2 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 19.04 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 3.84 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 1.06 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 6.26 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 8.97 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 8.18 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 10.65 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 2.38 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 8.26 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 6.35 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 1.56 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 1.38 ms for C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 4.11 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 13.07 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 1.6 ms for C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 8.06 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Tools\NASM\NASM.csproj.
  Restore completed in 9.76 ms for C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 2.4 ms for C:\Users\Administrator\Downloads\Cosmos-master\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 17.45 ms for C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 2.56 ms for C:\Users\Administrator\Downloads\Cosmos-master\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 1.33 ms for C:\Users\Administrator\Downloads\Cosmos-master\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 2.72 ms for C:\Users\Administrator\Downloads\Cosmos-master\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 11.21 ms for C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\IL2CPU\IL2CPU.csproj.


========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Build.Common -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Deploy.USB -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Deploy.Pixie -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Debug.GDB -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.Core.DebugStub -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.DebugStub.dll
  Spruce -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Spruce.dll
  XSharp.Assembler -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.Assembler.dll
  IL2CPU.API -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.API.dll
  VSPropertyPages -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  IL2CPU.Debug.Symbols -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  XSharp.x86 -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.x86.dll
  Cosmos.Debug.Kernel -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.dll
  Cosmos.VS.ProjectSystem -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.dll
  Cosmos.Common -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Common.dll
  Cosmos.Core -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.dll
  Cosmos.HAL2 -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.HAL2.dll
  Restore completed in 78.83 ms for C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Cosmos.System2 -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2.dll
  Cosmos.Debug.HyperVServer -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.VS.Windows -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.Windows.dll
  XSharp -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.dll
  Cosmos.Debug.Hosts -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Hosts.dll
  TheRingMaster -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\TheRingMaster.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project 'C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj' does not exist. [C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.Build.Tasks -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.TestRunner.TestController -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll
  NASM -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\NASM.dll
  Cosmos.Debug.HyperVServer -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
VTablesImpl.cs(4,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(1,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(8,24): error CS0246: The type or namespace name 'Debugger' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  Cosmos.VS.DebugEngine -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.VS.ProjectSystem -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.vsix
  Cosmos.System2_Plugs -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2_Plugs.dll
  Cosmos.VS.DebugEngine -> C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.vsix


========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in C:\Users\Administrator\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

**Comment by VisualDevelopment** [comment]
don't run as admin

**Comment by VisualDevelopment** [comment]
also rename your folder to Cosmos

**Comment by LukasSevc** [comment]
> don't run as admin

You mean with admin privileges or administrator account?

**Comment by LukasSevc** [comment]
> also rename your folder to Cosmos

Witch folder? You mean folder with cosmos installation files - in which is located "install vs 19.bat" bat file? The name must be simply "cosmos", right?

**Comment by VisualDevelopment** [comment]
yes it has to be cosmos and not `Cosmos-master` and i meant admin privileges

**Comment by LukasSevc** [comment]
Please sorry for my ( from my perspective ) stupid questions, but I want to be 100% sure about what I am doing. Please understand me, thanks!

**Comment by LukasSevc** [comment]
> yes it has to be cosmos and not `Cosmos-master` and i meant admin privileges

Ok I will try it

**Comment by VisualDevelopment** [comment]
it's alright lol

**Comment by LukasSevc** [comment]
thanks

**Comment by LukasSevc** [comment]
I have problem now because I can't run program without admin rights, I am running it as administrator account

**Comment by LukasSevc** [comment]
I ran it, and it seems to work correctly!

**Comment by LukasSevc** [comment]
It also created folders with name - common, il2cpu and xsharp, can I delete it?

**Comment by LukasSevc** [comment]
yes the cosmos now work fine, but as i asked before, can I delete those folders?

**Comment by VisualDevelopment** [comment]
do not delete these folders

**Comment by LukasSevc** [comment]
why?

**Comment by LukasSevc** [comment]
I have another problem now, when I run project ( vmware selected ) it compiles and run vmware, but it didn't create iso file so vmware can't boot

**Comment by LukasSevc** [comment]
I know where is problem, I have folder with name that can't be readed by cosmos - it has latin characters

**Comment by LukasSevc** [comment]
> do not delete these folders

why I can't delete those folders?

**Comment by VisualDevelopment** [comment]
you need them

**Comment by VisualDevelopment** [comment]
they are cosmos dependencies
