### ISSUE TITLE
feature request (or any plan) will support userspace network stack ?

### ISSUE THREAD

**Issue by sgf** [CosmosOS/Cosmos#1133]
#### Area of Cosmos - What area of Cosmos are we dealing with?
network

#### Expected Behaviour - What do you think that should happen?
how about directly support user space tcp/ip stack (just like dpdk) in Cosmos

#### Actual Behaviour - What unexpectedly happens?
none

#### Reproduction - How did you get this error to appear?

none
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos

**Comment by sgf** [comment]
the feature-- user space network stack.
is the cornerstone of operating systems in the future.

intel has take many time and money to develop dpdk.
but its only support linux/bsd/windows...so on.

but if Cosmos  direct support it.
maybe Cosmos will be more popular.
Every birth of a new great platform needs good characteristic.

i think thats one of that.
In the meantime, Cosmos, very compact and flexible.

**Comment by quajak** [comment]
There has been work on getting networking support, which is being tracked in a number of different issues.
