### ISSUE TITLE
A Project With Class Libary Cannot Be Started

### ISSUE THREAD

**Issue by ProDarkNinja** [CosmosOS/Cosmos#1135]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Startup

#### Expected Behaviour - What do you think that should happen?
Help me fix this probelm

#### Actual Behaviour - What unexpectedly happens?
I don't know it says an error that it cannot be started

#### Reproduction - How did you get this error to appear?
When I tried to launch the app

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit Latest as of 28/03/2019
![error](https://user-images.githubusercontent.com/39980226/55141493-61902f80-519f-11e9-980f-1c23232d0c95.JPG)

**Comment by ProDarkNinja** [comment]
Please Help!
I need to use this by tommarow!

**Comment by quajak** [comment]
That error most likely means that the installation of cosmos was not complete, and VS did not recognise the solution as a cosmos project.
