### ISSUE TITLE
Visual Studio 2019 Support?

### ISSUE THREAD

**Issue by TheCrafters001** [CosmosOS/Cosmos#1136]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Hello. I was wondering if the installer for Cosmos will install automatically to VS2019. I really want to try it, but I am unsure if it works in VS2019. Just want to make sure before I go and break everything.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, Latest Release.

**Comment by zarlo** [comment]
there is only support for it in the dev kit for now

**Comment by TheCrafters001** [comment]
> there is only support for it in the dev kit for now

Alright. When will there be support for the User Kit on VS 2019?

**Comment by zarlo** [comment]
it will be in the next release, dont know when that would be

**Comment by WinMister332** [comment]
@zarlo Likely when hell freezes over. Or the day China becomes a democracy.

**Comment by zarlo** [comment]
@WinMister332 well most of the time there is 1 update a year

**Comment by WinMister332** [comment]
@zarlo That's inefficient.

**Comment by charlesbetros** [comment]
If you would like to see releases more often, feel free to join the team to help out. :)
