### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by CMadian1998** [CosmosOS/Cosmos#1137]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Installation of the Dev Kit
#### Expected Behaviour - What do you think that should happen?

The installation process should be completed without errors
#### Actual Behaviour - What unexpectedly happens?

Installer ends with an error in the Build-Build.sln
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev kit. unsure about the version. Heres the log:

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"H:\Visual Studio 2017\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Skipping project "C:\Users\madig\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Skipping project "C:\Users\madig\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Restore completed in 59.88 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 74.87 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 75.01 ms for C:\Users\madig\Downloads\Cosmos-master\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 79.46 ms for C:\Users\madig\Downloads\Cosmos-master\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 3.98 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 27.56 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 17.2 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 10.24 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 55.13 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 3.57 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 3.86 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 13.49 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 3.79 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 12.08 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 3.78 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 5.47 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 3.42 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 4.2 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 8.46 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 4.72 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 3.93 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 3.59 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 4.92 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 5.4 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 8.07 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Tools\NASM\NASM.csproj.
  Restore completed in 3.44 ms for C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 3.41 ms for C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 9.49 ms for C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 6.65 ms for C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 4.55 ms for C:\Users\madig\Downloads\Cosmos-master\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 3.25 ms for C:\Users\madig\Downloads\Cosmos-master\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 9.86 ms for C:\Users\madig\Downloads\Cosmos-master\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 4.78 ms for C:\Users\madig\Downloads\Cosmos-master\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 11.38 ms for C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\IL2CPU\IL2CPU.csproj.

========================================
    Build - Build.sln
========================================

"H:\Visual Studio 2017\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Deploy.Pixie -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Build.Common -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Cosmos.Core.DebugStub -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.DebugStub.dll
  VSPropertyPages -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  Cosmos.Debug.GDB -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.GDB.exe
  IL2CPU.API -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.API.dll
  Cosmos.Debug.Kernel -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.dll
  Cosmos.Deploy.USB -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Common -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Common.dll
  Cosmos.TestRunner.TestController -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll
  IL2CPU.Debug.Symbols -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.VS.ProjectSystem -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.dll
  XSharp.x86 -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.x86.dll
  Cosmos.Debug.HyperVServer -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Spruce -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Spruce.dll
  XSharp.Assembler -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.Assembler.dll
  XSharp -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.dll
H:\Visual Studio 2017\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1879,5): warning : The referenced project 'C:\Users\madig\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj' does not exist. [C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.VS.ProjectSystem -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.vsix
  TheRingMaster -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\TheRingMaster.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
VTablesImpl.cs(4,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(1,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(8,24): error CS0246: The type or namespace name 'Debugger' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\madig\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  NASM -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\NASM.dll
  Cosmos.Core -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.dll
  Restore completed in 52.85 ms for C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Cosmos.Debug.HyperVServer -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.Debug.Hosts -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.VS.Windows -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.Windows.dll
  Cosmos.Build.Tasks -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.HAL2 -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.VS.DebugEngine -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.System2 -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2_Plugs.dll
  Cosmos.VS.DebugEngine -> C:\Users\madig\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by BaRRaKudaRain** [comment]
Read the following: error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?). Nuget Package? Missed dependency?

**Comment by quajak** [comment]
Is the IL2CPU version up to date?

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1147 and rename the folder Cosmos-Master to Cosmos
