### ISSUE TITLE
Can not start a project directly with a class library output type.

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1138]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Testing it.

#### Expected Behaviour - What do you think that should happen?
It should load without problems, I didn't even touch the sample code.

#### Actual Behaviour - What unexpectedly happens?
https://imgur.com/a/kVbXbXk

And in the project dependencies, there is warning icons, but the User Kit installed without errors :
https://imgur.com/a/oleai0Y

#### Reproduction - How did you get this error to appear?
I pressed the run button.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit at the time I'm writing this issue.

**Comment by ProgrammerDim** [comment]
Can you try the latest Dev Kit?
PS:What version of Visual Studio do you have?

**Comment by AnErrupTion** [comment]
Visual Studio 2017 or 2019, I think 2019.

**Comment by ProgrammerDim** [comment]
Can you check extension and see if `Cosmos Debug Engine` and `Cosmos Project System`  are installed?

**Comment by quajak** [comment]
Can you check what nuget sources there are? There should be one specifically for cosmos.
