### ISSUE TITLE
Error Cosmos Os

### ISSUE THREAD

**Issue by SarthakGupta22** [CosmosOS/Cosmos#1140]
Severity	Code	Description	Project	File	Line	Suppression State
**Error	MSB6006	"nasm.exe" exited with code 1.**	CosmosKernel1	C:\Users\MyProfile\.nuget\packages\cosmos.build\2018.10.10\build\Cosmos.Build.targets	206	

I am getting the above error while using cosmos in visual studio 2017. I think this happened when i used 2-d arrays in the code. Everything was ok till i was using 1-d arrays.
Can you tell me if cosmos support 2-d arrays. If yes then how can i resolve this issue?

**Comment by quajak** [comment]
Could you post the output log when you try to build?

**Comment by quajak** [comment]
Cosmos does not support 2d arrays currently and some work on the compiler to support them. For now dont use 2d arrrays.
