### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by arsium** [CosmosOS/Cosmos#1141]
It' s missing the dependencies when i create a new project in vb net with VS pro 2017

**Comment by arsium** [comment]
And I have only the possibilites to build a kernel not an operating system

**Comment by arsium** [comment]
CLose this just i've corrected my problem

**Comment by BaRRaKudaRain** [comment]
Do a NuGet restore and then reply me.

**Comment by charlesbetros** [comment]
If this is still a problem feel free to open a new issue.
