### ISSUE TITLE
Visual Studio unable to recognize/create CosmosOS projects 

### ISSUE THREAD

**Issue by iProgramMC** [CosmosOS/Cosmos#1142]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I don't know, perhaps installer

#### Expected Behaviour - What do you think that should happen?
CommonProject (C#).zip should appear in C:\Users\User\Documents\Visual Studio 2017\Templates\ProjectTemplates\Visual C#

#### Actual Behaviour - What unexpectedly happens?
CommonProject (C#).zip is missing, leading to unusability

#### Reproduction - How did you get this error to appear?
Installing the User Kit (found at [https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20181010](url))

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit (slightly confused)

**Comment by iProgramMC** [comment]
Also, I can not open any Cosmos projects downloaded from users.

**Comment by quajak** [comment]
As far as I know Cosmos Common is not part of the user kit at the moment and only needed for the dev kit. What is the problem opening projects from users?

**Comment by iProgramMC** [comment]
There are no templates for Cosmos. Opening outside projects returns the following error:
![image](https://user-images.githubusercontent.com/17717494/56466836-b54d0c00-641f-11e9-9514-8e9cdeee4e75.png)
This error also shows up if Cosmos User Kit is installed.

**Comment by iProgramMC** [comment]
![image](https://user-images.githubusercontent.com/17717494/56466874-3c9a7f80-6420-11e9-9fde-64088112fec9.png)
Reinstalling does not fix the problem. This is what the Visual C# section of my VS2017 project creation templates looks like.

**Comment by quajak** [comment]
If you look in Extensions, do you have the Cosmos Project System and Cosmos Debug System?

**Comment by iProgramMC** [comment]
![image](https://user-images.githubusercontent.com/17717494/56506203-6a69ec00-6526-11e9-9201-4f8597d16358.png)
Nope, it does not.

**Comment by iProgramMC** [comment]
![image](https://user-images.githubusercontent.com/17717494/56506280-aac96a00-6526-11e9-8158-873bc805da17.png)
No errors occured.

**Comment by quajak** [comment]
Can you check what the content of ./AppData/Roaming/Cosmos User Kit is?

**Comment by iProgramMC** [comment]
I've run "tree /a /f" and pasted the output here:
https://gist.github.com/iProgramMC/f046b5aac60402031400bef448ad2e40

**Comment by quajak** [comment]
During the cosmos installation, files are written under AppData, which is not under Cosmos but `C:\Users\User\AppData\Roaming\Cosmos User Kit` could check that path please?

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1147 for a fix until the problem is properly fixed

**Comment by iProgramMC** [comment]
What do you mean?

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1147#issuecomment-486568593 and https://github.com/CosmosOS/Cosmos/issues/1147#issuecomment-486564238

**Comment by iProgramMC** [comment]
What ProjectSystem folder are you talking about? I can't seem to find any.

**Comment by quajak** [comment]
Ok, so it is a different error, as the manifest is wrong, which did not occur in the other issue. The ProjectSystem folder should have a path like this `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Cosmos\ProjectSystem`

**Comment by iProgramMC** [comment]
`Cosmos\ProjectSystem` doesn't exist in the VS2017 extensions folder.

**Comment by iProgramMC** [comment]
![image](https://user-images.githubusercontent.com/17717494/56725960-85bb3e00-6756-11e9-9304-359729b7614d.png)

**Comment by quajak** [comment]
The error message "The extension manifest is invalid" seems to be caused by some problem with your visual studio installation. For example see https://github.com/wallabyjs/public/issues/1777 and try if the recommended steps help.

**Comment by iProgramMC** [comment]
I'll try repairing my installation. If it doesn't work, I'll try reinstalling.

**Comment by iProgramMC** [comment]
Yes! Turns out, the installation was partially broken, thus, now it works!
