### ISSUE TITLE
Error while opening the properties

### ISSUE THREAD

**Issue by AntINFINAit** [CosmosOS/Cosmos#1143]
I am using VS2019 with the Dev Kit.(i ran install-vs2019.bat)
When i try to go to properties - cosmos/cosmos new, i get the following errors, one after the other:
1 Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.
And after closing the properties window and opening again:
2 An error occurred trying to load the page.
Unable to create the designer.  File is already opened in an incompatible editor.

I want to set it to not wait for the debugger.

I can compile the project, and run it with the VMwarePlayer.
Any help?

**Comment by WinMister332** [comment]
I get that too, it's really annoying.

**Comment by WinMister332** [comment]
This doesn't fix the issue itself, but it at the very least will allow you to set debug state.
If your *project.csproj* does not have this in the First PropertyGroup:
```
<DebugEnabled>False</DebugEnabled>
<DebugMode>Source</DebugMode>
```
It should disable debug. Though I modified my .csproj file using tags from a VS2017 COSMOS project.

**Comment by AntINFINAit** [comment]
Thanks a lot.

**Comment by quajak** [comment]
It seems to be that the method `Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'` was removed in Visual Studio 2019, so the code has to be adjusted.

**Comment by jp2masa** [comment]
I updated the CPS packages a few days ago to fix this issue, and I tested it now and it seems to work fine. Please make sure you're using latest master from Common and Cosmos.

**Comment by WinMister332** [comment]
Does that mean we'll have to run the installer again...?

**Comment by jp2masa** [comment]
Yes.

**Comment by AntINFINAit** [comment]
Thanks. Issue can be closed.
