### ISSUE TITLE
Can't use System.IO

### ISSUE THREAD

**Issue by ad2017gd** [CosmosOS/Cosmos#1144]
Hello, i'm constantly getting a CPU error when trying to read/write to a volume. The problem is probably how I initialize the filesystem, because I tried .GetVolumes().Count which returned 0. Please tell me if I did anything wrong:
```csharp
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```
Any help?

**Comment by ad2017gd** [comment]
Ok I know what I'm doing wrong. I need to create a partition. But how?

**Comment by charlesbetros** [comment]
Cosmos doesn't currently create partitions. There is a fat32 image includes in the user kit,

**Comment by ad2017gd** [comment]
Well then any way i can use assembly to create a partition?

**Comment by charlesbetros** [comment]
I'm sure there is. Unfortunately I havrn't looked in to creating partitions. You could ask in our forums or in gitter.

**Comment by ad2017gd** [comment]
What forums? I couldn't find any.

**Comment by quajak** [comment]
https://www.atozed.com/forums/forumdisplay.php?fid=21
