### ISSUE TITLE
Cosmos does not generate CosmosKernel1Boot project

### ISSUE THREAD

**Issue by MegaBatchGames** [CosmosOS/Cosmos#1145]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Project Creation

#### Expected Behaviour - What do you think that should happen?
It creates a project called CosmosKernel1Boot

#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/48155604/56432040-e7495b80-62c3-11e9-8c24-a3c0f0d12b36.png)

#### Reproduction - How did you get this error to appear?
I created a project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 169dc5e.

**Comment by charlesbetros** [comment]
The new project system doesn't require a boot project. It's all contained in a single kernel project.

**Comment by quajak** [comment]
Can this issue be closed?
