### ISSUE TITLE
PS/2 device not suppprted

### ISSUE THREAD

**Issue by ad2017gd** [CosmosOS/Cosmos#1146]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting. 

#### Expected Behaviour - What do you think that should happen?
Start successfully. 

#### Actual Behaviour - What unexpectedly happens?
Exception occured while running kernel:
Exception : (PS/2 Controller) PS/2 device not suppprted

#### Reproduction - How did you get this error to appear?
Burned ISO to CD and booted. 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, latest version at the time of this post

**Comment by ad2017gd** [comment]
UPDATE: i tried booting from another machine and it worked. Any idea why?

**Comment by quajak** [comment]
As far as I can understand the error, the keyboard of the machine is not currently supported

**Comment by ad2017gd** [comment]
awesome... this is a laptop with the integrated keyboard. thanks for the help tho
