### ISSUE TITLE
Install Error on Build

### ISSUE THREAD

**Issue by ProgrammerDim** [CosmosOS/Cosmos#1147]
#### Area of Cosmos - What area of Cosmos are we dealing with?
installation

#### Expected Behaviour - What do you think that should happen?
Install normaly

#### Actual Behaviour - What unexpectedly happens?
An Error Appears(See below)

#### Reproduction - How did you get this error to appear?
using  install-VS2019.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using Dev Kit  Commit b9307acfdfa7f92b46093612fac761752763588b
### Description
When clicking at install-VS2019.bat it open normally but when it enters the Build - Build.sln state an Error appears!

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Skipping project "C:\Users\User\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Skipping project "C:\Users\User\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Restore completed in 120,97 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 121,41 ms for C:\Users\User\Downloads\Cosmos-master\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 127,87 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 11,67 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 150,86 ms for C:\Users\User\Downloads\Cosmos-master\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 51,67 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 45,43 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 63,69 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 63,87 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 8,88 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 3,76 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 8,68 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 9,47 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 3,2 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 11,04 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 13,2 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 11,42 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 26,57 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 33,33 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 7,69 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 19,44 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 12,29 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 34,25 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 23,84 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 8,44 ms for C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 38,93 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Tools\NASM\NASM.csproj.
  Restore completed in 29,36 ms for C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 24,1 ms for C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 4,39 ms for C:\Users\User\Downloads\Cosmos-master\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 44,17 ms for C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 7,46 ms for C:\Users\User\Downloads\Cosmos-master\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 6,14 ms for C:\Users\User\Downloads\Cosmos-master\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 10 ms for C:\Users\User\Downloads\Cosmos-master\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 40,02 ms for C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\IL2CPU\IL2CPU.csproj.

========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Build.Common -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Deploy.USB -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Debug.GDB -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.Deploy.Pixie -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Core.DebugStub -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.DebugStub.dll
  IL2CPU.API -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.API.dll
  VSPropertyPages -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  IL2CPU.Debug.Symbols -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\IL2CPU.Debug.Symbols.dll
  XSharp.x86 -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.x86.dll
  Cosmos.Debug.Kernel -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.dll
  Spruce -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Spruce.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3054,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
  XSharp.Assembler -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.Assembler.dll
  XSharp -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\XSharp.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1883,5): warning : The referenced project 'C:\Users\User\Downloads\Cosmos-master\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj' does not exist. [C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Restore completed in 126,32 ms for C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
VTablesImpl.cs(4,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(1,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(8,24): error CS0246: The type or namespace name 'Debugger' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\User\Downloads\Cosmos-master\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.Debug.HyperVServer -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.Debug.Hosts -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.VS.Windows -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.Windows.dll
  TheRingMaster -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\TheRingMaster.dll
  Cosmos.Debug.HyperVServer -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Build.Tasks -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.TestRunner.TestController -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  NASM -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\NASM.dll
  Cosmos.Common -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Common.dll
  Cosmos.Core -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.Core.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.HAL2 -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.VS.DebugEngine -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.System2 -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.System2_Plugs.dll
  VSPropertyPages -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  Cosmos.VS.DebugEngine -> C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by quajak** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3054,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\User\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
You have to unblock the file.

**Comment by ProgrammerDim** [comment]
@quajak I unblocked the file and tried again but the same error appears!
I have done some deep research and it seems the problem to be in the Inno Setup Script ("C:\Users\User\Downloads\Cosmos-master\Cosmos-master\Setup\Cosmos.iss") at line 83  it say to get all the file from a folder named "IL2CPU" under ".\Build\VSIP\" but that folder does not exist!

**Comment by quajak** [comment]
This seems to be very smilar to https://github.com/CosmosOS/Cosmos/issues/1137. 
I dont think the issue is caused by the inno setup script as that only runs after the build is finished. 
The issue might be `Skipping project "C:\Users\User\Downloads\Cosmos-master\IL2CPU..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.` but I am not sure how that is caused.

**Comment by ProgrammerDim** [comment]
Actually the file "C:\Users\User\Downloads\Cosmos-master\IL2CPU..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" does not exist neither at the folder in my computer nor at github
Any ideas how to install properly?

**Comment by quajak** [comment]
The path to the file seems to be messed up.

**Comment by ProgrammerDim** [comment]
Maybe the correct one is "C:\Users\User\Downloads\Cosmos-master (2)\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" ??

**Comment by quajak** [comment]
I dont understand the build process well enough to know if this is a problem and if yes, how to fix it. The same error message also appears in https://github.com/CosmosOS/Cosmos/issues/1110. The problem in that case is an outdated framework version, can you confirm that yours is up to date?

**Comment by ProgrammerDim** [comment]
I had .net 4.7.2 now I'm installing 4.8

**Comment by ProgrammerDim** [comment]
Updated to .net 4.8(latest) and still happens :-(

**Comment by jp2masa** [comment]
The folder should be named Cosmos, not Cosmos-master.

**Comment by ProgrammerDim** [comment]
@jp2masa @quajak Changed the name and now it creates the setup properly, it installs but when I open Visual Studio (2019) it doesn't show up in "Create new Project" section.

**Comment by quajak** [comment]
Might be a similar problem to https://github.com/CosmosOS/Cosmos/issues/1142. Can you check, if the Cosmos AppData was written?

**Comment by ProgrammerDim** [comment]
[output.txt](https://github.com/CosmosOS/Cosmos/files/3115527/output.txt)
Here is the my tree!

**Comment by ProgrammerDim** [comment]
@quajak Also here are my Extensions.
![image](https://user-images.githubusercontent.com/49944888/56717966-83e97e80-6746-11e9-985f-48d614567a9f.png)

**Comment by quajak** [comment]
Ok, so that seemed to have worked. Can you check if something similar to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Cosmos\ProjectSystem` exists? Note I am using VS 2017m so the path could be slightly different.

**Comment by ProgrammerDim** [comment]
It exists but its tree is 
\---~PC
    \---ProjectTemplates
With nothing in ProjectTemplates
Note: the path is
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Cosmos\ProjectSystem`

**Comment by ProgrammerDim** [comment]
@quajak Also note that there is a hidden file named "cache.bin"

**Comment by quajak** [comment]
Ok, so I think we found the issue. I do not have a cache.bin but there are files in ProjectTemplates and under ProjectSystem, which means that the installation for ProjectSystem is somehow failing. Are you getting any log while the packages are installing?

**Comment by ProgrammerDim** [comment]
I'm going to run the setup again and see

**Comment by quajak** [comment]
Ok, can you afterwards try and go under AppData/Roaming/Cosmos User Kit/VSIX there should be the two packages. If you run Cosmos.VS.ProjectSystem.vsix you should be able to install it manually.

**Comment by ProgrammerDim** [comment]
@quajak Tried both and it still doesn't show up!
1.(Setup)Setup Finished Sucessfully but took a long time to "add" the Cosmos Project Extension
2.(Manually)Says that it is allready installed!

**Comment by quajak** [comment]
Can you delete the empty ProjectSystem folder and try it again manually?

**Comment by ProgrammerDim** [comment]
@quajak  It works but when creatng that project all the dependencies are not found and the OS can't compile.

**Comment by quajak** [comment]
Have you tried rebuilding and a nuget restore? What are the error messages in the output?

**Comment by ProgrammerDim** [comment]
![image](https://user-images.githubusercontent.com/49944888/56723748-3c68ef80-6752-11e9-9b6d-fd88af6a011c.png)
1.This is the Error.
2.The nuget restore worked!(for the dependencies)

**Comment by quajak** [comment]
Have you installed vmware?

**Comment by ProgrammerDim** [comment]
@quajak I understand that it needs Vmware but can I debug with Bochs or Qemu?

**Comment by quajak** [comment]
Under Project Settings you have to change the deployement

**Comment by ProgrammerDim** [comment]
![image](https://user-images.githubusercontent.com/49944888/56725702-09c0f600-6756-11e9-867b-e894d2465caf.png)
Error

**Comment by quajak** [comment]
I have no idea what the problem is, Most likely the fix does not really work. @jp2masa might know how to fix the problem.

**Comment by ProgrammerDim** [comment]
@jp2masa Can you help?

**Comment by jp2masa** [comment]
You should use the Cosmos property page, not Cosmos (new). Also, are you using latest master from the Common repo?

**Comment by ProgrammerDim** [comment]
@jp2masa  Cosmos Property page:
![image](https://user-images.githubusercontent.com/49944888/56743972-44d81f00-6780-11e9-907e-fd46dfd354d9.png)
Also I'm not sure if it is the latest master from Common(I downloaded it yesterday)

**Comment by ProgrammerDim** [comment]
First I'm getting the Error:
`Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.`
And after closing the properties window and opening again:
```
An error occurred trying to load the page.
Unable to create the designer. File is already opened in an incompatible editor.
```

**Comment by quajak** [comment]
Please try and keep one issue to one error. For the error you are experiencing now check https://github.com/CosmosOS/Cosmos/issues/1143.
