### ISSUE TITLE
Can't change Ring

### ISSUE THREAD

**Issue by ProgrammerDim** [CosmosOS/Cosmos#1149]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Ring System

#### Expected Behaviour - What do you think that should happen?
The AssemblyInfo.cs does exist so you can change Ring

#### Actual Behaviour - What unexpectedly happens?
The AssemblyInfo.cs does not exist

#### Reproduction - How did you get this error to appear?
Create new Project try to change Ring(Change AssemblyInfo.cs)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit b9307acfdfa7f92b46093612fac761752763588b 
#### Description
Can't change Ring because AssemblyInfo.cs does not exist.
Trying to create a AssemblyInfo.cs (Assembly Info File) creates lot of errors like `Duplicate 'x' attribute`

**Comment by quajak** [comment]
Rings are currently disabled so you dont have to change the ring of a project.

**Comment by zarlo** [comment]
and you may have to make AssemblyInfo.cs your self

**Comment by quajak** [comment]
Most likely, but not in the near future.

**Comment by ProgrammerDim** [comment]
is there a reason that they are disabled?

**Comment by quajak** [comment]
`The next generation of the Cosmos compiler and architecture will be using a new ring structure, and to facilitate the move, the rings have been disabled.` See https://github.com/CosmosOS/Cosmos/wiki/Rings
