### ISSUE TITLE
inno setup install failed

### ISSUE THREAD

**Issue by Jennyhehe** [CosmosOS/Cosmos#1150]
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? using any of the .bats I've tried user and dev although I somehow got the kernel project

**Comment by ProgrammerDim** [comment]
Try to install Inno Seup manually [http://www.jrsoftware.org/isdl.php](Download Link)

**Comment by VisualDevelopment** [comment]
This issue is caused by an error in the code, it detects only Inno Setup V5, which I fixed and I made a pull request with the fix (#1148).
