### ISSUE TITLE
Goes to installer and crashes 

### ISSUE THREAD

**Issue by Jennyhehe** [CosmosOS/Cosmos#1153]
![AE824E2B-E6F5-4D3B-A39F-2588984136B6](https://user-images.githubusercontent.com/50123570/56999952-10e16d00-6b77-11e9-9e3f-10b7b56ddbbf.jpeg)

**Comment by RICKASHEYE** [comment]
XSharp isnt installing properly did you click yes to Install it and like two other packages

**Comment by Jennyhehe** [comment]
Yes it was a dependency il2cpu and inno but nothing about xsharp can I install it manually
