### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by robincosmos** [CosmosOS/Cosmos#1154]
Hello I would like to program an OS in Cosmos C # but I have no assembly references I've been using the latest Cosmos user kit (CosmosUserKit-20181010-vs2017)
I hope someone can help me
PS: I do not want to install the devkit

**Comment by quajak** [comment]
For what do you need the assembly reference? If you have any error message, can you please post it?

**Comment by robincosmos** [comment]
quajak ich will create a Gui for my OS when I try to install the devkit then comes this error:
 ERROR System.Exception

**Comment by robincosmos** [comment]
https://www.bilder-upload.eu/bild-f1f1c0-1556705055.png.html

**Comment by quajak** [comment]
Can you post the entire error log? Further what tutorial are you following?

**Comment by robincosmos** [comment]
https://www.bilder-upload.eu/bild-40eb7c-1556706990.png.html
I use Cosmos master for vs2017 and this error came

**Comment by quajak** [comment]
Can you post the entire log before this error as well please? There should be a button to copy the entire log and post it in a pastebin.

**Comment by robincosmos** [comment]
https://pastebin.com/khQn1qW5

**Comment by robincosmos** [comment]
I come from Germany 
and in the log was german sentences

**Comment by quajak** [comment]
It's ok I can speak German :) Can you check that no other program is currently accessing the files? That seems to be the most probable cause of the error `System.UnauthorizedAccessException: Der Zugriff auf den Pfad "Cosmos.Build.Tasks.dll" wurde verweigert.`

**Comment by robincosmos** [comment]
ok

**Comment by robincosmos** [comment]
i have another error

**Comment by robincosmos** [comment]
https://pastebin.com/NsdcrcWP

**Comment by quajak** [comment]
It seems to me as if you are installing the devkit right now, to install the userkit see https://www.gocosmos.org/docs/install/ you have to download the release version and run the exe.

**Comment by robincosmos** [comment]
I have installed the user kit at the last month and i would like change to the dev kit because i would like code a Gui for my os

**Comment by quajak** [comment]
ah ok, then you also have to pull IL2CPU, XSharp and Common see https://www.gocosmos.org/docs/install/ but do the same thing for https://github.com/CosmosOS/Common aswell

**Comment by robincosmos** [comment]
What do I have to do with it now?

**Comment by quajak** [comment]
if you have the other projects pulled, the build should run

**Comment by robincosmos** [comment]
Where do I have to recopy the folders?

**Comment by quajak** [comment]
The structure of the projects should be;
..\Cosmos\Cosmos\ 
..\Cosmos\IL2CPU\
..\Cosmos\XSharp\
..\Cosmos\Common\

**Comment by robincosmos** [comment]
I have the error https://pastebin.com/NsdcrcWP

**Comment by quajak** [comment]
It still says `Repos: IL2CPU, XSharp and Common not found.`, which means that you must not have correctly pulled the three github repos.

**Comment by robincosmos** [comment]
Can you send me a zip file?

**Comment by robincosmos** [comment]
https://pastebin.com/ubF5xwFF

**Comment by quajak** [comment]
Ok, a new error; `error MSB3644: Die Verweisassemblys für Framework ".NETFramework,Version=v4.7.2" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das SDK oder das Paket zur Festlegung von Zielversionen für die vorliegende Frameworkversion`. You have to install the .NETFramework SDK

**Comment by robincosmos** [comment]
Hello thanks its working but what can i do for the assemblyinfo.cs file
https://www.bilder-upload.eu/bild-9cb5af-1556801990.png.html

**Comment by quajak** [comment]
Why do you need it?

**Comment by charlesbetros** [comment]
You can still add AssemblyInfo.cs. Just add the attribute you need and leave the rest blank. It should get merged with the auto-generated one during build.

**Comment by robincosmos** [comment]
I Need it for the gui

**Comment by quajak** [comment]
What tutorial are you following?

**Comment by robincosmos** [comment]
https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI-The-basics

**Comment by robincosmos** [comment]
and the ring.user is also red i have import cosmos.common

**Comment by quajak** [comment]
Rings are currently not needed

**Comment by robincosmos** [comment]
So I do not need that [assembly: Ring (Ring.User)]?

**Comment by quajak** [comment]
yes

**Comment by robincosmos** [comment]
ok

**Comment by quajak** [comment]
Further most of the code there is out of date, look at https://github.com/CosmosOS/Cosmos/blob/master/Demos/CosmosGraphicSubsystem/Kernel.cs,

**Comment by quajak** [comment]
As your original issue is finished, I will be closing this issue.

**Comment by robincosmos** [comment]
Can i Code the gui with the Userkit?
