### ISSUE TITLE
Progress but errors 

### ISSUE THREAD

**Issue by Jennyhehe** [CosmosOS/Cosmos#1155]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installer

#### Expected Behaviour - What do you think that should happen?
Build -sln should run

#### Actual Behaviour - What unexpectedly happens?
Fails

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? Dev thanks to another user I got all the dependancies
![image](https://user-images.githubusercontent.com/50123570/57050435-2374a880-6c42-11e9-998e-811f34140123.jpg)
![image](https://user-images.githubusercontent.com/50123570/57050451-2cfe1080-6c42-11e9-826c-fadd328180fc.jpg)
![image](https://user-images.githubusercontent.com/50123570/57050468-4737ee80-6c42-11e9-8cfa-9dc4ba6aa40f.jpg)

**Comment by quajak** [comment]
The cosmos builder has a copy button, which you can use to copy the entire log. Could you please post the entire log in a pastebin?

**Comment by Jennyhehe** [comment]
========================================
    Builder Log
========================================


========================================
    Checking Dependencies
========================================

Repos: IL2CPU is installed.
Visual Studio 15.8+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.


========================================
    Restore - XSharp.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\Jiaku\Downloads\XSharp\XSharp.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\Jiaku\Downloads\XSharp\XSharp.sln


========================================
    Error
========================================
@quajak 
System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by Jennyhehe** [comment]
========================================
    Builder Log
========================================


========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.


========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\Jiaku\Desktop\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Skipping project "C:\Users\Jiaku\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Skipping project "C:\Users\Jiaku\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" because it was not found.
  Restore completed in 106.73 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 102.18 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 102.54 ms for C:\Users\Jiaku\Desktop\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 116.62 ms for C:\Users\Jiaku\Desktop\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 1.81 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 6.38 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 10.92 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 57.51 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 71.51 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 33.89 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 1.37 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 4.9 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 1.46 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 2.65 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 1.61 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 1.74 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 2.05 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 2.22 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 2.32 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 3.32 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 2.7 ms for C:\Users\Jiaku\Desktop\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 9.84 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 3.53 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 6.34 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 1.63 ms for C:\Users\Jiaku\Desktop\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 1.22 ms for C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 17.86 ms for C:\Users\Jiaku\Desktop\Cosmos-master\Tools\NASM\NASM.csproj.
  Restore completed in 16.55 ms for C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 4.79 ms for C:\Users\Jiaku\Desktop\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 1.28 ms for C:\Users\Jiaku\Desktop\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 1.44 ms for C:\Users\Jiaku\Desktop\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 1.67 ms for C:\Users\Jiaku\Desktop\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 2.91 ms for C:\Users\Jiaku\Desktop\XSharp\source\XSharp\XSharp.csproj.
  Restore completed in 6.17 ms for C:\Users\Jiaku\Desktop\IL2CPU\source\IL2CPU\IL2CPU.csproj.


========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\Jiaku\Desktop\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Deploy.Pixie -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Build.Common -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Debug.GDB -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.Debug.DebugConnectors -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Cosmos.Debug.Kernel -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.dll
  IL2CPU.Debug.Symbols -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.Deploy.USB -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Common -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Common.dll
  Cosmos.Core.DebugStub -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Core.DebugStub.dll
  Cosmos.TestRunner.TestController -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.TestRunner.TestController.dll
  IL2CPU.API -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\IL2CPU.API.dll
  Spruce -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Spruce.dll
  XSharp.x86 -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\XSharp.x86.dll
  VSPropertyPages -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  Cosmos.Debug.HyperVServer -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.VS.ProjectSystem -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.dll
  TheRingMaster -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\TheRingMaster.dll
  Cosmos.VS.Windows -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.VS.Windows.dll
  XSharp.Assembler -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\XSharp.Assembler.dll
  NASM -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\NASM.dll
  Cosmos.Core -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Core.dll
  Cosmos.HAL2 -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.HAL2.dll
  VSPropertyPages -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\VSPropertyPages.dll
  Cosmos.System2 -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.System2_Plugs.dll
  Restore completed in 94.33 ms for C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Cosmos.Debug.HyperVServer -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.Debug.Hosts -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.Build.Tasks -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Build.Tasks.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\Jiaku\Desktop\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.VS.DebugEngine -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.VS.ProjectSystem -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.VS.ProjectSystem.vsix
  XSharp -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\XSharp.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1879,5): warning : The referenced project 'C:\Users\Jiaku\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj' does not exist. [C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.VS.DebugEngine -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.VS.DebugEngine.vsix
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\Jiaku\Desktop\Cosmos-master\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
VTablesImpl.cs(4,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(1,14): error CS0234: The type or namespace name 'Debug' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?) [C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(8,24): error CS0246: The type or namespace name 'Debugger' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Jiaku\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]


========================================
    Error
========================================
@quajak 
here's the build log 
System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by quajak** [comment]
You have to rename the folder Cosmos-master to Cosmos

**Comment by charlesbetros** [comment]
If this is still a problem feel free to open a new issue.
