### ISSUE TITLE
Cosmos error in install plz help

### ISSUE THREAD

**Issue by RICKASHEYE** [CosmosOS/Cosmos#1156]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installer

#### Expected Behaviour - What do you think that should happen?
To install correctly but im too retarded to figure it out

#### Actual Behaviour - What unexpectedly happens?
doesnt work or install correctly

#### Reproduction - How did you get this error to appear?
pressed install-VS2017 and or replaced the files with new files and tried VS2019 and seem to hit the same error

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit from #1124 

LOG: https://pastebin.com/6U2JWcJw

**Comment by ProgrammerDim** [comment]
Can you get the tree of "C:\Users\rickasheye\Desktop\cosmos\"?
Go in cmd and type: 
`tree "C:\Users\rickasheye\Desktop\cosmos" /a /f`

**Comment by RICKASHEYE** [comment]
it was a problem with #1124 i already have fixed it by manually merging the new code with the newest commit
