### ISSUE TITLE
Error while running OS with Graphics

### ISSUE THREAD

**Issue by ProgrammerDim** [CosmosOS/Cosmos#1158]
#### Area of Cosmos - What area of Cosmos are we dealing with?
OS Debuging--Graphics

#### Expected Behaviour - What do you think that should happen?
Draw some lines

#### Actual Behaviour - What unexpectedly happens?
In VmWare it says 
![image](https://user-images.githubusercontent.com/49944888/57127266-824c3600-6d98-11e9-910d-a5f985d369aa.png)
and in Bochs it just restarts causing an infinite loop.

#### Reproduction - How did you get this error to appear?
Using below code and running in VmWare or Bochs

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit latest commit
###Code I'm using

```
using Cosmos.System.FileSystem;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel2
{
    public class Kernel : Sys.Kernel
    {
        Canvas screen = null;
        protected override void BeforeRun()
        {
            
            Console.WriteLine("<Cosmos booted successfully!>");
            screen = FullScreenCanvas.GetFullScreenCanvas();
            screen.Clear();
            screen.DrawLine(new Pen(Color.White), 10, 20, 40, 50);
        }

        protected override void Run()
        {
            screen.DrawLine(new Pen(Color.White), 10, 20, 10, 50);
        }
    }

}

```

**Comment by quajak** [comment]
There is a problem in master with graphics at the moment. Use the fix branch https://github.com/CosmosOS/Cosmos/pull/1124

**Comment by ProgrammerDim** [comment]
Why isn’t that branch merged?

**Comment by quajak** [comment]
As you can see by the discussion, there is a problem with appveyor timing out when running the graphics test. Until that is fixed, the branch will not be merged

**Comment by ProgrammerDim** [comment]
@quajak You can request a timeout inserance as seen [here](https://github.com/appveyor/ci/issues/517)

**Comment by quajak** [comment]
The timeout problem is a bug in the code, so it must be fixed by us.

**Comment by ProgrammerDim** [comment]
Okay then...
