### ISSUE TITLE
Cosmos property window issue

### ISSUE THREAD

**Issue by VisualDevelopment** [CosmosOS/Cosmos#1159]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio 2019 Extension

#### Expected Behaviour - What do you think that should happen?
Show the cosmos properties

#### Actual Behaviour - What unexpectedly happens?
It errors with `Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.`

#### Reproduction - How did you get this error to appear?
I went into the Cosmos project property window and went to either cosmos tabs.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Devkit master commit

**Comment by quajak** [comment]
It seems that https://github.com/CosmosOS/Cosmos/issues/1143 has not been fixed.

**Comment by VisualDevelopment** [comment]
The issue is fixed now
