### ISSUE TITLE
How to do something like Thread.Sleep?

### ISSUE THREAD

**Issue by EddyWilmer** [CosmosOS/Cosmos#116]

**Comment by mterwoord** [comment]
For now, pretty much the only way to do something like that is looping. (for (int i = 0; i < 1000*100;i++){;;;;;} and repeat that a bunch of times)...Other options are using the PIT but that one is not yet completely available in the current kernel..

**Comment by zdimension** [comment]
For seconds, you can use Cosmos.Core.RTC class, with a code like this : 
```csharp
public static void ForSeconds(int secNum)
{
    int StartSec = RTC.Second;
    int EndSec;
    if (StartSec + secNum > 59)
    {
        EndSec = 0;
    }
    else
    {
        EndSec = StartSec + secNum;
    }
    while (RTC.Second != EndSec)
    {
        // Loop round
    }
}
```
For milliseconds, as Matthijs said, you can use the PIT but it is not completely functional.
