### ISSUE TITLE
Cannot install Cosmos - Inno Setup not found

### ISSUE THREAD

**Issue by NinjaPaimen** [CosmosOS/Cosmos#1160]
So i tried to run installVS2019.bat and i have installed everything, but then it gives me an error:

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup not found.

========================================
    Error
========================================

Cosmos.Build.Builder.ViewModels.DependencyInstallationDialogViewModel.Dispose()
at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by ProgrammerDim** [comment]
Try instaling Inno Setup manually [here](http://www.jrsoftware.org/download.php/ispack.exe) and then try runnng the installer again

**Comment by NinjaPaimen** [comment]
> Try instaling Inno Setup manually [here](http://www.jrsoftware.org/download.php/ispack.exe) or check that you have the latest version(6.0.x) and then try running the installer again

I have it installed manually

**Comment by ProgrammerDim** [comment]
The error seems to be at `source/Cosmos.Build.Builder/ViewModels/DependencyInstallationDialogViewModel.cs`
Spesific at `Dispose()` Method(which only has 2 lines of code!)
OR
at `source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs` 
at `private async Task BuildAsync()`
I dont have any problem installing Cosmos using the latest master(are you using the latest??)
I dont know how to fix that issue maybe @quajak or @jp2masa knows.

**Comment by quajak** [comment]
Can you double check that you have Inno Setup version 6 installed and if yes check if the registry `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 6_is1` exists?

**Comment by NinjaPaimen** [comment]
> Can you double check that you have Inno Setup version 6 installed and if yes check if the registry `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 6_is1` exists?

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 6_is1 exists and i have Inno Setup Version 6 installed

**Comment by VisualDevelopment** [comment]
Something gives me the feeling that this is not the full build log...

**Comment by NinjaPaimen** [comment]
Okay so now it works I used the new commit.
