### ISSUE TITLE
Cant use timer

### ISSUE THREAD

**Issue by YaBoiMason** [CosmosOS/Cosmos#1161]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I think just plugs, but I'm not sure.

#### Expected Behaviour - What do you think that should happen?
Timers working

#### Actual Behaviour - What unexpectedly happens?
Timer plug doesn't exist so I can't use timers

#### Reproduction - How did you get this error to appear?
Using Timers

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit latest, C#

I'm trying to implement a time function into my OS, and so far I can't because lack of timers, so does anyone know a way I can use them? Thanks!

**Comment by BaRRaKudaRain** [comment]
Is project compiling? Maybe time library just not implemented...

-----Original Message-----

**Comment by quajak** [comment]
Threading and therefore timer has not yet been implemented. Once cosmos has threading, timers should be plugged.
