### ISSUE TITLE
COSMOS OS, Mouse Error

### ISSUE THREAD

**Issue by chathurax** [CosmosOS/Cosmos#1162]
`using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using Sys = Cosmos.System;
using SLOS.CDrivers;
using SLOS.System.Component;
using Cosmos.Hardware;
using Cosmos.Common;
using SLOS.System.Basic;

namespace SLOS
{
    public class Kernel : Sys.Kernel
    {
        private static int mx = 0;
        private static int my = 0;

        CProgressbar b;
        CLable lbl_welcome, lbl_cpy;
        

        protected override void BeforeRun()
        {
            Mouse m =new Mouse();
            m.Initialize(300, 200);

            CDisplay.bootVGA();
           

            b = new CProgressbar(100, 100);
            lbl_welcome = new CLable(110, 90, "Welcome C OS!",(int)ConsoleColor.Red);
            lbl_cpy = new CLable(10, 190, "Create By Chathura Wickramage!", (int)ConsoleColor.Blue);
            

        }
       

        protected override void Run()
        {
            
            CDisplay.drawPixel((uint)Sys.MouseManager.X, (uint)Sys.MouseManager.Y, 0);
            lbl_cpy.setText(Sys.MouseManager.X.ToString(), 0);
            CMouse.drawMouse();
            
            /*
            while (b.getValue() < 100)
            {
            
                b.stepUP();      
            
            }
           */

        }
    }
}
`
Output Error Is
Exception: System.ArgumentOutOfRangeException: Token 0x0a000095 is not valid in the scope of module Cosmos.Hardware.dll.	SLOS	C:\Users\Chathu\source\repos\CSLOS\SLOS\IL2CPU	1	

How Fix this?

**Comment by zarlo** [comment]
Cosmos.Hardware
is now Cosmos.HAL

**Comment by chathurax** [comment]
Oh,  thankx! How i use for add mouse?

**Comment by VisualDevelopment** [comment]
Use the new MouseManager

**Comment by quajak** [comment]
The mouse should be added automatically by the mouse manager. Simply intialize the mouse manager with
```
MouseManager.ScreenWidth = Columns;
MouseManager.ScreenHeight = Rows;
```
and the get co-ordinates with `MouseManager.X` and `MouseManager.Y`

**Comment by chathurax** [comment]
Thankx();
