### ISSUE TITLE
Debug executable specified in the debug profile not found.

### ISSUE THREAD

**Issue by shreyas13579** [CosmosOS/Cosmos#1163]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I am testing cosmos out and I am trying to run the basic program generated by cosmos. However i am having this error, telling me about "Debug executable specified in the debug profile not found."

#### Expected Behaviour - What do you think that should happen?
Cosmos should open up a virtual environment to run my program/OS.

#### Actual Behaviour - What unexpectedly happens?
It throws an error about "Debug executable specified in debug profile not found"

#### Reproduction - How did you get this error to appear?
I just clicked the green button in Visual Studio 2017 having my project name and the error showed up.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit

This is what the error looks like:

![error_cosmos](https://user-images.githubusercontent.com/43932047/57355388-878bf500-718b-11e9-8ab4-212abba7e852.png)

**Comment by quajak** [comment]
Visual Studio 2017 is no longer supported, you have to use an older version of the user kit or use Visual Studio 2019.
