### ISSUE TITLE
idk what title to put here, i get 4 errors in vs2019

### ISSUE THREAD

**Issue by NinjaPaimen** [CosmosOS/Cosmos#1164]
So im trying to do new os and when i open the project, i have these errors

Error		NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.	TestOS1	D:\Samuel\NinjaPaimen\Visual Studio\Cosmos\TestOS1\TestOS1\TestOS1.csproj	1	
Error	NU1101	Unable to find package Cosmos.System2. No packages exist with this id in source(s): discord.net, Microsoft Visual Studio Offline Packages, nuget.org	TestOS1	D:\Samuel\NinjaPaimen\Visual Studio\Cosmos\TestOS1\TestOS1\TestOS1.csproj	1	
Error	NU1101	Unable to find package Cosmos.Build. No packages exist with this id in source(s): discord.net, Microsoft Visual Studio Offline Packages, nuget.org	TestOS1	D:\Samuel\NinjaPaimen\Visual Studio\Cosmos\TestOS1\TestOS1\TestOS1.csproj	1	
Error	NU1101	Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): discord.net, Microsoft Visual Studio Offline Packages, nuget.org	TestOS1	D:\Samuel\NinjaPaimen\Visual Studio\Cosmos\TestOS1\TestOS1\TestOS1.csproj	1

**Comment by quajak** [comment]
Are you using visual studio 2019?

**Comment by quajak** [comment]
When you look at the nuget sources, do you have one called Cosmos Local Package Feed?

**Comment by NinjaPaimen** [comment]
> When you look at the nuget sources, do you have one called Cosmos Local Package Feed?

umm... no
Should I have it?

**Comment by quajak** [comment]
Yes, can you try setting it manually to `C:\Users\[User]\AppData\Roaming\Cosmos User Kit\packages\` ? It might work or there is some underlying problem I am not aware of.

**Comment by NinjaPaimen** [comment]
> Yes, can you try setting it manually to `C:\Users\[User]\AppData\Roaming\Cosmos User Kit\packages\` ? It might work or there is some underlying problem I am not aware of.

There is one problem. The directory C:\Users\[User]\AppData\Roaming\Cosmos User Kit does not exist.

**Comment by VisualDevelopment** [comment]
you're supposed to replace [User] with your username

**Comment by NinjaPaimen** [comment]
> you're supposed to replace [User] with your username

yes i did that but i just copied it for the comment

**Comment by quajak** [comment]
Dos it exist under Users\Admin ?

**Comment by NinjaPaimen** [comment]
Oh yeah i found it

**Comment by quajak** [comment]
Ok, you have to re-install the user kit. There is a prompt to chose the installation folder for the comos user kit, can you please select the appdata/roaming from the user you are activly using?

**Comment by NinjaPaimen** [comment]
> Ok, you have to re-install the user kit. There is a prompt to chose the installation folder for the comos user kit, can you please select the appdata/roaming from the user you are activly using?

When i run install-vs2019.bat it builds and then the installer opens and installs it to somewhere. There was no prompt to choose the path

**Comment by quajak** [comment]
Can you run the userkit installer to set the correct installation path and then reurn the devkit?

**Comment by NinjaPaimen** [comment]
> Can you run the userkit installer to set the correct installation path and then rerun the devkit?

Maybe, but when i run userkit-install.bat it says Looking for MSBuild
MSBuild not found. Please make sure Visual Studio 15.2+ is installed.
Press any key to continue . . .
I am using VS 2019

**Comment by NinjaPaimen** [comment]
> > Can you run the userkit installer to set the correct installation path and then rerun the devkit?
> 
> Maybe, but when i run userkit-install.bat it says Looking for MSBuild
> MSBuild not found. Please make sure Visual Studio 15.2+ is installed.
> Press any key to continue . . .
> I am using VS 2019

oh wait i figured it out

i edited the .bat to vs2109

**Comment by NinjaPaimen** [comment]
@echo off

install-VS2019 -USERKIT %*

**Comment by NinjaPaimen** [comment]
It works now, thanks for the help!
