### ISSUE TITLE
"Program does not contain a static 'Main' method suitable for an entry point" error.

### ISSUE THREAD

**Issue by shreyas13579** [CosmosOS/Cosmos#1168]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I am trying out Cosmos for making an "OS". I am using Cosmos UserKit20190508 with Visual Studio 2019. I previously had few error which were resolved with the help of NuGet Packages. However, another error is popping out demanding a ``Main()`` method.

#### Expected Behaviour - What do you think that should happen?
OS emulator should open and the code should run in it as an OS.

#### Actual Behaviour - What unexpectedly happens?
I am getting an error in the Error List demanding a ``Main()`` method for "suitable entry point".

#### Reproduction - How did you get this error to appear?
I normally clicked the green button with "Cosmos" written on it. And the error appeared in the Error List.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using Cosmos UserKit20190508 with Visual Studio 2019.

#### Error Code and Error
**Error Code: CS5001**
**Error Description: ``Program does not contain a static 'Main' method suitable for an entry point``**

This is the error (in the Error List dialog box at the bottom of the screen):
![Main()_cosmos](https://user-images.githubusercontent.com/43932047/57720648-ebd51a00-769f-11e9-95c1-bbec6495ebff.png)

**How do I resolve this error?**

**Comment by NikiGamePlay** [comment]
Wasn't able to reproduce on Visual Studio 2019 16.0.3 fresh install with cosmos user kit 20190508. I had the same error but after 10 seconds it disappeared automatically.

**Comment by shreyas13579** [comment]
@NikiGamePlay Were you able to run it successfully?

**Comment by quajak** [comment]
Is the output type set to `Class Library`?

**Comment by shreyas13579** [comment]
@quajak It was first set to ``Class Library``, but it was giving error. I searched for help and set it to ``Console Application``.

**Comment by quajak** [comment]
It should be set Class Library

**Comment by shreyas13579** [comment]
@quajak I set it to ``Class Library`` from ``Console Application`` and Release Configuration to ``Debug`` from ``Release``. The bar at the bottom says "Build successful.", but I am getting another error saying ``VMWare not found``. I guess, I will have to get it now. Thanks for the help, @quajak and @NikiGamePlay .

:)
