### ISSUE TITLE
IL2CPU requesting a plug i can't create

### ISSUE THREAD

**Issue by mcneb10** [CosmosOS/Cosmos#1169]
Keeps saying it needs a plug for: System.Int64  System.Threading.Interlocked.Exchange(&System.Int64, System.Int64).   Called from :
System.IO.UnmanagedMemoryStream::Int32 Read(Byte[], Int32, Int32)
System.IO.Stream::Int32 Read(Byte[], Int32, Int32)

**Comment by quajak** [comment]
Are you using the devkit or userkit? What is the problem with creating the plug? The plug should be added to InterlockedImpl.cs.

**Comment by mcneb10** [comment]
I am using the UserKit

**Comment by mcneb10** [comment]
The particular method is an external function

**Comment by quajak** [comment]
You either have to remove the code which is calling the external function, or switch to the devkit and implement the plug.

**Comment by mcneb10** [comment]
it doesn't say what triggered it
Here is what the console says:
1>------ Build started: Project: DOGE, Configuration: w Any CPU ------
1>DOGE -> C:\Users\mcneb10\source\repos\DOGE\DOGE\bin\w\netcoreapp2.0\cosmos\DOGE.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\mcneb10\source\repos\DOGE\DOGE\bin\w\netcoreapp2.0\cosmos\DOGE.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Int64  System.Threading.Interlocked.Exchange(&System.Int64, System.Int64).
1>  Called from :
1>System.IO.UnmanagedMemoryStream::Int32 Read(Byte[], Int32, Int32)
1>System.IO.Stream::Int32 Read(Byte[], Int32, Int32)
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 616
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 769
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 263
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:05.2826597
1>Done building project "DOGE.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
