### ISSUE TITLE
"Unable to start program" error. Problem while setting up VMWare Player for Cosmos program.

### ISSUE THREAD

**Issue by shreyas13579** [CosmosOS/Cosmos#1170]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I am using Cosmos UserKit 20190508 with Visual Studio 2019. I previously had some errors related to Cosmos and Visual Studio, but they were resolved. However on running the Cosmos generated program, two error boxes appear saying it has no virtual machine environment to run. For this, I installed VMWare Player (as it was an option in Project Settings). However, I don't know how to set it up for Cosmos.

#### Expected Behaviour - What do you think that should happen?
A Virtual Machine Environment Window / OS Emulator Windows (VMWare Player, to be specific) should open up and run my OS.

#### Actual Behaviour - What unexpectedly happens?
I get two Error Windows popping up, one containing some weird error, which I am unable to understand. The other Error Window shows an error related to Virtual Machine Environment and VMWare Player.

#### Reproduction - How did you get this error to appear?
I clicked the green button which had "Cosmos" written on it.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using Cosmos UserKit 20190508 and Visual Studio 2019.

#### Error Boxes:
**First Box that pops up:**
![new_comos_error](https://user-images.githubusercontent.com/43932047/57829663-52a42180-77cd-11e9-8042-d50b5f6eb469.png)

**Second Box that pops up after closing the first box:**
![new_cosmos_error_1](https://user-images.githubusercontent.com/43932047/57829686-664f8800-77cd-11e9-8837-4377e36af89c.png)

**_What do I do to resolve this and set up VMWare Player for Cosmos?_**

**Comment by mcneb10** [comment]
The first error is saying that it can’t find a namespace System.Reflection.TypeExtensions. You might be missing some SDKs

**Comment by mcneb10** [comment]
Try reinstalling cosmos

**Comment by shreyas13579** [comment]
@mcneb10 Reinstalling did not work.

What do you think, @quajak ?

**Comment by quajak** [comment]
I dont know anything about this. Maybe try installing the nuget package https://www.nuget.org/packages/System.Reflection.TypeExtensions/ I think @jp2masa has a better idea of what is going on.

**Comment by shreyas13579** [comment]
@quajak @mcneb10 , I tried installing ``System.Reflection.TypeExtensions`` version 4.0.0. The blue bar at the bottom says, ``Build Succeeded``, but it's still throwing the two errors that I mentioned earlier in this issue.

![nuget _pacman](https://user-images.githubusercontent.com/43932047/57966766-ed3e6500-7973-11e9-9a25-0d8b130968d2.png)


**The Errors:**

![build_successful_error](https://user-images.githubusercontent.com/43932047/57966784-3ee6ef80-7974-11e9-87c8-97dd336f9cef.png)

![error_2](https://user-images.githubusercontent.com/43932047/57966786-460dfd80-7974-11e9-8f77-b5082977a243.png)

**_Can you help, @jp2masa ?_**

**Comment by jp2masa** [comment]
I think we need to add binding redirects for `System.Reflection.TypeExtensions`, I'll take a look.

**Comment by jp2masa** [comment]
Actually it seems that the assembly is missing. I pushed a fix.

**Comment by shreyas13579** [comment]
@jp2masa What should I do on my side?

**Comment by quajak** [comment]
Can you install the devkit?

**Comment by shreyas13579** [comment]
@quajak Okay, I will try installing the Dev Kit. But, would that mean that I will have to uninstall the User Kit and also reinstall the NuGet Packages?

**Comment by shreyas13579** [comment]
@quajak The documentation for Dev Kit says that I need to run the .bat file to install. I see two .bat files in the repository. Which one should I run?

![bat_installer](https://user-images.githubusercontent.com/43932047/57969609-82eaec00-7996-11e9-8dc4-36395c8cc128.png)

**Comment by quajak** [comment]
The devkit build will automatically overwrite the user kit installation. You should run `install-VS2019.bat`

**Comment by shreyas13579** [comment]
@quajak I am out of town for a few days. I will try out the Dev Kit and will let you know when I am back.

**Comment by shreyas13579** [comment]
Hello @quajak , @jp2masa ! I am back in town. As instructed, I cloned the repository and ran ``install-VS2019.bat`` as Administrator and also with my Anti-Virus disabled. However, the .bat file was throwing an error. So I uninstalled the UserKit and tried installing DevKit again. However, the .bat file was still throwing the same error.
Take a look at it:
![cosmos-error](https://user-images.githubusercontent.com/43932047/58365760-74488b80-7ee6-11e9-8bc5-59b3f2f563ea.png)


**At the very beginning, I had run the .bat file without Administrator rights. So I cancelled the operation. Could this be the cause for the error? (On running it as Administrator, the operation which I had cancelled executed successfully, the next operation was throwing the error).**

**Comment by quajak** [comment]
Did you clone all four repositories? Can you please rename the cosmos git directory to `Cosmos`.

**Comment by shreyas13579** [comment]
@quajak Which other repositories? Can you please instruct me?

**Comment by quajak** [comment]
You also have to pull IL2CPU, XSharp and Common see https://www.gocosmos.org/docs/install/ but do the same thing for https://github.com/CosmosOS/Common aswell.

**Comment by shreyas13579** [comment]
@quajak Do I have to put the folder for "Common" repository in the same folder where the other three are placed?

**Comment by shreyas13579** [comment]
Hello @quajak ! I followed the given instructions and placed the four repositories in the same directory. However, on running ``install-VS2019.bat``, I am still getting the same error that I mentioned previously.

**The cloned repositories in the same directory:**
![directory_cosmos](https://user-images.githubusercontent.com/43932047/58370501-efc92d80-7f24-11e9-8b4a-e519a241c5de.png)

**The Error Window:**
![same_error_cosmos](https://user-images.githubusercontent.com/43932047/58370486-d0ca9b80-7f24-11e9-9857-b4b96b330153.png)

**_What should I do now?_**

**Comment by shreyas13579** [comment]
@quajak Should I try installing older releases of Cosmos UserKit?

**Comment by disks86** [comment]
I had a similar issue when trying to run the bat as administrator. Try opening an instance of CMD or powershell as administrator and navigate to that folder (in the terminal). Now from the terminal execute the bat file.

**Comment by disks86** [comment]
@quajak it seems like a waste to do a full PR but if you add the following line in the install bat after the echo it will allow users to double-click on the bat and have it run. All it does is set the working directory to the location of the bat file.

cd /D "%~dp0"

**Comment by shreyas13579** [comment]
@quajak @disks86 @jp2masa I have done what disks86 had asked me to do, and fortunately Cosmos compiled. I created a new Cosmos Project and it compiled successfully. However, VMware Player threw this error:
![vmware_error](https://user-images.githubusercontent.com/43932047/58694851-a0b24b00-83b1-11e9-9495-283be2e93ecb.png)

**_What should I do next?_**

**Comment by disks86** [comment]
Looks like the virtualization support on your machine is disabled or on use by another platform. Check your bios and make sure that virtualization is turned on. If it is but you still get this make sure you don't have any other hypervisors running.

**Comment by shreyas13579** [comment]
@disks86 @quajak @jp2masa @mcneb10 , It works now. Thank you all for help.

![cosmos_works](https://user-images.githubusercontent.com/43932047/58745895-c48a9500-8474-11e9-9a69-11f696e20fad.png)


**:)**
