### ISSUE TITLE
I get errors when i try to build

### ISSUE THREAD

**Issue by NinjaPaimen** [CosmosOS/Cosmos#1171]
When i click the run button in vs2019 i get this pop-up

![error2](https://user-images.githubusercontent.com/29013400/57861979-3ff71000-7800-11e9-8f3d-603ac6592300.PNG)

**Comment by quajak** [comment]
Can you confirm that the Cosmos Debug Engine extension is correctly installed? You should be able to find it under Manage Extensions.

**Comment by NinjaPaimen** [comment]
> Can you confirm that the Cosmos Debug Engine extension is correctly installed? You should be able to find it under Manage Extensions.

There is only Cosmos Project System

**Comment by NinjaPaimen** [comment]
What do i do now?

**Comment by quajak** [comment]
Go under /AppData/Cosmos User Kit/VSIX and manually run Cosmos.VS.DebugEngine.vsix

**Comment by NinjaPaimen** [comment]
It works now. Thx for help
