### ISSUE TITLE
Mouse doesn't work in code

### ISSUE THREAD

**Issue by gertpert** [CosmosOS/Cosmos#1172]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.HAl
Cosmos.Core.IOGroup;

#### Expected Behaviour - What do you think that should happen?
to use Mouse.Y Mouse.x and Mouse.ifclicked in a area

#### Actual Behaviour - What unexpectedly happens?
It doesn't work

#### Reproduction - How did you get this error to appear?
When i wanded  to locate where the mouse is and create a crosshair for the mouse.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
the latest version of Cosmos os with visual studio 2019 support

**Comment by JSPH2** [comment]
How did you fix this? Same issue.

**Comment by gertpert** [comment]
i created a temporary fix with 
`if(x == 0 || y == 0)
            {
                x = 512;
                y = 384;
            }
`
