### ISSUE TITLE
Cosmos os Error Mouse.

### ISSUE THREAD

**Issue by gertpert** [CosmosOS/Cosmos#1174]
I get a error with the mouse.
This is my code:

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.Core;
using Cosmos.Common;
using Cosmos.System.Graphics;
using System.Drawing;
using Cosmos.HAL.Drivers;

namespace voiceassistantos
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        
        public static Cosmos.HAL.VGAScreen screen = new Cosmos.HAL.VGAScreen();
        private uint ux = 1024;
        private uint uy = 768;
        private int x = 512;
        private int y = 384;
      
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Let's go in Graphic Mode");
            canvas = FullScreenCanvas.GetFullScreenCanvas();

            canvas.Clear(Color.Blue);
            Sys.MouseManager.ScreenHeight = uy;
            Sys.MouseManager.ScreenWidth = ux;

            // A red Point 
            Pen pen = new Pen(Color.Black);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 30, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 130, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 220, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 320, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 420, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 520, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 620, 80, 60);
        }

        protected override void Run()
        {
            mDebugger.Send("x: " + Sys.MouseManager.ScreenWidth + "y: " + Sys.MouseManager.ScreenHeight);

            x = Convert.ToInt32(Sys.MouseManager.X);
            y = Convert.ToInt32(Sys.MouseManager.Y);

            mDebugger.Send("mouse x: " + x + "mouse y: " + y);
            
            Pen pen = new Pen(Color.Red);
            canvas.DrawCircle(pen, x, y, 5);

        }

    }
}

when i remove the 
Sys.MouseManager.ScreenHeight = uy;
Sys.MouseManager.ScreenWidth = ux;
it works. what could be the problem?

**Comment by quajak** [comment]
What is the error/exception when you include the two lines?

**Comment by gertpert** [comment]
Wait I said it wrong. My VM will start and close immediately

**Comment by gertpert** [comment]
If it include the two lines

**Comment by quajak** [comment]
I tried running your code and could not find any problem with the two lines. The problem right now is that `canvas.DrawCircle(pen, x, y, 5);` throws when x = 0 or y=0 as the co-ordinates are out of bounds. When that problem is fixed, the code runs fine for me.
