### ISSUE TITLE
Avalonia a a primary GUI framework

### ISSUE THREAD

**Issue by xperiandri** [CosmosOS/Cosmos#1177]
Is there any popular framework planed as a primary GUI platform?
Can https://github.com/AvaloniaUI/Avalonia be used?

**Comment by Project-Magenta** [comment]
No GUI libraries are currently supported by Cosmos. See [Cosmos Graphics Subsystem](https://www.gocosmos.org/docs/cosmos-graphic-subsystem/) to learn how to draw to the screen.
