### ISSUE TITLE
Cosmos Mouse Draw Continuously

### ISSUE THREAD

**Issue by chathurax** [CosmosOS/Cosmos#1178]
I draw Mouse On Canvas in My COSMOS OS.
But it draw every where. Cannot use `canvas.clear();` It very slow.
What is Proper Efficient way Draw mouse on Canvas?

**Comment by Project-Magenta** [comment]
the "proper efficent way" is to use `canvas.clear()`.

**Comment by AbhinavAtrishi** [comment]
As an alternative you can also use the `canvas.DrawFilledRectangle()` function to only erase the rectangle bounding the mouse, this will work faster.

**Comment by quajak** [comment]
The new double buffering canvases should allow for non-flickering screens even when using clear.
