### ISSUE TITLE
install-VS2019 msbould not found but it there

### ISSUE THREAD

**Issue by Soulcrafter** [CosmosOS/Cosmos#1179]
#### Area of Cosmos - What area of Cosmos are we dealing with?

install-VS2019.bat
#### Expected Behaviour - What do you think that should happen?

fine my MSbuld and let me build the project
#### Actual Behaviour - What unexpectedly happens?

MSBuild not found, please make sure visual studio 16.0+ is installed
#### Reproduction - How did you get this error to appear?

I install everything it told me at https://www.gocosmos.org/docs/install/ for the dev kit.
I have tried everything I know, I reinstall visual studio 2017 and add everything again. I know I have MSBuild there I look in the folder. 
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I am using the dev kit, the newest master branch

**Comment by EuropaFantasy** [comment]
Same Error
