### ISSUE TITLE
Stuck on kit builder installing Repos

### ISSUE THREAD

**Issue by Soulcrafter** [CosmosOS/Cosmos#1180]
#### Area of Cosmos - What area of Cosmos are we dealing with?

kit builder
#### Expected Behaviour - What do you think that should happen?

everything should work and cosmos.sin should open
#### Reproduction - How did you get this error to appear?

I get to the cosmos kit builder and let it run for 3 hours, and sill installing repos: IL2CPU, XSHARP and COMMON... I haven't got anywhere else.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I am using the Dev Kit, I am using the master branch newest.
any help would be helpful.

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common not found.

========================================
    Error
========================================

System.Exception: Dependency installation failed! Dependency name: Repos: IL2CPU, XSharp and Common
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in D:\alex-stuff\workspace-save programs\Visual studio workarea\source\Cosmos\Cosmos\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 120

If I click cancel I also get 

   at Cosmos.Build.Builder.ViewModels.DependencyInstallationDialogViewModel.Dispose() in D:\alex-stuff\workspace-save programs\Visual studio workarea\source\Cosmos\Cosmos\source\Cosmos.Build.Builder\ViewModels\DependencyInstallationDialogViewModel.cs:line 73

**Comment by ProgrammerDim** [comment]
Have you cloned the other 3 repositories([XSharp](https://github.com/CosmosOS/XSharp),[IL2CPU](https://github.com/CosmosOS/IL2CPU),[Common](https://github.com/CosmosOS/Common))?

**Comment by Soulcrafter** [comment]
yes, i did it the way it told me.

**Comment by Soulcrafter** [comment]
well now my error is inno setup failed to install

**Comment by disks86** [comment]
@Soulcrafter do you have Inno Quick Start Pack installed? http://www.jrsoftware.org/isdl.php#qsp

**Comment by Soulcrafter** [comment]
yes i do

**Comment by Soulcrafter** [comment]
@disks86 yes i do

**Comment by Soulcrafter** [comment]
good news so when installing inno you have to use install it for all users. well then thanks for the help XD.
