### ISSUE TITLE
Stuck on waiting for debugger connection.

### ISSUE THREAD

**Issue by Mantaraix** [CosmosOS/Cosmos#1182]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugging

#### Expected Behaviour - What do you think that should happen?
It to continue after inserting password

#### Actual Behaviour - What unexpectedly happens?
It just gets stuck on the debugger connection

#### Reproduction - How did you get this error to appear?
I was on VMware after building COSMOS and then it gave me a warning saying that my USB devices could be used
Then COSMOS just crashed and VMware said you could restart it or shut it down so I restarted it and now COSMOS is stuck on 'Waiting for debugger connection.'
After restarting COSMOS Visual Studio crashed.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit

**Comment by disks86** [comment]
You mention inserting a password do you mean a Windows user account control (UAC) prompt? Are you an administrator on your own machine or is it locked down?

**Comment by Mantaraix** [comment]
My OS is password protected; meaning that you have to type a password and it will then allow it to run.

**Comment by disks86** [comment]
I have a feeling this is an issue with security. Can you try running visual studio as administrator?

**Comment by mterwoord** [comment]
Are you running within the VS debugger? Or manually in VM or physical
machine?


Op wo 5 jun. 2019 om 18:16 schreef Christopher Schaefer <
notifications@github.com>:

**Comment by asiawin** [comment]
![image](https://user-images.githubusercontent.com/52355164/74238268-76b07700-4cfb-11ea-80de-58f2e4083060.png)
### ******This is the solution for this!*******

Look at the image.
If you want to stop your os showing " Waiting for debugger " message, follow these steps:

- First, open your project.
- Next, right-click the solution name/root of the solution tree.
- Then, click unload project.
- When the project is unloaded, right-click it and Edit <Your-project-name>.cosmos
- Then, find <DebugEnabled> Element and set it to false!

That's it!
It will not show waiting for debugger again.
I'll hope this works for you!
For more tips and tricks, visit [codebasha.cf](http://codebasha.cf/)

**Comment by kilickerem066** [comment]
> ![image](https://user-images.githubusercontent.com/52355164/74238268-76b07700-4cfb-11ea-80de-58f2e4083060.png)
> 
> ### ******This is the solution for this!*******
> Look at the image.
> If you want to stop your os showing " Waiting for debugger " message, follow these steps:
> 
> * First, open your project.
> * Next, right-click the solution name/root of the solution tree.
> * Then, click unload project.
> * When the project is unloaded, right-click it and Edit .cosmos
> * Then, find  Element and set it to false!
> 
> That's it!
> It will not show waiting for debugger again.
> I'll hope this works for you!
> For more tips and tricks, visit [codebasha.cf](http://codebasha.cf/)

Thanks, dude.

**Comment by asiawin** [comment]
**@kilickerem066 Thanks! And why are you making an OS with C#? Try making an OS with C or C++. Cosmos converts the compiled IL code to x86 Assembly, which is** _**HUGE! When you make an OS with C or C++, it will be very small.**_  
_**The result of the following C# code is a massive 50.3 MB Assembly file.**_

```c#
namespace MyOS{
	class Main {
		public void main(){
		// Nothing.
		}
	}
}
```

Whereas the result of the following C code is a small 935 Bytes!

```c
#include <kernel.S>

void main(){
	// Nothing.
}
```

I hope this reply won't hurt you, I only said this for knowledge. And if you are making an OS for timepass or as a hobby project, COSMOS is best for you!

Also, visit my [forum](http://codersring.rf.gd/forum) and [blog.](http://codersring.rf.gd/wordpress) If you have time, you can also view some projects made by me at my [Organisation at Github](http://github.com/OpenCreeck)

**Comment by kilickerem066** [comment]
> **@kilickerem066 Thanks! And why are you making an OS with C#? Try making an OS with C or C++. Cosmos converts the compiled IL code to x86 Assembly, which is** _**HUGE! When you make an OS with C or C++, it will be very small.**_
> _**The result of the following C# code is a massive 50.3 MB Assembly file.**_
> 
> ```cs
> namespace MyOS{
> 	class Main {
> 		public void main(){
> 		// Nothing.
> 		}
> 	}
> }
> ```
> 
> Whereas the result of the following C code is a small 935 Bytes!
> 
> ```c
> #include <kernel.S>
> 
> void main(){
> 	// Nothing.
> }
> ```
> 
> I hope this reply won't hurt you, I only said this for knowledge. And if you are making an OS for timepass or as a hobby project, COSMOS is best for you!
> 
> Also, visit my [forum](http://codersring.rf.gd/forum) and [blog.](http://codersring.rf.gd/wordpress) If you have time, you can also view some projects made by me at my [Organisation at Github](https://github.com/OpenCreeck)

Good idea, but how? I have 3 options: C#, F# and VB.NET.

**Comment by Project-Magenta** [comment]
Creating an operating system in C++ or C requires a lot of manual work, and you do not use COSMOS.

**Comment by asiawin** [comment]
Yeah! I also started from there! I have some tutorial videos on how to nake OS from scratch on my YouTube channel. Check out my channel! -> https://www.youtube.com/channel/UCKWKXQOMdb6xEJ1Gx7-340g?view_as=subscriber

**Comment by kilickerem066** [comment]
@asiawin Thanks, and I also subscribed your channel

**Comment by kilickerem066** [comment]
@asiawin But which video? There are 18 videos containing Windows 10 installation

**Comment by asiawin** [comment]
@kilickerem066 Videos coming on the way! Keep subscribed to receive a notification when I post the OS tutorial series. I will first post a \`Simple Pyramid program in C++ \` then the OS tutorial series. Stay tuned.!

**Comment by asiawin** [comment]
@kilickerem066 Videos coming on the way! Keep subscribed to receive a notification when I post the OS tutorial series. I will first post a \`Simple Pyramid program in C++ \` then the OS tutorial series. Stay tuned.!

**Comment by kilickerem066** [comment]
Okay

**Comment by fy1vo51** [comment]
Don't you forget to put "False" on <VMware_DebugEnabled>???

**Comment by asiawin** [comment]
@fy1vo51 I did that. I'm not a c# os developer anymore. I am now making an OS with C and C++, its more easy than C#
