### ISSUE TITLE
Mouse code not functioning.

### ISSUE THREAD

**Issue by JSPH2** [CosmosOS/Cosmos#1183]
``
void GuiCycle() {
            var mx = Sys.MouseManager.Y;
            var my = Sys.MouseManager.X;
            pen.Color = System.Drawing.Color.White;
            canvas.DrawLine(pen, mx, my, mx+5, my+5);
}
``

GuiCycle() is called by Run().

What should happen is that I should have a white line on screen that I can move with the mouse.

What am I doing that is causing this not to happen?

**Comment by quajak** [comment]
What is happening? Are you getting an error or is something unexpected happening?
