### ISSUE TITLE
Cosmos can't build XSharp

### ISSUE THREAD

**Issue by ProgrammerDim** [CosmosOS/Cosmos#1184]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Install(Build of XSharp)

#### Expected Behaviour - What do you think that should happen?
Build XSharp normally

#### Actual Behaviour - What unexpectedly happens?
Due to recent changes in XSharp file/folder tree some project files can't be found
[LOG](https://pastebin.com/raw/vWNv3GnF)
#### Reproduction - How did you get this error to appear?
Installing Cosmos

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos: 42b7f4719ece9d8cef5f3c005afdb9202e14a48d
IL2CPU: CosmosOS/IL2CPU/master/7f761df441571169bd1b53fd9e901d681b952b89
X# : CosmosOS/XSharp/master/8542b7f03d824692c4cfce2d800c9ce4eecd8b52

The problems seem be caused by recent XSharp commits that changed the file/folder tree

**Comment by evilexecutable** [comment]
As a temporary measure, you can go in to your XSharp folder and run 
`git checkout 586b46a444`
Which will return the expected folder structure.

**Comment by charlesbetros** [comment]
Fixed #1190
