### ISSUE TITLE
Cannot write to file

### ISSUE THREAD

**Issue by Lorinet** [CosmosOS/Cosmos#1188]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Write to file with File.WriteAllBytes

#### Expected Behaviour - What do you think that should happen?
Write the file

#### Actual Behaviour - What unexpectedly happens?
Crashes VMware with 'Specified argument was out of range', Parameter name: aFirstCluster

#### Reproduction - How did you get this error to appear?
This issue does not happen with the default Filesystem.VMDK, only with a new one formatted with FAT32.

`File.WriteAllBytes(@"0:\Neutrino\COMMAND.LEX", CommandFile);`

`byte[] CommandFile = new byte[] { 0x4E, 0x45, 0x58, 0x20, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ........ };`

The directory was created earlier with `Directory.CreateDirectory(@"0:\Neutrino");`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190508
![image](https://user-images.githubusercontent.com/24529247/59367864-a6ab1300-8d45-11e9-9b51-12743cba476f.png)

**Comment by JSPH2** [comment]
I'm having the same issue.

**Comment by sudopigeek** [comment]
I had the same problem; it took me a while to figure it out.  It is caused because you are trying to access a file that is not in the root (0:\).  Your file is in folder "Neutrino".  Change the filepath to "0:\COMMAND.LEX" instead of "0:\Neutrino\COMMAND.LEX".

**Comment by CaydendW** [comment]
If the error still exists: Try change the Virtual Machine controller from IDE to SATA or SCSI.
