### ISSUE TITLE
DevKit installer error

### ISSUE THREAD

**Issue by Lorinet** [CosmosOS/Cosmos#1189]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installation of DevKit

#### Expected Behaviour - What do you think that should happen?
It should install DevKit with no errors

#### Actual Behaviour - What unexpectedly happens?
Installation fails with `System.Exception: The process failed to execute`
By looking into the log, it seems it can't find XSharp.csproj, XSharp.Assembler.csproj and XSharp.x86.csproj
I cloned the Cosmos, XSharp, Common and IL2CPU repos with GitHub Desktop, all in the same folder.

#### Reproduction - How did you get this error to appear?
Installing DevKit with `install-vs2019.bat`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit

#### Full build log:

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "I:\Dev\Cosmos Dev Kit\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(265,5): error MSB3202: The project file "I:\Dev\Cosmos Dev Kit\XSharp\source\XSharp\XSharp.csproj" was not found. [I:\Dev\Cosmos Dev Kit\Cosmos\Build.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(265,5): error MSB3202: The project file "I:\Dev\Cosmos Dev Kit\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj" was not found. [I:\Dev\Cosmos Dev Kit\Cosmos\Build.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(265,5): error MSB3202: The project file "I:\Dev\Cosmos Dev Kit\XSharp\source\XSharp.x86\XSharp.x86.csproj" was not found. [I:\Dev\Cosmos Dev Kit\Cosmos\Build.sln]

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in I:\Dev\Cosmos Dev Kit\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in I:\Dev\Cosmos Dev Kit\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in I:\Dev\Cosmos Dev Kit\Cosmos\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

**Comment by zenith391** [comment]
I found it was caused due to the recent XSharp update. Which merge the assemblies, althought Cosmos builder isn't updated for this change. The best solution is to clone from a commit before this one, and put it in the XSharp folder

**Comment by wessupermare** [comment]
Temporary fix at #1184 works on my machine.

**Comment by charlesbetros** [comment]
Fixed #1190
