### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Lorinet** [CosmosOS/Cosmos#1191]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Build and debug

#### Expected Behaviour - What do you think that should happen?
It should build my project, start VMware, and after it shuts down let me edit the code.

#### Actual Behaviour - What unexpectedly happens?
It gives errors saying that it cannot write to a pdb file because another process is using it (Visual Studio 2019). After I restart VS, I can finally build my project, but after the OS shuts down, Visual Studio crashes and restarts.

`
1>NeutrinoOS -> C:\Users\lorin\source\repos\NeutrinoOS\NeutrinoOS\bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 1 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 3 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 4 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 5 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 6 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 7 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 8 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 9 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Beginning retry 10 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): error MSB3027: Could not copy "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". Exceeded retry count of 10. Failed. The file is locked by: "Microsoft Visual Studio 2019 (22128)"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4260,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb" to "bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb". The process cannot access the file 'bin\Debug\netcoreapp2.0\cosmos\NeutrinoOS.pdb' because it is being used by another process.`

#### Reproduction - How did you get this error to appear?
Building the project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190508

**Comment by MishaTY** [comment]
Restart visual studio
