### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by josephkabba** [CosmosOS/Cosmos#1192]

**Comment by josephkabba** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6004	The specified task executable location "C:\Users\Rico premium\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.	testCosmos	C:\Users\Rico premium\.nuget\packages\cosmos.build\0.1.0-localbuild20190508053006\build\Cosmos.Build.targets	169

**Comment by charlesbetros** [comment]
Is the user kit installed?
