### ISSUE TITLE
FileSystem.GetFile(path).GetFileStream() softlocks OS

### ISSUE THREAD

**Issue by Techcraft7** [CosmosOS/Cosmos#1194]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FileSystem/Reading bytes from files

#### Expected Behaviour - What do you think that should happen?
Read a byte from a file

#### Actual Behaviour - What unexpectedly happens?
No more code is executed and nothing happens past the `FileSystem.GetFile(path).GetFileStream()`

#### Reproduction - How did you get this error to appear?
I used `FileSystem.GetFile(path).GetFileStream()`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit User Kit 20181010

**Comment by Techcraft7** [comment]
Im using c# btw

**Comment by GtaMasterYT** [comment]
Have you tried updating your userkit in the case there was an update for it?

**Comment by Techcraft7** [comment]
Yes I am using the latest user kit

**Comment by Techcraft7** [comment]
For vs2017 bc vs2019 is crashing when I open files

**Comment by KironDevCoder** [comment]
I also have an issue with the filesystem, but they only support vs2019 rn I think

**Comment by Techcraft7** [comment]
I’ll try vs 2019 to see if it fixed itself

**Comment by mariusvn** [comment]
is your file in a subdirectory of root ?

try in the root one. I have bugs with directories

**Comment by Techcraft7** [comment]
Looking back at my code I found that it is the root directory, path is setup.txt

**Comment by mariusvn** [comment]
no idea then

**Comment by quajak** [comment]
I tried reproducing the issue but was unable to do so. Can you please post a small code sample which reproduces the issue in a new kernel?
