### ISSUE TITLE
Waiting for debugger connection...

### ISSUE THREAD

**Issue by KironDevCoder** [CosmosOS/Cosmos#1195]
#### Area of Cosmos - What area of Cosmos are we dealing with?
the ISO file running in VirtualBox

#### Expected Behaviour - What do you think that should happen?
to actually run the basic example

#### Actual Behaviour - What unexpectedly happens?
it boots, but shows only "Waiting for debugger connection..." in green.

#### Reproduction - How did you get this error to appear?
building the example and running it in VirtualBox

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit CosmosUserKit-20190508-vs2019.exe

**Comment by charlesbetros** [comment]
Debugger support only works with Bochs and VMWare currently. To use Virtual Box you will need to disable the debugging by setting `<EnableDebug>false</EnableDebug>`

**Comment by KironDevCoder** [comment]
And where do I do that?

**Comment by KironDevCoder** [comment]
@charlesbetros

**Comment by charlesbetros** [comment]
Project properties for your Cosmos Kernel. Uncheck the '

![image](https://user-images.githubusercontent.com/11257591/60398823-5643fb80-9b22-11e9-895a-5c09e3bacd01.png)

**Comment by KironDevCoder** [comment]
But Project properties doesn't show Cosmos or Cosmos (new)

**Comment by KironDevCoder** [comment]
@charlesbetros Project properties doesn't show Cosmos or Cosmos (new)

**Comment by furesoft** [comment]
i have the same problem

**Comment by quajak** [comment]
Is the Cosmos Project System and Cosmos Debug Engine installed? You can check by looking at installed extensions.

**Comment by KironDevCoder** [comment]
@quajak for me, yes, but sidenote: when clicking on Cosmos Project System extension it gives a warning that it can't update automatically. I don't know how important that is as I downloaded Cosmos like 2 weeks ago.

**Comment by KironDevCoder** [comment]
Anyone? Please help me with this

**Comment by quajak** [comment]
If you create a new Cosmos project do the properties show?

**Comment by KironDevCoder** [comment]
nope

**Comment by quajak** [comment]
Can you try the new user kit?

**Comment by KironDevCoder** [comment]
I CAN try it, I did, but it still doesn't show Cosmos or Cosmos (new)

**Comment by KironDevCoder** [comment]
on https://github.com/CosmosOS/Cosmos/wiki/FAQ#what-version-of-visual-studio-can-i-use-to-develop-cosmos it doesn't say 2017, but that shouldn't be THAT different from 2015, 2018 or 2019 right?

**Comment by quajak** [comment]
Only VS 2019 is supported because there are breaking changes to VS 2017. So you can only use VS2017 with Userkit https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20181010 or older.

**Comment by KironDevCoder** [comment]
k ty, now it's working.

**Comment by sayaPintar** [comment]
i have same problem but with Vmware

**Comment by Windows-Src** [comment]
I be disabled the Debbuging(iam russia) and VirtualBox says me

**Comment by EnZon3** [comment]
> Project properties for your Cosmos Kernel. Uncheck 'Enable Remote Debugging'
> 
> ![image](https://user-images.githubusercontent.com/11257591/60398823-5643fb80-9b22-11e9-895a-5c09e3bacd01.png)

I can't find it

**Comment by EnZon3** [comment]
It wasn't in any of these windows. 
![image](https://user-images.githubusercontent.com/37979038/145508989-1ee66173-ea2e-4aeb-85a5-2d8731e6b3bb.png)

**Comment by rraffaelandrei** [comment]
![image](https://user-images.githubusercontent.com/91460382/219747876-1955592b-6c82-45e0-a50b-544a7dfb90fb.png)
