### ISSUE TITLE
System.Exception

### ISSUE THREAD

**Issue by FatalGameStudios** [CosmosOS/Cosmos#1196]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Kit Builder

#### Expected Behaviour - What do you think that should happen?
To be honest, I have no clue.

#### Actual Behaviour - What unexpectedly happens?
I got an error.

#### Reproduction - How did you get this error to appear?
Just by installing it/

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit, latest build.

![Capture](https://user-images.githubusercontent.com/36797676/60392448-4992b980-9ac8-11e9-921b-94c5cc697485.PNG)

Not sure if this is an actual error or if it thinks it is.

**Comment by quajak** [comment]
Do you have an internet connection? Can you also please copy the entire log using the button and paste it as in pastebin

**Comment by Haskusayt** [comment]
Error in programm line 46 in script only developers can reparier

**Comment by quajak** [comment]
Can you please open a new issue?
