### ISSUE TITLE
How to boot in Virtual Box

### ISSUE THREAD

**Issue by TheCrafters001** [CosmosOS/Cosmos#1197]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building

#### Expected Behaviour - What do you think that should happen?
Launch in VirtualBox

#### Actual Behaviour - What unexpectedly happens?
![](https://i.imgur.com/OMpXvjj.png)

#### Reproduction - How did you get this error to appear?
Running it with VirtualBox (Not VMWare) on my machine.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit 20190628

#### Extra
The page that tells you that you can run it in VirtualBox does not help :/

**Comment by quajak** [comment]
I think for Virtual Box you have to set Cosmos to create an iso, which you can then launch manually in VirtualBox.

**Comment by TheCrafters001** [comment]
@quajak 
I don't even know how to make an ISO, because I am still new with CosmosOS

**Comment by TheCrafters001** [comment]
Nevermind. I figured it out.
