### ISSUE TITLE
error when accessing item on array

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#1200]
hi, 
im writing a little vm, all works fine but only 1 sutff does not work. my jump instruction. 
the oop structure is the same but only in this class i cant get the value of the array index 0

`
public override void Do(MState vm, byte[] args)
        {
            
                vm.IP = args[0]; //vm.GetLabelPointer(args[0]);
            
        }`

but the array has a length of 1

**Comment by quajak** [comment]
Can you confirm that the array has a length of one? I could not reproduce the problem locally. Further try using a try catch block to catch and determine the exception.

**Comment by furesoft** [comment]
the array has length of 4

**Comment by quajak** [comment]
Can you simplify the code, so I can reproduce it locally?

**Comment by charlesbetros** [comment]
Closing this. Feel free to reopen if it's still an issues.
