### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by MCTeamTech** [CosmosOS/Cosmos#1205]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling the Kernel

#### Actual Behaviour - What unexpectedly happens?

Exception: System.InvalidOperationException: Value must be set.	IL2CPU	1	

![Przechwyty12wanie](https://user-images.githubusercontent.com/53260534/61807289-83da4700-ae39-11e9-81cd-2eb7764c8177.PNG)

#### Reproduction - How did you get this error to appear?
By trying to compile it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by GtaMasterYT** [comment]
I have seen this error a few times and there are some ways to fix IL2CPU errors.
1. Restart VS.
2. Try to use the devkit.
