### ISSUE TITLE
Stuck on starting developing with VGA.

### ISSUE THREAD

**Issue by KironDevCoder** [CosmosOS/Cosmos#1206]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Wiki

#### Expected Behaviour - What do you think that should happen?
It should have something about VGAScreen.

#### Actual Behaviour - What unexpectedly happens?
It... doesn't?

#### Reproduction - How did you get this error to appear?
Reading the wiki

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Userkit_20181010

Are there any good tutorials for this? I'm using C#.

**Comment by Project-Magenta** [comment]
You must use Canvas

**Comment by KironDevCoder** [comment]
But what about making actual good guis, with text.

**Comment by Project-Magenta** [comment]
You must implement this yourself.

**Comment by KironDevCoder** [comment]
And what about the guy in https://www.youtube.com/watch?v=688sewzmgWU, he can use VGAScreen, and why don't I have Assemblies in Reference Manager?

**Comment by Project-Magenta** [comment]
because that is old Cosmos

**Comment by Project-Magenta** [comment]
like 2 year old

**Comment by KironDevCoder** [comment]
Would downloading the old version work then?

**Comment by Project-Magenta** [comment]
yes but why?

**Comment by Project-Magenta** [comment]
The new API is so much easier to use and encapsulates VGA and VBE very well

**Comment by KironDevCoder** [comment]
nvm, the old version already creates way too much errors on installing.

**Comment by Project-Magenta** [comment]
What is the problem with using Canvas?

**Comment by KironDevCoder** [comment]
nothing really, I just preffer to follow tutorials on youtube.

**Comment by KironDevCoder** [comment]
And the code I have rn,

	using System;
	using Sys = Cosmos.System;
	using Cosmos.System.Graphics;
	using System.Drawing;

	namespace CosmosKernel1 {

		public class Kernel : Sys.Kernel {

			Canvas canvas;
			Pen pen;

			protected override void BeforeRun()
			{
				Console.WriteLine("Cosmos booted successfully. Let's go in Graphic Mode");

				canvas = FullScreenCanvas.GetFullScreenCanvas();
				pen = new Pen(Color.White);

				screen_clear();
			}

			protected void screen_clear()
			{
				canvas.Clear(Color.Black);
			}

			protected void screen_setPixel(int x, int y, Color c)
			{
				pen.Color = c;
				canvas.DrawPoint(pen, x, y);
			}

			protected override void Run()
			{
				for (int x = 4; x < 16; x++)
				{
					for (int y = 4; y < 16; y++)
					{
						screen_setPixel(x, y, Color.Red);
					}
				}
			}

		}

	}

Takes quite a while to complete, I know, I can just do `canvas.DrawFilledRectangle(pen, 4, 4, 11, 11);` but it's basically the same. and `canvas.DrawFilledRectangle(pen, 4, 4, 11, 11);` also takes about as long. Is there a faster way?

**Comment by Project-Magenta** [comment]
no

**Comment by KironDevCoder** [comment]
oof
