### ISSUE TITLE
Now create the kernel class.

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#1207]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running my COSMOS Operating System.

#### Expected Behaviour - What do you think that should happen?
Run the operating system.

#### Actual Behaviour - What unexpectedly happens?
On boot, the os throws a "Now create the kernel class". We have a kernel class.
![image](https://user-images.githubusercontent.com/18405555/61842673-fb729b00-ae66-11e9-858b-fc0ef56016c6.png)

#### Reproduction - How did you get this error to appear?
We did some development on a commandline output system. Here is our kernel code. I will happily provide other parts of our code if needed.
EDIT : Through some debugging, we figured out it is an issue in our Commands Class. this is the class. https://hasteb.in/fagitici.cs

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Dev Kit commit 6b8055c

**Comment by GtaMasterYT** [comment]
Found the error. Cosmos will refuse to load if you have a static ClassName() in your class. Removed that in my code and it worked. Closing issue.

**Comment by SomethingGeneric** [comment]
What do you mean 

>  refuse to load if you have a static ClassName() in your class

**Comment by embedisbae** [comment]
> What do you mean
> 
> > refuse to load if you have a static ClassName() in your class

I wouldn't know what to tell you. I haven't done Cosmos is a bit. I'll try to grab this for you if I can.

I am the person above, new account.
