### ISSUE TITLE
The filepaths don't work

### ISSUE THREAD

**Issue by KironDevCoder** [CosmosOS/Cosmos#1209]
#### Area of Cosmos - What area of Cosmos are we dealing with?
It's filesystem.

#### Expected Behaviour - What do you think that should happen?
Actually write and read files.

#### Actual Behaviour - What unexpectedly happens?
`Exception occured: Unable to determine filesystem for path: 0:\`

#### Reproduction - How did you get this error to appear?
    var fs = new Sys.FileSystem.CosmosVFS();
    Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Userkit, someversion from 2018.

P.S. I think the filepaths are like `0:\KironOS\blahblahblah.txt`

**Comment by charlesbetros** [comment]
The file system issues are fixed in the latest User Kit.

**Comment by KironDevCoder** [comment]
yeah, but the latest one doesn't work with Visual Studio 2017, and I don't have enough storage space for 2019 yet.

**Comment by charlesbetros** [comment]
Unfortunately we are only supporting 2019 now. 

You could try to checkout an old version of the sources and merge the file system fixes, but I think your time is better spent installing 2019.

**Comment by KironDevCoder** [comment]
Hey, I just installed Visual Studio 2019 and CosmosUserKit-20190628-vs2019.exe but it still gives me the same error, do I first need to uninstall Cosmos Userkit 2018? Do I need to start a new project? What do I need to do?

**Comment by KironDevCoder** [comment]
@charlesbetros

**Comment by KironDevCoder** [comment]
hello, still doesn't work in Visual Studio 2019.

**Comment by charlesbetros** [comment]
Are you using your own disk image or the one that ships with cosmos?

**Comment by KironDevCoder** [comment]
uhm... I use the ISO profile.

**Comment by KironDevCoder** [comment]
and does cosmos ship with one?

**Comment by charlesbetros** [comment]
You have a disk mounted that is formatted as FAT32? The file system in cosmos will search for it on boot.

**Comment by KironDevCoder** [comment]
uhm... probably not if it didn't work, how do I set it to FAT32?

**Comment by KironDevCoder** [comment]
nope it isn't FAT32 ._. how do I make it FAT32?

**Comment by KironDevCoder** [comment]
@charlesbetros

**Comment by KironDevCoder** [comment]
hello?

**Comment by KironDevCoder** [comment]
please tell me how to make it FAT32 @charlesbetros

**Comment by charlesbetros** [comment]
Head over to our Gitter channel for how-to help.

**Comment by KironDevCoder** [comment]
well, now `File.WriteAllText("0:\\test", "Test");` doesn't work for some reason?

**Comment by quajak** [comment]
That is a seperate problem, please open a new issue,
