### ISSUE TITLE
VMWare SVGA II driver broken

### ISSUE THREAD

**Issue by zdimension** [CosmosOS/Cosmos#121]
When you try to Fill, SetPixel or Clear, you get this error : 
```Cosmos.IL2CPU.x86->IL->Conv_I8.cs->The size 2 could not exist, because always is pushed Int32 or Int64!```

**Comment by mterwoord** [comment]
We got past this issue, now we're stuck with #126

**Comment by zdimension** [comment]
Err... it still doesn't work with the latest source...

**Comment by mterwoord** [comment]
Yes, but the cause of this issue ("size 2 could not exist") has been fixed. Functionally speaking, this issue is a duplicate of #126

**Comment by zdimension** [comment]
But his code appears to use an old build of Cosmos (it references Cosmos.Hardware) and the error isn't the same...
