### ISSUE TITLE
Need a plug!

### ISSUE THREAD

**Issue by Luky1234567890** [CosmosOS/Cosmos#1210]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Plugs

#### Expected Behaviour - What do you think that should happen?
Build the ISO file so I can emulate it in VirtualBox.

#### Actual Behaviour - What unexpectedly happens?
I get this error at build:
`1>Nelker -> C:\Users\Lukáš Konečný\Nelker\Nelker\bin\Debug\netcoreapp2.0\cosmos\Nelker.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Lukáš Konečný\Nelker\Nelker\bin\Debug\netcoreapp2.0\cosmos\Nelker.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Int32  Interop+Kernel32.CompareStringEx(System.Char*, System.UInt32, System.Char*, System.Int32, System.Char*, System.Int32, System.Void*, System.Void*, System.IntPtr).
1>  Called from :
1>System.Globalization.CompareInfo::Int32 CompareString(System.String, Int32, Int32, System.String, Int32, Int32, System.Globalization.CompareOptions)
1>System.Globalization.CompareInfo::Int32 Compare(System.String, System.String, System.Globalization.CompareOptions)
1>Microsoft.VisualBasic.CompilerServices.EmbeddedOperators::Int32 CompareString(System.String, System.String, Boolean)
1>Nelker.Nelker.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:00.7435507`

My code is:

`Imports System
Imports System.Collections.Generic
Imports System.Text

Namespace Nelker

    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.")
        End Sub

        Protected Overrides Sub Run()
            Console.Write("Input: ")
            Dim input = Console.ReadLine()
            If input = "abc" Then
                Console.WriteLine("You typed abc! The beggining of the alphabet!")
            End If
            Console.Write("Text typed: ")
            Console.WriteLine(input)
        End Sub

    End Class

End Namespace`

#### Reproduction - How did you get this error to appear?
Just start a vb.net example code and add a If Then statement.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by Project-Magenta** [comment]
Sorry, but I think that you are better off not using VB. The language uses a lot of special library calls that need to be implemented as plugs, and I don't believe people are actively working on them.

Sorry!

**Comment by Luky1234567890** [comment]
ok thanks
