### ISSUE TITLE
Missing Debug (Global.Dbg.Send is not defined)

### ISSUE THREAD

**Issue by danbulant** [CosmosOS/Cosmos#1211]
As the title says.
Even tried Using all available cosmos classes. There's Global defined, but no Dbg in it.

**Comment by evilexecutable** [comment]
Same problem this side.

**Comment by charlesbetros** [comment]
There is a static debugger instance in Cosmos.System.Global.mDebugger https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Global.cs#L20 or you can create your own in your kernel.
