### ISSUE TITLE
The filepaths don't work

### ISSUE THREAD

**Issue by KironDevCoder** [CosmosOS/Cosmos#1212]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FileSystem / `File.WriteAllText("0:\\test", "Test");`

#### Expected Behaviour - What do you think that should happen?
create an file

#### Actual Behaviour - What unexpectedly happens?
first it says the file doesn't exist (which is right, I didn't make it yet), then it fails to create the file and at last it says "0:\test.txt doesn't exist" because of it failed to make one.

#### Reproduction - How did you get this error to appear?
    var fs = new Sys.FileSystem.CosmosVFS();
    Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

    Console.WriteLine("Exists: " + File.Exists(path)); // False
    Console.WriteLine("Written: " + File.WriteAllText(path, text)); // Tho this doesn't return anything I made a function that returns True if it works and False if it didn't, in this case False
    if (FileSystem.Files.Exists(path)) // False
    {
        Console.WriteLine(FileSystem.Files.ReadAllText(path));
    }
    else
    {
        Console.WriteLine(path + " doesn't exist!");
    }
for full solution see the solution folder I put on google drive: https://drive.google.com/file/d/1wOeOzPxOmtmeny2io1PoFaYhANn-qRPJ/view

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Userkit, someversion from 2018.

**Comment by quajak** [comment]
Could you try reinstalling the userkit or replacing the Filesystem.vmdk file with a new one? If possible, could you install the devkit and run the testrunner, so we could get more debug info?

**Comment by KironDevCoder** [comment]
I'll try that in a few minutes

**Comment by KironDevCoder** [comment]
wait, testrunner?

**Comment by KironDevCoder** [comment]
replacing Filesystem.vmdk doesn't work as it needs to be formatted as FAT32, neither did reinstalling help, and what is the testrunner?

**Comment by quajak** [comment]
If you have installed the devkit, you can open Test.sln and run the testrunner but you would have to install bochs or vmware. In the testrunner there are quite a few tests related to the file system and the option for more debug logs, which could narrow down the problem.

**Comment by KironDevCoder** [comment]
NOPE! Never gonna trust .NET again!

**Comment by KironDevCoder** [comment]
isn't there some other way this can be fixed?

**Comment by quajak** [comment]
Maybe try a different way to run the os like bochs?
If that does not work could you maybe also upload the Filesystem.vmdk file you are currently using?

**Comment by KironDevCoder** [comment]
using Bochs seems to work, but still, why didn't it work with ISOs?

**Comment by KironDevCoder** [comment]
and... running it a second time halts the system because it can't read Filesystem.vmdk?

**Comment by quajak** [comment]
If you incorrectly close bochs, you have to delete the lock file `AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Filesystem.vmdk.lock` so that it can access the file again.
I dont know what causes the difference between working with iso and bochs.

**Comment by charlesbetros** [comment]
Closing this issue. If you need any additional help drop a question in our Gitter chat.
