### ISSUE TITLE
Problem with Build.sln

### ISSUE THREAD

**Issue by nesika0101** [CosmosOS/Cosmos#1213]
Hi I have this problem, i don't know what to do pleas help. Also I am 15 and I am learing coding in free time for 2 years only, so pleas try to be clear and simple. Thanks 

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\Pavel\Desktop\Cosmos-master\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
C:\Users\Pavel\Desktop\Cosmos-master\Build.sln.metaproj : error MSB4126: Zadaná konfigurace ²eþení Debug|HPD je neplatná. Zadejte platnou konfiguraci ²eþení pomocí vlastností Configuration a Platform (nap²íklad MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Libovolný procesor"). Pokud chcete pouºít výchozí konfiguraci ²eþení, nechejte tyto vlastnosti prázdné. [C:\Users\Pavel\Desktop\Cosmos-master\Build.sln]

========================================
    Error
========================================

System.Exception: The process failed to execute!
   v Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) v C:\Users\Pavel\Desktop\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:řádek 67
   v Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() v C:\Users\Pavel\Desktop\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:řádek 48
   v System.Threading.Tasks.Task.Execute()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   v Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() v C:\Users\Pavel\Desktop\Cosmos-master\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:řádek 128

**Comment by Project-Magenta** [comment]
Please try restarting.

**Comment by nesika0101** [comment]
I tried restart program and pc. Didn't work.

**Comment by quajak** [comment]
Try renaming Cosmos-master to Cosmos

**Comment by nesika0101** [comment]
Ok, I'll try, thanks.

**Comment by nesika0101** [comment]
Didn't work. Still the same problem. I thought I should rewrite something in code, but I don't know what, it says to rewrite path to file.

**Comment by quajak** [comment]
Can you translate the error message to english?

**Comment by nesika0101** [comment]
Hardly, I am nit from English speaking country

**Comment by quajak** [comment]
Can you try building Build.sln in Visual Studio?

**Comment by nesika0101** [comment]
I tryed, but error showed up

**Comment by Project-Magenta** [comment]
What is the erro?

**Comment by nesika0101** [comment]
It's in my mother language, so idk, if I am translating it right. 

Project with type of outcome library can't be started straight.
If you want to debug, add to solution a acesabel program.

Sometihng like that, sorry for ENG

**Comment by Project-Magenta** [comment]
can you screenshot your project tree?

**Comment by Project-Magenta** [comment]
Can you click on "Build" in the menu and build from there?

**Comment by nesika0101** [comment]
![image](https://user-images.githubusercontent.com/54510926/64102532-79806680-cd70-11e9-94cf-029fa2c7343b.png)

**Comment by VisualDevelopment** [comment]
Not that, they mean on the menu on the top inside the editor, or you can just press ctrl+b (i think).

**Comment by Project-Magenta** [comment]
yup. Ctrl+B
