### ISSUE TITLE
Docs - Need a more holistic set of instructions

### ISSUE THREAD

**Issue by thekev63** [CosmosOS/Cosmos#1216]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Install, first run

#### Expected Behaviour - What do you think that should happen?
It should run according to the instructions. Unable to find anything that mentions how Visual Studio settings are configured for VMWare Player and how to change them. Looking for, but unable to find a more complete list of steps for install.

#### Actual Behaviour - What unexpectedly happens?
It won't run

#### Reproduction - How did you get this error to appear?
I ran the install according to the instructions, Visual Studio 17 (and 19), Cosmos User Kit, already had VMWare Workstation installed. Simply won't run
![image](https://user-images.githubusercontent.com/14210514/63870295-f4afda00-c976-11e9-87b4-6ee6efe3c01d.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
CosmosUserKit-20190628-vs2019.exe

**Comment by quajak** [comment]
Visual Studio 2017 is not supported and may corrupt projects. Did you create and run the project using VS2019 only?

If yes can you check that both the Cosmos Project System and Cosmos Debug extensions are installed?

**Comment by thekev63** [comment]
I only installed VS 2017 after trying with VS 2019 (Enterprise). The project type wouldn’t show up so I went back to 2017, where it did but wouldn’t work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by thekev63** [comment]
I will reinstall everything and try again, using 2019. Thanks, Kevin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by thekev63** [comment]
I did a standard install of VS 2019 enterprise, and standard install of Cosmos but it doesn't show up as a project option. However, I see it installed into the templates area.

**Comment by thekev63** [comment]
Ha! Funny! I ran the old project I created in VS 2017 in VS2019 and it worked. So the workaround is have both versions of VS installed. The installation will work for 2017 but not for 2019. Create a new project in 2017 then open it in 2019 and voila!
