### ISSUE TITLE
Missing Global.Dbg

### ISSUE THREAD

**Issue by evilexecutable** [CosmosOS/Cosmos#1217]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Devkit Kernel

#### Expected Behaviour - What do you think that should happen?
Calling Global.Dbg.Send(string) should output to Visual Studio's debug console.

#### Actual Behaviour - What unexpectedly happens?
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'Global' does not exist in the current context	CosmosKernel1	C:\Users\Lewis Smith\source\repos\CosmosKernel1\Kernel.cs	16	Active

#### Reproduction - How did you get this error to appear?
Call Global.Dbg.Send()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit
Latest Devkit from Github as of 29/08/2019.

**Comment by quajak** [comment]
Try using a Cosmos.Debug.Kernel.Debugger

**Comment by evilexecutable** [comment]
> 
> 
> Try using a Cosmos.Debug.Kernel.Debugger

The options I get from that are:

DoBochsBreak();
Equals();
ReferenceEquals();
SendChannelCommand();
SendKernelPanic();

**Comment by quajak** [comment]
you have to instantiate an object the Send method is not static
