### ISSUE TITLE
I cant use System.IO

### ISSUE THREAD

**Issue by jwkim101201** [CosmosOS/Cosmos#1218]
i coded like this.

```cs
using System;
using Sys = Cosmos.System;
using System.IO;

namespace KellsNas
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("OS Sucessfully Booted!");
        }

        protected override void Run()
        {
            Console.Write("> ");
            var input = Console.ReadLine();
            if (input == "ls")
            {
                DirectoryInfo di = new DirectoryInfo(@"cloudfiles/");
                var dir = @"cloudfiles/";
                if (Directory.Exists(dir))
                {
                    foreach (var item in di.GetFiles())
                    {
                        Console.WriteLine("FILE NAME : " + item.Name);
                    }

                }
            }
            else
            {
                Console.WriteLine("No such command. " + input);
            }
        }
    }
}
```

but i am getting cpu exception. cpu exception code is NullReferenceException 0x020EE8B8

**Comment by RICKASHEYE** [comment]
Because you are asking for the directory without knowing it exists which means the directory is Null hence the NullReferenceException

**Comment by jwkim101201** [comment]
if i can resolve this error, can you give me solution?

**Comment by RICKASHEYE** [comment]
i guess the beginning path is incorrect as they're not C:/ or the program thinks your starting at cloudfiles which is incorrect the starting drive is 0:\\ so maybe instead of @"cloudfiles/" you could use "0://cloudfiles/"?

**Comment by charlesbetros** [comment]
Two things:
First, you need to initialize the file system. 
Here's an example. https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.Fat/Kernel.cs#L26

Second, as @rickasheye mentioned, the drives are mounted as numbers. 0:\, 1:\, etc, so 0:\cloudfiles is probably the one you want;
