### ISSUE TITLE
How to access internal hard disk from cosmos

### ISSUE THREAD

**Issue by ajayreigns** [CosmosOS/Cosmos#1221]
Any way to access internal hard disk from cosmos os?
I know file systems
var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            fs.Initialize();
_are used to create new file or read a file.._

**BUT I WANT TO READ FILE FROM INTERNAL HARD DISK CONNECTED WITH MY PC.
PLEASE HELP**

**Comment by quajak** [comment]
Mounting real hard disks is not a good idea as they can be corrupted. Further from within the vm this is not easily possible. You can include single files using the resources/manifeststreams.

**Comment by ajayreigns** [comment]
> Mounting real hard disks is not a good idea as they can be corrupted. Further from within the vm this is not easily possible. You can include single files using the resources/manifeststreams.

Ok quajak.  Actually, I made bootable pendrive from ISO file. If i boot into my system  Ya,  Its Working Properly (Not From Virtual Machine).. But I want list all files on hard disk. So please help me to read contents of my hard disk.

**Comment by quajak** [comment]
Well we on,ly support FAT32 File Systems right now, so you would have to partition a drive to be Fat32 then copy your files oiver and then cosmos should be able to read them.

**Comment by ajayreigns** [comment]
> Well we on,ly support FAT32 File Systems right now, so you would have to partition a drive to be Fat32 then copy your files oiver and then cosmos should be able to read them.

Thank You Quajak...
