### ISSUE TITLE
Can you add a mirror download to help developers in China

### ISSUE THREAD

**Issue by BiscuitcubeStudio** [CosmosOS/Cosmos#1223]
I want to download Release in China.But I can't download the latest Release. So can you add a mirror download to help developers in China download Cosmos more easily?
Thanks.

**Comment by Kiddo9000** [comment]
First, try a vpn service. Psiphon is a good one and is free to use. They can also email the vpn exe file to you automatically. I can give the address if you can't get on the website. [Link Here!](https://www.psiphon3.com/en/index.html) 

If you can't do that then what are some cloud services that you can access in china that we can also use.

If all else fails, then I can't help you at the moment. Wishing the best of luck.
