### ISSUE TITLE
Namespace and nuget errors in empty project

### ISSUE THREAD

**Issue by AlexRomberg** [CosmosOS/Cosmos#1226]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Opening new project

#### Expected Behaviour - What do you think that should happen?
the examplecode opens without errors

#### Actual Behaviour - What unexpectedly happens?
In the examplecode that shows up after the project-creation-process,
`using Sys = Cosmos.System` ,  `BeforeRun()` ,  `Run()` is marked as an Error.

There are allso 8 Errors in the Errorlist:

- CS0246	The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
- CS0115	'Kernel.BeforeRun()': no suitable method found to override
- CS0115	'Kernel.Run()': no suitable method found to override
- NU1101	Unable to find package Cosmos.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
- NU1101	Unable to find package Cosmos.System2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
- NU1101	Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
- NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
- Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.

#### Reproduction - How did you get this error to appear?
I installed the cosmos "User Kit" as explaned on the cosmoswebsite [https://www.gocosmos.org/docs/install/](url) 
Then I started creating my project like this github site explains [https://github.com/CosmosOS/Cosmos/wiki/Develop-Your-Own-Operating-System-in-C%23-or-VB.NET](url)

When the project was displayed, there were these errors.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using the CosmosUserKit-20190628-vs2019.

**Comment by sudopigeek** [comment]
This happens frequently on my system as well.  When you open the project and get the error, look in the Solution Explorer.  When everything is working properly, the contents of your project in your solution should look like this:
![cmdr-img](https://user-images.githubusercontent.com/37987178/66330693-c0b8c480-e8e5-11e9-81ec-7a21dd13ac3f.png)
If the "Dependencies" icon contains a warning sign or if "Cosmos Plugs" is not there, that is why you are getting the errors. As to fixing it, closing and reopening the project or waiting a minute or two after the project has loaded tends to do the trick.

**Comment by AlexRomberg** [comment]
Thank you very much for your answer.
I have tried it, but there are still no Cosmos plugs and the warning sign remains on "dependencies". I have also reinstalled Cosmos, but without effect.

**Comment by AlexRomberg** [comment]
There is some progress, I changed the target framework to ".NET Core 3.0" and reopened the project, so now there is only one error left.

- NETSDK1083	The specified RuntimeIdentifier 'cosmos' is not recognized.

**Comment by pizzabug** [comment]
Hello; I'm bumping this issue since I have produced the same errors as the op's first post from creating a new Cosmos project. 

Out of curiosity, what prerequisites are needed for Cosmos to run on VS 2019 Community (if it is supported)? The installation guide on gocosmos.com seems to be outdated and only outlines installation for VS 2017.

**Comment by sudopigeek** [comment]
Yes, visual studio community 2019 is supported. Although gocosmos.com's tutorial is outdated, the perquisites it lists for the userkit are still required for visual studio 2019.  The most recent release to the userkit is the first to support only vs 2019, before that, they supported only vs 2017.

**Comment by pizzabug** [comment]
Thank you for your prompt response, @sudopigeek!

It appears after an hour of playing around, I figured that running the installation as an administrator has alleviated the issues that I had, and should ideally result in the problems described in @AlexRomberg's main post.

I did the following;

- I reinstalled VS 2019 Community, although I don't believe this is necessary.

- I installed the Cosmos User Kit as administrator.

- I opened/created a new project, and reloaded the SDK/Packages. Upon doing so, the project successfully reloaded. However, the target framework should remain as ".NET Core 2.0" as per original for this to work, or it breaks.

**Comment by Mist-Design** [comment]
Okay, I followed the issue, and now it only has one of the eight errors. 

`NETSDK1 The specified RuntimeIdentifier 'cosmos' is not recognized.`

Also, I noticed that my project is missing 'Cosmos Plugs', which is probably the problem.
