### ISSUE TITLE
PS/2 Controller not supported on real pc

### ISSUE THREAD

**Issue by ChazzaH014** [CosmosOS/Cosmos#1232]
#### Area of Cosmos - What area of Cosmos are we dealing with?
initial boot

#### Expected Behaviour - What do you think that should happen?
should boot like normal as it does in a virtual machine.

#### Actual Behaviour - What unexpectedly happens?
Gives me an error that PS/2 Controller is not supported. i cant disable the controller in bios anywhere.

#### Reproduction - How did you get this error to appear?
by booting up the OS.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
 Userkit 20181010

**Comment by KM198912** [comment]
you can try to use the devkit and apply the changs from the ps2fixes branch manually, thats what i did to make it work

**Comment by ChazzaH014** [comment]
>you can try to use the devkit and apply the changs from the ps2fixes branch manually, thats what i did to make it work

@KM198912 how do i install dev kit (i have VS2017) and what file would i edit?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KM198912** [comment]
you will need VS2019 and the edit the files listed here
https://github.com/CosmosOS/Cosmos/commit/87e81c209bf5b0b59f2c4b95f9153db4533ba025

**Comment by ChazzaH014** [comment]
>you can try to use the devkit and apply the changs from the ps2fixes branch manually, thats what i did to make it work

@KM198912 do i change the red text to what it says in green?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KM198912** [comment]
Basically Yes :)
