### ISSUE TITLE
Dev Kit not installing: Visual Studio workloads not found

### ISSUE THREAD

**Issue by artizzq** [CosmosOS/Cosmos#1233]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Installation of Cosmos OS Dev Kit

#### Expected Behaviour - What do you think that should happen?

Properly installed Cosmos OS Dev Kit

#### Actual Behaviour - What unexpectedly happens?

On running "install-VS2019.bat" appears a message box "Cosmos Kit Builder" with the following text: 

![image](https://user-images.githubusercontent.com/56273839/66702209-a2582c00-ed1e-11e9-9986-606a2a90974c.png)

When I click OK, Visual Studio Installer is getting to run and appears for a while
![image](https://user-images.githubusercontent.com/56273839/66702231-cd428000-ed1e-11e9-895b-3e4a487267ee.png)

Then this message pops up:

![image](https://user-images.githubusercontent.com/56273839/66702247-efd49900-ed1e-11e9-92a5-e598daeeb0b6.png)

The final log:
![image](https://user-images.githubusercontent.com/56273839/66702265-1db9dd80-ed1f-11e9-9b55-760e0ebd9158.png)

I believe I have installed all dependencies and the workloads mentioned:

![image](https://user-images.githubusercontent.com/56273839/66702289-578ae400-ed1f-11e9-8bc0-9ce5cda82429.png)

What's going on?

#### Reproduction - How did you get this error to appear?

The steps are provided above.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev Kit commit 
ba2ace3

**Comment by burgerlX** [comment]
try updating your visual studio or restarting your computer

**Comment by artizzq** [comment]
It doesnt work either.

сб, 12 окт. 2019 г., 21:36 BurgerlX <notifications@github.com>:

**Comment by RICKASHEYE** [comment]
You need to add the vs extension when installing vs "Visual Studio extension development" you can install this by opening Visual Studio Installer and clicking the More Button then the Modify button or if its available on the main selection of buttons click modify then add the extension then click Modify wait for it to finish restart your computer then reinstall cosmos

**Comment by sudopigeek** [comment]
Since updating Visual Studio and restarting your system doesn't work, it sounds like your installation of Visual Studio is either located somewhere other than where the Cosmos devkit is searching, or your installation could be corrupt.  Go to Visual Studio Installer, select your installation, and click Repair.  Since both the userkit and the devkit require Visual Studio Workloads, try downloading and installing the userkit.   The only other thing you could try if the above two methods don't work is to reinstall Visual Studio.

**Comment by JohnSpahr** [comment]
What I did:
Updated Visual Studio
Ran Visual Studio Installer as Admin
Ran the installer for Cosmos

This worked for me. Hope it helps. :)

**Comment by artizzq** [comment]
Thanks for suggestions, guys.

> Since updating Visual Studio and restarting your system doesn't work, it sounds like your installation of Visual Studio is either located somewhere other than where the Cosmos devkit is searching, or your installation could be corrupt. Go to Visual Studio Installer, select your installation, and click Repair. Since both the userkit and the devkit require Visual Studio Workloads, try downloading and installing the userkit. The only other thing you could try if the above two methods don't work is to reinstall Visual Studio.

I tried it but it still didnt work although I have only one VS2019 version installed.

> What I did:
> Updated Visual Studio
> Ran Visual Studio Installer as Admin
> Ran the installer for Cosmos
> 
> This worked for me. Hope it helps. :)

I did it too. But at least now I am stuck on infinite loading:
![image](https://user-images.githubusercontent.com/56273839/67594065-fb8f7900-f77c-11e9-9aaf-1ac59045dc47.png)
Here's what happens in Task Manager. It just eats the CPU but I dont see anything happening outside.
![image](https://user-images.githubusercontent.com/56273839/67594147-27126380-f77d-11e9-89af-b9097a39efef.png)
Does it install something or I am wrong? This happened sometimes before I used your solution and didnt throw any error. But it doesnt make any effect, it just hangs.
Still no luck.

**Comment by quajak** [comment]
Try commenting out (`yield return new VisualStudioWorkloadsDependency(_visualStudioInstance);`) here and rerunning the builder https://github.com/CosmosOS/Cosmos/blob/dc794e0eb9283b5614f8dce1d5df21cd053cc335/source/Cosmos.Build.Builder/CosmosBuildDefinition.cs#L42

**Comment by artizzq** [comment]
It throws an error 
![image](https://user-images.githubusercontent.com/56273839/67597438-9fc8ee00-f784-11e9-9861-50c736dce136.png)
devenv.exe is somehow missing.

**Comment by quajak** [comment]
Can you use the copy button and paste the entire log in a pastebin?

**Comment by artizzq** [comment]
> Can you use the copy button and paste the entire log in a pastebin?

Alright, I solved it just by repairing the Visual Studio 2019 Build Tools Installation. All is good. Thank you very much!

quajak, your solution worked fine!
