### ISSUE TITLE
Thrown an error when installing CGSE

### ISSUE THREAD

**Issue by RICKASHEYE** [CosmosOS/Cosmos#1236]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installer

#### Expected Behaviour - What do you think that should happen?
Installed

#### Actual Behaviour - What unexpectedly happens?
Thrown an Error
`
========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common not found.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\m\Desktop\Cosmos\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 395.97 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 395.88 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 414.64 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 395.86 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 395.96 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 395.87 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 395.96 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 395.85 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 395.95 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 395.87 ms for C:\Users\m\Desktop\Cosmos\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 6.98 ms for C:\Users\m\Desktop\Cosmos\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 6.06 ms for C:\Users\m\Desktop\Cosmos\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 14.38 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 15.92 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 19.56 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 11.23 ms for C:\Users\m\Desktop\Cosmos\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 11.8 ms for C:\Users\m\Desktop\Cosmos\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 10.35 ms for C:\Users\m\Desktop\Cosmos\XSharp\source\XSharp\XSharp\XSharp.csproj.
  Restore completed in 524.91 ms for C:\Users\m\Desktop\Cosmos\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 107.32 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 606.98 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 606.88 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 609.92 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 198.75 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 204.21 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 214.26 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 202.93 ms for C:\Users\m\Desktop\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 670.99 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 205.78 ms for C:\Users\m\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 672.49 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 317.02 ms for C:\Users\m\Desktop\Cosmos\Cosmos\Tools\NASM\NASM.csproj.
  Restore completed in 305.11 ms for C:\Users\m\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj.

========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\m\Desktop\Cosmos\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.Common.dll
  Spruce -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Spruce.dll
  XSharp -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\XSharp.dll
BochsSupport.cs(76,30): warning CS0168: The variable 'ex' is declared but never used [C:\Users\m\Desktop\Cosmos\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj]
  Cosmos.Build.Common -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Build.Common.dll
  IL2CPU.API -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\IL2CPU.API.dll
DebugConnectorEdison.cs(216,17): warning CS0162: Unreachable code detected [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj]
DebugConnectorEdison.cs(143,22): warning CS0414: The field 'DebugConnectorEdison.mKernelSent' is assigned but its value is never used [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj]
  Cosmos.Debug.HyperVServer -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Core.DebugStub -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Core.DebugStub.dll
  Cosmos.Debug.Kernel -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.dll
DebugSymbolReader.cs(169,30): warning CS0168: The variable 'ex' is declared but never used [C:\Users\m\Desktop\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj]
DebugInfo.cs(54,24): warning CS0169: The field 'DebugInfo.mDbName' is never used [C:\Users\m\Desktop\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj]
  Cosmos.Debug.DebugConnectors -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Cosmos.Common -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Common.dll
  Cosmos.Deploy.Pixie -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Deploy.Pixie.exe
  IL2CPU.Debug.Symbols -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.Debug.GDB -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.TestRunner.TestController -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.TestRunner.TestController.dll
  TheRingMaster -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\TheRingMaster.dll
INTs.cs(139,29): warning CS0649: Field 'INTs.mLastKnownAddress' is never assigned to, and will always have its default value 0 [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj]
ACPI.cs(36,30): warning CS0414: The field 'ACPI.SCI_EN' is assigned but its value is never used [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj]
  Cosmos.Deploy.USB -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Deploy.USB.exe
  NASM -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\NASM.dll
  Cosmos.Core -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Core.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  VSPropertyPages -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\VSPropertyPages.dll
PCIDeviceBridge.cs(13,21): warning CS0108: 'PCIDeviceBridge.SecondaryBusNumber' hides inherited member 'PCIDevice.SecondaryBusNumber'. Use the new keyword if hiding was intended. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj]
BlockDevice\Ports\Sata.cs(112,21): warning CS0162: Unreachable code detected [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj]
BlockDevice\Ports\Satapi.cs(105,21): warning CS0162: Unreachable code detected [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj]
BlockDevice\Ports\Sata.cs(206,21): warning CS0162: Unreachable code detected [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj]
BlockDevice\Ports\Sata.cs(280,21): warning CS0162: Unreachable code detected [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj]
  Cosmos.IL2CPU -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.IL2CPU.dll
  Cosmos.HAL2 -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.HAL2.dll
Graphics\FullScreenCanvas.cs(27,46): warning CS0649: Field 'FullScreenCanvas.VBEDriver' is never assigned to, and will always have its default value null [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj]
Graphics\FullScreenCanvas.cs(43,36): warning CS0169: The field 'FullScreenCanvas._VideoDevice' is never used [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj]
Graphics\VGACanvas.cs(11,27): warning CS0169: The field 'VGACanvas.VGADriver' is never used [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj]
  Cosmos.Core_Asm -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Core_Asm.dll
  Cosmos.System2 -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.System2.dll
  Restore completed in 54.06 ms for C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  IL2CPU -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\IL2CPU.dll
  Cosmos.Core_Plugs -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Core_Plugs.dll
  Cosmos.Debug.HyperVServer -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
System\MathImpl.cs(391,26): warning CS0675: Bitwise-or operator used on a sign-extended operand; consider casting to a smaller unsigned type first [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj]
  Cosmos.System2_Plugs -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.System2_Plugs.dll
  Cosmos.Debug.Hosts -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Debug.Hosts.dll
ProjectSystem\VS\PlugsProjectTreeProvider.cs(41,44): warning CS0618: 'ProjectTreeProviderBase.TreeUpdateResult.TreeUpdateResult(IProjectTree, bool, IImmutableDictionary<NamedIdentity, IComparable>)' is obsolete: 'LazyFill parameter is no longer supported.' [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem_e4phdjkd_wpftmp.csproj]
ProjectSystem\VS\PlugsProjectTreeProvider.cs(88,44): warning CS0618: 'ProjectTreeProviderBase.TreeUpdateResult.TreeUpdateResult(IProjectTree, bool, IImmutableDictionary<NamedIdentity, IComparable>)' is obsolete: 'LazyFill parameter is no longer supported.' [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem_e4phdjkd_wpftmp.csproj]
ProjectSystem\VS\PropertyPages\OldPropertyManager.cs(27,35): warning CS0067: The event 'OldPropertyManager.ConfigurationsChanged' is never used [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem_e4phdjkd_wpftmp.csproj]
  Cosmos.Build.Tasks -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.Build.Tasks.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
ToolWindows\StackUC.xaml.cs(59,13): warning VSTHRD001: Await JoinableTaskFactory.SwitchToMainThreadAsync() to switch to the UI thread instead of APIs that can deadlock or require specifying a priority. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]
ToolWindows\RegistersControl.xaml.cs(20,13): warning VSTHRD001: Await JoinableTaskFactory.SwitchToMainThreadAsync() to switch to the UI thread instead of APIs that can deadlock or require specifying a priority. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]
ToolWindows\StackUC.xaml.cs(92,13): warning VSTHRD001: Await JoinableTaskFactory.SwitchToMainThreadAsync() to switch to the UI thread instead of APIs that can deadlock or require specifying a priority. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]
CosmosWindowsPackage.cs(67,17): warning VSSDK006: Check whether the result of GetService calls is null. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]
ToolWindows\AssemblyUC.xaml.cs(605,13): warning VSTHRD001: Await JoinableTaskFactory.SwitchToMainThreadAsync() to switch to the UI thread instead of APIs that can deadlock or require specifying a priority. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj]
  Cosmos.VS.Windows -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.VS.Windows.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Property.cs(229,10): warning CS1030: #warning: 'TODO: String[]' [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
CosmosDebugEnginePackage.cs(53,42): warning VSSDK006: Check whether the result of GetService calls is null. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7StackFrame.cs(121,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(372,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(377,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(408,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(394,25): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(438,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(516,33): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(593,17): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.LaunchGdbClient" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(613,17): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(665,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(940,17): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Engine.cs(259,17): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.Terminate" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(1084,17): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7Util.MessageBox" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Engine.cs(343,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.Step" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
AD7.Impl\AD7Process.cs(192,29): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.Step" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
Commands\DebugExecCommand.cs(40,13): warning VSTHRD010: Accessing "Cosmos.VS.DebugEngine.Commands.DebugExecCommand.DebugExec" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.VS.DebugEngine -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.VS.DebugEngine -> C:\Users\m\Desktop\Cosmos\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in C:\Users\m\Desktop\Cosmos\Cosmos\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

`
#### Reproduction - How did you get this error to appear?
Opened the Installler

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
the newest commit of 20/10/2019

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1100

**Comment by RICKASHEYE** [comment]
How do you unlock that also i fixed this issue by downloading through git or well "cloning".
