### ISSUE TITLE
Console.Beep() not workinng

### ISSUE THREAD

**Issue by erikpro007** [CosmosOS/Cosmos#1242]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CosmosOS functions.

#### Expected Behaviour - What do you think that should happen?
It should be able to produce sound that i can hear.
i used Virtualbox and Boot it with an usb-stick on my notebook.

#### Actual Behaviour - What unexpectedly happens?
No sound.

#### Reproduction - How did you get this error to appear?
just use the latest user kit sdk in cosmos and use Cosmos.Beep(); or Cosmos.Beep(150, 3000);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit (User Kit 20190628)

**Comment by Project-Magenta** [comment]
Does your notebook have a PC Speaker?

**Comment by Kiddo9000** [comment]
VirtualBox unfortunately cannot generate any PC speaker sounds. VirtualBox can only play back regular 16 bit audio. VMWare Player can play PC speaker tones so I suggest trying it as it is free to use.  
  
You can download the free VMWare Player software for free on their official website, [here.](https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/15_0)  
  
Hopefully this helps!

**Comment by quajak** [comment]
Can this issue be closed?

**Comment by kilickerem066** [comment]
> VirtualBox unfortunately cannot generate any PC speaker sounds. VirtualBox can only play back regular 16 bit audio. VMWare Player can play PC speaker tones so I suggest trying it as it is free to use.
> 
> You can download VMWare Player software for free on their official website, [here.](https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/15_0)
> 
> Hopefully this helps!

Thanks, dude.
