### ISSUE TITLE
[QUESTION] How can I draw text in CGS?

### ISSUE THREAD

**Issue by kbartek05** [CosmosOS/Cosmos#1243]
Hey, I've seen others draw text in CGS, so I have a question: how can I achieve something like this? There isn't any method related to drawing text. I'm guessing it's something with the Image object, but I'm not really sure.

**Comment by quajak** [comment]
There is currently no support for drawing text, so you have to draw the characters yourself, such as by using images. For images currently only bitmaps are supported.

**Comment by kbartek05** [comment]
Could someone make a library for that? I've tried that approach, and well... It didn't go well. Because of IL2CPU.

**Comment by Project-Magenta** [comment]
While Cosmos is a developing project and you can't expect a lot from it, you can make another issue for any problems you may have using bitmaps?
