### ISSUE TITLE
Dictionary.Clear() is broken

### ISSUE THREAD

**Issue by ArtyIF** [CosmosOS/Cosmos#1244]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Dictionary (and probably other generic enumerables)

#### Expected Behaviour - What do you think that should happen?
Calling Clear() in a dictionary variable should delete all keys and values from the dictionary.

#### Actual Behaviour - What unexpectedly happens?
Calling Clear() fires a CPU exception x06.
![ *** CPU Exception x06 *** Last known address: 0x020E1615](https://user-images.githubusercontent.com/8017858/68610462-df077680-04c8-11ea-8181-622185aa821c.png)
Or x0D (here it's called from BeforeRun)
![ *** CPU Exception x0D *** ](https://user-images.githubusercontent.com/8017858/68610743-81275e80-04c9-11ea-833c-7e07048334d7.png)

#### Reproduction - How did you get this error to appear?
1. Create a Dictionary variable
2. Add a value to it
3. Call Clear() on it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by quajak** [comment]
Should be fixed by https://github.com/CosmosOS/Cosmos/pull/1256
