### ISSUE TITLE
Making a new project, and building the project.

### ISSUE THREAD

**Issue by tb100** [CosmosOS/Cosmos#1245]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creating a project/running the build

#### Expected Behavior - What do you think that should happen?
All the files should be there, and the files should build/OS should run.

#### Actual Behavior - What unexpectedly happens?
When I create a new project, it says "Cosmos" is not recognized, is it an assembly reference, and the CosmosKernel1Boot in the file tree is not there. When I run/build the project, it says that there were build errors, and "A project with an Output type of Class Library cannot be started directly"

#### Reproduction - How did you get this error to appear?
By making a new project/running the build

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit (vs2019)

Is there anyway I can fix the problem? I tried to download an open source Cosmos OS, but when I opened it, the Boot section failed to load. I hope I can get this to work, as I have been very excited to try Cosmos. Thanks to who ever can help me.

**Comment by chrisevans9629** [comment]
What build errors do you get?  Can you send your build output?

**Comment by Mist-Design** [comment]
Thanks for the response @chrisevans9629 ! Do you mean the error message? Or an output from vs2019?

Error Message:
![image](https://user-images.githubusercontent.com/54515877/69202841-c45c7f80-0b10-11ea-8c2e-e44b9f706ad1.png)

**Comment by chrisevans9629** [comment]
I have had that issue before is as well.  On the start button at the top of visual studio, do you have the option `Start` under the `Cosmos` button?  If you do, try clicking on that.

![image](https://user-images.githubusercontent.com/33850520/69203997-65483c00-0b0b-11ea-9cd2-5380787b3723.png)

**Comment by Mist-Design** [comment]
No, there is no `Start` under the button. Here is what a template looks for me:

![image](https://user-images.githubusercontent.com/54515877/69279175-d17d7b00-0bb1-11ea-9dd0-09ae294acc2e.png)

**Comment by charlesbetros** [comment]
Looks like you need to do a `nuget restore`

**Comment by Mist-Design** [comment]
How would I do that? I'm new to Visual Studio.

**Comment by chrisevans9629** [comment]
Right click the solution in solution explorer and click restore

![image](https://user-images.githubusercontent.com/33850520/69282320-a134dd00-0baf-11ea-8bec-156d4d01ebcf.png)

I have been able to reproduce this issue on my other computer and restore didn't work for me.
I get the error:
```

Error	NU1101	Unable to find package Cosmos.Build. No packages exist with this id in source(s): nuget.org
```

**Comment by Mist-Design** [comment]
I just ran that, here's the outcome:

`NuGet package restore failed.
Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:01.5061037
========== Finished ==========
`

**Comment by Mist-Design** [comment]
Should I try this on a different device?

**Comment by chrisevans9629** [comment]
Might take a look at issue #1226 seems like it's a similar issue.  Try running the User Kit installer as administrator

**Comment by Mist-Design** [comment]
Thanks @chrisevans9629 ! I'll take a look at it!

**Comment by chrisevans9629** [comment]
Let me know how it goes.  I tried reinstalling the User Kit and changing from netcoreapp2.0 to 3.0 and back and still didn't work on my other machine.

**Comment by Mist-Design** [comment]
Okay, I followed the issue, and now it only has one of the eight errors.

`NETSDK1 The specified RuntimeIdentifier 'cosmos' is not recognized.`

Also, I noticed that my project is missing 'Cosmos Plugs', which is probably the problem.

**Comment by ArtyIF** [comment]
Whenever I create a project on the latest user kit, I just restart VS and it works. Also, the boot project is not created anymore since User Kit 20181010, so that was intended.

**Comment by tb100** [comment]
Sorry for the long delay. It's working now.
