### ISSUE TITLE
COSMOS System Failed to Boot: No files found.

### ISSUE THREAD

**Issue by OceanPhoenixYT** [CosmosOS/Cosmos#1248]
#### Project Info.
My project is called Moonsolar LegacyOS, and is in a folder on my desktop called OpenCMDOS.

#### Area of Cosmos - What area of Cosmos are we dealing with?
The VMWare Player test window.
I clicked the play button that said Cosmos

#### Expected Behaviour - What do you think that should happen?

It should display:
Input: 

Also I didn't change the code whatsoever.
#### Actual Behaviour - What unexpectedly happens?

It displays this error:
ISOLINUX 6.03 2014-10-06 ETCD Copyright (C) 1994-2014 H. Peter Anvin et al
Loading Moonsolar... failed!
No files found!
boot:

Then I press enter and it says:
Loading Moonsolar... failed!
No files found!
boot:

#### Reproduction - How did you get this error to appear?

Clicking the play button that said Cosmos.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I think it is the User kit. But same thing happens with dev kit. It is the latest version as of November 30th 2019.

#### Here's the Kernel.cs code:

`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Moonsolar_LegacyOS
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }

        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}
`

**Comment by sudopigeek** [comment]
The Vmware virtual disk probably isn't working properly. You can replace it and see if the error appears again.

**Comment by VladintTech** [comment]
Try booting from the ISO version of the Cosmos. You can find it in the build's directory in file explorer.

**Comment by laurinneff** [comment]
I had the same issue. It looks like it's caused when you have a space in the project name

**Comment by ZahidServers** [comment]
Have you solved it? I am also experiencing same issue

**Comment by Pritam252** [comment]
Hello everyone, I also have the same issue and it happens to me randomly after I met some errors and then I installed the dev kit and it was worse. Anyone has a solution?

**Comment by Josiah76** [comment]
> ###

if you boot it by iso, you will get stuck on waiting on debugger

**Comment by ptobuon** [comment]
2 years later...

**Comment by zarlo** [comment]
> > 
> 
> if you boot it by iso, you will get stuck on waiting on debugger

that is user error

**Comment by MEMESCOEP** [comment]
> > > 
> > 
> > 
> > if you boot it by iso, you will get stuck on waiting on debugger
> 
> that is user error

This can be fixed by disabling the Cosmos Remote Debugger in the project properties. Make sure you unckeck this checkbox:
![image](https://github.com/CosmosOS/Cosmos/assets/67339620/6110760b-4ede-4820-bd3d-1a88c82f6e1e)

**Comment by Josiah76** [comment]
oh thanks XD
