### ISSUE TITLE
Waiting for debugger connection

### ISSUE THREAD

**Issue by typicalname0** [CosmosOS/Cosmos#1249]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugger

#### Expected Behaviour - What do you think that should happen?
ISO to work normally and boot to the system

#### Actual Behaviour - What unexpectedly happens?
Shows "Waiting for debugger connection"

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit
CosmosUserKit-20190628-vs2019

#### Extra Notes from me
I went into Project > OS Properties
Set profile to "ISO Image"
Went to Cosmos (new) then switched Configuration: Debug to Configuration: Release
Also ticked off the "Enable Debug Button" in the IL2CPU section
Also I have looked at other GitHub issues, but the fixes don't work for me.
Sorry for my bad english

**Comment by typicalname0** [comment]
Nevermind, I fixed the issue.

**Comment by LuizFernandoNB** [comment]
@typicalname0 How did you fix the error? Could you explain me? It's happening to me too

**Comment by zarlo** [comment]
@LuizFernandoNB you need to not build in debug mode

**Comment by iTzUltraX** [comment]
@zarlo i am kind of new to VS, how would i NOT build in debug?

**Comment by luizfernandonb** [comment]
> @zarlo i am kind of new to VS, how would i NOT build in debug?

Change to Release in VS

**Comment by quajak** [comment]
No, you can disable the debugger in the project settings.
