### ISSUE TITLE
Unexpected Error on Build

### ISSUE THREAD

**Issue by nasiegel8** [CosmosOS/Cosmos#1250]
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? - User Kit 20190628

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\kevin\Downloads\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 83.4 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 83.54 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 92.35 ms for C:\Users\kevin\Downloads\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 90.35 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 84.35 ms for C:\Users\kevin\Downloads\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 85.01 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 90.32 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 1.31 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 86.06 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 1.4 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Restore completed in 2.08 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
  Restore completed in 2.97 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 1.72 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 2.75 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 30.88 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 33.17 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 2.13 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 2.23 ms for C:\Users\kevin\Downloads\Cosmos\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 4.39 ms for C:\Users\kevin\Downloads\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restore completed in 39.93 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 14.11 ms for C:\Users\kevin\Downloads\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restore completed in 11.82 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 2.39 ms for C:\Users\kevin\Downloads\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 20.03 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore completed in 1.65 ms for C:\Users\kevin\Downloads\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 4.16 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 1.54 ms for C:\Users\kevin\Downloads\XSharp\source\XSharp\XSharp\XSharp.csproj.
  Restore completed in 32.85 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
  Restore completed in 34.82 ms for C:\Users\kevin\Downloads\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 4.97 ms for C:\Users\kevin\Downloads\Cosmos\Tools\NASM\NASM.csproj.
  Restore completed in 7.24 ms for C:\Users\kevin\Downloads\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 4.34 ms for C:\Users\kevin\Downloads\IL2CPU\source\IL2CPU\IL2CPU.csproj.

========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\kevin\Downloads\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\kevin\Downloads\Cosmos\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\kevin\Downloads\Cosmos\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.Common.dll
  IL2CPU.Debug.Symbols -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.Deploy.Pixie -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Deploy.Pixie.exe
  IL2CPU.API -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\IL2CPU.API.dll
  Cosmos.Core.DebugStub -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Core.DebugStub.dll
  Cosmos.Debug.Kernel -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.dll
  Cosmos.Debug.HyperVServer -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Build.Common -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Spruce -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Spruce.dll
  NASM -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\NASM.dll
  Cosmos.Deploy.USB -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Deploy.USB.exe
  VSPropertyPages -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\VSPropertyPages.dll
  Cosmos.Common -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Common.dll
  Cosmos.TestRunner.TestController -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.TestRunner.TestController.dll
  Cosmos.Debug.GDB -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.GDB.exe
  XSharp -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\XSharp.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  Cosmos.Core -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Core.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\kevin\Downloads\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
  TheRingMaster -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\TheRingMaster.dll
  Cosmos.VS.Windows -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.VS.Windows.dll
  Restore completed in 94.33 ms for C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
  Cosmos.HAL2 -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.Debug.HyperVServer -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.System2 -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.System2.dll
  Cosmos.Debug.Hosts -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.System2_Plugs -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.System2_Plugs.dll
  Cosmos.IL2CPU -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.IL2CPU.dll
  Cosmos.Build.Tasks -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Build.Tasks.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\kevin\Downloads\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.Core_Asm -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Core_Asm.dll
  Cosmos.VS.DebugEngine -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.Core_Plugs -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.Core_Plugs.dll
  IL2CPU -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\IL2CPU.dll
  Cosmos.VS.DebugEngine -> C:\Users\kevin\Downloads\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in C:\Users\kevin\Downloads\Cosmos\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

**Comment by nasiegel8** [comment]
I've checked past errors of this type and nothing seems to be working for me

**Comment by quajak** [comment]
Did you do as recommended by https://github.com/CosmosOS/Cosmos/issues/1100 for `OldCosmosPropertyPageControl.resx`?

**Comment by nasiegel8** [comment]
I've fixed that error, but I'm running into another one:
![Capture](https://user-images.githubusercontent.com/50469542/71134130-14d80300-21cb-11ea-961f-3ce64d9db90b.PNG)

**Comment by quajak** [comment]
Have you installed vmware?

**Comment by nasiegel8** [comment]
How do i do that? Sorry, I'm a bit of a noob for os's and I'm trying to learn how without having to learn assembly or C

**Comment by quajak** [comment]
You can install it from here https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/15_0

**Comment by nasiegel8** [comment]
Thanks! I'll see if it works

**Comment by nasiegel8** [comment]
It worked! Thanks!

**Comment by MLXProjects** [comment]
I had the same problem today, and was enough just copy the contents of OldCosmosPropertyPageControl.resx into a new file, delete the original and then rename the new file with the original name. I didn't have the Unblock button on file properties.
