### ISSUE TITLE
Have to run VS2019 as admin to build

### ISSUE THREAD

**Issue by Techcraft7** [CosmosOS/Cosmos#1251]
#### Area of Cosmos - What area of Cosmos are we dealing with?
User Kit 20190628

#### Expected Behaviour - What do you think that should happen?
Be able to build normally

#### Actual Behaviour - What unexpectedly happens?
Error: Acess demoed

#### Reproduction - How did you get this error to appear?
build a project not running vs 2019 as admin

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by Luky1234567890** [comment]
If you want to launch VS2019 with administrator privileges, just right-click on VS2019 and choose "Run As Administator".

**Comment by Techcraft7** [comment]
Ya see, I know that, but I don’t want to have to do that. _That’s the whole point of this issue..._

**Comment by Luky1234567890** [comment]
Oh.........
Well, I don't know hot to make it _always_ launch as an administator, so I think that is a issue of Windows or VS, rather than Cosmos -_-

**Comment by quajak** [comment]
What files is Cosmos/VS trying to access so that it needs Administrator rights to build/Can you give a more detailed error description? 

Normally Cosmos projects can be built without needing VS to have admin rights.

**Comment by Techcraft7** [comment]
Sorry I’m busy right now I’ll get back As soon as I can. :(

**Comment by Techcraft7** [comment]
I think it might be something in AppData

**Comment by quajak** [comment]
When installing did you set the installation location to the users appdata?

**Comment by Techcraft7** [comment]
hmmm im not sure

**Comment by Techcraft7** [comment]
lol it builds fine now... 
# Ill leave this open just in case the issue comes back!

**Comment by Luky1234567890** [comment]
OK, hope it doesn't come back! ;)
