### ISSUE TITLE
[CGS] Bitmaps are rendering incorrectly

### ISSUE THREAD

**Issue by kbartek05** [CosmosOS/Cosmos#1252]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS (Cosmos Graphics Subsystem)

#### Expected Behaviour - What do you think that should happen?
The image I want to draw with `canvas.DrawImage(byte[] Image, int x, int y)` should display correctly. (Source image: https://i.imgur.com/IsrMa7b.png)

#### Actual Behaviour - What unexpectedly happens?
The rendered image is very distorted and corrupted (but width and height (or rather the dimensions) appear to be correct) (Result: https://i.imgur.com/yf6SDwc.png)

#### Reproduction - How did you get this error to appear?
1. Generate an image with the Drawing library from C# with any pixel format (e.g. Format32bppArgb)
2. Create a Bitmap from byte[] imageData, from ManifestResourceStream or Convert.FromBase64 (code: https://pastebin.com/4CUMrfYb)
3. Render the Bitmap with DrawImage()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using User Kit v20190628 with Net Core 2.0

**Comment by quajak** [comment]
This should be fixed by https://github.com/CosmosOS/Cosmos/pull/1254.
