### ISSUE TITLE
Cant install cosmos

### ISSUE THREAD

**Issue by panmrherobrine** [CosmosOS/Cosmos#1255]
Hi, I've got problem during installation. It throws me an error. (visual 19 with lastest cosmos)

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Projekt "C:\Users\Hirek\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" jest pomijany, poniewa¥ nie zostaê odnaleziony.
  Projekt "C:\Users\Hirek\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj" jest pomijany, poniewa¥ nie zostaê odnaleziony.
  Ukoõczono przywracanie w elemencie 70,37 ms (C:\Users\Hirek\Desktop\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj).
  Ukoõczono przywracanie w elemencie 69,87 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Common\Cosmos.Common.csproj).
  Ukoõczono przywracanie w elemencie 74,47 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj).
  Ukoõczono przywracanie w elemencie 70,56 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj).
  Ukoõczono przywracanie w elemencie 70,42 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Core\Cosmos.Core.csproj).
  Ukoõczono przywracanie w elemencie 70,46 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj).
  Ukoõczono przywracanie w elemencie 70,56 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj).
  Ukoõczono przywracanie w elemencie 70,04 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj).
  Ukoõczono przywracanie w elemencie 70,45 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj).
  Ukoõczono przywracanie w elemencie 70,4 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj).
  Ukoõczono przywracanie w elemencie 80,32 ms (C:\Users\Hirek\Desktop\Common\source\VSPropertyPages\VSPropertyPages.csproj).
  Ukoõczono przywracanie w elemencie 17,81 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj).
  Ukoõczono przywracanie w elemencie 17,8 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj).
  Ukoõczono przywracanie w elemencie 17,43 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.HAL2\Cosmos.HAL2.csproj).
  Ukoõczono przywracanie w elemencie 17,61 ms (C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj).
  Ukoõczono przywracanie w elemencie 98,41 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj).
  Ukoõczono przywracanie w elemencie 109,22 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj).
  Ukoõczono przywracanie w elemencie 109,21 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj).
  Ukoõczono przywracanie w elemencie 28,32 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.System2\Cosmos.System2.csproj).
  Ukoõczono przywracanie w elemencie 12,43 ms (C:\Users\Hirek\Desktop\XSharp\source\Spruce\Spruce.csproj).
  Ukoõczono przywracanie w elemencie 30,09 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\TheRingMaster\TheRingMaster.csproj).
  Ukoõczono przywracanie w elemencie 12,88 ms (C:\Users\Hirek\Desktop\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj).
  Ukoõczono przywracanie w elemencie 22,97 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj).
  Ukoõczono przywracanie w elemencie 115,37 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj).
  Ukoõczono przywracanie w elemencie 115,07 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj).
  Ukoõczono przywracanie w elemencie 7,17 ms (C:\Users\Hirek\Desktop\XSharp\source\XSharp\XSharp\XSharp.csproj).
  Ukoõczono przywracanie w elemencie 40,3 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj).
  Ukoõczono przywracanie w elemencie 27,98 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj).
  Ukoõczono przywracanie w elemencie 31,06 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Tools\NASM\NASM.csproj).
  Ukoõczono przywracanie w elemencie 33,39 ms (C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj).
  Ukoõczono przywracanie w elemencie 33,68 ms (C:\Users\Hirek\Desktop\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj).
  Ukoõczono przywracanie w elemencie 23,53 ms (C:\Users\Hirek\Desktop\IL2CPU\source\IL2CPU\IL2CPU.csproj).

========================================
    Build - Build.sln
========================================

"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\\" /p:"VsixOutputPath=C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.Common.dll
  Spruce -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Spruce.dll
  XSharp -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\XSharp.dll
  Cosmos.Build.Common -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Build.Common.dll
  IL2CPU.API -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\IL2CPU.API.dll
  Cosmos.Deploy.Pixie -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Core.DebugStub -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Core.DebugStub.dll
  Cosmos.Debug.HyperVServer -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.Kernel -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.Kernel.dll
  Cosmos.Debug.DebugConnectors -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  Cosmos.Deploy.USB -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Debug.GDB -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.Common -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Common.dll
  IL2CPU.Debug.Symbols -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\IL2CPU.Debug.Symbols.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  VSPropertyPages -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\VSPropertyPages.dll
  TheRingMaster -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\TheRingMaster.dll
  Cosmos.TestRunner.TestController -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.TestRunner.TestController.dll
  NASM -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\NASM.dll
  Cosmos.Core -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Core.dll
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project 'C:\Users\Hirek\Desktop\IL2CPU\..\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj' does not exist. [C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.VS.ProjectSystem -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.VS.ProjectSystem.dll
  Cosmos.HAL2 -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.VS.Windows -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.VS.Windows.dll
VTablesImpl.cs(4,14): error CS0234: Typ lub przestrzeõ nazw "Debug" nie wyst®puje w przestrzeni nazw "Cosmos" (czy nie brakuje odwoêania do zestawu?) [C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(1,14): error CS0234: Typ lub przestrzeõ nazw "Debug" nie wyst®puje w przestrzeni nazw "Cosmos" (czy nie brakuje odwoêania do zestawu?) [C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
VTablesImpl.Debug.cs(8,24): error CS0246: Nie mo¥na znale½å nazwy typu lub przestrzeni nazw "Debugger" (brak dyrektywy using lub odwoêania do zestawu?) [C:\Users\Hirek\Desktop\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj]
  Cosmos.System2 -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.System2_Plugs.dll
  Ukoõczono przywracanie w elemencie 63,27 ms (C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj).
  Cosmos.Debug.HyperVServer -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.Debug.Hosts -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Debug.Hosts.dll
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Wykryto konflikty pomi®dzy ró¥nymi wersjami elementu "System.Collections.Immutable", których nie mo¥na rozwiÑzaå. Takie konflikty odwoêaõ sÑ rejestrowane w dzienniku kompilacji po ustawieniu wysokiego poziomu szczegóêowoÿci. [C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.VS.ProjectSystem -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.VS.ProjectSystem.vsix
  Cosmos.Build.Tasks -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.VS.DebugEngine -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.VS.DebugEngine -> C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   w Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) w C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:wiersz 67
   w Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() w C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:wiersz 48
   w System.Threading.Tasks.Task.Execute()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   w Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() w C:\Users\Hirek\Desktop\Cosmos-Userkit_20190628\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:wiersz 128

**Comment by zarlo** [comment]
it can find the Debug class and Debugger do you have all 3 repos cloned

**Comment by VladintTech** [comment]
Did you use Github Desktop to clone it?

If not then you need to unblock the cosmos folder. Follow these instructions to do bulk unblocking:
https://www.howtogeek.com/70012/what-causes-the-file-downloaded-from-the-internet-warning-and-how-can-i-easily-remove-it/
