### ISSUE TITLE
int[,] array causes NASM.EXE to exit code 1

### ISSUE THREAD

**Issue by TheGoldenMinion** [CosmosOS/Cosmos#1257]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Nasm? I'm not completely sure.

#### Expected Behaviour - What do you think that should happen?
It runs and I can use my 2d int array.

#### Actual Behaviour - What unexpectedly happens?
Nasm exits with code 1.

#### Reproduction - How did you get this error to appear?
Using a int[,] array.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest user kit.

**Comment by charlesbetros** [comment]
Multi-dimensional arrays are not currently supported. You can use jagged arrays instead.
