### ISSUE TITLE
Assigning value to member of variable array throws an IL2CPU exception and doesn't compile

### ISSUE THREAD

**Issue by MLXProjects** [CosmosOS/Cosmos#1258]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Modifying variable array contents

#### Expected Behaviour - What do you think that should happen?
The kernel should compile and add the value I set to the variable array member

#### Actual Behaviour - What unexpectedly happens?
The project doesn't compile and it throws the next error: 
`1>IL2CPU : error : Exception: System.Exception: Error compiling method 'SystemVoidtest0KernelRun': System.Exception: Error interpreting stacktypes for IL_0034: Ldind_Ref ---> System.Exception: Invalid ref type: System.Void*`

#### Reproduction - How did you get this error to appear?
Just put this somewhere on the kernel code (like the Run function)
`            string[] letters = new string[10];`
`            letters[0] += "asd";`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit, cloned from repo 12/23/2019

**Comment by MLXProjects** [comment]
Works if I use `letters[0] =letters[0] + "asd";`

**Comment by quajak** [comment]
Fixed by https://github.com/CosmosOS/IL2CPU/pull/90
