### ISSUE TITLE
GUI Mouse Click

### ISSUE THREAD

**Issue by tb100** [CosmosOS/Cosmos#1259]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Graphic Subsystem.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit C# (VS2019)

---

I've got Cosmos to draw a couple of shapes on the screen, (taskbar), and I got a mouse from issue #1186, but I don't know how to use a mouse click event. I'm guessing it's something like: `if(Cosmos.System.MouseManager =  Cosmos.System.MouseState.L && Cosmos.System.MouseManager.X >= 100){             MyAction();             }`
But I'm not sure. Could someone help me?

**Comment by KM198912** [comment]
i did the same just now and checked what could be done, this seems to work fine for me

`        public static void Update()
        {

            Point cur = new Point((int)Sys.MouseManager.X, (int)Sys.MouseManager.Y);
            canvas.DrawLine(pen, cur, new Point(cur.X, cur.Y + 14));
            canvas.DrawLine(pen, new Point(cur.X + 1, cur.Y + 1), new Point(cur.X + 10, cur.Y + 10));
            canvas.DrawLine(pen, new Point(cur.X + 6, cur.Y + 10), new Point(cur.X + 10, cur.Y + 10));
            canvas.DrawLine(pen, new Point(cur.X + 1, cur.Y + 13), new Point(cur.X + 3, cur.Y + 11));
            canvas.DrawLine(pen, new Point(cur.X + 4, cur.Y + 12), new Point(cur.X + 6, cur.Y + 17));
            canvas.DrawPoint(pen, new Point(cur.X + 6, cur.Y + 11));
            canvas.DrawLine(pen, new Point(cur.X + 7, cur.Y + 12), new Point(cur.X + 9, cur.Y + 17));
            canvas.DrawLine(pen, new Point(cur.X + 7, cur.Y + 18), new Point(cur.X + 8, cur.Y + 18));
            if(Sys.MouseManager.MouseState == Sys.MouseState.Left) { Sys.PCSpeaker.Beep(); }
            if (Sys.MouseManager.MouseState == Sys.MouseState.Right && cur.X > 100 && cur.Y > 100) { pen.Color = Color.Red; }
            canvas.Clear(col);
      
        }`

**Comment by tb100** [comment]
Okay, thanks! That seems to work.
