### ISSUE TITLE
VGAScreen won't work..? Failed IL2CPU, StackOverflowException

### ISSUE THREAD

**Issue by pshah123** [CosmosOS/Cosmos#126]
Okay so I got through a bulk of my errors and stopped short with this VGAScreen problem. The problem is, if I try to use it through Cosmos.HAL, it gives me the standard ring error (as HAL is in ring 1, user is in ring 3, etc). So, I used Cosmos.Hardware. Unfortunately, it references fine, but instantiating or using VGAScreen in any way shape or form won't let it boot.

Here's the error:
```
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Process is terminated due to StackOverflowException.
```

Here's my code:
``` csharp
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.Hardware;

namespace Colonel
{
    public class Kernel : Sys.Kernel
    {
       public static VGAScreen screen = new VGAScreen();

        public void startGraphics()
        {
//screen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200,VGAScreen.ColorDepth.BitDepth8);
//screen.Clear(0);
        }

        protected override void BeforeRun()
        {
            Console.WriteLine("Successfully Loaded.");
        }

        protected override void Run()
        {
            Console.WriteLine("Welcome. Please login with the administrative credentials provided to you.");
            //LOGIN
            string username = "";
            string password = "";
            bool loggedIn = false;
            int attempts = 0;
            while (!loggedIn)
            {
                Console.Write("Username:");
                username = Console.ReadLine();
                Console.Write("Password:");
                password = Console.ReadLine();
                if (username == "root" && password == "password")
                    loggedIn = true;
                else { attempts++; Console.WriteLine("Error: password mismatch. Try again."); }
                if (attempts >= 3) 
                {
                    Console.WriteLine("Too many attempts. Please power down."); //add ACPI.Shutdown later
                    while (!loggedIn) { }
                }
            }
            //END LOGIN
            while (loggedIn)
            {
                Console.Write(">: ");
                var input = Console.ReadLine();
                if (input == "startx")
                {
                    startGraphics();
                }
            }
        }
    }
}
```

Even the simple instantiation of the VGAScreen produces this error. Help? I'm using Cosmos.Hardware underneath source2, and from the dll produced by build.

**Comment by ARMmaster17** [comment]
Are you using the UserKit or the DevKit? VGAScreen has had known problems. If you absolutely need it. It does have some degree of functionality on the old CodePlex version.

**Comment by pshah123** [comment]
I'm using the DevKit; how do I get to the old CodePlex version?

**Comment by ARMmaster17** [comment]
I wouldn't recommend it, but it is a solution. Just go to cosmos.codeplex.com and click the big purple *Download* button. I would probably wait for confirmation from @mterwoord first though. This has been broken for some time.

**Comment by mterwoord** [comment]
@pshah123 Please be aware that older versions have more obscure bugs in the compiler...

That being said, could you or @ARMmaster17 maybe try to pin down where in VGAScreen the thing is that triggers the bug? 

Also, could you guys attach a VGAScreen file to this issue, so someone can work on this?

**Comment by pshah123** [comment]
https://github.com/CosmosOS/Cosmos/blob/master/source2/Kernel/System/Hardware/Cosmos.Hardware/Drivers/VGAScreen.cs

**Comment by mterwoord** [comment]
Thanks!

**Comment by mterwoord** [comment]
This issue is fixed. However, it introduces triggering the rings check. What you need to do is implement Cosmos.System.VGAScreen, so that any calls you need are being forwarded to the private field, which is a Cosmos.Hardware.VGAScreen.
