### ISSUE TITLE
Broken .iso File with Visual Studio 2019

### ISSUE THREAD

**Issue by HStei** [CosmosOS/Cosmos#1261]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Windows 10, Visual Studio 2019, Cosmos OS User Kit

#### Expected Behaviour - What do you think that should happen?
The .iso File created, but when I want to start VMware with the .iso File, it says, that there is no file. See attached screenshot!

#### Actual Behaviour - What unexpectedly happens?
After I created the .iso File, a get an MessageBox with the Content: The System cannot find the file...

#### Reproduction - How did you get this error to appear?
After build the .iso File under Properties > Cosmos > ISO Image

![Screenshot (1)](https://user-images.githubusercontent.com/45461988/71559045-c98ae380-2a59-11ea-9655-675712de4f53.png)
![Screenshot (2)](https://user-images.githubusercontent.com/45461988/71559046-c98ae380-2a59-11ea-8473-5a0adde16922.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I use Visual Studio 2019, Cosmos User Kit 20190628

**Comment by AnErrupTion** [comment]
I get the exact same error, but I directly debugged instead of creating an ISO file.

**Comment by HStei** [comment]
Yes, but I want to create a bootable CD or USB device. And for that I need a not broken .iso File...

**Comment by LeonardoBaldazzi** [comment]
Try to make in manually with xorriso and GRUB using WSL

**Comment by HStei** [comment]
Can you give me a short example, please?

**Comment by LeonardoBaldazzi** [comment]
https://github.com/LeonardoBaldazzi/AuroraOS/blob/master/grub.cfg

See that project

**Comment by Silverdimond** [comment]
I get the same error using the VMvare option and using the ISO image option

**Comment by Silverdimond** [comment]
I fixed my issue by renaming the project

**Comment by VladintTech** [comment]
Try making a duplicate build of your Cosmos kernel, maybe that would work.
