### ISSUE TITLE
Booting stuck at Cosmos.bin

### ISSUE THREAD

**Issue by NezbednikSK** [CosmosOS/Cosmos#1264]
#### Area of Cosmos - What area of Cosmos are we dealing with?

When i create an iso, i burn it with Rufus Portable 3.8 to an USB and plug it into my computer

#### Expected Behaviour - What do you think that should happen?

It should boot up from the USB and display my welcome message

#### Actual Behaviour - What unexpectedly happens?

It gets stuck on "Loading Cosmos.bin... ok"
![IMG_20200105_072551](https://user-images.githubusercontent.com/47603275/71776187-6df6b380-2f8d-11ea-8c34-d40177d73c1f.jpg)

#### Reproduction - How did you get this error to appear?

I just burned the iso to the USB

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20150918

**Comment by LeonardoBaldazzi** [comment]
have you tried if it works in a virtual machine?

**Comment by NezbednikSK** [comment]
Yes, it does work in both VMWare and VirtualBox.

**Comment by VladintTech** [comment]
After it says "Loading Cosmos.bin... ok" does the cursor still blink?

**Comment by NezbednikSK** [comment]
Yes, it does.

**Comment by VladintTech** [comment]
Do you have another computer you that can use to boot the usb?

**Comment by NezbednikSK** [comment]
No, sadly

**Comment by VladintTech** [comment]
That's all right.

Another question, how long did you leave the USB loading. It may just take a long time.

Also is the USB usb 2.0 or usb 3.0. You should be able to find this information on the USB's package.

**Comment by valentinbreiz** [comment]
Hello @NezbednikSK, you are using an old and outdated version of the userkit (Userkit_20150918). As far as I remember we used to have some problems on real hardware with ATA devices initialization at boot time, could you try with the last Cosmos release ?
