### ISSUE TITLE
XSharp namespace not available

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [CosmosOS/Cosmos#1265]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Plugs
#### Expected Behaviour - What do you think that should happen?
XSharp namespace should be there to make Assembly calls.

#### Reproduction - How did you get this error to appear?
By creating a new Cosmos C# project in Visual Studio 2019.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit 20190508

**Comment by quajak** [comment]
You should not be needing to use XSharp directly in the kernel. If you need to add extra plugs/xsharp functions add a second project and add the xsharp nuget package.
