### ISSUE TITLE
Exception occured while running kernel:

### ISSUE THREAD

**Issue by LavamasterYT** [CosmosOS/Cosmos#1266]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos FAT File System

#### Expected Behaviour - What do you think that should happen?
Initialize the file systems and stuff then boot

#### Actual Behaviour - What unexpectedly happens?
I get a  error and vmware telling me the CPU shut off. The error says:
Exception occurred while running kernel:
Exception:
Parameter name: <Enum.ToString> not implemented

#### Reproduction - How did you get this error to appear?
I created 2 partitions on a physical drive, one was formatted to FAT32, added some test files, then on VMWare, added that partition that was formatted to FAT32 as a SATA disk.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

**Comment by quajak** [comment]
Can you please post the entire error log?
