### ISSUE TITLE
[CGS] Bitmap Rendering Incorrect, to say the least

### ISSUE THREAD

**Issue by xeu100** [CosmosOS/Cosmos#1267]
#### Area of Cosmos - What area of Cosmos are we dealing with?

CGS
#### Expected Behaviour - What do you think that should happen?

Renders an image file that looks like https://prnt.sc/qn86t1
#### Actual Behaviour - What unexpectedly happens?

Renders the image file in a distorted manner. https://prnt.sc/qn8796
#### Reproduction - How did you get this error to appear?

```
[ManifestResourceStream(ResourceName = "StarOS.resources.banner.bmp")]
        public static byte[] bannerData;

        protected override void Run()
        {
            Pen pen = new Pen(Color.FromArgb(253, 203, 110), width: 1);
            Image bannerImg = new Bitmap(300, 120, bannerData, ColorDepth.ColorDepth32);
            canvas.DrawImage(bannerImg, 10, 10);
        }
```
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev Kit (0.20150918.2613 commit a5939b085a31577a0d72998eb03a58b8a6c16027)

**Comment by quajak** [comment]
Can you please post the original bmp file?
