### ISSUE TITLE
Trying to get the files or directory in an "address" always gives the main directory's

### ISSUE THREAD

**Issue by seba4316** [CosmosOS/Cosmos#1268]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FAT FileSystem

#### Expected Behaviour - What do you think that should happen?
I expect the Directory.GetFiles(@"\test") to return the files inside of the "test" folder

#### Actual Behaviour - What unexpectedly happens?
It returns the files inside of the "\\" folder

#### Reproduction - How did you get this error to appear?
Add a Console.WriteLine(Directory.GetFiles(@"\test")[0]); in the BeforeRun

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using the UserKit v20190628

**Comment by zarlo** [comment]
the file system is more like windows you need to add the drive code it will likely be 0 eg "0:\test"

**Comment by seba4316** [comment]
That's not specified in the wiki.. But thanks for your help, is there a way to list all the drivers?
