### ISSUE TITLE
Networking.

### ISSUE THREAD

**Issue by seba4316** [CosmosOS/Cosmos#1269]
I found an OS created on top of a Cosmos fork which has networking implemented, with DHCP, TCP, UDP, ICMP and more. I also found that there are two developers in common in this and in that OS project.
Maybe, since Cosmos' networking is not present (and the project has been here for a very long time), that part of the OS could be ported into Cosmos.

The OS name is AuraOS (https://github.com/aura-systems/Aura-Operating-System)

Thanks for reading this far

**Comment by zarlo** [comment]
the people who work on do plan to push there networking up stream

**Comment by seba4316** [comment]
I see, is there a date or something? Or do we have to wait years?

**Comment by zarlo** [comment]
not that i know of

**Comment by sudopigeek** [comment]
As far as I know, the Cosmos team is mainly focused on the kernel and debugger, so things like TCP/IP are rather scarce.

**Comment by seba4316** [comment]
> As far as I know, the Cosmos team is mainly focused on the kernel and debugger, so things like TCP/IP are rather scarce.

Yes, that is true, and that's why they could work with the AuraOS' team to bring it over to Cosmos (and they might want to participate since they are running a forked version of Cosmos)

**Comment by Backup-eric645** [comment]
@aura-systems Make a pull request in your fork of COSMOS for the original COSMOS to merge. @CosmosOS Merge the pull request from aura-systems and close the issue.

**Comment by geomtech** [comment]
@Backup-eric645 @seba4316 Hi, I'm Alexy from Aura Team and we are still working on networking, it's not ready yet to be merge in Cosmos but we are planning to make a PR to push our networking work into Cosmos.

**Comment by valentinbreiz** [comment]
Hello @seba4316, some changes regarding networking on Cosmos have been pushed to master. You can find an article in our documentation about how to use clients for different protocols (ICMP, DNS, DHCP, UDP for now).

You can find it here: https://cosmosos.github.io/articles/Kernel/Network.html

Note that you will need to build Cosmos devkit.
