### ISSUE TITLE
String's LastIndexOf

### ISSUE THREAD

**Issue by seba4316** [CosmosOS/Cosmos#1270]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Plugs

#### Expected Behaviour - What do you think that should happen?
`"example".LastIndexOf("a")` should return `2`, and let the project compile

#### Actual Behaviour - What unexpectedly happens?
Whenever `"example".LastIndexOf("a")` is in the code, there is an empty System.Exception error
[As you can see from this screenshot](https://prnt.sc/qv77an)

#### Reproduction - How did you get this error to appear?
Just add `"example".LastIndexOf("a")` to your code and try to debug

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit v20190628

**Comment by quajak** [comment]
It should be fixed in the devkit, could you please post the entire output log?

**Comment by seba4316** [comment]
There's not much in it, but sure

```
1>------ Build started: Project: ExampleOS, Configuration: Debug Any CPU ------
1>ExampleOS -> C:\Users\Seba4316\source\repos\ExampleOS\ExampleOS\bin\Debug\netcoreapp2.0\cosmos\ExampleOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Seba4316\source\repos\ExampleOS\ExampleOS\bin\Debug\netcoreapp2.0\cosmos\ExampleOS.dll
1>IL2CPU : error : Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Seba4316\source\repos\ExampleOS\ExampleOS\bin\Debug\netcoreapp2.0\cosmos\ExampleOS.cdb' because it is being used by another process.
1>   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
1>   at System.IO.File.Delete(String path)
1>   at IL2CPU.Debug.Symbols.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in C:\Development\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 68
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 160
1>IL2CPU task took 00:00:00.3587191
1>Done building project "ExampleOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by zarlo** [comment]
restarting VS might fix that

**Comment by seba4316** [comment]
Restarting VS does not fix the issue

**Comment by zarlo** [comment]
well the issues is that
The process cannot access the file 'C:\Users\Seba4316\source\repos\ExampleOS\ExampleOS\bin\Debug\netcoreapp2.0\cosmos\ExampleOS.cdb' because it is being used by another process.

**Comment by seba4316** [comment]
I eventually figured this out, I closed VS, closed some other process manually and tried to launch again, now it's talking about missing plugs; I will now close the issue and install them; thanks everyone
