### ISSUE TITLE
Cosmos devkit hangs on installing workloads

### ISSUE THREAD

**Issue by metsatahe** [CosmosOS/Cosmos#1271]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installing devkit
install-VS2019.bat

#### Expected Behaviour - What do you think that should happen?

It should install cosmos.

#### Actual Behaviour - What unexpectedly happens?

Window hangs on Installing Visual Studio Workloads. Also vs_installer.exe is not running as clearly seen from task manager

#### Reproduction - How did you get this error to appear?

i ran install-VS2019.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Devkit (idk the version)

**Comment by quajak** [comment]
If you install Visual Studio Workloads seperately are you able to install the devkit?

**Comment by VladintTech** [comment]
Does Visual studio need an update in any chance? If yes update it then try again.
