### ISSUE TITLE
How to work with Network on Cosmos? (C#)

### ISSUE THREAD

**Issue by TheReactiveMouse** [CosmosOS/Cosmos#1272]
Hi guys! How to use network in Cosmos? 
Sys.Network.IPv4.Address or Config i can't use. Not in variables not in Console.WriteLine("").

I need add network to my kernel

**Comment by zarlo** [comment]
upstream Cosmos does not have a working network stack but you can look at aura network stack can you should be able to port it for to system https://github.com/aura-systems/

**Comment by TheReactiveMouse** [comment]
> 
> 
> upstream Cosmos does not have a working network stack but you can look at aura network stack can you should be able to port it for to system https://github.com/aura-systems/

I checked, how to add port and use? can get example?

**Comment by sudopigeek** [comment]
It is not as easy as you might think
