### ISSUE TITLE
Problem with File System

### ISSUE THREAD

**Issue by TheReactiveMouse** [CosmosOS/Cosmos#1273]
Where problem? I created new virtual hard drive, started my system, create partition in DOS, fat16. My system initializated disk, but while i trying create file or directory returns 'Invalid data size', how to fix?

**Comment by sudopigeek** [comment]
Try using FAT32 instead of FAT16. I also tend to use System.IO.StreamWriter and System.IO.StreamReader for reading and writing to files.

**Comment by TheReactiveMouse** [comment]
Thanks
