### ISSUE TITLE
System.NotImplementedException: OpCode 'Readonly' not implemented

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1274]
I have been working through my operating system and I have come across the error "OpCode 'ReadOnly' not implemented!" After some testing, I found that the error comes from a call to a method that returns a string. If I comment out the method call, the error goes away.  I thought "ReadOnly" was alluring to the internal keywords I added to some of my methods, so I replaced them with 'public', but it doesn't help.  Here is the build output:
![Annotation 2020-02-04 094822](https://user-images.githubusercontent.com/37987178/73771654-97912f00-4733-11ea-9d70-5baadde0ec65.jpg)

**Comment by zarlo** [comment]
il2CPU does not know what to do with the opcode ReadOnly as it has not use been implemented

**Comment by sudopigeek** [comment]
What exactly causes it?

**Comment by zarlo** [comment]
would not be able to say with out seeing the code

**Comment by sudopigeek** [comment]
Here is my main method:
![Annotation 2020-02-04 194511](https://user-images.githubusercontent.com/37987178/73809091-e7e5ac80-4786-11ea-8aa4-43166d232fe5.jpg)
The methods TranslateAbrevation() and GetVerseLimit() just retrieve values from lists and dictionaries (no LINQ) and "ChapterLimits" is a dictionary.

**Comment by zarlo** [comment]
i did not know if dictionaries are working

**Comment by sudopigeek** [comment]
True, dictionaries in Cosmos are questionable

**Comment by sudopigeek** [comment]
Removing the dictionaries fixed the problem

**Comment by sudopigeek** [comment]
Now I get this error:
![Annotation 2020-02-06 200953](https://user-images.githubusercontent.com/37987178/74000374-aedf4080-491c-11ea-86e5-110215d14f92.png)
Do you have any idea what could be causing that?

**Comment by zarlo** [comment]
what does the build log say

**Comment by sudopigeek** [comment]
Here is the build log:
![Annotation 2020-02-07 045600](https://user-images.githubusercontent.com/37987178/74031377-3309e600-4966-11ea-960f-135ab8f3e8f5.png)

**Comment by quajak** [comment]
For the `OpCode 'Readonly' not implemented` could you open an issue on IL2CPU?
For the second, without code I can tell much. Could you post your code in a pastebin?
