### ISSUE TITLE
CD/DVD Installation Read Problem

### ISSUE THREAD

**Issue by TheReactiveMouse** [CosmosOS/Cosmos#1275]
Hi guys, i created my own installer for my Kernel.But while copying file, i don't understand, how to copy files from CD/DVD(Live CD) to Hard Drive if i can work only with hard disk? How to fix this problem and copy syslinux and kernel to hard disk?

**Comment by sudopigeek** [comment]
That is not very easy. I would probably use C/C++/Assembly binaries to get the machine's drives, and then copy your files. Unless you are skilled with low-level programming languages such as Assembly, doing so would be difficult.

**Comment by elkaamee326** [comment]
Maybe you can manually copy those boot files onto the .vmdk and boot it, I have tried it once and it worked.

**Comment by MishaTY** [comment]
Also, Cosmos does not yet support reading from a cd/DVD drive.

**Comment by elkaamee326** [comment]
I meant take the contents of an iso and on Windows copy the contents into the vmdk file..
