### ISSUE TITLE
Keyboard Interupts

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [CosmosOS/Cosmos#1276]
I am making a OS with Cosmos and I want to handle keyboard interups. How do I do it?

**Comment by LeonardoBaldazzi** [comment]
is c#, so you can use all the methods contained in the console class to interface with the user using the keyboard

**Comment by Jaiganeshkumaran** [comment]
But it does not work with Cosmos Graphic System.

**Comment by MishaTY** [comment]
You can use the KeyboardManager. Here is an example: https://github.com/MishaTY/Misha-OS/blob/master/Misha-OS/Gui/Apps/Terminal.cs
