### ISSUE TITLE
Mouse flickering

### ISSUE THREAD

**Issue by Jan0660** [CosmosOS/Cosmos#1277]
I'm starting on using cosmos and i tried to make a quick dirty mouse GUI test but this mouse flickering really bothers me.

#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphic Subsystem

#### Expected Behaviour - What do you think that should happen?
The mouse should be moving clearly across the canvas.

#### Actual Behaviour - What unexpectedly happens?
The mouse flickers.

#### Reproduction - How did you get this error to appear?
```
       protected override void BeforeRun()
        {
            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Clear(Color.Blue);
            Sys.MouseManager.ScreenWidth = (uint)canvas.Mode.Columns;
            Sys.MouseManager.ScreenHeight = (uint)canvas.Mode.Rows;
            Sys.MouseManager.X = 100;
            Sys.MouseManager.Y = 100;
        }

        protected override void Run()
        {
            canvas.Clear(Color.Blue);
            Pen pen = new Pen(Color.Red);
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)(Sys.MouseManager.X + 5), (int)Sys.MouseManager.Y);
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)Sys.MouseManager.X , (int)(Sys.MouseManager.Y + 5));
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)(Sys.MouseManager.X + 5), (int)(Sys.MouseManager.Y + 5));
        }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

[Video of the mouse flickering](https://youtu.be/ModqIB2IT6E)

**Comment by MLXProjects** [comment]
How much does it flicker? That may be a pretty normal behavior because you're clearing the screen and drawing something at pretty high speed.

**Comment by Jan0660** [comment]
I've done two improvements so it doesn't flicker that bad. 
1) Only redrawing the screen after the mouse has been moved 
2) little timer after each drawing
