### ISSUE TITLE
[Q] What about using CoreRT for compiling OS?

### ISSUE THREAD

**Issue by DjArt** [CosmosOS/Cosmos#1280]
Sure, that X# is cool, but CoreRT can make assemblies that boot from UEFI right now: https://github.com/MichalStrehovsky/zerosharp/tree/master/efi-no-runtime.
P.S. that's just discussion question

**Comment by Shadowplays4k** [comment]
it requires more code to use CoreRT

**Comment by quajak** [comment]
CoreRT itself uses unmanaged code to do some of the fundamental work, which is something cosmos wants to minimise even further. It might be useful to look at how CoreRT does a few other features such as their limited Reflection and TypesSystem.
