### ISSUE TITLE
Canvas.GetPointColor kills VS/VMWare, no explanation/results

### ISSUE THREAD

**Issue by Ninjastorm380** [CosmosOS/Cosmos#1281]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Canvas

#### Expected Behaviour - What do you think that should happen?
Canvas.GetPointColor(x, y) should return a color

#### Actual Behaviour - What unexpectedly happens?
visual studio crashes if you are debugging, else vmware crashes

#### Reproduction - How did you get this error to appear?
use GetPointColor once you create a canvas

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Tested with both the latest devkit and User Kit 20190628

**Comment by quajak** [comment]
Fixed by https://github.com/CosmosOS/IL2CPU/pull/89
