### ISSUE TITLE
File system broken??? or am I doing it wrong???

### ISSUE THREAD

**Issue by Shadowplays4k** [CosmosOS/Cosmos#1282]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File system

#### Expected Behaviour - What do you think that should happen?
Create a Directory

#### Actual Behaviour - What unexpectedly happens?
Wipes the drive and does not create a directory

#### Reproduction - How did you get this error to appear?

Put in before run
`Sys.FileSystem.CosmosVFS FS = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(FS);`

in run
Directory.SetCurrentDirectory(@"0:\");
Directory.CreateDirectory("test");
foreach (string i in Directory.GetDirectories(@"0:\"))
                {
                    Console.WriteLine(@"0:\" + i);
                    foreach (string x in Directory.GetFiles(@"0:\" + i))
                    {
                        Console.WriteLine(@"0:\" + i + x);
                    }
                }

Thats the stripped down version 

![image](https://user-images.githubusercontent.com/37817019/74835076-8ee44f80-5314-11ea-95d7-613e5e6042b4.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by zarlo** [comment]
i dont think Directory.SetCurrentDirectory(@"0:"); works

**Comment by Shadowplays4k** [comment]
even without that its not working
Directory.CreateDirectory(@"0:\test");
and
Directory.CreateDirectory(@"0:\test\");

have no result

**Comment by SomethingGeneric** [comment]
Does anyone have working examples of FAT fs?

**Comment by CodeEasyYT** [comment]
SetCurrentDirectory never works, you need to store it as a variable.
I had same problem. I fixed it like this. I hope it will be helpful.

**Comment by SomethingGeneric** [comment]
@CodeEasyYT what's your example?

**Comment by AnErrupTion** [comment]
System.IO methods work for me. Strange.
What you can try is list all files in **0:\** (AND NOT **0:/** !!!!) (Get all files in a for loop using Directory.GetFiles() and print them).

**Comment by SomethingGeneric** [comment]
I assume you have to format the disk first, and make a partition, since
COSMOS can't. Does it matter if it's FAT or FAT32?

**Comment by CodeEasyYT** [comment]
I works best with FAT32, but I don'tb know what about FAT. And yes you shuold format the disk.

**Comment by SomethingGeneric** [comment]
@CodeEasyYT you mentioned you could give some examples in ur first reponse, could you please?

**Comment by CodeEasyYT** [comment]
Variables:
"class SystemInfos
{
public static string version = "1.0.0.0";
public static string path = "0:\\";
}"

Function:
"Console.WriteLine("File name? c/c to cancel.");
            Console.Write(":");
            var result2 = Console.ReadLine();
            if (result2 == "c/c" || result2 == "C/C")
            {
                Console.WriteLine("Operation canceled!");
                return;
            }
            File.Create(SystemInfos.path + "\\" + result2);
            Console.WriteLine("File Created!");"

I hope this codes help to you.
