### ISSUE TITLE
Visual Studio not accepting Cosmos Kernel Project

### ISSUE THREAD

**Issue by TbT-Developments** [CosmosOS/Cosmos#1283]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creation of Cosmos Kernel Project

#### Expected Behaviour - What do you think that should happen?
Being able to write, debug and Build a Cosmos Project

#### Actual Behaviour - What unexpectedly happens?
Almost everything in the "kernel.*" file throws an Error. Even "using System;" and other using-directives. Also types like Strings or "void" 's are throwing errors

#### Reproduction - How did you get this error to appear?
Creating a Cosmos Kernel Project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
The latest Cosmos User Kit

**Comment by TbT-Developments** [comment]
After playing around a bit everything works as it should node, I don't exactly know what I did but... I did something

**Comment by mutantDev-LP** [comment]
I didnt understad nothing you said ;-; I'm cant even create a cosmos kernel project
