### ISSUE TITLE
Cosmos Devkit Issues

### ISSUE THREAD

**Issue by VladintTech** [CosmosOS/Cosmos#1286]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Developer Kit

#### Expected Behaviour - What do you think that should happen?
Completely Installs Cosmos DevKit

#### Actual Behaviour - What unexpectedly happens?
Gives error:
The Process failed to execute!

Here's a screenshot:
https://user-images.githubusercontent.com/62192304/76692980-bf2dbe00-6634-11ea-88e6-1f87a29d1d8c.png

#### Reproduction - How did you get this error to appear?
Trying to install Cosmos Devkit

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit, most latest version.

**Comment by charlesbetros** [comment]
Based on the error in your image, some of the files are marked as "from the internet". You'll need to "allow" them to run by unblocking them. https://www.howtogeek.com/70012/what-causes-the-file-downloaded-from-the-internet-warning-and-how-can-i-easily-remove-it/

**Comment by VladintTech** [comment]
I will try that.

**Comment by VladintTech** [comment]
Unblocked everything, still got the same error.

**Comment by VladintTech** [comment]
Anything else?

**Comment by VladintTech** [comment]
That did not work.

**Comment by VladintTech** [comment]
I do have cosmos user kit installed too.
Can that make a problem?

**Comment by VladintTech** [comment]
Hello?

**Comment by zarlo** [comment]
have a userkit installed should not be a problem

**Comment by VladintTech** [comment]
Ok, so what are some other issues that could have happened.

**Comment by quajak** [comment]
Can you please copy and post the entire log in a pastebin?

**Comment by VladintTech** [comment]
Here is the link to the PasteBin.
[https://pastebin.com/1araqYex](url)

**Comment by VladintTech** [comment]
Sorry, that link does not work try this one:
https://pastebin.com/1araqYex

**Comment by VladintTech** [comment]
Never mind turns out bulk unblocking really worked. At first it did not work. 
Thank you all of you guys for the help.
Check out my site: Vladint.com

**Comment by VladintTech** [comment]
Never mind, got more issues for this kit, so I will explain that tomorrow, too tired right now.
Sorry.

**Comment by VladintTech** [comment]
Here is the new PasteBin:
https://pastebin.com/BYNwxzs4

Then, I got an error from some kind of visual studio opening by it self. The error from visual studio was: 
Error occurred while restoring NuGet packages: The operation failed as details for project Spruce could not be loaded.
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:05.1632027
========== Finished ==========

Please Note: The Visual Studio opened just for the installation.
Also, small thing: When user kit was installing I opened task manager and I could see that the user kit installer was 32 bit while my PC is 64 bit.

**Comment by quajak** [comment]
This means that the devkit has finished installing and is ready to use. The project which opened has been removed and used to open Kernel.sln, which might have contained broken references.
