### ISSUE TITLE
IL2CPU System.Exception without explanation when using System.IO.File.GetAttributes

### ISSUE THREAD

**Issue by qqa12** [CosmosOS/Cosmos#1288]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling the project.

#### Expected Behaviour - What do you think that should happen?
It should compile and give me the attributes of a file.

#### Actual Behaviour - What unexpectedly happens?
It gives an build error saying just “Exception: System.Exception:” without any further information from IL2CPU at line 1.

#### Reproduction - How did you get this error to appear?
1) Create a blank COSMOS kernel
2) Add ‘using System.IO;’
3) Place ‘File.GetAttributes("Root.txt")’ into one of the Run functions.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit, the installer was called ‘CosmosUserKit-20190628-vs2019.exe’
![SystemException](https://user-images.githubusercontent.com/61630043/76989262-5e5cf900-6946-11ea-8994-5af226a0311a.PNG)
![SystemException-Fullscreen](https://user-images.githubusercontent.com/61630043/76989279-62891680-6946-11ea-9960-b26a6ac92b3d.PNG)

**Comment by quajak** [comment]
You have to initialize the filesystem first

**Comment by quajak** [comment]
Also can you post the entire log from the output window?

**Comment by charlesbetros** [comment]
I don't think that plug is implemented.

**Comment by qqa12** [comment]
@quajak GetAttributes was the only thing making trouble in another project where I had already set up the filesystem.
Also I just discovered that yes, that plug is not implemented. I will close this now since missing plugs should not be reported as a bug.
