### ISSUE TITLE
Exception: System.Exception when using new code.

### ISSUE THREAD

**Issue by gabearthur4** [CosmosOS/Cosmos#1289]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
That the project should build successfully and boot.

#### Actual Behaviour - What unexpectedly happens?

I get an IL2CPU System.Exception Error (doesn't provide details)

#### Reproduction - How did you get this error to appear?

I got this error to appear after adding a new bit of code to my project to allow the OS to execute code in a .txt file (way of storing and executing programs)

Offending Code:
```
if (input == "execute") {
                var path = @"0:\Programs\result.exe";
                var csc = new CSharpCodeProvider();
                CompilerParameters parameters = new CompilerParameters(new[] { "mscorlib.dll", "System.Core.dll" }, path, true)
                {
                    GenerateExecutable = true
                };
                var code = File.ReadAllText(@"0:\Programs\test.txt");
                var result = csc.CompileAssemblyFromSource(parameters, code);

            }
```
Does anybody have a fix for this issue or an alternate way of achieving this task?
![Capture](https://user-images.githubusercontent.com/21002318/77291268-a060b300-6d29-11ea-8054-44b2a8c59f40.PNG)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I was using the User Kit, latest version I believe.

**Comment by zarlo** [comment]
CSharpCodeProvider needs to be plugged

**Comment by gabearthur4** [comment]
> CSharpCodeProvider needs to be plugged

how do I do that (do you have step by step instructions?  i am a noob when it comes to this)

**Comment by zarlo** [comment]
you will need to reimplement CSharpCodeProvider in a way that it will work in Cosmos

**Comment by vazer7070** [comment]
> 
> 
> you will need to reimplement CSharpCodeProvider in a way that it will work in Cosmos

hello, how i reimplement please.?
