### ISSUE TITLE
Booting from USB Stuck in Creating ATA IOGroup

### ISSUE THREAD

**Issue by pshah123** [CosmosOS/Cosmos#129]
Hey, so I just made my first bootable USB with cosmos. Unfortunately when booting from the USB it gets stuck on "Creating ATA IOGroup". It displays this twice on the screen then stalls. 

I'm booting external first, with USB booting enabled and in Legacy Boot Mode on a Sony VAIO.

Would much request urgent help on this issue, as I need to deploy very soon.

**Comment by pshah123** [comment]
Forgot to mention, it works fine on VMWare.

**Comment by mterwoord** [comment]
This issue is most likely related to #113 

We currently have limited people helping us move the project forward, so real harware booting is not a high priority right now..

**Comment by pshah123** [comment]
Thanks for the quick reply! I think I found the issue - simply when booting the iso it doesn't find a hard disk or somewhere to store its files. When provided a medium it works fine, so I'm guessing the USB needs to be partitioned in some way? 
Also, I'm interested in helping move this project forward as its one of my favorite repos on github, but I'm a newbie to C#. Anything simple I can start with?

**Comment by ARMmaster17** [comment]
@pshah123 You can help out with the docs. It gives you a nice opportunity to see a detailed look at the internals of Cosmos without the risk of breaking anything. The Wikipedia page also needs some work. I took out all the old stuff, but there are some new features that need to be documented more clearly.

**Comment by nnvt** [comment]
Any temporary fix for this? I would really like it to boot on one of my pc's but it's stuck at the same error, even when using PXE boot...

**Comment by mterwoord** [comment]
With real hardware, pretty much the only thing you can do is somehow disable the ATA controllers.

We know this issue sucks, but we don't have too many people working on things, so we are focusing on core things, one of which is the FAT support. After that, we're most likely going to fix the tis ATA bug.
