### ISSUE TITLE
is vb.net really supported???

### ISSUE THREAD

**Issue by fxyx** [CosmosOS/Cosmos#1291]
![Cosmos_Issue](https://user-images.githubusercontent.com/62747303/77849882-2d46b900-71cf-11ea-8ab7-33612719811d.png)

Same new project...

If I use the IF statement I receve a "Exception: System.NotImplementedException: OpCode 'Endfilter' not implemented!	SAM	D:\Sviluppo vb.Net\Sistemi Operativi\SAM\SAM\IL2CPU" error

**Comment by Shadowplays4k** [comment]
its recommended to use c# as vb is not fully supported from what I have seen

**Comment by fxyx** [comment]
Cosmos is an operating system "construction kit". Build your own OS using managed languages such as C#, VB.NET, and more!
Wouldn't it be better to just talk about supported languages or just specify which ones are?

**Comment by fxyx** [comment]
Moved to IL2CPU issue page, excuse me :s
