### ISSUE TITLE
Canvas does not draw shapes on Oracle VM VirtualBox

### ISSUE THREAD

**Issue by GreenCobalt1** [CosmosOS/Cosmos#1292]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Canvas

#### Expected Behaviour - What do you think that should happen?
Exactly what happens on VMWare Workstation 15.

#### Actual Behaviour - What unexpectedly happens?
On VirtualBox, when I activate my GUI with a command, it sets the correct canvas size but does not draw shapes.

#### Reproduction - How did you get this error to appear?
Just initialize a canvas and draw a rectangle. It will draw on vmware but not virtualbox.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit v20190628

Video:
![](https://im4.ezgif.com/tmp/ezgif-4-d8d25989c278.gif)

**Comment by quajak** [comment]
Virtual box is not currently supported.
