### ISSUE TITLE
ISOLinux says "Too Large for a bootstrap"

### ISSUE THREAD

**Issue by SomethingGeneric** [CosmosOS/Cosmos#1293]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building an OS

#### Expected Behaviour - What do you think that should happen?
OS should boot

#### Actual Behaviour - What unexpectedly happens?
Virtualbox / Real PC pauses with error message.

#### Reproduction - How did you get this error to appear?
I finally started implementing file system, and it no longer boots. I assume it's too large or something, but so then how do I restructure to skirt this limit?

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, commit cd5bbd16 (latest release)

**Comment by SomethingGeneric** [comment]
This is what happens on boot, without me doing anything:
![image](https://user-images.githubusercontent.com/12242178/78582948-1ffb8100-7804-11ea-9020-b5448368ae2e.png)

Then I tell it to boot and get this:
![image](https://user-images.githubusercontent.com/12242178/78583015-386b9b80-7804-11ea-9825-17c09a81d222.png)

**Comment by SomethingGeneric** [comment]
Strangely, this issue isn't present on real hardware

**Comment by SomethingGeneric** [comment]
Turns out, my VM needed more RAM. However, my question still remains about working around how much of the OS can fit as a "bootstrap"

**Comment by charlesbetros** [comment]
Are you on latest master? I thought we bumped the memory already to fix this.

**Comment by SomethingGeneric** [comment]
^ im on the latest "release", but that's 31 commits behind y'all's master branch

**Comment by SomethingGeneric** [comment]
Ok thanks y'all!
