### ISSUE TITLE
Download file.

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1295]
Hello.

I'm developing OS, and i'm need to download files. How do i can made that?

**Comment by pikalover6** [comment]
If you would like to download files through your OS that you are developing, I have no idea. If you want to import the files into your OS and you are using VMware, then you can use 7-zip to open up your operating system's vmdk file and drag and drop files to import them into your OS.  If you just need the Cosmos installer, it is here: https://www.gocosmos.org/download/

**Comment by zarlo** [comment]
to do that you will need to fix Cosmos' TCP stack as its not working
