### ISSUE TITLE
System stopping on dir creation process 

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1296]
I'm trying to create dir in my OS, and that stopping (not working).

My code: Directory.SetCurrentDirectory(@"0:\\");
                Console.Write("\n[ INSTALLER ] Starting installing process...\n");
                fs.CreateDirectory(@"0:\\System\\");
                fs.CreateDirectory(@"0:\\System\\sys");
                Console.Write("\n[ INSTALLER ] Creating system directories...\n");
                fs.CreateDirectory(@"0:\\System\\databases");
                Console.Write(@"\n[ INSTALLER ] Creating databases...\n");
                fs.CreateFile(@"0:\\System\\databases\\users.txt");
                Console.Write(@"\n[ INSTALLER ] Creating system files...\n");
                fs.CreateFile(@"0:\\System\\sys32\\login.cs");
                Console.Write("\n[ INSTALLER ] Adding users...\n");
                Console.Write("\n[ INSTALLER ] Enter user name: ");
                var username = Console.ReadLine();
                Console.Write("\n[ INSTALLER ] Enter user password...\n");
                var password = Console.ReadLine();
                Console.Write("\n[ INSTALLER ] Creating user with name " + username + " and password " + password + "...\n");
                File.WriteAllText(@"0\\System\\databases\\users.txt", "\n" + username + ":" + password + "\n");
                Console.Write("\n[ INSTALLER ] Installation completed. Rebooting...\n");
                Thread.Sleep(5000);
                Sys.Power.Reboot();

**Comment by pikalover6** [comment]
Hello, are you running this on real hardware, virtualbox, vmware...?

**Comment by radeberyt** [comment]
> Hello, are you running this on real hardware, virtualbox, vmware...?

Virtual Box

**Comment by radeberyt** [comment]
Github has "eated" my double \\*

**Comment by pikalover6** [comment]
This is mentioned in the FAT FileSystem section of the wiki:

The virtual file system won't work unless you change the .vmdk file of your VM to this if you are on VMware and this if you are on Hyper-V (currently nothing has been done for VirtualBox so far, RIP).

So I recommend that you VMWare

**Comment by pikalover6** [comment]
Console.Write(@"\n[ INSTALLER ] Creating databases...\n"); 
I wonder if the "@" sign is necessary...

**Comment by radeberyt** [comment]
Again, at VMWare Workstation 15 my OS stopping at dir creation process..

**Comment by radeberyt** [comment]
VMWare says 'The CPU has been disabled by the guest operating system. Power off or reset the virtual machine.'

**Comment by pikalover6** [comment]
Does your vmdk file match this?: https://github.com/CosmosOS/Cosmos/raw/master/Build/VMWare/Workstation/Filesystem.vmdk

**Comment by radeberyt** [comment]
> Does your vmdk file match this?: https://github.com/CosmosOS/Cosmos/raw/master/Build/VMWare/Workstation/Filesystem.vmdk

No:
version=1
encoding="windows-1251"
CID=fffffffe
parentCID=ffffffff
createType="monolithicSparse"

# Extent description
RW 16777216 SPARSE "UIHandeOS.vmdk"

# The Disk Data Base 
#DDB

ddb.adapterType = "ide"
ddb.geometry.cylinders = "16383"
ddb.geometry.heads = "16"
ddb.geometry.sectors = "63"
ddb.longContentID = "0d60c881152b469a36cc47c4fffffffe"
ddb.uuid = "60 00 C2 9d 4d 26 a2 55-71 7b 99 1f 02 7c 90 ff"
ddb.virtualHWVersion = "16"

**Comment by zarlo** [comment]
Directory.SetCurrentDirectory does not work
