### ISSUE TITLE
Files and directories doesn't creating.

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1297]
I'm trying to create file in my OS, and that says:
No partitions found!
Exception occurred: Unable to determine filesystem for path: 0:\\
Exception occurred while running kernel:
Eception: Value cannot be null.
Parameter name: aPath

I've entered all required arguments.

**Comment by pikalover6** [comment]
You must use the filesystem.vmdk provided by Cosmos.

**Comment by AdhithAdhi** [comment]
how to do that

> You must use the filesystem.vmdk provided by Cosmos.

can you show me?
