### ISSUE TITLE
OS freezes when creating directories/files

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1298]
I'm using VMWare Workstation 15
When i'm creating directories/files my OS freezes.
My code:
Before all methods:
        Sys.FileSystem.CosmosVFS fs;
        CmdHandler handler;
        string username;
        string password;
In BeforeRun():
            fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            fs.CreateDirectory(@"0:\\sys");

**Comment by zaiinn-x** [comment]
Hey, so when you type `fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);` it allows all System.IO functions to be used instead. Use `Directory.CreateDirectory(Path)` or `File.Create(Path)`
