### ISSUE TITLE
IL2CPU Error

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [CosmosOS/Cosmos#1299]
'SystemUInt32CosmosCoreMemoryRATGetFirstRATSystemVoidpointer': System.Exception: Error interpreting stacktypes for IL_0007: Sub ---> System.NotImplementedException: Sub on types 'System.Byte*' and 'System.Void*' not yet implemented!

**Comment by pikalover6** [comment]
Please give more information

**Comment by quajak** [comment]
Please post the entire log and the code.
