### ISSUE TITLE
How can i get GPU, CPU, RAM etc information?

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1301]
Hello, i'm creating command to get GPU, CPU, RAM, etc information.
How i can do that?

**Comment by zarlo** [comment]
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core/CPU.cs would be a good place to start

**Comment by Toonlink3000** [comment]
> https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core/CPU.cs would be a good place to start

Can you explain?

**Comment by quajak** [comment]
Work in this direction is being done in https://github.com/CosmosOS/Cosmos/pull/1237. `CPU` has a method to ge tthe current RAM. There is currently no work being done on GPU information.
