### ISSUE TITLE
"System cannot find the file specified." while building ISO

### ISSUE THREAD

**Issue by NezbednikSK** [CosmosOS/Cosmos#1304]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Building an ISO of my OS.

#### Expected Behaviour - What do you think that should happen?

An explorer window should open.

#### Actual Behaviour - What unexpectedly happens?

An error window saying "The system cannot find the file specified." appears.

#### Reproduction - How did you get this error to appear?

Setting the Cosmos profile to "ISO Image".

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I am using the newest userkit.
https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20190628

**Comment by pikalover6** [comment]
That has happened to me before, it turns out even without that option cosmos still builds an ISO image. Just turn debugging of, run it as normal an the ISO will be in:
`C:\Users\....\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos`

**Comment by NezbednikSK** [comment]
Thank you!
