### ISSUE TITLE
Cosmos OS crashes on boot

### ISSUE THREAD

**Issue by Maks1116** [CosmosOS/Cosmos#1305]
Hello! I'm writing my os in C# and when I hit compile while it is booting crashes.

**Comment by zarlo** [comment]
can we have more info like a some logs

**Comment by pikalover6** [comment]
This happened to me once, and I realized that it was because I was using string[] which is unsupported by cosmos. Also, have you added anything to your code yet, or is it the default kernel?

**Comment by Maks1116** [comment]
I tried with default kernel and this still happens

**Comment by quajak** [comment]
Can you please post the output logs/any logs you get before it crashes
