### ISSUE TITLE
Missing plug for System.Int64 - IL2CPU System.Exception

### ISSUE THREAD

**Issue by bartekmuzyk** [CosmosOS/Cosmos#1306]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Missing plugs.

#### Expected Behaviour - What do you think that should happen?
The image should build without errors and open up in VMWare.

#### Actual Behaviour - What unexpectedly happens?
I get an error about a missing plug for System.Int64.

#### Reproduction - How did you get this error to appear?
Create a new Bitmap object and use the DrawImage method to show it on a canvas.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using the newest User Kit https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20190628

And yes, I know, it says I shouldn't report this as a bug, but what else am I supposed to do?

**Comment by quajak** [comment]
Could you please post your code and build output?

**Comment by bartekmuzyk** [comment]
Of course, my apologies.
Source code: https://pastebin.com/qUWa04UK (Error occures in line 21/22)
Build output: https://pastebin.com/ZEjFs9b0 (Some of the text may be in polish so ignore that)

**Comment by bartekmuzyk** [comment]
Thanks for the help
