### ISSUE TITLE
Develop on Mac OS?

### ISSUE THREAD

**Issue by oybekrustamov** [CosmosOS/Cosmos#1307]
Is it possible to start development on the Cosmos OS platform in the MacOS operating system?

**Comment by pikalover6** [comment]
Cosmos user kit is not available on MacOS, but if you are techy enough you can compile the dev kit from source. Or try [wine](winehq.org), which is an applications for bsd, linux and macos that allows the user to run Windows applications. It is not perfect though and I have not tried it.

**Comment by oybekrustamov** [comment]
> Cosmos user kit is not available on MacOS, but if you are techy enough you can compile the dev kit from source. Or try [wine](winehq.org), which is an application for bsd, linux and macos that allows the user to run Windows applications. It is not perfect though and I have not tried it.
> 
> Update:
> Its seems as if everything needed to develop is supported on MacOS(Visual studio, .NET core..). The only thing missing is the CosmosOS kit, which you can build from source code. See: https://www.gocosmos.org/docs/install/.
> At the bottom there will be instructions on building CosmosOS from source

Thank you for answer!

**Comment by oybekrustamov** [comment]
We are waiting for the developers to release it for MAC OS..
P.S. I can crookedly collect from sources.. Better than the developers themselves...

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/884

**Comment by Vladimir-Moskalenko** [comment]
Installing Visual Studio is extremely hard using wine, so it is better to use it with a virtual machine

**Comment by mrGoodWolf** [comment]
my build for mac <here>  (https://www.github.com/mrGoodWolf/CosmosMac)
