### ISSUE TITLE
[Question] What happened to Cosmos.Assembler?

### ISSUE THREAD

**Issue by NezbednikSK** [CosmosOS/Cosmos#1308]
I was recently looking at the outdated GitHub Wiki you got here, and i stubled upon an article named "Intro To Plugs". It looked really cool and thinking about the fact that i started learning assembler today it would be cool if i could make my own stuff with assembler for Cosmos. Turns out it is already in the Archive directory. What happened to it?

**Comment by zarlo** [comment]
it should be in https://github.com/CosmosOS/IL2CPU
