### ISSUE TITLE
Image Coverting issue

### ISSUE THREAD

**Issue by chathurax** [CosmosOS/Cosmos#1311]
I need convert image and get array like
 new byte[] { 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,......}
this. what is the tool for that?

**Comment by quajak** [comment]
See Cosmos Image Converter under https://github.com/CosmosOS/Cosmos/wiki/Resources. 
Or under windows, you can use `Convert.ToBase64String(File.ReadAllBytes(fileName));` to get a string version of the file, which you can then load in Cosmos using `Convert.FromBase64String(outputstring);`

**Comment by valentinbreiz** [comment]
COSMOS Image Converter is totally outdated
