### ISSUE TITLE
How do i can create console gui? Can i use NuGet packages?

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1312]
Hello.

How do i can create console gui? Can i use NuGet packages?
And, how do i can detect other OS on PC?

**Comment by quajak** [comment]
I am not sure what you mean with console gui. If you want to create a console in graphics mode. You will have to implement youre own console. AFAIK there is no NuGet package for this case. 
It is currently not possible to detect other OS on the same PC.

**Comment by sudopigeek** [comment]
You can implement a console and GUI using this library [here](https://github.com/sudopigeek/CGUI).
