### ISSUE TITLE
COSMOS BMP Error

### ISSUE THREAD

**Issue by chathurax** [CosmosOS/Cosmos#1313]
how use `ManifestResourceStream` in cosmos for drawimage in canvas?
and optimze that loaded image preview?

**Comment by zarlo** [comment]
ManifestResourceStream does not work you need to make the files in to a byte array in your code

**Comment by chathurax** [comment]
solution?

**Comment by chathurax** [comment]
![os bmp ](https://user-images.githubusercontent.com/20703404/80977347-3b2cd100-8e42-11ea-99f3-900866c8cd0c.JPG)

### here output and original images

**Comment by quajak** [comment]
Can you post the original bmp file, so I can download it and use it to test?

**Comment by chathurax** [comment]
![cerberus bmp](https://user-images.githubusercontent.com/20703404/81029782-e4f07a00-8ea3-11ea-8e2e-c288afee403e.jpg)

please remove .jpg extention. this image is in bmp format. (github not allowed to upload bmp)

**Comment by Silverdimond** [comment]
Can we just have a webtool to convert bmp files to what we need to display the image?

**Comment by Shadowplays4k** [comment]
There is a web tool, look on the wiki.
https://github.com/CosmosOS/Cosmos/wiki/Resources#related-projects-and-resources

**Comment by Silverdimond** [comment]
How do you use it?

**Comment by chathurax** [comment]
`public String bigstring = "Qk02GAAAAAAAADYAAAAoAAAAMAAAACAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAA+vr6//Ly8v/39/f/9vb2//T09P/6+vr/8fHx//v7+//y8vL/9/f3//b29v/09PT/+fn5//Hx8f/6+vr/8/Pz//f39//39/f/9PT0//n5+f/w8PD/+vr6//Pz8//19fX/7e3t//Pz8//6+vr/8PDw//n5+f/09PT/9/f3//b29v/z8/P/+vr6//Hx8f/5+fn/8/Pz//b29v/39/f/8vLy//v7+//x8fH/+vr6//T09P/29vb/9/f3//Ly8v/6+vr/7u7u//v7+//z8/P/9vb2//n5+f/w8PD//v7+/+7u7v/7+/v/9PT0//X19f/5+fn/8PDw//39/f/v7+//+vr6//T09P/09PT/+fn5//Dw8P/Ly8v/cHBw/01NTf92dnb/fHx8/zo6Ov9eXl7/urq6/+7u7v/5+fn/9PT0//T09P/6+vr/7+/v//39/f/w8PD/+fn5//X19f/09PT/+/v7/+7u7v/+/v7/8PDw//n5+f/19fX/9PT0//v7+//u7u7//v7+//Dw8P/4+Pj/9vb2//Pz8//8/Pz/7u7u//39/f/w8PD/+Pj4//b29v/y8vL//Pz8/+7u7v/9/f3/8fHx//f39//19fX/kJCQ/yUlJf8AAAD/ERER/3d3d/8CAgL/BAQE/4KCgv8RERH/AAAA/xgYGP+Dg4P/7+/v//f39//y8vL//f39/+7u7v/8/Pz/8/Pz//b29v/4+Pj/8fHx//39/f/u7u7/+/v7//Ly8v/29vb/+Pj4//Dw8P/+/v7/8PDw//n5+f/09PT/9fX1//j4+P/x8fH//Pz8//Dw8P/5+fn/9PT0//X19f/4+Pj/8fHx//z8/P/w8PD/39/f/3Fxcf8aGhr/AAAA/wAAAP8EBAT/e3t7/wYGBv8AAAD/AAAA/wsLC/+Dg4P/AwMD/wAAAP8AAAD/DAwM/2dnZ//U1NT/8PDw//z8/P/x8fH/+Pj4//X19f/09PT/+fn5//Dw8P/8/Pz/8fHx//j4+P/19fX/9PT0//r6+v/w8PD/+Pj4//Pz8//29vb/9vb2//X19f/4+Pj/8/Pz//n5+f/z8/P/9/f3//b29v/09PT/+Pj4//Ly8v+Kior/Hh4e/wAAAP8AAAD/AAAA/wAAAP9ycnL/Hx8f/wAAAP8AAAD/AAAA/wAAAP8oKCj/c3Nz/wAAAP8AAAD/AAAA/wAAAP8TExP/jY2N//Pz8//4+Pj/9PT0//b29v/29vb/9PT0//n5+f/y8vL/+Pj4//T09P/29vb/9vb2//T09P/5+fn/9PT0//b29v/19fX/9vb2//b29v/19fX/9/f3//T09P/39/f/9fX1//b29v/29vb/5OTk/8HBwf8HBwf/AAAA/wAAAP8AAAD/AAAA/zY2Nv9mZmb/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/eXl5/zAwMP8AAAD/AAAA/wAAAP8AAAD/Dg4O/7W1tf/e3t7/9vb2//b29v/19fX/9/f3//T09P/39/f/9fX1//b29v/29vb/9fX1//f39//09PT/9PT0//f39//19fX/9vb2//b29v/19fX/9/f3//T09P/39/f/9vb2//b29v/29vb/09PT/wwMDP8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf8DAwP/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/DQ0N/21tbf8AAAD/AAAA/wAAAP8AAAD/AAAA/xUVFf/o6Oj/9vb2//b29v/19fX/9vb2//T09P/39/f/9fX1//b29v/29vb/9fX1//f39//09PT/+vr6//Ly8v+6urr/6Ojo//T09P/5+fn/8vLy//r6+v/z8/P/9/f3//b29v/09PT/8/Pz/wwMDP8AAAD/AAAA/wAAAP8AAAD/Kioq/w4ODv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xkZGf8oKCj/AAAA/wAAAP8AAAD/AAAA/xgYGP/29vb/9PT0//b29v/39/f/8/Pz//r6+v/y8vL/+fn5//T09P/R0dH/r6+v/+7u7v/6+vr/vb29/ycnJ/8xMTH/FxcX/3R0dP/W1tb//Pz8//Dw8P/6+vr/9PT0//X19f/4+Pj/cXFx/wAAAP8AAAD/AAAA/wAAAP8AAAD/Kysr/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8rKyv/AAAA/wAAAP8AAAD/AAAA/wAAAP9ycnL/9/f3//X19f/09PT/+fn5//Dw8P/7+/v/uLi4/1BQUP8SEhL/KCgo/xkZGf++vr7/dnZ2/wAAAP8AAAD/IyMj/yYmJv8DAwP/QUFB/4SEhP+fn5//rKys/5GRkf9CQkL/AAAA/wAAAP8AAAD/AAAA/wAAAP8qKir/MjIy/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8sLCz/Kysr/wAAAP8AAAD/AAAA/wAAAP8AAAD/MzMz/3x8fP+Tk5P/hISE/2ZmZv8iIiL/BAQE/y4uLv8ZGRn/AAAA/wAAAP+Wlpb/4uLi/yQkJP8AAAD/AAAA/wkJCf8iIiL/BwcH/wAAAP8AAAD/AAAA/wAAAP8QEBD/AAAA/wAAAP8AAAD/AAAA/wAAAP9hYWH/GBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8ZGRn/ZWVl/wAAAP8AAAD/AAAA/wAAAP8AAAD/FhYW/wAAAP8AAAD/AAAA/wAAAP8ZGRn/HR0d/wEBAf8AAAD/AAAA/0hISP/s7Oz/+/v7/9HR0f8JCQn/AAAA/wAAAP8BAQH/BgYG/wAAAP8AAAD/AAAA/zw8PP8ZGRn/AAAA/wAAAP8AAAD/AAAA/wAAAP9sbGz/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/XV1d/wAAAP8AAAD/AAAA/wAAAP8AAAD/Hx8f/zMzM/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/IiIi/+Xl5f/7+/v/9PT0//f39/+1tbX/CAgI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wUFBf8gICD/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/QkJC/wAAAP8AAAD/AAAA/wAAAP8AAAD/IyMj/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8XFxf/zc3N//f39//z8/P/9fX1//b29v/19fX/j4+P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8XFxf/DQ0N/wAAAP8AAAD/AAAA/wAAAP9WVlb/AAAA/wAAAP8AAAD/AAAA/xcXF/8zMzP/MTEx/xsbG/8AAAD/AAAA/wAAAP8AAAD/QUFB/wAAAP8AAAD/AAAA/wAAAP8UFBT/Dg4O/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+xsbH/9fX1//b29v/19fX/+Pj4//T09P/29vb/09PT/xUVFf+Li4v/HR0d/wAAAP8AAAD/AAAA/wAAAP8EBAT/Dg4O/wAAAP8AAAD/AAAA/xISEv+IiIj/AAAA/wAAAP8AAAD/BQUF/yYmJv8AAAD/AAAA/xcXF/8dHR3/AAAA/wAAAP8HBwf/oaGh/wgICP8AAAD/AAAA/wAAAP8SEhL/CgoK/wAAAP8AAAD/AAAA/wAAAP82Njb/hoaG/x0dHf/r6+v/9vb2//T09P/4+Pj/8fHx//n5+f/09PT/7+/v/4KCgv9ERET/W1tb/wAAAP8AAAD/AAAA/xAQEP8kJCT/CAgI/wAAAP8AAAD/AAAA/wAAAP9SUlL/CgoK/wAAAP8AAAD/IyMj/wAAAP8AAAD/AAAA/wAAAP8pKSn/AAAA/wAAAP8iIiL/Pj4+/wAAAP8AAAD/AAAA/wAAAP8ICAj/GRkZ/w0NDf8AAAD/AAAA/wAAAP9iYmL/VVVV/3p6ev/19fX/9PT0//n5+f/w8PD//v7+//Dw8P/4+Pj/9vb2/15eXv8oKCj/FhYW/wAAAP8AAAD/AAAA/wEBAf8dHR3/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn/c3Nz/wAAAP8AAAD/JiYm/wAAAP8AAAD/AAAA/wAAAP8tLS3/AQEB/wAAAP+Dg4P/RkZG/wAAAP8AAAD/AAAA/wAAAP8AAAD/JCQk/wAAAP8AAAD/AAAA/wAAAP8QEBD/IiIi/3p6ev/29vb/+Pj4//Hx8f/9/f3/7u7u//r6+v/z8/P/9fX1/+/v7/9ERET/AAAA/wAAAP8AAAD/AAAA/wAAAP8eHh7/FxcX/wAAAP8AAAD/AAAA/wQEBP+IiIj/6+vr/wwMDP8PDw//Ghoa/wAAAP8AAAD/AAAA/wAAAP8EBAT/Jycn/wYGBv/p6en/j4+P/wgICP8AAAD/AAAA/wAAAP8lJSX/DQ0N/wAAAP8AAAD/AAAA/wAAAP8BAQH/bGxs//j4+P/19fX/8/Pz//r6+v/u7u7//Pz8//Ly8v/39/f/9vb2//Pz8//5+fn/jIyM/wMDA/8AAAD/AAAA/wAAAP8CAgL/MTEx/wAAAP8AAAD/HR0d/8XFxf/29vb/8/Pz/2BgYP8oKCj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/IiIi/0xMTP/z8/P/9vb2/8XFxf8cHBz/AAAA/wAAAP8xMTH/AAAA/wAAAP8AAAD/AAAA/xEREf+ysrL/+vr6//Pz8//29vb/9/f3//Ly8v/7+/v/8/Pz//j4+P/19fX/9fX1//f39//z8/P/+fn5/7i4uP9QUFD/GBgY/wAAAP8AAAD/bm5u/7a2tv+CgoL/bm5u//X19f/19fX/9/f3/5+fn/8kJCT/AAAA/w4ODv8FBQX/AAAA/xEREf8AAAD/EBAQ/5iYmP/39/f/9fX1//X19f9ycnL/oKCg/9HR0f9lZWX/AAAA/wAAAP8pKSn/cXFx/9TU1P/5+fn/8/Pz//f39//19fX/9fX1//j4+P/y8vL/9vb2//X19f/29vb/9fX1//X19f/29vb/9fX1//b29v/19fX/2tra/1paWv8AAAD/eXl5//X19f/29vb/9fX1//X19f/19fX/9fX1/7S0tP8AAAD/AAAA/3V1df8CAgL/AAAA/35+fv8AAAD/AAAA/5iYmP/19fX/9fX1//X19f/19fX/9vb2//X19f9jY2P/BgYG/4CAgP/s7Oz/9fX1//b29v/19fX/9vb2//X19f/19fX/9fX1//X19f/29vb/9/f3//T09P/29vb/9vb2//X19f/39/f/9PT0//f39//19fX/9vb2//b29v+YmJj/p6en//T09P/39/f/9fX1//b29v/29vb/7Ozs/xoaGv8AAAD/Ozs7/2VlZf8FBQX/BQUF/1hYWP9CQkL/AAAA/xISEv/g4OD/9vb2//b29v/19fX/9/f3//T09P+goKD/vb29//b29v/29vb/9PT0//f39//09PT/9/f3//X19f/29vb/9vb2//X19f/39/f/8fHx//j4+P/09PT/9fX1//f39//y8vL/+vr6//Ly8v/4+Pj/9PT0//X19f/39/f/8vLy//r6+v/y8vL/+Pj4//X19f/19fX/2tra/wcHB/8HBwf/HBwc/1ZWVv8dHR3/FBQU/3BwcP8WFhb/CgoK/wgICP/Ly8v/9fX1//X19f/4+Pj/8vLy//r6+v/y8vL/9/f3//X19f/09PT/+Pj4//Hx8f/6+vr/8vLy//f39//19fX/9PT0//j4+P/y8vL//Pz8//Hx8f/39/f/9vb2//Ly8v/7+/v/7u7u//39/f/x8fH/9/f3//b29v/z8/P/+/v7/+7u7v/7+/v/8vLy//b29v/39/f/v7+//wAAAP8AAAD/AAAA/xoaGv8AAAD/AAAA/x8fH/8AAAD/AAAA/wAAAP+ysrL/9/f3//f39//y8vL//Pz8/+/v7//7+/v/8vLy//b29v/39/f/8fHx//z8/P/v7+//+/v7//Pz8//29vb/9/f3//Hx8f/8/Pz/7u7u//r6+v/z8/P/9fX1//n5+f/w8PD//f39/+7u7v/6+vr/8/Pz//X19f/5+fn/7+/v//39/f/u7u7/+fn5//T09P/09PT/4ODg/wkJCf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wcHB//Y2Nj/9PT0//T09P/6+vr/7+/v//39/f/v7+//+fn5//X19f/z8/P/+vr6/+7u7v/9/f3/7+/v//n5+f/19fX/8/Pz//v7+//u7u7//Pz8//Hx8f/4+Pj/9vb2//Pz8//7+/v/7u7u//z8/P/x8fH/9/f3//b29v/z8/P/+/v7/+7u7v/8/Pz/8vLy//b29v/39/f/0tLS/wAAAP8ZGRn/AAAA/wAAAP8AAAD/AAAA/wAAAP8NDQ3/GRkZ/wAAAP/IyMj/9/f3//f39//y8vL//Pz8/+/v7//7+/v/8/Pz//b29v/39/f/8fHx//z8/P/u7u7/+/v7//Pz8//29vb/+Pj4//Hx8f/8/Pz/8vLy//j4+P/19fX/9fX1//f39//y8vL/+vr6//Hx8f/4+Pj/9PT0//X19f/39/f/8/Pz//r6+v/y8vL/+Pj4//X19f/19fX/29vb/wAAAP8cHBz/IiIi/wAAAP89PT3/QUFB/wAAAP84ODj/DAwM/wAAAP/Q0ND/9fX1//X19f/4+Pj/8vLy//r6+v/y8vL/9/f3//X19f/09PT/+Pj4//Hx8f/6+vr/8vLy//f39//19fX/9PT0//j4+P/y8vL/+Pj4//T09P/39/f/9vb2//X19f/4+Pj/8/Pz//j4+P/09PT/9vb2//b29v/19fX/9/f3//Pz8//4+Pj/9PT0//b29v/29vb/9PT0/xsbG/8JCQn/NjY2/1NTU//19fX/9vb2/0ZGRv89PT3/AQEB/xEREf/x8fH/9vb2//b29v/19fX/+Pj4//Pz8//39/f/9fX1//b29v/29vb/9PT0//j4+P/z8/P/9/f3//X19f/29vb/9vb2//T09P/4+Pj/9vb2//X19f/29vb/9vb2//b29v/29vb/9fX1//b29v/19fX/9vb2//b29v/19fX/9vb2//X19f/29vb/9fX1//b29v/29vb/9vb2/3BwcP8TExP/ISEh/93d3f/29vb/9vb2/9PT0/8uLi7/AQEB/2NjY//19fX/9vb2//b29v/19fX/9vb2//X19f/29vb/9fX1//b29v/29vb/9fX1//b29v/19fX/9vb2//X19f/29vb/9vb2//X19f/29vb/8/Pz//j4+P/19fX/9vb2//f39//09PT/+fn5//Pz8//4+Pj/9fX1//b29v/39/f/8/Pz//n5+f/z8/P/9/f3//X19f/19fX/9/f3/9DQ0P8LCwv/fX19//f39//19fX/9fX1//f39/9zc3P/Dg4O/8zMzP/39/f/9fX1//X19f/39/f/8/Pz//n5+f/z8/P/9/f3//b29v/19fX/+Pj4//Pz8//5+fn/8/Pz//f39//29vb/9fX1//j4+P/z8/P/+/v7//Ly8v/39/f/9vb2//T09P/5+fn/8fHx//v7+//y8vL/9/f3//b29v/09PT/+vr6//Hx8f/6+vr/8/Pz//f39//39/f/9PT0//n5+f9qamr/8vLy//Pz8//39/f/9/f3//Pz8//o6Oj/aWlp//r6+v/z8/P/9/f3//f39//z8/P/+vr6//Hx8f/6+vr/9PT0//b29v/39/f/8/Pz//v7+//w8PD/+vr6//T09P/29vb/9/f3//Ly8v/7+/v/7u7u//v7+//z8/P/9fX1//n5+f/w8PD//v7+/+7u7v/7+/v/9PT0//X19f/5+fn/8PDw//7+/v/v7+//+vr6//T09P/19fX/+fn5//Dw8P/8/Pz/7+/v//r6+v/19fX/9PT0//r6+v/v7+///Pz8//Dw8P/5+fn/9fX1//T09P/6+vr/7+/v//7+/v/w8PD/+fn5//b29v/09PT/+/v7/+7u7v/+/v7/8PDw//n5+f/19fX/8/Pz//v7+//u7u7/";
       
 Bitmap bitmapm = new Bitmap(Convert.FromBase64String(bigstring));
 c_canvas.DrawImage(bitmapm, new Cosmos.System.Graphics.Point(48, 48));`


output very noizeeeeee. cannot identify image


here original image.

![cerberus-hades-greek-mythology-dog- bmp](https://user-images.githubusercontent.com/20703404/81504332-2fd81a80-9306-11ea-8025-d83aef653c18.jpg)

**Comment by quajak** [comment]
This was fixed #1316
