### ISSUE TITLE
Are there printer and other device drivers to interface with hardware?

### ISSUE THREAD

**Issue by camelCaseCo** [CosmosOS/Cosmos#1321]
I was wondering recently, whether it would be possible to interface with printers using CosmosOS. Is this possible? Do drivers exist for it? If so, how could I use them? Thanks!

**Comment by quajak** [comment]
Interfacing with printers is currently not implemented.

**Comment by camelCaseCo** [comment]
Okay, thanks. Will it ever be implemented? If so, is there a set date or approximate?

**Comment by Shadowplays4k** [comment]
The best you could get currently is creating your own implementation of it

**Comment by camelCaseCo** [comment]
That seems pretty hard, do you know of anyone else who has done it? (thanks though :D )

**Comment by quajak** [comment]
Its not planned, so it would not be implemented any time soon.

**Comment by camelCaseCo** [comment]
Ok. As a side note, are there any help resources that you know of to help me do that? If not thats perfectly fine.

**Comment by quajak** [comment]
I dont know any resources for developing a printer driver. For questions about how to do certain things in cosmos, feel free to ask in the gitter chat.

**Comment by camelCaseCo** [comment]
Alright, thanks! I'll close this now.
