### ISSUE TITLE
How to make a working installer?

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1322]
Hello.

I'm wan't to make an installer to my OS, because OS loads only from flash drive (ISO). 
In general, I need the OS to boot from the HDD.

**Comment by KM198912** [comment]
if you have a usb to hdd adapter you can use rufus to write the iso to hdd and then place it in the computer you need

**Comment by Arawn-Davies** [comment]
This would involve installing a bootloader (SYSLINUX) onto the MBR of the hard drive that will in turn boot the OS kernel (kernel.bin iirc)

While this is doable, there's not much point trying to do so until the operating system can load precompiled programs off the HDD or storage medium.
