### ISSUE TITLE
Regex in Cosmos

### ISSUE THREAD

**Issue by zaiinn-x** [CosmosOS/Cosmos#1323]
I am trying to use `string input = Console.ReadLine();
                var args = Regex.Matches(input, @"[\""].+?[\""]|[^ ]+")
                                        .Cast<Match>()
                                        .Select(m => m.Value)
                                        .ToArray();`
as input in the OS. This gives me this error `1>IL2CPU : error : Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.`

Is there another way to use Regex in Cosmos?

My goal is to split the `string input` by spaces unless it is in quotes.

**Comment by quajak** [comment]
Did you try without the following linq methods (`Cast`, `Select`)?

**Comment by charlesbetros** [comment]
Regex is not currently supported. It needs some plugs.
