### ISSUE TITLE
Desktop in CosmosOS

### ISSUE THREAD

**Issue by amxrmxhdx** [CosmosOS/Cosmos#1326]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Desktop / GUI

#### Expected Behaviour - What do you think that should happen?
I want to make a windowmanager/desktop environment with a cursor

#### Actual Behaviour - What unexpectedly happens?
Nothing happened yet

#### Reproduction - How did you get this error to appear?
Nothing happened yet

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Cosmos libraries/kits

**Comment by KM198912** [comment]
As far as i am aware currently there is no windowmanager, but you can implement your own using the available drivers (CGS/VBE/VGA)
