### ISSUE TITLE
Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.

### ISSUE THREAD

**Issue by radeberyt** [CosmosOS/Cosmos#1327]
My code (Kernel.cs):
using System;
using System.Collections.Generic;
using System.Text;
using System.Security.Cryptography;
using Sys = Cosmos.System;
using System.IO;
using Cosmos.Core;
using CatomOS.Extensions;
using Cosmos.System.Graphics;
using Cosmos.HAL;
using Cosmos.Core.IOGroup;
using System.Linq;

namespace CatomOS
{
    public class Kernel : Sys.Kernel
    {
        public static string login;
        public static string password;
        public static bool running;
        Sys.FileSystem.CosmosVFS fs;
        protected override void BeforeRun()
        {
            Console.Clear();
            Console.WriteLine("\nBooting...");
            ConsoleManager.WriteLineInfo("Starting services...");
            fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            ConsoleManager.WriteLineOK("File system initiated successfully.");
            ConsoleManager.WriteLineOK("Successfully started services.");
            if (!File.Exists(@"0:\System\NoInstall.cse") || !Directory.Exists(@"0:\Programs"))
            {
                running = false;
                ConsoleManager.WriteLineInfo("Running installer...");
                ConsoleManager.WriteLineInfo("Creating directories...");
                Directory.CreateDirectory(Directory.GetCurrentDirectory() + "System");
                Directory.CreateDirectory(Directory.GetCurrentDirectory() + "Programs");
                ConsoleManager.WriteLineOK("System files created");
                ConsoleManager.WriteLineInfo("Create a new user: ");
                Console.Write("Enter username: ");
                var newUsername = Console.ReadLine();
                Console.Write("Enter password: ");
                var newPassword = Console.ReadLine();
                ConsoleManager.WriteLineInfo("Created a new user with name " + newUsername);
                ConsoleManager.WriteLineInfo("Creating system files...");
                File.Create(@"0:\System\NoInstall.cse");
                File.Create(@"0:\System\user.sys");
                File.WriteAllText(@"0:\System\user.sys", newUsername + "\n" + newPassword);
                ConsoleManager.WriteLineOK("Successfully installed Catomos! Press any key to reboot.");
                Console.ReadKey();
                Sys.Power.Reboot();

            }
            else
            {
                a:
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write("\n   Username >> ");
                login = Console.ReadLine();
                Console.Write("   Password >> ");
                password = Console.ReadLine();
                string usernameInFile = File.ReadLines(@"0:\System\user.sys").First();
                string passwordInFile = File.ReadLines(@"0:\System\user.sys").ElementAtOrDefault(1);
                if (login == usernameInFile && password == passwordInFile)
                {
                    running = true;
                }
                else
                {
                    ConsoleManager.WriteLineError("Wrong username/password!");
                    goto a;
                }
            }
        }

        protected override void Run()
        {
            if (!running)
            {
                return;
            }
            else
            {
                BeforeCommand();
                var input = Console.ReadLine();
                switch (input)
                {
                    case "help":
                        Console.ForegroundColor = ConsoleColor.Blue;
                        Console.Write("\n[HELP]");
                        Console.ResetColor();
                        Console.Write(" REBOOT - Reboot current PC\n");
                        Console.ForegroundColor = ConsoleColor.Blue;
                        Console.Write("\n[HELP]");
                        Console.ResetColor();
                        Console.Write(" SHUTDOWN - Shutdown current PC\n");
                        Console.ForegroundColor = ConsoleColor.Blue;
                        Console.Write("\n[HELP]");
                        Console.ResetColor();
                        Console.Write(" LS - All files/directories in current directory\n");
                        Console.ForegroundColor = ConsoleColor.Blue;
                        Console.Write("\n[HELP]");
                        Console.ResetColor();
                        Console.WriteLine(" CURDIR - Get current directory");
                        break;
                    case "curdir":
                        ConsoleManager.WriteLineInfo(Directory.GetCurrentDirectory());
                        break;
                    case "reboot":
                        ConsoleManager.WriteLineOK("Rebooting...");
                        Sys.Power.Reboot();
                        break;

                    case "shutdown":
                        ConsoleManager.WriteLineOK("Shutdowning...");
                        Sys.Power.Shutdown();
                        break;
                    case "ls":
                        string Adr = Directory.GetCurrentDirectory();
                        string[] Directories = new string[Directory.GetDirectories(Adr).Length];
                        if (Directories.Length > 0)
                            Directories = Directory.GetDirectories(Adr);
                        else

                            Directories[0] = "No directories/files found.";
                        string[] Files = new string[Directory.GetFiles(Adr).Length];
                        if (Files.Length > 0)
                            Files = Directory.GetFiles(Adr);
                        else
                            Files[0] = "No files found.";

                        foreach (var item in Directories)
                        {
                            foreach (var files in Files)
                            {
                                ConsoleManager.WriteLineInfo(item + " " + files);
                            }
                        }
                        break;
                }
            }
          }
            public static void BeforeCommand()
            {
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.Write("\ncatom-pc");
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write("@");
                Console.Write(login);
                Console.Write(">");
                Console.ForegroundColor = ConsoleColor.White;
            }
        }
    }

Output:
1>CatomOS -> C:\Users\radeber\source\repos\CatomOS\CatomOS\bin\Debug\netcoreapp2.0\cosmos\CatomOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\radeber\source\repos\CatomOS\CatomOS\bin\Debug\netcoreapp2.0\cosmos\CatomOS.dll
1>IL2CPU : error : Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.
1>   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 559
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:03.3087994

**Comment by zarlo** [comment]
i dont think anything in System.Linq is pluged as alot of it is done in native code
