### ISSUE TITLE
Connecting to WiFi?

### ISSUE THREAD

**Issue by bladems** [CosmosOS/Cosmos#1328]
I just have a question: Is it possible to configure WiFi settings and make HTTP/HTTPS requests? I would love to do something similar to `apt-get install` and things like that for internet installations from files hosted on a webserver.

**Comment by quajak** [comment]
Networking is still in very early development and using HTTP is currently not possible.

**Comment by bladems** [comment]
Ok. Is there any specific end date estimate for this yet? I know about the roadmap and milestones, but is there a date estimate? Also, is there a way for me to do this myself? Thanks a lot!

**Comment by quajak** [comment]
There is no date estimate. AuraOS has implemented more networking and from there you could build up to HTTP/HTTPS.
