### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by Luzzle** [CosmosOS/Cosmos#1329]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Actual OS
#### Expected Behaviour - What do you think that should happen?
Keyboard works normally, all key inputs are correct

#### Actual Behaviour - What unexpectedly happens?
For some reason all key inputs are incorrect, the issue does not occur on VMWare or Virtualbox, only when i run the OS on physical hardware on my laptop.

#### Reproduction - How did you get this error to appear?
Installing the OS on a physical laptop

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit

**Comment by KM198912** [comment]
i have a similiar issue with the mouse you might want to see if you can implement the last push from the PS2 Branch and see if it makes any difference

**Comment by Luzzle** [comment]
How could i do this?

**Comment by KM198912** [comment]
look at this commit, red is what has been removed and green what has been added, make those changes before compiling the devkit https://github.com/CosmosOS/Cosmos/commit/87e81c209bf5b0b59f2c4b95f9153db4533ba025

**Comment by Luzzle** [comment]
will do, ill try that
