### ISSUE TITLE
File system problems (Formatting / File creation)

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1331]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File System

#### Expected Behaviour - What do you think that should happen?
It should format the virtual hard drive and should normally create files/directories

#### Actual Behaviour - What unexpectedly happens?
It seems to format, but i get an "aFirstCluster" exception when creating a file/directory

#### Reproduction - How did you get this error to appear?
I've first initialized my FAT file system :
```
VFSManager.RegisterVFS(Reference.FAT);
Reference.FAT.Initialize();
```
Reference.FAT is `public static CosmosVFS FAT = new CosmosVFS();`

Then I formatted the hard drive like this:
`Reference.FAT.Format(Reference.RootPath.Replace(@":\", string.Empty), "FAT32", true);`
Reference.RootPath is `0:\`, but I removed the `:\` part to only get the drive ID.

Then, after the format has finished, I've just tried to create a new file/directory.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by Jaiganeshkumaran** [comment]
If you're using a virtual machine you'll need to set the disk to [this](https://github.com/CosmosOS/Cosmos/raw/master/Build/VMWare/Workstation/Filesystem.vmdk) you are on VMware and [this](https://github.com/CosmosOS/Cosmos/raw/master/Build/HyperV/Filesystem.vhdx) if you are on Hyper-V (VirtualBox is not currently supported.)

**Comment by AnErrupTion** [comment]
@Jaiganeshkumaran The whole point of my code is to NOT use these files (that's why I've tried to format the VHD)

**Comment by KM198912** [comment]
Using the code below 
`        public static void FormatHDD()
            {
           vFS.Format(@"0", "FAT32", true);
            }` 
i was able to format a newly created vmdk and after write files to it

**Comment by CaydendW** [comment]
I am very sorry I was late, and I'm not sure this will help much by if you're using a Virtual Machine to run the OS try change the hard drive controller from IDE to SATA or SCSI. It doesn't work on IDE controller. That was what fixed my issue. Hope this helps!

**Comment by TheUnknown-007** [comment]
Simple question:
How do I format and use the disk, all through cosmos os?
Like making an installer.

Any help will be appreciated, thanks a lot :)
