### ISSUE TITLE
Debugger Failed to Start (System.Reflection.TypeExtensions failed to load.)

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1332]
#### Area of Cosmos - What area of Cosmos are we dealing with?

The Debugger

#### Expected Behaviour - What do you think that should happen?

A VMWare Instance should start with Cosmos's prefilled code.

(Echoing the user input back to the user)

#### Actual Behaviour - What unexpectedly happens?

The debugger gives the error:
  Unexpected exception during Attach
  System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.TypeExtentions, Version=4.0.0.0, Culture=neutral, PublicKeyToken b03f5f7f11d50a3a'
    at DapperExtensions.DapperExtensionsConfiguration.<>c__DisplayClass19_0.<GetMapType>b__0(Assembly a)
   at
 DapperExtensions.DapperExtensionsConfiguration.GetMapType(Type entityType)
  at
 DapperExtensions.DapperExtensionsConfiguration.GetMap(Type entityType)
  at
  DapperExtensions.DapperExtensionsConfiguration.GetMap[T]()
  at
 DapperExtensions.DapperImplementor.GetList[T](DbConnection connection, Object predicate, IList`1 sort, DbTransaction transaction, Nullable `1 commandTimeout, Boolean buffered)
 at
 DapperExtensions.DapperExtensions.GetList[T](DbConnection connection, Object predicate, IList`1 sort, DbTransacti……
 (In angle brackets: truncated)

#### Reproduction - How did you get this error to appear?

By starting the Debugger "Cosmos".

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit Versions:

20190628,
and
20190508,

#### Attempted Fixes

Installing System.Reflection.TypeExtensions version 4.0.0 and 4.7.0

2x Reinstalling userkit.
Installing older version of userkit.
6x Creating a new project.

**Comment by AnErrupTion** [comment]
Try to disable the debugger in the project's properties (right click on the project -> Properties) then find an option to disable debugging, then try to run the code again.

**Comment by TFTWPhoenix** [comment]
Didn't work :(
I went into "Project -> Properties -> Cosmos (New) -> IL2CPU" unchecked Enable Debugging and started with a profile set to not launch a process.
I noticed a new warning though:
Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework, Version=v4.6.2, .NETFramework, Version=v4.7, .NETFramework, Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatable with your project.
("mpatable with your project" was cut off my 1080p screen at 100% scaling.)

**Comment by TFTWPhoenix** [comment]
Same error.

**Comment by TFTWPhoenix** [comment]
Just so you know, I can develop on a separate Win10 machine. It works perfectly there.

**Comment by quajak** [comment]
Can you try manually adding System.Reflection.TypeExtensions via nuget?

**Comment by AdhithAdhi** [comment]
I have the same issue build is successful but debugger says file not found exception.
I got this error after updating to the new visual studio now I can't work.

**Comment by zaiinn-x** [comment]
Try installing an older version of VS2019. https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

I would get version 16.4.3.

**Comment by AdhithAdhi** [comment]
> Which VS version are you on now?

am currently using the latest vs 2019. 
I just updated last week
Installing the older version suck all my data (-_-).

**Comment by TFTWPhoenix** [comment]
I haven't checked this in a while.
I did try using nuget. Got 4.0.0 and 4.7.0 (in separate projects) same error. 
I'm gonna try older vs2019 now.

**Comment by TFTWPhoenix** [comment]
It worked. Older VS built absolutely fine. No nuget installing needed. Thanks a ton for your help!

**Comment by quajak** [comment]
I think this issue should stay open since it wont be possible for always to stay on older VS versions

**Comment by quajak** [comment]
This should be fixed on the newest master. So downgrading to an older version of Visual Studio is no longer required.

**Comment by JurijTSL** [comment]
I am having the same problem with the updated one.
![image](https://user-images.githubusercontent.com/30342756/100337319-8291cf00-2fd7-11eb-86c5-4e2247f1aaf7.png)

**Comment by quajak** [comment]
This is a different issue, your csproj seems to be broken. Please open an issue if this occurs to a new kernel.

**Comment by JurijTSL** [comment]
I have created a new project and it still happens.

**Comment by quajak** [comment]
Then please open a new issue on github.
