### ISSUE TITLE
How much characters do fit into the console?

### ISSUE THREAD

**Issue by LosSkillos** [CosmosOS/Cosmos#1350]
How do I change the hight or width, or just how much characters do fit in the basic resolution?
Is there something like 'mode' in windows cmd?

**Comment by quajak** [comment]
After https://github.com/CosmosOS/Cosmos/pull/913 is merged, multiple different VGA text "resolutions" will exist, changing the number of characters per screen. There will also be font support, which can change the height of every character. VGA only supports 8bit wide characters.

**Comment by LosSkillos** [comment]
Ok got it, the console is 80x25
