### ISSUE TITLE
ISO Failed to Build

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1355]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Building the OS.

#### Expected Behaviour - What do you think that should happen?

An explorer window should open showing the completed ISO image for the OS.

#### Actual Behaviour - What unexpectedly happens?

![err](https://user-images.githubusercontent.com/61560519/84094357-80986d00-a9b1-11ea-8435-af8f2cb1d13b.png)

The System could not find the file specified.

#### Reproduction - How did you get this error to appear?

Selecting ISO Image in profiles and starting a debug.
Also worth noting that selecting release gives a not supported error.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 20190628

**Comment by quajak** [comment]
This is currently the correct behaviour. The iso image should be generated. To disable debug, look under project properties.

**Comment by TFTWPhoenix** [comment]
When I use the ISO at C:\Users\<USER>\source\repos\<PROJECT>\<PROJECT>\bin\Debug\netcoreapp2.0\cosmos\<PROJECT>.iso in a blank VMWare Virtual Machine it still shows waiting for debugger connection. No new ISO was generated.

**Comment by quajak** [comment]
You have to disable debug in the project properties

**Comment by TFTWPhoenix** [comment]
Where I disabled IL2CPU Debugging.

**Comment by quajak** [comment]
You have to disable Remote Debugging.

**Comment by TFTWPhoenix** [comment]
Thank you so much! Works perfectly.
