### ISSUE TITLE
Color.Red or any other does not work

### ISSUE THREAD

**Issue by LosSkillos** [CosmosOS/Cosmos#1357]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
Color.<color> should not show up as a mistake

#### Actual Behaviour - What unexpectedly happens?
Visual studio shows color.<anycolorhere> as a mistake

#### Reproduction - How did you get this error to appear?
I tried using graphics

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by quajak** [comment]
What do you mean with mistake?

**Comment by LosSkillos** [comment]
> What do you mean with mistake?

Visual studio says: 'Color' does not exist in current context...

**Comment by LosSkillos** [comment]
sorry my bad, I didn't use System.Drawing
