### ISSUE TITLE
Dev Kit Installer Error

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1360]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Dev kit Installer

#### Expected Behaviour - What do you think that should happen?

The dev kit should install

#### Actual Behaviour - What unexpectedly happens?

![issue](https://user-images.githubusercontent.com/61560519/84618439-d7adae80-ae97-11ea-8e40-76928c52caae.jpg)

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in C:\Users\TFTWPhoenix\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in C:\Users\TFTWPhoenix\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in C:\Users\TFTWPhoenix\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

#### Reproduction - How did you get this error to appear?

Going to Install-VS2019.bat and selecting Run as Administrator.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev Kit (Commit 8141)

**Comment by EliaSulimanov** [comment]
Please install DapperExtensiin nuget package and see if it solves the problem.

**Comment by quajak** [comment]
Rename the directory Cosmos-master to Cosmos

**Comment by TFTWPhoenix** [comment]
Neither renaming or installing DapperExtensions worked. (DapperExtensions was installed in Build.sln the one erroring out.)

**Comment by EliaSulimanov** [comment]
Try to:  
- Run the installation not as administrator.
- In vs2019 go to Tools->Options->Environment->Extensions Manager, and there check the "load per user extensions when running as administrator".

**Comment by quajak** [comment]
Can you try running it without admin and can you please post the entire log in a pastebin?

**Comment by TFTWPhoenix** [comment]
Here is the pastebin (run without administrator): https://pastebin.com/SYGYdCTg
And "Load Per User Extensions When Running as Administrator was already checked.

**Comment by quajak** [comment]
This is most likely the problem
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3032,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Users\TFTWPhoenix\Downloads\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
```

**Comment by TFTWPhoenix** [comment]
How would I "remove the mark of the web"?

**Comment by charlesbetros** [comment]
Right click on the file and select Properties. There should be an "Unblock"
button on the bottom right.

**Comment by TFTWPhoenix** [comment]
Ok, so after removing the mark of the web the new log is here:
https://pastebin.com/AXfagQvf
No references to mark of the web. Will you please make sure I'm not missing something?

**Comment by charlesbetros** [comment]
It looks like you manually installed Dapper and DapperExtensions from nuget? Cosmos includes the appropriate version of these already. The version you installed is not compatible.

**Comment by TFTWPhoenix** [comment]
Thank you all so much. It works perfectly now. I had Dapper and DapperExtensions manually installed. I don't undo things that don't work. Fix was removing mark of the web. Nothing else.
