### ISSUE TITLE
Question: How can i reboot to a certain drive?

### ISSUE THREAD

**Issue by NezbednikSK** [CosmosOS/Cosmos#1366]
I know i already asked this on gitter, but i didn't get an answer so here goes.

I want to make a bootloader which lets you reboot to a certain drive ex. so i can reboot to windows 10 or windows 7.

Is this this possible?

edit: i want to make something like grub, except in cosmos

**Comment by EliaSulimanov** [comment]
You wish to create bootloader that is apart of cosmos project, or to make existing bootloader support loading cosmos aside with windows?

**Comment by NezbednikSK** [comment]
umm what

**Comment by Project-Magenta** [comment]
Try corert, it has built in support fpr compiling to UEFI.

**Comment by NezbednikSK** [comment]
i'm very confused
i was asking if it is possible to do something like this in cosmos

**Comment by EliaSulimanov** [comment]
Check this folder: "Users/Orvid/StructTest".

**Comment by NezbednikSK** [comment]
thank you, i will surely look into that
looks like it does what i need

**Comment by quajak** [comment]
Cosmos currently does not support rebooting to a certain drive.
