### ISSUE TITLE
Checking if a drive/partition was formatted using Cosmos'es FAT file system?

### ISSUE THREAD

**Issue by ascpixi** [CosmosOS/Cosmos#1367]
I'm making an OS, but I need some files to be copied over to the hard drive.
I want to ask the user if they want to actually format the drive and install those files, but I don't know how would I check if the drive has any files from other file systems or if it was actually formatted, without formatting it using the FAT file system.
I'm thinking of something like `Sys.FileSystem.VFS.VFSManager.WasFormattedUsingVFS()` or something like that.

**Comment by EliaSulimanov** [comment]
You can create new dummy file that would be used as a flag.

**Comment by Arawn-Davies** [comment]
If you want to check whether a filesystem is FAT or not, I made a small fdisk-style program some time ago which checks the filesystems ID type (0Ch for FAT32 with LBA addressing)
![image](https://user-images.githubusercontent.com/19764552/86276892-a76f4b00-bbcd-11ea-93fd-9adf579e23e1.png)

whole load of filesystem types and their respective IDs are on https://en.wikipedia.org/wiki/Partition_type#List_of_partition_IDs
although each OS usually has a different style of creating a FAT on a partition with many different IDs and stuff


Check my repo for more, bit outdated but it does the trick https://github.com/Siaranite-Solutions/SDFS

**Comment by MishaTY** [comment]
Fixed in cosmosvfs update pr
