### ISSUE TITLE
Compiling and running on hardware.

### ISSUE THREAD

**Issue by tb100** [CosmosOS/Cosmos#1368]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling code to ISO file, and running it on hardware.

#### Expected Behaviour - What do you think that should happen?
The ISO should compile correctly with no warnings, should flash correctly to the USB drive, and run on hardware.

#### Actual Behaviour - What unexpectedly happens?
I get two warnings, `-rock has same effect as -rational-rock on this platform.` and `creating filesystem that does not conform to ISO-9660.`. When I try to flash to the USB, I get an error about a missing file partition, and when I try to run it on my 2015 laptop, it says it can't boot.

#### Reproduction - How did you get this error to appear?
I get the error when running the project. (▶ Cosmos)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using Cosmos User Kit, and the code is in C#.

---
I'm not sure if these problems are related, but I just want to see if anyone knows what's going on. Thanks!

**Comment by Jaiganeshkumaran** [comment]
Ignore the warnings. Regarding the missing file partition error, do you try to read and write from your HDD/SSD? If so you need a FAT partition set up on the drive.

**Comment by tb100** [comment]
I am trying to read/write to the hard drive using System.IO. I'm using rufus 3.11.1678 and under "Format", I kept "File system", as it's default, "FAT32". Should I change this to "FAT"?

**Comment by Jaiganeshkumaran** [comment]
You don’t need to since Cosmos does support FAT. However, if you’re using GPT instead of MBR you won’t be able to read and write since the latest version of Cosmos release last year doesn’t support GPT.

**Comment by tb100** [comment]
The only option I have for "Partition scheme" is MBR.

**Comment by Jaiganeshkumaran** [comment]
That’s for the USB drive. What about the Hard Drive? Are you dual booting with an other operating system?

**Comment by tb100** [comment]
I'm dual booting with Windows 10. It's an HP Pavilion 2015. I do have an older Windows Vista PC too. I could try on that.

**Comment by Jaiganeshkumaran** [comment]
Use your Vista machine for Cosmos OS until the new version is out since Windows 10 uses the GPT partition scheme for your hard drive by default. There’re some apps that let you convert your GPT drive to MBR however, I don’t recommend you to do that since GPT has a lot of benefits.

**Comment by tb100** [comment]
Okay, I'll try that.

**Comment by tb100** [comment]
Okay! Thanks! It's working!
