### ISSUE TITLE
How to make a simple gui?

### ISSUE THREAD

**Issue by zalnaRs** [CosmosOS/Cosmos#1369]
#### Area of Cosmos - What area of Cosmos are we dealing with?
User Kit 20190628

how to make a simple  with background?

**Comment by tb100** [comment]
Cosmos has a built-in demo for graphics [here](https://github.com/CosmosOS/Cosmos/tree/master/Demos/CosmosGraphicSubsystem). You can draw rectangles, lines, points, and even bitmaps. Let me know if this works.

**Comment by zalnaRs** [comment]
Thanks its works!
