### ISSUE TITLE
Question: How do I mount drives and edit files?

### ISSUE THREAD

**Issue by CaydendW** [CosmosOS/Cosmos#1370]
#### Area of Cosmos - What area of Cosmos are we dealing with?
User kit

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190508

I want to be able to scan drives but when I try to run this:
 ```DriveInfo[] allDrives = DriveInfo.GetDrives();
                foreach (DriveInfo d in allDrives)
                {
                    Console.WriteLine("Drive {0}", d.Name);
                    Console.WriteLine("  Drive type: {0}", d.DriveType);
                    if (d.IsReady == true)
                    {
                        Console.WriteLine("  Volume label: {0}", d.VolumeLabel);
                        Console.WriteLine("  File system: {0}", d.DriveFormat);
                        Console.WriteLine(
                            "  Available space to current user:{0, 15} bytes",
                            d.AvailableFreeSpace);

                        Console.WriteLine(
                            "  Total available space:          {0, 15} bytes",
                            d.TotalFreeSpace);

                        Console.WriteLine(
                            "  Total size of drive:            {0, 15} bytes ",
                            d.TotalSize);
                    }```
The program just halts, it doesn't crash it just stops and lags. Am I missing something?
I am running it as an ISO in Hyper-V.

**Comment by quajak** [comment]
Have you tried running it using Bochs or Vmware?

**Comment by CaydendW** [comment]
I have tried on VMWare and it also doesn't work. I have the drive connected in Hyper-V but it's like it's not registering that it exists. Do I have to  mount it using cosmos or something. I'm relatively new so I don't know.

**Comment by quajak** [comment]
How are you getting `allDrives`?

**Comment by CaydendW** [comment]
Oh pardon me. I forgot that line. ```DriveInfo[] allDrives = DriveInfo.GetDrives();```

**Comment by quajak** [comment]
Did you try with first activating the filesystem? Also do you know which line it halts at approximately?

**Comment by CaydendW** [comment]
I don't know where it halts and how do I activate the file system. Also thank you for responding so quick.

**Comment by quajak** [comment]
To initialize the filesystem see https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#initiating-the-fat-driver

**Comment by CaydendW** [comment]
Thank you kindly. I'll respond with how it went soon.

**Comment by CaydendW** [comment]
Thank you very much for your help! It works perfectly after I formatted it with windows 10's file formater. Thank you for helping my inexperienced self through this.
