### ISSUE TITLE
Problem with character concatenation

### ISSUE THREAD

**Issue by zdimension** [CosmosOS/Cosmos#138]
If you try to concatenante a ```char``` with a ```string```, like this : 
```csharp
string str1 = "hello";
char ch1 = 'A';
string result = str1 + ch1;
```
It won't work, and it will crash ```Type 0x000C003A, MethodIndexes is null!``` (the "Type" value can vary).
The only way to make it work is to add ```.ToString()``` to the char like that : 
```csharp
string result = str1 + ch1.ToString();
```
It's very strange since char concat seems to have worked perfectly in previous builds.

**Comment by mterwoord** [comment]
Can you please verify that this problem still exists in the latest devkit? I tested your exact code and it seems to work just fine...
