### ISSUE TITLE
[Question] How can I build my OS using .NET Core CLI?

### ISSUE THREAD

**Issue by bogdanbankov** [CosmosOS/Cosmos#1380]
In issue #852 there was said that people can build OS from .NET Core CLI. How can I do this?

**Comment by quajak** [comment]
Did you try `dotnet run`?

**Comment by bogdanbankov** [comment]
It doesn't work

**Comment by quajak** [comment]
What happens?

**Comment by Project-Magenta** [comment]
You cannot. Cosmos does not currently support compiling directly outside of Visual Studio.
