### ISSUE TITLE
Enable installing with only bochs installed

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#139]
The installer checks for VMware. With our new bochs support, make sure that either vmware or bochs is installed..

**Comment by zdimension** [comment]
It seems that we can close the issue now (CosmosTask.cs, line 266).

**Comment by mterwoord** [comment]
Have you tested this?
(If not, I can do next week)

**Comment by charlesbetros** [comment]
Works on a fresh install of Windows 10 and VS 2015 and Bochs.
