### ISSUE TITLE
Cosmos BMP Exception

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1391]
When I try to make a Bitmap from my bmp file (put in a byte[]) I have this exception:
![image](https://user-images.githubusercontent.com/18724279/86965878-7ad8a780-c168-11ea-941d-9e3baf4a4362.png)

![image](https://user-images.githubusercontent.com/18724279/86966142-ec185a80-c168-11ea-9134-351368e6aad9.png)

I tried with and without compatibility option. The thing is the image from the GraphicTest is working so I don't know how to export my image

**Comment by quajak** [comment]
Can you try to catch the exception? Also what Bitmap ctor are you using?

**Comment by valentinbreiz** [comment]
When I put it in a try catch nothing happens :/
```
Setting FirstDataLookupTable to 
0x022C58E7
FirstDataLookupTable was set to 
0x022C58E7
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA device with speclevel ATAPI found, which is not supported yet!
Done initializing Cosmos.HAL.Global
KeyboardManager.AddKeyboard
Cls
Before Run
step one!

```
![image](https://user-images.githubusercontent.com/18724279/87061406-022b2700-c20c-11ea-8ede-bef08d0efa21.png)

**Comment by quajak** [comment]
Weird, cant really tell whats wrong. Can you please upload the image or reproducible code?

**Comment by valentinbreiz** [comment]
https://anonfiles.com/F5EfbbFfo6/Arrow_bmp
https://anonfiles.com/D2Ecb5Fao0/Arrow_cur
