### ISSUE TITLE
Broken link in Wiki (PSF to Base64 Converter)

### ISSUE THREAD

**Issue by typicalname0** [CosmosOS/Cosmos#1392]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Wiki

#### Expected Behaviour - What do you think that should happen?
A PSF to Base64 Converter

#### Actual Behaviour - What unexpectedly happens?
A broken link to the PSF to Base64 Converter

#### Reproduction - How did you get this error to appear?
In the https://github.com/CosmosOS/Cosmos/wiki/Somewhat-indepth-Canvas-Changes-explained page in the wiki, there is a link that goes to resources. When you click on it, the resources page shows fine (https://github.com/CosmosOS/Cosmos/wiki/Resources), but if you click on the "PSF to Base64 Converter", the Gofile has a message that says "This upload does not exist"

**Comment by valentinbreiz** [comment]
we will publish a tool soon for that

**Comment by Arawn-Davies** [comment]
This online utility can be used instead, https://base64.guru/converter/encode/file
just upload the PSF file and you'll get the base64 string which you can use.

At the moment, including files in the kernel is a bit buggy but it will be fixed.
