### ISSUE TITLE
Visual Studio Template

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#1401]
Is there a Visual Studio Template for vs2019. My vs cant find anyone searching cosmos

**Comment by valentinbreiz** [comment]
did you install Cosmos with the userkit or the devkit?

**Comment by quajak** [comment]
When looking for templates, be sure to be looking under All languages and All project types.

**Comment by furesoft** [comment]
userkit

**Comment by Arawn-Davies** [comment]
Are you still having this issue?

**Comment by furesoft** [comment]
yes

**Comment by devilAPI** [comment]
me2...

**Comment by quajak** [comment]
Can you confirm that the two cosmos VS extensions are installed and you are looking for cosmos under All languages and All project types?

**Comment by devilAPI** [comment]
fixed it, idk how but i fixed it

**Comment by devilAPI** [comment]
oh and make sure to use the normal, not the unstable build  of vs, that fixes a lot
