### ISSUE TITLE
I can't build my project in the latest user kit

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [CosmosOS/Cosmos#1405]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling and running

#### Expected Behaviour - What do you think that should happen?
It should compile in the latest user kit.

#### Actual Behaviour - What unexpectedly happens?
I get some package errors:

```
NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.

Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.	

Unable to find package Cosmos.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

Unable to find package Cosmos.System2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

#### Reproduction - How did you get this error to appear?
- Install the latest user kit and create a new project in Visual Studio.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit 20200708 on Visual Studio 2019 version

**Comment by EliaSulimanov** [comment]
Please try to right click on the solution and select "Restore NuGet Packages", and try restarting VS.
Also, did you start the build by hiting the "Start" button?

**Comment by Jaiganeshkumaran** [comment]
@EliaSulimanov I tried using 'Restore NuGet Packages' but it fails with the same error. I'm building the project using the build open not the start option.

**Comment by EliaSulimanov** [comment]
Please try to use the start option.
If it won't work, try to reinstall the userkit and let us know if any error messages appears

**Comment by quajak** [comment]
Select the Cosmos Nuget Feed

**Comment by Jaiganeshkumaran** [comment]
It's working now. Thanks!
