### ISSUE TITLE
Project Properties give error

### ISSUE THREAD

**Issue by katistix** [CosmosOS/Cosmos#1408]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Trying to make the example work.
#### Expected Behaviour - What do you think that should happen?
When I click on Project Properties the tab will open and I could change the settings of my project (to disable debug mode)

#### Actual Behaviour - What unexpectedly happens?
Project Properties give this text

> An error occurred trying to load the project properties window.  Close the window and try again.
> Value cannot be null.
> Parameter name: val

#### Reproduction - How did you get this error to appear?

The first time I installed Cosmos I got this.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using User Kit (Latest Release From GitHub)

**Comment by EliaSulimanov** [comment]
Can you tell what is the example use are tring to run?
Source code would be helpful too, remember the warp it with markdown ``` block
