### ISSUE TITLE
Feature Request: Linux Support

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1409]
Will Cosmos ever support Linux like it does Windows? For example I want to be able to use Cosmos like I can in Windows but on Ubuntu 20.04 LTS. Is this already in progress or not likely to happen? If this is a duplicate I'm sorry I couldn't find the original.

**Comment by asiawin** [comment]
You can't use COSMOS on Ubuntu because COSMOS is written in .NET Core, which is not supported in Ubuntu. And also, Visual Studio is not available for Ubuntu. There is Mono Framework, which is a port of .NET Framework and Core for Linux, but COSMOS won't work on that.

## Conclusion

Cosmos will not  work on linux

**Comment by Project-Magenta** [comment]
.NET Core is most certainly supported on Linux. Please check your facts.

**Comment by bartekmuzyk** [comment]
I will just post this link here so everyone can see that .NET Core actually works on linux:
https://docs.microsoft.com/pl-pl/dotnet/core/install/linux

**Comment by TFTWPhoenix** [comment]
@Project-Magenta thanks for the information. I'll use COSMOS in a Windows 10 VM.

**Comment by zarlo** [comment]
Cosmso should work on linux it just the build tools that need tot be ported

**Comment by asiawin** [comment]
Oh! I am not a .NET developer, so I don't know that. I should not comment on the issues that I don't know.

**Comment by Project-Magenta** [comment]
@zarlo my comment went into detail about everything

**Comment by Project-Magenta** [comment]
@Shadowplays4k why the dislike? i am not part of cosmos team, i am not responsible

**Comment by off-the-az** [comment]
I think Cosmos must work on linux and MacOS, cause if u wanna try to build own system in multiplatform system - u must make this kit multiplatform!!!

**Comment by AsertCreator** [comment]
> I think Cosmos must work on linux and MacOS, cause if u wanna try to build own system in multiplatform system - u must make this kit multiplatform!!!

cosmos is now ported to linux

**Comment by zarlo** [comment]
> I think Cosmos must work on linux and MacOS, cause if u wanna try to build own system in multiplatform system - u must make this kit multiplatform!!!

it will work out of the box on linux and windows for macos you will need to edit the make file

**Comment by off-the-az** [comment]
> > I think Cosmos must work on linux and MacOS, cause if u wanna try to build own system in multiplatform system - u must make this kit multiplatform!!!
> 
> it will work out of the box on linux and windows for macos you will need to edit the make file

I did it. However, how I can create Cosmos project on Linux.
Cause install and do all things, which it need is not hard, but I must create project on linux and work with this prj.

**Comment by zarlo** [comment]
right now you need to make the project by hand you can use this as a base https://github.com/CosmosOS/Cosmos/tree/master/source/Cosmos.VS.ProjectSystem/ProjectTemplates/CSharp/Cosmos/Cosmos%20Kernel

**Comment by off-the-az** [comment]
> right now you need to make the project by hand you can use this as a base https://github.com/CosmosOS/Cosmos/tree/master/source/Cosmos.VS.ProjectSystem/ProjectTemplates/CSharp/Cosmos/Cosmos%20Kernel

I just try it. However it`s not working cause it needs Cosmos library, which idk where did it lost.

**Comment by off-the-az** [comment]
![image](https://user-images.githubusercontent.com/96266521/206602327-399487b7-5241-46a1-a3bd-9bc360751aaf.png)
Smth like that

**Comment by zarlo** [comment]
did you install the nuget repo too?
```make install-nuget``` i think that the command

**Comment by off-the-az** [comment]
Nuget had been installed. However it wasn`t help me. I move to windows and try to work with Cosmos on Win 11.
