### ISSUE TITLE
Cosmos project template not showing up in New Project

### ISSUE THREAD

**Issue by MegaBatchGames** [CosmosOS/Cosmos#1410]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creating a project

#### Expected Behaviour - What do you think that should happen?
I should see a Cosmos option in the Templates in Visual Studio

#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/48155604/87583194-7b76be00-c6d3-11ea-81cc-f3a40283b017.png)
this

#### Reproduction - How did you get this error to appear?
Installing Cosmos

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using the User Kit, latest GitHub release

**Comment by bartekmuzyk** [comment]
Did you try installing the user kit as Administrator?

**Comment by MegaBatchGames** [comment]
Yes, although that wasn't the problem. I figured it out. I had to install C# support using the Visual Studio Installer. Closing.
