### ISSUE TITLE
How do I make the code wait for couple of milliseconds before continuing?

### ISSUE THREAD

**Issue by AAli107** [CosmosOS/Cosmos#1413]
How do I delay a code?

Cosmos.HAL.Global.PIT.Wait(milliseconds); does not work at all.

Thread.Sleep(); Does not work at all.

Using RTC, you can only do seconds of delay in minimum.

I need a way to stop the code for couple of milliseconds, to create ASCII animations and refresh screen properly in GUI without flickering.

**Comment by valentinbreiz** [comment]
Cosmos.HAL.Global.PIT.Wait(milliseconds); seems to work for me. What version of Cosmos are you using? Devkit? Userkit, if yes what version?
![ezgif-4-8a05e5536062](https://user-images.githubusercontent.com/18724279/87800412-a89bab80-c84e-11ea-93d2-48c94065b8f2.gif)

**Comment by AAli107** [comment]
> Cosmos.HAL.Global.PIT.Wait(milliseconds); seems to work for me. What version of Cosmos are you using? Devkit? Userkit, if yes what version?

I'm using the latest UserKit, I know, It works when you do that:
```
void DelayCode(uint milliseconds)
        {
            Cosmos.HAL.PIT pit = new Cosmos.HAL.PIT();
            pit.Wait(milliseconds);
            pit = new Cosmos.HAL.PIT();
        }
```

But if there is a Console.Beep() anywhere after the delay, the OS will freeze with the constant beeping sound.
