### ISSUE TITLE
Can't build from network drives

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [CosmosOS/Cosmos#1416]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling and building

#### Expected Behaviour - What do you think that should happen?
Cosmos should compile projects from network drives. 

#### Actual Behaviour - What unexpectedly happens?
I get this message and then objdump.bat exists with code -1.
`UNC paths are not supported.  Defaulting to Windows directory.`

#### Reproduction - How did you get this error to appear?
- Open a project from a network drive.
- Build it.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit version 20200708.

**Comment by EliaSulimanov** [comment]
I think this problem is about its cmd that doesn't support UNC paths.
It needs a drive name insted of network path.
