### ISSUE TITLE
Unable to find Cosmos Packages

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#1420]
VMware Booting

Its supposed to open VMware Player 14

Its has errors and doesn't work 

By clicking start

User Kit 2020, VS Community 2019

**Comment by quajak** [comment]
We can not help you if you do not provide enough information. What errors are you getting?

**Comment by DolphinFlopFish** [comment]
none it just doesn't start

**Comment by DolphinFlopFish** [comment]
Have I installed something wrong?
 I get about 8 errors

**Comment by quajak** [comment]
I need to know the errors you are getting to help you.

**Comment by DolphinFlopFish** [comment]
ok attached are screenshots of the errors
![Screenshot (20)](https://user-images.githubusercontent.com/52783833/89399972-8d89d080-d756-11ea-9dc9-18409061afd5.png)
![Screenshot (18)](https://user-images.githubusercontent.com/52783833/89399978-8f539400-d756-11ea-9b1b-2d920ed790d7.png)
![Screenshot (19)](https://user-images.githubusercontent.com/52783833/89399982-8fec2a80-d756-11ea-87fd-6c770a61694e.png)

**Comment by quajak** [comment]
Can you check if the two Cosmos Extensions are installed? Also under nuget manager, can you check if the Cosmos Local Package Feed exists and that Include Prereleases ist checked?

**Comment by DolphinFlopFish** [comment]
OK, if they are not installed, can you provide me the download links please?

**Comment by DolphinFlopFish** [comment]
ALSO I HAVE COSMOS USER KIT AND VISUAL STUDIO 2019

**Comment by quajak** [comment]
> OK, if they are not installed, can you provide me the download links please?

Are they installed? Can you please check in Visual Studio?

**Comment by DolphinFlopFish** [comment]
okie

**Comment by DolphinFlopFish** [comment]
uhh how do I check this??

**Comment by DolphinFlopFish** [comment]
nuget is installed

**Comment by DolphinFlopFish** [comment]
theres still errors, would I need .NET?

**Comment by DolphinFlopFish** [comment]
help

**Comment by quajak** [comment]
Yes you need to have .Net installed.

Under Extensions > Manage Extensions in Visual Studio you can see all installed extensions, there should be two Cosmos related extensions `Cosmos Debug Engine` and `Cosmos Project System`. 

In the nuget manager, check that `Include rerelease` is selected and check that under Package source there exists `Cosmos Local Package Feed`.

Could you further run a nuget restore?

**Comment by DolphinFlopFish** [comment]
I don't have the COSMOS Debug Engine Installed

**Comment by DolphinFlopFish** [comment]
nuget is not showing up, can I have download link?

**Comment by quajak** [comment]
> nuget is not showing up, can I have download link?

From https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio
> Starting in Visual Studio 2017, NuGet and the NuGet Package Manager are automatically installed with any .NET-related workloads. Install it individually by selecting the Individual components > Code tools > NuGet package manager option in the Visual Studio installer.



> I don't have the COSMOS Debug Engine Installed

Under `AppData\Roaming\Cosmos User Kit\VSIX` manually install the debug engine

**Comment by DolphinFlopFish** [comment]
whats the cosmos debug engine called in NuGet

**Comment by DolphinFlopFish** [comment]
P.S I GOT NUGET

**Comment by quajak** [comment]
You dont install the debug engine using nuget

**Comment by DolphinFlopFish** [comment]
oh, how then?

**Comment by DolphinFlopFish** [comment]
I don't know where to get the Debug Engine

**Comment by DolphinFlopFish** [comment]
Where do you get the Debug Engine?

**Comment by DolphinFlopFish** [comment]
Were do you get the COSMOS DEBUG ENGINE

**Comment by DolphinFlopFish** [comment]
.

**Comment by quajak** [comment]
Please dont spam the same question, it is quite disrespectful. As I said above, run `Cosmos.VS.DebugEngine.vsix` in  `%AppData%\Roaming\Cosmos User Kit\VSIX`

**Comment by DolphinFlopFish** [comment]
sorry

**Comment by DolphinFlopFish** [comment]
I installed COSMOS to G:\COSMOS User Kit so where would I click

**Comment by DolphinFlopFish** [comment]
I installed COSMOS Debug Engine and it still does not work

I need a checklist of things to download

**Comment by quajak** [comment]
Can you try manually adding a nuget source called Cosmos Local Package Feed and set the source to `%AppData%\Cosmos User Kit\packages\`.

**Comment by DolphinFlopFish** [comment]
ok

**Comment by DolphinFlopFish** [comment]
where can I get that, sorry

**Comment by quajak** [comment]
Under the Nuget Package Manager UI in VS, there is a gear icon for nuget sources.

**Comment by DolphinFlopFish** [comment]
ok

**Comment by DolphinFlopFish** [comment]
I can't find that, but in the extensions window there is a new Cosmos Option

**Comment by DolphinFlopFish** [comment]
> Can you try manually adding a nuget source called Cosmos Local Package Feed and set the source to `%AppData%\Cosmos User Kit\packages\`.

Like I said, I installed COSMOS to another Drive

**Comment by DolphinFlopFish** [comment]
THE DRIVE IS THE G:\ Drive

**Comment by quajak** [comment]
Then change the path to point to the same file where you installed it. See https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources for how to do the above steps.

**Comment by DolphinFlopFish** [comment]
i think its fine this way

**Comment by DolphinFlopFish** [comment]
I just had a look at it

**Comment by quajak** [comment]
Does it work now?

**Comment by DolphinFlopFish** [comment]
no

**Comment by DolphinFlopFish** [comment]
I don't know how to move the NuGet Package Manager because that post on the Microsoft Forums didn't help

**Comment by quajak** [comment]
What do you mean with "move"?

**Comment by DolphinFlopFish** [comment]
move the NuGet Manager to G:\Nuget Manager

**Comment by quajak** [comment]
You shouldnt move the nuget manager anywhere its a ui in VS

**Comment by DolphinFlopFish** [comment]
I Need help, i've never used cosmos before. I need more basic steps **Thank You**

**Comment by DolphinFlopFish** [comment]
Is there a way to get a super installer to latch everything?

**Comment by quajak** [comment]
You dont have to move the nuget manager. In VS open it and follow the instructions I stated above. If you do not have the nuget manager in vs use the vs installer to get it.

**Comment by DolphinFlopFish** [comment]
I don't get it, Sorry I replied so late

**Comment by quajak** [comment]
Can you do this in VS? 
![image](https://user-images.githubusercontent.com/8559822/91550163-6757ea80-e928-11ea-98e0-3acdd50f2aac.png)

**Comment by DolphinFlopFish** [comment]
yep, but it says "Incompatible" in the Solution Explorer

**Comment by DolphinFlopFish** [comment]
oh wait it works now

**Comment by DolphinFlopFish** [comment]
yep I clicked that

**Comment by quajak** [comment]
Ok can you post what packages are installed and their version numbers?

**Comment by DolphinFlopFish** [comment]
Cosmos.Build -- Version: v0.0.0-0
Cosmos.Debug.Kernel -- Version: v0.0.0-0
Cosmos.System2 -- Version: v0.0.0-0
Microsoft.NETCore.App -- Version: v2.0.9

**Comment by DolphinFlopFish** [comment]
is it normal to have the versions all on 0.0.0-0?

**Comment by DolphinFlopFish** [comment]
Do I need to install the c# extension in the vs installer?

**Comment by quajak** [comment]
Yeah the versions should not be zero. Can you click the button include prereleases and try update the cosmos packages.

**Comment by DolphinFlopFish** [comment]
ok, how do I do that?

**Comment by quajak** [comment]
![image](https://user-images.githubusercontent.com/8559822/92331222-6f750000-f075-11ea-8490-ac7b1f9e4034.png)
Check the button and then you should be able to click on the nuget packages and update them.

**Comment by DolphinFlopFish** [comment]
I can't, there is no button

**Comment by quajak** [comment]
Can you check if the Package Source Dropdown includes Cosmos Local Package Feed?

**Comment by DolphinFlopFish** [comment]
no

**Comment by quajak** [comment]
Can you add a package source with the following information, where you replace [AppData] with your path to app data
![image](https://user-images.githubusercontent.com/8559822/92455466-fe8f2e80-f1c1-11ea-9705-48b8b6dc0aa4.png)

**Comment by DolphinFlopFish** [comment]
ok done that, there was no directory with Cosmos User Kit in c:\My USERNAME\AppData\ROAMING\Cosmos User Kit

**Comment by DolphinFlopFish** [comment]
I found it

**Comment by DolphinFlopFish** [comment]
ok done that

**Comment by DolphinFlopFish** [comment]
it was on my G:\ drive because thats were I installed cosmos

**Comment by DolphinFlopFish** [comment]
Done it compiled, but I get this one error:
![Screenshot (26)](https://user-images.githubusercontent.com/52783833/92559513-12b35880-f2b4-11ea-8932-5a4794702bc4.png)

**Comment by DolphinFlopFish** [comment]
It changed to this error after I update the packages
	MSB6004	The specified task executable location "$Appdata\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.

**Comment by DolphinFlopFish** [comment]
I have cosmos on my G:\ Drive

**Comment by quajak** [comment]
Can you post the entire log from the output window?

**Comment by DolphinFlopFish** [comment]
I fixed that error

Now when I try compiling the ISO I get a "Cannot find the file specified" error

**Comment by quajak** [comment]
Thats fine. If you check the bin folder the bin should be there.

**Comment by DolphinFlopFish** [comment]
ok thanks

**Comment by DolphinFlopFish** [comment]
The ISO throws me an error saying something about LINUX

**Comment by quajak** [comment]
Please open a new issue with more information on the new problem

**Comment by DolphinFlopFish** [comment]
ok

**Comment by AcaiBerii** [comment]
After adding the Cosmos Local Package Feed source. I can still only see the 3 packages that are included as references to a Cosmos Kernel project, all at versions 0.0.0, without buttons to update them. There's nothing else at all.

**Comment by quajak** [comment]
Do you have prereleases enabled?
