### ISSUE TITLE
Visual Studio 2019: Empty kernel.cs

### ISSUE THREAD

**Issue by edivaldobrito53-ai** [CosmosOS/Cosmos#1421]
Hi Guys! I'm Edivaldo, Newbie of GitHub, I'm Having A Serious Problem, I installed Visual Studio 2019 and The Cosmos User Kit, and I created the project which is the cosmos kernel with C#, and the kernel.cs is not there, help me please?

**Comment by quajak** [comment]
Can you please post a screenshot of what you see in VS?

**Comment by edivaldobrito53-ai** [comment]
> Can you please post a screenshot of what you see in VS?

![Capturar](https://user-images.githubusercontent.com/69278501/89531759-1dfff980-d7c7-11ea-9e15-dfbfa6160f55.PNG)

**Comment by fdagrewwwfdgsdfs** [comment]
Try reinstalling cosmos userkit

**Comment by quajak** [comment]
Yeah it seems cosmos did not install properly.
Can you check under Extensions > Manage Extensions in Visual Studio, there should be two Cosmos related extensions `Cosmos Debug Engine` and `Cosmos Project System`.
