### ISSUE TITLE
Need plug

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1422]
1>------ 已启动生成: 项目: CosmosKernel1, 配置: Debug Any CPU ------
1>CosmosKernel1 -> C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.Runtime.InteropServices.Marshal.CopyToManaged(System.IntPtr, System.Object, System.Int32, System.Int32).
1>  Called from :
1>System.Runtime.InteropServices.Marshal::Void Copy(IntPtr, Byte[], Int32, Int32)
1>Cairo.ImageSurface::Byte[] get_Data()
1>CosmosKernel1.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:01.0849530
1>已完成生成项目“CosmosKernel1.csproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

Is it impossible to use cairosharp in cosmos?

**Comment by quajak** [comment]
Yes because as far as i can tell cairosharp is a wrapper around a c++ library, which wont work with cosmos.
