### ISSUE TITLE
When using CGS on Oracle VM Virtualbox it glitches out

### ISSUE THREAD

**Issue by fdagrewwwfdgsdfs** [CosmosOS/Cosmos#1424]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Graphics Subsystem

#### Expected Behaviour - What do you think that should happen?
Screen to be drawn correctly on VM Virtualbox

#### Actual Behaviour - What unexpectedly happens?
Screen is full of garbage
![image](https://user-images.githubusercontent.com/40271862/89623648-a650ce00-d89d-11ea-9118-664cf5f3391b.png)

#### Reproduction - How did you get this error to appear?
Use this code:
        public uint txtX = 0;
        public uint txtY = 0;
        public static Canvas driver;
        static Pen white;
        public static void InitGUI()
        {
            white = new Pen(Color.White);
            driver = FullScreenCanvas.GetFullScreenCanvas();
            driver.Mode = new Mode(800, 600, ColorDepth.ColorDepth32);
        }

        public void SetPixel(uint txtX,uint txtY, Pen color)
        {
            driver.DrawPoint(color, new Cosmos.System.Graphics.Point((int)txtX, (int)txtY));
        }

in kernel Run put:
InitGUI();
driver.Clear(Color.Blue);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
20200708 Userkit

**Comment by quajak** [comment]
Virtualbox is currently not supported by CGS AFAIK.
