### ISSUE TITLE
Cosmos for Raspberry?

### ISSUE THREAD

**Issue by quocthinhvo** [CosmosOS/Cosmos#1428]
Can I use Cosmos for Raspberry?

**Comment by nifanfa** [comment]
It seems that cosmos was created for the x86 platform

**Comment by zarlo** [comment]
you will be able to use it on a Raspberry when X# and some of the low level API's get ported to arm https://github.com/CosmosOS/Cosmos/pull/495

**Comment by quocthinhvo** [comment]
hmm thank. I will try it
