### ISSUE TITLE
[Question] How to drawstring on the canvas?

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1429]
is there any way to draw ttf font on the canvas?
like his project：https://www.youtube.com/watch?v=dfAoy7oAZaY&t=61s
i've heard that PixelFarm.Typography could do this. so i tried. but when i started running. IL2CPU said need a plugin with "System.IntPtr" and UnsafeHandler.

**Comment by nifanfa** [comment]
![QQ截图20200810192806](https://user-images.githubusercontent.com/54205437/89778360-f222a200-db3f-11ea-966d-784998a5bd24.png)
![QQ截图20200810192828](https://user-images.githubusercontent.com/54205437/89778377-f949b000-db3f-11ea-9ee5-ad456f49ddbc.png)



`using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        CosmosVFS fs;
        string CURRENT_DIRECTORY = @"0:\";
        Canvas canvas;

        protected override void BeforeRun()
        {
            fs = new CosmosVFS();
            VFSManager.RegisterVFS(fs);
            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
        }

        protected override void Run()
        {
            Pen pen = new Pen(Color.Black);
            byte[] Text = new byte[] { 0xC4, 0xE3, 0xBA, 0xC3 };
            canvas.Clear(Color.White);
            canvas.DrawString(pen, Text, 100, 100);
            Console.ReadKey();
        }
    }
}`

`using Cosmos.System.Graphics;
using System.Collections.Generic;
using System.IO;

namespace CosmosKernel1
{
    static class Fonts
    {
        static FileStream fileStream = new FileStream(@"0:\Fonts\HZK16", FileMode.Open);

        public static void DrawString(this Canvas canvas, Pen pen, byte[] fontBytes, int x, int y)
        {
            for (int q = 0; q < fontBytes.Length; q += 2)
            {
                List<byte> lb = new List<byte>();
                for (int m = 0; m < 2; m++)
                {
                    lb.Add(fontBytes[q + m]);
                }

                byte[] by = lb.ToArray();

                long offset = 32 * (94 * (by[0] - 0xA1) + by[1] - 0xA1);
                fileStream.Seek(offset, SeekOrigin.Begin);
                byte[] fontBuffer = new byte[32];
                fileStream.Read(fontBuffer, 0, 32);

                byte[] key = new byte[8] { 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01 };

                int i, j, k;
                int usedw = 0;

                for (k = 0; k < 16; k++)
                {
                    for (j = 0; j < 2; j++)
                    {
                        for (i = 0; i < 8; i++)
                        {
                            if ((fontBuffer[k * 2 + j] & key[i]) != 0)
                            {
                                canvas.DrawPoint(pen, x + usedw + ((q / 2) * 16), y + k);
                            }
                            usedw++;
                        }
                    }
                    usedw = 0;
                }
            }
        }
    }
}`

**Comment by nifanfa** [comment]
but how to draw ttf?

**Comment by Jaiganeshkumaran** [comment]
@nifanfa See this: https://github.com/CosmosOS/Cosmos/wiki/Somewhat-indepth-Canvas-Changes-explained

**Comment by Jaiganeshkumaran** [comment]
The latest userkit adds TTF support.

**Comment by nifanfa** [comment]
> The latest userkit adds TTF support.

i tried to load ttf font with PCScreenFont. but it didn't work and then the system just shotdown. PCScreenFont seems to only support PSF font.

**Comment by quajak** [comment]
There is no current ttf support from Cosmos, we only added support for PSF fonts as nifanfa said. To draw ttf, you would either have to plug the things missing in PixelFarm.Typography/adapt it to work with cosmos or find another library which works with cosmos or make your own.

**Comment by nifanfa** [comment]
if we can't draw ttf font. what font can be drawn in size and simplicity?

**Comment by nifanfa** [comment]
The font i use almost the same as the psf font. Fixed size. You cannot change the font size. So i want to draw ttf font. But it's too difficult to do that...

**Comment by quajak** [comment]
The difference between ttf font and psf fonts is that the psf format is very simple while ttf format is very complicated. Therefore, until someone is willing to develop support for ttf only psf will be supported
