### ISSUE TITLE
Resolved: Crash on Console.ReadKey()

### ISSUE THREAD

**Issue by fy1vo51** [CosmosOS/Cosmos#1430]
If anybody knows that Console.ReadKey() should crash the CPU at debugging, well I found a solution!

Here's the code that I made:
![cosmosc#_pause](https://user-images.githubusercontent.com/63316499/89740170-74359c80-da54-11ea-8a59-56ca35e6b5ce.png)

**Comment by EliaSulimanov** [comment]
What do you mean about the Console.ReadKey() crashing the CPU?
Does the template kernel provided with new project crashes for you?
