### ISSUE TITLE
nasm.exe has exited with code 1

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1431]
![QQ截图20200810035701](https://user-images.githubusercontent.com/54205437/89740729-f0b09580-dabd-11ea-9cda-50eac7b9b407.png)
![QQ截图20200810035646](https://user-images.githubusercontent.com/54205437/89740733-f8703a00-dabd-11ea-90d9-35d8054ef719.png)
As you can see i made a function for drawstring, and when i started to build this solution, build faild. "nasm.exe" has exited with code 1 and "interminable macro recursion",how to solve this problem??

**Comment by nifanfa** [comment]
it's seems that font file is too large, but how can i do? if you add font file in the resources then IL2CPU will except too.

**Comment by quajak** [comment]
If you convert a large byte array to a Base64 string and include it as a string and convert it back to a byte array at runtime, you can include larger data amounts.

**Comment by elkaamee326** [comment]
Another way to resolve an "interminable macro recursion," is to download an old nasm source (2012. The reason why it is the only build that supports resoving it, from my understanding), go to `preproc.c` and go to line 334, and change the dead man limit to a much larger value (that was how I solved it), and recompile nasm. Then, open Cosmos,  and go to `C:/yourusername/.nuget/packages` and search for Cosmos.Build, and replace it with the modified version of nasm. I think maybe in a newer build the error is resolved?
