### ISSUE TITLE
New Cosmos logo suggestion

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#1432]
![Cosmos Logo](https://user-images.githubusercontent.com/63316499/89792973-43587480-daf3-11ea-99d6-82f89dd2ffc3.png)
Hello! I maded the new logo for the next years. If anyone who interested this new logo. Let me know!

**Comment by BiberGames** [comment]
Thats Great!

**Comment by faisaltaher** [comment]
I love this logo looks better

**Comment by kilickerem066** [comment]
Better

**Comment by TFTWPhoenix** [comment]
Definitely says 2020 technology. Love it!

**Comment by AcaiBerii** [comment]
Way better :)

**Comment by RaphMar2021** [comment]
I don't find the logo better than the old one

**Comment by Kiirx** [comment]
for me, it's definitely more 2020s simplistic-like design, very cool

**Comment by MishaTY** [comment]
![Cosmossquare](https://user-images.githubusercontent.com/46088515/215230896-b87d81c9-8d4a-4b1c-bf15-8c45d0e2cdf2.png)

**Comment by cabfile** [comment]
shouldnt the issue be closed already?
