### ISSUE TITLE
drawimage didn't draw bitmap correctly and very slow to load

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1434]
using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        Bitmap wallpaper;

        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            wallpaper = new Bitmap(@"0:\Wallpaper.bmp");

            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
        }

        protected override void Run()
        {
            string s = Console.ReadLine();
            Console.WriteLine(s);

            canvas.Clear();
            canvas.DrawImage(wallpaper, 0, 0);
            canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
            canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);

            Console.ReadKey();
        }
    }
}

**Comment by nifanfa** [comment]
![UQR9DJRRDNYA688`6J~~$07](https://user-images.githubusercontent.com/54205437/90003228-5c654f00-dcc6-11ea-9f18-909405e1955c.jpg)

**Comment by nifanfa** [comment]
the size of bitmap is 900kb

**Comment by nifanfa** [comment]
it always takes more than 1 minute to load the bitmap

**Comment by nifanfa** [comment]
![20200812_184922_HDR.jpg](https://user-images.githubusercontent.com/54205437/90007018-8faadc80-dccc-11ea-8e41-5b4f176cee70.jpg)
VRAM Problem?

**Comment by quajak** [comment]
Could you post the original image?

**Comment by nifanfa** [comment]
> Could you post the original image?

sorry late
the github doesn't support bmp file so i send jpg to you
![184995](https://user-images.githubusercontent.com/54205437/90189904-96cb0b00-ddf0-11ea-99f7-70cbdc2a2969.jpg)
![707860](https://user-images.githubusercontent.com/54205437/90189907-99c5fb80-ddf0-11ea-93c7-9c2bcaedcf30.jpg)
