### ISSUE TITLE
Trying to run it in vmware but I see no iso file and when I build it has a error 

### ISSUE THREAD

**Issue by LumicMirror** [CosmosOS/Cosmos#1436]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6004	The specified task executable location "C:\Users\TV\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.	FIRSTOS	C:\Users\TV\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets	169	

User Kit

**Comment by quajak** [comment]
Can you try reinstall the userkit? Also is TV the current user?

**Comment by nifanfa** [comment]
https://github.com/CosmosOS/Cosmos/releases/download/Userkit_20200708/CosmosUserKit-20200708-vs2019.exe

**Comment by LumicMirror** [comment]
yes TV is the current user

**Comment by quajak** [comment]
Is TV the user under which the userkit was installed? If TV is not the admin account, ensure that the cosmos was installed under the TV user and not admin, by checking if you can find the files in the correct AppData directory.
