### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by fdagrewwwfdgsdfs** [CosmosOS/Cosmos#1437]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I/O

#### Expected Behaviour - What do you think that should happen?
The os accepts key strokes on real hardware

#### Actual Behaviour - What unexpectedly happens?
Nothing happens

#### Reproduction - How did you get this error to appear?
1) create a class named ConsoleInterpreter.cs
2) write in it
`        public void DoConsole()
        {
                  string input = Console.ReadLine();
        }`
3) in kernel write
`       public static ConsoleInterpreter cons;

        protected override void Run()
        {
            cons.DoConsole();
        }`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest userkit

**Comment by nifanfa** [comment]
cosmos seems only support ps/2 keyboard

**Comment by fdagrewwwfdgsdfs** [comment]
Ok thanks
