### ISSUE TITLE
In Cosmos I received this error saying:  Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented

### ISSUE THREAD

**Issue by elkaamee326** [CosmosOS/Cosmos#1439]
Here is my most recent build log:

1>------ Build started: Project: CosmosBitmapTest, Configuration: Debug Any CPU ------
1>CosmosBitmapTest -> C:\Users\elkaa\source\repos\CosmosBitmapTest\CosmosBitmapTest\bin\Debug\netcoreapp2.0\cosmos\CosmosBitmapTest.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\elkaa\source\repos\CosmosBitmapTest\CosmosBitmapTest\bin\Debug\netcoreapp2.0\cosmos\CosmosBitmapTest.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 988
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 266
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:36.9745550
1>Done building project "CosmosBitmapTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I was trying to display a bitmap onto the screen using this example https://github.com/CosmosOS/Cosmos/issues/1434
Here is the source code:

`using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        Bitmap wallpaper;

        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            wallpaper = new Bitmap(@"0:\wallpaper.bmp");

            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
        }

        protected override void Run()
        {
            string s = Console.ReadLine();
            Console.WriteLine(s);

            canvas.Clear();
            canvas.DrawImage(wallpaper, 0, 0);
            //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
            canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);

            Console.ReadKey();
        }
    }
}`

When I tried to build/compile it I receive an error saying "The system cannot find the file specified"

P.S : What directory or folder do I put the bitmap that i'm using do I put it on my physical PC or my virtual OS ? 
Thank you!

**Comment by elkaamee326** [comment]
I resolved the who System Exception error by reinstalling COSMOS and deleting it from all the installed locations on my PC but I don't know where to put the bitmap in what directory / folder Do I have to create it my self the directory? How do I put a bitmap on my computer to COSMOS 0:\Wallpaper-bmp.bmp? Thank you

**Comment by fdagrewwwfdgsdfs** [comment]
You need to create a fat32 partition on a blank virtual drive then mount it in windows and copy your file

**Comment by elkaamee326** [comment]
How do I do that? With VirtualDisk ImDisk? or with C# Cosmos Code?

**Comment by fdagrewwwfdgsdfs** [comment]
What vm do you use?

**Comment by fdagrewwwfdgsdfs** [comment]
Mount a windows installation disk in the vm. After it goes in the setup use the combination Shift+F10. A command prompt will appear. Type diskpart and press enter. Type sel dis 0, then clean. Type cre part primary. Type sel part 1. And last type format fs=fat32.

**Comment by fdagrewwwfdgsdfs** [comment]
Then you need to find a way to mount it in windows

**Comment by elkaamee326** [comment]
I tried mounting a vmdk file to my PCby following all the diskpart commands. Do I have to burn an iso on the virtual hard disk image? or do I use it in my cosmos OS virtual machine settings?

**Comment by elkaamee326** [comment]
I finally figured out how to find the correct location but every time I debug on VMware Workstation Player 15.0 I receive a CPU x06 exception. Than it says on the next line "Last known address: 0x0211DA11" than it shows the Filesystem initialization. when I have this code:

`using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
public class Kernel : Sys.Kernel
{
Canvas canvas;
Bitmap wallpaper;

    protected override void BeforeRun()
    {
        CosmosVFS cosmosVFS = new CosmosVFS();
        VFSManager.RegisterVFS(cosmosVFS);

        ###wallpaper = new Bitmap(@"0:\wallpaper.bmp");

        canvas = FullScreenCanvas.GetFullScreenCanvas();
        canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
    }

    protected override void Run()
    {
        string s = Console.ReadLine();
        Console.WriteLine(s);

        canvas.Clear();
        canvas.DrawImage(wallpaper, 0, 0);
        //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
        canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
        canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

        canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
        canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

        canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
        canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);

        Console.ReadKey();
    }
}
}`

But when I put this code:

`using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        Bitmap wallpaper;
        
        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);
            

            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
            ###wallpaper = new Bitmap(@"0:\wallpaper.bmp");
        }

        protected override void Run()
        {
            string s = Console.ReadLine();
            Console.WriteLine(s);

            canvas.Clear();
            canvas.DrawImage(wallpaper, 0, 0);
            //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
            canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);

            Console.ReadKey();
        }
    }
}`

I don't receive an exception or an error the filesystem initializes but it just gives me a blank black screen without the bmp being displayed. I'm using the same 900 kb bitmap now in the example #1439. But it doesn't display the image or even load it. I'm using the latest version of the cosmos userkit. Thank you!

**Comment by quajak** [comment]
Can you put the bitmap creation in a try catch block and look if some exception is thrown?

**Comment by elkaamee326** [comment]
I tried that but I don't recieve any exceptions I listed the right directory if I didn't it would have prompted me giving me a Fatal error message and visual studio devenv.exe message. For some reason the filesystsem doesn't load the image. Here is my latest Debug log:

Setting FirstDataLookupTable to 
0x0232C577
FirstDataLookupTable was set to 
0x0232C577
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA device with speclevel ATAPI found, which is not supported yet!
Done initializing Cosmos.HAL.Global
KeyboardManager.AddKeyboard
Cls
Before Run
Run
Not yet stopped
Really before Run
The program '' has exited with code 0 (0x0).

Thank you, very much appreciated!

**Comment by EliaSulimanov** [comment]
Can you approve that wallpaper.bmp is on the disk?
There is an explanation in the wiki about listing all the files on the disk.
I got similar error when tried to load bmp that dosn't exist.

**Comment by elkaamee326** [comment]
I mounted the Filesystem.vmdk file to my drive and I put the image there from VMware.

**Comment by EliaSulimanov** [comment]
Please try using this:
[https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#get-files-list](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#get-files-list)
or this:
[https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#read-all-the-files-in-a-directory](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#read-all-the-files-in-a-directory) 
to see if cosmos can see that the file is there.

**Comment by elkaamee326** [comment]
I tried using the wiki it showed the filesystem for get files list.

**Comment by quajak** [comment]
Can you try first loading the bytes from the file and then pass the bytes into the bitmap ctor, in a try catch block. Can you confirm that your problem occurs in the ctor and not when loading the bytes from the file?

**Comment by elkaamee326** [comment]
How do I do that?

**Comment by EliaSulimanov** [comment]
Just like this: [https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#read-specific-file](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#read-specific-file), but insted of writing to console, save it to string.
P.S. this might throw overflow exception when reading file of this size, so maybe try reading it by chanks for starts..

**Comment by elkaamee326** [comment]
Than do I use the variable in the bitmap?

**Comment by elkaamee326** [comment]
Or string?

**Comment by elkaamee326** [comment]
I have the latest userkit but Visual Studio 2019 16.5.2

**Comment by elkaamee326** [comment]
Not 16.6+

**Comment by elkaamee326** [comment]
Is that maybe why I get the CPU Exception?

**Comment by quajak** [comment]
No that shouldnt be a problem, you use the variable when calling the constructor of the bitmap.

**Comment by elkaamee326** [comment]
I did that I got a bunch of executable nonsense.

**Comment by quajak** [comment]
Can you post what you got?

**Comment by elkaamee326** [comment]
This is my Source code:

`using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using System.Text;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        Bitmap wallpaper;

        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            //wallpaper = new Bitmap(@"0:\wallpaper.bmp");
            try
            {
                var hello_file = cosmosVFS.GetFile(@"0:\wallpaper.bmp");
                var hello_file_stream = hello_file.GetFileStream();

                if (hello_file_stream.CanRead)
                {
                    byte[] text_to_read = new byte[hello_file_stream.Length];
                    hello_file_stream.Read(text_to_read, 0, (int)hello_file_stream.Length);
                    //Console.WriteLine(Encoding.Default.GetString(text_to_read));
                    wallpaper = new Bitmap(Encoding.Default.GetString(text_to_read));
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }

            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
        }

        protected override void Run()
        {
            //string s = Console.ReadLine();
            //Console.WriteLine(s);
            
            canvas.Clear();
            canvas.DrawImage(wallpaper, 0, 0);
            //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
            canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);
            
            //Console.ReadKey();
        }
    }
}`

Than when I compiled it I got this a few exceptions right before it started the nonsense:

![image](https://user-images.githubusercontent.com/69808082/90702791-27bf3d80-e25a-11ea-8771-bff4a8e31dc9.png)

![image](https://user-images.githubusercontent.com/69808082/90703077-cea3d980-e25a-11ea-8c1a-5752bbd1ddf8.png)

![image](https://user-images.githubusercontent.com/69808082/90702739-03fbf780-e25a-11ea-913c-8c0bce34f194.png)

I got a few exceptions before the nonsense than when its done all that I get a Visual Studio devenv.exe error and a VMware Fatal error Message Box about the CPU Shutdown Something like that. Here is my debug log:

Setting FirstDataLookupTable to 
0x02326926
FirstDataLookupTable was set to 
0x02326926
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA device with speclevel ATAPI found, which is not supported yet!
Done initializing Cosmos.HAL.Global
KeyboardManager.AddKeyboard
Cls
Before Run
The program '' has exited with code 0 (0x0).

So is it ctor related or is it from loading the bytes from the file? Thank you!

**Comment by quajak** [comment]
You are getting an exception The path contains illegal characters, followed by a lot of random symbols, which seem to indicate to me that somehow the file system is corrupted. Does the exception occur if you only do `var hello_file = cosmosVFS.GetFile(@"0:\wallpaper.bmp");` and not read the from file + try create the bitmap?

**Comment by EliaSulimanov** [comment]
By this line of yours:
`wallpaper = new Bitmap(Encoding.Default.GetString(text_to_read));`
I see you are tring to pass the file context to the Bitmap constructor, but the ctor of Bitmap that takes string expecting path.
Probably this is why you are getting illegal characters exception, apart from the corruption comes afterwards.

**Comment by elkaamee326** [comment]
When I try to load the bitmap it just stops at that line of code. ie: when I put the `wallpaper = new Bitmap("0:\wallpaper.bmp")` It just stops there. When I put it at the beginning it just loads everything until that line of code and gives me an exception. When I put it at the very last line of code in the function, it loads the desktop UI and the filesystem but not the bmp. I tried the example on the Root.txt file by default it just showed the initialization of the filesystem and displayed the text with this code:

``

**Comment by elkaamee326** [comment]
This is the file i'm trying to load:

![image](https://user-images.githubusercontent.com/69808082/90776893-aeaaff00-e2c8-11ea-95be-9ebf48e94cd8.png)

The same 900kb file in this example  #1434

**Comment by quajak** [comment]
Can you please try to load the file to a byte array first, which seems to work, and then in a try catch block load the bitmap by passing *only* the byte array as a byte array. Then log the error which occurs. If this fails please post the entire code you are using..

You shouldnt need to reinstall Cosmos.

**Comment by elkaamee326** [comment]
Can you please give me a source code example.

**Comment by quajak** [comment]
put this in the kernel and keep Run empty

```
protected override void BeforeRun()
{
CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
try
{
      var bytes = File.ReadAllBytes(@"0:\wallpaper.bmp");
     Bitmap bitmap = new Bitmap(bytes);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
        }
Console.WriteLine("Test finished");
    }
```

**Comment by elkaamee326** [comment]
Thank you very much. I'll do that and fetch all the exceptions

**Comment by elkaamee326** [comment]
When I was debugging I recieved this CPU Exception on the second image:

![image](https://user-images.githubusercontent.com/69808082/90789122-86290200-e2d4-11ea-9c69-8c03827d5b4f.png)


![image](https://user-images.githubusercontent.com/69808082/90789033-672a7000-e2d4-11ea-8934-039848e426dc.png)

Here is my debug log:

The program '' has exited with code 0 (0x0).

**Comment by quajak** [comment]
Could you determine if it was caused while loading the bitmap or when loading the byte array? If not please add a Console.WriteLine between the two and run it again

**Comment by elkaamee326** [comment]
When I compiled it I commented the **bolded** line of code:

using Cosmos.Core;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.IO;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    { 
        protected override void BeforeRun()
        {
            CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            try
            {
                var bytes = File.ReadAllBytes(@"0:\wallpaper.bmp");
                //Console.WriteLine();
               **// Bitmap bitmap = new Bitmap(bytes);**
                //Console.WriteLine();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            Console.WriteLine("Test finished");
        }

        protected override void Run()
        {

        }
    }
}

And this was my result:

![image](https://user-images.githubusercontent.com/69808082/90791844-b8882e80-e2d7-11ea-8b97-a0858a6023fc.png)

So it's most likely A bitmap problem.

**Comment by quajak** [comment]
Can you send me the original bmp files *as bmp*, so that I can try recreate the problem?

**Comment by elkaamee326** [comment]
When I found it it was in jpg from this example #1434 so I converted them to bmp and used it. Github doesn't support bmp.

**Comment by quajak** [comment]
Can you send it as a zip or some other service? I need the exact bmp to determine whats wrong.

**Comment by elkaamee326** [comment]
Let me know if there is anything wrong with the bmp file. This is the file converter i used https://onlineconvertfree.com/convert-format/jpg-to-bmp/ all I did was convert the file without any extra unnecessary parameters. If possible try displaying the bitmap with Cosmos and see if you get any errors or exceptions. Than try the same thing with a working bitmap file and let me know if it is file related or the Bitmap ctor related thank you.

**Comment by quajak** [comment]
Ok the tool you are using to create the bitmap is using a different header, which we do not currently support. If you open it in VS, change on pixel and resave it, it will have the correct header.

**Comment by elkaamee326** [comment]
Thank you so much!
