### ISSUE TITLE
FileSystem

### ISSUE THREAD

**Issue by mmkhmmkh** [CosmosOS/Cosmos#144]
Hello . 
I Just installed Lastest COSMOS userkit on VS2013 .

I Cant Find a Way to Access FileSystem . ( There isnt any Cosmos.system.FileSystem )

What Can I do For That ?

I Tried Using GLNFS Functions But it says :

Reference required to assembly 'Cosmos.Hardware, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983' containing the type 'Cosmos.Hardware.BlockDevice.Partition'. Add one to your project.	f:\visualstudioprojects\ORANDA OS\ORANDA OS\Kernel.vb	23	25	ORANDA OS

Its because Cosmos.Hardware is newly changed to Cosmos.HAL but my GLNFS DLL is very OLD !

So i want a way to format a BlockDevice And I Dont Know How to do this.
Also I dont know how to open an output stream or an input stream to a file.

Without FileSystem , Operating System has no meaning .

**Comment by mterwoord** [comment]
In the current devkit, we're working hard on getting FAT working. Once that's working, you can use the System.IO namespace, just like you're used to on windows.

**Comment by ARMmaster17** [comment]
@mmkhmmkh Although we don't officially recommend this, you could download the old version from the [CodePlex page](cosmos.codeplex.com), which is the version that GLNFS was created for. Just know that most Cosmos-referencing code will probably break (easy fix though). As per your last statement, if the filesystem is **really** that important, it's not that difficult to implement a live filesystem on RAM. I could walk you through it if you need help. You can find me on [Gitter](https://gitter.im/ARMmaster17).

@mterwoord Can we mark this and #145 as duplicates?

=====
If your issue has been resolved, please click *Close Issue*. Hope this information helped!
