### ISSUE TITLE
ProcessorInformation.GetVendorName() returns ""

### ISSUE THREAD

**Issue by fdagrewwwfdgsdfs** [CosmosOS/Cosmos#1440]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Hardware Information

#### Expected Behaviour - What do you think that should happen?
It should return "Intel"

#### Actual Behaviour - What unexpectedly happens?
It returns ""

#### Reproduction - How did you get this error to appear?
`Console.WriteLine("CPU Vendor: " + ProcessorInformation.GetVendorName());`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest Userkit

**Comment by quajak** [comment]
Can you try `CPU.GetCPUVendorName()`? Also what VM are you using?

**Comment by fdagrewwwfdgsdfs** [comment]
I'm using VM Virtualbox. CPU.GetCPUVendorName() is returning garbage

**Comment by fdagrewwwfdgsdfs** [comment]
I tried also on real hardware. Same garbage

**Comment by fdagrewwwfdgsdfs** [comment]
![image](https://user-images.githubusercontent.com/40271862/90486865-4af6c980-e142-11ea-9ff8-b1cd299c4a25.png)

**Comment by quajak** [comment]
Lets discuss that in #1441
