### ISSUE TITLE
"I/O apic write at unaligned address" when assigning a new byte array to a local variable in a while loop

### ISSUE THREAD

**Issue by ascpixel** [CosmosOS/Cosmos#1442]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling/Runtime/IL2CPU

#### Expected Behaviour - What do you think that should happen?
The code should run without any errors.

#### Actual Behaviour - What unexpectedly happens?
Bochs reports:
`03209475265p[IOAPIC] >>PANIC<< I/O apic write at unaligned address 0x0000fec00004`
The debug output is: https://pastebin.com/9ZqYPWyD

CPU fault occurs in both VMWare and Bochs (Bochs gives more info, though). Did not test with VirtualBox

#### Reproduction - How did you get this error to appear?
Paste these fields to the beginning of a static class: https://pastebin.com/yStJb1Dr
Then, copy this snippet of code to the said class: https://pastebin.com/gcbUWssy
Then, call `Decompress(byte[])` on any LZF-compressed byte array. Example: http://www.filedropper.com/lzfexample
(you can load the file with ManifestResourceStream)

IF you want to create your own LZF-compressed byte array for testing, use this code: https://pastebin.com/bJ3GFEeM (be sure to have the fields pasted)
(The compression code wasn't tested on COSMOS. You should run this on your own machine, and not in a VM)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit v106027
Visual Studio 2019 Community

**Comment by ascpixel** [comment]
Any updates on this? I'm still getting this problem, and I can't find any workarounds.

**Comment by quajak** [comment]
Sorry, havnt gottent around to lok at this, since you are allocating a lot of memory, I suspect its a problem with the memory manager, which is in the process of getting a rewrite.
