### ISSUE TITLE
Cannot get the array of string directories via System.IO.Directory.GetFiles(String, String, SearchOptions). Returns exception in IL2CPU.

### ISSUE THREAD

**Issue by LiquidRekto** [CosmosOS/Cosmos#1443]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File management

#### Expected Behaviour - What do you think that should happen?
Returns an array of string directories

#### Actual Behaviour - What unexpectedly happens?
Throws an exception in IL2CPU, line 1:
`Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.
(Happens in the 1st line of IL2CPU)`

#### Reproduction - How did you get this error to appear?
Create a `string` type variable and store the assign the function to it.
Using this function with more than 1 argument will result in an error.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, version 20200708

**Comment by nifanfa** [comment]
CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);
            
            DirectoryInfo directoryInfo = new DirectoryInfo(@"0:\");
            FileInfo[] fileInfos= directoryInfo.GetFiles();

            foreach (FileInfo fileInfo in fileInfos)
                Console.WriteLine(fileInfo.Name);

**Comment by LiquidRekto** [comment]
@nifanfa Sorry for not clarifying the issue, but what I meant to do is to get all of the filenames in the specified directory, as well as those in its sub-directories. From what I've researched, I must use an enum parameter called `SearchOptions.AllDirectories` to do so.
The example you prvoided obviously will work, but it will only print the filenames in that directory. Like, just FILES. Totally ignore the sub-directories.
Are there any solutions that don't trigger such exception?

**Comment by quajak** [comment]
Some work still has to be done on the compiler to support this method. Currently you can use GetFiles and GetDirectories and call them recursively to get all files.
