### ISSUE TITLE
 'System.UIntPtr' not yet implemented! 

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1444]
Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1DoubleBufferedVMWareSVGAII_Update': System.Exception: Error interpreting stacktypes for IL_0043: Add ---> System.NotImplementedException: Add on types 'System.UIntPtr' and 'System.UIntPtr' not yet implemented! CosmosKernel1 C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\IL2CPU 1

**Comment by nifanfa** [comment]
![QQ截图20200818225449](https://user-images.githubusercontent.com/54205437/90631937-29870200-e256-11ea-90f3-4ab5823cd9e3.png)
![QQ截图20200818230047](https://user-images.githubusercontent.com/54205437/90631945-2c81f280-e256-11ea-824c-1af47c165a87.png)

**Comment by quajak** [comment]
Can you post the entire stack trace of the error message?

**Comment by nifanfa** [comment]
![QQ截图20200819195348](https://user-images.githubusercontent.com/54205437/90631981-399ee180-e256-11ea-8645-bfeadfaedfa2.png)
![QQ截图20200819195338](https://user-images.githubusercontent.com/54205437/90631986-3ad00e80-e256-11ea-9afa-08d8e455be53.png)
as you can see. i just copied the source. but it didn't past the ilcpu

**Comment by nifanfa** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1DoubleBufferedVMWareSVGAII_Update': System.Exception: Error interpreting stacktypes for IL_0043: Add ---> System.NotImplementedException: Add on types 'System.UIntPtr' and 'System.UIntPtr' not yet implemented!	CosmosKernel1	C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\IL2CPU	1

**Comment by nifanfa** [comment]
1>------ 已启动生成: 项目: CosmosKernel1, 配置: Debug Any CPU ------
1>CosmosKernel1 -> C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\nifan\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1DoubleBufferedVMWareSVGAII_Update': System.Exception: Error interpreting stacktypes for IL_0043: Add ---> System.NotImplementedException: Add on types 'System.UIntPtr' and 'System.UIntPtr' not yet implemented!
1>   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 849
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 416
1>   --- End of inner exception stack trace ---
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 420
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 732
1>   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 558
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 511 ---> System.Exception: Error interpreting stacktypes for IL_0043: Add ---> System.NotImplementedException: Add on types 'System.UIntPtr' and 'System.UIntPtr' not yet implemented!
1>   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 849
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 416
1>   --- End of inner exception stack trace ---
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 420
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 448
1>   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 426
1>   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 732
1>   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 558
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 511
1>   --- End of inner exception stack trace ---
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 526
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 998
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 266
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:02.7018997
1>已完成生成项目“CosmosKernel1.csproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by quajak** [comment]
I think the fix could be changing the adding ` || (StackPopTypes[0] == typeof(UIntPtr) && StackPopTypes[1] == typeof(UIntPtr))` to the check in OpNone.cs in IL2CPU on line 584

**Comment by EliaSulimanov** [comment]
MoveDown function is being used by TextScreen.ScrollUp, and does not throw exception of this type.
Can you please explain me how to reproduce this error?

**Comment by quajak** [comment]
What is the type of offset in the code block? Could you please post a pastebin with code to reproduce the issue.

**Comment by nifanfa** [comment]
> What is the type of offset in the code block? Could you please post a pastebin with code to reproduce the issue.

Offset = width*height*depth;
width and height depth are uint

**Comment by nifanfa** [comment]
> MoveDown function is being used by TextScreen.ScrollUp, and does not throw exception of this type.
> Can you please explain me how to reproduce this error?

It seems like sth need to be plug "UIntptr"

**Comment by quajak** [comment]
To reproduce and fix this issue, I need to know the types involved in the calculation which caused it. Is offset a uint or uint*?

**Comment by nifanfa** [comment]
> To reproduce and fix this issue, I need to know the types involved in the calculation which caused it. Is offset a uint or uint*?

offset is a uint. not a  uint*

**Comment by EliaSulimanov** [comment]
My guess is that maybe you get this error because you are adding a pointer to a byte with uint and then pass it.
In the original source code, uint is added with uint and then convert it to pointer to byte.

In any case, the full source code will be much helpful.
This time, post a textual version and not a screenshot.

If you paste your source code here, please use the MD ```csharp tag at the start of it, and ``` at the end, so the code syntax will highlighted.
For example, this MD code:  

\```csharp
protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
\```

Will show as:
```csharp
protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
```

**Comment by quajak** [comment]
I cant reproduce your issue, uint* + uint works.
