### ISSUE TITLE
Multi-Threading Needed

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1447]
I think we need multi-threading to support the further development

**Comment by nifanfa** [comment]
have everyone heard about "Homemade Operating System Within 30 Days"

**Comment by nifanfa** [comment]
it says thread not run as the same time. just like run as the same time?

**Comment by nifanfa** [comment]
really? threads work like this?

**Comment by nifanfa** [comment]
![QQ截图20200820190216](https://user-images.githubusercontent.com/54205437/90762987-83500080-e318-11ea-9d60-313c18752f96.png)

**Comment by charlesbetros** [comment]
Threads are not currently planned until after things like memory management and networking.
