### ISSUE TITLE
Issues with mouse on real hardware

### ISSUE THREAD

**Issue by Moldytzu** [CosmosOS/Cosmos#1448]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I/O

#### Expected Behaviour - What do you think that should happen?
The black rectangle cursor moves accordingly with the real mouse.

#### Actual Behaviour - What unexpectedly happens?
The black rectangle disappears and nothing happens.

#### Reproduction - How did you get this error to appear?
Init the MouseManager and VmwareSvgaDriver with screen resolution 800 by 600.
Write in Run() override():
`svga.Clear(0); 
 svga.Fill(MouseManager.X,MouseManager.Y,1);`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest userkit

**Comment by boomik305** [comment]
> Вы USB-мышь? Cosmos не поддерживает USB-мышь

PS/2 support?
