### ISSUE TITLE
Broken Link in Wiki

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1449]
The virtual disk downloads in the [FAT Filesystem wiki](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem) are broken. I know how to fix this and will open a pull request once given the go ahead.

**Comment by quajak** [comment]
Feel free to fix the links. Any help with the wiki is appreciated and doesnt require a go ahead.

**Comment by TFTWPhoenix** [comment]
Ok thanks!

**Comment by TFTWPhoenix** [comment]
Fixed

**Comment by quajak** [comment]
Thanks
