### ISSUE TITLE
[Filesystem BUG] Shutdown while loading the bitmap (Cannot load files larger than 1mb)

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1458]
using System;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using CosmosKernel1.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        public static VMWareSVGAII vMWareSVGAII;

        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            Bitmap wallpaper = null;

            try
            {
                wallpaper = new Bitmap(@"0:\wallpaper.bmp");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.ReadKey();
            }

            VMWareSVGAII vMWareSVGAII = new VMWareSVGAII();
            vMWareSVGAII.SetMode(1024, 600);

            Graphics graphics = new Graphics(1024, 600);
            graphics.DrawImage(0, 0, wallpaper);
            graphics.Flush(0, 0, vMWareSVGAII.width, vMWareSVGAII.height, vMWareSVGAII.Video_Memory);

            vMWareSVGAII.Update(0, 0, vMWareSVGAII.width, vMWareSVGAII.height);
        }

        protected override void Run()
        {
        }
    }
}

**Comment by nifanfa** [comment]
loading the bitmaps larger than 1000kb will shutdown. try catch won't work

**Comment by elkaamee326** [comment]
I've got that same error once. And are you using bitmaps that are 32 bit or 24 bit? If not open the bitmap in VS2019 and go image properties and change the bitmap header to 24bpp bgr or 32bpp bgr. The VMware virtual machine only has 256 MB of ram and the bitmap is 1000kb and that is almost half of the ram! If you put the bitmap to 24bpp bgr the bitmap size will decrease if it is on 32bpp bgr. Than save it onto your Cosmos Drive. Try recompiling it after you changed the bitmap header to 24bpp bgr than click on F5 and try. If you still get a shutdown error try using the Canvas method in the latest DevKit. They recently added this new feature so that you can create the bitmap using either rgb an color order or a bgr bitmap color order in the canvas method. If it helps also try increasing the amount of VM Ram in VMware. Than try this code if you installed the latest devkit and nothing else worked out:

`using Cosmos.Core;
using Cosmos.Debug.Kernel;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        ColorOrder colorOrder;
        Bitmap wallpaper;

        protected override void BeforeRun()
        {
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);
            colorOrder = ColorOrder.Bgr; // Change this to your bitmaps colorOrder found in the header 24bpp bgr

            wallpaper = new Bitmap(@"0:\wallpaper.bmp", colorOrder);

            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);

            //string s = Console.ReadLine();
            //Console.WriteLine(s);

            canvas.Clear();
            canvas.DrawImage(wallpaper, 0, 0);
            //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
            canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);

            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
            canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);

            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
            canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);

            //Console.ReadKey();
        }

        protected override void Run()
        {

        }
    }
}`

See if this helps and let me know if you find any code errors and more exceptions and shutdowns.

**Comment by nifanfa** [comment]
> I've got that same error once. And are you using bitmaps that are 32 bit or 24 bit? If not open the bitmap in VS2019 and go image properties and change the bitmap header to 24bpp bgr. The VMware virtual machine only has 256 MB of ram and the bitmap is 1000kb and that is almost half of the ram! If you put the bitmap to 24bpp bgr the bitmap size will decrease if it is on 32bpp bgr. Than save it onto your Cosmos Drive. Try recompiling it after you changed the bitmap header to 24bpp bgr than click on F5 and try. If you still get a shutdown error try using the Canvas method in the latest DevKit. They recently added this new feature so that you can create the bitmap using either rgb an color order or a bgr bitmap color order in the canvas method. If it helps also try increasing the amount of VM Ram in VMware. Than try this code if you installed the latest devkit and nothing else worked out:
> 
> `using Cosmos.Core;
> using Cosmos.Debug.Kernel;
> using Cosmos.System.FileSystem;
> using Cosmos.System.FileSystem.VFS;
> using Cosmos.System.Graphics;
> using System;
> using System.Drawing;
> using Sys = Cosmos.System;
> 
> namespace CosmosKernel1
> {
> public class Kernel : Sys.Kernel
> {
> Canvas canvas;
> ColorOrder colorOrder;
> Bitmap wallpaper;
> 
> ```
>     protected override void BeforeRun()
>     {
>         CosmosVFS cosmosVFS = new CosmosVFS();
>         VFSManager.RegisterVFS(cosmosVFS);
>         colorOrder = ColorOrder.Bgr; // Change this to your bitmaps colorOrder found in the header 24bpp bgr
> 
>         wallpaper = new Bitmap(@"0:\wallpaper.bmp", colorOrder);
> 
>         canvas = FullScreenCanvas.GetFullScreenCanvas();
>         canvas.Mode = new Mode(640, 480, ColorDepth.ColorDepth32);
> 
>         //string s = Console.ReadLine();
>         //Console.WriteLine(s);
> 
>         canvas.Clear();
>         canvas.DrawImage(wallpaper, 0, 0);
>         //canvas.DrawString($"Installed RAM:{CPU.GetAmountOfRAM()}MB", new Pen(Color.White), 10, 10);
>         canvas.DrawFilledRectangle(new Pen(Color.FromArgb(199, 199, 199)), 0, 440, 640, 40);
>         canvas.DrawFilledRectangle(new Pen(Color.White), 0, 442, 640, 1);
> 
>         canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 634, 448);
>         canvas.DrawLine(new Pen(Color.FromArgb(135, 135, 135)), 560, 448, 560, 474);
> 
>         canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 560, 474, 634, 474);
>         canvas.DrawLine(new Pen(Color.FromArgb(255, 255, 255)), 634, 448, 634, 474 + 1);
> 
>         //Console.ReadKey();
>     }
> 
>     protected override void Run()
>     {
> 
>     }
> }
> ```
> 
> }`
> 
> See if this helps and let me know if you find any code errors and more exceptions and shutdowns.

1024kb equals to 1mb. the depth is 24bit resolution is 1024*600

**Comment by elkaamee326** [comment]
Try setting it to a 32bit resolution that might help.

**Comment by elkaamee326** [comment]
And try recompiling

**Comment by nifanfa** [comment]
@elkaamee326  very weird. and i try to load image with my own format. it also makes system shutdown

**Comment by elkaamee326** [comment]
How big is the image size and what header is it?

**Comment by nifanfa** [comment]
the resolution is 1920*1080 size is 10m

**Comment by elkaamee326** [comment]
try resizing the image to 1024 x 600 using Visual Studio 2019

**Comment by nifanfa** [comment]
![QQ截图20200824215034](https://user-imag@elkaamee326 ts.githubusercontent.com/54205437/91052318-e06aef80-e653-11ea-926b-7d4edd5a14bf.png)
@elkaamee326  this is the head

**Comment by nifanfa** [comment]
@elkaamee326 
![QQ截图20200824215034](https://user-images.githubusercontent.com/54205437/91052381-f5478300-e653-11ea-9c21-971bc8ad4955.png)
this is the head

**Comment by elkaamee326** [comment]
Open the bitmap in Visual Studio 2019 than press on settings it will display the image properties and change the format if it hasn't been modified to 24bpp bgr and save.

**Comment by elkaamee326** [comment]
Than try resizing it to the 1024 x 600.

**Comment by nifanfa** [comment]
![QQ截图20200824152215](https://user-images.githubusercontent.com/54205437/91052712-6b4bea00-e654-11ea-9d5a-3cac37331736.png)
@elkaamee326  idk what's the really problem is. but if i draw smaller image it will not shutdown

**Comment by nifanfa** [comment]
i don't think it's my graphics library's problem

**Comment by elkaamee326** [comment]
Did we resolve this or is there still A problem?

**Comment by nifanfa** [comment]
we didn't solve this problem. the problem is can't load the big bitmap

**Comment by elkaamee326** [comment]
Did you change the image size, how did you make the image smaller?

**Comment by nifanfa** [comment]
i'm using windows's painter to resize the picture

**Comment by elkaamee326** [comment]
Okay, try resizing it to the VMware SVGAII Mode 1024 x 600 and it should work. 
PS: do not go over the mode size.

**Comment by nifanfa** [comment]
what i should do if i want to load big bitmap?
the problem didn't solved. load the big bitmap still shutdown

**Comment by elkaamee326** [comment]
What is your bitmap header at check with VS2019

**Comment by nifanfa** [comment]
24bit 1920x1080

**Comment by elkaamee326** [comment]
Try resizing the image again to 640 x 480 that should help. Remember try not to change the mode it will give you errors and exceptions.

**Comment by nifanfa** [comment]
i don't think it's the really solution

**Comment by nifanfa** [comment]
i found a another problem

**Comment by elkaamee326** [comment]
Whats the problem?

**Comment by nifanfa** [comment]
file.readallbytes also makes virtual machine shutdown

**Comment by elkaamee326** [comment]
Is your bitmap set to null in the code?

**Comment by nifanfa** [comment]
not even run to create bitmap

**Comment by nifanfa** [comment]
protected override void BeforeRun()
        {

            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            byte[] vs = File.ReadAllBytes(@"0:\wallpaper.bin");
        }

**Comment by nifanfa** [comment]
readbytes make virtualmachine shutdown

**Comment by nifanfa** [comment]
and i'sure the file exist

**Comment by nifanfa** [comment]
@elkaamee326  can't load the real bitmap. and i try to load my imageformat it didn't work too. system just shutdown

**Comment by nifanfa** [comment]
and i'm try to load bytes it also makes system shutdown

**Comment by elkaamee326** [comment]
Don't load the bytes the image size isn't supposed to be 1920 x 1080 thats why your probably getting the error.

**Comment by nifanfa** [comment]
![QQ截图20200824221436](https://user-images.githubusercontent.com/54205437/91055431-3e4d0680-e657-11ea-9f87-ecb0f6da8fac.png)

**Comment by nifanfa** [comment]
@elkaamee326  when i try to load bytes it got this exception

**Comment by elkaamee326** [comment]
.bin doesn't work change `byte[] vs = File.ReadAllBytes(@"0:\wallpaper.bin");` to this if you have a bitmap  `byte[] vs = File.ReadAllBytes(@"0:\wallpaper.bmp");`

**Comment by elkaamee326** [comment]
But don't try that it won't load the bitmap it will probably display a whole bunch of nonsense use the code you used here in this image:
![](https://user-images.githubusercontent.com/54205437/91052712-6b4bea00-e654-11ea-9d5a-3cac37331736.png)

 but resize the image to 640 x 480 instead of the image size you were using there

**Comment by elkaamee326** [comment]
And modify the position of the image a bit.

**Comment by nifanfa** [comment]
idk why it works before. but it not works now

**Comment by nifanfa** [comment]
![a](https://user-images.githubusercontent.com/54205437/91056156-2f1a8880-e658-11ea-8883-c1605ecd50e8.gif)

**Comment by nifanfa** [comment]
my previous project

**Comment by nifanfa** [comment]
load big image won't shotdown the system

**Comment by elkaamee326** [comment]
How does it look like now when you try

**Comment by elkaamee326** [comment]
Will or Won't?

**Comment by nifanfa** [comment]
the system just shutdown

**Comment by elkaamee326** [comment]
Did you try what I told you because COSMOS Updates their code very rapidly?

**Comment by nifanfa** [comment]
load bitmap also thrown an exception as load my bin file

**Comment by elkaamee326** [comment]
What was the exception?

**Comment by nifanfa** [comment]
> Did you try what I told you because COSMOS Updates their code very rapidly?

i didn't update the userkit

**Comment by nifanfa** [comment]
![QQ截图20200824222624](https://user-images.githubusercontent.com/54205437/91056703-ddbec900-e658-11ea-9364-3393d5174e14.png)

**Comment by elkaamee326** [comment]
Is that your image name. And instead of read all bytes put wallpaper = new Bitmap(@"0:\YourBitmapName.bmp")

**Comment by elkaamee326** [comment]
ReadAllBytes will just give you a bunch of executable nonsense stuff.

**Comment by nifanfa** [comment]
thx for your help. but problem still not solved

**Comment by elkaamee326** [comment]
Are you trying to load the big bitmap size in the DrawImage Method it consists of DrawImage(Your bitmap, Position X, Position Y);
Notice how it didn't say the image size. That is because it needs to be used in the bitmap. If you try it should work give it a shot. If it doesn't work than it is probably a Driver bug. So try resizing it to 640 x 480 and try again okay.

**Comment by nifanfa** [comment]
> Are you trying to load the big bitmap size in the DrawImage Method it consists of DrawImage(Your bitmap variable, Position X, Position Y);
> Notice how it didn't say the image size. That is because it needs to be used in the bitmap. If you try it should work give it a shot. If it doesn't work than it is probably a Driver bug. So try resizing it to 640 x 480 and try again okay.

a really problem found

**Comment by nifanfa** [comment]
can't load file over 1000kb

**Comment by nifanfa** [comment]
load file over 1000kb will makes system shutdown

**Comment by elkaamee326** [comment]
what header and size is your image? It is very important to know this

**Comment by nifanfa** [comment]
bitmap

**Comment by nifanfa** [comment]
export from windows's painter depth is 24bit

**Comment by elkaamee326** [comment]
I mean header as in 24bpp or 32bpp check by opening it in vs 2019 and go properties

**Comment by nifanfa** [comment]
![QQ截图20200824224135](https://user-images.githubusercontent.com/54205437/91058412-ff20b480-e65a-11ea-8bbb-5fe8d3dbee54.png)

**Comment by nifanfa** [comment]
now i'm not load for picture. i just try to load bytes

**Comment by elkaamee326** [comment]
And see the size and change it to 640 x 480

**Comment by elkaamee326** [comment]
And try debugging again.

**Comment by nifanfa** [comment]
it's not the problem is

**Comment by nifanfa** [comment]
640x480 can be loaded because it's less than 1mb

**Comment by nifanfa** [comment]
1024x600 can be loaded because it's more than 1mb

**Comment by elkaamee326** [comment]
That is the full screen size

**Comment by elkaamee326** [comment]
640 x 480

**Comment by nifanfa** [comment]
screen size is sizeable

**Comment by nifanfa** [comment]
can you try to load a file more than 1mb? i was wonder is this my code's problem?

**Comment by elkaamee326** [comment]
Try changing the amount of VRam and try

**Comment by nifanfa** [comment]
vram is 128mb default

**Comment by nifanfa** [comment]
i just try to load file as binary

**Comment by elkaamee326** [comment]
put the DrawImage method than your wallpaper inside

**Comment by nifanfa** [comment]
you know what the bitmap.cs using filestream to read the file as binary and decode it. and now i can't even using filestream to load my bitmap because it will makes virtual machine shutdown

**Comment by nifanfa** [comment]
and this is the reason that new bitmap("0:\\1.bmp") makes virtual machine shutdown

**Comment by elkaamee326** [comment]
Use the old bitmap in this example:

![](https://user-images.githubusercontent.com/54205437/91052712-6b4bea00-e654-11ea-9d5a-3cac37331736.png)

and resize it to the fullscreen size in your Mode(640, 480); Make sure the bitmap size is 640, 480 because than the mode can't load the bitmap because it is too large not the filesize the screen size. Than it should work flawlessly

**Comment by elkaamee326** [comment]
It can load bigger images its just the mode. You need to keep the image size and the mode and the graphics size all the exact same.

**Comment by elkaamee326** [comment]
If it is too small make the image bigger but don't forget to change the mode and the graphics to the image size. Thats what you were missing

**Comment by elkaamee326** [comment]
Let me know if this resolved the issue.

**Comment by nifanfa** [comment]
@elkaamee326  thanks for your answer. but now i met an another problem that can't read the file over 1mb.

**Comment by elkaamee326** [comment]
Do you get an error, exception or what? Are you trying to read all of the bytes of the file. What is the current source code?

**Comment by elkaamee326** [comment]
Also did the first problem get resolved?

**Comment by nifanfa** [comment]
> Also did the first problem get solved?

yes first problem solved. thank u

**Comment by elkaamee326** [comment]
Can you recall how you solved the first problem?

**Comment by nifanfa** [comment]
> Can you recall how you solved the first problem?

just resize the picture and makes it less than 1mb then i can load it

**Comment by elkaamee326** [comment]
Was the image a fullscreen?

**Comment by nifanfa** [comment]
> Was the image a fullscreen?

no

**Comment by elkaamee326** [comment]
What is the size?

**Comment by nifanfa** [comment]
there's no resize picture method in cosmos currently

**Comment by nifanfa** [comment]
> What is the size?

any size if less than 1mb

**Comment by elkaamee326** [comment]
The image width and height

**Comment by nifanfa** [comment]
cosmos has filesystem problem.

**Comment by nifanfa** [comment]
> The image width and height

640*480 is safe

**Comment by nifanfa** [comment]
but it's 2020 now. who has a screen with 640*480

**Comment by elkaamee326** [comment]
What is the mode size and graphics size because I think instead of CGS VMwareSVGAII uses the Image width and height ratio to the Mode

**Comment by nifanfa** [comment]
i didn't use cgs

**Comment by elkaamee326** [comment]
Try Changing Mode = new Mode(1024, 600); and change the graphics variable to to 1024 x 600 and change the image back to 1024 x 600 and save. Than try debugging again and see if it is a code variable error or a filesystem error.

**Comment by nifanfa** [comment]
> Try Changing Mode = new Mode(1024, 600); and change the graphics variable to to 1024 x 600 and change the image back to 1024 x 600 and save. Than try debugging again and see if it is a code variable error or a filesystem error.

it nothing to do with screen mode

**Comment by nifanfa** [comment]
the problem is can't load the bitmap above 1mb

**Comment by nifanfa** [comment]
you can set any screen size you want even 4k

**Comment by elkaamee326** [comment]
The modes need to be the same in order to draw the fullscreen image.

**Comment by nifanfa** [comment]
can't load the bitmap which is 1024x600

**Comment by nifanfa** [comment]
it's more than 1mb

**Comment by nifanfa** [comment]
so if we want to draw a full screen image. you have to set your screen size in 640x480. oh man. where can i find a moniter in 2020 with 640x480?

**Comment by elkaamee326** [comment]
Okay, i'll try loading it with an image size 1024 x 600 and bigger than 1mb and see if I get the same errors too. And if it is successful, than i'll tell you the settings and source code that I have so you can use it.

**Comment by nifanfa** [comment]
> Okay, i'll try loading it with an image size 1024 x 600 and bigger than 1mb and see if I get the same errors too. And if it is successful, than i'll tell you the settings and source code that I have so you can use it.

thanks a lot

**Comment by elkaamee326** [comment]
Can I use the source code that you have and see if it works please?

**Comment by nifanfa** [comment]
[CosmosKernel1.zip](https://github.com/CosmosOS/Cosmos/files/5119201/CosmosKernel1.zip)

**Comment by nifanfa** [comment]
sure if u want

**Comment by nifanfa** [comment]
goto C:\Users\nifan\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\
and mount the filesystem.vmdk
add ur image in it

**Comment by elkaamee326** [comment]
I figured out how to put it full screen I modified the earlier position  to this `graphics.DrawImage(0, 0, sb);`. Here is the modified source code:

`using System;
using System.Drawing;
using System.IO;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using Cosmos.System.Graphics;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        public static VMWareSVGAII vMWareSVGAII;

        protected override void BeforeRun()
        {
            #region Debug
            CosmosVFS cosmosVFS = new CosmosVFS();
            VFSManager.RegisterVFS(cosmosVFS);

            Bitmap sb = new Bitmap(@"0:\sb.bmp");
            Bitmap bitmap = new Bitmap(@"0:\logo.bmp");

            vMWareSVGAII = new VMWareSVGAII();
            vMWareSVGAII.SetMode(1024, 600); // Make sure the bitmap dimensions are also 1024 X 600

            Graphics graphics = new Graphics(1024, 600); // Make sure the bitmap dimensions are also 1024 X 600

            graphics.Clear(Color.Red.ToArgb());
            graphics.Fill(-100, 280, 200, 200, Color.Blue.ToArgb());
            graphics.DrawImage(0, 0, sb);
            graphics.SetPixel(60, 80, Color.Black.ToArgb());
            graphics.DrawLine(10, 10, 50, 50, Color.Green.ToArgb());
            graphics.DrawRectangle(100, 100, 20, 20, Color.Black.ToArgb());
            graphics.DrawImageWithAlpha(150, 10, bitmap);
            graphics.DrawCircle(400, 300, 50, Color.Brown.ToArgb());
            graphics.DrawACSIIString(40, 55, "Hello World", Color.White.ToArgb());
            graphics.Flush(0, 0, vMWareSVGAII.width, vMWareSVGAII.height, vMWareSVGAII.Video_Memory);

            Graphics graphics1 = new Graphics(100, 100);
            graphics1.Clear(Color.Green.ToArgb());
            graphics1.Flush(300, 300, vMWareSVGAII.width, vMWareSVGAII.height, vMWareSVGAII.Video_Memory);

            Graphics graphics2 = new Graphics(300, 100);
            graphics2.CopyFromGraphics(graphics, 15, 380);
            graphics2.Blur(5);
            graphics2.Flush(500, 350, vMWareSVGAII.width, vMWareSVGAII.height, vMWareSVGAII.Video_Memory);

            vMWareSVGAII.Update(0, 0, vMWareSVGAII.width, vMWareSVGAII.height);
            #endregion
        }

        protected override void Run()
        {
        }
    }
}`

If the bitmap hasn't been resized yet than resize it to 1024 x 600 and save. If you get a weird looking bitmap than change the bitmap header from 24bpp to 32bpp. Hope this solved it. 

PS. Its not the filesystem because it loaded a bitmap (not 100% correctly not because of VMwareSVGAII because of my bitmap header maybe) But don't worry about that it should still work fine. Just replace the current code with the modified code.

**Comment by elkaamee326** [comment]
If your bitmap worked before in the small image than don't worry about the PS thing about the image. It's just the image i'm using since you are using A different image that most likely won't happen okay.

**Comment by nifanfa** [comment]
@elkaamee326 have you tried to load a bitmap above 1m?

**Comment by quajak** [comment]
So the underlying problem seems to be handling files with a size larger than 1MB. Most likely some problem in the filesystem, which will have to be investigated.

**Comment by nifanfa** [comment]
> Yes I tried but it did not shutdown the os. Did you copy and paste the code I modified?

can you send your bitmap?

**Comment by elkaamee326** [comment]
Here is the bmp [Wallpaper_Bmp.zip](https://github.com/CosmosOS/Cosmos/files/5120205/Wallpaper_Bmp.zip)

It loaded half of it and the rest a bunch of weird lines. I would recommend using your bitmap or if you want to use mine, change the header to 24bpp.

**Comment by nifanfa** [comment]
@elkaamee326 thx for help

**Comment by elkaamee326** [comment]
Did it work?

**Comment by nifanfa** [comment]
> Did it work?

unfortunately no

**Comment by elkaamee326** [comment]
How did it not work?

**Comment by nifanfa** [comment]
is still shutdown

**Comment by nifanfa** [comment]
can't load the bitmap

**Comment by elkaamee326** [comment]
With your bitmap or mine

**Comment by nifanfa** [comment]
how your works?

**Comment by nifanfa** [comment]
yes

**Comment by nifanfa** [comment]
i'm using your bitmap

**Comment by nifanfa** [comment]
hey man. i mean i just can't load the bitmap. not my screen size's problem..

**Comment by elkaamee326** [comment]
Can you send me the shutdown

**Comment by elkaamee326** [comment]
Error message?

**Comment by nifanfa** [comment]
no error message

**Comment by nifanfa** [comment]
try catch won't work

**Comment by elkaamee326** [comment]
What is it saying?

**Comment by nifanfa** [comment]
nothing

**Comment by elkaamee326** [comment]
Does it initialize the filesystem?

**Comment by nifanfa** [comment]
just run and the vmware player started and the screen shown the partitions info. and virtual machine shutdown

**Comment by nifanfa** [comment]
> Does it initialize the filesystem?

yes sure

**Comment by elkaamee326** [comment]
It shutdown?

**Comment by nifanfa** [comment]
how did your works? can you send your screenshot?

**Comment by nifanfa** [comment]
> It shutdown?

yes just like before

**Comment by nifanfa** [comment]
nothing changed

**Comment by elkaamee326** [comment]
I'll send you the solution okay .sln file

**Comment by elkaamee326** [comment]
But use your bitmaps okay because they worked better than my bitmap

**Comment by nifanfa** [comment]
thx

**Comment by elkaamee326** [comment]
[CosmosKernel1.zip](https://github.com/CosmosOS/Cosmos/files/5120266/CosmosKernel1.zip)

**Comment by elkaamee326** [comment]
Now use only your bitmap files and try okay and make sure the image is the same size / dimensions as the mode and graphics variables

**Comment by nifanfa** [comment]
@elkaamee326  i have a question

**Comment by nifanfa** [comment]
what's the version of your userkit?

**Comment by elkaamee326** [comment]
20200708

**Comment by elkaamee326** [comment]
Latest userkit

**Comment by nifanfa** [comment]
man my problem is can't load the bitmap. not can't show the bitmap

**Comment by nifanfa** [comment]
like Bitmap b = new Bitmap("0:\\Bitmap.bmp")

**Comment by nifanfa** [comment]
it will makes virtual machine shutdown

**Comment by nifanfa** [comment]
it's even nothing to do with my gui

**Comment by elkaamee326** [comment]
It worked fine for me. Let me try another bitmap file and see if it loads this time okay.

**Comment by nifanfa** [comment]
and it also worked fine for me

**Comment by elkaamee326** [comment]
How?

**Comment by nifanfa** [comment]
i mean. when you load a bitmap that above than 1mb then system will shutdown

**Comment by nifanfa** [comment]
the images that i'm using all less than 1mb

**Comment by elkaamee326** [comment]
Did the other bitmaps load fullscreen?

**Comment by nifanfa** [comment]
sure

**Comment by nifanfa** [comment]
it just can't load bitmap above 1mb

**Comment by nifanfa** [comment]
every file like this. you can read a file above than 1mb

**Comment by elkaamee326** [comment]
Than in that case just find another bitmap file that is less than 1 mb and use that. For you it is most likely a bug.

**Comment by elkaamee326** [comment]
Or something?

**Comment by nifanfa** [comment]
it's a bug

**Comment by elkaamee326** [comment]
Do you have the latest userkit?

**Comment by nifanfa** [comment]
yes sure

**Comment by nifanfa** [comment]
![QQ截图20200825052546](https://user-images.githubusercontent.com/54205437/91098107-75d9a400-e693-11ea-8c3f-32dbc10c1c07.png)

**Comment by nifanfa** [comment]
see this

**Comment by nifanfa** [comment]
i can load this bitmaps because these all less than 1mb

**Comment by elkaamee326** [comment]
It shutsdown when it is more than 1mb. Can I see an example please.

**Comment by nifanfa** [comment]
![QQ截图20200825052726](https://user-images.githubusercontent.com/54205437/91098220-afaaaa80-e693-11ea-8e6e-5d3be489df3e.png)

**Comment by elkaamee326** [comment]
What are the image dimensions because you can resize that to full screen

**Comment by nifanfa** [comment]
you can try it your self. make a new cosmoskernel project. and add your file above 1mb to the filesystem.vmdk. and load it in cosmos by filestream or file.readallbytes such fill access

**Comment by nifanfa** [comment]
i'm sure it will shutdown

**Comment by nifanfa** [comment]
> What are the image dimensions because you can resize that to full screen?

man you read it worng my mean

**Comment by nifanfa** [comment]
access a file any file above 1mb will makes system shutdown

**Comment by nifanfa** [comment]
i think it's a filesystem bug

**Comment by elkaamee326** [comment]
It worked for me it is not a filesystem bug

![image](https://user-images.githubusercontent.com/69808082/91100801-d33e0880-e633-11ea-8d2e-21cb3fe6b39a.png)

this is the solution file:

[CosmosKernel.zip](https://github.com/CosmosOS/Cosmos/files/5120426/CosmosKernel.zip)

This is the image I used:

[wallpaper.zip](https://github.com/CosmosOS/Cosmos/files/5120433/wallpaper.zip)

The image is bigger than a mb on my computer. Put the image in Filesystem.vmdk 0:\wallpaper.bmp and try recompiling. If you still get an error. Than my only suggestion is you reinstall cosmos okay. Hope this really helps solve the issue.

**Comment by nifanfa** [comment]
> It worked for me it is not a filesystem bug
> 
> ![image](https://user-images.githubusercontent.com/69808082/91100801-d33e0880-e633-11ea-8d2e-21cb3fe6b39a.png)
> 
> this is the solution file:
> 
> [CosmosKernel.zip](https://github.com/CosmosOS/Cosmos/files/5120426/CosmosKernel.zip)
> 
> This is the image I used:
> 
> [wallpaper.zip](https://github.com/CosmosOS/Cosmos/files/5120433/wallpaper.zip)
> 
> The image is bigger than a mb on my computer. Put the image in Filesystem.vmdk 0:\wallpaper.bmp and try recompiling. If you still get an error. Than my only suggestion is you reinstall cosmos okay. Hope this really helps solve the issue.
> 
> 
> 

Can you use a bigger bitmap?

**Comment by nifanfa** [comment]
Idk the real problem is

**Comment by elkaamee326** [comment]
Do you mean larger in size or as in the dimensions?

**Comment by elkaamee326** [comment]
It's a filesystem bug. Put the file in another location and rename it and than try debugging again.

**Comment by elkaamee326** [comment]
When this is solved than close the issue, okay.

**Comment by elkaamee326** [comment]
I figured out that some files worked and some files didn't It is really mostly the file because some files don't work some files just glitch some files gave me a CPU Exception and they range from all file sizes from 900 kb to 1.17mb it really depends on the file so if you use the right file converter tools than it should work fine because I noticed that the filesystem writes to the bitmap the cache and data so if you had problems with that file than find a different similar file or redownload the file and try. It is not only 1mb files it also shut down  A 900kb file too. You see it is the file that you were using not so much the size.  So re download the file and try loading it again. Find the files you want (not too big maybe not more than 1.17 MB) and do a trial and error so you will know which files worked and which didn't. It What was the name of the file converter you were using? Every file converter is different. Can you post the file converter you used below please?

**Comment by elkaamee326** [comment]
The 1.17 MB file worked, but the 900 KB file didn't work.

**Comment by nifanfa** [comment]
@elkaamee326 i'll find out how to load large file then close the question. thx

**Comment by quajak** [comment]
Well larger files should always work, can you please post a few files which dont work? Can you also confirm if you add the same file multiple times to the filesystem, that all of them can be loaded?

**Comment by nifanfa** [comment]
[a.zip](https://github.com/CosmosOS/Cosmos/files/5123882/a.zip)
@quajak this file can't be loaded. when i try to load this then system shutdown

**Comment by EliaSulimanov** [comment]
Are you sure the file you are tring to load is not corrupted?
Is the header correct?
The file system and bitmap are very sensitive.

**Comment by nifanfa** [comment]
#1844

**Comment by GoldenretriverYT** [comment]
probably related to the many memory leaks recently fixed, people are not complaining about that issue and I have seen a bunch of people loading bmps >1mb lately, so i think this can be closed

**Comment by valentinbreiz** [comment]
Fixed with last file system updates
