### ISSUE TITLE
Error on installer

### ISSUE THREAD

**Issue by PopulationX** [CosmosOS/Cosmos#1459]
#### Area of Cosmos - What area of Cosmos are we dealing with?
The Installation task

#### Expected Behaviour - What do you think that should happen?
The DevKit being ready for use. 

#### Actual Behaviour - What unexpectedly happens?
I get an Error 

#### Reproduction - How did you get this error to appear?
Just run the installer

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
quajak Merge pull request #1454 from CosmosOS/bug/random

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Determining projects to restore...
  All projects are up-to-date for restore.

========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=C:\Cosmos\Build\VSIP\\" /p:"VsixOutputPath=C:\Cosmos\Build\VSIP\\" /p:DeployExtension=False
  Cosmos.Debug.Common -> C:\Cosmos\Build\VSIP\Cosmos.Debug.Common.dll
  Cosmos.Build.Common -> C:\Cosmos\Build\VSIP\Cosmos.Build.Common.dll
  Cosmos.Debug.DebugConnectors -> C:\Cosmos\Build\VSIP\Cosmos.Debug.DebugConnectors.dll
  VSPropertyPages -> C:\Cosmos\Build\VSIP\VSPropertyPages.dll
  Cosmos.VS.Windows -> C:\Cosmos\Build\VSIP\Cosmos.VS.Windows.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3036,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [C:\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]
  Cosmos.Deploy.USB -> C:\Cosmos\Build\VSIP\Cosmos.Deploy.USB.exe
  Cosmos.Debug.GDB -> C:\Cosmos\Build\VSIP\Cosmos.Debug.GDB.exe
  Cosmos.Deploy.Pixie -> C:\Cosmos\Build\VSIP\Cosmos.Deploy.Pixie.exe
  Cosmos.Debug.Kernel -> C:\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.dll
  IL2CPU.Debug.Symbols -> C:\Cosmos\Build\VSIP\IL2CPU.Debug.Symbols.dll
  IL2CPU.API -> C:\Cosmos\Build\VSIP\IL2CPU.API.dll
  Cosmos.Core.DebugStub -> C:\Cosmos\Build\VSIP\Cosmos.Core.DebugStub.dll
  Spruce -> C:\Cosmos\Build\VSIP\Spruce.dll
  Determining projects to restore...
  All projects are up-to-date for restore.
  Cosmos.Debug.HyperVServer -> C:\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Debug.HyperVServer -> C:\Cosmos\source\Cosmos.Debug.Hosts\obj\Debug\netstandard2.0\HyperVServer\
  Cosmos.Debug.Hosts -> C:\Cosmos\Build\VSIP\Cosmos.Debug.Hosts.dll
  Cosmos.Common -> C:\Cosmos\Build\VSIP\Cosmos.Common.dll
  Cosmos.Core -> C:\Cosmos\Build\VSIP\Cosmos.Core.dll
  Cosmos.TestRunner.TestController -> C:\Cosmos\Build\VSIP\Cosmos.TestRunner.TestController.dll
  XSharp -> C:\Cosmos\Build\VSIP\XSharp.dll
  Cosmos.Debug.Kernel.Plugs.Asm -> C:\Cosmos\Build\VSIP\Cosmos.Debug.Kernel.Plugs.Asm.dll
  TheRingMaster -> C:\Cosmos\Build\VSIP\TheRingMaster.dll
  Cosmos.HAL2 -> C:\Cosmos\Build\VSIP\Cosmos.HAL2.dll
  Cosmos.System2 -> C:\Cosmos\Build\VSIP\Cosmos.System2.dll
  Cosmos.System2_Plugs -> C:\Cosmos\Build\VSIP\Cosmos.System2_Plugs.dll
  NASM -> C:\Cosmos\Build\VSIP\NASM.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]
  Cosmos.Build.Tasks -> C:\Cosmos\Build\VSIP\Cosmos.Build.Tasks.dll
  Cosmos.VS.DebugEngine -> C:\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.dll
  Cosmos.IL2CPU -> C:\Cosmos\Build\VSIP\Cosmos.IL2CPU.dll
  Cosmos.Debug.HyperVServer -> C:\Cosmos\Build\VSIP\Cosmos.Debug.HyperVServer.exe
  Cosmos.Core_Asm -> C:\Cosmos\Build\VSIP\Cosmos.Core_Asm.dll
  IL2CPU -> C:\Cosmos\Build\VSIP\IL2CPU.dll
  Cosmos.Core_Plugs -> C:\Cosmos\Build\VSIP\Cosmos.Core_Plugs.dll
  Cosmos.VS.DebugEngine -> C:\Cosmos\Build\VSIP\Cosmos.VS.DebugEngine.vsix

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process) in C:\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 67
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2() in C:\Cosmos\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext() in C:\Cosmos\source\Cosmos.Build.Builder\ViewModels\MainWindowViewModel.cs:line 128

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1100

**Comment by embedisbae** [comment]
> See #1100

This didn't work for me. Same error.

**Comment by quajak** [comment]
Please post your error message
