### ISSUE TITLE
VGAScreen crashes the IL2CPU compiler

### ISSUE THREAD

**Issue by CSharpLover** [CosmosOS/Cosmos#146]
Hi again. I was adding GUI support to my OS.
I'm using last devkit. But, it always says this strange error.

2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.Exception: Assembly 'CosmosKernel1' is in ring User(3). It references assembly 'Cosmos.HAL' which is in ring HAL(1), but this is not allowed!
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner, Assembly entryAssembly) in c:\Users\UserName\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 116
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Users\UserName\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 240
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.

I tried these forms of VGAScreen.

public static VGAScreen scr;
private VGAScreen scr;
public static VGAScreen scr = new VGAScreen();
private VGAScreen scr = new VGAScreen();

After one of these, i'm putting this code.
scr.Cear(0);

It has no errors in editor, but while IL2CPU compiling, the compiler crashes with this error.

Can we fix it, or has it a manual fix with changing source code? I can recompile my cosmos if it required.

**Comment by mterwoord** [comment]
This is due to our kernel architecture. There's a VGAScreen class in the System namespace as well, but that one needs to be extended so it forwards (for now...) the calls..

**Comment by lukaandjelkovic** [comment]
@mterwoord can you say this little more understandable?

**Comment by mterwoord** [comment]
Our architecture consists of levels. You cannot call into level1 (HAL) from level 3 (user code). You have to have a class in the middle (System)
