### ISSUE TITLE
Workloads

### ISSUE THREAD

**Issue by omerhijazi404** [CosmosOS/Cosmos#1460]
I just downloaded the latest repo and tried installing the devkit, but it starts installing workloads and doesn't do anything and there is no installer task in task manager, so can't I install the workloads manually, like can anyone tell me the exact workloads to be installed as that'd be much, much easier.
Thanks in advance :)

**Comment by quajak** [comment]
Check here for the required workloads https://www.gocosmos.org/download/

**Comment by embedisbae** [comment]
Running the installer as admin worked for me. It did give me a "Visual Studio Workloads failed to install" after installation but restarting the installer worked.

**Comment by omerhijazi404** [comment]
I have installed everything mentioned from .net to inno pack
But still it asks for workloads
And by the way, what is "visual studio workloads: visual studio extension development"
As I didn't understand that
Anyway as embedisbae has said I'll try running as administrator.

**Comment by quajak** [comment]
This is the visual studio extension workload you need https://docs.microsoft.com/en-us/visualstudio/extensibility/installing-the-visual-studio-sdk?view=vs-2019

**Comment by ChristofBecu** [comment]
The installer somehow messes up when VS Build Tools is installed next to Visual Studio.
After uninstalling VS Build Tools, the necessary workloads are detected/installed correctly.
Another workaround is [commenting out 1 line of code](https://github.com/CosmosOS/Cosmos/issues/1233#issuecomment-546464379), like that you can keep your VS Build Tools.

**Comment by omerhijazi404** [comment]
Well I have tried everything but it still says installing workloads and task manager doesn't show and vsinstaller.exe or anything related to visual studio installer

**Comment by omerhijazi404** [comment]
I uncommented and ran and everything went fine until:

![Capture44](https://user-images.githubusercontent.com/65223292/96090761-5f044080-0ed1-11eb-89e2-93ee6fab18d4.PNG)
![Capture33](https://user-images.githubusercontent.com/65223292/96090764-60356d80-0ed1-11eb-84ab-1ad599551c12.PNG)

**Comment by quajak** [comment]
Please copy and post the entire log, the actual error is further up in the log.

**Comment by omerhijazi404** [comment]
by the way, i ran the resulting setup and it ran well, but in visual studio while building with a project that has floats, I saw this:
![Capture44](https://user-images.githubusercontent.com/65223292/96094652-48141d00-0ed6-11eb-9aec-4398f37b7212.PNG)

There was a dropdown for Cosmos Plugs, so i thought something might have worked, but in build:   Need plug for: System.Int32  System.Threading.Interlocked.ExchangeAdd(&System.Int32, System.Int32)

**Comment by omerhijazi404** [comment]
> Please copy and post the entire log, the actual error is further up in the log.

https://pastebin.com/j9prCDhV

**Comment by quajak** [comment]
While it may be possible to add plugs from any dll, it is currently easiest to add a new plug to the cosmos source code in the devkit in one of the existing project.  It should be possible to add a plug for `System.Int32 System.Threading.Interlocked.ExchangeAdd(&System.Int32, System.Int32)` in https://github.com/CosmosOS/Cosmos/blob/1f8264132699148e41783e3087531d1e9c138be9/source/Cosmos.Core_Plugs/System/Threading/InterlockedImpl.cs#L7 similar to the other plug in the file. For other problems please create a new issue.

**Comment by omerhijazi404** [comment]
Well i have successfully installed
