### ISSUE TITLE
It wont build the OS.

### ISSUE THREAD

**Issue by embedvr** [CosmosOS/Cosmos#1461]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building my Operation System

#### Expected Behaviour - What do you think that should happen?
Build my OS.

#### Actual Behaviour - What unexpectedly happens?
It skips it. 

#### Reproduction - How did you get this error to appear?
I attempt to build it.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit Latest / Commit 8ebc75dab280924d61dc75ba37f7feeb4c96a31b

Screenshot https://doggo.ninja/nQlXRG.png

**Comment by embedisbae** [comment]
I should add that attempting to press Start in VS2019 gives me this.
https://doggo.ninja/vxVhO5.png

**Comment by quajak** [comment]
Can you click on the project directly *not the solution* and click on build the project from there?

**Comment by embedisbae** [comment]
> Can you click on the project directly _not the solution_ and click on build the project from there?

It just outputs "1 skipped" if I build it from the project or the solution. no difference.

**Comment by quajak** [comment]
Can you post the content of the csproj file?

**Comment by embedisbae** [comment]
`<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
        <RuntimeIdentifier>cosmos</RuntimeIdentifier>
        <SelfContained>True</SelfContained>
        <BinFormat>ELF</BinFormat>
        <StackCorruptionDetectionEnabled>True</StackCorruptionDetectionEnabled>
        <StackCorruptionDetectionLevel>MethodFooters</StackCorruptionDetectionLevel>
        <Deployment>ISO</Deployment>
        <DebugEnabled>False</DebugEnabled>
        <DebugMode>Source</DebugMode>
        <IgnoreDebugStubAttribute>False</IgnoreDebugStubAttribute>
        <VMware_StackCorruptionDetectionEnabled>True</VMware_StackCorruptionDetectionEnabled>
        <VMware_StackCorruptionDetectionLevel>MethodFooters</VMware_StackCorruptionDetectionLevel>
        <VMware_Description>Use VMware Player or Workstation to deploy and debug.</VMware_Description>
        <VMware_Deployment>ISO</VMware_Deployment>
        <VMware_Launch>VMware</VMware_Launch>
        <VMware_DebugEnabled>False</VMware_DebugEnabled>
        <VMware_DebugMode>Source</VMware_DebugMode>
        <VMware_IgnoreDebugStubAttribute>False</VMware_IgnoreDebugStubAttribute>
        <VMware_CosmosDebugPort>Serial: COM1</VMware_CosmosDebugPort>
        <VMware_VisualStudioDebugPort>Pipe: Cosmos\Serial</VMware_VisualStudioDebugPort>
        <VMware_PxeInterface>192.168.0.8</VMware_PxeInterface>
        <VMware_EnableGDB>False</VMware_EnableGDB>
        <VMware_StartCosmosGDB>False</VMware_StartCosmosGDB>
    </PropertyGroup>

    <PropertyGroup>
        <EnableGDB>False</EnableGDB>
        <StartCosmosGDB>False</StartCosmosGDB>
        <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
        <CosmosDebugPort>Serial: COM1</CosmosDebugPort>
        <Launch>None</Launch>
        <Profile>ISO</Profile>
        <Description>Creates a bootable ISO image which can be burned to a DVD. After running the selected project, an explorer window will open containing the ISO file. The ISO file can then be burned to a CD or DVD and used to boot a physical or virtual system.</Description>
        <PxeInterface>192.168.0.8</PxeInterface>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cosmos.Build" Version="0-*" NoWarn="NU1604" />
        <PackageReference Include="Cosmos.Debug.Kernel" Version="0-*" NoWarn="NU1604" />
        <PackageReference Include="Cosmos.System2" Version="0-*" NoWarn="NU1604" />
    </ItemGroup>

</Project>
`

**Comment by quajak** [comment]
Can you ensure that the nuget packages are on the newest Prerelease version?
Can you try switching the launch setting to VMWare?
