### ISSUE TITLE
[Question] How To Download a file ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1462]
Hello, i try to download a file with System.Net and WebClient but he didn't work this error apearer :System.NotImplementedException: OpCode 'Endfilter' not implemented!	ArtOS_Kernel	C:\Users\UserName\Desktop\ArtOS\Cosmos\ArtOS\IL2CPU	1	
So I turn to you, how can I download files with CosmosOS

**Comment by quajak** [comment]
Networking is currently not supported, so this is impossible without writing the drivers yourself for now.
