### ISSUE TITLE
I got "Exception: System.Exception:" in IL2CPU

### ISSUE THREAD

**Issue by EmDeeTee** [CosmosOS/Cosmos#1465]
![Przechwytywanie](https://user-images.githubusercontent.com/69502706/91666581-38936d00-eafe-11ea-9c26-80eedbf629e4.JPG)

#### Area of Cosmos - What area of Cosmos are we dealing with?
when trying to compile

#### Expected Behaviour - What do you think that should happen?
project should compile

#### Actual Behaviour - What unexpectedly happens?
Compile error

#### Reproduction - How did you get this error to appear?
After writing simple code and trying to compile

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708 Cosmos C#

**Comment by 5271** [comment]
:)
