### ISSUE TITLE
Softlocking when trying to start the ACPI

### ISSUE THREAD

**Issue by fdagrewwwfdgsdfs** [CosmosOS/Cosmos#1466]
#### Area of Cosmos - What area of Cosmos are we dealing with?
ACPI

#### Expected Behaviour - What do you think that should happen?
ACPI should start and the OS to continue running

#### Actual Behaviour - What unexpectedly happens?
The OS softlocks.

#### Reproduction- How did you get this error to appear?
Use this code:
`Cosmos.Core.ACPI.Start();`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

**Comment by quajak** [comment]
You shouldnt ned to call ACPI.Start as it is already being called when the kernel starts

**Comment by fdagrewwwfdgsdfs** [comment]
Ok! Thanks
