### ISSUE TITLE
(PS/2 Controller) PS/2 Device Not Supported

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1469]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Boot

#### Expected Behaviour - What do you think that should happen?

Start Succesfully.

#### Actual Behaviour - What unexpectedly happens?

Finding PCI Devices
Starting ACPI
Exeption occurred while running kernel:
Exeption: (PS/2 Controller) PS/2 Device Not Supported

#### Reproduction - How did you get this error to appear?

Boot From USB

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Userkit

Here Is The Screenshot:
![Cosmos_USB_Boot_Error](https://user-images.githubusercontent.com/70532109/91743023-3dbcee80-ebc8-11ea-8512-663bf07e9650.jpg)

**Comment by quajak** [comment]
Does it work when running with VMare? What are you doing in the kernel?

**Comment by Vardan2009** [comment]
@quajak Yes. It Works When I Run it in **VMware**

**Comment by quajak** [comment]
It seems like some hardware connected to the PC is not supported by Cosmos.

**Comment by Vardan2009** [comment]
What Hardware it can be?

**Comment by quajak** [comment]
It could be the mouse. Do you have the option in the bios to enable legacy ps/2 mouse?

**Comment by Vardan2009** [comment]
Ok, I'll try 👍

**Comment by Vardan2009** [comment]
@quajak **Update** _I tried boot from another computer and it worked_

**Comment by bartekmuzyk** [comment]
A bit late to the party, but I'll leave this tip here:
Sometimes the touchpad or some other built-in pointing device is used as a PS/2 device by the hardware and if you're lucky you can change this in your BIOS setup.

**Comment by Vardan2009** [comment]
I Changed Some Settings in BIOS and it now boots , BUT the keyboard is **Not working **![IMG_20200922_000629.jpg](https://user-images.githubusercontent.com/70532109/93815845-b3682780-fc67-11ea-99b4-bed2a5cf38f3.jpg)

**Comment by quajak** [comment]
Please open a new issue

**Comment by Vardan2009** [comment]
@quajak ok
