### ISSUE TITLE
Cosmos.Assembler crashes IL2CPU compiler.

### ISSUE THREAD

**Issue by CSharpLover** [CosmosOS/Cosmos#147]
Hi.

I was trying switch back real mode from protected mode. I imported Cosmos.Assembler class.

And i wrote this code:

            new Cosmos.Assembler.x86.ClrInterruptFlag();
            new Cosmos.Assembler.x86.Mov { SourceReg = Cosmos.Assembler.x86.Registers.CR0, DestinationReg = Cosmos.Assembler.x86.Registers.EAX };
            new Cosmos.Assembler.x86.Or { SourceValue = 1, DestinationReg = Cosmos.Assembler.x86.Registers.AL };
            new Cosmos.Assembler.x86.Mov { SourceReg = Cosmos.Assembler.x86.Registers.EAX, DestinationReg = Cosmos.Assembler.x86.Registers.CR0 };
            new Cosmos.Assembler.x86.Sti();

But, while i compiling it, it throws an IL2CPU exception.

Exception is:

2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.Exception: Native code encountered, plug required. Please see http://cosmos.codeplex.com/wikipage?title=Plugs). System.Object  System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType).
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :  Called from :
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : System.Collections.Generic.EqualityComparer`1[System.Type]::System.Collections.Generic.EqualityComparer`1[System.Type] CreateComparer()
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : System.Collections.Generic.EqualityComparer`1[System.Type]::System.Collections.Generic.EqualityComparer`1[System.Type] get_Default()
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : System.Collections.Generic.Dictionary`2[System.Type,System.String]::Void .ctor(Int32, System.Collections.Generic.IEqualityComparer`1[System.Type])
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : System.Collections.Generic.Dictionary`2[System.Type,System.String]::Void .ctor()
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Cosmos.Assembler.Instruction::Void .cctor()
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Cosmos.Assembler.Instruction
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Users\Faruk\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 525
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Users\Faruk\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 670
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Users\Faruk\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Users\Faruk\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.

Please, i really need fix it, executing assembly commands is very very important for me.
Is there a fix for it?

**Comment by mterwoord** [comment]
Can you show more context to your code? where are you using the assembler? 

Keep in mind that the assembler is part of the compiler, so using them in your kernel is not going to work. It's usable in plugs though..

**Comment by CSharpLover** [comment]
It is my full code.
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.HAL;
using Cosmos.Assembler;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {

        protected override void BeforeRun()
        {
            new Cosmos.Assembler.x86.ClrInterruptFlag();
            new Cosmos.Assembler.x86.Mov { SourceReg = Cosmos.Assembler.x86.Registers.CR0, DestinationReg = Cosmos.Assembler.x86.Registers.EAX };
            new Cosmos.Assembler.x86.Or { SourceValue = 1, DestinationReg = Cosmos.Assembler.x86.Registers.AL };
            new Cosmos.Assembler.x86.Mov { SourceReg = Cosmos.Assembler.x86.Registers.EAX, DestinationReg = Cosmos.Assembler.x86.Registers.CR0 };
            new Cosmos.Assembler.x86.Sti();
        }

        protected override void Run()
        {

        }
    }
}

Can writing a plug fix this problem?

**Comment by mterwoord** [comment]
You're using the compiler (assembler) as part of the kernel. THat's not possible. The only way that's possible is using assembler plugs. 

What are you trying to achieve?

**Comment by CSharpLover** [comment]
I'm trying switching real mode or another only-assembly thing.
Can you give an example to assembler plug?
I really need to use assembly.

**Comment by mterwoord** [comment]
Functionally speaking, what are you trying to achieve?

Right now, assembler plugs are possible everywhere I think, but at some point relatively soon, we'll diswable that. Almost everything can be done using c# code in Cosmos.

**Comment by mterwoord** [comment]
For more info on plugs, see https://github.com/CosmosOS/Cosmos/wiki/Intro-to-Plugs
