### ISSUE TITLE
Array.Length returns the same wrong negative value

### ISSUE THREAD

**Issue by ascpixel** [CosmosOS/Cosmos#1470]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Arrays/System namespace/Built-in types

#### Expected Behaviour - What do you think that should happen?
Array.Length should return a non-negative value that is the length of the array.

#### Actual Behaviour - What unexpectedly happens?
Array.Length returns a weird negative value: `-268370093`, no matter the file. A 512 byte, 22kb, and a 11kb file return this value.

#### Reproduction - How did you get this error to appear?
1. Create a byte array with a ManifestResourceStream attribute in the main Kernel class
2. Set the ManifestResourceStream attribute to point to a file
3. See the value of <byte array>.Length

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit v20200708

**Comment by zarlo** [comment]
i dont think ManifestResourceStream works

**Comment by quajak** [comment]
They seem to be working @zarlo

**Comment by quajak** [comment]
The likely problem is that the target of the manifest data stream was not static.

**Comment by charlesbetros** [comment]
Here's an example.

https://github.com/CosmosOS/Cosmos/blob/master/Demos/ZMachine/ZKernel/Kernel.cs#L19

**Comment by ascpixel** [comment]
Sorry for such a late response, but yep, the issue was that it wasn't static.
