### ISSUE TITLE
Cannot do anything in every directories but the root one

### ISSUE THREAD

**Issue by mariusvn** [CosmosOS/Cosmos#1471]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File System

#### Expected Behaviour - What do you think that should happen?
Read or write in every directories

#### Actual Behaviour - What unexpectedly happens?
 - Cannot write/create/read files in any folder but the root one
 - Cannot write/create directory in any folder but the root one

When I execute those functions, they are blocking the os. (like a non-stopping blocking call)

#### Reproduction - How did you get this error to appear?
```cs

namespace MyOS {
    public class FileSystem
    {
        CosmosVFS vfs;

        public FileSystem()
        {
            this.vfs = new CosmosVFS();
            VFSManager.RegisterVFS(this.vfs);
	    this.createTheBug();
        }

        public byte[] createTheBug()
        {
            this.vfs.CreateDirectory(@"0:\testdir"); // work
            this.vfs.CreateFile(@"0:\test.txt"); // work
            this.vfs.GetFile(@"0:\test.txt"); // work
            var list = this.vfs.GetDirectoryListing(@"0:\testdir"); // work
            this.vfs.CreateDirectory(@"0:\testdir\sub"); // don't work
            this.vfs.CreateFile(@"0:\testdir\test.txt"); // don't work
	}
    }		
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit: 0.1.0-localbuild20200903125546
(local build of the dev kit from master fetched the 5th September 2020, so I think it's the commit 8ebc75dab280924d61dc75ba37f7feeb4c96a31b)

**Comment by EliaSulimanov** [comment]
The work inside a directory is tricky, this should be easier.

- Can you please use a try-catch block, to see if any exceptions are thrown?
- Also, please try to do use the vfs manager for this operations.

If I remember correctly, vfs manager able to work inside a directory, but cosmos vfs not.
I would check this as soon as I can and would write an article about it.

Lastly, maybe it would be better if we make the cosmos vfs functions protected, and leave vfs manager for the end-user.

**Comment by mariusvn** [comment]
1. There is no exception as it's a blocking call?
2. I'll Check that asap

**Comment by EliaSulimanov** [comment]
Just checked it myself.
Can confirm that using the vfs manager works as expected.
```csharp
cosmosVFS = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(cosmosVFS);
Sys.FileSystem.VFS.VFSManager.CreateDirectory(@"0:\testdir\sub");
Sys.FileSystem.VFS.VFSManager.CreateFile(@"0:\testdir\test.txt");

var list = Sys.FileSystem.VFS.VFSManager.GetDirectoryListing(@"0:\testdir");
foreach (var directoryEntry in list)
{
    Console.WriteLine(directoryEntry.mName);
}
```

**Comment by quajak** [comment]
Thanks for checking @EliaSulimanov, I also tested it and cant reproduce it.
