### ISSUE TITLE
Creating a New Directory

### ISSUE THREAD

**Issue by Saincrad95** [CosmosOS/Cosmos#1474]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem, FAT32, Directory

#### Expected Behaviour - What do you think that should happen?
Create a directory

#### Actual Behaviour - What unexpectedly happens?
Throws a null exception

#### Reproduction - How did you get this error to appear?
Directory.CreateDirectory(path);
- If I edit this piece of code out. The error will go away

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit - Latest Update (9/6/2020 @ 11:00pm

CODE:
public void makeDirectoryCommand(string[] args) {
            string dirPath = args[1];
            Console.Write($"Do you want to make the directory: {dirPath} in {currentDirectory} (Y/N): ");
            string pathing = Console.ReadLine();
            switch (pathing.ToUpper()) {
                case "Y":
                    string localDirectory = currentDirectory + dirPath + "/";
                    Directory.CreateDirectory(localDirectory);
                    Console.WriteLine($"The directory {dirPath} was created at {currentDirectory} making {localDirectory}.");
                    currentDirectory = localDirectory;
                    break;
                default:
                    Console.WriteLine($"The directory {dirPath} will not be created.");
                    break;
        }
}

ERROR:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.Exception: Error compiling method 'SystemStringCosmosSystem_PlugsSystemIOPathImplGetDirectoryNameSystemString': System.InvalidOperationException: Nullable object must have a value.	ShellOS	~\Documents\Projects\VS2019\Cosmos\ShellOS\ShellOS\IL2CPU	1	

As shown in VS2019

-Saincrad95

**Comment by quajak** [comment]
Can you please post the build output logs?

**Comment by Saincrad95** [comment]
1>------ Build started: Project: ShellOS, Configuration: Debug Any CPU ------
1>ShellOS -> ~\Documents\Projects\VS2019\Cosmos\ShellOS\ShellOS\bin\Debug\netcoreapp2.0\cosmos\ShellOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: ~\Documents\Projects\VS2019\Cosmos\ShellOS\ShellOS\bin\Debug\netcoreapp2.0\cosmos\ShellOS.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Error compiling method 'SystemStringCosmosSystem_PlugsSystemIOPathImplGetDirectoryNameSystemString': System.InvalidOperationException: Nullable object must have a value.
1>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
1>   at System.Nullable`1.get_Value()
1>   at Cosmos.IL2CPU.AppAssembler.BeforeOp(_MethodInfo aMethod, ILOpCode aOpCode, Boolean emitInt3NotNop, Boolean& INT3Emitted, Boolean hasSourcePoint) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 1480
1>   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 511 ---> System.InvalidOperationException: Nullable object must have a value.
1>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
1>   at System.Nullable`1.get_Value()
1>   at Cosmos.IL2CPU.AppAssembler.BeforeOp(_MethodInfo aMethod, ILOpCode aOpCode, Boolean emitInt3NotNop, Boolean& INT3Emitted, Boolean hasSourcePoint) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 1480
1>   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 511
1>   --- End of inner exception stack trace ---
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 526
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 998
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 266
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\CosmosSource\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 206
1>IL2CPU task took 00:00:08.8663394
1>Done building project "ShellOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by quajak** [comment]
There is a current breaking bug in IL2CPU, so can you please checkout commmit cd0314778e0935427975cb10a70b08f8af96d496 for now and rebuild the devkit. Sorry about that.

**Comment by Saincrad95** [comment]
You're good thanks for the fast reply. Will do and let you know if it works

**Comment by Saincrad95** [comment]
Looks like that's all I needed here. Thanks for helping me out
