### ISSUE TITLE
ISO LINUX Error

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#1477]
The OS I made

it will boot into my OS

It has an error in ISOLINUX

Builded the OS (There is a error in the ISO BUilding

COSMOS USER KIT and VS COMMUNITY 2019

**Comment by quajak** [comment]
Can you please include a screenshot of the vm?

**Comment by kilickerem066** [comment]
Can you give us the **screenshot**?

**Comment by DolphinFlopFish** [comment]
ok, When making the ISO COSMOS throws me an error that says "The System cannot find the file specified
![Screenshot (42)](https://user-images.githubusercontent.com/52783833/92673804-5911c180-f35f-11ea-9c82-572b4c5295e0.png)
"

**Comment by DolphinFlopFish** [comment]
I did make the type "Other/Unknown"

**Comment by DolphinFlopFish** [comment]
I tried this on real hardware to see if this was just a VirtualBox Error, but this occurred on a Toshiba NB100

**Comment by quajak** [comment]
What is the name of the project?
Can you try typing [ProjectName].bin in the dialog.

**Comment by DolphinFlopFish** [comment]
atOS INST B1000.bin

**Comment by DolphinFlopFish** [comment]
that's were it fails, I typed that in and it came up with the same error

**Comment by quajak** [comment]
Can you try a project name without spaces?

**Comment by DolphinFlopFish** [comment]
ok

**Comment by DolphinFlopFish** [comment]
I couldn't rename it, I don't know how

**Comment by quajak** [comment]
Just create a new vs solution with the new name and copy all your files over.

**Comment by kilickerem066** [comment]
@DolphinFlopFish First of all, **VirtualBox** *doesn't* like *Cosmos*. Try it on **VMware Player**. Second is you can rename it by **making a new project with your new name** and *copy the code from your old project*.

**Comment by DolphinFlopFish** [comment]
there is a service missing from the VMware Player

**Comment by DolphinFlopFish** [comment]
I tried this on real hardware and it says "Waiting for debugger connection"

**Comment by quajak** [comment]
You have to disable debugging when running on real hardware.

**Comment by DolphinFlopFish** [comment]
Ok

**Comment by DolphinFlopFish** [comment]
THANKS SOOOOO MUCH!!!!
