### ISSUE TITLE
nasm.exe exited with code 1

### ISSUE THREAD

**Issue by kingofsponges** [CosmosOS/Cosmos#1478]
#### Area of Cosmos - What area of Cosmos are we dealing with?
exactly the compiler (c# to assembly)

#### Expected Behaviour - What do you think that should happen?
expected to compile the code, but after that i get an error like:
`MSB6006: nasm.exe exited with code 1`

#### Actual Behaviour - What unexpectedly happens?
it just gives me an error, i thought that the code would be compiled

#### Reproduction - How did you get this error to appear?
no idea ¯\\\_(ツ)_/¯

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user kit, latest i guess

**Comment by quajak** [comment]
Can you please post the entire output?

**Comment by kilickerem066** [comment]
Give us a **screenshot**

**Comment by kingofsponges** [comment]
yeah sure, i will try compiling the kernel again

**Comment by kilickerem066** [comment]
@kingofsponges Okay then

**Comment by bartekmuzyk** [comment]
@kingofsponges Any news?

**Comment by kingofsponges** [comment]
no, i will send the output in a day i guess, i dont have time now

**Comment by kingofsponges** [comment]
i had to reinstall windows due to a bug, but got my vs2019 projects back. possibly i can send the output this week i guess..
