### ISSUE TITLE
Loading CGS... failed!

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1479]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
My test CGS project should load normally.

#### Actual Behaviour - What unexpectedly happens?
I get a "Loading CGS... failed!" error when I try the ISO on VirtualBox and VMware.

#### Reproduction - How did you get this error to appear?
I just created a new project aside from my current one to test new CGS features.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708

**Comment by quajak** [comment]
What is your code?

**Comment by AnErrupTion** [comment]
`
using Cosmos.System.Graphics;
using System;
using System.Drawing;
using Sys = Cosmos.System;

namespace CGS_Tests
{
    public class Kernel : Sys.Kernel
    {
        private Canvas canvas;
        private TextRenderer text = new TextRenderer();

        protected override void BeforeRun()
        {
            Console.WriteLine("These are CGS Tests for Sartox OS.");
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(320, 200, ColorDepth.ColorDepth8));
            canvas.Clear(Color.Black);
        }

        protected override void Run()
        {
            Sys.Graphics.Point testPoint = new Sys.Graphics.Point(10, 10);
            text.StringTextHandler(canvas, "this is a test", testPoint);
        }
    }
}

`

**Comment by quajak** [comment]
Try a different (higher) resolution which is supported by SVGAII.

**Comment by AnErrupTion** [comment]
Still doesn't work with 800x600x32.

**Comment by quajak** [comment]
Try without specifying a screen mode

**Comment by AnErrupTion** [comment]
Still doesn't work.

**Comment by quajak** [comment]
The error seems supprising for me since I cant find any reference to `Loading CGS... failed` in the Cosmos source code. Can you confirm that `canvas = FullScreenCanvas.GetFullScreenCanvas();` does not work in Vmware.

**Comment by AnErrupTion** [comment]
I actually verified it and it really doesn't work in VMware either.

**Comment by samnad** [comment]
It works on VMWare for me. I'm using that exact method, I am specifying a mode though.

**Comment by AnErrupTion** [comment]
Maybe a part of the upgrade from Cosmos 2019 to 2020 failed?

**Comment by quajak** [comment]
Can you try in a new project? How did you upgrade from 2019 to 2020?

**Comment by AnErrupTion** [comment]
From what I remember, I either uninstalled 2019 and installed 2020 or just installed 2020, but I think it's the first. And yes I'll try tomorrow.

**Comment by AnErrupTion** [comment]
Oh, I found the problem. I had spaces in the name of my solution and project. Removing them fixed the problem.
