### ISSUE TITLE
ProcessorInformation.GetVendorName() returns blank

### ISSUE THREAD

**Issue by samnad** [CosmosOS/Cosmos#1482]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Core (ProcessorInformation)

#### Expected Behaviour - What do you think that should happen?

Returns CPU Vendor ID

#### Actual Behaviour - What unexpectedly happens?

Returns Blank

#### Reproduction - How did you get this error to appear?

Use Vmware and print this:
`Cosmos.Core.ProcessorInformation.GetVendorName()`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 20200708

**Comment by quajak** [comment]
There is a fix for GetVendorName in the devkit or the problem is that the CPU does not support CPUId.

**Comment by samnad** [comment]
I just used the CPU get vendor name method instead of the processorinformation and it worked, but is there a way to get the specific model, like Ryzen 5 3600?

**Comment by quajak** [comment]
Thats a bug that ProcessorInformation and CPU are returning different values.
There is no way currently to get the name of a specific model.

**Comment by samnad** [comment]
Ok Thanks!
