### ISSUE TITLE
File.CanRead hangs/crashes system

### ISSUE THREAD

**Issue by samnad** [CosmosOS/Cosmos#1483]
#### Area of Cosmos - What area of Cosmos are we dealing with?

VFS

#### Expected Behaviour - What do you think that should happen?

Returns boolean depending on whether the file can be read from (and I expect this should also work as a "file exists")

#### Actual Behaviour - What unexpectedly happens?

VMWare VM crashes/hangs

#### Reproduction - How did you get this error to appear?

Access FS variable from another class. Call CanRead on any fie.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest Userkit

**Comment by quajak** [comment]
Do you mean FileStream.CanRead, do you have a small kernel which reproduces this problem?

**Comment by samnad** [comment]
Yes, FileStream.CanRead, sorry. I made a new project and put the problematic code in, and it said this:
` *** CPU Exception x06 *** Last known address: 0x020A9865`
and then my Visual Studio crashed. I didn't see this before because I was in Canvas mode.

**Comment by quajak** [comment]
Can you please post the code for the new kernel here, so I can easily reproduce it?

**Comment by samnad** [comment]
Sure:
https://hastebin.com/ofiworixem.cpp

**Comment by quajak** [comment]
I cannot reproduce the crash.

**Comment by samnad** [comment]
I can't anymore as well. Sorry.
