### ISSUE TITLE
SYSLINUX

### ISSUE THREAD

**Issue by Backup-eric645** [CosmosOS/Cosmos#1485]
#### Area of Cosmos - What area of Cosmos are we dealing with?

SYSLINUX

#### Expected Behavior - What do you think that should happen?

Syslinux successfully booting

#### Actual Behavior - What unexpectedly happens?

```
ISOLINUX 6.03 2014-10-06 ETCD Copyright 1994-2014 H. Peter Anvin et al
Loading ShutDownSys.bin... failed!
No files found!
boot:
```

#### Reproduction - How did you get this error to appear?

I created some little test code to shutdown the machine whenever it's booted into the ISO.
I tested it in VMware 15 and oops... The message appeared.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 20200708

**Comment by samnad** [comment]
Can you go into the folder where your solution in Visual Studio is, go to \bin\Debug\netcoreapp2.0\cosmos\ISO, and list the files?

**Comment by Backup-eric645** [comment]
In Syslinux.cfg it's ShutDownSys and in the ISO folder it is also present as ShutDownSys. In the ISO file this file is also present and the Syslinux.cfg I extracted from there had the same exact contents as the one in the ISO folder. (I checked with Notepad and HxD.)

**Comment by charlesbetros** [comment]
How large is the kernel?
How much ram does the vm have?

This error usually occurs when the vm doesn't have enough ram to load the kernel in to memory.

**Comment by Backup-eric645** [comment]
It's a very small kernel, but I tries this on my MS-DOS virtual machine which has 16MB.

**Comment by Backup-eric645** [comment]
I then tried in VBox with 64MB and it worked.

**Comment by Backup-eric645** [comment]
Explorer says this ISO is 17,826 KB (18 MB).
