### ISSUE TITLE
userkit install unexpectedly reports an error message with no clear issue

### ISSUE THREAD

**Issue by Dominus-Nova** [CosmosOS/Cosmos#1486]
#### Area of Cosmos - What area of Cosmos are we dealing with?
userkit install program

#### Expected Behaviour - What do you think that should happen?
it should build successfully
[New Text Document.txt](https://github.com/CosmosOS/Cosmos/files/5268440/New.Text.Document.txt)

 

#### Actual Behaviour - What unexpectedly happens?
 error report and crash after trying to build

#### Reproduction - How did you get this error to appear?
I don't know how  or why its happening

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
userkit version Il2CPU

**Comment by fdagrewwwfdgsdfs** [comment]
Can you try to run as administrator?
