### ISSUE TITLE
Error MSB6006: "nasm.exe" exited with code 1.

### ISSUE THREAD

**Issue by MishaTY** [CosmosOS/Cosmos#1488]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Drawing image

#### Expected Behaviour - What do you think that should happen?
The OS Should compile and run. Then draw the image.

#### Actual Behaviour - What unexpectedly happens?
A error shows up: error MSB6006: "nasm.exe" exited with code 1

#### Reproduction - How did you get this error to appear?
I built the project.

Build Log: https://pastebin.com/WaV4tZ22
Source code: [DEMO.zip](https://github.com/CosmosOS/Cosmos/files/5284617/DEMO.zip)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev kit (latest)
Cloned on 9/25/2020

**Comment by quajak** [comment]
The data you are trying to include is too large. If you are using a ManifestResourceStream, you can compress more data using a Base64 string, otherwise you can also include the file in the vmdk to load larger images.

**Comment by MishaTY** [comment]
Thanks, I used a much smaller image and it worked!
