### ISSUE TITLE
install-VS2019.bat DevKit installer hangs.

### ISSUE THREAD

**Issue by samnad** [CosmosOS/Cosmos#1490]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Devkit installer.

#### Expected Behaviour - What do you think that should happen?

Builds and installs my current Cosmos fork.

#### Actual Behaviour - What unexpectedly happens?

Says IL2CPU, XSharp, and Common are not installed, prompts to install, hangs after approving. Nothing running in Task Manager, etc.

#### Reproduction - How did you get this error to appear?

Fork Cosmos, clone to local drive, run bat file.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Devkit latest with my new GetCPUBrandString() method added.

**Comment by quajak** [comment]
Can you clone IL2CPU, XSharp and Common manually?

**Comment by samnad** [comment]
You mean like download the zips and put them where?

**Comment by quajak** [comment]
Yeah or use the git command line. They should have the same base directory as the Cosmos directory.

**Comment by samnad** [comment]
Same thing happened

**Comment by quajak** [comment]
Can you post the log?

**Comment by samnad** [comment]
https://pastebin.com/jH6KNcNm

**Comment by quajak** [comment]
Can you post the tree structure of the directory containing the Cosmos directory?

**Comment by samnad** [comment]
- My OS
- Cosmos
- IL2CPU
- XSharp

**Comment by quajak** [comment]
No renaming the folders was correct, you also need to download Cosmos Common

**Comment by samnad** [comment]
Oh. It worked, thanks.
