### ISSUE TITLE
IL2CPU error

### ISSUE THREAD

**Issue by MishaTY** [CosmosOS/Cosmos#1492]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2cpu

#### Expected Behaviour - What do you think that should happen?
OS Should build and run

#### Actual Behaviour - What unexpectedly happens?
IL2CPU Throws exception 

#### Reproduction - How did you get this error to appear?
Use Path.GetDirrectoryName or something else

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Clone (Dev kit)

build log: https://pastebin.com/rGmF4Ck7
source code: https://github.com/MishaTY/Misha-OS

**Comment by quajak** [comment]
The error in IL2CPU should now be fixed, try again with the newest IL2CPU commmit

**Comment by MishaTY** [comment]
Ok, I will try it right now. Thanks

**Comment by MishaTY** [comment]
Thanks, it works now!
