### ISSUE TITLE
Virtual Filesystem

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1494]
I am trying to see if there is a way for the Cosmos filesystem to be real (not virtual). I have noticed that the filesystem in a given Cosmos OS is a virtual filesystem and doesn't actually save files to the hard disk when running on real hardware (as far as I know). Is it possible to do so? I was imagining being able to do file IO in an OS on real hardware and then opening and reading the files on the hard drive from Windows. My efforts thus far have been fruitless. Is this possible? If so, how?

**Comment by TFTWPhoenix** [comment]
What do you mean real as opposed to virtual? The filesystem is persistent across reboots. VMs act just like real machines to my knowledge. There should not be a FS difference as far as I know.
Reading from a Windows filesystem is impossible on Cosmos thus far. Windows uses NTFS which Cosmos can't read at the moment. Cosmos reads FAT32.

**Comment by sudopigeek** [comment]
I wanted to make files in Cosmos on real hardware and then remove its hard drive and plug it into a Windows system so it could read the files Cosmos made.

**Comment by quajak** [comment]
So you want the ability to unmount the filesystem on a disk?

**Comment by TFTWPhoenix** [comment]
Oh you want to make Cosmos files readable in Windows. That should be currently possible given that Cosmos uses FAT32 which Windows 10 can read and write to, however I am not positive. I haven't tried this particular thing before.

**Comment by sudopigeek** [comment]
I think there is a way you can mount a VMWare virtual disk file as a drive, but I haven't yet looked for it. I will also experiment with the Cosmos filesystem and see what I can do.

**Comment by elkaamee326** [comment]
You can go on VMware Workstation 15.0 player with Cosmos selected and go -> Edit virtual machine settings. Than you go -> Hardisk IDE than go on map virtual disk. Tick off read only mode on the dialog and press enter. Than you can add your Cosmos OS images and other assets to the virtual disk. As long as you have successfully built a cosmos project with the VMware tab selected on in Cosmos project properties.
