### ISSUE TITLE
How to create a GUI

### ISSUE THREAD

**Issue by WeRandom** [CosmosOS/Cosmos#1497]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI

#### Expected Behaviour - What do you think that should happen?
I should be able to make windows and such.

#### Actual Behaviour - What unexpectedly happens?
I cant.

#### Reproduction - How did you get this error to appear?
Not an error

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev kit
How do I make gui

**Comment by TFTWPhoenix** [comment]
Making GUI's is a very complicated subject. You would first need to enter a GUI mode, then you need to make a Window Manager. And all that would be useless without a way to launch apps (file browser, taskbar, dock, start menu, start screen, etc.). Even something as simple as text would require you to make your own font! I don't have any examples other than [MishaOS](https://github.com/MishaTY/Misha-OS), which may not even be a great example of what you'd want to do. (All apps here must be hardcoded, you can't make executables show up.) Another example is [the Cosmos GUI Framework](https://github.com/Myvar/CosmosGuiFramework) but please be aware that this is a 2016 project and almost certainly no longer works!

**Comment by WeRandom** [comment]
So you are saying there is no way to make gui

**Comment by WeRandom** [comment]
Are you guys planning on putting the gui thing back

**Comment by WeRandom** [comment]
and do you think i should just use the 2016 version of cosmos since it looks like it is more customizable and there is more I can do?

**Comment by WeRandom** [comment]
and is there a way to make the console bigger

**Comment by TFTWPhoenix** [comment]
Ok so GUI's are DEFINITELY still possible. Easier than ever with bitmap support. It's still a very advanced subject. And you can even set screen height with this (careful though bitmaps can only go up to a megabyte from my research but I'm not positive). 1920x1080 might be hard to accomplish but I have no doubts that its possible. And even on the cosmos wiki you can find a cursor tutorial.

**Comment by quajak** [comment]
Look at https://cosmosos.github.io/api/Cosmos.System.Graphics.Canvas.html for what methods are currently available for creating a gui. As @TFTWPhoenix said creating a working GUI is quite a lot of work.

> and is there a way to make the console bigger

You can set it in https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Graphics/VGATextMode.cs#L38

**Comment by WeRandom** [comment]
Ok thanks imma keep this open for 48 hours so I have time to try it out

**Comment by WeRandom** [comment]
just so you know the second code made no sense and I was so confused

**Comment by WeRandom** [comment]
speaking of gui how do you make a mouse that is super easy and can work with buttons

**Comment by samnad** [comment]
It isn't that simple. There are no "buttons". What you need is to make a mouse, then you get its x and y points and if they are in an area, do something.

**Comment by WeRandom** [comment]
oh ok

**Comment by samnad** [comment]
Sorry, should have mentioned that you also need to check if the mouse was clicked. 
Here's the code for that:
`MouseManager.MouseState == MouseState.Left`

**Comment by WeRandom** [comment]
Also, with vga screen it doesnt work when setting color depth and that kind of stuff [Here is the tutorial](https://www.codeproject.com/Articles/842576/Cosmos-Large-Cursor-GUI-tutorial) is there any way that this is an older version and the methods are diferent

**Comment by WeRandom** [comment]
Also How do i know the cordnates of things?

**Comment by WeRandom** [comment]
and why do i have the label pro?

**Comment by samnad** [comment]
Yes, that is an older version and the code is outdated. See my comment in your other issue, it explains it and there is a link to my more modern implementation of that same method.

**Comment by WeRandom** [comment]
ok

**Comment by WeRandom** [comment]
Your code was also confusing because there was folders with gui and stuff. I tried out the project and it worked but there was so much I was just confused

**Comment by WeRandom** [comment]
#1499 just so others coming in can see the other issue

**Comment by nifanfa** [comment]
https://github.com/nifanfa/Cosmos-GUI-Sample

**Comment by nifanfa** [comment]
See my project

**Comment by nifanfa** [comment]
> Making GUI's is a very complicated subject. You would first need to enter a GUI mode, then you need to make a Window Manager. And all that would be useless without a way to launch apps (file browser, taskbar, dock, start menu, start screen, etc.). Even something as simple as text would require you to make your own font! I don't have any examples other than [MishaOS](https://github.com/MishaTY/Misha-OS), which may not even be a great example of what you'd want to do. (All apps here must be hardcoded, you can't make executables show up.) Another example is [the Cosmos GUI Framework](https://github.com/Myvar/CosmosGuiFramework) but please be aware that this is a 2016 project and almost certainly no longer works!

actually it's very easy. i think the hardest is play sound....

**Comment by nifanfa** [comment]
if i know how to drive a sound card then i can make a really operating system

**Comment by nifanfa** [comment]
![image](https://github.com/nifanfa/Cosmos-GUI-Sample/blob/master/4.gif)

**Comment by WeRandom** [comment]
Thank you... I'll check it out

**Comment by WeRandom** [comment]
I made a new thread on how to add sound -- I doubt I wrote the question right but it can always be changed. #1501

**Comment by nifanfa** [comment]
I can only use console.beep to play sound now.  This reminds me of FC

**Comment by WeRandom** [comment]
how did you add the bit maps... I've been trying for a long time and it keeps saying null reference error

**Comment by WeRandom** [comment]
also is that clock a clock that's actually on time?

**Comment by WeRandom** [comment]
@nifanfa i did some research and if you want to play a specific sound from a sound file you use this...
Namespace you need -- using System.Media;
Code -- SoundPlayer player = new SoundPlayer (@"###.mp3");
player.Play();

**Comment by WeRandom** [comment]
i hope that helped

**Comment by nifanfa** [comment]
> @nifanfa i did some research and if you want to play a specific sound from a sound file you use this...
> Namespace you need -- using System.Media;
> Code -- SoundPlayer player = new SoundPlayer (@"###.mp3");
> player.Play();

I bet it won't work

**Comment by WeRandom** [comment]
who knows?

**Comment by WeRandom** [comment]
I'll try it and tell you if it does

**Comment by nifanfa** [comment]
You don't even let the operating system know that there's a sound card. And i bet it will makes il2cpu fails to compile. System.media seems not work in cosmos

**Comment by WeRandom** [comment]
yeah it doesnt

**Comment by WeRandom** [comment]
The sound player command needs system.media but cosmos doesn't like that meaning... Hey cosmos people... can you allow us to play sound files.

**Comment by WeRandom** [comment]
There is something called NAudio. I dont know how to use it but I think that it could work... It can record and play audio.

**Comment by Project-Magenta** [comment]
No, it doesn't work. Cosmos has no speaker support outside of playing tones with the PC speaker and `Console.Beep()`.

**Comment by nifanfa** [comment]
![A1789E2EEFC2E939B8425DBBEC40E0BB.gif](https://user-images.githubusercontent.com/54205437/95008977-d07dfc80-0650-11eb-9507-929f2a7956ec.gif) My previous project

**Comment by nifanfa** [comment]
Gui is really easy but play sound....

**Comment by nifanfa** [comment]
And networking...

**Comment by nifanfa** [comment]
#1464 #1458

**Comment by WeRandom** [comment]
You are really good at GUI

**Comment by nifanfa** [comment]
Thx

**Comment by WeRandom** [comment]
in your project on launch it says something about a filesystem failing or something and wont open the gui. How do you fix it?

**Comment by WeRandom** [comment]
It also says stack corruption occured after a while.

**Comment by nifanfa** [comment]
Have you put the files into filesystem.vmdk?

**Comment by WeRandom** [comment]
no how do I do that

**Comment by nifanfa** [comment]
![ezscreenshot-2020-10-05_21-58-52-600.png](https://user-images.githubusercontent.com/54205437/95088871-11136e00-0756-11eb-88ba-cbaeeab7b824.png)

**Comment by WeRandom** [comment]
Im confused... how do I add the files to the filesystem.mdk

**Comment by WeRandom** [comment]
also @nifanfa you could probably make a really great youtube channel that does cosmos os tutorials.

**Comment by nifanfa** [comment]
You should install VMware workstation and  find filesystem.vmdk in explorer Then press mouse right to mount the vmdk and put the files.

**Comment by WeRandom** [comment]
oh ok

**Comment by WeRandom** [comment]
when i try and mount it it doesn't do anythinh

**Comment by WeRandom** [comment]
do i need pro vmware to do it

**Comment by WeRandom** [comment]
How do you mount I still dont understand... I made a shared folder but it still says cpu exception

**Comment by elkaamee326** [comment]
You can go on VMware Workstation 15.0 player with Cosmos selected and go -> Edit virtual machine settings. Than you go -> Hardisk IDE than go on map virtual disk. Tick off read only mode on the dialog and press enter. Than you can add your Cosmos OS images and other assets to the virtual disk. As long as you have successfully built a cosmos project with the VMware tab selected on in Cosmos project properties.

**Comment by WeRandom** [comment]
do i need pro to do it?

**Comment by WeRandom** [comment]
and does that mean i have to download an older version of vmware

**Comment by sudopigeek** [comment]
I've built the VMDK containing the bitmaps for the Cosmos-GUI-Sample OS [here](https://drive.google.com/file/d/1g7mJoA2UMIP6P4fRmqFD_ClWk9iaGj4J/view?usp=sharing).

**Comment by WeRandom** [comment]
Thank you so much

**Comment by WeRandom** [comment]
it says CPU exception but then it says after that Exception occurred, invalid data size

**Comment by sudopigeek** [comment]
I remade the VMDK [here](https://drive.google.com/file/d/1RE1xEGWsGQ9W48NRwSazg9AHpRoi7r_r/view?usp=sharing); it no longer has CPU Exception.

**Comment by WeRandom** [comment]
can you explain what that is for future refrence

**Comment by WeRandom** [comment]
It works!!!

**Comment by sudopigeek** [comment]
CPU Exception can be thrown by many things, but it usually has to do with the filesystem. In this case, it was probably thrown because the OS couldn't find the required bitmaps when it initialized.

**Comment by WeRandom** [comment]
ok thanks

**Comment by WeRandom** [comment]
when launching it the gui is a bit messed up... Everything is yellow and the loading screen takes up half of the screen

**Comment by WeRandom** [comment]
also @nifanfa is the clock acurate?

**Comment by nifanfa** [comment]
Not really

**Comment by WeRandom** [comment]
ok

**Comment by WeRandom** [comment]
just checking

**Comment by sudopigeek** [comment]
As far as a GUI goes, [here](https://github.com/sudopigeek/CGUI) is a library I am developing that you might find useful.

**Comment by octaviousrex** [comment]
> As far as a GUI goes, [here](https://github.com/sudopigeek/CGUI) is a library I am developing that you might find useful.

Very useful. I will check it out. may your day be filled with puppies and gummy bears.

**Comment by octaviousrex** [comment]
> can you explain what that is for future reference

VMDK is a file format that describes containers for virtual hard disk drives to be used in virtual machines like VMware Workstation or VirtualBox.
