### ISSUE TITLE
Cpu Exception x05/Keyboard Interrupt stops responding/VMWare crashes when allocating memory

### ISSUE THREAD

**Issue by AXFsoftware** [CosmosOS/Cosmos#1498]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Boot C# framework

#### Expected Behaviour - What do you think that should happen?
Attempting to allocate a set number of bytes as memory. The bytes are stored in pages, which is a separate class called memoryPages. The data is stored in a base array of Bytes under hbAllocatedMemory. The memory is then "Zero-Paged", as in, all of the bytes are initialized to 0x00. The data should be stored as 0x00 bytes. The system was set to initially have 1 page of 4MB of bytesm but this failed, so the system was then changed to have 64kb pages, with 256 of them, or 16mb of data. This also does not work and causes unexpected behaviour.

#### Actual Behaviour - What unexpectedly happens?
several tests have been done each with different results:

1 page, with 0xFFFF bytes (~64kb): Works.

0xF Pages (15 pages) of 0xFFFF Bytes: Keyboard interrupt no longer responds, but VMWare is still active.

0xFF Pages (256 pages) of 0xFFFF Bytes: Either produces Cpu Exception x05 OR crashes VMWare (VMWare will exit with code 0 after initializing the debugger).

0xFFFF Pages (65536 pages): Crashes Visual Studio.

1 page, 0xFFFFFFFF Bytes: Either Keyboard interrupt no longer responds OR crashes VMWare (VMWare will exit with code 0 after initializing the debugger)

Attempting to print the result, as in Console.WriteLine(someMemoryPages[0].hbAllocatedMemory.Length  + " Bytes Free");, VMWare Crashes (VMWare will exit with code 0 after initializing the debugger).

NOTE: this is not an issue with my development machine having low ram. My machine has 16GB of DDR4 3200 Ram.
NOTE: Step Through (F11) produces the same results as above, except that in most cases it does not actually let me step through and just stop debugging after VMWare closes itself.

#### Reproduction - How did you get this error to appear?
See Above. I'm thinking there is some error in the allocation of the bytes that causes some issues.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos UserKit C#

**Comment by quajak** [comment]
Yeah this seems like some problem with how allocations are done in Cosmos. To be clear you are simply creating various byte arrays to cause this problems?

**Comment by AXFsoftware** [comment]
Yes. This was done using standard byte arrays, like "public static someByteArray[]", initializing the array within a class constructor and then using a separate function to fill the array with zeros.

**Comment by CodeEasyYT** [comment]
I have the same issue, but how to fix it?

**Comment by quajak** [comment]
There has been work to improve the memory management, which will hopefully fix this

**Comment by MishaTY** [comment]
Can this be reproduced?
