### ISSUE TITLE
Mouse and image help

### ISSUE THREAD

**Issue by WeRandom** [CosmosOS/Cosmos#1499]
How do i make a mouse in cosmos. Also how do I add my own pictures to cosmos.

**Comment by sudopigeek** [comment]
CodeProject has a good how-to for creating a mouse [here](https://www.codeproject.com/Articles/842576/Cosmos-Large-Cursor-GUI-tutorial). As for images, the Cosmos.Drawing.Graphics.Canvas class has a method called DrawImage() that you can use. For example, if you wanted to render a bitmap at x=1 and y=3, you would do something like this:
`
Canvas canvas = FullScreenCanvas.GetFullScreenCanvas();
`
`
canvas.DrawImage(new Bitmap("file.bmp"), 1, 3);
`

**Comment by WeRandom** [comment]
Thank you so much ive been looking for a long time... Is it ok if I keep this open in case I need more help?

**Comment by sudopigeek** [comment]
That should be fine

**Comment by WeRandom** [comment]
what is the maximum file size it can handle

**Comment by WeRandom** [comment]
it keeps saying null refrence error

**Comment by sudopigeek** [comment]
I am not sure how big the file can be, but it depends on the image quality/resolution. How did you add your image file into the project?

**Comment by WeRandom** [comment]
I made it on visual studio

**Comment by sudopigeek** [comment]
Since I have not experimented with images yet, I would try changing the "Build Action" attribute in the Properties window of your image file to Embedded Resource or other values and see what you can come up with.

**Comment by WeRandom** [comment]
Ok

**Comment by WeRandom** [comment]
It didnt work it still says nullerrorexception

**Comment by WeRandom** [comment]
The link for the mouse was super confusing and I kept on getting errors is there any other one that is easier to understand

**Comment by WeRandom** [comment]
So i found a way to make a super simple mouse and I just want to know why it is flickering the code is bellow.
`using Cosmos.HAL;
using Cosmos.System;
using Cosmos.System.Graphics;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Threading;
using Sys = Cosmos.System;

namespace Mousetest
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        protected override void BeforeRun()
        {
            canvas = FullScreenCanvas.GetFullScreenCanvas();
            //canvas.DrawImage(new Bitmap("im.bmp"), 1, 3);
            canvas.Clear(Color.Cyan);
            Sys.MouseManager.ScreenWidth = (uint)canvas.Mode.Columns;
            Sys.MouseManager.ScreenHeight = (uint)canvas.Mode.Rows;
            Sys.MouseManager.X = 1;
            Sys.MouseManager.Y = 1;
        }

        protected override void Run()
        {
            
            Pen pen = new Pen(Color.Black);
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)(Sys.MouseManager.X + 8), (int)Sys.MouseManager.Y);
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)Sys.MouseManager.X, (int)(Sys.MouseManager.Y + 8));
            canvas.DrawLine(pen, (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y, (int)(Sys.MouseManager.X + 8), (int)(Sys.MouseManager.Y + 8));
            //canvas.DrawImage(new Bitmap("im.bmp"), 1, 3);
            canvas.Clear(Color.Cyan);
        }


    }
}`

**Comment by samnad** [comment]
It's flickering because of the canvas itself. Easiest way to get around this is to make an array of pixels instead of directly setting the canvas pixels and then loop through all pixels in the array, only writing to the canvas if the pixel changed. This will get rid of the flicker and make the GUI much faster in the long run.

**Comment by WeRandom** [comment]
how do i do that? Sorry im only 13 and don't understand much

**Comment by samnad** [comment]
[This](https://www.codeproject.com/Articles/842576/Cosmos-Large-Cursor-GUI-tutorial) tutorial explains almost all of what I said, but it's a bit out of date. In summary, make an array of colors that is very large (think 500000 items) and then instead of setting the canvas pixel directly (with canvas.setPixel()), set the pixel in the array. Then, when you're done adding everything, make a method that loops through all pixels in the screen (loop though x and y) and gets the value from the screen pixel and the current pixel in the array, then if they are different, use the canvas.setPixel() method to change the pixel on screen.
 
Have a look at my CanvasDisplayDriver, it uses this same method: https://github.com/samnad/CobaltOS/blob/master/CosmosKernel1/GUI/CanvasDisplayDriver.cs

**Comment by WeRandom** [comment]
thats fully functional

**Comment by WeRandom** [comment]
and super confusing

**Comment by samnad** [comment]
Sorry that it's confusing, but it's the simplest way to get it to stop flickering that I know of. If you just copy the code, you won't understand it, so just try to go through it step by step. Then, after you understand what methods do what, copy it and play around with it in your OS.

**Comment by WeRandom** [comment]
what part of it do i copy

**Comment by WeRandom** [comment]
i tried doing it and all these errors showed up

**Comment by WeRandom** [comment]
and i realized that it needed all of these folders

**Comment by samnad** [comment]
So don't copy the whole code, only the setpixel, drawscreen, init methods and the variables.

**Comment by WeRandom** [comment]
is that in kernel? or is it in one of the gui's?

**Comment by WeRandom** [comment]
can you guys make tutorials for how to do this stuff in cosmos os. All of the other ones are for 2016

**Comment by samnad** [comment]
It's in the page I linked. I'll work on a tutorial, but no guarantees to when It'll be done.

**Comment by WeRandom** [comment]
ok. So the only code i need is the one in the page you linked

**Comment by samnad** [comment]
I made the tutorial. https://github.com/CosmosOS/Cosmos/wiki/Non-Flickering-Canvas-GUI-Tutorial

**Comment by WeRandom** [comment]
That was quick thanks ill look into it!!!

**Comment by WeRandom** [comment]
so i just tried it out and it says that kernel is not implemented it also says that screen x doesn't exist it also says that canvas does not exist. I know Im probably doing something wrong. Can you tell me what i am doing wrong?

**Comment by samnad** [comment]
Let me do some research. I'll get back to you soon.

**Comment by WeRandom** [comment]
ok

**Comment by WeRandom** [comment]
Do you want the code I did

**Comment by samnad** [comment]
Sure, that would help.

**Comment by WeRandom** [comment]
`using Cosmos.System.Graphics;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using Sys = Cosmos.System;

namespace RandomOSS
{
    public class Kernel : Sys.Kernel
    {
        int screenX = 800;
        int screenY = 640;

        

        private static Color[] pixelBuffer = new Color[(screenX * screenY) + screenX];
        private static Color[] pixelBufferOld = new Color[(screenX * screenY) + screenX];

        public static void init()
        {
            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Mode = new Mode(screenX, screenY, ColorDepth.ColorDepth32);
            Cosmos.System.MouseManager.ScreenWidth = Convert.ToUInt32(screenX);
            Cosmos.System.MouseManager.ScreenHeight = Convert.ToUInt32(screenY);
        }
        public static void drawScreen()
        {
            Pen pen = new Pen(Color.Orange);
            for (int y = 0, h = screenY; y < h; y++)
            {
                for (int x = 0, w = screenX; x < w; x++)
                {
                    if (!(pixelBuffer[(y * screenW) + x] == pixelBufferOld[(y * screenW) + x])) canvas.DrawPoint(pen, x, y);
                }
            }
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = pixelBufferOld[i];
            }
        }
        public static void clearScreen(Color c)
        {
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = c;
            }
        }
        public static void setPixel(int x, int y, Color c)
        {
            if (x > screenX || y > screenY) return;
            pixelBuffer[(x * y) + x] = c;
        }
        public static void update()
        {
            clearScreen(Color.Blue);
            setPixel(1, 1, Color.Black);
            setPixel(1, 2, Color.Black);
            setPixel(2, 1, Color.Black);
            setPixel(2, 2, Color.Black);
            drawScreen();
        }
    }
}
`

**Comment by WeRandom** [comment]
let me know what i did wrong

**Comment by samnad** [comment]
Ok, I will. I do have other things to do though.

**Comment by WeRandom** [comment]
ok

**Comment by octaviousrex** [comment]
> How do i make a mouse in cosmos. Also how do I add my own pictures to cosmos.

Keep in mind, the images have to be bmp's so heads up before you add any
