### ISSUE TITLE
Cosmos.Build package not found after devkit installation

### ISSUE THREAD

**Issue by ChristofBecu** [CosmosOS/Cosmos#1500]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installation of devkit

#### Expected Behaviour - What do you think that should happen?
Succesfull installation of clean devkit solution

#### Actual Behaviour - What unexpectedly happens?
Devkit installation succeeded succesfully, but following 2 errors are shown in VS, therefore building is not possible

```python
NU1103	Unable to find a stable package Cosmos.Build with version (>= 0.0.0)
  - Found 1 version(s) in Cosmos Local Package Feed [ Nearest version: 0.1.0-localbuild20201002024427 ]
  - Found 0 version(s) in nuget.org
  - Found 0 version(s) in https://ci.appveyor.com/nuget/cosmos-common
  - Found 0 version(s) in https://ci.appveyor.com/nuget/il2cpu
  - Found 0 version(s) in https://ci.appveyor.com/nuget/xsharp
  - Found 0 version(s) in https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json
  - Found 0 version(s) in https://www.myget.org/F/cosmos/api/v3/index.json	TRKernel	C:\_cosmos_devkit\Cosmos\source\Kernel-TapRoot\Demo\TRKernel.csproj	1	
```

```python
NU1103	Unable to find a stable package Cosmos.Build with version (>= 0.0.0)
  - Found 1 version(s) in Cosmos Local Package Feed [ Nearest version: 0.1.0-localbuild20201002024427 ]
  - Found 0 version(s) in nuget.org
  - Found 0 version(s) in https://ci.appveyor.com/nuget/cosmos-common
  - Found 0 version(s) in https://ci.appveyor.com/nuget/il2cpu
  - Found 0 version(s) in https://ci.appveyor.com/nuget/xsharp
  - Found 0 version(s) in https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json
  - Found 0 version(s) in https://www.myget.org/F/cosmos/api/v3/index.json	GuessKernelGen3	C:\_cosmos_devkit\Cosmos\source\Kernel-X86\50-Application\GuessKernelGen3.csproj	1	
```

#### Reproduction - How did you get this error to appear?
run install-VS2019.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit #1489

**Comment by ChristofBecu** [comment]
Nevermind, I think I get it : the devkit isn't supposed to be run.
Everytime changes are made to the devkit, install-VS2019.bat has to be executed so the userkit is updated, right?

**Comment by quajak** [comment]
I dont fully understand your second comment, but the devkit should be able to build the project. Regarding the errors when trying to build, select allow prereleases in the nuget package manager so that the instable versions can be used.

**Comment by ChristofBecu** [comment]
Thanks, allowing prereleases removed the errors indeed.

What I mean with the second comment is that I'm still figuring out exactly how to use the devkit in combination with the userkit.
Imagine following scenario:
- I am working on a project in the userkit
- I change something in one of the projects of the devkit, e.g. in Cosmos.Hal2
- To have these changes in the devkit implemented in my project in the userkit, I have to run install-VS2019.bat over again

**Comment by quajak** [comment]
You can only have either the devkit or the userkit installed at the same time. Running `install-VS2019.bat` will overwrite the current installation with that of the devkit. I dont really see a reason to keep some part of the project with the userkit.

**Comment by ChristofBecu** [comment]
Okay, I get it now. Thank you
