### ISSUE TITLE
Events do not work

### ISSUE THREAD

**Issue by MishaTY** [CosmosOS/Cosmos#1502]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Events

#### Expected Behaviour - What do you think that should happen?
OS should compile and run.

#### Actual Behaviour - What unexpectedly happens?
Plug error: https://pastebin.com/irVcjyaF
source code: https://pastebin.com/6Sng8Uwm
#### Reproduction - How did you get this error to appear?
By using an event

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
dev kit

**Comment by charlesbetros** [comment]
Use a delegate instead.

**Comment by MishaTY** [comment]
Thanks, I changed my code and it works now.
