### ISSUE TITLE
Error mapping Filesystem.vmdk

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1506]
#### Area of Cosmos - What area of Cosmos are we dealing with?
FileSystem

#### Expected Behaviour - What do you think that should happen?
The vmdk should map as a drive on my host machine.

#### Actual Behaviour - What unexpectedly happens?
![fserr](https://user-images.githubusercontent.com/61560519/95281388-a5e09f00-081c-11eb-9e86-fadc202a93a9.png)

#### Reproduction - How did you get this error to appear?
Right clicking on the .vmdk and clicking "Map virtual disk..."

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest user kit.

**Comment by sudopigeek** [comment]
Do you have VMWare Workstation pro installed, or just the player?

**Comment by TFTWPhoenix** [comment]
Player. (VMWare Workstation 15 Player)

**Comment by TFTWPhoenix** [comment]
Do i need to install Workstation Pro?

**Comment by TFTWPhoenix** [comment]
I'm trying with Workstation Pro...

**Comment by sudopigeek** [comment]
Yes. Unfortunately, it's not free, but as your screenshot shows, VMWARE won't let you read or write VMDKs without having pro installed.

**Comment by TFTWPhoenix** [comment]
RIP. Ok. Thanks for your help. As you commented it worked.
