### ISSUE TITLE
Detect if running on real hardware?

### ISSUE THREAD

**Issue by samnad** [CosmosOS/Cosmos#1508]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Running on real hardware

#### Actual Behaviour - What unexpectedly happens?

I can't.

#### Reproduction - How did you get this error to appear?

Not an error.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Devkit built with latest github

**Comment by TFTWPhoenix** [comment]
You want to detect if you are running on real hardware? If you want to know how to run on real hardware:
[Boot from USB](https://github.com/CosmosOS/Cosmos/wiki/Booting-Your-OS-from-a-USB-Drive)
or
[Install to a Hard Drive](https://github.com/CosmosOS/Cosmos/wiki/Deploy-%28install%29-Cosmos-on-physical-Hardware)

**Comment by samnad** [comment]
Thanks for the quick response! I know how to run on real hardware, I've been doing that, but some of the features that work in a virtual machine don't work on real hardware, so I was just seeing if it was possible to detect if the machine is physical or virtual.

**Comment by TFTWPhoenix** [comment]
Okay. Thanks for clarification.

**Comment by KM198912** [comment]
one solution i could think of (if you use a GUI) is to detect which driver is using the canvas, if the SVGAII driver is loaded you would know if you run in the VM,

**Comment by KM198912** [comment]
What i just thought of: if you use console mode you could for example on boot add a "loading" canvas which would init the canvas and then allows for detection of the graphics driver in use, then you could disable the canvas. Since only VMWare uses the SVGAII driver this could be a Solution.

**Comment by samnad** [comment]
Thanks, I based a solution some code I found based on your idea, like this:
`if (Cosmos.HAL.PCI.GetDevice(Cosmos.HAL.VendorID.VMWare, Cosmos.HAL.DeviceID.SVGAIIAdapter) != null || Cosmos.HAL.PCI.GetDevice(Cosmos.HAL.VendorID.Bochs, Cosmos.HAL.DeviceID.BGA) != null || Cosmos.HAL.PCI.GetDevice(Cosmos.HAL.VendorID.VirtualBox, Cosmos.HAL.DeviceID.VBVGA) != null)
            {`
and I don't even need to initialize the canvas. I got it here: https://github.com/aura-systems/Aura-Operating-System/blob/master/Aura%20Operating%20System/Aura_OS/System/Video.cs
