### ISSUE TITLE
It won't show up even i use .exe installer where to put cosmos?

### ISSUE THREAD

**Issue by blockplacer** [CosmosOS/Cosmos#1509]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Install

#### Expected Behaviour - What do you think that should happen?

Seeing cosmo os in vs 2017
#### Actual Behaviour - What unexpectedly happens?

it won't show up
#### Reproduction - How did you get this error to appear?
Just installing User Kit

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit 20181010

I need just get it into vs 2017 it won't show up i reinstalled zillion of times but it won't work.
I need template get to working but it not.
Where to put files that installer extracted even every youtube video is so outdated or using  vs 2008.
Also where even installs extension i can't find any damn sort of extension in vs 2017 installation extensions folder.

**Comment by blockplacer** [comment]
it won't work still i tried again reinstaling few times it still doesn't appear in vs 2017

**Comment by blockplacer** [comment]
theres no damn instruction to where put the damn source code.
they directly say install and it will be in vs 2017 but it isn't

**Comment by ChristofBecu** [comment]
You need [VS2019](https://www.gocosmos.org/download/)

**Comment by blockplacer** [comment]
its userkit for vs 2017 but it won't work

**Comment by blockplacer** [comment]
it susposed to used  with vs 2017 as the versions say the latest version can used with vs 2017 was userkit20181010

**Comment by blockplacer** [comment]
i stuck with vs 2017 beacuse vs 2019 install won't start due manual uninstallation of vs 2019 and vs 2019 stuck in windows registry

**Comment by quajak** [comment]
You should be able to just run the userkit install, the exact location shouldnt matter. If the extensions arent installing check under `AppData\Roaming\Cosmos User Kit\VSIX` and manually install the two extensions

**Comment by blockplacer** [comment]
> You should be able to just run the userkit install, the exact location shouldnt matter. If the extensions arent installing check under `AppData\Roaming\Cosmos User Kit\VSIX` and manually install the two extensions
it won't install
16.10.2020 11:21:59 - Microsoft VSIX Installer
16.10.2020 11:21:59 - -------------------------------------------
16.10.2020 11:21:59 - vsixinstaller.exe version:
16.10.2020 11:21:59 - 16.7.3069
16.10.2020 11:21:59 - -------------------------------------------
16.10.2020 11:21:59 - Command line parameters:
16.10.2020 11:21:59 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\casper\AppData\Roaming\Cosmos User Kit4\VSIX\Cosmos.VS.ProjectSystem.vsix
16.10.2020 11:21:59 - -------------------------------------------
16.10.2020 11:21:59 - Microsoft VSIX Installer
16.10.2020 11:21:59 - -------------------------------------------
16.10.2020 11:22:03 - System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query)
   konum: VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
   konum: VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
   konum: VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
   konum: VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
   konum: VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   konum: VSIXInstaller.App.Initialize()
   konum: System.Threading.Tasks.Task`1.InnerInvoke()
   konum: System.Threading.Tasks.Task.Execute()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by quajak** [comment]
This is a problem with your installation/configuration of VS. I cant really help you with this, maybe google this error message. A quick look found this https://developercommunity.visualstudio.com/content/problem/869732/vsix-installer-fails-with-object-reference-not-set.html
