### ISSUE TITLE
Please give better instructions about how to install cosmos

### ISSUE THREAD

**Issue by blockplacer** [CosmosOS/Cosmos#1510]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Install guide on website
#### Expected Behaviour - What do you think that should happen?

Giving detail what to do about extracted thing
#### Actual Behaviour - What unexpectedly happens?
in visual studio templates it won't show up is theres ay extra steps?

#### Reproduction - How did you get this error to appear?
just install it it will not show up

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest one

just give every detail how to install this thing it WON'T APPEAR in vs and theres no instruction to WHat to do damn extracted things **WHAT IM SUSPOSED TO DO EXTRACTED USERKIT**?

theres just they saying

Download the latest release of Cosmos (download the exe file)
Wait for the download to complete then run the installer. Allow it to run as admin. Make sure VS2019 is NOT running when you do this.
Click “Next” then “Install”
Wait for the install to progress. Tip: At the end the installer may look like it has stalled, but it is still doing something in the background. WAIT for the “Finish” button to become available.
Cosmos should now be installed. Follow other tutorials to find out how to create your first OS.

tried: running as admin
vs isn't on
finish button is available at end its directly allows me finish installer
its seems to be not showing in templates where it even installs extension

please give to way install extension manually without Dev kit just **extension File**

**Comment by zarlo** [comment]
there is a guide on the site http://www.gocosmos.org/docs/install/

**Comment by blockplacer** [comment]
its not works installs but nothing on Visual Studio
**HOW TO INSTALL make better installer or make an manual installation for user kit(basically compiled version of dev kit) that user needs open visual studio drag drop extensions**

**Comment by zarlo** [comment]
you can just download the source and run the install-*.bat

**Comment by octaviousrex** [comment]
I certainly had issues with installing Cosmos, but only with the DevKit. I think that Cosmos' dormant YouTube channel should be put to use and add some more videos on the matter. I myself would like to make videos on Cosmos but I not think that I have enough Cosmos Know- How to do so. 

For the user kit, I just installed VS19 (Visual Studio 2019) and downloaded the cosmos exe from here (https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20200708) and I also grabbed the zip file. I hope your issue gets resolved because I've had a lot of fun with Cosmos just in the last three weeks of me using it!

**Comment by octaviousrex** [comment]
> #### Area of Cosmos - What area of Cosmos are we dealing with?
> Install guide on website
> 
> #### Expected Behaviour - What do you think that should happen?
> Giving detail what to do about extracted thing
> 
> #### Actual Behaviour - What unexpectedly happens?
> in visual studio templates it won't show up is theres ay extra steps?
> 
> #### Reproduction - How did you get this error to appear?
> just install it it will not show up
> 
> #### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
> latest one
> 
> just give every detail how to install this thing it WON'T APPEAR in vs and theres no instruction to WHat to do damn extracted things **WHAT IM SUSPOSED TO DO EXTRACTED USERKIT**?
> 
> theres just they saying
> 
> Download the latest release of Cosmos (download the exe file)
> Wait for the download to complete then run the installer. Allow it to run as admin. Make sure VS2019 is NOT running when you do this.
> Click “Next” then “Install”
> Wait for the install to progress. Tip: At the end the installer may look like it has stalled, but it is still doing something in the background. WAIT for the “Finish” button to become available.
> Cosmos should now be installed. Follow other tutorials to find out how to create your first OS.
> 
> tried: running as admin
> vs isn't on
> finish button is available at end its directly allows me finish installer
> its seems to be not showing in templates where it even installs extension
> 
> please give to way install extension manually without Dev kit just **extension File**

I would honestly do Userkit first
