### ISSUE TITLE
Keyboard not working.... help

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1511]
I made an os in c# and booted it from USB... It Booted successfully , but the keyboard wasn't working.... Please help!!

![IMG_20200922_000629.jpg](https://user-images.githubusercontent.com/70532109/93815845-b3682780-fc67-11ea-99b4-bed2a5cf38f3.jpg)

**Comment by zarlo** [comment]
is the keyboard PS/2 or USB

**Comment by Vardan2009** [comment]
@zarlo it's USB

**Comment by Vardan2009** [comment]
@BiberGames Really???

**Comment by samnad** [comment]
Yes. USB support is coming in the future.

**Comment by Vardan2009** [comment]
But I tried on another computer and it worked...

**Comment by quajak** [comment]
Some BIOS support using USB Keyboards as PS2 Keyboards.

**Comment by Vardan2009** [comment]
**Ok!**
Thanks for helping me!!
