### ISSUE TITLE
inno setup is installed but its says failed to install depencency inno setup

### ISSUE THREAD

**Issue by blockplacer** [CosmosOS/Cosmos#1514]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Setup

#### Expected Behaviour - What do you think that should happen?
It should install

#### Actual Behaviour - What unexpectedly happens?
fails

#### Reproduction - How did you get this error to appear?

just install dev kit
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest devkit

inno setup already existed
is theres a way to modify depencency checker to skip depencency checking and **JUST INSTALL** without failing it?

or rather than downloading new version of innosetup make it  just download right version for cosmos

**Comment by sudopigeek** [comment]
Can you please post the error log?

**Comment by blockplacer** [comment]
its just depencency failed to install error log is depencency failed to install one.
attempts for fixing this:
modifying .cs files to remove detection of inno setup but weirdly vsforcing to run old versions of setup as the result new files never gets compiled

**Comment by ThomasBonomo** [comment]
Same issue here, which sucks, because I can't use the latest version of the UserKit either.

**Comment by octaviousrex** [comment]
I got those issues too, but i eventually used the user kit instead. I will look around though, see what i can find.
