### ISSUE TITLE
Debugger restarts visual studio

### ISSUE THREAD

**Issue by carcarjg** [CosmosOS/Cosmos#1515]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugger

#### Expected Behaviour - What do you think that should happen?
Debugger starts -> VMWare opens -> Debugger connects -> OS Crashes -> VMWare closes -> Edit code on VS without it restarting

#### Actual Behaviour - What unexpectedly happens?

Debugger starts -> VMWare opens -> Debugger connects -> OS Crashes -> VMWare closes -> Visual Studio Restarts

#### Reproduction - How did you get this error to appear?

Made a OS and ran it.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

UserKit, Latest.

**Comment by quajak** [comment]
Do you get any error message in the VS logs?

**Comment by carcarjg** [comment]
No, It just silently closes and reopens. Nothing like a crash but more like an application is telling it to. It saves all unsaved work and cleans up things on close just as if I would of hit the close button.

**Comment by quajak** [comment]
Does the `ActivityLog.xml` (`%APPDATA%\Microsoft\VisualStudio\Version\ActivityLog.xml`) mention Cosmos anywhere?  
Could you also check Windows Event Viewer (Start -> Event viewer->Windows Logs->Application) and see if there are error logs for devenv.exe with timestamp that matches the crash?

**Comment by carcarjg** [comment]
None, in the Event Viewer. I haven't checked the ActivityLog yet
