### ISSUE TITLE
Repeated Exception x06's

### ISSUE THREAD

**Issue by carcarjg** [CosmosOS/Cosmos#1516]
#### Expected Behaviour - What do you think that should happen?
Not this

#### Actual Behaviour - What unexpectedly happens?
Runs then throw CPU exeption on address 02156664 (l .text 00000000 DebugStub_SendCoreDump_Block2_End)
Seems to happen on both file loading and screen calls. Can't seem to pin it down.
Tried on VMware, botch, and real steel

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User

**Comment by TFTWPhoenix** [comment]
What file loading method are you using? Most of system.io works perfectly. And what are you referring to as "screen calls"?

**Comment by carcarjg** [comment]
After some digging, it seems that the font drawer or beep was causing it.

**Comment by carcarjg** [comment]
Nevemind its Canvas.clear(Color.Blue); When it hits that line on the breakpoints it errors

**Comment by TFTWPhoenix** [comment]
Try either using Cosmos's breakpoints (not VS-2019's) or using the integer value for blue instead of `Color.Blue`

**Comment by carcarjg** [comment]
> Try either using Cosmos's breakpoints (not VS-2019's) 
I was not aware Cosmos had its own breakpoints.

**Comment by TFTWPhoenix** [comment]
It does. Use them by `Global.Dbg.Break();`
