### ISSUE TITLE
Is there a way to lock the mouse?

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1517]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI

#### Expected Behaviour - What do you think that should happen?
I should be able to move my window freely, so as I wish.

#### Actual Behaviour - What unexpectedly happens?
I can only move the window at either bottom or right.

#### Reproduction - How did you get this error to appear?
It's not an error, but then I need a way to make the mouse not go away when trying to move my window at left or top.
Here's my code :

`if (Open)
{
                if (IsTitlebarClicked())
                {
                    if (LastX != X || LastY != Y)
                    {
                        Display.FillRectangle(LastX, LastY, Width, Height + TitlebarHeight, Display.DefaultColor);

                        LastX = X;
                        LastY = Y;
                    }

                    X = Mouse.X;
                    Y = Mouse.Y;
                    Draw();
                }
            }`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Userkit (2020)

**Comment by quajak** [comment]
> I should be able to move my window freely, so as I wish.

Cosmos does not currently support windows out of the box. Are you using additional code/library for window functionality? If yes, this question should not be asked here.

**Comment by KM198912** [comment]
> 
> 
> > I should be able to move my window freely, so as I wish.
> 
> Cosmos does not currently support windows out of the box. Are you using additional code/library for window functionality? If yes, this question should not be asked here.

i experience the same issue @quajak  however this only happens on real hardware i.e Laptops with touchpad without third party library so it relates more to the PS/2 Driver

**Comment by AnErrupTion** [comment]
> > I should be able to move my window freely, so as I wish.
> 
> Cosmos does not currently support windows out of the box. Are you using additional code/library for window functionality? If yes, this question should not be asked here.

I use my own Window Manager. However I figured out how to make the window move, but then the cursor still goes away from the title bar (filled rectangle) which causes some more problems, so is there a way to technically "lock" (sort of) the cursor?

**Comment by quajak** [comment]
What do you mean with lock the mouse? Keep it at a certain position?

**Comment by AnErrupTion** [comment]
Like make it so that it doesn't go out of a specific rectangle (like it doesn't go out of bounds of it)

**Comment by quajak** [comment]
You can overwrite the position of the mouse stored in MouseManager.

**Comment by AnErrupTion** [comment]
But then it moves the window because the left click is hold by the user

**Comment by quajak** [comment]
I dont really see the need for Cosmos to support this behaviour this can be handled in a custom mouse manager.
