### ISSUE TITLE
Again Exception system.exception

### ISSUE THREAD

**Issue by vazer7070** [CosmosOS/Cosmos#1519]
Hello everyone,

I saw on a previous topic that this problem had already occurred but it just says "reimplente sharpcodeprovider", but no way how to do that and I find myself with this bug without knowing how to fix it.
Could someone help me please.?

thanks in advance

#### Reproduction - How did you get this error to appear?
just add new code in Cosmos project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
i use the latest version of the UserKit

**Comment by quajak** [comment]
Can you please post the error message or output related to this bug?

**Comment by vazer7070** [comment]
![Sans titre](https://user-images.githubusercontent.com/48102423/96165703-3f930500-0f1d-11eb-9414-08ee4aac5d5c.png)

**Comment by quajak** [comment]
Please post the log in the output window as well.

**Comment by vazer7070** [comment]
![Sans titre](https://user-images.githubusercontent.com/48102423/96167102-2db26180-0f1f-11eb-810c-79250c8dc15f.png)

**Comment by quajak** [comment]
You are trying to use code which requires a plug related to threading. Add these plugs is not a priority and therefore wont be fixed anytime soon. You are welcome to add your own placeholder plug and a pr with the plug is appreciated.

**Comment by vazer7070** [comment]
how to add plug please.? any doc or tutorial.?

**Comment by quajak** [comment]
You will need the devkit. https://www.gocosmos.org/docs/plugs/ gives an overview of how to write plugs. In your case you will have to create a plug class for Interop.Kernel32 in https://github.com/CosmosOS/Cosmos/tree/master/source/Cosmos.System2_Plugs/System with a method plugging Kernel32.GetCurrentProcessId() (it can just return 1 always). Look around Cosmos.System2_Plugs for examples of plugs.

**Comment by charlesbetros** [comment]
Looks like you are calling
`Process.GetCurrentProcess()` in your Console Initialize. As @quajak mentioned Processes and Threading are not currently supported.

We don't plan to work on those any time soon.
