### ISSUE TITLE
Directory.Create is broken

### ISSUE THREAD

**Issue by GreenCobalt** [CosmosOS/Cosmos#1520]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Filesystem

#### Expected Behaviour - What do you think that should happen?

Creates directory

#### Actual Behaviour - What unexpectedly happens?

Doesn't

#### Reproduction - How did you get this error to appear?

Initialize filesystem. Use that method.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev kit latest.

**Comment by quajak** [comment]
Can you please post code which reproduces your problem?

**Comment by samnad** [comment]
Yeah, just initialize the FS and use 
`Directory.CreateDirectory(@"0:\SYS\");`

**Comment by quajak** [comment]
As you can see here https://github.com/CosmosOS/Cosmos/blob/25639bc2799d109719fa193bb1b391934279d0cb/Tests/Kernels/Cosmos.Kernel.Tests.Fat/System.IO/DirectoryTest.cs#L16 this shoudld be working. Did you modify the vmdk file?

**Comment by KM198912** [comment]
@quajak i tested it myself, if you create a directory, then try to write a file to that directory it errors with a null exception and the file created in the folder is displayed in a garbled manner
Directory.CreateDirectory(@"0:\SYSTEM");
File.Create(@"0:\SYSTEM\fs.cfg");

**Comment by quajak** [comment]
That may have a similar cause as https://github.com/CosmosOS/Cosmos/pull/1480 had.

**Comment by samnad** [comment]
So fs.CreateDirectory() is now working, but now I also can't delete files or directories, with either method. I changed nothing.

**Comment by quajak** [comment]
If you run the Fat tests, do the directory test pass?

**Comment by samnad** [comment]
I don't know what that is. But I got an error message this time:
the specified argument was outside the range of acceptable values
argument: aFirstCluster

**Comment by charlesbetros** [comment]
Did you create the virtual hard disk?

If yes, how did you format it?
