### ISSUE TITLE
VS wants me to set Startup Project but startup project button does nothing.

### ISSUE THREAD

**Issue by blockplacer** [CosmosOS/Cosmos#1521]
Have you checked Github Issues for similar errors?
yes
**Exception**
it just want some things 
set startup project etc. also weirdly cosmos symbol won't appear on project

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
nothing
**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
just installing user kit and trying to building it
**Screenshots**

**Context**
Before posting please confirm that the following are in order
[ Yes] Both Cosmos VS Extensions are installed
[ Yes] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.

**Comment by blockplacer** [comment]
i fixed it but it now just shows depencencies with yellow warning symbol but why?
everyhting installed

**Comment by quajak** [comment]
In the nuget manager, check that `Include rerelease` is selected and check that under Package source there exists `Cosmos Local Package Feed`. This should mean that all cosmos nuget packages have a version number.
Can you also check the output log for information?

**Comment by blockplacer** [comment]
theres noothing called cosmos local package number and version numbers not exist on nuget packages weirdly in visual studio.
coming from another ide pretty newbie to visual studio

**Comment by blockplacer** [comment]
going to try to copy nuget packages from somewhere else seems to be its not installed correctly

**Comment by quajak** [comment]
Can you please manually add a nuget source with the following values and then restore nuget packages?
![image](https://user-images.githubusercontent.com/8559822/96346756-bb1bc000-109d-11eb-9134-996e6708a0bc.png)

**Comment by blockplacer** [comment]
where to do (newbie to visual studio)

**Comment by quajak** [comment]
In the nuget package manager 
![image](https://user-images.githubusercontent.com/8559822/96347907-52384600-10a5-11eb-8bd3-964164ff2c39.png)

**Comment by blockplacer** [comment]
after its added still error present

**Comment by blockplacer** [comment]
trying to update packages it might solve it

**Comment by blockplacer** [comment]
error occurred: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
1>   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
1>   at Cosmos.IL2CPU.Program.Run(String[] args, Action`1 logMessage, Action`1 logError) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\Program.cs:line 58
1>IL2CPU task took 00:00:39.7259336

**Comment by quajak** [comment]
What userkit version are you using? No iso was generated since IL2CPU failed to run.

**Comment by blockplacer** [comment]
latest one

**Comment by quajak** [comment]
Is that the entire output log, if not, can you please post the rest as well?

**Comment by blockplacer** [comment]
its  dll compiling and fail message

**Comment by quajak** [comment]
Have you tried creating a new kernel? With the information currently provided, I have no idea what the cause is.

**Comment by blockplacer** [comment]
yes tried few times
