### ISSUE TITLE
Windows 10 insider built ran into problem

### ISSUE THREAD

**Issue by adityadand** [CosmosOS/Cosmos#1528]
#### Area of Cosmos - What area of Cosmos are we dealing with?
testing command line os

#### Expected Behaviour - What do you think that should happen?
application should not let windows 10 to crash

#### Actual Behaviour - What unexpectedly happens?
windows 10 is crashing when running code

#### Reproduction - How did you get this error to appear?
when i removed console.readline statement this error occoured

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
CosmosUserKit-20181010-vs2017
visual studio 2017

**Comment by KM198912** [comment]
VS2017 UserKit is outdated, you should upgrade to VS2019 and use latest UserKit
