### ISSUE TITLE
Interacting with programatically created VFS folders causes an exception

### ISSUE THREAD

**Issue by samnad** [CosmosOS/Cosmos#1539]
#### Area of Cosmos - What area of Cosmos are we dealing with?

VFS

#### Expected Behaviour - What do you think that should happen?

Does whatever the action is: listing files, creating files, etc etc.
**Note: creating the folder is fine. It shows up when I list the contents of the parent dir and shows as a folder.**

#### Actual Behaviour - What unexpectedly happens?

Causes "Exception: Specified argument was out of the range of valid values. Parameter name: aFirstCluster"

#### Reproduction - How did you get this error to appear?

Copy and paste this code into the kernel.cs of a new project:
```using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.Listing;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Sys = Cosmos.System;

namespace testKernel
{
    public class Kernel : Sys.Kernel
    {
        public static CosmosVFS fs;

        protected override void BeforeRun()
        {
            fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

            Console.WriteLine("Formatting drive...");
            fs.Format(@"0:\", "FAT32", false);
            Console.WriteLine("Done! Making folder...");
            Directory.CreateDirectory(@"0:\SYS\");
            Console.WriteLine("Done!");
        }

        protected override void Run()
        {
            Console.Write(">");
            var input = Console.ReadLine();
            if (input == "test")
            {
                try
                {
                    List<DirectoryEntry> dl = fs.GetDirectoryListing(@"0:\SYS\");
                    foreach(DirectoryEntry d in dl)
                    {
                        Console.WriteLine(d.mName);
                    }
                } catch (Exception ex)
                {
                    Console.WriteLine("Exception caught: " + ex);
                }
            }
        }
    }
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest Devkit build

**Comment by samnad** [comment]
Ok, I just mounted the vdmk into my File Explorer in windows and when I tried to open the folder, it said that it was "missing".

**Comment by quajak** [comment]
Thanks for the good bug report, was able to reproduce and fix it.

**Comment by samnad** [comment]
Nice, thanks!
