### ISSUE TITLE
open a real directory in a real hardware

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1542]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Filesystem

#### Expected Behaviour - What do you think that should happen?

open a real directory in a real hardware

#### Reproduction - How did you get this error to appear?

    CosmosVFS` fs = new Sys.FileSystem.CosmosVFS();

 Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

 s = "C:\";
                                var directory_list = fs.GetDirectoryListing(s);
                                var dirlistarray = directory_list.ToArray();
                            
                                foreach (var directoryEntry in directory_list)
                                {

                                    Console.WriteLine(directoryEntry.mName);
                                }

It Shows this
![File System Files List](https://user-images.githubusercontent.com/70532109/97145986-8cc67080-1780-11eb-9c35-41b7bcb0de44.png)

Is It Possible to open a real directory?

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

EDIT: I Booted it from USB, it says "Invalid Data Size"

**Comment by quajak** [comment]
If the hdd connected to the real hardware has a fat32 partition it should be possible to read from the real directory.

**Comment by Vardan2009** [comment]
When Booting it from USB, it says "Invalid Data Size"

**Comment by KM198912** [comment]
> 
> 
> When Booting it from USB, it says "Invalid Data Size"

This looks like a wrong formatted Partition

**Comment by Vardan2009** [comment]
??

**Comment by KM198912** [comment]
ok i see the error, you assign s = "C:" but cosmos uses a numeric system, so you have to do string s = @"0:\";

**Comment by Vardan2009** [comment]
Is it gonna work?

**Comment by KM198912** [comment]
it should

**Comment by Vardan2009** [comment]
its not working...

**Comment by quajak** [comment]
whats the current error message?

**Comment by Vardan2009** [comment]
it just shows the same

**Comment by Vardan2009** [comment]
EDIT: I think after booting this will work :/
