### ISSUE TITLE
OS Freezes when drawing an image

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1543]
#### Area of Cosmos - What area of Cosmos are we dealing with?

GUI.

#### Expected Behaviour - What do you think that should happen?

Draw a bitmap image

#### Actual Behaviour - What unexpectedly happens?

the OS freezes

#### Reproduction - How did you get this error to appear?

I Just wrote this line to draw an image:
` canvas.DrawImage(new Bitmap(@"C:\Users\user\Desktop\BITMAP.bmp"), 40, 30);`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

**Comment by quajak** [comment]
The path to the bitmap must be on the filesystem of the os not the system used to compile it.

**Comment by Vardan2009** [comment]
but how to do this...

**Comment by elkaamee326** [comment]
You can go on VMware Workstation 15.0 player with Cosmos selected and go -> Edit virtual machine settings. Than you go -> Hardisk IDE than go on map virtual disk. Tick off read only mode on the dialog and press enter. Than you can add your Cosmos OS images and other assets to the virtual disk.

**Comment by Vardan2009** [comment]
I Cant Map The virtual disk
![Error](https://user-images.githubusercontent.com/70532109/97808183-ddf1cb00-1c7e-11eb-895e-bd930f0900a7.jpg)

**Comment by Vardan2009** [comment]
`dunduk productions!`

**Comment by Vardan2009** [comment]
:(

**Comment by octaviousrex** [comment]
> I Cant Map The virtual disk
> ![Error](https://user-images.githubusercontent.com/70532109/97808183-ddf1cb00-1c7e-11eb-895e-bd930f0900a7.jpg)
> 

I'd look that up, because there may be a relevant search result for the mapping part

**Comment by sudopigeek** [comment]
You can't map the virtual disk because that feature is only avaliable in Vmware pro, unfortunately

**Comment by quajak** [comment]
Can you try map the vmdk from within Windows Explorer?

**Comment by Vardan2009** [comment]
how to do this

**Comment by KM198912** [comment]
use IMDisk ToolKit https://sourceforge.net/projects/imdisk-toolkit/

**Comment by Vardan2009** [comment]
but how to use it?

**Comment by MagicMikey6** [comment]
`Public class Hi {
    Public void g {
        Console.write("Banananananananananananananananana");
    }
}`
Output:
`Banananananananananananananananana`

**Comment by nimmam831** [comment]
?
