### ISSUE TITLE
How to make mouse cursor

### ISSUE THREAD

**Issue by boyangsic** [CosmosOS/Cosmos#1545]
**How To make Mouse?**

**Comment by valentinbreiz** [comment]
We have a wiki for that: https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI:-Adding-the-mouse

**Comment by Edersteiner** [comment]
> 
> 
> We have a wiki for that: https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI:-Adding-the-mouse

The mouse device link is removed

**Comment by boyangsic** [comment]
yea old device link removed

**Comment by Edersteiner** [comment]
> 
> 
> yea old device link removed

You can use the built-in mouse device.

**Comment by Vardan2009** [comment]
Use MouseManager!

MouseManager m = new MouseManager();

then draw the cursor

Pen pen = new Pen(Color.Black);
canvas.DrawPoint(pen,m.X,m.Y);


Hope this helps!
