### ISSUE TITLE
Does COSMOS Support the DLLImport Attribute ???

### ISSUE THREAD

**Issue by elkaamee326** [CosmosOS/Cosmos#1548]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Importing external functions from C++ dlls into C# COSMOS.

Also would it be affected due to COSMOS being a seperate filesystem instead of loading it from C:/ ? Or it should work perfectly fine?
ie:
`[DllImport("DllName.dll")]`
`public static extern void Function(int do_something, bool this);`
`public void Afunction(int do_something, bool this)`
`{`
   ` Function(do_something, this);`
`}`

And than use the function in another function.

#### Reproduction - How did you get this error to appear?
It's not an error, its just a question.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit 20200708

Thank you, an answer is very much appreciated!

**Comment by quajak** [comment]
Cosmos doesnt support importing c++ dlls.

**Comment by elkaamee326** [comment]
Does it support C# dlls?

**Comment by quajak** [comment]
yeah they should work

**Comment by elkaamee326** [comment]
Okay than. Thank you very much!
