### ISSUE TITLE
New IDE software for Windows for developing an operating system announcement

### ISSUE THREAD

**Issue by fy1vo51** [CosmosOS/Cosmos#1552]
This year, I would like to introduce a new IDE software for developing an operating system with BASIC programming language called DevOS Studio IDE, is a free software for Windows platform. It's similar like Cosmos of C#, but this is with BASIC code.

The software is under development, try the beta release to test yourself and you can enjoy for a stable release.

Site: [https://sourceforge.net/projects/devos-studio/](https://sourceforge.net/projects/devos-studio/)

![image](https://user-images.githubusercontent.com/63316499/97810959-27212b00-1c3d-11eb-856c-f5c4e481e2d0.png)

![image](https://user-images.githubusercontent.com/63316499/97811111-01485600-1c3e-11eb-9035-ed5ef062bef7.png)

**Comment by ascpixel** [comment]
Sorry, but I don't think you should be advertising your software in the issues of an open-source repo :P

**Comment by fy1vo51** [comment]
I know this one it's not an issue but yeah you're right, I posted this in the issue but I might be remove and post in another page, but where?

**Comment by Edersteiner** [comment]
> 
> 
> I know this one it's not an issue but yeah you're right, I posted this in the issue but I might be remove and post in another page, but where?

This isn't really Cosmos related, so it shouldn't be posted here. osdev.org is a more appropriate place to post this.

**Comment by fy1vo51** [comment]
Ok, I'll close this issue now.
