### ISSUE TITLE
Can't change color with ANSI ESC character

### ISSUE THREAD

**Issue by thkdlflghlsdghilr** [CosmosOS/Cosmos#1555]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Printing to screen

#### Expected Behaviour - What do you think that should happen?
Print colored text

#### Actual Behaviour - What unexpectedly happens?
Prints arrow and the code without changing the color

#### Reproduction - How did you get this error to appear?
Console.WriteLine("\x1B[31mHello World!\u001b[0m");

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Newest User Kit

Pic of the console with the arrow: https://ibb.co/q9vGykq

**Comment by KM198912** [comment]
if you want to change the color look at Console.ForegroundColor, ie Console.ForegroundColor = Color.Red;

**Comment by thkdlflghlsdghilr** [comment]
> if you want to change the color look at Console.ForegroundColor, ie Console.ForegroundColor = Color.Red;

I want to use escape characters to change the color so I can console.WriteLine(); a image as text

**Comment by thkdlflghlsdghilr** [comment]
Console.ForegroundColor, ie Console.ForegroundColor = Color.Red; I will have to use a massive loop

**Comment by KM198912** [comment]
as far as i am aware the only supported way of changing colors currently is the way mentioned above

**Comment by thkdlflghlsdghilr** [comment]
oof

**Comment by ascpixel** [comment]
> > if you want to change the color look at Console.ForegroundColor, ie Console.ForegroundColor = Color.Red;
> 
> I want to use escape characters to change the color so I can console.WriteLine(); a image as text

You can use `Console.Write()` with the `Console.ForegroundColor` and `Console.BackgroundColor` properties to change colors without creating a new line

**Comment by thkdlflghlsdghilr** [comment]
yeah but I have an image saved as a big string of escape characters, boxes, and new lines that I want to print all at once rather than going box by box changing the color
