### ISSUE TITLE
Ability to add large files

### ISSUE THREAD

**Issue by ascpixel** [CosmosOS/Cosmos#1556]
**Is your feature request related to a problem? Please describe.**
With ManifestResourceStream, it's impossible to attach big (over 1MB) files to the OS, mainly because of NASM failing to compile the project. Holding the file in memory all the time is also not a great idea.

**Describe the solution you'd like**
Storing the file on the disk that the OS is running from sounds like a good idea. This could also solve the problem of holding the file in memory all the time. Something like a method that would return a byte array would be best; it would work very similarly to ManifestResourceStream when it comes to using it - the only difference would be that a method would be used instead of a attribute: `ResourceManager.GetResource("MyCosmosProject.Path.To.File.example.png");` vs the current `[ManifestResourceStream(ResourceName = "MyCosmosProject.Path.To.File.example.png")]`

**Describe alternatives you've considered**
There is also the possibility of storing all files in one singular chunk. This probably require a table of contents, and it would require seeking. If accessing different files wouldn't work, this would probably be the solution. Another solution would be to somehow include the file in the binary itself, but not store it in memory (something modern software installers do). This would allow to store the table of contents in memory, and to read from the binary we know we are executing using the offsets + sizes we would store in the table of contents.

**Additional context**
If a file that is too big would be provided to ManifestResourceStream, NASM would report: `Kernel.asm:300: error: interminable macro recursion`

**Comment by valentinbreiz** [comment]
So did you try to put your file in the filesystem?

**Comment by ascpixel** [comment]
Sorry for the late response!
What do you mean by putting the file into the filesystem? If you are talking about making a VM with a ready disk image, I'm afraid that won't work for my case... I'm trying to package the files in the final ISO; just like you would do with a regular OS distribution. I would be fine with CD/DVD image support, but it seems that COSMOS only supports hard drives, and does not support reading from CDs or DVDs.

**Comment by elkaamee326** [comment]
For some reason, NASM reports, when I have too much code on a page, it reports it as interminable macro recursion, would there be a way to resolve the interminable macro recursion error? Thank you :)

**Comment by elkaamee326** [comment]
Try using YASM if https://github.com/CosmosOS/Cosmos/pull/1728 doesn't still resolve the error. But, you are going to need to do a few manual modifications to the `Nasm.cs` file in the dev kit.

**Comment by MishaTY** [comment]
The best way to solve this problem is to implement ATAPI and the iso9660 file system, then we can read files from the CD. See #1779
