### ISSUE TITLE
how to put the image

### ISSUE THREAD

**Issue by boyangsic** [CosmosOS/Cosmos#1560]
how to put the image with only cosmos Code?(No use Vmware disk edit, only code)

**Comment by KM198912** [comment]
canvas,DrawImage(bitmapfile)

**Comment by boyangsic** [comment]
i mean, how to put image files on cosmos filesystem with code

**Comment by sudopigeek** [comment]
As far as I know, Cosmos doesn't yet have the ability to access outside drives. The only other option for doing this is probably to use code to crrate a blank image file and edit it within Cosmos.

**Comment by zarlo** [comment]
you can store the file in a byte array

**Comment by KM198912** [comment]
or use a resourcefile

**Comment by boyangsic** [comment]
how to use resourcefile?

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/blob/master/Demos/ZMachine/ZKernel/Kernel.cs#L19 for an example

**Comment by octaviousrex** [comment]
> See https://github.com/CosmosOS/Cosmos/blob/master/Demos/ZMachine/ZKernel/Kernel.cs#L19 for an example
I assume the resourcefile is a folder that cosmos can access? where would it be located on my pc, and if its located anywhere, can i just drag and drop compatible files into the folder?

**Comment by quajak** [comment]
To add a file as resource file add it to your project in visual studio and in the properties set its type to Embedded Resource.

**Comment by octaviousrex** [comment]
Thanks, that does make sense.

**Comment by quajak** [comment]
Can this issue be closed?

**Comment by octaviousrex** [comment]
I do think that it should be, as all of the questions have been answered.
