### ISSUE TITLE
Defining events

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1561]
I have been trying to code events with Cosmos for a little while now, and I haven't yet figured out how. I have a general idea of how to do it from issue #1502, but I don't have a solid idea. Any suggestions?

**Comment by MishaTY** [comment]
Hi, this is what extactly I changed in my code:

from `public event EventHandler MyEvent;`
to:
```
        private EventHandler MyEvent_Handler;
        public event EventHandler MyEvent
        {

            add
            {
                MyEvent_Handler= value;
            }

            remove
            {
                MyEvent_Handler-= value;
            }
        }
```


How I invoked the event was to call `MyEvent_Handler.Invoke(this,new EventArgs());`

**Comment by sudopigeek** [comment]
Thanks, it works nicely now

**Comment by octaviousrex** [comment]
Is calling the same as `using`? I think that is what it is but I am pretty forgetful
