### ISSUE TITLE
System.Int32 plug

### ISSUE THREAD

**Issue by omerhijazi404** [CosmosOS/Cosmos#1562]
I don't know how to add a plug for the system.int32 namespace although it exists in the repository.
I can't use floats, doubles, decimals, or any other thing except for int!
Please help.

**Comment by octaviousrex** [comment]
is system.int32 your own custom namespace?

**Comment by quajak** [comment]
Whats the error message and the output log when you try to compile?

**Comment by omerhijazi404** [comment]
> is system.int32 your own custom namespace?

umm no its a system namespace with things like floats doubles etc.

**Comment by omerhijazi404** [comment]
> Whats the error message and the output log when you try to compile?

Build started...
1>------ Build started: Project: ChocOsV1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>ChocOsV1 -> C:\Users\HP\source\repos\ChocOsV1\bin\Debug\netcoreapp2.0\cosmos\ChocOsV1.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\HP\source\repos\ChocOsV1\bin\Debug\netcoreapp2.0\cosmos\ChocOsV1.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Int32  System.Threading.Interlocked.ExchangeAdd(&System.Int32, System.Int32).
1>  Called from :
1>System.Threading.Interlocked::Int32 Add(Int32 ByRef, Int32)
1>System.Threading.Interlocked::Int32 Increment(Int32 ByRef)
1>System.Data.DataTable::Void .ctor()
1>ChocOsv1.Kernel::Double Evaluate(System.String)
1>ChocOsv1.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\HP\me\Code\Opensource\CosmosDeps\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 619
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\HP\me\Code\Opensource\CosmosDeps\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 772
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Users\HP\me\Code\Opensource\CosmosDeps\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\HP\me\Code\Opensource\CosmosDeps\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 206
1>IL2CPU task took 00:00:02.3475954
1>Done building project "ChocOsV1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zarlo** [comment]
it the Threading the needs to be pluged

**Comment by omerhijazi404** [comment]
So how can I do that???

**Comment by quajak** [comment]
You will need the devkit. https://www.gocosmos.org/docs/plugs/ gives an overview of how to write plugs. In your case you will add the plug to InterlockedImpl.cs https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core_Plugs/System/Threading/InterlockedImpl.cs with a method plugging Interlocked.ExchangeAdd(System.Int32*, System.Int32). Look around Cosmos.System2_Plugs for examples of plugs.

**Comment by omerhijazi404** [comment]
So i'll add then rebuild devkit? (i already have devkit)

**Comment by quajak** [comment]
Yes, after you made your changes you have to rebuild it. You can test your changes using the Test Runner.
