### ISSUE TITLE
Question: Is there a way to run binary files?

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1563]
Can you run binary files from inside Cosmos? For example:
`System.Diagnostics.Process.Start(@"0:\executable.exe");` Not actually an EXE but you get the point.
If so would they need to be compiled with GCC's -ffreestanding argument?

**Comment by Picoseconds** [comment]
Yes to both

**Comment by TFTWPhoenix** [comment]
Awesome thank you. Is it just `System.Diagnostics.Process.Start()`?

**Comment by Picoseconds** [comment]
It's nowhere near that easy, you must load the specific executable type and jmp to it. 

See https://github.com/Myvar/CosmosELF

**Comment by TFTWPhoenix** [comment]
Ok thank you.
