### ISSUE TITLE
 Hi, I have an error adding the gui and the Mouse. 

### ISSUE THREAD

**Issue by alessiobb1** [CosmosOS/Cosmos#1564]
Hi! 
I have an error in Gui and Mouse. if i add the your mouse code i have some errors. 
You can help me? 
p.s i'm italian, and i not usage the translator, sorry for my english grammar, and i'm 13 years old.. Tranks! 
![Immagine 2020-11-13 140934](https://user-images.githubusercontent.com/65780895/99075538-eec50980-25b9-11eb-8f0a-539644be0dda.jpg)

**Comment by octaviousrex** [comment]
If you are following the mouse and gui tutorial on the cosmos website, they are a little outdated. Try looking at [this](https://github.com/nifanfa/Cosmos-GUI-Sample)

**Comment by alessiobb1** [comment]
I don't see the tutorial. i see only the code.. you know the tutorial?

**Comment by alessiobb1** [comment]
Why VMware error: Error in determine filesystem in 0:/

**Comment by octaviousrex** [comment]
> I don't see the tutorial. i see only the code.. you know the tutorial?

Sorry, it's not a tutorial, but it does point you in the right direction on how to do mouse, and gui

**Comment by octaviousrex** [comment]
> Why VMware error: Error in determine filesystem in 0:/
> 

You should also join the Cosmos Hitter Chat. I can add you, it is the official place to talk about cosmos, and get real-time help

**Comment by alessiobb1** [comment]
Tranks! I join in the group..
