### ISSUE TITLE
Potential IDE for cross-platform

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#1565]
Hi I've been searching for an IDE that may work for CosmosOS to be crossplatform (Linux and Mac), and I think Eclipse with the aCute extension could be a good candidate. aCute allows for C# development. It is also possible make Eclipse extensions. Maybe an eclipse extension for the project type "Cosmos C# Kernel" could work. As for an Inno Setup replacement wouldn't just a bash/zsh script suffice? aCute is just for C# syntax highlighting.

**Comment by TFTWPhoenix** [comment]
Oh also an eclipse extension means it can run regardless of the underlying OS. So any Linux distribution, MacOS, or even windows could all run with an eclipse extension.

**Comment by charlesbetros** [comment]
Visual Studio Code is cross-platform and where we will be focusing our efforts in the future.

**Comment by TFTWPhoenix** [comment]
Okay, I'm excited for that. Thank you for the quick response.
