### ISSUE TITLE
How make font and gui

### ISSUE THREAD

**Issue by alessiobb1** [CosmosOS/Cosmos#1566]
Hi! how i make font and gui?
But the Tutorials that i watched need the Cosmos.Hardware but if i write on 1* line "using Cosmos.Hardware" i recive some Error on "Cosmos.Hardware is not exist in assembly or using." I have UserKit, VS 2019, Win 10 Home.

Tranks!!!

**Comment by quajak** [comment]
The tutorial is most likely out of date. Look at the wiki and other issues for how others are doing it.

**Comment by sudopigeek** [comment]
Try using [CGUI](https://github.com/sudopigeek/CGUI); it should have what you need

**Comment by alessiobb1** [comment]
sudopigeek, the Cgui is not work. the vmware after cosmos boot, load a black screen and after 2 second reboot..

**Comment by alessiobb1** [comment]
I can make a timer in cGUI? or i can make in Run a struing and after the operation,contiue.. Tranks!

**Comment by boyangsic** [comment]
> Try using [CGUI](https://github.com/sudopigeek/CGUI); it should have what you need

how to make cursor using CGUI?

**Comment by quajak** [comment]
Thats a question for the CGUI repository not his one
