### ISSUE TITLE
objdump.bat

### ISSUE THREAD

**Issue by Automedi** [CosmosOS/Cosmos#1567]
Have you checked Github Issues for similar errors?

**Exception**
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	MSB6006	"objdump.bat" exited with code 1.	OS	C:\Users\David\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build	C:\Users\David\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets	258

** VS Output Logs **
1>------ Build started: Project: OS, Configuration: Debug Any CPU ------
1>OS -> C:\Users\David\Desktop\c#\OS\OS\bin\Debug\netcoreapp2.0\cosmos\OS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\David\Desktop\c#\OS\OS\bin\Debug\netcoreapp2.0\cosmos\OS.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.INT3Label'
1>IL2CPU task took 00:00:06.1819688
1>Nasm task took 00:00:09.5758018
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\netcoreapp2.0\cosmos\OS.bin bin\Debug\netcoreapp2.0\cosmos\OS.obj
1>LD task took 00:00:00.2068121
1>Extracting Map file...
1>The system cannot find the path specified.
1>Press any key to continue . . .
1>C:\Users\David\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets(258,9): error MSB6006: "objdump.bat" exited with code 1.
1>Extracting Map file took 00:00:00.4348600
1>Done building project "OS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
No changes. Did a fresh reinstall of everything. And still nothing works

**Screenshots**
![Capture](https://user-images.githubusercontent.com/69730078/99364328-bf5e1780-28ad-11eb-972b-a02ba9a5e5d4.jpg)

**Context**
Before posting please confirm that the following are in order
[x] Both Cosmos VS Extensions are installed
[x] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.

**Comment by quajak** [comment]
What launch configuration are you using?
Can you check if `bin\Debug\netcoreapp2.0\cosmos\OS.bin bin\Debug\netcoreapp2.0\cosmos\OS.obj` exists?

**Comment by Automedi** [comment]
yes they both exist

**Comment by quajak** [comment]
> What launch configuration are you using?

How are you trying to launch cosmos? (Vmware, bochs, iso, etc)

**Comment by Automedi** [comment]
I use VMware Workstation 16 Player

**Comment by Automedi** [comment]
but I also used to compile to just ISO and upload it to virtual box  and it worked fine.
but after a month or so I tried to launch the sln file and the project wouldnt load anything so i created another project with cosmos c# and pressed debug but i got that error

**Comment by quajak** [comment]
Are you currently trying to launch vmware or compile to iso?

**Comment by Automedi** [comment]
currently im trying to launch with vmware

**Comment by quajak** [comment]
I dont really have any idea what is going wrong. Do you have the devkit installed, that might allow further debugging. Otherwise can you try create another kernel with a different name and check that it also happens.

**Comment by Automedi** [comment]
![Capture](https://user-images.githubusercontent.com/69730078/100377555-5c852280-3009-11eb-9424-cdabff04102e.JPG)

**Comment by Automedi** [comment]
I reinstalled everything even visual studio. Now I get this error when I try to build. I have no clue what's going on

**Comment by Automedi** [comment]
Build started...
1>------ Build started: Project: dgos, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>dgos -> C:\Users\David\Desktop\c#\dgos\dgos\bin\Debug\netcoreapp2.0\cosmos\dgos.dll
1>C:\Users\David\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets(258,9): error MSB4044: The "ExtractMapFromElfFile" task was not given a value for the required parameter "InputFile".
1>Done building project "dgos.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Automedi** [comment]
The fix to this was to go to https://github.com/CosmosOS/Cosmos/tree/00309e81bda27fe12cc73698a46c1a2cf2c589bf/source/Cosmos.Build.Tasks/tools/cygwin/win and download objdump.exe and replace the old one in cosmos user kit installation folder.
