### ISSUE TITLE
Application like games in Console

### ISSUE THREAD

**Issue by Edx09** [CosmosOS/Cosmos#1568]
So I started Programming in cosmos os a few days ago and wanted to add a game to my os , but i don´t know how to do it.
Thanks

**Comment by TFTWPhoenix** [comment]
So if you're trying to make a game for your OS you would want to:
A) Make a graphical mode for games or
B) Write a console graphics library.
You might write a console graphics library using something like this:
```
Console.backgroundColor = ConsoleColor.Blue;
Console.Write(" ");
Console.resetColor();

```

**Comment by Edx09** [comment]
Nice . Thanks for your reply , I want to do console games like in the 8 bit era when you needed to type in to start it. But when you mean that a gui was easier to make then i´ll try it.
Thanks
