### ISSUE TITLE
IL2CPU plugs do not work correctly

### ISSUE THREAD

**Issue by MishaTY** [CosmosOS/Cosmos#1574]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Plugs

#### Expected Behaviour - What do you think that should happen?
IL2CPU should replace the old code with my implementation.

#### Actual Behaviour - What unexpectedly happens?
IL2CPU is ignoring it because my function does not have extern.

#### Reproduction - How did you get this error to appear?
using the code: https://pastebin.com/RqkfR6mH
Also, I was trying to make events work.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev kit

**Comment by charlesbetros** [comment]
Plugs are only scanned from Plugs assemblies. They won't be found in your kernel.

**Comment by MishaTY** [comment]
Ok, I moved it to one of the plugs assemblies and it worked. Thanks!

**Comment by quajak** [comment]
You can add your own plug assembly. See https://github.com/CosmosOS/Cosmos/wiki/Intro-to-Plugs#custom-plug-library

**Comment by MishaTY** [comment]
Yes, thats what I did. I put the plug into InterlockedImpl.cs in Cosmos.Core_Plugs.System. Also, reran install-VS2019.bat.

**Comment by MishaTY** [comment]
Also, this is how the file looks like: https://pastebin.com/61VfyCnT
