### ISSUE TITLE
Specified .obj does not exist

### ISSUE THREAD

**Issue by JurijTSL** [CosmosOS/Cosmos#1575]
**Have you checked Github Issues for similar errors?**
Yes, i have checked this one (https://github.com/CosmosOS/Cosmos/issues/1332) and tried everything but it didn't work.

**Exception**
Assertion failed.

**VS Output Logs**
Build started...
1>------ Build started: Project: ArstotzkaOS, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>ArstotzkaOS -> D:\Dokumenti\Visual Studio Projects\ArstotzkaOS\ArstotzkaOS\bin\Debug\netcoreapp2.0\cosmos\ArstotzkaOS.dll
1>Done building project "ArstotzkaOS.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
Default cosmos project.

**Screenshots**
![image](https://user-images.githubusercontent.com/30342756/100420546-f17a3100-3086-11eb-85fb-6b050a5e2abc.png)

It happens when it tries to build it or write it to USB.

**Context**
Before posting please confirm that the following are in order
[\*] Both Cosmos VS Extensions are installed
[\*] The Cosmos NuGet packages are installed

**Comment by quajak** [comment]
So the problem is that it cant find the obj file, Can you confirm that the bin directory includes an obj file?

**Comment by JurijTSL** [comment]
It does not.

**Comment by Edx09** [comment]
Try reinstall cosmos

i had some problems too yesterday i reinstalled it and now the problems are gone 

if you dont want to loose your stuff copy your classes to your desktop

**Comment by JurijTSL** [comment]
How do I uninstall it 😅?

**Comment by JurijTSL** [comment]
Nevermind. I'll just reinstall the whole VS.

**Comment by Edx09** [comment]
you pressed on repair right?

**Comment by JurijTSL** [comment]
Nah. I won't bother with repairing. I will just reinstall it.

**Comment by Edx09** [comment]
Repairing removes all extensions ... also cosmos , but reinstalling it is good too

**Comment by Edx09** [comment]
Just have seen that you have used the bootable usb profile 
All the profiles are completly buggy ... thats why i have reinstalled cosmos .
Btw: The normal profile is the VMware

**Comment by JurijTSL** [comment]
Nope. I have reinstalled VS and Cosmos Dev Kit but it has still the same error.

**Comment by quajak** [comment]
Is there anything in the build/debug logs in VS?

**Comment by JurijTSL** [comment]
Where can I get those?

**Comment by quajak** [comment]
should automatically show up in the output window in VS

**Comment by JurijTSL** [comment]
This is when I try to compile it for USB.

```
Build started...
1>------ Build started: Project: ArstotzkaOS, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>ArstotzkaOS -> E:\Dokumenti\Visual Studio Projects\ArstotzkaOS\ArstotzkaOS\bin\Debug\netcoreapp2.0\cosmos\ArstotzkaOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: E:\Dokumenti\Visual Studio Projects\ArstotzkaOS\ArstotzkaOS\bin\Debug\netcoreapp2.0\cosmos\ArstotzkaOS.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:00:07.5300213
1>Nasm task took 00:00:08.7855081
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\netcoreapp2.0\cosmos\ArstotzkaOS.bin bin\Debug\netcoreapp2.0\cosmos\ArstotzkaOS.obj
1>LD task took 00:00:00.3085342
1>Extracting Map file...
1>Extracting Map file took 00:00:04.8589763
1>Done building project "ArstotzkaOS.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Edx09** [comment]
Just realised that you have pressed debug (run cosmos ) and not build

The build is succsesfull but vmware can´t start it 
you can flash your usb now

**Comment by JurijTSL** [comment]
Yes but how can I flash USB?

**Comment by Edx09** [comment]
You need rufus (if you have ever made a linux usb you know that tool )

Here is a tutorial : 

https://github.com/CosmosOS/Cosmos/wiki/Booting-Your-OS-from-a-USB-Drive

Just make sure that you have uncheked debug under  Cosmos(new)

Btw : Sorry for answering that late i am 12 years old and don´t have much time
