### ISSUE TITLE
Print extended ascii characters?

### ISSUE THREAD

**Issue by Edx09** [CosmosOS/Cosmos#1579]
So how do I print extended ascii characters?

**Comment by quajak** [comment]
Create your own custom PCScreenFont which includes symbols for extended ascii characters. Use https://cosmosos.github.io/api/Cosmos.System.Graphics.Fonts.PCScreenFont.html to load the font and use https://cosmosos.github.io/api/Cosmos.HAL.VGADriver.html#Cosmos_HAL_VGADriver_WriteFont_System_Byte___System_Byte_ to make VGA use it

**Comment by Edx09** [comment]
Sorry for asking for an example , but i don´t realy understand the docs

**Comment by valentinbreiz** [comment]
To print extended ascii characters you need to set a different encoding from the default one.
You can do it like this: 
```
Encoding.RegisterProvider(CosmosEncodingProvider.Instance);
Console.InputEncoding = Encoding.GetEncoding(437); //CP437 for example
Console.OutputEncoding = Encoding.GetEncoding(437);
```

**Comment by Edx09** [comment]
It has worked Thanks
