### ISSUE TITLE
How to make executable files for my OS

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1582]
Is it possible to make a file that can be executed by my OS?

For example .exe for Windows

**Comment by Edx09** [comment]
well it would be possible but first of all you would need to make an installer and make your system compile it self 

normaly Vs19 is copiing the os and making it a simple iso 

Aura did a great job with their installer : 
[https://github.com/aura-systems/Aura-Operating-System](url)

and then you would need a system which compiles the aplication

**Comment by Vardan2009** [comment]
So uhh.. what I need to do?

**Comment by Edx09** [comment]
this is only an example you need to implement the whole system with instaler and filesystem

but this topic is very complicated and it is way esier to write own programms and put them into the system.

Btw : What types of programms do you mean , Text editors , Games , etc

**Comment by Vardan2009** [comment]
Something like text editors

**Comment by Edx09** [comment]
Well then MIV would be something for you : 

[https://github.com/bartashevich/MIV/](url) 

U just need to modify it so that it works as a class

**Comment by Vardan2009** [comment]
wow, and how to use it?

**Comment by Vardan2009** [comment]
Also, I tried to do it myself
this is the result xD

![Новый проект](https://user-images.githubusercontent.com/70532109/101174109-dac27400-365c-11eb-9054-e872f9f88789.gif)

**Comment by Edx09** [comment]
Well here is a video on it : 
[`https://m.youtube.com/watch?v=fNRj-LWeTXk`](url)

**Comment by Vardan2009** [comment]
@Edx09 ok

**Comment by Edx09** [comment]
I havent used it yet but i know that it is not so complicated ;-)

**Comment by Edx09** [comment]
You put it into a class and make the main funktion public. 

When there is no main function look into the kernel and look what functions are called and create a `public static void Main()` with the functions that are called

**Comment by Vardan2009** [comment]
![a](https://user-images.githubusercontent.com/70532109/101175393-9041f700-365e-11eb-90c9-a2b0f9e1d2c3.jpg)
there's an error in Kernel.file

**Comment by Vardan2009** [comment]
Ok, It worked, Thanks!
