### ISSUE TITLE
Any Way of becoming a member of the cosmos team?

### ISSUE THREAD

**Issue by Edx09** [CosmosOS/Cosmos#1583]
Hi ,
Is there any way of becoming a member of the team ?
Like supporter or so?

**Comment by octaviousrex** [comment]
That is a good question. Do you mean like a paid supporter, where you donate annually/monthly?

**Comment by Edx09** [comment]
i maen yust a suporter which helps other people in the issues and can change the lables or idk  because recently i tried to help a lot of people , and never could change the labels etc.

**Comment by Edx09** [comment]
Like when someone isnt answeing for 2 weeks  the issue gets a pending user answer 
label

**Comment by valentinbreiz** [comment]
Becoming a team member can vary depending on the individual's involvement and the amount of work brought to the project. Since we don't have moderators, I close this issue
