### ISSUE TITLE
How to Make A Web Browser

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1584]
I Want to make a web browser in my OS...
Is it possible?
Thanks!

**Comment by zarlo** [comment]
possible: yes
very hard (right now): yes
first you will need to fix Cosmos' tcp stack
then make a http client (i would not even look at http/2 or https yet)
then a html and css parser and renderer
then is you want js you will need a js engine
and at this point you will likely find 1 thread is far to slow and you might want to work on muilt threading in Cosmos
and if you can do all this yo should feel alot of pride as that is a lot of hard work

**Comment by Vardan2009** [comment]
Can you say please, how to do it

**Comment by zarlo** [comment]
for the tcp stack i think https://github.com/aura-systems has a working one
for the rest i dont know where would be best to start

**Comment by valentinbreiz** [comment]
https://github.com/CosmosOS/Cosmos/issues/1587 duplicate

I close this. (thanks for your response @zarlo)
