### ISSUE TITLE
Method GetMBIAddress requires a plug, but none is implemented

### ISSUE THREAD

**Issue by ThomasBonomo** [CosmosOS/Cosmos#1586]
Have you checked Github Issues for similar errors? <- Yes

**Exception**
Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented	DataOS	D:\VS_Applications\DataOS\IL2CPU	1

** VS Output Logs **
1>------ Build started: Project: DataOS, Configuration: Debug Any CPU ------
1>DataOS -> D:\VS_Applications\DataOS\bin\Debug\netcoreapp2.0\cosmos\DataOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: D:\VS_Applications\DataOS\bin\Debug\netcoreapp2.0\cosmos\DataOS.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 987
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 265
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:02.3101035
1>Done building project "DataOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
No changes, just installed the newest version. (CosmosUserKit-20200708-vs2019)

**Screenshots**
![2020-12-07 00-25-13_gif](https://user-images.githubusercontent.com/54190019/101296337-2292f800-3823-11eb-8284-5e2e41e2418d.gif)

**Context**
[ ✔ ] Both Cosmos VS Extensions are installed
[ ✔ ] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.
{
    Occurred after installing the newest version of Cosmos.
    Completely removing and then reinstalling didn't help. (tried 3 times)
}

**Comment by quajak** [comment]
Its fixed in the devkit.

**Comment by ThomasBonomo** [comment]
@quajak thx :)
