### ISSUE TITLE
Would it be possible to create an html web browser, without an advanced gui, even just reading the labels?

### ISSUE THREAD

**Issue by alessiobb1** [CosmosOS/Cosmos#1587]
Hello, as you read from the title I would like to know how to create an html reader from the net. Thanks!

**Comment by Picoseconds** [comment]
You need to write a TCP stack and network drivers, and write an HTTP client. Then, you need to parse the HTML (there are pure-C# libraries for that, I personally recommend [Fizzler](https://github.com/atifaziz/Fizzler)). Finally, you can display the content of the labels in the console using Console.Write.

**Comment by alessiobb1** [comment]
Ok, tranks.. but you have a tutorial of all? or you can help me to coding?

**Comment by Picoseconds** [comment]
No.

**Comment by alessiobb1** [comment]
Don't you know a tutorial on how to do what you wrote? :(

**Comment by Picoseconds** [comment]
No such tutorial exists, because those are all isolated steps that need to be done on their own. Would you ask for a tutorial to drive to a store, buy groceries, take the groceries home, make a meal, eat it and wash the dishes?

**Comment by alessiobb1** [comment]
I understand what you mean, but I don't know how to start ...

**Comment by valentinbreiz** [comment]
TCP stack is currently removed from AuraOS but I will work on it as soon as I can.

I think this issue can be closed now, thanks @Picoseconds
