### ISSUE TITLE
Install Cosmos in correct %appdata% location

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1588]
Cosmos User Kit folder must be written in the correct %appdata% location.

For example if a user change the location of his Roaming folder, Cosmos installer will force the install path to C:\ (C:\Users\username\AppData\Roaming\Cosmos User Kit)).

**Comment by octaviousrex** [comment]
yeah, i learned this the hard way

**Comment by valentinbreiz** [comment]
@octaviousrex it is fixed now 😉
