### ISSUE TITLE
Cosmos Debug Engine extension disabled by default

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1590]
On last version of Visual Studio (16.8.3) and dotnet (5.0.101), Cosmos Debug Engine extension is disabled by default when the devkit is built. It has to be enabled again to use Cosmos Debug and access the property page of a Cosmos Kernel.

**Comment by MishaTY** [comment]
Can this issue be closed?

**Comment by quajak** [comment]
Has anyone had the same experience? I havnt heard any complaints on the github, so this could have been a one off event.
