### ISSUE TITLE
[Question] What is the current state of LINQ support in Cosmos?

### ISSUE THREAD

**Issue by Picoseconds** [CosmosOS/Cosmos#1591]
Title says it all. I want to know if basic methods such as `Select` work and if they don't, any alternatives (besides a foreach loop).

**Comment by sudopigeek** [comment]
Unfortunately, nothing in linq works right now as far as I know. However, alternatives are avaliable but it depends on what you are trying to do.

**Comment by valentinbreiz** [comment]
Linq will be supported after our work of Cosmos and IL2CPU to .NET Core 5.0
