### ISSUE TITLE
List.IndexOf not working

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1592]
#### Expected Behaviour - What do you think that should happen?
Find the index of an object in a List of objects through IndexOf

#### Actual Behaviour - What unexpectedly happens?
Just make the OS freeze, no exception

#### Reproduction - How did you get this error to appear?

Not working:

`int index = Keys.IndexOf(key);`

Working:

```
int index = 0;

foreach (var device in Keys)
{
    if (key == device)
    {
        break;
    }
    index++;
}
```

**Comment by EliaSulimanov** [comment]
Does Array.IndexOf shows the same behavior?

**Comment by MishaTY** [comment]
Cannot reproduce
