### ISSUE TITLE
List.Contains is not working

### ISSUE THREAD

**Issue by geomtech** [CosmosOS/Cosmos#1595]
#### Expected Behaviour - What do you think that should happen?
Find the index of an object in a List of objects through Contains

#### Actual Behaviour - What unexpectedly happens?
Just make the OS freeze, no exception

#### Reproduction - How did you get this error to appear?
Not working:

```csharp
return Keys.Contains(key);

```
Working:
```csharp
foreach (var device in Keys)
{
	if (k == device)
	{
		return true;
	}
}
return false;
```

**Comment by valentinbreiz** [comment]
Seems related to #1592

**Comment by MishaTY** [comment]
Cannot reproduce
