### ISSUE TITLE
Cosmos Mouse Problem

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1596]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Graphical User Interface

#### Expected Behaviour - What do you think that should happen?

draw a mouse

#### Actual Behaviour - What unexpectedly happens?

Shows This:
![Error X_X](https://user-images.githubusercontent.com/70532109/102250010-72a54500-3f1c-11eb-940a-92ec267fc7e8.png)

#### Reproduction - How did you get this error to appear?

Here's The Code:
  `void UpdateMouse()
        {
       
            Pen black = new Pen(System.Drawing.Color.Black);
          
            canvas.DrawCircle(black, Convert.ToInt32(Cosmos.System.MouseManager.X), Convert.ToInt32(Cosmos.System.MouseManager.Y), 10);

            UpdateMouse();
        }
`
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Userkit

**Comment by TheRealEli310** [comment]
This is a not an issue. Go to VM > Removable devices in VMWare and attach the mouse.

**Comment by Vardan2009** [comment]
When I'm Doing It It says:
![bandicam 2020-12-16 23-02-10-952](https://user-images.githubusercontent.com/70532109/102394212-d7cb6a00-3ff2-11eb-8946-49100996f188.jpg)

**Comment by Vardan2009** [comment]
What to do :/

**Comment by Vardan2009** [comment]
:(

**Comment by octaviousrex** [comment]
Maybe this is related to the PS2 mouse issue I saw on the Cosmos Gitter Chat (where VMware would crash because it does not support USB connected mice). What kind of mouse are you using? USB or PS2?

**Comment by Vardan2009** [comment]
USB

**Comment by octaviousrex** [comment]
> USB

![image](https://user-images.githubusercontent.com/41166588/102698240-f8b9d800-4209-11eb-92b0-cab246b3b1f1.png)

There is the thread i read about

**Comment by Vardan2009** [comment]
So, Can I fix this?

**Comment by octaviousrex** [comment]
> So, Can I fix this?

I think you can, although I don't know exactly how to do so. I don't have the dev-kit, I only have the user kit.

**Comment by Vardan2009** [comment]
I'm using userkit too

**Comment by octaviousrex** [comment]
For me personally, I halted development on my mouse, but I wouldn't give up just yet

**Comment by octaviousrex** [comment]
I will read up on how the mouse is used in cosmos, however

**Comment by octaviousrex** [comment]
https://gitter.im/CosmosOS/Cosmos
I would join this, so you can get more help on Cosmos :)

**Comment by Vardan2009** [comment]
But I think after booting on a real hardware it will work 🤔

**Comment by octaviousrex** [comment]
> But I think after booting on a real hardware it will work 🤔

i only boot it on virtual machines, because booting cosmos on your actual pc may break it.

**Comment by Vardan2009** [comment]
> > But I think after booting on a real hardware it will work 🤔
> 
> i only boot it on virtual machines, because booting cosmos on your actual pc may break it.

I already booted it and everything works fine

**Comment by octaviousrex** [comment]
Just make sure that when you boot, don't do anything with filesystems
