### ISSUE TITLE
Project not creating sucsessfully

### ISSUE THREAD

**Issue by OmegaPlusTwo** [CosmosOS/Cosmos#1597]
So I wanted to start making my own COSMOS kernel, but every time I make a project I get an error saying that a migration of the .vsproj file failed and to see the migration report for more details. I would assume that the migration report would tell me what to do but I can't actually find it.

**Comment by valentinbreiz** [comment]
What is your version of Cosmos? Userkit or Devkit? What is also your Visual Studio and dotnet version?
