### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by TheRealEli310** [CosmosOS/Cosmos#1599]
Have you checked Github Issues for similar errors?
Yes

**Exception**
See screenshots

** VS Output Logs **
Post the entire output log given by Visual Studio for the build

**To Reproduce**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/33650824/102462933-8bd5ff00-409e-11eb-9cbd-af2333527bf4.png)

**Context**
Before posting please confirm that the following are in order
[yes] Both Cosmos VS Extensions are installed
[yes] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.

**Comment by valentinbreiz** [comment]
Hello, what is your Visual Studio and dotnet version?
