### ISSUE TITLE
In builder, check all requirements and list them, not 1-by-1

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#160]

**Comment by sgetaz** [comment]
Can someone provide a description for this? It is not clear what needs to be done from the title alone

**Comment by ARMmaster17** [comment]
@sgetaz Here's what's happening with the current codebase. Let's assume that you have Visual Studio installed, but not the SDK, and you also have the installer builder installed.

1. Checking for VS: [OK]
2. Checking for VS SDK [FAIL]
STOP: tell user they are missing the VS SDK

What we want:
1. Checking for VS: [OK]
2. Checking for VS SDK: [FAIL]
3. Checking for installer builder: [OK]
STOP: tell user that they have everything except for the VS SDK.

**Comment by mterwoord** [comment]
Well kind of. What we want is to do all checks, and then get a list of all the failed ones. If you don't have Innosetup and the VS SDK, it should list those 2. Right now, it only lists the first one. You then have to fix it, and run install.bat again to see the next one.

**Comment by sgetaz** [comment]
OK, I have identified the problem. Working on it at the moment. Thanks for the help
