### ISSUE TITLE
Question : I can use VMWareSVGAII on real hardware ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1602]
Can I use VMWareSVGAII on real hardware ?
If yes, i must be modify my code or Cosmos ?
Thanks for reading

**Comment by valentinbreiz** [comment]
Hello, you have Discussions now if you want to ask questions ;)

VMWareSGVAII isn't supported by real graphic cards. If you want to use graphics and the Cosmos Graphic Subsystem on real hardware you have to write a driver for your graphic card but this is a real pain. You can also use the old VBE technology but still used by most of graphic gards, which is almost supported by Cosmos. You just have to enable it at boot time, to do it you have to rebuild Cosmos devkit with this version of IL2CPU: https://github.com/aura-systems/IL2CPU

**Comment by ArtGo-Devloppper** [comment]
Ok, thaks for your help.
I close.
