### ISSUE TITLE
Add ability to choose which instance of Visual Studio at build time

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1603]
Having multiple instances of Visual Studio installed can cause build issues saying Visual Studio Workloads are not installed and / or failed to install. Detecting if multiple versions of Visual Studio are installed and add the ability to choose which one at build time would be good.

I had the issue with these for example:
![image](https://user-images.githubusercontent.com/18724279/102919091-8276d900-4488-11eb-82e9-9189a500b980.png)

**Comment by charlesbetros** [comment]
We should remove the auto-install of workloads and just provide a message telling the user which to install

**Comment by MishaProductions** [comment]
I think this was fixed
