### ISSUE TITLE
How I can Animate ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1604]
How I can made animations in my Cosmos OS ?
If I can, with what and how ?
Thanks for you awanser #

**Comment by EliaSulimanov** [comment]
Please use the issue templates. It will make it easier for us to understand what you want to do.
For your question, Cosmos have textual user-interface. Hope it helps.

**Comment by ArtGo-Devloppper** [comment]
An textural user-interface ?

**Comment by EliaSulimanov** [comment]
Yes.

**Comment by ArtGo-Devloppper** [comment]
Ok but how i can use it ?

**Comment by valentinbreiz** [comment]
I'm sorry but I don't understand your request. If you have questions please post something more clear in [discussions](https://github.com/CosmosOS/Cosmos/discussions) ;)
