### ISSUE TITLE
Missing Plug for Interlocked.Exchange

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1606]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU
#### Expected Behaviour - What do you think that should happen?
I use Refference.Object (Asign a bitmap var with a ressource file)

#### Reproduction - How did you get this error to appear?
`ProgsImages[6] = new Bitmap(Ressources.Backgrounds.timg);`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I use User Kit 20200708

Thanks for you awanser

**Comment by quajak** [comment]
Whats the error message you are getting?

**Comment by ArtGo-Devloppper** [comment]
Just `IL2CPU Error : System.Exeption :`

**Comment by quajak** [comment]
Whats after the colon, can you please post the entire message

**Comment by charlesbetros** [comment]
A missing plug I am guessing? Cosmos doesn't support embedded resources.

**Comment by ArtGo-Devloppper** [comment]
> Whats after the colon, can you please post the entire message

No, I can’t because the message is just `IL2CPU Error : System.Exeption : `

**Comment by quajak** [comment]
Please post the entire log from VS output. I doubt that no further information about the exception is insluded in the log.

**Comment by ArtGo-Devloppper** [comment]
The vs output si thé cosmos debugger ?

**Comment by quajak** [comment]
VS has an output window which should either in the debug/build log have more information about the build. The Cosmos debugger does not play a role here.

**Comment by ArtGo-Devloppper** [comment]
This ?
`L'opération de génération a démarré...
1>------ Début de la génération : Projet : ArtOS, Configuration : Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: La version cible de .NET Framework ('netcoreapp2.0') n'est pas prise en charge et ne recevra pas les mises à jour de sécurité. Consultez https://aka.ms/dotnet-core-support pour plus d'informations sur la stratégie de support.
1>ArtOS -> C:\Users\USERNAME\Documents\GitHub\ArtOS (Computers)\ArtOS (Computers)\bin\Debug\netcoreapp2.0\cosmos\ArtOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\USERNAME\Documents\GitHub\ArtOS (Computers)\ArtOS (Computers)\bin\Debug\netcoreapp2.0\cosmos\ArtOS.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Int64  System.Threading.Interlocked.Exchange(&System.Int64, System.Int64).
1>  Called from :
1>System.IO.UnmanagedMemoryStream::Int32 Read(Byte[], Int32, Int32)
1>System.IO.Stream::Int32 Read(Byte[], Int32, Int32)
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:00.9896622
1>Génération du projet "ArtOS.csproj" terminée -- ÉCHEC.
========== Génération : 0 a réussi, 1 a échoué, 0 à jour, 0 a été ignoré ==========
`

**Comment by quajak** [comment]
The plug for `System.Int64 System.Threading.Interlocked.Exchange(&System.Int64, System.Int64)` is missing which is being used by `System.IO.Stream::Int32 Read(Byte[], Int32, Int32)`. You either dont use that method or impement that plug.

**Comment by quajak** [comment]
Closed by https://github.com/CosmosOS/Cosmos/pull/1641

**Comment by ArtGo-Devloppper** [comment]
Hello, after compiling the new vertion of Cosmos, i implemented the plug and try my code, but the error is still here.
Did I do something wrong or the plug does not work?

**Comment by charlesbetros** [comment]
The Interlocked plugs are fine. There is more work required to make something like this work.

Remember, we aren't executing the OS assembly, so there is no Embedded Resource when the OS is running.

We have ManifestResourceAttribute which does what you want.It takes an embedded resource and stored the bytes in your OS as a static.

**Comment by ArtGo-Devloppper** [comment]
ManifestResourceAttribute ?
