### ISSUE TITLE
What is SYSLINUX I saw on boot

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1609]
What is SYSLINUX I saw on booting of my os
![IMG_20201226_191436.jpg](https://user-images.githubusercontent.com/70532109/103154079-b3b81780-47ae-11eb-8cb7-072b790fbfd4.jpg)

**Comment by GDEngine** [comment]
if you have read https://github.com/CosmosOS/Cosmos/wiki/Develop-Your-Own-Operating-System-in-C%23-or-VB.NET you would know. says at the very end

**Comment by GDEngine** [comment]
![image](https://user-images.githubusercontent.com/66632141/103155707-1dfd9780-4770-11eb-9ff3-ae366f67302a.png)

**Comment by Vardan2009** [comment]
Thanks ☺️
