### ISSUE TITLE
Devkit install error

### ISSUE THREAD

**Issue by StringOS** [CosmosOS/Cosmos#1612]
**Describe the problem**
I get the error attached below when running install-VS2019.bat

**Steps of installation up to now**
Followed the instructions to build the devkit up to running install-VS2019.bat

**Expected behavior**
It to work

**Logs**
Windows cannot find 'source\Cosmos.Build.Builder\bin\Debug\Cosmos.Build.Builder.exe'. Make sure you typed the name correctly, and then try again.

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) >>> Devkit
 - Are you using an admin account? >>> Yes (but not an admin cmd, it doesn't work either way)
 - VS Version if applicable >>> Community 2019

**Additional context**
![image](https://user-images.githubusercontent.com/73358272/103241618-aab07d00-494b-11eb-992f-f2a6217c0ee4.png)

**Comment by quajak** [comment]
You have a problem with your .net setup on the computer. The actual error message is the line in red `The SDK Microsoft.NET.Sdk specified could not be found` See https://stackoverflow.com/questions/46257393/msbuild-throws-error-the-sdk-microsoft-net-sdk-specified-could-not-be-found or google for a solution

**Comment by StringOS** [comment]
Turns out there was a missing enviroment variable that points to the SDK. Thanks
