### ISSUE TITLE
What do i put into the Run Main Kernel Loop to make the Mouse render

### ISSUE THREAD

**Issue by octaviousrex** [CosmosOS/Cosmos#1613]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI (Mouse).

#### Expected Behavior - What do you think that should happen?
Mouse will render on the screen.

#### Actual Behavior - What unexpectedly happens?
The mouse does not display.

#### Reproduction - How did you get this error to appear?
Follow what the tutorial i followed did.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit

I was following these following tutorials: https://github.com/CosmosOS/Cosmos/wiki/Non-Flickering-Canvas-GUI-Tutorial
and https://github.com/CosmosOS/Cosmos/wiki/Adding-a-mouse-to-our-Non-Flickering-Canvas-GUI.
When i boot up my OS, the mouse does not render. I beleive this is due to the fact that i do not know hat to put in the Run loop

https://user-images.githubusercontent.com/41166588/103316910-eef95700-49f7-11eb-8529-3afcbc5b8cbc.mp4

**Comment by octaviousrex** [comment]
It is supposed to boot up to the blue background, btw

**Comment by quajak** [comment]
This is not something which should be addressed in an issue. Can you please ask your questions in Discussions?
