### ISSUE TITLE
IL2CPU exception on boolean

### ISSUE THREAD

**Issue by Shadowblitz16** [CosmosOS/Cosmos#1617]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I am trying to execute commands in a dictionary

#### Expected Behaviour - What do you think that should happen?
I expected it to run

#### Actual Behaviour - What unexpectedly happens?
gives System.Exception IL2CPU

#### Reproduction - How did you get this error to appear?
using this code...
```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace Os95.Commands
{
    public abstract class Command
    {

        string         _id;
        CommandManager _manager;

        public string          GetID() => _id;
        public abstract string GetDesc();
        public abstract void   Execute(string[] args);

        protected CommandManager Manager => _manager;

        public Command(CommandManager manager, string id)
        {
            _id      = id;
            _manager = manager;
        }
    }

    public class CommandManager : IEnumerable<Command>
    {
        Dictionary<string, Command> commands = new Dictionary<string, Command>();

        public void Execute(string command)
        {
            var str = command.Split(' ');
            var id = str[0].ToUpper();

            if (commands.ContainsKey(id))
            {
                var args = new string[str.Length - 2];
                Array.Copy(str, 1, args, 0, args.Length);
   
                commands[id].Execute(args);
            }
            else
            {
                Console.WriteLine("Command " + id + " does not exist. Type HELP for more info");
            }
        }


        public  void Register<T>(string id) where T : Command
        {
            id = id.ToUpper();
            commands.Add(id, (T)Activator.CreateInstance(typeof(T), this, id));
        }

        public IEnumerator<Command> GetEnumerator()
        {
            return commands.Values.GetEnumerator();
        }


        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
```

```cs
using System;
using System.Collections.Generic;
using System.Text;

namespace Os95.Commands
{
    public class CommandHelp : Command
    {
        public CommandHelp(CommandManager manager, string id) : base(manager, id) { }

        public override void   Execute(string[] args)
        {
            if (args.Length > 0)
            {
                Console.WriteLine(GetID() + " takes 0 arguments.");
            }

            foreach (var cmd in Manager)
            {
                Console.WriteLine(cmd.GetID() + " - " + cmd.GetDesc());
            }
        }
        public override string GetDesc()
        {
            return "Shows a list of commands.";
        }
    }
}

```
```cs
using Os95.Commands;
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Os95
{
    public class Kernel : Sys.Kernel
    {
        CommandManager CommandManager = new CommandManager();

        protected override void BeforeRun()
        {
            CommandManager.Register<CommandHelp>("help");
            Console.WriteLine("Os95 booted successfully. Type help to get a list of commands.");
        }

        protected override void Run()
        {
            Console.Write(">");
            CommandManager.Execute(Console.ReadLine());
        }
    }
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using CosmosUserKit-20200708-vs2019

**Comment by zarlo** [comment]
i would need the full build log but its most likely IEnumerator none of that as been pluged as some uses native code

**Comment by Shadowblitz16** [comment]
not sure where to find the full build log but here is the one from the output in visual studio...```
1>------ Build started: Project: Os95, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>Os95 -> C:\Users\Shadowblitz16\Documents\Projects\Cs\Os95\Os95\bin\Debug\netcoreapp2.0\cosmos\Os95.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Shadowblitz16\Documents\Projects\Cs\Os95\Os95\bin\Debug\netcoreapp2.0\cosmos\Os95.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Boolean  System.RuntimeTypeHandle.IsComObject(System.RuntimeType, System.Boolean).
1>  Called from :
1>System.RuntimeType::Boolean IsGenericCOMObjectImpl()
1>System.RuntimeType::System.Object CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
1>System.Activator::System.Object CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
1>System.Activator::System.Object CreateInstance(System.Type, System.Object[])
1>Os95.Commands.CommandManager::Void Register[CommandHelp](System.String)
1>Os95.Kernel::Void BeforeRun()
1>Cosmos.System.Kernel::Void BeforeRun()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:11.3574096
1>Done building project "Os95.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========```

**Comment by Shadowblitz16** [comment]
oh nvm I see " DO NOT REPORT THIS AS A BUG."

**Comment by Shadowblitz16** [comment]
reopening this as a question

**Comment by Shadowblitz16** [comment]
is there a way to implement the required plug?
I read the main plug page and I still don't see how this can be done on base types
