### ISSUE TITLE
QUESTION : How to add proprely a file in the VM Drive ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1621]
I want to add a file in my VM drive but i use ImDisk to mount the drive, only the app is buged and the file isn't add proprely.
Do you have a application for mount a vm Drive ?
Thanks for your awanser !

**Comment by TFTWPhoenix** [comment]
Hi! You need to mount the a Virtual drive in VMWare but this requires workstation pro. If you have this you can go into the Virtual Machine settings, click on your drive, and press Map Virtual Disk. Make sure its writable. After doing this you can edit the files like it is a flash drive.

**Comment by ArtGo-Devloppper** [comment]
Ok thanks, but Cosmos mount automaticaly the drive ?

**Comment by TFTWPhoenix** [comment]
[OSFMount](https://www.osforensics.com/tools/mount-disk-images.html) is probably your best bet for mounting using an external program. However I would still recommend using Workstation Pro whenever possible.

**Comment by ArtGo-Devloppper** [comment]
Yes, but OSFMount can’t write on a VMDK disk.
VirtualBox can mount drive ?

**Comment by TFTWPhoenix** [comment]
I do not believe VirtualBox can mount and if OSFMount can't write, I'm out of ideas.

**Comment by ArtGo-Devloppper** [comment]
Thanks, i close
