### ISSUE TITLE
Visual Studio Workloads not found. Install .NET Core cross-platform development, Visual Studio Extension development

### ISSUE THREAD

**Issue by emanueleriboldi** [CosmosOS/Cosmos#1626]
========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads not found. Install .NET Core cross-platform development, Visual Studio Extension development, 

========================================
    Error
========================================

Visual Studio Workloads not found.

But i installed .NET Core cross-platform development,.NET Core dev kit 
![Immagine 2021-01-07 075600](https://user-images.githubusercontent.com/63238570/103861589-f686c300-50bd-11eb-8257-c75d90272ded.png)

![Immagine 2021-01-07 075633](https://user-images.githubusercontent.com/63238570/103861593-f7b7f000-50bd-11eb-9575-3cc956cd8f55.png)

and Visual Studio Extension development!

**Comment by quajak** [comment]
This seems to be connected to https://github.com/CosmosOS/Cosmos/issues/1603 in that, we as soon as multiple vs installations the check breaks. If you are installing the devkit, the easiest way would be to simply disable to check in the local installation, for an actual fix, the two solutions I can think of are 1) detect if there is more than 1 vs installation, disable check but warn user or 2) always warn the user if the check did not succeed but let the installation continue, even if they arnt installed, as it will break at some later point.

**Comment by jp2masa** [comment]
Maybe the check for multiple VS instances is not working, it should show a dialog to select the target instance:

https://github.com/CosmosOS/Cosmos/blob/86dfa0879f882e6a9c09557ad080cb8a694d6961/source/Cosmos.Build.Builder/App.xaml.cs#L56-L76

**Comment by PythonVbaUser** [comment]
> 
> 
> This seems to be connected to #1603 in that, we as soon as multiple vs installations the check breaks. If you are installing the devkit, the easiest way would be to simply disable to check in the local installation, for an actual fix, the two solutions I can think of are 1) detect if there is more than 1 vs installation, disable check but warn user or 2) always warn the user if the check did not succeed but let the installation continue, even if they arnt installed, as it will break at some later point.

Of course! I had 2 visual studio! Thanks very much, now is working!

**Comment by quajak** [comment]
This issue should stay open until we fix the underlying issue. 

> Maybe the check for multiple VS instances is not working, it should show a dialog to select the target instance:
> 
> https://github.com/CosmosOS/Cosmos/blob/86dfa0879f882e6a9c09557ad080cb8a694d6961/source/Cosmos.Build.Builder/App.xaml.cs#L56-L76

Thanks, that seems the likely culprit.

**Comment by PythonVbaUser** [comment]
> 
> 
> This issue should stay open until we fix the underlying issue.
> 
> > Maybe the check for multiple VS instances is not working, it should show a dialog to select the target instance:
> > https://github.com/CosmosOS/Cosmos/blob/86dfa0879f882e6a9c09557ad080cb8a694d6961/source/Cosmos.Build.Builder/App.xaml.cs#L56-L76
> 
> Thanks, that seems the likely culprit.

Ok
