### ISSUE TITLE
Exception: System.Exception: Error compiling method 'SystemVoidCosmosCore_AsmDelegateImplInvoke': System.Exception: Events with return type not yet supported!

### ISSUE THREAD

**Issue by tarithj** [CosmosOS/Cosmos#1629]
When I build my project I get this error
```
Exception: System.Exception: Error compiling method 'SystemVoidCosmosCore_AsmDelegateImplInvoke': System.Exception: Events with return type not yet supported!
```
what does it mean

**Comment by quajak** [comment]
Only delegates which dont return anything are supported. So `Action` works but `Func` does not.
If you post your code, I can highlight where you are doing something which is currently not supported.

**Comment by tarithj** [comment]
https://1drv.ms/u/s!AnTeQHe84KKpgTmYbRkbbNLdvaJL?e=q9aWSQ

**Comment by tarithj** [comment]
is there any workaround

**Comment by quajak** [comment]
Can you please post the code somewhere publically accessible without requirement for an acount?
A workaround could be to not return the value directly but rather store it in some object which is not passed directly.

**Comment by tarithj** [comment]
> Can you please post the code somewhere publically accessible without requirement for an acount?
Sorry about that here's a dropbox link: https://www.dropbox.com/s/m30u0qig3e7jh7e/mag.zip?dl=0

**Comment by tarithj** [comment]
Sorry about that, I just noticed that you can upload files in gihub
[mag.zip](https://github.com/CosmosOS/Cosmos/files/5787217/mag.zip)

**Comment by quajak** [comment]
In your case I think the best approach would be a purely object orientated approach to only work with objects representating the commands and factories which produce them (I think the `Func<CommandHandler>` should be easily replaced with a `CommandFactory`). For further discussion on workarounds/design principles please open a thread on discussions.

**Comment by Barshan-Mandal** [comment]
please implement it as soon as you can
