### ISSUE TITLE
DriveInfo not working | Null exception

### ISSUE THREAD

**Issue by PythonVbaUser** [CosmosOS/Cosmos#1632]
Have you checked Github Issues for similar errors?
yes
**Exception**
Null exception

** VS Output Logs **

**To Reproduce**
nothing

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[yes ] Both Cosmos VS Extensions are installed
[yes ] The Cosmos nuget packages are installed

Hello, I want to insert into an array list all drives label.. but is throwing an error.

Code:             
```

var drives = DriveInfo.GetDrives();


foreach (DriveInfo info in drives)
            {
                drivers.Add(info.VolumeLabel.ToString());
            }
```

**Comment by MishaTY** [comment]
Have you initialized the file system? You can do that by calling: 
```
CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```
That's needed for the File System stuff to work.

**Comment by PythonVbaUser** [comment]
> 
> 
> Have you initialized the file system? You can do that by calling:
> 
> ```
> CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
> Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
> ```
> 
> That's needed for the File System stuff to work.

YOu're right, I haven't initialized the file system. Thanks. Have a good night!

**Comment by MishaTY** [comment]
Your welcome
