### ISSUE TITLE
[Question] 3D support ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1636]
Hello, i want to use 3D in cosmos but cosmos support 3D ?

**Comment by zarlo** [comment]
out of the box not but it can be done you will need to make your own 3d graphics library

**Comment by ArtGo-Devloppper** [comment]
Ok, but if i want to make my own lib, how i can make geometrical forms (like a circle or a round rectangle) ?

**Comment by quajak** [comment]
These kind of questions should go into discussions, for follow up discussion please start a thread there. There should be tutorials for creating your own 3d graphics library in general. Dont expect any good performance without adding specific driver support.
