### ISSUE TITLE
Add method to draw arc

### ISSUE THREAD

**Issue by quajak** [CosmosOS/Cosmos#1639]
Thanks to the discussion https://github.com/CosmosOS/Cosmos/discussions/1638, I noticed that a method to draw an arc between two points is currently missing from canvas and should be added(the algorithm should be very similar to how we draw circles or ellipses).

**Comment by juliusfriedman** [comment]
Wonder how much effort it would be to just support Geometry en general.

**Comment by quajak** [comment]
What further methods do you think would be helpful?

**Comment by juliusfriedman** [comment]
I sent you an invitation, honestly I am not sure. I see many things in Cosmos which are `existential`

**Comment by quajak** [comment]
Thanks for the invitation, I dont fully understand how it would help/work with Cosmos.

**Comment by juliusfriedman** [comment]
Well I figure once you have some shape you could save it as WKT perhaps or SVG instead of BMP..

Perhaps for CNC Machines / GCODE

Never mind.

**Comment by AcaiBerii** [comment]
You can use pi and fill in rectangles of a 1x1 size in the shape of a circle.  
Two things I wouldn't know how to do, though, would be to find the locations of where you should fill in the rectangles and how to cut it in half without overlaying content.  
If you can make an svg renderer though it would make it much easier.

**Comment by quajak** [comment]
Resolved by #2421
