### ISSUE TITLE
Canvas.DrawImage is slow

### ISSUE THREAD

**Issue by ArtOS-Developper** [CosmosOS/Cosmos#1640]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI

#### Expected Behaviour - What do you think that should happen?
Canvas.DrawImage() is very slow

#### Actual Behaviour - What unexpectedly happens?
Image drawing is very slow

#### Reproduction - How did you get this error to appear?
use Canvas.DrawImage();

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
The laset version

Hello!
Canvas.DrawImage is slow (line by line loading), how i can made faster ?
(The image : https://raw.githubusercontent.com/ArtGo-Devloppper/ArtOS-Bootable/master/yosemitefull.bmp)

**Comment by quajak** [comment]
I assume you are using VMWare, on VBE we already have a more optimised version which copies the memory in lines. The best speed up for VMWare would be to also add an implementation to SVGACanvas/Driver which draws lines of image at once by copying between the memory locations directly.

**Comment by ArtGo-Devloppper** [comment]
Okay, but how i can made this ?

**Comment by quajak** [comment]
The best way would be to use the `MemoryOperations.Fill`

**Comment by quajak** [comment]
This should be fixed in the devkit #1959

**Comment by ascpixi** [comment]
@quajak feel like this can be closed now ^^'>
