### ISSUE TITLE
The master boot record (MBR) on this virtual machine's hard disk does not contain valid bootstrap code

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1643]
#### Area of Cosmos - What area of Cosmos are we dealing with?
VMWare

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I use the lasted sources [(This)](https://github.com/CosmosOS/Cosmos/commit/5457d051340435e1d17f01ed00ed18ab080c33b9)

#### The error : 
The master boot record (MBR) on this virtual machine's hard disk does not contain valid bootstrap code. MBR corruption is usually the result of a failure while installing the guest operating system. The virtual machine will power off when you click OK.

How i can fix it ?

**Comment by quajak** [comment]
Can you disable debugging in the kernel and upload the asm file if it keeps on happening?
