### ISSUE TITLE
Http, Rtp, Rtsp, Sip etc

### ISSUE THREAD

**Issue by juliusfriedman** [CosmosOS/Cosmos#1645]
Wondering you level of intent to support such protocols.

https://github.com/juliusfriedman/net7mma_core/ (That was not an advertisement)

Think about WASM support it will give you a lot of options... (running wasm not necessarily running on it)

Thank you for your time and your Operating System / Compiler!

**Comment by quajak** [comment]
This kind of question is meant for discussion and not issues. Could you please open it there, since it seems very interesting? Does the net7mma_core run on cosmos?

**Comment by juliusfriedman** [comment]
Yes it should and sorry. No further discussion is needed at this time unless you deem it so.
