### ISSUE TITLE
Refinement

### ISSUE THREAD

**Issue by juliusfriedman** [CosmosOS/Cosmos#1646]
Nice work so far!

Please refine the offering here such that there are clean and concise packages.

E.g. 
Compiler => Comos.Compiler (Only allows using IL2CPU for whatever purpose e.g. to make a java frontend for CIL)
-Example compilers- (Baroke, a C# IL2CPU Compiler, inter alia) useful for compiling or potentially executing programs (depending on if you use coff/elf etc)
Operating System Libraries / Runtime => Cosmos.Core (Systems stuff, memcmp, memmove etc, Port definitions et al) Possible segment into Cosmos.HardwareAbstractionLayer etc
-Builder-? (Allows one to build a CosmosOS using a Gui, Console, web etc)
Full Operating System => CosmosOS
Features / PlugIns / Packages => Basic UI / Console other such thingz (Cosmos.Console, Cosmos.Forms etc [Ring security])

**Comment by quajak** [comment]
I am happy to disucss this but these kind of questions should be in discussions, not issues.

**Comment by juliusfriedman** [comment]
I apologize.
