### ISSUE TITLE
Where I Can See The Output of mDebugger

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1655]
When I Write   mDebugger.Send("X: "+x);  Where I Can See The Output?

**Comment by quajak** [comment]
It should be visible in the VS output window in the debug tab along with other messages from Cosmos. If not, try adding `#define COSMSODEBUG` to the file which contains the send.

In future, please ask these kind of questions in discussions.

**Comment by Vardan2009** [comment]
Thanks!
