### ISSUE TITLE
How To Make Button?

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1656]
#### Area of Cosmos - What area of Cosmos are we dealing with?

GUI.

Here's The Code
if (Sys.MouseManager.MouseState == Sys.MouseState.Left) 
{
                canvas.DrawFilledRectangle(blue, 50, 40, 70, 60);
            }
            else
            {
                canvas.DrawFilledRectangle(white, 50, 40, 70, 60);
            }

But how do I check when the mouse is within the button

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Cosmos User Kit 20200708 vs2019

**Comment by MishaTY** [comment]
You can take a look at how I do it: [https://github.com/MishaTY/Misha-OS/blob/master/Misha-OS/Gui/Windows/Controls/Button.cs](link)

**Comment by Vardan2009** [comment]
Thanks A Lot! 😍😎

**Comment by taha-taheri-2020** [comment]
سلام علیکم
