### ISSUE TITLE
Devkit stuck at installing dependencies?

### ISSUE THREAD

**Issue by Luky1234567890** [CosmosOS/Cosmos#1657]
**Describe the problem**
So, I tried installing the devkit and everything went fine until it said that some repos were missing (IL2CPU, X# and Common) so it wanted to install them. I pressed OK and it's installing, just for a very long time. If I cancel it, it just stops everything but if I let it be, it just says installing forever.

**Steps of installation up to now**
Download devkit, launch install-VS2019.bat, wait until it launches the GUI, press OK on dialog "Repos: IL2CPU, XSharp and Common is a dependency, but it was not found! It will be installed now."

**Expected behavior**
Install the dependencies and continue with the installation.

**Logs**
I cloudn't find any logs other than the small one when you cancel the installation:
System.Exception: Dependency installation failed! Dependency name: Repos: IL2CPU, XSharp and Common

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) devkit
 - Are you using an admin account? yes
 - VS Version if applicable VS2019

**Additional context**
I waited one hour before doing something, so I cloud try waiting longer but wasn't sure if it wasn't stuck.

**Comment by quajak** [comment]
If its unable to download the dependencies automatically, try downloading the repos yourself.

**Comment by Luky1234567890** [comment]
And where should I place them?

**Comment by Luky1234567890** [comment]
> 
> 
> If its unable to download the dependencies automatically, try downloading the repos yourself.

And where should I place them? Does it search the computer for them or do I have to place them in a specific folder?

**Comment by quajak** [comment]
Read https://www.gocosmos.org/docs/install/. They should all share the same parent directory with the Cosmos directory.

**Comment by Luky1234567890** [comment]
It works now. Thanks!
