### ISSUE TITLE
When I tried to install the userkit from the .bat file it threw an error on the build log....

### ISSUE THREAD

**Issue by elkaamee326** [CosmosOS/Cosmos#1658]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Nasm, with loading large byte arrays.

#### Expected Behaviour - What do you think that should happen?
It should load it and parse it with no errors.

#### Actual Behaviour - What unexpectedly happens?
When I tried to use a byte array full of values, in 1 line ie: `byte[] myFile { ... };`, and when it reaches a certain limit, Visual Studio becomes very slow, and when I attempt to compile the project, nasm threw me with an error saying `Nasm: Interminable Macro Recursion`. Is it possible to resolve this error? Has it already been resolved in a newer version of Nasm, and would I just download that version of Nasm and put it in the Tools->NAsm folder??? 

#### Reproduction - How did you get this error to appear?
When I tried to load a big byte array.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)
The latest UserKit.

Is there anyway, to fix this problem?
Thank you :)

**Comment by nifanfa** [comment]
split them

**Comment by elkaamee326** [comment]
I am trying to play Sound from #1653. Also, the error won't go away if I make that byte array one line of code, or kind of change it, it will still say interminable macro recursion, because Nasm is saying the file is too big / kernel. And it would be two hard to play splitted buffers of those bytes. Would I have to use a different version of Nasm? It isn't the file or the audio, everything worked perfectly fine, the only thing was Nasm, prevented me from playing a huge byte array. Is there any implementation / build of Nasm that resolved this error? Thank you.

**Comment by elkaamee326** [comment]
Is there anything I can do?

**Comment by nifanfa** [comment]
![QQ截图20210201191456](https://user-images.githubusercontent.com/54205437/106451654-d3371400-64c1-11eb-8fd5-1907a5650253.png)

**Comment by nifanfa** [comment]
just split them into multi-part

**Comment by nifanfa** [comment]
and each part shouldn't larger than 32kb maybe lesser

**Comment by nifanfa** [comment]
convert the bytes into base64 in windows

**Comment by elkaamee326** [comment]
I resolved the interminable macro recursion by replacing nasm with another build of it, but now when I play from the giant byte array (it would take forever to split a bunch of lines of it since the entire array is around 256,000,000 lines of code), it stops at about 8 seconds of the sound track I was playing. Would I go in and modify the value of the 64k buffer, so that it can play from larger arrays? Or would I need to modify something else? Thank you.

**Comment by elkaamee326** [comment]
Or the value of bufferinmem (Memory block), would this work instead? Thank you.

**Comment by elkaamee326** [comment]
What would I need to modify, because the higher I set the buffer, the less the sound track played, so should I set it lower? What should I do, so that it plays more of the soundtrack?

**Comment by MishaTY** [comment]
Right now, It cannot play files larger than 64 kb because the IRQs are not working. Once I fix them, it would be able to play files larger then 64 KB.

**Comment by elkaamee326** [comment]
Okay, thx.

**Comment by elkaamee326** [comment]
Also, when the IRQ implementation is complete and stable, how would I use the irq and make it fire / execute. So that it would be able to play larger files? Thx.

**Comment by MishaTY** [comment]
The driver will handle the IRQ.

**Comment by elkaamee326** [comment]
Okay, thx.

**Comment by elkaamee326** [comment]
In the article Sound.md, it said that the dev kit was required to run the code correctly. When I tried to install the latest userkit.bat, (I updated that cloned source with all the latest sound features), it gave me this error. Also, when I tried to install the dev kit, I would get this error:

![image](https://user-images.githubusercontent.com/69808082/107106777-46f75a80-67fb-11eb-9cda-c00bd8f0b3e9.png)

I have everything installed? What could've been the cause for the userkit build to halt and produce an error, and as well as the dev kit? I followed all the required instructions to install the COSMOS dev kit, from the gocosmos.org website, and I would just receive this error? What does this error mean? Thank you :)

**Comment by MishaTY** [comment]
Look at this issue: #1100

**Comment by elkaamee326** [comment]
Thx, it installed successfully, and after that the kit builder window closed. So, now do I just run the Cosmos.iss file in setup (This was my first sucessful build when building the kit)? Do run the iss script? Thx for your help :)

**Comment by elkaamee326** [comment]
![image](https://user-images.githubusercontent.com/69808082/107121366-fcf49000-685f-11eb-9ce7-a6bbc08377b4.png)

**Comment by elkaamee326** [comment]
I just opened this manually.

**Comment by elkaamee326** [comment]
Oh.... I was just supposed to open the userkit output in the setup folder, thx.
