### ISSUE TITLE
MemoryBlock.Copy() freeze the system

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1659]
![GIF 2021-2-1 4-01-40](https://user-images.githubusercontent.com/54205437/106396413-bdced500-6442-11eb-95f4-bb84cbc00555.gif)  
![QQ截图20210201040549](https://user-images.githubusercontent.com/54205437/106396430-caebc400-6442-11eb-9873-9c7ee6a5b811.png)

**Comment by nifanfa** [comment]
This is the hardest problem that prevent the further development

**Comment by nifanfa** [comment]
I can sure that the system stuck is because the videoDriver.Video_Memory.Copy(mainGraphics.memory); because i tried to write log while execute every method. and i viewed the log.

**Comment by elkaamee326** [comment]
Could you put a try and catch block, and write a statement to your log so that it could be easier to find out what is causing the problem?

**Comment by MishaTY** [comment]
This is an issue with the memory manager, that the system runs out of memory and freezes the system.

**Comment by elkaamee326** [comment]
So, (just asking out of curiosity) would a solution to that be to increase the amount of installed ram? Or will that be reserved for "free space?" Or is it a video ram issue?

**Comment by MishaTY** [comment]
Yes, a temporary solution is too increase the amount ram, that helped me.

**Comment by nifanfa** [comment]
> Could you put a try and catch block, and write a statement to your log so that it could be easier to find out what is causing the problem?

Try Catch won't work at all.

**Comment by nifanfa** [comment]
> Yes, a temporary solution is too increase the amount ram, that helped me.

No. how many ram you increased it will crash at last.

**Comment by nifanfa** [comment]
https://github.com/nifanfa/CosmosKernel1

> So, (just asking out of curiosity) would a solution to that be to increase the amount of installed ram? Or will that be reserved for "free space?" Or is it a video ram issue? Edit: (Question) How can you increase Video RAM on VMware?

**Comment by nifanfa** [comment]
#1844
