### ISSUE TITLE
Add CosmosOS Nuget Package

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/Cosmos#1660]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installation

#### Expected Behaviour - What do you think that should happen?
Install CosmosOS From Nuget Package Manger With One Click.

#### Actual Behaviour - What unexpectedly happens?
There Is No CosmosOS Nuget package

**Comment by zarlo** [comment]
you need to select the local cosmos repo and not the nuget one

**Comment by ilobilo** [comment]
Thanks!
