### ISSUE TITLE
Deleting file and directory not working

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1665]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File system

#### Expected Behaviour - What do you think that should happen?
I should be able to delete files and directories when I want.

#### Actual Behaviour - What unexpectedly happens?
I can only delete files and directories after I created them, after I close VMware and I re-open it (via the Start button in VS 2019) I can't delete them anymore. **However this only seems to happen to folders and files I create, as I was able to delete the directory TEST, though it got created automatically.**

#### Reproduction - How did you get this error to appear?
Initialize a CosmosVFS, then create a file or directory, close and open VMware again (from VS 2019 via the Start button, or F5) and try to delete the file or directory you've created.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit (20200708)

**Comment by quajak** [comment]
Can the files still be found in the filesystem?

**Comment by AnErrupTion** [comment]
I think so

**Comment by quajak** [comment]
So reading the files works but deleting does not?

**Comment by AnErrupTion** [comment]
If I remember correctly yes. This is old so I don't remember exactly but in my memories I could read files but not write or delete them.

**Comment by AnErrupTion** [comment]
I'm closing this since it's most likely a duplicate of other issues.
