### ISSUE TITLE
How to add to filesystem

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1666]
How to add images,f iles, e.t.c to filesystem?

Please help

Thanks 😊

**Comment by elkaamee326** [comment]
All you need to do is go on VMware Work Station Player and find the Cosmos Virtual Machine and click on virtual machine settings. After that, you go to where the hard disk and the file system setting so are, and you click the button Map Virtual is, and you uncheck the readonly box and hit enter. After that a new window in FileExplorer Should open and you should see the new file system called COSMOS in a new window, along with other folders too. After that, to add images you just take the image and copy it to the COSMOS drive and close the window.

**Comment by Vardan2009** [comment]
![Capture](https://user-images.githubusercontent.com/70532109/107614847-85aa6c00-6c64-11eb-93fc-fa10b8b878aa.PNG)
I Cant Map The Virtual Disk

**Comment by elkaamee326** [comment]
Are you using VMware Workstation 15 Player or VMware Workstation Pro? Because Cosmos does not deploy your OS on the pro version, it uses the Player for deployment, maybe that could be the cause of your problem.

**Comment by Vardan2009** [comment]
I'm Using VMWare Workstation 16 Player

**Comment by elkaamee326** [comment]
I think the reason why the map button is disabled is because I think the VM cannot find the `Filesystem.vmdk` file. If it can't, then you have a problem, so can you confirm that the COSMOS Filesystem and the Filesystem.vmdk file works fine on that version of VMware? Also, can you debug fine with COSMOS? When your project is done building, does VMware Open up, or do you just receive an error when you attempt to debug the project?

**Comment by TFTWPhoenix** [comment]
Mapping a .vmdk in VMWare requires workstation pro.

**Comment by Vardan2009** [comment]
Ok.. I Installed VMware workstation 16 pro
Now When I Click Map
![Screenshot 2021-02-19 111129](https://user-images.githubusercontent.com/70532109/108470324-3d61fe00-72a3-11eb-88d6-a1233e43f692.png)
It Shows This... What To do next?

**Comment by Vardan2009** [comment]
Oh It Worked... THANKS!!!!!!!!!!!!!!!!!!!!!!!!! SO MUCH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Vardan2009** [comment]
thaAAANKS
