### ISSUE TITLE
Visualstudio don't find Cosmos

### ISSUE THREAD

**Issue by alessiobb1** [CosmosOS/Cosmos#1667]
I reistalled Windows, and after instal VisualStudio 2019 Community, VMWARE and Cosmos UserKit, If open a my old ploject, Visualstudio don't find cosmos, and question to me where is it the executible. Tranks for help.

**Comment by quajak** [comment]
That most likely means that Cosmos wasnt actually sucessfully installed. Can you find the two Cosmos extensions in VS?

**Comment by alessiobb1** [comment]
I resolved two days ago, i forgot to install the Microsoft Framework SDK. Sorry i forgot to avvise you(this you is plural).
