### ISSUE TITLE
OS Not loading

### ISSUE THREAD

**Issue by theopcoder** [CosmosOS/Cosmos#1668]
#### Area of Cosmos - What area of Cosmos are we dealing with?
VMWare

#### Expected Behaviour - What do you think that should happen?
It should load to the os

#### Actual Behaviour - What unexpectedly happens?
VMWare opens up then says No files found! Boot:

#### Reproduction - How did you get this error to appear?
Install Visual Studio 2019, Install Cosmos os Userkit latest release, VMWare Version 16

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit- 20200708

**Comment by theopcoder** [comment]
Just as an extra note, I recently had to get a new computer so I installed all the things I needed. On my old computer, it had Visual Studio 2019 with the tools needed, and the same User Kit version but it had VMWare version 15. Any help/fixes would be great!

**Comment by elkaamee326** [comment]
When you open that version of VMware, do you see a virtual machine called Cosmos?

**Comment by theopcoder** [comment]
yes I do

**Comment by elkaamee326** [comment]
Are you able to debug with VMware, when you try to build and run a project?

**Comment by theopcoder** [comment]
I'm not 100% sure what you mean by that but when ever I run the os through visual studio code, its set to debug. This is what it looks like:
![Uploads](https://user-images.githubusercontent.com/58401646/107911791-13f74a00-6f12-11eb-94df-5dc79cdd43eb.PNG)

**Comment by elkaamee326** [comment]
By that I mean when you debug, does COSMOS open VMware, or do you just receive an error message?

**Comment by theopcoder** [comment]
Oh, when I press the debug, it starts up VMWare like normal, but then once its open, it just says the no files found. If I try to start the vm from the app its self, does the same error. If I try to create a new virtual machine and use the iso, same issue.

**Comment by elkaamee326** [comment]
Does it say loading `YourCosmosProject.bin... okay`?

**Comment by theopcoder** [comment]
Sorry for the wait! Pretty much when I open Visual Studio 2019 and launch the project, no error messages occur, everything works fine and opens VMWare. Then when VMWare opens up, it says Loading ProX.... failed! No files found! boot: 

It's quite odd. I tried creating a new os on my old computer and all seemed to work fine. It could be possible an update to Visual Studio 2019 broke it? I'm not sure. Here is a screenshot of what loads after I load the project from VS 2019. 
![image](https://user-images.githubusercontent.com/58401646/108034524-80457c80-6fea-11eb-90c6-09c890a1b949.png)

**Comment by theopcoder** [comment]
I'm not sure if this might help but, When I close the VM, the output on VS 2019 says this: 
![image](https://user-images.githubusercontent.com/58401646/108034634-a66b1c80-6fea-11eb-953c-e71c978a2d74.png)

**Comment by theopcoder** [comment]
Here is a screenshot of the VM and Visual Studio Open. This is the os with no changes made to it, just the default code that loads when you create a new C# Cosmos Os Project. 
![image](https://user-images.githubusercontent.com/58401646/108034938-1da0b080-6feb-11eb-8685-3649e66db7cf.png)

**Comment by quajak** [comment]
If you press enter in the VM does it then find Cosmos? You can also try write Cosmos.bin and see if it finds it then.

**Comment by AnErrupTion** [comment]
There probably has been an issue when building. Did you install everything when selecting the .NET Workload in the Visual Studio Installer? If not, try going back there and selecting .NET Core development tools. Or else try re-installing Cosmos.

**Comment by AnErrupTion** [comment]
Oh, I know. Remove the space in your project name (ProX OS to ProXOS). I had the same problem and it worked! As you can see, it tries to load ProX, not ProX OS.

**Comment by theopcoder** [comment]
@AnErrupTion It worked! Thank you very much for the help. Should I report this issue as a bug? Also, Thank you to everyone else who helped!

**Comment by elkaamee326** [comment]
Oh yeah, that’s is a common error to look out for, I didn’t think of that.

**Comment by theopcoder** [comment]
Alright! Thank you guys for all the help! I'm going to close this bug now. Have a good day!
