### ISSUE TITLE
shutdown and restart

### ISSUE THREAD

**Issue by louis123456** [CosmosOS/Cosmos#167]
make a shutdown and restart command because cosmos.sys.deboot.shutdown(); and bla.bla.bla.reboot(); does not work

**Comment by mterwoord** [comment]
This is a known thing. ACPI is not implemented, and won't be for a while..

**Comment by ARMmaster17** [comment]
See #114. Talk to us on Gitter if you have any problems.

=====
If your question has been resolved, please click *Close Issue*.

**Comment by ARMmaster17** [comment]
Correction, that code relies on a different framework. If you have done OS development, #114 provides a nice guide. If you haven't, just save everything (if you have a file system implemented), clear the screen, and put `It is now safe to turn off the computer`.

=====
If your question has been resolved, please click *Close Issue*.

**Comment by zdimension** [comment]
Well, there's a simple method for rebooting : 
```c
void reboot()
{
    uint8_t good = 0x02;
    while (good & 0x02)
        good = inb(0x64);
    outb(0x64, 0xFE);
    halt();
}
```
Just convert it to C# and enjoy.
For shutdown, it's much complicated, it needs ACPI that is not wel implemented yet.

**Comment by mterwoord** [comment]
@zdimension Problem is, with the rings enforcement, that won't be easy, as accessing ports is only allowed by the HAL.

**Comment by zdimension** [comment]
Then implement it directly in Cosmos (in the bla.bla.bla.Reboot() function)

**Comment by mterwoord** [comment]
To anyone, feel free to add it to cosmos. For now put it in a Machine class i guess..

**Comment by louis123456** [comment]
thanx it helped me a lot

**Comment by Backup-eric645** [comment]
try out `Cosmos.System.Power` class.

**Comment by DolphinFlopFish** [comment]
@Backup-eric645  yes, try Cosmos.System.Power.Shutdown(); or Cosmos.System.Power.Reboot();

**Comment by notmithun** [comment]
> @Backup-eric645 yes, try Cosmos.System.Power.Shutdown(); or Cosmos.System.Power.Reboot();

Thank you, this helped me!

**Comment by SuperUserDone** [comment]
Insane. I was 11 when I posted this XD. Just found it again.

**Comment by zdimension** [comment]
> Insane. I was 11 when I posted this XD. Just found it again.

I did a double take when I saw a GH notification on this repo. I was 12 when I posted my hacky reboot snippet. Those were the days. In retrospect, Cosmos taught me so much about OSdev.

**Comment by SuperUserDone** [comment]
Same. Crazy how a little project I played with at age 11 shaped my life, career and interests.
