### ISSUE TITLE
Don't have an ISO when building an ISO

### ISSUE THREAD

**Issue by TheAirBlow** [CosmosOS/Cosmos#1670]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building an ISO

#### Expected Behaviour - What do you think that should happen?
It should build an ISO in the project bin directory

#### Actual Behaviour - What unexpectedly happens?
There's no ISO files in the directory

#### Reproduction - How did you get this error to appear?
Set build mode to `Build ISO` and compile

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708

**Comment by AnErrupTion** [comment]
Do you have the ISO if you use the VMware Build Mode? If yes, then it's probably just a Cosmos issue. If not, make sure you're in the correct folder (Debug or Release for whatever you've set, then netcoreapp2.0 then cosmos).
