### ISSUE TITLE
from where to install devkit

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1671]
from where to install devkit

Thanks!

**Comment by elkaamee326** [comment]
All you need to do is download the latest Cosmos zip file, and go to this specific directory and unblock this file: `YourinstallLocation\Cosmos\source\Cosmos.VS.ProjectSystem\ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx` and go to properties, and press Unblock.

after that find `InstallVS-2019.bat` and run as admin, and everything will do the work for you afterwards. When it is done installing the devkit, go to `Test.sln` if you want to edit the Cosmos source.

**Comment by Vardan2009** [comment]
when i opened my project, nothing changed, but how can i check is it installed?

**Comment by elkaamee326** [comment]
Just open a regular cosmos solution and see if the Cosmos Icon appears. Honestly, even I am still learning how to use the dev kit.

**Comment by Vardan2009** [comment]
Thanks!

**Comment by TheRealEli310** [comment]
> 
> 
> All you need to do is download the latest Cosmos zip file, and go to this specific directory and unblock this file: `YourinstallLocation\Cosmos\source\Cosmos.VS.ProjectSystem\ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx` and go to properties, and press Unblock.
> 
> after that find `InstallVS-2019.bat` and run as admin, and everything will do the work for you afterwards. When it is done installing the devkit, go to `Test.sln` if you want to edit the Cosmos source.

Sorry but what do you mean by press Unblock? I dont see that button anywhere

**Comment by elkaamee326** [comment]
You have to go to properties and press Unblock, because some or most `.resx` files should give the user the ability to unblock it.
![image](https://user-images.githubusercontent.com/69808082/110728803-a5916900-81eb-11eb-9748-e0c4ff5c2f57.png)
It should look like an image like this (I was unsure if there was a checkbox or a button there)...
