### ISSUE TITLE
Filesystem Error

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1674]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Filesystem

#### Expected Behaviour - What do you think that should happen?

Show files and directories

#### Actual Behaviour - What unexpectedly happens?

throws this exception
![Screenshot 2021-02-21 213543](https://user-images.githubusercontent.com/70532109/108633330-24b53c00-748d-11eb-8ac5-e47c596e2fc8.png)

#### Reproduction - How did you get this error to appear?

I Used this code:
![Screenshot 2021-02-21 213657](https://user-images.githubusercontent.com/70532109/108633336-2c74e080-748d-11eb-9ad4-e386c1fd9a07.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

**Comment by Vardan2009** [comment]
plz answer :(

**Comment by Vardan2009** [comment]
:(

**Comment by alessiobb1** [comment]
If i create a new disk in another vm with windows and format is FAt32 and "insert" the disk in Cosmos, i have this errror, but if i use: https://github.com/CosmosOS/Cosmos/raw/master/build/VMWare/Workstation/Filesystem.vmdk it work.

**Comment by Vardan2009** [comment]
That means I need to replace Filesyste.vmdk with this one?

**Comment by EliaSulimanov** [comment]
Hi @Vardan2009,
please check out this: [File System Warnings](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#warnings
)
It would also be helpful if tell us if it helped.

**Comment by Vardan2009** [comment]
Thanks! I'll try

**Comment by Vardan2009** [comment]
Thanks! I Replaced the .vmdk file and it worked..
