### ISSUE TITLE
Please update userkit along with devkit

### ISSUE THREAD

**Issue by Barshan-Mandal** [CosmosOS/Cosmos#1677]
Please update userkit along with devkit

**Comment by zarlo** [comment]
this will likely be done after the network and threading work is stable ish

**Comment by Barshan-Mandal** [comment]
tnx....please help me....cant draw a mouse...vs19 crashes

**Comment by quajak** [comment]
The aim for the next devkit is when cosmos supports .net5.0 until then I suggest installing the devkit, if you want the new features.
