### ISSUE TITLE
Mouse flashes with a Canvas

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1681]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
Add a mouse updated and a Canvas refiled in a loop

#### Actual Behaviour - What unexpectedly happens?
Mouse flashes

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lasted build (not relase, github code)

**Comment by MishaTY** [comment]
See [https://github.com/CosmosOS/Cosmos/wiki/Non-Flickering-Canvas-GUI-Tutorial](url)

**Comment by ArtGo-Devloppper** [comment]
It works but the driver takes time to "write" the screen, do you have a solution ?

**Comment by MishaTY** [comment]
You can take a look at this driver here: https://github.com/nifanfa/Cosmos-DoubleBufferedVMWareSVGAII Its very fast in VMware, but it will not work on real hardware.

**Comment by quajak** [comment]
For most drivers, buffered versions are included in the devkit, which should be quicker. At some point you will have to "write" to the screen, which takes some time. For further optimizations regarding the GUI, please open a thread on discussions or use the gitter chat.
