### ISSUE TITLE
Files System Error

### ISSUE THREAD

**Issue by unknown850** [CosmosOS/Cosmos#1683]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.System.FileSystem

#### Expected Behaviour - What do you think that should happen?
It should print out the Available Free Space: (available_space) Bytes

#### Actual Behaviour - What unexpectedly happens?
The output is: 
Exception occurred while running kernel:
Exception: Unable to determine filesystem for path: 0:/

#### Reproduction - How did you get this error to appear?
I use this code
long available_space = fs.GetAvailableFreeSpace("0:/");
Console.WriteLine("Available Free Space: " + available_space + " Bytes");

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit with Cosmos, IL2CPU, X# master version I thing

**Comment by elkaamee326** [comment]
Are you using VMware Workstation Player as your Virtual Machine? If you are, make sure that it can find `Filesystem.vmdk`. To check go to `C:/Users/Yourusername/AppData/Roaming/Cosmos UserKit/Build/VMware/Workstation/Filesystem.vmdk`, and if you find it, launch VMware Workstation Player 15.0 from your start menu and search for Cosmos and press Edit Virtual Machine Settings and find Hardisk IDE and make sure that the Filesystem.vmdk file is installed from the location above. `Filesystem.vmdk` is where you can store images and any assets you would like to use in your Cosmos projects.

**Comment by unknown850** [comment]
I checked it and it still there
![image](https://user-images.githubusercontent.com/79923622/109787552-ee23b200-7c40-11eb-87b5-1df190355cff.png)

**Comment by elkaamee326** [comment]
I am unsure about the result for the `filesystem.vmdk` file loadig correctly in your VM (16.0), but try using VMware Workstation 15 for now.

**Comment by EliaSulimanov** [comment]
Hi @unknown850,
[Please check the first warning mentioned here.](https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#warnings)
It will be helpful if you tell us if it solved the issue.

**Comment by hyperdawg** [comment]
my virtual machine always says "Filesystem.vmdk not found" help me find it please

**Comment by hyperdawg** [comment]
oh i fixed it
