### ISSUE TITLE
[BUG] MemoryBlock crahes

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1684]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
II think it's an overload in the video memory

#### Actual Behaviour - What unexpectedly happens?
I think a GUI freeze

#### Reproduction - How did you get this error to appear?
Using a MemoryBlock and add operation with Kernel.Run()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Laset sources

**Comment by MishaTY** [comment]
See: #1659

**Comment by ArtGo-Devloppper** [comment]
OK, I increased my VM to 4Gb of ram, but when will this bug be fixed (with the new memory manager) ?

**Comment by quajak** [comment]
The bug and better memory management is one of the priorities after getting cosmos to work with .net 5.

**Comment by ArtGo-Devloppper** [comment]
Ok thanks for your help

**Comment by ArtGo-Devloppper** [comment]
Does Comos have a system to empty the video memory?

**Comment by quajak** [comment]
The part of memory used for the video driver depends on the exact driver. I dont understand fully understand what you meant with "empty", the clear method always sets the entire region to one value. For follow-up questions please use discussions or gitter rather than the issues.

**Comment by ArtGo-Devloppper** [comment]
ok here : https://github.com/CosmosOS/Cosmos/discussions/1709
