### ISSUE TITLE
PS/2 Controller not supported

### ISSUE THREAD

**Issue by Wolfsurge** [CosmosOS/Cosmos#1685]
#### Area of Cosmos - What area of Cosmos are we dealing with?
When I make an ISO build and attempt to boot it.

#### Expected Behaviour - What do you think that should happen?
It should start normally, without the error.

#### Actual Behaviour - What unexpectedly happens?
When I try to boot it, it gives me the error:
Exception: ((PS/2 Device) PS/2 controller not supported)

#### Reproduction - How did you get this error to appear?
Booting my ISO file off of a USB drive.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

**Comment by Wolfsurge** [comment]
> That means that your keyboard controller is not supported. Try it on another computer.

I've tried booting it with keyboard And mouse unplugged, and it does nothing.

**Comment by quajak** [comment]
Will be fixed by https://github.com/CosmosOS/Cosmos/pull/1541, until then the only chance you have is if you are on devkit and manually remove the code where it throws the exception.

**Comment by KM198912** [comment]
#1745 should temporarily bypass this issue, can you please try again, eventually you will need to unplug your mouse due to a missing bit in the PS/2 controller which detects if you use a mouse or keyboard.
