### ISSUE TITLE
 How do I Change directory of COSMOS

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#1687]
Hello when I build I get this error:
Error	MSB6004	The specified task executable location "G:\COSMOS User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.

How do I change the G:\ to the H:\Cosmos User Kit directory?

Thanks for any help

**Comment by DolphinFlopFish** [comment]
please

**Comment by zarlo** [comment]
dev kit or user kit

**Comment by emrns** [comment]
user kit

**Comment by DolphinFlopFish** [comment]
don't worry I got it
