### ISSUE TITLE
Cosmos Kit Builder building userkit and not devkit

### ISSUE THREAD

**Issue by TheRealEli310** [CosmosOS/Cosmos#1688]
**Describe the problem**
In the Cosmos Kit Builder, It is building userkit when I want devkit

**Steps of installation up to now**
I dont know how this happened 

**Expected behavior**
For the builder to build devkit

**Logs**

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
 - Are you using an admin account? Yes
 - VS Version if applicable

**Additional context**
I have installed userkit before but it is uninstalled.

**Comment by zarlo** [comment]
that is what the Cosmos Kit Builder it builds a user kit
