### ISSUE TITLE
Get when a key is pressed!

### ISSUE THREAD

**Issue by zalnaRs** [CosmosOS/Cosmos#1689]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Keyboard

#### Expected Behaviour - What do you think that should happen?
Run something when a key is pressed!

#### Actual Behaviour - What unexpectedly happens?
i don't find how to get when a key is pressed!

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708

**Comment by TheRealEli310** [comment]
This is not a bug

**Comment by TheRealEli310** [comment]
just use Console.ReadKey();

**Comment by zalnaRs** [comment]
> just use Console.ReadKey();

Yes i know but i want to use special keys

**Comment by zalnaRs** [comment]
> See: https://github.com/MishaTY/Misha-OS/blob/d20913f45862bb6989daee1c94425c57089d9154/Misha-OS/Gui/Apps/Terminal.cs#L71
Thank you!
