### ISSUE TITLE
Weird glitches while using font

### ISSUE THREAD

**Issue by virtualtoja** [CosmosOS/Cosmos#1690]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
Print text in choosen font

#### Actual Behaviour - What unexpectedly happens?
It displayed weird glitches

#### Reproduction - How did you get this error to appear?
just used the same font that is used in AuraOS

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? 
I Use the newest userkit

Screenshot:
![obraz](https://user-images.githubusercontent.com/76951241/110452895-e5f6c700-80c5-11eb-8e55-ecf3509b633f.png)
![obraz](https://user-images.githubusercontent.com/76951241/110452997-0757b300-80c6-11eb-80eb-a228cea4a071.png)

**Comment by MishaTY** [comment]
How did you set the font?

**Comment by virtualtoja** [comment]
I set it by running VGAScreen.SetFont() and as arguments i pasted the base64 in Covert.FromBase64String() copied from official AuraOS Code

**Comment by quajak** [comment]
If the issues is only with this specific font, then I would ask the AuraOS team, since AFAIK they use the same/very similar vga code. Can you confirm that using other fonts works?

**Comment by virtualtoja** [comment]
for me only the default font works. I tried others but they were stretched

**Comment by quajak** [comment]
Could you try either update to the devkit or copy the PCScreenFont related code and check if that works?

**Comment by RSTPlays** [comment]
> I set it by running VGAScreen.SetFont() and as arguments i pasted the base64 in Covert.FromBase64String() copied from official AuraOS Code

Hey there, where is the Base64 Code in Aura OS? Please help, i'm trying to add a custom font to my OS
