### ISSUE TITLE
Downloading Cosmos on another disk gives me error

### ISSUE THREAD

**Issue by emrns** [CosmosOS/Cosmos#1691]
I downloaded cosmos on d disk and i get this error :

translate of it : 
Cant find executable at path "C:\Users\nasfa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe"

If i need nuget packages give me link

**Comment by zarlo** [comment]
user kit or dev kit
all the nuget packages it uses will be from a repo (it just a folder) on your system

**Comment by elkaamee326** [comment]
On the installer, did you set the install location to `D:/`? or did you leave it the way it is? Because (on the userkit), COSMOS has this hardcoded install location, which means you can only install COSMOS in that directory.

**Comment by emrns** [comment]
i downloaded it to c disk so am not getting any errors any more
