### ISSUE TITLE
Gui user input

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/Cosmos#1696]
I am trying to make GUI terminal, but I don't know how to get user input. Can anyone help me with it?

**Comment by napalmtorch** [comment]
Cosmos.System.KeyboardManager should be what you need, with that you can get IsKeyUp and IsKeyDown, if you check out my OS I have a keyboard input implementation

**Comment by MishaTY** [comment]
See https://github.com/MishaTY/Misha-OS/blob/master/Misha-OS/Gui/Apps/Terminal.cs

**Comment by ilobilo** [comment]
Thanks
