### ISSUE TITLE
how to make mouse correctly

### ISSUE THREAD

**Issue by sayaPintar** [CosmosOS/Cosmos#1701]
#### Area of Cosmos - What area of Cosmos are we dealing with?
mouse(GUI)

#### Expected Behaviour - What do you think that should happen?
i following a mouse tutorial in Wiki cosmos but its not working.

#### Actual Behaviour - What unexpectedly happens?
its not working return a exception

#### Reproduction - How did you get this error to appear?
im only following a code make mouse in Wiki cosmos.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit 20200708

**Comment by alessiobb1** [comment]
Hi! I have put mouse in my Os and driver video by the Purple Moon OS project, this is the link for the video: https://www.youtube.com/watch?v=2TRR6473XXA and this the code: https://github.com/napalmtorch/PurpleMoonOS_Old and this is the link for a video that test my OS (but is italian): https://www.youtube.com/watch?v=kDwwF4J-Zso
