### ISSUE TITLE
Cosmos User Kit Issue: Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by Prisision** [CosmosOS/Cosmos#1702]
I Know Its Can Be That No One Reacts To Here But i need Your Help!

I wanted To build My Cosmos Project(Cosmos User Kit Because I Dont Know How To Use Dev Kit)

And This Error Comes Up.

1>------ Erstellen gestartet: Projekt: VoxelOS, Konfiguration: Debug Any CPU ------
1>VoxelOS -> C:\Users\Elisabeth Gerson\Desktop\Voxel\VoxelOS\VoxelOS\bin\Debug\netcoreapp2.1\cosmos\VoxelOS.dll
1>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
1>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
1>IL2CPU task took 00:00:00.6167897
1>Die Erstellung des Projekts "VoxelOS.csproj" ist abgeschlossen -- FEHLER.
========== Erstellen: 0 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========

HELP PLEASE I DONT KNOW HOW TO FIX THIS :'(

**Comment by quajak** [comment]
Can you pin point what code caused the problem?

**Comment by charlesbetros** [comment]
What version of Visual Studio, dotnet cli, etc do you have?
