### ISSUE TITLE
External executable execution

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/Cosmos#1703]
** Complexity of plug **
I think very complex

**Describe alternatives you've considered**
Are there ways to work around this plug not existing?
No

**Additional context**
Add any other context about the plug request here.
Run precompiled c# apps from filesystem (write programs with c# not asm)

**Comment by MishaTY** [comment]
See: https://github.com/MishaTY/DotNetParser

It's very basic currently, but it can run C# apps in Cosmos.

**Comment by ilobilo** [comment]
Thank you!
