### ISSUE TITLE
Cosmos DrawString

### ISSUE THREAD

**Issue by Prisision** [CosmosOS/Cosmos#1704]
I Need Soome Help...
I am Using Cosmos User Kit 20181010-vs2017 And Dont Know How To Draw Letters Or String Like 

canvas.DrawString("Hello World);

I Really Need Help!

**Comment by sudopigeek** [comment]
[CGUI](https://github.com/sudopigeek/CGUI) _**should**_ work in Visual Studio 2017; download the latest release from [here](https://github.com/sudopigeek/CGUI/releases/latest) and add it to your project (wiki [here](https://github.com/sudopigeek/CGUI/wiki)). It should serve your purpose; let me know it goes.

**Comment by quajak** [comment]
That version of cosmos does not provide a standard way. Use a newer version or use a third party solution. For questions like this please use discussions or gitter and not github issues.
