### ISSUE TITLE
Cant boot on actual hardware

### ISSUE THREAD

**Issue by nailuj29gaming** [CosmosOS/Cosmos#1705]
I just made a very simple OS, however, I can't get it to boot on my computer. When I image the flash drive with the ISO, I get a warning like "This ISO isn't bootable".

I've tried on both the latest devkit and userkit

**Comment by nailuj29gaming** [comment]
I just discovered the ISO Image build option, but i still cant build it. 
![image](https://user-images.githubusercontent.com/54189157/111920205-20684880-8a64-11eb-8762-bb984f02fd2a.png)

**Comment by IdkGD** [comment]
ignore this error. i think visual studio is trying to open a file that just doesn't exists or is invalid.
but the iso file is somewhere in the project folder, so you can put it in a virtual machine or to image the flash drive with it as you say.

**Comment by nailuj29gaming** [comment]
Tried that, now I get an error about PS/2

**Comment by octaviousrex** [comment]
> Tried that, now I get an error about PS/2 when I boot.

what kind of error?

**Comment by nailuj29gaming** [comment]
Yes, that is my error
