### ISSUE TITLE
Execute ELF files

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/Cosmos#1706]
**What is the usecase for this plug**
Run static ELF (Linux) executables

** Complexity of plug **
Complex

**Describe alternatives you've considered**
No

**Comment by quajak** [comment]
This is currently not possible and is not planned for the near future. For further discussion and what is currently possible/what others have created to execute programs see discussions or the gitter.

**Comment by iMonZ** [comment]
> This is currently not possible and is not planned for the near future. For further discussion and what is currently possible/what others have created to execute programs see discussions or the gitter.

Very sad for this project.
Some projects have potential and then destroy it and put the project into shit

**Comment by valentinbreiz** [comment]
Language please and you can still use CosmosELF (https://github.com/Myvar/CosmosELF)

**Comment by Lamm-nguy** [comment]
@valentinbreiz can u tell me how to use it in my os? i have compiled it into some dll files 
![image](https://github.com/CosmosOS/Cosmos/assets/112396747/79be9a13-ce82-434f-a2d4-cfae714bc847)
