### ISSUE TITLE
IL2CPU ERRORS \ Files not found \ Build Problems

### ISSUE THREAD

**Issue by NETdeve** [CosmosOS/Cosmos#1708]
Hello, i am new in GitHub and COSMOS aswell
I am finding this problem: when i compile VS says error MSB6004. 
After this i deleted a part of a code 
`string directory;
 foreach (string Files in System.IO.Directory.GetFiles(directory))
                        {
                            Console.WriteLine(Files);
                        }`
i saved and built, now it builds (VS says build completed) but when i run on debug i see a VS messagebox (File not found) I cant find ISO file in \bin\Debug\netcoreapp2.0\cosmos. thanks in advice

**Comment by MishaTY** [comment]
Are you using the user kit or the dev kit? And what exactly is the error?

**Comment by NETdeve** [comment]
I am using user kit
Error is MSB6004->the file .exe in path specified is not valid [exe not valid is IL2CPU.exe]. I am actually trying to reinstall user kit. Sometimes VS crashes randomly too [while kernel project is open]

**Comment by quajak** [comment]
What launch setting are you using?

**Comment by NETdeve** [comment]
I am using standard settings, anyway I fixed, i reinstalled 2 times user kit. Now i am not sure how to close this issue. I'll try. Anyway thanks guys 👍
