### ISSUE TITLE
Duplicate packet with AMD PCNETII driver & VMWare

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1713]
Packets sent from Cosmos (with the PCNET II driver) and received on a remote computer are duplicated for an unknown reason, the same packet is received twice. It only happens with the TX descriptor, RX works on Cosmos and does not receive duplicate packets from other computers.

**Comment by MishaTY** [comment]
Does it work correctly with the rtl8139 driver?

**Comment by valentinbreiz** [comment]
It should yes, could you test it?

**Comment by valentinbreiz** [comment]
I tested with VirtualBox and Am79C970A (PCnet-PCI II) and I don't have this packet doublon problem. The issue is only on VMWare...

![image](https://user-images.githubusercontent.com/18724279/116708290-d9a92f00-a9cf-11eb-8af3-60f5a5bfb2c9.png)

**Comment by valentinbreiz** [comment]
After a few tests I can confirm that our driver is working, it's VMWare related (https://thedatamachine.wordpress.com/2019/12/26/vmware-workstation-dup-packet-issue-resolved-sort-of/)
