### ISSUE TITLE
Network stack test system

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1714]
We need to test packet sending and receiving on different implemented protocols. Since the network stack can be used outside Cosmos we can test the the whole stack without Cosmos, or we can make a fake network driver that will send and receive from the testrunner.

**Comment by quajak** [comment]
Its a good idea to not rely on the specific driver and rather introduce an interface, so that we can unit testing directly in VS.

**Comment by valentinbreiz** [comment]
Done
