### ISSUE TITLE
Timer and Threading support

### ISSUE THREAD

**Issue by frankhaugen** [CosmosOS/Cosmos#172]
I'm not a professional programmer, so this might not be missing, and I'm just not looking in the right place.

I am loving Cosmos as a concept, and I'm playing around with it. But getting the console to be more "visual", I'm needing a timer/clock and the option to halt either the thread or the task, (having WriteLines appear at intervals for instance).

I've used the Run() method to assign "ticks" to a counter and then at every second adding a tick to another class-level variable to simplify the clock, (100 000 ticks per second is frustrating to work with). This is however, a hack that's not optimal.

As a footnote, there are NO documentation available online, it would be nice to at least have a badly formatted document of notes, so everything is easier to get a handle on

**Comment by mterwoord** [comment]
At this moment there's no threading support, nor will there be for a while.
It should be able (with a little effort) to implement a simple timer, using the PIT (see http://wiki.osdev.org/PIT) it's possible to make a basic timer.

Regarding documentation: We know, we're devs, and are bad at documenting what we do.

That being said, we are currently focusing on 2 major breakthroughs (FAT support and memory management). Once we get that going, we will most likely do some more documenting.

Before we reach that mark, feel free to add some more docs to our project..

**Comment by frankhaugen** [comment]
That wasn't a simple read. But very helpful and definitely informative.

I might actually contribute some documentation. If for nothing else, then to discover the inner workings for myself.

Thank you for your reply!

**Comment by mterwoord** [comment]
If you're interested in helping out, please join either our mailinglist, or our gitter chat. We can get you going by explaining things there..
If this issue is resolved, please close it. Thanks!
