### ISSUE TITLE
Copy the iso file in a Virtual Disk isn't work.

### ISSUE THREAD

**Issue by alessiobb1** [CosmosOS/Cosmos#1722]
Hi! Why if I try to copy the iso files (estracted in 7z) in a Cosmos Virtual disk created in a WIndows 7 Vm SATA formattated in FAT32 (this virtual disk is work in Cosmos, so if i create a folder in this virtualdisk is work!!!!!! in Windows 7 vm and in Cosmos! Wow!!!) return in the point, because if I copy ALL files isn't work, Vmware don't find boot device, so if i use the .iso is work?

Tranks!!!!!!!  
Sorry if this english is not good but i'm 14 italian...

**Comment by Arawn-Davies** [comment]
A bootloader needs to be installed to the virtual disk for any computer to boot Cosmos, regardless as whether it's a virtual machine or a real computer. Currently only booting from ISO is supported.

You could install SYSLINUX to the MBR of the virtual drive, but you'd have to do that yourself as reading from the optical drive isn't finished (yet!)
