### ISSUE TITLE
Is There a canvas.DrawString method?

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1723]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI

#### Expected Behaviour - What do you think that should happen?
Draw String Using canvas.DrawString()

#### Actual Behaviour - What unexpectedly happens?
there's no canvas.DrawString() method

#### Reproduction - How did you get this error to appear?
canvas.DrawString();

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest Userkit

**Comment by MishaTY** [comment]
Use fullscreenCanvas.GetFullscreenCanvas(DrawString())

**Comment by quajak** [comment]
DrawString is only available in the devkit currently.

**Comment by elkaamee326** [comment]
You could use this: https://github.com/nifanfa/Cosmos-DrawString. You can draw any string with the loaded font .

**Comment by Vardan2009** [comment]
@elkaamee326 thanks! I will try

**Comment by Vardan2009** [comment]
@elkaamee326 THANKS IT WORKS!!!!!!!!!!!!!!!!!!!!!!!
![Screenshot 2021-04-18 180021](https://user-images.githubusercontent.com/70532109/115148292-f8263680-a06f-11eb-96d6-f0f8ded021bd.png)
