### ISSUE TITLE
Is there a canvas.drawstring method?

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1725]
Is there a canvas.drawstring method?
I installed the lastest userkit and there's no canvas.drawstring or canvas.drawchar method
Please help..
thanks!

**Comment by MishaTY** [comment]
The userkit does not have a Canvas.drawstring or Canvas.drawchar method. Install the devkit to get these methods.

**Comment by quajak** [comment]
Duplicate of https://github.com/CosmosOS/Cosmos/issues/1723

**Comment by Vardan2009** [comment]
@quajak sorry that I opened two issues :D
