### ISSUE TITLE
No method to check if a specific key is pressed.

### ISSUE THREAD

**Issue by BlitzWolfMatthew** [CosmosOS/Cosmos#1726]
#### Area of Cosmos - What area of Cosmos are we dealing with?

KeyboardManager
#### Expected Behaviour - What do you think that should happen?

Currently we can only read a key at a time from the keyboard using KeyboardManager#TryReadKey(out KeyEvent oKey) but this implementation wont allow the user to check if, for example, a combination of key is pressed (eg.  LWin + LShift + S) as we cannot check if multiple keys are being pressed at once.
#### Actual Behaviour - What unexpectedly happens?

Method to check if a specific key is pressed.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit

**Comment by quajak** [comment]
I think a better approach to find the current pressed key is a combination of `Console.KeyAvailable` and `Console.ReadKey`. `Console.ReadKey` should include information on all ConsoleModifiers.

**Comment by BlitzWolfMatthew** [comment]
Yes, but wouldn't that halt the CPU?

**Comment by quajak** [comment]
If you use Console.KeyAvailable you should be able to not have to halt, since it tells you when there is something to read. I dont think standard C#  has a way to detect multiple keys beyond what ReadKey supports (modifiers). ANd I am not sure if there is actually the need for Cosmos to support something like that.

**Comment by KM198912** [comment]
you can also see a implementation of how to use it here which was removed a while ago to allow users to handle those cases themself https://github.com/CosmosOS/Cosmos/commit/cabc72bb9ebbb2d737cf39542dc5838891f12d53

**Comment by BlitzWolfMatthew** [comment]
Didn't really find a solution to check for multiple letter keys, but I settled down on this: 
`if (Sys.KeyboardManager.ControlPressed && Sys.KeyboardManager.ShiftPressed && input.Key == ConsoleKeyEx.S)`
