### ISSUE TITLE
Error when Changing Mouse Sensitivity

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1730]
#### Area of Cosmos - What area of Cosmos are we dealing with?

GUI

#### Expected Behaviour - What do you think that should happen?

Change Mouse Sensitivity

#### Actual Behaviour - What unexpectedly happens?

OS Freezes and this appears....
![Screenshot 2021-04-20 182942](https://user-images.githubusercontent.com/70532109/115413883-9d731300-a206-11eb-8d99-cf52ab87bb22.png)

#### Reproduction - How did you get this error to appear?

  SYS.MouseManager.MouseSensitivity += 0.1f;
or
  SYS.MouseManager.MouseSensitivity -= 0.1f;

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Lastest Userkit

**Comment by quajak** [comment]
That seems like a bug, can you make a simple kernel which reproduces the issue?

**Comment by Vardan2009** [comment]
I put this on try{} catch{} and it wrote this
Exception: ArgIndexOutOfRangeException

**Comment by quajak** [comment]
Could you possibly be drawing outside of the valid screen region?

**Comment by Vardan2009** [comment]
No. btw Here's the full code:
  try
                    {
                        if (SYS.MouseManager.Y >= 130 && SYS.MouseManager.Y <= 130 + 10)
                        {
                            if (SYS.MouseManager.X >= 150 && SYS.MouseManager.X <= 150 + 10)
                            {
                                if (SYS.MouseManager.MouseState == SYS.MouseState.Left)
                                {
                                    FontDrawer.WriteText("Mouse Speed: " + SYS.MouseManager.MouseSensitivity, 50, 130, Color.Gray);
                                    SYS.MouseManager.MouseSensitivity += 0.1f;

                                    FontDrawer.WriteText("Mouse Speed: " + SYS.MouseManager.MouseSensitivity, 50, 130, Color.Black);
                                }
                            }
                        }
                        if (SYS.MouseManager.Y >= 130 && SYS.MouseManager.Y <= 130 + 10)
                        {
                            if (SYS.MouseManager.X >= 160 && SYS.MouseManager.X <= 160 + 10)
                            {
                                if (SYS.MouseManager.MouseState == SYS.MouseState.Left)
                                {
                                    FontDrawer.WriteText("Mouse Speed: " + SYS.MouseManager.MouseSensitivity, 50, 130, Color.Gray);
                                    SYS.MouseManager.MouseSensitivity -= 0.1f;

                                    FontDrawer.WriteText("Mouse Speed: " + SYS.MouseManager.MouseSensitivity, 50, 130, Color.Black);
                                }
                            }
                        }
                    }
                    catch (Exception e) { canvas.CleanScreen(); FontDrawer.WriteText("EXCEPTION: " + e.ToString(), 1, 1, Color.Red); }

**Comment by quajak** [comment]
Does `MouseManager.MouseSensitivity = 2;` work?

**Comment by Vardan2009** [comment]
Oh... I don't know. I'll try that tomorrow

**Comment by Vardan2009** [comment]
I will try that now

**Comment by Vardan2009** [comment]
It worked!
