### ISSUE TITLE
Canvas Color Error

### ISSUE THREAD

**Issue by Overjamed** [CosmosOS/Cosmos#1735]
So i have writen the kernel and tried it out but It Shows instead of Green Red, And Aqua White... Please Help Me!

**Comment by Arawn-Davies** [comment]
Hi, thanks for opening the issue. Could you provide the code that you're using and possibly a screenshot of the output you're getting?

**Comment by AcaiBerii** [comment]
Are you using ConsoleColor? I am, not getting the same issue. It could be an issue with your virtual machine or hardware.
