### ISSUE TITLE
Remote debugging still happening whilst having remote debugging disabled

### ISSUE THREAD

**Issue by sketchedgrey** [CosmosOS/Cosmos#1743]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building an ISO

#### Expected Behaviour - What do you think that should happen?
I should be able to run my ISO in VMWare 16

#### Actual Behaviour - What unexpectedly happens?
I get "Waiting for remote debugger connection"

#### Reproduction - How did you get this error to appear?
Build a release version ISO with Remote Debugging disabled.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

See #1195

**Comment by quajak** [comment]
How did you disable the debugging? Also can you try deleting the existing iso and creating a new one to see if the problem is still there?

**Comment by sketchedgrey** [comment]
> How did you disable the debugging? Also can you try deleting the existing iso and creating a new one to see if the problem is still there?

I went to the project properties in VS, selected "Cosmos," went to "Debug" and disabled remote debugging. I also marked my project as release and built a new ISO.

**Comment by MishaTY** [comment]
The release configuration is not supported. Change it to Debug.

**Comment by sketchedgrey** [comment]
Thanks @MishaTY , sorry for another silly question.

**Comment by AcaiBerii** [comment]
This is still happening with the debug configuration lol

Cosmos is trash.
