### ISSUE TITLE
Cosmos VFS not working

### ISSUE THREAD

**Issue by sketchedgrey** [CosmosOS/Cosmos#1751]
Have you checked Github Issues for similar errors? Yes

**Exception**
Error CS0246 The type or namespace name 'CosmosVFS' could not be found (are you missing a using directive or an assembly reference?)

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
^^^

**To Reproduce**
Use "CosmosVFS fs = new Sys.FileSystem.CosmosVFS();" before BeforeRun()

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[Yes ] Both Cosmos VS Extensions are installed
[Yes ] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.
I'm using the Userkit, it looks like my code should work with it according to the documentation.

**Comment by elkaamee326** [comment]
You need to import `using Cosmos.System.FileSystem.VFS;` 
as well as `using Cosmos.System.FileSystem;` These are two sperate namespaces that must be included.

**Comment by elkaamee326** [comment]
Here is the updated wiki: https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

**Comment by sketchedgrey** [comment]
Thanks!
