### ISSUE TITLE
Mode 800x640@32 is not supported by this driver

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1754]
#### Area of Cosmos - What area of Cosmos are we dealing with?
gui

#### Expected Behaviour - What do you think that should happen?
change canvas mode

#### Actual Behaviour - What unexpectedly happens?

throws an exception:
![Screenshot 2021-05-06 101950](https://user-images.githubusercontent.com/70532109/117250668-9d088800-ae54-11eb-854e-0da6404a7e39.png)

#### Reproduction - How did you get this error to appear?
     canvas.Mode = new Sys.Graphics.Mode(800, 640, Sys.Graphics.ColorDepth.ColorDepth32);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
lastest userkit

**Comment by Vardan2009** [comment]
full code:
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;


namespace vOS.Hardware
{
    public static class Graph
    {
        // driver
        private static int screenX = 800;
        
        private static int screenY = 640;
        private static Color[] pixelBuffer = new Color[(screenX * screenY) + screenX];
        private static Color[] pixelBufferOld = new Color[(screenX * screenY) + screenX];
        private static Sys.Graphics.Canvas canvas = Sys.Graphics.FullScreenCanvas.GetFullScreenCanvas();

        public static void init()
        {
            try
            {
                canvas.Mode = new Sys.Graphics.Mode(screenX, screenY, Sys.Graphics.ColorDepth.ColorDepth32);
                Cosmos.System.MouseManager.ScreenWidth = Convert.ToUInt32(screenX);
                Cosmos.System.MouseManager.ScreenHeight = Convert.ToUInt32(screenY);
            }catch (Exception e)
            {
                canvas.Disable();
                Console.WriteLine("ERROR IN INIT(): "+e.ToString());
            }
         
        }

        public static void setPixel(int x, int y, Color c)
        {
            if (x > screenX || y > screenY) return;
            pixelBuffer[(x * y) + x] = c;
        }
        public static void update()
        {
           
                clearScreen(Color.Blue);
                setPixel(1, 1, Color.Black);
                setPixel(1, 2, Color.Black);
                setPixel(2, 1, Color.Black);
                setPixel(2, 2, Color.Black);
                setPixel(Convert.ToInt32(Cosmos.System.MouseManager.X), Convert.ToInt32(Cosmos.System.MouseManager.Y), Color.White);
                drawScreen();
         
        }
        public static void drawScreen()
        {
            Sys.Graphics.Pen pen = new Sys.Graphics.Pen(Color.Orange);
            for (int y = 0, h = screenY; y < h; y++)
            {
                for (int x = 0, w = screenX; x < w; x++)
                {
                    if (!(pixelBuffer[(y * x) + x] == pixelBufferOld[(y * y) + x]))
                    {
                        pen.Color = pixelBuffer[(y * screenX) + x];
                        canvas.DrawPoint(pen, x, y);
                    }
                }
            }
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = pixelBufferOld[i];
            }
        }
        public static void clearScreen(Color c)
        {
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = c;
            }
        }
    }
}

**Comment by quajak** [comment]
What virtual machine are you using?

**Comment by Vardan2009** [comment]
I use VMware workstation 16 pro

**Comment by quajak** [comment]
SVGA currently does not have mode listed as one which is supported https://github.com/CosmosOS/Cosmos/blob/19132e34eb279be193ff64afe29146f0d7fbe404/source/Cosmos.System2/Graphics/SVGAIICanvas.cs#L219 . If you think that SVGA can actually support this mode, we can try add it.
