### ISSUE TITLE
Keys with 3 chars not working !

### ISSUE THREAD

**Issue by uralgo2** [CosmosOS/Cosmos#1755]
#### Area of Cosmos - What area of Cosmos are we dealing with?

System.Generic Dictionary

#### Expected Behaviour - What do you think that should happen?

code :
this.opcodes.TryGetValue(opcode, out OpCode op)
must return a OpCode 

#### Actual Behaviour - What unexpectedly happens?

its return Arg_KeyNotFound
Keys over 2 chars not working in dictionary

#### Reproduction - How did you get this error to appear?

im trying make virtual machine and assembler to he.
When im tested it on windows all worked correctly
But on cosmos it does not work.

im add keys :

 public void InitOpCodes()
        {
            this.opcodes.Add("add", new add());
            this.opcodes.Add("mov", new mov());
            this.opcodes.Add("jmp", new jmp());
            this.opcodes.Add("je", new je());
            this.opcodes.Add("jne", new jne());
            this.opcodes.Add("jl", new jl());
            this.opcodes.Add("jle", new jle());
            this.opcodes.Add("jg", new jg());
            this.opcodes.Add("jge", new jge());
            this.opcodes.Add("ret", new ret());
            this.opcodes.Add("cmp", new cmp());
            this.opcodes.Add("int", new Int());
            this.opcodes.Add("nop", new nop());
        }
but working only keys with 2 chars.

Im add condition:

if(opcode == "mov"){
Console.WriteLine("Opcode equal to mov")
}
and this working.
and when im do this:
this.opcodes["mov"].Run();
this working.

im dont know where error
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

last userkit

**Comment by uralgo2** [comment]
and this.opcodes[opcode] also not working

**Comment by uralgo2** [comment]
and when im change mov to move its working

**Comment by quajak** [comment]
This sounds like a dictionary bug.

**Comment by uralgo2** [comment]
i'm fixed it. had to implents own dictionary.

**Comment by quajak** [comment]
Fixed by https://github.com/CosmosOS/Cosmos/pull/2340
