### ISSUE TITLE
Cosmos Nuget Error on All Projects

### ISSUE THREAD

**Issue by KatliamEye** [CosmosOS/Cosmos#1756]
I get this error on any .net core project;
`Error restoring NuGet Packages: local resource 'D:\F\Cosmos User Kit V2\packages\' does not exist`

I reinstalled visual studio but not changed
Please help me

**Comment by quajak** [comment]
Where did you install the user kit?

**Comment by KatliamEye** [comment]
I removed to user kit

**Comment by quajak** [comment]
Did you install the devkit? Otherwise Cosmos needs the user kit files to function.

**Comment by TheRealEli310** [comment]
Try reinstalling the userkit.
