### ISSUE TITLE
Coordinates System in Cosmos

### ISSUE THREAD

**Issue by NETdeve** [CosmosOS/Cosmos#1757]
Hello everybody. Actually i don't know how to coordinates work, i mean: where is the origin of the axis? Thanks in advance

**Comment by sudopigeek** [comment]
Screen coordinates begin at the top left corner of the screen at (0, 0). X increases and decreases by moving right or left, and Y increases and decreases by moving up or down:
![unnamed](https://user-images.githubusercontent.com/37987178/117368769-97796500-ae89-11eb-8cdf-981a6b24b39e.jpg)

**Comment by NETdeve** [comment]
Thanks @sudopigeek
