### ISSUE TITLE
[Net] TCP Implementation

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1762]
This issue is dedicated to follow TCP work on CosmosOS. The initial pull request is https://github.com/CosmosOS/Cosmos/pull/1664

- [x] TCP Client
- [x] Fix double packet send problem (not fixed but bypassed)
- [x] SYN in
- [x] SYN out
- [x] SYN/ACK in
- [x] SYN/ACK out
- [x] ACK in
- [x] ACK out
- [x] FIN in
- [x] FIN out
- [x] FIN/ACK in
- [x] FIN/ACK out
- [x] PSH in
- [x] PSH out
- [x] Packet parsing tests
- [x] Documentation
- [x] Generate unique port
- [x] Packet sequencing
- [ ] Wait with RTT, don't hardcode values
- [ ] Check checksum from incoming packets
- [x] Split states computing into methods instead of one big receive method
- [x] Transmission Control Block
- [x] Connect to already opened connection (SYN out)

**Comment by AcaiBerii** [comment]
> This cause problems on receive packets: #1769

Well I guess it semi works still.
