### ISSUE TITLE
Filesystem Not Working On Actual Hardware

### ISSUE THREAD

**Issue by Liesar1** [CosmosOS/Cosmos#1771]
#### Area of Cosmos - What area of Cosmos are we dealing with?
The Cosmos Fat 32 Filesystem
System.IO
Cosmos.System.FileSystem

#### Expected Behaviour - What do you think that should happen?
The FAT 32 partition on the formatted hard drive should show up as 0, as a new partition.

#### Actual Behaviour - What unexpectedly happens?
The FAT 32 partition on the freshly formatted hard drive is not detected and shows the message Partition Not Found!

#### Reproduction - How did you get this error to appear?
When using          
   fs = new Sys.FileSystem.CosmosVFS();
   Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs); on actual hardware, this error shows up.

The hardware that I am using is an Alienware M17 Laptop from 2014.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using the most recent User Kit.

Here is the code that I am using:
[My Program.txt](https://github.com/CosmosOS/Cosmos/files/6462115/My.Program.txt)

**Comment by MishaTY** [comment]
What is the error?

**Comment by Liesar1** [comment]
![20210511_173320](https://user-images.githubusercontent.com/66841932/117892940-29fd7800-b27f-11eb-9477-c271b18cd863.jpg)

I have since fixed the set window size error.

**Comment by MishaTY** [comment]
Try enabling IDE emulation in the bios.

**Comment by Liesar1** [comment]
I just found out that I will probably not be able to use my pc for the rest of tonight, so I will not be able to reply to anything else tonight. Thanks for working with me to try and get this fixed!

**Comment by Liesar1** [comment]
I got back a little while ago and after fiddling around with some of the SATA settings, I got it to work with the ACHI setting.

**Comment by Liesar1** [comment]
Sorry to reopen this issue, but after further inspection, it seems that I can read from the hard drive just fine, however, any attempts to write to it cause the system to hang for >1 hour.

**Comment by quajak** [comment]
So to be clear, you got it finding a drive? Can you send a screenshot of the fs initialization output?

**Comment by Liesar1** [comment]
Sorry for the late reply, I have attached the picture of the filesystem below. One thing that I thought was off was that there are two filesystems that they were recognized even though there is only one FAT partition on the drive.
![20210513_153346](https://user-images.githubusercontent.com/66841932/118184457-0104f080-b401-11eb-8360-5d5fdc5fac9e.jpg)

**Comment by quajak** [comment]
Ok so it seems like the fact one is being incorrectly parsed (there should be a cluster coumt and a data sector count), which would explain why its failing to write are failing. Should the fs be fat32?

**Comment by Liesar1** [comment]
I formatted the hard drive as fat 32, using the Seagate DiscWizard program on another computer. Im not sure if that would cause the issue since im transfering from a different computer.

**Comment by quajak** [comment]
It can also be the case that Cosmos has some bug detecting the fat32 partition. The only way to fix this, would be if you have the devkit and we add some more logging to the filesystem initialization.

**Comment by DultzyWaltzy** [comment]
it isn't stale
