### ISSUE TITLE
string.split() does not work

### ISSUE THREAD

**Issue by virtualtoja** [CosmosOS/Cosmos#1774]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I dont know

#### Expected Behaviour - What do you think that should happen?
I tried using string.split() but it doesnt compile when i do that

#### Actual Behaviour - What unexpectedly happens?
It throws an error: "System.NotImplementedException: This is not implemented!"

#### Reproduction - How did you get this error to appear?
use string.split();

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
newest userkit

Also if string.split() is not working and theres no way to make it work what do i use as a replacement?

**Comment by valentinbreiz** [comment]
String.Split is working for me, could you send me a code snippet with your problem isolated?

**Comment by virtualtoja** [comment]
Yes

Code:
```
//code is a string looking like that: "command1;command2;command3"
string[] lines = code.Split(';');
//This function just reads all of the lines with foreach(line in lines) and executes them.
AppHelper.RunSystemCodes(lines);
```

**Comment by virtualtoja** [comment]
Ok it turns out that it was the function that made it not compile not code.split(). string.split() works fine
