### ISSUE TITLE
Unable to start debugging on vs2019

### ISSUE THREAD

**Issue by xxxMEMESCOEPxxx** [CosmosOS/Cosmos#1784]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugging

#### Expected Behaviour - What do you think that should happen?
Debugging should continue and start the debug engine

#### Actual Behaviour - What unexpectedly happens?
As soon as debugging begins I get an error that says "Unable to start debugging, the startup project cannot be started."

#### Reproduction - How did you get this error to appear?
The error appeared right after installation

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
CosmosUserKit-20200708-vs2019

**Comment by xxxMEMESCOEPxxx** [comment]
Found out that I forgot to install the .net core tools lol

**Comment by TizuHD** [comment]
> Found out that I forgot to install the .net core tools lol

I can't figure out how to install them, am I blind or something?
