### ISSUE TITLE
Can't access some of the List functions from class other than Kernel

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1786]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Collections/Lists (plugs maybe?)

#### Expected Behaviour - What do you think that should happen?
I should be able to access and use a list's functions (Add, Remove, Contains, etc..) in any class, when and where ever i want.

#### Actual Behaviour - What unexpectedly happens?
Whenever I try to use any of a list's functions in a class other than Kernel (the main one), the OS simply hangs. However, this is strange, because some functions appear to work (Add) and some don't (Remove, Contains).

#### Reproduction - How did you get this error to appear?
Create a separate class with a static List of what you want (like strings). Now, create another class with a function that will be calleed in the Kernel's Run() method, and in that custom function try to use some of the list's functions.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit (Cosmos 2815c84, X# 053ecc9, IL2CPU ee3f7d5)

**Comment by quajak** [comment]
Is this a duplicate of #1592 and #1595 ?

**Comment by AnErrupTion** [comment]
I didn't try IndexOf but this might be related to

**Comment by AnErrupTion** [comment]
Trying to set an object to null in the list (since I'm using a list with my own object) like this :
`list[i] = null;`
doesn't work and also freezes the OS.

**Comment by JuliusCaesar12** [comment]
What is the type of the objects in the list?

**Comment by quajak** [comment]
What is the generic type used for the list?

**Comment by AnErrupTion** [comment]
> What is the type of the objects in the list? Because perhaps you cannot create a null item like that. I would personally use List.Remove

I use a custom object (Window, I'm creating a Window Manager and I also have another list which is also a custom type, Button).



> What is the generic type used for the list?

None, they're custom. But I'm not creating any null objects.

**Comment by AnErrupTion** [comment]
By the way, .NET 5 doesn't solve the issue, so it's definitely a Cosmos, IL2CPU or X# issue (probably not an X# issue though).

**Comment by quajak** [comment]
So it seems like we have to investigate and expand upon the current list support and current testing.

**Comment by AnErrupTion** [comment]
So I tried again with the latest commits to see if anything changed, and now I'm getting this error on VMWare :

![Capture](https://user-images.githubusercontent.com/49339966/120824573-e124a080-c558-11eb-96c5-28e5c15f4d0c.PNG)

Here is the specified log :
[vmware.log](https://github.com/CosmosOS/Cosmos/files/6599516/vmware.log)

**Comment by GoldenretriverYT** [comment]
This is still happening, without Debugger it just hangs and with debugger it shows a NullReferenceException, which doesn't even lead you to your code but rather some lines in the Debugger code

**Comment by quajak** [comment]
If you have an issue with Dictionary please open a new issue with code to reproduce the issue.

**Comment by AnErrupTion** [comment]
Seems like this is fixed for me.
