### ISSUE TITLE
Website's Installation tutorial page does not open.

### ISSUE THREAD

**Issue by PranavKishan213** [CosmosOS/Cosmos#1787]

**Comment by raxracks** [comment]
can confirm, just stuck loading forever and has this message behind the loading screen
![image](https://user-images.githubusercontent.com/39295557/119301161-270a7a80-bcb6-11eb-937b-dcbc474f1b0f.png)

**Comment by MishaTY** [comment]
This is a known issue, and we are figuring out why its not working.

**Comment by Arawn-Davies** [comment]
Website has been fixed, a deprecated source code syntax highlighting plugin was the culprit
