### ISSUE TITLE
CPU exception x06 when defining bitmap

### ISSUE THREAD

**Issue by xxxMEMESCOEPxxx** [CosmosOS/Cosmos#1789]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Bitmap definition

#### Expected Behaviour - What do you think that should happen?
OS should not throw CPU exception

#### Actual Behaviour - What unexpectedly happens?
OS throws CPU exception when bitmap defined with byte array

#### Reproduction - How did you get this error to appear?
Defined bitmap with byte array

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user kit version 20200708

But if I remove the definition, everything works fine!

Screenshot of error:
https://drive.google.com/file/d/1D1t6CBfKIDQ-C2lVQN9rk876uIbTE6ex/view?usp=sharing

Here is my OS code (yes, I know it is very messy, and some code is terrible):

`

using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;
using System.Drawing;
using Cosmos.Core.IOGroup;
using System.IO;

namespace Cosmoslol
{
    public class Kernel : Sys.Kernel
    {
        private Bitmap cursorbmp;
        
        byte[] cursor; 
        
        //VGAScreen screen;
        Mouse mouse = new Mouse();

        Canvas canvas;
        
                Pen pen = new Pen(Color.Black, 10);
        public static VGAScreen screen = new VGAScreen();
        private uint ux = 1024;
        private uint uy = 768;
        private int x = 512;
        private int y = 384;
        //public static VGAScreen screen = new VGAScreen();

        //int x = 1;
        //int y = 1;

        public static bool mflag = false;
        //private static int x = 0;
        //private static int y = 0;
        Cosmos.HAL.VGADriver driverVGA = new Cosmos.HAL.VGADriver();
        //private static Sys.MouseState s = Sys.MouseState.None;
        protected override void BeforeRun()
        {
            
            Console.WriteLine("Loading Shell...");
            Console.WriteLine("[OK]");
            try
            {
                cursorbmp = new Bitmap(19, 32, new byte[] { 0x3f, 0xff, 0xe0, 0x5f, 0xff, 0xe0, 0x6f, 0xff, 0xe0, 0x77, 0xff, 0xe0, 0x7b, 0xff, 0xe0, 0x7d,
    0xff, 0xe0, 0x7e, 0xff, 0xe0, 0x7f, 0x7f, 0xe0, 0x7f, 0xbf, 0xe0, 0x7f, 0xdf, 0xe0, 0x7f, 0xef,
    0xe0, 0x7f, 0xf7, 0xe0, 0x7f, 0xfb, 0xe0, 0x7f, 0xfd, 0xe0, 0x7f, 0xfe, 0xe0, 0x7f, 0xff, 0x60,
    0x7f, 0xff, 0xa0, 0x7f, 0xe0, 0x00, 0x7f, 0xef, 0xe0, 0x7f, 0xf7, 0xe0, 0x7b, 0xf7, 0xe0, 0x75,
    0xfb, 0xe0, 0x6d, 0xfb, 0xe0, 0x5e, 0xfd, 0xe0, 0x3e, 0xfd, 0xe0, 0x7f, 0x7e, 0xe0, 0xff, 0x7e,
    0xe0, 0xff, 0xbf, 0x60, 0xff, 0xbf, 0x60, 0xff, 0xdf, 0x60, 0xff, 0xde, 0xe0, 0xff, 0xe1, 0xe0}, ColorDepth.ColorDepth32);
            }
            catch
            {
                canvas.Clear(Color.Red);
                canvas.Disable();
                Console.Clear();
                Console.WriteLine("CPU FAULT!");
            }
            
            Console.WriteLine("Initializing File System...");
            try
            {
                var fs = new Sys.FileSystem.CosmosVFS();
                Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            }
            catch
            {
                Console.WriteLine("Failed to initialize Filesystem!");
                return;
            }
            Console.WriteLine("[OK]");
            Console.WriteLine("[DONE]");
            Console.Clear();
            //Console.WriteLine("Installed RAM:" + Cosmos.Core.CPU.GetAmountOfRAM() + "MB");
            
            Console.WriteLine("Welcome to andOS! Type help for a list of commands");
            
            //Cosmos.System.Graphics.VGAScreen.PixelHeight = 640;
            //Cosmos.System.Graphics.VGAScreen.PixelWidth = 480;
            screen = new VGAScreen();
            //screen();
            //screen.Clear(0);
            //Cosmos.System.Graphics.VGACanvas;
        }
        string prevCMD = "";
        protected override void Run()
        {
            
            
            Console.Write(">> ");
            
            var input = Console.ReadLine();
            if(prevCMD == null)
            {

            }

            if(input == "hello")
            {
                Console.WriteLine("Hello User!");
            }
            else if (input == "shutdown")
            {
                Console.WriteLine("Shutting Down...");
                Sys.Power.Shutdown();
            }
            else if (input == "cls")
            {
                Console.Clear();
            }
            else if (input.StartsWith("write"))
            {
                if (File.Exists(input.Substring(6)))
                {
                    Console.WriteLine(File.ReadAllText(input.Substring(6)));
                }
                else
                {
                    try
                    {
                        File.Create(input.Substring(6));
                    }
                    catch
                    {
                        Console.WriteLine("Failed to create file " + "\"" + input.Substring(6) + "\"");
                    }
                }
                
                
            }
            else if (input == "reboot")
            {
                Console.WriteLine("Rebooting...");
                Sys.Power.Reboot();
            }
            else if (input == "prevcmd")
            {
                Console.WriteLine(prevCMD);
                
            }
            else if (input.StartsWith("echo"))
            {
                try
                {
                    Console.WriteLine(input.Substring(5));
                }
                catch
                {
                    Console.WriteLine("You need to specify a string. EX: echo hello world!");
                }
                

            }
            else if (input == "initNET")
            {
                Console.WriteLine("Initializing Network...");
                string ipaddr = Sys.Network.IPv4.Address.Broadcast.ToString();
                Console.WriteLine("IP ADDRESS: " + ipaddr);
            }
            else if(input == "initFS")
            {
                var fs = new Sys.FileSystem.CosmosVFS();
                Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

            }
            else if (input == "dl")
            {
                string[] filePaths = Directory.GetFiles(@"0:\");
                var drive = new DriveInfo("0");
                Console.WriteLine("Volume in drive 0 is " + $"{drive.VolumeLabel}");
                Console.WriteLine("Directory of " + @"0:\");
                Console.WriteLine("\n");
                for (int i = 0; i < filePaths.Length; ++i)
                {
                    string path = filePaths[i];
                    Console.WriteLine(System.IO.Path.GetFileName(path));
                }
                foreach (var d in System.IO.Directory.GetDirectories(@"0:\"))
                {
                    var dir = new DirectoryInfo(d);
                    var dirName = dir.Name;

                    Console.WriteLine(dirName + " <DIR>");
                }
                Console.WriteLine("\n");
                Console.WriteLine("        " + $"{drive.TotalSize}" + " bytes");
                Console.WriteLine("        " + $"{drive.AvailableFreeSpace}" + " bytes free");
            }
            else if (input == "GUI")
            {
                Pen pen2 = new Pen(Color.White, 50);
                
                pen2.Color = Color.White;
                pen.Color = Color.Green;
                pen.Width = 5;
                //canvas.DrawPoint(pen, Cosmos.System.MouseManager.X, Cosmos.System.MouseManager.Y);
                canvas = FullScreenCanvas.GetFullScreenCanvas();
                canvas.Clear(Color.White);

                Sys.MouseManager.ScreenHeight = uy;
                Sys.MouseManager.ScreenWidth = ux;

                

                int x25 = ((int)Sys.MouseManager.X - 25);
                int y25 = ((int)Sys.MouseManager.Y - 25);
                
                x = Convert.ToInt32(Sys.MouseManager.X);
                y = Convert.ToInt32(Sys.MouseManager.Y);
                Sys.Graphics.Point mousePos = new Sys.Graphics.Point(x, y);
                //System.Threading.Thread.Sleep(1000);
                //System.Drawing.Point mouseLocation = new System.Drawing.Point();
                int prevPosX = x;
                int prevPosY = y;
                bool ClearSCR = false;
                while (true)
                {

                    canvas.DrawFilledRectangle(pen2, mousePos, 10, 10);
                    if (prevPosX != x && prevPosY != y)
                    {
                        //canvas.Clear(Color.White);
                        canvas.DrawFilledRectangle(pen2, mousePos, 10, 10);
                        prevPosX = x;
                        prevPosY = y;
                        ClearSCR = false;
                    }
                    
                    //canvas.DrawFilledRectangle(pen2, mousePos, 50, 50);
                    //mDebugger.Send("x: " + Sys.MouseManager.ScreenWidth + " y: " + Sys.MouseManager.ScreenHeight);
                    //canvas.DrawFilledRectangle(pen2, mousePos, 50, 50);
                    x = Convert.ToInt32(Sys.MouseManager.X);
                    y = Convert.ToInt32(Sys.MouseManager.Y);
                    //mouseLocation = new System.Drawing.Point(x, y);
                    mousePos = new Sys.Graphics.Point(x, y);
                    
                    //mousePos.X = x;
                    //mousePos.Y = y;
                    mDebugger.Send("mouse x: " + x + " mouse y: " + y);

                    //Pen pen = new Pen(Color.Red);
                    //canvas.DrawCircle(pen, x, y, 5);
                    //canvas.Clear(Color.White);
                    /*canvas.DrawFilledRectangle(pen2, mousePos, 50, 50);
                    canvas.DrawLine(pen, x, y, x + 25, y);
                    canvas.DrawLine(pen, x, y, x, y - 25);
                    canvas.DrawLine(pen, x, y, x + 25, y - 25);
                    canvas.DrawFilledRectangle(pen2, mousePos, 50, 50);
                    //canvas.DrawFilledCircle(pen, mousePos, 5);
                    canvas.Clear(Color.White);*/
                    DrawGUI();
                    DrawMouse(Color.Red);
                    
                    

                }
                

                /*while (true)
                {
                    
                    Xpos = Convert.ToInt32(Sys.MouseManager.X);
                    Ypos = Convert.ToInt32(Sys.MouseManager.Y);

                    //canvas.Clear(Color.White);
                    //canvas.DrawLine(pen, Xpos, Ypos, Xpos + 100, Ypos + 100);
                    DrawMouse(Color.Red);
                }*/
                //System.Threading.Thread.Sleep(1000);

                //canvas.Clear(Color.Blue);
                Console.WriteLine("This Feature is not working yet!");

                /*canvas = FullScreenCanvas.GetFullScreenCanvas();
                Sys.MouseManager.ScreenHeight = 800;
                Sys.MouseManager.ScreenWidth = 600;

                while (true)
                {
                    canvas.Clear(Color.White);
                    pen = new Pen(Color.Black, 10);
                    Xpos = Convert.ToInt32(Sys.MouseManager.X);
                    Ypos = Convert.ToInt32(Sys.MouseManager.Y);
                    canvas.DrawCircle(pen, Xpos, Ypos, 5);
                }*/
                

            }
            else if (input == "help")
            {
                Console.WriteLine("\nhelp - Displays commands");
                Console.WriteLine("GUI - Displays OS GUI");
                Console.WriteLine("echo - Displays text in the console");
                Console.WriteLine("cls - Clears the console");
                Console.WriteLine("shutdown - shuts down the computer");
                Console.WriteLine("initNET - Initializes the network andprints the IP address");
                Console.WriteLine("dl - Directory Listing; Shows files and folders in the current directory");
                Console.WriteLine("write - creates/shows contents of files");
                Console.WriteLine("reboot - reboots the computer\n");
            }
            else if(input == "")
            {

            }
            else
            {
                Console.WriteLine("Command Not Found: " + input);
                if(input == "exit")
                {
                    Console.WriteLine("Did you mean \"shutdown\"?");
                }
            }
            prevCMD = input;
        }
        

        void DrawMouse(Color color) // Draws Mouse Cursor
        {
            
            Pen pen1 = new Pen(color);

            /*canvas.DrawLine(pen1, x, y,
                x + 6, y);
            canvas.DrawLine(pen1, x, y,
                x, y + 6);
            canvas.DrawLine(pen1, x, y,
                x + 6, y + 6);
            */

            //canvas.DrawImage(cursor, x, y);
            //Cosmos.System.Graphics.Image cursorIMG = ".\\cursor.png";
            
            
            
            canvas.DrawImage(cursorbmp, new Sys.Graphics.Point(x, y));
        }
        void DrawGUI()
        {
            // A red Point 
            //Pen pen = new Pen(Color.Black);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 30, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 130, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 220, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 320, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 420, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 520, 80, 60);
            //Button
            canvas.DrawFilledRectangle(pen, 40, 620, 80, 60);
        }

    }
    
}
`

**Comment by MishaTY** [comment]
The bitmap does not seem vaild. What format is the bitmap and what did you use to convert it to a byte array?

**Comment by xxxMEMESCOEPxxx** [comment]
I used https://javl.github.io/image2cpp/ to convert it to a byte array, and the file I used was a valid bmp

**Comment by MishaTY** [comment]
That tool converts the bitmap into a special format, and cannot be used with cosmos.

**Comment by xxxMEMESCOEPxxx** [comment]
Ahhhhh ok

How else would I convert the bmp into a byte array?

**Comment by MishaTY** [comment]
You can convert the file to base64 then you can put it into your kernel. Then you can use Convert.FromBase64("put base64 here") to get back the byte array.

**Comment by xxxMEMESCOEPxxx** [comment]
alright Thanks!
