### ISSUE TITLE
Unify MemoryBlock and ManagedMemoryBlock Interface

### ISSUE THREAD

**Issue by quajak** [CosmosOS/Cosmos#1796]
Currently the two have very different interfaces to access the underlying data. Since both classes represent something very similar, there is no real reason for this.

We should design the interface of the two classes so that they have the same interface.

**Comment by MishaTY** [comment]
Was this fixed in .net 5?

**Comment by quajak** [comment]
No, I dont think there has been no work done to refractor the two classes

**Comment by ADev531** [comment]
uhm, i was making something like this... i will search for that

**Comment by quajak** [comment]
I think performance was a reason to keep the two separate.
