### ISSUE TITLE
As a demo and stresstest, implement Z-machine interpreter

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#18]
See http://en.wikipedia.org/wiki/Z-machine for more info.

Working on this, you'll likely hit issues. Please contact us if so..

**Comment by MyvarHD** [comment]
I found some docs on the z machine and with FAT basicly here, we can make this work.
http://inform-fiction.org/zmachine/standards/z1point1/index.html

**Comment by MyvarHD** [comment]
I started studying the zork machine,  i will know by tonight i have the guts to do it lol

**Comment by MyvarHD** [comment]
I just read all the docs, and it not to bad i have written harder vm's before, but there are a few things that will not work in cosmos like sounds for example.

**Comment by ROBLOXVIP735** [comment]
This is still open.
That is an issue within itself.

**Comment by charlesbetros** [comment]
This "issue" is more of a story for someone to take on. GitHub only has issues and tags to categorize them so that's why it's open.

**Comment by czhower** [comment]
@MyvarHD 
Sound is not used in most games. We only need the oldest ZIL level support to run Zork etc and none of them have sounds.

**Comment by ROBLOXVIP735** [comment]
Alright then.

Still think this should be closed-I'm pretty sure this has already been added by now.

**Comment by charlesbetros** [comment]
It doesn't work.

**Comment by mihail-mojsoski** [comment]
Maybe you can check this project out:
https://frotznet.codeplex.com/

**Comment by czhower** [comment]
We have already looked at that and several others. Many of them use dynamic code gen which presents a problem currently.

**Comment by charlesbetros** [comment]
We have frotz in our solution. Someone took a run at it but ran in to an issue reading from storage. That issue is fixed, but no one has picked it up again.

**Comment by MichaelTheShifter** [comment]
I was the one who did the original port - and yes I basically abandoned it
- not enough time to work on it right now. Feel free to try it out and
diagnose it if you want.
