### ISSUE TITLE
I can't install VS2015 DevKit

### ISSUE THREAD

**Issue by asterd-og** [CosmosOS/Cosmos#1802]
**Description**
I can't install VS2015 DevKit. It give me an error

**Steps of installation up to now**
Install devkit 2015 and run it

**Logs**
https://pastebin.com/1fqsBawv

**Setup**
 - Cosmos Version=Devkit20150918
 - Are you using an admin account?=Yes
 - VS Version if applicable=2015

**Comment by zarlo** [comment]
Devkit20150918 is a ever old build and will not likely get any support

**Comment by MishaTY** [comment]
The 2015 devkit is not supported anymore.
