### ISSUE TITLE
Does someone have a compiled version of devkit2015/2016?

### ISSUE THREAD

**Issue by asterd-og** [CosmosOS/Cosmos#1805]
i want to make graphics and filesystem in my OS, but the userkit don't have that... and why am i trying to get the devkit of 2015/2016? well, it is because of my visual studio, i can't install devit/userkit for vs2017 and vs2019...

**Comment by AnErrupTion** [comment]
So you can't install the devkit for VS2017 and VS2019, and you try to install an even older one... we can't provide support for old devkit/userkit versions. Open an issue about the problem you're having installing the latest devkit, and we'll help you. Otherwise we will not.

**Comment by MishaTY** [comment]
We do not provide support for old Cosmos versions, like @AnErrupTion said

**Comment by asterd-og** [comment]
> So you can't install the devkit for VS2017 and VS2019, and you try to install an even older one... we can't provide support for old devkit/userkit versions. Open an issue about the problem you're having installing the latest devkit, and we'll help you. Otherwise we will not.

i already did it (#1793), but i still can't solve that

**Comment by Arawn-Davies** [comment]
@asterd-og We're not going to give you an older version of the devkit because it isn't supported. 
The latest userkit and devkit only support Visual Studio 2019, nothing lower. Make sure you've installed all the dependencies, try installing the userkit and then see if you continue to have issues.
