### ISSUE TITLE
Exception: 0:\Root.txt was found, but is not a file.

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#1806]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File system

#### Expected Behaviour - What do you think that should happen?
I should be able to read the files Kudzu.txt and Root.txt in the root path.

#### Actual Behaviour - What unexpectedly happens?
I get the exception from the title for both Kudzu.txt and Root.txt.

#### Reproduction - How did you get this error to appear?
I used this exact piece of code in the Run() method, after properly initializing my file system :
```C#
try
{
    var hello_file = fs.GetFile(@"0:\Kudzu.txt"); // can also be 0:\Root.txt
    var hello_file_stream = hello_file.GetFileStream();

    if (hello_file_stream.CanRead)
    {
        byte[] text_to_read = new byte[hello_file_stream.Length];
        hello_file_stream.Read(text_to_read, 0, text_to_read.Length);
        foreach (char ch in text_to_read)
        {
              Console.Write(ch.ToString());
        }
    }
}
catch (Exception e)
{
    Console.WriteLine(e.ToString());
}
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit latest commits from branches netcoreapp2.1 and net5 (Cosmos, IL2CPU, X# and Common)

**Comment by AnErrupTion** [comment]
The strange thing is that if I read all files from the root directory, the Root.txt and Kudzu.txt and their contents show up in the standard output.

**Comment by AnErrupTion** [comment]
This seems to also occur for the files I create. I can create and write to them successfully, but I can't read them. It throws the same exception.

**Comment by Arawn-Davies** [comment]
Looks like GetFileStream and Stream-related methods are failing, while ReadAllText, ReadAllLines, and ReadAllBytes are working just fine.

I've never used .NET Streams in my own code before, and I can't tell you the current status of their impl in Cosmos, but for now until more investigation is done, I'd use the other methods where applicable :)

**Comment by AnErrupTion** [comment]
It's actually GetFile() that fails, because in CosmosVFS.cs it's the method that returns this exception if the method fails.

**Comment by Arawn-Davies** [comment]
What's the exact exception that's being thrown? Something's definitely not right because I tried your code in my kernel (still using latest devkit commits) and it's worked just fine, no exceptions being thrown at all

code:
![image](https://user-images.githubusercontent.com/19764552/120925893-962e9880-c6d2-11eb-8277-8d8a03bbae1c.png)

result:
![image](https://user-images.githubusercontent.com/19764552/120925901-9cbd1000-c6d2-11eb-9cbb-b0f0afec2051.png)

**Comment by MishaTY** [comment]
It's probably because @AnErrupTion is using the .NET 5 branch.

**Comment by AnErrupTion** [comment]
I'm actually not using it anymore. Also I'm initializing the VFS in the BeforeRun() function. The exact exception that's being thrown in the one from the title.

**Comment by AnErrupTion** [comment]
Well, same error with regular Dev Kit.

**Comment by AnErrupTion** [comment]
Ok nevermind, seems to work for now. I'll tell if anything gets screwed up, but because it worked for Arawn, it's probably because my code doesn't work, I'll see.
