### ISSUE TITLE
Waiting for debugger connection with turned off debug

### ISSUE THREAD

**Issue by m4dc1t4** [CosmosOS/Cosmos#1808]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building the ISO(sorry for my english, i'm from russia)

#### Expected Behaviour - What do you think that should happen?
It should boot normally

#### Actual Behaviour - What unexpectedly happens?
I get "Waiting for debugger connection", even with turned off debug mode

#### Reproduction - How did you get this error to appear?
Build a release version ISO with DebugEnable disabled

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Last version of User Kit

**Comment by AnErrupTion** [comment]
Go to your Cosmos project's properties, go to the Cosmos (new) tab, uncheck "Enable debug" and press Ctrl + S.

**Comment by m4dc1t4** [comment]
So, I fixed it! I just changed DebugEnabled in one place. Sorry for disturbance.
