### ISSUE TITLE
Errors in starter example

### ISSUE THREAD

**Issue by mathsy** [CosmosOS/Cosmos#1809]
When I start the starter example, this errors come around. (Sorry, some errors are german)

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0246	Der Typ- oder Namespacename "Cosmos" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\Kernel.cs	4	Aktiv
Fehler	CS0115	'"Kernel.BeforeRun()": Es wurde keine passende Methode zum Überschreiben gefunden.	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\Kernel.cs	10	Aktiv
Fehler	CS0115	'"Kernel.Run()": Es wurde keine passende Methode zum Überschreiben gefunden.	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\Kernel.cs	15	Aktiv
Fehler	NU1101	Das Paket "Cosmos.Debug.Kernel" wurde nicht gefunden. Es sind keine Pakete mit dieser ID in folgenden Quellen vorhanden: Microsoft Visual Studio Offline Packages, nuget.org	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\CosmosKernel4.csproj	1	
Fehler	NU1101	Das Paket "Cosmos.System2" wurde nicht gefunden. Es sind keine Pakete mit dieser ID in folgenden Quellen vorhanden: Microsoft Visual Studio Offline Packages, nuget.org	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\CosmosKernel4.csproj	1	
Fehler	NU1101	Das Paket "Cosmos.Build" wurde nicht gefunden. Es sind keine Pakete mit dieser ID in folgenden Quellen vorhanden: Microsoft Visual Studio Offline Packages, nuget.org	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\CosmosKernel4.csproj	1	
Fehler		NETSDK1056: Das Projekt ist auf die Runtime "cosmos" ausgelegt, aber hat keine runtimespezifischen Pakete aufgelöst. Diese Runtime wird vom Zielframework möglicherweise nicht unterstützt.	CosmosKernel4	C:\Users\raber\source\repos\CosmosKernel4\CosmosKernel4.csproj	1	
Fehler		Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.	CosmosKernel4	C:\Users\raber\.nuget\packages\microsoft.netcore.app\2.0.9\build\netcoreapp2.0\Microsoft.NETCore.App.targets	19

**Comment by AnErrupTion** [comment]
You need to install Cosmos and .NET Core properly.

**Comment by mathsy** [comment]
Well, I installed VS 2019 just like normal software. I downloaded CosmosOS and VMWare and installed it per installer executable. 

So everything has to be right in that case (in my opinion)

**Comment by quajak** [comment]
Are the two VS extensions installed? It looks like the local package source is missing.

**Comment by Arawn-Davies** [comment]
This issue appears to be a duplicate of #1420 


> Well, I installed VS 2019 just like normal software. I downloaded CosmosOS and VMWare and installed it per installer executable.
> 
> So everything has to be right in that case (in my opinion)

It's not just VS 2019 that you need, however. You need to install these dependencies as the website clearly states
![image](https://user-images.githubusercontent.com/19764552/121664294-3ef84180-ca9f-11eb-90b0-17e05def7b54.png)

If these are installed, then your project isn't restoring the NuGet packages correctly
