### ISSUE TITLE
Cannot Create Project

### ISSUE THREAD

**Issue by accurateisaiah** [CosmosOS/Cosmos#1810]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Making a project

#### Expected Behaviour - What do you think that should happen?
it should make the project

#### Actual Behaviour - What unexpectedly happens?
It says it cannot locate the .NET sdk.

#### Reproduction - How did you get this error to appear?
I just created a project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit - Cosmos

**Comment by quajak** [comment]
You need to install the .net sdk 2.0

**Comment by accurateisaiah** [comment]
It's still not working. Maybe because VS studio is installed on my E drive?

**Comment by quajak** [comment]
Without the exact error message I dont know but I doubt that vs installation location is the problem.

**Comment by Arawn-Davies** [comment]
What versions of .NET have you installed? Please make sure you have installed every dependency

**Comment by accurateisaiah** [comment]
I'm not sure
but I installed what it told me.
might as well not use it lol

**Comment by Arawn-Davies** [comment]
You might be missing .NET Core 2.1, could you try installing this? 

https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-2.1.816-windows-x64-installer

We are in the process of updating the website and documentation so apologies if we missed it out!

**Comment by accurateisaiah** [comment]
Thanks, It worked!
