### ISSUE TITLE
Keyboard doesn't work on a real machine

### ISSUE THREAD

**Issue by m4dc1t4** [CosmosOS/Cosmos#1812]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running the OS on a real PC

#### Expected Behaviour - What do you think that should happen?
My keyboard should work

#### Actual Behaviour - What unexpectedly happens?
It just doesn't work and I can't type anything

#### Reproduction - How did you get this error to appear?
I was trying to run my OS on my PC

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708

**Comment by quajak** [comment]
Currently only PS/2 keyboards are supported. Some BIOS allow USB to PS/2 translation.

**Comment by quajak** [comment]
Ah, I assumed you were using a USB keyboard :) 
The userkit still has the problem with the PS/2 not supported exception. To get around that you will sadly need to use the devkit.
