### ISSUE TITLE
the cosmos namespace was not found

### ISSUE THREAD

**Issue by kingofsponges** [CosmosOS/Cosmos#1817]
#### Area of Cosmos - What area of Cosmos are we dealing with?
cosmos namespace

#### Expected Behaviour - What do you think that should happen?
basically work perfectly without any errors and stuff

#### Actual Behaviour - What unexpectedly happens?
i have like 7 (visual studio shows 3 when list closed) errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Cosmos.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\SpongeOS.csproj	1	
Error	NU1101	Unable to find package Cosmos.System2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\SpongeOS.csproj	1	
Error	NU1101	Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\SpongeOS.csproj	1	
Error	CS0115	'Kernel.Run()': no suitable method found to override	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\Kernel.cs	15	Active
Error	CS0115	'Kernel.BeforeRun()': no suitable method found to override	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\Kernel.cs	10	Active
Error	CS0246	The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)	SpongeOS	C:\Users\qpate\source\repos\SpongeOS\SpongeOS\Kernel.cs	4	Active
```

#### Reproduction - How did you get this error to appear?
just creating a cosmos kernel project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user kit, 2020.07.08

**Comment by quajak** [comment]
Have you looked at https://github.com/CosmosOS/Cosmos/issues/1420 ?

**Comment by Arawn-Davies** [comment]
Did it work? please close the issue if it did

**Comment by Arawn-Davies** [comment]
Duplicate of #1420

**Comment by kingofsponges** [comment]
also @Arawn-Davies, you can't confirm this is a duplicate without evidence that i have the same problem.

**Comment by quajak** [comment]
Have you been able to install the nuget pacakges?

**Comment by kingofsponges** [comment]
i'm reinstalling cosmos for the [insert which time i am doing it because i don't know]th time, wait

**Comment by kingofsponges** [comment]
wait hold on just trying to compile it and run it on qemu

**Comment by kingofsponges** [comment]
oh right forgot that qemu is kinda broken so i'll try reinstalling it

**Comment by quajak** [comment]
Qemu or cosmos? So is cosmos working now?

**Comment by kingofsponges** [comment]
i had to reinstall qemu or something

alright it works, issue closed.

**Comment by Arawn-Davies** [comment]
> also @Arawn-Davies, you can't confirm this is a duplicate without evidence that i have the same problem.

Evidence that you're having the same problem as other people is the error that you're getting. It's a duplicate. Once you're having another issue, open a new issue and don't continue changing the subject of this one. Thank you.

**Comment by kingofsponges** [comment]
@Arawn-Davies issue closed. no comments.
