### ISSUE TITLE
Cosmos folder not showing up in %appdata%

### ISSUE THREAD

**Issue by SecretAgent-YT** [CosmosOS/Cosmos#1819]
The data folder is not showing up, I am trying to install cosmos debug engine.

**Comment by quajak** [comment]
Are you installing from the admin user? Did you select the correct app data folder during installation?

**Comment by Arawn-Davies** [comment]
@SecretAgent-YT You've not given hardly any information as to what the problem is. Please give a more detailed output as to what is happening.
