### ISSUE TITLE
User Kit falsely claims VS2013 is installed

### ISSUE THREAD

**Issue by thoralmighty** [CosmosOS/Cosmos#183]
When attempting to install the User Kit 20150130 on Windows 8.1 Pro x64, there's an error message after language selection that claims either Visual Studio 2013 or it's integrated shell is installed. I'm aware the kit requires VS2015 and the 2013 edition was indeed installed on the first occasion, however after uninstalling and replacing it with 2015 Express for Desktop, the error still appears.

![image](https://cloud.githubusercontent.com/assets/4562605/9145913/a10b88b2-3d58-11e5-9a7d-5b999dac21e6.png)

As an extra precaution, 2015 was uninstalled again. I then went through both files and registry deleting all references to Visual Studio, no change to symptoms.

**Comment by zdimension** [comment]
In fact, there's a typo in the message.
What you need to understand is "Either Visual Studio 2013  or Visual Studio 2013 (integrated shell) is **NOT** installed!"
In fact, when this userkit was built, Cosmos didn't support VS2015, it only supported 2013. So it seems that the userkit is only compatible with 2013.

**Comment by thoralmighty** [comment]
Aaah, I see. So it should be "neither" rather than "either"... Okay, that's a start.
Isn't 20150130 the latest kit though? It's what I get when clicking "Latest release", and it wouldn't install even when I still had VS2013 on my system. Additionally, the Getting Started guide clearly states, "Visual Studio 2013 and older are no longer supported."

**Comment by zdimension** [comment]
Yes but the Getting Started guide is more recent than the Userkit. So you need to wait for the next userkit, or download the devkit (which is nearly the same as the userkit, you only need to run a program to install it as userkit)

**Comment by mterwoord** [comment]
@thoralmighty Is this issue "solved"? If so, please close this issue. Thanks.

**Comment by thoralmighty** [comment]
Not necessarily solved as per the original issue, but I'll say that if you do experience these symptoms, try using the devkit. Closing.
