### ISSUE TITLE
Cosmos reference have a warning icon, and can't build project.

### ISSUE THREAD

**Issue by FreeBSoD** [CosmosOS/Cosmos#1834]
Have you checked Github Issues for similar errors?
Yes, but the answers do not fix it.
**Exception**
Post the exception returned by Visual Studio

NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.	Ramenen	C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj	1	

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: Ramenen, Configuration: Debug Any CPU ------
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103: Unable to find a stable package Cosmos.Debug.Kernel with version 
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 1 version(s) in Cosmos Local Package Feed [ Nearest version: 0.1.0-localbuild20200708061311 ]
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in nuget.org
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103: Unable to find a stable package Cosmos.System2 with version 
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 1 version(s) in Cosmos Local Package Feed [ Nearest version: 0.1.0-localbuild20200708061311 ]
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in nuget.org
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103: Unable to find a stable package Cosmos.Build with version 
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 1 version(s) in Cosmos Local Package Feed [ Nearest version: 0.1.0-localbuild20200708061311 ]
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error NU1103:   - Found 0 version(s) in nuget.org
1>C:\Users\milan\source\repos\Ramenen\Ramenen\Ramenen.csproj : error : NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
1>Done building project "Ramenen.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
I did not change anything.
**Context**
Before posting please confirm that the following are in order
[Yes] Both Cosmos VS Extensions are installed
[Yes] The Cosmos nuget packages are installed

I cannot build it because the NuGet packages have an warning icon

**Comment by quajak** [comment]
> [Yes] The Cosmos nuget packages are installed

This is impossible since the error is that it cant find a stable version of the packages, so they cant be installed. To select Allow Prereleases in the Nuget Package Manager.

**Comment by TRex-Code** [comment]
> > [Yes] The Cosmos nuget packages are installed
> 
> This is impossible since the error is that it cant find a stable version of the packages, so they cant be installed. To fix select Include Prereleases in the Nuget Package Manager.

That does not fix it

**Comment by quajak** [comment]
Were you then able to install the packages?

**Comment by JuliusCaesar12** [comment]
I was able to reproduce this by removing the versions completely from one of the items in the package section of my .csproj file.
For reference, here is that section:
![Screenshot (72)](https://user-images.githubusercontent.com/44103262/122218597-37a4af80-ce74-11eb-9ce9-69a648e376b7.png)
 The versions should all be 0-*

**Comment by TRex-Code** [comment]
> I was able to reproduce this by removing the versions completely from one of the items in the package section of my .csproj file.
> For reference, here is that section:
> ![Screenshot (72)](https://user-images.githubusercontent.com/44103262/122218597-37a4af80-ce74-11eb-9ce9-69a648e376b7.png)
> The versions should all be 0-*

Thanks! It worked!

**Comment by TRex-Code** [comment]
It does not work anymore, I still have it as 0-*

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1500
