### ISSUE TITLE
cosmos os keeps going back to the original code not the new one and when i try to make a gui it keeps on giving me errors  

### ISSUE THREAD

**Issue by awipslinuxuser** [CosmosOS/Cosmos#1839]

**Comment by MishaTY** [comment]
What are the errors? What do you mean by "going back to the original code not the new one" Are you using the devkit or the userkit

**Comment by awipslinuxuser** [comment]
like when im using using Cosmos.Hardware;   VGAScreen screen: screen = new VGAScreen();
screen.SetMode320x200x8();
screen.Clear(0);
screen.SetPixel320x200x8(uint x, uint y, uint c);
and when i deleted the code when you first start cosmos it still booted the original code ps im using vmware workstation player 16 and the latest release of cosmos and all the recommend software in the list

**Comment by awipslinuxuser** [comment]
and here is one of the codes im tying to use and it does the same thing https://www.instructables.com/Make-A-Simple-Operating-System/

**Comment by awipslinuxuser** [comment]
and here is all my errors 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8370	Feature 'top-level statements' is not available in C# 7.3. Please use language version 9.0 or greater.	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	1	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	4	Active
Error	CS0234	The type or namespace name 'Sys' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?)	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	11	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	21	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	23	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	33	Active
Error	CS0234	The type or namespace name 'Sys' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?)	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	42	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	51	Active
Error	CS0103	The name 'Console' does not exist in the current context	OSCAROSV1	C:\Users\awips\source\repos\OSCAROSV1\OSCAROSV1\Kernel.cs	59	Active
Warning	NETSDK1138	The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.	OSCAROSV1	C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets	28

**Comment by MishaTY** [comment]
> like when im using using Cosmos.Hardware; VGAScreen screen: screen = new VGAScreen();
> screen.SetMode320x200x8();
> screen.Clear(0);
> screen.SetPixel320x200x8(uint x, uint y, uint c);
> and when i deleted the code when you first start cosmos it still booted the original code ps im using vmware workstation player 16 and the latest release of cosmos and all the recommend software in the list

That code is old and won't work. See [the wiki](https://github.com/CosmosOS/Cosmos/wiki/GUI) about how to create a gui.
