### ISSUE TITLE
VMWare required but not installed.

### ISSUE THREAD

**Issue by AcaiBerii** [CosmosOS/Cosmos#1841]
Have you checked Github Issues for similar errors?
Yes

**Exception**
Post the exception returned by Visual Studio
No exception from visual studio. Only exceptions during runtime.

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
Computer having networking issues.

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Literally just debug the kernel.

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[x] Both Cosmos VS Extensions are installed
[x] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.
Vmware wasn't installed during the user kit setup process and couldn't be found during debugging.

**Comment by JuliusCaesar12** [comment]
Did you, yourself, install VMWare Player or did you not?

**Comment by AcaiBerii** [comment]
I didn't. Thank you for the help.
