### ISSUE TITLE
Annoying errors when building or debugging a kernel.

### ISSUE THREAD

**Issue by AcaiBerii** [CosmosOS/Cosmos#1842]
Have you checked Github Issues for similar errors?
yes

**Exception** 
Please check screenshots.

**VS Output Logs**
I cannot access the logs because the error froze visual studio. The logs didn't have much helpful information otherwise. The exception only occured during debugging.
                                        
**To Reproduce**
Simply make a new cosmos kernel and run it.

**Screenshots**
https://ibb.co/nmmbW1k https://ibb.co/rpH9jds

**Context**
Before posting please confirm that the following are in order
- [x] Both Cosmos VS Extensions are installed
- [x] The Cosmos nuget packages are installed

Add any other context about the problem which might be helpful.

- I'm running this on an x64 device running Windows 10.

- Although I was previously running the latest userkit, this problem also continues into the latest devkit.

- The error informs me that it cannot access a .cdb file that was clearly in my build folder.

**Comment by MishaTY** [comment]
It looks like some program is using the iso, try to restart your computer.

**Comment by AcaiBerii** [comment]
@MishaTY Doesn't work.

**Comment by AcaiBerii** [comment]
I got the iso build to kinda work but no /bin/ folder is generated. Cosmos strong.

**Comment by quajak** [comment]
How did you get the iso to build without a bin folder?

**Comment by AcaiBerii** [comment]
I have no idea.

**Comment by AcaiBerii** [comment]
After building and installing the devkit, debugging no longer works at all.

**Comment by AcaiBerii** [comment]
https://ibb.co/nmmbW1k
https://ibb.co/rpH9jds
