### ISSUE TITLE
Fatal Memory Management Problem(Freeze)

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1844]
# Heap.MemAlloc(uint aSize) calls every time. but no free. It cause system to freeze.(Out of memory)

**Comment by nifanfa** [comment]
System stuck when calling update

**Comment by quajak** [comment]
I thought we fixed that, are you on the newest devkit?

**Comment by nifanfa** [comment]
> I thought we fixed that, are you on the newest devkit?

no

**Comment by nifanfa** [comment]
@quajak I can't build the newest cosmos can you build it for me?
![QQ截图20210621184653](https://user-images.githubusercontent.com/54205437/122750427-118e6d80-d2c1-11eb-8839-baab8e16653b.png)

**Comment by nifanfa** [comment]
![QQ截图20210621190353](https://user-images.githubusercontent.com/54205437/122752365-71861380-d2c3-11eb-9985-3a08c440fb4f.png)

**Comment by nifanfa** [comment]
@quajak  the system still crashes within a minute

**Comment by nifanfa** [comment]
![QQ截图20210621191334](https://user-images.githubusercontent.com/54205437/122753431-d5f5a280-d2c4-11eb-9bd8-75aced09c5f6.png)

**Comment by nifanfa** [comment]
![QQ截图20210621191643](https://user-images.githubusercontent.com/54205437/122753716-3ab0fd00-d2c5-11eb-906b-2fdc16761c1d.png)

**Comment by nifanfa** [comment]
The code like this will crash in a few minutes

**Comment by nifanfa** [comment]
This can be discovered hardly if Remote Debugging enabled

**Comment by quajak** [comment]
Yes the problem in this case is that Garbage Collection is currently still missing. I am currently working on fixing that.

**Comment by AcaiBerii** [comment]
Congratulations, I can't even get Cosmos Kernels to run with the latest devkit!

**Comment by nifanfa** [comment]
![GIF 2021-6-22 15-14-21](https://user-images.githubusercontent.com/54205437/122918712-fccdda80-d391-11eb-86eb-357c1abb6c58.gif)

**Comment by nifanfa** [comment]
Heap.MemAlloc calls every time. but no free. It cause system to freeze.

**Comment by nifanfa** [comment]
by the way system always calls heap.memalloc(16) i don't know what does 16 mean

**Comment by nifanfa** [comment]
> Yes the problem in this case is that Garbage Collection is currently still missing. I am currently working on fixing that.

I think you should not try to implement GC now. You should find a way to release an object. It's more simple than GC and it can actually solve this problem.

**Comment by nifanfa** [comment]
If you want to implement GC, you need to find a way to check whether something has accessed the variable. It's so hard

**Comment by nifanfa** [comment]
and i guess it will reduce the efficiency

**Comment by nifanfa** [comment]
just free the object and tell system that the area can be used again

**Comment by AcaiBerii** [comment]
@nifanfa 
heap.memalloc(16) allocates 16 bytes to a heap, from what I can tell. The documentation for memory management is very unclear.

**Comment by nifanfa** [comment]
> @nifanfa
> heap.memalloc(16) allocates 16 bytes to a heap, from what I can tell. The documentation for (memory?) management is very unclear.
> I guess a way to fix it would be to make an event that fires when a heap is made and the memory is allocated. Tell if that heap is being used by a process and if it isn't just free it from the memory.

I know through the test

**Comment by nifanfa** [comment]
i don't read the documentation actually

**Comment by nifanfa** [comment]
> @nifanfa
> heap.memalloc(16) allocates 16 bytes to a heap, from what I can tell. The documentation for (memory?) management is very unclear.
> I guess a way to fix it would be to make an event that fires when a heap is made and the memory is allocated. Tell if that heap is being used by a process and if it isn't just free it from the memory.

yes. it easy to achieve. but you must know which method called this method to allocate memory and dispose the 
useless object. through the test i know that almost everytime there will be 23 objects created. you need to know what is that.but how

**Comment by nifanfa** [comment]
just free is useless. because heap.free just calls the CPU.ZeroFill it doesn't tell system that the area can be used again.

**Comment by nifanfa** [comment]
before solving this problem. it is impossible to make a GUI OS. because the memory management problem. the GUI will cause the system crashes within a few minutes even worse (disable the Debug mode fps>60)

**Comment by JuliusCaesar12** [comment]
Ah, the joys of paging!
From what I read, for a page to be reused, the index of said page needs to be set to zero, or the page needs to be marked unused.
From what I've parsed in the RAT, the pages can be reused after they are set to empty, and the heap is only set to free large heaps. So, perhaps that's the issue?

**Comment by nifanfa** [comment]
> Ah, the joys of paging!
> From what I read, for a page to be reused, the index of said page needs to be set to zero, or the page needs to be marked unused.
> From what I've parsed in the RAT, the pages can be reused after they are set to empty, and the heap is only set to free large heaps. So, perhaps that's the issue?
> Edit: wait, you're using the old heap, which doesn't allocate with the RAT.

yes the cosmos still use the old heap

**Comment by nifanfa** [comment]
please view Cosmos.Core.GCImplememt

**Comment by JuliusCaesar12** [comment]
It seems as though the GCImplementation is just creating a new Old.Heap every time one asks it to allocate a new object, which, as the old heap was created, just creates a new area in memory to be written to without the use of a directory, a free-able page, or the likes because it is quick and simple. Perhaps a section of the RAT should be created to handle Garbage Collection with rewritable pages?

**Comment by nifanfa** [comment]
we just need to create a method to free objects. we don't actually need GC i think

**Comment by JuliusCaesar12** [comment]
I concur because for what I have seen elsewhere, the reason the system crashes when doing absolutely nothing or just writing the system runtime was from editing memory too quickly (which could probably be solved with GC). The way I know of to fix it is to literally increase the execution time of Run() or delay its loop. 

In a recent project, I used the old Heap for static things like a VGA second buffer due to it's rewritable functionality.

**Comment by nifanfa** [comment]
> I concur because for what I have seen elsewhere, the reason the system crashes when doing absolutely nothing or just writing the system runtime was from editing memory too quickly (which could probably be solved with GC). The way I know of to fix it is to literally increase the execution time of Run() or delay its loop.
> 
> In a recent project, I used the old Heap for static things like a VGA second buffer due to it's rewritable functionality.

No Man. in command line. system will stop on Console.ReadLine to wait for command. that will stop system to create new object. so the system will not crash so fast

**Comment by quajak** [comment]
There is a PR to rework memory management, which already supports free and I am working on having an actually ref counting GC working.

**Comment by AcaiBerii** [comment]
As long as you have a "free" method you can just use events.

**Comment by nifanfa** [comment]
This Problem Hasn't Resolved

**Comment by MishaTY** [comment]
Fixed by: #1734

**Comment by MishaTY** [comment]
Fixed

**Comment by nifanfa** [comment]
Doesn't  really matter for me now
