### ISSUE TITLE
Does this work on rider for kubuntu 20.04?

### ISSUE THREAD

**Issue by Shadowblitz16** [CosmosOS/Cosmos#1848]
Does this work for rider and kubuntu 20.04?

**Comment by AcaiBerii** [comment]
No. Unless you use wine, this can't run on Linux without Visual Studio.

**Comment by Picoseconds** [comment]
No, but not because COSMOS requires Visual Studio (it doesn't) but because there are many native dependencies such as nasm (which could be compiled for Linux)

**Comment by AcaiBerii** [comment]
> No, but not because COSMOS requires Visual Studio (it doesn't) but because there are many native dependencies such as nasm (which could be compiled for Linux)

Huh? https://cosmosos.github.io/articles/GettingStarted.html
COSMOS is used with Visual Studio and doesn't really work with anything else.

**Comment by quajak** [comment]
IL2CPU only works under Windows. You technically dont need VS though.
