### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by VoxelDeveloperDavid** [CosmosOS/Cosmos#1853]
When i try to update Cosmos with the installer(new gui) it says System.UnathorizedAccessException: Access To the path ".nupkg.metadata" Got Denied how can i fix that?

**Comment by quajak** [comment]
Have you tried running as admin?

**Comment by quajak** [comment]
Also can you please post the entire log?

**Comment by quajak** [comment]
@MishaTY Do you have any idea what is going on?

**Comment by MishaTY** [comment]
Maybe something is using it?

**Comment by VoxelDeveloperDavid** [comment]
> Maybe something is using it?

no already checked it
