### ISSUE TITLE
Interacting with FileSystem freezes VM

### ISSUE THREAD

**Issue by AcaiBerii** [CosmosOS/Cosmos#1855]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos FAT32

#### Expected Behaviour - What do you think that should happen?
Interactions with filesystem do not freeze the OS

#### Actual Behaviour - What unexpectedly happens?
All interactions with the file system freeze the operating system.

#### Reproduction - How did you get this error to appear?
Add any method that uses the file system to run, such as "Directory.GetFiles(@"C:\");" to your BeforeRun() method.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit, using pull request #1845 (does not affect Cosmos other than implementing BitFonts) with commit f8cfd08d76aaf8160db5cba2d996e73bc9d4045e. Uses #1845's release of X# and IL2CPU.

#### Additional info
https://youtu.be/cNt8bizy-us

**Comment by Arawn-Davies** [comment]
Have you definitely initialized the filesystem before using any System.IO methods?
```
Sys.FileSystem.CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
```
make sure this line is in Kernel.cs before BeforeRun() and make sure the following line:
```
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```
is inside the BeforeRun() method

**Comment by MishaTY** [comment]
Also use 0:\ instead of C:

**Comment by AcaiBerii** [comment]
Oh.

**Comment by quajak** [comment]
Did that fix it?

**Comment by AcaiBerii** [comment]
Yes it fixed it.
