### ISSUE TITLE
No partitions found!

### ISSUE THREAD

**Issue by LeonTheDev** [CosmosOS/Cosmos#1866]
#### Area of Cosmos - What area of Cosmos are we dealing with?

File Systems

#### Expected Behaviour - What do you think that should happen?

Not give me an error

#### Actual Behaviour - What unexpectedly happens?

"No partitions found!" is printed when the computer starts. (I am trying to get this to work on real hardware)

#### Reproduction - How did you get this error to appear?

private CosmosVFS vfs;

this.vfs = new CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(this.vfs);

(Run it on real hardware)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I don't know

**Comment by valentinbreiz** [comment]
Hello, what is your disk SATA and in which mode IDE, AHCI, RAID?

**Comment by LeonTheDev** [comment]
> Hello, is your disk SATA and in which mode IDE, AHCI, RAID?

I'm not sure how to check

**Comment by terminal-cs** [comment]
> Hello, is your disk SATA and in which mode IDE, AHCI, RAID?

+
