### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error		Exception: System.Exception: Error while generating output for file AsmBreak.xs ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files\CosmosUserKit-20200708-vs2019\XSharp\DebugStub\AsmBreak.xs' is denied.	CosmosKernel2	C:\Users\Barry Piel\source\repos\CosmosKernel2\CosmosKernel2\IL2CPU	1	

### ISSUE THREAD

**Issue by FocalFossa0997** [CosmosOS/Cosmos#1867]
I tried to compile the default project, and I got this error. Here is a screenshot...
![image](https://user-images.githubusercontent.com/69269521/124049974-70916800-d9ce-11eb-927e-2d5025d1ecea.png)
My system specs (if useful) are below:
System: Dell latitude 5414
CPU: i5-6300u
RAM: 8GB
OS: Windows 11

**Comment by quajak** [comment]
Please dont install the Cosmos user Kit to Program Files, since then the compiler needs admin rights every time it runs. Could you please reinstall and select somewhere in App Data for example?
