### ISSUE TITLE
Errors when building my OS after installing the DevKit and removing the UserKit

### ISSUE THREAD

**Issue by virajkhanna** [CosmosOS/Cosmos#1871]
Exception
System.IO.FileNotFoundException: Could not load file or assembly 'IL2CPU.Debug.Symbols, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16'. The system cannot find the file specified.

VS Output Logs
Build started...
1>------ Build started: Project: Test1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>Test1 -> C:\Users\********\source\repos\Test1\Test1\bin\Debug\netcoreapp2.0\cosmos\ViniuxOS.dll
1>Error : error occurred: System.IO.FileNotFoundException: Could not load file or assembly 'IL2CPU.Debug.Symbols, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16'. The system cannot find the file specified.
1>File name: 'IL2CPU.Debug.Symbols, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16'
1>   at Cosmos.IL2CPU.CompilerEngine.Execute()
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError)
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError)
1>
1>
1>IL2CPU task took 00:00:06.5307740
1>Done building project "Test1.csproj" -- FAILED.

It was working fine with the UserKit. I deleted the UserKit and installed the DevKit. When I build the same code it returns this error after I installed the DevKit

**Comment by virajkhanna** [comment]
I tried the build again. This time, it returned a different error.

System.IO.FileNotFoundException: Could not load file or assembly 'C:\Users\******\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll'. The system cannot find the file specified.

**Comment by quajak** [comment]
Can you check if the files exist at that location?

**Comment by virajkhanna** [comment]
![image](https://user-images.githubusercontent.com/68863014/124885350-ce3a3b80-dff0-11eb-8375-b77fcb8df37c.png)
They don't exist, even after installing the DevKit with install-VS2019.bat

**Comment by virajkhanna** [comment]
I ran userkit install.bat and it worked.
