### ISSUE TITLE
Heap.Free() issue with byte*

### ISSUE THREAD

**Issue by SkillAura13** [CosmosOS/Cosmos#1872]
I am running into an odd compiler issue.
Heap.Free() should be able to free this byte*, but instead a rather strange error occurs.

The error is 
`Exception: System.Exception: Error compiling method 'SystemUInt32CosmosCoreMemoryRATGetFirstRATSystemVoidpointer': System.Exception: Error interpreting stacktypes for IL_0007: Sub ---> System.NotImplementedException: Sub on types 'System.Byte*' and 'System.Void*' not yet implemented!`

Here is my code that causes the issue:
```
public unsafe void Run()
        {
            // Allocate some memory for this program
            byte* address = Heap.Alloc((uint)code.Length);

            // Copy it in
            for (uint n = 0u; n < (uint)code.Length; n += 1)
                address[n] = code[n];

            Execute.Call((uint)address);

            // Free the memory
            Heap.Free(address);
        }
```

**Comment by quajak** [comment]
Are you using the devkit or the userkit?

**Comment by SkillAura13** [comment]
> Are you using the devkit or the userkit?

I'm kind of new to using this kit, so I apologize for my incompetence. I'm using whatever is installed after running install-vs2019.bat

**Comment by quajak** [comment]
So you cloned the repositories and built from source?

**Comment by SkillAura13** [comment]
> So you cloned the repositories and built from source?

Yes, I did

**Comment by quajak** [comment]
Ok, so you are using the devkit. Its likely that this is already fixed in the IL2CPU pr to upgrade to .net 5.0

**Comment by SkillAura13** [comment]
> 
> 
> Ok, so you are using the devkit. Its likely that this is already fixed in the IL2CPU pr to upgrade to .net 5.0

Alright, thanks so much for the info

**Comment by valentinbreiz** [comment]
Is this fixed @quajak?

**Comment by MishaTY** [comment]
It should be, then how would gc free objects?
