### ISSUE TITLE
Unable to create files inside of directories.

### ISSUE THREAD

**Issue by core-hacked** [CosmosOS/Cosmos#1873]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File System

#### Expected Behaviour - What do you think that should happen?
When creating a file inside a directory the file should get created.

#### Actual Behaviour - What unexpectedly happens?
The file is unable to be created inside the given directory / under the given path.

#### Reproduction - How did you get this error to appear?
Create a project with the cosmos file system, create a function to make directories.
make a function to change to the directory and store the current directory.
add a command to make a file inside the current or specified directory.
run system and cd to any directory.
Then try to make a file inside the directory. 

Result: Fails to create the file, outright crashes or bugs to another command or part of the os code.
Additional information: A file is only unable to be created if inside of another directory. If you are only inside of 0:\ however, the file creation process works with no problem.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit 20200708 C# .NET, IDE: VS 2019 latest.

**Comment by virajkhanna** [comment]
Hi @core-hacked, can you share the code that triggered this error?

**Comment by core-hacked** [comment]
This is the code tied to the MK command which creates a file, the method may also be invoked without the command being submitted by the user.
```C#
public override void Execute(string line, string[] args)
        {
            bool success = false;
            string path = "";
            if (line.Length > 3)
            {
                path = line.Substring(3, line.Length - 3);
                if (path.EndsWith('\\')) { CLI.WriteLine("Invalid argument! file name expected.", Color.Red); }
                else
                {
                    if (path.StartsWith(PMFAT.CurrentDirectory)) { PMFAT.CreateFile(path); success = true; }
                    else if (path.StartsWith(@"0:\")) { PMFAT.CreateFile(path); success = true; }
                    else if (!path.StartsWith(PMFAT.CurrentDirectory) && !path.StartsWith(@"0:\"))
                    {
                        PMFAT.CreateFile(PMFAT.CurrentDirectory + path);
                        success = true;
                    }
                    else { CLI.WriteLine("Could not locate directory!", Color.Red); }
                }
            }
            else { CLI.WriteLine("Invalid argument! file name expected.", Color.Red); }

            if (success) { CLI.Write("Successfully created file \"", Color.Green); CLI.Write(path, Color.Yellow); CLI.Write("\"", Color.Green); CLI.WriteLine(string.Empty); }
        }
```
The var ``PMFAT.CurrentDirectory`` is logically where the user is currently in eg. ``0:\Dir\``

The code to create the file inside of PMFAT:

```C#
public static bool CreateFile(string name)
        {
            bool value = false;
            if (FileExists(name)) { value = false; }
            else { File.Create(name); value = true; }
            return value;
        }
        ```
As said, the code works with no problem inside of ``0:\`` only inside directories it outright crashes or jumps to a different line of code inside the OS.

**Comment by EliaSulimanov** [comment]
Have you checked the wiki page about it?

**Comment by core-hacked** [comment]
@EliaSulimanov haven't seen anything about it there. Could you point me if I'm mistaken?

**Comment by quajak** [comment]
The current code can not be reproduced. Could you please post code which can be run, preferably without any required user input?
