### ISSUE TITLE
Runtime error when trying to run UserKit as of 7th July 2021

### ISSUE THREAD

**Issue by isaacwalkercox** [CosmosOS/Cosmos#1876]
**Describe the problem**
A clear and concise description of where the installation is going wrong.
Executing UserKit.exe and allowing Admin rights produces this:
![image](https://user-images.githubusercontent.com/22714656/125366084-4f852b80-e36d-11eb-92aa-33df5dc80c76.png)

**Steps of installation up to now**
Download source and run "userkit install" as of 12 July 2021"

**Expected behavior**
I expect an installer to appear

**Logs**
Please post the entire log given by Cosmos. For long logs please use pastebin.
No log is generated as far as I can tell.

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) UserKit
 - Are you using an admin account? Yes
 - VS Version if applicable VS 2019

**Additional context**
I tried using the two latest releases as of 7th July 2021 and had the same issue.

**Comment by raxracks** [comment]
did you try running install-vs2019.bat?

**Comment by terminal-cs** [comment]
> did you try running install-vs2019.bat?

he described he is installing userkit, vs2019 does not exist there

**Comment by zarlo** [comment]
if you ran ```userkit install.bat``` that is for making user kits you want to run install-VS2019.bat

**Comment by isaacwalkercox** [comment]
> if you ran `userkit install.bat` that is for making user kits you want to run install-VS2019.bat

Isn't the userkit what you install to be able to use the VS projects/extensions etc for Cosmos?

**Comment by quajak** [comment]
I have never heard of this error before and a bit of googling indicates that this is most likely a problem with Windows and not cosmos itself. What windows version are you using?

**Comment by isaacwalkercox** [comment]
Windows 10 20H2

**Comment by quajak** [comment]
That should be supported. It really sounds to be a problem more with your windows installation and not cosmos, so your best bet is googling.
