### ISSUE TITLE
CPU Exception Last known address: 0x020C17B4 (This is shown while deleting a file.)

### ISSUE THREAD

**Issue by Blixermations** [CosmosOS/Cosmos#1878]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Deleting a file

#### Expected Behaviour - What do you think that should happen?
It should grab the file the user has specified and the current directory to delete it.

#### Actual Behaviour - What unexpectedly happens?
When entered the command, it takes the current directory and the file. That Works.
But when it goes to delete it, it shows a error. (CPU Exception. Last known address: 0x020C17B4)

#### Reproduction - How did you get this error to appear?
Code to reproduce the error: 
`File.Delete(currentdir + usersfile)`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am using User Kit

**Comment by quajak** [comment]
This most likely means an error is thrown when trying to delete the file. Are you sure that the path exists?

**Comment by Blixermations** [comment]
> This most likely means an error is thrown when trying to delete the file. Are you sure that the path exists?

Yea. The os should have 0:\testing.txt, but I have no idea why its not working

**Comment by quajak** [comment]
Most likely there is some bug in cosmos for delete. There are a series of other ways in Cosmos, you can try delete the file, which may work.

**Comment by AcaiBerii** [comment]
Are you using:
- devkit (built straight from the last commit made to this repo)
- userkit (downloaded from github releases)

If you're using the userkit, follow the instructions below to build and install the devkit.

- 1 Make sure you're running Windows and have a fresh installation of git-scm.
- 2 Run ```git clone https://github.com/CosmosOS/Cosmos.git```  in a directory of your choice.
- 3 Open your new "Cosmos" directory and run "install VS2019.bat".
- 4 Wait for everything to build and run through the installer.
- 5 Reopen Visual Studio.

The Cosmos devkit should now be installed and this problem could be solved.

**Comment by Blixermations** [comment]
> Are you using:
> 
> * devkit (built straight from the last commit made to this repo)
> * userkit (downloaded from github releases)
> 
> If you're using the userkit, follow the instructions below to build and install the devkit.
> 
> * 1 Make sure you're running Windows and have a fresh installation of git-scm. Uninstall any existing versions of Cosmos or let the installer at the end uninstall them for you.
> * 2 Run `git clone https://github.com/CosmosOS/Cosmos.git`  in a directory of your choice.
> * 3 Open your new "Cosmos" directory and run "install VS2019.bat".
> * 4 Wait for everything to build and run through the installer.
> * 5 Reopen Visual Studio.
> 
> The Cosmos devkit should now be installed and this problem could be solved.
> 
> If you're still having problems:
> 
> * Try listing the directory, like doing a foreach loop with Directory.GetAllFiles and printing the file name to the console. See if testing.txt exists.
> * Make sure the CosmosVFS is initialized.
> * Try running your OS on a VM like VMWare.

I have just done that and the code is now working, thx!

https://user-images.githubusercontent.com/70741560/125891555-ea7b6712-ddeb-4e03-8749-15eb13ead0be.mp4
