### ISSUE TITLE
os gives an error and Visual studio crashed

### ISSUE THREAD

**Issue by Blazzycrafter** [CosmosOS/Cosmos#1879]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I Dont Know...
(*EDIT* I THINK IT KERNEL)
#### Expected Behaviour - What do you think that should happen?

1. open os...
2. check if file "command" exist (dont exist)
3. and reboot by running function "ResetBoot()"

#### Actual Behaviour - What unexpectedly happens?
os gives an error and Visual studio crashed and restarted

#### Reproduction - How did you get this error to appear?
```

    Imports System
    Imports System.Collections.Generic
    Imports System.IO
    Imports System.Text
    Namespace CosmosKernel1

    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            Dim existCMD = Cosmos.System.FileSystem.VFS.VFSManager.FileExists("command")
            If Not existCMD Then
                ResetBoot()
            End If
        End Sub

        Protected Overrides Sub Run()
            Console.WriteLine("test data")

        End Sub

        Public Sub ResetBoot()
            Console.WriteLine("test data")
            ' Do something and reboot
            Cosmos.System.Power.Reboot()
        End Sub
    End Class

End Namespace
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit Latest Today installed

#### Images
[Code](https://i.imgur.com/fKQlDLV.png)
[Error](https://i.imgur.com/UCAAYwr.png)

**Comment by zarlo** [comment]
you need to initialize the file system
this page should have the info needed https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

**Comment by Blazzycrafter** [comment]
> you need to initialize the file system
> this page should have the info needed https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

yeah .... ok i tried it now .... but i am dumb as fuk and dont know how to do that shit in vb .net... -_-
my code now:
```
Imports System
Imports System.Collections.Generic
Imports System.IO
Imports System.Text
Imports Cosmos.System.FileSystem.VFS
Imports Cosmos.System.FileSystem

Dim fs = Cosmos.System.FileSystem.CosmosVFS()

Namespace CosmosKernel1
    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            Cosmos.System.FileSystem.VFS.VFSManager.RegisterVFS(fs)
            Dim existCMD = Cosmos.System.FileSystem.VFS.VFSManager.FileExists("command")
            If Not existCMD Then
                ResetBoot()
            End If
        End Sub

        Protected Overrides Sub Run()
            Console.WriteLine("test data")

        End Sub

        Public Sub ResetBoot()
            Console.WriteLine("test data")
            ' Do something and reboot
            Cosmos.System.Power.Reboot()
        End Sub
    End Class

End Namespace
```
Errors:
Line 8 `Dim fs = Cosmos.System.FileSystem.CosmosVFS()`
BC30001: Statement is not valid in a namespace
BC30109 "CosmosVFS" is a class type and cannot be used as an expression.
Line 15 `            Cosmos.System.FileSystem.VFS.VFSManager.RegisterVFS(fs)`
BC30451 "fs" was not declared. Access may not be possible due to protection level.

**Comment by zarlo** [comment]
put 
Dim fs = Cosmos.System.FileSystem.CosmosVFS()
in BeforeRun

**Comment by Blazzycrafter** [comment]
> put
> Dim fs = Cosmos.System.FileSystem.CosmosVFS()
> in BeforeRun

ok
Line 12
BC30109 "CosmosVFS" is a class type and cannot be used as an expression.
EDITED CODE:
```
Namespace CosmosKernel1
    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            Dim fs = Cosmos.System.FileSystem.CosmosVFS()
            Cosmos.System.FileSystem.VFS.VFSManager.RegisterVFS(fs)
            Dim existCMD = Cosmos.System.FileSystem.VFS.VFSManager.FileExists("command")
            If Not existCMD Then
                ResetBoot()
            End If
        End Sub
....
....
```

**Comment by EliaSulimanov** [comment]
@Blazzycrafter 
I believe that in vb it should be:
```vb
Dim fs As CosmosVFS = New Cosmos.System.FileSystem.CosmosVFS()
```
Also, please maintain proper language.

**Comment by Blazzycrafter** [comment]
@EliaSulimanov 
> Also, please maintain proper language.

sry i try to learn it by doing xD
```
I am trying to make a Löshu operating system
so i can mark a file to delete via context menu and the next time i start the computer it deletes the files with this os...
```
can I do that at all here?

**Comment by EliaSulimanov** [comment]
Cosmos VFS supports this.
To be able to do so, you must have some knowledge of programming and vs.net/c#.

The wiki page about VFS is updated and it shows some basic operations with it.
You can also read the documentation to learn about the other VFS methods.

If the issue is no longer exists, please close this issue.

**Comment by Blazzycrafter** [comment]
ok thenks to all :D you helped me a lot

CLOSED
