### ISSUE TITLE
Error when attempting to uninstall

### ISSUE THREAD

**Issue by tdsteve** [CosmosOS/Cosmos#188]
When attempting to uninstall Cosmos from Control Panel, I get this error in a pop-up window:
"Runtime Error (at 47:416):"
"Internal error: Cannot disable FS redirection on this version of Windows."

**Comment by ARMmaster17** [comment]
@stevethedude Sorry if I missed it on Gitter, what version of Windows are you on (Major version, feature level, platform)?

**Comment by stevethedude** [comment]
Sorry about that, I'm running 32 bit Windows 8.1. AFAIK I've got a standard install of Cosmos.

**Comment by mterwoord** [comment]
This is a long-standing issue with our installer I think. Maybe you could jump into this issue?
