### ISSUE TITLE
Can we only create Console OS ?

### ISSUE THREAD

**Issue by 178900PRITAM** [CosmosOS/Cosmos#1885]
Can we only create console based os it would better if we would create a os like windows as windows is created in c , c++ , c# , assembly ,do cosmos will support every type of creating oses

**Comment by AcaiBerii** [comment]
If you want to call c or cpp your best bet is to use system.runtime.interopservices and dllimport your file as an SO.

**Comment by terminal-cs** [comment]
> If you want to call c or cpp your best bet is to use system.runtime.interopservices and dllimport your file as an SO.
> 
> You can also call inline asm in c#.
> 
> If these don't work just submit a plug request or bug report.

he's talking about a gui

and yes, it is possible to make a GUI, but canvas is unfortunatley very slow right now

**Comment by terminal-cs** [comment]
infact heres my os using canvas
![Prism-OS 21 7 16](https://user-images.githubusercontent.com/76945439/126021905-f12c3737-cd06-43d8-a175-baab0d88727f.png)

**Comment by 178900PRITAM** [comment]
the GUi can be created i know that but the executable file arent supported yet. in cosmos

**Comment by AcaiBerii** [comment]
Machine code moment.
I'm sure there's a way to store machine code in a file and execute it.

**Comment by JuliusCaesar12** [comment]
Asfaik, you can call external code by reading the bytes from a file, placing on a heap, creating an asm-method using XSharp (you have to add a reference in the project file), placing the address of the heap pointer into eax, and then using XS.Call().

Of course, there are other options such as MishaTY's .NET CLR for Cosmos ( https://github.com/MishaTY/DotNetParser ) or Myvar's ELF loader ( https://github.com/Myvar/CosmosELF )

**Comment by valentinbreiz** [comment]
Execute raw binary is indeed possible. We had a working implementation some time ago on Aura Operating System.

AuraOS pull request:
https://github.com/aura-systems/Aura-Operating-System/pull/38/files

Sample program + mini libc:
https://github.com/aura-systems/Aura-Executable
