### ISSUE TITLE
CPU Exception x06 *** when run a command (the "***" in the Title is not a curse word, it is really in the error code)

### ISSUE THREAD

**Issue by unknown850** [CosmosOS/Cosmos#1887]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running

#### Expected Behaviour - What do you think that should happen?
I think i should print out Opened System

#### Actual Behaviour - What unexpectedly happens?
Visual Studio 2019 crashed without any error or notify, it dont even said that it crash recently. The VM just freeze out and do nothing

#### Reproduction - How did you get this error to appear?
I get this error to appear by typing "fm"(a command i coded) in the VMs

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I just using the latest version of User Kit.

This is the os repos for more info, I updated it
https://github.com/unknown850/MineBro10-OS/
                                                                                                                  (the *** stars is not a curse word, it's in the error code)

**Comment by AcaiBerii** [comment]
You might want to try upgrading to a devkit.

**Comment by unknown850** [comment]
nvm i just forget it init the classes
