### ISSUE TITLE
Plug System.Drawing

### ISSUE THREAD

**Issue by AcaiBerii** [CosmosOS/Cosmos#1890]
**What is the usecase for this plug**
```
Colorful.Console.WriteLine(string, System.Drawing.Color);
```

** Complexity of plug **
Can this plug be added without requiring new drivers or a lot of work? (Methods requiring Linq, Reflection or Networking etc. are too complex for this request)
```
It may need a lot of work. I'm only thinking about plugging System.Drawing.Color or other methods needed by Colorful.Console.
```

**Describe alternatives you've considered**
Are there ways to work around this plug not existing?
```
No. You can't print a System.Drawing.Color color to the console.
```

**Additional context**
Add any other context about the plug request here.
```
Help
```

**Comment by AnErrupTion** [comment]
Colorful.Console uses other, unplugged methods from the Win32 API I think, so it's more complex to plug.

**Comment by quajak** [comment]
The current console most likely does not support the methods needed to even plug this.

**Comment by EliaSulimanov** [comment]
Check out HAL.TextScreen.SetColor.

**Comment by AcaiBerii** [comment]
I found a workaround (mostly).  
If System.Drawing (not functions needed by the win32 api is plugged), my library will be able to convert System.Drawing.Color objects to ConsoleColors.
