### ISSUE TITLE
How do i continue a code in another file?

### ISSUE THREAD

**Issue by oofgo** [CosmosOS/Cosmos#1891]
#### Area of Cosmos - What area of Cosmos are we dealing with?
visual studio

#### Expected Behaviour - What do you think that should happen?
nome

#### Actual Behaviour - What unexpectedly happens?
i dont know how to do it

#### Reproduction - How did you get this error to appear?
nothing

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
both

Hi i want to know how to continue code in another file like example (not real code just a random code)
If Somthing
{
ContinueCodeTo("Somthing.cs");
}

**Comment by zarlo** [comment]
are you new to c# you do the same thing as you would in any c# program

**Comment by oofgo** [comment]
> are you new to c# you do the same thing as you would in any c# program
no i am not new
i am new to cosmos

**Comment by AnErrupTion** [comment]
You just... call a function in that Something class that continues the code? It's easy with classes. I don't think you know C# very well if you don't know how to use classes.
