### ISSUE TITLE
issues with "Cosmos.Build.Builder.exe" not being found by windows

### ISSUE THREAD

**Issue by deepfriedpineapl** [CosmosOS/Cosmos#1892]
**Describe the problem**
The "install-VS2019.bat" file when ran with or without administrator permissions both throw the same error which is "Windows cannot find 'source\Cosmos.build.builder\bin\Debug\Cosmos.build.builder.exe'. make sure you typed the name correctly, and then try again." 

**Steps of installation up to now**
install "Visual Studio Community 2019 v 16.10.4" from microsoft in Visual Studio Installer v 2.11.13.53049 and make sure you have .net stuff installed, as well as MSbuild. download Cosmos from this github (https://github.com/CosmosOS/Cosmos). unzip via 7zip, right-click "install-VS2019.bat" and click run as administrator, cmd opens in admin, it looks for MSBuild, attempts to build builder.sln and then error occurs

**Expected behavior**
i expected the install to go through this time as i have all the software i should need installed

**Logs**
(im not entirely sure where the logs are but here is what i could copy down by hand from the cmd myself)
"
Looking for MSBuild
Building Builder.sln
C:\Users\ {Name} \Downloads\Cosmos-master\source\Cosmos.build.builder\Cosmos.Build.Builder.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found."

and then a popup... well pops up and says "Windows cannot find 'source\Cosmos.build.builder\bin\Debug\Cosmos.build.builder.exe'. make sure you typed the name correctly, and then try again."

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
  I believe Userkit? i downloaded the zip of this "https://github.com/CosmosOS/Cosmos"
 - Are you using an admin account?
Yes
 - VS Version if applicable
 Visual Studio Community 2019 v 16.10.4

**Additional context**

im using .net versions listed below

"• .NET SDK 5.0.302
    • .NET Runtime 5.0.8
    • ASP.NET Core Runtime 5.0.8
    • .NET Windows Desktop Runtime 5.0.8"

and i've had this problem with a couple other install versions. i looked around a bit to see if anyone had the same issue but i didnt see anyone else with the same error so sorry if this has already been brought up. im just trying to learn C# by making a simple OS. i also have screenshots of the CMD if thats what you need and if you can point me in the direction of where the logs are stored in the SDK then ill gladly attach a pastebin link

**Comment by quajak** [comment]
I think you need to install the .net core 2.1 SDK to fix the error `MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.`

**Comment by deepfriedpineapl** [comment]
i didnt realize that i need .net CORE but even that didnt seem to fix my issue unfortunatly. now i have dotnet sdk v 2.1.81 and the newest version v 3.1341 as well as the non core version 5.0.302
none of which seem to work to fix the issue

**Comment by quajak** [comment]
> I believe Userkit? i downloaded the zip of this "https://github.com/CosmosOS/Cosmos"

To download the userkit you download from https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20200708 
You only have to download the source when you are installing the devkit

**Comment by deepfriedpineapl** [comment]
I'm trying to build my own OS from (kinda) scratch using C# so it's the devkit i need then. I'm just now kinda understanding the difference between user and dev kit i think. Will what i have work for what I'm trying to do?

**Comment by quajak** [comment]
You should be able to also use the devkit from that, since they both are functionally the same, just the devkit has newer code. If you want the devkit, you also need to clone IL2CPU, XSharp and Common for the installation to work.

**Comment by deepfriedpineapl** [comment]
alright ive downloaded all 3 but im not entirely sure how to get them to work together, i also tried the userkit you linked and that seems to give the same errors. is there a tutorial on this?

**Comment by deepfriedpineapl** [comment]
Hey, i think i figured it out. I just wiped everything i had installed and started fresh, following the tutorial on the official site step by step exactly as it said and after a bit of messing with it and installing all net core related things in the visual studio installer it seems to be functioning fine. I'm still not entirely sure what i did wrong. If i had to guess i had the wrong type of .net or something. Thanks for all your help!
