### ISSUE TITLE
Cosmos installer detected as a virus

### ISSUE THREAD

**Issue by virajkhanna** [CosmosOS/Cosmos#1893]
**Describe the problem**
I tried to update cosmos and ran the installer again. When I did so, everything went fine except the time the exe, CosmosUserKit-20210801-vs2019 had run. At that time my antivirus (Mcafee Total Protection) stopped it and detected it as a virus. I don't want to make an exclusion in my antivirus for the file in case some harmful stuff may be in that file. It used to be fine but now, after installing the updated version, it detects it as a virus.

![image](https://user-images.githubusercontent.com/68863014/127764874-8ee0b0e9-fcde-44f3-b9b3-6493764c26ae.png)

**Expected behavior**
I expect it to install properly

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): DevKit Latest
 - Are you using an admin account? Yes
 - VS Version if applicable: VS 2019

**Comment by ilobilo** [comment]
I think it says virus because it's custom built. I guarantee its safe

**Comment by virajkhanna** [comment]
Ok, Thank you
