### ISSUE TITLE
Bitmap not drawing.

### ISSUE THREAD

**Issue by tihonryzhikov** [CosmosOS/Cosmos#1895]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Image drawing.

#### Expected Behaviour - What do you think that should happen?

Bitmap should render.

#### Actual Behaviour - What unexpectedly happens?

OS freezes without exception

#### Reproduction - How did you get this error to appear?

Bitmap drawing test / OS Dev

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest Dev kit

---------------------------------------------------------------------------------------------------------------

Can I draw bitmap using another way?

**Comment by ilobilo** [comment]
Can you send the bitmap you are trying to draw?

**Comment by tihonryzhikov** [comment]
![lightning-os-logo](https://user-images.githubusercontent.com/66679206/128173206-75238adb-00dd-41f1-a746-a3c9d7dac137.png)


I'm converted this to .png before
In OS, I'm using .bmp

**Comment by jOS-X** [comment]
That file is 2mb. Cosmos currently has a bug where you can't load files over 1mb.

**Comment by tihonryzhikov** [comment]
But before I'm tried draw file smaller than 1 MB...

**Comment by tihonryzhikov** [comment]
OK, I'm partially solved this problem, but

**Comment by tihonryzhikov** [comment]
OK, how to draw bitmap using byte array? How to convert bitmap to byte array?
