### ISSUE TITLE
Don't waste the time on filesystem, write networking

### ISSUE THREAD

**Issue by Inshi666** [CosmosOS/Cosmos#190]
Hi. I have a idea for Cosmos Kernel - Do a working UDP or TCP Networking. It can be used as "cloud-based os". Use external server with working filesystem(e.g. linux), write the application on linux for list files available in user folder and send it to Cosmos Operating System.

**Comment by ARMmaster17** [comment]
@Inshi666 I know it sounds like a good idea, but trust me, a filesystem is a whole lot easier to implement than a networking stack. Not only do you have to implement TCP/UDP, but you also have to write drivers for every type of network card, in addition to special case code for VMs. All data storage devices use the same codebase (ATA) in Cosmos, which makes it much easier to implement.

Now that filesystem support is nearing completion (in terms of basic usage support), we will be looking into other major tasks (networking, more CPU types, memory management, etc...)

=====
If your issue has been resolved, please click *Close issue*. If you need to PM me about technical questions, please use Gitter with your GitHub login: https://gitter.im/ARMmaster17

**Comment by ARMmaster17** [comment]
@Inshi666 Sorry if I wasn't clear, FAT32/16 support has already been implemented in the live source (`git pull`, not GitHub Releases). We are going to finish up on that, then move on to another large objective (some that are on the roadmap are listed above).

**Comment by Inshi666** [comment]
Thanks for reply.
I know it's live source there are any docs about implement it to cosmos distrib?

**Comment by mterwoord** [comment]
@Inshi666 What do you mean?

**Comment by Inshi666** [comment]
Documents, tutorials about writing operating system with filesystem.

**Comment by MyvarHD** [comment]
And i believe UDP is implmented btw.

**Comment by mterwoord** [comment]
@Inshi666 It's not yet in the main kernel, but when it lands there, you'll just be using System.IO

@MyvarHD Not really. In the old kernel it was, in the new one, there's basic AMD pcnet driver support, but only for sending raw (byte[]) packages, not even ethernet..

**Comment by mterwoord** [comment]
@Inshi666 If this issue is solved, please close it. Thanks!
