### ISSUE TITLE
The Folder Cosmos Is Missing In Visual Studio 2019\Templates\ProjectTemplates

### ISSUE THREAD

**Issue by QxtN** [CosmosOS/Cosmos#1900]
Cosmos Has Installed Without Errors But after the installation, but there are only kernel templates are there 
When I see in Documents\Visual Studio 2019\Templates\ProjectTemplates There are No Folder Named Cosmos
**I have changed the installation path for the first time but I changed it to default path: _%appdata%/Cosmos User Kit_** When I'm installing it again and I have re-installed it several times but it doesn't work

**Files after Installation**

![Screenshot (55)](https://user-images.githubusercontent.com/88580885/128598146-605324da-7939-4b13-9fee-2027996669a6.png)

**Templates Folder**

![Screenshot (56)](https://user-images.githubusercontent.com/88580885/128598193-5a3bb74c-a2b4-47b3-8658-66324da4dc03.png)

**Please Help _Me_**

**Comment by ilobilo** [comment]
Can you create cosmos project from visual studio?

**Comment by QxtN** [comment]
No

**Comment by QxtN** [comment]
What is the `source code.zip` in [here](https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20200708) can i install from it

**Comment by quajak** [comment]
Are the VS extensions correctly installed by the installer?
