### ISSUE TITLE
When building, my project is showing this error Exception: Method GetMBIAddress requires a plug, but none is implemented

### ISSUE THREAD

**Issue by sakshamlang** [CosmosOS/Cosmos#1901]
Have you checked Github Issues for similar errors?

yes
**Exception**

Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented	

** VS Output Logs **

Build started...
1>------ Build started: Project: CosmosKernel2, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>CosmosKernel2 -> C:\Users\Saksham\source\repos\CosmosKernel2\CosmosKernel2\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel2.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Saksham\source\repos\CosmosKernel2\CosmosKernel2\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel2.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Method GetMBIAddress requires a plug, but none is implemented
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Jasper\Desktop\RandomProgrammieren\COSMOS\CosmosREAL\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 987
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Users\Jasper\Desktop\RandomProgrammieren\COSMOS\CosmosREAL\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 265
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Jasper\Desktop\RandomProgrammieren\COSMOS\CosmosREAL\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:16.0675814
1>Done building project "CosmosKernel2.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**

just run the default cosmos kernel c# project without editing it

**Context**
Before posting please confirm that the following are in order
[ yes ] Both Cosmos VS Extensions are installed
[ yes ] In the NuGet Package Manager "Include prerelease" is selected
[ yes ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ yes ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by quajak** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1586 ?
