### ISSUE TITLE
Errors in Visual Studio when building COSMOS and packages missing

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#1903]
Hello,

I get a error message when trying to build a COSMOS project. I did have previous problems with it as I opened a issue last year about it, it is error #1420 but it is closed now. 

If you need anymore info just reply to this issue.

Thanks, DolphinFlopFish

**Comment by DALVES2981** [comment]
What version you have? What visual studio you have? What version of cosmos you have?
Please tell all this things to try to resolve the problem.

**Comment by DolphinFlopFish** [comment]
I have the latest cosmos user kit, visual studio 2019 and windows 8.1

**Comment by DolphinFlopFish** [comment]
I got it to work by changing the NuGet package manager to the right dir, then changing the Cosmos.build.targets file to go to my dir
