### ISSUE TITLE
[FEATURE REQUEST] Have the TCPListener give you the Client IP as well.

### ISSUE THREAD

**Issue by ThomasBeHappy** [CosmosOS/Cosmos#1904]
As far as I am aware I am unable to get the IP adress of the client connecting to the TCPListener. In my opinion this is a crucial thing especially for sending data back and forth between multiple clients (due to multi threading not being implemented yet) and also for logging this would be important.

I hope this can get added.

**Comment by valentinbreiz** [comment]
Good point, I will make a pull request asap. Keep in touch ;)

**Comment by ThomasBeHappy** [comment]
Epic! Thanks!

**Comment by valentinbreiz** [comment]
Hello again @ThomasBeHappy it's merged and should be working
