### ISSUE TITLE
TCPListener unable to be looped.

### ISSUE THREAD

**Issue by ThomasBeHappy** [CosmosOS/Cosmos#1905]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Networking

#### Expected Behaviour - What do you think that should happen?
The TCPListener to start listening again after a client is closed.

#### Actual Behaviour - What unexpectedly happens?
The first client can connect fine, the second one as well. But the third one just isn't able to connect. I have tried multiple ways to do this. But the only "stable" way I found is to have a 10 second delay between the client closing and the TCPListener restarting.

#### Reproduction - How did you get this error to appear?
Have the TCPListener in a while loop at port 80, try connecting with the web browser, after a few connections you should see the browser say it takes too long to respond. With no more TCP packets arriving at the listener.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit - Latest

**Comment by valentinbreiz** [comment]
If you still have it, could you provide me the code you used to have this issue?
