### ISSUE TITLE
Templates not installing

### ISSUE THREAD

**Issue by Kiffolisk** [CosmosOS/Cosmos#1906]
**Describe the problem**
I've installed Cosmos twice and the templates never seemed to appear. The extension appeared though.

**Steps of installation up to now**
Run the installer

**Expected behavior**
Templates getting installed.

**Logs**
(can't find log file)

**Setup:**
 - Cosmos Version (Userkit/Devkit) Userkit
 - Are you using an admin account? Yes.
 - VS Version if applicable VS2019 16.8.3

**Comment by quajak** [comment]
Did one or both of the extensions get installed? 
Have you looked at https://github.com/CosmosOS/Cosmos/issues/1142
