### ISSUE TITLE
Console.SetCursorPosition not implemented?

### ISSUE THREAD

**Issue by stevethedude** [CosmosOS/Cosmos#191]
When calling Console.SetCursorPosition in my code, it prints "Not implemented: SetCursorPosition" even though many Cosmos tutorials exist that use it.

**Comment by mterwoord** [comment]
Most likely the older tutorials use ancient cosmos releases. We basically redid the whole kernel at some point. 

That being said, implementing it shouldn't be too hard. You might be able to do it yourself..

**Comment by MCMainiac** [comment]
Maybe you should update your kernel @stevethedude. I can find the method under Console.SetCursorPosition(int top, int left). Have you specified the using directive "using Sys = Cosmos.System;"?

**Comment by mterwoord** [comment]
@MCMainiac You should be able to use Microsoft's Console.SetCursorPosition. If that's not working, but our implementation just works, it means we are missing a plug. Could you or @stevethedude post a fix for that please? :)

**Comment by stevethedude** [comment]
Looks like using Microsoft's implementation works.

**Comment by mterwoord** [comment]
Can you double check and if it actually works as excepted, close this issue? Thanks.

**Comment by Shagunandroid** [comment]
I also have the same issue.

**Comment by jp2masa** [comment]
Last time I used it, it was working.
What Cosmos version are you using?
