### ISSUE TITLE
Cosmos kernel is only found in VS | There's nothing else

### ISSUE THREAD

**Issue by os-lover** [CosmosOS/Cosmos#1912]
Hey there,

When I have installed cosmos many times, there are only THREE templates that show up. They are all different versions of the Cosmos Kernel and nothing else is there. What's even weirder is the fact that there are no template files (Cosmos's ones) in the VS template folder.

All I have done is installed Cosmos normally.

I'm using Cosmos userkit and I'm on the latest version of VS 2019

Thank you.

**Comment by raxracks** [comment]
The kernel is the correct template for a cosmos project

**Comment by os-lover** [comment]
In every over tutorial (even the official one on the website) they don't make an os by using the kernel template. I have no clue lol

**Comment by MishaTY** [comment]
Use the kernel template, that is a cosmos project.
