### ISSUE TITLE
System.IO.FileLoadException Error

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#1917]
Hi,

I got this issue when trying to build using VS 2017 Community and Cosmos UserKit 2018:

Severity	Code	Description	Project	File	Line	Suppression State
Error	occurred	System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	earthOS	C:\Users\me\source\repos\earthOS\earthOS\Error	1

I don't know why it happens though, it just does.

From DolphinFlopFish

**Comment by DolphinFlopFish** [comment]
anyone?

**Comment by DolphinFlopFish** [comment]
This is the error: 
![Screenshot (3)](https://user-images.githubusercontent.com/52783833/131924340-181bf1cd-a84d-4f96-999f-fbe107450d4f.png)

**Comment by zarlo** [comment]
Cosmos UserKit 2018 is not longer supported
 
 you could try restoring the project nuget packages

**Comment by DolphinFlopFish** [comment]
ok
