### ISSUE TITLE
Severity	Code	Description	Project	Path	File	Line	Suppression State Error		Exception: System.IO.IOException: The process cannot access the file 'C:\Users\space\source\repos\FourSOS\FourSOS\bin\Debug\netcoreapp2.0\cosmos\FourSOS.cdb' because it is being used by another process.	FourSOS	C:\Users\space\source\repos\FourSOS\FourSOS	C:\Users\space\source\repos\FourSOS\FourSOS\IL2CPU	1	

### ISSUE THREAD

**Issue by saluransains** [CosmosOS/Cosmos#1919]
Build started...
1>------ Build started: Project: FourSOS, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>FourSOS -> C:\Users\space\source\repos\FourSOS\FourSOS\bin\Debug\netcoreapp2.0\cosmos\FourSOS.dll
1>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
1>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
1>IL2CPU task took 00:00:00.1086467
1>Done building project "FourSOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
![image](https://user-images.githubusercontent.com/72846692/132285936-c52fcc03-eb06-4dbc-bbcd-054bd8735b2c.png)

I don't know what is happening? It happens when I build my projects. Can someone help me?

**Comment by terminal-cs** [comment]
What does your code look like?

**Comment by saluransains** [comment]
There is so much code. I will give you the project

**Comment by saluransains** [comment]
Here the project
https://we.tl/t-hXXLQ2Y4rv

**Comment by saluransains** [comment]
> What does your code look like?

Here is the project download link
https://we.tl/t-hXXLQ2Y4rv

**Comment by quajak** [comment]
Restarting VS should fix the `The process cannot access the file 'C:\Users\space\source\repos\FourSOS\FourSOS\bin\Debug\netcoreapp2.0\cosmos\FourSOS.cdb' because it is being used by another process` error.

**Comment by saluransains** [comment]
> Restarting VS should fix the `The process cannot access the file 'C:\Users\space\source\repos\FourSOS\FourSOS\bin\Debug\netcoreapp2.0\cosmos\FourSOS.cdb' because it is being used by another process` error.

Thanks

**Comment by saluransains** [comment]
> Restarting VS should fix the `The process cannot access the file 'C:\Users\space\source\repos\FourSOS\FourSOS\bin\Debug\netcoreapp2.0\cosmos\FourSOS.cdb' because it is being used by another process` error.

Thank you so much
