### ISSUE TITLE
Filesystem folders bug.

### ISSUE THREAD

**Issue by jwoff78** [CosmosOS/Cosmos#1924]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel Level, with file system. when creating a folder.

#### Expected Behaviour - What do you think that should happen?
Hopefully create a folder without any issues that at least's goes up to 32 or 64 before errors.

#### Actual Behaviour - What unexpectedly happens?
After 8 characters in folder name doing fs.CreateDirectory(path) it add a period and continues to finish. This is workable with but it create a haphazard environment for guessing what the directory is without looking inside the vmdk everytime.

#### Reproduction - How did you get this error to appear?
Initialize file system like normal, than do filesystem.CreateDirectory(@"0:\ExampleExample"); this will not be visibly disruptive, but if you open VMDK inside of 7Zip you will see 8 characters than a period and the rest of characters.
(filesystem assuming you called your CosmosVFS filesystem)

NOTE: THIS HAS NOT BEEN TESTED WITH DIRECTORIES OVER 10 CHARACTERS
I will test with larger files and comment below.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit (latest)

**Comment by quajak** [comment]
Does Cosmos display the name correctly?

**Comment by jwoff78** [comment]
I tried with 45 characters without any errors, it seems to be a 10 character issue. the exact string was "ExeExample" which was just random string I put in there. Name displays correctly and everything, unsure what has caused this particularly. I tested just now with ExampleExa and it cut off as such ExampleE.xa it appears to be a 10 character issue.

**Comment by jwoff78** [comment]
That said I haven't tried anywhere in between or below.

**Comment by jwoff78** [comment]
9 character issue, 10 character issue, and 11 character issue, after that it seems to be non-existent.

**Comment by quajak** [comment]
Since this issue does not seem to affect cosmos functionality and seems to be a very minor, this will most likely not be fixed.
