### ISSUE TITLE
Error initializing hyper-v debug

### ISSUE THREAD

**Issue by DoorsDev** [CosmosOS/Cosmos#1925]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Hyper-v Debug

#### Expected Behaviour - What do you think that should happen?

Open hyper-v window and start debuging

#### Actual Behaviour - What unexpectedly happens?

Gives me an error

#### Reproduction - How did you get this error to appear?

Debuging in hyper-v

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev kit commit from 2 days ago

**Comment by quajak** [comment]
What error?

**Comment by DoorsDev** [comment]
i will send screenshots

![image](https://user-images.githubusercontent.com/79535084/133292028-5a387801-eac2-421c-b8c0-aeea2a01d7ef.png)

**Comment by quajak** [comment]
This error only appears when trying to use Hyper-V?

**Comment by DoorsDev** [comment]
Yes

**Comment by DoorsDev** [comment]
I thing
