### ISSUE TITLE
Debugger issue

### ISSUE THREAD

**Issue by AlexChecker** [CosmosOS/Cosmos#1930]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugger

#### Expected Behaviour - What do you think that should happen?
It should launch

#### Actual Behaviour - What unexpectedly happens?
VMware throws error that mbr is broken. After closing it's window, VS restarts and tells that there were issues with cosmos debugger and recommends to turn it off.

#### Reproduction - How did you get this error to appear?
just compiled os with debugging enabled

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using latest User Kit

**Comment by MishaTY** [comment]
Can you please send your project's code?
