### ISSUE TITLE
The target "CosmosBuild" does not exist in the project.

### ISSUE THREAD

**Issue by peymanmajidi** [CosmosOS/Cosmos#1933]
Hello, I don't know what happened to Cosmos, I can't run my project,   
even when I make a new and clean project it's still have the same problem

![image](https://user-images.githubusercontent.com/24313930/135054129-95296fff-4e14-44f8-a243-f885cff9ed53.png)

I tried to change target framework to 3x and 5 but still there.

** VS Output Logs **
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "CosmosBuild" does not exist in the project.	CosmosKernel6	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	934	

Thanks in advance

**Comment by peymanmajidi** [comment]
Hey Everyone...

I try to reinstall VS, Vmware player and Cosmos SDK... problem still remains

**Comment by MishaTY** [comment]
See #1934

**Comment by MishaTY** [comment]
See #1926

**Comment by valentinbreiz** [comment]
Can we close this?
