### ISSUE TITLE
Restore - Build.sln fails to install Cosmos (install-VS2019)

### ISSUE THREAD

**Issue by patrickfrom** [CosmosOS/Cosmos#1935]
**Describe the problem**
I can run "install-VS2019", but the installation fails during _Restore - Build.sln_

**Steps of installation up to now**
Just by starting up the "install-VS2019" installation.

**Expected behavior**
I expect it to install Cosmos so I can use it on Visual Studio.

**Logs**
https://pastebin.com/HHcGm8Zi

**Steup (please complete the following information):**
 - Cosmos Version: DevKit
 - Using Admin Account: Yes
 - VS Version: 2019

**Comment by zarlo** [comment]
this is a known issue for more info have a look at [https://github.com/CosmosOS/Cosmos/issues/1926](https://github.com/CosmosOS/Cosmos/issues/1926)

**Comment by patrickfrom** [comment]
> this is a known issue for more info have a look at #1926

Did not work at all.

**Comment by patrickfrom** [comment]
I'll just give up on the Project I had in mind,
was a tiny project but it's okay :)
