### ISSUE TITLE
I was banned AGAIN

### ISSUE THREAD

**Issue by Awire9966** [CosmosOS/Cosmos#1943]
I was banned again. Unban me and I will make the best function for cosmos ever.
BTW, I have your youtube. https://www.youtube.com/channel/UCjoUyd0fBFzZTHWMf6mM5ww

**Comment by MishaTY** [comment]
Ban evasion is not allowed.

**Comment by Awire9966** [comment]
Alright then unban me.

**Comment by LuftKatzeBASIC** [comment]
no

**Comment by Awire9966** [comment]
I have an idea for cosmos.
