### ISSUE TITLE
Im not gonna stop.

### ISSUE THREAD

**Issue by Awire9966** [CosmosOS/Cosmos#1945]
I can do this all day. I didnt want to have to troll but I guess I have no choice.

**Comment by LuftKatzeBASIC** [comment]
![image](https://user-images.githubusercontent.com/82577368/136661161-b9d403c0-6223-47c1-9e6b-fdcc965ccc42.png)

**Comment by Awire9966** [comment]
Guess who used their mommies phone!

**Comment by TRDP1404** [comment]
please no

**Comment by Awire9966** [comment]
Its not gonna happen.

**Comment by Awire9966** [comment]
Jokes on u
Im on a vpn.

**Comment by TRDP1404** [comment]
this is a joke please

**Comment by LuftKatzeBASIC** [comment]
Oh no! now I'm scared

**Comment by TRDP1404** [comment]
> Its simple. Unban me or else comsosOS Will die.

you wish

**Comment by Pwlx0** [comment]
cry about it

**Comment by LuftKatzeBASIC** [comment]
ill unban you

**Comment by LuftKatzeBASIC** [comment]
accept my friend request on discord

**Comment by TRDP1404** [comment]
we are pissing are selfs come back

**Comment by Awire9966** [comment]
Alright Lets get this show on the road.

**Comment by TRDP1404** [comment]
no

**Comment by Awire9966** [comment]
Thats it

**Comment by TRDP1404** [comment]
its been 5 minutes?
