### ISSUE TITLE
misha said the n-word.

### ISSUE THREAD

**Issue by Awire9966** [CosmosOS/Cosmos#1946]
https://github.com/MishaTY said this
![misha](https://user-images.githubusercontent.com/65136929/136662149-b6c35cfa-3859-4053-89bf-f5fcbd368b77.png)

**Comment by Awire9966** [comment]
https://github.com/CosmosOS/Cosmos/issues/1946#issuecomment-939306332
He Did

**Comment by LuftKatzeBASIC** [comment]
he say "nature"

**Comment by ilobilo** [comment]
We have your ip

**Comment by Awire9966** [comment]
Good for you but misha said the N word

**Comment by Awire9966** [comment]
He is a racist

**Comment by Awire9966** [comment]
Well then what did he say?

**Comment by TRDP1404** [comment]
ok wait whats you discord name

**Comment by TRDP1404** [comment]
![image](https://user-images.githubusercontent.com/76277026/136662297-9d2bcf3b-5417-4d3e-952f-dff799c80a4f.png)
you child looks nothing alike

**Comment by TRDP1404** [comment]
I need to talk to you on discord

**Comment by Awire9966** [comment]
Im @Coder#4211

**Comment by vishvanathan-k** [comment]
That dp doesn't look like misha's discord profile

**Comment by Awire9966** [comment]
Well What are we going to do

**Comment by Awire9966** [comment]
He said the N word. I dont want to have to give more eveidnce

**Comment by TRDP1404** [comment]
you don't I need to ask you one thing

**Comment by vishvanathan-k** [comment]
Make sure you don't get unbanned :rofl:

**Comment by Awire9966** [comment]
https://github.com/CosmosOS/Cosmos/issues/1946#issuecomment-939306995
Fuck off will ya?

**Comment by TRDP1404** [comment]
no bad word my mom might yell at me

**Comment by TRDP1404** [comment]
you are a 2 year old

**Comment by Awire9966** [comment]
https://github.com/CosmosOS/Cosmos/issues/1946#issuecomment-939307438
I may be. but you just fell for it.

**Comment by TRDP1404** [comment]
I would be in trouble

**Comment by Awire9966** [comment]
Anyway, Can someone ban @MishaTY  for saying the N word?

**Comment by TRDP1404** [comment]
can Someone ban @Awire9966 for spreading fake screenshot "Proving" some one you doing something bad

**Comment by TRDP1404** [comment]
and don't say server pfps Misha doesn't have nitro

**Comment by Awire9966** [comment]
https://github.com/CosmosOS/Cosmos/issues/1946#issuecomment-939307885
Yea cause he is a poor racist.

**Comment by TRDP1404** [comment]
oh my fucking god
