### ISSUE TITLE
It Does Not Boot

### ISSUE THREAD

**Issue by partisani** [CosmosOS/Cosmos#1953]
I Cannot Boot My Operting System With The Iso That I Have Builded

It Get Stuck In This Screen, See:
![reason](https://user-images.githubusercontent.com/88511157/137782129-acd99ffc-66dc-4725-91f4-704bfda15940.png)

How I Fix It?

**Comment by IsaacPar** [comment]
I'm Getting Problem In Booting It By A Iso That I Have Builded In Visal Studio
