### ISSUE TITLE
Usb with Cosmos OS burned onto it not showing on windows boot manager.

### ISSUE THREAD

**Issue by insertnamehere432** [CosmosOS/Cosmos#1957]
### I did use rufus to burn the iso file onto the usb
---
It still does not show up I have used multiple settings from various sources and still nothing.

I really don't have any idea what's wrong so I can't supply much else.

**Comment by MishaTY** [comment]
You need too boot from the usb, not from your hard drive.

**Comment by valentinbreiz** [comment]
Are you in bios mode or uefi?

**Comment by insertnamehere432** [comment]
uefi

**Comment by Andrej123456789** [comment]
Try change in BIOS Utility, but new Acer laptops don't supprot Legacy Boot Mode
