### ISSUE TITLE
I can't install the Devkit

### ISSUE THREAD

**Issue by FreeBSoD** [CosmosOS/Cosmos#1962]
**Describe the problem**
I can't install the Devkit

**Steps of installation up to now**
Run install vs2019.bat

**Expected behavior**
That it installs to visual studio 2019

**Logs**
CSC : error CS1705: Assembly 'IL2CPU.Debug.Symbols' with identity 'IL2CPU.Debug.Symbols, Version=10.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\Users\Not Showing lol\Downloads\cm\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) - Devkit
 - Are you using an admin account? - Yes
 - VS Version if applicable - 2019

**Additional context**
I can't install the Devkit i don't know why

**Comment by MishaTY** [comment]
The installer has not yet been updated too check for .net 5, try installing . net 5 runtime and sdk.

**Comment by MishaTY** [comment]
See above issue.
