### ISSUE TITLE
Getting a lot of errors as soon as the solution loads up

### ISSUE THREAD

**Issue by Great-error** [CosmosOS/Cosmos#1968]
The namespace type 'Cosmos' could not be found (Something like that)

It was an error saying:
Build started...
Failed to restore D:\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj (in 3.46 sec).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>D:\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj : error NU1101: Unable to find package Cosmos.System2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
1>D:\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj : error NU1101: Unable to find package Cosmos.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
1>D:\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj : error NU1101: Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
1>D:\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj : error : NETSDK1056: Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
1>Done building project "CosmosKernel1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I made no changes

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected (I don't know what this is)
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages' (I don't know what this is)
[ ] The Cosmos NuGet packages are installed (I don't know what this is)

I just want a basic CLI that responds to time, about and other basic cmds

**Comment by brokedev** [comment]
@Great-error sorry i bumped this and im late but create a file named Cosmos.Local.PackageFeed.config and put this code there:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="Cosmos Local Package Feed" value="Your Cosmos User Kit/Packages location"/>
  </packageSources>
</configuration>
```
Replace "Your Cosmos User Kit/Packages location" with what it says (for example, C:\Users\broke\AppData\Roaming\Cosmos User Kit\packages
Then try building
