### ISSUE TITLE
MSB6004	The specified task executable location

### ISSUE THREAD

**Issue by Great-error** [CosmosOS/Cosmos#1973]
I have don't think I can find another issue of the same type

Both Cosmos VS Extensions are installed
In the NuGet Package Manager "Include prerelease" is selected
The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages
The Cosmos NuGet packages are installed

I had an error before but fixed it after some help from @quajak and @MishaTY, they quick, props to them

now I have another error (not unexpected)

the error message is:
Error	MSB6004	The specified task executable location "C:\Users\Sam.LAPTOP-DAH28UJU\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.	CosmosKernel1	C:\Users\Sam.LAPTOP-DAH28UJU\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets	169	

please help me fix it

Thanks in advance

**Comment by quajak** [comment]
Where is the user kit installed? If its installed under another user, please reinstall it and set the path to the above mentioned one.

**Comment by Great-error** [comment]
Not on another user same user I know where it is but I don't know how to set it to the path

**Comment by quajak** [comment]
When you use the installer, there should be a page to select installation location. If it doesnt show up, first deinstall cosmos and then reinstall it.

**Comment by Great-error** [comment]
Ok

**Comment by MishaTY** [comment]
Closed as no user response

**Comment by AudioTore** [comment]
Nothing else?

**Comment by Great-error** [comment]
> Nothing else?

No I quit I started learning how to make an os from scratch since then

**Comment by AudioTore** [comment]
Don't blame ya. Cosmos OS is a bit buggy. Good luck ;) 👍

**Comment by AudioTore** [comment]
I'm scared of making an OS from scratch 💀

**Comment by Great-error** [comment]
> 

damn maybe we could collab?

**Comment by AudioTore** [comment]
Sure! The hard part for me is making the bootloader in x86 assembly. Assembly has never really been my gig.

**Comment by Great-error** [comment]
org 7C00h
 
         jmp short Start ;Jump over the data (the 'short' keyword makes the jmp instruction smaller)
 
 Msg:    db "Hello World! "
 EndMsg:
 
 Start:  mov bx, 000Fh   ;Page 0, colour attribute 15 (white) for the int 10 calls below
         mov cx, 1       ;We will want to write 1 character
         xor dx, dx      ;Start at top left corner
         mov ds, dx      ;Ensure ds = 0 (to let us load the message)
         cld             ;Ensure direction flag is cleared (for LODSB)
 
 Print:  mov si, Msg     ;Loads the address of the first byte of the message, 7C02h in this case
 
                         ;PC BIOS Interrupt 10 Subfunction 2 - Set cursor position
                         ;AH = 2
 Char:   mov ah, 2       ;BH = page, DH = row, DL = column
         int 10h
         lodsb           ;Load a byte of the message into AL.
                         ;Remember that DS is 0 and SI holds the
                         ;offset of one of the bytes of the message.
 
                         ;PC BIOS Interrupt 10 Subfunction 9 - Write character and colour
                         ;AH = 9
         mov ah, 9       ;BH = page, AL = character, BL = attribute, CX = character count
         int 10h
 
         inc dl          ;Advance cursor
 
         cmp dl, 80      ;Wrap around edge of screen if necessary
         jne Skip
         xor dl, dl
         inc dh
 
         cmp dh, 25      ;Wrap around bottom of screen if necessary
         jne Skip
         xor dh, dh
 
 Skip:   cmp si, EndMsg  ;If we're not at end of message,
         jne Char        ;continue loading characters
         jmp Print       ;otherwise restart from the beginning of the message
 
 
 times 0200h - 2 - ($ - $$)  db 0    ;Zerofill up to 510 bytes
 
         dw 0AA55h       ;Boot Sector signature
 
 ;OPTIONAL:
 ;To zerofill up to the size of a standard 1.44MB, 3.5" floppy disk
 ;times 1474560 - ($ - $$) db 0


I would say this is a good example of a bootloader quite simple yet the syntax is complex

**Comment by AudioTore** [comment]
I don't have a discord. We can chat in the issues tab though.

**Comment by Great-error** [comment]
> I don't have a discord. We can chat in the issues tab though.

what!!! plus I don't think the people managing these issues are ok with that

**Comment by AudioTore** [comment]
I wouldn't have a problem doing that on my project issues tab

**Comment by Great-error** [comment]
alright but you should consider making a discord in the near future if this goes any further

**Comment by AudioTore** [comment]
Ok

**Comment by AudioTore** [comment]
What are we working on? The OS I made?

**Comment by Great-error** [comment]
yes

**Comment by AudioTore** [comment]
Ok. I'm gonna make an issues tab in the OS Repository for us to talk.

**Comment by AudioTore** [comment]
Closed
