### ISSUE TITLE
ATA Error And File Corruption

### ISSUE THREAD

**Issue by Winksplorer** [CosmosOS/Cosmos#1975]
#### Area of Cosmos - What area of Cosmos are we dealing with?
VFS

#### Expected Behaviour - What do you think that should happen?
the file system should be able to work. only marking the four files corrupted.

#### Actual Behaviour - What unexpectedly happens?
any file system action results in an ATA error.
and both of the "winksplorer" files get corrupted and the first 4 letters of the contents of the file gets replaced with contents of the gse and txt file.

#### Reproduction - How did you get this error to appear?
there is two files called gse & txt.
and another two called winksplorer.gsi & winksplorer.gsi$
and in 1 folder.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit v20200708

**Comment by quajak** [comment]
Could you post code to reproduce your problem? It is clearly a bug but with the current information, its impossible to pinpoint where.

**Comment by Winksplorer** [comment]
> Could you post code to reproduce your problem? It is clearly a bug but with the current information, its impossible to pinpoint where.

**Code To Create Files And Directories**
                if (System.IO.Directory.Exists(@"0:\GLINTSYS\") != true)
                {
                    fs.CreateDirectory(@"0:\GLINTSYS\");
                    fs.CreateFile(@"0:\GLINTSYS\FS_DIRTY.GSI");
                    fs.CreateDirectory(@"0:\GLINTSYS\EXT\");
                    fs.CreateFile(@"0:\GLINTSYS\gse");
                    fs.CreateFile(@"0:\GLINTSYS\txt");
                    File.WriteAllText(@"0:\GLINTSYS\gse", "gict");
                    File.WriteAllText(@"0:\GLINTSYS\txt", "miv");
                    File.WriteAllText(@"0:\GLINTSYS\FS_DIRTY.GSI", "0");
                }
**Code To List Files And Directories**
        public static void ls()
        {
            string fst = Kernel.fs.GetFileSystemType("0:/");
            var dir = Kernel.fs.GetDirectoryListing(Kernel.path);
            long avs = Kernel.fs.GetAvailableFreeSpace("0:/");
            foreach (var directoryEntry in dir)
            {
                if(directoryEntry.mName.EndsWith(".gse"))
                {
                    Console.ForegroundColor = ConsoleColor.DarkYellow;
                    Console.WriteLine(directoryEntry.mName);
                    Console.ForegroundColor = ConsoleColor.White;
                }
                if(directoryEntry.mName.EndsWith(".xzsd"))
                {
                    Console.ForegroundColor = ConsoleColor.Blue;
                    Console.WriteLine(directoryEntry.mName);
                }
                if(directoryEntry.mName.EndsWith("$"))
                {
                    continue;
                }
                else if(directoryEntry.mEntryType == Sys.FileSystem.Listing.DirectoryEntryTypeEnum.Directory)
                {
                    Console.ForegroundColor = ConsoleColor.DarkGreen;
                    Console.WriteLine(directoryEntry.mName);
                    Console.ForegroundColor = ConsoleColor.White;
                }
                else
                {
                    Console.WriteLine(directoryEntry.mName);
                }
            }
            Console.WriteLine(avs + " Bytes Free, File System: " + fst);
        }

**Comment by quajak** [comment]
Thank you
I dont think FAT supports file endings which arnt 3 characters, so that might be the problem but I might be wrong on that.
