### ISSUE TITLE
Failed to install Cosmos DevKit

### ISSUE THREAD

**Issue by tihonryzhikov** [CosmosOS/Cosmos#1976]
**Describe the problem**
Installation error

**Steps of installation up to now**
Standart installation process

**Expected behavior**
Successfull Cosmos DevKit installation

**Logs**
The process failed to execute!
Error: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1216,5): error MSB3644: ¡Ñ ¡á®ñÑ¡Ù ßßÙ½«þ¡ÙÑ ßí«Ó¬¿ ñ½´ .NETFramework,Version=v4.8. ùÔ«íÙ ÒßÔÓá¡¿Ôý ÝÔÒ »Ó«í½Ñ¼Ò, ÒßÔá¡«ó¿ÔÑ »á¬ÑÔ ÓáºÓáí«Ôþ¿¬á (»á¬ÑÔ SDK ¿½¿ »á¬ÑÔ ¡áµÑ½¿óá¡¿´) ñ½´ ÝÔ«® óÑÓß¿¿ »½áÔõ«Ó¼Ù ¿½¿ »ÑÓÑ¡áµÑ½ýÔÑ »Ó¿½«ªÑ¡¿Ñ. Åá¬ÑÔÙ ÓáºÓáí«Ôþ¿¬á ñ½´ »½áÔõ«Ó¼Ù .NET Framework ¼«ª¡« ß¬áþáÔý ¡á ßÔÓá¡¿µÑ https://aka.ms/msbuild/developerpacks. [C:\cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem_fzzc2ce3_wpftmp.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4678,5): error MSB3021: ¡Ñ Òñá½«ßý ß¬«»¿Ó«óáÔý õá®½ "C:\Users\Tihon\.nuget\packages\microsoft.netcore.app.runtime.win-x64\5.0.8\runtimes\win-x64\native\ucrtbase.dll" ó "C:\cosmos\Cosmos\Build\VSIP\ucrtbase.dll". ÄÔ¬áºá¡« ó ñ«ßÔÒ»Ñ »« »ÒÔ¿ "C:\cosmos\Cosmos\Build\VSIP\ucrtbase.dll". [C:\cosmos\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj]

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): Latest
 - Are you using an admin account?: yes
 - VS Version if applicable: VS 2019

**Additional context**
I trying to reinstall .NET Framework 5, .NET Core 2 SDK and VS Cross-platform tools.

**Comment by quajak** [comment]
It seems like some sdk is missing but the text is from a different encoding. What language is your system in? Can you try screenshot the error message?

**Comment by tihonryzhikov** [comment]
Thx, changing system language helps me. Before changing all works fine.
