### ISSUE TITLE
GCImplementationRefs Fail On Compilation

### ISSUE THREAD

**Issue by Winksplorer** [CosmosOS/Cosmos#1977]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU & Compiler

#### Expected Behaviour - What do you think that should happen?
Compile?

#### Actual Behaviour - What unexpectedly happens?
Throws A TypeInitalization Exception For Cosmos.IL2CPU.GCImplementationRefs.

#### Reproduction - How did you get this error to appear?
Well, Compile.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit 106027

**Comment by quajak** [comment]
Was fixed by reverting changes on il2cpu
