### ISSUE TITLE
DHCP System Error

### ISSUE THREAD

**Issue by Winksplorer** [CosmosOS/Cosmos#1979]
#### Area of Cosmos - What area of Cosmos are we dealing with?
DHCP & Networking

#### Expected Behaviour - What do you think that should happen?
A Network Configuration should be returned.

#### Actual Behaviour - What unexpectedly happens?
Throws CPU Exception x06.
Last Known Address is 0x021958E5, debugger returns no output.

#### Reproduction - How did you get this error to appear?
```cs
                Cosmos.HAL.Network.NetworkInit.Init();
                using (var xClient = new Sys.Network.IPv4.UDP.DHCP.DHCPClient())
                {
                    xClient.SendDiscoverPacket();
                }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit 106027 - Latest Revision

**Comment by valentinbreiz** [comment]
Hello @Winksplorer, what Virtual Machine are you using?

**Comment by Winksplorer** [comment]
VMware Workstation 16 Pro

**Comment by valentinbreiz** [comment]
@Winksplorer Cosmos.HAL.Network.NetworkInit.Init(); should not be called, it is already called in Cosmos HAL initialization. Your error is due to some problem on a double initialization, remove this line and put your VM in NAT mode and it should be working.

**Comment by quajak** [comment]
@valentinbreiz Can we add a check to the init code to ensure that it is only called once?

**Comment by Winksplorer** [comment]
> @Winksplorer Cosmos.HAL.Network.NetworkInit.Init(); should not be called, it is already called in Cosmos HAL initialization. Your error is due to some problem on a double initialization, remove this line and it should be working.

ah, thanks.
