### ISSUE TITLE
CPU Exception x09

### ISSUE THREAD

**Issue by MCMainiac** [CosmosOS/Cosmos#198]
When I first started a fresh new Cosmos project, everything compiled fine and so on. But in the VMware Player, it said "*** CPU Exception x09 ***". What does that mean? What do I have to do?

**Comment by mterwoord** [comment]
Are you really, really sure it's 0x09?? I've prtty much seen all cpu exceptions that you can expect with cosmos, but 0x09 isn't 1 that you can normally get...
0x06 sounds more ike it..

**Comment by MCMainiac** [comment]
Nope I'm sure. If you want me to, I can even put a link to a screenshot in another comment. I'm not sure if this is just an issue for me because, when I tried it the next day, I didn't recieve this error again. Anyway I am now unable to build my OS because there is a MissingMethoException in the Cosmos.HAL class when trying to switch to a VGAScreen...

**Comment by mterwoord** [comment]
Are you using a custom built devkit? If so, are you changing kernel code?

**Comment by mterwoord** [comment]
Could you please post a screenshot?

Also, are you on a userkit or on devkit?

**Comment by Ray1015** [comment]
CPU Exception x09: Invalid Characters In Your Code. Example: `<`, `>`,

**Comment by mterwoord** [comment]
Can you provide the code you used to reproduce?

**Comment by Ray1015** [comment]
// <summary>
// </summary>

**Comment by mterwoord** [comment]
Can you provide sample code to reproduce the issue?
