### ISSUE TITLE
Constantly appearing NullReferenceException

### ISSUE THREAD

**Issue by tihonryzhikov** [CosmosOS/Cosmos#1980]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel.

#### Expected Behaviour - What do you think that should happen?
Successfully OS boot.

#### Actual Behaviour - What unexpectedly happens?
NullReferenceException throwing

#### Reproduction - How did you get this error to appear?
Nothing. Default code doesn't working

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest DevKit(MemoryManager branch).

**Comment by quajak** [comment]
Please be more specific. Could you add some code to reproduce the issue? What is throwing the NullReferenceException?

**Comment by Winksplorer** [comment]
> Please be more specific. Could you add some code to reproduce the issue? What is throwing the NullReferenceException?

i think he means the default `Cosmos Booted Successfully` code.

**Comment by tihonryzhikov** [comment]
> > Please be more specific. Could you add some code to reproduce the issue? What is throwing the NullReferenceException?
> 
> i think he means the default `Cosmos Booted Successfully` code.

Yes, I mean this code.

```
using System;
using Sys = Cosmos.System;

namespace Lightning
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
            Console.Read();
        }

        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}
```

**Comment by quajak** [comment]
Is VS throwing the exception or the kernel?

**Comment by tihonryzhikov** [comment]
> Is VS throwing the exception or the kernel?

Kernel. OS starts and exception throwing after successful connection with debugger

**Comment by quajak** [comment]
The issue was that Cosmos was on the MemoryManager branch while IL2CPU was on master, which means that there was an incongruency in how the Virtual Method Table was being initialised (too few values being sent by the Il2CPU side). Keeping both on master or both on MemoryManager should fix the problem.
