### ISSUE TITLE
NullReferenceException Thrown On idling in 90x60 text mode

### ISSUE THREAD

**Issue by Winksplorer** [CosmosOS/Cosmos#1983]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel
Exact File: il2cpu\source\cosmos.il2cpu\vtablesimpl.cs line 175

#### Expected Behaviour - What do you think that should happen?
it should be able to idle for a longer time.

#### Actual Behaviour - What unexpectedly happens?
cosmos debug engine is saying a NullReferenceException Happened in SystemUInt32CosmosIL2CPUVTablesImplGetMethodAddressForTypeSystemUInt32SystemUInt32.

it seems like pressing keys makes the time to crash shorter.

#### Reproduction - How did you get this error to appear?
```cs
VGAScreen.SetTextMode(Cosmos.HAL.VGADriver.TextSize.Size90x60);
Console.WriteLine(timestr);
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
dev kit v106027 latest revision

**Comment by quajak** [comment]
How long does it idle?

**Comment by Winksplorer** [comment]
5 minutes, but with a lot of key presses it gets shorter

**Comment by quajak** [comment]
are you sure that this does not happen with normal resolution?

it seems like its a memory problem

**Comment by MishaTY** [comment]
Can this be reproduced with new memory manager merged?

**Comment by quajak** [comment]
Its important to also call Heap.Collect from time to time if this is an out of memory problem

**Comment by Winksplorer** [comment]
Just a little comment, I fixed this, In TextScreen.CS there is the rows and columns which i edit for line clearing. And the code that reserves memory for the screen has separate rows and columns value which i forgot the change. so yeah.
