### ISSUE TITLE
80x25 Line Clearing In 90x60

### ISSUE THREAD

**Issue by Winksplorer** [CosmosOS/Cosmos#1984]
#### Area of Cosmos - What area of Cosmos are we dealing with?
lines

#### Expected Behaviour - What do you think that should happen?
The Whole Line Should be cleared.

#### Actual Behaviour - What unexpectedly happens?
It Thinks The Screen Is 80x25 When It Isn't, So This Happens.
![image](https://user-images.githubusercontent.com/49623720/140244503-68c62a79-b1e5-4605-adfb-6a5e20b8d77e.png)

#### Reproduction - How did you get this error to appear?
Use Any Console Command That Uses Lines, for example, writeline and readline.
In A 90x60 Console.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
dev kit 106027 latest revision

**Comment by quajak** [comment]
It looks like TextScreen.cs https://github.com/CosmosOS/Cosmos/blob/afc07521701e638241b7ecdf527e108dfc7b7171/source/Cosmos.HAL2/TextScreen.cs#L12 and https://github.com/CosmosOS/Cosmos/blob/afc07521701e638241b7ecdf527e108dfc7b7171/source/Cosmos.System2/Graphics/VGATextMode.cs#L10 dont communicate currently, which means that TextScreen never understands that the VGA changed resolution. Further TextScreen cant currently handle other sizes, although that should be relatively easily fixed.

I think the best way to fix this is to merge Core.IOGroup.TextScreen into the VGATextMode and then update the HAL2.TextScreen to also have a change of mode method.

@valentinbreiz @MishaTY @charlesbetros  Any experience with/thoughts on this?
