### ISSUE TITLE
Thread.Sleep stops working after using once Console.Beep

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#1985]
#### Area of Cosmos - What area of Cosmos are we dealing with?
HAL

#### Expected Behaviour - What do you think that should happen?
Thread.Sleep pauses for an amount of milliseconds

#### Actual Behaviour - What unexpectedly happens?
It pauses forever

#### Reproduction - How did you get this error to appear?
```cs
System.Console.Beep(37, 1000);
System.Threading.Thread.Sleep(4);
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
c092bcf82b1d3380bc36b98caaac75113c6efea4 (memorymanager)

**EDIT:** I've figured out that the problem happens because the PCSpeaker class uses its own instance of PIT while Thread.Sleep uses the one in Cosmos.HAL.Global

**Comment by ilobilo** [comment]
If thread.sleep uses pit as timer maybe Beep doesn't reset PIT frequency

**Comment by LuftKatzeBASIC** [comment]
Use this

```
void Sleep(int ms)
        {
            for (int i = 0; i < ms * 100000; i++) 
            {
                ;
                ;
                ;
                ;
                ;
            }
        }
 ```

**Comment by Project-Magenta** [comment]
The problem happens because the PCSpeaker class uses its own instance of PIT while Thread.Sleep uses the one in Cosmos.HAL.Global

**Comment by Project-Magenta** [comment]
@Siaranite

**Comment by quajak** [comment]
> EDIT: I've figured out that the problem happens because the PCSpeaker class uses its own instance of PIT while Thread.Sleep uses the one in Cosmos.HAL.Global

Good find, this should be fixable by just making PCSpeaker also use the same instance of PIT.

**Comment by zarlo** [comment]
we should move Thread.Sleep to some thing like APIC so then its per CPU core

**Comment by quajak** [comment]
Yeah APIC would be better but thats seperate from this issue.
