### ISSUE TITLE
Weird bitmap colors

### ISSUE THREAD

**Issue by tihonryzhikov** [CosmosOS/Cosmos#1987]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
Normal bitmap draw

#### Actual Behaviour - What unexpectedly happens?
Bitmap draws, but colors is weird

#### Reproduction - How did you get this error to appear?
Just bitmap drawing

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos(MemoryManager), IL2CPU(MemoryManager), Common(Latest), XSharp(Latest)

Original image:
![blogo](https://user-images.githubusercontent.com/66679206/140608046-d6c43f3c-a578-44ca-bd68-83eb7fbd80f4.png)

And what I get:
![image](https://user-images.githubusercontent.com/66679206/140608053-4fc9ff80-5097-40f6-8858-30a1b269a72b.png)

**Comment by quajak** [comment]
Is the bitmap 24 or 32bits?

**Comment by tihonryzhikov** [comment]
> Is the bitmap 24 or 32bits?

24bits

**Comment by quajak** [comment]
Did you try both Pixel formats?

**Comment by tihonryzhikov** [comment]
> Did you try both Pixel formats?

Yes. First, I'm tried to draw BGR pixel format image(from Paint, 24bpp) and draw it. After i get drawed image, but with weird colors.
Second, I'm tried to draw RGB pixel format image(from Photoshop, 24bpp) and draw it(I'm change in Bitmap pixel format to RGB). Doesn't draws, just black screen.
