### ISSUE TITLE
GIT Pull ?

### ISSUE THREAD

**Issue by mmkhmmkh** [CosmosOS/Cosmos#199]
Hi everyone.
I dont know how to get sources with git pull ( because i want Filesystem ) and ARMmaster said that FIlesystem is available on git pull ( https://github.com/CosmosOS/Cosmos/issues/190 )
I have git installed on my Windows.

**Comment by mterwoord** [comment]
IUt's in sentinels playground project. It's not completed yet..

**Comment by mmkhmmkh** [comment]
When it completes ?

**Comment by mterwoord** [comment]
Not sure, Charles is currently busy with other things (non-cosmos related)...

**Comment by mterwoord** [comment]
If this issue is taken care of, please close it. Thanks!

**Comment by ARMmaster17** [comment]
@mmkhmmkh if you want to play with the current codebase (without FS), go to `My Documents` and create a folder (name doesn't matter, just don't use spaces or symbols). Go into the folder, and right-click on an empty space. On the menu that pops up, click *Open Git Bash*. When that opens, type in `git clone https://github.com/CosmosOS/Cosmos.git` and press enter. If in the future you want to update the codebase with the current one, right-click and open the git bash again and type `git pull`. It may ask you for your GitHub login to run these commands depending on how you have your Git configured.

---

If your question has been answered or solution has been resolved, please click *Close Issue*. Thanks!
