### ISSUE TITLE
how to make apps for cosmos c#

### ISSUE THREAD

**Issue by EndermanPC** [CosmosOS/Cosmos#1996]
i finished the work with cosmos but i cant find any way to make an app on cosmos
I'm new to cosmos and I'm not very good at it
help me
thanks in advance

**Comment by Andreas010** [comment]
Please further describe your issue, e.g. What do you mean by "App".

If you want something like the Windows cmd or others, where you can type an app's name and make it execute, you gotta do that on your own in C#, e.g. with a Console.ReadLine() and then somehow figuring out, what to run with what arguments

**Comment by EndermanPC** [comment]
hmm, i just want to create a simple application like cmd on windows, i want us to enter a deep command and it will open, i don't know how to activate an application in cosmos

**Comment by Andrej123456789** [comment]
@EndermanPC I think you think about third party developer which create executable for your OS developed by Cosmos Kit
