### ISSUE TITLE
Boot OS on real hardware

### ISSUE THREAD

**Issue by Andrej123456789** [CosmosOS/Cosmos#1998]
**What is the usecase for this plug**
Boot operating system made by Cosmos Kit on real hardware

** Complexity of plug **
I am not sure, probably it's not so complex

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by reisxd** [comment]
See https://github.com/CosmosOS/Cosmos/wiki/Booting-Your-OS-from-a-USB-Drive

**Comment by Andrej123456789** [comment]
Ok. Thanks
