### ISSUE TITLE
class file not working in cosmos

### ISSUE THREAD

**Issue by EndermanPC** [CosmosOS/Cosmos#2001]
i create a class file in universe, i don't understand why it doesn't work (i mean: create a class file and use it in kernel)

**Comment by valentinbreiz** [comment]
hello which version of Cosmos are you using? 
And could you provide me your source code?

**Comment by EndermanPC** [comment]
![image](https://user-images.githubusercontent.com/88751712/141612796-a73eef31-2174-41ea-b0a0-ce430fcaaea4.png)
this is the version i am using
==========================
this is my class file
![image](https://user-images.githubusercontent.com/88751712/141612905-5347d46f-12fe-40a5-b0e3-8153f80797e5.png)
and this is my kernel,  this is where i use the layer file\
![image](https://user-images.githubusercontent.com/88751712/141613045-9e813a94-9e2e-4029-9550-65b03e06b49d.png)
![image](https://user-images.githubusercontent.com/88751712/141613060-055219f1-ea37-4031-8a3b-812d239d6a32.png)

**Comment by EndermanPC** [comment]
if you want, If you want, I can provide more

**Comment by KM198912** [comment]
You cannot call a class like this, you can only call it like Endergui.test();
