### ISSUE TITLE
mkisofs error code 13

### ISSUE THREAD

**Issue by 404Dev-404** [CosmosOS/Cosmos#2010]
Have you checked Github Issues for similar errors?
I checked Issue #1753. I tried every solution I saw but it didn't fix it

**Exception**
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"mkisofs.exe" exited with code 13.	Theory64	C:\Users\Tony\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets	323	

** VS Output Logs **
Build started...
1>------ Build started: Project: Theory64, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>Theory64 -> C:\Users\Tony\source\repos\Theory64\bin\Debug\netcoreapp2.0\cosmos\Theory64.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Tony\source\repos\Theory64\bin\Debug\netcoreapp2.0\cosmos\Theory64.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:00:23.1431126
1>Nasm task took 00:00:30.6914707
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\netcoreapp2.0\cosmos\Theory64.bin bin\Debug\netcoreapp2.0\cosmos\Theory64.obj
1>LD task took 00:00:00.5657069
1>Extracting Map file...
1>Extracting Map file took 00:01:25.6662118
1>-relaxed-filenames -J -R -o bin\Debug\netcoreapp2.0\cosmos\Theory64.iso -b isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table bin\Debug\netcoreapp2.0\cosmos\ISO
1>mkisofs : warning : -rock has same effect as -rational-rock on this platform.
1>MAKEISO : warning : creating filesystem that does not conform to ISO-9660.
1>mkisofs: Permission denied. Unable to open disc image file
1>C:\Users\Tony\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets(323,9): error MSB6006: "mkisofs.exe" exited with code 13.
1>Done building project "Theory64.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NETSDK1138	The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.	Theory64	C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets	28	
Severity	Code	Description	Project	File	Line	Suppression State
Warning		-rock has same effect as -rational-rock on this platform.	Theory64	C:\Users\Tony\source\repos\Theory64\mkisofs	1	
Severity	Code	Description	Project	File	Line	Suppression State
Warning		creating filesystem that does not conform to ISO-9660.	Theory64	C:\Users\Tony\source\repos\Theory64\MAKEISO	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"mkisofs.exe" exited with code 13.	Theory64	C:\Users\Tony\.nuget\packages\cosmos.build\0.1.0-localbuild20200708061311\build\Cosmos.Build.targets	323	

**To Reproduce**
IDK Here's the code:
`
using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace Theory64
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;
        private readonly Bitmap bitmap = new Bitmap(10, 10,
                new byte[] { 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255,
                    23, 59, 88, 255, 0, 255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255, 23, 59, 88, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255, 153, 57, 12, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 0, 255, 243, 255, 153, 57, 12, 255, 23, 59, 88, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243,
                    255, 0, 255, 243, 255, 0, 255, 243, 255, 72, 72, 72, 255, 72, 72, 72, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 72, 72,
                    72, 255, 72, 72, 72, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 10, 66, 148, 255, 10, 66, 148, 255,
                    10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148,
                    255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, }, ColorDepth.ColorDepth32);
        protected override void BeforeRun()
        {
            Console.WriteLine("Theory64 loaded.");
            Console.WriteLine("Entering Graphics Mode");
            try
            {
                canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(640,
                                                                       480,
                                                                       ColorDepth.ColorDepth32));
            }
            catch (Exception e)
            {
                Console.WriteLine("Error Initializing Graphics Mode.");
                Console.WriteLine(e.ToString());
                Console.WriteLine("Press key to reboot");
                Console.ReadKey();
                Sys.Power.Reboot();
            }
        }

        protected override void Run()
        {
            canvas.DrawImage(bitmap, new Point(100, 150));
        }
    }
}
`

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[Yes] Both Cosmos VS Extensions are installed
[No] In the NuGet Package Manager "Include prerelease" is selected
[?] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[?] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by quajak** [comment]
To be clear, restarting VS does not help?

**Comment by 404Dev-404** [comment]
i made a new project and after a while it happened again

**Comment by quajak** [comment]
Can you check which process is blocking access to the file?

**Comment by 404Dev-404** [comment]
i would guess hyper-v but it happens even when it isn't running
