### ISSUE TITLE
IL2CPU task failed. - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TFTWPhoenix** [CosmosOS/Cosmos#2011]
Have you checked Github Issues for similar errors?
Yes, didn't find anything that was within the last few years (tried the solutions in the outdated ones i did find however, no luck)
**Exception**
Post the exception returned by Visual Studio

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
```
Build started...
1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>CosmosKernel1 -> C:\Users\tftwp\source\repos\CosmosKernel1\bin\Debug\net5.0\CosmosKernel1.dll
1>IL2CPU task took 00:00:00.0001047
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018: The "IL2CPU" task failed unexpectedly.
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018:    at Cosmos.Build.Tasks.IL2CPU.GenerateResponseFileCommands() in C:\Users\tftwp\Documents\Cosmos\source\Cosmos.Build.Tasks\IL2CPU.cs:line 78
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018:    at Cosmos.Build.Tasks.IL2CPU.Execute() in C:\Users\tftwp\Documents\Cosmos\source\Cosmos.Build.Tasks\IL2CPU.cs:line 116
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\tftwp\.nuget\packages\cosmos.build\0.1.0-localbuild20211118063126\build\Cosmos.Build.targets(172,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "CosmosKernel1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```
**To Reproduce**
This issue occurs with the default kernel.

**Screenshots**

**Context**
Before posting please confirm that the following are in order
- [x] Both Cosmos VS Extensions are installed
- [x] In the NuGet Package Manager "Include prerelease" is selected
- [x] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
- [x] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
This is also a clean installation of VS2022 and the Cosmos devkit.
(Using VS2022 branch of cosmos incase that has any relevance to this)

**Comment by KM198912** [comment]
Should have been fixed with https://github.com/CosmosOS/IL2CPU/commit/8b073a3d0ef7c61509e19a629d434b5951ccbdbd , please try pulling il2cpu and report back

**Comment by TFTWPhoenix** [comment]
On that commit. Just checked.

**Comment by KM198912** [comment]
what happens if you add this: <CompileVBEMultiboot>False</CompileVBEMultiboot>
        <VBEResolution>800x600x32</VBEResolution> to your csproj file

**Comment by TFTWPhoenix** [comment]
just within <Project></Project>?

**Comment by TFTWPhoenix** [comment]
Nevermind, found where it goes. Waiting for this to build to see if it still breaks or not. Isn't immediately giving the error like it was

**Comment by TFTWPhoenix** [comment]
Well now it looks like its having issues finding System.Runtime? IL2CPU ran fine tho.

![image](https://user-images.githubusercontent.com/61560519/142562773-dfc163bc-5d38-4b0c-9d0c-28ced5915d6b.png)

**Comment by KM198912** [comment]
i have that too at times, it recently popped up and i havent figured out why yet, i usually disable the debugger and run it directly in vmware

**Comment by TFTWPhoenix** [comment]
![image](https://user-images.githubusercontent.com/61560519/142563621-7ae23b1a-d88f-4714-9a78-e53a0f9364a5.png)
how would i go about disabling that? it looks like its already disabled?

**Comment by KM198912** [comment]
Have a look here https://github.com/CosmosOS/Cosmos/wiki/Cosmos-on-Visual-Studio-2022

**Comment by TFTWPhoenix** [comment]
Tyvm
