### ISSUE TITLE
Cannot install to Visual Studio

### ISSUE THREAD

**Issue by Max0824** [CosmosOS/Cosmos#2022]
Describe the problem:
When i run install-VS2019.bat it says "msbuild not found."

well idk

Expected behavior
Expected it to install and pop up in Visual Studio.

Setup
Cosmos Version: DevKit
Admin account: No
VS Version: 2022 Community Edition?

Additional context
Just refuses to say that visual studio exists.

**Comment by valentinbreiz** [comment]
Which branch are using? Visual Studio 2022 is not supported in master

**Comment by Max0824** [comment]
...Branch? Well, I did some digging and my version is 17.0.1 if thats helpful

**Comment by Max0824** [comment]
Also how can it support vs 2022?

**Comment by valentinbreiz** [comment]
> ...Branch? Well, I did some digging and my version is 17.0.1 if thats helpful

Are you familiar to git?

> Also how can it support vs 2022?

VS2022 support is currently in work and will be merged soon (see https://github.com/CosmosOS/Cosmos/pull/2009)

**Comment by KM198912** [comment]
you can use git clone https://github.com/CosmosOS/Cosmos --branch VS2022 for more info you can also check here:
https://github.com/CosmosOS/Cosmos/wiki/Cosmos-on-Visual-Studio-2022

**Comment by Max0824** [comment]
Thx. I'll just wait then!

**Comment by Max0824** [comment]
Nvm, it doesnt work. My new q -> https://github.com/CosmosOS/Cosmos/issues/2023
