### ISSUE TITLE
install-VS2022.bat failing (File missing?)

### ISSUE THREAD

**Issue by Max0824** [CosmosOS/Cosmos#2023]
**Describe the problem**
A clear and concise description of where the installation is going wrong.
When I run install-VS2022.bat it says C:\source\CosmosOS\Cosmos\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error MSB4236: The SDK 'Microsoft.N
ET.Sdk' specified could not be found.

**Steps of installation up to now**
Downloaded the VS-2022 branch. Ran install-VS2022.bat. Error above.

**Expected behavior**
I expected it to install correctly.

**Logs**
Please post the entire log given by Cosmos. For long logs please use pastebin.
Looking for MSBuild
Building Builder.sln
C:\source\CosmosOS\Cosmos\source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj : error MSB4236: The SDK 'Microsoft.N
ET.Sdk' specified could not be found.

**Setup (please complete the following information):**
Cosmos Version: Dev Kit.
Admin account: No.
VS Version: VS Community 2022, 17.0.1

**Additional context**
OS: Windows 11 Home, build 21H2

**Comment by quajak** [comment]
Do you have the .net 5 runtime installed?

**Comment by Max0824** [comment]
Wait a sec.... no, I have ver. 4.8.04161 installed lemme go fix that now

**Comment by Max0824** [comment]
Installed .NET 5.0, now it says this:
![C__WINDOWS_system32_cmd exe 11_28_2021 7_34_25 PM](https://user-images.githubusercontent.com/76849308/143795755-f112642f-6c95-49f6-9d1c-2be0480b8b88.png)

**Comment by quajak** [comment]
Could be related to #1978

**Comment by Max0824** [comment]
Nope, the Cosmos location is 'C:\source\CosmosOS\Cosmos'.

**Comment by Max0824** [comment]
My cosmos tree:
<pre>-C:\
--source\
---CosmosOS\
----Common\
-----files...
----Cosmos\
-----files...
----IL2CPU\
-----files...
----XSharp
-----files...</pre>

**Comment by Max0824** [comment]
Wait, could a space in the user folder be a problem? The user path is <pre>C:\Users\Maxwell Patrick</pre>

**Comment by Max0824** [comment]
Ok, i changed the user folder name and now its saying the version (5.0.0.0) does not match version! (4.1.2.0)
Full log here: https://pastebin.com/7VRenUdm

**Comment by Max0824** [comment]
Just ran it again and it ran fine. Cant find it in VS Studio 2022 though

**Comment by Max0824** [comment]
Nvm, its in there! Thx for your help!!

**Comment by Winksplorer** [comment]
If anyone is here with the same issue and this doesn't help much, try uninstalling all x86 distros of .NET, worked for me.
