### ISSUE TITLE
Unable to find Cosmos in Boot Picker

### ISSUE THREAD

**Issue by TizuHD** [CosmosOS/Cosmos#2024]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting Cosmos on real hardware

#### Expected Behaviour - What do you think that should happen?
Cosmos should boot.

#### Actual Behaviour - What unexpectedly happens?
Cosmos won't be displayed in the boot picker.

#### Reproduction - How did you get this error to appear?
1. Create a simple OS using cosmos.
2. Compile it (ISO preset)
3. Burn it onto an USB stick using Rufus
4. Try to boot from it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20200708

**Comment by RSTPlays** [comment]
It’s probably because your using the Aptio BIOS. Same thing happened to me, the USB didn’t show up. Try use it on a different pc
