### ISSUE TITLE
Cosmos Debugger Bug

### ISSUE THREAD

**Issue by jwoff78** [CosmosOS/Cosmos#2030]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I was debugging my OS and ran into an issue

#### Expected Behaviour - What do you think that should happen?
Debugger should have loaded the OS and ran it as normal

#### Actual Behaviour - What unexpectedly happens?
Debugger Crashed so did the OS due to null reference exception, I could not find a null reference exception.
I am not sure what issue is but I got screenshots

#### Reproduction - How did you get this error to appear?
I am unsure how issue was produced I was building my OS builds are on bitbucket, and I was using debugger and it couldn't load the OS due to null reference exception but there was no null reference exception anywhere

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using Dev Kit

Link for picture of crash - [Imgur](https://imgur.com/a/PLtO4IC)

**Comment by MishaTY** [comment]
The error message shows exactly where the null reference exception occurs, and it occurred in your OS.
