### ISSUE TITLE
GitHub CI nuget restore command: Unable to find package Cosmos.System2. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by EnZon3** [CosmosOS/Cosmos#2035]
**Describe the problem**
A clear and concise description of where the installation is going wrong.
While trying to set up GitHub CI for my OS, apparently some of the nuget Cosmos packages cannot be found.
I would say this issue classifies as installation because GitHub Actions can't install the required dependencies for Cosmos.

**Steps of installation up to now**
Set up GitHub CI using the dotnet template, change the 'Restore dependencies' section command to nuget restore or dotnet restore.
Commit to repos

**Expected behavior**
As before a commit the latest build is tested to work, the CI results should be successful.

**Logs**
Please post the entire log given by Cosmos. For long logs please use Pastebin.
Well, I'm too lazy to upload to Pastebin so I'm just gonna use the service that I always use:
https://textuploader.com/t58e7

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): Userkit
 - Are you using an admin account?: Yes
 - VS Version if applicable: 2019

**Additional context**
The building in VS is fine, the only problem is GitHub actions.

**Comment by EnZon3** [comment]
Hold on gotta upload a new log uri expired

**Comment by EnZon3** [comment]
> Hold on gotta upload a new log uri expired

Fixed

**Comment by MishaTY** [comment]
That's because cosmos is not installed.

**Comment by EnZon3** [comment]
Then how do you install it on GitHub actions?

**Comment by MishaTY** [comment]
See https://github.com/CosmosOS/Cosmos/blob/master/appveyor.yml

**Comment by valentinbreiz** [comment]
Hello @EnZon3, if you want I made a github action script to check the build on AuraOS.

https://github.com/aura-systems/Aura-Operating-System/blob/master/.github/workflows/dotnet-core.yml

**Comment by EnZon3** [comment]
> Hello @EnZon3, I think that it can be interesting for you, I made a github action workflow to check the build on AuraOS.
> 
> https://github.com/aura-systems/Aura-Operating-System/blob/master/.github/workflows/dotnet-core.yml

Thanks!

**Comment by EnZon3** [comment]
> Hello @EnZon3, I think that it can be interesting for you, I made a github action workflow to check the build on AuraOS.
> 
> https://github.com/aura-systems/Aura-Operating-System/blob/master/.github/workflows/dotnet-core.yml

Also, do I have to modify anything to get it to work with my repos?
