### ISSUE TITLE
Cosmos does not appear!

### ISSUE THREAD

**Issue by TCFFFANYT** [CosmosOS/Cosmos#2037]
![image](https://user-images.githubusercontent.com/95889972/146545927-65d253b4-5135-4300-a400-81410ec220b7.png)

**Comment by MishaTY** [comment]
Please ask on the discord server for these types of issues.

**Comment by TCFFFANYT** [comment]
> Please ask on the discord server for these types of issues.

Sorry, I don't have discord.

**Comment by TCFFFANYT** [comment]
Also, can you reopen this?

**Comment by valentinbreiz** [comment]
Hello @TCFFFANYT, did you install the userkit or devkit?

**Comment by RSTPlays** [comment]
Hi, have you tried to restart your machine? If it doesn't work try and reinstall the **user kit** instead

**Comment by roboisaac11** [comment]
What version of visual studio do you have? if it's 2022, It wont work, at least, for me it didn't. You'll have to use 2019
