### ISSUE TITLE
How can I show the date and time in CosmosOS C# ?

### ISSUE THREAD

**Issue by RSTPlays** [CosmosOS/Cosmos#2051]
Hello, I need it where if I type date, it shows the date and time. I already have the command but I need it to do something.

**Comment by TiM-SyStEm** [comment]
Hello, first  import Cosmos.HAL.RTC, `using Date = Cosmos.HAL.RTC;`, now to find out the time or date you can use **Date.Year, Date.Month, Date.Hour, Date.Minute, Date.Second**

**Comment by RSTPlays** [comment]
Thank you so much! When I get back from Work i'll try it out.

**Comment by TiM-SyStEm** [comment]
ok, if anything, write

**Comment by RSTPlays** [comment]
sure

**Comment by RSTPlays** [comment]
How can I change the font of the cosmos command prompt?

**Comment by TiM-SyStEm** [comment]
quite interesting but I do not know that

**Comment by RSTPlays** [comment]
ive seen aura-systems do it with there operating system

**Comment by TiM-SyStEm** [comment]
Yes, the aura is made on Cosmos

**Comment by RSTPlays** [comment]
If they changed the system font, how can I?
