### ISSUE TITLE
swbemlocator not found

### ISSUE THREAD

**Issue by BioShot** [CosmosOS/Cosmos#2055]
When i try to install Cosmos UserKit 2020vs2019 it gives me this error: swbemlocator not found. i have vs c++ tools but i have no idea whats going on, can anybody help me?

**Comment by zarlo** [comment]
can you send the full error log

**Comment by BioShot** [comment]
> can you send the full error log

That was the full error

**Comment by RSTPlays** [comment]
send the error please, we need more info on what your talking about

**Comment by BioShot** [comment]
Ok so, when i click on the installer(in my downloads) it prompts a password(Because im not an admin my gradian enters it. aka my parent) and then it says language i click english then click next, then i get this error "SWBEMLocator not found" then i click the ok button then exit. So, i have check and have everything gocosmos.org says. but still, it does not work. If you guys find a find a way to fix it that would be great! on weekdays i will be responding around 4:10 to 8:30 pm EST. Cheers, have a nice day.

**Comment by quajak** [comment]
Some part of the inno setup is failing, which almost never fails. The easiest way to fix this is to download the dev kit and remove lines https://github.com/CosmosOS/Cosmos/blob/master/Setup/Cosmos.iss#L159-L230 from the inno file and then run the installer script.

**Comment by BioShot** [comment]
Ok, Thanks! I Will try that. If it does not work. I will let you know, :)

**Comment by BioShot** [comment]
Hey Sorry, Quick Question Lol. What do i run. im getting ALOTTTT OF Errors.

**Comment by BioShot** [comment]
When i run the Cosmos.iss file i get this error message. (After i delete code) Line 19: Column 21: Expression expected but opening brace ("{") found.

**Comment by BioShot** [comment]
And it can't find this file: "E:\Cosmos\,\Build\VSIP\IL2CPU"

**Comment by BioShot** [comment]
it also cannot find anything in the VSIP folder

**Comment by BioShot** [comment]
I think i may have fix it. I commited some source things out. nvm it says its installed. i have had a couple errors. can somebody fork there working project and send it?

**Comment by quajak** [comment]
What are the errors you are getting now?

**Comment by quajak** [comment]
> it also cannot find anything in the VSIP folder

You are still running install-VS2019.bat to install cosmos?

**Comment by BioShot** [comment]
ok, i dont even know what swbemlocator is(kinda). im guessing because my pc is 7 years old and was upgraded from windows 11 to 10

**Comment by quajak** [comment]
My recommended fix above for now would be to remove the part form the inno setup which uses swbemlocator. What error did you get after removing the lines + getting iss file compiling again and then rerunning install-vs2019.bat?

**Comment by BioShot** [comment]
Hey! So i got a screen shot for you
![Capture](https://user-images.githubusercontent.com/86807700/156907869-eea66ba1-c15c-4f48-be20-3361f1c84931.PNG)
.

**Comment by BioShot** [comment]
And here is one for the vs2019 installer
![Capture2](https://user-images.githubusercontent.com/86807700/156907913-61eca42d-0dde-44dc-b194-c76ad5575af0.PNG)

**Comment by BioShot** [comment]
Hope this helps :)

**Comment by quajak** [comment]
Thank you, the new error is very unexpected. Could you please open Builder.sln and show what configuration is currently selected?
