### ISSUE TITLE
VMDK file links for VFS in wiki are broken

### ISSUE THREAD

**Issue by EnZon3** [CosmosOS/Cosmos#2058]
#### URL of Documentation - What page of documentation are we dealing with?
https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

#### Expected Behaviour - What do you think should happen?
The links at the bottom for the VMDK links should bring me to a download

#### Actual Behaviour - What is the issue?
it brings me to a 404

**Comment by MishaTY** [comment]
fixed it
