### ISSUE TITLE
Dev kit installation problem.

### ISSUE THREAD

**Issue by Loiuy123** [CosmosOS/Cosmos#2059]
Hey, trying to install Dev Kit.

![image](https://user-images.githubusercontent.com/26145867/149221995-dc4ac2c9-bdd5-4f4d-9165-705613b0c324.png)

It asks me to install ".Net Core 4.8 SDK" but there is not such a version. Latest Core version is 3.1 or 3.2. 
What am I supposed to do?

**Comment by MishaTY** [comment]
install the .net 4.8 sdk, and .net 5 runtime and sdk

**Comment by Loiuy123** [comment]
> install the .net 4.8 sdk, and .net 5 runtime and sdk

Should I report it as a bug?

**Comment by MishaTY** [comment]
I guess it's a bug

**Comment by Loiuy123** [comment]
Okey, there is a problem.

I have `.net 4.8 sdk, and .net 5 runtime and sdk` installed.

**Comment by Mantaraix** [comment]
![image](https://user-images.githubusercontent.com/51055281/149238060-80163c1f-e73e-4752-904e-12cba1b4b4e5.png)
make sure u have these
