### ISSUE TITLE
Question about installing Cosmos

### ISSUE THREAD

**Issue by mchinitz** [CosmosOS/Cosmos#206]
Hi,

I am trying to install the Cosmos user kit on my Windows 7 machine. I have already installed VS 2015. I get the following error message: "Either Visual Studio 2013 or Visual Studio 2013 (integrated shell) is installed! Please see CodePlex documentation for supported editions/versions of Visual Studio." I have already tried getting rid of older versions of Visual Studio, but I still get the same error.

Thanks for you help,
Michael Chinitz

**Comment by mterwoord** [comment]
In the current userkit, there's a bug in that message. It's supposed to say "is NOT installed". In other words: the current userkit only supports VS2013.

If you want to get going with 2015, you can use the devkit..

**Comment by emersont1** [comment]
You can create a userkit from the devkit. You just need the extensibility tools
You can do this by doing the following:
+ make sure you have VMware installed
+ install [Inno Setup](http://www.jrsoftware.org/isinfo.php)
+ clone the repo and open `source/builder.sln` in VS  
   * if you do not have the extensibility tools installed, open `source/build.sln` and you will be prompted to install the extensibility tools
+ add `-bat -vs2015 -USERKIT` to the command line parameters
+ run in VS
+ run the installer in `setup/output`
+ restart VS
There should be VB and C# cosmos template

**Comment by mterwoord** [comment]
Doing it this way actually doesn't make sense, it's what the install-VS2015.bat script does.

Also, make sure you have the innosetup quickstart pack.

**Comment by emersont1** [comment]
Even with innosetup installed, the builder doesn't seem to work outside vs on my machine

**Comment by mterwoord** [comment]
Then, like I said before, we should find out what's wrong, instead of working around it.. ;)
