### ISSUE TITLE
How can I display images such as .png files in Cosmos C#

### ISSUE THREAD

**Issue by RSTPlays** [CosmosOS/Cosmos#2061]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I'd like to display my OS's logo, it is a .png file. How can I display that?

#### Expected Behaviour - What do you think that should happen?
N/A

#### Actual Behaviour - What unexpectedly happens?
N/A

#### Reproduction - How did you get this error to appear?
N/A

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

**Comment by MishaTY** [comment]
You can only display bmp files.

**Comment by RSTPlays** [comment]
How may I do that?
