### ISSUE TITLE
How to display .bmp images in Cosmos OS C#

### ISSUE THREAD

**Issue by RSTPlays** [CosmosOS/Cosmos#2062]
#### Area of Cosmos - What area of Cosmos are we dealing with?
How can I display .bmp images? I'd like to use this for my logo

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

**Comment by zarlo** [comment]
you can use this https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Graphics/Canvas.cs#L852

**Comment by RSTPlays** [comment]
What shall I do with this?

**Comment by valentinbreiz** [comment]
Hello @RSTPlays,
You have to load your image first like here:

`Bitmap bitmap = new Bitmap(Convert.FromBase64String(yourBitmapFileInBase64));`

And then draw it like this:

`canvas.DrawImage(bitmap, x, y);`

I close this.

**Comment by RSTPlays** [comment]
Oh thank you so much! I'll try to give it a go. Thanks, but how can I convert it to Base64?

**Comment by RSTPlays** [comment]
Ok I figured how you  work it out, but the x, y. What are those going to be used for?

**Comment by valentinbreiz** [comment]
The location of the image on screen

**Comment by RSTPlays** [comment]
I'm getting this error, how can I fix tha
![Screenshot 2022-01-31 191858](https://user-images.githubusercontent.com/80816207/151863761-5e5aeeb6-cf0d-41c9-961b-234fedec6475.png)
t?
