### ISSUE TITLE
USB Keyboard won't work on real hardware

### ISSUE THREAD

**Issue by RSTPlays** [CosmosOS/Cosmos#2064]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I booted my OS on real hardware and everything works except the keyboard.

#### Expected Behaviour - What do you think that should happen?
When I type letters should show

#### Actual Behaviour - What unexpectedly happens?
Nothing happens

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by BlitzWolfMatthew** [comment]
Cosmos does not support USB Keyboard.
