### ISSUE TITLE
Cosmos Kernel project type does not exist in VS2022

### ISSUE THREAD

**Issue by AlubJ** [CosmosOS/Cosmos#2065]
**Describe the problem**
The installation of Cosmos is fine, however, the Cosmos Kernel project type does not exist in VS2022. The .NET Framework 4.6.2 is installed and the NuGet packages show up in the NuGet package manager.

**Steps of installation up to now**
Installation went fine.

**Expected behavior**
Cosmos Kernel project type to exist.

**Logs**
N/A

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): Userkit Latest
 - Are you using an admin account? Yes
 - VS Version if applicable 17.0.2

**Additional context**
N/A

**Comment by litecave** [comment]
latest installer were maded when it was only vs2019, so you can use vs2019 for now instead

**Comment by Kiirx** [comment]
you can use cosmos for VS2022 but you need to change the branch of cosmos to VS2022 and run install-VS2022.bat
