### ISSUE TITLE
Project File Not found

### ISSUE THREAD

**Issue by abjdev** [CosmosOS/Cosmos#2066]
**Describe the problem**
??

**Steps of installation up to now**
??

**Expected behavior**
I got MSB3202 and it says Cosmos.Build.Common.csproj,  not found 

**Logs**

========================================
    Build Log
========================================

========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"N:\vs2019\MSBuild\Current\Bin\MSBuild.exe" "C:\source\CosmosOS\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:"Net48=True" /p:DeployExtension=False
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.Net48.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]

========================================
    Error
========================================

The process failed to execute!
_Sorry,_Im using Turkish language._
Error: 
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]
N:\vs2019\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(290,5): error MSB3202: "C:\source\CosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.Net48.csproj" proje dosyasì bulunamadì. [C:\source\CosmosOS\Cosmos\Build.sln]

**Steup (please complete the following information):**
 - Cosmos Version: Im using userkit. But i am working on building devkit
 - Are you using an admin account?: NO
 - VS Version if applicable: 2019

**Additional context**
My English is bad, sorry.

**Comment by BlitzWolfMatthew** [comment]
I am not sure if you can run both the userkit and the adminkit at once.

**Comment by zarlo** [comment]
when you install a devkit or userkit it will remove what ever you currently have installed

**Comment by abjdev** [comment]
I removed User Kit but i got this:
![image](https://user-images.githubusercontent.com/91409956/150370492-92b4aebc-173d-4003-a57a-8435613b826a.png)

**Comment by abjdev** [comment]
Yes, I installed MSBuild, but i had CS1705 Error:


========================================
    Error
========================================

The process failed to execute!
Error: 
CSC : error CS1705: 'IL2CPU.Debug.Symbols.Net48, Version=10.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16' kimlikli 'IL2CPU.Debug.Symbols.Net48' derlemesi, baƒvurulan 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' kimlikli 'System.Runtime' derlemesinden daha yüksek sürüme sahip 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' kullanìyor [C:\source\CosmosOS\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]

**Comment by abjdev** [comment]
YEA! I'M INSTALLED THE DEV KIT!! IT TOOKS ME 2 MONTH BUT THATS AVESOME
