### ISSUE TITLE
How do i draw a string in cosmos graphic?

### ISSUE THREAD

**Issue by saluransains** [CosmosOS/Cosmos#2078]
### Discussed in https://github.com/CosmosOS/Cosmos/discussions/2077

<div type='discussions-op-text'>

<sup>Originally posted by **saluransains** January 28, 2022</sup>
How do I Draw a String in cosmos graphic?</div>

**Comment by RSTPlays** [comment]
Same I need help, but I think AuraOS did something like that. I recommend you take a look at there source code
