### ISSUE TITLE
Problem building project

### ISSUE THREAD

**Issue by bobbinkin** [CosmosOS/Cosmos#208]
whenever I attempt to build or debug a project, I recieve the same warning. 
Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosSystemKernelStart': System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(SymbolFormat symFormat, String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 133
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 106
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 99
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(String aAsmPathname, Int32 aMethodToken, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 347
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(MethodBase aMethod, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 342
2>	   at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 175
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 472 ---> System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(SymbolFormat symFormat, String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 133
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 106
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 99
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(String aAsmPathname, Int32 aMethodToken, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 347
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(MethodBase aMethod, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 342
2>	   at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 175
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 472
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238

Whic is followed by
 Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.4592606
2>Done building project "CosmosKernel5Boot.Cosmos" -- FAILED.
2>
Build has been canceled.

I dont know what to do. Thanks, 
bobbinkin

**Comment by mterwoord** [comment]
Please install .net 3.5. That should fix it. 

It's needed (for now..) to access debug information inside pdb files.

**Comment by bobbinkin** [comment]
When I attempt to install .NET 3.5 I recieve an error saying I already have it or a higher version...

**Comment by bobbinkin** [comment]
I resolved this issue sometime yesterday but forgot to mention it (sorry) 
The problem was that I already had 3.5, yet I needed to enable it by going to the "Enable a programm" tool in control panel. 

Thanks a bunch! 
-Bobbinkin
