### ISSUE TITLE
Cosmos can't find Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2080]
**Describe the problem**
When I try to install lask devkit vs2019 I get this error.
![Capture d’écran 2022-02-03 225938](https://user-images.githubusercontent.com/43090601/152436226-8d320002-3790-42f6-883b-58672b712a1e.png)
(It cant find 'Microsoft.NET.Sdk' and the error message says: Windows can't find the path to the builder.exe)
**Steps of installation up to now**

**Expected behavior**
The build should show up and begin

**Logs**
posted on the phote

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) none
 - Are you using an admin account? Yes
 - VS Version if applicable VS2019

**Comment by Kiirx** [comment]
![image](https://user-images.githubusercontent.com/43090601/152436569-f0d59c9c-8295-4d4b-9727-7dc26c1fca2e.png)
the bin folder isnt here

**Comment by MishaTY** [comment]
Try installing .net 5 sdk

**Comment by Kiirx** [comment]
-_- its already installed

**Comment by Kiirx** [comment]
how do I reopen

**Comment by Kiirx** [comment]
ok so now after building the builder on visual studio it can open now but with this ```
========================================
    Build Log
========================================


========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.


========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "D:\Documents\cosmosOS\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\IL2CPU\IL2CPU.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\XSharp\source\XSharp\XSharp\XSharp.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\XSharp\source\XSharp\XSharp\XSharp.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\TheRingMaster\TheRingMaster.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\TheRingMaster\TheRingMaster.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\Tools\NASM\NASM.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\Tools\NASM\NASM.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\XSharp\source\Spruce\Spruce.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\XSharp\source\Spruce\Spruce.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\Cosmos\Resources\Dependencies\DapperExtensions.StrongName\DapperExtensions.StrongName.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\Cosmos\Resources\Dependencies\DapperExtensions.StrongName\DapperExtensions.StrongName.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols.Net48\IL2CPU.Debug.Symbols.Net48.csproj : warning NU1503: Ignorer la restauration du projet 'D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols.Net48\IL2CPU.Debug.Symbols.Net48.csproj'. Il est possible que le fichier projet ne soit pas valide ou qu'il ne contienne pas toutes les cibles nécessaires à la restauration. [D:\Documents\cosmosOS\Cosmos\Build.sln]
  Identification des projets à restaurer...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning : Projet à restaurer introuvable ! [D:\Documents\cosmosOS\Cosmos\Build.sln]


========================================
    Build - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "D:\Documents\cosmosOS\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Build" /p:"OutputPath=D:\Documents\cosmosOS\Cosmos\Build\VSIP\\" /p:"VsixOutputPath=D:\Documents\cosmosOS\Cosmos\Build\VSIP\\" /p:DeployExtension=False
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\XSharp\source\XSharp\XSharp\XSharp.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\TheRingMaster\TheRingMaster.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Tools\NASM\NASM.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\XSharp\source\Spruce\Spruce.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Resources\Dependencies\DapperExtensions.StrongName\DapperExtensions.StrongName.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols.Net48\IL2CPU.Debug.Symbols.Net48.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU\IL2CPU.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : error MSB4236: Le SDK 'Microsoft.NET.SDK' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.


========================================
    Error
========================================

The process failed to execute!
Error: 
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\XSharp\source\XSharp\XSharp\XSharp.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\TheRingMaster\TheRingMaster.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Tools\NASM\NASM.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\XSharp\source\Spruce\Spruce.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Common\source\VSPropertyPages\VSPropertyPages.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\Resources\Dependencies\DapperExtensions.StrongName\DapperExtensions.StrongName.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols.Net48\IL2CPU.Debug.Symbols.Net48.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\IL2CPU\IL2CPU.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : error MSB4236: Le SDK 'Microsoft.NET.SDK' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.
D:\Documents\cosmosOS\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj : error MSB4236: Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable.


```
![image](https://user-images.githubusercontent.com/43090601/152526037-b6dc44a2-58ed-4427-ae0e-e41247fc0411.png)

**Comment by Kiirx** [comment]
I fixed this by adding MSbuild to a variable path

**Comment by Kiirx** [comment]
but now nuget times out when installing packages
