### ISSUE TITLE
Not Implemented: Write

### ISSUE THREAD

**Issue by dsdude123** [CosmosOS/Cosmos#209]
"Not Implemented: Write" is printed if multiple arguments are provided to Write() and WriteLine().

Example:

Console.Write("Lol", "Test")
 
would print "Not Implemented: Write". The only way around this is to use multiple Write statements.

![capture](https://cloud.githubusercontent.com/assets/14354266/9972834/3eb8b7ca-5e1e-11e5-826e-0c76cae9fb9a.PNG)

**Comment by mterwoord** [comment]
Are you interested in helping us out? It should be easy to write a plug for this overload..

**Comment by dsdude123** [comment]
Depends what language the plugs need to be written in, I only know VB.NET, C#, and Java. I'm also a full-time student so it may take me a week or two depending on how much free time I have.

**Comment by mterwoord** [comment]
Please join our gitter chat. Lots of knowledge there....


Most plugs are implemented by normal c# code.

**Comment by dsdude123** [comment]
Should the plug be added to Cosmos.System.Plugs.System.Console?

**Comment by mterwoord** [comment]
Correct!

**Comment by dsdude123** [comment]
Wonderful, I currently have a plug that is partially working. If I declare 3 different objects and try to write them using 

Console.Write(a,b,c); 

It acts as if the plug doesn't exist asks for different arguments (it asks for string format and params object[] arg). However, if I reference Cosmos.System.Plugs in my project and use

Cosmos.System.Plugs.System.ConsoleImpl.Write(a, b, c); 

It works perfectly fine. Any reason why this would happen? A copy of the method I added is below.

public static void Write(params object[] args)
        {
            foreach (object value in args)
            {
                Write(value.ToString());
            }

        }

**Comment by mterwoord** [comment]
Please verify, using ilspy or a similar tool, which overload of Console.Write is being used in your situation....

**Comment by Cyber4** [comment]
Why would you need to Console.Write("Lol", "Hi");
?

**Comment by mterwoord** [comment]
var xInput = Console.ReadLine();
Console.Write("Value was: ", xInput);

**Comment by Fireflies** [comment]
>Why would you need to Console.Write("Lol", "Hi");
>?

Perhaps you may wish to write calculated data, input from ReadLine as @mterwoord pointed out or maybe you just feel like it?

**Comment by dsdude123** [comment]
How does one use ilspy? I've never used it before. That aside, here's a screen shot of what I'm talking about:
![badarg](https://cloud.githubusercontent.com/assets/14354266/10261536/b6ca7882-6951-11e5-81ca-1d07bab70279.png)

**Comment by mterwoord** [comment]
Install the ILSpy VS extension. That's the easiest route to take. Then right-click your project in the solution explorer and select "Open output in ILSpy". Then find your method, and on the right it'll decompile the method. On top you have a combobox for selecting decompilation language. Change it to IL, and you can see exactly which Write overload you're using.

**Comment by dsdude123** [comment]
Which project am I supposed to open in ILSpy? If it's the one above where I'm trying to test Console.Write(), I can't because VS fails to build because the arguments are invalid because it's expecting different arguments.

**Comment by mterwoord** [comment]
You get a cosmos build error, but then your class library is already built. Open that one in ILSpy.

**Comment by dsdude123** [comment]
The build is failing when building the class library. As a result, ILSpy says it cant find the assembly.

1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>C:\Users\Conner\AppData\Local\Temporary Projects\CosmosKernel1\Kernel.cs(20,27,20,28): error CS1503: Argument 1: cannot convert from 'object' to 'string'
Build has been canceled.

**Comment by mterwoord** [comment]
Well, that's a c# error then. You'll first have to fix that.

**Comment by dsdude123** [comment]
That's where I'm stuck. When I type Console.Write(a ,b, c). It gives the error I pasted above but when I type Cosmos.System.Plugs.System.ConsoleImpl.Write(a, b, c) It builds just fine.

**Comment by mterwoord** [comment]
that means you made a "plug" for a method that doesn't exist.

**Comment by dsdude123** [comment]
Oh, that would make sense, perhaps I should make plugs for the other write methods that aren't implemented then?

**Comment by mterwoord** [comment]
Yes! Please! :)

**Comment by dsdude123** [comment]
Okay, I'll start working on that. Sorry for any confusion I have caused, it has been awhile since I really did much coding in C# (was busy with learning Java) so I tend to forget some things.

**Comment by dsdude123** [comment]
Okay so I did some work on the code and have hit a roadblock. String.Format appears to be needing a plug. My code relies on String.Format so I'm kinda left in a tough situation. Any advice on what to do about this?

**Comment by mterwoord** [comment]
Your best bet is to refactor your code to not rely on String.Format....

**Comment by charlesbetros** [comment]
String.Format is implemented now.

**Comment by mterwoord** [comment]
So I'd say issue can be closed?

**Comment by charlesbetros** [comment]
I think it just needs verification.
