### ISSUE TITLE
How can I make a mouse in Cosmos?

### ISSUE THREAD

**Issue by RSTPlays** [CosmosOS/Cosmos#2091]
#### Area of Cosmos - What area of Cosmos are we dealing with?
How can I make a mouse in CosmosOS
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit C#

**Comment by MishaTY** [comment]
https://github.com/CosmosOS/Cosmos/discussions/2089
