### ISSUE TITLE
[Devkit] Cannot check CPU on last devkit

### ISSUE THREAD

**Issue by fusedevgithub** [CosmosOS/Cosmos#2103]
#### Area of Cosmos - What area of Cosmos are we dealing with?

CPU Checking (System info)

#### Expected Behaviour - What do you think that should happen?
Fixed it on the last devkit

#### Actual Behaviour - What unexpectedly happens?
Kernel Panic 0x290
CPU Exception x05

#### Reproduction - How did you get this error to appear?
First, this bug does not happen in devkit (13/1/2022) but after I upgraded to the last devkit today that crashing with Kernel Panic
This is my check CPU model code:
```
Console.WriteLine("CPU: " + CPU.GetCPUBrandString());
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Devkit C#

**Comment by fusedevgithub** [comment]
if you need a screenshot okay.
![panic](https://cdn.discordapp.com/attachments/833978908189392916/940953239237562388/unknown.png)

**Comment by valentinbreiz** [comment]
I have the same issue, it's due to changes with the new memory manager

**Comment by quajak** [comment]
Fixed by #2101

**Comment by quajak** [comment]
Nvm

**Comment by valentinbreiz** [comment]
It should indeed be fixed with last commits, could you try it @fusedevgithub
