### ISSUE TITLE
Could not load file or assembly 'Cosmos.Debug.Kernel',Version =10.0.0.0

### ISSUE THREAD

**Issue by penguin-number-123** [CosmosOS/Cosmos#2105]
Have you checked Github Issues for similar errors?
Yes
**Exception**
Post the exception returned by Visual Studio
System.IO.FileLoadException: Could not load file or assembly 'Cosmos.Debug.Kernel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'.	PiniguinDOS	C:\Users\Mumuji\source\repos\Penguin OS\PiniguinDOS\Error	1	

** VS Output Logs **
1>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'Cosmos.Debug.Kernel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'.
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
1>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
1>IL2CPU task took 00:00:00.1068218
1>Done building project "PiniguinDOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
**To Reproduce**
Install newest userkit, and create a new kernel, then run.

**Screenshots**
![image](https://user-images.githubusercontent.com/62600889/153317326-0312c1b5-035f-4864-8f0a-6adbcac90b68.png)
![image](https://user-images.githubusercontent.com/62600889/153317368-0aa2e7c1-260f-4fd8-bb69-7915fec1a3be.png)

**Context**
Before posting please confirm that the following are in order
[T] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

Using latest userkit
Originally after updating vs2019 could not detect cosmos, though it is a project option. The file was recreated and the problems went away, however this one persists.

**Comment by penguin-number-123** [comment]
![image](https://user-images.githubusercontent.com/62600889/153319028-35d1036a-07c7-4198-86c8-7af85321d685.png)
![image](https://user-images.githubusercontent.com/62600889/153319096-f28cde0b-25c5-4c91-970d-9b873ca104e4.png)


Cosmos seems to be installed, I cannot confirm with NuGet as I have not used it before.

**Comment by penguin-number-123** [comment]
![image](https://user-images.githubusercontent.com/62600889/153319273-16de89e8-5e93-44ef-bc92-800e8434bbfb.png)
here is output logs

**Comment by penguin-number-123** [comment]
After a fresh install, the error persists.

**Comment by penguin-number-123** [comment]
![image](https://user-images.githubusercontent.com/62600889/153333324-125ae036-2346-484d-8178-0173e8965ecc.png)
After using NuGet package Manager, this is what the installed things are
None of them are version  10, not sure why it is asking for v10.

**Comment by quajak** [comment]
Can you clear the nuget cache?

**Comment by penguin-number-123** [comment]
Ok so here are instructions on how to fix it.

1) Go to tools -> NuGet Package Manager -> Package Manager Settings -> Clear cache
2) Go to tools -> NuGet Package Manager -> Package Manager Settings -> Manage NuGet packages for solution
3) uninstall the "Cosmos debug kernel"
4) Click on browse
5) Near the top right corner where it says "Manage Packages for Solution", click on that and choose Cosmos Local Package Feed
6) Choose "Include prerelease"
7) Reinstall "Cosmos.Debug.Kernel"
8) right click the something.sln file, then choose rebuild
It should work after that.
If you get any missing files, rerun the installer and do the steps again.

**Comment by realrandombeans** [comment]
Still got the same issue.
