### ISSUE TITLE
Is there a way to modify the boot messages?

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2107]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel

**Comment by Kiirx** [comment]
I wanted to modify them because its not coherent

**Comment by Kiirx** [comment]
![Screenshot 2022-02-07 120301](https://user-images.githubusercontent.com/43090601/153453177-6be4ed9c-298a-420e-9d79-3db9a87addb9.png)
look

**Comment by Kiirx** [comment]
I want the lines like Starting ACPI to have at the beginning of the line

**Comment by quajak** [comment]
So would a method to be overwritten in kernel be better? For example `void Kernel.BootEvent(string message)` which allows the user to do with what ever he needs?

**Comment by Kiirx** [comment]
like, these boot messages, I want to customize them 
![image](https://user-images.githubusercontent.com/43090601/153460497-eee1e75c-6e56-4e54-bd15-3ddb271b6270.png)

**Comment by KM198912** [comment]
> So would a method to be overwritten in kernel be better? For example `void Kernel.BootEvent(string message)` which allows the user to do with what ever he needs?

i will look into it, i have to revisit the driver enable anyhow

**Comment by Kiirx** [comment]
no, I think I'll just do a plug

**Comment by swordlink1** [comment]
![forgithub](https://user-images.githubusercontent.com/55672893/160670579-fbc072fc-78c2-44a0-b6be-e59431d293aa.png)
Like this?

**Comment by Kiirx** [comment]
yes
