### ISSUE TITLE
System.IO.FileLoaderException: Could not load file or assembly Cosmos.Debug.Kernel

### ISSUE THREAD

**Issue by realrandombeans** [CosmosOS/Cosmos#2110]
![image](https://user-images.githubusercontent.com/97028115/153651463-90002e1c-1ff7-456a-bec2-a2cb914dea59.png)

Please help.

**Comment by quajak** [comment]
Are you using devkit/userkit?

**Comment by realrandombeans** [comment]
Latest userkit.

**Comment by valentinbreiz** [comment]
Hello @realrandombeans, could you try this userkit build? https://anonfiles.com/hfgbd4Idx4/CosmosUserKit-20220214-vs2019_exe

**Comment by AnnoyingB** [comment]
I had the same problem and tried downloading that user kit and I am still having the same problem.

**Comment by quajak** [comment]
Clear the nuget cache and try again.

**Comment by quajak** [comment]
Are the nuget packages installed from the devkit or from the userkit?

**Comment by AnnoyingB** [comment]
user

**Comment by quajak** [comment]
Can you post the entire build log?

**Comment by AnnoyingB** [comment]
![image](https://user-images.githubusercontent.com/81764357/162497935-c3738585-d983-4542-bbaf-f5ce62676498.png)

**Comment by quajak** [comment]
Can you post your csproj file?

**Comment by AnnoyingB** [comment]
https://www.file.io/BP57/download/uICvMrA2DRx9

**Comment by quajak** [comment]
Thanks, can you show which versions of the nuget packages you have installed?

**Comment by AnnoyingB** [comment]
how?

**Comment by AnnoyingB** [comment]
it's V3

**Comment by quajak** [comment]
In the nuget package manager it should show you which version is installed for each package.

**Comment by YarikDev2008** [comment]
i has same problem
while i trying clean nuget cache popups error
i reinstalled cosmos seveal times, but it won't work

**Comment by RockZombie4** [comment]
maybe just reinstall user kit ..?

**Comment by AnnoyingB** [comment]
already been tried 4 times

**Comment by quajak** [comment]
The issue is that the local nuget cache on the machine still contains old versions which have a higher version number than the new correct packages. To fix this please clear the local nuget cache and then check which nuget package versions are installed for the cosmos packages.

**Comment by AnnoyingB** [comment]
That isn't really fixing my problem

**Comment by quajak** [comment]
> In the nuget package manager in visual studio can you show the list of all available versions for the cosmos nuget packages?

Can you please post this information? Otherwise we can triage and fix this issue.

**Comment by AnnoyingB** [comment]
![image](https://user-images.githubusercontent.com/81764357/171708981-30512985-b3d2-4f3b-9757-fdc86ab3b970.png)

**Comment by AnnoyingB** [comment]
I just reinstalled cosmos yesterday though

**Comment by AnnoyingB** [comment]
i just checked and the only ones there are from February

**Comment by AnnoyingB** [comment]
i was looking at release oops

**Comment by AnnoyingB** [comment]
I am having the same problem as #1623

**Comment by AnnoyingB** [comment]
i can't find cosmos template

**Comment by AnnoyingB** [comment]
vs 2022

**Comment by quajak** [comment]
You are on the newest devkit?

**Comment by AnnoyingB** [comment]
Yes.
