### ISSUE TITLE
Graphics example draws only black screen

### ISSUE THREAD

**Issue by astromediaonly** [CosmosOS/Cosmos#2111]
#### URL of Documentation - What page of documentation are we dealing with?
https://www.gocosmos.org/docs/cosmos-graphic-subsystem/

#### Expected Behaviour - What do you think should happen?
Example here should draw something else than black screen I suppose.

#### Actual Behaviour - What is the issue?
Makes black screen (atleast while run by default with VMWare Workstation). Latest version of Cosmos as far as I know.
Also I had to add ``using System.Drawing;`` not mentioned there to get ``Color`` to not throw errors. Maybe issue is because of this somehow?

**Comment by penguin-number-123** [comment]
You likely forgot canvas.Display();

**Comment by astromediaonly** [comment]
Oh ... that was not mentioned there ... now its working, thanks ... this graphics stuff is changing so much its hard to find reliable examples and so ... I would appretiate if atleast official "working example" was realy working (updated) :)

**Comment by quajak** [comment]
Which official working example do you mean?

**Comment by astromediaonly** [comment]
The code under the header "A working example" on page mentioned in my initial topic: https://www.gocosmos.org/docs/cosmos-graphic-subsystem/

```
using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace GraphicTest
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;

        protected override void BeforeRun()
        {
            
            Console.WriteLine("Cosmos booted successfully. Let's go in Graphic Mode");
            canvas = FullScreenCanvas.GetFullScreenCanvas();
            canvas.Clear(Color.Blue);
        }

        protected override void Run()
        {
            try
            {
                
                Pen pen = new Pen(Color.Red);
                canvas.DrawPoint(pen, 69, 69);

                
                pen.Color = Color.GreenYellow;
                canvas.DrawLine(pen, 250, 100, 400, 100);

                
                pen.Color = Color.IndianRed;
                canvas.DrawLine(pen, 350, 150, 350, 250);

                
                pen.Color = Color.MintCream;
                canvas.DrawLine(pen, 250, 150, 400, 250);

                
                pen.Color = Color.PaleVioletRed;
                canvas.DrawRectangle(pen, 350, 350, 80, 60);

                Console.ReadKey();

                
                canvas.Mode = new Mode(800, 600, ColorDepth.ColorDepth32);

                
                pen.Color = Color.LimeGreen;
                canvas.DrawRectangle(pen, 450, 450, 80, 60);

                Console.ReadKey();

                Stop();
            }
            catch (Exception e)
            {
                mDebugger.Send("Exception occurred: " + e.Message);
                mDebugger.Send(e.Message);
                Stop();
            }
        }
    }
}
```

Its clearly no longer working because of missing using statement and ``canvas.Display()`` method calls.

**Comment by quajak** [comment]
Thanks, I updated the article located at https://cosmosos.github.io/articles/Kernel/CGS.html. I have made the gocososmos link point to that one as well.
