### ISSUE TITLE
Cannot use 1280*960 colordepth 32 for VBECanvas

### ISSUE THREAD

**Issue by penguin-number-123** [CosmosOS/Cosmos#2112]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphic, specifically VBECanvas

#### Expected Behaviour - What do you think that should happen?
It should display a azure screen with a simple mouse (Like in Canvas)

#### Actual Behaviour - What unexpectedly happens?
It does not appear to enter Graphic mode.

#### Reproduction - How did you get this error to appear?
VBECanvas canvas = new(new(1280,960,(ColorDepth)32));
The problem is I do not know the supported things, as it is still listed

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit, latest.

**Comment by penguin-number-123** [comment]
![image](https://user-images.githubusercontent.com/62600889/153701005-7ce41846-1af7-4fd4-a132-4181b3246beb.png)

**Comment by quajak** [comment]
The supported modes are listed here. https://github.com/CosmosOS/Cosmos/blob/d1ac2c20cb7448c09dcbad19da50d684520d72bf/source/Cosmos.System2/Graphics/VBECanvas.cs#L129
