### ISSUE TITLE
Cosmos not showing up in Visual Studio 2022

### ISSUE THREAD

**Issue by aHappyConstant** [CosmosOS/Cosmos#2113]
**Describe the problem**
So I installed Visual Studio 2022 and Cosmos User Kit but the project is not showing up

![image](https://user-images.githubusercontent.com/97287115/153707822-f08d0bea-bf4b-4895-931b-e978a4f74627.png)

**Steps of installation up to now**
Install Visual Studio 2022 Community and Cosmos User Kit (in C:/Users/*username*/AppData/Roaming)
(Replace the *username* with your Windows username)

**Expected behavior**
I thought that the project will show up

**Logs**
I didn't find any logs

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): Userkit
 - Are you using an admin account?: Yes
 - VS Version if applicable: Visual Studio 2022 17.06

**Additional context**
Before Visual Studio 2022, I installed Cosmos and it worked. After resetting my PC (don't ask me why) Visual Studio 2022 was released, I installed that and now I can't use Cosmos

**Comment by The-Anonymous-Developer** [comment]
Read the documentation, Cosmos supports VS 2019 and **only** VS 2019.

**Comment by quajak** [comment]
Cosmos should also work with VS2019 community edition, there is a pr for VS2022 support but it is still wip.

**Comment by aHappyConstant** [comment]
> Read the documentation, Cosmos supports VS 2019 and **only** VS 2019.

Thank you for this. If other people are reading this, please create a account/sign in Azure DevOps in order to get Visual Studio 2019 and older versions (its free btw)

**Comment by The-Anonymous-Developer** [comment]
No problem, happy I could help.
