### ISSUE TITLE
Could not load file or assembly 'Cosmos.Debug.Kernel, Version= 10.0.0.0'

### ISSUE THREAD

**Issue by realrandombeans** [CosmosOS/Cosmos#2116]
Have you checked Github Issues for similar errors?
Yes, but no solutions worked
**Exception**
![image](https://user-images.githubusercontent.com/97028115/153729873-e873b37f-de07-4355-bb7f-d9f40d2f9105.png)

**To Reproduce**
Install the latest userkit

How can I fix it?

**Comment by fusedevgithub** [comment]
try this:
https://github.com/CosmosOS/Cosmos/issues/2114#issuecomment-1037136042
