### ISSUE TITLE
VGA 320x200x8 has 6-bit color

### ISSUE THREAD

**Issue by z-targz** [CosmosOS/Cosmos#212]
So, when using the 320x200x8 mode, there is a problem.  Instead of having 8 bit color with 0x00 to 0xff, it only supports 0x00 to 0x3f, aka 6-bit color or 64 colors.

**Comment by mihail-rotmg** [comment]
I also have that problem.
When i use any color bigger than 6-bit i get black color

**Comment by mihail-rotmg** [comment]
https://en.wikipedia.org/wiki/List_of_monochrome_and_RGB_palettes#6-bit_RGB
There is no 8-bit color.

**Comment by Cyber4** [comment]
What about the 3-3-2 mode? I was assuming that is what it would be using

**Comment by fanoI** [comment]
I think too that it should support 256 colors... maybe a palette issue?

By the way I'm having a worst problem I cannot draw a pixel onto the screen!

This the code I'm using:

`
protected override void BeforeRun()
        {
            VGA.SetGraphicsMode(ScreenSize.Size320x200, ColorDepth.BitDepth8);
            //VGA.Clear(0);
            VGA.SetPixel(42, 42, 0x000003);
      }
`

In Run is simply an empty infinite loop...
Do you do something different?

**Comment by quajak** [comment]
Has this issue been fixed by changes to CGS?
