### ISSUE TITLE
Simplified Chinese garbled 

### ISSUE THREAD

**Issue by MasterYuan418** [CosmosOS/Cosmos#2121]
**Describe the problem**
When I try to install Cosmos with Release, I'm getting a garbled error in Simplified Chinese for the installer.
![图片](https://user-images.githubusercontent.com/58651976/153784113-82f396b4-e3bf-4a28-9c72-bf1ea23b7355.png)

**Steps of installation up to now**

1. Download Userkit.
2. Run,and select 'Simplified Chinese' language.

**Expected behavior**
Install application will display the content normally.

**Logs**
No logs.

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit): **Userkit 20220209**
 - Are you using an admin account? **Yes**
 - VS Version if applicable **16.11.9**

**Additional context**
No additional context.

**Comment by penguin-number-123** [comment]
Possible that the encoding is different, this happens when I have files with Chinese names and google drive turns them to garbled characters. Maybe you can reverse the process...

**Comment by MishaTY** [comment]
Can you test this with the latest version of innosetup?
