### ISSUE TITLE
Devkit simply doesn't want to install. Builder.exe missing.

### ISSUE THREAD

**Issue by realrandombeans** [CosmosOS/Cosmos#2122]
**Describe the problem**
Whenever I run Install-VS2019.bat, I get the following error:
![image](https://user-images.githubusercontent.com/97028115/153913364-df91164e-25a9-47d4-84de-ccb2f221ecd8.png)

**Steps of installation up to now**
Download the devkit, and run the bat file.
**Expected behavior**
I expected it to install the devkit, but it didn't.
**Logs**
![image](https://user-images.githubusercontent.com/97028115/153913535-52c67838-2af8-47ae-adc4-7812efbdf924.png)

**Additional info**
I have a second drive (D:) which the devkit is on.
I have downloaded the devkit as a .zip off Github.

**Comment by quajak** [comment]
Could you try install cosmos at a location where the path has no spaces?

**Comment by realrandombeans** [comment]
> Could you try install cosmos at a location where the path has no spaces?

How can I do that? I tried putting the folder in C:\Cosmos-master\Cosmos but it didn't work.

**Comment by zarlo** [comment]
> > Could you try install cosmos at a location where the path has no spaces?
> 
> How can I do that? I tried putting the folder in C:\Cosmos-master\Cosmos but it didn't work.

how did it not work, did you get any errors

**Comment by realrandombeans** [comment]
> > > Could you try install cosmos at a location where the path has no spaces?
> > 
> > 
> > How can I do that? I tried putting the folder in C:\Cosmos-master\Cosmos but it didn't work.
> 
> how did it not work, did you get any errors

Yes, just those errors in the original message.

**Comment by quajak** [comment]
Can you please post the screenshot/log since I really doubt that the current path has the same not recognized issue?

**Comment by quajak** [comment]
Just whats written to the screen.

**Comment by realrandombeans** [comment]
![image](https://user-images.githubusercontent.com/97028115/155130413-ce51b3d9-7cee-4137-b9e4-fada8b315d3d.png)
![image](https://user-images.githubusercontent.com/97028115/155130483-b4e82931-b17f-48b7-94bd-1b1e55812655.png)
^ This is the errors I found in Build.sln

**Comment by MishaTY** [comment]
Fixed
