### ISSUE TITLE
VS giving weird nuget errors on every project after updating Cosmos

### ISSUE THREAD

**Issue by virtualtoja** [CosmosOS/Cosmos#2123]
Have you checked Github Issues for similar errors?
Yes

**Exception**
Code	Severity	Description	Project	Project Rank	File	Line	Suppression State
NU1202	Error	Package Cosmos.System2 0.1.0-localbuild20220209054647 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / cosmos. Package Cosmos.System2 0.1.0-localbuild20220209054647 supports: net5.0 (.NETCoreApp,Version=v5.0)	ScamOS	1	C:\Users\User\source\repos\ScamOS\ScamOS\ScamOS.csproj	1	

Code	Severity	Description	Project	Project Rank	File	Line	Suppression State
NU1202	Error	Package Cosmos.System2 0.1.0-localbuild20220209054647 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Cosmos.System2 0.1.0-localbuild20220209054647 supports: net5.0 (.NETCoreApp,Version=v5.0)	ScamOS	1	C:\Users\User\source\repos\ScamOS\ScamOS\ScamOS.csproj	1	

** VS Output Logs **
I cant:
![obraz](https://user-images.githubusercontent.com/76951241/153947732-babdc366-b678-45fa-9956-a01a661fa430.png)

**To Reproduce**
Create a new project and try to open it

**Screenshots**
![obraz](https://user-images.githubusercontent.com/76951241/153947571-61670329-8008-4d12-9190-bb56cd6115ef.png)

![obraz](https://user-images.githubusercontent.com/76951241/153947610-c6a24be0-8aaa-4d5e-98ce-bd6d95d03688.png)

**Context**
Before posting please confirm that the following are in order
[X ] Both Cosmos VS Extensions are installed
[X ] In the NuGet Package Manager "Include prerelease" is selected
[X] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[X ] The Cosmos NuGet packages are installed

**Comment by Kiirx** [comment]
.Net 2.0 is really old and now outdated and unsupported, please install .Net 5.0 instead

**Comment by fusedevgithub** [comment]
This bugs is can fixed by
you need just create new project
and copy file eg. kernel.cs from old project folder to new project folder.
location of file
```
C:\Users\USERNAME\source\repos\
```
Normally CosmosOS older version cannot use with CosmosOS newer but you can export file from CosmosOS old project to newer.
and 90% that will working.
