### ISSUE TITLE
Error MSB6006: "yasm.exe" exited with code -1073741515.

### ISSUE THREAD

**Issue by pto-buon** [CosmosOS/Cosmos#2127]
**Exception**
Error MSB6006: "yasm.exe" exited with code -1073741515.

**VS Output Logs**

Build started...
1>------ Build started: Project: BootNet, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>BootNet -> C:\Users\Pto\source\repos\BootNet\BootNet\bin\Debug\net5.0\BootNet.dll
1>-g dwarf2 -f elf -o bin\Debug\net5.0\BootNet.obj -dELF_COMPILATION -O0 bin\Debug\net5.0\BootNet.asm
1>C:\Users\Pto\.nuget\packages\cosmos.build\0.1.0-localbuild20220219121807\build\Cosmos.Build.targets(214,9): error MSB6006: "yasm.exe" exited with code -1073741515.
1>Yasm task took 00:00:00.0762604
1>Done building project "BootNet.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
I have installed Visual Studio 2022, VMware Workstation 16 Player and Cosmos Dev Kit 20220209 on branch VS2022

**Context**
Before posting please confirm that the following are in order
[ x] Both Cosmos VS Extensions are installed
[ x] In the NuGet Package Manager "Include prerelease" is selected
[ x] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ x] The Cosmos NuGet packages are installed

**Comment by quajak** [comment]
Could you post your code?

**Comment by valentinbreiz** [comment]
Hello, please see https://github.com/CosmosOS/Cosmos/issues/2102

**Comment by pto-buon** [comment]
I installed Visual C++ 2010 but I still have problems with debugging and building. I just wanted to ask: do I need to reinstall Cosmos dev kit to make it work?

**Comment by quajak** [comment]
Please open a new issue for those issues. Installing the devkit should not be required.
