### ISSUE TITLE
VGA 640x480x4 does not write to planes correctly

### ISSUE THREAD

**Issue by Cyber4** [CosmosOS/Cosmos#213]
the 640x480x4 VGA driver does not correctly write to the four planes.  Also, the clear function is broken and causes a crash.

**Comment by CSharpLover** [comment]
It is fixed.

**Comment by mterwoord** [comment]
@CSharpLover So this issue can be closed?

**Comment by CSharpLover** [comment]
Yes, i was fixed this before (and its pr was merged) so it can be closed now, yes.
