### ISSUE TITLE
Heap.Collect() not working correctly

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2131]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Heap.Collect()

#### Expected Behaviour - What do you think that should happen?
It should work fine with the OS

#### Actual Behaviour - What unexpectedly happens?
Time doesnt work and fps is always at 0

#### Reproduction - How did you get this error to appear?
use Heap.Collect() method

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
last devkit

without Heap.Collect():
![image](https://user-images.githubusercontent.com/43090601/154848623-923af6c7-ce3e-4a0e-9a89-2c832dba200e.png)

with Heap.Collect():
![image](https://cdn.discordapp.com/attachments/833978908189392916/944947034765533244/unknown.png)

**Comment by quajak** [comment]
Heap.Collect is not free, so it will have an effect on the FPS. The current time value seems to be an actual bug, do you have a short piece of code, preferably without graphics, which reproduces the problem?

**Comment by Kiirx** [comment]
I only do `canvas.DrawString($"{RTC.Hour}:{RTC.Minute}.{RTC.Second}", PCScreenFont.Default, BlackPen, (int) screenWidth - 70, 3);` and it doesnt work when I use Heap.Collect

**Comment by BlitzWolfMatthew** [comment]
In my experience with using VBECanvas, Heap.Collect() still lets the OS crash.

**Comment by quajak** [comment]
I will look into the RTC issue.

> In my experience with using VBECanvas, Heap.Collect() still lets the OS crash. It literally does not change a thing, only make it slower.

Heap.Collect does not depend on VBECanvas at all. If you are still having memory leaks please open a new issue with code to reproduce the issue.

**Comment by Kiirx** [comment]
I'll look at it when @misha will add the vFS plug to crossplatform branch because without it I cant run my OS

**Comment by valentinbreiz** [comment]
I think it's because you're calling PCScreenFont.Default and it's allocating a new font every time, make a copy don't call it directly
