### ISSUE TITLE
Canvas's image scaling method gives images a severe yellow tint and significantly darkens them

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2134]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
The image should be properly scaled, with it looking mostly the same.

#### Actual Behaviour - What unexpectedly happens?
the image gets scaled correctly, but has a severe yellow tint and is darkened a lot (examples below)

#### Reproduction - How did you get this error to appear?
use Canvas.ScaleImage

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest devkit

#### Screenshots
![VirtualBox_Prism_24_02_2022_14_11
![Wallpaper](https://user-images.githubusercontent.com/76945439/155801068-90437cd3-2495-41e4-80b2-be828b3a077b.png)
_55](https://user-images.githubusercontent.com/76945439/155800724-2f3cdfdc-e0cb-455e-a70c-438bc3a1cdad.png)
s

**Comment by Kiirx** [comment]
try converting to .bmp with this site, it always work https://image.online-convert.com/fr/convertir-en-bmp

**Comment by terminal-cs** [comment]
> try converting to .bmp with this site, it always work https://image.online-convert.com/fr/convertir-en-bmp

it is already bmp.

**Comment by Kiirx** [comment]
yes I know just do it again
the site you used probably converted the image to .bmp incorrectly

**Comment by MishaTY** [comment]
Your color order or bmp is invalid.
