### ISSUE TITLE
How do I format a drive?

### ISSUE THREAD

**Issue by quajak** [CosmosOS/Cosmos#2140]
### Discussed in https://github.com/CosmosOS/Cosmos/discussions/2135

<div type='discussions-op-text'>

<sup>Originally posted by **MinecraftW06** February 26, 2022</sup>
Sys.FileSystem.VFS.VFSManager.Format("0", "FAT32", true) worked on earlier versions of cosmos but it's not working in the latest dev kit.</div>

**Comment by MishaTY** [comment]
I removed the method, replaced in managed partition class. It is found in getdisks() in the vfs

**Comment by tails2012timnew** [comment]
that is not working.
