### ISSUE TITLE
Using try/catch in while loop causes build failure

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2141]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling

#### Expected Behaviour - What do you think that should happen?
Cosmos should compile normaly

#### Actual Behaviour - What unexpectedly happens?
Cosmos gives and error and stops building (screenshot below)

#### Reproduction - How did you get this error to appear?
use the following code below:
```cs
while (true)
            {
                try
                {
                    Canvas.Clear(Color.Green);
                    Paint.Clock2(Canvas);
                    Canvas.DrawString(15, 50, "Last error: " + LastError, Color.Red);
                    Canvas.DrawBitmap((int)Mouse.X, (int)Mouse.Y, Files.Resources.Cursor);
                    Canvas.Update();
                }
                catch (Exception EX)
                {
                    LastError = EX.Message;
                }
            }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest devkit

#### Screenshots
![image](https://user-images.githubusercontent.com/76945439/155907832-305ade34-3345-47d3-a9a7-8360092f098c.png)

**Comment by MishaTY** [comment]
Can you show the entire build log?

**Comment by quajak** [comment]
Does the issue remain if you remove the canvas methods?

**Comment by MishaTY** [comment]
Closing as not enough information
