### ISSUE TITLE
Help! NETSDK1083

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2145]
**Exception**
указанный RuntimeIdentifier "cosmos" не распознан (The specified RuntimeIdentifier "cosmos" is not recognized)

** VS Output Logs **
NETSDK1083 указанный RuntimeIdentifier "cosmos" не распознан. kotos	C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	89	

I install better version of cosmos and i get this trouble.

**Screenshots**
![image](https://user-images.githubusercontent.com/79642857/156212046-7971372f-15d6-4a00-8e5a-90bdd3df36a5.png)

**Comment by quajak** [comment]
Remove the RuntimeIdentifier line from the csproj.

**Comment by koteProgrammist** [comment]
> Remove the RuntimeIdentifier line from the csproj.

thanks!
and can help me again please?
![image](https://user-images.githubusercontent.com/79642857/156225891-5d1cfc0e-3055-4076-810e-20f9593149aa.png)
I get this stupid error! Help please!

**Comment by quajak** [comment]
Problem with the devkit installation, reinstall the devkit.

**Comment by koteProgrammist** [comment]
ok, thanks
