### ISSUE TITLE
Uninstalling Cosmos

### ISSUE THREAD

**Issue by finaloblivious** [CosmosOS/Cosmos#215]
I know that the uninstaller crashing on newer OSes is a known issue, but I need to completely remove it from my computer. Is there some sort of manual method to uninstalling it?

"Runtime Error (at 47:380):
An error occurred while unregistering from Cosmos from VIsual Studio!"

PS. I have a Windows 10 computer

**Comment by mterwoord** [comment]
The bug in the uninstaller is a longstanding known bug. We really welcome work on this..

**Comment by rayw1** [comment]
If anyone is working with release `20150918`, a quick way to fix this uninstall runtime error is to edit **./setup/events.inc** and replace the procedure **CurUninstallStepChanged** with this:
```
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
    xResultCode: Integer;
begin
    EnableFsRedirection(true);
    ShellExec('runas', ExpandConstant('{code:VSNET2013_PATH|}\devenv.exe'), '/setup', '', SW_HIDE, ewWaitUntilTerminated, xResultCode);
    EnableFsRedirection(false);
end;
```
