### ISSUE TITLE
Visual studio 2022 msbuild error

### ISSUE THREAD

**Issue by DoorsDev** [CosmosOS/Cosmos#2152]
Have you checked Github Issues for similar errors? Yes, and it exists. But no answer...

**Exception**
Post the exception returned by Visual Studio D:\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4631,5): e
rror MSB3030: Could not copy the file "obj\Debug\Cosmos.Build.Builder.exe" because it was not found. [D:\CosmOS\CosmOS\
source\Cosmos.Build.Builder\Cosmos.Build.Builder.csproj]

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Change version list in the batch file to 17.0, 18.0

**Screenshots**
![image](https://user-images.githubusercontent.com/79535084/156882272-a527ef99-51a7-4853-b787-f491202ec2f9.png)

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful:
Visual studio 2022 18.0 x64 bits
I'm portuguese so you will need to translate the image text to english... Sorry!

**Comment by MishaTY** [comment]
Can you translate the error in cmd?

**Comment by DoorsDev** [comment]
Ok, i will resume it to you:
System.IO.FileNotFoundExepcion could not load the file Microsoft.Build.Framework Version 15.1.0.0 or one dependence.
The system could not found the specified file.

**Comment by DoorsDev** [comment]
I don't know what that error means...

**Comment by DoorsDev** [comment]
@MishaTY?

**Comment by BioShot** [comment]
hm same error with me, im using vs2017 though.

**Comment by Kiirx** [comment]
try adding this to thy environment path (replace the version with yours)

![image](https://user-images.githubusercontent.com/43090601/156931783-9e854c0c-ac19-460e-98d8-f401817ad677.png)
