### ISSUE TITLE
Visual Studio does not have the "Cosmos" option for running the project

### ISSUE THREAD

**Issue by Miki200v2** [CosmosOS/Cosmos#2158]
Have you checked Github Issues for similar errors?

**Exception**
There is none, it does not even have the "Cosmos" option for running it

**VS Output Logs**
There is none, as it does not even run it
**To Reproduce**
It does not matter if it is a clean kernel or a heavily modified one, as visual studio does not want

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[Yes] Both Cosmos VS Extensions are installed
[Yes] In the NuGet Package Manager "Include prerelease" is selected
[Yes] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[Yes] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
I am a guest in a Live Share project

**Comment by MishaTY** [comment]
Cosmos currently does not have support for liveshare.

**Comment by winbamstudios** [comment]
just copy paste the code into a new Cosmos Kernel project
worked for me

**Comment by EnterTheVoid-x86** [comment]
> just copy paste the code into a new Cosmos Kernel project worked for me

thats not even related to what the user's issue is.

**Comment by winbamstudios** [comment]
that fixes it

**Comment by MishaTY** [comment]
Liveshare does not support running projects locally when you are a guest
