### ISSUE TITLE
VBE broken

### ISSUE THREAD

**Issue by Cyber4** [CosmosOS/Cosmos#216]
VBE is broken.  In VMware it crashes immediately, and in Bochs it resizes the window but freezes on a black screen.

**Comment by MyvarHD** [comment]
VBE does not support, it works 100% in virtual box, and there is a simple bug that stops botch from working i will fix it this weekend just use virtual box for now.

**Comment by Cyber4** [comment]
Virtualbox doesn't work for me at all.  I can't figure out how to export it to virtualbox.  When I do the ISO it doesn't do anything, it will clear the screen to the color I choose but it won't set any pixels or anything else, it also won't invoke the while() function either.

**Comment by ARMmaster17** [comment]
@Cyber4 +1, I had the same pixel write issue with the last devkit. Have not tested current devkit. Running on latest Vbox(as of ~May/June).

**Comment by Cyber4** [comment]
@ARMmaster17 I actually found a fix.

Create a new Other->Other VM.

Select create a virtual hard disk.

Then go to the settings and change the location of the disk drive (not hard drive) from Empty to yourosBoot.iso

**Comment by Cyber4** [comment]
That at least works on the latest devkit

**Comment by MyvarHD** [comment]
Ok please Send me a zip with your os source code in and i can take a look. (i think you can attach it in chat.)

**Comment by ARMmaster17** [comment]
@Cyber4 What were you doing before? That's the same config I had when I initially ran into issues (old devkit).

**Comment by Cyber4** [comment]
Before I didn't have a virtual hard disk

**Comment by mterwoord** [comment]
Any progress on this?

**Comment by Cyber4** [comment]
@mterwoord it still works on Virtualbox but that is a problem because I have not found a way to use any filesystem stuff in virtualbox.  I added Filesystem.vmdk to virtualbox and it still throws errors when in use, and rewrites the entire contents of the disk with one file named whatever you tried to write to a file.  VBE still throws errors on vmware and will not work, so yet it is still a valid issue.

**Comment by mterwoord** [comment]
Are you sure virtualbox supports vmware harddisk images?

**Comment by CSharpLover** [comment]
I think it should, because it has an option to add a harddisk image with vmware harddisk image's file extension

**Comment by mterwoord** [comment]
what kind of harddisk controller you have?

**Comment by MyvarHD** [comment]
I fixed vbe in Bochs pr: #301

**Comment by charlesbetros** [comment]
@Cyber4 can you see if the fix resolves your issue? If so can you close it please?

**Comment by fanoI** [comment]
Is this issue yet valid? Or could it be closed?
