### ISSUE TITLE
FEATURE SUGGESTION: Window Manager Builder

### ISSUE THREAD

**Issue by WillKenzie** [CosmosOS/Cosmos#2162]
#### Area of Cosmos - What area of Cosmos are we dealing with?
User Zone / Graphics Module

#### Expected Behaviour - What do you think that should happen?
You should be able to draw a window - which behind the screens creates a box that can be dragged using a defined mouse. This would make building a functional system much easier, even if it is barebones. Also, you should be able to run executable files stored in the filesystem in Cosmos, to compliment this feature.

#### Actual Behaviour - What unexpectedly happens?
You can only draw boxes

**Comment by MishaTY** [comment]
You have to make that yourself

**Comment by MishaTY** [comment]
If cosmos implements this then it won't be very customizable.

**Comment by WillKenzie** [comment]
Okay, how about something in documentation discussing this type of thing?

**Comment by quajak** [comment]
Feel free to open a discussion post to get some ideas on how to do this.
