### ISSUE TITLE
Memory initialization fails after holding any key during memory initialization.

### ISSUE THREAD

**Issue by Incoherent-Code** [CosmosOS/Cosmos#2165]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting the Kernel

#### Expected Behaviour - What do you think that should happen?
The memory should initialize normally and load the Kernel

#### Actual Behaviour - What unexpectedly happens?
The system shuts down with VMWare saying that the Virtual CPU entered the shutdown state.

#### Reproduction - How did you get this error to appear?
1.Start VM or power on Real Hardware
2.Begin to hold down any key.
3.Hold and the OS will crash

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Devkit (Cosmos, IL2CPU, Xsharp, and Common all were obtained in their respective vs2022 branch.)

I only tested it on VMWare but I have tested it on both the current build of my OS and a fresh project with the code unmotified.

**Comment by zarlo** [comment]
mmm do we know if this is us or the boot loader

**Comment by valentinbreiz** [comment]
This is Cosmos and we should disable interrupts while initializing memory

**Comment by KM198912** [comment]
> This is Cosmos and we should disable interrupts while initializing memory

This works for the moment, once we get into paging this will not be a solution since we will require interrupts for ISR 14 i am afraid.

**Comment by AnErrupTion** [comment]
I wasn't able to reproduce this, was it fixed? @Incoherent-Code @valentinbreiz

**Comment by quajak** [comment]
Check if we added the code to disable interrupts while doing the intialisation, if yes it was fixed

**Comment by quajak** [comment]
We do disable interrupts so this is no longer an issue
