### ISSUE TITLE
VS2022 User Kit Build (Maby wrong category?!) 

### ISSUE THREAD

**Issue by Space-Vest-Studio** [CosmosOS/Cosmos#2168]
**Describe the problem**
I wanna see vs2022 user kit BUILD

**Steps of installation up to now**
1) Go to Releases

**Expected behavior**
vs2022 user kit build

**Logs**
-

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) UserKit
 - Are you using an admin account? No
 - VS Version if applicable. vs2022

**Additional context**
-

**Comment by Space-Vest-Studio** [comment]
Please I really need it.

**Comment by ilobilo** [comment]
Just build the devkit

**Comment by Space-Vest-Studio** [comment]
Oh really, just prebuild. Ok, thanks!

**Comment by Space-Vest-Studio** [comment]
And is vs2019 version and vs2022 version are compatible?

**Comment by KM198912** [comment]
No, but it is really not that hard to install, you will need to install git and innosetup, then you make a directory like C:\Cosmos , open a cmd and cd into C:\Cosmos, then clone Cosmos,Common and XSharp into that directory, in C:\Cosmos\Cosmos you will now find "install-vs2022.bat" run that, if you are missing any packages in visual studio the builder will tell you so. if you keep having issues feel free to join our Discord Server https://discord.com/invite/kwtBwv6jhD

**Comment by Space-Vest-Studio** [comment]
Thanks!
