### ISSUE TITLE
Opcode Issue with Unsigned and Signed int and long arrays.

### ISSUE THREAD

**Issue by Cyber4** [CosmosOS/Cosmos#217]
Here's an example:

Error: Exception: System.Exception: Error compiling method 'AnyMethodThatUsesArraysOfIntsOrLongs': System.Exception: OpCode IL_0010: Stelem_I4 tries to pop item at stack position 0 with type System.Int32, but actual type is System.UInt32

I have tried with both types, signed and unsigned, for both int and long.  they both do this.

**Comment by mterwoord** [comment]
Can you make a repro case?

**Comment by Cyber4** [comment]
?

**Comment by mterwoord** [comment]
You have code that triggers this issue. If you can narrow down the code to a small snippet, please post the code, so we can reproduce it..

**Comment by Cyber4** [comment]
When I try and use an array of a type to double buffer a gui, I add to a setpixel method that is accessible from the kernel ring (ring 4).  If you call one of those buffers from outside of the ring it freaks out.  Not sure, it might even freak out inside that one class library.

**Comment by mterwoord** [comment]
I'm pretty sure it doesn't have anything to do with the rings system.

Can you make a repro project? (As small as possible)

**Comment by charlesbetros** [comment]
Any update on this @Cyber4 ?

**Comment by charlesbetros** [comment]
Fixed
417df82cf7ee4ed841f82ee4704cbd8d72fe84f7
