### ISSUE TITLE
yasm.exe compile error

### ISSUE THREAD

**Issue by Werokowy** [CosmosOS/Cosmos#2172]
Have you checked Github Issues for similar errors?

**Exception**
Command "yasm.exe" exited with code -10737411515

** VS Output Logs **
Rozpoczęto kompilację...
1>------ Kompilacja rozpoczęta: Projekt: workplease, Konfiguracja: Debug Any CPU ------
1>workplease -> C:\Users\VM\source\repos\workplease\workplease\bin\Debug\net5.0\workplease.dll
1>-g dwarf2 -f elf -o bin\Debug\net5.0\workplease.obj -dELF_COMPILATION -O0 bin\Debug\net5.0\workplease.asm
1>C:\Users\VM\.nuget\packages\cosmos.build\0.1.0-localbuild20220209054635\build\Cosmos.Build.targets(214,9): error MSB6006: Polecenie „yasm.exe” zakończone przez kod -1073741515.
1>Yasm task took 00:00:00.0342469
1>Kompilowanie projektu „workplease.csproj” wykonane — NIEPOWODZENIE.
========== Kompilacja: 0 zakończono powodzeniem, 1 zakończono niepowodzeniem, 0 zaktualizowano, 0 pominięto ==========

**To Reproduce**
I have not changed anything, this is a clean installed Cosmos User Kit, meeting ALL requirements

**Screenshots**
![image](https://user-images.githubusercontent.com/66722567/159997797-b5b56be9-e9db-448a-8588-48cb2f782807.png)

Sorry for having a Polish visual studio (I'm from Poland) but I think you'll understand aI mean

**Comment by pto-buon** [comment]
Hello, please see #2102

**Comment by Werokowy** [comment]
> Hello, please see #2102

thanks, it works
