### ISSUE TITLE
The problem of starting the OS on a real computer

### ISSUE THREAD

**Issue by strike11** [CosmosOS/Cosmos#2173]
Hello. After I made a bootable usb flash drive and booted from the bios, I get an error related to PS / 2. Does anyone know how to solve it? Here is a photo
![photo_2022-03-27_10-08-29](https://user-images.githubusercontent.com/54178564/160267632-b7e872e2-a968-48bd-a87f-d6e0ab7358bf.jpg)
On Virtual Box my os works normal.

**Comment by zarlo** [comment]
that happens when it cant find any ps/2 devices

**Comment by strike11** [comment]
> that happens when it cant find any ps/2 devices

I connected a ps/2 keyboard, but the error remained the same

**Comment by MishaTY** [comment]
I will remove the console.readline later today to bypass this issue
