### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by HONAK0** [CosmosOS/Cosmos#2175]
how to delete.

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by NikonDs** [comment]
нужно не много пасасать, и заебись будет!

**Comment by AnnoyingB** [comment]
What error? What have you tried? What did you download? Please clarify more on "Installation error how to delete"
