### ISSUE TITLE
Create userkit for VS2022

### ISSUE THREAD

**Issue by SreeramSathya2014** [CosmosOS/Cosmos#2177]
Hello, Could you create User Kit for Visual Studio 2022? If not, then I couldn't make an operating system anymore.
<br/>
![image](https://user-images.githubusercontent.com/100463998/161384353-99bed9e6-8e38-4c02-b0ba-bebeab74f89e.png)

**Comment by MishaTY** [comment]
Use vs2022 branch in cosmos repo

**Comment by SreeramSathya2014** [comment]
No, not to build!

**Comment by SreeramSathya2014** [comment]
I DID NOT MEAN THE DEV KIT!!!!!!!!!

**Comment by SreeramSathya2014** [comment]
I DID NOT MEAN DEV KIT FOR VS2022!!!!!!!!!

**Comment by MishaTY** [comment]
You need to use the devkit.

**Comment by SreeramSathya2014** [comment]
NO!

**Comment by SreeramSathya2014** [comment]
I have full disk space on E:\.

**Comment by SreeramSathya2014** [comment]
@MishaTY Subsequently I don't have to do that!!!

**Comment by SreeramSathya2014** [comment]
OPEN IT BACK!!!!!!!!!!!

**Comment by SreeramSathya2014** [comment]
THX!

**Comment by MishaTY** [comment]
Cosmos is not larger than 1GB, and there is no vs2022 userkit yet because it is not very stable.

**Comment by SreeramSathya2014** [comment]
NO, VS2022 IS STABLE!!!!!!!!!

**Comment by SreeramSathya2014** [comment]
DEV KIT = BAD!!!!!!!!!!!!

**Comment by zarlo** [comment]
a user kit is just a prebuild devkit you know that right?

**Comment by SreeramSathya2014** [comment]
NO!!

**Comment by zarlo** [comment]
yes it is

**Comment by donut2008** [comment]
@SreeramSathya2014 if you want to use cosmos in visual studio 2022, use the dev kit
use it or don't use it
or just install visual studio 2019, how hard is it lmao

**Comment by lofcz** [comment]
r/githubdrama

**Comment by PrelevatedInsider22581** [comment]
No, I have an C:\ drive!

**Comment by PrelevatedInsider22581** [comment]
Whatever, I WILL create an Dev Kit.
I am running Visual Studio 2022 Preview.

**Comment by PrelevatedInsider22581** [comment]
Dev Kit == Advanced

**Comment by quajak** [comment]
There is a new userkit out now

**Comment by PrelevatedInsider22581** [comment]
Oh! It is VS2022 (20221121)!

**Comment by AsertCreator** [comment]
ʷᵗʰ ʲᵘˢᵗ ʰᵃᵖᵖᵉⁿᵉᵈ
