### ISSUE TITLE
Compiler uses .net 3.5 specific stuff for debug symbols

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#218]
This means, on a clean win 8 machine with vs 2015 installed, the compiler crashes.

There's some nuget package around for accessing debug symbols with a managed reader. This task is replacing the current COM-based stuff to the managed reader.

**Comment by lukaandjelkovic** [comment]
What COM does mean? It is a command line?
And managed reader is GUI?
Sorry, i dont speak english.

**Comment by mterwoord** [comment]
COM is Windows COM, see https://en.wikipedia.org/wiki/Component_Object_Model

the nuget package gives us a library (.net) which we can use to read pdb file info as well.

**Comment by lukaandjelkovic** [comment]
OK.
Just say me what to do.

**Comment by lukaandjelkovic** [comment]
Where is the folder with these things?
The respitory is extremly huge.

**Comment by lukaandjelkovic** [comment]
Where is the location of that Windows COM?

**Comment by lukaandjelkovic** [comment]
Are you active?

**Comment by czhower** [comment]
Matthijs is offline for a few days but he will answer you when he returns.

**Comment by lukaandjelkovic** [comment]
I think on mterwoord
Maybe he thinks that i am stupid; but i even arent adult.

**Comment by lukaandjelkovic** [comment]
Then can anyone say me where are location of Windows COM?
Or folder that have this issue?
I am waiting two days for response.

**Comment by yates199** [comment]
.NET should already inherit Windows

You could try import Microsoft. Windows...idk


Shouldn't be a  COM reference unless you mean something else


I.e. communication devices

Tim Yates





On Thu, Oct 29, 2015 at 2:11 PM -0700, "Luka Andjelkovic" <notifications@github.com> wrote:
Then can anyone say me where are location of Windows COM?
Or folder that have this issue?
I am waiting two days for response.

---

**Comment by lukaandjelkovic** [comment]
1>------ Build started: Project: ThontOSBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
1>	Working directory = 'C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Plug found: 'System.RuntimeType'
1>	Plug found: 'System.OutOfMemoryException'
1>	Plug found: 'System.Double'
1>	Plug found: 'System.Delegate'
1>	Plug found: 'System.Array'
1>	Plug found: 'System.Buffer'
1>	Plug found: 'System.Enum'
1>	Plug found: 'System.EventHandler'
1>	Plug found: 'System.Exception'
1>	Plug found: 'System.MulticastDelegate'
1>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>	Plug found: 'System.Math'
1>	Plug found: 'System.String'
1>	Plug found: 'System.Diagnostics.Debugger'
1>	Plug found: 'System.Byte'
1>	Plug found: 'System.Environment'
1>	Plug found: 'System.GC'
1>	Plug found: 'System.Int16'
1>	Plug found: 'System.Int32'
1>	Plug found: 'System.Int64'
1>	Plug found: 'System.IntPtr'
1>	Plug found: 'System.Number'
1>	Plug found: 'System.Object'
1>	Plug found: 'System.Single'
1>	Plug found: 'System.SR'
1>	Plug found: 'System.UInt16'
1>	Plug found: 'System.UInt32'
1>	Plug found: 'System.UInt64'
1>	Plug found: 'System.Threading.Interlocked'
1>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>	Plug found: 'System.Resources.ResourceManager'
1>	Plug found: 'System.Net.IPAddress'
1>	Plug found: 'System.Net.SocketAddress'
1>	Plug found: 'System.Globalization.NumberFormatInfo'
1>	Plug found: 'System.Drawing.Color'
1>	Plug found: 'System.Drawing.SR'
1>	Plug found: 'System.Security.CodeAccessSecurityEngine'
1>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>	Plug found: 'System.RuntimeTypeHandle'
1>	Plug found: 'System.SByte'
1>	Plug found: 'System.UIntPtr'
1>	Plug found: 'System.Security.Cryptography.Utils'
1>	Plug found: 'System.Globalization.CultureInfo'
1>	Plug found: 'Microsoft.Win32.RegistryKey'
1>	Plug found: 'Cosmos.Core.CPU'
1>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>	Plug found: 'Cosmos.Core.IOPortBase'
1>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>	Plug found: 'System.Char'
1>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>	Plug found: 'System.Random'
1>	Plug found: 'System.Console'
1>	Plug found: 'System.Type'
1>	Plug found: 'System.Threading.Monitor'
1>	Plug found: 'System.Text.DecoderFallback'
1>	Plug found: 'System.Text.EncoderFallback'
1>	Plug found: 'System.Text.ASCIIEncoding'
1>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Common.MethodIlOp'
1>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Common.Document'
1>	Detecting fields for type 'Cosmos.Debug.Common.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel2KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\corapi.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:05.1748232
1>Done building project "ThontOSBoot.Cosmos" -- FAILED.
1>
1>Build FAILED.
Build has been canceled.
Finally when i installed NET 3.5 after couple of weeks:
Cosmos.Debug.Common.Method
AND
SystemVoidCosmosKernel2KernelRun

**Comment by yates199** [comment]
Ok, you may have a compatibility issue between 3.5 and 4.0, I've seen this when working with templates, check the source code or Rsnx file, try system.globalization


One thing you could try checking class references to see if there is an error, that would tell you what you need to import, sometime it will say import is redundant, meaning you need it at all...


Sorry I'm an amateur at best


Tim Yates





On Thu, Oct 29, 2015 at 2:32 PM -0700, "Luka Andjelkovic" <notifications@github.com> wrote:
1>------ Build started: Project: ThontOSBoot, Configuration: Debug x86 ------
1>      Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll"
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>      Executing command line "C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll"
1>      Working directory = 'C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\'
1>      Loaded : DebugEnabled
1>      Loaded : StackCorruptionDetectionEnabled
1>      Loaded : DebugMode
1>      Loaded : TraceAssemblies
1>      Loaded : DebugCom
1>      Loaded : UseNAsm
1>      Loaded : OutputFilename
1>      Loaded : EnableLogging
1>      Loaded : EmitDebugSymbols
1>      Loaded : IgnoreDebugStubAttribute
1>      Loaded : References
1>      Executing IL2CPU on assembly
1>      Plug found: 'System.RuntimeType'
1>      Plug found: 'System.OutOfMemoryException'
1>      Plug found: 'System.Double'
1>      Plug found: 'System.Delegate'
1>      Plug found: 'System.Array'
1>      Plug found: 'System.Buffer'
1>      Plug found: 'System.Enum'
1>      Plug found: 'System.EventHandler'
1>      Plug found: 'System.Exception'
1>      Plug found: 'System.MulticastDelegate'
1>      Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>      Plug found: 'System.Math'
1>      Plug found: 'System.String'
1>      Plug found: 'System.Diagnostics.Debugger'
1>      Plug found: 'System.Byte'
1>      Plug found: 'System.Environment'
1>      Plug found: 'System.GC'
1>      Plug found: 'System.Int16'
1>      Plug found: 'System.Int32'
1>      Plug found: 'System.Int64'
1>      Plug found: 'System.IntPtr'
1>      Plug found: 'System.Number'
1>      Plug found: 'System.Object'
1>      Plug found: 'System.Single'
1>      Plug found: 'System.SR'
1>      Plug found: 'System.UInt16'
1>      Plug found: 'System.UInt32'
1>      Plug found: 'System.UInt64'
1>      Plug found: 'System.Threading.Interlocked'
1>      Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>      Plug found: 'System.Resources.ResourceManager'
1>      Plug found: 'System.Net.IPAddress'
1>      Plug found: 'System.Net.SocketAddress'
1>      Plug found: 'System.Globalization.NumberFormatInfo'
1>      Plug found: 'System.Drawing.Color'
1>      Plug found: 'System.Drawing.SR'
1>      Plug found: 'System.Security.CodeAccessSecurityEngine'
1>      Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>      Plug found: 'System.RuntimeTypeHandle'
1>      Plug found: 'System.SByte'
1>      Plug found: 'System.UIntPtr'
1>      Plug found: 'System.Security.Cryptography.Utils'
1>      Plug found: 'System.Globalization.CultureInfo'
1>      Plug found: 'Microsoft.Win32.RegistryKey'
1>      Plug found: 'Cosmos.Core.CPU'
1>      Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>      Plug found: 'Cosmos.Core.IOPortBase'
1>      Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>      Plug found: 'System.Char'
1>      Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>      Plug found: 'System.Random'
1>      Plug found: 'System.Console'
1>      Plug found: 'System.Type'
1>      Plug found: 'System.Threading.Monitor'
1>      Plug found: 'System.Text.DecoderFallback'
1>      Plug found: 'System.Text.EncoderFallback'
1>      Plug found: 'System.Text.ASCIIEncoding'
1>      Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>      Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>      Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>      Detecting fields for type 'Cosmos.Debug.Common.MethodIlOp'
1>      Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>      Detecting fields for type 'Cosmos.Debug.Common.Document'
1>      Detecting fields for type 'Cosmos.Debug.Common.Method'
1>      Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel2KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>         at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>         at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>         at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>         at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>         at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>         at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>         at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>         at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512
1>         --- End of inner exception stack trace ---
1>         at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
1>         at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
1>         at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>         at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>      Loaded assemblies:
1>      C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>      C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>      C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\corapi.dll
1>      C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
1>      Errorred
1>      IL2CPU invoked with DebugMode='Source', DebugEnabled='False', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>      IL2CPU task took 00:00:05.1748232
1>Done building project "ThontOSBoot.Cosmos" -- FAILED.
1>
1>Build FAILED.
Build has been canceled.
Finally when i installed NET 3.5 after couple of weeks:
Cosmos.Debug.Common.Method
AND
SystemVoidCosmosKernel2KernelRun

---

**Comment by lukaandjelkovic** [comment]
Now when i tried to compile more times and restart VS two times it worked. My problem solved.

**Comment by yates199** [comment]
Cool


Tim Yates





On Thu, Oct 29, 2015 at 2:45 PM -0700, "Luka Andjelkovic" <notifications@github.com> wrote:
Now when i tried to compile more times and restart VS two times it worked. My problem solved.

---

**Comment by OriginalSandman** [comment]
Hi, I have the same issue as Luka but i cannot find a fix. I have all the .net packages installed and i have tried re-installing COSMOS from scratch to no avail. can anyone point me in the right direction as to what the fix could be, thanks.

**Comment by mterwoord** [comment]
What issue are you getting?
the debug symbols one (which is what this issue is about), or the stack interpreter one?

**Comment by OriginalSandman** [comment]
the stack interpreter one. (sorry if i've posted in the wrong section)

**Comment by mterwoord** [comment]
Please make a new issue for that issue. THanks.
