### ISSUE TITLE
Notebook keyboard bot working

### ISSUE THREAD

**Issue by josealissonbr** [CosmosOS/Cosmos#2187]
Not working on Notebook internal keyboard, but working with USB Keyboard.

**Comment by BlitzWolfMatthew** [comment]
Can you give us a few more details? Cosmos doesn't support USB keyboard unless emulated.

**Comment by pto-buon** [comment]
See #1511

**Comment by josealissonbr** [comment]
Let me explain, I can't use the notebook's keyboard, but if I plug another keyboard into the notebook's USB port, it works perfectly.

**Comment by terminal-cs** [comment]
It is likely your laptop is using internal USB for the main keyboard but external usb ports are emulating ps/2 input internaly
