### ISSUE TITLE
Cosmos not installing on vs2019

### ISSUE THREAD

**Issue by pto-buon** [CosmosOS/Cosmos#2188]
**Describe the problem**
I tried to install dev kit and user kit on vs2019, but not work

**Steps of installation up to now**
**Dev kit**
- Download latest branch
- open install-vs2019.bat

**User kit**
- Download latest release 
- run .exe

**Expected behavior**
Clean install of dev kit or user kit

**Logs**
https://www.toptal.com/developers/hastebin/rososizitu 
Cool the new hastebin feature

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) Devkit latest branch userkit latest release
 - Are you using an admin account? Yes
 - VS Version if applicable 16.11.12 vs2019

**Additional context**
After installing (user kit):
![image](https://user-images.githubusercontent.com/98218366/163037502-23da7f99-d75f-4c0c-a2c5-05a0460e118e.png)
Sorry i'm italian

**Comment by quajak** [comment]
There is some error happening when running the installer. Could you please translate the error to english?

**Comment by pto-buon** [comment]
OK:
The format of path specified is not supported [C:\source\Cosmos-vs2019\Cosmos\Build.sln]
All errors are this

**Comment by pto-buon** [comment]
My source tree
C:\source\
|____Cosmos-vs2019
       |____Cosmos
       |____Common
       |____IL2CPU
       |____XSharp

**Comment by LoxyMono** [comment]
Try naming a new folder on your desktop to just "Cosmos", no quotes. I don't know if it's just desktop, but it works perfectly for me

**Comment by pto-buon** [comment]
Same error
![image](https://user-images.githubusercontent.com/98218366/163041006-e98469b5-3d16-40b4-8dc6-59f21bd326d1.png)

**Comment by LoxyMono** [comment]
Just like that

**Comment by LoxyMono** [comment]
Are all of the files (as listed in the github repo) there?

**Comment by pto-buon** [comment]
I will try to redownload the last branch

**Comment by LoxyMono** [comment]
Let me know how it goes, just delete the contents of the cosmos folder and replace them with the contents of the devkit install

**Comment by pto-buon** [comment]
Solved, thanks
