### ISSUE TITLE
Change the setup and devkit builder to check for .NET 3.5

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#219]
See #218 for specifics. This is a temporary measure, #218 is the longer-term solution.

**Comment by lukaandjelkovic** [comment]
Do it need to just compile to non NET 3.5 version, or more code to do?
(I will be inactive within 14:00 and 18:00 in my time zone)

**Comment by mterwoord** [comment]
This issue for making the installer detect error situations. More details on this issue in #218
