### ISSUE TITLE
CPU Exception x06 when run String.IsNullOrEmpty()

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2190]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Strings

#### Actual Behaviour - What unexpectedly happens?
An CPU Exception happend when i run String.IsNullOrEmpty(myString)

#### Reproduction - How did you get this error to appear?
Type the code
`if (String.IsNullOrEmpty(args[1]))
 {
 }`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I'm using Cosmos User Kit 20200708 with Visual Studio 2019

**Comment by MishaTY** [comment]
args is null

**Comment by RaphMar2021** [comment]
> args is null

@MishaTY  Normally, its return true. not an exception!
The method documentation : [https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorempty?view=net-5.0](url)
