### ISSUE TITLE
Error when compiling resources.

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2191]
**Exception**
System.Exception : Resource 'SipaaOperatingSystem.Resources.Cursor.bmp' not found!

** VS Output Logs **
L'opération de génération a démarré...
1>------ Début de la génération : Projet : SipaaOperatingSystem, Configuration : Debug Any CPU ------
1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(22,30,22,41): warning CS0649: Le champ 'OSResources.SipaaOSLogo' n'est jamais assigné et aura toujours sa valeur par défaut null
1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(16,30,16,36): warning CS0649: Le champ 'OSResources.Cursor' n'est jamais assigné et aura toujours sa valeur par défaut null
1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(13,30,13,43): warning CS0649: Le champ 'OSResources.wallpaper1080' n'est jamais assigné et aura toujours sa valeur par défaut null
1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(19,30,19,34): warning CS0649: Le champ 'OSResources.Font' n'est jamais assigné et aura toujours sa valeur par défaut null
1>SipaaOperatingSystem -> C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\bin\Debug\net5.0\SipaaOperatingSystem.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\bin\Debug\net5.0\SipaaOperatingSystem.dll
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Resource 'SipaaOperatingSystem.Resources.Cursor.png' not found!
1>   at Cosmos.IL2CPU.AppAssembler.ProcessField(FieldInfo aField) in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 1117
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 1030
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 277
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 222
1>IL2CPU task took 00:00:03.3089986
1>Génération du projet "SipaaOperatingSystem.csproj" terminée -- ÉCHEC.

**To Reproduce**
Added resources to the project.
Added a class for register resources into the OS

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by MishaTY** [comment]
Self explanatory.

**Comment by Samma2009** [comment]
> **Exception** System.Exception : Resource 'SipaaOperatingSystem.Resources.Cursor.bmp' not found!
> 
> ** VS Output Logs ** L'opération de génération a démarré... 1>------ Début de la génération : Projet : SipaaOperatingSystem, Configuration : Debug Any CPU ------ 1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(22,30,22,41): warning CS0649: Le champ 'OSResources.SipaaOSLogo' n'est jamais assigné et aura toujours sa valeur par défaut null 1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(16,30,16,36): warning CS0649: Le champ 'OSResources.Cursor' n'est jamais assigné et aura toujours sa valeur par défaut null 1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(13,30,13,43): warning CS0649: Le champ 'OSResources.wallpaper1080' n'est jamais assigné et aura toujours sa valeur par défaut null 1>C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\OSResources.cs(19,30,19,34): warning CS0649: Le champ 'OSResources.Font' n'est jamais assigné et aura toujours sa valeur par défaut null 1>SipaaOperatingSystem -> C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\bin\Debug\net5.0\SipaaOperatingSystem.dll 1>Message: Executing IL2CPU on assembly 1>Message: Kernel Base: Cosmos.System.Kernel 1>Message: Checking target assembly: C:\Users\pc2\Documents\Sipaa-Operating-System\SipaaOperatingSystem\bin\Debug\net5.0\SipaaOperatingSystem.dll 1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO' 1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING' 1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp' 1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile' 1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document' 1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method' 1>IL2CPU : error : Exception: System.Exception: Resource 'SipaaOperatingSystem.Resources.Cursor.png' not found! 1> at Cosmos.IL2CPU.AppAssembler.ProcessField(FieldInfo aField) in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 1117 1> at Cosmos.IL2CPU.ILScanner.Assemble() in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 1030 1> at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 277 1> at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\valentinbreiz\Documents\Github\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 222 1>IL2CPU task took 00:00:03.3089986 1>Génération du projet "SipaaOperatingSystem.csproj" terminée -- ÉCHEC.
> 
> **To Reproduce** Added resources to the project. Added a class for register resources into the OS
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Context** Before posting please confirm that the following are in order [ ] Both Cosmos VS Extensions are installed [ ] In the NuGet Package Manager "Include prerelease" is selected [ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages' [ ] The Cosmos NuGet packages are installed
> 
> Add any other context about the problem which might be helpful.

can you help me
