### ISSUE TITLE
Trying to write a txt file to disk crashes the virtual machine

### ISSUE THREAD

**Issue by vuk5002** [CosmosOS/Cosmos#2192]
#### Area of Cosmos - What area of Cosmos are we dealing with?
System.IO
Cosmos.System.FileSystem

#### Expected Behaviour - What do you think that should happen?
A file called test1.txt should be created and contents to be Hello, World!.

#### Actual Behaviour - What unexpectedly happens?
After clicking enter to create the file VMware crashes

#### Reproduction -  How did you get this error to appear?
Code that I used
`File.WriteAllText(@"test1.txt", "Hello, World!");`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev Kit

**Comment by MishaTY** [comment]
Show entire code

**Comment by vuk5002** [comment]
`using System;
using System.IO;
using Sys = Cosmos.System;
using System.Drawing;


namespace OS
{
    public class OS : Sys.Kernel
    {

        protected override void BeforeRun()
        {

            Console.WriteLine("Sucess! Started with no errors.");
        }

        protected override void Run()
        {
            Kernel();
        }
        private void Kernel()
        {
            
            string input = Console.ReadLine();
            Console.Write(">>");
            if (input == "help")
            {
                Console.WriteLine("-HELP- \n help -- this \n write -- Writer");
            }
            if (input == "write")
            {
                Console.Clear();
                Console.WriteLine("1) test writing to disk");
                string inputW = Console.ReadLine();

                if (inputW == "1")
                {
                    File.WriteAllText(@"test1.txt", "Hello, World!");

                }


            }
        }
    }
}
`

**Comment by MishaTY** [comment]
You did not initialize the vfs, read the documentation
