### ISSUE TITLE
PS/2 Controller error

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2193]
Finding PCI Devices
Starting ACPI
(PS/2 Controller) Device detection failed
This is usually Fine for USB to PS / 2 Emulation
Press any key to resume (Good Luck)

i press any key but this not work
I test my OS on real PC
i don't have PS/2 Keyboard :(
But PS/2 Ports is working

please help!

**Comment by MishaTY** [comment]
Duplicate
