### ISSUE TITLE
Question : How to create a graphical console with Cosmos?

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2195]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Actual Behaviour - What unexpectedly happens?
How to create a graphical console with Cosmos?

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#Last )?
Last User Kit

**Comment by MishaTY** [comment]
See this: https://github.com/MishaTY/Misha-OS/blob/master/Misha-OS/Gui/Apps/Terminal.cs

**Comment by RaphMar2021** [comment]
Misha, I don't want make a GUI OS. i want make the graphical console like AuraOS

**Comment by MishaTY** [comment]
You can use the same thing

**Comment by RaphMar2021** [comment]
And , you can add a ScrollUp function to the Canvas class?
