### ISSUE TITLE
No filesystem on VM

### ISSUE THREAD

**Issue by vuk5002** [CosmosOS/Cosmos#2199]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem

#### Expected Behaviour - What do you think that should happen?
In VM drive letter should show up and I can create a file.

#### Actual Behaviour - What unexpectedly happens?
Drive letter doesn't show up, no filesystem, cannot read/write 

#### Reproduction - How did you get this error to appear?
I compiled a .iso file and to test it on Qemu with NEW .img disk and there is no filesystem. Also tried that on VirtualBox and nothing.
Filesystem WORKS when i use filesystem.vmdk

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev Kit

**Comment by MishaTY** [comment]
Qemu arguments?

**Comment by vuk5002** [comment]
creating the disk: qemu-img create disk.img 512M
loading: qemu-system-x86_64 -boot d -cdrom os.iso -m 512 -hda disk.img

**Comment by MishaTY** [comment]
You need to format it first.

**Comment by vuk5002** [comment]
@MishaTY Formatted as raw and nothing
qemu-system-x86_64 -drive format=raw,file=disk.img -cdrom os.iso

**Comment by vuk5002** [comment]
@MishaTY I formatted and it gives me
no supported network card found!!

with this: qemu-system-x86_64 -boot d -drive format=raw,file=disk.img -cdrom os.iso

**Comment by MishaTY** [comment]
I meant filesystem
