### ISSUE TITLE
ISO Error

### ISSUE THREAD

**Issue by AppLoginCreator** [CosmosOS/Cosmos#220]
Hello, I am having an issue booting from the iso. I have burned it to an optical disc, However when I boot from it it pauses on the line "Creating ATA IOGroup". Please reply soon
Thank you,

Email: applogincreator@gmail.com

Screenshot:
https://cloud.githubusercontent.com/assets/15154772/10537427/933b0f3a-73a6-11e5-99a7-32d844e202d6.jpg

**Comment by mterwoord** [comment]
Please don't post the same question twice, or hijack threads. (See #112 )

What version are you using?
