### ISSUE TITLE
CPU Exception when creating an instance of Canvas

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2200]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Actual Behaviour - What unexpectedly happens?
I'm coding an OS and i want create an instance of Canvas with FullScreenCanvas.GetFullScreenCanvas(Mode mode)
and when i start my OS, i get a CPU Exception

#### Reproduction - How did you get this error to appear?
Create a blank cosmos kernel, Add a Canvas variable, Add in the BeforeRun() method this code: `canvas = FullScreenCanvas.GetFullscreenCanvas(new Mode(1024, 768, ColorDepth.ColorDepth32));`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 2022

**Comment by AsertCreator** [comment]
how you fixed problem?
