### ISSUE TITLE
SWbemLocator: Class not Registered

### ISSUE THREAD

**Issue by BioShot** [CosmosOS/Cosmos#2203]
Tried Installing, didn't work.

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
 - Are you using an admin account?
 - VS Version if applicable

**Additional context**

**Comment by Samma2009** [comment]
the same thing

**Comment by Samma2009** [comment]
I've been trying to install it for 25 days now

**Comment by quajak** [comment]
Should be fixed by https://github.com/CosmosOS/Cosmos/pull/2184
