### ISSUE TITLE
Cosmos.Hardware error

### ISSUE THREAD

**Issue by vuk5002** [CosmosOS/Cosmos#2206]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.Hardware

#### Expected Behaviour - What do you think that should happen?
using Cosmos.Hardware.Drivers.PCI.video; without any issues

#### Actual Behaviour - What unexpectedly happens?
The type or namespace name 'Hardware' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?)

#### Reproduction - How did you get this error to appear?
added this code `using Cosmos.Hardware.Drivers.PCI.video;`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest Dev Kit

**Comment by MishaTY** [comment]
That namespace was removed 10 years ago. Replace hardware with HAL
