### ISSUE TITLE
i need help cosmos user kit 20220209

### ISSUE THREAD

**Issue by Samma2009** [CosmosOS/Cosmos#2207]
![ScreenShot_20220428185204](https://user-images.githubusercontent.com/81291107/165976173-f28629bb-04e4-4ff8-8e71-ac836305c0f2.jpeg)

please help me

**Comment by RaphMar2021** [comment]
Try to reinstall Cosmos nuget packages.

**Comment by quajak** [comment]
In the csproj comment out RuntimeIdentifier line.

**Comment by Samma2009** [comment]
> In the csproj comment out RuntimeIdentifier line.

it did not work

**Comment by quajak** [comment]
Same error message?

**Comment by Samma2009** [comment]
the same

**Comment by Samma2009** [comment]
![ScreenShot_20220502192005](https://user-images.githubusercontent.com/81291107/166293919-9d2e62c1-8672-4143-a4bb-93fff4f10cd2.jpeg)

the logs are in Italian because I am an Italian developer, this is the logi in English:

Severity Code Description Project File Line Deletion status
Error CS0234 The type or name of the 'System' namespace does not exist in the 'Cosmos' namespace. An assembly reference is probably missing. CosmosKernel14 C: \ Users \ samue \ source \ repos \ CosmosKernel14 \ Kernel.cs 4 Active

Severity Code Description Project File Line Deletion status
Error CS0115 'Kernel.BeforeRun ()': No suitable methods were found to override CosmosKernel14 C: \ Users \ samue \ source \ repos \ CosmosKernel14 \ Kernel.cs 10 Active

Severity Code Description Project File Line Deletion status
Error CS0115 'Kernel.Run ()': No suitable methods were found to override CosmosKernel14 C: \ Users \ samue \ source \ repos \ CosmosKernel14 \ Kernel.cs 15 Active

Severity Code Description Project File Line Deletion status
NETSDK Error1083 The specified RuntimeIdentifier 'cosmos' is not recognized. CosmosKernel14 C: \ Program Files \ dotnet \ sdk \ 6.0.201 \ Sdks \ Microsoft.NET.Sdk \ targets \ Microsoft.NET.Sdk.FrameworkReferenceResolution.targets 90

**Comment by quajak** [comment]
You havnt commented out/removed the RuntimeIdentifier line?

**Comment by Samma2009** [comment]
how i do this

**Comment by Samma2009** [comment]
please send me an tutorial

**Comment by Samma2009** [comment]
i resolved removing this line <RuntimeIdentifier>cosmos</RuntimeIdentifier>

**Comment by Samma2009** [comment]
<RuntimeIdentifier>cosmos</RuntimeIdentifier>
