### ISSUE TITLE
Unexpected exception during Attach when building an OS on VS 2022 branch [UNSOLVED]

### ISSUE THREAD

**Issue by realrandombeans** [CosmosOS/Cosmos#2208]
![image](https://user-images.githubusercontent.com/97028115/165983287-68b38568-143f-45c1-91dd-d52bbe777160.png)

Please help! It is happening on the VS 2022 branch. I have reinstalled the userkit and devkit twice, still hasn't worked.

**Comment by Samma2009** [comment]
you need to install a older version ov vmware

**Comment by realrandombeans** [comment]
Didn't work. I set the launch profile to ISO and this is what I get
![image](https://user-images.githubusercontent.com/97028115/165985282-cb41f825-a152-41ca-8196-d6304ffed7b3.png)
