### ISSUE TITLE
Help Error occurred while invoking IL2CPU

### ISSUE THREAD

**Issue by zarlo** [CosmosOS/Cosmos#221]
when i try to build i get this error
Severity	Code	Description	Project	File	Line
Error		Error occurred while invoking IL2CPU.	punkskyosBoot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31

Imports System
Imports System.Collections.Generic
Imports System.IO
Imports System.Net
Imports System.Net.Sockets
Imports System.Text
Imports System.Threading
Imports Microsoft.VisualBasic
Namespace punkskyos

    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.")
        End Sub

        Protected Overrides Sub Run()
            Do
                Try

                    Console.WriteLine(core.program(Console.ReadLine.ToString()))
                Catch ex As Exception

                End Try
            Loop
        End Sub

    End Class

    Public Class core

        Shared Function program(_input As String)
            Dim input() As String = Split(_input, " ")

            Dim i As Integer
            For i = 1 To input.GetUpperBound(0)

                Try
                    Dim CurArg() As Char = input(i).ToCharArray(0, input(i).Length)
                    If (CurArg(0) = "-") Or (CurArg(0) = "/") Then
                        Select Case Char.ToLower(CurArg(1), System.Globalization.CultureInfo.CurrentCulture)
                            Case "print" ' Local interface to bind to
                                i = i + 1
                                Return input(i)
                            Case Else
                                Return "error"

                        End Select
                    End If
                Catch e As Exception
                End Try
                Return "error"
            Next
        End Function

    End Class

End Namespace

**Comment by mterwoord** [comment]
Can you post the contents of the output window?

**Comment by zarlo** [comment]
1>------ Build started: Project: punkskyosBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:D:\DEV\Projects\OS\Punksky\punkskyos\bin\Debug\punkskyosBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:D:\DEV\Projects\OS\Punksky\punkskyos\bin\Debug\punkskyos.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:D:\DEV\Projects\OS\Punksky\punkskyos\bin\Debug\punkskyosBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\kaleb\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:D:\DEV\Projects\OS\Punksky\punkskyos\bin\Debug\punkskyos.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>	Working directory = 'D:\DEV\Projects\OS\Punksky\punkskyos\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Error: No Kernel found!
1>	Errorred
Build has been canceled.

**Comment by mterwoord** [comment]
Can you verify if all the references are in place?

**Comment by zarlo** [comment]
they are all in place

**Comment by mterwoord** [comment]
CAn you send a zip file containing your projects?

**Comment by zarlo** [comment]
https://dl.dropboxusercontent.com/u/153282115/Punksky.zip

**Comment by mterwoord** [comment]
I don't have much time to test now, but I must say, we all use C# to do development, so the VB.NET specific support is less tested...

**Comment by zarlo** [comment]
I Think this is making the error in File "Cosmos.targets"

    <IL2CPU  DebugMode="$(DebugMode)"
             DebugEnabled="$(DebugEnabled)"
             StackCorruptionDetectionEnabled="$(StackCorruptionDetectionEnabled)"
             TraceAssemblies="$(TraceAssemblies)"
             IgnoreDebugStubAttribute="$(IgnoreDebugStubAttribute)"
             DebugCom="1"
             UseNAsm="true"
             References="@(ReferencePath)"
             OutputFilename="$(TargetDir)$(MSBuildProjectName).asm"
             EnableLogging="true"
             EmitDebugSymbols="$(DebugSymbols)"
             CosmosBuildDir="$(CosmosDir)\Build"
             WorkingDir="$(TargetDir)"/>

**Comment by zarlo** [comment]
i get the same error when i use C#

**Comment by lukaandjelkovic** [comment]
Me too, on AMD cpu

**Comment by zarlo** [comment]
I think this is the same as https://github.com/CosmosOS/Cosmos/issues/187

**Comment by mterwoord** [comment]
Have you tried installing .NET 3.5 as mentioned in #187?

**Comment by zarlo** [comment]
Yes

**Comment by zarlo** [comment]
fixed it by restarting the project
