### ISSUE TITLE
FTP connection not working. Cant get local folder and aborts connection.

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2211]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Networking - FTPserver

#### Expected Behaviour - What do you think that should happen?
should work fine

#### Actual Behaviour - What unexpectedly happens?
```
Status: Connecting at 192.168.133.128:21...
Status: Connected, waiting for greeting...
Status: Server not secure, it does not support FTP over TLS.
Status: The server does not support non-ASCII characters.
Status: Connected
Status: Retrieving folder contents...
Command: PWD
Answer: 257 / created.
Command: TYPE I
Answer: 200 Command okay.
Command: PORT 192,168,133,1,224,9
Error: Disconnected from server: ECONNABORTED - Connection canceled
Error: Unable to retrieve folder contents
``` 
when connecting via filezila (its on active mode)
I use `192.168.133.128:21`

#### Reproduction - How did you get this error to appear?
Create DHCP connection on your os, Create FTP server, connect to the OS FTP server via its IP and tada

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
last DevKit

**Comment by valentinbreiz** [comment]
Hello this should be fixed using CosmosFtp

**Comment by Kiirx** [comment]
it cant even connect now, you can reopen this.

**Comment by valentinbreiz** [comment]
If you can connect to your OS over udp or something I will reopen
If not, as I said you multiple times it's not a FTP related or even an IPv4 problem. It's about your local network configuration

**Comment by Kiirx** [comment]
Well I never changed anything about the network configuraton and it was working before

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kiirx** [comment]
the network configuration was never changed, it was on NAT and its still NAT, doesnt work on AuraOS too
