### ISSUE TITLE
CPU Exception 0x06 when invoking a method that accepts a ref parameter and using Console.ReadLine

### ISSUE THREAD

**Issue by ascpixi** [CosmosOS/Cosmos#2212]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel

#### Expected Behaviour - What do you think that should happen?
No CPU exception should be thrown

#### Actual Behaviour - What unexpectedly happens?
A CPU Exception 0x06 is thrown (Invalid opcode)

#### Reproduction - How did you get this error to appear?
After invoking a method with a `ref` (passed-by-reference) parameter, and invoking `Console.ReadLine()`, a CPU exception may occur.
Download [CpuExceptionRepro.zip](https://github.com/CosmosOS/Cosmos/files/8599189/CpuExceptionRepro.zip), and run the project. Entering a dot character (`.`) seems to reproduce the bug consistently. The issue only occurs when using `Console.ReadLine()`.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev Kit (from commit 113e5fc6c6b8bf9d498dc0eb596586f2d300bcb5, installed using `install-vs2019.bat`)

**Comment by valentinbreiz** [comment]
Hello, thanks for your test kernel but I didn't succeed to reproduce the bug. Can you try again using .net6 and last changes of the devkit?
