### ISSUE TITLE
How to mount drives?

### ISSUE THREAD

**Issue by MEMESCOEP** [CosmosOS/Cosmos#2214]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem

#### Expected Behaviour - What do you think that should happen?
When using the MountPartition function, the specified partition should be mounted, and given a path

#### Actual Behaviour - What unexpectedly happens?
The partitions are mounted, but not given a proper path.

#### Reproduction - How did you get this error to appear?
use MountPartition to mount a specific drive

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit 20220209

**Comment by MishaTY** [comment]
That method is supposed to be used on new partitions. It is called during the boot process, and is not meant to be used directly unless you formated a partition.

**Comment by MEMESCOEP** [comment]
Ahh, thanks for letting me know
