### ISSUE TITLE
Cosmos: Kernel needs to be loaded first

### ISSUE THREAD

**Issue by Ardumine** [CosmosOS/Cosmos#2217]
Hi! Im currently using Cosmus and i bean a few days  ago. Today i started the aplication and i got this error:
My aplication name is 'ARDUMINE OS'
![image](https://user-images.githubusercontent.com/61353807/166471752-6ee6327b-c89c-44e1-ae7f-c2227c5b2610.png)

**Comment by MishaTY** [comment]
Remove the spaces from your project name
