### ISSUE TITLE
VS 2022 build not working: spills out a bunch of errors on installation

### ISSUE THREAD

**Issue by realrandombeans** [CosmosOS/Cosmos#2219]
https://www.toptal.com/developers/hastebin/oyiduqituw Log

I don't understand what's happening here. I'm using the VS 2022 branch with the latest userkit installed.

**Comment by realrandombeans** [comment]
UPDATE: I'm getting these errors now
![image](https://user-images.githubusercontent.com/97028115/166811181-bb3be4d3-e869-41df-835e-1df31ba10e47.png)

Log: https://www.toptal.com/developers/hastebin/ihituyunaw

**Comment by quajak** [comment]
You need to pull the newest version of xsharp
