### ISSUE TITLE
Unexpected exception during Attach on Hyper-V when building an OS on VS 2022 branch

### ISSUE THREAD

**Issue by Diamantino-Op** [CosmosOS/Cosmos#2222]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/59661806/167458980-515c3a96-139d-4ed1-b7f8-e8736c8aa40d.png">

I get this error when trying to attach a default system to Hyper-V

<img width="747" alt="image" src="https://user-images.githubusercontent.com/59661806/167459189-5361d97d-d815-4e18-bc8d-8d767c5706df.png">

**Comment by ptobuon** [comment]
Did you try with VMware?
If not follow these steps:
#2224
