### ISSUE TITLE
Cosmos Error while building

### ISSUE THREAD

**Issue by Ghalbeyou** [CosmosOS/Cosmos#2224]
# Erorr
hello, the error:
https://user-images.githubusercontent.com/97028115/165983287-68b38568-143f-45c1-91dd-d52bbe777160.png

please help me,I  tried everything.
like: install older version of VM 
use vs 2019
nothing worked.

**Comment by ptobuon** [comment]
I had the same error and you have 2 solutions: 
- Are you using vmware workstation or player? Set it in properties ==> vmware ==> workstation or player
- Try reinstalling Cosmos. If you want you can use VS2022 #2009

**Comment by ptobuon** [comment]
This is not a build error, this is a debug error. You can't start vmware. But the iso is already builded.

**Comment by Ghalbeyou** [comment]
I used the vs2022 And i did all of the thing you said to me, but non of them worked :(

**Comment by LoxyMono** [comment]
Re install IL2CPU, and you might as well re install cosmos as well. Then, transfer your code if needed

**Comment by KM198912** [comment]
This is solved by rebuilding the devkit, there is a issue between .net 4.8 and 5.0 where it references the wrong file at times, rebuild the devkit and it should work

**Comment by ROSASmith** [comment]
Kindly DM Cosmos Agent On support [LIVE CHAT]

**Comment by Ghalbeyou** [comment]
don't work

**Comment by valentinbreiz** [comment]
Hello @Ghalbeyou are you using last commits of Cosmos, IL2CPU, XSharp and Common? This should be fixed with last changes

**Comment by Ghalbeyou** [comment]
Yes.

**Comment by quajak** [comment]
Are you using vs19 or vs22?
