### ISSUE TITLE
QUESTION:  Run os without the iso?

### ISSUE THREAD

**Issue by vuk5002** [CosmosOS/Cosmos#2225]
Ok, so can I run the os without the iso inserted? Or do I need to copy files to the filesystem?
Example:
Copy the iso contents (or bin) to the filesystem and boot off that disk where everything is copied

and if its possible how do i do that?

**Comment by ptobuon** [comment]
No, currently cosmos can't be run without iso or disk/dvd/usb. You can start a discussion to suggest it: https://github.com/CosmosOS/Cosmos/discussions
Anyway, if cosmos is running in filesystem how do you create a text file? And if you want to format the disk it erase the operative system too. I think it will not be possible to implement it.
