### ISSUE TITLE
Canvas not cleans screen

### ISSUE THREAD

**Issue by ShakalnyKot** [CosmosOS/Cosmos#2226]
When i try to clean graphic mode screen via Canvas, cleaning just not happends
Code:
![2022-05-11_17-57-00](https://user-images.githubusercontent.com/103893968/167798753-4d0e2d3f-85ed-40fa-8d81-59b6faf13301.png)
Result in QEMU:
![2022-05-11_17-58-44](https://user-images.githubusercontent.com/103893968/167798947-33a86f73-398f-4246-8d02-0c4707ae46bb.png)

**Comment by ptobuon** [comment]
Did you try with vmware?

**Comment by Samma2009** [comment]
ptobuon it doesn't work with vmware as well

**Comment by LoxyMono** [comment]
you are trying to use console functions in your run loop, and canvas.Display() needs to be un-commented
in your run loop, put:
canvas.Clear(Color.Black);

canvas.Display();

**Comment by ShakalnyKot** [comment]
@LoxyMono your way doesn't work
Code:
![2022-05-12_09-39-07](https://user-images.githubusercontent.com/103893968/167964543-c229d347-58c7-4963-be5f-bb29b6f00739.png)
Result:
![2022-05-12_09-39-41](https://user-images.githubusercontent.com/103893968/167964575-89175d28-2339-4f67-ae3c-acc79ce40654.png)

**Comment by LoxyMono** [comment]
Try using VMWare, and defining the mode in the GetFullScreenCanvas

GetFullScreenCanvas(new Mode(800, 600, ColorDepth.ColorDepth32))

**Comment by ShakalnyKot** [comment]
On VMWare all works

**Comment by LoxyMono** [comment]
Great, all is fine now?

**Comment by ShakalnyKot** [comment]
Yes, but i doesn't know, why Canvas does not work on anything except VMWare

**Comment by LoxyMono** [comment]
I dont know much about QEMU, but vmware is very reliable

**Comment by zarlo** [comment]
can you give us the output of ```canvas.Name();``` so we know that back end is been used

**Comment by KM198912** [comment]
This is not a bug for Qemu, you have 2 options, you can set the Qemu graphics mode to BGA (Bochs) or you use the multiboot option and pass something like 1024x768x32 and use the VBECanvas directly.

**Comment by KM198912** [comment]
if you want to use fullscreen canvas, you can do something like this

`namespace NexusOS
{
    public class Kernel : Sys.Kernel
    {
        internal static Sys.Graphics.Canvas vbe;
        internal static Cosmos.Core.VBE.ModeInfo mode;
        protected override void BeforeRun()
        {
            mode = Cosmos.Core.VBE.getModeInfo();
            vbe = Sys.Graphics.FullScreenCanvas.GetFullScreenCanvas(new Sys.Graphics.Mode(mode.width, mode.height, (Sys.Graphics.ColorDepth)mode.bpp));
            
        }

        protected override void Run()
        {
            vbe.Clear(Color.Teal);
            vbe.Display();
        }
    }
}`

**Comment by valentinbreiz** [comment]
If you want to use VBE under qemu or real hardware you have to use this option in the Visual Studio property page:
![image](https://user-images.githubusercontent.com/18724279/174486367-fcb54b7c-e789-4575-a23c-941b8e6c6c09.png)
