### ISSUE TITLE
Bug! the canvas doesen't work

### ISSUE THREAD

**Issue by Samma2009** [CosmosOS/Cosmos#2227]
also with the right code the canvas of cosmos 20220209 does not work

**Comment by Kiirx** [comment]
We can't help you if you don't explain further, give the error, and the code.

**Comment by AsertCreator** [comment]
canvas in new userkit uses double buffering. it means that there are two screens. first is your workspace, second is what user see. when you draw something it draws to first screen. you need to swap them. then user sees the picture. use canvas Display method

**Comment by zarlo** [comment]
@AsertCreator not all the canvas backends use double buffering.
