### ISSUE TITLE
Visual Studio Workloads?

### ISSUE THREAD

**Issue by ImThereum** [CosmosOS/Cosmos#2233]
Currently I have been trying to get CosmosOS but I don't understand what to do, I am using Visual Studio 2022 and I'n getting the DevKit and not the UserKit.

Logs:
https://www.toptal.com/developers/hastebin/avakedilag

The error is about Visual Studio Workloads but I already have .NET 5.0 Core Runtime and i have no clue where to get Visual Studio Extension Development at.

I have done a Reinstall and a Repair but still nothing happens.

**Comment by ImThereum** [comment]
> You need to install it from the visual studio installer, it is a sort of "module" you can find

Hmm ok i'll see if that works if it doesnt I have no clue whats happening

**Comment by abjdev** [comment]
install .net core development and visual studio extension development workloads

**Comment by ptobuon** [comment]
![image](https://user-images.githubusercontent.com/98218366/169358697-1d9782c6-2bb6-46fd-8994-00a0b19df923.png)
Visual studio exstensione development

**Comment by terminal-cs** [comment]
If this issue is solved, it would be nice of you to close it.

**Comment by zarlo** [comment]
> I am using Visual Studio 2022

the current master branch only works on vs 2019

**Comment by ImThereum** [comment]
> install .net core development and visual studio extension development workloads

I'm pretty sure i have this installed ill check again soon

**Comment by ImThereum** [comment]
> If this issue is solved, it would be nice of you to close it.

it isnt just yet

**Comment by Kiirx** [comment]
> the current master branch only works on vs 2019

the vs 2022 branch just got merged to master
