### ISSUE TITLE
Problem with Format

### ISSUE THREAD

**Issue by ComCon2022** [CosmosOS/Cosmos#2234]
**Exception**
'VFSManager' does not contain a definition for 'format'

** VS Output Logs **
```
Build started...
1>------ Build started: Project: BaseDOS_C, Configuration: Debug Any CPU ------
1>C:\Users\Abram\source\repos\BaseDOS_C\BaseDOS_C\Kernel.cs(14,43,14,49): error CS0117: 'VFSManager' does not contain a definition for 'format'
1>Done building project "BaseDOS_C.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Context**
I'm trying to format a disk but  ```Sys.FileSystem.VFS.VFSManager.Format("0", "FAT32", true);``` does not work, it says that VFSManager does not contain a definition for Format.

**Comment by quajak** [comment]
@MishaTY What is currently the correct way to format a disk?

**Comment by MishaTY** [comment]
See the methods under VFSManager.GetDisks
