### ISSUE TITLE
Math.Tan as way off

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2235]
#### Area of Cosmos - What area of Cosmos are we dealing with?
System.math

#### Expected Behaviour - What do you think that should happen?
The equation I put in should be equal to 72.9467445271450862

#### Actual Behaviour - What unexpectedly happens?
It returns the value of 1.000001

#### Reproduction - How did you get this error to appear?
Run ``1 / Math.Tan(90 * 0.5f / 180.0f * 3.14159f);``

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit

**Comment by quajak** [comment]
![image](https://user-images.githubusercontent.com/8559822/169407083-fba18d02-cf14-47ee-8fc1-71b2f5c8769b.png)
C# under Windows seems to agree with Cosmos?

**Comment by terminal-cs** [comment]
hm... using mathway gives a very slightly different answer (1.00000132) and the android calculator gives 72.9467445271450862

**Comment by terminal-cs** [comment]
using the microsoft math solver gives the same as the android calculator

**Comment by zarlo** [comment]
check ```Math.Tan(0.7853975)```  and ```1 / Math.Tan(0.7853975)``` it could be a rounding issue

**Comment by quajak** [comment]
Could it be that android calculator and microsoft math be using degrees and not radians?

**Comment by quajak** [comment]
The minor differences between mathway, cosmos and c# windows I would ignore.

**Comment by ascpixi** [comment]
> Could it be that android calculator and microsoft math be using degrees and not radians?

yep, Math.Tan is correct here, `1 / Math.Tan((90 * 0.5f / 180.0f * 3.14159f) * (Math.PI / 180))` ([run](https://rextester.com/JGDXJ37171)) returns the expected value of `72.94674177739903`, as it operates on radians, not degrees
