### ISSUE TITLE
Cursor is stuck and cant move

### ISSUE THREAD

**Issue by vuk5002** [CosmosOS/Cosmos#2236]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.HAL

#### Expected Behaviour - What do you think that should happen?
Cursor can move 

#### Actual Behaviour - What unexpectedly happens?
Cursor is stuck

#### Reproduction - How did you get this error to appear?
`try
                    {
                        canvas = new SVGAIICanvas(new Mode(800, 600, ColorDepth.ColorDepth32));
                        canvas.Clear(Color.Green);

                        Sys.MouseManager.ScreenWidth = 800;
                        Sys.MouseManager.ScreenHeight = 600;

                        Sys.MouseManager.X = (uint)((int)canvas.Mode.Columns / 2);
                        Sys.MouseManager.Y = (uint)((int)canvas.Mode.Rows / 2);

                        Pen bluepen = new Pen(Color.Cyan);
                        Pen brownpen = new Pen(Color.FromArgb(101, 67, 33));

                        canvas.DrawLine(bluepen, (int)Cosmos.System.MouseManager.X, (int)Cosmos.System.MouseManager.Y,
                            (int)Cosmos.System.MouseManager.X + 6, (int)Cosmos.System.MouseManager.Y);
                        canvas.DrawLine(bluepen, (int)Cosmos.System.MouseManager.X, (int)Cosmos.System.MouseManager.Y,
                            (int)Cosmos.System.MouseManager.X, (int)Cosmos.System.MouseManager.Y + 6);
                        canvas.DrawLine(brownpen, (int)Cosmos.System.MouseManager.X, (int)Cosmos.System.MouseManager.Y,
                            (int)Cosmos.System.MouseManager.X + 12, (int)Cosmos.System.MouseManager.Y + 12);

                        canvas.Display();
                        canvas.Clear(Color.Green);
            }
                    catch (Exception e)
                    {
                        mDebugger.Send("Exception occurred: " + e.Message);
                        Sys.Power.Shutdown();
                    }`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by ascpixi** [comment]
are you sure you're doing this in the main system loop, or only in `BeforeRun`? i see a canvas initialization:
```cs
canvas = new SVGAIICanvas(new Mode(800, 600, ColorDepth.ColorDepth32));
canvas.Clear(Color.Green);
```
which makes me think that this is ran only once in `BeforeRun`...

**Comment by quajak** [comment]
You are constantly setting the mouse position?

```
Sys.MouseManager.X = (uint)((int)canvas.Mode.Columns / 2);
Sys.MouseManager.Y = (uint)((int)canvas.Mode.Rows / 2);
```

**Comment by vuk5002** [comment]
> are you sure you're doing this in the main system loop, or only in `BeforeRun`? i see a canvas initialization:
> 
> ```cs
> canvas = new SVGAIICanvas(new Mode(800, 600, ColorDepth.ColorDepth32));
> canvas.Clear(Color.Green);
> ```
> 
> which makes me think that this is ran only once in `BeforeRun`...

Main loop in Run();

**Comment by ascpixi** [comment]
> > are you sure you're doing this in the main system loop, or only in `BeforeRun`? i see a canvas initialization:
> > ```cs
> > canvas = new SVGAIICanvas(new Mode(800, 600, ColorDepth.ColorDepth32));
> > canvas.Clear(Color.Green);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which makes me think that this is ran only once in `BeforeRun`...
> 
> Main loop in Run();

well, you should put the canvas initialization code in `BeforeRun()`, like so:
```cs
protected override void BeforeRun(){
    canvas = new SVGAIICanvas(new Mode(800, 600, ColorDepth.ColorDepth32));
}
```
...and leave the rest of your code in `Run()`

this by itself shouldn't be the issue you're experiencing, it's probably the bit of code that Quajak pointed out that sets the MouseManager's X and Y coordinates - try removing those two lines (or put them in `BeforeRun`, as it seems you want to center the cursor's position once on boot)
