### ISSUE TITLE
Compiler Won't Work - ld.exe Error

### ISSUE THREAD

**Issue by theopcoder** [CosmosOS/Cosmos#2237]
Have you checked Github Issues for similar errors?

**Exception**
Post the exception returned by Visual Studio
MSB6006 "ld.exe" exited with code -1073741502

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
MSB6006 "ld.exe" exited with code -1073741502

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Try building project

**Screenshots**

![image](https://user-images.githubusercontent.com/58401646/169680617-c5895439-3222-4584-a2f5-cf6be0179287.png)

sometimes instead of the error box it will post this in console. it seems random 
![image](https://user-images.githubusercontent.com/58401646/169680752-e123cb8b-63ae-4be1-8350-2bef03f200e3.png)

Codeblock:
Build started...
1>------ Build started: Project: PrismOS, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>PrismOS -> D:\GitHub\Prism-OS\PrismOS\bin\Debug\net5.0\PrismOS.dll
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\net5.0\PrismOS.bin bin\Debug\net5.0\PrismOS.obj
1>      0 [main] ? (26592) C:\Users\bob\.nuget\packages\cosmos.build\0.1.0-localbuild20220517070801\tools\cygwin\win\ld.exe: *** fatal error - unable to allocate heap, heap_chunk_size 0x300000, slop 0xDC300000, Win32 error 87

Edit:
![unknown](https://user-images.githubusercontent.com/55886806/169680807-855b078f-f56d-4b62-b846-982f59f2a2e5.png)

**Context**
Before posting please confirm that the following are in order
[ ✔] Both Cosmos VS Extensions are installed
[✔ ] In the NuGet Package Manager "Include prerelease" is selected
[✔ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[✔ ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

When trying to build the solution it keeps giving that error.

**Comment by quajak** [comment]
Does this only happen when building PrismOS or any kernel?

**Comment by theopcoder** [comment]
I have fixed the issue just recently.

Steps:
Uninstall Cosmos Dev Kit
Uninstall/Repair Visual Studio 2022

After VS 2022 Is reinstalled or repaired, reinstall cosmos dev kit and it was fixed.

I believe that this error was some corrupted or missing file elsewhere. However, repairing VS2022 and reinstalling the cosmos dev kit have seemed to fix the error.
