### ISSUE TITLE
TCP source code is in internal

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2240]
#### Area of Cosmos - What area of Cosmos are we dealing with?
TCP source code

all of it is in internal so its impossible to make a plug of it

**Comment by quajak** [comment]
You can technically plug internal methods. Are you trying to use the internal methods or overwrite them?

**Comment by Kiirx** [comment]
overwrite them, since some of the things doesnt seems right for me

**Comment by quajak** [comment]
with "some of the things dont seem right" do you mean that the implementation seems buggy or that your usecase requires changes?

**Comment by Kiirx** [comment]
the implementation seems really buggy, it sometimes cant connect to the server, but when it does it sends the data and idk what Cosmos do but the server just resends nothing, I got it to send the data to the Cosmos Kernel 2 times but even with that cosmos could'nt get it back, also it fails to close the connection

**Comment by quajak** [comment]
In that case, a better course of action would be to fix the bugs in the Cosmos Implementation, rather than allow a way for every user to fix the bugs themselves.

**Comment by Kiirx** [comment]
well it would be very slow, I would have to rebuild cosmos everytime, build the project, there's like 5 min per build if I do like that

**Comment by quajak** [comment]
you can either move the code you need to test it into one of the existing test kernels or include your own kernel as a test kernel and use the TestRunner so that you dont need to run the installer every time.

**Comment by Kiirx** [comment]
the TestRunner???

**Comment by zarlo** [comment]
> well it would be very slow, I would have to rebuild cosmos everytime, build the project, there's like 5 min per build if I do like that

you can speed this up by just building the Cosmos.System2 nuget package and copy it into the local nuget repo
or you can just include it as a project reference

**Comment by valentinbreiz** [comment]
Bonjour @Kiirx, what do you need to be public in the tcp classes? What are you trying to do?

**Comment by Kiirx** [comment]
> Bonjour @Kiirx, what do you need being public in the tcp classes? What are you trying to do?

hey you're really back! 

Actually I dont need it anymore because I was thinking that something was wrong in the code, like when closing the TCP connection, I can close that
