### ISSUE TITLE
Canvas not showing

### ISSUE THREAD

**Issue by ptobuon** [CosmosOS/Cosmos#2245]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debug

#### Actual Behaviour - What unexpectedly happens?
I have started and compiled my OS, but the canvas isn't showing

#### Reproduction - How did you get this error to appear?
Code:
![image](https://user-images.githubusercontent.com/98218366/170103483-ab547588-56eb-403e-8465-9922c5c5e0d2.png)
Result:
![image](https://user-images.githubusercontent.com/98218366/170103532-2c7561f7-78c0-401d-ae3b-cdb242086d76.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev kit on VS2022

**Comment by Kiirx** [comment]
this isnt a bug, you're asking cosmos to clear the canvas screen and then you tell cosmos what is the canvas.
