### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by KittenPixel-cell** [CosmosOS/Cosmos#2249]
#### VM-Ware Error -
VMware Player unrecoverable error: (vcpu-0)

This virtual machine has tried to execute an invalid part of memory. It is possible that the virtual disk or CD media you are using is not bootable or that a program or driver running in the virtual machine has malfunctioned.

A log file is available in "C:\Users\natet\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\vmware.log".  

You can request support.  

To collect data to submit to VMware technical support, run "vm-support".

We will respond on the basis of your support entitlemen

**Comment by ptobuon** [comment]
- Install the latest user kit/dev kit. 20200708 is a build of 2020
- Try to reinstall or update vmware,

**Comment by KittenPixel-cell** [comment]
ok

**Comment by KittenPixel-cell** [comment]
wait nvm I forgot I had latest user kit

**Comment by ptobuon** [comment]
And, you can see the file `C:\Users\natet\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\vmware.log` and paste it here? Maybe i can understand something

**Comment by KittenPixel-cell** [comment]
one sec I am trying my own fix of something I added

**Comment by quajak** [comment]
Restart vs to fix the new error. Can you post the code for your kernel?

**Comment by KittenPixel-cell** [comment]
Ya I don't have much not even a gui yet

**Comment by KittenPixel-cell** [comment]
I restarted my pc it fixed it
