### ISSUE TITLE
How can i create project in vs 2022

### ISSUE THREAD

**Issue by sajjadarashhh** [CosmosOS/Cosmos#2253]
theres a way to build and make cosmos in vs 2019!?

**Comment by zarlo** [comment]
the current dev kit support for vs2019 was droped use it in vs 2019 you can use the current user kit

**Comment by ptobuon** [comment]
This is the latest release (Download exe for user kit or zip for dev kit)
https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20220209

**Comment by Kiirx** [comment]
Don't pick the userkit

**Comment by quajak** [comment]
> the current dev kit support for vs2019 was droped use it in vs 2019 you can use the current user kit

We havent made a new userkit with vs 2022 support yet, so you currently still need to use the devkit.

**Comment by Kiirx** [comment]
> > the current dev kit support for vs2019 was droped use it in vs 2019 you can use the current user kit
> 
> We havent made a new userkit with vs 2022 support yet, so you currently still need to use the devkit.

Ans also it's less stable than the latest devkit

**Comment by Diamantino-Op** [comment]
i still have one devkit for VS2019
and it's not old, or, you can go in previous commits and see the source to download it

**Comment by valentinbreiz** [comment]
If you want to use VS2019 download and install the last release if you want to use VS2022 clone and install the devkit
