### ISSUE TITLE
Hangs at "waiting for debugger connection" when booting as ISO

### ISSUE THREAD

**Issue by RockZombie4** [CosmosOS/Cosmos#2262]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Boot

#### Expected Behaviour - What do you think that should happen?
Boot up my OS

#### Actual Behaviour - What unexpectedly happens?
Hangs at: "Waiting for Debugger connection..."

#### Reproduction - How did you get this error to appear?
Followed instructions from here:
[Website](https://www.gocosmos.org/docs/booting-your-os-from-a-usb-drive/
)
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by Kiirx** [comment]
please see the other issues or on the discord before opening this is a common issue and its getting kind of annoying, just disable the debugger

---
**How to remove "Waiting for debugger connection"**

Go to properties of the project (right click, than click properties), click cosmos, go to debug and uncheck remote debugging

**Comment by RockZombie4** [comment]
ok, FINALLY, THank you.
