### ISSUE TITLE
Cosmos built OS not loading

### ISSUE THREAD

**Issue by AyProductions** [CosmosOS/Cosmos#2268]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio Build

#### Expected Behaviour - What do you think that should happen?
Cosmos should not give error and open VMware with my OS

#### Actual Behaviour - What unexpectedly happens?
Error - A project with an output Type of Class Library cannot be started directly.

#### Reproduction - How did you get this error to appear?
Click the 'Run' option

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos

**Comment by quajak** [comment]
Please use the correct issue template.

Can you please provide the following information?
**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

**Comment by AyProductions** [comment]
[Installed] Both Cosmos VS Extensions are installed
[Not Done] In the NuGet Package Manager "Include prerelease" is selected
[Not Checked] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[Installed through User kit installer from gocosmos.org] The Cosmos NuGet packages are installed

![image](https://user-images.githubusercontent.com/76834319/171386716-b1f1dea5-2f7b-4fa0-8203-127f2b475243.png)
