### ISSUE TITLE
Port Cosmos to .net7

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#2270]

**Comment by Kiirx** [comment]
bruh .net 7 already

**Comment by valentinbreiz** [comment]
@Kiirx we have until November 12, 2024 (end of .net6 support), don't worry ;)

**Comment by AnErrupTion** [comment]
It's still in Preview :)

**Comment by Kiirx** [comment]
oh ok :D

**Comment by zarlo** [comment]
> @Kiirx we have until November 12, 2024 (end of .net6 support), don't worry ;)

and by then we will have .net 8 and .net 9 will be coming up

**Comment by AsertCreator** [comment]
omg net 7 already. I just did started migrating to net 6

**Comment by quajak** [comment]
I think we should stay on LTS versions as much as possible.

**Comment by MishaTY** [comment]
Closing as we should only stay on lts versions
