### ISSUE TITLE
Multiple Invalid plug method! Target method not found

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#2271]
3>Message : warning : Invalid plug method! Target method not found. : SystemBooleanCosmosCore_PlugsSystemMulticastDelegateImplTrySetSlotSystemMulticastDelegateSystemObjectarraySystemInt32SystemObject
3>Message : warning : Invalid plug method! Target method not found. : SystemStringCosmosCore_PlugsSystemTimeZoneInfoImplTryGetLocalizedNameByMuiNativeResourceSystemString
3>Message : warning : Invalid plug method! Target method not found. : SystemVoidCosmosSystem_PlugsSystemRuntimeInteropServicesMarshalImplSetLastWin32ErrorSystemInt32
3>Message : warning : Invalid plug method! Target method not found. : SystemInt64CosmosSystem_PlugsSystemDateTimeImplGetSystemTimeAsFileTime
3>Message : warning : Invalid plug method! Target method not found. : SystemInt32CosmosSystem_PlugsSystemRandomImplGenerateGlobalSeed
3>Message : warning : Invalid plug method! Target method not found. : SystemInt32CosmosSystem_PlugsSystemThreadingThreadImplGetOptimalMaxSpinWaitsPerSpinIterationInternal
3>Message : warning : Invalid plug method! Target method not found. : SystemVoidCosmosSystem_PlugsSystemThreadingThreadImplStartupSetApartmentStateInternal
3>Message : warning : Invalid plug method! Target method not found. : SystemVoidCosmosSystem_PlugsSystemThreadingThreadImplStartInternal
3>Message : warning : Invalid plug method! Target method not found. : SystemVoidCosmosSystem_PlugsSystemThreadingThreadImplSetStartSystemDelegateSystemInt32

**Comment by zarlo** [comment]
they are its saying there is a plug for a method that does not exist

**Comment by Diamantino-Op** [comment]
It's normal dw, they shouldn't give problems for now

**Comment by MishaTY** [comment]
This is normal
