### ISSUE TITLE
Cannot use filesystem on vmware without running from visual studio.

### ISSUE THREAD

**Issue by RockZombie4** [CosmosOS/Cosmos#2272]
#### Area of Cosmos - What area of Cosmos are we dealing with?
filesystem

#### Expected Behaviour - What do you think that should happen?
Filesystem behaves like normal on vmware

#### Actual Behaviour - What unexpectedly happens?
If I use the ISO on vmware directly, the filesystem doesn't work.

#### Reproduction - How did you get this error to appear?
I built the os without debugger mode and then used the ISO on VMware.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by zarlo** [comment]
the disk on the VM needs to be formatted to FAT ahead of time

**Comment by Yekc** [comment]
> the disk on the VM needs to be formatted to FAT ahead of time

How do I do this?
When creating a new virtual machine on vmware I can't seem to find any settings related to the hard disk like on the one automatically generated by Cosmos
![image](https://user-images.githubusercontent.com/71790420/182984401-d0e01714-51e7-4804-99ff-d75eb83cfde9.png)
