### ISSUE TITLE
VFS documentation for formatting is outdated

### ISSUE THREAD

**Issue by EnZon3** [CosmosOS/Cosmos#2273]
#### URL of Documentation - What page of documentation are we dealing with?

https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

#### Expected Behaviour - What do you think should happen?
The functions implemented in my OS from the documentation should work

#### Actual Behaviour - What is the issue?
'CosmosVFS' does not contain a definition for 'Format' and no accessible extension method 'Format' accepting a first argument of type 'CosmosVFS' could be found (are you missing a using directive or an assembly reference?)

**Comment by Diamantino-Op** [comment]
where evn is Format?

**Comment by EnZon3** [comment]
> where evn is Format?

[cosmos.github.io](https://cosmosos.github.io/articles/Kernel/VFS.html)

**Comment by Diamantino-Op** [comment]
that is a bit outdated, but the github version is not

**Comment by quajak** [comment]
https://github.com/CosmosOS/Cosmos/issues/2234 explains how it can currently be done

**Comment by quajak** [comment]
The documentation hosted on cosmosos.github.io is the only one being kept up to date, since we can review any changes before they are added. Feel free to add PRs to update the documentation. I made a small PR to remove the outdated information https://github.com/CosmosOS/Cosmos/pull/2275
