### ISSUE TITLE
Error while invoking l2cpu

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#228]
using System;
    using System.Collections.Generic;
    using System.Text;
    using Sys = Cosmos.System;
    namespace CosmosKernel2
         public class Kernel : Sys.Kernel
         {
              protected override void BeforeRun()
              {
                  Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
               }

               protected override void Run()
               {
                    Console.Write("Input: ");
                    var input = Console.ReadLine();
                    Console.Write("Text typed: ");
                    Console.WriteLine(input);
                }
          }
     }
I am running AMD cpu, VS 2015 Release
There is exactly whole log i get: 
1>------ Build started: Project: ThontOS, Configuration: Debug Any CPU ------
1>  ThontOS -> C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll
2>------ Build started: Project: ThontOSBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
2>	Working directory = 'C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Plug found: 'Cosmos.Core.CPU'
2>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Plug found: 'Cosmos.Core.IOPortBase'
2>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Plug found: 'System.Char'
2>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Plug found: 'System.Random'
2>	Plug found: 'System.Console'
2>	Plug found: 'System.Type'
2>	Plug found: 'System.Threading.Monitor'
2>	Plug found: 'System.Text.DecoderFallback'
2>	Plug found: 'System.Text.EncoderFallback'
2>	Plug found: 'System.Text.ASCIIEncoding'
2>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
2>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosSystemKernelStart': System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(SymbolFormat symFormat, String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 133
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 106
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 99
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(String aAsmPathname, Int32 aMethodToken, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 347
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(MethodBase aMethod, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 342
2>	   at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 175
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 472 ---> System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(SymbolFormat symFormat, String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 133
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule, String searchPath) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 106
2>	   at Microsoft.Samples.Debugging.CorSymbolStore.SymbolAccess.GetReaderForFile(String pathModule) in c:\Data\Sources\OpenSource\Cosmos\source\MDbg4\src\debugger\corapi\SymAccess.cs:line 99
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(String aAsmPathname, Int32 aMethodToken, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 347
2>	   at Cosmos.Debug.Common.DebugInfo.GetSequencePoints(MethodBase aMethod, Boolean aFilterHiddenLines) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 342
2>	   at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 175
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 472
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
Build has been canceled.

**Comment by mterwoord** [comment]
You need to install .NET 3.5

**Comment by lukaandjelkovic** [comment]
I can't because FUCKING WINDOWS 10 programs and features is broken. I alerd tried that. Can you make new branch without use of NET 3.5? Win 10 users will be so goddamit happy

**Comment by mterwoord** [comment]
No need to become rude!

My Windows 10 just allows me to install .NET 3.5

Maybe you're interested in helping us out with removing out .NET 3.5 dependency?

**Comment by ARMmaster17** [comment]
@mterwoord Programs and Features is broken on several non-insider/non-pro versions of Windows 10. I recently had a LAN party and we all wanted to play a game that required a Windows component to be installed (DirectPlay), everyone who had Windows 10 could install it. It just hanged and errored out at 50%.

@lukaandjelkovic What version of W10 do you have?

**Comment by lukaandjelkovic** [comment]
RTM 10240
All forums are full with this installing. The installation just halts after time.

**Comment by lukaandjelkovic** [comment]
And @mterwoord yes i want to help.

**Comment by mterwoord** [comment]
We can use help with #219  (which would have prevented you from installing Cosmos all together)
And fixing the actual issue is #218

**Comment by lukaandjelkovic** [comment]
Now when i successfully installed it using DVD cmd, now it says:
1>------ Build started: Project: ThontOSBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll" 
1>	Working directory = 'C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Plug found: 'System.RuntimeType'
1>	Plug found: 'System.OutOfMemoryException'
1>	Plug found: 'System.Double'
1>	Plug found: 'System.Delegate'
1>	Plug found: 'System.Array'
1>	Plug found: 'System.Buffer'
1>	Plug found: 'System.Enum'
1>	Plug found: 'System.EventHandler'
1>	Plug found: 'System.Exception'
1>	Plug found: 'System.MulticastDelegate'
1>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>	Plug found: 'System.Math'
1>	Plug found: 'System.String'
1>	Plug found: 'System.Diagnostics.Debugger'
1>	Plug found: 'System.Byte'
1>	Plug found: 'System.Environment'
1>	Plug found: 'System.GC'
1>	Plug found: 'System.Int16'
1>	Plug found: 'System.Int32'
1>	Plug found: 'System.Int64'
1>	Plug found: 'System.IntPtr'
1>	Plug found: 'System.Number'
1>	Plug found: 'System.Object'
1>	Plug found: 'System.Single'
1>	Plug found: 'System.SR'
1>	Plug found: 'System.UInt16'
1>	Plug found: 'System.UInt32'
1>	Plug found: 'System.UInt64'
1>	Plug found: 'System.Threading.Interlocked'
1>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>	Plug found: 'System.Resources.ResourceManager'
1>	Plug found: 'System.Net.IPAddress'
1>	Plug found: 'System.Net.SocketAddress'
1>	Plug found: 'System.Globalization.NumberFormatInfo'
1>	Plug found: 'System.Drawing.Color'
1>	Plug found: 'System.Drawing.SR'
1>	Plug found: 'System.Security.CodeAccessSecurityEngine'
1>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>	Plug found: 'System.RuntimeTypeHandle'
1>	Plug found: 'System.SByte'
1>	Plug found: 'System.UIntPtr'
1>	Plug found: 'System.Security.Cryptography.Utils'
1>	Plug found: 'System.Globalization.CultureInfo'
1>	Plug found: 'Microsoft.Win32.RegistryKey'
1>	Plug found: 'Cosmos.Core.CPU'
1>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>	Plug found: 'Cosmos.Core.IOPortBase'
1>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>	Plug found: 'System.Char'
1>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>	Plug found: 'System.Random'
1>	Plug found: 'System.Console'
1>	Plug found: 'System.Type'
1>	Plug found: 'System.Threading.Monitor'
1>	Plug found: 'System.Text.DecoderFallback'
1>	Plug found: 'System.Text.EncoderFallback'
1>	Plug found: 'System.Text.ASCIIEncoding'
1>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Common.MethodIlOp'
1>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Common.Document'
1>	Detecting fields for type 'Cosmos.Debug.Common.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel2KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Luka\documents\visual studio 2015\Projects\ThontOS\ThontOS\bin\Debug\ThontOS.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\corapi.dll
1>	C:\Users\Luka\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:05.1748232
1>Done building project "ThontOSBoot.Cosmos" -- FAILED.
1>
1>Build FAILED.
Build has been canceled.

**Comment by lukaandjelkovic** [comment]
Its Cosmos.Debug.Common.Method!

**Comment by lukaandjelkovic** [comment]
I installed NET 3.5 and it is same;
It doesnt have any matter with NET 3.5
Something else:
1> Detecting fields for type 'Cosmos.Debug.Common.Method' 1> Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel2KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!

**Comment by yates199** [comment]
Check for recursive loops I guess only thing I could think would cause it to call more things than there are


Check Do while and For next loops,


Try add stop check loops




Tim Yates





On Thu, Oct 29, 2015 at 2:37 PM -0700, "Luka Andjelkovic" <notifications@github.com> wrote:
I installed NET 3.5 and it is same;
It doesnt have any matter with NET 3.5
Something else:
1> Detecting fields for type 'Cosmos.Debug.Common.Method' 1> Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel2KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!


---

**Comment by mterwoord** [comment]
@yates199 THe problem is in our compiler. It has an interpreter which does some analytical calculations. 

@lukaandjelkovic Can you reproduce it with a small bit of code? If so, please post that code here, so we can fix the issue..

**Comment by lukaandjelkovic** [comment]
I fixed it by installing NET 3.5. And default code doesnt work.
