### ISSUE TITLE
[VS2022] QEMU isn't installed, when it is.

### ISSUE THREAD

**Issue by Carcass-Project** [CosmosOS/Cosmos#2286]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Debugging and Test Running.
#### Expected Behaviour - What do you think that should happen?

QEMU starts emulating my kernel.
#### Actual Behaviour - What unexpectedly happens?

Errors, and says that QEMU is not installed, while it is.
#### Reproduction - How did you get this error to appear?

Set the profile to QEMU, and run with debug.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Devkit, Not exactly sure, but my Cosmos folder is from January 9th, 2022. VS2022 Branch.(tested with latest master right now, no changes.)

I get this error message when I try to launch my project.
![image](https://user-images.githubusercontent.com/91569324/173129366-9f1ea74f-051c-41d8-ac8b-219c63cfd12c.png)
Afterwards, I get this
![image](https://user-images.githubusercontent.com/91569324/173129494-de93864e-a44e-4cfe-9ebd-238840a701e1.png)

I dug through the code, and noticed that it reads from a registry subkey "QemuConfigFile\shell\Run\command"

If you mention these two nodes, it should allow a custom QEMU installation directory.
![image](https://user-images.githubusercontent.com/91569324/173129323-f41fed08-cb66-49b3-8e3f-3fda839c00a4.png)
However, even with those settings, it shows the same error.

**Comment by valentinbreiz** [comment]
Hello @Carcass-Project should be fixed and merged in master
