### ISSUE TITLE
Unable to read files from Disk Image

### ISSUE THREAD

**Issue by VeryCoolMoment** [CosmosOS/Cosmos#2298]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem

#### Expected Behaviour - What do you think that should happen?
Read anything from the Disk Image (Files, Directory Listings, etc)

#### Actual Behaviour - What unexpectedly happens?
FileNotFoundException happens

#### Reproduction - How did you get this error to appear?
Calling anything that requires `0:\` or `1:\`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Version of the Dev Kit

**Comment by quajak** [comment]
Are you using a virtual machine or real hardware?

**Comment by VeryCoolMoment** [comment]
Virtual Machine

**Comment by ptobuon** [comment]
```csharp
Sys.FileSystem.CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```
You are using this code, right?

**Comment by VeryCoolMoment** [comment]
Yup I am

**Comment by VeryCoolMoment** [comment]
Wait no I wasn't using the 2 line iirc

**Comment by quajak** [comment]
> Virtual Machine

Which one?

**Comment by VeryCoolMoment** [comment]
I was using Oracle's Virtualbox but iirc it happened in VMWare aswell

**Comment by VeryCoolMoment** [comment]
Yeah it does the same thing on VMWare

**Comment by quajak** [comment]
How are you adding the disks to vmware?

**Comment by Kiirx** [comment]
> Just through the CD ROM disk with IDE (since this only happens with the cosmos iso and not hard drive imgs)

Cosmos automatically creates a pre-formatted fat32 vmdk for your VM, using a blank vmdk wont work

**Comment by VeryCoolMoment** [comment]
No I don't mean it like that 
If I put a file in isofiles it doesn't seem to read or even see if there's anything in the drive (that's why I said 1:\)
This was about the CD image and not a hard drive image, sorry about that

**Comment by Kiirx** [comment]
Oh yeah thats another thing, im experiencing it too, it just doesnt detects 1:

**Comment by VeryCoolMoment** [comment]
I see

**Comment by VeryCoolMoment** [comment]
Windows shows that the iso contains the files in isoFiles but Cosmos can't detect it for some unknown reason
I'm running on the latest version but yeah this is confusing

**Comment by quajak** [comment]
@MishaTY Any idea what the issue could be?

**Comment by VeryCoolMoment** [comment]
![image](https://user-images.githubusercontent.com/64923791/187021477-fae67adb-eaef-4eae-9cba-2d5b6db71c3f.png)
I think this maybe the issue but i'm running a outdated version of cosmos right now so i'll try compiling a new version

**Comment by VeryCoolMoment** [comment]
Tried compiiling a new version and the issue seems to still be there

**Comment by Kiirx** [comment]
#2438
