### ISSUE TITLE
How do I Make a GUI, Use Voids in other classes with them being static and overall help with the Canvas

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#2299]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Canvas and using voids in other classes

#### Expected Behaviour - What do you think that should happen?
I need more help with using the canvas. Also how do I use a void in another class without a static void. And How do I create a GUI any help would be great.

#### Actual Behaviour - What unexpectedly happens?
Its hard to create a canvas and I can't access anything in another class

#### Reproduction - How did you get this error to appear?
using a static void in a void. Trying to get a GUI in Cosmos

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos version 2020 User kit

Any help is appreciated, thanks

**Comment by ptobuon** [comment]
For creating a GUI, i recommend to start from a "template": https://github.com/nifanfa/Cosmos-GUI-Sample
If you are a newbie, read the CGS docs here: https://cosmosos.github.io/articles/Kernel/CGS.html
If you are a advanced user and you want to know the api, see the cgs api docs here: https://cosmosos.github.io/api/Cosmos.System.Graphics.SVGAIICanvas.html

**Comment by valentinbreiz** [comment]
Thank you very much for helping @ptobuon

**Comment by DolphinFlopFish** [comment]
Thanks So Much!!!
