### ISSUE TITLE
PlugsReference must contain an absolute path

### ISSUE THREAD

**Issue by GoldenretriverYT** [CosmosOS/Cosmos#2300]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Project structure, building

#### Expected Behaviour - What do you think that should happen?
Building should not throw an exception when using relative paths when including plugs

#### Actual Behaviour - What unexpectedly happens?
Including a plug using the PlugsReference tag results in following error:

```
1>Error : error occurred: System.ArgumentException: Path "..\SpaghettoOSPlugs\bin\Debug\net6.0\SpaghettoOSPlugs.dll" is not an absolute path. (Parameter 'assemblyPath')
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\franc\source\repos\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
1>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\franc\source\repos\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\franc\source\repos\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\franc\source\repos\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
```

This is the line where I include the plugs:
`<PlugsReference Include="..\SpaghettoOSPlugs\bin\Debug\net6.0\SpaghettoOSPlugs.dll" />`

#### Reproduction - How did you get this error to appear?
Create two projects, one class library including a plug and one being a Cosmos kernel. Edit the csproj file and add a PlugsReference tag using a relative path

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit
Cosmos Commit: https://github.com/CosmosOS/Cosmos/commit/e37128584501e825632fb4cd0322829395e5b0d3
IL2CPU Commit: https://github.com/CosmosOS/IL2CPU/commit/efcd2fe9a315b57171b872e9c9c8e203e076ce2f

Should be a bug according to [this reply](https://github.com/CosmosOS/Cosmos/discussions/2297#discussioncomment-2958995)

**Comment by Arawn-Davies** [comment]
I've been able to use a path with $(MSBuildProjectDirectory)\, so     
```<PlugsReference Include="$(MSBuildProjectDirectory)\..\MedliPlugs\bin\Debug\netcoreapp2.0\MedliPlugs.dll" />```
as opposed to a path starting with ..\ so try give this a go. I'm not using Cosmos at the moment but that's how I've had it in my long-term project and I haven't had an issue with it, but I can't say if it's working at the moment either
