### ISSUE TITLE
Canvas.DrawString() Problem

### ISSUE THREAD

**Issue by DolphinFlopFish** [CosmosOS/Cosmos#2301]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Fonts/Graphics

#### Expected Behaviour - What do you think that should happen?
I should be able to create a font and use the Canvas.DrawString() Function

#### Actual Behaviour - What unexpectedly happens?
The VM crashes (I think it is the font creation)

#### Reproduction - How did you get this error to appear?
I think that I am making the font wrong, I am doing Sys.Graphics.Fonts.Font font; and then putting it in the DrawString() Function.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Dev Kit 2022

**Comment by MishaTY** [comment]
Use PCScreenFont.Default

**Comment by DolphinFlopFish** [comment]
Now the mouse is lagging

**Comment by LoxyMono** [comment]
The default cosmos drawstring is slow, it will heavily drop the fps

**Comment by DolphinFlopFish** [comment]
oh

**Comment by quajak** [comment]
The way PCScreenFont.Default currently works is that you get a new instance every time. Loading the font is slow. Therefore you should try keep a copy of PCScreenFont.Default in your code so no new instance is created.

**Comment by AsertCreator** [comment]
create new static field, where you load default font once. then change your code to reference that field. it wont make new instances every time, making your system run faster. here is some code example:
```
private static PCScreenFont cache;

// call this method before you start drawing and only once
public static void Initialize(){
    /*if you already have some code there, leave it there*/
    cache = PCScreenFont.Default;
}
/*then, change all occurrences of "PCScreenFont.Default" to "cache"*/
```

**Comment by anamay2222** [comment]
Thanks For the answer ! I only have one more question it is not related to the topic but I would appreciate if you answer it .When is the Linux support coming ???

**Comment by AsertCreator** [comment]
it's there alredy. you can get more information about it in cosmos documentation.

**Comment by anamay2222** [comment]
Can you please provide me a link
