### ISSUE TITLE
IL2CPU.exe error

### ISSUE THREAD

**Issue by andrewkitaev** [CosmosOS/Cosmos#2312]
I have problems when building the project, the output is:

```
Error MSB6006 "IL2CPU.exe" exited with code -2147450730. Agnelix Kernel C:\Users\(user)\.nuget\packages\cosmos.build\0.1.0-localbuild20220209054635\build\Cosmos.Build.targets 175
```

I reinstalled 3 times Cosmos User Kit

How can I solve it?

**Comment by quajak** [comment]
Can you post the entire build output log?

**Comment by andrewkitaev** [comment]
> Can you post the entire build output log?

where is the file located?

**Comment by quajak** [comment]
Its in the output window in Visual Studio

**Comment by quajak** [comment]
can you post the entire log? most likely the actual error is earlier in the log

**Comment by andrewkitaev** [comment]
Damn, I don't really understand Visual Studio, and for the time being I decided to try to learn assembler ( Flat assembler ), memory addresses, registers, etc. to write an OS on it, Cosmos is in the background, but thanks for the fact that you help at least somehow. Issue solved failed
