### ISSUE TITLE
Visual Studio 2022 Exception: changing project profile

### ISSUE THREAD

**Issue by Claupio** [CosmosOS/Cosmos#2317]
When I try to change the project profie from VMware to ISO Visual Studio 2022 crashes. When I use VMware it normally works.
<img width="1052" alt="Exception" src="https://user-images.githubusercontent.com/46087711/176958042-a1b2c297-4322-4e52-a81c-0cc6ba500a5a.png">

**Comment by Kiirx** [comment]
We're not italian
