### ISSUE TITLE
Shutdown error iL2CPU.exe -2147450730

### ISSUE THREAD

**Issue by Konmn** [CosmosOS/Cosmos#2320]
When i'm trying to build or run cosmos application, i got an error that said me: "IL2CPU.exe" shotdown with code -2147450730.

How can i fix that?
VS 2019, latest version of Cosmos User Kit, im trying to reinstall kit billion times, nothing happened.

**Comment by quajak** [comment]
Please post the entire build logs from Visual Studio.

**Comment by Konmn** [comment]
oh my god, thank you so much. He didn't have .net 5.0, i install it and problem disappeared.
