### ISSUE TITLE
System.IO (FileNotFoundException), When using File.Exists.

### ISSUE THREAD

**Issue by Doonort3** [CosmosOS/Cosmos#2323]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.System.FileSystem
System.IO (used exactly that)

#### Expected Behaviour - What do you think that should happen?
**In the first case:**
* Check if there is a file to copy and the directory where to copy via File.Exists and Directory.Exists, where to copy this file, if one of the above is not found - display an error.

**In the second case:**
* Check for the file via File.Exists, if not found - create it.

#### Actual Behaviour - What unexpectedly happens?
FileNotFoundException (https://docs.microsoft.com/en-us/dotnet/api/system.io.filenotfoundexception?view=net-5.0)
Namely - FileNotFoundException (https://docs.microsoft.com/en-us/dotnet/api/system.io.filenotfoundexception.-ctor?view=net-5.0#system-io-filenotfoundexception-ctor)

**In the first case:**
![изображение](https://user-images.githubusercontent.com/69197339/177840256-6a97038a-0e2f-4efe-a28d-13442de5e29f.png)
**In the second case:**
![image](https://user-images.githubusercontent.com/69197339/177839958-75c9ae05-540b-4803-8027-d96c5713c6d6.png)

#### Reproduction - How did you get this error to appear?
A new use of File.Exists that takes arguments:
**In the first case:**
* as a file name and the directory where to copy the file

**In the second case:**
* as a name for the new file

_**In both cases I get this error, but in past invocations of this method - there was no problem, this problem appeared now.**_

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I use the Dev Kit for Visual Studio 2022, it was downloaded a long time ago, in 2021, and I don't remember which commit I have installed, I apologize for that. If I can find out the version in cosmos files, show me how, and I will do it.

### Code problem area (commented), for convenience, rename it to .cs
[Lines of code with error.txt](https://github.com/CosmosOS/Cosmos/files/9066616/Lines.of.code.with.error.txt)

If you have any questions about my lame issue, write and I'll clarify it.

**Comment by zarlo** [comment]
have you set up the VFS?

**Comment by quajak** [comment]
The VFS should be enabled since otherwise the list command would not have worked.
Does `touch newfile.txt` work? What about `touch newfil.txt` and `touch newfil.mtxt`?

In your code what values does `Kernel.CurrentDirectory` have?

**Comment by Doonort3** [comment]
> The VFS should be enabled since otherwise the list command would not have worked. Does `touch newfile.txt` work? What about `touch newfil.txt` and `touch newfil.mtxt`?
> 
> In your code what values does `Kernel.CurrentDirectory` have?

VFS и vmdk инициализированы, в прошлый использованиях методов из IO, с использованием VFS, всё было стабильно и без ошибок. Команда touch newfile.txt как и любое другое название для файла - не работают.

**Comment by Doonort3** [comment]
> have you set up the VFS?

Yes, of course I initialized VFS. In the issue I wrote that up to that point - all code worked correctly with VFS and IO

**Comment by Doonort3** [comment]
I think that in any case, trying to check the file or directory should happen, not display an error. Even if any of the arguments are wrong, File.Exists and Directory.Exists are checked.

**Comment by quajak** [comment]
> I think that in any case, trying to check the file or directory should happen, not display an error. Even if any of the arguments are wrong, File.Exists and Directory.Exists are checked.

Yes, I agree. I was trying to figure out if we can easily pinpoint the issue since the Cosmos tests for File.Exists are passing with no error. In the past there have been issues with exact file names in Fat32 so I was trying to figure out if that was the case here.

**Comment by Doonort3** [comment]
> 



> > I think that in any case, trying to check the file or directory should happen, not display an error. Even if any of the arguments are wrong, File.Exists and Directory.Exists are checked.
> 
> Yes, I agree. I was trying to figure out if we can easily pinpoint the issue since the Cosmos tests for File.Exists are passing with no error. In the past there have been issues with exact file names in Fat32 so I was trying to figure out if that was the case here.

It turns out that this is a more serious problem? I tried to run the code with the same methods - but no success, maybe I should reinstall cosmos, although it's very strange that it worked a couple of days ago, maybe there was some shift? But in that case the previous code shouldn't work either, but it does, mysteriously

**Comment by quajak** [comment]
What do you mean with no success? Reinstalling should not really help. The issue is most likely with the vmdk currently being used.  Most likely it got corrupted somehow. Can you please keep a copy of the current vmdk and then try with a clean one (you can download it from the repo)?

**Comment by Doonort3** [comment]
> What do you mean with no success? Reinstalling should not really help. The issue is most likely with the vmdk currently being used. Most likely it got corrupted somehow. Can you please keep a copy of the current vmdk and then try with a clean one (you can download it from the repo)?

I created a new project and used File.Exists there, it still pops up FileNotFoundException. I replaced the vmdk image with the one I just downloaded from cosmos repository, the problem did not go away, neither the cp command nor the touch command works
____
![image](https://user-images.githubusercontent.com/69197339/178104758-a8564af6-d62f-42e0-bdd9-ecbc7374ef0f.png)
![image](https://user-images.githubusercontent.com/69197339/178104766-a65bce26-5a1a-417a-bd45-93ba77edcb8f.png)

**Comment by Doonort3** [comment]
> What do you mean with no success? Reinstalling should not really help. The issue is most likely with the vmdk currently being used. Most likely it got corrupted somehow. Can you please keep a copy of the current vmdk and then try with a clean one (you can download it from the repo)?

### I found a solution and why this was happening!
It had **only to do with my code**, 

1. I should have used **"else if"**, instead of just **"else"**.

2. I should have put **Kernel.CurrentDirectory** wherever files or directories are checked and created, so that all checks are not by empty space.

Without Kernel.CurrentDirecory:
```
> touch newFile.txt
* newFile.txt\ *
>> Error like "not found"
```

With Kernel.CurrentDirectory:
```
> touch newFile.txt
* 0:\newFile.txt\ *
>> File created
```



![Screenshot_1](https://user-images.githubusercontent.com/69197339/178105769-8ef33e35-7d69-41ed-97aa-ce3ab01fd5ec.png)
![изображение](https://user-images.githubusercontent.com/69197339/178105906-483b6115-eb7f-4f47-882a-a9ce8bcb54f2.png)


_But I have no idea why a simple else would not work._

**Comment by Doonort3** [comment]
> What do you mean with no success? Reinstalling should not really help. The issue is most likely with the vmdk currently being used. Most likely it got corrupted somehow. Can you please keep a copy of the current vmdk and then try with a clean one (you can download it from the repo)?

### I found a solution and why this was happening!
It had **only to do with my code**, 

1. I should have used **"else if"**, instead of just **"else"**.

2. I should have put **Kernel.CurrentDirectory** wherever files or directories are checked and created, so that all checks are not by empty space.

Without Kernel.CurrentDirecory:
```
> touch newFile.txt
* newFile.txt\ *
>> Error like "not found"
```

With Kernel.CurrentDirectory:
```
> touch newFile.txt
* 0:\newFile.txt\ *
>> File created
```



![Screenshot_1](https://user-images.githubusercontent.com/69197339/178105769-8ef33e35-7d69-41ed-97aa-ce3ab01fd5ec.png)
![изображение](https://user-images.githubusercontent.com/69197339/178105906-483b6115-eb7f-4f47-882a-a9ce8bcb54f2.png)

## After all these manipulations, it all worked and the FileNotFoundException error did not appear.

_But I have no idea why a simple else would not work._

**Comment by quajak** [comment]
That sounds like you found a workaround for the bug, Let's actually solve it so we dont have this issue in the future. 

> I should have put Kernel.CurrentDirectory wherever files or directories are checked and created, so that all checks are not by empty space.

What do you mean by this?

**Comment by Doonort3** [comment]
> That sounds like you found a workaround for the bug, Let's actually solve it so we dont have this issue in the future.
> 
> > I should have put Kernel.CurrentDirectory wherever files or directories are checked and created, so that all checks are not by empty space.
> 
> What do you mean by this?

I attached examples with and without `Kernel.CurrentDirectory`. If you use, for example, `File.Copy`, it needs a path, if you enter just `File.Copy(arguments[0], arguments[1])`, we get that we copy file from unknown place and unknown place, because we don't have specified VFS root folder, which is exactly what is specified in `Kernel.CurrentDirectory`.

I put `Kernel.CurrentDirectory` at the beginning of each path argument when using `File.Exists`, `File.Create`, `File.Copy` methods. In my case, `Kernel.CurrentDirectory` always has 0:\ at its beginning.
Example: `File.Copy(Kernel.CurrentDirectory + arguments[0], Kernel.CurrentDirectory + arguments[1])` = `copy 0:\{specified file} to 0:\{specified folder}` and `File.Copy(arguments[0], arguments[1])` = `copy {specified file} to {specified folder}`.
#### In the second case, we cannot logically find anything, because we are looking outside the initialized VFS.

**Comment by quajak** [comment]
Ah, ok. So to be clear the issue was caused by `File.Copy(arguments[0], arguments[1]) `?

**Comment by Doonort3** [comment]
> Ah, ok. So to be clear the issue was caused by `File.Copy(arguments[0], arguments[1]) `?

The problem is caused by `else,` coming out of `if (File.Exists())` and the incorrect path statement in the methods
