### ISSUE TITLE
Error when running Cosmos for the first time

### ISSUE THREAD

**Issue by Vladimir-Moskalenko** [CosmosOS/Cosmos#2326]
#### Version - Were you using the User Kit or Dev Kit? the latest release as of 7/9/2022
![image](https://user-images.githubusercontent.com/93604107/178168352-1312d456-7957-4ba0-9144-99bf4ebc42b9.png)
![image](https://user-images.githubusercontent.com/93604107/178168256-022aa4c0-1ed9-4a17-adf3-b85c5d4ed977.png)
![image](https://user-images.githubusercontent.com/93604107/178168082-1305ccc8-fd5f-4ef5-824a-c74cc3d31cec.png)

**Comment by MishaTY** [comment]
The release configuration is not currently supported.

**Comment by Arawn-Davies** [comment]
You need to switch to Debug configuration in the second toolbar at the top. Closing this issue, as there are still many things to be done before Release is ready for use.
