### ISSUE TITLE
Could not load file or assembly System.Console.

### ISSUE THREAD

**Issue by ser-ui** [CosmosOS/Cosmos#2328]
when i try to compile my OS, VS gives me this error.
![imagen](https://user-images.githubusercontent.com/73035524/178321131-4804aeb1-d928-48c0-b563-75b55b6fdd20.png)
*(some parts of the image are in spanish, but the principal text is in english)*
in the code, i added the following using:
![imagen](https://user-images.githubusercontent.com/73035524/178321511-e0d8f28d-d6c7-46dd-aa3b-eae6c5674731.png)
i dont have any idea to solve that problem, so any solution may help me

**Comment by ser-ui** [comment]
i placed the solution and project in the same directory, but now gives me this error:
![imagen](https://user-images.githubusercontent.com/73035524/178342497-1637d7a3-47b8-4d0c-8f4c-e3359838035c.png)

**Comment by terminal-cs** [comment]
> try connecting to internet and re-trying the build make sure that when you created the project, the "Place solution and project in same directory" is checked make sure that the packages could restore

posting generic dotnet fixing steps is not likely to help, this is an IL2CPU error

**Comment by quajak** [comment]
Are you using the devkit or the userkit? Could you also post the entire output from vs build and debug log?
