### ISSUE TITLE
Mouse doesn't work on real hardware

### ISSUE THREAD

**Issue by Claupio** [CosmosOS/Cosmos#2330]
#### Actual Behaviour - What unexpectedly happens?

Touchpad doesn't work on my Lenovo laptop but keyboard does.  In VMware all goes well.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Dev Kit. I changed some things in the Canvas class.

**Comment by Arawn-Davies** [comment]
This depends on whether the Lenovo touchpad uses USB or works in PS/2 compatibility mode. Newer laptops have done away with the PS/2 standard (keyboards are often kept PS/2 compatible for legacy software). Does an external USB mouse work with Cosmos? Sometimes a laptop can emulate PS/2 mice only over USB

**Comment by Claupio** [comment]
No, USB mouse doesn't work. I forgot one thing: I boot Cosmos from USB. When I disable legacy USB support my pendrive doesn't "appear".

**Comment by terminal-cs** [comment]
you must use PS/2 mice and keyboards, USB is not supported in cosmos. it is possible your motherboard has USB-to-PS/2 emulation but it is not likely, as i have not seen it a lot.
