### ISSUE TITLE
NU1103 and NU1604 on some few steps - don't think anything is gone.

### ISSUE THREAD

**Issue by josaih-mo** [CosmosOS/Cosmos#2335]
**Describe the problem**
A clear and concise description of where the installation is going wrong.
I don't see what's gone, and something failed to restore. Honestly I never check the folders because they are usually fine.

**Steps of installation up to now**
I don't know what happened.

**Expected behavior**
A clear installation of COSMOS so I could make Operating Systems again.

**Logs**
Please post the entire log given by Cosmos. For long logs please use pastebin.
https://www.toptal.com/developers/hastebin/edagajudub

**Steup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) Userkit latest
 - Are you using an admin account? Of course
 - VS Version if applicable: 2022

**Additional context**
This is now on a windows 11 machine.
Edition	Windows 11 Home
Version	21H2
Installed on	‎7/‎18/‎2022
OS build	22000.978
Experience	Windows Feature Experience Pack 1000.22000.978.0

**Comment by quajak** [comment]
Just to be clear, you are running the userkit installer exe?

**Comment by Mar10Josh** [comment]
> Just to be clear, you are running the userkit installer exe?

I used the "userkit install.bat" and "install-VS2022.bat" files to install. Nothing works.

**Comment by zarlo** [comment]
did you clone the other repos?

**Comment by Mar10Josh** [comment]
> did you clone the other repos?

I used the installer to clone

**Comment by quajak** [comment]
Try move this code block https://github.com/CosmosOS/Cosmos/blob/ea6350b6c896159bfd6d06ade0a43fbf5bc4ebb5/source/Cosmos.Build.Builder/CosmosBuildDefinition.cs#L133-L141
to line 102 and then run the builder again.

**Comment by josaih-mo** [comment]
@quajak Error.

C:\Users\Josiah\Downloads\Cosmos-master\source\Cosmos.Build.Builder\CosmosBuildDefinition.cs(108,46): error CS0841: Can
not use local variable 'cosmosPackageProjects' before it is declared [C:\Users\Josiah\Downloads\Cosmos-master\source\Co
smos.Build.Builder\Cosmos.Build.Builder.csproj]

**Comment by josaih-mo** [comment]
The installer is fixed, but the setup process is where it stops.

**Comment by josaih-mo** [comment]
Nope nevermind.
