### ISSUE TITLE
[Feature request] Implement nameof(enum)

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2337]
#### Area of Cosmos - What area of Cosmos are we dealing with?
enum, nameof(), strings

#### Expected Behaviour - What do you think that should happen?
should return the name in the enum

#### Actual Behaviour - What unexpectedly happens?
i don't remember but either plug error or runtime error

#### Reproduction - How did you get this error to appear?
try to get the name of an enum using nameof()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
any version applies

**Comment by AsertCreator** [comment]
as far as i know nameof() is compile-time operator, it doesnt needs runtime things

**Comment by terminal-cs** [comment]
> as far as i know nameof() is compile-time operator, it doesnt needs runtime things

even if it is, it does not work in cosmos

**Comment by quajak** [comment]
I tested nameof(Enum) and it worked for me. Could you please post code where it does not work? The nameof syntax should not need special support in cosmos since it  is a compile time feature.

**Comment by terminal-cs** [comment]
The last I checked it did not work but that's a long time ago, if it works for you currently we can probably close this issue
