### ISSUE TITLE
Strings pulled from Console.ReadLine() don't work as Dictionary Keys if the string lengh is odd numbered

### ISSUE THREAD

**Issue by Incoherent-Code** [CosmosOS/Cosmos#2338]
I have no idea what causes this or if its even cosmos' fault but if an input from Console.ReadLine()  is odd numbered it is not recognized in a Dictionary with with the string as a key.
This issue also happens when decoding strings from a filesystem and trying to use them as a key.
This does not happen if the string is made in the code like if you do: dictionaryEx.Contains("a");

#### Area of Cosmos - What area of Cosmos are we dealing with?
System.Collections.Generic.Dictionary<>

#### Expected Behaviour - What do you think that should happen?
![image](https://user-images.githubusercontent.com/24883579/179656938-647f43d7-7b08-4975-bdbf-bda9d528c59b.png)
All of these inputs are in my Dictionary but only the ones with even amounts of characters work.
Expected behavior would have all of these inputs return true.

#### Reproduction - How did you get this error to appear?
You can either make your system take console inputs and try to use them in a dictionary that uses string as keys with different lengths,
or you can try this test kernel that I used in the screenshot:
https://pastebin.com/DJnbqaac

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev kit Commit (Updated my installation 4 days ago)

**Comment by quajak** [comment]
Thanks for the bug report with code to reproduce it. I have been able to locally reproduce the bug and am investigating.

**Comment by quajak** [comment]
The issue should be fixed by the PR. The important detail was that there was a difference with the calculation of the GetNonRandomizedHashCode between strings allocated on the heap and constant strings in certain conditions.

**Comment by coolcoder613eb** [comment]
i had this issue with the userkit,
i cant compile the devkit.

**Comment by zarlo** [comment]
there was just a new release of the userkit it should have it

**Comment by coolcoder613eb** [comment]
will it work to migrate my code?

**Comment by zarlo** [comment]
it should
