### ISSUE TITLE
Calling IronPython code from C#

### ISSUE THREAD

**Issue by dm-vev** [CosmosOS/Cosmos#2344]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiler(Correct me, maybe I'm wrong)

#### Expected Behaviour - What do you think that should happen?
Sucefull build

#### Actual Behaviour - What unexpectedly happens?
Build error

#### Reproduction - How did you get this error to appear?
Install the IronPython hosting script, and try to run the IronPython code from C#.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
last

![image](https://user-images.githubusercontent.com/80632449/180429884-37826b32-e494-4e0a-91da-d6736d6a7cbd.png)

I ran into a nasty problem, I wanted to make IronPython code run from my C# code, but judging by the error log, it says there is no plug. Tell me, is it possible to run IronPython code from C# directly, or should I do everything at once in IronPython? If so, please tell me how to make a test project on it in Visual Studio 2022.

I will be very grateful for your help.
PS This is not a bug report, it's more of a question: "is it possible?"

**Comment by jwoff78** [comment]
Seems like IronPython is using reflection to run, reflection isn't really supported / plugged.

**Comment by dm-vev** [comment]
It's a pity, but how can you use Cosmos and IronPython directly? Is it possible through Visual Studio?

**Comment by dm-vev** [comment]
I think I didn't put the question correctly. How can I turn IronPython code into ISO?

**Comment by quajak** [comment]
You need to use the iron Python compiler and link the cosmos nuget packages

**Comment by dm-vev** [comment]
Could you provide an example code for the kernel?
