### ISSUE TITLE
Using IronPython directly.

### ISSUE THREAD

**Issue by dm-vev** [CosmosOS/Cosmos#2346]
I'm running into a problem running Cosmos from IronPython. I just don't understand how you can create a base class and build it into an ISO? Someone could help me with this? I am not asking for just a basic example of a kernel and how it should be compiled into an ISO. I tried through standard tools and through Visual Studio with SharpDevelop. I would be very grateful to you.

Apologies in advance for my bad English, I used Google Translate to translate.

**Comment by MishaTY** [comment]
Duplicate of #1503
