### ISSUE TITLE
Range indexing in arrays not plugged

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2350]
**What is the usecase for this plug**
A clear and concise description of where the plug is needed
range indexing in arrays, it is used like so to shorten code:
```cs
byte[] Buffer = new byte[512];
Buffer = RAW[100..612];
```

** Complexity of plug **
Can this plug be added without requiring new drivers or a lot of work? (Methods requiring Linq, Reflection or Networking etc. are too complex for this request)
should not be hard at all, it is easy to implement in regular code
* edit *
example:
```cs
int[] T = new int[X01.Length - 1];
for (int I = 0; I < T.Length; I++)
{
  T[I] = X01[I];
}
X01 = T;
```

**Describe alternatives you've considered**
Are there ways to work around this plug not existing?
yes, however it is way more convenient to use this method

**Additional context**
Add any other context about the plug request here.
nothing much else, it'd also be nice for char[], string[] etc. it workin in normal string, just not arrays afaik

**Comment by quajak** [comment]
Solved by #2442
