### ISSUE TITLE
Cosmos wont install at all

### ISSUE THREAD

**Issue by HAKANKOKCU** [CosmosOS/Cosmos#2351]
**Describe the problem**
When i install cosmos user kit, it doesnt show up at visual studio

**Steps of installation up to now**
I was installed visual studio to "D:/Visual Studio 2022" (Not C: Drive)

I set the installation path to "%appdata%\Cosmos User Kit"
The setup seemed like installed correctly. (but at end there was red text in command prompt but they closed after a half second)
When i opened visual studio, it didnt show up.

**Expected behavior**
it should apear at  "Create a new project" page of visual studio

**Logs**
The setup didnt gave me the logs

**Setup (please complete the following information):**
 - Cosmos Version Userkit 20220209
 - Are you using an admin account? Yes
 - VS Version if applicable 2022 Community

**Additional context**
The setup seemed like did not do anything except putting its files

**Comment by quajak** [comment]
Are the VS Extensions installed?

**Comment by HAKANKOKCU** [comment]
> Are the VS Extensions installed?

if you are saying cosmos ones, no. they didnt

**Comment by quajak** [comment]
You are running the installer exe for the Userkit? It is unclear to me, when the inno setup would be showing red text in a command prompt unless its configuring the nuget packages.

**Comment by HAKANKOKCU** [comment]
> You are running the installer exe for the Userkit? It is unclear to me, when the inno setup would be showing red text in a command prompt unless its configuring the nuget packages.

yes, its installer exe for userkit.

i saw that the command promt with red text is nuget error..

**Comment by quajak** [comment]
Can you try manually installing the vs extensions? The VSIX files are found under %appdata%/Cosmos User Kit/VSIX

**Comment by dm-vev** [comment]
У меня была похожая проблема, я решил так:
1) Установил расширения для создания расширений
![image](https://user-images.githubusercontent.com/80632449/180942430-a1730084-f05b-4ed6-85e4-a0cc5b2d4f86.png)
2) Обновил Висуал Studio до последней версии
3) Запустил install  vs2022.bat
4)  Если произошла ошибка, то перезапустите установщик

Простите что на скриншоте не английский, я не из англоговорящей страны.

**Comment by HAKANKOKCU** [comment]
I still get same error..

Some parts of log is turkish..
[dd_VSIXInstaller_20220726125313_1584.log](https://github.com/CosmosOS/Cosmos/files/9188700/dd_VSIXInstaller_20220726125313_1584.log)

**Comment by HAKANKOKCU** [comment]
Am i installing correct ones?
![resim](https://user-images.githubusercontent.com/103432992/180979593-00028a26-f006-46b2-a477-df6bb08a128d.png)

**Comment by dm-vev** [comment]
Can you tell if your Visual Studio is installed in the default path?

**Comment by HAKANKOKCU** [comment]
> Can you tell if your Visual Studio is installed in the default path?

No. I said in main issue comment:

>**Steps of installation up to now**
>I was installed visual studio to "D:/Visual Studio 2022" (Not C: Drive)

**Comment by quajak** [comment]
> i tried double clicking but it says its not compatiable for installed versions

What versions does the installer list? We are using the standard VS installer system which should handle custom installation locations.

Which packages do you have installed for VS 2022 community?

**Comment by HAKANKOKCU** [comment]
> > i tried double clicking but it says its not compatiable for installed versions
> 
> What versions does the installer list? We are using the standard VS installer system which should handle custom installation locations.
> 
> Which packages do you have installed for VS 2022 community?

it dedects:
visual studio 2022 community,
visual basic 2010 

as the installer came turkish i cloudnt translate them fully: (packages)
.net for desktop apps
.net for android and ios (xamarin)
a package for making extensions for vs

**Comment by quajak** [comment]
And you are only trying to install it for vs 2022 community?

**Comment by HAKANKOKCU** [comment]
> And you are only trying to install it for vs 2022 community?

yes

**Comment by quajak** [comment]
What version of Vs 2022 do you have installed?

**Comment by HAKANKOKCU** [comment]
> What version of Vs 2022 do you have installed?

i dont remember it but i was updated it 2 days ago

**Comment by quajak** [comment]
The issue is that the current userkit is still for VS19. Only the devkit works for VS22

**Comment by HAKANKOKCU** [comment]
when the userkit will for vs2022?

**Comment by quajak** [comment]
There currently does not exist one
