### ISSUE TITLE
IL2CPU.exe" exited with code -2147450730

### ISSUE THREAD

**Issue by nvthielen81** [CosmosOS/Cosmos#2354]
Have you checked Github Issues for similar errors?
yes 

**Exception**
Post the exception returned by Visual Studio
Yes

** VS Output Logs **
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"IL2CPU.exe" exited with code -2147450730.	CosmosKernel1	C:\Users\nadir\.nuget\packages\cosmos.build\0.1.0-localbuild20220209054635\build\Cosmos.Build.targets	175	

** Whit **
Version Visual Studio 16.11.17

** Code **
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {

        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }

        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}
** end code **

**Comment by quajak** [comment]
Please post the content of the vs build output.

**Comment by nvthielen81** [comment]
soft i whit installing , Core tools 5.0
