### ISSUE TITLE
IL2CPU.exe exited with code -2147450730

### ISSUE THREAD

**Issue by AudioTore** [CosmosOS/Cosmos#2359]
For some resson whenever I click run it gives me that error.
I'm a new user to cosmos and the installation so far is very painfull. Any help would make me thankfull.

Inside of my appdata  Cosmos User kit are folders containing "Build", kernel, packages, VSIX, Xsharp, The cosmos.ico uninstall.exe

**Comment by AudioTore** [comment]
Update: Ok so I got the error to go away but now it's giving the error: "yasm.exe" excited with code -1073741515

**Comment by quajak** [comment]
For the yasm.exe issue, the fix is to Install Microsoft Visual C++ 2010 Service Pack
Link: https://www.microsoft.com/en-us/download/details.aspx?id=26999

**Comment by Yekc** [comment]
> Update: Ok so I got the error to go away but now it's giving the error: "yasm.exe" excited with code -1073741515

How?
I'm having the IL2CPU.exe exited with code -2147450730 error and can't find out how to fix it

**Comment by Yekc** [comment]
> > Update: Ok so I got the error to go away but now it's giving the error: "yasm.exe" excited with code -1073741515
> 
> How? I'm having the IL2CPU.exe exited with code -2147450730 error and can't find out how to fix it

Nevermind (hooray)
I just had to install https://versionsof.net/core/5.0/5.0.0/
