### ISSUE TITLE
Making an Iso doesn't seem to be working.

### ISSUE THREAD

**Issue by AudioTore** [CosmosOS/Cosmos#2363]
Whenever I select the iso profile from the build options and try to compile it, it just says "File not specified"

**Comment by Kiirx** [comment]
it still should be building, check the bin folder

**Comment by AudioTore** [comment]
There's a iso in bin folder but it's only bootable for virtual machines.

**Comment by dm-vev** [comment]
Try setting the export iso in the project properties, by default there is an export iso for vmware
