### ISSUE TITLE
Outdated/Broken Tuorial

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2368]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Wiki, iso burning

#### Expected Behaviour - What do you think that should happen?
the ISO file should be read and flashed by rufus

#### Actual Behaviour - What unexpectedly happens?
rufus says it cannot read the ISO file

#### Reproduction - How did you get this error to appear?
Compile cosmos prpject, try to open output iso file with rufus

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit

#### Screenshots
![image](https://user-images.githubusercontent.com/76945439/182046616-4176d8c1-f057-4ea8-864d-c91ba9fb3610.png)

#### Wiki link
https://github.com/CosmosOS/Cosmos/wiki/Booting-Your-OS-from-a-USB-Drive

**Comment by AudioTore** [comment]
YEP I relate to this 100%%. I had a lot of pain installing and just getting Cosmos to work properly on it. Whenever I tried to burn the iso to the usb using rufus it also gave me that exact same error. I don't think the owner cares very much about the wiki and bugs and leans more towards features and whatnot. The guy is very smart but I think he's a bit well I'm not sure but lazy about bugs and stuff.

**Comment by AudioTore** [comment]
I'm developing my Operating System right now and I wish I could just get it to work fine on booting but it seems like the os doesn't support modern computers and usb keyboards and mouses.

**Comment by terminal-cs** [comment]
> I'm developing my Operating System right now and I wish I could just get it to work fine on booting but it seems like the os doesn't support modern computers and usb keyboards and mouses.

Cosmos does not support usb

**Comment by AudioTore** [comment]
Yes that's what I said.

**Comment by winbamstudios** [comment]
I ran it off of USB by using Grub 2.06 for Windows and copying the "grub.cfg" and "<OS NAME>.bin" files

**Comment by terminal-cs** [comment]
Issue closed: use rufus v3.18, however cosmos devs should still look into this

**Comment by coolcoder613eb** [comment]
it works if you use rufus 2.18
