### ISSUE TITLE
Cosmos crashing with kernel panic when running CGS for too long

### ISSUE THREAD

**Issue by AsertCreator** [CosmosOS/Cosmos#2369]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
Cosmos will not crash and will run CGS for at least 16 hours

#### Actual Behaviour - What unexpectedly happens?
Cosmos crashed after ~2 minutes, while getting slower and laggier

#### Reproduction - How did you get this error to appear?
     using Cosmos.System.Graphics.Fonts;
     using Cosmos.System.Graphics;
     using Cosmos.System;
     using System;
     using System.Drawing;
     using System.Collections.Generic;
     using System.Linq;
     using System.Text;
     using System.Threading.Tasks;
     
     namespace someOS.Core
     {
         public static class Shell
         {
             public static PCScreenFont Font = PCScreenFont.Default;
             public static Canvas FSC;
             public static Pen Cursor0 = new Pen(Color.White, 1);
             public static Pen Cursor1 = new Pen(Color.Black, 1);
             public static int CursorSize = 10;
             public static int CursorBorderSize = 2;
             public static Pen Dock0 = new Pen(Color.Red, 1);
             public static Pen Dock1 = new Pen(Color.DarkRed, 1);
             public static int DockBorderSize = 2;
             public static int DockSize = 35;
             public static int ScreenWidth;
             public static int ScreenHeight;
             public static bool Running = true;
             public static List<Window> AllWindows = new();
             public static void Run()
             {
                 FSC = FullScreenCanvas.GetFullScreenCanvas();
                 FSC.Mode = FSC.AvailableModes[4];
                 FSC.Clear();
                 ScreenWidth = FSC.Mode.Columns;
                 ScreenHeight = FSC.Mode.Rows;
                 MouseManager.ScreenWidth = (uint)ScreenWidth;
                 MouseManager.ScreenHeight = (uint)ScreenHeight;
                 AllWindows = new List<Window>()
                 {
                     new Window() { Title = "File Manager" },
                     new Window() { Title = "Desktop" }
                 };
                 while (Running)
                 {
                     FSC.Clear(Color.White);
                     int index = 0;
                     foreach (var win in AllWindows)
                     {
                         RenderWindow(win, AllWindows.Count, index);
                         index++;
                     }
                     RenderDock();
                     FSC.DrawFilledRectangle
                         (Cursor0, (int)MouseManager.X, (int)MouseManager.Y, CursorSize, CursorSize);
                     FSC.Display();
                 }
                 FSC.Disable();
                 Kernel.ShutdownPC();
             }
             public static void RenderWindow(Window window, int tilecount, int tile)
             {
                 int xw = ScreenWidth / tilecount;
                 int yh = ScreenHeight - DockSize;
                 FSC.DrawRectangle(Cursor1, xw * tile, 0, xw, yh);
                 FSC.DrawFilledRectangle(Cursor1, xw * tile, 0, xw, Font.Height + 10);
                 FSC.DrawString(window.Title, Font, Cursor0, xw * tile + 5, 5);
             } 
             public static void RenderDock()
             {
                 int docky = ScreenHeight - DockSize;
                 FSC.DrawFilledRectangle(Dock0, 0, docky, ScreenWidth, DockSize);
                 FSC.DrawLine(Dock1, 0, docky, 0, ScreenWidth);
                 FSC.DrawString("This is Dock", PCScreenFont.Default, Cursor0, 10, docky + 10);
             }
         }
      }

`Window` class contains nothing but window title as get&set property

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev Kit after my latest pull request

EDIT: forgot to mention, i use vmware workstaion pro 16

**Comment by JsphA** [comment]
You must tell the garbage collector to collect memory every so often, otherwise Cosmos will run out of memory:
`Cosmos.Core.Memory.Heap.Collect()`

**Comment by LoxyMono** [comment]
Cosmos will run out of memory eventually, due to memory leaks, even with Heap.Collect

**Comment by AsertCreator** [comment]
oh, will `Cosmos.Core.Memory.Heap.Collect()` slow down cosmos? its single-threaded and requires more cpu time to collect garbage

**Comment by LoxyMono** [comment]
I've run it every frame before and i still do, it probably wont affect _much_, but it might be best to do it with a timer

**Comment by zarlo** [comment]
> oh, will `Cosmos.Core.Memory.Heap.Collect()` slow down cosmos? its single-threaded and requires more cpu time to collect garbage

even with muilt-threaded it would still slow things down as it would need to make a lock

**Comment by AsertCreator** [comment]
so i almost fully rewrote my code and it become 2x faster, and it runs a lot longe. cosmos crash still a bug, i will not close this issue

**Comment by LoxyMono** [comment]
well, i'm pretty sure this is a well known issue, just saying. but glad it runs longer and faster!

**Comment by AsertCreator** [comment]
well CGS doesnt even run, when i try to run `FullScreenCanvas.GetFullScreenCanvas` vmware reports a cpu error and vs reports a nullreferenceexception at some address

**Comment by zarlo** [comment]
try removeing ```FSC.Mode = FSC.AvailableModes[4];```
