### ISSUE TITLE
MSB6006	"IL2CPU.exe" exited with code -2147450730.	

### ISSUE THREAD

**Issue by TheMrRedstone** [CosmosOS/Cosmos#2374]
I keep geetting the error MSB6006 "IL2CPU.exe" exited with code -2147450730. in my vs console so anyone know how to fix it?

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"IL2CPU.exe" exited with code -2147450730.	Test OS	C:\Users\Computer\.nuget\packages\cosmos.build\0.1.0-localbuild20220209054635\build\Cosmos.Build.targets	175

**Comment by TheMrRedstone** [comment]
Figured Out Issue

**Comment by lfpu** [comment]
> Figured Out Issue

hello, i'm gettin the same issue, so  how to fixed it ?

**Comment by HazelNutHoney** [comment]
> > Figured Out Issue
> 
> hello, i'm gettin the same issue, so  how to fixed it ?

Hey! This was a few years ago when I got the error and then figured out how to fix it and I sadly do not remember how I fixed it because it was a few years ago. I should have posted the solution to fixing it but I didn't think so for some reason so I am sorry in advance.

- Hazel
