### ISSUE TITLE
more errors

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2377]
I update Visual Studio 2019 to 2022, and reinstall DevKit.
And i got soooooooome errors.

Code:
`using System;
using sus = Cosmos.System;
using System.Drawing;

namespace GraphicTest
{
    public class Kernel : sus.Kernel
    {
        public static Canvas canvas;
        public static bool iswindow;
        public static bool isrc;
        public static int memsec;
        public static int memX;
        public static int memY;

        private readonly Bitmap bitmap = new Bitmap(10, 10,
                new byte[] { 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255,
                    23, 59, 88, 255, 0, 255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255, 23, 59, 88, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 23, 59, 88, 255, 153, 57, 12, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 0, 255, 243, 255, 153, 57, 12, 255, 23, 59, 88, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243,
                    255, 0, 255, 243, 255, 0, 255, 243, 255, 72, 72, 72, 255, 72, 72, 72, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0,
                    255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 72, 72,
                    72, 255, 72, 72, 72, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 10, 66, 148, 255, 10, 66, 148, 255,
                    10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255,
                    243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148, 255, 10, 66, 148,
                    255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255,
                    0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, 0, 255, 243, 255, }, ColorDepth.ColorDepth32);

        protected override void BeforeRun()
        {
            memsec = 61;
            iswindow = false;
            Console.WriteLine("KoTOS booted successfully, BUT IF YOU SEE THIS, OS BOOTED UNCORRECTLY!");
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(640, 480, ColorDepth.ColorDepth32));
            sus.MouseManager.ScreenHeight = 480;
            sus.MouseManager.ScreenWidth = 640;
            sus.MouseManager.X = 320;
            sus.MouseManager.Y = 240;
        }
        public static bool CheackClick(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Left)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        public static bool CheackClickRight(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Right)
                    {
                        memX = (int)sus.MouseManager.X;
                        memY = (int)sus.MouseManager.Y;
                        return true;
                    }
                }
            }
            return false;
        }
        protected override void Run()
        {
            try
            {
                canvas.Clear(Color.RoyalBlue);
                Pen pen = new Pen(Color.White);
                var X = Cosmos.System.MouseManager.X;
                var Y = Cosmos.System.MouseManager.Y;
                int mont;
                mont = DateTime.Now.Month;
                string montt = "";
                switch (mont)
                {
                    case 01:
                        montt = "January";
                        break;
                    case 02:
                        montt = "February";
                        break;
                    case 03:
                        montt = "March";
                        break;
                    case 04:
                        montt = "April";
                        break;
                    case 05:
                        montt = "May";
                        break;
                    case 06:
                        montt = "June";
                        break;
                    case 07:
                        montt = "July";
                        break;
                    case 08:
                        montt = "August";
                        break;
                    case 09:
                        montt = "September :(";
                        break;
                    case 10:
                        montt = "October";
                        break;
                    case 11:
                        montt = "November";
                        break;
                    case 12:
                        montt = "December";
                        break;
                }
                if (CheackClick(615, 5, 20, 20))
                {
                    if (iswindow == false)
                    {
                        iswindow = true;
                    }
                }
                if (CheackClickRight(615, 5, 20, 20))
                {
                    if(iswindow == true)
                    {
                        iswindow = false;
                    }
                }
                if (CheackClick(505, 195, 30, 30))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Shutdown();
                    }
                }
                if (CheackClick(540, 195, 30, 30))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Reboot();
                    }
                }
                if (CheackClickRight(0,30,640,450))
                {
                    if (isrc == true)
                    {
                        isrc = false;
                    }
                }
                if (CheackClickRight(0, 30, 640, 450))
                {
                    if (isrc == false)
                    {
                        isrc = true;
                    }
                }
                if (CheackClick(530, 410, 90, 90) == true)
                {
                    canvas.Disable();
                    Console.Clear();
                    Console.WriteLine("Enter 'help' for help!");
                    while (true)
                    {
                        var txt = Console.ReadLine();
                        switch (txt)
                        {
                            case "exit":
                                sus.Power.Shutdown();
                                break;
                            case "help":
                                Console.WriteLine("cls - clear the console");
                                Console.WriteLine("calc - calculator");
                                Console.WriteLine("time - now time");
                                Console.WriteLine("help - help");
                                Console.WriteLine("proc - find the percentage of the number");
                                Console.WriteLine("reboot - reboot");
                                Console.WriteLine("exit - shutdown");
                                Console.WriteLine("settings - settings");
                                Console.WriteLine("standby - standby mode");
                                Console.WriteLine("3d - Look at 3D Images!");
                                Console.WriteLine("images - Look at 2D Images!");
                                Console.WriteLine("game - play game 'guess the number'");
                                Console.WriteLine("mtest - mathe test!");
                                Console.WriteLine("mel - lesson the music");
                                Console.WriteLine("graph - graphics mode");
                                Console.WriteLine("");
                                break;
                            /*case "disk":
                                Console.WriteLine(sus.FileSystem.VFS.VFSManager.GetTotalSize("0:\\").ToString() + " / " + sus.FileSystem.VFS.VFSManager.GetTotalFreeSpace("0:\\").ToString());
                                break;*/
                            case "graph":
                                sus.Power.Reboot();
                                break;
                            case "reboot":
                                sus.Power.Reboot();
                                break;
                            case "cls":
                                Console.Clear();
                                break;
                            case "calc":
                                double a, b;

                                Console.WriteLine("");
                                try
                                {
                                    Console.Write("Enter first number: ");

                                    a = double.Parse(Console.ReadLine());
                                    Console.WriteLine("");
                                    Console.Write("Enter second number: ");

                                    b = double.Parse(Console.ReadLine());
                                }
                                catch
                                {
                                    Console.WriteLine("You are an idiot?");
                                    break;
                                }
                                Console.WriteLine("Choose an option:");
                                Console.WriteLine("a - add");
                                Console.WriteLine("s - subtract");
                                Console.WriteLine("m - multiply");
                                Console.WriteLine("d - devide");
                                Console.Write("You option:");

                                switch (Console.ReadLine())
                                {
                                    case "a":
                                        Console.WriteLine(a + b);
                                        Console.WriteLine("");
                                        break;
                                    case "s":
                                        Console.WriteLine(a - b);
                                        Console.WriteLine("");
                                        break;
                                    case "m":
                                        Console.WriteLine(a * b);
                                        Console.WriteLine("");
                                        break;
                                    case "d":
                                        Console.WriteLine(a / b);
                                        Console.WriteLine("");
                                        break;
                                    default:
                                        Console.WriteLine("ERROR: UNKNOWN OPTION");
                                        Console.WriteLine("");
                                        break;
                                }
                                break;
                            case "time":
                                Console.WriteLine(DateTime.Now);
                                Console.WriteLine("");
                                break;
                            case "proc":
                                double sd, sf;
                                Console.WriteLine("");
                                Console.WriteLine("You can find the percentage of the number");
                                Console.WriteLine("");
                                try
                                {
                                    Console.Write("Enter percentages: ");
                                    sd = double.Parse(Console.ReadLine());
                                    Console.Write("Enter number: ");
                                    sf = double.Parse(Console.ReadLine());
                                }
                                catch
                                {
                                    Console.WriteLine("You are an idiot?");
                                    break;
                                }
                                double r = sf / 100;
                                double res = r * sd;
                                Console.WriteLine("Result: " + res);
                                break;
                            case "settings":
                                Console.WriteLine("theme - set the existing color set");
                                Console.WriteLine("bg - set background color");
                                Console.WriteLine("tc - set the text color");
                                string setttt = Console.ReadLine();
                                switch (setttt)
                                {
                                    case "theme":
                                        Console.WriteLine("Choose a theme: dark, light, mc (multicolored), sd (standart), flopoos(author's favorite theme)");
                                        Console.WriteLine("");
                                        Console.Write("You choose: ");
                                        string cs = Console.ReadLine();
                                        switch (cs)
                                        {
                                            case "dark":
                                                Console.ForegroundColor = ConsoleColor.Gray;
                                                Console.BackgroundColor = ConsoleColor.Black;
                                                Console.Clear();
                                                break;
                                            case "light":
                                                Console.ForegroundColor = ConsoleColor.White;
                                                Console.BackgroundColor = ConsoleColor.Gray;
                                                Console.Clear();
                                                break;
                                            case "mc":
                                                Console.ForegroundColor = ConsoleColor.DarkBlue;
                                                Console.BackgroundColor = ConsoleColor.Green;
                                                Console.Clear();
                                                break;
                                            case "bios":
                                                Console.ResetColor();
                                                Console.BackgroundColor = ConsoleColor.Blue;
                                                Console.Clear();
                                                break;
                                            case "flopoos":
                                                Console.ResetColor();
                                                Console.BackgroundColor = ConsoleColor.Black;
                                                Console.ForegroundColor = ConsoleColor.DarkRed;
                                                Console.Clear();
                                                break;
                                        }
                                        break;
                                    case "bg":
                                        Console.WriteLine("please set the bg color... (g - green, r - red, b - blue, bl - black, y - orange, c - cyan, m - magenta, gr - gray)");
                                        string bgc = Console.ReadLine();
                                        if (bgc == "g")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Green;
                                            Console.Clear();
                                        }
                                        if (bgc == "r")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Red;
                                            Console.Clear();
                                        }
                                        if (bgc == "b")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Blue;
                                            Console.Clear();
                                        }
                                        if (bgc == "bl")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Black;
                                            Console.Clear();
                                        }
                                        if (bgc == "y")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Yellow;
                                            Console.Clear();
                                        }
                                        if (bgc == "c")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Cyan;
                                            Console.Clear();
                                        }
                                        if (bgc == "m")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Magenta;
                                            Console.Clear();
                                        }
                                        if (bgc == "gr")
                                        {
                                            Console.BackgroundColor = ConsoleColor.Gray;
                                            Console.Clear();
                                        }
                                        break;
                                    case "tc":
                                        Console.WriteLine("Please, set the text color... (g - green, r - red, b - blue, w - white, y - yellow, c - cyan, dg - dark green, m - magenta, gr - gray)");
                                        string clr = Console.ReadLine();
                                        if (clr == "g")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Green;
                                            Console.Clear();
                                        }
                                        if (clr == "r")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Red;
                                            Console.Clear();
                                        }
                                        if (clr == "b")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Blue;
                                            Console.Clear();
                                        }
                                        if (clr == "w")
                                        {
                                            Console.ForegroundColor = ConsoleColor.White;
                                            Console.Clear();
                                        }
                                        if (clr == "y")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Yellow;
                                            Console.Clear();
                                        }
                                        if (clr == "c")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Cyan;
                                            Console.Clear();
                                        }
                                        if (clr == "dg")
                                        {
                                            Console.ForegroundColor = ConsoleColor.DarkGreen;
                                            Console.Clear();
                                        }
                                        if (clr == "m")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Magenta;
                                            Console.Clear();
                                        }
                                        if (clr == "gr")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Gray;
                                            Console.Clear();
                                        }
                                        if (clr == "bl")
                                        {
                                            Console.ForegroundColor = ConsoleColor.Black;
                                            Console.Clear();
                                        }
                                        if (clr == "drr")
                                        {
                                            Console.ForegroundColor = ConsoleColor.DarkRed;
                                            Console.Clear();
                                        }
                                        break;
                                }
                                break;
                            case "standby":
                                Console.BackgroundColor = ConsoleColor.Black;
                                Console.ForegroundColor = ConsoleColor.Gray;
                                Console.Clear();
                                Console.ReadKey();
                                Console.ResetColor();
                                Console.BackgroundColor = ConsoleColor.Blue;
                                Console.Clear();
                                break;
                            case "images":
                                Console.WriteLine("");
                                Console.WriteLine("1. Tree");
                                Console.WriteLine("2. Sunrice");
                                Console.WriteLine("3. Bunny");
                                Console.WriteLine("4. Cat");
                                Console.WriteLine("5. Beach");
                                Console.WriteLine("");
                                Console.Write("Enter number of image: ");
                                string ImgCh = Console.ReadLine();
                                switch (ImgCh)
                                {
                                    case "1":
                                        Console.WriteLine("");
                                        Console.WriteLine("     @@@     ");
                                        Console.WriteLine("    @@@@@    ");
                                        Console.WriteLine("   @@@@@@@   ");
                                        Console.WriteLine("  @@@@@@@@@  ");
                                        Console.WriteLine("   @@@@@@@   ");
                                        Console.WriteLine("     ###  __ ");
                                        Console.WriteLine("  ___### /   ");
                                        Console.WriteLine("     ###/    ");
                                        Console.WriteLine("   --###     ");
                                        Console.WriteLine("     ###     ");
                                        Console.WriteLine("#############");
                                        Console.WriteLine("#############");
                                        Console.WriteLine("");
                                        break;
                                    case "2":
                                        Console.WriteLine("");
                                        Console.WriteLine("...,,,:::+++***???##?***+++:::,,,...");
                                        Console.WriteLine("..,,:::+++***???S####S???***+++:::,,..");
                                        Console.WriteLine("..,,::+++***???S##@@##S???***+++::,,..");
                                        Console.WriteLine("..,,::++***???SS##@@##SS???***++::,,..");
                                        Console.WriteLine("..,,::++**???%SS##@@##SS%???**++::,,..");
                                        Console.WriteLine("..,,::++**??%%SS##@@##SS%%??**++::,,..");
                                        Console.WriteLine("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
                                        Console.WriteLine("");
                                        break;
                                    case "3":
                                        Console.WriteLine("");
                                        Console.WriteLine("  /]__/]");
                                        Console.WriteLine(" ( @  @)");
                                        Console.WriteLine(" (   ^ )");
                                        Console.WriteLine(" (  >##)");
                                        Console.WriteLine(" (_____)");
                                        Console.WriteLine("  !   !");
                                        Console.WriteLine("");
                                        break;
                                    case "4":
                                        Console.WriteLine("");
                                        Console.WriteLine("            /]___/]");
                                        Console.WriteLine("     ______/ @  @ |");
                                        Console.WriteLine("    /      ____^__|");
                                        Console.WriteLine(" ---|  __ /        ");
                                        Console.WriteLine("    |_| |_|        ");
                                        Console.WriteLine("");
                                        break;
                                    case "5":
                                        Console.WriteLine("");
                                        Console.WriteLine("     =#@@@@/@@= ");
                                        Console.WriteLine("           |    ");
                                        Console.WriteLine("           /    ");
                                        Console.WriteLine("__________/_____");
                                        Console.WriteLine("_________|______");
                                        Console.WriteLine("");
                                        break;
                                    default:
                                        Console.WriteLine("Unknown Image");
                                        break;
                                }
                                break;
                            case "3d":
                                Console.WriteLine("");
                                Console.WriteLine("1. 3D Cube");
                                Console.WriteLine("2. 3D Letter 'T'");
                                Console.WriteLine("");
                                Console.Write("Enter number of image: ");
                                string treeD = Console.ReadLine();
                                switch (treeD)
                                {
                                    case "1":
                                        Console.WriteLine("");
                                        Console.WriteLine("     ___________ ");
                                        Console.WriteLine("    /         / | ");
                                        Console.WriteLine("   /         /  | ");
                                        Console.WriteLine("  /         /   | ");
                                        Console.WriteLine(" -----------    | ");
                                        Console.WriteLine(" |         |    / ");
                                        Console.WriteLine(" |         |   / ");
                                        Console.WriteLine(" |         |  / ");
                                        Console.WriteLine(" ------------- ");
                                        Console.WriteLine("");
                                        break;
                                    case "2":
                                        Console.WriteLine("");
                                        Console.WriteLine("  _________");
                                        Console.WriteLine(" /________/|");
                                        Console.WriteLine(" |________|/ ");
                                        Console.WriteLine("   | | |");
                                        Console.WriteLine("   | | |");
                                        Console.WriteLine("   | | |");
                                        Console.WriteLine("   | | |");
                                        Console.WriteLine("   | | |");
                                        Console.WriteLine("   |_|/");
                                        Console.WriteLine("");
                                        break;
                                    default:
                                        Console.WriteLine("Unknown 3D Image");
                                        break;
                                }
                                break;
                            case "game":
                                Console.Write("Choose mode (1. easy 2. hard) enter number: ");
                                string chs = Console.ReadLine();
                                switch (chs)
                                {
                                    case "1":
                                        Random rand = new Random();
                                        int ina = rand.Next(25);
                                        Console.WriteLine("I made a number from 0 to 25, find this number!");

                                        while (true)
                                        {
                                            if (ina < 15) Console.WriteLine("number < 15");
                                            else Console.WriteLine("number > or = 15");

                                            try
                                            {
                                                int x = Convert.ToInt32(Console.ReadLine());
                                                if (ina == x)
                                                {
                                                    Console.WriteLine("Good! You Win!");
                                                    break;
                                                }
                                                else
                                                {
                                                    Console.WriteLine("No!");
                                                    continue;
                                                }
                                            }
                                            catch
                                            {
                                                Console.WriteLine("You are an idiot?");
                                            }

                                        }
                                        break;
                                    case "2":
                                        Random rando = new Random();
                                        int inaa = rando.Next(75);
                                        Console.WriteLine("I made a number from 0 to 75, find this number!");

                                        while (true)
                                        {
                                            if (inaa < 35) Console.WriteLine("number < 35");
                                            else Console.WriteLine("number > or = 35");
                                            try
                                            {
                                                int x = Convert.ToInt32(Console.ReadLine());
                                                if (inaa == x)
                                                {
                                                    Console.WriteLine("Good! You Win!");
                                                    break;
                                                }
                                                else
                                                {
                                                    Console.WriteLine("No!");
                                                    continue;
                                                }
                                            }
                                            catch
                                            {
                                                Console.WriteLine("You are an idiot?");
                                            }
                                        }
                                        break;
                                    default:
                                        Console.WriteLine("Unknown Mode!");
                                        break;
                                }
                                break;
                            case "mtest":
                                try
                                {
                                    Random shoo = new Random();
                                    Random sho = new Random();
                                    int sdf = shoo.Next(9999);
                                    int fwt = sho.Next(8346);
                                    int answer = sdf + fwt;
                                    Console.Write("" + sdf + " + " + fwt + " = ");
                                    while (true)
                                    {
                                        string ya = Console.ReadLine();
                                        int yaa = Convert.ToInt32(ya);
                                        if (yaa == answer)
                                        {
                                            Console.WriteLine("Good!");
                                            break;
                                        }
                                        else
                                        {
                                            Console.WriteLine("Wrong!");
                                            continue;
                                        }
                                    }
                                }
                                catch (Exception)
                                {
                                    Console.WriteLine("ERROR!!!");
                                    break;
                                }
                                break;
                            case "mel":
                                Console.WriteLine("Do you want lesson the music? TIP: IF YOU DONT HEAR THE MUSIC, CHECK BIOS FOR FUNCTION 'ENABLE BEEP' OR 'ENABLE SPEAKER' OR etc... IF LAST HINT DONT HELP, CHECK YOU PC FOR HAS SPEAKER, IF YOU PC DONT HAVE A SPEAKER FORGET THIS COMMAND :( SORRY!");
                                Console.WriteLine("Choose Music: 1 - Happy Birthday 2 - Mission Impossible 3 - mobilnik");
                                switch (Console.ReadKey(true).Key)
                                {
                                    case ConsoleKey.D1:
                                        melody.mel.HappyBirthday();
                                        break;
                                    case ConsoleKey.D2:
                                        melody.mel.MissionImpossible();
                                        break;
                                    case ConsoleKey.D3:
                                        melody.mel.mobilnik();
                                        break;
                                    default:
                                        break;
                                }
                                break;
                            default:
                                Console.WriteLine("Error. Unknown Command");
                                sus.PCSpeaker.Beep();
                                break;
                        }
                    }
                }

                if (iswindow == true)
                {
                    canvas.DrawFilledRectangle(new Pen(Color.SkyBlue), new sus.Graphics.Point(500, 30), 140, 200);
                    canvas.DrawFilledRectangle(new Pen(Color.Red), new sus.Graphics.Point(505, 195), 30, 30);
                    canvas.DrawFilledRectangle(new Pen(Color.Orange), new sus.Graphics.Point(540, 195), 30, 30);
                }

                if (isrc == true)
                {
                    canvas.DrawImage(bitmap,new sus.Graphics.Point(memX, memY));
                    //canvas.DrawFilledRectangle(new Pen(Color.White), new sus.Graphics.Point(memX, memY), 75, 100);
                }

                canvas.DrawFilledRectangle(new Pen(Color.SteelBlue), new sus.Graphics.Point(0, 0), 640, 30);

                canvas.DrawFilledCircle(new Pen(Color.DeepSkyBlue), new sus.Graphics.Point(625, 15), 10);

                canvas.DrawFilledCircle(new Pen(Color.Black), new sus.Graphics.Point(560, 440), 30);

                canvas.DrawLine(new Pen(Color.DarkGray), 580, 440, 545, 420);
                canvas.DrawLine(new Pen(Color.DarkGray), 580, 440, 545, 460);

                if (memsec != DateTime.Now.Second)
                {
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Hour.ToString() + ":" + DateTime.Now.Minute.ToString() + ":" + DateTime.Now.Second.ToString(), 5, 1, 63);
                    txtxtx.FontDrawer.WriteText(montt, 5, 10, 36);
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Day.ToString() + "th " + DateTime.Now.Year.ToString(), 5, 19, 36);
                }

                canvas.DrawLine(pen, new sus.Graphics.Point((int)X + 10, (int)Y + 10), new sus.Graphics.Point((int)X, (int)Y));
                canvas.DrawLine(pen, new sus.Graphics.Point((int)X, (int)Y), new sus.Graphics.Point((int)X, (int)Y + 6));
                canvas.DrawLine(pen, new sus.Graphics.Point((int)X, (int)Y), new sus.Graphics.Point((int)X + 6, (int)Y));

                if (sus.MouseManager.MouseState == sus.MouseState.Right)
                {
                    isrc = true;
                }
                if (sus.MouseManager.MouseState == sus.MouseState.Left)
                {
                    isrc = false;
                }

                canvas.Display();
            }
            catch (Exception e)
            {
                sus.Power.Shutdown();
            }
        }
    }
}`

Errors:
![image](https://user-images.githubusercontent.com/79642857/183314948-b15db3aa-582c-4870-aaca-0dd50a64ae69.png)
![image](https://user-images.githubusercontent.com/79642857/183314956-1ab16394-3e1e-4826-a334-9c92256b61fe.png)

**Comment by zarlo** [comment]
did you update the nuget packages?

**Comment by koteProgrammist** [comment]
Thanks! This is work now!
