### ISSUE TITLE
Add Xaml Design Support

### ISSUE THREAD

**Issue by CSharpChase** [CosmosOS/Cosmos#2380]
Add support for xaml design in cosmos. It would help with the GUI framework.

**Comment by terminal-cs** [comment]
Cosmos does not have UI support at all, nor application support (with the exception of stuff other users have made)
Call is way too high level for an osdev kit, you should try making it yourself, the point of cosmos isn't for making dotnet apps

**Comment by MishaTY** [comment]
XAML is too complex and is out of the scope for this project.

**Comment by zarlo** [comment]
this is some thing you would make in its own library
