### ISSUE TITLE
Get a error when trying to build project

### ISSUE THREAD

**Issue by MasterYuan418** [CosmosOS/Cosmos#2383]
Have you checked Github Issues for similar errors?
Yes

**Exception**
Post the exception returned by Visual Studio
`NETSDK1045 The current .NET SDK does not support targeting .NET 6.0. Please target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0`
** VS Output Logs **
Post the entire output log given by Visual Studio for the build

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.

**Screenshots**
![图片](https://user-images.githubusercontent.com/58651976/185521665-d0dd0875-e467-44c6-b1ec-c7fd21c4f30c.png)

**Context**
Before posting please confirm that the following are in order
[√] Both Cosmos VS Extensions are installed
[√] In the NuGet Package Manager "Include prerelease" is selected
[√] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[√] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by zarlo** [comment]
if you just installed the dev kit you will need yo update your old .csproj you use .net 6

**Comment by MasterYuan418** [comment]
> 

Thanks, that solve my problem. :)
