### ISSUE TITLE
The specified task executable location is invalid

### ISSUE THREAD

**Issue by Marko21552** [CosmosOS/Cosmos#2389]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building and debugging

#### Expected Behaviour - What do you think should happen?
Build and run without any error

#### Actual Behaviour - What unexpectedly happens?
I get an error that says "The specified task executable location '\pathidontknow\IL2CPU.exe' is invalid." Never seen this before.

#### Reproduction - How did you get this error to appear?
It just happens when I build and run

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by Marko21552** [comment]
Finally found out why the error happens, the folder "Cosmos User Kit" in AppData\Roaming is missing, still don't know how to fix it

**Comment by zarlo** [comment]
you need to install cosmos in the default install path

**Comment by Marko21552** [comment]
i found out before you commented but now i get another eror: IL2CPU.exe exited with code -2147450730

**Comment by Marko21552** [comment]
making another issue with another error with the name: IL2CPU.exe exited with code -2147450730 so go for that one if ya wanna hear more
