### ISSUE TITLE
IL2CPU.exe exited with code -2147450730

### ISSUE THREAD

**Issue by Marko21552** [CosmosOS/Cosmos#2394]
Have you checked Github Issues for similar errors?
a day ago i did but i only read a few pages and i couldn't find anything.

**Exception**
Post the exception returned by Visual Studio
IL2CPU.exe exited with code -2147450730

** VS Output Logs
IL2CPU.exe exited with code -2147450730

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
It just happens.

**Screenshots**
Making this issue on another pc that doesn't support vs 2022 or cosmos so no screenshots.

**Context**
Before posting please confirm that the following are in order
[y] Both Cosmos VS Extensions are installed
[idk] In the NuGet Package Manager "Include prerelease" is selected
[idk] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[y] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful
I dunno why but whenever i build my Cosmos project "CosmOS (in development)" it just says IL2CPU.exe exited with code -2147450730. My previous error was specified task executable location /pathidk/IL2CPU.exe is invalid and now when i fixed that this happend no matter how many times i reinstall Cosmos so can anybody help?

**Comment by GoldenretriverYT** [comment]
Not enough information. Post the **FULL** output log.

> [idk] In the NuGet Package Manager "Include prerelease" is selected
> [idk] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'

You should check this **before** creating an issue.
