### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'Cosmos.IL2CPU.GCImplementationRefs' threw an exception

### ISSUE THREAD

**Issue by Marko21552** [CosmosOS/Cosmos#2395]
Have you checked Github Issues for similar errors?
like i said, a day ago but i only checked a few pages before  went to bed so no

**Exception**
Post the exception returned by Visual Studio
System.TypeInitializationException: The type initializer for 'Cosmos.IL2CPU.GCImplementationRefs' threw an exception

** VS Output Logs **
Post the entire output log given by Visual Studio for the build
System.TypeInitializationException: The type initializer for 'Cosmos.IL2CPU.GCImplementationRefs' threw an exception visual studio 2019

**To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Hey, it just happens.

**Screenshots**
Dunno how to shoot screenshots in Windows 11 so no

**Context**
Before posting please confirm that the following are in order
[y] Both Cosmos VS Extensions are installed
[idk] In the NuGet Package Manager "Include prerelease" is selected
[idk] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[y] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
I try compiling my project as  soon as i made it and this error appeared: System.TypeInitializationException: The type initializer for 'Cosmos.IL2CPU.GCImplementationRefs' threw an exception. I hope there are any people who understand this and can fix this.

**Comment by zarlo** [comment]
are you running a user kit or dev kit?

**Comment by Marko21552** [comment]
user kit

**Comment by GoldenretriverYT** [comment]
As a first troubleshooting step I would recommend using the devkit.
The user kit is incredibly outdated.

**Comment by Marko21552** [comment]
ok lemme try closing for now

**Comment by Marko21552** [comment]
it didn't even work at all

**Comment by quajak** [comment]
Please provide more details
