### ISSUE TITLE
USB Stick stuck on Creating ATA IOGroup

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#240]
Also, the whole boot process is slower than on Vmware. Seem to be like #129 and #113 . USB 3.0, AHCI. UEFI Bios. Flash drives are way slower than VmWare. A Fat32 formated 128 mb flash. Used newest UserKit, when building was been completed, VS Crashed.

**Comment by mterwoord** [comment]
So, you're trying to boot on real hardware, or?

Booting on real hardware is still untested at best..

**Comment by lukaandjelkovic** [comment]
Yes, real hardware. Just to know, pretty new laptop with new hardware.

**Comment by lukaandjelkovic** [comment]
I think is booting the OS is highest priority. What OS is OS which cant boot?

**Comment by ARMmaster17** [comment]
@lukaandjelkovic You have to note that Cosmos is still "experimental". Nothing can be proven to work 100% yet.

**Comment by mterwoord** [comment]
Besides that, our main focus is specialized operating system kernels (specific server roles, hpc related stuff, etc) with the main targets of VM guests (currently VMware working, others will be done as well)

That being said, we definitely want to get running on normal hardware (although, probably with a specific set of hardware) but that's a bit down the road.

**Comment by valentinbreiz** [comment]
@lukaandjelkovic https://github.com/CosmosOS/Cosmos/wiki/Fix-Stuck-on-Creating-ATA-IOGroup works for me

**Comment by KingLuigi4932** [comment]
@lukaandjelkovic Will be fixed with the AHCI Controller Driver :)
#763

**Comment by KingLuigi4932** [comment]
For now, we can cancel ATA Initialization when it doesn't exist ;)

**Comment by frenzibyte** [comment]
I'm not sure whether this issue has been checked recently, nor do I recall whether any of my PRs fixed this, I'm guessing #822 was supposed to cancel ATA initialization if it doesn't "exist", but not sure whether it fixes this tracked issue.

@valentinbreiz ping, for visibility if you aren't aware of this already.

**Comment by JuliusCaesar12** [comment]
My os seems to run faster on real hardware, but that's probably just me...

**Comment by Arawn-Davies** [comment]
128mb flash, are you sure the stick is USB 2.0 EHCI? Modern 128mb sticks sound rare and I'd expect 128 to be 1.x OHCI instead.
