### ISSUE TITLE
Hi, I want to display a bitmap image on my OS but I can't please help me

### ISSUE THREAD

**Issue by AmjadAwor0** [CosmosOS/Cosmos#2402]
Hi, I want to display a bitmap image on my OS but I can't please help me

**Comment by ascpixi** [comment]
We can't really help you unless you supply the code that's causing the issue... :/
Here's an example snippet on how to display a bitmap:
```cs
canvas.DrawImage(bitmap, new Point(100, 150));
canvas.Display();
```
...where `bitmap` is a `Bitmap` object. You can create such an object from a BMP file by reading the bytes of the file using the `Bitmap(byte[])` constructor.

**Comment by AmjadAwor0** [comment]
> We can't really help you unless you supply the code snippet that's causing the issue... :/ Here's an example on how to display a bitmap:
> 
> ```cs
> canvas.DrawImage(bitmap, new Point(100, 150));
> canvas.Display();
> ```
> 
> ...where `bitmap` is a `Bitmap` object. You can create such an object from a BMP file by reading the bytes of the file using the [`Bitmap(byte[])`](https://cosmosos.github.io/api/Cosmos.System.Graphics.Bitmap.html#Cosmos_System_Graphics_Bitmap__ctor_System_Byte___) constructor.

Hi, Thank you for your reply.
but I have a bmp image called wallpaper.bmp but I can't load it

**Comment by ascpixi** [comment]
The way you can load the file is either by packaging the file into the ISO file and using a `CosmosVFS` object to read from the disc, or by directly appending the file into the kernel binary (easier, but not recommended). To do that:
```cs
[ManifestResourceStream(ResourceName = "(name of your os).MyImage.bmp")]
readonly static byte[] bmpBytes;
```
The above snippet will import the file `MyImage.bmp` located at the root of your solution to the kernel binary into the `bmpBytes` array, that you can use to create a `Bitmap` object.

Also, please consider moving this issue to the Discussions section, as it'll help organize everything, thanks! ^^

**Comment by AmjadAwor0** [comment]
> الطريقة التي يمكنك بها تحميل الملف هي إما عن طريق تعبئة الملف في ملف ISO واستخدام كائن للقراءة من القرص ، أو عن طريق إلحاق الملف مباشرة في ثنائي kernel (أسهل ، ولكن لا ينصح به ؛ سيظل الملف عالقا في الذاكرة إلى الأبد). لتضمين ملف داخل kernel، يمكنك القيام بما يلي:`CosmosVFS`
> 
> ```cs
> [ManifestResourceStream(ResourceName = "(name of your os).MyImage.bmp")]
> readonly static byte[] bmpBytes;
> ```
> 
> سيقوم المقتطف أعلاه باستيراد الملف الموجود في جذر الحل الخاص بك إلى ثنائي kernel في الصفيف ، والذي يمكنك استخدامه لإنشاء كائن.`MyImage.bmp``bmpBytes``Bitmap`
> 
> أيضا ، يرجى التفكير في نقل هذه المشكلة إلى قسم المناقشات ، لأنها ستساعد في تنظيم كل شيء ، شكرا! ^^

Can you record a video for me?
if you can't it's ok

**Comment by AmjadAwor0** [comment]
I will try it
Thank you
