### ISSUE TITLE
1:/ is not exists

### ISSUE THREAD

**Issue by dev-alphagot** [CosmosOS/Cosmos#2403]
#### Area of Cosmos - What area of Cosmos are we dealing with?
ISO

#### Expected Behaviour - What do you think that should happen?
1:/ exists

#### Actual Behaviour - What unexpectedly happens?
1:/ is not exists and 0:/ is HDD

#### Reproduction - How did you get this error to appear?
I tried to access my ISO's file but it failed

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit

**Comment by AsertCreator** [comment]
i have the same issue, whenever i try to access 1:/ os says its doesnt exist

**Comment by MishaTY** [comment]
Your dvd drive controller is probably sata, and only ide is supported currently.
