### ISSUE TITLE
ISO Build error

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2412]
![image](https://user-images.githubusercontent.com/79642857/190896812-affca04b-a428-4944-821e-b8d0f3587989.png)

I build iso image and got this error

**Comment by MishaTY** [comment]
Try disabling the debugger

**Comment by koteProgrammist** [comment]
> Try disabling the debugger

Debugger was disabled

**Comment by Kiirx** [comment]
the iso should still be generated

**Comment by koteProgrammist** [comment]
> the iso should still be generated

how?

**Comment by AsertCreator** [comment]
build iso without running. you can find it in "build" menu
