### ISSUE TITLE
Is there a way to make it so Cosmos can automatically detect if the system unexpectedly crashes?

### ISSUE THREAD

**Issue by AudioTore** [CosmosOS/Cosmos#2425]
I'm building my own OS. And there are times where I do something and the system just crashes. I was thinking of a maybe  sort of
blue screen of death (BSOD) kind of thing like windows. Is there a way to execute something like that when this does happen?

**Comment by zarlo** [comment]
yes have a look at https://github.com/aura-systems/Aura-Operating-System/blob/master/SRC/Aura_Plugs/INTs.cs

**Comment by terminal-cs** [comment]
What happens if the kernel is not stopped, for instance, if the error is just shown in a dialog box

**Comment by zarlo** [comment]
that would depends on the state its left in (some errors this would be fine but others will make it unusable)

**Comment by Kiirx** [comment]
Errors are not the same as faults, faults has to be taken more seriously, for example a general protection fault, divide by 0 fault and other things, also I dont think triple faults are handled

**Comment by ataberk320** [comment]
can we display an bitmap on the plug
