### ISSUE TITLE
How i install the DevKit?

### ISSUE THREAD

**Issue by GreenSoupDeveloper** [CosmosOS/Cosmos#2432]
**What is the usecase for this plug**
How i install the DevKit?

**Comment by RaphMar2021** [comment]
Requirements : 
Visual Studio 2022 with Extension developement workload.
VMware, QEMU or Hyper-V

Download the Cosmos source, extract it, rename the cosmos folder to Cosmos and use VS2022-install.bat file, Wait until the setup opens and install it like a normal program.

**Comment by GreenSoupDeveloper** [comment]
> Requirements : Visual Studio 2022 with Extension developement workload. VMware, QEMU or Hyper-V
> 
> Download the Cosmos source, extract it, rename the cosmos folder to Cosmos and use VS2022-install.bat file, Wait until the setup opens and install it like a normal program.

oh, Thanks! :)

**Comment by MishaTY** [comment]
Read the documentation.
