### ISSUE TITLE
VTableImpl "Method Not Found"

### ISSUE THREAD

**Issue by TheFocusMan** [CosmosOS/Cosmos#2433]
Sometimes that i run an OS with the framework I Got a proplem with VTableImpl "Method Not Found", when i got the problem it was ESP register with worng type id value, I saw that the proplem happened while the CallVirt op code is runnig

**Comment by quajak** [comment]
Can you post code to reproduce the issue?

**Comment by TheFocusMan** [comment]
[https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.IL2CPU/IL/Callvirt.cs](url)

**Comment by TheFocusMan** [comment]
> Can you post code to reproduce the issue?

The code url: https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.IL2CPU/IL/Callvirt.cs

**Comment by quajak** [comment]
I meant a code sample for a kernel which would cause the issue to occur when running it

**Comment by TheFocusMan** [comment]
> I meant a code sample for a kernel which would cause the issue to occur when running it

The issue is dosent depend on on code sample

**Comment by TheFocusMan** [comment]
[Area: Compiler]

**Comment by GoldenretriverYT** [comment]
> The issue is dosent depend on on code sample

But it has to. Callvirt is a pretty common OpCode and it doesn't happen everytime. I never had it happen to me, you will have to provide a code sample that triggers this error.

**Comment by quajak** [comment]
Yeah, I am assuming you are running into some edge case which we did not think of or some other corruption which only becomes apparent when a callvirt is executed. To debug the issue, I need a case to reproduce it.

**Comment by TheFocusMan** [comment]
> Yeah, I am assuming you are running into some edge case which we did not think of or some other corruption which only becomes apparent when a callvirt is executed. To debug the issue, I need a case to reproduce it.

Ok, Last time i had the issue is On Kernel.Start while Invoking the Run Function it happen, On launcer Qmeu

**Comment by TheFocusMan** [comment]
> You aren't supposed to call the Run method, its automatically executed.

I meant that the problem is when Cosmos.System.Kernel.Start calls Kernel.Run is throw The message "Method Not Found"

**Comment by GoldenretriverYT** [comment]
Oh, whats in your Run method?

**Comment by TheFocusMan** [comment]
> Oh, whats in your Run method?

The method was empty
