### ISSUE TITLE
Visual Studio 2022 with Cosmos UserKit/DevKit

### ISSUE THREAD

**Issue by ZGStuff** [CosmosOS/Cosmos#2437]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio 2022 Support

#### Expected Behaviour - What do you think that should happen?
It SHOULD be able to work!

#### Actual Behaviour - What unexpectedly happens?
Unknown, as I have waited for official support.

#### Reproduction - How did you get this error to appear?
Reproduction is easy, just use Cosmos with VS2022!

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit! I was using the latest version of the COSMOS User Kit.

**Comment by terminal-cs** [comment]
Userkit does not work in vs2022, it was last built when we were using vs2019.

**Comment by ZGStuff** [comment]
ah! OK! just making sure, as VS 2019 isn't downloadable anymore unless you have something else that uses VS 2019 like Unity/Unreal Engine.

**Comment by zarlo** [comment]
you can use the devkit (build from source) that supports vs2022

**Comment by BioShot** [comment]
Tried doesn't work.

**Comment by AsertCreator** [comment]
well... vs2019 is still downloadable, tough it is only downloadble through dev essentials https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by BioShot** [comment]
Ah ok. It still gives me an error like “SWbemLocator class not found”

**Comment by BioShot** [comment]
Some more detail on that:
My system is an 8yr old HP-Phoenix  running an upgraded version of windows 10 pro from windows 7 pro.

**Comment by BioShot** [comment]
> #### Area of Cosmos - What area of Cosmos are we dealing with?
> 
> Visual Studio 2022 Support
> 
> 
> 
> #### Expected Behaviour - What do you think that should happen?
> 
> It SHOULD be able to work!
> 
> 
> 
> #### Actual Behaviour - What unexpectedly happens?
> 
> Unknown, as I have waited for official support.
> 
> 
> 
> #### Reproduction - How did you get this error to appear?
> 
> Reproduction is easy, just use Cosmos with VS2022!
> 
> 
> 
> #### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
> 
> User Kit! I was using the latest version of the COSMOS User Kit.

I've also gotten close to getting it running on vs2022 by building from the dev kit but I have come to a stopping point. Like me, I noticed your drive was different from the c:\ drive in which vs2022's was. In order to build it. Go into the dev kit batch and replace the program files path with your path and change the msbuild path as well and play around with it and see how it goes. If you find a solution I love to hear it!

**Comment by quajak** [comment]
The userkit now works with vs22
