### ISSUE TITLE
ISO9660 filesystem broken

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2438]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem ISO9660

#### Expected Behaviour - What do you think that should happen?
When we put files in the corresponding folder in the project, it should be there on cosmos

#### Actual Behaviour - What unexpectedly happens?
No ISO9660 partitions detected

#### Version - last devkit 18/10/22 (wasnt working with the last userkit)

**Comment by TheFocusMan** [comment]
This is a problem in the heap area that the Mount disk reapitly check the partions and then the Small Heap throw that SMT is null,

Just add this code in `Kernel.BeforeRun` function
`if (HeapSmall.SMT == null)
GCImpletition.Init();`

**Comment by Kiirx** [comment]
Ill try that thank you

**Comment by quajak** [comment]
> Just add this code in `Kernel.BeforeRun` function `if (HeapSmall.SMT == null) GCImplementation.Init();`
> 
> i alredy fixed it but i wait that the creator is merge my PR

Which PR fixes this?

**Comment by TheFocusMan** [comment]
> > Just add this code in `Kernel.BeforeRun` function `if (HeapSmall.SMT == null) GCImplementation.Init();`
> > i alredy fixed it but i wait that the creator is merge my PR
> 
> Which PR fixes this?

PR of remove debug output on boot because this action was corrupting the stack point and the function GCImplementation.Init() was not called

**Comment by quajak** [comment]
I see, thank you. So this is fixed?

**Comment by TheFocusMan** [comment]
> I see, thank you. So this is fixed?

Yep it fixed it

**Comment by Kiirx** [comment]
well absolutely not for me

**Comment by quajak** [comment]
@MishaTY Any ideas on the possible cause or how to debug this?
