### ISSUE TITLE
The circular dependencies

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#244]
I have project with one file : Kernel.cs which is in ring User (Kernel must be in user).
I have another project too but with more folders, files, etc. which is in ring HAL.
And so compiler say that communication through that is not allowed. So i created the project between rings of them (The ring is System) so it can communicate. But i need to reference them. So also the projects need to refernce the connector project too. That creates circular dependency. How to avoid the circular dependency? (Without making every part of code per one ring & project)

**Comment by charlesbetros** [comment]
Kernel references System which references HAL.

You should be calling methods in System which wrap the HAL.

**Comment by lukaandjelkovic** [comment]
@charlesbetros yes i know, but is there a way to make it in two projects?
More projects there are, slower building is.
When i create OS with one project:5 sec IL2CPU.
When i create OS with two projects:10 sec IL2CPU.
When i create OS with three projects: 15 sec IL2CPU.
So how i can optimize the build with only one or maybe two projects?

**Comment by mterwoord** [comment]
Adding extra assemblies to your cosmos kernel shouldn't matter much (definitely not that much).
Are you sure you're just adding class libraries?

**Comment by lukaandjelkovic** [comment]
ya, actually creating copies of my projects, and then renaming it everywhere and deleting unneeden.

**Comment by mterwoord** [comment]
If then it gets that much slower, there's something wrong..

**Comment by charlesbetros** [comment]
Is this resolved?

**Comment by lukaandjelkovic** [comment]
no.

**Comment by mterwoord** [comment]
So I guess we have to look into this. Have you tried disabling stack corruption detection?

Also, can you please list your hardware specs? (cpu, ram, harddisk type)

**Comment by lukaandjelkovic** [comment]
CPU : 2.7 GHZ 2x Core AMD A4
RAM : 4GB (But 3.2 GB Usable, because i set 800 megs for integrated graphics)
Hard Disk is HDD, Simple , MBR.
My OS is Windows 10.
I think that other specs isnt needen.
I have HP ProBook 655 G1 Laptop.

**Comment by lukaandjelkovic** [comment]
Disabling Stack Corruption Detection seem to speed up for 2-3 secs. But whole process is 60 seconds.
More projects i have, +20 secs it build.

**Comment by charlesbetros** [comment]
Can you post your source somewhere?

**Comment by lukaandjelkovic** [comment]
It doesnt matter anymore. Its enough fast.
