### ISSUE TITLE
Using class constuctor instead of BeforeRun causes CPU shutdown

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2445]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernel

#### Expected Behaviour - What do you think that should happen?
Should run fine like BeforeRun

#### Actual Behaviour - What unexpectedly happens?
CPU shutdown

#### Reproduction - How did you get this error to appear?
use public Kernel() { }

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit

**Comment by Kiirx** [comment]
Cosmos \_(:D)_/

**Comment by terminal-cs** [comment]
> Cosmos _(:D)_/

fr

**Comment by quajak** [comment]
Could you please clarify on

> Reproduction - How did you get this error to appear?
> use public Kernel() { }

**Comment by terminal-cs** [comment]
> Could you please clarify on
> 
> > Reproduction - How did you get this error to appear?
> > use public Kernel() { }

Not sure what needs to be clarified, just having it there causes the issue

**Comment by AsertCreator** [comment]
when and how must it be used? cosmos already uses kernel cctor for system initialization. it might be a bad idea to override it. plus, your cctor is empty, so system will not startup

**Comment by terminal-cs** [comment]
> when and how must it be used? cosmos already uses kernel cctor for system initialization. it might be a bad idea to override it. plus, your cctor is empty, so system will not startup

cctors are not overrided, the base cctor is called then the extention one is called.

yes i know it''s emplty, this is only an example

**Comment by quajak** [comment]
Oh, that might be a change made by https://github.com/CosmosOS/IL2CPU/blob/7b54b04c8f66a7a8ecfa8abfc294ab1433e22360/source/Cosmos.IL2CPU/AppAssembler.cs#L1355 . Cosmos now allows you override the standard boot routine if you implement Kernel.Start in your own code. Cosmos doesnt really use the Kernel ctor to do anything important

**Comment by terminal-cs** [comment]
> Oh, that might be a change made by https://github.com/CosmosOS/IL2CPU/blob/7b54b04c8f66a7a8ecfa8abfc294ab1433e22360/source/Cosmos.IL2CPU/AppAssembler.cs#L1355 . Cosmos now allows you override the standard boot routine if you implement Kernel.Start in your own code. Cosmos doesnt really use the Kernel ctor to do anything important

Alright, but why isn't it called automatically?

**Comment by AsertCreator** [comment]
just use `Kernel.Start` instead

**Comment by terminal-cs** [comment]
> just use `Kernel.Start` instead

That's not the point, the point is that this shouldn't happen.

**Comment by AnErrupTion** [comment]
I'm not able to reproduce this issue. Here's my class:
```
public class Kernel : Sys.Kernel
{
    public Kernel()
    {

    }

    protected override void BeforeRun()
    {
        Console.WriteLine("HEHEHEHAW");
    }

    protected override void Run()
    {
        var input = Console.ReadLine();

        Console.WriteLine(input);
    }
}
```

Is there anything else required to produce this bug? @terminal-cs

**Comment by terminal-cs** [comment]
> I'm not able to reproduce this issue. Here's my class:
> 
> ```
> public class Kernel : Sys.Kernel
> {
>     public Kernel()
>     {
> 
>     }
> 
>     protected override void BeforeRun()
>     {
>         Console.WriteLine("HEHEHEHAW");
>     }
> 
>     protected override void Run()
>     {
>         var input = Console.ReadLine();
> 
>         Console.WriteLine(input);
>     }
> }
> ```
> 
> Is there anything else required to produce this bug? @terminal-cs

try putting the writeline in the constructor, compiler optimizations could have removed it before cosmos compiled it

**Comment by AnErrupTion** [comment]
Alright now it boot loops.

**Comment by AnErrupTion** [comment]
Ok so the issue is that the VGA text mode isn't initialized. This is not a problem with Cosmos
