### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by HeXedek** [CosmosOS/Cosmos#2447]
Ok so i was creating some shit os with tutorial and when i did the gui it didnt work
tut: https://www.youtube.com/watch?v=V1eRdbwExOk
my code: https://github.com/HeXedek/someshitos

#### Expected Behaviour - What do you think that should happen?

gui should work

#### Actual Behaviour - What unexpectedly happens?

gui dosent show

#### Reproduction - How did you get this error to appear?

i copied it from tutorial

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos user kit

**Comment by MishaTY** [comment]
Not a cosmos issue, you never create an instance of ``gui``.
