### ISSUE TITLE
IL2CPU Doesn't exist!

### ISSUE THREAD

**Issue by IAmDazen** [CosmosOS/Cosmos#2451]
#### Area of Cosmos - What area of Cosmos are we dealing with?
C#

#### Expected Behaviour - What do you think that should happen?
File runs perfecctly

#### Actual Behaviour - What unexpectedly happens?
turns out IL2CPU didn't get installed

#### Reproduction - How did you get this error to appear?
running the program

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit IL2CPU

**Comment by IAmDazen** [comment]
by c# i meant kernal

**Comment by ptobuon** [comment]
Are you using vs2019 or 2022?

**Comment by IAmDazen** [comment]
vs2019

**Comment by IAmDazen** [comment]
but i checked the program files and it doesn't exist

**Comment by AsertCreator** [comment]
cosmos installs itself to the appdata folder. does the project run? did you install cosmos?

**Comment by IAmDazen** [comment]
yes i did

**Comment by IAmDazen** [comment]
but no the project does not procceed to run cosmos kernal

**Comment by IAmDazen** [comment]
cuz cosmos didn't install the frickin  directory

**Comment by IAmDazen** [comment]
just the vs2019 projects

**Comment by IAmDazen** [comment]
wait

**Comment by IAmDazen** [comment]
just send me the c# open source maneged operating system directory and i can put it in roaming

**Comment by IAmDazen** [comment]
make sure its user kit

**Comment by IAmDazen** [comment]
to see if it was an install error i ran the installer 3
T
I
M
E
S

**Comment by AsertCreator** [comment]
![image](https://user-images.githubusercontent.com/53435943/198830551-29a6e67a-f392-4bcd-a151-8bfd06b7dc1d.png)
look there is `Cosmos User Kit` folder in appdata roaming. cosmos installer installs it into appdata roaming folder, not program files! maybe your installer was corrupted while downloading, try re-download it. plus you must install these dependencies:
- vs2019 workload: .net development
- vs2019 workload: .net core tools
- .net 5.0
- vmware player

without these it will not work. also i recommend you downloading cosmos user kit

**Comment by MishaTY** [comment]
*.net 6

**Comment by IAmDazen** [comment]
i didn't install the dependencies (or at least i dont think i did) i will do that after my rick roll virus shuts me down!

**Comment by IAmDazen** [comment]
also i dont think i have enough ram on my drive AKA space

**Comment by AsertCreator** [comment]
> *.net 6

for userkit, its .net 5, not .net 6

**Comment by AsertCreator** [comment]
> i didn't install the dependencies (or at least i dont think i did) i will do that after my rick roll virus shuts me down!

what rick roll virus?
