### ISSUE TITLE
MacOS & ARM64 Support

### ISSUE THREAD

**Issue by makabaka1880** [CosmosOS/Cosmos#2456]
#### Area of Cosmos - What area of Cosmos are we dealing with?
MacOS support on x86_64 and arm64 will be very much appreciated. It’s very frustrating to not be able experience such a great project on my Apple Silicon m2

#### Expected Behaviour - What do you think that should happen?
—

#### Actual Behaviour - What unexpectedly happens?
—

#### Reproduction - How did you get this error to appear?
—

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
—

**Comment by zarlo** [comment]
add you should need to do is edit this line https://github.com/CosmosOS/Cosmos/blob/master/Makefile#L73

**Comment by AsertCreator** [comment]
no, il2cpu and cosmos both dont support arm yet. il2cpu cant produce instructions, cosmos cant use arm features

**Comment by AsertCreator** [comment]
p.s. there is a crossplatform version of cosmos, but only through cli. maybe try that?

**Comment by zarlo** [comment]
> crossplatform version of cosmos

yes the only things that only work on windows are the vs extensions and the windows builder program (makes the windows installer)

**Comment by Kiirx** [comment]
As crossplatform is now at a stable state you should be able to run cosmos, if not tell us!

**Comment by MishaTY** [comment]
Macos/linux support is already in cosmos, but supporting arm will require major rewrites to il2cpu/cosmos.
