### ISSUE TITLE
Can't load project

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#246]
There's the log:
```
4>	Error: Exception: System.TypeLoadException: Could not load type 'CritSys.CPU' from assembly 'TriangleOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
4>	   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
4>	   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
4>	   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
4>	   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
4>	   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILReader.cs:line 328
4>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 545
4>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
4>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
4>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```
In error list i have only Error Invoking il2cpu
What is that talking about?

**Comment by mterwoord** [comment]
What are you trying to do here?

**Comment by lukaandjelkovic** [comment]
To load the project that needs to organize CPU

**Comment by mterwoord** [comment]
Can you try to be more specific what you're doing? It seems like you're mixing up assembly versions somewhere..

**Comment by charlesbetros** [comment]
Did this get resolved? I think we will need more information to do anything more.

**Comment by lukaandjelkovic** [comment]
no.

**Comment by mterwoord** [comment]
@lukaandjelkovic Can you please answer my question?

**Comment by lukaandjelkovic** [comment]
i have three projects.
Kernel
Critical System
System

When i load Critical System from System, i get that log above.
When i comment out that, everything work.

**Comment by mterwoord** [comment]
Have you configured VS c# projects, with normal refrence settings?

**Comment by lukaandjelkovic** [comment]
It doesn't really matter. Don't take time on this shit.

**Comment by lukaandjelkovic** [comment]
yes, just deleted unneeden and added the needen.

**Comment by mterwoord** [comment]
Can you post a complete sample project (zip file) somewhere?

**Comment by lukaandjelkovic** [comment]
Men, it's so goddamit huge so i can't give it to anyone. Every time i create a project it doesn't work.
Maybe because i create user-kit solution which contains the new project which i move to my Cosmos dev-kit solution?
Does it matter?

**Comment by mterwoord** [comment]
Shouldn't matter. You say it's huge: large projects take longer to compile.

Can you make a small test case, showing the slowness?

**Comment by lukaandjelkovic** [comment]
@mterwoord , i just confuse you: This the issue about it doesn't load, but the slowness is closed.

**Comment by mterwoord** [comment]
OK, so the doesn't load thing: Even if it's larger, if you want the issue solved, we can help you if you put the issue up somewhere.

**Comment by lukaandjelkovic** [comment]
Don't take time on this. It's just a few shits walking around.
