### ISSUE TITLE
CosmosOS will not mount CosmosVFS

### ISSUE THREAD

**Issue by lukeacourt2** [CosmosOS/Cosmos#2462]
#### Area of Cosmos - What area of Cosmos are we dealing with?

CosmosVFS

#### Expected Behaviour - What do you think that should happen?

Should Display Registed VFS

#### Actual Behaviour - What unexpectedly happens?

N/A

#### Reproduction - How did you get this error to appear?

Use The latest Dev Kit plus VS 2022 Build 17.4.0

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

  I am using the Current Version of the Dev Kit with Visual Studio 2022.

**Comment by MishaTY** [comment]
It doesn't do that with newer versions
