### ISSUE TITLE
Issue with graphics

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [CosmosOS/Cosmos#2465]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Probably Graphics or something.. 

#### Expected Behaviour - What do you think that should happen?
The system should draw to the screen as expected.

#### Actual Behaviour - What unexpectedly happens?
The VMware sizes up, blank.
And then it closes.

#### Reproduction - How did you get this error to appear?
Use the tutorial on non-flickering canvas

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by terminal-cs** [comment]
Could you link to the article you followed?

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> Could you link to the article you followed?

https://github.com/CosmosOS/Cosmos/wiki/Non-Flickering-Canvas-GUI-Tutorial

**Comment by terminal-cs** [comment]
> > Could you link to the article you followed?
> 
> https://github.com/CosmosOS/Cosmos/wiki/Non-Flickering-Canvas-GUI-Tutorial

What are you running your os on

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> What are you running your os on

My host? Windows 11.
Visual studio 2022
BIOS Version/Date	American Megatrends Inc. P2.00, 3/28/2017

**Comment by terminal-cs** [comment]
> > What are you running your os on
> 
> My host? Windows 11. Visual studio 2019 BIOS Mode UEFI BaseBoard Manufacturer ASRock BaseBoard Product B250 Gaming K4

directly? because if so normal canvas can only be used in a vm

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> directly? because if so normal canvas can only be used in a vm
I am using a VM.

**Comment by GoldenretriverYT** [comment]
Devkit or Userkit?

If you are using the Userkit, switch to the devkit.

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> Devkit or Userkit?
> 
> If you are using the Userkit, switch to the devkit.

Did that, didn't work.

**Comment by zarlo** [comment]
can we see the code you are running

**Comment by imadethisaccountsoicanmakeanissue** [comment]
```
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using System.Drawing;
using Cosmos.System.Graphics;

namespace CosmosKernel7
{
    public class Kernel : Sys.Kernel
    {
        private static int screenX = 800;
        private static int screenY = 640;
        private static Color[] pixelBuffer = new Color[(screenX * screenY) + screenX];
        private static Color[] pixelBufferOld = new Color[(screenX * screenY) + screenX];
        private static Canvas canvas;
        protected override void BeforeRun()
        {
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(screenX, screenY, ColorDepth.ColorDepth8));
        }
        protected override void Run()
        {

            while (true) {
                update();
            }

            
        }

        public static void setPixel(int x, int y, Color c)
        {
            if (x > screenX || y > screenY) return;
            pixelBuffer[(x * y) + x] = c;
        }
        public static void drawScreen()
        {
            Pen pen = new Pen(Color.Orange);
            for (int y = 0, h = screenY; y < h; y++)
            {
                for (int x = 0, w = screenX; x < w; x++)
                {
                    if (!(pixelBuffer[(y * x) + x] == pixelBufferOld[(y * y) + x]))
                    {
                        pen.Color = pixelBuffer[(y * screenX) + x];
                        canvas.DrawPoint(pen, x, y);
                    }
                }
            }
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = pixelBufferOld[i];
            }
            canvas.Display();
        }
        public static void clearScreen(Color c)
        {
            for (int i = 0, len = pixelBuffer.Length; i < len; i++)
            {
                pixelBuffer[i] = c;
            }
        }
        public static void update()
        {
            clearScreen(Color.Blue);
            setPixel(1, 1, Color.Black);
            setPixel(1, 2, Color.Black);
            setPixel(2, 1, Color.Black);
            setPixel(2, 2, Color.Black);
            drawScreen();
        }
    }
}

```

**Comment by imadethisaccountsoicanmakeanissue** [comment]
Noone wanted to help :( If you have the same issue, open a new issue

**Comment by ascpixi** [comment]
I know this is closed, but this line:
`!(pixelBuffer[(y * x) + x] == pixelBufferOld[(y * y) + x])`
doesn't make much sense; shouldn't it be
`!(pixelBuffer[(y * w) + x] == pixelBufferOld[(y * w) + x])`
as to convert the 2D index into a 1D index?

Also, I'm pretty sure the Cosmos canvas does double buffering by default; CMIIW.

**Comment by MarcTho8** [comment]
I'll try when i get my pc to work
(new acc)

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> I'll try when i get my pc to work (new acc)

(true)

**Comment by imadethisaccountsoicanmakeanissue** [comment]
It turns to be a issue with the canvas, so i will open up a new issue.
