### ISSUE TITLE
Iso not working outside VMware

### ISSUE THREAD

**Issue by Arnotronix75** [CosmosOS/Cosmos#2469]
If I try to open the Iso file outside Visual Studio with VMware it will just say this:

 ![Github](https://user-images.githubusercontent.com/118206809/201724823-bd6a751d-1dda-4d79-a522-caf95daa5f51.png)
Here is the code:
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Text;
using Sys = Cosmos.System;

using Cosmos.System.FileSystem;
using System.ComponentModel;
namespace OS_TRONIX
{
    public class Kernel : Sys.Kernel
    {
        private CosmosVFS vfs;
        void cls()
        {
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
            Console.WriteLine("\n");
        }

        protected override void BeforeRun()
        {
            this.vfs = new CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(this.vfs);
            cls();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine(" |-----| ______");
            Console.WriteLine(" |     |   ||  ");
            Console.WriteLine(" |     |   ||  ");
            Console.WriteLine(" |     |   ||  ");
            Console.WriteLine(" |-----|   ||  ");
            Console.WriteLine("  OS Tronix    ");
        }

        protected override void Run()
        {
            Console.Write("Tronix@Tronix|");
            var input = Console.ReadLine();
            if (input == "info")
            {
                Console.Write("An OS made by Arnotronix\n");
            }
            if (input == "echo")
            {
                Console.Write("What do you want to say:");
                var x = Console.ReadLine();
                Console.Write(x + "\n");
            }
            if (input == "help")
            {
                Console.Write("info\n");
                Console.Write("echo\n");
                Console.Write("clear\n");
                Console.Write("shd > shutdown\n");
                Console.Write("ret > restart\n");
                Console.Write("color\n");
                Console.Write("mf > make file\n");
                Console.Write("del > delet file\n");
                Console.Write("ls > shows all files\n");
                Console.Write("rf > read file\n");
                Console.Write("wf > write to file\n");
                Console.Write("help\n");

            }
            if (input == "clear")
            {
                cls();
            }
            if (input == "shd")
            {
                Cosmos.System.Power.Shutdown();
            }
            if (input == "ret")
            {
                Cosmos.System.Power.Reboot();
            }
            if (input == "color")
            {
                Console.Write("Which color do you want?(r > red, g > green, b > blue)\n");
                Console.Write("Your color: ");
                var colorinput = Console.ReadLine();
                if (colorinput == "r")
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                }
                if (colorinput == "g")
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                }
                if (colorinput == "b")
                {
                    Console.ForegroundColor = ConsoleColor.Blue;
                }
            }
            if (input == "calc")
            {
                Console.Write("What type of Calculation?");
                var calctype = Console.ReadLine();
                Console.Write("Number1: ");
                var num1 = Console.ReadLine();
                Console.Write("Number2: ");
                var num2 = Console.ReadLine();
                if (calctype == "+")
                {
                    int num3 = Int32.Parse(num1) + Int32.Parse(num2);
                    Console.Write("Solution: " + num3 + "\n");
                }
                if (calctype == "*")
                {
                    int num3 = Int32.Parse(num1) * Int32.Parse(num2);
                    Console.Write("Solution: " + num3 + "\n");
                }
                if (calctype == "-")
                {
                    int num3 = Int32.Parse(num1) - Int32.Parse(num2);
                    Console.Write("Solution: " + num3 + "\n");
                }

            }
            if (input == "ls")
            {
                var directory_list = Directory.GetFiles(@"0:\");
                foreach (var directory in directory_list)
                {
                    Console.WriteLine(directory);
                }
            }
            if (input == "mf")
            {
                Console.WriteLine("filename: ");
                var filename = Console.ReadLine();
                try
                {
                    Sys.FileSystem.VFS.VFSManager.CreateFile(@"0:\" + filename);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                }
            }
            if (input == "wf")
            {
                Console.WriteLine("filename: ");
                var filename = Console.ReadLine();
                Console.WriteLine("infile: ");
                var infile = Console.ReadLine();
                try
                {
                    File.WriteAllText(@"0:\" + filename, infile);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                }
            }
            if (input == "rf")
            {
                Console.WriteLine("filename: ");
                var filename = Console.ReadLine();
                try
                {
                    Console.WriteLine(File.ReadAllText(@"0:\" + filename));
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                }
            }
        }
    }
}

Can you help me?

**Comment by ptobuon** [comment]
I don't see any wrong code, maybe try reinstalling cosmos or vmware.

**Comment by Arnotronix75** [comment]
thanks i will try that

**Comment by Arnotronix75** [comment]
It‘s not showing me that error but now it‘s showing me this:
![Github2](https://user-images.githubusercontent.com/118206809/202553125-fc5f3b08-2f20-4f8e-8893-79c8bfdb7ca9.png)

**Comment by Arnotronix75** [comment]
Can you please tell me why

**Comment by quajak** [comment]
Does creating a file with the name `tests.txt` also not work?

**Comment by Arnotronix75** [comment]
nope

**Comment by quajak** [comment]
Can you try with a clean vmdk downloaded from the Cosmos github?

**Comment by Arnotronix75** [comment]
Thanks!!!
