### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by TiM-SyStEm** [CosmosOS/Cosmos#2471]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
I use:
-VS22
-Cosmos User Kit (built from repo via "userkit install.bat")
-.NET 6

I has run the start project "Kernel" and didn't change code.

**Comment by quajak** [comment]
What version of the nuget packages is the project using?

**Comment by TiM-SyStEm** [comment]
> What version of the nuget packages is the project using?

6.4.0.111
