### ISSUE TITLE
Modulo broken

### ISSUE THREAD

**Issue by Jspa2** [CosmosOS/Cosmos#2472]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
Modulo should work correctly

#### Actual Behaviour - What unexpectedly happens?
The modulo operator outputs an incorrect value.

#### Reproduction - How did you get this error to appear?
```cs
double x = 3;
double y = 3;
Console.WriteLine(x % y);
```
Outputs **3**, yet should output **0**.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Developer kit
Cosmos - f6372f4
IL2CPU - `7b54b04`
X# - `fbf2111`

**Comment by quajak** [comment]
Will be fixed by https://github.com/CosmosOS/IL2CPU/pull/177
