### ISSUE TITLE
Can't read a file

### ISSUE THREAD

**Issue by sytzemeijer** [CosmosOS/Cosmos#2474]
#### Area of Cosmos - What area of Cosmos are we dealing with?
file system

#### Expected Behaviour - What do you think that should happen?
can't read a  file

#### Actual Behaviour - What unexpectedly happens?
If I Read a file I get this
![afbeelding](https://user-images.githubusercontent.com/115628711/202705859-737cd213-b211-4c3e-a185-4bd736be371c.png)

#### Reproduction - How did you get this error to appear?
```c#
using system.IO;
File.ReadAllText("0:\\Root.txt")
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user Kit 2019

######Can I read and write a file in the userkit 2019

**Comment by quajak** [comment]
Did you confirm that the file exists?

**Comment by quajak** [comment]
Could you please upload the vmdk file you are using to help reproduce this issue?
