### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by osser00** [CosmosOS/Cosmos#2475]
#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/118602079/202846553-ddcd6199-e4b8-416c-8b5a-96aa090faa15.png)

#### Reproduction - How did you get this error to appear?
When i try to start (debug)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

**Comment by quajak** [comment]
Please check if the cosmos vs extensions are installed and the nuget packages found
