### ISSUE TITLE
I can not find a CosmosKernel1Boot file

### ISSUE THREAD

**Issue by Arnotronix75** [CosmosOS/Cosmos#2491]
#### Expected Behaviour - What do you think that should happen?
There should be an CosmosKernel1Boot

#### Actual Behaviour - What unexpectedly happens?
There is no

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit
![File](https://user-images.githubusercontent.com/118206809/204094247-96f5dd7e-3677-47c4-988d-4129646883cb.png)

**Comment by MishaTY** [comment]
Not a bug, this was removed a very long time ago

**Comment by Arnotronix75** [comment]
why
