### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2493]
Why not add a way to custom the default exception message as it is very intrusive even when you use a try catch

**Comment by zarlo** [comment]
you can its not that hard

**Comment by AsertCreator** [comment]
wrap your code in try catch block and you are ready

**Comment by Kiirx** [comment]
And thats why i created this issue, sometimes even with a try catch it throws a generic exception

**Comment by quajak** [comment]
I havnt tested if it does work but maybe plugging https://github.com/CosmosOS/Cosmos/blob/9d0ccc2be22938424d8992611b11409aaabf74ea/source/Cosmos.Core/INTs.cs#L691 this method, should allow you to make a custom exception handler for crashes. Just keep in mind that even object allocation might no longer be working.

**Comment by AsertCreator** [comment]
if you mean cpu exception, you can use the `INTs` class to redefine default exception handling routines. maybe it will not work, but try that

**Comment by Kiirx** [comment]
I was talking about kernel exception but heh I'll just close this
