### ISSUE TITLE
VSIX Installer for extensions blocked by background Git

### ISSUE THREAD

**Issue by AnErrupTion** [CosmosOS/Cosmos#2495]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Builder

#### Expected Behaviour - What do you think that should happen?
The extensions and templates should install correctly

#### Actual Behaviour - What unexpectedly happens?
The extensions are not installed because of a background Git executable running in the background, causing the VSIX silent installer to hang after some time (that's my guess though), instead of force killing the Git tasks.

#### Reproduction - How did you get this error to appear?
I just installed Cosmos

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit (20221121 ) and also Dev Kit, it doesn't change anything

**Comment by AnErrupTion** [comment]
Some additional information: it could be related to the new Git file system watcher (which I enabled during installation), though I still don't know why it would conflict with the VSIX installer...

**Comment by quajak** [comment]
This seems like an issue which we will most likely not fix. For now if the VSIX installer hangs, you can manually rerun it using the .vsix files found under `AppData\Roaming\Cosmos User Kit\VSIX`
