### ISSUE TITLE
Deleting a directory in the VFS.

### ISSUE THREAD

**Issue by ser-ui** [CosmosOS/Cosmos#2496]
I cant delete a directory in the vfs... im trying with the following code:
`Directory.Delete(folder);`
"folder" is a string with the directory to delete, and is `folder = Console.ReadLine();` (a input from the user).
The error is that `Directory.Delete` doesnt work with a string. How can I use the class to delete a directory that the user types?

**Comment by ptobuon** [comment]
you need to write in console 0:\folder to delete it

**Comment by zarlo** [comment]
what is the value of ``folder`` it might be invalid

**Comment by 9xbt** [comment]
Directory.Delete works from a string, wdym
