### ISSUE TITLE
Update documentation. VS2013, Ring enforcement

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#25]
Update documentation to mention:
- VS2013 (including community edt)
- Rings are enforced now.
- also go through everything and update it.. (links for example)

**Comment by charlesbetros** [comment]
@mterwoord is this still valid?

**Comment by lukaandjelkovic** [comment]
@mterwoord But Cosmos supports VS 15, not VS 13!

**Comment by mterwoord** [comment]
No, VS14, which is 2015.

**Comment by Arawn-Davies** [comment]
Can this be closed? We're on vs2017 and the documentation, especially on wikipedia and the website appears to be up to date :)
