### ISSUE TITLE
Help with deleting files

### ISSUE THREAD

**Issue by ThatHindiKid** [CosmosOS/Cosmos#2502]
#### Version - Using- VS2022, UserKit latest version, Cosmos C#
![Screenshot (43)](https://user-images.githubusercontent.com/119788704/206898449-f719b032-9133-4759-82e5-517d4a528ce6.png)

**Comment by 9xbt** [comment]
No need to make an issue here. It crashes because the file you entered doesn't exist. You also need to type the file extension of the file else it won't work.
