### ISSUE TITLE
Console bug

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2507]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
Should make the console cursor appear when System.Console.CursorVisible is set to true

#### Actual Behaviour - What unexpectedly happens?
Doesn’t do anything

#### Reproduction - How did you get this error to appear?
By running the line of code fyi

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Idk

**Comment by AnErrupTion** [comment]
Potentially related to #2371

**Comment by 9xbt** [comment]
Sorry then imma close this
