### ISSUE TITLE
Weird bug when changing the terminal background color.

### ISSUE THREAD

**Issue by audiotore482** [CosmosOS/Cosmos#2527]
- Area of Cosmos - What area of Cosmos are we dealing with?
Changing the background color of the shell when using Console.BackgroundColor

- Expected Behaviour - What do you think that should happen?
Change the background color fine no bugs.

- Actual Behaviour - What unexpectedly happens?
For some resson when hit clear the console or type it
clears out the color back to the default shell color (black)

- Reproduction - How did you get this error to appear?
Using Console.BackgroundColor to change a color.

- Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using Dev kit with the latest merge request being from the user quajaks on December 20 of 2022

- Result:
![image](https://user-images.githubusercontent.com/117720256/208754185-435614ea-69f2-4cbb-907d-5a6f8d4a1dc2.png)

**Comment by MishaTY** [comment]
Can you send a simple piece of code that can reproduce this issue?

**Comment by audiotore482** [comment]
> Can you send a simple piece of code that can reproduce this issue?

Course! Give me a second.

**Comment by audiotore482** [comment]
Not sure if thats enough

**Comment by 9xbt** [comment]
It IS supposed to do that, that's how it should work
You just need to clear the screen
And that's it

**Comment by 9xbt** [comment]
Ew light mode

**Comment by MishaTY** [comment]
You need to clear the entire screen to change the color.

**Comment by 9xbt** [comment]
Thanks

**Comment by audiotore482** [comment]
> You need to clear the entire screen to change the color.

I didn't have time to respond back?

**Comment by audiotore482** [comment]
Sadly this didn't even work either. I have a titlebar on top that shows name of the OS and time and date. As well as the build date I think this has something to do with the color not changing properly.

**Comment by audiotore482** [comment]
Thanks

**Comment by audiotore482** [comment]
No it seems to be doing something weird.. I just figured out it was the titlebar.
My goal here is to make it so even if the titlebar is there it changes the color.

**Comment by audiotore482** [comment]
The titlebar code seems to change the position of the print cursor and do something weird that causes this to set the color back to its original

**Comment by audiotore482** [comment]
![image](https://user-images.githubusercontent.com/117720256/208764299-820403d5-6520-48d9-a8dc-36846765bbd2.png)

**Comment by audiotore482** [comment]
Hm is there a possible way to read a file and store it into a variable in Cosmos?
