### ISSUE TITLE
Project template support for dotnet new

### ISSUE THREAD

**Issue by winbamstudios** [CosmosOS/Cosmos#2529]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Creating a project

#### Expected Behaviour - What do you think that should happen?
Cosmos Project showing up in "dotnet new --list"

#### Actual Behaviour - What unexpectedly happens?
It does not appear.

#### Reproduction - How did you get this error to appear?
It's not really an _error_ but it's annoying.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit pull request merge #2526

**Comment by Kiirx** [comment]
You just have to create a blank console project and add the cosmos.system2 and cosmos.buil nuget packages

**Comment by zarlo** [comment]
we could port the template system to the new .net one so it works on all platforms

**Comment by winbamstudios** [comment]
good idea

**Comment by winbamstudios** [comment]
i'm only used to the GUI package system how do i install the nupkg files?

**Comment by Kiirx** [comment]
> i'm only used to the GUI package system how do i install the nupkg files?

VScode has a GUI system if you download the extension for

**Comment by winbamstudios** [comment]
> VScode has a GUI system if you download the extension for
How do I do this? I can't install the packages from .nupkg file.

**Comment by winbamstudios** [comment]
**UPDATE!**
I got it to say the packages weren't missing, but I get the following errors.
`/home/windowsbammer/TechOS/CosmosTTF/TTFManager.cs(6,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(23,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/Kernel.cs(23,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/Window.cs(21,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(35,86): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(35,102): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/Window.cs(28,48): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/Window.cs(28,65): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/Window.cs(28,81): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]
/home/windowsbammer/TechOS/CosmosTTF/TTFManager.cs(69,58): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]`

**Comment by zarlo** [comment]
you will need to update your code to use the newer apis

**Comment by winbamstudios** [comment]
> **UPDATE!** I got it to say the packages weren't missing, but I get the following errors. `/home/windowsbammer/TechOS/CosmosTTF/TTFManager.cs(6,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(23,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/Kernel.cs(23,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/Window.cs(21,38): error CS0234: The type or namespace name 'Point' does not exist in the namespace 'Cosmos.System.Graphics' (are you missing an assembly reference?) [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(35,86): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/GUIToolkit/WindowManager.cs(35,102): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/Window.cs(28,48): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/Window.cs(28,65): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/Window.cs(28,81): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj] /home/windowsbammer/TechOS/CosmosTTF/TTFManager.cs(69,58): error CS1069: The type name 'Pen' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [/home/windowsbammer/TechOS/P64_devkit.csproj]`

UPDATE: fixed

**Comment by winbamstudios** [comment]
but the ISO file doesn't work

**Comment by zarlo** [comment]
how does it not work we need more info

**Comment by winbamstudios** [comment]
> how does it not work we need more info

in virtualbox it says "guru meditation" and in qemu it hangs

**Comment by quajak** [comment]
please open a new issue for the new problem

**Comment by AnErrupTion** [comment]
It's actually quite easy: https://devblogs.microsoft.com/dotnet/how-to-create-your-own-templates-for-dotnet-new/
