### ISSUE TITLE
The OS cannot boot!!

### ISSUE THREAD

**Issue by S-FAMILY1** [CosmosOS/Cosmos#2532]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Virtualization

#### Expected Behaviour - What do you think that should happen?
The OS should boot successfully

#### Actual Behaviour - What unexpectedly happens?
the command line pops up and saying "error : file /boot/test was not found"

#### Reproduction - How did you get this error to appear?
The build was successful and when the vmware window pops up and  show the above error

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I am Using cosmos user kit

![Screenshot 2022-12-21 214948](https://user-images.githubusercontent.com/121184870/208953555-8ca23fb6-08ce-42a1-8176-ebc42c71d088.png)

**Comment by S-FAMILY1** [comment]
Please help me. I don"t know what is wrong.

**Comment by AnErrupTion** [comment]
You can't have a space in your project name.

**Comment by S-FAMILY1** [comment]
Ohhhh! I'll try that.

**Comment by S-FAMILY1** [comment]
It worked! Than you so much!
