### ISSUE TITLE
Can't see the Project Template in Visual Studio

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#2533]
**Describe the problem**
A clear and concise description of where the installation is going wrong.

I can't see the Project Template in Visual Studio

**Steps of installation up to now**

Download Latest Cosmos Userkit Setup and Run it as admin

**Expected behavior**

to see the project template in the Create a new Project window

**Setup (please complete the following information):**
 - userkit 20221121
 - running installer as administrator
 - Visual Studio 2022

**Comment by Arkinetic** [comment]
same

**Comment by Vardan2009** [comment]
Nevermind I fixed it.

**Comment by Arkinetic** [comment]
> Nevermind I fixed it.

how?

**Comment by Vardan2009** [comment]
I had two versions of Visual Studio, 2022 and 2019. I uninstalled the 2019 one and now it works somehow

**Comment by Vardan2009** [comment]
I guess the installer installed cosmos on the 2019 version, thats why it wasn't showing up in vs2022

**Comment by 9xbt** [comment]
yeah that's a bug, you need to ONLY have vs2022 installed, else it will install to vs2019. Happened to me the first time i installed it too, vs2022 at least doesn't BSOD my computer so i consider it an upgrade
