### ISSUE TITLE
Weird filesystem issue.

### ISSUE THREAD

**Issue by audiotore482** [CosmosOS/Cosmos#2534]
#### Area of Cosmos - What area of Cosmos are we dealing with?
File system.

#### Expected Behaviour - What do you think that should happen?
Create this file fine.

#### Actual Behaviour - What unexpectedly happens?
Gives me the error: Exception occurred while running
kernel: Value cannot be null. Parameter name: aPath

#### Reproduction - How did you get this error to appear?
Its a little bit confusing but I believe it has something to do
with the filesystem.
![image](https://user-images.githubusercontent.com/117720256/209483106-f75b822f-3a5a-4da5-b82e-3c8df4a6d765.png)

**Comment by 9xbt** [comment]
What is your code and are you creating the file with Cosmos's VFSManager class or System.IO?

**Comment by audiotore482** [comment]
Cosmos VFSManager class

**Comment by 9xbt** [comment]
Try printing what the parameter is

**Comment by audiotore482** [comment]
How do you do that?

**Comment by audiotore482** [comment]
im creating the file in 0:\ by the way

**Comment by Kiirx** [comment]
you have to use the System.IO classes

**Comment by audiotore482** [comment]
It doesnt seem like VFS is very reliable then.

**Comment by Kiirx** [comment]
> It doesnt seem like VFS is very reliable then.

why???

**Comment by audiotore482** [comment]
> > It doesnt seem like VFS is very reliable then.
> 
> why??? I still don't understand why are you saying that

So many people are saying they have problems with VFS. Plus VFS doesnt work on bare metal hardware believe or not. Only on
virtual machines it works fine.

**Comment by Kiirx** [comment]
well like most things, I don't see a lot of people having issues with the vFS

**Comment by MishaTY** [comment]
VFSManager is not intended to be used directly, use System.IO classes.

**Comment by audiotore482** [comment]
https://cosmosos.github.io/api/Cosmos.System.FileSystem.Disk.html it seems like you have to format it first.
