### ISSUE TITLE
Cosmos is broken on macOS

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2545]
**Have you checked Github Issues for similar errors?**
Yes. Didn't found anything  

**Exception**
error MSB6003: Impossible d'exécuter la tâche exécutable spécifiée "IL2CPU". System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/opt/cosmos/Build/IL2CPU/IL2CPU' with working directory '/Users/raphaelm/Projects/OpenKernel/OpenKernel'. Exec format error
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()

**Visual Studio Output Logs**
Génération de la solution OpenKernel (Debug)
La génération a démarré 02/01/2023 13:21:30.
__________________________________________________
Projet "/Users/raphaelm/Projects/OpenKernel/OpenKernel/OpenKernel.csproj" (Build cibles) :

GenerateTargetFrameworkMonikerAttribute cible :
  La cible est ignorée "GenerateTargetFrameworkMonikerAttribute", car tous les fichiers de sortie sont à jour par rapport aux fichiers d'entrée.
CoreGenerateAssemblyInfo cible :
  La cible est ignorée "CoreGenerateAssemblyInfo", car tous les fichiers de sortie sont à jour par rapport aux fichiers d'entrée.
CoreCompile cible :
  La cible est ignorée "CoreCompile", car tous les fichiers de sortie sont à jour par rapport aux fichiers d'entrée.
GenerateBuildDependencyFile cible :
  La cible est ignorée "GenerateBuildDependencyFile", car tous les fichiers de sortie sont à jour par rapport aux fichiers d'entrée.
CopyFilesToOutputDirectory cible :
    OpenKernel -> /Users/raphaelm/Projects/OpenKernel/OpenKernel/bin/Debug/net6.0/OpenKernel.dll
IL2CPU cible :
    /opt/cosmos/Build/IL2CPU/IL2CPU KernelPkg:
    EnableDebug:True
    EnableStackCorruptionDetection:True
    StackCorruptionDetectionLevel:MethodFooters
    DebugMode:Source
    TraceAssemblies:
    DebugCom:1
    TargetAssembly:/Users/raphaelm/Projects/OpenKernel/OpenKernel/bin/Debug/net6.0/OpenKernel.dll
    OutputFilename:/Users/raphaelm/Projects/OpenKernel/OpenKernel/bin/Debug/net6.0/OpenKernel.asm
    EnableLogging:True
    EmitDebugSymbols:True
    IgnoreDebugStubAttribute:False
    CompileVBEMultiboot:False
    VBEResolution:800x600x32
    RemoveBootDebugOutput:False
    AllowComments:False
    References:/Users/raphaelm/Projects/OpenKernel/OpenKernel/obj/Debug/net6.0/OpenKernel.dll
    References:/Users/raphaelm/.nuget/packages/cosmos.common/0.1.0-localbuild/lib/net6.0/Cosmos.Common.dll
    References:/Users/raphaelm/.nuget/packages/cosmos.core/0.1.0-localbuild/lib/net6.0/Cosmos.Core.dll
    References:/Users/raphaelm/.nuget/packages/cosmos.debug.kernel/0.1.0-localbuild/lib/netstandard2.0/Cosmos.Debug.Kernel.dll
    References:/Users/raphaelm/.nuget/packages/cosmos.hal2/0.1.0-localbuild/lib/net6.0/Cosmos.HAL2.dll
    References:/Users/raphaelm/.nuget/packages/cosmos.system2/0.1.0-localbuild/lib/net6.0/Cosmos.System2.dll
    References:/Users/raphaelm/.nuget/packages/il2cpu.api/0.1.0-localbuild/lib/netstandard2.0/IL2CPU.API.dll
    PlugsReferences:/opt/cosmos/Kernel/Cosmos.Core_Asm.dll
    PlugsReferences:/opt/cosmos/Kernel/Cosmos.Core_Plugs.dll
    PlugsReferences:/opt/cosmos/Kernel/Cosmos.Debug.Kernel.Plugs.Asm.dll
    PlugsReferences:/opt/cosmos/Kernel/Cosmos.System2_Plugs.dll
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003: Impossible d'exécuter la tâche exécutable spécifiée "IL2CPU". System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/opt/cosmos/Build/IL2CPU/IL2CPU' with working directory '/Users/raphaelm/Projects/OpenKernel/OpenKernel'. Exec format error
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
    /Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
    IL2CPU task took 00:00:00.2939811
Génération de la cible "IL2CPU" terminée dans le projet "OpenKernel.csproj" -- ÉCHEC.

Génération du projet "OpenKernel.csproj" terminée -- ÉCHEC.

ÉCHEC de la build.

/Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003: Impossible d'exécuter la tâche exécutable spécifiée "IL2CPU". System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/opt/cosmos/Build/IL2CPU/IL2CPU' with working directory '/Users/raphaelm/Projects/OpenKernel/OpenKernel'. Exec format error
/Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
/Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
/Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/Users/raphaelm/.nuget/packages/cosmos.build/0.1.0-localbuild/build/Cosmos.Build.targets(191,9): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
    0 Avertissement(s)
    1 Erreur(s)

Temps écoulé 00:00:00.60

========== Build : 0 réussite(s), 1 échec(s), 0 à jour, 0 ignorée(s) ==========

Version : 1 erreurs, 0 avertissements
**How To Reproduce**
Install Cosmos on a macOS host/guest with this commands : 
make
make install
make nuget-install

And make a new library project and add Cosmos NuGet packages.

Make a kernel class and build.

**Screenshots**
![Capture d’écran 2023-01-02 à 13 31 00](https://user-images.githubusercontent.com/81994075/210231642-a82fe06a-4b14-4ca7-910b-5d1c89181e15.png)

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[*] In the NuGet Package Manager "Include prerelease" is selected
[*] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[*] The Cosmos NuGet packages are installed

**macOS Version**
macOS 11 (Big Sur)
Darwin Kernel 20.6.0

**Comment by Kiirx** [comment]
as I am speaking I am making a hackintosh, I will try to see If I can reproduce the error on my end

**Comment by AsertCreator** [comment]
i dont think vs for mac supports vsix files. it uses mpack ones, which cosmos doesnt compile to

**Comment by zarlo** [comment]
did you edit the edit the make file so it will build for macos and not linux

**Comment by zarlo** [comment]
> i dont think vs for mac supports vsix files. it uses mpack ones, which cosmos doesnt compile to

the vsix files are only needed for the debugger
