### ISSUE TITLE
TcpListener does not work

### ISSUE THREAD

**Issue by Jspa2** [CosmosOS/Cosmos#2547]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Networking

#### Expected Behaviour - What do you think that should happen?
TcpListener should listen to connections

#### Actual Behaviour - What unexpectedly happens?
Either nothing happens or an interrupt occurs

#### Reproduction - How did you get this error to appear?
Use TcpListener class:
```csharp
Listener = new TcpListener(8080);
Listener.Start();

while (true)
{
    Console.WriteLine("Waiting...");
    TcpClient client = Listener.AcceptTcpClient(timeout: -1);
    Console.WriteLine($"Connection: {client.RemoteEndPoint.Address.ToString()}");
}
```
(Tested with VMware NAT, VMware Bridged, and QEMU RTL8139.)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev-kit
Cosmos 9d59ffa
IL2CPU [`b201480`](https://github.com/CosmosOS/IL2CPU/commit/b201480d089af5666b80b57708e3ca7461fde907)
X# [`63f738b`](https://github.com/CosmosOS/XSharp/commit/63f738b4f754a922229d45e16adf535eac3fa7a8)

**Comment by zarlo** [comment]
how are you connecting to it?

**Comment by Jspa2** [comment]
> how are you connecting to it?

I'm finding the VM's IP with the NetworkConfiguration class. I test it's correct by pinging it (Cosmos prints to the debug console when I do). And then I connect with either Microsoft Telnet or a web browser.
