### ISSUE TITLE
Bug: VBE doesn't work

### ISSUE THREAD

**Issue by ptobuon** [CosmosOS/Cosmos#2559]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
It should draw a string "THIS WORK" on screen

#### Actual Behaviour - What unexpectedly happens?
In normal canvas (Cosmos.System.Graphics.FullScreenCanvas) the string appear:
![image](https://user-images.githubusercontent.com/98218366/213777976-ed04f87e-582c-44d5-8daf-ee2723d1f754.png)

With VBE (Multiboot and VBE Resolution is 1024x768x32) 
![image](https://user-images.githubusercontent.com/98218366/213778252-183805ce-ff9a-450c-8b24-ce8fbfb0a2ae.png)
![image](https://user-images.githubusercontent.com/98218366/213778449-81b96a64-07da-491c-a474-1f0eda7ac70d.png)
The string doesn't appear and it shows only a black screen. 
![image](https://user-images.githubusercontent.com/98218366/213778823-39747ccc-4a4f-4d23-b9b1-808aec738942.png)

It doesn't work with rectangles or shapes too, so it isn't a DrawString problem.

#### Reproduction - How did you get this error to appear?
BeforeRun() Code: 
![image](https://user-images.githubusercontent.com/98218366/213778967-33401472-af5e-4a17-adea-959cc8253d73.png)

Run() Code:
![image](https://user-images.githubusercontent.com/98218366/213779012-d4c23f8d-a1ed-4390-a054-1c8f24115868.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev kit commit [c4a5df3](https://github.com/CosmosOS/Cosmos/commit/c4a5df3b53dd5dd8384c10ec28b864ee5ca7bc36)

**Comment by Kiirx** [comment]
only works on virtualbox somehow

**Comment by terminal-cs** [comment]
> only works on virtualbox somehow

VBECanvas using the multiboot vbe works everywhere

**Comment by ptobuon** [comment]
Well in VMware Player no.

**Comment by terminal-cs** [comment]
> Well in VMware Player no.

It does, i've tested it

**Comment by zarlo** [comment]
using the methods in FullScreenCanvas is the officially supported way to use the canvas system
