### ISSUE TITLE
Stack Interpreter issue. 

### ISSUE THREAD

**Issue by OriginalSandman** [CosmosOS/Cosmos#258]
Hi, i'm getting issues with compiling my project (which at the moment is the stock project that comes with COSMOS) and i get the errors below. I have all versions of .net framework installed. 

1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>  CosmosKernel1 -> \\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll
2>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = '\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Data.SQLite.SQLiteException (0x80004005): unable to open database file
2>	   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
2>	   at System.Data.SQLite.SQLiteConnection.Open()
2>	   at Cosmos.Debug.Common.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.Debug.Common\DebugInfo.cs:line 90
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 209
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	\\ONL_DRIVE\VolumeMain\User\Documents\Visual Studio 2015\Projects\COSMOS\CSharpOS\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.2725115
2>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
2>
Build has been canceled.

Thanks for your help.

**Comment by mterwoord** [comment]
Are you trying to store your project on a network drive?

**Comment by OriginalSandman** [comment]
yeah, it's stored on a network drive.

**Comment by OriginalSandman** [comment]
oh haha, i just stored it locally and now its giving me another error. 
![error](https://cloud.githubusercontent.com/assets/15888545/11212763/fcefec6c-8d8b-11e5-9374-c7ff3b8b1ea6.png)

**Comment by mterwoord** [comment]
It doesn't find VMware.. Have you got vmware (player or server) installed?

**Comment by OriginalSandman** [comment]
no, i use virtualbox. i remember being able to use it without any problems a few years ago with COSMOS version 3 and 4. Is there any way to bypass this and use virtualbox? Thanks. Sorry for the delay in my reply, got tied down with a few assignments.

**Comment by mterwoord** [comment]
Virtualbox is not supported. You can install bochs though.

Other optin is to target basic ISO files, and disable remote debugging. But this way you don't have our debugger support.

**Comment by OriginalSandman** [comment]
ok well I just downloaded vmware player as that seems like the easier option, but just for the record how would I have done the latter option. Also, Thank you for your help in my problem :)

**Comment by mterwoord** [comment]
So this issue is resolved now? If so, please close it. Thanks!

**Comment by OriginalSandman** [comment]
it is mostly, but visual studio crashes everytime vmware starts my project. Is there anyway for me to just make the ISO and open it manually?

**Comment by mterwoord** [comment]
Go to the project settings of the cosmos project. There you can configure output.

What's happening when it crashes though? Have you started vmware manualy already?
When you start the ISO manually, you dont get our debugger...

**Comment by OriginalSandman** [comment]
ok thanks. Well I press the debug button in visual studio, everything goes through and then when vmware starts loading my OS, visual studio just crashes. (windows dialogue box comes up saying visual studio is not responding and windows is attempting to restart the program)

**Comment by mterwoord** [comment]
Have you tried bochs?

**Comment by OriginalSandman** [comment]
ok so i just tried bochs and it still happens. But for the moment i'll just disable the debugger as I don't think i'll need it

**Comment by OriginalSandman** [comment]
OK just to confirm, went to project settings and just selecting "ISO image" instead of vmware boot works perfectly. (It took me a while to find the cosmos properties so i'll post just incase anyone else has the same issue. Right Click "CosmosKernelBoot" in solution explorer and select properties). Matthijs ter Woord, Thanks I appreciated all your help.

**Comment by psyCHOder** [comment]
I have the same problem 
....
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.7356437
2>Done building project "VMOSBoot.Cosmos" -- FAILED.
2>
Build has been canceled.


I have stored it in my local drive itself... Still I get this error... Visual studio 2015...
I have already installed vmware but in output I dont get the options of vmware... I get any cpu or x86
