### ISSUE TITLE
keyboard issue on actual hardware

### ISSUE THREAD

**Issue by slavekrouta** [CosmosOS/Cosmos#2580]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running COSMOS on actual hardware

#### Expected Behaviour - What do you think that should happen?
After setting keyboard map it should work, right?

#### Actual Behaviour - What unexpectedly happens?
well, no. On virtualbox, it works fine. But when I boot from USB with Cosmos on it (installed via [Rufus](https://rufus.ie)) on my old laptop (with 32bit CPU {visit my [another issue](https://github.com/CosmosOS/Cosmos/issues/2581) for more info}) it boots normally, it also shows the line it is supposed to! But the keyboard is not doing anything. (There is not single working key) And yes, I set the keyboard map to EN Querty... Thank you!
(Im using the ISO file from "User\source\repos\myproject\myproject\bin\Debug\net6.0\myproject.iso" because when i click "run" in vs with run option on "iso file" mode or any else, it shows an error. idk why. so im only doing "build")

#### Reproduction - How did you get this error to appear?
Booted Cosmos up

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest?

**Comment by GoldenretriverYT** [comment]
USB keyboards are not supported so make sure its a PS/2 keyboard or you have PS/2 keyboard emulation enabled

**Comment by slavekrouta** [comment]
> USB keyboards are not supported so make sure its a PS/2 keyboard or you have PS/2 keyboard emulation enabled

oh, I meant laptop.

**Comment by AnErrupTion** [comment]
@slavekrouta The laptop's keyboard may or may not use PS/2. If it doesn't and PS/2 emulation isn't enabled or isn't availabie in the firmware, you won't be able to use it in Cosmos yet.

**Comment by slavekrouta** [comment]
oh.

**Comment by slavekrouta** [comment]
okay
