### ISSUE TITLE
No Disk Found

### ISSUE THREAD

**Issue by powderedd** [CosmosOS/Cosmos#2582]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Probably cosmos VFS

#### Expected Behaviour - What do you think that should happen?
It works fine on VMWARE

#### Actual Behaviour - What unexpectedly happens?
I get an error saying "NO DISK FOUND".

#### Reproduction - How did you get this error to appear?
I booted my ISO on a real pc and it displayed it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I built using the User Kit

**Comment by zarlo** [comment]
do you have a sata disk (hdd/ssd) using MBR that is formatted with FAT32

**Comment by powderedd** [comment]
no, just a sata hdd with windows 7 installed
i think its not fat32
does it need to be fat32?

**Comment by powderedd** [comment]
if it does, is there a way to access the filesystem of the USB flashdrive???

**Comment by zarlo** [comment]
yes right now cosmos cosmos can only read FAT32 filesystems and no you cant read off the usb

**Comment by powderedd** [comment]
oh
