### ISSUE TITLE
Ubuntu kernel paging request bug when installing under QEMU

### ISSUE THREAD

**Issue by MEMESCOEP** [CosmosOS/Cosmos#2586]
**Describe the problem**
When trying to install Cosmos on Ubuntu server 18.04 under QEMU, I'm recieving this error:
![image](https://user-images.githubusercontent.com/67339620/220960188-18ac8948-34f1-4bc0-8021-fd8fe2d18cd3.png)

**Steps of installation up to now**
1. Clone the cosmos repository
2. Enter the cosmos folder and run `make all`

**Expected behavior**
Cosmos should compile and install with no errors.

**Logs**
I could not find any build logs.

**Setup (please complete the following information):**
 - Cosmos Version: Devkit
 - Running with or without `sudo` produces the same result
 - Visual Studio Version: None

**Comment by Jspa2** [comment]
That is a kernel panic, not a cosmos error

**Comment by MishaTY** [comment]
This is an issue with ubuntu/qemu
