### ISSUE TITLE
Cosmos.Core.CPU.GetCPUCycleSpeed(); Causes CPU exception

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2594]
#### Area of Cosmos - What area of Cosmos are we dealing with?
`Cosmos.Core.CPU.GetCPUCycleSpeed();`

#### Expected Behaviour - What do you think that should happen?
Should get CPU's cycle speed

#### Actual Behaviour - What unexpectedly happens?
Throws a normal exception and afterwards throws a CPU exception (if you do a try & catch)

#### Reproduction - How did you get this error to appear?
Doing `Cosmos.Core.CPU.GetCPUCycleSpeed();`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Some version from ‎19th‎ February‎ 2023

![image](https://user-images.githubusercontent.com/109512837/222951402-f8aa2b95-93a7-4209-8cdf-a219b71f073b.png)

![image](https://user-images.githubusercontent.com/109512837/222951410-3c5ee8c0-3dd3-4254-8309-ca123a334e65.png)

**Comment by quajak** [comment]
What VM are you using?

**Comment by 9xbt** [comment]
Im using VMware Workstation Pro. Also I think I didnt have this issue before, which is weird

**Comment by AsertCreator** [comment]
`CPU.GetCPUCycleSpeed()` uses an extraction method (?). it enumerates through CPU model name and seeks for number, which may be a frequency. but AMD CPUs, do not usually have frequency in their model name, unlike Intel ones. therefore, method may not be able to correctly get multiplier and number, hence the exception. did you switch to AMD recently?

**Comment by 9xbt** [comment]
Yeah. That build is from December

**Comment by 9xbt** [comment]
Yes, I did

**Comment by 9xbt** [comment]
Okay then. Btw, is it possible to have a list of AMD CPUs with their frequencies so the function works in AMDs?

**Comment by AsertCreator** [comment]
theoretically - yes, practically - there are too many AMD CPUs out there, so it will take a lot of time
