### ISSUE TITLE
Help with Cosmos.Hardware

### ISSUE THREAD

**Issue by SteveFiggy** [CosmosOS/Cosmos#260]
I'm trying to implement GLNFS into my OS and it requires Comos.Hardware. Everytime I try to compile I get this error

Error occurred while invoking IL2CPU.	GUI TestBoot	E:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31

**Comment by mterwoord** [comment]
Cosmos.Hardware is old, and isn't valid anymore.

Your best bet is to adjust it to latest kernel. Also, you didn't paste the real error....

**Comment by SteveFiggy** [comment]
great

**Comment by charlesbetros** [comment]
Is this resolved?

**Comment by lukaandjelkovic** [comment]
@SteveFiggy Use Cosmos.HAL, Cosmos.Hardware is very oboselte.
