### ISSUE TITLE
cosmos apparently wont draw lines?

### ISSUE THREAD

**Issue by st33theducc** [CosmosOS/Cosmos#2602]
#### Area of Cosmos - What area of Cosmos are we dealing with?
gui drawing/graphics

#### Expected Behaviour - What do you think that should happen?
the ui should actually draw for god's sake

#### Actual Behaviour - What unexpectedly happens?
it goes to a weird glitched out screen like this
![image](https://user-images.githubusercontent.com/87030486/224769197-c286c00f-c9e6-40bf-a93b-141d6d567e74.png)

#### Reproduction - How did you get this error to appear?
tried to draw lines in different colors

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
userkit

**Comment by 9xbt** [comment]
Can you show us the code?

**Comment by terminal-cs** [comment]
This is not a line issue, You don't appear to be using the right graphics driver.

**Comment by ptobuon** [comment]
if you want to avoid these errors, use FullScreenCanvas.GetFullScreenCanvas(); to find the best driver and resolution. If you are usino VBE make sure that vbe multiboot is enabled in project settings. If you already solved this issue, please close it. Thanks
