### ISSUE TITLE
Dictionary with TKey as string does not allow using "" as key

### ISSUE THREAD

**Issue by GoldenretriverYT** [CosmosOS/Cosmos#2609]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos or IL2CPU

#### Expected Behaviour - What do you think that should happen?
This should work fine as it also works with no issues in regular .NET

#### Actual Behaviour - What unexpectedly happens?
The operating system crashes due to stack corruption when adding the value

#### Reproduction - How did you get this error to appear?
```cs
var groups = new Dictionary<string, Dictionary<string, string>>();
// this does not crash:
groups.Add("_", new());
// this does:
groups.Add("", new());
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest DevKit

**Comment by zarlo** [comment]
my guess this might be a bug in GetHashCode() for strings

**Comment by GoldenretriverYT** [comment]
Hm I just tried to execute `"".GetHashCode()` and it gave me a normal result so I am not sure about that

**Comment by zarlo** [comment]
okay i have been looking at the code for Dictionary<string,T> and it looks like GetNonRandomizedHashCode is used ill add a check for blank strings note im not 100% on if this would fix if my not even be the issuse as it dose have logic for if strings are blank 

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/NonRandomizedStringEqualityComparer.cs
