### ISSUE TITLE
VmWare Player BlockNum disabled on startup (and meaning inverted)

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#261]
When CosmoOS start blocknum key that I usually have enabled is disabled by the OS. I suggest that it remains in his actual state (that is do not change it). If I exit from the VM blocknum is enabled again but when I return on it is disabled again.
The meaning of blocknum seems inverted too! When it is disabled the number are printed while when enabled '2' becomes arrow down.

**Comment by charlesbetros** [comment]
Numlock?

**Comment by fanoI** [comment]
Yes sorry I'm Italian keyboard is called "Bloc Num"!

**Comment by Cyber4** [comment]
VMware has a built in feature that saves keyboard states when inside your guest
