### ISSUE TITLE
method been emitted twice

### ISSUE THREAD

**Issue by zarlo** [CosmosOS/Cosmos#2619]
#### Area of Cosmos - What area of Cosmos are we dealing with?
likely il2cpu

it looks like a method is been emitted twice

build log https://gist.github.com/zarlo/05326ba30698d4b3b9216c8d77a4b9bb

#### Reproduction - How did you get this error to appear?
clone https://gitlab.com/zarlo/cosmos.zarlo/-/tree/temp-bug/ and build Test

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit 
cosmos: 721904a27703b65c6456ebc17bb45516d6dded4f (current master will work too)
il2cpu: be7250ec43730dcd9e78bafee1cec83576e1c22c
x#: 63f738b4f754a922229d45e16adf535eac3fa7a8
common: dbba1150f05f0384f3bc833a34172719f2d89a87

**Comment by quajak** [comment]
I assume this is caused by https://github.com/CosmosOS/IL2CPU/issues/150

**Comment by zarlo** [comment]
looks like it could be
