### ISSUE TITLE
Project don't working

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2622]
Project don't work.
![image](https://user-images.githubusercontent.com/79642857/227963684-e979e0cf-7268-450a-8b73-8a9a004ee08d.png)

code:

using Cosmos.System.Graphics;
using System;
using System.Drawing;
using sus = Cosmos.System;
using System.Windows.Input;

namespace GraphicTest
{
    public class Kernel : sus.Kernel
    {
        public static Canvas canvas;
        public static bool iswindow;
        public static bool issetting;
        public static bool issynth;
        public static bool iscolors;
        public static bool iscalc;
        public static bool istaskm;
        public static bool isalwaysshowfps = false;
        public static int memsec;
        public static bool iscalcready = false;
        public static string first;
        public static string second;
        public static long firstI;
        public static long secondI;
        public static float c;
        public static Color colora;

        protected override void BeforeRun()
        {
            memsec = 61;
            iswindow = false;
            issetting = false;
            iscolors = false;
            issynth = false;
            iscalc = false;
            colora = Color.LimeGreen;
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("QeweOS IS STARTING...");
            Console.Beep(3000, 500);
            Console.Beep(2000, 250);
            Console.Beep(4000, 250);
            Console.Beep(2000, 250);
            Console.Beep(4000, 250);
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(640, 480, ColorDepth.ColorDepth32));
            sus.MouseManager.ScreenHeight = 480;
            sus.MouseManager.ScreenWidth = 640;
            sus.MouseManager.X = 320;
            sus.MouseManager.Y = 240;
            qeweOS.FpsShower.ShouldRender = true;
        }
        public static bool CheackClick(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Left)
                    {
                        sus.MouseManager.MouseState = sus.MouseState.None;
                        return true;
                    }
                }
            }
            return false;
        }
        public static bool CheackClickInfinity(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Left)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        public static bool CheackPos(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    return true;
                }
            }
            return false;
        }
        public static bool CheackClickRight(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Right)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        protected override void Run()
        {
            try
            {
                canvas.Clear(colora);
                Color pen = Color.White;
                var X = sus.MouseManager.X;
                var Y = sus.MouseManager.Y;
                int mont;
                mont = DateTime.Now.Month;
                string montt = "";
                switch (mont)
                {
                    case 01:
                        montt = "January";
                        break;
                    case 02:
                        montt = "February";
                        break;
                    case 03:
                        montt = "March";
                        break;
                    case 04:
                        montt = "April";
                        break;
                    case 05:
                        montt = "May";
                        break;
                    case 06:
                        montt = "June";
                        break;
                    case 07:
                        montt = "July";
                        break;
                    case 08:
                        montt = "August";
                        break;
                    case 09:
                        montt = "September :(";
                        break;
                    case 10:
                        montt = "October";
                        break;
                    case 11:
                        montt = "November";
                        break;
                    case 12:
                        montt = "December";
                        break;
                }
                if (CheackPos(615, 0, 25, 25))
                {
                    if (iswindow == false)
                    {
                        iswindow = true;
                    }
                }
                if (CheackClickRight(25, 30, 300, 150))
                {
                    if (issetting == true)
                    {
                        issetting = false;
                    }
                }
                if (CheackClickRight(25, 30, 270, 75))
                {
                    if (iscolors == true)
                    {
                        iscolors = false;
                    }
                }
                if (CheackClickRight(25, 30, 245, 335))
                {
                    if (iscalc == true)
                    {
                        iscalc = false;
                    }
                }
                if (CheackClickRight(485, 390, 150, 85))
                {
                    if (istaskm == true)
                    {
                        istaskm = false;
                    }
                }
                if (CheackClickRight(25, 30, 315, 40))
                {
                    if (issynth == true)
                    {
                        issynth = false;
                    }
                }
                if (CheackClick(505, 70, 88, 8))
                {
                    if (iswindow == true)
                    {
                        if (issynth == false)
                        {
                            iscolors = false;
                            iswindow = false;
                            issetting = false;
                            issynth = true;
                            iscalc = false;
                        }
                    }
                }
                if (CheackClick(505, 40, 88, 8))
                {
                    if (iswindow == true)
                    {
                        if (issetting == false)
                        {
                            iscolors = false;
                            iswindow = false;
                            issynth = false;
                            issetting = true;
                            iscalc = false;
                        }
                    }
                }
                if (CheackClick(505, 55, 48, 8))
                {
                    if (iswindow == true)
                    {
                        if (iscolors == false)
                        {
                            issetting = false;
                            iswindow = false;
                            iscolors = true;
                            issynth = false;
                            iscalc = false;
                        }
                    }
                }
                if (CheackClick(505, 100, 128, 8))
                {
                    if (iswindow == true)
                    {
                        if (istaskm == false)
                        {
                            istaskm = true;
                            issetting = false;
                            iswindow = false;
                            iscolors = false;
                            issynth = false;
                            iscalc = false;
                        }
                    }
                }
                if (CheackClick(505, 85, 80, 8))
                {
                    if (iswindow == true)
                    {
                        if (iscalc == false)
                        {
                            c = 0;
                            firstI = 0;
                            secondI = 0;
                            first = "";
                            second = "";
                            iscalcready = false;
                            issetting = false;
                            iswindow = false;
                            iscolors = false;
                            issynth = false;
                            iscalc = true;
                        }
                    }
                }
                if (sus.MouseManager.MouseState == sus.MouseState.Right)
                {
                    if (iswindow == true)
                    {
                        iswindow = false;
                    }
                }
                
                if (CheackClick(505, 195, 30, 30))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Shutdown();
                    }
                }
                if (CheackClick(540, 195, 30, 30))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Reboot();
                    }
                }

                if (isalwaysshowfps == true)
                {
                    canvas.DrawFilledRectangle(Color.Black, 0, 460, 66, 20);
                    txtxtx.FontDrawer.WriteText("FPS:" + (qeweOS.FpsShower.FPS / 2).ToString(), 5, 465, Color.White);
                }

                if (issetting == true)
                {
                    canvas.DrawFilledRectangle(Color.LightGray, 25, 30, 300, 103);
                    txtxtx.FontDrawer.WriteText("Computer Information", 80, 40, Color.Black);
                    txtxtx.FontDrawer.WriteText("RAM: " + Cosmos.Core.CPU.GetAmountOfRAM().ToString() + "MB", 30, 55, Color.Black);
                    txtxtx.FontDrawer.WriteText("Resolution: 640x480, Color Depth: 32bit", 30, 70, Color.Black);
                    txtxtx.FontDrawer.WriteText("CPU Vendor: " + Cosmos.Core.CPU.GetCPUVendorName(), 30, 85, Color.Black);
                    txtxtx.FontDrawer.WriteText("Frames Per Second: " + (qeweOS.FpsShower.FPS / 2).ToString(), 30, 100, Color.Black);
                    txtxtx.FontDrawer.WriteText("QeweOS Version: Open Lolys Alpha 1H", 30, 115, Color.Black);
                    if (CheackClick(30, 100, 176, 15))
                    {
                        if (isalwaysshowfps == false)
                        {
                            isalwaysshowfps = true;
                        }
                        else if (isalwaysshowfps == true)
                        {
                            isalwaysshowfps = false;
                        }
                    }
                }

                if (issynth == true)
                {
                    canvas.DrawFilledRectangle(Color.LightGray, 25, 30, 315, 40);
                    txtxtx.FontDrawer.WriteText("Use keyboard for play! A,S,D,F,G,H,J,K", 30, 35, Color.Black);
                    txtxtx.FontDrawer.WriteText("Press ESC to quit!", 30, 50, Color.Black);
                    switch (Console.ReadKey(true).Key)
                    {
                        case ConsoleKey.A:
                            Console.Beep(500, 1);
                            break;
                        case ConsoleKey.S:
                            Console.Beep(1000, 1);
                            break;
                        case ConsoleKey.D:
                            Console.Beep(2000, 1);
                            break;
                        case ConsoleKey.F:
                            Console.Beep(3000, 1);
                            break;
                        case ConsoleKey.G:
                            Console.Beep(4500, 1);
                            break;
                        case ConsoleKey.H:
                            Console.Beep(5000, 1);
                            break;
                        case ConsoleKey.J:
                            Console.Beep(6000, 1);
                            break;
                        case ConsoleKey.K:
                            Console.Beep(7000, 1);
                            break;
                        case ConsoleKey.Escape:
                            issynth = false;
                            break;
                        default:
                            break;
                    }
                }

                if (iscolors == true)
                {
                    canvas.DrawFilledRectangle(Color.LightGray, 25, 30, 270, 75);
                    canvas.DrawFilledRectangle(Color.Yellow, 30, 35, 75, 30);
                    canvas.DrawFilledRectangle(Color.Red, 110, 35, 75, 30);
                    canvas.DrawFilledRectangle(Color.Green, 190, 35, 75, 30);
                    canvas.DrawFilledRectangle(Color.Blue, 30, 70, 75, 30);
                    canvas.DrawFilledRectangle(Color.Black, 110, 70, 75, 30);
                    canvas.DrawFilledRectangle(Color.LimeGreen, 190, 70, 75, 30);
                    if (CheackClick(30, 35, 75, 30))
                    {
                        colora = Color.Yellow;
                    }
                    if (CheackClick(110, 35, 75, 30))
                    {
                        colora = Color.Red;
                    }
                    if (CheackClick(190, 35, 75, 30))
                    {
                        colora = Color.Green;
                    }
                    if (CheackClick(30, 70, 75, 30))
                    {
                        colora = Color.Blue;
                    }
                    if (CheackClick(110, 70, 75, 30))
                    {
                        colora = Color.Black;
                    }
                    if (CheackClick(190, 70, 75, 30))
                    {
                        colora = Color.LimeGreen;
                    }
                }

                if (iswindow == true)
                {
                    canvas.DrawFilledRectangle(Color.YellowGreen, 500, 30, 140, 200);
                    txtxtx.FontDrawer.WriteText("Information", 505, 40, Color.Black);
                    txtxtx.FontDrawer.WriteText("Colors", 505, 55, Color.Black);
                    txtxtx.FontDrawer.WriteText("Synthesator", 505, 70, Color.Black);
                    txtxtx.FontDrawer.WriteText("Calculator", 505, 85, Color.Black);
                    txtxtx.FontDrawer.WriteText("Hardware Monitor", 505, 100, Color.Black);
                    canvas.DrawFilledRectangle(Color.Red, 505, 195, 30, 30);
                    canvas.DrawFilledRectangle(Color.Orange, 540, 195, 30, 30);
                }

                if (istaskm == true)
                {
                    long ponos = Cosmos.Core.GCImplementation.GetUsedRAM() / 1024 / 1024;
                    canvas.DrawFilledRectangle(Color.LightGray, 485, 390, 150, 85);
                    txtxtx.FontDrawer.WriteText("Hardware Monitor", 490, 395, Color.Black);
                    txtxtx.FontDrawer.WriteText("RAM Usage in MBs:", 490, 410, Color.Black);
                    canvas.DrawFilledRectangle(Color.DarkGreen, 490, 425, 100, 20);
                    canvas.DrawFilledRectangle(Color.Lime, 490, 425, (int)(ponos / Cosmos.Core.CPU.GetAmountOfRAM()) * 100, 20);
                    txtxtx.FontDrawer.WriteText(ponos.ToString(), 495, 430, Color.Black);
                    txtxtx.FontDrawer.WriteText("Frames Per Second: " + (qeweOS.FpsShower.FPS / 2).ToString(), 490, 450, Color.Black);
                }

                if (iscalc == true)
                {
                    try
                    {
                        canvas.DrawFilledRectangle(Color.DarkGray, 25, 30, 245, 335);
                        txtxtx.FontDrawer.WriteText("Calculator", 160, 35, Color.Black);
                        //cifri buttons - 1
                        canvas.DrawFilledRectangle(Color.Gray, 30, 140, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 80, 140, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 130, 140, 40, 40);
                        txtxtx.FontDrawer.WriteText("1", 50, 160, Color.Black);
                        txtxtx.FontDrawer.WriteText("2", 100, 160, Color.Black);
                        txtxtx.FontDrawer.WriteText("3", 150, 160, Color.Black);
                        //2
                        canvas.DrawFilledRectangle(Color.Gray, 30, 190, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 80, 190, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 130, 190, 40, 40);
                        txtxtx.FontDrawer.WriteText("4", 50, 210, Color.Black);
                        txtxtx.FontDrawer.WriteText("5", 100, 210, Color.Black);
                        txtxtx.FontDrawer.WriteText("6", 150, 210, Color.Black);
                        //3
                        canvas.DrawFilledRectangle(Color.Gray, 30, 240, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 80, 240, 40, 40);
                        canvas.DrawFilledRectangle(Color.Gray, 130, 240, 40, 40);
                        txtxtx.FontDrawer.WriteText("7", 50, 260, Color.Black);
                        txtxtx.FontDrawer.WriteText("8", 100, 260, Color.Black);
                        txtxtx.FontDrawer.WriteText("9", 150, 260, Color.Black);
                        //0
                        canvas.DrawFilledRectangle(Color.Gray, 80, 290, 40, 40);
                        txtxtx.FontDrawer.WriteText("0", 100, 310, Color.Black);
                        canvas.DrawFilledRectangle(Color.Gray, 130, 290, 40, 40);
                        txtxtx.FontDrawer.WriteText("R", 150, 310, Color.Black);
                        canvas.DrawFilledRectangle(Color.Gray, 30, 290, 40, 40);
                        txtxtx.FontDrawer.WriteText("-", 50, 310, Color.Black);
                        //end
                        //button press
                        //1
                        if (CheackClick(30, 140, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "1";
                            }
                            else
                            {
                                second += "1";
                            }
                        }
                        //2
                        if (CheackClick(80, 140, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "2";
                            }
                            else
                            {
                                second += "2";
                            }
                        }
                        //3
                        if (CheackClick(130, 140, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "3";
                            }
                            else
                            {
                                second += "3";
                            }
                        }
                        //4
                        if (CheackClick(30, 190, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "4";
                            }
                            else
                            {
                                second += "4";
                            }
                        }
                        //5
                        if (CheackClick(80, 190, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "5";
                            }
                            else
                            {
                                second += "5";
                            }
                        }
                        //6
                        if (CheackClick(130, 190, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "6";
                            }
                            else
                            {
                                second += "6";
                            }
                        }
                        //7
                        if (CheackClick(30, 240, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "7";
                            }
                            else
                            {
                                second += "7";
                            }
                        }
                        //8
                        if (CheackClick(80, 240, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "8";
                            }
                            else
                            {
                                second += "8";
                            }
                        }
                        //9
                        if (CheackClick(130, 240, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "9";
                            }
                            else
                            {
                                second += "9";
                            }
                        }
                        //0
                        if (CheackClick(80, 290, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "0";
                            }
                            else
                            {
                                second += "0";
                            }
                        }
                        if (CheackClick(30, 290, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                first += "-";
                            }
                            else
                            {
                                second += "-";
                            }
                        }
                        //R
                        if (CheackClick(130, 290, 40, 40))
                        {
                            if (iscalcready == false)
                            {
                                iscalcready = true;
                            }
                            else if(iscalcready == true)
                            {
                                iscalcready = false;
                            }
                        }
                        //end
                        if (iscalcready == false)
                        {
                            canvas.DrawFilledRectangle(Color.Green, 30, 50, 190, 15);
                            canvas.DrawFilledRectangle(Color.White, 30, 85, 190, 15);
                        }
                        if (iscalcready == true)
                        {
                            canvas.DrawFilledRectangle(Color.White, 30, 50, 190, 15);
                            canvas.DrawFilledRectangle(Color.Green, 30, 85, 190, 15);
                        }
                        canvas.DrawFilledRectangle(Color.White, 30, 115, 190, 15);
                        txtxtx.FontDrawer.WriteText(first, 35, 54, Color.Black);
                        txtxtx.FontDrawer.WriteText(second, 35, 89, Color.Black);
                        txtxtx.FontDrawer.WriteText("Plus", 30, 70, Color.Black);
                        txtxtx.FontDrawer.WriteText("Minus", 70, 70, Color.Black);
                        txtxtx.FontDrawer.WriteText("Devide", 115, 70, Color.Black);
                        txtxtx.FontDrawer.WriteText("Multiply", 185, 70, Color.Black);
                        firstI = Convert.ToInt64(first);
                        secondI = Convert.ToInt64(second);
                        if (CheackClickInfinity(30, 70, 32, 8))
                        {
                            c = firstI + secondI;
                            txtxtx.FontDrawer.WriteText(c.ToString(), 30, 119, Color.Black);
                        }
                        if (CheackClickInfinity(70, 70, 40, 8))
                        {
                            c = firstI - secondI;
                            txtxtx.FontDrawer.WriteText(c.ToString(), 30, 119, Color.Black);
                        }
                        if (CheackClickInfinity(115, 70, 48, 8))
                        {
                            c = firstI / secondI;
                            txtxtx.FontDrawer.WriteText(c.ToString(), 30, 119, Color.Black);
                        }
                        if (CheackClickInfinity(185, 70, 64, 8))
                        {
                            c = firstI * secondI;
                            txtxtx.FontDrawer.WriteText(c.ToString(), 30, 119, Color.Black);
                        }
                    }
                    catch (Exception){}
                }

                canvas.DrawFilledRectangle(Color.Black, 0, 0, 640, 30);

                canvas.DrawFilledCircle(Color.Green, 625, 15, 10);

                txtxtx.FontDrawer.WriteText("QeweOS", 272, 15, Color.White);

                if (memsec != DateTime.Now.Second)
                {
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Hour.ToString() + ":" + DateTime.Now.Minute.ToString() + ":" + DateTime.Now.Second.ToString(), 5, 1, Color.White);
                    txtxtx.FontDrawer.WriteText(montt, 5, 10, Color.White);
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Day.ToString() + "th " + DateTime.Now.Year.ToString(), 5, 19, Color.White);
                }

                canvas.DrawLine(pen, (int)X + 10, (int)Y + 10, (int)X, (int)Y);
                canvas.DrawLine(pen, (int)X, (int)Y, (int)X, (int)Y + 6);
                canvas.DrawLine(pen, (int)X, (int)Y, (int)X + 6, (int)Y);

                Cosmos.Core.Memory.Heap.Collect();
                canvas.Display();
            }
            catch (Exception)
            {
                sus.Power.Shutdown();
            }
        }
    }
}

heres commented code

/*using Cosmos.System.Graphics;
using System;
using System.Drawing;
using sus = Cosmos.System;

namespace GraphicTest
{
    public class Kernel : sus.Kernel
    {
        public static Canvas canvas;
        public static bool iswindow;
        public static int memsec;

        protected override void BeforeRun()
        {
            memsec = 61;
            iswindow = false;
            Console.WriteLine("QeweOS booted successfully, BUT IF YOU SEE THIS, OS BOOTED UNCORRECTLY");
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(320, 240, ColorDepth.ColorDepth32));
            sus.MouseManager.ScreenHeight = 240;
            sus.MouseManager.ScreenWidth = 320;
            sus.MouseManager.X = 160;
            sus.MouseManager.Y = 120;
        }
        public static bool CheackClick(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Left)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        public static bool CheackPos(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    return true;
                }
            }
            return false;
        }
        public static bool CheackClickRight(int x, int y, int w, int h)
        {
            if (sus.MouseManager.X <= x + w && sus.MouseManager.X >= x)
            {
                if (sus.MouseManager.Y <= y + h && sus.MouseManager.Y >= y)
                {
                    if (sus.MouseManager.MouseState == sus.MouseState.Right)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        protected override void Run()
        {
            try
            {
                canvas.Clear(Color.LimeGreen);
                Color pen = Color.White;
                var X = sus.MouseManager.X;
                var Y = sus.MouseManager.Y;
                int mont;
                mont = DateTime.Now.Month;
                string montt = "";
                switch (mont)
                {
                    case 01:
                        montt = "January";
                        break;
                    case 02:
                        montt = "February";
                        break;
                    case 03:
                        montt = "March";
                        break;
                    case 04:
                        montt = "April";
                        break;
                    case 05:
                        montt = "May";
                        break;
                    case 06:
                        montt = "June";
                        break;
                    case 07:
                        montt = "July";
                        break;
                    case 08:
                        montt = "August";
                        break;
                    case 09:
                        montt = "September :(";
                        break;
                    case 10:
                        montt = "October";
                        break;
                    case 11:
                        montt = "November";
                        break;
                    case 12:
                        montt = "December";
                        break;
                }
                if (CheackPos(310, 0, 10, 10))
                {
                    if (iswindow == false)
                    {
                        iswindow = true;
                    }
                }
                if (sus.MouseManager.MouseState == sus.MouseState.Right)
                {
                    if (iswindow == true)
                    {
                        iswindow = false;
                    }
                }
                if (CheackClick(280, 50, 15, 15))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Shutdown();
                    }
                }
                if (CheackClick(300, 50, 15, 15))
                {
                    if (iswindow == true)
                    {
                        sus.Power.Reboot();
                    }
                }

                if (iswindow == true)
                {
                    canvas.DrawFilledRectangle(Color.Yellow, 275, 10, 40, 60);
                    canvas.DrawFilledRectangle(Color.Red, 280, 50, 15, 15);
                    canvas.DrawFilledRectangle(Color.Orange, 300, 50, 15, 15);
                }

                //canvas.DrawFilledRectangle(Color.Green, 0, 0, 640, 30);

                //canvas.DrawFilledCircle(Color.Green, 625, 15, 10);

                if (memsec != DateTime.Now.Second)
                {
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Hour.ToString() + ":" + DateTime.Now.Minute.ToString() + ":" + DateTime.Now.Second.ToString(), 5, 1, 63);
                    txtxtx.FontDrawer.WriteText(montt, 5, 10, 36);
                    txtxtx.FontDrawer.WriteText(DateTime.Now.Day.ToString() + "th " + DateTime.Now.Year.ToString(), 5, 19, 36);
                }

                //txtxtx.FontDrawer.WriteText("RAM: " + Cosmos.Core.CPU.GetAmountOfRAM().ToString() + "MB", 150, 15, 0);
                //txtxtx.FontDrawer.WriteText("QeweOS Executive", 250, 15, 0);

                canvas.DrawLine(pen, (int)X + 5, (int)Y + 5, (int)X, (int)Y);
                canvas.DrawLine(pen, (int)X, (int)Y, (int)X, (int)Y + 3);
                canvas.DrawLine(pen, (int)X, (int)Y, (int)X + 3, (int)Y);

                canvas.Display();
            }
            catch (Exception)
            {
                sus.Power.Shutdown();
            }
        }
    }
}*/

**Comment by lentas1** [comment]
sorry, i cant help, because you have so much code

**Comment by lentas1** [comment]
but you can test it on real hw

**Comment by MishaTy** [comment]
Please provide a smaller project.
