### ISSUE TITLE
Avast say that Cosmos is trojan!

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#263]
There is info i got:
Virus type : MSIL Agent CBA [TRJ]
Called from : VBCSCompiler.exe
Malicous file : Cosmos.Build.Builder.exe
Every time i update my devkit i need to disable Avast. Is repsitory infected?

**Comment by CSharpLover** [comment]
I think not, I have both norton and kaspersky, and there is no warning.

**Comment by fanoI** [comment]
It pretty obvious that Cosmos is not a trojan but IMHO the installer is doing something that triggers virus behavior!
I'm using Avast because is the only anti virus that does not annoy with commercial pop up, udate pop up, upgrade pop up and so on... it does his things silently.
