### ISSUE TITLE
It refuses to create an .iso.

### ISSUE THREAD

**Issue by SyeGD** [CosmosOS/Cosmos#2630]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugging

#### Expected Behaviour - What do you think that should happen?
Should create a .iso file.

#### Actual Behaviour - What unexpectedly happens?
Doesn't create a .iso file.

#### Reproduction - How did you get this error to appear?
Clicking the debug button in VS2022

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit.

**Comment by Kiirx** [comment]
Is there any error?

**Comment by SyeGD** [comment]
No there isn't an error.
