### ISSUE TITLE
Canvas not working.

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [CosmosOS/Cosmos#2634]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics, mostly canvas.

#### Expected Behaviour - What do you think that should happen?
Canvas should open up properly

#### Actual Behaviour - What unexpectedly happens?
The VM crashes.

#### Reproduction - How did you get this error to appear?
Use any type of canvas.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit

**Comment by MishaTy** [comment]
Please provide more details. How does the vm crash? How do you use the canvas?
