### ISSUE TITLE
FAT filesystem formatting doesn't work

### ISSUE THREAD

**Issue by husaral2** [CosmosOS/Cosmos#2636]
#### Area of Cosmos
Filesystem

#### Expected Behaviour - What do you think that should happen?
After the formatting, the FS should work.

#### Actual Behaviour - What unexpectedly happens?
While using a preformatted disk, the VFS works fine. But when I format the disk to FAT32 (in Cosmos) again, I can't do anything with files. When I try to format it again, it says "FAT signature not found".

#### Reproduction - How did you get this error to appear?
`
Cosmos.System.FileSystem.FAT.FatFileSystemFactory factory = new Cosmos.System.FileSystem.FAT.FatFileSystemFactory();
            Cosmos.System.FileSystem.VFS.FileSystemManager.Register(factory);
            Cosmos.System.FileSystem.FileSystem fs = factory.Create(|partitionyouwanttoformat|, "0:", (long)device.BlockSize);
            fs.Format("FAT32", false);
`
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit

**Comment by terminal-cs** [comment]
Formatting is currently broken iirc

**Comment by audiotore482** [comment]
> Formatting is currently broken iirc

Yeah, it is. Not sure what even broke it.
I will try to fix it lmao...

**Comment by husaral2** [comment]
It probably didn't work because it started to write from the first sector of disk (which contains the information for partitions). I added the ability for partition information writing on the partition table so it should work now but the FS still needs a lot of bugfixes.
