### ISSUE TITLE
Codepage 858 doesn't work properly

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2638]
#### Area of Cosmos - What area of Cosmos are we dealing with?
ExtendedASCII's Codepage 858

#### Expected Behaviour - What do you think that should happen?
Should print `Á` properly

#### Actual Behaviour - What unexpectedly happens?
Prints what `Á` (0xB5) is in Codepage 437, which is `╡`

#### Reproduction - How did you get this error to appear?
By doing `Console.OutputEncoding = Sys.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(858);`, then doing `Console.WriteLine("Á");`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by 9xbt** [comment]
How can I change the font then?

**Comment by quajak** [comment]
See here for how to change the VGA font
https://github.com/CosmosOS/Cosmos/blob/77c4b7f298827d2929aec5ecf3ebf58ca1c1ec2d/Tests/Kernels/GraphicTest/Kernel.cs#L164-L165

You will need one for codepage 858

**Comment by 9xbt** [comment]
Is there a pre-made one btw? I don't know how to make one that's compatible with PCScreenFont

**Comment by quajak** [comment]
I don't think there is one for Spanish. You might have to either make one using a tool like https://github.com/quajak/afe or add support for a more advanced font format.

**Comment by 9xbt** [comment]
Well it isn't really necessary to have one for spanish, just one that works with Codepage 858

**Comment by 9xbt** [comment]
But yeah, I'll try your font editor later. Thanks!
