### ISSUE TITLE
OS too slow. . .

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#264]
Before this, i was being in userkit. I upgraded to devkit, and builded it first time. User Kit cosmos was so much faster, and this devkit is like am on old 1945 computer. Graphics very slow, the typing is very slow, loading the PCI devices is very slow . . . Everything is slower in devkit than userkit!

**Comment by mterwoord** [comment]
devkit is a self-built userkit.

DO you have debugging enabled now, while you didn't have before?

**Comment by lukaandjelkovic** [comment]
no , in userkit was debugging enabled and here is debugging enabled.

**Comment by lukaandjelkovic** [comment]
if i set it to Release i get : System.Exception: OpCode IL_014D: Dup tries to pop more stuff from analytical stack than there is!

**Comment by lukaandjelkovic** [comment]
For some part of my OS.

**Comment by mterwoord** [comment]
Like i told you a bunch of times before: don't pick release builds for c#. It's not possible yet.

**Comment by lukaandjelkovic** [comment]
Yea i remember, so WTF is the error? Someone broken that? Or because i commented two lines that give error?

**Comment by lukaandjelkovic** [comment]
Maybe to much IO in my real computer?

**Comment by lukaandjelkovic** [comment]
I even see the green Creating Kernel Class for some time

**Comment by lukaandjelkovic** [comment]
My CPU fan is too loud, the Cosmos in unoptimized here!

**Comment by lukaandjelkovic** [comment]
It stopped when it get finished loading. Everytime i press something in keyboard on console fan get 100%! I stop it get turned off! But when i type now its really fast!

**Comment by lukaandjelkovic** [comment]
I see glitches in VGA too!

**Comment by lukaandjelkovic** [comment]
i will give you ISO to take a look, because is slow! (Dont worry, it will be stand-alone ISO!)

**Comment by lukaandjelkovic** [comment]
https://files.fm/u/nzeqeqo

**Comment by lukaandjelkovic** [comment]
Seem debugging is problem. This ISO is fast!

**Comment by lukaandjelkovic** [comment]
But graphics are still slow!

**Comment by Maldus0** [comment]
Debugging make Cosmos almost 10 or 20x time slower, but that's a normal behavior. Concerning the graphics, it's not yet fully ready so.... 
ps : And please, edit your comment to add a line, you just spamming my mail box ;) (though a new bomb mail attack incoming) 
Thanks !

**Comment by lukaandjelkovic** [comment]
@Maldus0 , but debugging in UserKit is very fast!
