### ISSUE TITLE
COSMOS DEBUG PROBLEM

### ISSUE THREAD

**Issue by samiemrepr** [CosmosOS/Cosmos#2640]
I INSTALLED VS22 and downloaded cosmos latest dev release.
but i get this error when i debug it.

VMWARE Player opens.
Says Waiting for debug connection.
and the something pops up like this
Stack corruption occured at adress 0x02334C0B! Halting now.
my cosmos remote debugger is on.
but i still dont know how to fix the issue.

**Comment by quajak** [comment]
What code are you running?

**Comment by samiemrepr** [comment]
> 

C#

**Comment by terminal-cs** [comment]
> > 
> 
> C#

He is asking what code you are using, not what programming language

**Comment by samiemrepr** [comment]
is there anything wrong?
i started new.

**Comment by samiemrepr** [comment]
![resim](https://user-images.githubusercontent.com/82812868/231277201-7b13c6d0-d200-4ce1-a8ef-2aac45132e09.png)

**Comment by quajak** [comment]
Can you open the ./bin directory and look for a .map file? In that file, please search for the address stated in the error message and report what it says for that line.
