### ISSUE TITLE
Plug

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#265]
Can anyone code this plug?

**System.String** 
I want to convert the byte[] to string, for FAT filesystem.

*System.Number.FormatDecimal()* is actually i need.

**Comment by lukaandjelkovic** [comment]
It say that GetUtf8String doesnt exist.

**Comment by lukaandjelkovic** [comment]
@mterwoord , Can you make System.String plug?
I know you are working on FAT, but this topic is about FAT. How can i write on console the readen bytes?
It need System.String and System.Number.FormatDecimal() for converting to string.

**Comment by charlesbetros** [comment]
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Common/Extensions/ByteConverter.cs
