### ISSUE TITLE
Limine crashses by holding any key before the 'Cosmos layer' starts.

### ISSUE THREAD

**Issue by Nokodev-programming** [CosmosOS/Cosmos#2651]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Limine

#### Expected Behaviour - What do you think that should happen?
Does nothing.

#### Actual Behaviour - What unexpectedly happens?
Fault ocurred to the CPU and entered to a shutdown state.

#### Reproduction - How did you get this error to appear?
Hold any key before the 'cosmos layer' starts.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest version (Tested: Devkit, Cosmos. Custom ziOS fork (Sadly i don't know what version of cosmos is))

#### ISO - What iso where you using? (Custom)
ziOS but any other os with limine will have tthe issue.

### Image - What did the VM show? (Custom)
![Annotation 2023-04-22 114324](https://user-images.githubusercontent.com/86970410/233776436-bd50834d-510d-4954-a1a2-6c48d8bd60c0.png)

**Comment by GoldenretriverYT** [comment]
I can confirm that this is not exclusive to the ziOS fork and that the problem is present on the latest devkit

**Comment by Nokodev-programming** [comment]
Updated issue.

**Comment by 9xbt** [comment]
This seems to be more of a Limine issue than a Cosmos issue, please report the bug [here](https://github.com/limine-bootloader/limine/issues/)

**Comment by Nokodev-programming** [comment]
This issue is closed because turns out cosmos is using a old version of limine, the solution is to update limine to the latest version (currently its semi-fixed)
