### ISSUE TITLE
How to remove "Waiting for debugger connection..." Screen?

### ISSUE THREAD

**Issue by Sheudz** [CosmosOS/Cosmos#2654]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Creating an iso

#### Expected Behaviour - What do you think that should happen?

The operating system should not display a "Waiting for debugger connection..." screen upon startup.

#### Actual Behaviour - What unexpectedly happens?

The "Waiting for debugger connection..." screen is not necessary for me.

#### Reproduction - How did you get this error to appear?

I wanted to build a standalone operating system in C# using COSMOS, but I was unable to build the Release version due to the error shown in this screenshot: https://prnt.sc/J4ArQTK85B2p The Debug version cannot function independently because it requires a debugger connection, as shown here: https://prnt.sc/TFolxc1m-i-w I found a similar issue here: https://github.com/CosmosOS/Cosmos/issues/1096, but the solution provided there did not work for me because I have already disabled remote debugging, as shown in this screenshot: https://prnt.sc/-5LsApzEbBNP

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

I use CosmosUserKit-20221121-vs2022 and Visual Studio 2022

**Comment by GoldenretriverYT** [comment]
Disable debugging in project properties

**Comment by Sheudz** [comment]
Are you talking about Remote Debugging? If you're talking about him, then I turned it off

**Comment by GoldenretriverYT** [comment]
and the "Waiting for debugger connection..." message still appears?

**Comment by Sheudz** [comment]
I also told in the question that I disabled this function, if the screen disappeared, I would not ask this question

**Comment by Sheudz** [comment]
I found a solution, in the project settings in the "Profile" in the "Launch" parameter, I set VMware instead of the ISO image, and it all worked

**Comment by 9xbt** [comment]
![image](https://user-images.githubusercontent.com/109512837/234886682-a41d98bf-de4c-43ea-b83f-b61190c7e73b.png)
Unmark that checkbox right there

**Comment by GoldenretriverYT** [comment]
> ![image](https://user-images.githubusercontent.com/109512837/234886682-a41d98bf-de4c-43ea-b83f-b61190c7e73b.png) Unmark that checkbox right there

Please read the issue before answering, I made the same mistake. They have already done so and have already explained that a second time in the comments.

And they have already fixed it, as they've said in their comment. Not sure why it isnt closed though.
