### ISSUE TITLE
COSMOS unable to start program VS 2022

### ISSUE THREAD

**Issue by Vladimir-Moskalenko** [CosmosOS/Cosmos#2660]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Built to .iso/bootable USB

#### Expected Behaviour - What do you think that should happen?
A window should open with the options to save the OS

#### Actual Behavior - What unexpectedly happens?
The following error is shown:
![image](https://user-images.githubusercontent.com/93604107/235287284-9f0e3434-7084-41f5-9fd8-359f70edecc1.png)
The terminal output:
`Build started...
1>------ Build started: Project: Z_OS, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>Z_OS -> C:\Users\WinBook Pro 14.2\source\repos\Z_OS\Z_OS\bin\Debug\net6.0\Z_OS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\WinBook Pro 14.2\source\repos\Z_OS\Z_OS\bin\Debug\net6.0\Z_OS.dll
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.INT3Label'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:00:22.0973294
1>-g null -f bin -o bin\Debug\net6.0\Z_OS.bin -dBIN_COMPILATION -O1 bin\Debug\net6.0\Z_OS.asm
1>bin\Debug\net6.0\Z_OS.asm:1683505: warning: binary object format does not support global variables
1>Yasm task took 00:00:13.3458651
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error : FileNotFoundException: Could not find file 'C:\Users\WinBook Pro 14.2\source\repos\Z_OS\Z_OS\bin\Debug\net6.0\Z_OS.map'.
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.StreamReader..ctor(String path, Encoding encoding)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at Cosmos.Build.Tasks.ReadNasmMapToDebugInfo.ParseMapFile(String aMapFile) in C:\Development\CosmosOS\Cosmos\source\Cosmos.Build.Tasks\ReadNasmMapToDebugInfo.cs:line 59
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :    at Cosmos.Build.Tasks.ReadNasmMapToDebugInfo.Execute() in C:\Development\CosmosOS\Cosmos\source\Cosmos.Build.Tasks\ReadNasmMapToDebugInfo.cs:line 27
1>C:\Users\WinBook Pro 14.2\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets(308,9): error :
1>ReadNasmMapToDebugInfo task took 00:00:00.0147560
1>Done building project "Z_OS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 11:17 PM and took 38.580 seconds ==========
`

#### Reproduction - How did you get this error to appear?
The error pops up when I run it without a debugger, or build the project to an .iso/USB bootable drive (w/ and w/o debugger)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit.

**Comment by AsertCreator** [comment]
consider disabling .map file extraction, as it's very buggy

**Comment by 9xbt** [comment]
yeah and just ignore it, the iso is built

**Comment by brianberns** [comment]
New user here, getting the same error right out of the box (with map file extraction disabled). It would be nice to be able to run the OS outside of the debugger, as in the tutorial. Any advice on how to fix or work around this problem? Thanks.

**Comment by quajak** [comment]
If you are just building an iso file as here, this will occur but the iso is built
