### ISSUE TITLE
Iso burning has no boatloader

### ISSUE THREAD

**Issue by danielpastoor** [CosmosOS/Cosmos#2661]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Iso Image

#### Expected Behaviour - What do you think that should happen?
That I can boot the Cosmos os from a usb

#### Actual Behaviour - What unexpectedly happens?
![image](https://user-images.githubusercontent.com/28786031/235362920-13481b11-f2e7-4374-8d82-46fabfaeaa15.png)

#### Reproduction - How did you get this error to appear?
Use the iso from the bin folder and burn it to a sd card.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest version of the dev-kit

**Comment by danielpastoor** [comment]
Related to #2401

**Comment by Kiirx** [comment]
It does actually have a bootloader, in this case limine. But yeah this error is weird it may be a problem on their end.

**Comment by danielpastoor** [comment]
This was the latest install Version of portable rufus. Version 4

**Comment by danielpastoor** [comment]
Is linime Packed in the iso?

Because if I use Balena Etcher then I get a different warming: there is no partition found

**Comment by danielpastoor** [comment]
Maybe to give more context I'm trying to boot kunnen custom made Magic-mirror os on a Raspberry-pi 4

**Comment by Kiirx** [comment]
> This was the latest install Version of portable rufus. Version 4
so as I saw there https://github.com/CosmosOS/Cosmos/issues/2661 apparently rufus only supports ISOs made with isolinux or WinPE which isn't our case anymore, I recommend switching over to [Ventoy](https://www.ventoy.net/en/screenshot.html) that is easier to use, can use multiple ISOs while still letting you put your files on the USB key

**Comment by danielpastoor** [comment]
Thank you. I Will try it with that tool

**Comment by Kiirx** [comment]
is it working?
If yes please close the issue.

**Comment by danielpastoor** [comment]
Yes it works. Thank you
