### ISSUE TITLE
Error starting project in vs2022

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#2665]
gives this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.Exception: Error while generating output for file AsmBreak.xs	 projectname	IL2CPU	line1	

doesn't build

**Comment by 9xbt** [comment]
Are you using the devkit or userkit?

**Comment by randomusert** [comment]
userkit

**Comment by randomusert** [comment]
> Are you using the devkit or userkit?

userkit

**Comment by zarlo** [comment]
where are you installing cosmos to?

**Comment by randomusert** [comment]
c:\program files

**Comment by zarlo** [comment]
okay that is why its not working see https://github.com/CosmosOS/Cosmos/issues/1867#issuecomment-872101553

**Comment by randomusert** [comment]
> okay that is why its not working see [#1867 (comment)](https://github.com/CosmosOS/Cosmos/issues/1867#issuecomment-872101553)

does it need to be in path env variable

**Comment by randomusert** [comment]
now it is unable to find these packages: Cosmos.Debug.Kernel
Cosmos.System2
and Cosmos.build

**Comment by zarlo** [comment]
you may need to clean/restore the project

**Comment by zarlo** [comment]
see this https://github.com/CosmosOS/Cosmos/issues/2102#issuecomment-1033642179

**Comment by randomusert** [comment]
thanks
