### ISSUE TITLE
How to get IPv4 address?

### ISSUE THREAD

**Issue by hubabuba444** [CosmosOS/Cosmos#2666]
How to get IPv4 address?

**Comment by ptobuon** [comment]
NetworkConfiguration.CurrentAddress.ToString() is the string.
For more information read here: https://cosmosos.github.io/articles/Kernel/Network.html 
API: https://cosmosos.github.io/api/Cosmos.System.Network.Config.NetworkConfiguration.html

**Comment by hubabuba444** [comment]
Thanks

**Comment by 9xbt** [comment]
Can we close this? Because it seems to be fixed
@zarlo
