### ISSUE TITLE
Trying to set InputEncoding or OutputEncoding results in System.Exception error

### ISSUE THREAD

**Issue by KernelFox0** [CosmosOS/Cosmos#2668]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos ExtendedASCII failing to compile

#### Expected Behaviour - What do you think that should happen?
Adding the ExtendedASCII namespace and setting the encoding should allow us to display characters like █. It was working in a previous version.

#### Actual Behaviour - What unexpectedly happens?
Trying to make it work results in System.Exception without any details.

#### Reproduction - How did you get this error to appear?
Adding these lines of code to a project:

```cs
Encoding.RegisterProvider(CosmosEncodingProvider.Instance);
Console.InputEncoding = CosmosEncodingProvider.Instance.GetEncoding(437);
Console.OutputEncoding = CosmosEncodingProvider.Instance.GetEncoding(437);
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest possible devkit. (Commit [6802c4e](https://github.com/CosmosOS/Cosmos/commit/6802c4ebf0dde9e4c577fd14b924845b79b5c6ea))

This is the output log:

```
1>  Need plug for: System.Boolean  Interop+Kernel32.SetConsoleOutputCP(System.Int32)(Plug Signature: System_Boolean__Interop_Kernel32_SetConsoleOutputCP_System_Int32_ ).
1>  Static: True
1>  Assembly: System.Console, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
1>  Called from:
1>System.ConsolePal::Void SetConsoleOutputEncoding(System.Text.Encoding)
1>System.Console::Void set_OutputEncoding(System.Text.Encoding)
```

I reported this as a bug because it was working in a previous version.

**Comment by zarlo** [comment]
do you know what previous version it work in

**Comment by KernelFox0** [comment]
Sadly I don't know the exact version. But I remember that the last time I updated before it broke with the newest was in November back in 2022

**Comment by 9xbt** [comment]
Do it like this instead:
```Console.InputEncoding = Cosmos.System.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(437);
Console.OutputEncoding = Cosmos.System.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(437);```

**Comment by KernelFox0** [comment]
The same problem happens.

**Comment by KernelFox0** [comment]
I found a version where it still works:
It's commit 189f4e1

https://github.com/CosmosOS/Cosmos/tree/189f4e1d9698db4062635a05b9a0eb820ff9a814

**Comment by quajak** [comment]
Is it broken with any newer commit?

**Comment by code32123** [comment]
Just pulled the devkit last night, and I'm getting a different error. The code
```
Encoding ExtendedEncoding = Cosmos.System.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(437);
Console.OutputEncoding = ExtendedEncoding;
```
gives
```
bin/cosmos/Debug/net6.0/MyOS.asm:188956: error: undefined symbol `SystemVoidSystemStringarrayctorSystemInt32SystemInt32' (first use)
bin/cosmos/Debug/net6.0/MyOS.asm:188956: error:  (Each undefined symbol is reported only once.)
```
This, unfortunately, is wildly beyond my skill level. Do any of you with a better understanding have any ideas of how to resolve this?

**Comment by pleasenoban** [comment]
im working on a fix rn, InputEncoding and OutputEncoding only has a getter and not a setter because of a refactoring commit
