### ISSUE TITLE
System.Excption error in IL2CPU

### ISSUE THREAD

**Issue by afifafifafifafifali** [CosmosOS/Cosmos#2672]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.Exception:	Orzenos1	C:\Users\User\source\repos\Orzenos1\IL2CPU	1

**Comment by GoldenretriverYT** [comment]
Send us the build log.

**Comment by afifafifafifafifali** [comment]
Sorry for giving the log after 3 days

**Comment by AsertCreator** [comment]
you can't use reflection in cosmos as it's compiled ahead-of-time. for what you tried use reflection for?

**Comment by GoldenretriverYT** [comment]
looking at the code he tried to use attributes, which require heavy use of Reflection. There is no support for attributes right now. Also, AOT Compilation doesn't necessarily mean reflection is impossible. There are parts that you can add even with AOT compilation.

Cosmos already adds some [metadata like the type names](https://github.com/CosmosOS/Cosmos/blob/7062349ad0f23f942c92d9ed47af5e5330172902/source/Cosmos.Core/VTablesImpl.cs#LL416C19-L416C25) at compile time that is readable by the compiled code. My pr #2639 also adds a new struct to it that has a list of enum entry names and enum entry values.

I think implementing attributes shouldn't be too hard, but well, someone has to add it first.

**Comment by afifafifafifafifali** [comment]
Here's my Kernel.cs code

**Comment by afifafifafifafifali** [comment]
using System;
using System.Collections.Generic;
using System.Text;
using Cosmos.Core;
using Cosmos.System.Graphics;
using Sys = Cosmos.System;
using System.IO;
using Cosmos.System.FileSystem.VFS;
using Orzenos1;


namespace Orzenos1
{
    public class Kernel : Sys.Kernel
    {
        Sys.FileSystem.CosmosVFS fs;
        string current_directory = "0:\\";

        protected override void BeforeRun()
        {
            fs = new Sys.FileSystem.CosmosVFS();
            VFSManager.RegisterVFS(fs);

            string kernelFilePath = @"0:\\Orzensystems\\Kernel.cs";
            if (!File.Exists(kernelFilePath))
            {
                Console.Clear();
                Console.WriteLine("Loading Files......");
                Cosmos.HAL.Global.PIT.Wait(10000);
                Console.WriteLine("----------------Orconos installer------------------------");
                Console.WriteLine("This will install the Orzenos DOS");
                string kernelCode = @"using System;
using System.Collections.Generic;
using System.Text;
using Cosmos.Core;
using Cosmos.System.Graphics;
using Sys = Cosmos.System;
using System.IO;
using Cosmos.System.FileSystem.VFS;

namespace Orzenos1
{
    public class Kernel : Sys.Kernel
    {
        Sys.FileSystem.CosmosVFS fs;
        string current_directory = ""0:\\"";

        protected override void BeforeRun()
        {
            fs = new Sys.FileSystem.CosmosVFS();
            VFSManager.RegisterVFS(fs);
            CheckPassword();
        }

        protected override void Run()
        {
            Console.Write(current_directory + ""$"");
            var input = Console.ReadLine();
            if (input == ""Sysinfo"")
            {
                Console.WriteLine($""Vendor: {CPU.GetCPUVendorName()}, Name: {CPU.GetCPUBrandString()}, Frequency: {CPU.GetCPUCycleSpeed()} OS Name: Orzen Dos  From: https://orc.com.ezyro.com"");
            }
            else if (input == ""Shutdown"")
            {
                Shutdown();
            }
            else if (input == ""Reboot"")
            {
                Sys.Power.Reboot();
            }
            else if (input == ""Xp mode"")
            {
                XpMode();
            }
            else if (input == ""Calculator"")
            {
                Calculator.Run();
            }
            else if (input == ""Filemanager"")
            {
                FileManager fileManager = new FileManager();
                fileManager.Run();
            }
            else if (input == ""Texteditor"")
            {
                TextEditor.Run();
            }
            else if (input == ""help_color"")
            {
                Console.WriteLine(""All color numbers start with color-number"");
                Console.WriteLine(""1=red, 2=green, 3=blue, 4=yellow, 5=default"");
            }
            else if (input.StartsWith(""color-""))
            {
                string[] parts = input.Split('-');
                if (parts.Length == 2)
                {
                    try
                    {
                        Console.ForegroundColor = (ConsoleColor)Enum.Parse(typeof(ConsoleColor), parts[1], true);
                    }
                    catch
                    {
                        Console.WriteLine(""Invalid color."");
                    }
                }
                else
                {
                    Console.WriteLine(""Invalid command."");
                }
            }
            else
            {
                Console.WriteLine(""Invalid command."");
            }
        }

        private void CheckPassword()
        {
            string password = File.ReadAllText(""0:\\Orzensystems\\password.db"");
            Console.Write(""Type your password: "");
            string inputPassword = Console.ReadLine();
            if (inputPassword == password)
            {
                Run();
            }
            else
            {
                Console.WriteLine(""WRONG PASSWORD. TRY AGAIN!"");
                CheckPassword();
            }
        }

        private void XpMode()
        {
            Console.Clear();
            Console.WriteLine(""Welcome to Windows XP"");
            Console.WriteLine(""Click on the Start button to begin."");
            Console.WriteLine();
            Console.WriteLine(""                     "");
            Console.WriteLine(""  |--------------------|"");
            Console.WriteLine(""  |]   Start          [|"");
            Console.WriteLine(""  |]   Programs       [|"");
            Console.WriteLine(""  |]   Documents      [|"");
            Console.WriteLine(""  |]   Settings       [|"");
            Console.WriteLine(""  |]   Find           [|"");
            Console.WriteLine(""  |]   Help           [|"");
            Console.WriteLine(""  |]   Run            [|"");
            Console.WriteLine(""  |]   Quit           [|"");
            Console.WriteLine(""  |]   --------------------  [|"");
            Console.WriteLine(""                     "");
            Console.WriteLine();
            Console.Write(current_directory + ""$"");
            string input = Console.ReadLine();
            if (input == ""Start"")
            {
                Run();
            }
            else
            {
                Console.WriteLine(""Invalid command."");
                XpMode();
            }
        }
    }

    public class FileManager
    {
        private string currentDirectory;
        
        public void Run()
        {
            currentDirectory = ""0:\\"";
            Console.Clear();
            Console.WriteLine(""-------------------File Manager--------------------"");
            Console.WriteLine(""Enter 'exit' to return to the main menu"");
            Console.WriteLine();
            Console.WriteLine(""Current Directory: "" + currentDirectory);
            Console.WriteLine(""---------------------------------------------------"");
            while (true)
            {
                Console.Write(currentDirectory + ""$"");
                string input = Console.ReadLine();
                if (input == ""exit"")
                {
                    break;
                }
                else if (input.StartsWith(""cd ""))
                {
                    ChangeDirectory(input.Substring(3));
                }
                else if (input == ""ls"")
                {
                    ListFiles();
                }
                else if (input.StartsWith(""touch ""))
                {
                    CreateFile(input.Substring(6));
                }
                else if (input.StartsWith(""rm ""))
                {
                    DeleteFile(input.Substring(3));
                }
                else if (input.StartsWith(""cat ""))
                {
                    PrintFileContent(input.Substring(4));
                }
                else
                {
                    Console.WriteLine(""Invalid command."");
                }
            }
        }

        private void ChangeDirectory(string targetDirectory)
        {
            if (targetDirectory == "".."")
            {
                if (currentDirectory != ""0:\\"")
                {
                    currentDirectory = currentDirectory.Substring(0, currentDirectory.Length - 1);
                    int lastIndex = currentDirectory.LastIndexOf('\\');
                    currentDirectory = currentDirectory.Substring(0, lastIndex + 1);
                }
            }
            else
            {
                string newDirectory = currentDirectory + targetDirectory + '\\';
                if (Directory.Exists(newDirectory))
                {
                    currentDirectory = newDirectory;
                }
                else
                {
                    Console.WriteLine(""Directory not found."");
                }
            }
        }

        private void ListFiles()
        {
            string[] files = Directory.GetFiles(currentDirectory);
            foreach (string file in files)
            {
                Console.WriteLine(file);
            }
        }

        private void CreateFile(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                Console.WriteLine(""File already exists."");
            }
            else
            {
                using (File.Create(filePath)) { }
                Console.WriteLine(""File created."");
            }
        }

        private void DeleteFile(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                File.Delete(filePath);
                Console.WriteLine(""File deleted."");
            }
            else
            {
                Console.WriteLine(""File not found."");
            }
        }

        private void PrintFileContent(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                string content = File.ReadAllText(filePath);
                Console.WriteLine(content);
            }
            else
            {
                Console.WriteLine(""File not found."");
            }
        }
    }

    public class Calculator
    {
        public static void Run()
        {
            while (true)
            {
                Console.Write(""Enter an expression (or 'exit' to quit): "");
                string input = Console.ReadLine();
                if (input == ""exit"")
                {
                    break;
                }
                else
                {
                    try
                    {
                        int result = EvaluateExpression(input);
                        Console.WriteLine(""Result: "" + result);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(""Error: "" + ex.Message);
                    }
                }
            }
        }

        private static int EvaluateExpression(string expression)
        {
            // Evaluate the expression using your desired logic
            // This is just a placeholder implementation
            int result = 0;
            if (int.TryParse(expression, out result))
            {
                return result;
            }
            else
            {
                throw new Exception(""Invalid expression."");
            }
        }
    }

    public class TextEditor
    {
        public static void Run()
        {
            Console.WriteLine(""Text Editor"");
            Console.WriteLine(""Enter 'exit' to return to the main menu"");
            Console.WriteLine();
            StringBuilder sb = new StringBuilder();
            while (true)
            {
                Console.Write(""#"");
                string input = Console.ReadLine();
                if (input == ""exit"")
                {
                    break;
                }
                else if (input == ""save"")
                {
                    SaveToFile(sb.ToString());
                }
                else
                {
                    sb.AppendLine(input);
                }
            }
        }

        private static void SaveToFile(string content)
        {
            Console.WriteLine(""Enter the file name to save: "");
            string fileName = Console.ReadLine();
            File.WriteAllText(fileName, content);
            Console.WriteLine(""File saved."");
        }
    }
}

public static class Program
{
    public static void Main()
    {
        Console.Clear();
        Console.WriteLine(""Welcome to Orzenos DOS"");
        Console.WriteLine(""Type 'help' to see available commands."");
        Console.WriteLine();
        var kernel = new Kernel();
        kernel.Start();
    }
}
}";

                Directory.CreateDirectory(@"0:\Orzensystems");
                Directory.CreateDirectory(@"0:\Orzensystems\Textfiles");
                File.WriteAllText(kernelFilePath, kernelCode);
                Console.Clear();
                Console.WriteLine("Orzenos DOS installed successfully!");
                Console.WriteLine("Please reboot the system to start Orzenos DOS.");
            }
            else
            {
                Console.Clear();
                Console.WriteLine("Orzenos DOS is already installed.");
                Console.WriteLine("Press any key to continue...");
                Console.ReadKey();
            }
        }

        protected override void Run()
        {
            Console.Write(current_directory + "$");
            var input = Console.ReadLine();
            if (input == "Sysinfo")
            {
                Console.WriteLine($"Vendor: {CPU.GetCPUVendorName()}, Name: {CPU.GetCPUBrandString()}, Frequency: {CPU.GetCPUCycleSpeed()} OS Name: Orzen Dos  From: https://orc.com.ezyro.com");
            }
            else if (input == "Shutdown")
            {
                Sys.Power.Shutdown();
            }
            else if (input == "Reboot")
            {
                Sys.Power.Reboot();
            }
            else if (input == "Xp mode")
            {
                XpMode();
            }
            else if (input == "Calculator")
            {
                Calculator.Run();
            }
            else if (input == "Filemanager")
            {
                FileManager fileManager = new FileManager();
                fileManager.Run();
            }
            else if (input == "Texteditor")
            {
                TextEditor.Run();
            }
            else if (input == "help_color")
            {
                Console.WriteLine("All color numbers start with color-number");
                Console.WriteLine("1=red, 2=green, 3=blue, 4=yellow, 5=default");
            }
            else if (input.StartsWith("color-"))
            {
                string[] parts = input.Split('-');
                if (parts.Length == 2)
                {
                    try
                    {
                        Console.ForegroundColor = (ConsoleColor)Enum.Parse(typeof(ConsoleColor), parts[1], true);
                    }
                    catch
                    {
                        Console.WriteLine("Invalid color.");
                    }
                }
                else
                {
                    Console.WriteLine("Invalid command.");
                }
            }
            else
            {
                Console.WriteLine("Invalid command.");
            }
        }

        private void XpMode()
        {
            Console.Clear();
            Console.WriteLine("Welcome to Windows XP");
            Console.WriteLine("Click on the Start button to begin.");
            Console.WriteLine();
            Console.WriteLine("                     ");
            Console.WriteLine("  |--------------------|");
            Console.WriteLine("  |]   Start          [|");
            Console.WriteLine("  |]   Programs       [|");
            Console.WriteLine("  |]   Documents      [|");
            Console.WriteLine("  |]   Settings       [|");
            Console.WriteLine("  |]   Find           [|");
            Console.WriteLine("  |]   Help           [|");
            Console.WriteLine("  |]   Run            [|");
            Console.WriteLine("  |]   Quit           [|");
            Console.WriteLine("  |]   --------------------  [|");
            Console.WriteLine("                     ");
            Console.WriteLine();
            Console.Write(current_directory + "$");
            string input = Console.ReadLine();
            if (input == "Start")
            {
                Run();
            }
            else
            {
                Console.WriteLine("Invalid command.");
                XpMode();
            }
        }
    }

    public class FileManager
    {
        private string currentDirectory;

        public void Run()
        {
            currentDirectory = "0:\\";
            Console.Clear();
            Console.WriteLine("-------------------File Manager--------------------");
            Console.WriteLine("Enter 'exit' to return to the main menu");
            Console.WriteLine();
            Console.WriteLine("Current Directory: " + currentDirectory);
            Console.WriteLine("---------------------------------------------------");
            while (true)
            {
                Console.Write(currentDirectory + "$");
                string input = Console.ReadLine();
                if (input == "exit")
                {
                    break;
                }
                else if (input.StartsWith("cd "))
                {
                    ChangeDirectory(input.Substring(3));
                }
                else if (input == "ls")
                {
                    ListFiles();
                }
                else if (input.StartsWith("touch "))
                {
                    CreateFile(input.Substring(6));
                }
                else if (input.StartsWith("rm "))
                {
                    DeleteFile(input.Substring(3));
                }
                else if (input.StartsWith("cat "))
                {
                    PrintFileContent(input.Substring(4));
                }
                else
                {
                    Console.WriteLine("Invalid command.");
                }
            }
        }

        private void ChangeDirectory(string targetDirectory)
        {
            if (targetDirectory == "..")
            {
                if (currentDirectory != "0:\\")
                {
                    currentDirectory = currentDirectory.Substring(0, currentDirectory.Length - 1);
                    int lastIndex = currentDirectory.LastIndexOf('\\');
                    currentDirectory = currentDirectory.Substring(0, lastIndex + 1);
                }
            }
            else
            {
                string newDirectory = currentDirectory + targetDirectory + '\\';
                if (Directory.Exists(newDirectory))
                {
                    currentDirectory = newDirectory;
                }
                else
                {
                    Console.WriteLine("Directory not found.");
                }
            }
        }

        private void ListFiles()
        {
            string[] files = Directory.GetFiles(currentDirectory);
            foreach (string file in files)
            {
                Console.WriteLine(file);
            }
        }

        private void CreateFile(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                Console.WriteLine("File already exists.");
            }
            else
            {
                using (File.Create(filePath)) { }
                Console.WriteLine("File created.");
            }
        }

        private void DeleteFile(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                File.Delete(filePath);
                Console.WriteLine("File deleted.");
            }
            else
            {
                Console.WriteLine("File not found.");
            }
        }

        private void PrintFileContent(string fileName)
        {
            string filePath = currentDirectory + fileName;
            if (File.Exists(filePath))
            {
                string content = File.ReadAllText(filePath);
                Console.WriteLine(content);
            }
            else
            {
                Console.WriteLine("File not found.");
            }
        }
    }

    public class Calculator
    {
        public static void Run()
        {
            while (true)
            {
                Console.Write("Enter an expression (or 'exit' to quit): ");
                string input = Console.ReadLine();
                if (input == "exit")
                {
                    break;
                }
                else
                {
                    try
                    {
                        int result = EvaluateExpression(input);
                        Console.WriteLine("Result: " + result);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Error: " + ex.Message);
                    }
                }
            }
        }

        private static int EvaluateExpression(string expression)
        {
            // Evaluate the expression using your desired logic
            // This is just a placeholder implementation
            int result = 0;
            if (int.TryParse(expression, out result))
            {
                return result;
            }
            else
            {
                throw new Exception("Invalid expression.");
            }
        }
    }

    public class TextEditor
    {
        public static void Run()
        {
            Console.WriteLine("Text Editor");
            Console.WriteLine("Enter 'exit' to return to the main menu");
            Console.WriteLine();
            StringBuilder sb = new StringBuilder();
            while (true)
            {
                Console.Write("#");
                string input = Console.ReadLine();
                if (input == "exit")
                {
                    break;
                }
                else if (input == "save")
                {
                    SaveToFile(sb.ToString());
                }
                else
                {
                    sb.AppendLine(input);
                }
            }
        }

        private static void SaveToFile(string content)
        {
            Console.WriteLine("Enter the file name to save: ");
            string fileName = Console.ReadLine();
            File.WriteAllText(fileName, content);
            Console.WriteLine("File saved.");
        }
    }
}

public static class Program
{
    public static void Main()
    {
        Console.Clear();
        Console.WriteLine("Welcome to Orzenos DOS");
        Console.WriteLine("Type 'help' to see available commands.");
        Console.WriteLine();
        var kernel = new Kernel();
        kernel.Start();
    }
}

**Comment by GoldenretriverYT** [comment]
I didnt look through the whole code but I can tell you that Enum.Parse is definitely not gonna work right now.

**Comment by terminal-cs** [comment]
This can be closed
