### ISSUE TITLE
Build Error - System.Exception

### ISSUE THREAD

**Issue by achia70** [CosmosOS/Cosmos#2678]
**Exception**
Exception: System.Exception: Error while generating output for file AsmBreak.xs

**Visual Studio Output Logs**
https://pastebin.com/AsaDws5D

**How To Reproduce**
Building the project gives this error

**Screenshots**
![ภาพ](https://github.com/CosmosOS/Cosmos/assets/65407363/2911a919-2c5b-496f-9cef-0b1741ee5c8a)

**Comment by 9xbt** [comment]
I've never seen that happen before, try reinstalling IL2CPU because that seems to be messed up

**Comment by 9xbt** [comment]
Are you using the userkit or the devkit?

**Comment by hubabuba444** [comment]
Haven't seen it, try reinstalling CosmosOS

**Comment by achia70** [comment]
> Are you using the userkit or the devkit?

userkit

**Comment by hubabuba444** [comment]
try insall Devkit

**Comment by zarlo** [comment]
where did you install cosmos
