### ISSUE TITLE
Getting CPU cycle speed on AMDs results in Exception followed by CPU Exception

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2680]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.Core

#### Expected Behaviour - What do you think that should happen?
Should get cycle speed

#### Actual Behaviour - What unexpectedly happens?
Throws an exception, which is normal, but then throws a CPU exception, which is annoying

#### Reproduction - How did you get this error to appear?
Getting CPU cycle speed on an AMD CPU

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by 9xbt** [comment]
This is a well known issue. I don't know how to get the CPU cycle speed like Windows does (for example), there needs to be a way to do that

**Comment by GoldenretriverYT** [comment]
Whats the point of this issue? You already made #2594, why not reopen that one? Well anyways, now its too late.

**Comment by 9xbt** [comment]
Oh, I forgot
