### ISSUE TITLE
When using canvas, system slows down and kernel panics

### ISSUE THREAD

**Issue by winbamstudios** [CosmosOS/Cosmos#2681]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
The canvas should not lag and display everything without crashing.

#### Actual Behaviour - What unexpectedly happens?
The kernel panics after about 2 seconds.

#### Reproduction - How did you get this error to appear?
I initialized the graphics, displaying 2 images, and then it paniced with code 0x103.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit, commit 10555

#### My Code:
```
Heap.Collect();
Canvas.Clear(Color.White);
Canvas.DrawImage(new Bitmap(auroraRaw), 0, 0)
Canvas.DrawImageAlpha(new Bitmap(cursorRaw), (int)Sys.MouseManager.X, (int)Sys.MouseManager.Y
Canvas.Display();
```

**Comment by GoldenretriverYT** [comment]
![7n7qui](https://github.com/CosmosOS/Cosmos/assets/49924528/9648d7da-b580-4e9e-add8-6cce6c49a6ed)

**Comment by 9xbt** [comment]
Exactly lol

**Comment by 9xbt** [comment]
Use Heap.Collect() for collecting memory leaks

**Comment by winbamstudios** [comment]
> Use Heap.Collect() for collecting memory leaks

I am.

**Comment by winbamstudios** [comment]
I added my code

**Comment by GoldenretriverYT** [comment]
You are reinstantiating 2 bitmaps every time. The GC doesn't clean up large objects properly right now, so you are probably running out of memory very quickly. Also, even if the GC **would** ever get fixed, it would still be stupid to do that.

**Comment by winbamstudios** [comment]
OHHHH! ok.

**Comment by winbamstudios** [comment]
It works now!
