### ISSUE TITLE
Cosmos Output Encoding

### ISSUE THREAD

**Issue by Owen2k6** [CosmosOS/Cosmos#2684]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Output Encoder

#### Expected Behaviour - What do you think that should happen?
e.g Console.OutputEncoding = Cosmos.System.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(437);
should set the output encoder to "437" which contains some useful chars to create text UIs in the console

#### Actual Behaviour - What unexpectedly happens?
Build will fail with "System.Exception"

#### Reproduction - How did you get this error to appear?
I tried setting the Output Encoder anywhere in my OS Source code.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
https://github.com/CosmosOS/Cosmos/commit/7062349ad0f23f942c92d9ed47af5e5330172902 
(Latest commit as of time of report)

**Comment by quajak** [comment]
Check the Visual Studio Log window for the entire error message

**Comment by 9xbt** [comment]
We can close this @quajak

**Comment by 9xbt** [comment]
We can close this now @quajak since its fixed
