### ISSUE TITLE
Not popping up to create the Cosmos Kernel.

### ISSUE THREAD

**Issue by KittenPixel-cell** [CosmosOS/Cosmos#2687]
**Describe the problem**
When I install it and start VS 2022 it is not a package

**Steps of installation up to now**
Install Normally and start VS 2022

**Expected behavior**
Me be able to make cosmos kernel

**Logs**
None

**Setup (please complete the following information):**
 - Cosmos Version User Kit 20221121
 - Are you running installer as administrator? Yes
 - Visual Studio Version if applicable VS2022

**Additional context**
None

**Comment by GoldenretriverYT** [comment]
Do you have VS2019 installed too? You will have to uninstall that one first if so

**Comment by KittenPixel-cell** [comment]
Thanks
