### ISSUE TITLE
Not building correctly

### ISSUE THREAD

**Issue by shamppa** [CosmosOS/Cosmos#269]
Hi,
I haven't used COSMOS for long time, and lots seems to have changed...
I'm having issue trying to build .iso image, as Visual Studio seems only to build projects as libraries. 
It seems that il2cpu doesn't start at all, so I'm left only with .dll files?
Have I missed something?

I'm using VS2015 Community Edition, Windows 8.1

**Comment by mterwoord** [comment]
What error do you get?

**Comment by shamppa** [comment]
It didn't give any error, but I got it working; {Projectname}Boot -project was skipped every time solution was built (*Project skipped, as it's not necessary for running*). Solution was to set {Projectname}Boot as startup project. 
Thanks for replying though!
