### ISSUE TITLE
canvas.Clear() is slow

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#2702]
#### Area of Cosmos - What area of Cosmos are we dealing with?

GUI (VGACanvas)

#### Expected Behaviour - What do you think that should happen?

canvas.Clear() to work instantly

#### Actual Behaviour - What unexpectedly happens?

canvas.Clear() is slowly clearing the screen from left to right

#### Reproduction - How did you get this error to appear?

Here is a part of my code:
`protected override void BeforeRun()
{
 canvas = new VGACanvas();
            Sys.MouseManager.X = (UInt32)(canvas.Mode.Rows / 2);
            Sys.MouseManager.Y = (UInt32)(canvas.Mode.Columns / 2);
            Sys.MouseManager.ScreenHeight = (UInt32)canvas.Mode.Rows;
            Sys.MouseManager.ScreenWidth = (UInt32)canvas.Mode.Columns;
        

            canvas.Clear(Color.Blue);
             canvas.DrawString("Test",PCScreenFont.Default,new Pen(Color.White),new Sys.Graphics.Point(10,10));
             canvas.Display();
}
protected override void Run()
{
canvas.Clear(Color.Blue);
            Pen pen = new Pen(Color.White);
            canvas.DrawString("Test", PCScreenFont.Default, new Pen(Color.White), new Sys.Graphics.Point(10, 10));
            Int32 cursorSize = 20;
            canvas.DrawFilledRectangle(pen,System.Convert.ToInt32(Sys.MouseManager.X), System.Convert.ToInt32(Sys.MouseManager.Y),cursorSize,cursorSize);
            canvas.Display();
}

`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit 20221121

**Comment by RaphMar2021** [comment]
Don't use VGA. It's outdated, slow and only small resolutions supported. Use SVGAII or VBE instead. Also, it only fill a big rectangle.

**Comment by RaphMar2021** [comment]
And use DevKit instead of UserKit

**Comment by Vardan2009** [comment]
I want to make an OS that can run on real hardware, can SVGAII or VBE do that? Thanks.

**Comment by Vardan2009** [comment]
Also, is there a way to upgrade to devkit when I already have userkit installed?

**Comment by pleasenoban** [comment]
vbe should work if you specify VBEResolution (i might get the naming wrong) in the project configs although i think you cant change the mode in runtime

also you can just uninstall userkit then build devkit and install it

**Comment by Vardan2009** [comment]
Thanks! It works, but is there a way to disable the VBECanvas at the start and enable it later?

**Comment by RaphMar2021** [comment]
No, you can't but you can make a custom console for VBECanvas

**Comment by Vardan2009** [comment]
Thank you, I will close this now.
