### ISSUE TITLE
Keyboard keys not working as expected

### ISSUE THREAD

**Issue by slavekrouta** [CosmosOS/Cosmos#2704]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Input - Keyboard

#### Expected Behaviour - What do you think that should happen?
Keyboard keys should work how expected: A is A, ENTER is ENTER,  BACKSPACE is BACKSPACE

#### Actual Behaviour - What unexpectedly happens?
Keyboard keys are messed up. A acts like ENTER for example.

#### Reproduction - How did you get this error to appear?
I get the .iso file from \source\repos\project\project\bin\Debug\net6.0\ and write it to an USB with Rufus. Boot into Cosmos on actual hardware. (Yes, I use PS/2 keyboard)
(My code is [on pastebin](https://pastebin.com/KRRSWRWe) and the password is `CosmosOS`)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest UserKit

**Comment by ptobuon** [comment]
Try to set the keyboard layout of your keyboard using KeyboardManager.SetKeyLayout() or try with another keyboard
