### ISSUE TITLE
Adding embeded resources causes build times and file sizes to increase exponentially

### ISSUE THREAD

**Issue by terminal-cs** [CosmosOS/Cosmos#2705]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Embeded resources

#### Expected Behaviour - What do you think that should happen?
Files should be cleanly added to the assembly (somehow?) and size should not grow many times larger than the file being added. Also, il2cpu and yasm compile times exponentially increase as more files are added, as if they are trying to process the file as assembly.

#### Actual Behaviour - What unexpectedly happens?
Files should be added with no noticeable compile time impact and assembly file should not grow more than what was added.

#### Reproduction - How did you get this error to appear?
Embed large image files 1080p seems to show it very well).

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by zarlo** [comment]
the files might be getting base64 encoded

> Also, il2cpu and yasm compile times exponentially increase as more files are added, as if they are trying to process the file as assembly.

that should not be the case as it should be included as data ``db [content in hex here]``

**Comment by terminal-cs** [comment]
> the files might be getting base64 encoded
> 
> > Also, il2cpu and yasm compile times exponentially increase as more files are added, as if they are trying to process the file as assembly.
> 
> that should not be the case as it should be included as data `db [content in hex here]`

If it's base-64 encoded it would most certainly be the case, because it has to process it back into binary.

Would there be a different way to go about this?

**Comment by GoldenretriverYT** [comment]
well you can use the isoFiles folder now since i have fixed it in #2703

**Comment by terminal-cs** [comment]
> well you can use the isoFiles folder now since i have fixed it in #2703

Interesting, thanks for that.

**Comment by terminal-cs** [comment]
> well you can use the isoFiles folder now since i have fixed it in #2703

What do i add in my csproj to enable this? I'm on linux and i don't know the name of it

**Comment by quajak** [comment]
Do you have timings to support an exponential increase in time?

**Comment by terminal-cs** [comment]
> Do you have timings to support an exponential increase in time?

No i haven't recorded anything, but i defenetly remember it taking a _lot_ more time, and a while ago my assembly file would get to 300 MB (originaly (100 MB) after adding only a few MBs of embeded resources. I just moved to using the isoFiles folder and can say for sure that yasm completes a lot faster and the resulting bin size is merely 3 MB instead of 8

**Comment by quajak** [comment]
I would expect the growth to be linear but that doesn't mean its very efficient. Might make sense to improve this in future.

**Comment by zarlo** [comment]
> > Do you have timings to support an exponential increase in time?
> 
> No i haven't recorded anything, but i defenetly remember it taking a _lot_ more time, and a while ago my assembly file would get to 300 MB (originaly (100 MB) after adding only a few MBs of embeded resources. I just moved to using the isoFiles folder and can say for sure that yasm completes a lot faster and the resulting bin size is merely 3 MB instead of 8

you can time it with ```time dotnet build```

**Comment by steve-studios** [comment]
Yeah, after adding a 4k image for my desktop background, the build time increased to over 8 minutes each build.
Basically cosmos is barely usable for me right now.

**Comment by 9xbt** [comment]
Can we close this @quajak. It's been fixed for a while
