### ISSUE TITLE
Cosmos doesn't install correctly on Windows

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2707]
**Describe the problem**
It doesn't install Visual Studio extensions & nuget source.

**Steps of installation up to now**
Install latest DevKit

**Expected behavior**
It should install everything

**Logs**
I don't know where's the logs

Cosmos Dev Kit (Administrator) with VS2022 17.5 on Windows 10 22H2

**Comment by ptobuon** [comment]
Same thing

**Comment by ptobuon** [comment]
It said that is installed correctly but the project files and the packages are not present.

**Comment by quajak** [comment]
Will be fixed by #2708

**Comment by Jspa2** [comment]
A temporary workaround is to manually install the .vsix files placed in the Cosmos installation directory
