### ISSUE TITLE
Making a string with a negative length should just cause an exception

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2717]
#### Area of Cosmos - What area of Cosmos are we dealing with?
System.String

#### Expected Behaviour - What do you think that should happen?
`new string(' ', -1);` should just throw `System.ArgumentOutOfRangeException`

#### Actual Behaviour - What unexpectedly happens?
Causes a CPU Exception

#### Reproduction - How did you get this error to appear?
`new string(' ', -1);`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by quajak** [comment]
This should be easy to fix with an addition to the string ctor

**Comment by 9xbt** [comment]
Thanks
