### ISSUE TITLE
cosmosOS freezes on amd laptop

### ISSUE THREAD

**Issue by tacitmarmot271** [CosmosOS/Cosmos#2719]
when i load it on an amd e300 laptop and it throws an exception

i was loading it up on real hardware

please help 
userkit vs_2022

**Comment by zarlo** [comment]
can we have more info like what was the exception, do you have a git repo?

**Comment by tacitmarmot271** [comment]
no i dont have a repo yet but i can post one
also it was a cosmos cpu exception

**Comment by MEMESCOEP** [comment]
What did the CPU Exception say?
