### ISSUE TITLE
Canvas Issues

### ISSUE THREAD

**Issue by Superbro525Alt** [CosmosOS/Cosmos#2722]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Graphics 

#### Expected Behaviour - What do you think that should happen?
It should display multiple colours in boxes on the left.

#### Actual Behaviour - What unexpectedly happens?
It gives a black screen

#### Reproduction - How did you get this error to appear?
I am using the latest userkit and am using VMware to run it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit latest

#### Code
using Cosmos.System.Graphics;
using Cosmos.System.Graphics.Fonts;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Text;
using Sys = Cosmos.System;

namespace GraphicsTest
{
	public class Kernel : Sys.Kernel
	{
		
		public void graphics_init_test()
		{
			Canvas canvas = FullScreenCanvas.GetFullScreenCanvas();
			
			canvas.Clear(Color.Yellow);
			canvas.DrawString("Black text on a yellow bg.", PCScreenFont.Default, new Pen(Color.Black), new Sys.Graphics.Point());

			Color[] cols = new Color[9];
			cols[0] = Color.Black;
			cols[1] = Color.White;
			cols[2] = Color.Purple;
			cols[3] = Color.DodgerBlue;
			cols[4] = Color.SteelBlue;
			cols[5] = Color.LightGreen;
			cols[6] = Color.Green;
			cols[7] = Color.Orange;
			cols[8] = Color.Magenta;
			int boxX = 20;
			foreach (Color col in cols)
			{
				if (col != null)
				{
					canvas.DrawFilledRectangle(new Pen(col), 5, boxX, 100, 50);
					if (col != Color.Black)
						canvas.DrawString(col.Name, PCScreenFont.Default, new Pen(Color.Black), new Sys.Graphics.Point(5, boxX + 10));
					else
						canvas.DrawString(col.Name, PCScreenFont.Default, new Pen(Color.White), new Sys.Graphics.Point(5, boxX + 10));
					boxX += 50;
				}
			}
		}
		protected override void BeforeRun()
		{
			Console.WriteLine("Cosmos booted successfully. Starting Test");

			graphics_init_test();
			
		}

		protected override void Run()
		{
		}
	}
}

**Comment by 9xbt** [comment]
you uhh, forgot to render.
`Canvas.Display()`

**Comment by Superbro525Alt** [comment]
Thanks but where do I call it?

**Comment by Superbro525Alt** [comment]
thanks for the help. fixed it.

**Comment by 9xbt** [comment]
np
