### ISSUE TITLE
IL2CPU Bitmap drawing issue

### ISSUE THREAD

**Issue by PratyushKing** [CosmosOS/Cosmos#2724]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphical Interfaces (using the canvas.DrawImage() to draw the background.bmp via the Resources file)

#### Expected Behaviour - What do you think that should happen?
It should normally draw the background (as it has worked in other projects)

#### Actual Behaviour - What unexpectedly happens?
It just shows "Exception: System.Exception: " and then just doesn't mention what went wrong.

#### Reproduction - How did you get this error to appear?
Via This code:
Bitmap wallpaper = new Bitmap((uint)Kernel.screenWidth, (uint)Kernel.screenHeight, Resources.backimg, ColorDepth.ColorDepth32);
canvas.DrawImage(wallpaper, 0, 0);
(the backimg is from my resource file)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using UserKit although not sure about versions.

**Comment by pleasenoban** [comment]
have you tried
```
Bitmap wallpaper = new Bitmap(Resources.backimg);
```
since it is a .bmp resource?

**Comment by CodeDevel0per** [comment]
> have you tried
> 
> ```
> Bitmap wallpaper = new Bitmap(Resources.backimg);
> ```
> 
> since it is a .bmp resource?

Yes of course I did, and a couple other attempts.

**Comment by 9xbt** [comment]
Send us the entire build log please so we can get more info about the issue

**Comment by CodeDevel0per** [comment]
> Send us the entire build log please so we can get more info about the issue

so as in the log that shows up when you start compiling?

**Comment by CodeDevel0per** [comment]
its just using plugs from cosmos-build stuff and then its the exception

**Comment by 9xbt** [comment]
you can still click on "view build log" and see the log when its finished

**Comment by 9xbt** [comment]
@PratyushKing when will you send the logs its been fucking 2 months since i asked

**Comment by quajak** [comment]
> @PratyushKing when will you send the logs its been fucking 2 months since i asked

Please be more respectful with your language

**Comment by PratyushKing** [comment]
I am really sorry, I forgot to close the issue, it has been fixed.
