### ISSUE TITLE
Cosmos Produces "Unbootable ISO"

### ISSUE THREAD

**Issue by edy131109** [CosmosOS/Cosmos#2729]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Loading the ISO to a usb stick using Rufus

#### Expected Behaviour - What do you think that should happen?
I should be able to load the ISO on to the usb stick

#### Actual Behaviour - What unexpectedly happens?
Rufus says the ISO is not bootable

#### Reproduction - How did you get this error to appear?
Built my project and loaded the iso into Rufus

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit latest version

**Comment by 9xbt** [comment]
Not a Cosmos issue, a Rufus issue
Rufus doesn't know about the existance of limine, Cosmos's bootloader, so it says the ISO is unbootable, but it isn't

**Comment by 9xbt** [comment]
Report the issue to the rufus github repository's issues page
