### ISSUE TITLE
COSMOS has no configs or profiles, as well as not auto-opening VMWare.

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2731]
### Area of Cosmos - What area of Cosmos are we dealing with?
Visual Studio integration, VMWare integration.. ?

### Expected Behaviour - What do you think that should happen?
--VMWare Problem--
1. Build
2. Open VMWare Player
3. Connect debugger to COM1
4. Run OS.

--Config problem--
1. Right-click on project in Solution Explorer
2. Click properties
3. There should be a COSMOS menu, from which I can config build/post-build settings.

#### Actual Behaviour - What unexpectedly happens?
--VMWare Problem--
1. Build
2. VS 2022 "a project of output type Class Library cannot be opened directly"

--Config problem--
1. Right-click on project in Solution Explorer
2. Click properties
3. There is no "Cosmos" menu for build config

#### Reproduction - How did you get this error to appear?
VMWare: Debug project
Config: I genuinely have absolutely no idea.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Newest COSMOS user kit.

![error](https://github.com/CosmosOS/Cosmos/assets/140258220/57602f9a-34c5-40f6-a8ca-cba830535768)

**Comment by GoldenretriverYT** [comment]
You most likely haven't installed cosmos correctly. Make sure you do not have an installation of VS2019 & VS2022 at the same time. If you have VS2019 installed, uninstall it and reinstall Cosmos.

**Comment by Neil-Ciciglycerin** [comment]
ok i'll try that 
:P

**Comment by Neil-Ciciglycerin** [comment]
ok the config problem was solved now i'm just waiting for the build to finish.

**Comment by Neil-Ciciglycerin** [comment]
yeah nope that worked. silly me, and sorry for using your time on something that trivial
