### ISSUE TITLE
Directory.CreateDirectory() does not create a directory, but there is not an exception.

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2732]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem/FAT32

#### Expected Behaviour - What do you think that should happen?
The folder 0:TestFolder gets created

#### Actual Behaviour - What unexpectedly happens?
The folder does not get created and there is no exception.

#### Reproduction - How did you get this error to appear?
Use the function System.IO.Directory.CreateDirectory to create a directory.
Code:
var info = Directory.CreateDirectory(@cwd + cmd[1]);

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, cosmos for VS2022, newest version.

**Comment by GeorgeFence** [comment]
try Directory.CreateDirectory(path);

**Comment by HyperWinX** [comment]
Did you mounted partition? I got same problems when tried to create something in unmounted or not existing partitions

**Comment by Neil-Ciciglycerin** [comment]
> try Directory.CreateDirectory(path);

That was the function i was having a problem with.

> Did you mounted partition? I got same problems when tried to create something in unmounted or not existing partitions

I was using the 0: drive.

**Comment by HyperWinX** [comment]
I asked: did you mount partition with something like fs.Disks[0].Mount(0) (i forgot functions)

**Comment by Neil-Ciciglycerin** [comment]
OH WAIT DO YOU HAVE TO MOUNT THAT???
I'm using VM and can already edit, create and read files. But i'll try that.

**Comment by Neil-Ciciglycerin** [comment]
Nothing. As a logging tool, upon creating the directory, i'm printing information from the DirectoryInfo returned from the CreateDirectory() call. It always prints the name and path correctly, but never the "parent" folder. That's just empty.

**Comment by Neil-Ciciglycerin** [comment]
Code to mount:
            FileSystem.GetDisks()[0].Mount();

**Comment by Neil-Ciciglycerin** [comment]
@HyperWinX you still there?

**Comment by HyperWinX** [comment]
Ye, im here

**Comment by HyperWinX** [comment]
Looks normal... You are using something like Directory.CreateDirectory("0:\\dir");?

**Comment by Neil-Ciciglycerin** [comment]
YEP. Directory.CreateDirectory(0:testdir).

**Comment by Neil-Ciciglycerin** [comment]
On attempted creation of 0:/testdir, it throws "Value cannot be null. Parameter name: aPath"

**Comment by HyperWinX** [comment]
You forgot "" chars
Weird...

**Comment by Neil-Ciciglycerin** [comment]
I'll try @"0:\testdir"? Maybe?

**Comment by Neil-Ciciglycerin** [comment]
IT WORKED!!!!!

**Comment by HyperWinX** [comment]
Whaaaaaaaa, how

**Comment by Neil-Ciciglycerin** [comment]
I have no idea.
