### ISSUE TITLE
Cannot switch from CGS to console plugs.

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2735]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
1. I display a bitmap
2. I wait for the user to press a key, using `while(!System.Console.KeyAvailable){}`
3. I clear the canvas
4. I return to console mode

#### Actual Behaviour - What unexpectedly happens?
1. I display a bitmap
2. I wait for the user to press a key, using `while(!System.Console.KeyAvailable){}`
3. I clear the canvas
4. Nothing???????

#### Reproduction - How did you get this error to appear?
Straight from my code:
```c#

                        canvas = FullScreenCanvas.GetFullScreenCanvas();
                        byte[] image_bytes = File.ReadAllBytes(@cwd+cmd[1]);
                        Bitmap image = new Bitmap(image_bytes);
                        System.Console.Clear();
                        canvas.Clear();
                        canvas.DrawImage(image, 0, 0);
                        canvas.Display();
                        PrintDebug("Displaying image.");
                        while(!System.Console.KeyAvailable) { }
                        PrintDebug("Key pressed.");
                        canvas.Clear();
                        PrintDebug("Canvas cleared.");
                        System.Console.BackgroundColor = ConsoleColor.Blue;
                        System.Console.ForegroundColor = ConsoleColor.White;
                        System.Console.Clear();
``` 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Newest user kit.

**Comment by pleasenoban** [comment]
you need to disable the canvas by using
```cs
canvas.Disable();
```
before you can use the regular console

**Comment by Neil-Ciciglycerin** [comment]
can you then use graphics mode again?

**Comment by pleasenoban** [comment]
you can just
```cs
FullScreenCanvas.GetFullScreenCanvas();
```
again iirc

**Comment by Neil-Ciciglycerin** [comment]
ah. thanks comrade.
