### ISSUE TITLE
Images are hue-shifted by CGS

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2736]
#### Area of Cosmos - What area of Cosmos are we dealing with?
CGS

#### Expected Behaviour - What do you think that should happen?
1. I load a test image
2. I display it on the screen, exactly as if viewed from windows

#### Actual Behaviour - What unexpectedly happens?
1. I load a test image
2. It's hue-shifted when displayed on screen
Visual reference:
![comp](https://github.com/CosmosOS/Cosmos/assets/140258220/7929be2a-6004-472b-ac9d-60b2073782f6)

#### Reproduction - How did you get this error to appear?
m'code:
```c#
                        canvas = FullScreenCanvas.GetFullScreenCanvas();
                        byte[] image_bytes = File.ReadAllBytes(@cwd+cmd[1]);
                        Bitmap image = new Bitmap(image_bytes);
                        System.Console.Clear();
                        canvas.Clear();
                        canvas.DrawImage(image, 0, 0);
                        canvas.Display();
``` 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit, newest.

**Comment by pleasenoban** [comment]
whats the color order of the image youre trying to draw?

**Comment by Neil-Ciciglycerin** [comment]
> whats the color order of the image youre trying to draw? cosmos needs bga iirc

what does that mean

**Comment by pleasenoban** [comment]
you need to convert your bitmap's color order to bgr to be drawn correctly

**Comment by Neil-Ciciglycerin** [comment]
but how do i do that?

**Comment by pleasenoban** [comment]
you could try using this instead of reading all bytes (untested)
```cs
Bitmap(string path, ColorOrder.RGB);
```
or (untested)
```cs
Bitmap(byte[] imageData, ColorOrder.RGB);
```

**Comment by Neil-Ciciglycerin** [comment]
ok that worked :P

**Comment by ptobuon** [comment]
If that worked, please close the issue. Thanks.
