### ISSUE TITLE
Cosmos Canvas Renderization Error Black Screen Cosmos.System.Graphics

### ISSUE THREAD

**Issue by PedroLucas201441** [CosmosOS/Cosmos#2738]
Area of Cosmos - Graphics Subsystem
Expected Behavior - The expected behavior is that the code provided should render graphics on the screen using the Cosmos System Graphics subsystem.
Actual Behavior - However, when executing the code, the screen remains black, and no graphics are rendered using the Cosmos.System.Graphics.
Reproduction - I am not able to reproduce the issue myself based on the provided information.
Version - The issue is observed in the latest version of Cosmos as of November 21, 2022 (20221121).

Hello everyone! When I try to use the Cosmos Graphic library (Cosmos.System.Graphics), the screen stays black and nothing is rendered. In the code, there was an error detector that would report errors to the console, but it didn't report anything. Additionally, when I press Enter, VMware closes. Can someone help me?

The code I used to check if the library was working is an official example of how to create a GUI in Cosmos using the Cosmos Graphic Subsystem.

Code:
using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace GraphicTest
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;

        protected override void BeforeRun()
        {
            
            Console.WriteLine("Cosmos booted successfully. Let's go in Graphic Mode");

            canvas = FullScreenCanvas.GetFullScreenCanvas();

            canvas.Clear(Color.Blue);
        }

        protected override void Run()
        {
            try
            {
                
                Pen pen = new Pen(Color.Red);
                canvas.DrawPoint(pen, 69, 69);

                
                pen.Color = Color.GreenYellow;
                canvas.DrawLine(pen, 250, 100, 400, 100);

                
                pen.Color = Color.IndianRed;
                canvas.DrawLine(pen, 350, 150, 350, 250);

                
                pen.Color = Color.MintCream;
                canvas.DrawLine(pen, 250, 150, 400, 250);

                
                pen.Color = Color.PaleVioletRed;
                canvas.DrawRectangle(pen, 350, 350, 80, 60);

                Console.ReadKey();

                
                canvas.Mode = new Mode(800, 600, ColorDepth.ColorDepth32);

                
                pen.Color = Color.LimeGreen;
                canvas.DrawRectangle(pen, 450, 450, 80, 60);

                Console.ReadKey();

                Stop();
            }
            catch (Exception e)
            {
                mDebugger.Send("Exception occurred: " + e.Message);
                mDebugger.Send(e.Message);
                Stop();
            }
        }
    }
}

**Comment by Kiirx** [comment]
you forgot to update the canvas

**Comment by HyperWinX** [comment]
You need to enable canvas by using Display(), and update every frame using Update()
Put Display to beforerun, and update to end of run

**Comment by HyperWinX** [comment]
Also move mode changing to beforerun, remove console readkey and stop methods

**Comment by PedroLucas201441** [comment]
I Will try Now

**Comment by PedroLucas201441** [comment]
After of             canvas.DrawRectangle(pen, 450, 450, 80, 60);
I Tryed Use canvas.Update() and Update() not exist

**Comment by HyperWinX** [comment]
Weird, it has to be there

**Comment by PedroLucas201441** [comment]
What its Correct Command to Use Update()

**Comment by PedroLucas201441** [comment]
I used the canvas.Display(); and this is Result i dont see if its Correct im am begginer in c# and Cosmos i have 9 Years 
![image](https://github.com/CosmosOS/Cosmos/assets/118313199/95912896-c115-4bb6-a999-ca686eafc03a)

**Comment by PedroLucas201441** [comment]
Its OK its Solved

**Comment by PedroLucas201441** [comment]
Solved Now im will make GUI in Klanto OS

**Comment by GoldenretriverYT** [comment]
> i have 9 Years

you have 9 years what? 9 years to live? 9 years experience?

**Comment by PedroLucas201441** [comment]
Yes

**Comment by PedroLucas201441** [comment]
No im have 9 years Old

**Comment by PedroLucas201441** [comment]
Im am kid learning C#

**Comment by RayElProOficial** [comment]
me too, i have 11 :)

**Comment by HyperWinX** [comment]
Bro HAS 11 kids in basement💀
