### ISSUE TITLE
FAT : How to use?

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#274]
Say me how to use FAT in Cosmos.
Seem that these lines don't work:
```C#
ulong block = 0;
...
byte[] Block = Fat.NewClusterArray();
Fat.ReadCluster(block, Block);
return Block;
```
I will write to Wiki what you say.

**Comment by charlesbetros** [comment]
#270 there are a few examples in the fat test project, it's not 100% working yet.

**Comment by lukaandjelkovic** [comment]
@charlesbetros , but when i load it in my system i only i get kudzu.txt and root.txt.

**Comment by mterwoord** [comment]
Maybe that's what's on the virtual harddisk?

**Comment by lukaandjelkovic** [comment]
what is the main disk? I think how to get all current partition labels?

**Comment by lukaandjelkovic** [comment]
*partition char, like C:// or D://

**Comment by mterwoord** [comment]
The virtual machine starts with a virtual harddisk attached. It contains some default test stuff. 
Volumes are number currently. @"0:\"

**Comment by lukaandjelkovic** [comment]
How to write in?

**Comment by mterwoord** [comment]
Mainly using System.IO

**Comment by lukaandjelkovic** [comment]
Yes i was able to see that in Tests, but if its virtual, does it save anything

**Comment by lukaandjelkovic** [comment]
i mean create a.txt, restart; open a.txt.
This should work only for USB devices?

**Comment by mterwoord** [comment]
Please use chat to ask lots of small questions, please use the gitter chat.

I think when running, the virtual harddisk is saved, if not, it's a good thing to get working. We can guide you in making that.

**Comment by lukaandjelkovic** [comment]
OOKLA.

**Comment by mterwoord** [comment]
OOKLA?
