### ISSUE TITLE
How to Set the VgA font without bytes using ttf

### ISSUE THREAD

**Issue by PedroLucas201441** [CosmosOS/Cosmos#2740]
I set the font vga ttf without bytes and ascii plase help me to set font

**Comment by PedroLucas201441** [comment]
using PCScreenFont to console and Canvas

**Comment by GoldenretriverYT** [comment]
not happening

1st) TTF Fonts are not VGA fonts.
2nd) PCScreenFonts are not TTF fonts.
3rd) Without bytes? Where would the font come from? It cant magically appear.
4th) Tf does "without ascii" even mean
5th) PCScreenFonts are also not the same as VGA fonts.

**Comment by PedroLucas201441** [comment]
It's because I want to simplify just ttf because bytes and arrays and ascii is too advanced for my age I'm only 9 years old

**Comment by PedroLucas201441** [comment]
I want to change the vga font to a ttf one

**Comment by PedroLucas201441** [comment]
im see PCScreenFonts its not same font but cutsmize

**Comment by husaral2** [comment]
`I'm only 9 years old`

You should look for programs easier to code then, writing an operating system is too complicated and it will be very hard even with a helper framework

**Comment by PedroLucas201441** [comment]
not  im writing in C# im see its complicated im chosing comos for facility😊

**Comment by 9xbt** [comment]
> It's because I want to simplify just ttf because bytes and arrays and ascii is too advanced for my age I'm only 9 years old

It's not that hard

https://learn.microsoft.com/en-us/dotnet/api/system.byte?view=net-6.0
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/
https://en.wikipedia.org/wiki/ASCII

**Comment by 9xbt** [comment]
TTF is way more complex than bytes, arrays and ASCII

**Comment by GoldenretriverYT** [comment]
Pedro, we aren't trying to offend you but it really is not a good idea to try to make an OS at 9 years old. Considering you find "bytes" too complicated, you lack fundamental knowledge. Take on some easier task. Make a text editor for windows first or something

**Comment by PedroLucas201441** [comment]
> Pedro, we aren't trying to offend you but it really is not a good idea to try to make an OS at 9 years old. Considering you find "bytes" too complicated, you lack fundamental knowledge. Take on some easier task. Make a text editor for windows first or something

I know it's compiled so I'm going to do it without bytes I'm going to try to make my operating system with the maximum that it only has in the next update add this function my Name is Pedro because im Brazilian

**Comment by PedroLucas201441** [comment]
I trying learn Assembly Now OK to Facility to make an GBA Emulator to Add My System

**Comment by PedroLucas201441** [comment]
i learned a bit of bytes in an ultra low level programming language called befunge 
I did hello world by myself it was like this: 
>v
  > ,,,,, "Hello"v
                    >  ,,,,,"World"

Explication:
When the program starts a byte will move down and then continue and then I will write the commas of how many bits the message will have in the case 5 bits = 5 letters so it will be 5 and the message is Hello then a byte goes down and turns to the right and go ahead and there are some more commas there that have 5 bits and I printed it like this in the Console: First line below 1 byte: Hello Second line below 2 byte:World

**Comment by PedroLucas201441** [comment]
Ok

**Comment by PedroLucas201441** [comment]
But do you know any github alternatives for my age with user interaction without code blocks

**Comment by PedroLucas201441** [comment]
And have Cosmos Project or No

**Comment by PedroLucas201441** [comment]
after 3 years i will back for response now i will use github for view open source download and view issues for 3 years

**Comment by PedroLucas201441** [comment]
Attention GitHub Moderators: Please Do Not Ban Mine Why It will only be inactive for 3 years for me to complete 12 years the issue will not be closed until I want to

**Comment by Kiirx** [comment]
> Attention GitHub Moderators: Please Do Not Ban Mine Why It will only be inactive for 3 years for me to complete 12 years the issue will not be closed until I want to

I propose instead that you reopen the issue when you are 12 years old, we already have a lot of open issues so it would help cleaning up

**Comment by Kiirx** [comment]
Also don't give your age, name, nationality like that, you should do it only to people you trust, see internet safety rules online
