### ISSUE TITLE
GC causes problems

### ISSUE THREAD

**Issue by GoldenretriverYT** [CosmosOS/Cosmos#2741]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Garbage Collector

#### Expected Behaviour - What do you think that should happen?
Should work fine with Heap.Collect

#### Actual Behaviour - What unexpectedly happens?
If I run Heap.Collect every tenth frame, as soon as I invoke the event it crashes due to a VTables METHOD NOT FOUND error. Its happening somewhere within my event handler it seems, as commenting out the event handler code (not the subscribing itself) works.

#### Reproduction - How did you get this error to appear?
https://github.com/GoldenretriverYT/nxtlvlOS
Its probably too big to put it directly here, but in summary following happens: The WindowManager provides an Event (custom event implementation using a List of Actions, seen in Windowing/Utils/Event.cs) called "GlobalMouseUpEvent"; the ContextMenuService subscribes (listens) to that event. Then apparently, when clicking, the code linked here causes a VTables METHOD NOT FOUND error with type id 0x0000000 and method id 0x00000250 - I have iterated through all types to check which ones even have that many to begin with, and only SzArrayHelper came up.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by quajak** [comment]
Yeah, there seems to be an issue with GC and I can't really get a good hold of it. Regarding your reproduction, 
> VTables METHOD NOT FOUND error with type id 0x0000000 and method id 0x00000250

this most likely means that, the object for which the virtual method was called is incorrectly null, as this would result in id 0. If possible I would try run the code in Bochs. Then once the error occurs, you can get the strack trace. From there we can figure out which object is getting incorrectly freed etc

**Comment by GoldenretriverYT** [comment]
yeah, i will take a look at it (as soon as I have added VBE support to nxtlvlOS at least)

**Comment by quajak** [comment]
I havn't tested it with this code base since this is a bit of work to setup but I havn't heard much feedback regarding the last changes in general so idk if its fixed but it is possible

**Comment by cameronos** [comment]
I'll rebuild and stress test a GUI OS for as long as I can seeing how long the GC holds up

**Comment by GoldenretriverYT** [comment]
look i aint an asshole, even though arawn davies doesnt like me i tested it and the problem seems to be gone 👍
