### ISSUE TITLE
error MSB4018 while building

### ISSUE THREAD

**Issue by Samma2009** [CosmosOS/Cosmos#2745]
**Describe the problem**
i tried to install the latest version of the cosmos devkit, i launched the `install-VS2022.bat` and it started with no problem but when the build started the error `MSB4018` appeared.
i tried to:
- reinstall visual studio
- re run the cosmos setup
- redownload the dependeces (Il2CPU,ecc...)
i have the requirements:
-  visual studio 2022 15.4+
- .net 6.0
- inno setup 6.0+

**Steps of installation up to now**
i only runned `install-VS2022.bat` (after renameing the folder `Cosmos-master` to `Cosmos`)

**Expected behavior**

**Logs**
[My logs](https://pastebin.com/RcxRJDAa)
**Setup (please complete the following information):**
 - Devkit
 - Are you running installer as administrator? - Yes
 - Visual Studio Version if applicable - 2022 latest

**Additional context**
the errorr appeared after i formatted my computer because of an harddrive corruption

**Comment by Jspa2** [comment]
is your machine x64 or x86?

**Comment by Samma2009** [comment]
yes, it is x64

**Comment by Samma2009** [comment]
> is your machine x64 or x86?

yes,it is X64

**Comment by ptobuon** [comment]
Have you installed Microsoft Visual C++ 2010? If not, here is the link https://www.microsoft.com/en-us/download/details.aspx?id=26999
