### ISSUE TITLE
System Boolean plug

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#275]
System.Boolean  System.Security.CodeAccessSecurityEngine.QuickCheckForAllDemands()
Needed.
I want it to read all lines of file:
FileRead = File.ReadAllLines(FileAdr);

**Comment by charlesbetros** [comment]
Use the FileStream.ReadAllText() there is a sample in the Fat test kernel.

**Comment by mterwoord** [comment]
Or make a plug for ReadAllLines..

**Comment by lukaandjelkovic** [comment]
No i think i will make a big byte array which contain contents of file, and so search the ENTER byte in the loop.
