### ISSUE TITLE
Cosmos won't show up on VS2017 after installation

### ISSUE THREAD

**Issue by Thrilltech** [CosmosOS/Cosmos#2750]
**Describe the problem**
After running CosmosUserKit-20170928-vs2017.exe, and waiting for the installation to complete, when I try to create an new Project in VS2017, nothing from Cosmos shows up.

**Steps of installation up to now**
Start CosmosUserKit-20170928-vs2017.exe, wait for the installation to complete. Open VS2017. Try to create new project.

**Expected behavior**
After installing Cosmos, to find the Project-Template (Something like C# Operating System).

**Logs**

**Setup (please complete the following information):**
 - Cosmos Version (Userkit)
 - Are you running installer as administrator? - Of course
 - Visual Studio Version if applicable - VS2017

**Additional context**
I have VS2022 also installed, but without the .NET thing. I only have the .NET whatever for VS2017, thats why I want to use 2017.

**Comment by PratyushKing** [comment]
you gotta be kidding me

**Comment by PratyushKing** [comment]
please stop using older verisons of software and for god sake update to vs 2022, we wont kill you

**Comment by PratyushKing** [comment]
and you dont need to run as admin
if it requires admin then it will auto prompt

**Comment by Thrilltech** [comment]
> please stop using older verisons of software and for god sake update to vs 2022, we wont kill you

Not everyone do have a nice pc, that can run it without problems.

> you gotta be kidding me

Noo, I'm not. 

> and you dont need to run as admin if it requires admin then it will auto prompt

I know, I'm not stupid. It auto-promted, so I ran it as administrator. Also it was a question of the form, so don't blame me!

**Comment by ptobuon** [comment]
Sorry @Thrilltech, but older versions of cosmos are very outdated and may not work. Have you tried installing the [latest version](https://github.com/CosmosOS/Cosmos/releases/download/Userkit_20181010/CosmosUserKit-20181010-vs2017.exe) for vs2017? also, can you send detailed build logs?

**Comment by 9xbt** [comment]
@zarlo we can close this

**Comment by 9xbt** [comment]
we dont support a 6 year old cosmos version anymore man

**Comment by GoldenretriverYT** [comment]
yeah sorry but you seriously cant expect support for a 6 year old version

**Comment by AnErrupTion** [comment]
@Thrilltech Currently, if you want to use Cosmos, you either need to use Windows with VS2022 or Linux with any IDE or code editor. But support won't be provided for such an old version or Cosmos, so even if you get that working, we won't be able to help you.

**Comment by zarlo** [comment]
> @Thrilltech Currently, if you want to use Cosmos, you either need to use Windows with VS2022 or Linux with any IDE or code editor. But support won't be provided for such an old version or Cosmos, so even if you get that working, we won't be able to help you.

well cosmos should work on older version of VS you will just not have the debugger and all the VS depended things (this includes the cosmos project type showing in VS)
