### ISSUE TITLE
Program exiting at random moments.

### ISSUE THREAD

**Issue by xripsdev** [CosmosOS/Cosmos#2751]
Whenever I try to build the project, VMWare runs the OS but then as soon as it establishes a connection with a debugger (I think) it just closes.

This is the output:

In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Creating Secondary ATA IOGroup
ATAPI: Primary controller: False Bus postion: IsMaster: True
ATA device with speclevel ATAPI found
Network Devices Init
Done initializing Cosmos.HAL.Global
Network Stack Init
KeyboardManager.AddKeyboard
Cls
Before Run
The program '' has exited with code 0 (0x0).

This is my code:

using IL2CPU.API.Attribs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Sys = Cosmos.System;

namespace Kernel
{
    public class NanoDOS : Sys.Kernel
    {
        private string currentDirectory;
        protected override void BeforeRun()
        {
            Console.WriteLine("Loading kernel...");
            currentDirectory = Directory.GetCurrentDirectory();

            string sys16Directory = Path.Combine(currentDirectory, "sys16");
            string desktopDirectory = Path.Combine(currentDirectory, "desktop");
            string userInfoFile = Path.Combine(sys16Directory, "user_info.txt");

            if (!Directory.Exists(sys16Directory))
            {
                Directory.CreateDirectory(sys16Directory);
            }

            if (!Directory.Exists(desktopDirectory))
            {
                Directory.CreateDirectory(desktopDirectory);
            }

            if (File.Exists(userInfoFile))
            {
                Login();
            }
            else
            {
                SetNewCredentials(sys16Directory);
            }
        }

        protected override void Run()
        {
            Console.WriteLine("Kernel loaded.");

            TermsAndConditions();

            while (true)
            {
                string desktopDirectory = Path.Combine(currentDirectory, "desktop");
                Directory.SetCurrentDirectory(desktopDirectory);

                Console.WriteLine();
                Console.Write($"[help] {Directory.GetCurrentDirectory()} >> ");
                string command = Console.ReadLine();

                if (command == "about")
                {
                    Console.WriteLine("Encoding type: MST-UNI which stands for Mystic Unicode.");
                }
                else if (command.StartsWith("encrypt "))
                {
                    string filename = command.Substring(8);
                    EncryptFile(filename);
                }
                else if (command.StartsWith("decrypt "))
                {
                    string filename = command.Substring(8);
                    DecryptFile(filename);
                }
                else if (command.StartsWith("mkfile "))
                {
                    string filename = command.Substring(7);
                    CreateFile(filename);
                }
                else if (command.StartsWith("mkdir "))
                {
                    string dirname = command.Substring(6);
                    CreateDirectory(dirname);
                }
                else if (command.StartsWith("cd "))
                {
                    string path = command.Substring(3);
                    ChangeDirectory(path);
                }
                else if (command.StartsWith("openfile "))
                {
                    string filename = command.Substring(9);
                    OpenFile(filename);
                }
                else if (command == "ls")
                {
                    ListContents();
                }
                else if (command.StartsWith("del "))
                {
                    string item_path = command.Substring(4);
                    DeleteItem(item_path);
                }
                else if (command == "help")
                {
                    Console.WriteLine("Available commands:");
                    Console.WriteLine("  - help:            Displays this text.");
                    Console.WriteLine("  - about:           Displays the encoding type.");
                    Console.WriteLine("  - encrypt <path>:  Encrypts a file using the MST-UNI encoding type.");
                    Console.WriteLine("  - decrypt <path>:  Decrypts a file using the MST-UNI encoding type.");
                    Console.WriteLine("  - mkfile <path>:   Creates a new file in the specified path.");
                    Console.WriteLine("  - mkdir <path>:    Creates a new directory in the specified path.");
                    Console.WriteLine("  - openfile <path>: Opens a file in the specified path and displays its content.");
                    Console.WriteLine("  - cd <path>:       Changes to a new directory specified by the user.");
                    Console.WriteLine("  - ls:              Lists all the files/folders in the current working directory.");
                    Console.WriteLine("  - del <item_path>: Deletes a file/folder in the specified directory.");
                }
                else
                {
                    Console.WriteLine($"'{command}' is not recognized. Type 'help' to see the available commands.");
                }
            }
        }

        private void Login()
        {
            
            Console.WriteLine("Enter your username:");
            string enteredUsername = Console.ReadLine();

            Console.WriteLine("Enter your password:");
            string enteredPassword = Console.ReadLine();

            string sys16Directory = Path.Combine(currentDirectory, "sys16");
            string userInfoFile = Path.Combine(sys16Directory, "user_info.txt");

            string[] lines = File.ReadAllLines(userInfoFile);
            if (lines.Length == 2 && lines[0] == enteredUsername && lines[1] == enteredPassword)
            {
                Console.WriteLine("Login successful!");
                Run();
            }
            else
            {
                Console.WriteLine("Invalid username or password. Please try again.");
                Login();
            }
        }

        private void SetNewCredentials(string sys16Directory)
        {
            Console.Write("Enter a username: ");
            string username = Console.ReadLine();
            Console.Write("Enter a password: ");
            string password = Console.ReadLine();

            try
            {
                using (StreamWriter writer = new StreamWriter(Path.Combine(sys16Directory, "user_info.txt"), true))
                {
                    writer.WriteLine($"{username}:{password}");
                    Console.WriteLine("User account created. You can now log in.");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred: {e}");
            }
        }

        static void CreateFile(string path)
        {
            try
            {
                string currentDirectory = Directory.GetCurrentDirectory();
                string fullPath = Path.Combine(currentDirectory, path);

                string directory = Path.GetDirectoryName(fullPath);

                if (directory != null && directory.ToLower() == "sys16")
                {
                    Console.WriteLine("You can't write files to a system directory.");
                    return;
                }

                if (!File.Exists(fullPath))
                {
                    File.Create(fullPath).Close();
                    Console.WriteLine($"File '{path}' created.");
                }
                else
                {
                    Console.WriteLine($"File '{path}' already exists.");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred while creating the file: {e.Message}");
            }
        }

        private void ListContents()
        {
            string[] files = Directory.GetFiles(currentDirectory);
            string[] directories = Directory.GetDirectories(currentDirectory);

            Console.WriteLine($"Contents of {currentDirectory}:");

            foreach (string directory in directories)
            {
                string directoryName = Path.GetFileName(directory);
                Console.WriteLine($"[D] {directoryName}");
            }

            foreach (string file in files)
            {
                string fileName = Path.GetFileName(file);
                Console.WriteLine($"[F] {fileName}");
            }
        }

        private void CreateDirectory(string path)
        {
            try
            {
                string fullDirectoryPath = Path.Combine(currentDirectory, path);
                if (fullDirectoryPath.ToLower() == "sys16")
                {
                    Console.WriteLine("You can't create directories in the sys16 directory.");
                    return;
                }
                Directory.CreateDirectory(fullDirectoryPath);
                Console.WriteLine($"Directory '{path}' created.");
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred while creating the directory: {e.Message}");
            }
        }

        private void OpenFile(string filename)
        {
            string fullPath = Path.Combine(currentDirectory, filename);

            if (Path.GetDirectoryName(fullPath)?.ToLower() == "sys16")
            {
                Console.WriteLine("You can't view files in the sys16 directory.");
                return;
            }

            try
            {
                string content = File.ReadAllText(fullPath);
                Console.WriteLine($"Content of '{filename}':\n{content}");
            }
            catch (FileNotFoundException)
            {
                Console.WriteLine($"Error: File '{filename}' not found.");
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred while opening the file: {e.Message}");
            }
        }

        static void ChangeDirectory(string path)
        {
            try
            {
                string currentDirectory = Directory.GetCurrentDirectory();
                string targetDirectory = Path.Combine(currentDirectory, path);

                if (Directory.Exists(targetDirectory))
                {
                    Directory.SetCurrentDirectory(targetDirectory);
                    Console.WriteLine($"Changed directory to: {targetDirectory}");
                }
                else
                {
                    Console.WriteLine($"Directory '{path}' does not exist.");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred while changing directory: {e.Message}");
            }
        }

        private void DeleteItem(string name)
        {
            string itemPath = Path.Combine(currentDirectory, name);

            if (name.ToLower() == "sys16")
            {
                Console.WriteLine("You can't delete the sys16 directory.");
                return;
            }

            if (IsInsideSys16Directory(itemPath))
            {
                Console.WriteLine("You can't delete items inside the sys16 directory.");
                return;
            }

            if (File.Exists(itemPath))
            {
                File.Delete(itemPath);
                Console.WriteLine($"File '{name}' deleted.");
            }
            else if (Directory.Exists(itemPath))
            {
                Directory.Delete(itemPath, true);
                Console.WriteLine($"Directory '{name}' deleted.");
            }
            else
            {
                Console.WriteLine($"Item '{name}' not found.");
            }
        }

        private bool IsInsideSys16Directory(string path)
        {
            string sys16Directory = Path.Combine(currentDirectory, "sys16");
            return path.StartsWith(sys16Directory, StringComparison.OrdinalIgnoreCase);
        }

        static void TermsAndConditions()
        {
            Console.WriteLine("Terms and Conditions");
            Console.WriteLine("Welcome to the NanoDOS operating system.");
            Console.WriteLine("This program is a custom-built DOS. By using this DOS, you agree to be bound by the following terms and conditions. Please read them carefully.\n");

            Console.WriteLine("1. Encryption and Decryption:");
            Console.WriteLine("   The Program provides the functionality to encrypt and decrypt text using the Mystic Unicode encoding. You understand that the encrypted data may not be reversible, and the decryption process depends on the correct encoding mappings.\n");

            Console.WriteLine("2. Data Security:");
            Console.WriteLine("   While we have taken measures to ensure the security of your data during encryption and decryption, we do not guarantee that the Program is immune to potential vulnerabilities. It is recommended to only use this Program for non-sensitive information.\n");

            Console.WriteLine("3. File Modifications:");
            Console.WriteLine("   When you encrypt a file, the original content will be replaced with the encrypted data. Similarly, decrypting a file will replace the encrypted data with the decrypted text. Make sure to back up important files before using the Program.\n");

            Console.WriteLine("4. Usage Guidelines:");
            Console.WriteLine("   You may use the Program for personal or educational purposes. You agree not to use the Program for any illegal, malicious, or harmful activities. You are responsible for the content you encrypt, decrypt, or transmit using the Program.\n");

            Console.WriteLine("5. No Warranty:");
            Console.WriteLine("   The Program is provided 'as is' without any warranty of any kind, either expressed or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, or non-infringement.\n");

            Console.WriteLine("6. Limitation of Liability:");
            Console.WriteLine("   In no event shall the developers of the Program be liable for any damages, whether direct, indirect, special, incidental, or consequential, arising out of the use or inability to use the Program.\n");

            Console.WriteLine("7. Changes to Terms and Conditions:");
            Console.WriteLine("   The developers of the Program may update or modify these terms and conditions at any time without prior notice. It is your responsibility to review the terms periodically.\n");

            Console.WriteLine("By using the Mystic Unicode Encryption and Decryption Program, you acknowledge that you have read, understood, and agreed to these terms and conditions. If you do not agree with these terms, please refrain from using the Program.\n");

            Console.WriteLine("Last updated: [8/12/2023]\n");
            Console.WriteLine("For any questions or concerns, please contact christofarah18@gmail.com.");
            Console.WriteLine("Github: xripsdev\n");

            Console.Write("Do you agree to the terms and conditions?\nY/n >> ");
            string agreement = Console.ReadLine();
            if (agreement != "Y" && agreement != "y")
            {
                Environment.Exit(0);
            }
        }

        static void EncryptFile(string inputFilename)
        {
            try
            {
                string text = File.ReadAllText(inputFilename);
                string encryptedText = EncodeText(text, EncodingMapping);

                File.WriteAllText(inputFilename, encryptedText);

                Console.WriteLine("File successfully encrypted and saved.\n");
            }
            catch (FileNotFoundException)
            {
                Console.WriteLine("Error: Input file not found.\n");
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred during encryption: {e}\n");
            }
        }

        static void DecryptFile(string inputFilename)
        {
            try
            {
                string encryptedText = File.ReadAllText(inputFilename);
                string decryptedText = DecodeText(encryptedText, DecodingMapping);

                File.WriteAllText(inputFilename, decryptedText);

                Console.WriteLine("File successfully decrypted and saved.\n");
            }
            catch (FileNotFoundException)
            {
                Console.WriteLine("Error: Input file not found.\n");
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred during decryption: {e}\n");
            }
        }

        static string EncodeText(string text, Dictionary<char, string> mapping)
        {
            string encodedText = "";
            foreach (char c in text)
            {
                if (mapping.ContainsKey(c))
                {
                    encodedText += mapping[c];
                }
                else
                {
                    encodedText += c;
                }
            }
            return encodedText;
        }

        static string DecodeText(string encodedText, Dictionary<string, char> mapping)
        {
            string decodedText = "";
            string currentChunk = "";

            foreach (char c in encodedText)
            {
                if (char.IsWhiteSpace(c))
                {
                    decodedText += c;
                }
                else
                {
                    currentChunk += c;
                    if (mapping.ContainsKey(currentChunk))
                    {
                        decodedText += mapping[currentChunk];
                        currentChunk = "";
                    }
                }
            }

            if (!string.IsNullOrEmpty(currentChunk))
            {
                decodedText += currentChunk;
            }

            return decodedText;
        }

        static Dictionary<char, string> EncodingMapping = new Dictionary<char, string>
        {
            {'a', "¿"}, {'b', "Ø˨˩"}, {'c', "ͼ͡"}, {'d', "ѠѓѮ"}, {'e', "ϡϢ"},
            {'f', "θκϡϢ"}, {'g', "ӸӺ"}, {'h', "₣"}, {'i', "▫ⱥ"}, {'j', "▓"},
            {'k', "▓▐"}, {'l', "╗⌠"}, {'m', "Ω∂"}, {'n', "꜠"}, {'o', "ↄ"}, {'p', "♥"},
            {'q', "■"}, {'r', "◊"}, {'s', "☻"}, {'t', "ⱹꜚ"}, {'u', "♫‖"}, {'v', "№"},
            {'w', "ꭘ"}, {'x', "ꭑ"}, {'y', "ꬿ"}, {'z', "ꟿ"},
            {'1', "8"}, {'2', "3"}, {'3', "9"}, {'4', "5"}, {'5', "7"},
            {'6', "0"}, {'7', "2"}, {'8', "1"}, {'9', "4"}, {'0', "6"},
            {'A', "¿"}, {'B', "Ø˨˩"}, {'C', "ͼ͡"}, {'D', "ѠѓѮ"}, {'E', "ϡϢ"},
            {'F', "θκϡϢ"}, {'G', "ӸӺ"}, {'H', "₣"}, {'I', "▫ⱥ"}, {'J', "▓"},
            {'K', "▓▐"}, {'L', "╗⌠"}, {'M', "Ω∂"}, {'N', "꜠"}, {'O', "ↄ"}, {'P', "♥"},
            {'Q', "■"}, {'R', "◊"}, {'S', "☻"}, {'T', "ⱹꜚ"}, {'U', "♫‖"}, {'V', "№"},
            {'W', "ꭘ"}, {'X', "ꭑ"}, {'Y', "ꬿ"}, {'Z', "ꟿ"},
        };

        static Dictionary<string, char> DecodingMapping = new Dictionary<string, char>
        {
            {"¿", 'a'}, {"Ø˨˩", 'b'}, {"ͼ͡", 'c'}, {"ѠѓѮ", 'd'}, {"ϡϢ", 'e'},
            {"θκϡϢ", 'f'}, {"ӸӺ", 'g'}, {"₣", 'h'}, {"▫ⱥ", 'i'}, {"▓", 'j'},
            {"▓▐", 'k'}, {"╗⌠", 'l'}, {"Ω∂", 'm'}, {"꜠", 'n'}, {"ↄ", 'o'}, {"♥", 'p'},
            {"■", 'q'}, {"◊", 'r'}, {"☻", 's'}, {"ⱹꜚ", 't'}, {"♫‖", 'u'}, {"№", 'v'},
            {"ꭘ", 'w'}, {"ꭑ", 'x'}, {"ꬿ", 'y'}, {"ꟿ", 'z'},
            {"8", '1'}, {"3", '2'}, {"9", '3'}, {"5", '4'}, {"7", '5'},
            {"0", '6'}, {"2", '7'}, {"1", '8'}, {"4", '9'}, {"6", '0'},
            {"¿", 'A'}, {"Ø˨˩", 'B'}, {"ͼ͡", 'C'}, {"ѠѓѮ", 'D'}, {"ϡϢ", 'E'},
            {"θκϡϢ", 'F'}, {"ӸӺ", 'G'}, {"₣", 'H'}, {"▫ⱥ", 'I'}, {"▓", 'J'},
            {"▓▐", 'K'}, {"╗⌠", 'L'}, {"Ω∂", 'M'}, {"꜠", 'N'}, {"ↄ", 'O'}, {"♥", 'P'},
            {"■", 'Q'}, {"◊", 'R'}, {"☻", 'S'}, {"ⱹꜚ", 'T'}, {"♫‖", 'U'}, {"№", 'V'},
            {"ꭘ", 'W'}, {"ꭑ", 'X'}, {"ꬿ", 'Y'}, {"ꟿ", 'Z'},
        };
    }
}

I have the nuget packages downloaded.

**Comment by xripsdev** [comment]
And sometimes it gets stuck at HW Bootstrap Init. And sometimes it quits at random moments.

**Comment by xripsdev** [comment]
Never mind I tried Bochs and got the error it's an easy fix.

**Comment by xripsdev** [comment]
Now i have another thing in the output:

In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Creating Secondary ATA IOGroup
ATAPI: Primary controller: False Bus postion: IsMaster: True
ATA device with speclevel ATAPI found
Network Devices Init
Done initializing Cosmos.HAL.Global
Network Stack Init
KeyboardManager.AddKeyboard
Cls
Before Run
Mounting disk
Mounted partition.
Mounting disk
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
The program '' has exited with code 0 (0x0).

It exited from VMWare for no reason at ATAPI: Polling

I tried Bochs but it entered in a Panic state.

**Comment by HyperWinX** [comment]
Try to change ur hdd image, maybe this image is destroyed

**Comment by xripsdev** [comment]
how do I do that? I am new to COSMOS and have no idea.

**Comment by xripsdev** [comment]
> Try to change ur hdd image, maybe this image is destroyed

How do I do that? I am new to Cosmos.

**Comment by HyperWinX** [comment]
In cosmos repo open folders Build/VMware/Workstation, download Filesystem.vmdk, and replace ur image located in C:/Users/(username)/AppData/Roaming/Cosmos User Kit/Build/VMware/Workstation/Filesystem.vmdk with new one, downloaded from GitHub

**Comment by xripsdev** [comment]
I'll try that and I'll let you know.

**Comment by xripsdev** [comment]
For now, in Bochs, it doesn't do anything it just crashes kinda, and in the output in says The program '' has exited with code 0 (0x0). without anything else.

In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
The program '' has exited with code 0 (0x0).

That is the output when I ran it in VMWare.

**Comment by xripsdev** [comment]
And also I forgot to mention that I removed the VFS reference in the BeforeRun() function, so I'll try to re-write it in the function.

**Comment by xripsdev** [comment]
A little progress adding the VFS reference

In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Creating Secondary ATA IOGroup
ATAPI: Primary controller: False Bus postion: IsMaster: True
ATA device with speclevel ATAPI found
Network Devices Init
Done initializing Cosmos.HAL.Global
Network Stack Init
KeyboardManager.AddKeyboard
Cls
Before Run
Mounting disk
Mounted partition.
Mounting disk
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
The program '' has exited with code 0 (0x0).

That's in VMWare.

**Comment by xripsdev** [comment]
Thats in Bochs

![image](https://github.com/CosmosOS/Cosmos/assets/139073674/dc553fe9-0bba-4952-86ee-9e2fbd178a40)

**Comment by HyperWinX** [comment]
U need to use that in VMware, not in bochs

**Comment by xripsdev** [comment]
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Creating Secondary ATA IOGroup
ATAPI: Primary controller: False Bus postion: IsMaster: True
ATA device with speclevel ATAPI found
Network Devices Init
Done initializing Cosmos.HAL.Global
Network Stack Init
KeyboardManager.AddKeyboard
Cls
Before Run
Mounting disk
Mounted partition.
Mounting disk
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
The program '' has exited with code 0 (0x0).

That's the output of VMWare. It just closed the program as soon as it hit ATAPI: Polling

**Comment by xripsdev** [comment]
> U need to use that in VMware, not in bochs

In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Creating Secondary ATA IOGroup
ATAPI: Primary controller: False Bus postion: IsMaster: True
ATA device with speclevel ATAPI found
Network Devices Init
Done initializing Cosmos.HAL.Global
Network Stack Init
KeyboardManager.AddKeyboard
Cls
Before Run
Mounting disk
Mounted partition.
Mounting disk
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 1 SectorCount: 1
ATAPI: Polling
ATAPI: Polling complete
ATAPI: Reading block. Sector: 0 SectorCount: 1
ATAPI: Polling
The program '' has exited with code 0 (0x0).

That's the output of VMWare. It just closed the program as soon as it hit ATAPI: Polling
