### ISSUE TITLE
Cosmos Gui not working for me

### ISSUE THREAD

**Issue by Tsegab432** [CosmosOS/Cosmos#2756]
Sure, here's an example of how you could structure your GitHub issue based on your questions:

#### Area of Cosmos
I am currently working on creating a GUI OS using Cosmos with C#.

#### Expected Behaviour
I expect the canvas, pen, and related functionalities to work as described in the documentation. This should allow me to create graphical elements and interact with them.

#### Actual Behaviour
However, despite installing the dev kit, I'm encountering issues where the canvas, pen, and related features are not functioning as expected. I'm unable to create or manipulate graphical elements as intended.

#### Reproduction
To reproduce this issue, follow these steps:
1. Install the latest dev kit version.
2. Attempt to create a canvas or use the pen functionality to draw on it.
3. Observe that the canvas doesn't render or the pen actions don't take effect.

#### Version
I am using the Dev Kit version of Cosmos. The specific commit versions are as follows:
- Cosmos: [Insert Commit/Version Here]
- IL2CPU: [Insert Commit/Version Here]
- X#: [Insert Commit/Version Here]

I appreciate any assistance in resolving this issue. Thank you!

**Comment by pleasenoban** [comment]
can you give me the code, the docs on the website is really outdated and the pen class is removed

**Comment by GoldenretriverYT** [comment]
If you are using DevKit, you have to use https://cosmosos.github.io/articles/Kernel/CGS.html

**Comment by Tsegab432** [comment]
So I tried the link you gave me @GoldenretriverYT  and still there is somethings missing
![Screenshot 2023-08-31 153412](https://github.com/CosmosOS/Cosmos/assets/116906490/de870d84-31c8-4301-bb5c-5e9bff032b2a)
This one the debugger does not exits in the current context

**Comment by Tsegab432** [comment]
oh wait.. when I remove the debugger code thing it shows a blue screen with random lines.

**Comment by Tsegab432** [comment]
I tried without using the pen class and the canvas, windows, drawwindow and button are missing.
![Screenshot 2023-08-31 154159](https://github.com/CosmosOS/Cosmos/assets/116906490/c2a02ef2-22bd-4bb0-bca9-0f1eaec2fb23)

**Comment by ascpixi** [comment]
There's no such functionality included in Cosmos - these classes never existed at any point. Did you generate the code with AI?

**Comment by ascpixi** [comment]
Ah... it looks like you have also written your issue with GPT.
> Sure, here's an example of how you could structure your GitHub issue based on your questions:

You've forgotten to remove this from its response.

**Comment by Tsegab432** [comment]
Yea my grammar is kind of bad that's why but can you help me fix the problem

**Comment by ascpixi** [comment]
> Yea my grammar is kind of bad that's why but can you help me fix the problem

You'll have to either find an API for creating GUIs, or create your own. I'd recommend you first approach development outside of Cosmos - it's much harder to debug and write code for than for your usual console application.

LLMs like GPT-3/GPT-4 won't help you with development on Cosmos, since it doesn't have any knowledge about Cosmos - it's more about memorization than mastery. I would personally discourage the use of AI for writing mission-critical code altogether, given its tendency to generate sub-par/buggy code.

**Comment by HyperWinX** [comment]
Oh gosh, bro really wrote issue with chatGPT
