### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by NikitaPos** [CosmosOS/Cosmos#2758]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/8d842263-8b8e-4e39-8a3d-b741a05077af)
idk what is this

**Comment by HyperWinX** [comment]
It means, ur OS has unsupported by IL2CPU code

**Comment by NikitaPos** [comment]
> 

how i can fix it?

**Comment by HyperWinX** [comment]
Try debugging and checking code, maybe you'll find it

**Comment by NikitaPos** [comment]
> Try debugging and checking code, maybe you'll find it

fun fact there no errors

**Comment by NikitaPos** [comment]
idk now to be honest

**Comment by NikitaPos** [comment]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/7b8d1b01-f604-451c-a072-08602511167e)
is it error?
@HyperWinX

**Comment by HyperWinX** [comment]
Definitely no, post ur code, or just join official discord server

**Comment by NikitaPos** [comment]
> Definitely no, post ur code, or just join official discord server

where i can send you it

**Comment by HyperWinX** [comment]
In discord server, or just post screenshots here

**Comment by GoldenretriverYT** [comment]
**do what the message tells you to.** and send the build output. it really isnt that hard.
oh yeah, and HyperWinX said, send your code too.

**Comment by NikitaPos** [comment]
> **do what the message tells you to.** and send the build output. it really isnt that hard. oh yeah, and HyperWinX said, send your code too.

ok

**Comment by NikitaPos** [comment]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/7b7d8b90-fff0-43d7-b431-0eed489548bf)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/40287d1e-7585-4344-902c-ad0f60bc7d3f)

**Comment by NikitaPos** [comment]
@GoldenretriverYT @HyperWinX sent

**Comment by HyperWinX** [comment]
U cant use goto's

**Comment by GoldenretriverYT** [comment]
you havent sent your build output

**Comment by NikitaPos** [comment]
> U cant use goto's

what is that

**Comment by NikitaPos** [comment]
> you havent sent your build output

![image](https://github.com/CosmosOS/Cosmos/assets/138600818/b3a09b5a-8b91-4de7-ad21-e993fec4c41d)
there @GoldenretriverYT

**Comment by NikitaPos** [comment]
what it can be?

**Comment by GoldenretriverYT** [comment]
did you really just send 4 fucking lines of the output? i am done with you

it honestly isnt worth helping you

**Comment by NikitaPos** [comment]
> did you really just send 4 fucking lines of the output? i am done with you
> 
> it honestly isnt worth helping you

what i needed lol

**Comment by NikitaPos** [comment]
+ if you dont want to help then dont help

**Comment by GoldenretriverYT** [comment]
you should learn programming before asking for help for every fucking thing

**Comment by NikitaPos** [comment]
> you should learn programming before asking for help for every fucking thing

lol ik 5 languages

**Comment by GoldenretriverYT** [comment]
if you arent even capable of sending a full build log, then you shouldnt bother about making an OS, even with cosmos.

**Comment by GoldenretriverYT** [comment]
> > you should learn programming before asking for help for every fucking thing
> 
> lol ik 5 languages

lol you are incredibly bad at programming and debugging then

**Comment by NikitaPos** [comment]
> > > you should learn programming before asking for help for every fucking thing
> > 
> > 
> > lol ik 5 languages
> 
> lol you are incredibly bad at programming and debugging then

i didnt learned c# b4

**Comment by GoldenretriverYT** [comment]
> > > > you should learn programming before asking for help for every fucking thing
> > > 
> > > 
> > > lol ik 5 languages
> > 
> > 
> > lol you are incredibly bad at programming and debugging then
> 
> i didnt learned c# b4

And what does that have to do with anything? You are incapable of showing us the **full build output**

**Comment by NikitaPos** [comment]
> > > > > you should learn programming before asking for help for every fucking thing
> > > > 
> > > > 
> > > > lol ik 5 languages
> > > 
> > > 
> > > lol you are incredibly bad at programming and debugging then
> > 
> > 
> > i didnt learned c# b4
> 
> And what does that have to do with anything? You are incapable of showing us the **full build output**
missing plug

**Comment by NikitaPos** [comment]
missing plug

**Comment by NikitaPos** [comment]
what is even plug mean (im not form england)

**Comment by NikitaPos** [comment]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/4c56f452-6567-4e23-951d-08ada288086c)

**Comment by GoldenretriverYT** [comment]
> what is even plug mean (im not form england)

read the docs (im not form england) + send the full build output it really isnt that hard... (spoiler: that is not the full build output)

**Comment by NikitaPos** [comment]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/3f49af55-0b77-426b-ab30-355b83dcf0fa)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/8d399989-2a24-4d6c-bc00-ab1f111cefe4)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/38259b5a-e302-42b8-a95e-12dc744d7010)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/ae2ecc58-8ee7-4a48-9b6c-ccc5859fe332)

**Comment by GoldenretriverYT** [comment]
finally. can you please send us your code again? why did you delete it at all?

**Comment by NikitaPos** [comment]
yes

**Comment by PratyushKing** [comment]
for the love of god finally

**Comment by NikitaPos** [comment]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/59dac8dc-a894-4931-a062-0bb7a13cb50b)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/bc56d2f1-3c99-4af7-b991-e90566a8fc83)

**Comment by GoldenretriverYT** [comment]
hmm thats kinda weird, let me take a closer look at it

**Comment by GoldenretriverYT** [comment]
I can't reproduce it. Maybe it was fixed recently, so please install [the devkit](https://cosmosos.github.io/install.html#dev-kit) and try again.

**Comment by NikitaPos** [comment]
> I can't reproduce it. Maybe it was fixed recently, so please install [the devkit](https://cosmosos.github.io/install.html#dev-kit) and try again.

it is with devkit

**Comment by NikitaPos** [comment]
idk now.... it says that i need plug @GoldenretriverYT

**Comment by PratyushKing** [comment]
@NikitaPos We respect your helpful messages throughout this issue. But we request you to reinstall cosmos.

**Comment by NikitaPos** [comment]
> @NikitaPos We respect your helpful messages throughout this issue. But we request you to reinstall cosmos.

how i can delete it at first?

**Comment by PratyushKing** [comment]
Open control panel and delete it like a regular program @NikitaPos

**Comment by NikitaPos** [comment]
okay

**Comment by NikitaPos** [comment]
willl try

**Comment by NikitaPos** [comment]
@PratyushKing do you have discord or smt?

**Comment by PratyushKing** [comment]
Yes we do

**Comment by NikitaPos** [comment]
can you send me link?

**Comment by PratyushKing** [comment]
https://discord.gg/c2BpajZ8

**Comment by NikitaPos** [comment]
fixed bt myfelf :)

**Comment by PratyushKing** [comment]
wow

**Comment by 9xbt** [comment]
oh my fucking god

**Comment by MEMESCOEP** [comment]
> did you really just send 4 fucking lines of the output? i am done with you
> 
> it honestly isnt worth helping you

This is the kind of attitude that drives people away from osdev. Why not try to help by giving useful input instead of expecting everyone to know everything. Cosmos is not intuitive with the way it handles build output. 

Instead of being an ass, try to be a kind & useful member of society.

**Comment by MemeHovy** [comment]
> > did you really just send 4 fucking lines of the output? i am done with you
> > it honestly isnt worth helping you
> 
> This is the kind of attitude that drives people away from osdev. Why not try to help by giving useful input instead of expecting everyone to know everything? Cosmos is not intuitive with the way it handles build output.
> 
> Instead of being an ass, try to be a kind & useful member of society.

I looked through this whole comment section and I swear this is the longest I've seen a github thread of people trying to help a  9 year old trying to work how coding and C# works, like I swear I would lose my patience too if I had to go through something like this, I don't think anyone has the patience to help a -90 IQ person 🗿

**Comment by MEMESCOEP** [comment]
> > > did you really just send 4 fucking lines of the output? i am done with you
> > > it honestly isnt worth helping you
> > 
> > 
> > This is the kind of attitude that drives people away from osdev. Why not try to help by giving useful input instead of expecting everyone to know everything? Cosmos is not intuitive with the way it handles build output.
> > Instead of being an ass, try to be a kind & useful member of society.
> 
> I looked through this whole comment section and I swear this is the longest I've seen a github thread of people trying to help a 9 year old trying to work how coding and C# works, like I swear I would lose my patience too if I had to go through something like this, I don't think anyone has the patience to help a -90 IQ person 🗿

I'm not saying that the author is doing everything right, just that @GoldenretriverYT should be a bit less rude. He's done this many times lol

**Comment by MemeHovy** [comment]
> > > > did you really just send 4 fucking lines of the output? i am done with you
> > > > it honestly isnt worth helping you
> > > 
> > > 
> > > This is the kind of attitude that drives people away from osdev. Why not try to help by giving useful input instead of expecting everyone to know everything? Cosmos is not intuitive with the way it handles build output.
> > > Instead of being an ass, try to be a kind & useful member of society.
> > 
> > 
> > I looked through this whole comment section and I swear this is the longest I've seen a github thread of people trying to help a 9 year old trying to work how coding and C# works, like I swear I would lose my patience too if I had to go through something like this, I don't think anyone has the patience to help a -90 IQ person 🗿
> 
> I'm not saying that the author is doing everything right, just that @GoldenretriverYT should be a bit less rude. He's done this many times lol. Anyway, this isn't the place to start a war, so I'll just stop it here.

ik, I'm saying he probably just lost his patience over trying to help them

**Comment by Arawn-Davies** [comment]
@GoldenretriverYT your conduct on both Discord and GitHub has been abusive, hateful and wholly unacceptable. If you continue to treat other users, beginner or advanced, in the manner you have been doing so, you will be banned from both the discord and from commenting on the GitHub repository.

I sincerely hope you learn how to treat others with respect, no matter how dumb you think the questions are. We were all once in their boat, and by treating others with less experience than you like this, you bring yourself and the entire community down.

Consider this your last warning

**Comment by GoldenretriverYT** [comment]
> @GoldenretriverYT your conduct on both Discord and GitHub has been abusive, hateful and wholly unacceptable. If you continue to treat other users, beginner or advanced, in the manner you have been doing so, you will be banned from both the discord and from commenting on the GitHub repository.
> 
> I sincerely hope you learn how to treat others with respect, no matter how dumb you think the questions are. We were all once in their boat, and by treating others with less experience than you like this, you bring yourself and the entire community down.
> 
> Their comments have been removed from this issue, and they have been reported to GitHub, hopefully will be banned from the repo too.

![speech-bubble-chicken](https://github.com/CosmosOS/Cosmos/assets/49924528/9a926614-a7a0-4592-b787-ccb4da827eeb)

**Comment by GoldenretriverYT** [comment]
no but srsly what the fuck did you expect after we told them like 30 times already (including in other issues) to send the **full** build output and then they send random ass 4 lines, thats literally the most obvious trolling ever as I dont think anyone can be that stupid

**Comment by MEMESCOEP** [comment]
> no but srsly what the fuck did you expect after we told them like 30 times already (including in other issues) to send the **full** build output and then they send random ass 4 lines, thats literally the most obvious trolling ever as I dont think anyone can be that stupid

Just because you tell someone something a few times doesn't mean that you have to be a jerk. Please be nice on the future, it will only help you.

**Comment by GoldenretriverYT** [comment]
> > no but srsly what the fuck did you expect after we told them like 30 times already (including in other issues) to send the **full** build output and then they send random ass 4 lines, thats literally the most obvious trolling ever as I dont think anyone can be that stupid
> 
> Just because you tell someone something a few times doesn't mean that you have to be a jerk. Please be nice on the future, it will only help you.

I got tired of helping them and quit the conversation, what else do you want me to do? Force myself to continue?

**Comment by MEMESCOEP** [comment]
Well you didn't really quit the conversation, as you kept talking and insulting people. I'm gonna stop talking because I don't want to continue this or make the moderator's lives harder. Have a good day.

**Comment by GoldenretriverYT** [comment]
I did not. 

> did you really just send 4 fucking lines of the output? i am done with you
it honestly isnt worth helping you

That was my last comment as far as I remember.

**Comment by PratyushKing** [comment]
bro i swear to god the issue keeps getting worse

**Comment by GoldenretriverYT** [comment]
wow did you just remove the amazing chicken 😢

**Comment by Arawn-Davies** [comment]
> I did not.
> 
> > did you really just send 4 fucking lines of the output? i am done with you
> > it honestly isnt worth helping you
> 
> That was my last comment as far as I remember.

You're not being "employed" as a contributor to the project. You have no obligation to, nor are you a member of coredev. Yes I removed your comment because you're mocking the situation.

If you don't want to 'help' anyone, just leave. Don't come back. You're not welcome here anymore. You have been warned time and time again. Goodbye.
