### ISSUE TITLE
CosmosVFS Gone

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#276]
When i closed my Visual Studio and reinstalled Cosmos because i created some Cosmos code : ReadAllLines(); in System.IO;
So then when i started VS again, i got an error that CosmosVFS Doesn't exist.
Yes i have Using Cosmos.System.FileSystem;
and Using Cosmos.System.FileSystem.VFS;
But CosmosVFS() gone;
There it is:
```C#
private VFSBase VFS;
    ...
VFS = new CosmosVFS();
```
Yellow bulb only says : Create new class 'CosmosVFS'.

**Comment by charlesbetros** [comment]
Did you resolve this?

**Comment by lukaandjelkovic** [comment]
Yes. I reinstalled Cosmos.
