### ISSUE TITLE
MSB6006 xorriso.exe

### ISSUE THREAD

**Issue by NikitaPos** [CosmosOS/Cosmos#2761]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/2c96c592-8f28-48e8-89f4-0053a8d0ecb7)
i made new project didnot changed anything just tested so i see that
log
борка начата…
1>------ Сборка начата: проект: fernet-os, Конфигурация: Debug Any CPU ------
1>Анализаторы пропускаются для ускорения сборки. Для запуска анализаторов можно выполнить команды "Собрать" или "Пересобрать".
1>fernet-os -> C:\Users\HP\source\repos\fernet-os\fernet-os\bin\Debug\net6.0\fernet-os.dll
1>Executing IL2CPU on assembly
1>Kernel Base: Cosmos.System.Kernel
1>Checking target assembly: C:\Users\HP\source\repos\fernet-os\fernet-os\bin\Debug\net6.0\fernet-os.dll
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.INT3Label'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:00:22.0498540
1>-g dwarf2 -f elf -o bin\Debug\net6.0\fernet-os.obj -dELF_COMPILATION -O1 bin\Debug\net6.0\fernet-os.asm
1>Yasm task took 00:00:09.6196011
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\net6.0\fernet-os.bin bin\Debug\net6.0\fernet-os.obj -m elf_i386
1>LD task took 00:00:00.2937389
1>-as mkisofs -relaxed-filenames -J -R -l -o bin\Debug\net6.0\fernet-os.iso  -b boot/limine-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table bin\Debug\net6.0\ISO
1>GNU xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
1>
1>Drive current: -outdev 'stdio:bin\Debug\net6.0\fernet-os.iso'
1>Media current: stdio file, overwriteable
1>Media status : is blank
1>Media summary: 0 sessions, 0 data blocks, 0 data, 29.5m free
1>Added to ISO image: directory '/'='/cygdrive/c/Users/HP/source/repos/fernet-os/fernet-os/bin\Debug\net6.0\ISO'
1>xorriso : UPDATE :       6 files added in 1 seconds
1>xorriso : UPDATE :       6 files added in 1 seconds
1>xorriso : FAILURE : Image size 16941s exceeds free space on media 15134s
1>libisofs: MISHAP : Image write cancelled
1>xorriso : NOTE : -return_with SORRY 32 triggered by problem severity FAILURE
1>C:\Users\HP\.nuget\packages\cosmos.build\0.1.0-localbuild20230904053805\build\Cosmos.Build.targets(387,9): error MSB6006: "xorriso.exe" завершилась с кодом 32.
1>Сборка проекта "fernet-os.csproj" завершена с ошибкой.
========== Сборка: успешно выполнено — 0 , со сбоем — 1, в актуальном состоянии — 0, пропущено — 0 ==========
========== Сборка запущено в 17:45, заняло 32,672 с ==========

**Comment by NikitaPos** [comment]
@PratyushKing

**Comment by PratyushKing** [comment]
after deeply analysing, reinstall cosmos..

**Comment by NikitaPos** [comment]
> after deeply analysing, reinstall cosmos..

5 time?

**Comment by PratyushKing** [comment]
9.5 times

**Comment by NikitaPos** [comment]
💀

**Comment by 9xbt** [comment]
lmfao
