### ISSUE TITLE
Look at screenshots (Vmware special)

### ISSUE THREAD

**Issue by NikitaPos** [CosmosOS/Cosmos#2762]
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/00c91bd4-6bf4-4262-91c2-9eadcfacb528)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/8eba3d82-fedc-4103-9011-179be0a2ba92)
![image](https://github.com/CosmosOS/Cosmos/assets/138600818/447c5cf2-08d2-4a30-a1dc-edc99004bd02)

**Comment by NikitaPos** [comment]
@PratyushKing

**Comment by PratyushKing** [comment]
@zarlo any idea?

**Comment by MEMESCOEP** [comment]
Something seems seriously wrong with your main os, you did need to reinstall cosmos a few times...

**Comment by AsertCreator** [comment]
i'd recommend you to screenshot these errors in one piece, or try to rewrite them as text

**Comment by AsertCreator** [comment]
but overall, your cosmos installation might be corrupted or your code might have incompatibilities with il2cpu or smth. try to reinstall cosmos

**Comment by zarlo** [comment]
are you using a devkit or a userkit

**Comment by NikitaPos** [comment]
> are you using a devkit or a userkit

dev kit

**Comment by NikitaPos** [comment]
I fixed it. Ty all for helping me.

**Comment by MEMESCOEP** [comment]
> I fixed it. Ty all for helping me.

What fixed the issue?
