### ISSUE TITLE
And on types 'System.Boolean' and 'System.Int32' not yet implemented!

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#277]
And on types 'System.Boolean' and 'System.Int32' not yet implemented.

**Comment by mterwoord** [comment]
IL interpreter bug.

**Comment by mterwoord** [comment]
Are you compiling in release mode?

**Comment by lukaandjelkovic** [comment]
No.
I am compiling in debug mode. It doesn't work in userkit or devkit. It magically started to appear.

**Comment by lukaandjelkovic** [comment]
Anybody?

**Comment by lukaandjelkovic** [comment]
0x41 0x6e 0x79 0x6e 0x6f 0x64 0x79 0x20 0x68 0x65 0x72 0x65 0x3f

**Comment by lukaandjelkovic** [comment]
This is impossible, what?

**Comment by mterwoord** [comment]
Please join our chat, we can guide you on how to fix this one..

**Comment by Irxori-TheBetrayed** [comment]
Why is this still open, and why has this issue still got the labels?
