### ISSUE TITLE
Stuck on Serial COM3 preparing

### ISSUE THREAD

**Issue by ADev531** [CosmosOS/Cosmos#2772]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Running on device (DVD-RW)

#### Expected Behaviour - What do you think that should happen?

runs with console shell

#### Actual Behaviour - What unexpectedly happens?

Its Stucks on Serial Preparing

#### Reproduction - How did you get this error to appear?

Deployed iso by imgburn, used CSM to boot.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

i think before devkit 9/12.

**Comment by zarlo** [comment]
did you disable the debugger when building it?
