### ISSUE TITLE
FileNotFoundException FileSystem Error

### ISSUE THREAD

**Issue by JonJon565** [CosmosOS/Cosmos#2778]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Exception occurred while running kernel:
FileNotFoundException

![image](https://github.com/CosmosOS/Cosmos/assets/97921266/7b346c40-6500-4785-a355-cacd2b7e91ae)

![image](https://github.com/CosmosOS/Cosmos/assets/97921266/84412f98-0f86-4e0b-96e3-f527e512b803)

#### Expected Behaviour - What do you think that should happen?
i think it should work duh

#### Actual Behaviour - What unexpectedly happens?
It shows FileNotFoundException

#### Reproduction - How did you get this error to appear?
`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.System.FileSystem;
using System.IO;

namespace TestKernOS
{
    public class Kernel : Sys.Kernel
    {
        Sys.FileSystem.CosmosVFS fs = new Cosmos.System.FileSystem.CosmosVFS();
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
        }

        protected override void Run()
        {
            var available_space = fs.GetAvailableFreeSpace(@"0:\");
            Console.WriteLine("Available Free Space: " + available_space);
        }
    }
}
`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest...

**Comment by 9xbt** [comment]
weird

**Comment by 9xbt** [comment]
devkit or userkit btw

**Comment by JonJon565** [comment]
userkit but i have inno installed and SDK 6.0.414

**Comment by JonJon565** [comment]
and i dont know which one i have dont know how too tell

**Comment by zarlo** [comment]
> and i dont know which one i have dont know how too tell

how did you install cosmos was it with a .exe or did you run a .bat
