### ISSUE TITLE
Dictionary TryGetValue() and [] operator not working 

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#278]
The plug System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType) is required.

This the code that exposes this behaviour:

```
public static Dictionary<string, ICommand> CommandList = new Dictionary<string, ICommand>()
                                               {
                                                        {"info", new Info()},
                                                        {"echo", new Echo()},
                                                        {"cls",  new Cls()},
                                                        //{"calc", new Calc()},
                                                        {"help", new Help()},
                                              };

 ICommand theCommand;

 bool result = CommandList.TryGetValue(Command, out theCommand);
 if (result == false)
 {
            Console.WriteLine("Unknown command '" + Command + 
                                     "' please press 'help' to get a list of aviable commands");
            return;
  }

  // OK let's do something with theCommand
```

Doing    `theCommand = CommandList[Command]` gives the same result.

This the complete result of the compilation:

1>------ Build started: Project: RunOS, Configuration: Debug Any CPU ------
1>  RunOS -> C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll
2>------ Build started: Project: RunOSBoot, Configuration: Debug x86 ------
2>  Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>  Executing command line "C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\System.Core.dll" 
2>  Working directory = 'C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\'
2>  Loaded : DebugEnabled
2>  Loaded : StackCorruptionDetectionEnabled
2>  Loaded : DebugMode
2>  Loaded : TraceAssemblies
2>  Loaded : DebugCom
2>  Loaded : UseNAsm
2>  Loaded : OutputFilename
2>  Loaded : EnableLogging
2>  Loaded : EmitDebugSymbols
2>  Loaded : IgnoreDebugStubAttribute
2>  Loaded : References
2>  Executing IL2CPU on assembly
2>  Plug found: 'System.RuntimeType'
2>  Plug found: 'System.OutOfMemoryException'
2>  Plug found: 'System.Double'
2>  Plug found: 'System.Delegate'
2>  Plug found: 'System.Array'
2>  Plug found: 'System.Buffer'
2>  Plug found: 'System.Enum'
2>  Plug found: 'System.EventHandler'
2>  Plug found: 'System.Exception'
2>  Plug found: 'System.MulticastDelegate'
2>  Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>  Plug found: 'System.Math'
2>  Plug found: 'System.Diagnostics.Debugger'
2>  Plug found: 'System.Byte'
2>  Plug found: 'System.Environment'
2>  Plug found: 'System.GC'
2>  Plug found: 'System.Int16'
2>  Plug found: 'System.Int32'
2>  Plug found: 'System.Int64'
2>  Plug found: 'System.IntPtr'
2>  Plug found: 'System.Number'
2>  Plug found: 'System.Single'
2>  Plug found: 'System.SR'
2>  Plug found: 'System.UInt16'
2>  Plug found: 'System.UInt32'
2>  Plug found: 'System.UInt64'
2>  Plug found: 'System.Threading.Interlocked'
2>  Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>  Plug found: 'System.Resources.ResourceManager'
2>  Plug found: 'System.Net.IPAddress'
2>  Plug found: 'System.Net.SocketAddress'
2>  Plug found: 'System.Globalization.NumberFormatInfo'
2>  Plug found: 'System.Drawing.Color'
2>  Plug found: 'System.Drawing.SR'
2>  Plug found: 'System.Security.CodeAccessSecurityEngine'
2>  Plug found: 'System.Char'
2>  Plug found: 'System.Object'
2>  Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>  Plug found: 'System.RuntimeTypeHandle'
2>  Plug found: 'System.SByte'
2>  Plug found: 'System.String'
2>  Plug found: 'System.UIntPtr'
2>  Plug found: 'System.Security.Cryptography.Utils'
2>  Plug found: 'System.Globalization.CultureInfo'
2>  Plug found: 'Microsoft.Win32.RegistryKey'
2>  Plug found: 'Cosmos.Core.CPU'
2>  Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>  Plug found: 'Cosmos.Core.IOPortBase'
2>  Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>  Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>  Plug found: 'System.Random'
2>  Plug found: 'System.Console'
2>  Plug found: 'System.Type'
2>  Plug found: 'System.Threading.Monitor'
2>  Plug found: 'System.Text.DecoderFallback'
2>  Plug found: 'System.Text.EncoderFallback'
2>  Plug found: 'System.Text.ASCIIEncoding'
2>  Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>  Plug found: 'System.IO.Directory'
2>  Plug found: 'System.IO.DirectoryInfo'
2>  Plug found: 'System.IO.DriveInfo'
2>  Plug found: 'System.IO.File'
2>  Plug found: 'System.IO.FileInfo'
2>  Plug found: 'System.IO.FileStream'
2>  Plug found: 'System.IO.FileSystemInfo'
2>  Plug found: 'System.IO.Path'
2>  Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Object  System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType).
2>   Called from :
2>  System.Collections.Generic.EqualityComparer`1[System.String]::System.Collections.Generic.EqualityComparer`1[System.String] CreateComparer()
2>  System.Collections.Generic.EqualityComparer`1[System.String]::System.Collections.Generic.EqualityComparer`1[System.String] get_Default()
2>  System.Collections.Generic.Dictionary`2[System.String,RunOS.ICommand]::Void .ctor(Int32, System.Collections.Generic.IEqualityComparer`1[System.String])
2>  System.Collections.Generic.Dictionary`2[System.String,RunOS.ICommand]::Void .ctor()
2>  RunOS.Kernel::Void .cctor()
2>  RunOS.Kernel
2>     in Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 528
2>     in Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 673
2>     in Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 254
2>     in Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:riga 238
2>  Loaded assemblies: 
2>  C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>  C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>  C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_it_b77a5c561934e089\mscorlib.resources.dll
2>  Errorred
2>  IL2CPU invoked with DebugMode='Source', DebugEnabled='False', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>  IL2CPU task took 00:00:00.8056837
2>Done building project "RunOSBoot.Cosmos" -- FAILED.
Build has been canceled.

**Comment by mterwoord** [comment]
Dictionary<K,V> uses interfaces heavily, which is not yet supported (and working) in Cosmos.

**Comment by fanoI** [comment]
Ops! So there is no alternative to if / else if / else if or switch for now!

**Comment by mterwoord** [comment]
Yes, you could make a custom dictionary

**Comment by quajak** [comment]
Dictionary are supported with string keys. Other support can be added relatively easily. Ask in Gitter for support if you want to do this.
