### ISSUE TITLE
How to create and manage directories inside of cosmos os

### ISSUE THREAD

**Issue by PantheraTheDev** [CosmosOS/Cosmos#2788]
Hi, I am actually trying to make a replica of MS DOS using cosmos in my own style. I actually want to make a command like mkdir which will create a directory and also the LS command should list the files of the directory in which they are and it should also show in which directory the user is and CD command should change to the specified directory.

![image](https://github.com/CosmosOS/Cosmos/assets/145775300/c55552ac-2015-4601-a538-3702195e7e84)
Something like this. This is from Windows CMD. I would really appreciate if anyone helps me

**Comment by 9xbt** [comment]
use the standard library, this isnt an issue too and should be a discussion
