### ISSUE TITLE
Cosmos doesn't work

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2796]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos itself

#### Expected Behaviour - What do you think that should happen?
Should work

#### Actual Behaviour - What unexpectedly happens?
It doesn't

#### Reproduction - How did you get this error to appear?
`git checkout bf6ee5ab619a7c1af6e3afe7152cb13334abc828` (latest commit has the same issue)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest

**Comment by zarlo** [comment]
we need more into then this

**Comment by Guillermo-Santos** [comment]
If is like med, then the extension is not working, i asume whatever is used to see if the project is a cosmos kernel one is bot working. Since the install run well (tried like 3 times)

**Comment by Kiirx** [comment]
We cant help you if you just say that cosmos doesnt work we need more info

**Comment by 9xbt** [comment]
So building doesn't work, it cant find the Cosmos.Build.Tasks.dll file
it just don't work man

**Comment by 9xbt** [comment]
also the cosmos templates are kinda screwed

**Comment by 9xbt** [comment]
it's completely broken and fucking unusable, we need a development branch because we can't accept pushing non-working shit to the main branch
