### ISSUE TITLE
Foreach List<Type> Problem

### ISSUE THREAD

**Issue by TekuSP** [CosmosOS/Cosmos#280]
Foreaching List<type> is not working. It goes through all items, freezes after last one. 
http://pastebin.com/cQkrUi3z Here is code.

**Comment by AnotherAltr** [comment]
Cosmos does not support the interface, probably...

**Comment by mterwoord** [comment]
Interfaces in general are not supported. Some might work, but in most cases, you should try to not use them. You can change your code to be a for(;;) loop instead.

**Comment by charlesbetros** [comment]
Works now
