### ISSUE TITLE
Visual Studio Workloads was not found. Install install .Net Core 6.0 Runtime, 

### ISSUE THREAD

**Issue by mutethecat** [CosmosOS/Cosmos#2818]
**Describe the problem**
the install-VS2022.bat file is giving me an error that .Net Core 6.0 Runtime is not installed even though it is.

**Steps of installation up to now**
unknown

**Expected behavior**
a successful install.

**Logs**

========================================
    Build Log
========================================

========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads was not found. Install install .Net Core 6.0 Runtime, 

========================================
    Error
========================================

Visual Studio Workloads not found.

**Setup (please complete the following information):**
 Devkit
 No

**Comment by zarlo** [comment]
have you installed Workload: Visual Studio Extension Development?

**Comment by mutethecat** [comment]
> have you installed Workload: Visual Studio Extension Development?

Yes I have.

**Comment by quajak** [comment]
Can you please include a screenshot of them installed?

**Comment by ptobuon** [comment]
You need to check on "Individual components" .NET 6.0 Core Runtime
![image](https://github.com/CosmosOS/Cosmos/assets/98218366/19494743-c999-4530-8f15-ea1b716a5a84)
