### ISSUE TITLE
Convert.ToXXX not implemented

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#282]
I was trying to convert a bool to a byte and doing Convert.ToByte() got "the native plug encountered"!
Same problem is if I try convert the bool to an Int32 so I suspect all the Convert static class is not correctly implemented.

This is the sample test code that shows the issue:

```
     bool test = true;
     int testAsInt = Convert.ToInt32(test);
```

This is the confusing plug error that talks of Decimal.toString()? I don't understand the link between a simple conversion of a boolean in a byte..

1>------ Build started: Project: RunOS, Configuration: Debug Any CPU ------
1>  RunOS -> C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll
2>------ Build started: Project: RunOSBoot, Configuration: Debug x86 ------
2>  Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>  Executing command line "C:\Users\fano\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\fano\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\RunOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\System.Core.dll" 
2>  Working directory = 'C:\Users\fano\Documents\Visual Studio 2013 bkp\Projects\RunOS\RunOS\bin\Debug\'
2>  Loaded : DebugEnabled
2>  Loaded : StackCorruptionDetectionEnabled
2>  Loaded : DebugMode
2>  Loaded : TraceAssemblies
2>  Loaded : DebugCom
2>  Loaded : UseNAsm
2>  Loaded : OutputFilename
2>  Loaded : EnableLogging
2>  Loaded : EmitDebugSymbols
2>  Loaded : IgnoreDebugStubAttribute
2>  Loaded : References
2>  Executing IL2CPU on assembly
2>  Plug found: 'System.RuntimeType'
2>  Plug found: 'System.OutOfMemoryException'
2>  Plug found: 'System.Double'
2>  Plug found: 'System.Delegate'
2>  Plug found: 'System.Array'
2>  Plug found: 'System.Buffer'
2>  Plug found: 'System.Enum'
2>  Plug found: 'System.EventHandler'
2>  Plug found: 'System.Exception'
2>  Plug found: 'System.MulticastDelegate'
2>  Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>  Plug found: 'System.Math'
2>  Plug found: 'System.Diagnostics.Debugger'
2>  Plug found: 'System.Byte'
2>  Plug found: 'System.Environment'
2>  Plug found: 'System.GC'
2>  Plug found: 'System.Int16'
2>  Plug found: 'System.Int32'
2>  Plug found: 'System.Int64'
2>  Plug found: 'System.IntPtr'
2>  Plug found: 'System.Number'
2>  Plug found: 'System.Single'
2>  Plug found: 'System.SR'
2>  Plug found: 'System.UInt16'
2>  Plug found: 'System.UInt32'
2>  Plug found: 'System.UInt64'
2>  Plug found: 'System.Threading.Interlocked'
2>  Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>  Plug found: 'System.Resources.ResourceManager'
2>  Plug found: 'System.Net.IPAddress'
2>  Plug found: 'System.Net.SocketAddress'
2>  Plug found: 'System.Globalization.NumberFormatInfo'
2>  Plug found: 'System.Drawing.Color'
2>  Plug found: 'System.Drawing.SR'
2>  Plug found: 'System.Security.CodeAccessSecurityEngine'
2>  Plug found: 'System.Char'
2>  Plug found: 'System.Object'
2>  Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>  Plug found: 'System.RuntimeTypeHandle'
2>  Plug found: 'System.SByte'
2>  Plug found: 'System.String'
2>  Plug found: 'System.UIntPtr'
2>  Plug found: 'System.Security.Cryptography.Utils'
2>  Plug found: 'System.Globalization.CultureInfo'
2>  Plug found: 'Microsoft.Win32.RegistryKey'
2>  Plug found: 'Cosmos.Core.CPU'
2>  Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>  Plug found: 'Cosmos.Core.IOPortBase'
2>  Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>  Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>  Plug found: 'System.Random'
2>  Plug found: 'System.Console'
2>  Plug found: 'System.Type'
2>  Plug found: 'System.Threading.Monitor'
2>  Plug found: 'System.Text.DecoderFallback'
2>  Plug found: 'System.Text.EncoderFallback'
2>  Plug found: 'System.Text.ASCIIEncoding'
2>  Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>  Plug found: 'System.IO.Directory'
2>  Plug found: 'System.IO.DirectoryInfo'
2>  Plug found: 'System.IO.DriveInfo'
2>  Plug found: 'System.IO.File'
2>  Plug found: 'System.IO.FileInfo'
2>  Plug found: 'System.IO.FileStream'
2>  Plug found: 'System.IO.FileSystemInfo'
2>  Plug found: 'System.IO.Path'
2>  Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.String  System.Number.FormatDecimal(System.Decimal, System.String, System.Globalization.NumberFormatInfo).
2>   Called from :
2>  System.Decimal::System.String ToString()
2>  System.Decimal
2>     in Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 528
2>     in Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 673
2>     in Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:riga 254
2>     in Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\fano\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:riga 238

**Comment by Ray1015** [comment]
I Had The Same Problem. Answer:
Put It In A Variable.

**Comment by fanoI** [comment]
Yes I've found a work around (I did something weird as "test == true ? testAsInt = 1 : testAsInt = 0") but the official method in C# to convert types is that so should work. Well I cannot understand why cannot do a simple cast as in C I'd do...

**Comment by jp2masa** [comment]
a44f62a9acbaeffbf3f8d315bd85fac62f804df2 fixes Convert. Only types currently not working in Cosmos won't work with Convert.

**Comment by RMuskovets** [comment]
I have error like this:
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Plug found: 'Cosmos.Core.CPU'
2>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Plug found: 'Cosmos.Core.IOPortBase'
2>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Plug found: 'System.Char'
2>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Plug found: 'System.Random'
2>	Plug found: 'System.Console'
2>	Plug found: 'System.Type'
2>	Plug found: 'System.Threading.Monitor'
2>	Plug found: 'System.Text.DecoderFallback'
2>	Plug found: 'System.Text.EncoderFallback'
2>	Plug found: 'System.Text.ASCIIEncoding'
2>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Plug found: 'System.IO.Directory'
2>	Plug found: 'System.IO.DirectoryInfo'
2>	Plug found: 'System.IO.DriveInfo'
2>	Plug found: 'System.IO.__Error'
2>	Plug found: 'System.IO.File'
2>	Plug found: 'System.IO.FileInfo'
2>	Plug found: 'System.IO.FileStream'
2>	Plug found: 'System.IO.FileSystemInfo'
2>	Plug found: 'System.IO.Path'
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  System.Runtime.CompilerServices.RuntimeHelpers.Equals(System.Object, System.Object).
2>	 Called from :
2>	System.Object::Boolean Equals(System.Object)
2>	System.String::Boolean Equals(System.String)
2>	   ў Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) ў c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:бва®Є  525
2>	   ў Cosmos.IL2CPU.ILScanner.ScanQueue() ў c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:бва®Є  670
2>	   ў Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) ў c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:бва®Є  255
2>	   ў Cosmos.IL2CPU.CompilerEngine.Execute() ў c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:бва®Є  238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\LINKOR\Documents\Visual Studio 2015\Projects\Roman OS\Roman OS\bin\Debug\Roman OS.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	C:\Users\LINKOR\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\LINKOR\Documents\Visual Studio 2015\Projects\Roman OS\Roman OS\bin\Debug\CGL (Cosmos GUI Library).dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\mscorlib.resources.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.5022300

**Comment by fanoI** [comment]
What was doing your code? Test that two bool were the same?

**Comment by charlesbetros** [comment]
Convert isn't implemented yet.

**Comment by jp2masa** [comment]
This had been fixed, but regressed because there were no tests and we "filtered" plugs during the .NET Core work, leaving only the necessary ones. I'll create a PR to add back the required plugs, and some tests.
