### ISSUE TITLE
cant find an option to compile iso for VS 2015

### ISSUE THREAD

**Issue by saveriokarol112** [CosmosOS/Cosmos#2821]
ive installed user kit and i did my os, but i couldnt find any option to build the iso, ive saw some threads looking at folder net... etc... i dont have that folder! Someone help me?

Thanks

**Comment by MishaProductions** [comment]
only VS 2022 is supported

**Comment by pleasenoban** [comment]
cosmos dropped support for 2015 a long time ago

**Comment by saveriokarol112** [comment]
i used that cuz i use windows 8.1. do still work that for 2022 for that windows?

**Comment by saveriokarol112** [comment]
frick! windows 10 i need for this???

**Comment by pleasenoban** [comment]
well u could install an older version of vs2022 but idk if it works correctly

**Comment by saveriokarol112** [comment]
ive installed windows 10, go see my second issue

**Comment by saveriokarol112** [comment]
is at the top
