### ISSUE TITLE
Endless downloading

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2839]
Trying to reinstall devkit to new version. Delete old version and download new ver. **When installer trying to install IL2CPU, XSharp and common, it's downloads endless**. Idk what to do. Help.
![image](https://github.com/CosmosOS/Cosmos/assets/79642857/8f1fbd8a-2cd1-4f8a-9b1f-7aa3dc6cc5d6)

**Comment by zarlo** [comment]
do you have git install?

**Comment by koteProgrammist** [comment]
> do you have git install?

No, i must download it? I just download .zip of cosmos and try to install

**Comment by zarlo** [comment]
> > do you have git install?
> 
> No, i must download it? I just download .zip of cosmos and try to install

the installer needed it

**Comment by ADev531** [comment]
> > do you have git install?
> 
> No, i must download it? I just download .zip of cosmos and try to install

installer download il2cpu, Common, XSharp with git.

**Comment by koteProgrammist** [comment]
thanks very much to zarlo and adev531, its worked
