### ISSUE TITLE
Cosmos user kit templates not appearing in vs2022

### ISSUE THREAD

**Issue by EpicSentry** [CosmosOS/Cosmos#2840]
**Describe the problem**
A clear and concise description of where the installation is going wrong.
I am installing the latest cosmos userkit which claims to support vs2022, i have the .net and visual studio extension workloads installed and when i install the userkit it says it all completed successfully. Upon rebooting my pc, no templates appear and i cant use cosmos at all.

**Steps of installation up to now**
Install the userkit and restart when prompted, open vs2022 and go to create a new project.

**Expected behavior**
The cosmos kernel templates show up.

**Logs**
Please post the entire log given by Cosmos. For long logs please use pastebin.
None

**Setup (please complete the following information):**
 - Cosmos Version Userkit
 - Are you running installer as administrator? Yes
 - Visual Studio Version if applicable VS2022, latest version

**Additional context**
None

**Comment by GoldenretriverYT** [comment]
If you have VS2019 installed too, make sure to uninstall it.

**Comment by EpicSentry** [comment]
> If you have VS2019 installed too, make sure to uninstall it.

I have 2013, 2015, 2017 and 2022 installed. Not 2019.

**Comment by GoldenretriverYT** [comment]
> > If you have VS2019 installed too, make sure to uninstall it.
> 
> I have 2013, 2015, 2017 and 2022 installed. Not 2019.

They probably cause issues too, make sure to only have 2022 installed. The installer has some problems with other VS installations being present

**Comment by EpicSentry** [comment]
> > > If you have VS2019 installed too, make sure to uninstall it.
> > 
> > 
> > I have 2013, 2015, 2017 and 2022 installed. Not 2019.
> 
> They probably cause issues too, make sure to only have 2022 installed. The installer has some problems with other VS installations being present

Oh god, I guess I'll use a different computer for this as I need these legacy versions installed, thanks for the help.

**Comment by zarlo** [comment]
you can use the cli tool to make the project

**Comment by EpicSentry** [comment]
> you can use the cli tool to make the project

can you tell me how?
