### ISSUE TITLE
Packages and virtual machines not loading 

### ISSUE THREAD

**Issue by hanicraft** [CosmosOS/Cosmos#2842]
I installed both VMware and cosmos and also required version of dotnet but sadly I can't get it working.  When I select and load a template it works but when it's opens up it can't find packages (like cosmos.system, cosmos.debug, etc ) also there is no such a option as run with vm and other stuff. I would be happy if you guys help me. Also when I tried to install nuget packages manually it said it not work on on dotnet framework 5.0

**Comment by zarlo** [comment]
you need to have .net 6 installed

**Comment by hanicraft** [comment]
Alright got it working by installing it on vs2022 but still got some problems 
First when I go to nuget package manager it said it's installed (version 0-*) but still does not recognize it . Also I can't get it working to start vm player
It gives me this error
![۲۰۲۳۱۲۱۱_۱۶۵۸۴۷.jpg](https://github.com/CosmosOS/Cosmos/assets/66449213/83417453-e677-4f52-9ba3-90e392ad6dd8)

**Comment by quajak** [comment]
Try restore the project. Are you connected to the internet since there seems to be an issue reaching nuget.org

**Comment by randomusert** [comment]
@quajak it doesn't Work like that I can from The issue template and it says "NOT nuget.org"

**Comment by quajak** [comment]
In the build logs it states that it is unable to load service index for source https://api.nuget.org/v3/index.json
This sounds like an issue with nuget and not cosmos
