### ISSUE TITLE
Exception of type 'System.Exception' was thrown. in first use

### ISSUE THREAD

**Issue by misagh1389** [CosmosOS/Cosmos#2846]
am select c# Cosmos korner and enter the name after click create show me (Exception of type 'System.Exception' was thrown. in first use)Eror can fix this
![Capture](https://github.com/CosmosOS/Cosmos/assets/110731422/1b56b7c9-e3b6-4c99-af3a-740bae96cd51)
eror message(Visual studio 2022)

**Comment by misagh1389** [comment]
The method you suggested doesn't work (maybe in Windows 10).

**Comment by GoldenretriverYT** [comment]
Can you show me your PATH environment variable (both the System & User PATH please)

**Comment by misagh1389** [comment]
![Capture](https://github.com/CosmosOS/Cosmos/assets/110731422/60c5b0cb-af4a-4f53-9664-90c7624eeffa)
PATH

**Comment by misagh1389** [comment]
![Capture](https://github.com/CosmosOS/Cosmos/assets/110731422/6cdce8e2-a509-4225-bd80-b425d3e9520a)

**Comment by quajak** [comment]
Can you check if the VS logs include anything relevant?

**Comment by jzzjackz** [comment]
this doesnt work, it still errors for me,

**Comment by jzzjackz** [comment]
> 2023-04-20_12-01-31.mp4 
> Its probably this problem. (The video shows the solution and was made by StrieX on the Cosmos DC)

it still doesnt work

**Comment by TajemulCSE** [comment]
> 2023-04-20_12-01-31.mp4 
> Its probably this problem. (The video shows the solution and was made by StrieX on the Cosmos DC)

Thanks. It worked for me.

**Comment by tarik-ozturk** [comment]
> 2023-04-20_12-01-31.mp4 
> Its probably this problem. (The video shows the solution and was made by StrieX on the Cosmos DC)

This worked for me too.. Thanks

**Comment by Tom-Benoit** [comment]
> 2023-04-20_12-01-31.mp4 
> Its probably this problem. (The video shows the solution and was made by StrieX on the Cosmos DC)

Work for me too ! Thank you.

**Comment by arpitajha23** [comment]
not working

**Comment by Vineeth0077** [comment]
Not Working. Please let us know if someone is facing this issue recently and fixed
