### ISSUE TITLE
The COSMOS Template is nowhere in VS 2022

### ISSUE THREAD

**Issue by rIV4444** [CosmosOS/Cosmos#2848]
**Describe the problem**
The template is just not there. The extensions are. But not the template.

**Steps of installation up to now**
Installed VS 2022. Installed COSMOS User-Kit-20221121. No template. Googled. Saw for no support for VS 2022. Un-installed VS 2019 & COSMOS. Installed VS 2019. Installed COSMOS User-Kit-20200209. Still no template. Googled. Now.

**Expected behavior**
There to be a template for COSMOS.

**Logs**
*(There is nothing)*

**Setup (please complete the following information):**
 - Cosmos Version: User-Kit
 - Are you running installer as administrator? Yes.
 - Visual Studio Version if applicable: VS 2019 16.11.32.

***Thank you to the people who help!***

**Comment by zarlo** [comment]
current versions of cosmos only support VS 2022

**Comment by rIV4444** [comment]
> current versions of cosmos only support VS 2022

did you not read what I wrote? I got vs 2022 and it also didn't work, plus I got as vs 2019 version of it

**Comment by zarlo** [comment]
the vs 2019 version is not supported only current user kit and dev kits are

**Comment by rIV4444** [comment]
> the vs 2019 version is not supported only current user kit and dev kits are

I told all of you, I clearly wrote that I already tried VS 2022, WITH the newest COSMOS User-Kit (20221121) and there were no templates there. I then googled for the problem, and ultimately decided to downgrade COSMOS to User-Kit (20200209) & VS 2019, which I have now.

**Comment by rIV4444** [comment]
https://github.com/CosmosOS/Cosmos/assets/97630682/d0c8335e-8955-4c3e-9cea-6113c7aab041

**Comment by rIV4444** [comment]
I needed the VS 2022 .NET Workload.
