### ISSUE TITLE
Cosmos.Hardware.RTC.Year - missing in the new package ?

### ISSUE THREAD

**Issue by eddy0223** [CosmosOS/Cosmos#285]
Hello, 

Can someone tell me what is the new library that replaces "Cosmos.Hardware.RTC.Year" in VS 2015 ? 

I am testing a Cosmos app build with Visual Studio 2013, when I open with VS 2015 I get an error 
     public static int Year = Cosmos.Hardware.RTC.Year; (Missing Reference)     

Thank you

**Comment by mterwoord** [comment]
We need someone to make a plug for the System.DateTime class to make this work.

**Comment by eddy0223** [comment]
Hello,

I have experience with C# and I will love to contribute to your project if you don' t mind.

Ailiam

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Dec 10, 2015 at 11:19 PM -0800, "Matthijs ter Woord" <notifications@github.com<mailto:notifications@github.com>> wrote:


We need someone to make a plug for the System.DateTime class to make this work.

-

**Comment by mterwoord** [comment]
If you want to help out, please join our gitter channel, so we can get you started..

**Comment by cjhannah** [comment]
It's cosmos.HAL not cosmos.Hardware
