### ISSUE TITLE
The Release Configuration Currently isn't supported!

### ISSUE THREAD

**Issue by rIV4444** [CosmosOS/Cosmos#2850]
Have you checked Github Issues for similar errors?: Yes

**Exception**
(the image)

**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build

**How To Reproduce**
Just change to "release", and to "bootable iso"

**Screenshots**
![image](https://github.com/CosmosOS/Cosmos/assets/97630682/d00aded1-091c-47f5-9930-732ea2e6e01e)

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed: yes
[ ] In the NuGet Package Manager "Include prerelease" is selected: yes
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages': yes
[ ] The Cosmos NuGet packages are installed: yes

Add any other context about the problem which might be helpful.
( i am using the newest version of cosmos, with vs 2022)

**Comment by MishaProductions** [comment]
use the debug configuration

**Comment by MishaProductions** [comment]
try disabling remote debugging in the project settings

**Comment by rIV4444** [comment]
> try disabling remote debugging in the project settings

It was not enabled

**Comment by rIV4444** [comment]
> try disabling remote debugging in the project settings

"Remote Debugging" was never enabled, and I would like if you could help me please.

**Comment by zarlo** [comment]
> > try disabling remote debugging in the project settings
> 
> "Remote Debugging" was never enabled, and I would like if you could help me please.

is it disabled in the csproj file? as i think its default is enabled

**Comment by rIV4444** [comment]
I don't think that it's in either:

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_LastSelectedProfileId>C:\Users\bob\source\repos\kerNAL\kerNAL\Properties\PublishProfiles\FolderProfile.pubxml</_LastSelectedProfileId>
  </PropertyGroup>
</Project>
`

and

`<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        
        <Platform>cosmos</Platform>
        <SupportsX86Intrinsics>false</SupportsX86Intrinsics>
        <SelfContained>True</SelfContained>
    </PropertyGroup>

    <PropertyGroup>
        <EnableGDB>False</EnableGDB>
        <StartCosmosGDB>False</StartCosmosGDB>
        <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
        <CosmosDebugPort>Serial: COM1</CosmosDebugPort>
        <Launch>VMware</Launch>
        <Profile>VMware</Profile>
        <Description>Use VMware Player or Workstation to deploy and debug.</Description>
        <PxeInterface>192.168.0.8</PxeInterface>
        <VMWareEdition>Player</VMWareEdition>
        <RemoveBootDebugOutput>True</RemoveBootDebugOutput>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cosmos.Build" Version="0-*" NoWarn="NU1604" />
        <PackageReference Include="Cosmos.Debug.Kernel" Version="0-*" NoWarn="NU1604" />
        <PackageReference Include="Cosmos.System2" Version="0-*" NoWarn="NU1604" />
    </ItemGroup>

</Project>
`

**Comment by 9xbt** [comment]
Release configuration isn't currently supported so if you want to get the iso instead of clicking run click compile, the ISO option is to not run vmware but it does throw an error which just compiling doesn't throw. Cosmos Moment(tm)
