### ISSUE TITLE
Debug Working filesystem but VMware filesystem Error occurs

### ISSUE THREAD

**Issue by RafCodes-del** [CosmosOS/Cosmos#2852]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Filesystem Folders. 

#### Expected Behaviour - What do you think that should happen?
Normal os filesystem - will make folder

#### Actual Behaviour - What unexpectedly happens?
![image](https://github.com/CosmosOS/Cosmos/assets/83568542/8cc990ab-5556-4e0f-854c-fdc888052f3a)

#### Reproduction - How did you get this error to appear?
using System.IO;
using System;

namespace LortOS.Commands
{
    public static class SetupCommand
    {
        public static void Execute(ref string currentDirectory)
        {
            Console.WriteLine("Setting up the LortOS...");

            string prgrmsPath = System.IO.Path.Combine(currentDirectory, "prgrms");
            if (!System.IO.Directory.Exists(prgrmsPath))
            {
                System.IO.Directory.CreateDirectory("prgrms");
                Console.WriteLine("Created 'prgrms' folder. Setup Complete!");
            }
        }
    }
}
my code. seperate from kernel.cs trying to make a folder

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
i.. do not know what version i was running.

Edit: Debug Version works but when i run Debug .iso without VS it shows that error.

**Comment by zarlo** [comment]
```System.IO.Directory.CreateDirectory("prgrms");```
you need to use the full path

**Comment by RafCodes-del** [comment]
It works but when i try running the .iso file on VMware it shows that error.

**Comment by RafCodes-del** [comment]
Debug - With VS Launching or Visual Basic Running VMware
![image](https://github.com/CosmosOS/Cosmos/assets/83568542/66467300-0527-4642-a735-9ee1016cfad1)
Debug - Manual Launch - Without VS Launching VMware:
![image](https://github.com/CosmosOS/Cosmos/assets/83568542/f11423c3-62cf-4aa3-87a6-a433f30f6763)
