### ISSUE TITLE
VMware: Too low memory amount for Limine to load a Cosmos kernel

### ISSUE THREAD

**Issue by RaphMar2021** [CosmosOS/Cosmos#2856]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Bootloader, VMware

#### Expected Behaviour - What do you think that should happen?
Limine should load the kernel

#### Actual Behaviour - What unexpectedly happens?
Limine show an "Out of memory" error.

#### Reproduction - How did you get this error to appear?
By putting a bunch of code in a kernel, and trying to load it in VMware

#### Happening on?
All DevKits and UserKits who uses 256mb of RAM for the test VMware VM

#### How to fix?
By putting an highter memory amount for the test VMware VM

#### Screenshot
![image](https://github.com/CosmosOS/Cosmos/assets/81994075/1cf6fce1-ea83-424c-beea-d0f9aa97aa60)

**Comment by zarlo** [comment]
how big is you kernel .bin file? its in the iso it should be called [project].bin

**Comment by RaphMar2021** [comment]
21mb

**Comment by zarlo** [comment]
mmm

**Comment by RaphMar2021** [comment]
I did puch a bunch of code in it XD

**Comment by RaphMar2021** [comment]
Ahhh, it's because i did put the wrong settings to the Cosmos debugger
