### ISSUE TITLE
Сolor channels are mixed. Canvas.DrawImage(new Bitmap("0:\\myimage.bmp"), 0, 0)

### ISSUE THREAD

**Issue by Kayi-KuzinAlexandr25456** [CosmosOS/Cosmos#2862]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Drawing images on canvas, loaded from a BMP file via `canvas.DrawImage`

#### Expected Behaviour - What do you think that should happen?
Drawing an image exactly like in a BMP file.

#### Actual Behaviour - What unexpectedly happens?
The color channels are mixed. The image is drawn in an incomprehensible color. I used this cycle to eliminate it:

```
for (int y = 0; y < bitmap.Height; y++)
{
    for (int x = 0; x < bitmap.Width; x++)
    {
        Color color = Color.FromArgb(bitmap.RawData[y * bitmap.Width + x]);
        color = Color.FromArgb(255, color.G, color.R, color.A);
        canvas.DrawPoint(color, x, y);
    }
} 
```

#### Reproduction - How did you get this error to appear?
I called `new Bitmap("0:\\myimage.bmp")`, passed the path to the BMP file.

I used the following code: 
```
Stream sr = VFSManager.GetFileStream("0:\\myimage.bmp");
byte[] bitmap_bytes = new byte[sr.Length];
sr.Read(bitmap_bytes, 0, bitmap_bytes.Length);
sr.Close();

canvas.Clear();

Bitmap bitmap = new Bitmap(bitmap_bytes);

for (int y = 0; y < bitmap.Height; y++)
{
    for (int x = 0; x < bitmap.Width; x++)
    {
        Color color = Color.FromArgb(bitmap.RawData[y * bitmap.Width + x]);
        color = Color.FromArgb(255, color.G, color.R, color.A);
        canvas.DrawPoint(color, x, y);
    }
}

canvas.Display();
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Dev Kit, vs-2022

**Comment by zarlo** [comment]
what back end are you using?

**Comment by Kayi-KuzinAlexandr25456** [comment]
> what back end are you using?

what is a back end in this context? What do you mean?

**Comment by zarlo** [comment]
the canvas what back end are you using

**Comment by ADev531** [comment]
you need 32BPP BGR Image. or color channel mixed.

**Comment by Kayi-KuzinAlexandr25456** [comment]
Full screen canvas. Does Cosmos use BGR?

**Comment by ADev531** [comment]
Yes, Cosmos is not RGB, BGR.

**Comment by zarlo** [comment]
it all depends on the backend

**Comment by Kayi-KuzinAlexandr25456** [comment]
> it all depends on the backend

Fine.  What kind of backends are there?

**Comment by zarlo** [comment]
VGA, VBE, SVGAII
