### ISSUE TITLE
heap collect causes freeze

### ISSUE THREAD

**Issue by Samma2009** [CosmosOS/Cosmos#2871]
#### Area of Cosmos - What area of Cosmos are we dealing with?
memory management / GUI

#### Expected Behaviour - What do you think that should happen?
os not freezing

#### Actual Behaviour - What unexpectedly happens?
os freezes

#### Reproduction - How did you get this error to appear?
by calling Heap.Collect() after canvas.display()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest devkit

**Comment by quajak** [comment]
With the current level of details, we will be unable to reproduce and thus fix the issue. Please find a simpler reproduction to share.

**Comment by pleasenoban** [comment]
this could be closed
