### ISSUE TITLE
OS not working on real hardware

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2882]
I have some issues with graphics in real hardware. I have VBECanvas and it worked in VMWare, but when i trying to start it on my notebook (I5-8300H, 16GB RAM, GTX 1050) graphics don't working. I try Canvas instead VBECanvas. My OS is booting normally in UEFI and when graphics is enable system is freeze.

**Comment by valentinbreiz** [comment]
hello, what's the issue when you use VBECanvas with your laptop? It just does nothing or you have errors?

**Comment by koteProgrammist** [comment]
> hello, what's the issue when you use VBECanvas with your laptop? It just does nothing or you have errors?

my OS starts normally but after few seconds it freeze and system not responce

**Comment by koteProgrammist** [comment]
I know it's trouble with VGADriver. Same trouble in #2923
