### ISSUE TITLE
IL2CPU not compiling

### ISSUE THREAD

**Issue by m1ke10** [CosmosOS/Cosmos#2886]
**What is the usecase for this plug**
System.Void & System.Reflection.RuntimeAssembly.GetSimpleName, IL2CPU

**Complexity of plug**
I honestly don't know.

**Describe alternatives you've considered**
I don't believe there is any.

**Additional context**
Add any other context about the plug request here.

**Comment by quajak** [comment]
Please add more information to the issue.

**Comment by m1ke10** [comment]
full stack trace:
Build started at 11:11 PM...
1>------ Build started: Project: NovaOS, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>NovaOS -> C:\Users\bitmi\source\repos\NovaOS\bin\Debug\net6.0\NovaOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\bitmi\source\repos\NovaOS\bin\Debug\net6.0\NovaOS.dll
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.Reflection.RuntimeAssembly.GetSimpleName(System.Runtime.CompilerServices.QCallAssembly, System.Runtime.CompilerServices.StringHandleOnStack)(Plug Signature: System_Void__System_Reflection_RuntimeAssembly_GetSimpleName_System_Runtime_CompilerServices_QCallAssembly__System_Runtime_CompilerServices_StringHandleOnStack_ ).
1>  Static: True
1>  Assembly: System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1>  Called from:
1>System.Reflection.RuntimeAssembly::System.String GetSimpleName()
1>System.Exception::System.String CreateSourceName()
1>System.Exception::System.String get_Source()
1>NovaOS.Kernel::Void BeforeRun()
1>Cosmos.System.Kernel::Void BeforeRun()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 625
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 816
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 276
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 223
1>IL2CPU task took 00:00:01.9345314
1>Done building project "NovaOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:11 PM and took 03.610 seconds ==========

**Comment by quajak** [comment]
There is no implementation for `Exception.Source` right now

**Comment by m1ke10** [comment]
alright
