### ISSUE TITLE
Visual Studio 2015 Community doesnt show the Cosmos Template!

### ISSUE THREAD

**Issue by Delta2Force** [CosmosOS/Cosmos#289]
![Screenshot1](http://i.imgur.com/TYFEsmV.png)
Please answer immediatly!

**Comment by Redall** [comment]
You have few possibilities for the Cosmos Templates are not in the Visual Studio Templates :

1) The templates is not at the good directory :
 * Verify if the templates is located at C:\Users\<yourUserName>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos
 --> If not exists, uninstall the Cosmos User Kit from %appdata%\Cosmos User Kit\unins000.exe file
 --> Delete all zip files from C:\Users\<yourUserName>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos
 --> Install Cosmos
 * If does not work, see the second possibilitie.

2) The version of Visual Studio is not correct.
 * Verify when you open Visual Studio, you see at title bar a text like : 'Visual Studio 2015 Community Edition'
 --> If you don't have this text like this, you will need to download the good version (from Microsoft).
 * Download & install the good version
 * Re-install Cosmos by using steps from the first possibilitie.

**Comment by Delta2Force** [comment]
I have one problem, i am not the Administrator.

**Comment by Redall** [comment]
Oh, so, you need to be with the 'Administrator' user to fix this problem. 
Sorry, but if you try to uninstall, there will need the 'Administrator' user.

**Comment by Delta2Force** [comment]
I asked my father if i could go into his profile and copy all the files of it. It worked.

**Comment by czhower** [comment]
On 12/13/2015 1:06 PM, Delta2Force wrote:
> I asked my father if i could go into his profile and copy all the files
> of it. It worked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmosOS/Cosmos/issues/289#issuecomment-164277667>.
>

As a developer - Cosmos or not - you are going to have a very tough time 
if you are not an admin on your machine.

**Comment by Delta2Force** [comment]
I know.

**Comment by Ray1015** [comment]
I Had To Try 3 Times To Get It Working Even On Admin!

**Comment by zarlo** [comment]
@Delta2Force can you close this if you have fixed it
