### ISSUE TITLE
It Could find the resource .bmp file while Compiling, but it exist in Solution Explorer and Windows File Explorer.

### ISSUE THREAD

**Issue by alessiob07** [CosmosOS/Cosmos#2890]
Have you checked Github Issues for similar errors?
Yes

**Exception**
Post the exception returned by Visual Studio
Exception: System.Exception: Resource 'aleOS.Res.CursorStdWhite.bmp' not found!

**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build
`Build started at 21:28...
1>------ Build started: Project: aleOS, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>E:\Dev\aleOS\aleOS\Hardware\aMouse.cs(28,104,28,120): warning CS0649: Field 'aMouse.BcursorClickSkin' is never assigned to, and will always have its default value null
1>E:\Dev\aleOS\aleOS\Hardware\aMouse.cs(31,103,31,118): warning CS0649: Field 'aMouse.BcursorFuckSkin' is never assigned to, and will always have its default value null
1>E:\Dev\aleOS\aleOS\Hardware\aMouse.cs(25,102,25,116): warning CS0649: Field 'aMouse.BcursorStdSkin' is never assigned to, and will always have its default value null
1>aleOS -> E:\Dev\aleOS\aleOS\bin\Debug\net6.0\aleOS.dll
1>Executing IL2CPU on assembly
1>Kernel Base: Cosmos.System.Kernel
1>Checking target assembly: E:\Dev\aleOS\aleOS\bin\Debug\net6.0\aleOS.dll
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Invalid plug method! Target method not found. : A0SystemInt64A2CosmosSystem_PlugsSystemIOOSFileStreamStrategyImplSeekA0SystemInt64A0SystemObject
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>IL2CPU : error : Exception: System.Exception: Resource 'aleOS.Res.CursorStdWhite.bmp' not found!
1>   at Cosmos.IL2CPU.AppAssembler.ProcessField(FieldInfo aField) in E:\Downloads\Cosmos-main\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 1145
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in E:\Downloads\Cosmos-main\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 985
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable'1 plugsAssemblies) in E:\Downloads\Cosmos-main\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 272
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in E:\Downloads\Cosmos-main\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 186
1>IL2CPU task took 00:00:04.3532912
1>Done building project "aleOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 21:28 and took 05.112 seconds ==========
`

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
On a new Class, I wrote this: 
`internal class aMouse`
`{`
 `   //Init cursors`
`    [ManifestResourceStream(ResourceName = "aleOS.Res.CursorStdWhite.bmp")] public static byte[] BcursorStdSkin;`
`    public static Bitmap cursorStdSkin = new(BcursorStdSkin);`
` ...`

**Screenshots**
![image](https://github.com/CosmosOS/Cosmos/assets/65780895/8d4fab12-1d92-473a-ac7e-a9baf73e3be1)
![image](https://github.com/CosmosOS/Cosmos/assets/65780895/c5807099-3bc9-44fb-b134-6ff91819f347)

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed
YES, are they ok.

Add any other context about the problem which might be helpful.

I watched some tutorials and read code of others that used that and seems equal the path (projectName.Folder.Filename) so idk why it couldn't find it.

**Comment by ascpixi** [comment]
Have you set the "Build Action" property of the file to "Embedded Resource"?

**Comment by alessiob07** [comment]
Oh, no, how should I?

Il ven 12 gen 2024, 00:49 ascpixi ***@***.***> ha scritto:

**Comment by ascpixi** [comment]
As you're using Visual Studio: click on the file you want to embed; its properties should show in the "Properties" window. You can change the "Build Action" from there.
![image](https://github.com/CosmosOS/Cosmos/assets/44982772/aa24bfad-4fb7-4a51-94b4-f2a4f8a178bd)

**Comment by alessiob07** [comment]
Oh. thanks now works.

**Comment by alessiob07** [comment]
Oh thanks, now works!
