### ISSUE TITLE
Canvas.DrawString of accent letters writes wrong chars. (þ instead of è)

### ISSUE THREAD

**Issue by alessiob07** [CosmosOS/Cosmos#2893]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Encoding of DrawString function

#### Expected Behaviour - What do you think that should happen?
Print the char that I insert

#### Actual Behaviour - What unexpectedly happens?
It writes the wrong char.

#### Reproduction - How did you get this error to appear?
aGPU.cnv.DrawString("è", PCScreenFont.Default, Color.White, 100, 10);
But it prints þ.  (Same using \u00E8) 
![image](https://github.com/CosmosOS/Cosmos/assets/65780895/420c9ccb-3d70-4758-b0f2-efc9ff6fb2a2)

![image](https://github.com/CosmosOS/Cosmos/assets/65780895/1caead9f-2a9d-4265-99b3-6bf778379b78)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
05 jan 2024 Devit.

**Comment by quajak** [comment]
The standard font is for https://en.wikipedia.org/wiki/Code_page_437, if you want other characters you have to use another font.
