### ISSUE TITLE
KeyboardManager Assign wrong char when doing a 'Tab' it assing an '\0' instead of '\t'

### ISSUE THREAD

**Issue by Guillermo-Santos** [CosmosOS/Cosmos#2894]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.System and Cosmos.HAL i guess.

#### Expected Behaviour - What do you think that should happen?
To write a tab on the console.

#### Actual Behaviour - What unexpectedly happens?
It writes a null character.

#### Reproduction - How did you get this error to appear?
<img width="680" alt="image" src="https://github.com/CosmosOS/Cosmos/assets/96314559/89df1c2e-a39b-4c13-8d65-7b92eb971e12">

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
- Dev Kit

**Comment by 9xbt** [comment]
I'm confused, so ReadKey() returns `null` when doing a tab?

**Comment by Guillermo-Santos** [comment]
No, it return '\0', the null char. That happends with tab and some others

**Comment by zarlo** [comment]
we might not have the key map?

**Comment by zarlo** [comment]
mmm it looks to be mapped https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Keyboard/ScanMaps/USStandardLayout.cs#L41 but i have no clue dont know much about this part of cosmos

**Comment by zarlo** [comment]
okay we might need to do what is done for space and add '\t' as the second argument

**Comment by Guillermo-Santos** [comment]
i will se if that is

**Comment by Guillermo-Santos** [comment]
> okay we might need to do what is done for space and add '\t' as the second argument

it is and is not at the same time?
<img width="114" alt="image" src="https://github.com/CosmosOS/Cosmos/assets/96314559/0d348baf-978c-4f9e-a018-bd553c70f2a8">
the space i marked on was a tab done with console.readkey, an the dots market on blue are four tabs i did on readline...i'll have to check my console plugs again...xd

**Comment by zarlo** [comment]
i think we had it so /t was hard coded as 4 spaces when printing in Console

**Comment by Guillermo-Santos** [comment]
i changed it to be a dinamic size depending on X cursor position.

The thing on that image is that when i made the change you pointed out readkey started to work correctly, but for some reason readline is getting the wrong char, or is making the wrong conversion.

**Comment by Guillermo-Santos** [comment]
the only difference i see is that ReadKey use Console.WriteLine to write the character, while ReadLine write directly to the textscreen (this because readline actually write to console even when output is redirected).

**Comment by Guillermo-Santos** [comment]
This was the second issue....well...i'll make a PR then
<img width="380" alt="image" src="https://github.com/CosmosOS/Cosmos/assets/96314559/a335d472-b42b-4df2-8ebf-1643d1fd1924">
