### ISSUE TITLE
NullReferenceException occurred

### ISSUE THREAD

**Issue by Lamm-nguy** [CosmosOS/Cosmos#2895]
this is what i get when try to run my os
![image](https://github.com/CosmosOS/Cosmos/assets/112396747/0da2e49f-a432-4df5-9b29-214c64e56a8c)
![image](https://github.com/CosmosOS/Cosmos/assets/112396747/b80182c2-a442-4b0e-91cf-b901d9796ba7)
it is normal when i modify kernel.cs, add Class1.cs ,modify Class1.cs, import Class1.cs to Kernel.cs.
but if i use Class1.cs, it occured

**Comment by zarlo** [comment]
```new class1 gojo``` is wrong 

```class1 gojo = new()```

**Comment by Lamm-nguy** [comment]
new cannot be used with tuple type now. Do i need to use newer dotnet framework version?

**Comment by zarlo** [comment]
why are you using a tuple?

**Comment by Lamm-nguy** [comment]
new () is a tuple

**Comment by zarlo** [comment]
you are using .net 6 right? if not then new Class1()

**Comment by Lamm-nguy** [comment]
still there. hope my log useful:
Setting FirstDataLookupTable to 
0x02244BB3
FirstDataLookupTable was set to 
0x02244BB3
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
Before Core.Global.Init
PCI Devices
ACPI Init
PS/2 Controller Init
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA device with speclevel ATAPI found, which is not supported yet!
Done initializing Cosmos.HAL.Global
KeyboardManager.AddKeyboard
Cls
Before Run
The program '' has exited with code 0 (0x0).

**Comment by 9xbt** [comment]
he's probably using a userkit from like 2018, since he didnt get the latest version working, and that version is long unsupported by now... @valentinbreiz

**Comment by valentinbreiz** [comment]
@Lamm-nguy you should use devkit as @9xbt mentioned
