### ISSUE TITLE
AC97.Initialize causes OS to hang.

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2901]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos Audio Infrastructure

#### Expected Behavior - What do you think that should happen?
The audio driver should start, and system initialization should continue. I know it hangs on `AC97.Initialize()` because of `PrintDebug()` statements and a bootscreen.

#### Actual Behavior - What unexpectedly happens?
It hangs. No error message, no nothing.

#### Reproduction - How did you get this error to appear?
```c#
var Output = AC97.Initialize(4096)
``` 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev kit. Forked it today and merged impl/multitask.

**Comment by quajak** [comment]
impl/multitask is still WIP so we cant make any guarantees everything will work with it right now.
