### ISSUE TITLE
Add Hibernation into Cosmos (suggestion

### ISSUE THREAD

**Issue by Samdasti** [CosmosOS/Cosmos#2913]
Suggested function to add to Cosmos userkit and devkit: Cosmos.System.Power.Hibernate(); - Hibernates the Cosmos OS Project.

Also, i am currently using the user kit.

**Comment by valentinbreiz** [comment]
Hello, this is a good suggestion but needs a good ACPI implementation. ACPI is barely supported in Cosmos but a work is in progress to port [lai](https://github.com/managarm/lai) in Cosmos: [CosmosAML](https://github.com/MishaProductions/AMLParser).
