### ISSUE TITLE
NullReferenceException on GetFullscreenCanvas()

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#2922]
#### Area of Cosmos - What area of Cosmos are we dealing with?
The CGS (Cosmos Graphic Subsystem)

#### Expected Behavior - What do you think that should happen?
I should get a Canvas which I can draw to.

#### Actual Behavior - What unexpectedly happens?
I get a NullReferenceException.

#### Reproduction - How did you get this error to appear?
```c#

            PrintDebug("__sysstartup__");
            c = FullScreenCanvas.GetFullScreenCanvas();
            c.Clear();
            PrintDebug("0");
``` 

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using dev kit, most recent commit as of issue creation.

**Comment by Neil-Ciciglycerin** [comment]
On windows 10, using VS2022, in VMWare Workstation?

**Comment by koteProgrammist** [comment]
> On windows 10, using VS2022, in VMWare Workstation?

Try to enter the resolution like
c = FullScreenCanvas.GetFullScreenCanvas(new Mode(1920, 1080, ColorDepth.ColorDepth32));

or any resolution what you want.

**Comment by valentinbreiz** [comment]
Hello, is debug mode enabled? if yes this is a known issue and you should not using debug with graphics on VMWare :/

**Comment by Neil-Ciciglycerin** [comment]
Ah, it is. Thanks for helping!

**Comment by Neil-Ciciglycerin** [comment]
What, exactly _is_ debug mode, however?

**Comment by zarlo** [comment]
a mode where the debugger code it emitted when building to allow the os to talk to the IDE

**Comment by Neil-Ciciglycerin** [comment]
I figured it out. FOR THE PEOPLES WHO COME HERE IN THE FUTURE: uncheck the checkbox that says "Enable Cosmos Remote Debugger"
