### ISSUE TITLE
VBE Can't change monitor resolution

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2923]
I tried to test my OS on some real hardware, 2 PC's and 2 laptops. My PC don't work because limine is deny :) My second start my OS on VBE graphics mode and all be normal. My laptop decided to use VGA and there's starting some issues... Also it with my second laptop. Check attached screenshots: 
![Безымянный](https://github.com/CosmosOS/Cosmos/assets/79642857/5183cd0a-68b9-4c4e-a469-33adb72cc244)
![Безымянный1](https://github.com/CosmosOS/Cosmos/assets/79642857/ab11f992-e112-4580-a42a-18d31b144f67)

**Comment by pleasenoban** [comment]
that looks like an issue with using the vmware svgaii driver on vbox to me

**Comment by koteProgrammist** [comment]
I found out the VBoxVGA use not VGA! It use VBE! This glitches on VBox screen was because theres be 1024x768 instead 800x600. Why VBE cant change monitor resolution?

**Comment by valentinbreiz** [comment]
> I found out the VBoxVGA use not VGA! It use VBE! This glitches on VBox screen was because theres be 1024x768 instead 800x600. Why VBE cant change monitor resolution?

Pure VBE needs to be in real mode(16bit) to change resolution. Cosmos is 32bit protected mode. The only way now to get VBE working on real hardware is to compile your kernel with VBE informations in multiboot so that the bootloader will set the mode for you when it is still in 16bit mode.

**Comment by koteProgrammist** [comment]
> > I found out the VBoxVGA use not VGA! It use VBE! This glitches on VBox screen was because theres be 1024x768 instead 800x600. Why VBE cant change monitor resolution?
> 
> 
> 
> Pure VBE needs to be in real mode(16bit) to change resolution. Cosmos is 32bit protected mode. The only way now to get VBE working on real hardware is to compile your kernel with VBE informations in multiboot so that the bootloader will set the mode for you when it is still in 16bit mode. 

Thanks you very much! It worked with my laptop, 2 PC's and all VM's!
