### ISSUE TITLE
How do I make a mouse button?

### ISSUE THREAD

**Issue by Utenok12** [CosmosOS/Cosmos#2924]
So I want to make something like a taskbar in macintosh system 1.1, it has buttons, but I do not know how to make them, **there are no textbooks on the Internet**.

**Comment by 9xbt** [comment]
There **are** tutorials on the internet, just not for Cosmos, but you can make them work with cosmos

**Comment by 9xbt** [comment]
also @quajak can you make the tags be the proper ones & close this issue for not complying with this
> **Reporting an issue**
> If you think you found a bug in Cosmos, please check existing [issues](https://github.com/CosmosOS/Cosmos/issues) first before opening a new one. Do not open an issue if you need help with something in Cosmos that is not a bug, if you don't know how to code it's not a Cosmos issue for example.

**Comment by zarlo** [comment]
@Utenok12 https://github.com/CosmosOS/Cosmos/discussions is a better place for asking things like this
