### ISSUE TITLE
How can I implement a taskbar?

### ISSUE THREAD

**Issue by Utenok12** [CosmosOS/Cosmos#2925]
I need a taskbar, like in **macintosh system 1.1**, that is, there should be buttons, and when you click on them, a menu with a list. I do not know how to do this. **Please help me**

**Comment by koteProgrammist** [comment]
If you have some applications, just make own class with all tasks and when you start application, makes variable with your task class. And you can make everything with your task. Also if you want to implement RAM usage, check #2567

**Comment by GoldenretriverYT** [comment]
why did you create a new issue for that?
1) you could have just changed the title of your previous one
2) this fits into discussions, not issues

**Comment by Utenok12** [comment]
> Если у вас есть несколько приложений, просто создайте свой собственный класс со всеми задачами и при запуске приложения сделайте переменную с вашим классом задачи. И вы можете сделать все со своей задачей. Также, если вы хотите реализовать использование оперативной памяти, проверьте #2567

The problem is that I can't create a taskbar

**Comment by Utenok12** [comment]
As I understand it, the GUI in cosmos works terribly, but they must cope with the styling of the 1984 system

**Comment by GoldenretriverYT** [comment]
> As I understand it, the GUI in cosmos works terribly, but they must cope with the styling of the 1984 system

No Buddy most people just don't know how to optimise. And looking at your history of questions you don't even know how to code, so it ain't on you to judge other people.

**Comment by 9xbt** [comment]
# Reporting an issue

If you think you found a bug in Cosmos, please check existing [issues](https://github.com/CosmosOS/Cosmos/issues) first before opening a new one. Do not open an issue if you need help with something in Cosmos that is not a bug, if you don't know how to code it's not a Cosmos issue for example.

**Comment by ascpixi** [comment]
> As I understand it, the GUI in cosmos works terribly, but they must cope with the styling of the 1984 system

Personally, I'd first recommend learning the basics of software development before you criticize the works of others, mainly desktop applications - developing a GUI system is similar to developing a regular user application, just without a widget toolkit.

To add to that, you have incorrectly marked your question as an issue - issues are used to report bugs and to file feature requests. This issue should be converted into a **discussion** instead.

Good luck with your future software development efforts!
