### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by Blackneeed** [CosmosOS/Cosmos#2930]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
AliceBlue Screen Background

#### Actual Behaviour - What unexpectedly happens?
A entirely black screen
Not becuase of the background even with different colors still a black screen drawing a point also black screen just nothing appears

#### Reproduction - How did you get this error to appear?
Running mainCanvas.Clear(Color.AliceBlue);
mainCanvas is my fullscreen canvas (FullScreenCanvas.GetFullScreenCanvas)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit C# CosmosOS with VMware Workstation Pro 17

**Comment by Blackneeed** [comment]
I think its becuase i dont update canvas but i dont update cause there is no such thing as canvas.Update();

**Comment by Blackneeed** [comment]
i mean mainCanvas.Update()

**Comment by 9xbt** [comment]
you dont call canvas.Update(); you don't get anything on the screen.

**Comment by 9xbt** [comment]
also please just move to the devkit it's so much better

**Comment by Blackneeed** [comment]
But there is no such thing as canvas.Update

**Comment by 9xbt** [comment]
canvas.Display?

**Comment by WyattSteinmann** [comment]
canvas.Display.Update(); is a Fix

**Comment by Blackneeed** [comment]
> canvas.Display.Update(); is a Fix

Bruh, you can't even understand a simple conversation of course it's canvas.Display();

**Comment by WyattSteinmann** [comment]
oops i mean canvas.Display();

**Comment by WyattSteinmann** [comment]
i typed it wrong

**Comment by WyattSteinmann** [comment]
In Old Cosmos You Did Not Need canvas.Display(); But Now You Need To Call It Put It At The End Of Your Class With Your GUI Or When Ever You Need To Update The Screen Hope This Helped Even Tho Its Closed
