### ISSUE TITLE
mkisofs exited with code 13

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#2933]
Have you checked Github Issues for similar errors? yes

**Exception**
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"mkisofs.exe" exited with code 13.	tinos_version2	C:\Users\Eetu\.nuget\packages\cosmos.build\0.1.0-localbuild20221121055958\build\Cosmos.Build.targets	392	

**Visual Studio Output Logs**
[output log](https://gist.github.com/randomusert/cb69f39c7bf534847607e4e202acc0ba)

**How To Reproduce**
nothing
**Screenshots**
![kuva](https://github.com/CosmosOS/Cosmos/assets/127417963/8d43d942-afbe-47d1-b83d-7e260279e269)

**Context**
Before posting please confirm that the following are in order
-[ X ] Both Cosmos VS Extensions are installed
-[ X ] In the NuGet Package Manager "Include prerelease" is selected
-[ X ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
-[ X ] The Cosmos NuGet packages are installed

using user kit

**Comment by valentinbreiz** [comment]
Use devkit :)
