### ISSUE TITLE
System.Exception

### ISSUE THREAD

**Issue by Magicgamer1212** [CosmosOS/Cosmos#2934]
#### Expected Behaviour - What do you think that should happen?
no

#### Actual Behaviour - What unexpectedly happens?
when I want to  create a project , then I got a message with System.Exception

#### Reproduction - How did you get this error to appear?
I just want create a project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit

**Comment by randomusert** [comment]
Check #2615
I had the same thing
