### ISSUE TITLE
Cosmos OS shows cosmos cpu exception 0x02.

### ISSUE THREAD

**Issue by Samdasti** [CosmosOS/Cosmos#2935]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting up.

#### Expected Behavior - What do you think that should happen?
It should boot the command line OS.

#### Actual Behavior - What unexpectedly happens?
It shows a bunch of gibberish with this text: 
"Cosmos CPU Exception
GPFor Code: 0x02
General Protection Fault
".

#### Reproduction - How did you get this error to appear?
When i tried to store the prompt, shutdown, restart, and welcome messages in text files.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest userkit.

**Comment by GoldenretriverYT** [comment]
show us your code, we cant smell what you are doing

**Comment by Samdasti** [comment]
> show us your code, we cant smell what you are doing

I already fixed the issue myself, so this issue is now obsolete.
