### ISSUE TITLE
I want to add System_Windows_Forms assembly and i got this error MSB3290

### ISSUE THREAD

**Issue by Magicgamer1212** [CosmosOS/Cosmos#2940]
Have you checked Github Issues for similar errors?
yes

**Exception**
MSB3290

**Visual Studio Output Logs**
Severity Code Description Project File Line Bypass status
Warning MSB3290 Unable to configure wrapper assembly for specific libraries '{215d64d2-031c-33c7-96e3-61794cd1ee61}'. The 'System_Windows_Forms' element library has been exported from a CLR assembly and cannot be re-imported as a CLR assembly. Radiar D:\folders\visual studio\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets 3010

**Context**
Before posting please confirm that the following are in order
[no ] Both Cosmos VS Extensions are installed
[ yes] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
when I want to add System_Windows_Forms assembly then i got this error: MSB3290

**Comment by 9xbt** [comment]
cosmos doesnt support windows forms

**Comment by 9xbt** [comment]
please close this @quajak as it's not meant to be used like that

**Comment by 9xbt** [comment]
thanks
