### ISSUE TITLE
Cosmos doesn't boot from CD with VIA Cyrix III.

### ISSUE THREAD

**Issue by nimmam831** [CosmosOS/Cosmos#2950]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting from CD

#### Expected Behavior - What do you think that should happen?
Should boot, even if it goes slowly.

#### Actual Behavior - What unexpectedly happens?
It just bootloops.

#### Reproduction - How did you get this error to appear?
Use 86Box or PCem, use a machine with VIA Cyrix III, and try to boot it from the .ISO file.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit version 20221121 / 5cf0c98 (#2479)

**Comment by nimmam831** [comment]
Here is the source code (.ZIP):
[source.zip](https://github.com/CosmosOS/Cosmos/files/14250779/source.zip)

**Comment by nimmam831** [comment]
Doesn't say anything, no exception, just reboots

**Comment by nimmam831** [comment]
Accidentally closed

**Comment by randomusert** [comment]
Try Oracle virtual box

**Comment by nimmam831** [comment]
With VirtualBox, it just won't draw (when it creates canvas, it glitches)

**Comment by randomusert** [comment]
Have you tried other software like qemu

**Comment by nimmam831** [comment]
Similar glitches but no icon repeating

**Comment by nimmam831** [comment]
Used -vga cirrus on QEMU to fix it.

**Comment by nimmam831** [comment]
Works with Pentium 3 emulated. Probably doesn't have the right instructions for earlier CPUs.

**Comment by randomusert** [comment]
IT IS Then CPU issue
