### ISSUE TITLE
MSB6006 IL2CPU ended with a code -2147450730 in File Cosmos.Build.targets

### ISSUE THREAD

**Issue by FelekDevYT** [CosmosOS/Cosmos#2952]
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace MyOS
{
    public class Kernel : Sys.Kernel
    {

        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }

        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}

**Comment by quajak** [comment]
Please include build logs
