### ISSUE TITLE
Partition Manager is broken for parition size bigger than 2GB!, because of the data type is `int` instead of `ulong`

### ISSUE THREAD

**Issue by COR-ET** [CosmosOS/Cosmos#2954]
#### Version - ofc DevKit and should be last month version.
![image](https://github.com/CosmosOS/Cosmos/assets/103145985/69d8223f-8df5-4013-9fc0-4fdd5b1bdbf8)

**Comment by zarlo** [comment]
i see no issue with the requested change of replacing the use of int to uint in the VFS and fs drivers

**Comment by COR-ET** [comment]
@zarlo  It would only increase from Max partition size from 2 GB to 4 GB wouldn't it ?

**Comment by zarlo** [comment]
o i meant to put ulong

**Comment by funcieqDEV** [comment]
I have same

**Comment by Blackneeed** [comment]
@zarlo @COR-ET Could you close this?
