### ISSUE TITLE
MSB6006 IL2CPU ended with a code -2147450730 in File Cosmos.Build.targets 

### ISSUE THREAD

**Issue by FelekDevYT** [CosmosOS/Cosmos#2955]
Default code

**Comment by zarlo** [comment]
what version of cosmos are you using?

**Comment by FelekDevYT** [comment]
The latest Cosmos User Kit

**Comment by quajak** [comment]
Please include the build logs

**Comment by FelekDevYT** [comment]
---------------------------
Сбой подтверждения: Прервать=Выход, Повторить=Отладка, Игнорировать=Продолжить
---------------------------
Unexpected exception during Attach

System.Exception: Debug data file C:\Users\cryovacuum\Desktop\Assembler\CosmosKernel1\CosmosKernel1\bin\Debug\net6.0\CosmosKernel1.cdb not found. Project path is C:\Users\cryovacuum\Desktop\Assembler\CosmosKernel1\CosmosKernel1\CosmosKernel1.csproj and iso path C:\Users\cryovacuum\Desktop\Assembler\CosmosKernel1\CosmosKernel1\bin\Debug\net6.0\CosmosKernel1.iso. Could be a omitted build process of Cosmos project so that not created.

   в Cosmos.VS.DebugEngine.AD7.Impl.AD7Process..ctor(Dictionary`2 aDebugInfo, EngineCallback aCallback, AD7Engine aEngine, IDebugPort2 aPort)

   в Cosmos.VS.DebugEngine.AD7.Impl.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended(String aPszServer, IDebugPort2 aPort, String aDebugInfo, String aArgs, String aDir, String aEnv, String aOptions, enum_LAUNCH_FLAGS aLaunchFlags, UInt32 aStdInputHandle, UInt32 aStdOutputHandle, UInt32 hStdError, IDebugEventCallback2 aAD7Callback, IDebugProcess2& oProcess)

   в Cos......

<усечено>
---------------------------
Прервать   Повтор   Пропустить   
---------------------------

**Comment by quajak** [comment]
These are not the entire logs
