### ISSUE TITLE
Cosmos halts on "Found partition at idx 0"

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#296]
I am running latest devkit, 12.12.2015. at 22:00 (in my time zone), so does FAT broke something?

**Comment by mterwoord** [comment]
Are you running on real hardware, or?

**Comment by lukaandjelkovic** [comment]
No, on VMWare.
I reinstalled Cosmos for problem before. (Reinstalling fixes Everything!)

**Comment by lukaandjelkovic** [comment]
Well, i have one MB hard drive for practice
