### ISSUE TITLE
VMWare Issue

### ISSUE THREAD

**Issue by PratyushKing** [CosmosOS/Cosmos#2968]
**Exception**
VMWare no longer in the latest version (released today) supports the Filesystem.vmdk for Cosmos on Windows and Linux, Linux entirely doesn't work (while it did properly with filesystems last release) and Windows no longer supports the Filesystems directly and only the existing ones work.

**Visual Studio Output Logs**
None

**How To Reproduce**
Open an existing Cosmos VMWare machine via VMWare, go to settings of that VM and try adding a new hard disk with the already used Filesystem.vmdk file.

**Screenshots**
![image](https://github.com/CosmosOS/Cosmos/assets/83279568/73d8a1f9-edb8-4f65-b404-9e6521bdf61c)

**Context**
Before posting please confirm that the following are in order
[ ✅ ] Both Cosmos VS Extensions are installed
[ ✅ ] In the NuGet Package Manager "Include prerelease" is selected
[ ✅ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ✅ ] The Cosmos NuGet packages are installed

(A possible solution could be making a new Filesystem.vmdk file but I don't know how to 😕)

**Comment by valentinbreiz** [comment]
Oh that's sad
What virtual disk file type is now supported?

**Comment by selkij** [comment]
Can be closed

**Comment by zarlo** [comment]
@PratyushKing
