### ISSUE TITLE
IL2CPU Documentation references Syslinux when Limine is being used

### ISSUE THREAD

**Issue by MEMESCOEP** [CosmosOS/Cosmos#2969]
#### URL of Documentation - What page of documentation are we dealing with?
https://cosmosos.github.io/articles/Compiler/il2cpu.html

#### Expected Behaviour - What do you think should happen?
The IL2CPU documentation states that Cosmos uses Syslinux

#### Actual Behaviour - What is the issue?
The IL2CPU documentation should be updated to say Limine

**Comment by 9xbt** [comment]
Jesus christ that's old

**Comment by 9xbt** [comment]
Since this is a really easy thing to do, I'm up to fix it and maybe improve that page a bit
