### ISSUE TITLE
Where are the classes?

### ISSUE THREAD

**Issue by indevhero** [CosmosOS/Cosmos#297]
Hello. I have no class "Power.cs" and many others. What to do?

**Comment by indevhero** [comment]
Deboot dont found. 
What to do?

**Comment by Redall** [comment]
Try to :
* Verify if the templates is located at C:\Users<yourUserName>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos --> If not exists, uninstall the Cosmos User Kit from %appdata%\Cosmos User Kit\unins000.exe file --> Delete all zip files from C:\Users<yourUserName>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos --> Install Cosmos

**Comment by indevhero** [comment]
C:\Users\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos <- Three .zip files.

**Comment by Redall** [comment]
Yes. Delete it.

**Comment by indevhero** [comment]
That is, it is necessary to completely remove it and install  to C:\Users\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos ?

**Comment by indevhero** [comment]
Sorry for the stupid question.

**Comment by indevhero** [comment]
I can not delete Cosmos. Error:
Runtime Error (at 37:380)
An error occurred while unregistering Cosmos from Visual Studio!
What to do?

**Comment by Redall** [comment]
I don't know...

**Comment by indevhero** [comment]
Very bad.

**Comment by mterwoord** [comment]
@indevhero The uninstaller not working is a (very) longstanding issue, but nobody steps up to fix it..

You can just install new versions over old versions, though.

**Comment by indevhero** [comment]
I found a problem. I install a very old version. But now another question, how to remove already installed.

**Comment by indevhero** [comment]
The question is closed. The solution found, and now I will understand. Thanks for the help.
