### ISSUE TITLE
'Cosmos.Core_Asm' is incompatible with 'all' frameworks in this project

### ISSUE THREAD

**Issue by winbamstudios** [CosmosOS/Cosmos#2971]
### **THIS IS A LINUX ISSUE**

Have you checked Github Issues for similar errors?
Yes
**Exception**
Post the exception returned by Visual Studio
'Cosmos.Core_Asm' is incompatible with 'all' frameworks in this project
**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build
  Determining projects to restore...
  Writing /tmp/tmpnzUSSb.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/share/dotnet/sdk/8.0.101/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/share/dotnet/sdk/8.0.101/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'Cosmos.Core_Asm' into project '/home/will/OmegaOS/OmegaOS.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/cosmos.core_asm/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/cosmos.core_asm/index.json 3353ms
info : Restoring packages for /home/will/OmegaOS/OmegaOS.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/cosmos.il2cpu/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/cosmos.il2cpu/index.json 3173ms
error: NU1101: Unable to find package Cosmos.IL2CPU. No packages exist with this id in source(s): Cosmos Local Package Feed, nuget.org
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.02.29.05.28.27/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.02.29.05.28.27/2024.03.01.17.28.38/vulnerability.update.json
error: Package 'Cosmos.Core_Asm' is incompatible with 'all' frameworks in project '/home/will/OmegaOS/OmegaOS.csproj'.
**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Install all NuGet packages except the following: Cosmos.Debug.Kernel.Plugs.Asm.0.1.0-localbuild.nupkg Cosmos.System2.0.1.0-localbuild.nupkg IL2CPU.Debug.Symbols.0.1.0-localbuild.nupkg Cosmos.Core_Plugs.0.1.0-localbuild.nupkg Cosmos.HAL2.0.1.0-localbuild.nupkg Cosmos.System2_Plugs.0.1.0-localbuild.nupkg Spruce.0.1.0-localbuild.nupkg Cosmos.Debug.Kernel.0.1.0-localbuild.nupkg Cosmos.Plugs.0.1.0-localbuild.nupkg
Compile on Arch Linux
**Screenshots**
N/A
**Context**
Before posting please confirm that the following are in order
[N/A] Both Cosmos VS Extensions are installed (Linux project)
[#] In the NuGet Package Manager "Include prerelease" is selected
[#] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[#] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by zarlo** [comment]
what .net version is OmegaOS using?

**Comment by winbamstudios** [comment]
8.0.101

**Comment by winbamstudios** [comment]
i'm stupid, i used .net 8 instead of 6
