### ISSUE TITLE
'Visual Studio Workloads is not installed. Please install .Net Core 6.0 Runtime.'

### ISSUE THREAD

**Issue by winbamstudios** [CosmosOS/Cosmos#2979]
**Describe the problem**
After running install-vs2022.bat, default options used, a popup appears saying 'Visual Studio Workloads is not installed. Please install .Net Core 6.0 Runtime.' I have all .NET 6 runtimes + the SDK installed and the Visual Studio extension development workload is installed as well as the .NET application development workload, and a .NET 6 console app does indeed function.

**Steps of installation up to now**
(Windows 11)
Install VS2022 with the VSIX and .NET desktop workload
Download Cosmos source code
Attempt to compile with default options

**Expected behavior**
Cosmos Devkit would begin compiling and install.

**Logs**
Please post the entire log given by Cosmos. For long logs please use pastebin.

```
========================================
    Build Log
========================================


========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads was not found. Install install .Net Core 6.0 Runtime, 


========================================
    Error
========================================

Visual Studio Workloads not found.

```
**Setup (please complete the following information):**
 - Using DevKit
 - Are you running installer as administrator? Yes
 - Visual Studio Version if applicable: VS 2022 17.9.2

**Additional context**
Running on Windows 11 23H2

**Comment by ArtemHasker** [comment]
install .NET Desktop Runtime and SDK [net core 6](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)

**Comment by winbamstudios** [comment]
Here's the thing. I DID.

**Comment by ArtemHasker** [comment]
you installed Universal Windows Platform Development?

**Comment by 9xbt** [comment]
> Here's the thing. I DID.

do this instead
![image](https://github.com/CosmosOS/Cosmos/assets/109512837/7c02b603-59fd-4e26-9634-208a7c8fb61d)

**Comment by 9xbt** [comment]
had the same issue a few days ago and that fixed it

**Comment by 9xbt** [comment]
> you installed Universal Windows Platform Development?

why would he fucking need to install development tools for UWP

**Comment by winbamstudios** [comment]
> > you installed Universal Windows Platform Development?
> 
> why the fuck would he need to install development tools for UWP

idfk
