### ISSUE TITLE
Kernel panic whenever trying to do any thing that has something to do with disk

### ISSUE THREAD

**Issue by Tabby1527** [CosmosOS/Cosmos#2987]
![Screenshot 2024-03-12 093040](https://github.com/CosmosOS/Cosmos/assets/69824094/25694c7b-73f7-4ecb-a988-bb833cf51044)
![Screenshot 2024-03-12 092946](https://github.com/CosmosOS/Cosmos/assets/69824094/b5809dd3-68f3-4ada-af6f-76ab86850577)
![Screenshot 2024-03-12 092910](https://github.com/CosmosOS/Cosmos/assets/69824094/b5bfb341-6f47-4657-b2e4-9ab7c076df39)

#### Expected Behaviour - What do you think that should happen?
To do the command just fine without any error

#### Actual Behaviour - What unexpectedly happens?
Kernel panic

#### Reproduction - How did you get this error to appear?
Whenever trying to do anything that involves  disk

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit

**Comment by 9xbt** [comment]
Can you actually give us code, maybe you didn't init the vfs (really common beginner mistake)

**Comment by Tabby1527** [comment]
Just checked , and I didn't init the vfs , thanks for help, It works now
