### ISSUE TITLE
The two Warnings That Doesn't Exist In Visual Studio And Don't Have Error Codes Like "-rock has same effect as -rational-rock on this platform." or "creating filesystem that does not conform to ISO-9660." What Is This?Its Happend In Visual Studio 2019 So Fix This With A Update Of VS2019

### ISSUE THREAD

**Issue by MateXP20** [CosmosOS/Cosmos#2995]
Have you checked Github Issues for similar errors?

**Exception**
Post the exception returned by Visual Studio

**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by ptobuon** [comment]
They are warnings generated by Cosmos, you don't have to worry about them, as long as they don't prevent you from compiling your project.

**Comment by MishaProductions** [comment]
These warnings are safe to ignore.
