### ISSUE TITLE
The Website Instructions Say To Install VS 2019, But latest Version Runs VS 2022

### ISSUE THREAD

**Issue by ApplePieCodes** [CosmosOS/Cosmos#3003]
#### URL of Documentation - What page of documentation are we dealing with?
https://www.gocosmos.org/docs/install/

#### Expected Behaviour - What do you think should happen?
It should say to download VS 2022

#### Actual Behaviour - What is the issue?
It Says To Download VS 2019

**Comment by randomusert** [comment]
It probally hasn't been updated after vs 2022 release

**Comment by ptobuon** [comment]
The Cosmos website (goCosmos.org) is pretty outdated, you should use the Cosmos documentation (cosmosos.github.io)

**Comment by ADev531** [comment]
So... Can you close it, please?
@ApplePieCodes

**Comment by 9xbt** [comment]
@zarlo can be closed

**Comment by ApplePieCodes** [comment]
> So... Can you close it, please? @ApplePieCodes

sorry, didnt know i needed to close it
