### ISSUE TITLE
Plug for RegularExpression (Regex)

### ISSUE THREAD

**Issue by xavier114** [CosmosOS/Cosmos#3005]
**What is the usecase for this plug**
There should be a plug for RegularExpression so Regex could be Used.

** Complexity of plug **
I dont think so

**Describe alternatives you've considered**
Well i use simpler command

**Additional context**
Its just would be useful for Command lIne parsing which is a big part of Command Line Interface.

**Comment by zarlo** [comment]
when we update to .net 8 we should have support for ".NET regular expression source generators" so you will be able to use regex if the expressions are known at compile time

and as for plugging runtime Regex it makes use of emit and reflection so that will take a while

**Comment by xavier114** [comment]
Okay thanks a lot for this informations.

**Comment by Blackneeed** [comment]
SammaPixelStudio has made a port of RegularExpression for COSMOS: 
https://github.com/Samma2009/System.Text.RegularExpressions

And if you have some questions about it, ask him @samma2009
