### ISSUE TITLE
filesystem

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#3006]
Have you checked Github Issues for similar errors?
YES
**Exception**
Post the exception returned by Visual Studio
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0234	The type or namespace name 'FileSystem' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?)	tinos	C:\Users\Kone\Desktop\tinos\tinos\tinos\Kernel.cs	11	Active	

**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build
Build started at 20.13...
1>------ Build started: Project: tinos, Configuration: Debug Any CPU ------
1>C:\Users\Kone\Desktop\tinos\tinos\tinos\Kernel.cs(11,50,11,60): error CS0234: The type or namespace name 'FileSystem' does not exist in the namespace 'Cosmos' (are you missing an assembly reference?)
1>Done building project "tinos.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 20.14 and took 04,913 seconds ==========

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
try and initialize the VFS
**Screenshots**
![image](https://github.com/CosmosOS/Cosmos/assets/127417963/dc85cc90-43e6-4e09-9c4d-509cb8c79a72)

**Context**
Before posting please confirm that the following are in order
[ X ] Both Cosmos VS Extensions are installed
[ X ] In the NuGet Package Manager "Include prerelease" is selected
[ X ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ X ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by Blackneeed** [comment]
It’s not Cosmos.Filesystem but its Cosmos.System.Filesystem

**Comment by randomusert** [comment]
It was from The website sothat was  wrong
