### ISSUE TITLE
CS0120

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#3008]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.Hal.TextScreenBase.Clear()

#### Expected Behaviour - What do you think that should happen?
not give an error

#### Actual Behaviour - What unexpectedly happens?
it gives CS0120

#### Reproduction - How did you get this error to appear?
add Cosmos.HAL.TextScreenBase.Clear()

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
userkit

### spesific error
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0120	An object reference is required for the non-static field, method, or property 'TextScreenBase.Clear()'	tinos_version2	C:\Users\Kone\Desktop\tinos_version2\tinos_version2\Kernel.cs	17	Active

**Comment by zarlo** [comment]
what are you trying to do?

**Comment by randomusert** [comment]
Clear The screen

**Comment by zarlo** [comment]
then you want ``Console.Clear()`` https://learn.microsoft.com/en-us/dotnet/api/system.console.clear?view=net-8.0

**Comment by randomusert** [comment]
I didn't know that .net has that bult in
