### ISSUE TITLE
VBE Canvas - positioning issue

### ISSUE THREAD

**Issue by SzymekkYT** [CosmosOS/Cosmos#3009]
#### Area of Cosmos - What area of Cosmos are we dealing with?
VBE Canvas/Graphics

## (SVGAII Canvas)
![obraz_2024-04-29_205308616](https://github.com/CosmosOS/Cosmos/assets/69077038/030677a7-fa21-458d-931c-14b69edff09a)

## (VBE Canvas)
![obraz_2024-04-29_205543430](https://github.com/CosmosOS/Cosmos/assets/69077038/88d0bb34-4a51-4bf6-b568-2b8a902badd0)
![obraz_2024-04-29_205333885](https://github.com/CosmosOS/Cosmos/assets/69077038/72faf0cc-655b-4681-b74c-22d3666ad793)
^Real hardware

#### Reproduction - How did you get this error to appear?
Just 	make a vbe canvas
GUI.MainCanvas  =  new VBECanvas(new Mode(GUI.ScreenSizeX, GUI.ScreenSizeY, Cosmos.System.Graphics.ColorDepth.ColorDepth32));
and draw multiple (like 3) images.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit - latest [c6155b9](https://github.com/CosmosOS/Cosmos/commit/c6155b904d8730be63665fe129592a312e0a0913)

**Comment by funcieqDEV** [comment]
:( its big bug

**Comment by Blackneeed** [comment]
Skill issue
Uh i didnt say nothiing

**Comment by MrJachowski21** [comment]
I have the same bug

**Comment by SzymekkYT** [comment]
more like cosmos skill issue 🗿

**Comment by Blackneeed** [comment]
Emmmm, ..., i think i meant that (maybe)

**Comment by zarlo** [comment]
can you post a recreate able test

**Comment by SzymekkYT** [comment]
Okay, also i think that only drawing images is bugged
SVGAIICanvas
![obraz_2024-04-30_173334505](https://github.com/CosmosOS/Cosmos/assets/69077038/bba4c25c-d4b8-4423-943f-feae86a8b7a2)
VBE
![obraz_2024-04-30_173433188](https://github.com/CosmosOS/Cosmos/assets/69077038/3ac9990f-5764-497a-adcf-045f1bf6fb93)

[Code here cuz github deleted whitespaces](https://szymekk.pl/VbeTest.cs)

**Comment by valentinbreiz** [comment]
I also had this bug on virtual box, "fixed" by implementing compositing

**Comment by SzymekkYT** [comment]
Well i cant do compositing because i have to change many images multiple times. Also first frame is good, but then its all broken 
first frame:
![obraz_2024-04-30_175502764](https://github.com/CosmosOS/Cosmos/assets/69077038/e4f7e21e-bb48-4797-960f-7a199036891e)
later:
![obraz_2024-04-30_175417992](https://github.com/CosmosOS/Cosmos/assets/69077038/2a6683e9-f90d-4b30-94e2-0ec08e9a9ff5)

**Comment by valentinbreiz** [comment]
Really weird
I'll investigate when I will have time. But you still should implement compositing I think

**Comment by SzymekkYT** [comment]
Yea but it still cant handle more than 2 images 
SVGAIICanvas
![image](https://github.com/CosmosOS/Cosmos/assets/69077038/74194be4-eeb0-4725-9776-db03a1ce121b)

VBE:
![obraz_2024-04-30_180906855](https://github.com/CosmosOS/Cosmos/assets/69077038/c357b223-571e-4d7a-8739-0a05ccc3a859)
(just change i < 1)
