### ISSUE TITLE
VBECanvas display issue

### ISSUE THREAD

**Issue by ThatGuyAstral** [CosmosOS/Cosmos#3014]
#### Area of Cosmos - What area of Cosmos are we dealing with?

CGS’s VBECanvas

#### Expected Behaviour - What do you think that should happen?

On a 1920x1080 monitor, Cosmos should display a GUI with no issues

#### Actual Behaviour - What unexpectedly happens?

The GUI is displayed incorrectly but is still running

#### Reproduction - How did you get this error to appear?

Just create a VBECanvas with a mode of 1920x1080x32 and also specify VBE Multiboot Info and draw anything

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Devkit (Before Szymekk’s FS Fix)
![Image of proof](https://github.com/CosmosOS/Cosmos/assets/144744086/576c8e2a-7a44-450d-94c1-d4e2a7169344)

**Comment by Kiirx** [comment]
Hi can you provide us your code and the project .csproj?

**Comment by ThatGuyAstral** [comment]
oh crap forgot about this GitHub post

**Comment by ThatGuyAstral** [comment]
I fixed it already

**Comment by ThatGuyAstral** [comment]
by setting the canvas resolution to 1024x768

**Comment by Kiirx** [comment]
If you think it's fixed you can close it then

**Comment by 9xbt** [comment]
limine usually gives you a 1024x768 canvas with grub so yh cosmos just thinks its the resolution youre saying but cosmos uses grub so no
