### ISSUE TITLE
Can’t find one for vs-2010

### ISSUE THREAD

**Issue by Miner2589** [CosmosOS/Cosmos#3015]
Badly need a version for vs-2010 but can’t find one here. Website proves that they exist. Homing for a release from 2010/11

**Comment by Gabolate** [comment]
Try the oldest userkit available (year 2015), there are some VS 2010 mentions: https://github.com/CosmosOS/Cosmos/blob/v0.20150130/Docs/Express/Compile.md

**Comment by 9xbt** [comment]
cosmos was on codeplex before, go there for earlier releases. also why the fuck would you create that issue here

**Comment by Gabolate** [comment]
> cosmos was on codeplex before, go there for earlier releases. also why the fuck would you create that issue here

I tried using the wayback machine to see if it was possible to download older versions from codeplex as it dosen't exist anymore, but it just displays the 'thanks for downloading' text, it seems like the code that makes the download start dosen't work or wasn't saved in the wayback machine
