### ISSUE TITLE
Won’t boot on old computers

### ISSUE THREAD

**Issue by Miner2589** [CosmosOS/Cosmos#3016]
So older devices like the thinkpad 570 from ibm and like 90s stuff used it boot into cosmos with vs-2010 versions but now with the latest version of cosmos it just hangs at the blinking underscore.

I am having the issue with the user kit and vs 2022

**Comment by Gabolate** [comment]
Are you using devkit or userkit? (please give more info when making an issue)

**Comment by Miner2589** [comment]
User

**Comment by Gabolate** [comment]
Does the 'welcome to grub' text appear or is it just black screen when trying to boot?

**Comment by Miner2589** [comment]
Bit like trying to boot off a blank cd. The files are on the main partition on my hdd so I won't be a cd error

**Comment by Gabolate** [comment]
Do other OS (not cosmos) work in those pcs?

**Comment by Miner2589** [comment]
Yes, both have a functional copy of windows 98se (or did before cosmos)

**Comment by 9xbt** [comment]
maybe grub doesnt like it

**Comment by Miner2589** [comment]
Is that replaceable? The grub?

**Comment by Gabolate** [comment]
the devkit uses limine, but that's more modern so it might not work either, grub is really old actually (made since 1995) an older version could work

**Comment by Miner2589** [comment]
How can I implement an older version of grub?

**Comment by Miner2589** [comment]
Can I just change the files for grub or do I need to reconfigure my bin file

**Comment by Blackneeed** [comment]
> Can I just change the files for grub or do I need to reconfigure my bin file

You cant. But what you can do instead is replace the bootloader injection command i think it's in a file called MakeIso.cs or something, but if not, then look for it Cosmos.Build.Tasks somewhere.

Blackneeed - 2024

**Comment by tails2012timnew** [comment]
I tried to run it on my old gateway GP6-490 and it shows the cosmos splash screen (I think the bootloader) then it "loads" but the screen is black. Could be because it is trying to use gui

**Comment by zarlo** [comment]
how are you setting up the GUI

**Comment by Miner2589** [comment]
I’m not using GUi I’m using the default welcome to cosmos screenOn 15 Aug 2024, at 5:40 AM, zarlo ***@***.***> wrote:﻿
how are you setting up the GUI

**Comment by Gabolate** [comment]
> Bit like trying to boot off a blank cd. The files are on the main partition on my hdd so I won't be a cd error

If only the files are on your main partition, it could explain why its not working. you see, GRUB is stored on the MBR, its not a file you can copy from the ISO. you could either burn the ISO into a CD or somehow install the bootloader

**Comment by MishaProductions** [comment]
Please open an issue an limine repo.

**Comment by Miner2589** [comment]
I wrote a custom boot loader, that worked perfectly but I just don't understand why Grub dosent like it.

**Comment by Miner2589** [comment]
> Please open an issue an limine repo.

What does that mean?

**Comment by MishaProductions** [comment]
https://github.com/limine-bootloader/limine/issues/new

**Comment by Miner2589** [comment]
It's grub.

**Comment by SzymekkYT** [comment]
try switching to devkit. Also remember that propably only VGA is going to work (its pain)

**Comment by Miner2589** [comment]
I don’t like the dev kit gui or script system. But I’ll try it

**Comment by SzymekkYT** [comment]
dev kit gui or script system? its a new better and newer version of cosmos...

**Comment by SzymekkYT** [comment]
userkit is just a prebuild but its 2yrs old
