### ISSUE TITLE
"Visual Studio Workloads was not found. Install install .Net Core 6.0 Runtime"

### ISSUE THREAD

**Issue by WushR00M** [CosmosOS/Cosmos#3020]
**Describe the problem**
I follow every step correctly, but when I tried to use the Kit Builder, it asks for .Net Core 6.0 Runtime, which is already installed. I'm using the latest dev kit and Windows 11.

**Steps of installation up to now**

- Run Batch File as Administrator
- Cosmos Kit Builder opens
- Follow steps
- Error happens here!

**Expected behavior**
The process of CosmosOS installing should've continued as normal.

**Logs**

```
========================================
    Build Log
========================================


========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads was not found. Install install .Net Core 6.0 Runtime, 


========================================
    Error
========================================

Visual Studio Workloads not found.
```

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit) **Devkit**
 - Are you running installer as administrator? **Yes**

**Comment by Gabolate** [comment]
Did you installed .NET SDK apart from Runtime?

**Comment by 9xbt** [comment]
He probably didn't. It says right in the installation prerequesites to do that

**Comment by WushR00M** [comment]
Closing issue, just realized I accidently chose VS 2019 instead of VS 2022 :b
