### ISSUE TITLE
Build ISO Doesn't Work At All

### ISSUE THREAD

**Issue by Doofus-Mc-Goofus** [CosmosOS/Cosmos#3024]
Using the latest user kit, Visual Studio 2022, and Windows 10. Literally NO changes to the C# sample program and it doesn't work. IDFK how to replicate it.

MSB6006 "yasm.exe" exited with code -1073741515.

![a](https://github.com/CosmosOS/Cosmos/assets/170259314/294d0554-b2c9-41b4-ac5f-042461143e22)

Help would be appreciated. Sorry if I missed any important details, new to this bug reporting thing.

UPDATE: Fix a problem, but got 2 new ones.
![1](https://github.com/CosmosOS/Cosmos/assets/170259314/9b655386-7d4f-4f22-983e-c5136073c208)
![2](https://github.com/CosmosOS/Cosmos/assets/170259314/6c658b88-5833-454d-802a-fcd4ab1aff21)

**Comment by Blackneeed** [comment]
Install VC++ 2010 MLC security update
https://www.microsoft.com/en-us/download/details.aspx?id=26999

**Comment by Blackneeed** [comment]
@Doofus-Mc-Goofus

**Comment by Doofus-Mc-Goofus** [comment]
I will try that. thx

**Comment by Blackneeed** [comment]
Np, i believe this should work.

**Comment by Doofus-Mc-Goofus** [comment]
Fixed something, but got 2 new errors.
![1](https://github.com/CosmosOS/Cosmos/assets/170259314/957329de-aa51-4c73-9872-e5a1feeeaa69)
![2](https://github.com/CosmosOS/Cosmos/assets/170259314/62fcfb0e-0653-42eb-85f8-c20ccfab8fda)

**Comment by Blackneeed** [comment]
In the settings, have you chose to build to an iso instead of vmware, if yes these errors will always appear but ur iso is in project dir\bin\debug\net6.0/PROJECTNAME.iso

**Comment by Doofus-Mc-Goofus** [comment]
Thanks for the help.

**Comment by alessiob07** [comment]
same issue here

**Comment by Blackneeed** [comment]
Glad i was able to help!
