### ISSUE TITLE
can someone help me i dont know how to fix this

### ISSUE THREAD

**Issue by ChipVR11** [CosmosOS/Cosmos#3030]
i get an error

**Steps of installation up to now**
Steps to reproduce the behavior: start installing it

**Expected behavior**
download with no errors

**Logs**

https://pastebin.com/qPzVGc7V

i have everything needed.

im stupid

**Comment by Gabolate** [comment]
Do you have .NET 6.0 runtime installed?

**Comment by ChipVR11** [comment]
yes i have .net 6.0 installed

**Comment by ThatGuyAstral** [comment]
odd, it’s an IL2CPU error
