### ISSUE TITLE
Nothing happens to me after starting my OS (the input cursor flashes, but I did not add this to the code)

### ISSUE THREAD

**Issue by FelekDevYT** [CosmosOS/Cosmos#3031]
Code of my os : https://github.com/FelekDevYT/FelsOS-myOS-

**Comment by FelekDevYT** [comment]
In the console of my OS, I entered a command to delete the file. After that, an input cursor appeared on the next line, but nothing was entered, and this is not how command input looks in my OS.I decided to restart the OS with a button on Vmware. Then I turned on my OS again and what I said above appeared there.

**Comment by MishaProductions** [comment]
Please provide screenshots and source code.
