### ISSUE TITLE
Cosmos is not reading my code

### ISSUE THREAD

**Issue by Megasimister** [CosmosOS/Cosmos#3037]
Hello, i have an issue with Cosmos User Kit. I normally create project and edit text for example i delete "Input, Output", i insert some commands and when i boot it, OS is running on original code and i dont know how to fix. Please help :)

**Comment by ThatGuyAstral** [comment]
hey um i know this might not be relevant to your problem but, you should use the dev kit

**Comment by MEMESCOEP** [comment]
You may need to clear your build cache, I've had this happen to me numerous times. Iirc you can clear the build cache by deleting the `bin` folder (maybe the `obj` folder too)
