### ISSUE TITLE
Cosmos not installing -- Im still waiting for a solution

### ISSUE THREAD

**Issue by Seifthegamer** [CosmosOS/Cosmos#3041]
**Describe the problem**
The installation wont install for some reason.

**Steps of installation up to now**
Run install-VS2022.bat
Install Cosmos

**Expected behavior**
1. Run install-VS2022.bat
2. Install Cosmos
3. Use it and create an operating system

**Logs**

========================================
    Build Log
========================================

========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe" "E:\CosmosOS\Cosmos\Build.sln" /nologo /maxcpucount /m /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False

  Determining projects to restore...
C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(169,5): error : Found invalid data while decoding. [E:\CosmosOS\Cosmos\Build.sln]

========================================
    Error
========================================

The process failed to execute!
Error: 
C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(169,5): error : Found invalid data while decoding. [E:\CosmosOS\Cosmos\Build.sln]

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
 Devkit
 - Are you running installer as administrator?
 Yes
 - Visual Studio Version if applicable
 2022

**Additional context**
I tried Reinstalling both visual studio and cosmos multiple times. When i tried installing the userkit, it installed succesfully But I need the devkit

**Comment by Seifthegamer** [comment]
There is still no solution
If someone has a solution pls post it here

**Comment by 9xbt** [comment]
> I will close this issue and create a new one because im still not getting any solutions.

thats stupid

**Comment by Coder-660** [comment]
> > I will close this issue and create a new one because im still not getting any solutions.
> 
> thats stupid

your stupid
