### ISSUE TITLE
I can't build my OS into an ISO

### ISSUE THREAD

**Issue by DomTheNoob** [CosmosOS/Cosmos#3044]
I can't build my OS into an ISO, i need to share it to someone

**Comment by 9xbt** [comment]
You ARE bring able to build it to an ISO. Cosmos just shows an error because it's fucking cosmos but if you go to the bin folder, where the dll usually is the iso is there. Also why does the iso option still fucking esist it's useless I can just dotnet build and get the iso no problem without that option

**Comment by SanskarSontakke** [comment]
The COSMOS ISO option in Launch Profile is use less.
Instead you should set it to VMWare and check if it works normal.
Then you do the following steps :
    1.Solution explorer >> Right click on your project >> Properties.
    2.Scroll a little bit down and find the Debug and VMWare section.
    3.Disable the remote debugging in Debut section.
    4. Disable the BDG debugger in VMWare section.
 
Then you can find your ISO in **(yourProject)>>bin>>Debug>>net6.0.**
You need to look for the file as there is a mess of files there but the file usually has the name of your project.
You need to disable the debugger so you can avoid the "Waiting for debugger screen".
if you don't find it in Debug folder. Then
    1.Go to configuration manager.
    2.Set configuration to Debug.
    3.Set platform to Any CPU.

**Comment by tails2012timnew** [comment]
1. Go into your user profile folder (C:/Users/<Your user name>) then go to the source/repos/(yourProjectName)/bin/Debug/net6.0 your iso file should be there
