### ISSUE TITLE
Cosmos Wont Install

### ISSUE THREAD

**Issue by Seifthegamer** [CosmosOS/Cosmos#3045]
**Describe the problem**
It wont install

**Steps of installation up to now**
Run the .bat File as Administrator
Check "Install Visual studio Extensions" box
Start install 
Now i get an erros
**Expected behavior**
Start installing Cosmos

**Logs**

"C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe" "E:\CosmosOS\Cosmos\Build.sln" /nologo /maxcpucount /m /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False

Determining projects to restore...
C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(169,5): error : Found invalid data while decoding. [E:\CosmosOS\Cosmos\Build.sln]

========================================
Error
The process failed to execute!
Error:
C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(169,5): error : Found invalid data while decoding. [E:\CosmosOS\Cosmos\Build.sln]`

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
 Devkit
 - Are you running installer as administrator?
 Yes
 - Visual Studio Version if applicable
 Visual Studio 2022 17.10.4

**Additional context**
I tried Reinstalling both visual studio and cosmos multiple times. When i tried installing the userkit, it installed succesfully But I need the devkit. I also made an issue but i got no comments

**Comment by 9xbt** [comment]
can you fucking be patient and wait for somebody to solve your issue instead of closing it and creating another one jesus christ

**Comment by 9xbt** [comment]
have you tried recloning the repo

**Comment by Seifthegamer** [comment]
Yes

**Comment by 9xbt** [comment]
Try putting cosmos on the c drive

**Comment by 9xbt** [comment]
Maybe that'll help

**Comment by Seifthegamer** [comment]
> Try putting cosmos on the c drive
> ###

Still same thing

**Comment by Seifthegamer** [comment]
I will close this issue as I finally installed cosmos

I realized the name of my user had a space in it. The best way to install it was to create a new user without a space
