### ISSUE TITLE
OS crashing after 1-2 minutes because ram usage going up

### ISSUE THREAD

**Issue by Schaapie-D2** [CosmosOS/Cosmos#3047]
#### Area of Cosmos - What area of Cosmos are we dealing with?
GUI or Memory

#### Expected Behaviour - What do you think that should happen?
OS should not crash and work fine.

#### Actual Behaviour - What unexpectedly happens?
OS crashed after about 1-2 minutes due to RAM usage going up.

#### Reproduction - How did you get this error to appear?
by using the GUI system, I think. Kernel code: `using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;
using System.Drawing;
using Cosmos.System;
using HontelOS.GUI;
using HontelOS.System;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using Cosmos.System.FileSystem;
using Cosmos.System.FileSystem.VFS;
using IL2CPU.API.Attribs;
using Cosmos.Core;
using Cosmos.System.Graphics.Fonts;
using HontelOS.GUI.Elements;
using Cosmos.Core.Memory;
using HontelOS.Resources;
using Cosmos.HAL;

namespace HontelOS
{
    public class Kernel : Sys.Kernel
    {
        public static Canvas canvas;
        Dock dock;
        TopBar topBar;
        CosmosVFS fileSystem;
        PasswordWindow passwordWindow;

        public static int screenWidth = 1920;
        public static int screenHeight = 1080;

        public Bitmap logo = new Bitmap(ResourceManager.Image__Hontel_LogoRaw, ColorOrder.RGB);
        public Bitmap BG1 = new Bitmap(ResourceManager.Image__Background_1Raw, ColorOrder.RGB);

        public static List<GUIElement> guiElements = new List<GUIElement>();

        public static bool appListVisable;
        static bool mouseClickNotice;

        //LockScreen
        static bool isUnlocked;

        protected override void BeforeRun()
        {
            canvas = FullScreenCanvas.GetFullScreenCanvas(new Mode(1920, 1080, ColorDepth.ColorDepth32));

            fileSystem = new CosmosVFS();
            VFSManager.RegisterVFS(fileSystem);

            // Boot progress image
            canvas.DrawImage(logo, screenWidth / 2 - (int)logo.Width / 5, screenHeight / 2 - (int)logo.Height / 5, (int)logo.Width / (int)2.5f, (int)logo.Height / (int)2.5f);
            canvas.Display();

            MouseManager.ScreenWidth = 1920;
            MouseManager.ScreenHeight = 1080;
            MouseManager.X = (uint)screenWidth / 2;
            MouseManager.Y = (uint)screenHeight / 2;

            dock = new Dock();
            topBar = new TopBar();

            passwordWindow = new PasswordWindow();

            appListVisable = false;
            isUnlocked = true;
        }

        protected override void Run()
        {
            UpdateSystem();

            canvas.Clear();
            // Drawing GUI
            canvas.DrawImage(BG1, 0, 0);
            if (isUnlocked)
            {
                DrawDesktop();

                if (appListVisable)
                    DrawAppList();

                // Top Drawing GUI
                topBar.Draw();
                dock.Draw();
            }
            else
            {
                LockScreen();
            }

            foreach (GUIElement gUIElement in guiElements)
                gUIElement.Draw();

            DrawCursor(Cursor.defaultCursor, MouseManager.X, MouseManager.Y);

#if DEBUG
            DrawDebugInfo();
#endif

            canvas.Display();
            Heap.Collect();
        }

        #region Drawing
        void DrawDesktop()
        {
            // TODO
        }

        void LockScreen()
        {
            passwordWindow.Draw();
        }

        void DrawAppList()
        {
            canvas.DrawFilledRectangle(new Pen(Color.FromArgb(128, 194, 194, 194)), 0, 0, screenWidth, screenHeight);
        }

        void DrawCursor(int[] cursor, uint x, uint y)
        {
            for (uint h = 0; h < cursor[3]; h++)
            {
                for (uint w = 0; w < cursor[2]; w++)
                {
                    int pixelX = (int)(w + x + cursor[0]);
                    int pixelY = (int)(h + y + cursor[1]);

                    if (pixelX >= 0 && pixelX < screenWidth && pixelY >= 0 && pixelY < screenHeight)
                    {
                        if (cursor[h * cursor[2] + w + 4] == 1)
                        {
                            canvas.DrawPoint(new Pen(Color.Black), pixelX, pixelY);
                        }
                        else if (cursor[h * cursor[2] + w + 4] == 2)
                        {
                            canvas.DrawPoint(new Pen(Color.White), pixelX, pixelY);
                        }
                    }
                }
            }
        }
        #endregion

        #region System
        void UpdateSystem()
        {
            // Update top GUI
            if (isUnlocked)
            {
                dock.Update();
                topBar.Update();
            }

            if (MouseManager.MouseState == MouseState.None)
                mouseClickNotice = false;
        }

        public static void Reboot()
        {
            Sys.Power.Reboot();
        }
        public static void Shutdown()
        {
            Sys.Power.Shutdown();
        }
        #endregion

        #region Input
        public static bool MouseInArea(int x1, int y1, int x2, int y2)
        {
            int MX = (int)MouseManager.X;
            int MY = (int)MouseManager.Y;
            return (MX >= x1 && MX <= x2 && MY >= y1 && MY <= y2);
        }

        public static bool MouseClick()
        {
            if (MouseManager.MouseState == MouseState.Left && !mouseClickNotice)
            {
                mouseClickNotice = true;
                return true;
            }
            return false;
        }
        #endregion

        #region DEBUG
#if DEBUG
        void DrawDebugInfo()
        {
            canvas.DrawString("RAM usage: " + GCImplementation.GetUsedRAM().ToString(), PCScreenFont.Default, new Pen(Color.Blue), 0, 0);
        }
#endif
        #endregion
    }
}
`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit. Latest version

**Comment by SzymekkYT** [comment]
Hi! First of all, the userkit is **very** outdated, so try downloading the devkit. (just download the code from github as a zip, nothing difficult) And another thing that probably doesn't affect memory problems, but there is no need to clear the canvas when you draw the wallpaper. Clearing the canvas just kills your fps

**Comment by Schaapie-D2** [comment]
ohhhh. thanks. I will download it and see if it helps!

**Comment by Schaapie-D2** [comment]
nope. maybe it's in a other part of the code?
<img width="281" alt="image" src="https://github.com/user-attachments/assets/accddac0-a3d0-4e74-a497-efdeaa496ef7">

**Comment by Schaapie-D2** [comment]
when i remove the dock.Draw(); and topBar.Draw(); it doesn't do that.
Dock.cs: 
`using Cosmos.Core;
using Cosmos.Core.Memory;
using Cosmos.HAL;
using Cosmos.System;
using Cosmos.System.Graphics;
using HontelOS.Resources;
using IL2CPU.API.Attribs;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HontelOS.System
{
    public class Dock
    {

        Canvas c = Kernel.canvas;

        public int dockWidth;
        public int items = 1;

        Bitmap logo = new Bitmap(ResourceManager.Image__Hontel_LogoRaw, ColorOrder.RGB);
        Bitmap appList = new Bitmap(ResourceManager.Image__App_ListRaw, ColorOrder.RGB);

        public void Draw()
        {
            int posX = Kernel.screenWidth / 2 - dockWidth / 2;
            int posY = Kernel.screenHeight - 84;
            int sizX = dockWidth;
            int sizY = 74;

            c.DrawFilledRectangle(new Pen(Color.FromArgb(64, 64, 64)), posX - 2, posY - 2, sizX + 4, sizY + 4);
            c.DrawFilledRectangle(new Pen(Color.FromArgb(194, 194, 194)), posX, posY, sizX, sizY);

            c.DrawImage(appList, posX + 5, posY + 5, 64, 64);

            //for (int i = 0; i < kernel.Processes.Count; i++)
            //{
            //    canvas.DrawImage(kernel.Processes[i].icon, posX + 79 + i * 64, posY + 5, 64, 64);
            //}
        }

        public void Update()
        {
            int posX = Kernel.screenWidth / 2 - dockWidth / 2;
            int posY = Kernel.screenHeight - 84;
            if (Kernel.MouseInArea(posX + 5, posY + 5, posX + 69, posY + 69) && Kernel.MouseClick())
                Kernel.appListVisable = !Kernel.appListVisable;
            //items = kernel.Processes.Count + 1;
            dockWidth = 5 + items * 69;
        }
    }
}
`
TopBar.cs:
`using Cosmos.System.Graphics;
using System;
using System.Drawing;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using IL2CPU.API.Attribs;
using HontelOS.GUI.Elements;
using Cosmos.System;
using HontelOS.Resources;

namespace HontelOS.System
{
    internal class TopBar
    {

        Canvas c = Kernel.canvas;

        Bitmap logo = new Bitmap(ResourceManager.Image__Hontel_LogoRaw); 

        public void Draw()
        {
            c.DrawFilledRectangle(new Pen(Color.FromArgb(128, 194, 194, 194)), 0, 0, Kernel.screenWidth, 32);
            c.DrawImage(logo, 4, 4, 12, 24);
        }

        public void Update()
        {
            if (Kernel.MouseInArea(4, 4, 32, 32) && Kernel.MouseClick())
            {
                string[] _items = { "Restart", "Shutdown" };
                Action<int>[] _actions =
                {
                    index => Kernel.Reboot(),
                    index => Kernel.Shutdown()
                };

                ContextMenu menu = new ContextMenu(_items, _actions, (int)MouseManager.X, (int)MouseManager.Y);
                Kernel.guiElements.Add(menu);
            }
        }
    }
}
`

**Comment by SzymekkYT** [comment]
hmm maybe try deleting everything in both updates? 
also ContextMenu menu = new ContextMenu(_items, _actions, (int)MouseManager.X, (int)MouseManager.Y);
            Kernel.guiElements.Add(menu);
        } is just spamming new context menu every frame, so thats why your ram is filling up

**Comment by Schaapie-D2** [comment]
Hmm.. that won't work because the issue is with both draw methods. and TopBar won't spam new instances.
Maybe it is the fact that it uses the draw methods in canvas too many times?

**Comment by Schaapie-D2** [comment]
aaahhh... I see what the problem is! it is:
c.DrawImage(logo, 4, 4, 12, 24); in TopBar.cs. and:
c.DrawImage(appList, posX + 5, posY + 5, 64, 64); in Dock.cs.

Maybe the bmp files are so big that the memory can't store them properly?

**Comment by Schaapie-D2** [comment]
Fixed it!
finally figured out how to install the dev kit!
now it works!

**Comment by SzymekkYT** [comment]
nice!
