### ISSUE TITLE
Problem while building COSMOS OS

### ISSUE THREAD

**Issue by gamma63** [CosmosOS/Cosmos#3048]
Have you checked Github Issues for similar errors?
#3046 

**Exception**
IL2CPU : error : Exception: System.Exception: Native code encountered, plug required. Check build output for more information.

**Output Logs**
https://gist.github.com/gamma63/434cc9645a2de32240780d205f21db66

**How To Reproduce**
**Nothing** (if by kernel you mean COSMOS distribution also **nothing**, just ```git clone https://github.com/Vardan2009/radiant.git```)

**Screenshots**
![image](https://github.com/user-attachments/assets/2ee2fc93-5772-4c72-83d3-6daced7b6306)
![image](https://github.com/user-attachments/assets/c2cb945e-7b2d-4c63-9ce7-8def09123f94)

**Context**
 [ ] Both Cosmos VS Extensions are installed (I am using linux)
 [ ] In the NuGet Package Manager "Include prerelease" is selected
 [ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'  (I am using linux)
 [x] The Cosmos NuGet packages are installed
 [x] Other projects are compiling

**Comment by zarlo** [comment]
you need to use the cosmos tcp client not the .net one

**Comment by gamma63** [comment]
Okay, I will try
