### ISSUE TITLE
File system problem

### ISSUE THREAD

**Issue by Tosic12** [CosmosOS/Cosmos#305]
Hello, I am using the code from the FAT FileSystem tutorial on the github page (https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem), and I am getting Build Canceled and the following on the output:

1>------ Build started: Project: testBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\testBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:D:\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:D:\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:D:\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\test.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "D:\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\testBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:D:\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:D:\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:D:\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" "References:C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\test.dll" 
1>	Working directory = 'C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Plug found: 'System.RuntimeType'
1>	Plug found: 'System.OutOfMemoryException'
1>	Plug found: 'System.Double'
1>	Plug found: 'System.Delegate'
1>	Plug found: 'System.Array'
1>	Plug found: 'System.Buffer'
1>	Plug found: 'System.Enum'
1>	Plug found: 'System.EventHandler'
1>	Plug found: 'System.Exception'
1>	Plug found: 'System.MulticastDelegate'
1>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>	Plug found: 'System.Math'
1>	Plug found: 'System.String'
1>	Plug found: 'System.Diagnostics.Debugger'
1>	Plug found: 'System.Byte'
1>	Plug found: 'System.Environment'
1>	Plug found: 'System.GC'
1>	Plug found: 'System.Int16'
1>	Plug found: 'System.Int32'
1>	Plug found: 'System.Int64'
1>	Plug found: 'System.IntPtr'
1>	Plug found: 'System.Number'
1>	Plug found: 'System.Object'
1>	Plug found: 'System.Single'
1>	Plug found: 'System.SR'
1>	Plug found: 'System.UInt16'
1>	Plug found: 'System.UInt32'
1>	Plug found: 'System.UInt64'
1>	Plug found: 'System.Threading.Interlocked'
1>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>	Plug found: 'System.Resources.ResourceManager'
1>	Plug found: 'System.Net.IPAddress'
1>	Plug found: 'System.Net.SocketAddress'
1>	Plug found: 'System.Globalization.NumberFormatInfo'
1>	Plug found: 'System.Drawing.Color'
1>	Plug found: 'System.Drawing.SR'
1>	Plug found: 'System.Security.CodeAccessSecurityEngine'
1>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>	Plug found: 'System.RuntimeTypeHandle'
1>	Plug found: 'System.SByte'
1>	Plug found: 'System.UIntPtr'
1>	Plug found: 'System.Security.Cryptography.Utils'
1>	Plug found: 'System.Globalization.CultureInfo'
1>	Plug found: 'Microsoft.Win32.RegistryKey'
1>	Plug found: 'Cosmos.Core.CPU'
1>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>	Plug found: 'Cosmos.Core.IOPortBase'
1>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>	Plug found: 'System.Char'
1>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>	Plug found: 'System.Random'
1>	Plug found: 'System.Console'
1>	Plug found: 'System.Type'
1>	Plug found: 'System.Threading.Monitor'
1>	Plug found: 'System.Text.DecoderFallback'
1>	Plug found: 'System.Text.EncoderFallback'
1>	Plug found: 'System.Text.ASCIIEncoding'
1>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Int32  System.Threading.Thread.get_ManagedThreadId().
1>	 Called from :
1>	System.IO.Iterator`1[System.String]::Void .ctor()
1>	System.IO.FileSystemEnumerableIterator`1[System.String]::Void .ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1[System.String], Boolean)
1>	System.IO.FileSystemEnumerableFactory::System.Collections.Generic.IEnumerable`1[System.String] CreateFileNameIterator(System.String, System.String, System.String, Boolean, Boolean, System.IO.SearchOption, Boolean)
1>	System.IO.Directory::System.String[] InternalGetFileDirectoryNames(System.String, System.String, System.String, Boolean, Boolean, System.IO.SearchOption, Boolean)
1>	System.IO.Directory::System.String[] InternalGetFiles(System.String, System.String, System.IO.SearchOption)
1>	System.IO.Directory::System.String[] GetFiles(System.String)
1>	Display.DisplayDriver::System.String[] GetFsFadr(System.String)
1>	test.Kernel::Void Run()
1>	Cosmos.System.Kernel::Void Run()
1>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 525
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	D:\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	D:\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	D:\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\test.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	D:\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Korisnik\documents\visual studio 2015\Projects\test\test\bin\Debug\Hardware.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.6891577
1>Done building project "testBoot.Cosmos" -- FAILED.
1>
Build has been canceled.

**Comment by Klako** [comment]
The page says it's under construction http://puu.sh/m582w/06adad0f09.png

**Comment by mterwoord** [comment]
Are you on devkit?
