### ISSUE TITLE
Workloads

### ISSUE THREAD

**Issue by Kakao-Team** [CosmosOS/Cosmos#3056]
**Describe the problem**
I installed all the necessary libraries for the dev kit but the installation failed no matter what I did

**Logs**

========================================
    Build Log
========================================

========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads was not found. Install install Visual Studio Extension development, 

========================================
    Error
========================================

Visual Studio Workloads not found.

**Setup (please complete the following information):**
 - Cosmos Version (Userkit/Devkit)
 - Are you running installer as administrator?
 - Visual Studio Version if applicable

**Additional context**
On other systems everything installed fine before, I also have user kit installed

**Comment by zarlo** [comment]
install Visual Studio Extension development work load

**Comment by Kakao-Team** [comment]
i have .net 6.0 and other

**Comment by Kakao-Team** [comment]
I wrote that I have everything necessary installed, but it all doesn't work at all, although it used to work, but most likely the reason is that .net 6.0 sdk is already outdated and is not supported by the studio, and installing it through the program does not work.

**Comment by zarlo** [comment]
the install says you dont have "Visual Studio Extension development work load" installed

**Comment by PythonProjects09** [comment]
Download Visual Studio C++ 2010 Resource Pack :
https://www.microsoft.com/en-us/download/details.aspx?id=26999

I hope your problem is solved :-)

**Comment by MishaProductions** [comment]
Install Visual Studio Extension development in visual studio installer. If you have multiple visual studio installs, uninstall one of them.
