### ISSUE TITLE
Can't create more strings

### ISSUE THREAD

**Issue by SanskarSontakke** [CosmosOS/Cosmos#3057]
Have you checked Github Issues for similar errors?
yes
**Exception**
CS8103

**Visual Studio Output Logs**
Error (active)	CS8103	Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

**How To Reproduce**
try to create a lot big strings

**Screenshots**
![image_2024-08-01_074716425](https://github.com/user-attachments/assets/2f2655be-77fb-4613-a31b-b79fe3f1dccf)

I was just trying to add more background images.
I was using base 64 strings for this purpose.
I think so there is a way to edit the .csproj file and solve this issue but I don't know how ?

Using Devkit 2022

**Comment by zarlo** [comment]
use embedded resources for this it will save space and be faster

**Comment by SanskarSontakke** [comment]
How can I do that? 
Should I use ManifestResourceStream ? 
I saw a example of it here : 
but it says resource not found even though I have entered the correct path.
![image_2024-08-01_102115016](https://github.com/user-attachments/assets/e89673cb-54b3-4ff7-9dc2-ff1d89ce96f5)

**Comment by zarlo** [comment]
it might be the space in the name

**Comment by SanskarSontakke** [comment]
Can you please show me an example of it.
I am new to coding.

**Comment by SzymekkYT** [comment]
if you are new, its not a good idea to create an os even in cosmos. Its slower to build so its harder to debug, there is no exception debug, and ofc the big scary plug not found. But anyway just read the documentation 😉
https://cosmosos.github.io/articles/Kernel/ManifestResouceStream.html

**Comment by SanskarSontakke** [comment]
Thanks it helped a lot and my issue is resolved.
The image appeared successfully.
