### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by SanskarSontakke** [CosmosOS/Cosmos#3058]
#### Area of Cosmos - Devkit 2022
How to add custom fonts to my OS ?

**Comment by Gabolate** [comment]
For Canvas use PSF (PCScreenFont), on console i think VGA Fonts can work but i've never used them before

**Comment by SanskarSontakke** [comment]
I current use PCScreenFont.Default but how do I add a new font like OpenSans from a .tff file

**Comment by Schaapie-D2** [comment]
maybe this can help: https://github.com/GoldenretriverYT/CosmosTTF
