### ISSUE TITLE
Unable to start program. The debbuger is not properly installed.

### ISSUE THREAD

**Issue by Schaapie-D2** [CosmosOS/Cosmos#3063]
**Have you checked Github Issues for similar errors?**
Yes

**Exception**
<img width="311" alt="image" src="https://github.com/user-attachments/assets/e5151734-160e-481e-81fb-16b3d5dca17f">

**Visual Studio Output Logs**
Nothing

**How To Reproduce**
Building the project (VMWare)

**When the error occurred**
All the files that were removed from the project came back.

**Screenshots**
<img width="311" alt="image" src="https://github.com/user-attachments/assets/dfbb3cee-0aff-4339-9fbb-c31858290a63">

**Context**
Before posting please confirm that the following are in order
[-] Both Cosmos VS Extensions are installed
[-] In the NuGet Package Manager "Include prerelease" is selected
[-] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[-] The Cosmos NuGet packages are installed

**Comment by SzymekkYT** [comment]
Do you have vmware player or workstation pro?
I think that cosmos uses player as default, you can change it 
here
![image](https://github.com/user-attachments/assets/d823fdb8-fcbc-4598-b4d2-983a09e97e3b)
if it won't work, just build it as iso
![image](https://github.com/user-attachments/assets/f6cdee49-742d-46d3-923f-c4a83c1caaf5)
then you will also get 2 errors but ignore them.
You can find your iso here: `YourOS\bin\Debug\net6.0`

**Comment by Schaapie-D2** [comment]
i have player but when i set it. it still gives that error

**Comment by SzymekkYT** [comment]
Then just build it as ISO Image, when you want to change something just build again and restart your OS
