### ISSUE TITLE
Project creation error...

### ISSUE THREAD

**Issue by LeonGamerPS1** [CosmosOS/Cosmos#3064]
Have you checked Github Issues for similar errors?
The project file cannot be opened. This version of the .NET SDK (8.0.303) requires at least version 17.8.3 of MSBuild. The currently available version of MSBuild is 16.11.2.50704. Change the version of the .NET SDK specified in "global.json" to a higher version that is compatible with the current version of msbuild!
**Exception**
Post the exception returned by Visual Studio

**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build
none

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
...?

**Screenshots**
![image](https://github.com/user-attachments/assets/5ccf4c69-3394-4163-873e-08602189da40)

**Context**
Before posting please confirm that the following are in order
[X] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[x ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
accurs on cosmos project creation

**Comment by DuperNO-Alt** [comment]
read what it says, ms-build is outdated

**Comment by LeonGamerPS1** [comment]
yeah what actual VERSION tho

Am Sa., 10. Aug. 2024 um 12:53 Uhr schrieb Duper NO! <
***@***.***>:

**Comment by MishaProductions** [comment]
Try updating visual studio and/or .NET. closing as this isn't a cosmos issue.

**Comment by LeonGamerPS1** [comment]
womp womp, kys
