### ISSUE TITLE
System.IO.FileLoadException while trying to execiute UNIX 9.0

### ISSUE THREAD

**Issue by simone2014june** [CosmosOS/Cosmos#3070]
Have you checked Github Issues for similar errors?
No
**Exception**
Post the exception returned by Visual Studio
System.IO.FileLoadException: Could not load file or assembly 'UNIX 9.0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build
1>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'UNIX 9.0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
I Dont Know

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] In the NuGet Package Manager "Include prerelease" is selected
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[ ] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by GoldenretriverYT** [comment]
babe wake up "unix 9.0" dropped

**Comment by SzymekkYT** [comment]
there is no help for "I Dont Know"
