### ISSUE TITLE
Exception: System.Exception: in IL2CPU

### ISSUE THREAD

**Issue by UnsyncedMaster** [CosmosOS/Cosmos#3073]
Have you checked Github Issues for similar errors?
yes but nothing as similar

**Exception**
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		Exception: System.Exception:	ExterOS	C:\Users\super\OneDrive\Desktop\ExterOS-vfs-implementation\ExterOS\IL2CPU	1	

**Visual Studio Output Logs**
Build started at 4:31 PM...
1>------ Build started: Project: ExterOS, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>ExterOS -> C:\Users\super\OneDrive\Desktop\ExterOS-vfs-implementation\ExterOS\bin\Debug\net6.0\ExterOS.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\super\OneDrive\Desktop\ExterOS-vfs-implementation\ExterOS\bin\Debug\net6.0\ExterOS.dll
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>Message : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.Diagnostics.Debugger.CustomNotification(System.Diagnostics.ICustomDebuggerNotification)(Plug Signature: System_Void__System_Diagnostics_Debugger_CustomNotification_System_Diagnostics_ICustomDebuggerNotification_ ).
1>  Static: True
1>  Assembly: System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1>  Called from:
1>System.Diagnostics.Debugger::Void NotifyOfCrossThreadDependencySlow()
1>System.Diagnostics.Debugger::Void NotifyOfCrossThreadDependency()
1>System.Threading.Tasks.Task::Boolean InternalWaitCore(Int32, System.Threading.CancellationToken)
1>System.Threading.Tasks.Task::Boolean InternalWait(Int32, System.Threading.CancellationToken)
1>System.Threading.Tasks.Task`1[System.Boolean]::Boolean GetResultCore(Boolean)
1>System.Threading.Tasks.Task`1[System.Boolean]::Boolean get_Result()
1>Programs.Programs::Void WriteProg(System.String, System.String)
1>ExterOS.Kernel::Void ShowWrite(System.String[])
1>ExterOS.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 625
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 816
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 276
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 223
1>IL2CPU task took 00:00:02.0730055
1>Done building project "ExterOS.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 4:31 PM and took 02.690 seconds ==========

**How To Reproduce**
Added VFS, and File Tools For Writing And Listing Files

**Screenshots**
![image](https://github.com/user-attachments/assets/4c043853-6c0a-48a2-87e7-c9c6daeecea5)

(put yes as in to say that i've checked and done it all)
**Context**
Before posting please confirm that the following are in order Yes
[ ] Both Cosmos VS Extensions are installed Yes
[ ] In the NuGet Package Manager "Include prerelease" is selected Yes
[ ] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages' Yes
[ ] The Cosmos NuGet packages are installed Yes

Add any other context about the problem which might be helpful.

**Comment by Schaapie-D2** [comment]
This usually means that there is something wrong with your code. Can I see Run() in your kernel?

**Comment by zarlo** [comment]
some thing is calling
> System.Void System.Diagnostics.Debugger.CustomNotification(System.Diagnostics.ICustomDebuggerNotification)

that is not supported right now

**Comment by UnsyncedMaster** [comment]
> This usually means that there is something wrong with your code. Can I see Run() in your kernel?

yes here is my Run()

        protected override void Run()
        {
            while (isRunning)
            {
                Console.Write("ExterOS>: ");
                var input = Console.ReadLine().Trim().ToLower();
                var commandArgs = input.Split(' ');

                switch (commandArgs[0])
                {
                    case "help":
                        ShowHelp();
                    break;
                    case "clear":
                        Console.Clear();
                    break;
                    case "exit":
                        ExitOS();
                    break;
                    case "time":
                        ShowTime();
                    break;
                    case "date":
                        ShowDate();
                    break;
                    case "echo":
                        Echo(commandArgs);
                    break;
                    case "reboot":
                        Sys.Power.Reboot();
                    break;
                    case "titties": // this is a joke command but is a real thing
                        ShowTitties(commandArgs);
                    break;
                    case "wr":
                        ShowWrite(commandArgs);
                    break;
                    case "ls":
                        ShowList(commandArgs);
                    break;
                    case "rd":
                        ShowRead(commandArgs);
                    break;
                    case "show directory":
                        ShowDir();
                    break;
                    default:
                        Console.WriteLine($"Unknown Command: {commandArgs[0]}. Type 'help' For A List Of Commands.");
                    break;
                }
            }
        }

**Comment by UnsyncedMaster** [comment]
> some thing is calling
> 
> > System.Void System.Diagnostics.Debugger.CustomNotification(System.Diagnostics.ICustomDebuggerNotification)
> 
> that is not supported right now

Looked Over Everything And Haven't Found Anything That Call's That

**Comment by Schaapie-D2** [comment]
I think the logs say that there is something in ShowWrite() that is calling that unsupported function. Can we see ShowWrite()?

**Comment by UnsyncedMaster** [comment]
okay, here is WriteProg()

        public void WriteProg(string File, string Input)
        {
            var FileExists = vFSTools.FileExistanceCheck(File).Result;
            if (!FileExists)
            {
                System.Console.WriteLine("This File Does Not Exist. Do You Want To Create It Now?\n\r[Y] [N]");
                ConsoleKeyInfo ConsoleKeyInfo = System.Console.ReadKey(true);
                if (ConsoleKeyInfo.Key == ConsoleKey.Y)
                {
                    vFSTools.CreateFile(File);
                    vFSTools.Write(File, Input);
                }
            }
        }

**Comment by Schaapie-D2** [comment]
I think something in vFSTools is calling a function that is not supported yet.

**Comment by UnsyncedMaster** [comment]
well the source is up on my github under the vfs implementation branch, i would appreciate it alot if you'd check it out

**Comment by Schaapie-D2** [comment]
I looked through the code. And i think that using Task causes the issue, maybe you can try to just use void instead of Task?

**Comment by UnsyncedMaster** [comment]
i will try right now

**Comment by UnsyncedMaster** [comment]
okay i tried it! it kinda fixed it, it boots now so that's good, now i'm on to the rest! thanks for the help.

Een Prettige Dag Verder! :)

**Comment by Schaapie-D2** [comment]
U ook! ;)
