### ISSUE TITLE
Why do some methods of Canvas not support alpha colors?

### ISSUE THREAD

**Issue by Schaapie-D2** [CosmosOS/Cosmos#3074]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
all canvas methods should draw colors with alpha if the alpha channel is set

#### Actual Behaviour - What unexpectedly happens?
only some do it correctly. (example: DrawFilledCircle)

#### Reproduction - How did you get this error to appear?
use DrawFilledRectangle for example

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest dev kit

#### screenshot
the corners are with DrawFilledCircle and the filling is with DrawFilledRectangle
<img width="391" alt="image" src="https://github.com/user-attachments/assets/70f4a588-7a0d-4844-b9d7-a1732276b284">

**Comment by SzymekkYT** [comment]
Easy. Using DrawFilledRectangle copies pixels "linearly" into the video buffer. If you want to use alpha, you would have to blend each pixel and copy it one at a time, which is terrible. And by terrible i mean 1920x1080 is 1-2 fps. You can make rounded corners by drawing filled spheres or use draw image **alpha** which is slow. The best method is to use my cosmos fork and call Canvas.GetImage(), then you can cache things and make own fast alpha blending. Here is a small example
![image](https://github.com/user-attachments/assets/c3aa0178-9a73-4c35-addf-ca07bae372e4)
Just 2 blended bitmaps (background and window)

**Comment by Schaapie-D2** [comment]
Thank you!
