### ISSUE TITLE
OS reaches an unrecoverable state during DHCP Discover

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [CosmosOS/Cosmos#3075]
#### Area of Cosmos - What area of Cosmos are we dealing with?
DHCP discover?

#### Expected Behaviour - What do you think that should happen?
It should continue running, as normal

#### Actual Behaviour - What unexpectedly happens?
Vmware reports "vcpu-0" error, which means CosmosOS accessed an invalid part of memory. Debug engine reports a NullReferenceException at addr. 0x0138363A.

Core dump:
`EAX = 0x01383601   EBX = 0x0104FFAC   ECX = 0x00000000
EDX = 0x01070000
EDI = 0x10508B8   ESI = 0x00000000
EBP = 0x010508B0   ESP = 0x10508B4   EIP = 0x010508B8`
Call stack:
`at 0x0137C25B
at 0x01373209
at 0x017AC349
at 0x01372121`

#### Reproduction - How did you get this error to appear?
Trying to run a DHCP discover? I modified some of the network settings in the vmx in an attempt to get DHCP to not return 0.0.0.0
I will put my code, map file, and VMX in a github repo, and add a reply once I do.
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Man, not even I know. It's probably the newest user kit? VMWare, VS2022

**Comment by Neil-Ciciglycerin** [comment]
[Neil-Ciciglycerin/GLaDOSOS](https://github.com/Neil-Ciciglycerin/GLaDOSOS)
Repo containing all of my code. The map file was to big, but you should be able to reproduce it by recompiling.

**Comment by Neil-Ciciglycerin** [comment]
NOTE: This happens w./w.o. Cosmos Debugger.

**Comment by Neil-Ciciglycerin** [comment]
I'mma try updating to the newest devkit to see if that does anything.

**Comment by Neil-Ciciglycerin** [comment]
The newest devkit is broken.
`1>IL2CPU : error : Exception: System.Exception: Native code encountered, plug required. Check build output for more information.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.String..ctor(System.ReadOnlySpan`1<System.Char>)(Plug Signature: System_Void__System_String__ctor_System_ReadOnlySpan_1_System_Char__ ).
1>  Static: False
1>  Assembly: System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1>  Called from:
1>System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::System.String ToStringAndClear()
1>Cosmos.System.Kernel::Void Start()`

**Comment by Neil-Ciciglycerin** [comment]
Commit [1f3bb52](https://github.com/CosmosOS/Cosmos/commit/1f3bb528ce0bce0451d23a79763dce29349b0d6f)

**Comment by Neil-Ciciglycerin** [comment]
On the most recent Userkit, it doesn't crash, but just returns 0.0.0.0

**Comment by Neil-Ciciglycerin** [comment]
I tried changing the connection type to NAT and it didn't do nothing, although it was able to recognize eth0 now.

**Comment by Neil-Ciciglycerin** [comment]
bump

**Comment by Neil-Ciciglycerin** [comment]
_**bump**_

**Comment by Neil-Ciciglycerin** [comment]
anyone out there? i've been waiting forever.

**Comment by ADev531** [comment]
Hello! @Neil-Ciciglycerin 
It's maybe too late... after Installing Devkit, You need to install Cosmos.Plugs in Userkit project.
How? : In NuGet Package Manager -> Cosmos Local Feed -> Cosmos.Plugs.
Please see this!

**Comment by Neil-Ciciglycerin** [comment]
I updated the devkit, installed Cosmos.Plugs and it started working.

**Comment by ADev531** [comment]
Good!
Can you close this, please?
