### ISSUE TITLE
How can i add files to the ISO?

### ISSUE THREAD

**Issue by Schaapie-D2** [CosmosOS/Cosmos#3079]
How can i add files to this ISO? So I can do "0:\\file.txt". I thought that the files in the isoFiles folder would get added to the ISO.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
latest dev kit

**Comment by TheVogels** [comment]
The isoFiles folder does get added to the iso, has you tried mounting it to your Operating system? If you can't find those then that isn't right. There is another way to embed files mentioned at [Cosmos Documentation - Manifest Resource Streams](https://cosmosos.github.io/articles/Kernel/ManifestResouceStream.html),  and a documentation to using the file system at [Cosmos Documentation - File System](https://cosmosos.github.io/articles/Kernel/VFS.html).

**Comment by Schaapie-D2** [comment]
oohh.. I see them. so to get the file you do this path?: 0:\boot\file.txt

**Comment by TheVogels** [comment]
No, inside the isoFiles folder is the root, if you had that file inside a folder called boot then it would be there.
The files inside isoFiles are used in the root, isoFiles\file would be 0:\file and isoFiles\Folder\file would be 0:\Folder\file.

**Comment by Schaapie-D2** [comment]
Okay. thank you!
