### ISSUE TITLE
String.Empty and "" are different

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#308]
I have noticed that these two constants that should have the same value (ascii code 0x20 SPACE) are in reality different!

This simple test shows reproduce the issue:
```
if (String.Empty != "")
    Console.WriteLine("Empty different from ''");
```
Printing them as byte values with (byte)"MyString"[0] gives two different values (confirming that they are _numerically_ different) " " is 213 while String.Empty is 83.

**Comment by charlesbetros** [comment]
6ed36d75b6598147ca027b275dac8e39afa4cf71 fixed.
