### ISSUE TITLE
OS wont boot on real hardware

### ISSUE THREAD

**Issue by OxSharp** [CosmosOS/Cosmos#3083]
When i use my usb to boot my OS on my laptop it loads like normal and says loading (OSNAME).bin and then it shows a black screen.

**Comment by Gabolate** [comment]
A few questions:

- Does your computer support BIOS, UEFI or both?
- Did you used graphics or only text mode (console) in your OS?
- In case you used graphics, have you choosed VBECanvas, VGACanvas or SVGAIICanvas?

**Comment by OxSharp** [comment]
My computer supports UEFI, and I’m using dev kit

**Comment by Gabolate** [comment]
But you are booting in legacy mode?

**Comment by OxSharp** [comment]
Yes

**Comment by Gabolate** [comment]
Does it boot on a vm?

**Comment by OxSharp** [comment]
Yes

**Comment by OxSharp** [comment]
Oh btw I did use SVGAIICanvas but I’m just using console rn. Also what graphics work with real hardware?

**Comment by Gabolate** [comment]
only VBECanvas works on real hardware iirc

**Comment by OxSharp** [comment]
So how do I make it work and boot on real hardware?

**Comment by Gabolate** [comment]
Try with cosmos default OS and see if it works, if not then i think we'll need your code, at least the start of it

**Comment by OxSharp** [comment]
I made no changes to the code it’s the default console

**Comment by Gabolate** [comment]
Are you using rufus, ventoy or another tool to burn the ISO?

**Comment by Szymekk44** [comment]
remember that vga doesn't work with uefi (aand vga text mode)

**Comment by OxSharp** [comment]
I’m using Rufus 2.18

**Comment by GBX9570** [comment]
this happens to me too, only boots on real hardware if using the userkit

**Comment by OxSharp** [comment]
Fr?

**Comment by OxSharp** [comment]
But how do I use the vbecanvas?

**Comment by GBX9570** [comment]
> Fr?

yeah, but userkit is very outdated compared to the devkit so its not really a good idea to use it

**Comment by OxSharp** [comment]
I tried it with the user kit and it didn’t boot

**Comment by Gabolate** [comment]
im not sure if there are any differences here, but ig you could try the ISO mode in rufus and if that dosen't work then try DD mode

**Comment by OxSharp** [comment]
Ok I’ll try later I’ll let you know if works

**Comment by sasdallas** [comment]
If you have any other hardware you can try, it might help to rule out whether it's your kernel or the hardware. Even better, (but unlikely), if there's a way to get serial output out of your laptop you could access the debugger potentially (think that's how it works)
