### ISSUE TITLE
Error in VMware audio initalisation

### ISSUE THREAD

**Issue by Stepanchikitsme** [CosmosOS/Cosmos#3084]
#### Expected Behaviour - What do you think that should happen?
When booting OS in VMware (playing startup sound), there should be a startup sound

#### Actual Behaviour - What unexpectedly happens?
I'm getting this exception:
No AC97-compatible device could be found - the reset timeout has expired.

#### Reproduction - How did you get this error to appear?
Boot an OS in VMware and try to play some sound. In VirtualBox it'll work perfect, but VMware...

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Using the last version of Dev kit

**Comment by ascpixi** [comment]
AC97 is not supported in VMWare. AFAIK, VMWare can only emulate an Intel HD Audio controller.

**Comment by Stepanchikitsme** [comment]
> AC97 is not supported in VMWare. AFAIK, VMWare can only emulate an Intel HD Audio controller (which is the default) or a legacy ES1371 sound card.

Is there any community driver for any of them?

**Comment by ascpixi** [comment]
> > AC97 is not supported in VMWare. AFAIK, VMWare can only emulate an Intel HD Audio controller (which is the default) or a legacy ES1371 sound card.
> 
> Is there any community driver for any of them?

Not that I know of, no. I think that VMware has undocumented support for Sound Blaster 16, though, if you modify the VMX file to have `sound.virtualDev` set to `sb16`. I have made a [partially implemented Sound Blaster 16 driver](https://gist.github.com/ascpixi/af4f138bf61a2a3f62c670a34ee1f7ce) for Cosmos a while ago, but it's for an older version of the API, and is quite buggy, so you will probably need to make some major adjustments to it.

**Comment by Stepanchikitsme** [comment]
> > > AC97 is not supported in VMWare. AFAIK, VMWare can only emulate an Intel HD Audio controller (which is the default) or a legacy ES1371 sound card.
> > 
> > 
> > Is there any community driver for any of them?
> 
> Not that I know of, no. I think that VMware has undocumented support for Sound Blaster 16, though, if you modify the VMX file to have `sound.virtualDev` set to `sb16`. I have made a [partially implemented Sound Blaster 16 driver](https://gist.github.com/ascpixi/af4f138bf61a2a3f62c670a34ee1f7ce) for Cosmos a while ago, but it's for an older version of the API, and is quite buggy, so you will probably need to make some major adjustments to it.

I'll take a look. Thank you much!
