### ISSUE TITLE
Why stucked at <waiting for debugger connection> independent in VMware

### ISSUE THREAD

**Issue by lfpu** [CosmosOS/Cosmos#3089]
when i used VS 2022 to debug, the VMware is working, and it can entry the OS successfully.

But when i used VMware Workstation without VS2022 to create new virtual computer it stucked at "Waiting for debugger connection..."

the ISO path is :\bin\Debug\net6.0\xxxx.iso

![image](https://github.com/user-attachments/assets/1c0a4c23-5b74-44f6-bfa2-f8d514140fa3)

![image](https://github.com/user-attachments/assets/441ca4cb-213d-4f07-99bf-e7351180d2f1)

![image](https://github.com/user-attachments/assets/6b7ce85d-be34-40b9-959c-6989a7af22bd)

**Comment by zarlo** [comment]
you need to disable the cosmos debugger in you project then rebuild

**Comment by Schaapie-D2** [comment]
the fix for me was that if Visual Studio showed that it was not started (if the  ⏵ cosmos   button wasn't gone or disabled), I closed VMWare and restarted it.

**Comment by lfpu** [comment]
> you need to disable the cosmos debugger in you project then rebuild

thank  found it.
