### ISSUE TITLE
error while building cosmos

### ISSUE THREAD

**Issue by randomusert** [CosmosOS/Cosmos#3101]
#### Area of Cosmos - What area of Cosmos are we dealing with?
building the dev kit

#### Expected Behaviour - What do you think that should happen?
it should build

#### Actual Behaviour - What unexpectedly happens?
it gives errors about missing .csproj files

#### Reproduction - How did you get this error to appear?
try to follow the build guide in linux manually building each repository

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
tried to use dev kit, but couldn't build it

**Comment by Gabolate** [comment]
Can you send screenshots?

**Comment by randomusert** [comment]
![il2cpp and cosmos](https://github.com/user-attachments/assets/9f34a132-0169-4682-85b9-7325a48361aa)

**Comment by Gabolate** [comment]
could it be a problem related to the directory names? yk, case-sensitive

**Comment by randomusert** [comment]
I did not think about that, but it could Be because 2 out of The 4 were compiled successfully

**Comment by randomusert** [comment]
oh it was the dircetory names.
