### ISSUE TITLE
Mouse X and Y always 0 

### ISSUE THREAD

**Issue by Kazancik** [CosmosOS/Cosmos#3102]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics(Mouse, Visual Basic) 

#### Expected Behaviour - What do you think that should happen?

It displaying the correct place of the mouse
#### Actual Behaviour - What unexpectedly happens?

It always shows 0 as X and Y 
#### Reproduction - How did you get this error to appear?
Running this in VMware or VirtualBox
`Imports System
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Runtime.ConstrainedExecution
Imports System.Text
Imports Cosmos.Core
Imports Cosmos.Core.IOGroup
Imports Cosmos.System
Imports Cosmos.System.FileSystem.CosmosVFS
Imports Cosmos.System.Graphics
Imports Cosmos.System.Graphics.Extensions
Imports Console = System.Console
Imports Point = Cosmos.System.Graphics.Point

Namespace Emulated_Operating_System
    Public Class Kernel
        Inherits Cosmos.System.Kernel
        Dim theCanvas As Canvas

        Public Overrides Sub Start()
            MyBase.Start()
        End Sub

        Protected Overrides Sub BeforeRun()

        End Sub

        Protected Overrides Sub Run()
            Try

                Console.Write("Komutum: ")
                Dim imp = Console.ReadLine()

                If imp.StartsWith("kurgui", StringComparison.InvariantCultureIgnoreCase) Then
                    theCanvas = FullScreenCanvas.GetFullScreenCanvas()
                    theCanvas.Clear(Color.DarkGoldenrod)

                    While True

                        Dim cur = New Point(Int(MouseManager.X), (Int(MouseManager.Y)))
                        theCanvas.DrawRectangle(Color.Beige.ToPen(1), cur.X + 1, cur.Y + 1, cur.X + 50, cur.Y + 50)
                        theCanvas.Display()
                    End While
                End If
            Catch ex As Exception

            End Try

        End Sub
    End Class

End Namespace`
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest User Kit and Visual Studio 2022

**Comment by Kazancik** [comment]
Oh, I guess I didn't read the doc correctly. Do you know how to get the current ScreenWidth and ScreenHeight? (because I belive it sets the best setting for the screen)

**Comment by Gabolate** [comment]
``canvas.Mode.Width`` and ``canvas.Mode.Height`` will give you the screen size, just give it to MouseManager and it should work
