### ISSUE TITLE
I installed it but theres not anything happending and i cant find the c# operating system

### ISSUE THREAD

**Issue by SasoPlayzYT** [CosmosOS/Cosmos#3113]
#### Expected Behaviour - What do you think that should happen?
it should show

#### Actual Behaviour - What unexpectedly happens?
no c# operating system in visual studio

#### Reproduction - How did you get this error to appear?
NO ERROR

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit

![image](https://github.com/user-attachments/assets/92e9165b-6212-4e73-b6ac-eedd9525529b)

**Comment by Gabolate** [comment]
Do you have more than 1 visual studio versions installed?

**Comment by SasoPlayzYT** [comment]
yes

**Comment by SasoPlayzYT** [comment]
i have 3 vs 2017 vs 2019 vs 2022

**Comment by SasoPlayzYT** [comment]
> Do you have more than 1 visual studio versions installed?

do i need to uninstall some?

**Comment by Gabolate** [comment]
Cosmos usually has problems when you have multiple versions, if the installer doesn't ask you where to install i would recommend if possible uninstalling all the versions except for 2022

**Comment by SasoPlayzYT** [comment]
uh ok

**Comment by SasoPlayzYT** [comment]
but it ask me where to install

> Cosmos usually has problems when you have multiple versions, if the installer doesn't ask you where to install i would recommend if possible uninstalling all the versions except for 2022

**Comment by Gabolate** [comment]
> but it ask me where to install

Try using all the options and see if it appears on vs

**Comment by SasoPlayzYT** [comment]
> > but it ask me where to install
> 
> Try using all the options and see if it appears on vs

where?

**Comment by SasoPlayzYT** [comment]
oh ok

**Comment by SasoPlayzYT** [comment]
> > but it ask me where to install
> 
> Try using all the options and see if it appears on vs

it dont work ):

**Comment by SasoPlayzYT** [comment]
> > > but it ask me where to install
> > 
> > 
> > Try using all the options and see if it appears on vs
> 
> it dont work ):

):::::::;;;

**Comment by SasoPlayzYT** [comment]
> > > > but it ask me where to install
> > > 
> > > 
> > > Try using all the options and see if it appears on vs
> > 
> > 
> > it dont work ):
> 
> ):::::::;;;

)::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;

**Comment by SasoPlayzYT** [comment]
> > > > > but it ask me where to install
> > > > 
> > > > 
> > > > Try using all the options and see if it appears on vs
> > > 
> > > 
> > > it dont work ):
> > 
> > 
> > ):::::::;;;
> 
> )::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;

i mostly dont know why?????/:

**Comment by SasoPlayzYT** [comment]
can u help

> > but it ask me where to install
> 
> Try using all the options and see if it appears on vs

it dont work

**Comment by Gabolate** [comment]
uninstalling visual studio versions ig then

**Comment by SasoPlayzYT** [comment]
ok

**Comment by SasoPlayzYT** [comment]
> uninstalling visual studio versions ig then

do i reinstall cosmos too?

**Comment by SasoPlayzYT** [comment]
> uninstalling visual studio versions ig then

IT WORKED YES!!!!!!!!!!!!!!!!!!!!!!!!!!! i can finally make my operating system
