### ISSUE TITLE
X86_ASM

### ISSUE THREAD

**Issue by WyattSteinmann** [CosmosOS/Cosmos#3115]
**Run X86_ASM From A String Example**
Cosmos.System.RunASM("mov eax, 1");

**Complexity of plug**
Can this plug be added without requiring new drivers or a lot of work? No I Don't Think

**Alternatives that I considered**
Are there workarounds for this plug? Just Running X86_ASM I Am Happy But It Makes It WAY More Easy In My Code If Its A String :D And You Can Make It Compile To Bin Under The Hood Then Run That

**Additional context**
I Need To Run X86_ASM Code In My Project So I Can Make A Compiled Lang Or Just A Run Command To Run X86_ASM

**Comment by MishaProductions** [comment]
Documentation for creating plugs can be found at https://cosmosos.github.io/articles/Kernel/Plugs.html

**Comment by WyattSteinmann** [comment]
> Documentation for creating plugs can be found at https://cosmosos.github.io/articles/Kernel/Plugs.html

Can You Give Me More Info? That's Way To Nerdy D:
