### ISSUE TITLE
In VMWare I Gave 8GB Then I Ran Cosmos.Core.CPU.GetAmountOfRAM(); And It Gave Me 4GB

### ISSUE THREAD

**Issue by WyattSteinmann** [CosmosOS/Cosmos#3116]
#### Reproduction - How did you get this error to appear? public static string NeoFetch()
{
uint RAM = Cosmos.Core.CPU.GetAmountOfRAM();
Thread.Sleep(2); // Prevent Deadlock
string CPU = Cosmos.Core.CPU.GetCPUBrandString() + " | " + Cosmos.Core.CPU.GetCPUVendorName();
return "Neofetch:" + "\n\tSystem OS: " + Kernel.Name + " " + Kernel.Version + " " + Kernel.Code + "\n\tSystem RAM: " + RAM + " MB" + "\n\tSystem CPU: " + CPU;
}

**Comment by WyattSteinmann** [comment]
This Maybe May Happen If Its A 32Bit OS If The Case Please Add 64Bit Support

**Comment by Szymekk44** [comment]
Yes, cosmos is only 32 bit.
Its not easy as as "Please Add 64Bit Support". You should learn more about osdev.
Cosmos is open source so everyone can add stuff.
Anywyas you have to options.
1 - Wait for cosmos gen 3
2 - Implement it yourself
by the way wydm "IDK, IDK, IDK"..??

**Comment by MishaProductions** [comment]
Cosmos is 32 bit, and does not support paging, so it can only access up to 4gb of memory. There is an unfinished PR to add x64 support: https://github.com/CosmosOS/Cosmos/pull/2827

**Comment by WyattSteinmann** [comment]
Oh Okay I Will Try To Just Keep It 32Bit Can I Still Run It On 64Bit Processors And How Hard Is It To Actually Add My Self? Sorry For This I Will Try To Be Careful To Submit Better Requests D:

**Comment by WyattSteinmann** [comment]
> Yes, cosmos is only 32 bit. Its not easy as as "Please Add 64Bit Support". You should learn more about osdev. Cosmos is open source so everyone can add stuff. Anywyas you have two options. 1 - Wait for cosmos gen 3 2 - Implement it yourself by the way wydm "IDK, IDK, IDK"..??

The IDK IDK IDK is I Dont Know The Ver Of Cosmos DevKit I Dont Know The Ver Of IL2CPU And I Dont Know The Ver Of X# By The Way Are You Szymekk I Watch Your YT Vids Btw Please Add A English Ver On Your OS Ser I Cant Understand A Word I Use Subtitles But Thats Hard To Understand But Thanks For The Vids And I Will Learn More About OS Dev But I Don't Get ASM At All But I Kinda Need It To Do Anything In OS Dev ):
