### ISSUE TITLE
Cosmos errors to bluescreens

### ISSUE THREAD

**Issue by parabolah** [CosmosOS/Cosmos#312]
Is there a way to handle errors thrown by Cosmos as a bluescreen like function in the OS instead of just writing the error and quitting. Like when an error is thrown, check if it's a Cosmos error and if it is then don't close the OS, but show a bluescreen that provides the error information and wait for a response before closing the OS. Would make debugging a lot easier for me: seeing as at least half the time the error isn't written to the debug console.

**Comment by mterwoord** [comment]
you have full control over exception handling. However CPU exceptions are hadnled by lowlevel functions, over which you dont have too much control.

**Comment by jesus123123** [comment]
You could always use a try catch.

`try {
//your code
}
catch(Exception) { //This catch uses the exception type "Exception". It handles every type.
///if your code errors, do THIS code
}`
