### ISSUE TITLE
RAM Bug

### ISSUE THREAD

**Issue by WyattSteinmann** [CosmosOS/Cosmos#3122]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Cosmos.Core.CPU

#### Expected Behaviour - What do you think that should happen?
Cosmos.Core.CPU.GetAmountOfRAM(); To Return The Amount Of Ram 512mb

#### Actual Behaviour - What unexpectedly happens?
Cosmos.Core.CPU.GetAmountOfRAM(); Returns 254mb

#### Reproduction - How did you get this error to appear?
Ran This In VMWare:
uint RAM = Cosmos.Core.CPU.GetAmountOfRAM();
Thread.Sleep(2); // Prevent Deadlock
string CPU = Cosmos.Core.CPU.GetCPUBrandString() + " | " + Cosmos.Core.CPU.GetCPUVendorName();
Console.WriteLine("System Info:");
Console.WriteLine("\tCPU:  " + CPU);
Console.WriteLine("\tRAM:  " + RAM + " MB");

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? DevKit

Note: I Made A Issue About This With 8GB Of Memory And It Got Closed Due To 32 Bit OS But Now I Am Thinking This Is A Real Bug And Needs To Be Looked At And Yes I Do Actually Have 512Mb In VMWare

**Comment by ADev531** [comment]
1. Cosmos VM gets overrided per each run
Can you create new VM and test it?

**Comment by WyattSteinmann** [comment]
> 1. Cosmos VM gets overrided per each run
>        Can you create new VM and test it?

Ok I Will Try I Had It In The Default Cosmos VM And With The Debuger Disabled

**Comment by WyattSteinmann** [comment]
Now Its 510 Hmmm

**Comment by ADev531** [comment]
It's 1024/1000b problem
Occurs on every os, no way to fix it

**Comment by WyattSteinmann** [comment]
That's Closer But Its 510 Not 512

**Comment by WyattSteinmann** [comment]
Oh Well That's Weard

**Comment by WyattSteinmann** [comment]
*weird

**Comment by WyattSteinmann** [comment]
Mibi Bytes?

**Comment by ADev531** [comment]
Yeah it's because Mibibytes/Megabytes is different
Can you close this now?

**Comment by WyattSteinmann** [comment]
Ya
