### ISSUE TITLE
Console new line error

### ISSUE THREAD

**Issue by MyvarHD** [CosmosOS/Cosmos#313]
The console does make a new line on \n but it prints it to (screen shot)
![image](https://cloud.githubusercontent.com/assets/6468605/12017943/8bfd8218-ad65-11e5-9f40-1816925b2811.png)

**Comment by MyvarHD** [comment]
I will fix this once i finshed implmenting the header code for the zork demo

**Comment by MyvarHD** [comment]
Fixed #314

**Comment by Ray1015** [comment]
`\n` Does That. I Recommend Using Multiple `Console.WriteLine();`

**Comment by MyvarHD** [comment]
Nope it does not do that in windows console or linux terminal

**Comment by MyvarHD** [comment]
Btw i alredy fixed it, just need to merg the pr

**Comment by Ray1015** [comment]
I Know Only On COSMOS.
