### ISSUE TITLE
Methods of filesystem with problems

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#317]
# Methods of filesystem with problems

In the following issue there is a list of the properties / methods implemented for the Filesystem and related classes but that have problems.
### Methods implemented but not respecting the specifications
- [ ] WriteAllText(String path, String text): if 'path' does not exist a new file should be created
- [x] WriteAllBytes(String path, Byte[] data): **null pointer exception is thrown** (fixed by https://github.com/CosmosOS/Cosmos/pull/321)
- [x] WriteAllLines(String path, Byte[] data): **null pointer exception is thrown** (fixed by https://github.com/CosmosOS/Cosmos/pull/321)
- [ ] AppendAllText(String path, String text): if the file already exists 'text' should be appended instead the file content is always overwritten
## Filestream

The constructor (InitializeStream) takes as the argument FileMode but this is not passed to the low level functions so de facto it tries to open always the file if it is not existing too. This seems to be the cause of weird behaviors.

**Comment by fanoI** [comment]
PR https://github.com/CosmosOS/Cosmos/pull/321fixes the worst of these problem: the null pointer exception!

**Comment by quajak** [comment]
Have the problems been fixed?

**Comment by Kiirx** [comment]
Could still be there, I'll maybe one day fix that, but now we use the System.IO.

**Comment by quajak** [comment]
It seems like we no longer implement these methods directly and use the implementations from System.IO

Nevertheless feel free to improve the stability of the filesystem.
