### ISSUE TITLE
Boot Project Properties Window not loading

### ISSUE THREAD

**Issue by BHazel** [CosmosOS/Cosmos#322]
I have installed the User Kit (18/09/2015) onto Visual Studio 2015 Community.  The Cosmos project group appears fine and I can create and build Cosmos projects including ISO images in Debug mode.  However, I am unable to get to the Boot project properties window: when I click on the Properties submenu item an error appears:

_An error occurred trying to load the project properties window.  Close the window and try again.
Cannot evaluate the item metadata "%(FullPath)".  The item metadata "%(FullPath)" cannot be applied to the path "obj\Debug|x86\CosmosOSBoot.exe".  Illegal characters in path.  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets"_

I have tried to manually edit the Boot project file but this results in build errors when running IL2CPU.

**Comment by mterwoord** [comment]
To me, that error sounds like you have special characters in your home folder. Is that the case?

**Comment by BHazel** [comment]
Not that I know of unless spaces or numbers can cause an issue:
_C:\Users\Benedict Hazel\Documents\Visual Studio 2015\Projects\Experiments\HelloCosmos_

**Comment by mterwoord** [comment]
Can you try to place the cosmos kernel somewhere else, just for sake of testing?

**Comment by charlesbetros** [comment]
The issue is the build target path visual studio chose. "obj\Debug|x86\CosmosOSBoot.exe" There is a | in the path and the "pipe" isn't a valid character for paths. Under Build -> Configuration Manager what is the selected "Active Solution Configuration" and "Active Solution Platform"?

**Comment by BHazel** [comment]
Sorry for the delay!

For both Debug and Release under Active Solution Configuration, the Active Solution Platform is Any CPU.  However, the Cosmos Boot project has a platform of x86.  If I try to click on either the platform or configuration cells for the Boot project they clear their contents.

**Comment by cjhannah** [comment]
I have the same issue here. Have you installed a driver kit by any chance?

**Comment by cjhannah** [comment]
To anyone who sees this: I've managed to fix it. You must edit the Cosmos.TARGETS in the Msbuild folder

**Comment by cjhannah** [comment]
If you have a driver kit installed, REMOVE IT and it will work!

**Comment by DjSinae** [comment]
i have the same bug..

how do you uninstall the driver kit?
and why do you have a solution that doesnt work out of the box?

**Comment by lcnvdl** [comment]
I got the same problem too
