### ISSUE TITLE
[Question] Running Cosmos on Raspberry PI

### ISSUE THREAD

**Issue by JustCubed** [CosmosOS/Cosmos#324]
How can I get cosmos to run on the Raspberry Pi? It has a ARMv7 processor.

**Comment by mterwoord** [comment]
It's one of the somewhat longer term plans. First we need basic stuff working first. :)

**Comment by JustCubed** [comment]
Okay!

**Comment by FacePalmDev** [comment]
Hey guys, Any update on this in 2022? I appreciate that you're busy working and maintaining this fantastic project

**Comment by zarlo** [comment]
we still do not have any arm support

**Comment by AsertCreator** [comment]
unfortunately for you, cosmos maybe too deeply connected with x86 hardware and we cant just port it to arm. when cosmos gen 3 will be released, it maybe will support arm, but chances are low.

p.s. if youre looking for embedded device os, try official raspberry pi os or little kernel

**Comment by zarlo** [comment]
arm support will not be coming with gen3 but gen3 will make it easier to add support for arm
