### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by JustCubed** [CosmosOS/Cosmos#325]
![image](https://cloud.githubusercontent.com/assets/16735711/12373710/28fc4e66-bc50-11e5-9203-2c6795d791cb.png)

I get this error when I try to run in VMWare. I'm running VS Community 2015.

**Comment by mterwoord** [comment]
Have you tried manually running vmware once?
Also, are you using VMware player or workstation?

For support, you could also join our gitter chat....

**Comment by JustCubed** [comment]
Nevermind. I figured it out. VMWare had some missing files :P
Sorry for wasting your time D:
