### ISSUE TITLE
GUI toutorial

### ISSUE THREAD

**Issue by masterex1000** [CosmosOS/Cosmos#326]
I was following the tutorial for GUI basics and visual studio keeps giving me the error 

a project with the output type Class library can't be started directly.

I have no idea what is happening.

**Comment by mterwoord** [comment]
Which tutorial are you referring to?
There are some really old tutorials, referring to MS3-4 (which is like 4-5 years old)

**Comment by masterex1000** [comment]
The one that i am talking about is this tutorial.

https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI---The-basics

i son't know if i have an old version of cosmos so i will install that to see if anything is fixed.

**Comment by mterwoord** [comment]
Well, You dont have the right project set as startup project. Please set the .Cosmos project as startup project.

**Comment by masterex1000** [comment]
That did it it now works. thanks so much!

**Comment by mterwoord** [comment]
If this issue is resolved, please close it. Thanks
