### ISSUE TITLE
Runtime error when uninstalling cosmos

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#327]
I am getting the same issue when uninstalling as described in #215 (although it should be fixed?) :

`Runtime Error (at 47:380): An error occurred while unregistering Cosmos from Visual Studio!`

**Comment by ImaBrokeDude** [comment]
I can confirm this as well.

**Comment by mterwoord** [comment]
Any of you guys interested in helping out to fix this?
Also, what versions are you using?

**Comment by a-ctor** [comment]
I am using the `20150918` version (Seems like the latest one). 
Would help, but I don't know where to start...

**Comment by mterwoord** [comment]
Start off by joining gitter. Pretty much all the time someone's awake in there..

Are you familiar with innosetup?

**Comment by a-ctor** [comment]
No idea about innosetup

**Comment by mterwoord** [comment]
We can get you going if you want, start off by joining our gitter channel... :)

**Comment by BHazel** [comment]
I can confirm this is also happening to me as well.  I am using 20150918.

**Comment by charlesbetros** [comment]
This should be fixed already in master.

**Comment by domi1819** [comment]
I had the same message. I successfully removed the user kit by removing the installation folder of Cosmos, as well as running "devenv /setup" with explicit elevated privileges. (I checked the registry, all keys from the setup file were already removed by the uninstaller, so I guess the uninstaller is unable to start devenv as admin?)

**Comment by cristo1985** [comment]
WTF!!! Motherfucker give me the uninstaller!!!

**Comment by cristo1985** [comment]
ehm how many years you can fix this fucking error?!

**Comment by czhower** [comment]
ehm - keep the foul language to yourself or you will be banned.

Cosmos is open source and we have limited resources. Feel free to submit a patch.

**Comment by rayw1** [comment]
If anyone is working with release `20150918`, a quick way to fix this uninstall runtime error is to edit **./setup/events.inc** and replace the procedure **CurUninstallStepChanged** with this:
```
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
    xResultCode: Integer;
begin
    EnableFsRedirection(true);
    ShellExec('runas', ExpandConstant('{code:VSNET2013_PATH|}\devenv.exe'), '/setup', '', SW_HIDE, ewWaitUntilTerminated, xResultCode);
    EnableFsRedirection(false);
end;
```
