### ISSUE TITLE
Error: Exception: System.NotImplementedException: OpCode 'Mul_Ovf_Un' not implemented!

### ISSUE THREAD

**Issue by Codyn6263** [CosmosOS/Cosmos#329]
So im working on a very basic OS just for fun and also to get to know how cosmos works and all, and when i try to build the project i get this in the output window. I have heard something about the list<> causing issues, but i dont believe thats my problem here. Can anyone help?

**Comment by mterwoord** [comment]
Can you post the full code stack please?

**Comment by charlesbetros** [comment]
This should be fixed in the latest devkit.
