### ISSUE TITLE
Creating a GUI the Basics: NewBufferedDisplayDriver(); not found

### ISSUE THREAD

**Issue by DeadPro60** [CosmosOS/Cosmos#333]
I've followed the "Creating GUI the basics" tutorial and i get this error.help?

**Comment by zarlo** [comment]
rename NewBufferedDisplayDriver to DisplayDriver their is an error in the tutorial

**Comment by DeadPro60** [comment]
By the way, what does it mean to create a member display of your kernel class of class displaydriver?

**Comment by jordansrowles** [comment]
In your Kernel class in Kernel.cs, add the this right after your class declaration

```
DisplayDriver display;
```

This makes a DisplayDriver instance that can be called from any method (BeforeRun(), ...)

**Comment by DeadPro60** [comment]
Thank you!
