### ISSUE TITLE
A few problems. priority_extreme

### ISSUE THREAD

**Issue by jesus123123** [CosmosOS/Cosmos#335]
1. Rings.
Whenever I try to add the assembly for ring in the hardware class, i always get the error 
that there is basically no such thing. "The type or namespace 'Ring' could not be found..."
2. Running?!
"A project with an Output Type of Class Library cannot be started directly."
I have honestly no clue.

**Comment by mterwoord** [comment]
1: Add a reference to Cosmos.Common assembly, which is where the RingAttribute is located
2: You should have a .cosmos project in your solution. THat's the project you need to set as startup project.

**Comment by jesus123123** [comment]
1. i did add a reference to cosmos.common.
2. How can i tell the what the file extension is

**Comment by mterwoord** [comment]
1: Have you also added the using statement in the top of the file?
2: It's the one with the cosmos icon. Probably has Boot as suffix.

**Comment by jesus123123** [comment]
1. I added
`using Cosmos.Common;`
and
`using Cosmos.Common.Extensions`

**Comment by mterwoord** [comment]
What Cosmos version are you using?

Can you find the boot project yet?

**Comment by jesus123123** [comment]
I just installed the cosmos devkit, lets see if it works now. 


I was using the userkit >-<

**Comment by jesus123123** [comment]
1. done, ring working now

2. Wont start the boot project.


error i think thats causing it: Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.String  System.Number.FormatInt32(System.Int32, System.String, System.Globalization.NumberFormatInfo).

A few lines later...

1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.6561749
1>Done building project "CosmosKernel2Boot.Cosmos" -- FAILED.
1>
Build has been canceled.

**Comment by mterwoord** [comment]
You're using a method that's not working yet.
You could switch to devkit.

**Comment by jesus123123** [comment]
I am currently using devkit, the most recent one.

**Comment by mterwoord** [comment]
Devkit? THen int32.tostring should work. Maybe you could join the gitter chat? That way we can communicate faster.

What's the code of your kernel?

**Comment by jesus123123** [comment]
Yeah, lets move to a COSMOS gitter chat
