### ISSUE TITLE
How do I get a mouse?

### ISSUE THREAD

**Issue by jesus123123** [CosmosOS/Cosmos#339]
I have been trying to get a mouse, but it just won't work. My current code is in the display driver, as a public void.
   
    ` var m = new Mouse();`
           ` var display = new DisplayDriver();`
            `var mew = m.X;`
            `var mewtwo = m.Y;`
            `display.setPixel(mew, mewtwo, 40);`
            `display.setPixel(mew + 1, mewtwo, 40);`
           ` display.setPixel(mew + 2, mewtwo , 40);`
           ` display.setPixel(mew , mewtwo + 1, 40);`
           ` display.setPixel(mew, mewtwo + 2, 40);`
            `display.setPixel(mew + 1, mewtwo + 1, 40);`
           ` display.setPixel(mew + 2, mewtwo + 2, 40);`
            `display.setPixel(mew + 3, mewtwo + 3, 40);`
            `display.initmouse();`

**Comment by zarlo** [comment]
is the project in ring HAL

**Comment by jesus123123** [comment]
yes

**Comment by jesus123123** [comment]
all the initmouse code does is loop from itself back to that public void, so its constantly updating

**Comment by jesus123123** [comment]
`using Cosmos.Common;


// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: Ring(Ring.System)]
[assembly: AssemblyTitle("Package Name")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Company")]
[assembly: AssemblyProduct("Package Name")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: NeutralResourcesLanguage("en-US")]`

**Comment by zarlo** [comment]
i use https://github.com/zarlo/PunkOS/blob/master/PunkOS.System/MouseRenderer.cs

**Comment by jesus123123** [comment]
Not working

The issue remains open.

**Comment by mterwoord** [comment]
So, what happens?

**Comment by jesus123123** [comment]
All it does it create a mouse in the corner, which i cannot move

**Comment by charlesbetros** [comment]
Please ask for further help in the chat. This isn't really an "issue" and is more of a "how to". Once you get things working you could help us out by updating the docs with working code.

**Comment by jesus123123** [comment]
What chat? You mean gitter?

**Comment by mterwoord** [comment]
Yes, gitter :)
