### ISSUE TITLE
CosmosBoot error

### ISSUE THREAD

**Issue by NajiMacmillan** [CosmosOS/Cosmos#340]
Visual Studio 2015 Community is not loading the boot project, It seems that the project file is invalid.
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{8c687a0c-7a22-4034-95c8-4cbe17fc5ac0}</ProjectGuid>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
    <Name>NajiOSBoot</Name>
    <BinFormat>elf</BinFormat>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Profile>VMware</Profile>
    
    <DebugEnabled>true</DebugEnabled>
    <DebugMode>Source</DebugMode>
    <TraceMode>User</TraceMode>
    <EnableGDB>False</EnableGDB>
    <StartCosmosGDB>false</StartCosmosGDB>
    <VMWareEdition>Player</VMWareEdition>
    <OutputPath>bin\Debug\</OutputPath>
    <Name>NajiOSBoot</Name>
    <Description>Use VMware Player or Workstation to deploy and debug.</Description>
    <Deployment>ISO</Deployment>
    <Launch>VMware</Launch>
    <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include=".\NajiOS.csproj">
      <Name>NajiOS</Name>
      <Project>{0ceb5653-f1d8-4d82-84c3-5291269d78e0}</Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Cosmos.Core.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.System.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.Debug.Kernel.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
  </ItemGroup>
  
  <Import Project="$(MSBuildExtensionsPath)\Cosmos\Cosmos.targets" />
</Project>`

**Comment by jesus123123** [comment]
Do you have VMware Player or Workstation installed? You cannot use virutalbox.

**Comment by mterwoord** [comment]
What error do you get?

**Comment by jesus123123** [comment]
If your not going to respond to this issue, either close it or respond. :)
