### ISSUE TITLE
No Kernel?

### ISSUE THREAD

**Issue by Irxori-TheBetrayed** [CosmosOS/Cosmos#342]
I'm trying to make ONE pixel, or actually run my program with the whole "VGAScreen" thingy. It says there's an error invoking IL2CPU, and in the output it says Error: No Kernel Found! Why!?
Kernel:
```c#
namespace GUITest
{
    public class Kernel : Sys.Kernel
    {
        private DisDrive display;

        protected override void BeforeRun()
        {
            Console.Clear();
            display = new DisDrive();
            display.init();
        }

        protected override void Run()
        {
            display.screen.SetPixel320x200x8(0, 255, 255);
        }
    }
}
```
Display Driver:
```c#
using Cosmos.HAL;
using Sys = Cosmos.System;
namespace Display
{
    public class DisDrive
    {

        public VGAScreen screen;
        private int width, height;

        public DisDrive()
        {
            screen = new VGAScreen();
        }

        public void init()
        {
            screen.SetGraphicsMode (VGAScreen.ScreenSize.Size320x200,VGAScreen.ColorDepth.BitDepth8);
            screen.Clear(0);
            width = screen.PixelWidth;
            height = screen.PixelHeight;
        }

        public virtual void setPixel(int x, int y, int c)
        {
            if (screen.GetPixel320x200x8((uint)x, (uint)y) != (uint)c)
                setPixelRaw(x, y, c);
        }

        public virtual byte getPixel(int x, int y)
        {
            return (byte)screen.GetPixel320x200x8((uint)x, (uint)y);
        }

        public virtual void clear()
        {
            clear(0);
        }

        public virtual void clear(int c)
        {
            screen.Clear(c);
        }

        public virtual void step() { }

        public int getWidth()
        {
            return width;
        }

        public int getHeight()
        {
            return height;
        }

        public void setPixelRaw(int x, int y, int c)
        {

            screen.SetPixel320x200x8((uint)x, (uint)y, (uint)c);

        }
    }
}
```

In my solution, it's like this:
```c#
-Solution lololo
    -GUITest Project
        -References
            -All necessary References, the Hardware Project etc.
        -Kernel
        -AssemblyInfo
     -GUITestBoot Project
         -References
      -Hardware Project
          -References
              -All necessary References, Cosmos.HAL, Cosmos.Common etc.
           -AssemblyInfo
           -Kernel
```

**Comment by jesus123123** [comment]
Please post your error log.

**Comment by mterwoord** [comment]
From your Cosmos project, remove the reference to the GUITest project, and add it again.

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord It removed that "Error: No Kernel Found!" error, but now it has an error invoking IL2CPU.
@jesus123123 This is the error log after fixing the No Kernel Found error, so this will only have the error invoking IL2CPU.

```c#
1>------ Build started: Project: GUITestBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITestBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\CosmosKernel4\bin\Debug\CosmosKernel4.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITestBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\CosmosKernel4\bin\Debug\CosmosKernel4.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
Build has been canceled.
```

**Comment by mterwoord** [comment]
Can you post complete output of il2cpu?

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord What does that mean?

**Comment by mterwoord** [comment]
Hmm, seems you already did. What is your VS settings regarding the output panel in Visual Studio?

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord I don't know what you mean, but the Output has now said new things like ```c#Loading: Whatever``` and ```c#Plug Found: System.Whatever```

**Comment by jesus123123** [comment]
Ah, thats a good thing. Presumably there is a very long list of plug founds?

Reading back, it seems you now have an IL2CPU error. You ARE using vmware and _NOT_ virtualbox?

**Comment by charlesbetros** [comment]
In Run() try display.setPixel instead of             display.screen.SetPixel320x200x8(0, 255, 255

**Comment by Irxori-TheBetrayed** [comment]
@jesus123123 Bochs.

**Comment by mterwoord** [comment]
@Irxori-TheBetrayed Now you have more text on the output window, can you post the full contents?

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord 1>------ Build started: Project: GUITest, Configuration: Debug Any CPU ------
1>  GUITest -> C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITest.dll
2>------ Build started: Project: GUITestBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITestBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\CosmosKernel4\bin\Debug\CosmosKernel4.dll" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITest.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITestBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\CosmosKernel4\bin\Debug\CosmosKernel4.dll" "References:C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITest.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = 'C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void  System.Threading.Monitor.Exit(System.Object).
2>	 Called from :
2>	System.Console::Void InitializeStdOutError(Boolean)
2>	System.Console::System.IO.TextWriter get_Out()
2>	System.Console::Void WriteLine(System.String)
2>	Cosmos.IL2CPU.CustomImplementation.System.StringImpl::Boolean StartsWith(System.String, System.String, System.StringComparison)
2>	Plug Sub Method
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 525
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\CosmosKernel4\bin\Debug\CosmosKernel4.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Harry\Documents\Visual Studio 2015\Projects\CosmosKernel4\GUITest\bin\Debug\GUITest.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
2>	C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\Harry\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:05.4426852
2>Done building project "GUITestBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
Build has been canceled.

**Comment by jesus123123** [comment]
Your using a method that is not supported, hence the "native code found, plug required." Try removing some code, then running the program. You will eventually find a block of code that is causing the problem. Sometimes the problem can be fixed by coding it in a different way.

**Comment by charlesbetros** [comment]
Do you have any other code besides what is posted here? Are you using TextWriter?

**Comment by Irxori-TheBetrayed** [comment]
@charlesbetros Nope.
@jesus123123 Is that on the display driver or the Kernel?

**Comment by Irxori-TheBetrayed** [comment]
@charlesbetros What even is TextWriter?

**Comment by jesus123123** [comment]
It could be both, try removing some code from both. I'll bet its the kernel though.

Try putting all of your definitions into Run, instead of having the declarations in beforerun.

Your also overcomplicating the setpixel command. You could easily use
`display.setPixel(255, 255, 0);` or whatever arguments you want for it

**Comment by Irxori-TheBetrayed** [comment]
@jesus123123 It's highly unlikely that the Kernel has the native code, as it only has three lines of code.

**Comment by jesus123123** [comment]
Doesn't mean that it cant have native code - it could be one line, and it could still be native code.

**Comment by mterwoord** [comment]
@Irxori-TheBetrayed Can you send a zip file containing your full project?

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord I can't, I don't have a lot of experience with Visual Studio. I'm just used to giving people the project. With VS, it dosen't let me open the project in a different folder. Should I just install BasicOS?

**Comment by zarlo** [comment]
yes BasicOS is a go starting project

**Comment by mterwoord** [comment]
Go to disk and zip up the project there.

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord Disk? Would that be D:?

**Comment by mterwoord** [comment]
No clue where you saved your cosmos project. Ths is normal windows stuff...

**Comment by Irxori-TheBetrayed** [comment]
@mterwoord https://www.sendspace.com/file/pa7uou

**Comment by charlesbetros** [comment]
@Irxori-TheBetrayed Right click on GUITestBoot and select "Add Reference" then add Cosmos.Core.Plugs, Cosmos.Debug.Kernel.Plugs, and Cosmos.System.Plugs then you should be good.

**Comment by Irxori-TheBetrayed** [comment]
@charlesbetros Thanks! It actually loads up Bochs now, so it's time for a mouse...
