### ISSUE TITLE
The wiki NEEDS to be updated.

### ISSUE THREAD

**Issue by Irxori-TheBetrayed** [CosmosOS/Cosmos#344]
Just saying, the wiki here at Github has a lot of the GUI tutorials saying, "Empty.", and some of the tutorials are probably outdated. And maybe you could update the status on FAT, we're all looking forward to that.

**Comment by charlesbetros** [comment]
Perhaps you could help us out with that? The limited resources we have are focused on core items. GUI is a low priority for how.

**Comment by MyvarHD** [comment]
I dont have time right now to commit for some core development but i can put in a hour or 2 on docs, i understand cosmos pretty well should not be to hard, im an dyslexsic thow so some one will have to grammer/spell cheack me after words

**Comment by Irxori-TheBetrayed** [comment]
@MyvarHD Yes, I'll grammar/spell check you afterwards. I'm not that good at cosmos so...yeah.

**Comment by intotheunknown1997** [comment]
thanks can you show how to make a mouse please i'm soo stuck on it

**Comment by Irxori-TheBetrayed** [comment]
@intotheunknown1997 As I'm just learning the basics of GUIs and that, I can't help you. Even if I could, we'd be filling up the issue comments with irrelevant content. Try getting help from the Gitter chat room (Somebody's on there pretty much all the time, day and night) or wait for the wiki to be updated.

**Comment by zarlo** [comment]
you can look at other peoples project [Cosmos-Projects-Tools](https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Projects-Tools#operating-systems)

**Comment by xeu100** [comment]
I agree, I am actually making a wiki for it with what I know!
