### ISSUE TITLE
using Cosmos.System.FileSystem;

### ISSUE THREAD

**Issue by tsoj** [CosmosOS/Cosmos#346]
Hello,
how can i use namespaces like Cosmos.System.FileSystem or others? If i launch it it shows me that:
"... The type or namespace name 'FileSystem' does not exist in the namespace 'Cosmos.System' (are you missing an assembly reference?)"
What is an assembly reference or better how can i fix that without big troubles?

**Comment by mterwoord** [comment]
WHat version of Cosmos are you using? Probably you're referring to old namespaces.....

**Comment by tsoj** [comment]
im using the "UserKit 20150918". with "using Cosmos.HAL;" its the same but if i add the Cosmos.HAL reference it works but i dont know wich reference i should use for .FileSystems.

**Comment by fanoI** [comment]
The UserKit had no FAT implemented or it was - probably - only a mockup you should use the last devKit or wait for the release of the new userKit.

**Comment by tsoj** [comment]
ok, thank you :)
