### ISSUE TITLE
Error GLNFS and IL"s

### ISSUE THREAD

**Issue by AndDOS** [CosmosOS/Cosmos#350]
Hello,I have a GLNFS.dll but system is error?
https://yadi.sk/d/bATJybwHqnves this is soure cod.
https://yadi.sk/i/a6PeKj9wqnvga  this is video error.
this is error:
{
Ошибка	7	Не удалось загрузить файл или сборку "GLNFS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
   в System.RuntimeMethodHandle.GetMethodBody(IRuntimeMethodInfo method, RuntimeType declaringType)
   в System.Reflection.RuntimeMethodInfo.GetMethodBody()
   в Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) в g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILReader.cs:строка 42
   в Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) в g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:строка 561
   в Cosmos.IL2CPU.ILScanner.ScanQueue() в g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:строка 686
   в Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) в g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:строка 277
   в Cosmos.Build.MSBuild.IL2CPUTask.Execute() в g:\IL2CPU\source2\Build\Cosmos.Build.MSBuild\IL2CPUTask.cs:строка 239	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	6	CosmosKernel1Boot
}
how i have use a GLNFS filesytem?
i use cosmos 108477,microsoft visual studio 2013 professional.

**Comment by AnotherAltr** [comment]
dll is not found....

**Comment by fanoI** [comment]
GNLFS is - in any case - an old implementation realized before Cosmos added a clear separations between user code and kernel code with the Rings so it probably will not work in any case. The good news is that Cosmos has now FAT support so GNLFS is not needed anymore.

**Comment by AndDOS** [comment]
In FAT I cant make dir...i can read files
