### ISSUE TITLE
Console.ReadLine() freeze os

### ISSUE THREAD

**Issue by Julien12150** [CosmosOS/Cosmos#351]
Using the last devkit version, the `Console.ReadLine();` method freeze the os...

I'm using the "ISO Image" option in the Cosmos Boot properties.
[Download to iso](https://github.com/CosmosOS/Cosmos/files/208791/problem.zip)

**Comment by MyvarHD** [comment]
That is how Readline works it whats for the user to provide input then continues execution.
try creating a standard c# console application and call readline you will see the same thing happen.
This is not a bug.

**Comment by Julien12150** [comment]
i know, but this time the cursor doesn't blink, and i cannot type anything

**Comment by mterwoord** [comment]
@Julien12150 Where are you running it? Inside VMware, bochs? On physical machine?

**Comment by MyvarHD** [comment]
If you are in a VM make sure you captured the mouse and keyboard in th vm.

**Comment by Julien12150** [comment]
most of the time i'm using virtualbox, i just tried it on vmware, it's still not working

**Comment by mterwoord** [comment]
So using latest devkit, things started towork fine?

**Comment by fanoI** [comment]
Please reopen this! It was talking of **userkit** I can confirm that the last devkit are not working!
Try the guess demo keyboard scancodes are not read anymore, VNMWare gives no errors but Bochs writes:

01150400000i[KBD   ] internal keyboard buffer full, ignoring scancode.(86)
01151120000i[KBD   ] internal keyboard buffer full, ignoring scancode.(06)
01154340000i[KBD   ] internal keyboard buffer full, ignoring scancode.(86)
01155012000i[KBD   ] internal keyboard buffer full, ignoring scancode.(06)
01158356000i[KBD   ] internal keyboard buffer full, ignoring scancode.(86)
01159040000i[KBD   ] internal keyboard buffer full, ignoring scancode.(06)
01162788000i[KBD   ] internal keyboard buffer full, ignoring scancode.(86)

**Comment by charlesbetros** [comment]
Isn't this already covered by a different issue?
