### ISSUE TITLE
OS doesn't accept keyboard input

### ISSUE THREAD

**Issue by jpmac26** [CosmosOS/Cosmos#357]
I just installed the userkit via the batch file (and I have also tried the installVS2015.bat file, it doesn't fix this problem), and after I create a new C# operating system and try to boot using a VM (VMWare with and without debugger, even VirtualBox), and the OS will boot just fine, but no matter what I try, typing on the keyboard in the VM doesn't do anything, and no characters appear after the "Input: " prompt. I have had this problem for a while now (at least a month, probably more), and I haven't seen any other issues reporting this, so I assume I'm still doing something wrong. Any help would be appreciated!

**Comment by charlesbetros** [comment]
You built Cosmos from the latest source?

**Comment by jpmac26** [comment]
Yes, I built just yesterday with a clean clone of the commit "reversed return values". I also just recently reinstalled Windows 10 (Professional 64-bit, if you're wondering) because I was having occasional random issues, and it's been working well, although it still didn't fix the above issue. I've had this problem for quite a while now, I figured it was just a passing bug that other people would have. But I haven't seen anyone else mention it, so I figured I would.

**Comment by xeu100** [comment]
Cosmos is very specific when it comes to configuration, make sure your Visual Studio has been setup to your keyboard layout.

**Comment by fanoI** [comment]
After you have compiled the devKit have you installed a new UserKit using installUserKit.bat from the Cosmos sources? If not you are yet using an old version...

Other thing inside the Cosmos source you could try if the Guess demo is working? For me it works but it is really a lot that I do not update my toy OS so maybe works only in the Guess demo?

**Comment by charlesbetros** [comment]
I've tried it on GuessOS as well as my own kernel. Works on the latest source.

**Comment by jpmac26** [comment]
Ok, I decided to try deleting and re-cloning the repo, and I also uninstalled the userkit from its AppData folder too, and now I can't get the userkit or the VS2015 batch file to build Cosmos anymore. I'm getting 27 Errors, and I think it's something about not being able to find a reference assembly, but it also keeps talking about Visual Studio 10.0, which is VS2010 IIRC, which I don't have installed. Is there any way to find the build log for the Cosmos installer so that I can paste it here?

**Comment by zarlo** [comment]
[DevKit 22.04.16 prebuilt](https://www.dropbox.com/s/8i5qswtetabvgng/CosmosDevKit%2022.04.16%20.exe?dl=0)

**Comment by jpmac26** [comment]
The prebuilt version has finally fixed the problem, thanks so much! I'm still gonna have to see why I can't get the source to compile on my end, but I guess this issue was also a problem with my computer, so I'm gonna close the issue for now.
