### ISSUE TITLE
Help ME!!!!!!!

### ISSUE THREAD

**Issue by nvn488** [CosmosOS/Cosmos#360]
I Created the Project and It has error : 
![image](https://cloud.githubusercontent.com/assets/18691258/14840263/d1a8e5cc-0c5c-11e6-8365-1b829759869b.png)

**Comment by zarlo** [comment]
can we have the error log, are you using DevKit Or UserKit, are you using visual studio 2015

**Comment by mterwoord** [comment]
It seems you are using an ancient version of cosmos. What version is that?
