### ISSUE TITLE
When will a new userkit?

### ISSUE THREAD

**Issue by AndDOS** [CosmosOS/Cosmos#361]
For VS2013?or else?

**Comment by zarlo** [comment]
a userkit is just a pre built devkit

**Comment by fanoI** [comment]
I think a new UserKit will be released when we have a complete FAT implementation.

**Comment by zarlo** [comment]
so soon

**Comment by mterwoord** [comment]
VS2013 don't be suported anymore.

If you have VS2015 and a non-express edition, you can build a devkit yourself.....
