### ISSUE TITLE
More directory issues.

### ISSUE THREAD

**Issue by MichaelTheShifter** [CosmosOS/Cosmos#365]
Alright so I got two issues here.

One, when I get the directory listing of ANY child directory within the volume, so for example, 0:\apple, this happens.

![image](https://cloud.githubusercontent.com/assets/18349904/15228256/4af3e316-1859-11e6-90ab-1fb7ca1dfe4d.png)

Second thing is, that exact crash happens when you try to write to the directory - though I can create directories within it, but I see that the directories give me an NRE when I try to get their parent's name.

**Comment by Julien12150** [comment]
this screenshot is too tiny, we cannot see anything

**Comment by MichaelTheShifter** [comment]
My apologies. Let me get another one.

![image](https://cloud.githubusercontent.com/assets/18349904/15234012/40db630a-187b-11e6-9178-6f0546667eb2.png)

**Comment by charlesbetros** [comment]
This should be fixed in the latest master.
