### ISSUE TITLE
CosmosBoot load failed

### ISSUE THREAD

**Issue by NajiMacmillan** [CosmosOS/Cosmos#366]
I am having issues with my CosmosBoot project, VS2015 Community Edition is failing to load the project file.I would like to note that I use VMware Workstation.
Here is the project file:
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{9b725efb-e78a-45f7-88c9-79ac1a967cf0}</ProjectGuid>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
    <Name>CosmosKernel2Boot</Name>
    <BinFormat>elf</BinFormat>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Profile>VMware</Profile>
    
    <DebugEnabled>true</DebugEnabled>
    <DebugMode>Source</DebugMode>
    <TraceMode>User</TraceMode>
    <EnableGDB>False</EnableGDB>
    <StartCosmosGDB>false</StartCosmosGDB>
    <VMWareEdition>Workstation</VMWareEdition>
    <OutputPath>bin\Debug\</OutputPath>
    <Name>CosmosKernel2Boot</Name>
    <Description>Use VMware Player or Workstation to deploy and debug.</Description>
    <Deployment>ISO</Deployment>
    <Launch>VMware</Launch>
    <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include=".\CosmosKernel2.csproj">
      <Name>CosmosKernel2</Name>
      <Project>{c15e163e-d0c6-4857-a91b-17af5419d596}</Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" />
    <Reference Include="Cosmos.HAL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" />
    <Reference Include="Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" />
    <Reference Include="Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" />
  </ItemGroup>
  
  <Import Project="$(MSBuildExtensionsPath)\Cosmos\Cosmos.targets" />
</Project>`

**Comment by MichaelTheShifter** [comment]
How are you opening the project? Are you doing so through the .sln in the root of the solution, or the .cosmos in the boot project?

**Comment by zarlo** [comment]
edit <TargetFrameworkVersion>v4.5</TargetFrameworkVersion> to <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
