### ISSUE TITLE
Thrwoing exceptions inside IL2CPU process confuses compiler

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#368]
Having an exception inside an Opcode IL2CPU class confuse the compile that throws the exception during compilation instead that at run time when the Opcode is used.

This is the sample code to reproduce the problem:

```
using System;
using CPUx86 = Cosmos.Assembler.x86;

namespace Cosmos.IL2CPU.X86.IL
{
    /// <summary>
    /// Converts the unsigned integer value on top of the evaluation stack to F (native float) it can be double or some FPU extended precision Floating Point
    /// type as the weird 80 bit float of x87). For now we assume it to be always equal to double.
    /// </summary>
    [Cosmos.IL2CPU.OpCode( ILOpCode.Code.Conv_R_Un )]
     
    public class Conv_R_Un : ILOp
    {
        
        public Conv_R_Un( Cosmos.Assembler.Assembler aAsmblr )
            : base( aAsmblr )
        {
        }

        public override void Execute( MethodInfo aMethod, ILOpCode aOpCode )
        {
            var xValue = aOpCode.StackPopTypes[0];
            var xValueIsFloat = TypeIsFloat(xValue);
            var xValueSize = SizeOfType(xValue);

            throw new NotImplementedException("Conv_R_Un with type " + aOpCode.StackPopTypes[0] + " not supported!");
        }
    }
}
```

compiling this gives this error during compilation:
`
04:55:09.720845 Start executing
04:55:09.767954   Start configuration. IsELF = True, Target = Bochs
04:55:10.164583     Starting kernel 'C:\Users\fano\Documents\GitHub\Cosmos\Tests
\Cosmos.TestRunner\bin\Debug\Cosmos.Compiler.Tests.Bcl.dll'
04:55:10.165584       Running task 'IL2CPU'
04:55:12.724519         Msg: Executing command line "C:\Users\fano\Documents\Git
Hub\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\IL2CPU.exe"  "DebugEnabled:true" "S
tackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:MethodFoote
rs" "DebugMode:Source" "TraceAssemblies:User" "DebugCom:1" "UseNAsm:True" "Outpu
tFilename:C:\Users\fano\Documents\GitHub\Cosmos\Tests\Cosmos.TestRunner\bin\Debu
g\WorkingDirectory\Kernel.asm" "EnableLogging:True" "EmitDebugSymbols:True" "Ign
oreDebugStubAttribute:False" "References:C:\Users\fano\Documents\GitHub\Cosmos\T
ests\Cosmos.TestRunner\bin\Debug\Cosmos.Compiler.Tests.Bcl.dll" "References:C:\U
sers\fano\Documents\GitHub\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\Cosmos.Core.
Plugs.dll" "References:C:\Users\fano\Documents\GitHub\Cosmos\Tests\Cosmos.TestRu
nner\bin\Debug\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\fano\Document
s\GitHub\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\Cosmos.System.Plugs.dll"
04:55:12.725519         Msg: Working directory = 'C:\Users\fano\Documents\GitHub
\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\WorkingDirectory'
04:55:15.521228         Msg: Loaded : DebugEnabled
04:55:15.522229         Msg: Loaded : StackCorruptionDetectionEnabled
04:55:15.522229         Msg: Loaded : DebugMode
04:55:15.522229         Msg: Loaded : StackCorruptionDetectionLevel
04:55:15.522229         Msg: Loaded : TraceAssemblies
04:55:15.522229         Msg: Loaded : DebugCom
04:55:15.522229         Msg: Loaded : UseNAsm
04:55:15.523230         Msg: Loaded : OutputFilename
04:55:15.523230         Msg: Loaded : EnableLogging
04:55:15.524231         Msg: Loaded : EmitDebugSymbols
04:55:15.524231         Msg: Loaded : IgnoreDebugStubAttribute
04:55:15.524231         Msg: Loaded : References
04:55:15.524231         Msg: Executing IL2CPU on assembly
04:55:18.067894         Msg: Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
04:55:18.067894         Msg: Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
04:55:18.506188         Msg: Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
04:55:18.507188         Msg: Detecting fields for type 'Cosmos.Debug.Common.Document'
04:55:18.508189         Msg: Detecting fields for type 'Cosmos.Debug.Common.Method'
04:55:18.514193         Msg: Error: Exception: System.Exception: Error compiling
 method 'SystemDoubleCosmosSystemPlugsSystemRandomImplGetUniform': System.NotImplementedException: Conv_R_Un with type System.UInt32 not supported!
`

**Comment by charlesbetros** [comment]
This is expected behavior. The IL2CPU methods are there to generate assembly and they throw exceptions during compilation. Those methods aren't called at runtime.

**Comment by fanoI** [comment]
So how to emit the "not implemented exception" when the user invoke Conv.R.Un at run time?

**Comment by mterwoord** [comment]
You don't, the compiler comes across a compiletime error situation, so you just have the compiler make a crash (throw exception)
