### ISSUE TITLE
Stuck on checking hardware phase when running on physical hardware.

### ISSUE THREAD

**Issue by Rocker98585** [CosmosOS/Cosmos#370]
When I'm booting on physical hardware like my desktop or even my laptop, it doesn't get past the checking PCI devices phase. It also freezes during the device check on VirtualBox. My operating system will only ever boot on VMware.

**Comment by MichaelTheShifter** [comment]
What version of Cosmos are you using? Userkit ot Devkit? Also note that Cosmos isn't really supported by certain hardware, so it may not recognize it and problems like that may occur. For example, Cosmos' latest DevKit is fully compatible with my development machine, but not compatible with my Toshiba Satellite from 2007 (which I got originally to actually test my OS on).

If you're on Userkit, try upgrading to Devkit. It has a lot more features and fixes, and supports more hardware. I know this first-hand with the Satellite... Userkit doesn't boot at all, but DevKit at least tries to.
