### ISSUE TITLE
Keyboard class causes "Error occurred while invoking IL2CPU." 

### ISSUE THREAD

**Issue by yewmisgoat** [CosmosOS/Cosmos#372]
Keyboard keyboard = GetKeyboard(); //causes error

Keyboard keyboard = new Keyboard(); //also causes error

PS2Keyboard keyboard = new PS2Keyboard(); // again, also causes error

GetKeyboard().ReadKey(); // and once again, also causes the error

**Comment by mterwoord** [comment]
Can you post the contents of the output window?

I'm thinking you're getting the Rings check error.

**Comment by mterwoord** [comment]
FOr normal usage, you'd use Console.ReadKey, ReadLine etc.

**Comment by yewmisgoat** [comment]
Yes; however, Console.ReadKey is currently broken and causes an error.

**Comment by mterwoord** [comment]
Please join the gitter chat and we can get you going for solving this...

**Comment by jp2masa** [comment]
Is this still valid?
