### ISSUE TITLE
Debug works but release doesn't

### ISSUE THREAD

**Issue by Raepheles** [CosmosOS/Cosmos#373]
Hello,

I was trying to make a simple calculator but I had couple problems. Current code below is compilable at debug mode perfectly but it doesn't compile at release mode.

`Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1KernelRun': System.Exception: OpCode IL_0088: Call tries to pop more stuff from analytical stack than there is!`

[Functions.cs](http://pastebin.com/KETDz9uP)
[Kernel.cs](http://pastebin.com/ymMQuXV1)

There are couple things about the code. GetNum is between -100 and 100 currently to make it run faster. That virtual machine is extremely slow I don't think it'll be big issue when I boot it via usb. And I use int because I got another error when I tried to use float numbers instead.

**Comment by charlesbetros** [comment]
Currently the release target isn't supported, only debug.

**Comment by Raepheles** [comment]
But someone said that in order to boot from usb drive I gotta save iso file in release mode. I tried in debug one anyway it got stuck at start never booted program. So this means I cannot boot it with usb?

**Comment by charlesbetros** [comment]
I think he was referring to disabling the kernel debugger in Cosmos. Right click on your .Cosmos project and select properties. Under the debug tab there is an "Enable Remote Debugging" option. Turn that off.

**Comment by Raepheles** [comment]
There is no debug tab under ISO Image Profile. 

This is the comment I'm talking about btw: https://github.com/CosmosOS/Cosmos/issues/112#issuecomment-104767464

**Comment by charlesbetros** [comment]
I can't remember the options under Iso. I'll have to check when I get to my machine.

**Comment by Raepheles** [comment]
Not much actually doubt there is something that can be done here.

http://prntscr.com/bbmduo
http://prntscr.com/bbmdx0
http://prntscr.com/bbmdyq
http://prntscr.com/bbme10

**Comment by charlesbetros** [comment]
Looks like we are missing the Debug options for the ISO profile. They are there for the other profiles.

**Comment by Raepheles** [comment]
Yes I found what you were talking about under VMware profile but changing it there doesn't effect ISO Image profile right? Documentation on this cosmos is almost non-existent :(

**Comment by yewmisgoat** [comment]
I updated the instructions; I could have sworn I set it from debug to release, but I recreated it and it works just fine without the release setting if you're using the latest dev-kit.

**Comment by Raepheles** [comment]
But I tried it with debug settings and it really got stuck at booting like you said :D

**Comment by yewmisgoat** [comment]
Hmm... I'll make you a video tutorial. Trust me, I'm very impatient so I'd hate to leave you waiting too XD

**Comment by yewmisgoat** [comment]
Give me roughly 15-45 minutes and I'll have that tutorial for you ;P

**Comment by Raepheles** [comment]
Thanks waiting for it!

**Comment by yewmisgoat** [comment]
Well, XSplit gave me problems and so did OBS, so I'm reinstalling XSplit Broadcaster again. I promise you I **will** make this for you! XD

**Comment by Raepheles** [comment]
Don't force yourself to do it right now :D It's 3.00 AM here anyway I'll probably hang around 1-1.5h more and sleep. I'll check here tomorrow. Thanks again for your effort.

**Comment by yewmisgoat** [comment]
No problem! I love the COSMOS project, and if I can help it and it's community, I will :)

**Comment by charlesbetros** [comment]
Why not come visit the gitter chat? :)

**Comment by Raepheles** [comment]
I actually went there and stood there for couple hours but it's not very active I guess.

**Comment by yewmisgoat** [comment]
How does one navigate to said locale?

**Comment by Raepheles** [comment]
https://gitter.im/CosmosOS/Cosmos

It's on wiki page. There are also other groups like yahoo facebook etc.

**Comment by yewmisgoat** [comment]
Okay, you're lucky I'm persistent. Just downloafed the forsaken Bandicam software. Talk about desperate measures. Officially en route.

**Comment by yewmisgoat** [comment]
Video is done! However, Bandicam, being the crapware it is, doesn't allow for voice capture (Discovered that by the lack of my voice in the video XD) but I'll send it to you as is. If you have any questions, feel free to ask me! You can ask here or message me at yewmisgoat@gmail.com

**Comment by Raepheles** [comment]
Thanks. You guys should create discord server for cosmos. It's really popular chat program despite it being new and it's becoming even more popular every day.

**Comment by yewmisgoat** [comment]
Your voiceless (darn bandicam) tutorial can be found [here(]https://youtu.be/631YitcB6ro).
Sorry for all the hassle; trust me, I've been trying as hard as I can to provide you this information. XD

**Comment by yewmisgoat** [comment]
and lol, I love Discord.

**Comment by yewmisgoat** [comment]
Ignore my background lol. My gf drew it.

**Comment by Raepheles** [comment]
Btw I did the exact same things :D Even used rufus just like you did. Guess there is something wrong with my code or pc that I was trying to boot it. Gonna test tomorrow with default OS and see if it works. If it doesn't work too then gonna try on another pc. Background is fine :+1:

**Comment by yewmisgoat** [comment]
Hmm well if you want, don't hesitate to ask! My email, Skype, and Discord are in my GitHub profile, and I'm pretty much available most of the time (Graduated school over a year early, so I've got all the free time in the world atm ;)

**Comment by charlesbetros** [comment]
There are only a few core devs active active currently, but one of us is usually there or if not responds quickly.
