### ISSUE TITLE
CPU Exception x09

### ISSUE THREAD

**Issue by benwhiting64** [CosmosOS/Cosmos#374]
Hi,
When I am trying to run my project in VMWare, it will not run, saying "CPU Exception x09". Is there a fix for this?
Thanks

**Comment by zarlo** [comment]
it is just saying "CPU Exception x09" and code is running when you get the error

**Comment by TheCool1James** [comment]
I have the same error. I have `Console.WriteLine("Welcome to LiquiDOS");` under BeforeRun() and it runs fine. However, the moment I add `Console.ForegroundColor = ConsoleColor.Green;` before the WriteLine() the CPU Exception 0x9 pops up in red in VMWare AND Virtualbox. When I move the statement into the Run() method, the Exception turns into 0x8 in red.
Is there any alternative to changing console color? Thanks.
-Jamez

**Comment by mterwoord** [comment]
What version of cosmos are yo using?

**Comment by TheCool1James** [comment]
Latest cosmos with .NET V5. Recently switched to devkit and everything I fine now. I don't know what happened there.

**Comment by mterwoord** [comment]
.NET 5? Didn't know that exists yet...

Our compiler has seen lots of improvements last months....

**Comment by TheCool1James** [comment]
Sorry, I meant .NET 4.52 (messed up)  but things work now at least
