### ISSUE TITLE
Floats not implemented

### ISSUE THREAD

**Issue by Py64** [CosmosOS/Cosmos#386]

**Comment by MichaelTheShifter** [comment]
Floats are being worked on by @fanol if I remember correctly, so you'll have to wait until they're implemented.

**Comment by fanoI** [comment]
Yes I'm working on them... in my repo they are _partially_ implemented but I have to do a little more work...

**Comment by fanoI** [comment]
Another thing: what is in particular that you have find to not be implemented? Surely partially they worked (in the sense that you can do d1 + d2, d1 > d2... toString() is a problem instead).
