### ISSUE TITLE
Cannot Build because of random error.  

### ISSUE THREAD

**Issue by mas0701** [CosmosOS/Cosmos#388]
Hi! So I just installed cosmos (I got a new PC) and for some reason nothing will work!  I opened up the project I was working on, and I get the error "error occured while invoking il2cpu". okay, whatever.  So I open up the default "Blank" template that actually has some code in it.  still the same error I am using .Net 4.5 and my code is:
http://pastebin.com/kAvk6Ku7

thanks - mike

**Comment by mterwoord** [comment]
What cosmos version are you using?

**Comment by mas0701** [comment]
I dont exactly know.  I just downloaded the latest I believe.  For VS Community 2015

**Comment by mas0701** [comment]
The latest, 20150918
https://github.com/CosmosOS/Cosmos/wiki/How-to-install-Cosmos
I followed this exactly^^

**Comment by mterwoord** [comment]
Can you post the contents of the output panel in here please?

**Comment by mas0701** [comment]
http://pastebin.com/F9UWxQCU

**Comment by mterwoord** [comment]
Do you have .net 3.5 installed?

**Comment by mas0701** [comment]
I dont.  The how to install guide said that cosmos relied on 4.5, so thats what I installed

**Comment by mterwoord** [comment]
Well, after that release, we foudn out we also rely on parts of 3.5.
Can you install it?

**Comment by mas0701** [comment]
okay it's installed.  Should I switch the application framework to 3.5

**Comment by mterwoord** [comment]
No. We use some kind of com object which is only installed on 3.5. The kernel should be 4.5

**Comment by mas0701** [comment]
Oh, okay.  Thanks! Everything seems to be working fine now!

**Comment by mterwoord** [comment]
Awesome! Maybe you could update the wiki page to mention 3.5? Would be awesome ! :)

**Comment by mas0701** [comment]
Sure!

**Comment by mterwoord** [comment]
Thanks. Afterwards, please close this issue.

**Comment by mas0701** [comment]
It seems that I have the issue again, and 3.5 is still active.  the build stops and says "error occured while invoking il2cpu"

**Comment by mterwoord** [comment]
Please post the output panle here. Most likely it's a different issue now.

We currently have a bug/unimplemented feature, where the actual error isn't printed to the error list.

**Comment by mterwoord** [comment]
We could use your help though.. ;)

**Comment by mas0701** [comment]
http://pastebin.com/mZ10z4Tk

**Comment by mterwoord** [comment]
The code you're using hits an unimplemented opcod (Mul_Ovf). 

How would you feel about helping us out implementing stuff?

In fact, implementing this one is easy. I can guide you through (on gitter).

**Comment by mas0701** [comment]
I'm sorry, but I'm not that experienced with coding.

**Comment by MichaelTheShifter** [comment]
Hey, me and @mterwoord investigated the issue. Turns out that this OpCode is implemented in the latest source code, which means that the error shouldn't occur.

Try downloading the latest source code (not the one listed on the wiki. Head to 'Code' on this github page and it should give you an option to download the repo as a zip or clone it. Do that, and install it just like any other devkit.
