### ISSUE TITLE
Building the devkit throws NuGet errors.

### ISSUE THREAD

**Issue by Irxori-TheBetrayed** [CosmosOS/Cosmos#392]
Hey, the title says it all, here's a nopaste:
https://nopaste.xyz/?c57aa526bfabfc46#ySmhXBjZeJwONbXJ4E6EHqUly2Y0Oz1couDmlUvXE40=

**Comment by charlesbetros** [comment]
You are running the latest master?

**Comment by Irxori-TheBetrayed** [comment]
Yep.

**Comment by Irxori-TheBetrayed** [comment]
Never mind, when you were telling me about it on Gitter, I actually wasn't there, and I saw a link to this tree:
https://github.com/CosmosOS/Cosmos/tree/76605da1ddb8658eb05b50fc01e5006ff9bac34d
Go there if you're getting these errors!
