### ISSUE TITLE
The type or namespace name 'Sys' does not exist in the namespace 'Cosmos'

### ISSUE THREAD

**Issue by condargames** [CosmosOS/Cosmos#398]
I'm getting the errors below when I try to build Cosmos.Sys.Deboot.Shutdown();
Please help me :(

**Comment by mterwoord** [comment]
What Cosmos version are you using?

**Comment by condargames** [comment]
I'm using this version : Release 106458

**Comment by mterwoord** [comment]
That's a really old release. See https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20150918

**Comment by condargames** [comment]
Ok, this version is only working on VS 2013 ?

**Comment by mterwoord** [comment]
The version in the link is for VS2015.

**Comment by condargames** [comment]
Thank , but it's not working
Error : The type or namespace name 'Sys' does not exist in the namespace 'Cosmos'

**Comment by jp2masa** [comment]
It's not Cosmos.Sys it's Cosmos.System or only Sys(if Cosmos.System is imported as Sys)

**Comment by mterwoord** [comment]
I think it's an ancient namespace...

**Comment by condargames** [comment]
Ok thanks @jp2masa it's working :)

**Comment by condargames** [comment]
i'm back.
 I'm stuck for 30 minutes on it

Screen : http://www.hostingpics.net/viewer.php?id=77563227461.png

**Comment by mterwoord** [comment]
What environment are you trying to run your kernel?


2016-06-28 16:41 GMT-04:00 condargames <notifications@github.com>:

**Comment by condargames** [comment]
Windows 10

**Comment by mterwoord** [comment]
Ok, what virtualization or emulation software are you using? The kernel runs as an operating system.

**Comment by condargames** [comment]
VMware Workstation 12 Player

**Comment by mterwoord** [comment]
So with the default F5 machine you get that situation?

**Comment by condargames** [comment]
It's always the same

**Comment by charlesbetros** [comment]
It sounds like an assembly target mismatch issue between the kernel and cosmos assemblies.

**Comment by condargames** [comment]
Ok reinstall cosmos ?

**Comment by condargames** [comment]
@mterwoord Ok man what is the version?
Cosmos.hardware is not available !!
I have just Cosmos.System and Cosmos.debug

**Comment by charlesbetros** [comment]
Are you using the latest from GitHub? Cosmos.Hardware no longer exists. It was renamed to Cosmos.HAL.
