### ISSUE TITLE
Stuck On "Creating ATA IOGroup" - VirtualBox

### ISSUE THREAD

**Issue by Listrix** [CosmosOS/Cosmos#400]
I know that this issue has been reported before but since nothing has been done about it I thought I'd report it again. I used to make OSs using Cosmos a year or two ago and used VirtualBox just fine, but now I'm trying to use VirtualBox and it's stuck on "Creating ATA IOGroup". I read on some earlier posts that you need to partition the drives a certain way or disable ATA controllers but how do I fix it for VirtualBox?

**Comment by mterwoord** [comment]
If I'm not mistaken, virtualbox emulates SATA drives etc. We have some compatibility issues there, and we know that. I'm unsure how to fix that in virtualbox. Your best bet is to use bochs. That way, you also have the VS integration of cosmos.. (including our debugger)

**Comment by Listrix** [comment]
okay, I'll try to run it in Bochs and see how that goes, thanks for the advice

**Comment by RAY-THE-HOT-DOG** [comment]
Happened to me too.

**Comment by mterwoord** [comment]
@Listrix Have you tried bochs yet?

To both of you: can you post a screenshot here of the virtualbox configuration you made?

**Comment by Listrix** [comment]
I've tried it on Bochs, it kinda worked. The emulation works fine, but for some reason why I try to build my project it keeps failing, can't figure out why. Actually, just thought of something. It doesn't fail when I change the build settings to ISO it works perfectly, then when I change to debug in Bochs it says that the build fails but asks if it should run the last successful build.

But in terms of the emulation it's perfectly fine

**Comment by mterwoord** [comment]
Can you show the error you get when building? Also, try reinstalling cosmos in your own user account, so you don't have any potential permission issues.
