### ISSUE TITLE
Can't use filesystem driver

### ISSUE THREAD

**Issue by autoossite** [CosmosOS/Cosmos#401]
It says: The type or namespace name 'FileSystem' does not exist in the namespace 'Cosmos.System' (are you missing an assembly reference?)

**Comment by jp2masa** [comment]
Are you using the userkit or the devkit?

**Comment by RAY-THE-HOT-DOG** [comment]
userkit

**Comment by jp2masa** [comment]
The FileSystem was created some time after the latest userkit release so if you need the FileSystem build the devkit

**Comment by RAY-THE-HOT-DOG** [comment]
I can't.
I need the VMware service and I don't have a work address.

**Comment by jp2masa** [comment]
a work address?

**Comment by RAY-THE-HOT-DOG** [comment]
you need to make an account

**Comment by jp2masa** [comment]
When I installed I thought I had to do it but there's a version that doesn't need account

**Comment by RAY-THE-HOT-DOG** [comment]
give me a link

**Comment by RAY-THE-HOT-DOG** [comment]
hello?

**Comment by RAY-THE-HOT-DOG** [comment]
are you going to?

**Comment by jp2masa** [comment]
https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0

**Comment by RAY-THE-HOT-DOG** [comment]
wrong thing

**Comment by RAY-THE-HOT-DOG** [comment]
oh. you don't need it

**Comment by RAY-THE-HOT-DOG** [comment]
the vs2015 build won't work

**Comment by jp2masa** [comment]
why?

**Comment by RAY-THE-HOT-DOG** [comment]
![](http://i67.tinypic.com/2lj1207.jpg)

**Comment by RAY-THE-HOT-DOG** [comment]
where do I put it?

**Comment by RAY-THE-HOT-DOG** [comment]
???

**Comment by jp2masa** [comment]
You didn't run the install-VS2015.bat directly right? Because the working directory should be the repo folder.

**Comment by jp2masa** [comment]
Just double click the intall-VS2015.bat file

**Comment by RAY-THE-HOT-DOG** [comment]
I did. No repo though.  I'll try again.

**Comment by RAY-THE-HOT-DOG** [comment]
On July 12.

**Comment by mterwoord** [comment]
@RAY-THE-HOT-DOG You can also use bochs if you cant use vmware...

**Comment by RAY-THE-HOT-DOG** [comment]
You should have posted this on the other issue. 
Talk with you there.

**Comment by RAY-THE-HOT-DOG** [comment]
You should have posted this on the other issue. 
Talk with you there.

**Comment by RAY-THE-HOT-DOG** [comment]
Inno setup link?

**Comment by charlesbetros** [comment]
www.google.com

**Comment by autoossite** [comment]
I'll use google then.

**Comment by autoossite** [comment]
VIX needs an account.

**Comment by Zino2201** [comment]
I have builded the devkit into a userkit install, do you want it ?

**Comment by autoossite** [comment]
yes

**Comment by autoossite** [comment]
???

**Comment by autoossite** [comment]
Completed in #411.
