### ISSUE TITLE
vmware doesn't work

### ISSUE THREAD

**Issue by autoossite** [CosmosOS/Cosmos#402]
![] (http://i66.tinypic.com/fapx14.jpg)

**Comment by mterwoord** [comment]
What did you do/try/etc?

Also, are there any special chracters in your user path?

**Comment by RAY-THE-HOT-DOG** [comment]
It's way of working depends on a glitch. It's in another account with a forgotten password.

**Comment by RAY-THE-HOT-DOG** [comment]
Used to work. Still seems to be a glitch, I opened the os in administrator mode, started showing up in recent. I can still set the compilation to iso and copy everything. Also can access all files in the other account.

**Comment by mterwoord** [comment]
I'd suggest not using that trick: Using normal operations means you can use our debugger...

**Comment by RAY-THE-HOT-DOG** [comment]
Then I'll use my new computer when I get it?
