### ISSUE TITLE
The userkit NEEDS to be updated NOW!

### ISSUE THREAD

**Issue by autoossite** [CosmosOS/Cosmos#403]
You guys, get some more people working on everything but core stuff.

**Comment by mterwoord** [comment]
Wht do you mean? ditch the engine, and work on the cart?

**Comment by fanoI** [comment]
The UserKit will be updated when we will be ready :-)

**Comment by zarlo** [comment]
the user kit is just a prebuild dev kit

**Comment by autoossite** [comment]
But there is no filesystem in the userkit

**Comment by autoossite** [comment]
why did you close it

**Comment by charlesbetros** [comment]
Two reasons.

1. Demanding things of the dev team in all caps is not polite.
2. You can build a "userkit" from the master branch any time you like.

**Comment by autoossite** [comment]
how?

**Comment by autoossite** [comment]
Sorry, not demanding.
