### ISSUE TITLE
How to switch to AZERTY keyboard ?

### ISSUE THREAD

**Issue by Zino2201** [CosmosOS/Cosmos#405]
Hello, i use Cosmos but i'm french, so my keyboard is AZERTY.

How do i switch to AZERTY ? By default, it's in QWERTY.

**Comment by MichaelTheShifter** [comment]
Not too sure if you can... not without programming the keyboard layout into the driver yourself. That requires the devkit, and modifying Cosmos' source code.

**Comment by Julien12150** [comment]
you can try something like this
```csharp
public static char GetAzertyChar(char c)
{
    if(c == 'q') return 'a';
    else if(c == 'w') return 'z';
    //etc
    else return c;
}
```

**Comment by Zino2201** [comment]
Ok I will try

**Comment by jp2masa** [comment]
The AZERTY keyboard layout is implenented, but to use it the devkit needs to be recompiled so I will try to do a little change to make it easier to change the keyboard layout

**Comment by jp2masa** [comment]
When my PR gets merged, to switch to FR layout it's only needed to include this in BeforeRun():
```
KeyboardScanMap = new Sys.ScanMaps.FR_Standard();
```

**Comment by Zino2201** [comment]
Ok, thanks ^^
