### ISSUE TITLE
Can not build devkit

### ISSUE THREAD

**Issue by autoossite** [CosmosOS/Cosmos#406]
![](http://i67.tinypic.com/2czyc2b.png)

**Comment by jp2masa** [comment]
Are you using the naster branch files?

**Comment by mterwoord** [comment]
Why are you manually restoring packages? (You're using wrong arguments btw

Try using the install-VS2015.bat script.

**Comment by autoossite** [comment]
That's exactly what i'm using: the install-VS2015.bat script.

**Comment by mterwoord** [comment]
So why do you get a prompt then?

Are you calling each statement in the batch file manually, or executing the bat file?

**Comment by autoossite** [comment]
executing it

**Comment by mterwoord** [comment]
Then it seems the install-VS2015.bat file is seriously goofed up. Can you compare your version with the version on github?

**Comment by autoossite** [comment]
shall I show you what I get with latest version?
