### ISSUE TITLE
Userkit installer does not install anything!

### ISSUE THREAD

**Issue by autoossite** [CosmosOS/Cosmos#409]
![](http://i64.tinypic.com/205zgc1.png)

**Comment by jp2masa** [comment]
You compiled the userkit or devkit?

**Comment by autoossite** [comment]
userkit (Read Title)

**Comment by jp2masa** [comment]
ok sry didnt read I think you need to open the created exe

**Comment by autoossite** [comment]
it opened by itself

**Comment by jp2masa** [comment]
And you installed it?

**Comment by jp2masa** [comment]
Right click on the project and click Reload project what error comes up?

**Comment by autoossite** [comment]
wait...

**Comment by autoossite** [comment]
![](http://i66.tinypic.com/642hk2.png)

**Comment by autoossite** [comment]
???

**Comment by jp2masa** [comment]
Close Visual Studio and run the setup again in your "Cosmos folder/Setup/something.exe"

**Comment by autoossite** [comment]
OK

**Comment by autoossite** [comment]
![](http://i64.tinypic.com/imp5rq.png)

**Comment by autoossite** [comment]
Hello?

**Comment by autoossite** [comment]
#408

**Comment by autoossite** [comment]
@mterwoord See this please

**Comment by jp2masa** [comment]
It's not Builder its an .msi

**Comment by autoossite** [comment]
where is it

**Comment by jp2masa** [comment]
the main Cosmos folder in the setup/output folder

**Comment by autoossite** [comment]
OK

**Comment by autoossite** [comment]
Seems to be working...

**Comment by autoossite** [comment]
it is an exe not a msi

**Comment by jp2masa** [comment]
oh sry then i first said exe but then you opened Builder so i thought it was msi and my mistake...

**Comment by autoossite** [comment]
it's done

**Comment by jp2masa** [comment]
works now?

**Comment by autoossite** [comment]
yeah
