### ISSUE TITLE
An error when building my OS

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#410]
It says: 
`1>------ Build started: Project: AutoOS APE 1.2Boot, Configuration: Debug x86 ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '.\AutoOS APE 1.2.2\AutoOS APE 1' does not exist.
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AutoOS APE 1.2\AutoOS APE 1.2\bin\Debug\AutoOS APE 1.2Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AutoOS APE 1.2\AutoOS APE 1.2\bin\Debug\AutoOS APE 1.2Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>	Working directory = 'C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AutoOS APE 1.2\AutoOS APE 1.2\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Error: No Kernel found!
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.3082756
1>Done building project "AutoOS APE 1.2Boot.Cosmos" -- FAILED.
1>
1>Build FAILED.
Build has been canceled.`

**Comment by jp2masa** [comment]
What is the Kernel.cs namespace and the reference in the Boot project?

**Comment by autoossite** [comment]
You want code?

**Comment by autoossite** [comment]
`
using System;
using System.Linq;
using System.Data;
using System.Text.RegularExpressions;
using Sys = Cosmos.System;

namespace AutoOS_APE_1._2
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            var input = "AutoOS Burrito 3.6";
            Console.WriteLine(input);
            Console.Clear();
            Console.WriteLine("----////\\\\----");
            Console.WriteLine("AutoOS Burrito 3.6");
        }

        protected override void Run()
        {
            startTerminal(null, null);
        }
        public void startTerminal(string[] aa, string[] commands)
        {
            var Badges = new string[10];
            Badges[0] = "You used AutoOS!";
            var BadgeInfo = new string[10];
            BadgeInfo[0] = "Congratulations!";
            string[] Commands = new string[999];
            string[] s2 = new string[999];
            var index11212 = 1;
            Console.WriteLine("AutoOS Burrito 3.6. Copyright 2016");
            Console.WriteLine("All Rights Reserved. Type 'help' For List Of Commands.");
            string clipboard = "";
            while (true)
            {
                var xc = 0;
                Console.Write("Commands>");
                string TypedCommand = Console.ReadLine();
            dds:
                var parts1 = TypedCommand.Split(' ');
                string command1 = parts1[0];
                int index1321 = 0;
                switch (command1)
                {
                    case "new":
                        Console.Clear();
                        Console.WriteLine("New Commands Wizard:");
                        xc = 0;
                        xc++;
                        Console.WriteLine("This is your " + xc + "st command!");
                        Console.WriteLine("Enter commands, Separated by commas, to execute when your command is typed. ");
                        Commands[index11212] = Console.ReadLine();
                        var array = Commands[index11212].Split(',');
                        Console.WriteLine("What is your command going to be?");
                        s2[index11212] = Console.ReadLine();
                        index11212++;
                        Console.WriteLine("");
                        //Console.Write("Would You Like To Create A Workspace File (Native Executable) To Save Your Application? (Y/N)");
                        //var Response = Console.ReadLine();
                        //if (Response == "Y")
                        //{

                        //}
                        Console.Write("Type your command and a space and delete to delete it. (" + s2[index11212] + ")");
                        if (s2 == null)
                        {
                            startTerminal(s2, Commands);
                        }
                        else
                        {

                        }
                        break;
                    case "cls":
                        Console.Clear();
                        break;
                    case "help":
                        Console.WriteLine("Commands: \nhelp: This command (get list of commands), \nclear: Clear the console, \nprint: Echo typed text.");
                        break;
                    default:
                        goto sauch;
                    ddsa:
                        index1321++;
                    sauch:
                        try
                        {
                            if (command1 == aa[index1321])
                            {
                                goto dds;
                            }
                        }
                        catch (Exception)
                        {
                            goto lolos;
                        }
                        goto ddsa;
                    lolos:
                        if (command1 == "print")
                        {
                            var code = TypedCommand.Split(new[] { "print " }, StringSplitOptions.RemoveEmptyEntries)[0];
                            var output = code.Substring(6);
                            Console.WriteLine(output);
                            break;
                        }
                        else if (command1 == "copy")
                        {
                            var code = TypedCommand;
                            var output = code.Substring(5);
                            clipboard = output;
                            Console.WriteLine(output + " Has Been Copied To Clipboard.");
                            break;
                        }
                        else if (command1 == "paste")
                        {
                            if (parts1[2] == "/c")
                            {
                                Console.WriteLine("Enter Name Of Command To Send Copied Text To: ");
                                TypedCommand = Console.ReadLine() + " " + clipboard;
                                goto dds;
                            }
                            Console.WriteLine(clipboard);
                            break;
                        }
                        else
                        {
                            Console.WriteLine("'" + command1 + "' Is Not The Name Of A Valid Command.");
                            break;
                        }
                }
                Console.WriteLine("");
                startTerminal(aa, commands);
            }
        }
        public void codeSignalModules(string ds, string cess)
        {
            var c1 = "Code Green";
            var c2 = "Code Yellow";
            var c3 = "Code Red: Something is wrong!";
            var c4 = "Code Blue: Permission Requested";
            var c5 = "Code Grey";
            if (cess == "1")
            {
                Console.WriteLine(c1 + " " + ds);
            }
            if (cess == "2")
            {
                Console.WriteLine(c2 + " " + ds);
            }
            if (cess == "3")
            {
                Console.WriteLine(c3 + " " + ds);
            }
            if (cess == "4")
            {
                Console.WriteLine(c4 + " " + ds + " press enter twice to allow, press a and then enter to ignore");
                switch (Console.ReadLine())
                {
                    case "a":
                        Console.WriteLine("Request ignored.");
                        break;
                    case "":
                        Console.WriteLine("Press enter again to allow. You still have one chance to press a then enter to ignore the request");
                        break;
                }
                switch (Console.ReadLine())
                {
                    case "a":
                        Console.WriteLine("Request ignored.");

                        break;
                    case "":
                        Console.WriteLine("Press enter again to allow.");
                        break;
                }
            }
            if (cess == "5")
            {
                Console.WriteLine(c5 + "This information may be irrelevant/spam");
                irrelevantInfo(ds);
            }
            if (cess == "6")
            {
                Console.WriteLine(c5 + " " + ds);
            }
        }

        private void irrelevantInfo(string parameter)
        {
            Console.WriteLine("Are you sure you want to view the maybe irrelevant/spam info?");
            switch (Console.ReadLine())
            {
                case "no":
                    break;
                case "yes":
                    codeSignalModules(parameter, "6");
                    break;
                default:
                    Console.WriteLine("Sorry, invalid answer. Answer must be yes or no.");
                    irrelevantInfo(parameter);
                    break;
            }
        }
        private void giveBadge(string badge)
        {

        }
        private void drawLetter(string arrayonetwosoon)
        {
            var ascii_11 = @"     /\";
            var ascii_12 = @"    /  \";
            var ascii_13 = @"   /    \";
            var ascii_14 = @"  /------\";
            var ascii_15 = @" /        \";
            var ascii_16 = @"/          \";
            var ascii_21 = @"";
            string[] a;
            a = new string[6];
            a[0] = ascii_11;
            a[1] = ascii_12;
            a[2] = ascii_13;
            var ascii_251 = @"\       /";
            var ascii_252 = @" \     /";
            var ascii_253 = @"  \   /";
            var ascii_254 = @"   \ /";
            var ascii_255 = "     |";
            var ascii_256 = "     |";
            var abcs = "abcdefghijklmnopqrstuvwxyz";
            string[] abc;
            abc = new string[26];
        }
    }
}`

**Comment by jp2masa** [comment]
Only the namespace of the Kernel class

**Comment by autoossite** [comment]
look at it please

**Comment by jp2masa** [comment]
And if possible open the boot project file in a text editor and copy the line that references Kernel.cs

**Comment by autoossite** [comment]
the reference is containing spaces while the namespace contains "_"
reference: AutoOS APE 1.2

**Comment by autoossite** [comment]
namespace: AutoOS_APE_1._2

**Comment by autoossite** [comment]
problems with the reference generator?

**Comment by autoossite** [comment]
Should I change it?
I could.

**Comment by autoossite** [comment]
Maybe.

**Comment by jp2masa** [comment]
Check if the path to Kernel.cs in the Boot project file is exactly equal to the path of Kernel.cs relative to the project folder

**Comment by autoossite** [comment]
OK

**Comment by autoossite** [comment]
too compilicated

**Comment by autoossite** [comment]
this is the path:
C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AutoOS APE 1.2\AutoOS APE 1.2

**Comment by autoossite** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{4caac17e-c364-4966-88c2-f513cc6a3f74}</ProjectGuid>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
    <Name>AutoOS APE 1.2Boot</Name>
    <BinFormat>elf</BinFormat>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Profile>VMware</Profile>
    <DebugEnabled>true</DebugEnabled>
    <DebugMode>Source</DebugMode>
    <TraceMode>User</TraceMode>
    <EnableGDB>False</EnableGDB>
    <StartCosmosGDB>false</StartCosmosGDB>
    <VMWareEdition>Player</VMWareEdition>
    <OutputPath>bin\Debug\</OutputPath>
    <Name>AutoOS APE 1.2Boot</Name>
    <Description>Use VMware Player or Workstation to deploy and debug.</Description>
    <Deployment>ISO</Deployment>
    <Launch>VMware</Launch>
    <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include=".\AutoOS APE 1.2.2\AutoOS APE 1">
      <Name>AutoOS APE 1.2</Name>
      <Project>{df1c5de2-9c6d-4721-b64d-ec488169faa1}</Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Cosmos.Core.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.System.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.Debug.Kernel.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
  </ItemGroup>
  
  <Import Project="$(MSBuildExtensionsPath)\Cosmos\Cosmos.targets" />
</Project>

**Comment by autoossite** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{4caac17e-c364-4966-88c2-f513cc6a3f74}</ProjectGuid>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
    <Name>AutoOS APE 1.2Boot</Name>
    <BinFormat>elf</BinFormat>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Profile>VMware</Profile>
    <DebugEnabled>true</DebugEnabled>
    <DebugMode>Source</DebugMode>
    <TraceMode>User</TraceMode>
    <EnableGDB>False</EnableGDB>
    <StartCosmosGDB>false</StartCosmosGDB>
    <VMWareEdition>Player</VMWareEdition>
    <OutputPath>bin\Debug\</OutputPath>
    <Name>AutoOS APE 1.2Boot</Name>
    <Description>Use VMware Player or Workstation to deploy and debug.</Description>
    <Deployment>ISO</Deployment>
    <Launch>VMware</Launch>
    <VisualStudioDebugPort>Pipe: Cosmos\Serial</VisualStudioDebugPort>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include=".\AutoOS APE 1.2.2\AutoOS APE 1">
      <Name>AutoOS APE 1.2</Name>
      <Project>{df1c5de2-9c6d-4721-b64d-ec488169faa1}</Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Cosmos.Core.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.System.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
    <Reference Include="Cosmos.Debug.Kernel.Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983"/>
  </ItemGroup>
  
  <Import Project="$(MSBuildExtensionsPath)\Cosmos\Cosmos.targets" />
</Project>
`

**Comment by autoossite** [comment]
@jp2masa Hello?

**Comment by jp2masa** [comment]
I think the error is the dots on the namespace
I think it's not a good idea to include the version on the namespace abd the dots are changing the namespace. Replace the dots by underscores and try.

**Comment by jp2masa** [comment]
The dot*

**Comment by jp2masa** [comment]
You can simply remove the dot as there's already an underscore

**Comment by autoossite** [comment]
I don't get it the source is too complicated can you do it for me?

**Comment by jp2masa** [comment]
Replace
namespace AutoOS_APE_1._2
With
namespace AutoOS_APE_1_2

**Comment by autoossite** [comment]
I replaced it with AutoOS_APE

**Comment by jp2masa** [comment]
In Kernel.cs

**Comment by autoossite** [comment]
I did

**Comment by jp2masa** [comment]
Now try it

**Comment by autoossite** [comment]
OK

**Comment by autoossite** [comment]
I need to change the cosmos file

**Comment by autoossite** [comment]
how?

**Comment by autoossite** [comment]
change what?

**Comment by jp2masa** [comment]
?

**Comment by jp2masa** [comment]
Tou are getting the same error?

**Comment by autoossite** [comment]
yes

**Comment by zarlo** [comment]
You need to add your kernel as a ref in your cosmos boot project

**Comment by Project-Magenta** [comment]
how?
