### ISSUE TITLE
The process cannot access the file 'C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\DeciduOS\DeciduOS\bin\Debug\DeciduOSBoot.iso' because it is being used by another process.

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#413]
Restarted Visual Studio, tried using Unlocker.

**Comment by autoossite** [comment]
@jp2masa @autoossite

**Comment by mterwoord** [comment]
Did you try rebooting? Normally means something is keeping the fle occupied.

**Comment by Project-Magenta** [comment]
no

**Comment by MichaelTheShifter** [comment]
Is a VM using that ISO file? Be sure to shut down the VM first.

If that doesn't work, reboot. If THAT doesn't work, something's hungry and trying to eat your file. xD

**Comment by fanoI** [comment]
Unlocker should usually solve the problem.

**Comment by Project-Magenta** [comment]
look at my question

**Comment by Project-Magenta** [comment]
![](https://github.com/Project-Magenta/Cosmos/issues/4)

**Comment by fanoI** [comment]
OK you have tried to used Unlocker and what it did? You don't get what process was locking the file (so to kill it)? Do you Have the possibility to delete the file?
