### ISSUE TITLE
How do I add a shutdown and reboot function?

### ISSUE THREAD

**Issue by CheesyNM** [CosmosOS/Cosmos#414]
Can anyone help me?

**Comment by CheesyNM** [comment]
I'm trying to add a GUI using the basic tutorial, but I do not know how to add the member (display).

**Comment by jp2masa** [comment]
DisplayDriver display;

**Comment by jp2masa** [comment]
then on BeforeRun() write:

display = new DisplayDriver();
display.init()

**Comment by CheesyNM** [comment]
Do I need to put DisplayDriver display in my main kernel?

**Comment by jp2masa** [comment]
You know how to declare variables in C#?

**Comment by jp2masa** [comment]
Right after
public class Kernel : Sys.Kernel
{

Write:

DisplayDriver display;

**Comment by CheesyNM** [comment]
It says that the namespace could not be found

**Comment by CheesyNM** [comment]
I've pasted it right after the "public class Kernel : Sys.Kernel
{"

**Comment by jp2masa** [comment]
You included the other project(created during tutorial)?

**Comment by CheesyNM** [comment]
Yes, the other class

**Comment by jp2masa** [comment]
The DisplayDriver class is in other project, right?

**Comment by CheesyNM** [comment]
No just in the same project only in another class

**Comment by CheesyNM** [comment]
I'll just send some pictures.
![image](https://cloud.githubusercontent.com/assets/20524347/16940224/a5ac96fe-4d88-11e6-9985-5d6393284946.png)
![image](https://cloud.githubusercontent.com/assets/20524347/16940236/b90341f8-4d88-11e6-8b39-fe9005593cb7.png)
![image](https://cloud.githubusercontent.com/assets/20524347/16940238/c3a3d85c-4d88-11e6-9c90-d9b57aea0d4e.png)

**Comment by CheesyNM** [comment]
Can you help me?

**Comment by jp2masa** [comment]
In the tutorial it says to create a new project and change the new project ring to System and the DisplayDriver class is created there. Then you reference the new project on the first and you can run it. You changed the main project Ring now just change it back to User or delete that line from assemblyinfo

**Comment by jp2masa** [comment]
Then in the Kernel.cs file write:
```
using Display;
```
and the rest of the code is fine

**Comment by CheesyNM** [comment]
Thanks

**Comment by CheesyNM** [comment]
If I need any more help I'll ask it in this "Issue".

**Comment by CheesyNM** [comment]
I'm still getting errors:
![image](https://cloud.githubusercontent.com/assets/20524347/16963889/f8a3d384-4df8-11e6-938d-5f4ffddf51e3.png)
![image](https://cloud.githubusercontent.com/assets/20524347/16963896/02bcabfc-4df9-11e6-80e2-397f3db90cb5.png)
![image](https://cloud.githubusercontent.com/assets/20524347/16963903/0d4f6636-4df9-11e6-8e24-b65690fd9ae9.png)

**Comment by jp2masa** [comment]
```
using Cosmos.Common
```

must be right after the other usings on the start of the file

**Comment by jp2masa** [comment]
And
```
DisplayDriver display;
```

must be right after the class not the namespace

**Comment by CheesyNM** [comment]
Still getting errors with the "using Hardware;" and "using Cosmos.Common;"

**Comment by jp2masa** [comment]
Send a screenshot please

**Comment by jp2masa** [comment]
And delete the "using Hardware;" part

**Comment by CheesyNM** [comment]
![image](https://cloud.githubusercontent.com/assets/20524347/16965707/c7294042-4e01-11e6-95b1-fe45ecd62d23.png)
It's inside the main project

**Comment by CheesyNM** [comment]
The ''DisplayDriver display;'' is good

**Comment by CheesyNM** [comment]
No errors with that

**Comment by jp2masa** [comment]
You only needs Cosmos.Common on the AssemblyInfo of the Hardware project

**Comment by jp2masa** [comment]
Also to start the DisplayDriver, on the BeforeRun() method add:
```
display = new DisplayDriver();
display.init();
```

**Comment by CheesyNM** [comment]
Like this
![image](https://cloud.githubusercontent.com/assets/20524347/16965837/3875bc62-4e02-11e6-9eee-80661b87e715.png)

**Comment by jp2masa** [comment]
Try to compile now

**Comment by CheesyNM** [comment]
Getting an error with the main project assemblyinfo
![image](https://cloud.githubusercontent.com/assets/20524347/16965937/9f250c92-4e02-11e6-8eec-54fb498471da.png)

**Comment by CheesyNM** [comment]
I just need to remove it, right?

**Comment by jp2masa** [comment]
Yes, remove that Ring line

**Comment by CheesyNM** [comment]
If I remove it I get this
![image](https://cloud.githubusercontent.com/assets/20524347/16965994/dbe7ab08-4e02-11e6-9860-f4077dd2ea1a.png)

**Comment by jp2masa** [comment]
Right click the Boot project and set it as startup project

**Comment by CheesyNM** [comment]
Second time I set the boot project as a startup project, but now it seems to work

**Comment by jp2masa** [comment]
Because when you created the Hardware project it set HardwareBoot project as startup and then you delete it and it selected the main project and not the Boot

**Comment by CheesyNM** [comment]
Is it normal that when I test it in Oracle VMWare, the screen is all blue and red

**Comment by jp2masa** [comment]
Yes, it lags a bit. Try removing the Screen.Clear line from DisplayDriver class, I think it works.

**Comment by CheesyNM** [comment]
You mean this:
`public virtual void clear(int c)
        {
            screen.Clear(c);
        }`

**Comment by CheesyNM** [comment]
Or this:
`screen.Clear(0);
`

**Comment by CheesyNM** [comment]
Do you also know how to add a mouse, because the turorial is a bit unclear of where to put it in.

**Comment by jp2masa** [comment]
I was talking about `Screen.Clear(0)` and for the mouse you should visit the original link which is in the wiki page of the mouse

**Comment by jp2masa** [comment]
`Sys.Power.Reboot()` and `Stop()` should work

**Comment by jp2masa** [comment]
Called directly from the Kernel.cs

**Comment by CheesyNM** [comment]
`Stop();` doesnt't work how I want it, i want it to actually shut down the computer/virtual machine. Is that possible?

**Comment by jp2masa** [comment]
For now, it isn't.

**Comment by CheesyNM** [comment]
Ok then I'll just add a message: It is now safe to turn the machine off

**Comment by vogon101** [comment]
Hey: Take a look at BasicOS: https://github.com/vogon101/basicos

**Comment by mihail-rotmg** [comment]
Create a new Cosmos C# Project named `Core`.
Delete `Kernel.cs` (From the `Core` project) and the `CoreBoot` project.
Set your `KernelBoot` project as your startup project.
Add `Cosmos.Core` and `Cosmos.Common` to references.
Go to `AssemblyInfo.cs` and add this following lines of code to it:
`using Cosmos.Common;` and `[assembly: Ring(Ring.Core)]`.

Now add this files to the `Core` project.

`ACPI.cs`: http://pastebin.com/kYi6nY25
`PortIO.cs`: http://pastebin.com/4iX5ruDx

After that add the `Core` project to the references of your project where you want to use it.
And in the file that you plan to use ACPI functions add this line: `using Core;`

Use `ACPI.Shutdown();` to shutdown the PC.
Use `ACPI.Reboot();` to reboot the PC.
