### ISSUE TITLE
Help with file system/system.io

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#415]
**System.io streamreader/writer doesn't work. Will this be fixed soon? is there an alternate way to do file management in your os?**

Output I get:

1>------ Build started: Project: StrawberryOS testerBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\StrawberryOS testerBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\StrawberryOS tester.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\StrawberryOS testerBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\StrawberryOS tester.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>	Working directory = 'C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Plug found: 'System.RuntimeType'
1>	Plug found: 'System.OutOfMemoryException'
1>	Plug found: 'System.Double'
1>	Plug found: 'System.Delegate'
1>	Plug found: 'System.Array'
1>	Plug found: 'System.Buffer'
1>	Plug found: 'System.Enum'
1>	Plug found: 'System.EventHandler'
1>	Plug found: 'System.Exception'
1>	Plug found: 'System.MulticastDelegate'
1>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>	Plug found: 'System.Math'
1>	Plug found: 'System.String'
1>	Plug found: 'System.Diagnostics.Debugger'
1>	Plug found: 'System.Byte'
1>	Plug found: 'System.Environment'
1>	Plug found: 'System.GC'
1>	Plug found: 'System.Int16'
1>	Plug found: 'System.Int32'
1>	Plug found: 'System.Int64'
1>	Plug found: 'System.IntPtr'
1>	Plug found: 'System.Number'
1>	Plug found: 'System.Object'
1>	Plug found: 'System.Single'
1>	Plug found: 'System.SR'
1>	Plug found: 'System.UInt16'
1>	Plug found: 'System.UInt32'
1>	Plug found: 'System.UInt64'
1>	Plug found: 'System.Threading.Interlocked'
1>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>	Plug found: 'System.Resources.ResourceManager'
1>	Plug found: 'System.Net.IPAddress'
1>	Plug found: 'System.Net.SocketAddress'
1>	Plug found: 'System.Globalization.NumberFormatInfo'
1>	Plug found: 'System.Drawing.Color'
1>	Plug found: 'System.Drawing.SR'
1>	Plug found: 'System.Security.CodeAccessSecurityEngine'
1>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>	Plug found: 'System.RuntimeTypeHandle'
1>	Plug found: 'System.SByte'
1>	Plug found: 'System.UIntPtr'
1>	Plug found: 'System.Security.Cryptography.Utils'
1>	Plug found: 'System.Globalization.CultureInfo'
1>	Plug found: 'Microsoft.Win32.RegistryKey'
1>	Plug found: 'Cosmos.Core.CPU'
1>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>	Plug found: 'Cosmos.Core.IOPortBase'
1>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>	Plug found: 'System.Char'
1>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>	Plug found: 'System.Random'
1>	Plug found: 'System.Console'
1>	Plug found: 'System.Type'
1>	Plug found: 'System.Threading.Monitor'
1>	Plug found: 'System.Text.DecoderFallback'
1>	Plug found: 'System.Text.EncoderFallback'
1>	Plug found: 'System.Text.ASCIIEncoding'
1>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void  System.Threading.Thread.MemoryBarrier().
1>	 Called from :
1>	System.IO.StreamWriter::System.Text.Encoding get_UTF8NoBOM()
1>	System.IO.File::Void WriteAllText(System.String, System.String)
1>	CosmosKernel1.Kernel::Void Run()
1>	Cosmos.System.Kernel::Void Run()
1>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 525
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Charles\Documents\Visual Studio 2015\Projects\StrawberryOS tester\StrawberryOS tester\bin\Debug\StrawberryOS tester.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
1>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Users\Charles\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:01.7229334
1>Done building project "StrawberryOS testerBoot.Cosmos" -- FAILED.
1>
Build has been canceled.

**Comment by jp2masa** [comment]
Are you using the latest devkit?

**Comment by cps12145** [comment]
no. I'm using the latest Userkit

**Comment by jp2masa** [comment]
Only devkit has Filesystem implemented.
If you want to install it clone the repo or download as .zip and run install-VS2015.bat it will fail on some dependencies probably just install them

**Comment by cps12145** [comment]
Do you know when Filesystem will be implemented in Userkit? I think I might just wait.

**Comment by jp2masa** [comment]
I don't know the exact time it will take for a userkit release, but I think it will take some weeks.

**Comment by jp2masa** [comment]
If you want I compiled the current state of Cosmos: http://jp2masa.tk/downloads/CosmosUserKit-20160719-vs2015.zip

**Comment by cps12145** [comment]
Thanks, but are you sure this is safe?

**Comment by cps12145** [comment]
Thank you. Can I safely install this over the userkit version, or will it create any errors?

**Comment by jp2masa** [comment]
I think you won't have problems

**Comment by cps12145** [comment]
Hi! I successfully installed the version you gave me, but when I tried to run an OS (even without filesystem functions), I get this in my console.

1>------ Build started: Project: StrawberryOS, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Cosmos.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Cosmos.HAL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Users\Charles\documents\visual studio 2015\Projects\StrawberryOS\StrawberryOS\Kernel.cs(4,13,4,19): error CS0246: The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Charles\documents\visual studio 2015\Projects\StrawberryOS\StrawberryOS\Kernel.cs(5,7,5,13): error CS0246: The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Charles\documents\visual studio 2015\Projects\StrawberryOS\StrawberryOS\Kernel.cs(18,33,18,42): error CS0115: 'Kernel.BeforeRun()': no suitable method found to override
1>C:\Users\Charles\documents\visual studio 2015\Projects\StrawberryOS\StrawberryOS\Kernel.cs(29,33,29,36): error CS0115: 'Kernel.Run()': no suitable method found to override
Build has been canceled.

 I saw that for the devkit version you needed a program to do with your processor, and 3.5 framework. Does this need to be on my machine when I'm using your compiled version?

**Comment by cps12145** [comment]
Hmm... I successfully installed it, but when I run an OS (even without filesystem functions), it will successfully compile, but when I get the virtual machine window open, it's just black. No option to power off, or on, so idk. What could this be?

**Comment by jp2masa** [comment]
You use VMWare or Bochs?

**Comment by cps12145** [comment]
VMware

**Comment by jp2masa** [comment]
It seems like a VMWare error does it show any error dialog?

**Comment by cps12145** [comment]
No, just a black screen. It worked perfectly before I got this new version. Lemme restart my machine and try again.

**Comment by cps12145** [comment]
Nope. It still is doing the same thing. I'm going to let it wait. Here's what it looks like.
![image](https://cloud.githubusercontent.com/assets/20527072/16973385/dcc901ac-4df8-11e6-895a-a5ca7fb836ab.png)

**Comment by jp2masa** [comment]
It's really strange. Are you using the default Kernel.cs code?

**Comment by jp2masa** [comment]
Try running the Cosmos installer again and reboot.

**Comment by cps12145** [comment]
Still isn't working... Yes I'm using default kernel code

**Comment by cps12145** [comment]
How do you disable remote debugging in VMware? I tried to just run the cosmos os from VMware, it starts to work, but I get stuck on the "Waiting for debugger connection" screen.

**Comment by cps12145** [comment]
THIS IS SO WEIRD! It randomly started working again... You think because it's a devkit version and not fully stable yet? hmm... Thanks for your help, thought. If I have any more problems tonight I'll be sure to let you know. I can't try the filesystem functions currently, because I have to go do something, but later I will. I tried adding the using cosmos.system.filesystem and it showed up which was a good sign. :)

**Comment by cps12145** [comment]
HI, again. VMware started working again, but when I tried using this code: 
                StreamWriter file = new StreamWriter("test.txt");
                file.WriteLine("Hello World! :D");
                file.Close();
It gave me the same "Build cancelled" error that I originally got. I did do "Using cosmos.system.Fileysystem" and "using system.io" I think I accidently used System.IO not filesystem stuff. What's the code for FileSystem?

**Comment by jp2masa** [comment]
I answered in #416
