### ISSUE TITLE
System.io doesn't work Cosmos.System.Filesystem

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#416]
I downloaded a compiled version of the current state of the devkit from someone who helped me. I was able to add the Cosmos.System.FileSystem, but when I tried to use system.io, I get the same error of "You need a plug, and build cancelled" I did do Using system.io. How do you make/write files with Cosmos.System.filesystem. Sorry for the dumb question, I'm a Comos noob! ;)

**Comment by jp2masa** [comment]
There is a tutorial about filesystems. You need to initialize it first.

**Comment by jp2masa** [comment]
From the tutorial:

```
var fs = new Sys.FileSystem.CosmosVFS(); Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```

Write this on BeforeRun()

**Comment by cps12145** [comment]
Once I initialize it, can I use system.io functions?

**Comment by cps12145** [comment]
Hold on, I tried the fs.CreateFile but I could only do it in BeforeRun() because it couldn't find the variable in Run()

**Comment by mterwoord** [comment]
The VFS methods aren't supposed to be directly used. After initializing, you can just use System.IO.

**Comment by cps12145** [comment]
I tried:
StreamWriter thing = new StreamWriter("Hello.txt");
            thing.WriteLine("Hello, World, This is my test file.");
            thing.Close();

but once again I get the build cancelled. I thought System.IO was supposed to work....

**Comment by jp2masa** [comment]
What error do you get?

**Comment by mterwoord** [comment]
Partially, it works. I think stuff like streamreader isn't yet working..

**Comment by cps12145** [comment]
Then how can I use the file.create? I need a file path. What's the file path for VMware stuff?

**Comment by cps12145** [comment]
I got an error when trying to make a file. I don't know what it was because it flashed and then closed... I also got an error when checking if a file exists, I don't know if they relate.
![image](https://cloud.githubusercontent.com/assets/20527072/16997180/ff62dfea-4e79-11e6-9d9a-a345c9b6e63e.png)

**Comment by jp2masa** [comment]
can you show the line of code that creates the file?

**Comment by cps12145** [comment]
I got it to work now... simple mistake of using "/" instead of "\\" one thing though, how do I delete files? File.delete isn't working, and giving me the same "plug required. build cancelled" thing.

**Comment by jp2masa** [comment]
Delete is still not working, it will be fixed soon I think

**Comment by cps12145** [comment]
Oh okay. Thanks :)

**Comment by cps12145** [comment]
This probably will never happen, but let's say it did. What if I had my OS on it's own hardware with no other OS in it. Would the drive name still be "0:\\"?

**Comment by jp2masa** [comment]
There's a method to get available drives. The drives are loaded as "0:\", "1:\", ...

**Comment by MichaelTheShifter** [comment]
Yes, it would. The "0:\" is like a drive letter in Windows, except instead of letters it's numbers, and the order in which drive numbers are assigned is based on the order in which the partitions are in the partition table. For example, say I had 2 partitions on the drive, and the second one had a file on it called "Galaxy.txt". And on the other, I have a directory called "Users". 0:\ will contain that "Users" directory, while 1:\ will contain the "Galaxy.txt".

However, I don't know if Cosmos mounts all the partitions automatically or if it's just the first one it finds.

**Comment by jp2masa** [comment]
I think the method is `fs.GetVolumes()`

**Comment by fanoI** [comment]
In future there is the idea to make volume ids personalizables too so one could have the first drive called C: as in DOS / Windows or simply '\' as in Windows.

I'm unsure that is correct to give error only because of inverted slash Windows Explorer accepts 'E:\' and 'E:/' as valid paths pointing to my BR drive...

**Comment by cps12145** [comment]
Ok, but my question is if I were to have my OS on real hardware not VMware, would the drive name still be 0:\\?

**Comment by jp2masa** [comment]
You can use `fs.GetVolumes()` to check the available drives and their paths, the first, if there is any, is always "0:\" and the next will be "1:\", ...

**Comment by cps12145** [comment]
Alrighty thank you! :)

**Comment by cps12145** [comment]
How can I create a sub directory within a directory? The Directory.createdirectory("0:\\Example\\textfiles\\") Will try to create textfiles AND example. How can I make it so that it only makes textfiles in example?

**Comment by jp2masa** [comment]
You have to specify the full path, and sub directories are possibly with a bug, anyway you can try using it.

**Comment by charlesbetros** [comment]
The .net docs say it should create all directories in the specified path and return the object for the last one. If all directories in the specified path exist it will return the existing directory at that path.

**Comment by charlesbetros** [comment]
You can pass a relative path to create, but it relies on current directory being correct. That's up to you to keep it up to date.

**Comment by cps12145** [comment]
Whenever I try to create a file, I get this in my OS Console window along with it closing out.

"Exception occurred while running kernel : 
 Exception: Unable to determine filesystem path for: 1:\"
 
This ALSO happens when I try to use 0:\

**Comment by charlesbetros** [comment]
Is this still an issue?
