### ISSUE TITLE
Filesystem path errors

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#417]
Whenever I try to create a file, I get this in my OS Console window along with it closing out.

![image](https://cloud.githubusercontent.com/assets/20527072/17046248/cb946f44-4f96-11e6-9bc1-fd71a14114cb.png)

"Exception occurred while running kernel : 
Exception: Unable to determine filesystem path for: 1:\"
This ALSO happens when I try to use 0:\

**Comment by jp2masa** [comment]
Did you initialize the filesystem?

**Comment by cps12145** [comment]
Yup

**Comment by jp2masa** [comment]
Try `Console.WriteLine(Sys.FileSystem.CosmosVFS.GetVolumes().Count);` and see if it's bigger than 0

**Comment by cps12145** [comment]
I pasted it in my code, and I got this.
![image](https://cloud.githubusercontent.com/assets/20527072/17072186/187499d4-502c-11e6-9c7e-31c4f08d151f.png)

**Comment by jp2masa** [comment]
sorry, it's ``fs.GetVolumes()`

**Comment by cps12145** [comment]
Where to I put fs.GetVolumes? Console.WriteLine(Sys.FileSystem.fs.GetVolumes().Count);  doesn't work

**Comment by jp2masa** [comment]
`Console.WriteLine(fs.GetVolumes().Count);`

**Comment by cps12145** [comment]
oh okay I'm trying it

**Comment by cps12145** [comment]
It came back with 1

**Comment by jp2masa** [comment]
try `0:/` and `0:\` and see if one of them work

**Comment by cps12145** [comment]
ok

**Comment by cps12145** [comment]
Using 1 \ or / gives me an Unrecognized escape sequence

**Comment by cps12145** [comment]
same error with File.WriteAllText("0:\\d.text", "Hi, hello");

**Comment by cps12145** [comment]
Neither 0:\\ or 0:// worked

**Comment by cps12145** [comment]
It's weird because it used to work fine just like I'm doing now.

**Comment by jp2masa** [comment]
There's a mounted drive, so it's really weird what emulator are you using?

**Comment by cps12145** [comment]
What do you mean?

**Comment by jp2masa** [comment]
VMWare or Bochs?

**Comment by cps12145** [comment]
Sorry late reply! VMware

**Comment by cps12145** [comment]
This is quite confusing now. I figured out it only happens when I try to do something System.IO related with a variable. For example: File.WriteAllText(path, "Hello World!");
That returns the error. I can only do something like File.WriteAllText("0:\\hey", "Hello World!");
But now users couldn't create custom file names...

**Comment by jp2masa** [comment]
`Console.WriteLine(path);` and check if the path is correct

**Comment by cps12145** [comment]
I did, and it was.

**Comment by jp2masa** [comment]
It's actually really weird that the string works but the variable doesn't. Try setting a breakpoint at the File.WriteAllText line and check the path value everytime it's called

**Comment by cps12145** [comment]
The path value in the error just matches what my code says. So if I was using 0:\ it'd say Unable to determine filesystem path for: 0:\

**Comment by jp2masa** [comment]
Can you show the code for the path definition until the File.WriteAllText?

**Comment by cps12145** [comment]
Console.Write("> ");
            var input = Console.ReadLine();
            string path = "0:\\" + input;

**Comment by jp2masa** [comment]
Try `string path = @"0:\" + input;`

**Comment by cps12145** [comment]
Hello! Sorry for the late reply, I had a sleep over with a friend of mine. I tried what you said, and I got the same original error... I even tried making new projects to test it out and it did the same thing. :\

**Comment by charlesbetros** [comment]
What does Console.WriteLine(path) show?

**Comment by cps12145** [comment]
Already did that. It displays the correct path. "0:\\example\\example"

**Comment by cps12145** [comment]
Hello?

**Comment by jp2masa** [comment]
This is a weird issue I don't know how to fix it, so I suggest that you try different variables and strings to see what's the cause of the issue

**Comment by cps12145** [comment]
ok thank you.

**Comment by cps12145** [comment]
I reinstalled Cosmos, and when I try file.writealltext, I know get "Exception: can't find file 0:\\example\\test.whatever" But I'm not trying to find the file... I'm trying to create it...

**Comment by jp2masa** [comment]
The folder "0:\example" was created previously?

**Comment by TheCool1James** [comment]
The file is in a folder? I'm having issues created files and folders inside of folders too.

**Comment by cps12145** [comment]
Hi, sorry I haven't written in here in a long time -- vacation. I still have the same problem. Yes the folder example was previously created. Nothing seems to be working. Do you guys have any further information?

**Comment by jp2masa** [comment]
Try:
```
var file = xFS.GetFile(your_path_here);
```
And see if you get any error.

**Comment by TheCool1James** [comment]
I have tons of fs issues rn. Can't do anything properly with the fs :(

**Comment by charlesbetros** [comment]
Should be working now.
