### ISSUE TITLE
How do I make a mouse

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#419]
![](https://xpjkrw.bn1302.livefilestore.com/y3mBjlk6ha3_VvtqX7Oa-IKORUoOr7vu-RQBPxzy52uEW8CqSPNNfs10JJteUj51a1O6e3gUFLMY48_IhGr68OK5Ezmg63MuWMMvGKNr4rRib2GVQpFPp9QYGrwLD8Db96d4cvLVx8oigo756FLCByjNgYWJYHVRcaJ1oh6SbI8GpY?width=1366&height=736&cropmode=none)

**Comment by MyvarHD** [comment]
Have you installed all the build requirements:
```
(Free) source code of Devloppement Kit from Cosmos on GitHub
You must clone the repository using Git. For a detailed walkthrough, see here.
When following the tutorial, replace OctoCat with CosmosOS and Spoon-Knife with Cosmos.
(Free) Visual Studio 2013 Community
(Free) InnoSetup QuickStart Kit
This is required to build the setup kit which is used to build and install the Visual Studio integration libaries for Cosmos.
During install it will ask you about optional components to install. Be sure you check "Install Inno Setup Preprocessor".
Visual Studio SDK: download here.
```
(Refrance)[https://github.com/CosmosOS/Cosmos/blob/master/Docs/Installation/DevKit.md]

**Comment by MyvarHD** [comment]
As for making a gui mouse:
http://www.codeproject.com/Articles/842576/Cosmos-Large-Cursor-GUI-tutorial
https://github.com/Myvar/CosmosGuiFramework

Virtual box is recommended for fps of 30 and up, but bochs works

**Comment by Project-Magenta** [comment]
the first is outdated

**Comment by Project-Magenta** [comment]
I followed the wiki.

**Comment by jp2masa** [comment]
The wiki only has a part of the full tutorial which is the first link
