### ISSUE TITLE
String[] or string[] arrays

### ISSUE THREAD

**Issue by NateDogg1232** [CosmosOS/Cosmos#422]
String[] or string[] arrays do not work and cause an error in the assembly code (at least that's what I think it is, I honestly have no idea. I've tried changing everything but taking them out, but it worked before I added the command parser [Which is what uses the string arrays])

It may also be the typing of functions with that type (string[])

Here's a screenshot.

![cosmos os issue](https://cloud.githubusercontent.com/assets/12480453/17268390/24735718-55de-11e6-970e-2461ea65aa97.png)

I can set up a git of the code and commit it, if necessary to help the issue.

**Comment by mterwoord** [comment]
Are you using multidimensional arrays?

**Comment by NateDogg1232** [comment]
Yes. I am.

**Comment by NateDogg1232** [comment]
Are multidimensional arrays not implemented?

**Comment by mterwoord** [comment]
Correct. In general, I'd suggest to use jagged arrays instead of multidimensional arrays.
