### ISSUE TITLE
Cosmos Wiki Update

### ISSUE THREAD

**Issue by CaveSponge** [CosmosOS/Cosmos#423]
I've updated the link of Ari OS in the Cosmos Projects .md file and changed it to Chocolate OS with the new URL http://github.com/CaveSponge/Chocolate, and heres the URL to the new repo with this change https://github.com/CaveSponge/CosmosWIki

http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github I used this stackoverflow page to see how to because GitHub doesn't allow wiki pull requests. Thank you.

**Comment by DjAlEx234** [comment]
...

**Comment by jp2masa** [comment]
The wiki can be edited now, so this issue can now be closed.
