### ISSUE TITLE
drawing mouse?

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#424]
![](http://i65.tinypic.com/4kjoti.png)

**Comment by popey456963** [comment]
Your screen hasn't been defined.  Are you sure you've implemented Hardware and defined Screen?

**Comment by Project-Magenta** [comment]
Define?
Nowhere does it say that in the wiki.

**Comment by jp2masa** [comment]
Try `display` instead of `Screen` if you've already setup the DisplayDriver. If not follow the tutorial: https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI---The-basics

**Comment by Project-Magenta** [comment]
#441
