### ISSUE TITLE
Cosmos Intel Edison Support / Need your help

### ISSUE THREAD

**Issue by flodt** [CosmosOS/Cosmos#425]
Hey guys! I like the idea behind Cosmos and i was always looking to run C# code on  the edison but i am not able to find any instruction how to flash the edison. I created a simple project because i am new to this. 

`namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Merlin OS - C# auf dem Intel Edison");
        }

        protected override void Run()
        {
            Console.Write("Geben Sie etwas ein: ");
            var input = Console.ReadLine();
            Console.Write("Sie meinten: ");
            Console.WriteLine(input);
            Console.WriteLine(".:: Merlin OS Ende ::.");
            Console.ReadKey();
        }
    }
}`

I changed VMware to Intel Edison in the project properties and selected x86 instead of 'AnyCPU' when i click compile no errors occur but it also happens nothing what am I doing wrong?

Sorry for my bad english i'm 10th grade from germany.

**Comment by czhower** [comment]
Edison requires special support.

Matthijs and I did some work on this last year and has basic booting but 
we've since moved on to other tasks.
