### ISSUE TITLE
Support Other Keyboards

### ISSUE THREAD

**Issue by popey456963** [CosmosOS/Cosmos#426]
Somewhat linked to #405, lots of us require other keyboards which do not conform to the default one.  For example, EN-UK appears to have the pipe key as "~" instead of the bottom left key, which currently prints absolutely nothing.

It seems a pretty important implementation for internationalisation.

**Comment by Unknown6656** [comment]
I added the layout and support for the german keyboard and future ones (including ones with the 102th key, which is OEM specific)

See pull request #435 (which was originally meant for something completely else ^^), commit [f246908](https://github.com/CosmosOS/Cosmos/pull/435/commits/f246908358a4f0fa74655b2b3aaf1b6f6922a624).

**Comment by fanoI** [comment]
Do you confirm that in any case for now the layout cannot be changed by Cosmos?

**Comment by jp2masa** [comment]
I found that problem a few weeks ago and worked on changing the implementation of the Keyboard (PR #407), and the problem exists. But the PR has some problems as it fails in some kernels(including the FAT test), declaring more than one VMT declaration of type UInt32.

**Comment by jp2masa** [comment]
Now that PR #407 was merged, you can do, for example:
```Sys.KeyboardManager.SetKeyLayout(new Sys.ScanMaps.DE_Standard());```
Currently there is US, FR and DE.

**Comment by popey456963** [comment]
Mhm, neat!  Thanks guys.  Closing :+1:
