### ISSUE TITLE
make it 32bit or 64bit other stuff

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#427]
just make it 32bit or 64bit its just what i want
the os maker or custom 32bit or 64bit
and make it easier to make a gui os

**Comment by jp2masa** [comment]
make what?

**Comment by kessanro** [comment]
@jp2masa 
just make it 32bit or 64bit its just what i want
the os maker or custom 32bit or 64bit
and make it easier to make a gui os

**Comment by jp2masa** [comment]
You want the option to build it in 64bit?

**Comment by kessanro** [comment]
@jp2masa easy way to make a gui like (might be imposible) click and drag gui or type stuff like
mouse.show();

**Comment by jp2masa** [comment]
It isn't planned to create a tool for easy drag and drop gui, this is a framework so I think it's not going to implement full mouse, with drawing, you have to draw it with the screen type you choose and you can use the mouse location from the mouse driver.

**Comment by kessanro** [comment]
@jp2masa know any others that can

**Comment by jp2masa** [comment]
Others that can do what?

**Comment by jp2masa** [comment]
Frameworks?

**Comment by kessanro** [comment]
make a os with a easy gui making

**Comment by jp2masa** [comment]
That's what I searched for the last few years and Cosmos is the simplest way I can find to make an OS. Because an OS involves much coding and many customizations, there aren't only gui editors, you have to code it.

**Comment by kessanro** [comment]
@jp2masa yeah i guess

**Comment by kessanro** [comment]
@jp2masa ut do you think it will ever do that

**Comment by jp2masa** [comment]
If I think Cosmos will support drag and drop gui?

**Comment by kessanro** [comment]
@jp2masa when in 2years

**Comment by jp2masa** [comment]
It's possible that someone develops that idea, and maybe from Cosmos, but I think no one has plans for it

**Comment by fanoI** [comment]
The fact is that Cosmos is only a kernel so:

1. Yes in future the will be a 64 bit version (but ask yourself this question? A part for marketing reasons 64 bit is really needed? What application need > 4 GB of RAM? In my Windows 10 installation 90% of processes is running at 32 Bit practically only the Kernel is running at 64 Bit!)
2. Cosmos is only a kernel so it is not is scope to make a drag & drop GUI but to create the tools that give the possibility to do it: proper drivers that support all resolution, accelerations and so on... in the end it should give the possibility to show rectangles. Your OS will create a GUI derived from it as YOU like (Windows like, Apple like, something original...)

My personal interest in a real time console OS for now to replace Linux / VxWorks IMHO the desktop is of Windows and is naive to think it could be ever replaced. If I'll need a GUI application I'll do it in "kiosk" mode (no desktop only my application).

**Comment by kessanro** [comment]
@fanoI ok ill give you time and i understand

**Comment by kessanro** [comment]
is me i had to recreate my account due to it not working correctly

**Comment by TheCool1James** [comment]
@ghost If you want (so badly) to create a 64-bit operating system, and have a fluent GUI framework up, it's better to just roll your own OS. You can use GRUB (bootloader) to drop you off into 64-bits, then have it to set up the VBE addresses and whatnot. Then, you can port the basic C libraries (after setting up the IDT and memory and paging and whatnot), and then after, you can port the Cario Library to use as a GUI. Demo of this: https://ghostkernel.org/features and the repo https://github.com/maxdev1/ghost
:) Just sayin'

**Comment by fanoI** [comment]
The fact is that Cosmos aims to be a generic kernel and we want in particular to support embedded hardware as Intel Edison and Galileo that are x86 only. This does not mean that in future there will be an x32 version (middle way between a legacy x86 kernel and a pure x64 kernel) and a x64 version... there will be an ARM port too probably!

But first to think of x32 / x64 or ARM we should finish the x86 version...

I'll close this for now as it is not really an "issue".
