### ISSUE TITLE
F# Project missing Cosmos.HAL

### ISSUE THREAD

**Issue by Arawn-Davies** [CosmosOS/Cosmos#428]
I created a new F# Kernel and after creation I got the error 

```
Severity    Code    Description Line    Project File    Suppression State
Error       The type 'TextScreenBase' is required here and is unavailable. You must add a reference to assembly 'Cosmos.HAL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'.    5   CosmosKernel2   c:\users\WalterWhite\documents\visual studio 2015\Projects\CosmosKernel2\CosmosKernel2\Kernel.fs    
```

with type Kernel() = having Kernel highlighted with red, I did find a post creation workaround by referencing Cosmos.HAL and that seemed to do the trick

**Comment by CaveSponge** [comment]
I just found that you can add the reference tag to the fsproj in Cosmos.VS.Package/Template/CosmosProject (F#) so maybe if I were to make this change and start a pull request although I do find it weird how a Cosmos.HAL reference is required in F# but not C# or VB

**Comment by jp2masa** [comment]
Also, at least on C#, the Kernel has to be in the User ring and it can't reference Cosmos.HAL

**Comment by CaveSponge** [comment]
yeah, that's why we make a Hardware project in the HAL ring

**Comment by fanoI** [comment]
No it is evident something is wrong here: any kernel should be in user ring being it in C#, VB.NET or F#...

The list on "using" (or how are called in F# is the same?). It should use only the Console class that is in System so why wants TextScreenBase?

**Comment by jp2masa** [comment]
I think it is because Kernel inherits from Cosmos.System.Kernel, which uses TextScreenBase

**Comment by fanoI** [comment]
OK but F# should have the same behavior of C# maybe in the template some references are missing that in the C# template are present?

**Comment by mterwoord** [comment]
@fanoI I think F# compiler functions differently..

**Comment by fanoI** [comment]
I have checked and the references are the sames of C# and VB.Net so yes I concord it should be some strange difference with the F# compiler.

**Comment by Arawn-Davies** [comment]
Any updates on this? Sorry it's been so long since this issue was mentioned, over a year :D I'll see if this issue is still evident which it probably is as nothing been doing regarding F# for a while.

It's like TextScreenBase is part of a standard User project in C#, but for some reason with F# it's in the HAL ring?

**Comment by fanoI** [comment]
IMHO is a problem of F#... the problem has became worse with Net Core as Microsoft has no VS tooling support for F#.
In theory it should be added to VS 15.5...

**Comment by Arawn-Davies** [comment]
Hope it is, would be good to get it working, is there much point getting it to work with a VS15.0/15.1 install? I've got it on one of my Windows Server boxes with all Cosmos dependencies already installed (I built the latest userkit on it :P ) so I can see if there's anything I can do on our part, if not just wait until 15.5

**Comment by fanoI** [comment]
Last time I've tried I could not create a normal F# application using Net Core so if this is not fixed by Microsoft we cannot do nothing sadly...

**Comment by jp2masa** [comment]
I think it's working now, If not, please reopen the issue.
