### ISSUE TITLE
Possible string.Concat(string, string...) bug

### ISSUE THREAD

**Issue by TheCool1James** [CosmosOS/Cosmos#429]
I have a bug in my texteditor, where it would only save the first line of text I saved, even though all the lines were CLEARLY (through some `Kernel.PrintDebug()`) stored in the array and list. The text editor works by saving all the 80 chars of the line into a list, and then adding a new entry into the list when enter is pressed). When the user saves, the list is converted into an array, then the array is saved via `File.WriteAllLines()`, simple. I know the list->array conversion was sucessful (debug methods), but when I tried `File.WriteAllLines`, it failed to save properly. Through some digging, I tried the `string.concat` method found inside the cosmos source, and the concat only concated the first entry of the array (did that make sense?). So, only the first line/entry was saved.
*Note:* When I hardcoded a string array to be saved, it worked like a charm.
*Code:* [FileMan.cs](https://github.com/TheCool1James/LiquiDOS-Cosmos/blob/master/LiquiDOS/FileManager.cs#L98) (GitHub)

**Comment by jp2masa** [comment]
I tried `String.Concat("A", "\nB");` to test and it worked right so I think it's not the issue. Try debugging more precisely to see what is happening.

**Comment by TheCool1James** [comment]
Yea, when I hardcoded all the values, it worked. I tested this out on a normal console too, and it worked. I don't know what possibly could've gone wrong. Breakpoints show that the string isn't being concated. I could use a dirty array of chars though. I'm legit stumped rn :/

**Comment by TheCool1James** [comment]
My issue. Had 0x0 null terminator in my string
