### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Hetal728** [CosmosOS/Cosmos#43]
Is there a license currently for this project? If there is, please create a file (LICENSE.txt) with the license pasted in it.

**Comment by mterwoord** [comment]
During our migration process, we forgot to make a license file.
Feel free to make a pull request, copying the license info from CodePlex
Op 2 jan. 2015 21:51 schreef "Hetal728" <notifications@github.com>:

**Comment by Hetal728** [comment]
Ok
