### ISSUE TITLE
i have a problem whit plugs:system.RuntimeTypeHandle

### ISSUE THREAD

**Issue by AleksaS003** [CosmosOS/Cosmos#430]
When i want to compile my cosmos kernel i get error:
![capture](https://cloud.githubusercontent.com/assets/20742097/17545674/76cec340-5ede-11e6-9de5-8b95a0509049.PNG)
cosmos builder says;system.RuntimeTypeHandle
have somebody solution?

**Comment by jp2masa** [comment]
You are using a method which calls a native method that hasn't been plugged in Cosmos yet. Can you show more lines of the error?

**Comment by AleksaS003** [comment]
i programed this in VS2008 with milestone 4 but later i programed this agin in VS2015 and show error like kernel not found:
1>------ Build started: Project: pineapple 0S v1.0, Configuration: Debug Any CPU ------
1>  pineapple 0S v1.0 -> C:\Users\Aleksa\Desktop\moj os\pineapple 0S v1.0\pineapple 0S v1.0\bin\Debug\pineapple 0S v1.0.dll
2>------ Build started: Project: pineapple 0S v1.0Boot, Configuration: Debug x86 ------
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '.\pineapple 0S v1.0.0\pineapple 0S v1' does not exist.
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Aleksa\Desktop\moj os\pineapple 0S v1.0\pineapple 0S v1.0\bin\Debug\pineapple 0S v1.0Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Aleksa\Desktop\moj os\pineapple 0S v1.0\pineapple 0S v1.0\bin\Debug\pineapple 0S v1.0Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Aleksa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = 'C:\Users\Aleksa\Desktop\moj os\pineapple 0S v1.0\pineapple 0S v1.0\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Error: No Kernel found!
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.0790468
2>Done building project "pineapple 0S v1.0Boot.Cosmos" -- FAILED.
2>
Build has been canceled.

**Comment by mterwoord** [comment]
MS4 is ancient. You'll have to create a new kernel and port your code over.
