### ISSUE TITLE
[Question] Writing Plug using X# or X86?

### ISSUE THREAD

**Issue by Unknown6656** [CosmosOS/Cosmos#432]
Hello,
I am currently writing a plug for the internal method [`system::threading::thread::sleep(int)`](https://msdn.microsoft.com/en-us/library/d00bd51t(v=vs.110).aspx) and I have already a concept of this function in x86-Assembler:
```asm
DELAY PROC
TIMER:
MOV AH, 00H
INT     1AH
CMP     DX,WAIT_TIME
JB      TIMER
ADD     DX,3         ;1-18, where smaller is faster and 18 is close to 1 second
MOV     WAIT_TIME,DX
RET
DELAY ENDP
```
I am now translating it into C# to use it as plug in my test operating system.

**My question is:** Is it possible to write this plug directly in X# or in x86? And if so, how exactly do I configure my project?
_[The wiki article about plugs](https://github.com/CosmosOS/Cosmos/wiki/Intro-to-Plugs) only uses plugs written in C#._

**Comment by mterwoord** [comment]
The code you show uses BIOS calls, which is not possible with cosmos..

**Comment by Unknown6656** [comment]
@mterwoord : Hm... I of course can understand, why BIOS calls will be difficult/impossible to support, but I have a few questions then:

1. Do you know, how I could implement a "sleep" function? The OS somehow needs information about timespans, cpu cycles or other time-measuring information.
2. This "sleep"-plug, which I am writing, is one of the many functions, which RegEx does need in the .NET-Framework _(It is a nightmare writing this plug ^^)_.
Do plans exist about implementing Regex in the near future in Cosmos? _(I will be happy to contribute, if I can...)_

**Comment by mterwoord** [comment]
Regex needs sleep????

Besides that: implementing regex is planned, but not soon (contributions are welcome).

If you want more info on current state etc, feel free to join our gitter chat!

**Comment by Unknown6656** [comment]
@mterwoord : Yes, Regex does need sleep for the Timeout functions during initalization ....
``Hashtable.Item{get;set;} (used in MatchCollection) does also use Thread.Sleep (http://referencesource.microsoft.com/#mscorlib/system/collections/hashtable.cs,10fefb6e0ae510dd,references)

I will join the chat later and inform myself about the current state.
Thank you very much, for your help, Sir.

**Comment by Unknown6656** [comment]
I added basic time functions (see #434) and I am currently implementing the Stopwatch-class, meaning that Thread.Sleep could soon be implemented
