### ISSUE TITLE
Every new file is an Alias for one file?

### ISSUE THREAD

**Issue by yewmisgoat** [CosmosOS/Cosmos#433]
I'm having the strangest issue with the VFS... Every time I create a new file, it successfully creates a new "file." However, when I edit one file, all files are overwritten with the same edit. If I File.Create("0:\filea.txt") then File.WriteAllLines("0:\filea.txt", lines) //(lines is a string array) and then File.Create("0:\fileb.txt"), fileb.txt has the contents of filea.txt, and if I edit fileb.txt using File.WriteAllLines, filea.txt's contents are also overwritten.

**Comment by TheCool1James** [comment]
SAME ISSUE HERE! Even when I reboot, and the file has been READ by the OS, not written, the contents of the target file I wrote to gets written onto all the file's I've interacted with. Strangely, Root.txt and Kudzu.txt are not affected.

**Comment by charlesbetros** [comment]
Fixed in latest master.
