### ISSUE TITLE
x64 instructions

### ISSUE THREAD

**Issue by Hetal728** [CosmosOS/Cosmos#44]
x64 instructions would be a great enhancement, I could give it a shot if I figure out where/what I have to do.

**Comment by mterwoord** [comment]
At this point in the project, we don't want x64 support added. We only have limited resources (devs), and we want to focus on 1 platform (x86) for now.
Doesn't mean it's definitely planned though.

Maybe you're interested in helping us out?

**Comment by Hetal728** [comment]
I'm relatively new to OS programming, but not to .NET/C#, I could probably help out.

**Comment by mterwoord** [comment]
See our issues tab, there's some tasks there. For the rest, we're pretty much blocked on a few larger issues currently. If you're willing to dive in something bigger, feel free. #25 and #42 are up for taking, or otherwise #9....

**Comment by VortexIncAdmin** [comment]
Update: I think it supports x64 now.

**Comment by jp2masa** [comment]
We don't have x64 support, but x86 can run on x86_64 computers.

**Comment by jp2masa** [comment]
This issue was moved to CosmosOS/IL2CPU#14
