### ISSUE TITLE
Mouse is in Cosmos.HAL

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#441]
`1>------ Build started: Project: AOSBoot, Configuration: Debug x86 ------
1>  Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\AOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\DeciduOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
1>  Executing command line "C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\AOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\DeciduOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>  Working directory = 'C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\'
1>  Loaded : DebugEnabled
1>  Loaded : StackCorruptionDetectionEnabled
1>  Loaded : DebugMode
1>  Loaded : StackCorruptionDetectionLevel
1>  Loaded : TraceAssemblies
1>  Loaded : DebugCom
1>  Loaded : UseNAsm
1>  Loaded : OutputFilename
1>  Loaded : EnableLogging
1>  Loaded : EmitDebugSymbols
1>  Loaded : IgnoreDebugStubAttribute
1>  Loaded : References
1>  Executing IL2CPU on assembly
1>  Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>  Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>  Detecting fields for type 'Cosmos.Debug.Common.MethodIlOp'
1>  Rings: Start check
1>  Rings: Assembly 'Cosmos.System'
1>  Rings:         Ring = System
1>  Rings:     Dependency 'Cosmos.HAL'
1>  Rings:         Ring = HAL
1>  Rings: Assembly 'DeciduOS'
1>  Rings:         Ring = User
1>  Rings:     Dependency 'Cosmos.System'
1>  Rings:         Ring = System
1>  Rings:     Dependency 'Hardware'
1>  Rings:         Ring = User
1>  Rings:     Dependency 'Cosmos.HAL'
1>  Rings:         Ring = HAL
1>  Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>  Detecting fields for type 'Cosmos.Debug.Common.Document'
1>  Detecting fields for type 'Cosmos.Debug.Common.Method'
1>  Error: Exception: System.Exception: Assembly 'DeciduOS' is in ring User(3). It references assembly 'Cosmos.HAL' which is in ring HAL(1), but this is not allowed!
1>     at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner, Assembly entryAssembly) in C:\Users\Ray6y\Documents\Cosmos\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 116
1>     at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Ray6y\Documents\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 254
1>  Loaded assemblies: 
1>  C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>  C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\DeciduOS.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Memory.dll
1>  C:\Users\Ray6y\Documents\Visual Studio 2015\Projects\AOS\AOS\bin\Debug\Hardware.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Microsoft.Samples.Debugging.CorApi.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
1>  C:\Users\Ray6y\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.TestRunner.TestController.dll
1>  Errorred
1>  IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>  IL2CPU task took 00:00:06.5383831
1>Done building project "AOSBoot.Cosmos" -- FAILED.
1>
Build has been canceled.`

**Comment by jp2masa** [comment]
You need to delete the reference to Cosmos.HAL from your project with the Kernel.cs

**Comment by Project-Magenta** [comment]
OK.

**Comment by Project-Magenta** [comment]
Offending line is `
 public static Mouse m = new Mouse();`

**Comment by jp2masa** [comment]
Create a class in the project in ring System and do the mouse drawing things there. Then call some method (something like DrawMouse) from the main project

**Comment by Project-Magenta** [comment]
I'll try that.

**Comment by Project-Magenta** [comment]
When I do that, the sreen is black and nothing appears.

**Comment by jp2masa** [comment]
What code are you using to draw the mouse?

**Comment by Project-Magenta** [comment]
Code in the wiki

**Comment by jp2masa** [comment]
Are you calling the mouse drawing method from Run() in your Kernel?

**Comment by Project-Magenta** [comment]
I'm doing it from BeforeRun().

**Comment by jp2masa** [comment]
BeforeRun() only runs once. Run() is always running so you need to draw the mouse inside Run()

**Comment by Project-Magenta** [comment]
But I have an infinite loop in Run() with a bunch of stuff.

**Comment by jp2masa** [comment]
The last line in Run() should be the mouse drawing method call

**Comment by Project-Magenta** [comment]
Ok.

**Comment by Project-Magenta** [comment]
not working.

**Comment by Project-Magenta** [comment]
Nothing is happening

**Comment by Project-Magenta** [comment]
I can't tell. wait till #447 is resolved.

**Comment by cjhannah** [comment]
Did you initialize the mouse?

**Comment by Project-Magenta** [comment]
Yes.

**Comment by Project-Magenta** [comment]
I get a blank screen

**Comment by Project-Magenta** [comment]
Hello?

**Comment by jp2masa** [comment]
When CGS is merged, graphics will be easier to use and faster, so you should wait.

**Comment by APERSONA32** [comment]
im using Fanol's branch and it says CGS is working   how would I go about using it?

**Comment by jp2masa** [comment]
It's still not very fast, but it works, see the test kernel made by @fanoI : https://github.com/fanoI/Cosmos/blob/master/Tests/GraphicTest/Kernel.cs

**Comment by APERSONA32** [comment]
I have been trying that but I cant seem to get anything working. It just pauses the continues the console.

**Comment by APERSONA32** [comment]
Sorry  ignore me   it works fine.  Just not in virtual box. Is there anyway to get it working in virtual box?

**Comment by jp2masa** [comment]
The driver is for Bochs, but it is supported by Virtual Box, so it should work.

**Comment by APERSONA32** [comment]
oh. well I couldn't get it to work

it paused for a second but remains on the Command Line

**Comment by fanoI** [comment]
@APERSONA32 can you open a separate issue for the fact that CGS does not works in Virtual Box? I've not tried it personally but in theory Virtual Box (and Qemu) should have used the same virtual GPU.
