### ISSUE TITLE
How much of internet is implemented and can I use it?

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#443]

**Comment by jp2masa** [comment]
I think internet was already implemented but it doesn't work right now

**Comment by fanoI** [comment]
I there are no network card drivers in Cosmos and any case all the TCP/IP stack is not yet implemented.

**Comment by LegitSoulja** [comment]
@fanol hm, should we/I start working on this? 

Me and @zarol will be working on a widget framework, in which Windows will be implemted. A console, could be implemented aswell.

Also have a package manage similar to apt-get/yum.

What does the future of Cosmos look like? Let's invent. We need to start making priority todo lists and get to working.

**Comment by zarlo** [comment]
https://www.gocosmos.org/roadmaps/ it more or less a priority todo list

**Comment by Project-Magenta** [comment]
@LegitSoulja actually, it's not uppercase because you are working on *windows* and not the operating system Windows.

**Comment by Project-Magenta** [comment]
:)
