### ISSUE TITLE
Strange error that freezes OS on user input (Console)

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#447]
Severity	Code	Description	Project	File	Line	Suppression State
Error		17 [main] objdump 6344 tty_list::allocate: No tty allocated	AOSBoot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	40

**Comment by fanoI** [comment]
Really strange indeed! Do you have done something different from the usual kernel setup? Maybe are you trying to compile in release mode?

**Comment by charlesbetros** [comment]
This was an issue in older versions. It should be fixed in trunk.

**Comment by Project-Magenta** [comment]
Trunk?

**Comment by charlesbetros** [comment]
Fixed in latest master.
