### ISSUE TITLE
PXE booting does not work!

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#449]
![](http://i64.tinypic.com/11ghrfc.png)

**Comment by jp2masa** [comment]
Do you see the Cosmos PXE GUI before that error or it comes right after compiling?

**Comment by Project-Magenta** [comment]
The PXE gui comes aftr the error

**Comment by jp2masa** [comment]
You can ignore that error as it's not a PXE error, it's a Debug Engine error.

**Comment by Project-Magenta** [comment]
It doesn't work though. VMWare's VM is set to Bridged.

**Comment by jp2masa** [comment]
I think you need to open some firewall ports. I don't know what ports are needed, try searching on google.

**Comment by jp2masa** [comment]
To allow ports, you need to change Firewall settings. Search on google for it and read carefully, because it can cause security issues if you change the settings in a wrong way.

**Comment by Project-Magenta** [comment]
What ports?

**Comment by jp2masa** [comment]
You need to disable firewall on UDP ports 67, 69 and 4011, I think. Maybe port 68 too.

**Comment by Project-Magenta** [comment]
there is a rule called cosmos.deploy.pixie.exe that allows all ports.

**Comment by jp2masa** [comment]
Try disabling Remote Debugging. If it doesn't work try following this video I found: https://www.youtube.com/watch?v=kXwlg-NN8NI

**Comment by namitjuyal** [comment]
I am too getting this issue. That youtube video does not seem to be of any help. Can anyone help?

**Comment by jp2masa** [comment]
If the problem is the same as the screenshot in the question, just ignore the message.

**Comment by namitjuyal** [comment]
Is there a sample for remote network boot hardware and not VMs?

**Comment by jp2masa** [comment]
For remote I think you just need to use the IP for the local network where the other computer is connected.

**Comment by namitjuyal** [comment]
So where do I have to use  the remote client  IP  once the PXE is up?

**Comment by jp2masa** [comment]
What IP are you using in the Cosmos project settings? 0.0.0.0, 127.0.0., a local network IP or the "global" IP?

**Comment by namitjuyal** [comment]
The default hardcoded one 192.168.42.1

**Comment by jp2masa** [comment]
Try using 0.0.0.0

**Comment by namitjuyal** [comment]
So that will be the PXE server IP but what about the client IP?

**Comment by jp2masa** [comment]
Are you trying it on vmware? It isn't being detected?

**Comment by namitjuyal** [comment]
No I am trying to boot a real hardware on network  which is a thin client box

**Comment by jp2masa** [comment]
Have you tried on vmware? If not try it there and when it works you can try with real hardware

**Comment by namitjuyal** [comment]
Ok will try.

**Comment by namitjuyal** [comment]
So I was able to boot VM.  Please let me know how can I boot the remote hardware?  Also is it possible to load windows image using cosmos pxe network boot?

**Comment by jp2masa** [comment]
It should be similar to the VM, what is failing? Also, Cosmos Pixie wasn't made for loading windows images, if you want that, there are many softwares that can do it.

**Comment by czhower** [comment]
Have you seen this video? It uses the PXE support.

https://www.youtube.com/watch?v=d_1Bup3TR_M
