### ISSUE TITLE
Error/Question

### ISSUE THREAD

**Issue by Hetal728** [CosmosOS/Cosmos#45]
Error	25	Requested value 'None' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at Cosmos.Build.MSBuild.IL2CPUTask.Initialize() in g:\IL2CPU\source2\Build\Cosmos.Build.MSBuild\IL2CPUTask.cs:line 158
   at Cosmos.Build.MSBuild.IL2CPUTask.Execute() in g:\IL2CPU\source2\Build\Cosmos.Build.MSBuild\IL2CPUTask.cs:line 189	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	6	Test

Is there any way I can figure out where this error is located or fix this error?

**Comment by mterwoord** [comment]
What Cosmos version do you have installed?

**Comment by Hetal728** [comment]
It was the latest user kit available at 6/15/14 from CodePlex, which if I remember correctly did not include your reference fixes from February.

**Comment by mterwoord** [comment]
Are you able to run devkit? If so, please try that one...

**Comment by Hetal728** [comment]
I was able to install the Dev Kit, now I get the error "Error occurred while invoking IL2CPU"

**Comment by mterwoord** [comment]
No details?

**Comment by Hetal728** [comment]
Error	2	Error occurred while invoking IL2CPU.	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	6	GalaxyBoot

**Comment by mterwoord** [comment]
Yes, but no other errors before that? Also, look on the output pane, sometimes over there, theres more info.

**Comment by Hetal728** [comment]
There are no other errors before that, the output pane only shows when the IL2CPU started and how long the task took.

**Comment by mterwoord** [comment]
Then I guess there are some issues with capturing the IL2CPU.exe output into msbuild. Have you ever done output capturing and msbuild tasks?
If so, please try to fix it..  (I know, this blows, but it will let you get going with the project.)

The task is in IL2CPU.cs (Cosmos.sln, then Build\Cosmos.Build.MSBuild project)

**Comment by Hetal728** [comment]
I have no experience doing so, I can try.

**Comment by mterwoord** [comment]
Remember, when you want to test it, you have to run install.bat each time..

**Comment by Hetal728** [comment]
The exit code is confirmed to be '2', which if it follows http://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx, then it means ERROR_FILE_NOT_FOUND.

**Comment by Hetal728** [comment]
I looked through the code some more, and figured out it just meant that IL2CPU.exe errored.

**Comment by Hetal728** [comment]
I'm on the verge of giving up, are there any alternative solutions?

**Comment by Hetal728** [comment]
I've downgraded to the current user kit on CodePlex as a temporary solution, I'll try to figure this out soon.
