### ISSUE TITLE
Method Cosmos.HAL.TextScreenBase not found/does not exist?

### ISSUE THREAD

**Issue by SqlAspens** [CosmosOS/Cosmos#451]
> 1>------ Build started: Project: Hardware, Configuration: Debug Any CPU ------
2>------ Build started: Project: AspensJabOSBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\AspensJabOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\AspensJabOS.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\AspensJabOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\AspensJabOS.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = 'C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Plug found: 'Cosmos.Core.CPU'
2>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Plug found: 'Cosmos.Core.IOPortBase'
2>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Plug found: 'System.Char'
2>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Plug found: 'System.Random'
2>	Plug found: 'System.Console'
2>	Plug found: 'System.Type'
2>	Plug found: 'System.Threading.Monitor'
2>	Plug found: 'System.Text.DecoderFallback'
2>	Plug found: 'System.Text.EncoderFallback'
2>	Plug found: 'System.Text.ASCIIEncoding'
2>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Error: Exception: System.MissingMethodException: Method not found: 'Void Cosmos.System.Console..ctor(Cosmos.HAL.TextScreenBase)'.
2>	   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
2>	   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
2>	   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
2>	   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
2>	   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILReader.cs:line 328
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 545
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Elite\Documents\Visual Studio 2015\Projects\AspensJabOS\AspensJabOS\bin\Debug\AspensJabOS.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Elite\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): warning MSB5021: "csc" and its child processes are being terminated in order to cancel the build.
Build has been canceled.

I get this error on build/debug. I have latest cosmos installed.

**Comment by jp2masa** [comment]
What project template are you using? VB, C# or F#?

**Comment by fanoI** [comment]
Have you found what part of your code generated the problem? If yes please post it here...

**Comment by SqlAspens** [comment]
I'm using Userkit and I have been struggling to find the offending code`

> http://pastebin.com/XT44AE37

**Comment by jp2masa** [comment]
Try commenting the ForegroundColor line and see if it compiles.

**Comment by SqlAspens** [comment]
I just commented `Console.ForegroundColor = ConsoleColor.Green;` out and it still  doesn't build (https://ghostbin.com/paste/mxvew)

**Comment by jp2masa** [comment]
Try reinstalling Cosmos. If it doesn't work, try the devkit, because many bugs are fixed there. If you don't want to install the devkit dependencies go to http://jp2masa.tk/downloads/CosmosUserKit-20160719-vs2015.zip and install that version. I compiled a minimally stable devkit version and it already has some FAT implementations.

**Comment by fanoI** [comment]
Yes please try the last devKit or the userKit @jp2masa posted maybe some issues will be resolved.
Looking at the code your kernel seems to use VGA right? I see too complex constructs in the code for example I'm unsure if System.Collections.Generic.IEnumerable is implemented in Cosmos...

**Comment by SqlAspens** [comment]
now I get this: https://ghostbin.com/paste/9ua56

**Comment by jp2masa** [comment]
Change your projects(except the one with Boot in the name) target framework to 4.5.2

**Comment by SqlAspens** [comment]
@jp2masa I just tried that, restarted visual studio and everything but it still thinks I am targeting 4.5? This is probably a problem with visual studio so I am closing this.
Thanks everyone <3

**Comment by charlesbetros** [comment]
There is a target version in the Cosmos Boot project as well. The easiest thing to do is create a new Cosmos project and copy your code to it. It should have the correct versions.
