### ISSUE TITLE
IL2CPU Could not be Loaded

### ISSUE THREAD

**Issue by Chay8** [CosmosOS/Cosmos#454]
Getting error 

The "Cosmos.Build.MSBuild.IL2CPU" task could not be loaded from the assembly

I made sure I had 3.5 and 4.5.2 installed, and I have all software installed that is required.

**Comment by jp2masa** [comment]
Are you using userkit or devkit?

**Comment by Chay8** [comment]
I get the error with both of them.

**Comment by jp2masa** [comment]
Try to reboot and if it doesn't work try to reinstall Cosmos.

**Comment by j4cobgarby** [comment]
I have the same problem - none of these suggestions helped.

**Comment by jp2masa** [comment]
Can you post the output log?

**Comment by Rammelkast** [comment]
I'm having this issue too.
 The "Cosmos.Build.MSBuild.IL2CPU" task could not be loaded from the assembly

**Comment by Rammelkast** [comment]
Tried to reinstall, userkit and devkit, installed on different locations, no difference.

**Comment by jp2masa** [comment]
Can you paste the output log of the project build?
