### ISSUE TITLE
My boot project doesn't want to compile

### ISSUE THREAD

**Issue by mihail-rotmg** [CosmosOS/Cosmos#455]
3>------ Rebuild All started: Project: MihailBoot, Configuration: Debug x86 ------
3>Project skipped, as it's not necessary for running
This are my projects
http://imgur.com/a/wt5tY

**Comment by jp2masa** [comment]
Right click the solution, go to Configuration Manager and select MihailBoot project as active(a checkbox)

**Comment by mihail-rotmg** [comment]
Thank you for your fast answer but i solved this issue by changing my MihailBoot as my startup project.

**Comment by charlesbetros** [comment]
You can also accomplish this by tight click on the Boot project and selecting 'Set as startup project'.
