### ISSUE TITLE
Any programming language interpreter that works in COSMOS Filesystem

### ISSUE THREAD

**Issue by mihail-rotmg** [CosmosOS/Cosmos#457]
I have to ask if any interpreter works for Cosmos.
I have found LUA and Basic interpreters but i am not sure if they work.
Now i am testing Moonsharp (Lua) interpreter.

If they dosen't work i should make my own interpreter.

**Comment by jp2masa** [comment]
Filesystem functionality isn't still complete and has some bugs, but you can try to use interpreters in Cosmos. Interfaces don't work totally, so you can have trouble using external libraries

**Comment by mihail-rotmg** [comment]
I won't even try to use external libraries.
