### ISSUE TITLE
Is there any good display driver?

### ISSUE THREAD

**Issue by mihail-rotmg** [CosmosOS/Cosmos#461]
My display driver (taken from Basic OS) has 6.7 FPS average (from 6-7 but it is 7 more often).
When i move around with the mouse i get 6 FPS average (from 5-7 FPS).
I only draw the name of the operating system, background with static color and the mouse.
I tried removing them all and i got the same results (6.7 FPS)
Also debugging is off and i use VMware Workstation 12.

This is the code i draw:
```
            while (Running)
            {
                display.fillArea(0, 0, 320, 200, 5);
                FontRenderer Text = new FontRenderer(display, BasicPixelated);
                Text.renderString(10, 10, "MihailOS".ToUpper());
                FPSData = FPS.Draw(FPSData[0], FPSData[1], FPSData[2]);
                Text.renderString(300, 2, FPSData[2].ToString());
                if (mouse.isAnyClicked()) { display.clear(); };
                mr.renderMouse();
                display.step();
            }
```

And this is my FPS Counter Code:
```
using MihailOS.Hardware;

namespace MihailOS.GSYS.Functions
{
    public static class FPS
    {
        internal static int[] Draw(int Frames, int TimeLast, int FramesOut)
        {
            int[] data = new int[3];
            if (TimeLast != Time.Second())
            {
                FramesOut = Frames;
                Frames = 0;
            }
            TimeLast = Time.Second();
            Frames++;
            data[0] = Frames;
            data[1] = TimeLast;
            data[2] = FramesOut;
            return data;
        }
    }
}

```

And this are the drivers:
http://pastebin.com/avRNwAwS
http://pastebin.com/aXa0rhyK

Is there any way i that i can improve?

**Comment by jp2masa** [comment]
As far as I know the driver is going to be updated and it will be a fast driver for sure, but I think it's not a priority so you will have to wait

**Comment by mihail-rotmg** [comment]
Ok, i will wait :)

**Comment by fanoI** [comment]
Are you using the VGA driver right? Looking at the source our VBE driver could work only on Bochs (it is not really a VBE driver but a strange kludge implemented by the Bochs team) and you are using VmWare so I think yes...

**Comment by Cyber4** [comment]
VBE is much faster to VGA due to a bug (or something) relating to terrible speeds using delegates.  It's a really easy fix if you want to get your hands dirty in the devkit code but honestly i'm very, very surprised this hasn't been changed by now since it was brought up _ages_ ago and it's not a difficult fix at all, I just don't think it's ever been merged.

**Comment by charlesbetros** [comment]
This is more a question than an issue. Closing the issue, but head over to our Gitter chat if you have other questions.
