### ISSUE TITLE
How to work with ACPI and shut a computer down?

### ISSUE THREAD

**Issue by ArtyomIsFlash** [CosmosOS/Cosmos#462]
Previously, there was a nice function named `Cosmos.Sys.Deboot.ShutDown();`, but now it's gone. All I found is `Cosmos.System.Power.Reboot();` and `Cosmos.HAL.Power.Reboot();`. I couldn't find any function to turn off the computer. Could you please help me? My C# level is intermediate, so I'm afraid I can't contribute to Cosmos.

**Comment by jp2masa** [comment]
If you want you can implement ACPI, there's an implenentation somewhere and if you want I can give you the link. If you don't want to implement ACPI you can just use Stop function in your Kernel and shutdown manually

**Comment by jp2masa** [comment]
ACPI: https://files.gitter.im/CosmosOS/Cosmos/v8bF/ACPI.cs

**Comment by cjhannah** [comment]
Thanks!

**Comment by jp2masa** [comment]
Cosmos will have an ACPI implementation soon(#542) and this issue is a bit old.

**Comment by mirman-coyoushaei2021** [comment]
Where do I put the ACPI.cs file

**Comment by valentinbreiz** [comment]
ACPI is already implemented in Cosmos.

**Comment by mirman-coyoushaei2021** [comment]
thank you

**Comment by fanoI** [comment]
You simple have to call:  Cosmos.System.Power.Shutdown();

**Comment by mirman-coyoushaei2021** [comment]
thanks
