### ISSUE TITLE
After update it crashes on input, and Graphics doesn't even load

### ISSUE THREAD

**Issue by mihail-rotmg** [CosmosOS/Cosmos#465]
I updated to the newest version

**Comment by cjhannah** [comment]
more info please

**Comment by mihail-rotmg** [comment]
Well i updated to the newest devkit.
I would get errors when i boot.
Then i tried updating again and now it is 100% broken, it doesn't even boot correctly.

**Comment by cjhannah** [comment]
Weird. I'm having the same issue.

**Comment by mihail-rotmg** [comment]
Soo... any fixes?

**Comment by cjhannah** [comment]
downgrading should work.

**Comment by mihail-rotmg** [comment]
Nope i downgraded it got worse :(

**Comment by charlesbetros** [comment]
Fixed in latest master.
