### ISSUE TITLE
CPU Exception 0x6 upon trying to type

### ISSUE THREAD

**Issue by cjhannah** [CosmosOS/Cosmos#467]
Trying to type in VMWARE causes a cpu exception 0x6 at a random address beginning with 0x2 I believe.
Trying to type in QEMU just doesn't do anything.
If this could be fixed, I would love it. I'm using the DevKit.

**Comment by cjhannah** [comment]
seems to be exactly like #357

**Comment by mihail-rotmg** [comment]
Same as my problem. After update, everything has gone to shit.

**Comment by fanoI** [comment]
This the same of https://github.com/CosmosOS/Cosmos/issues/465.
Issue https://github.com/CosmosOS/Cosmos/issues/357 was effectively fixed as I've done some test with kernel with VB.Net some week ago and surely they worked. 
I think the problem should be different in this case probably something related with the work done in the RAT branch.

**Comment by fanoI** [comment]
This two ASM files are two copies of the Guess demo one compiled inside the kernel (and it works) the other as separated kernel obtained installing the userKit:
[TwoGuess.zip](https://github.com/CosmosOS/Cosmos/files/477750/TwoGuess.zip)

**Comment by charlesbetros** [comment]
Fixed in latest master.
