### ISSUE TITLE
Using Random.Next causes a Invalid Opcode error

### ISSUE THREAD

**Issue by cjhannah** [CosmosOS/Cosmos#468]
How to Reproduce:
Use Random.Next in your code
It should crash with a Invalid Opcode
Workaround:
Use a alternative RNG (SimpleRNG)
initializing random works, it's just Random.Next

**Comment by Unknown6656** [comment]
I'll just post my changements to the `RandomImpl`-class:
https://github.com/Unknown6656/Cosmos/blob/79960b4dfa0be44c2f354f44137eed46c19da6aa/source/Cosmos.System.Plugs/System/RandomImpl.cs

And a test kernel:
https://github.com/Unknown6656/Cosmos/blob/79960b4dfa0be44c2f354f44137eed46c19da6aa/source/Cosmos.Kernel.Tests.System/Kernel.cs
