### ISSUE TITLE
Using Windows Driver Kit makes Boot Properties undisplayable

### ISSUE THREAD

**Issue by cjhannah** [CosmosOS/Cosmos#469]
You will get an error message if you have the Windows Driver Kit installed and try to edit Boot Properties, basically making Cosmos unusable.

**Comment by fanoI** [comment]
But what is Windows Driver Kit?

**Comment by cjhannah** [comment]
It's a kit from Microsoft for developing kernel-level or user-mode drivers.

**Comment by fanoI** [comment]
Hmm so it seems we have a conflict with another Visual Studio extension!
What is the error?

**Comment by cjhannah** [comment]
In RegexReplace it screws up with Debug|AllCpu or something like that. If you google it, it's happened with other projects too

**Comment by fanoI** [comment]
I'm asking myself at this point if it is a problem of this Visual Studio Extension and so they should solve the problem...

**Comment by lcnvdl** [comment]
I'm having the same problem. Is there any solution ?

**Comment by fanoI** [comment]
@cjhannah with give me the link to google in which this happened to other projects too?

This the WDF github: https://github.com/Microsoft/Windows-driver-frameworks and if it is their bug is there that the issue should be opened but first we must be sure that is not some our weird problem.

**Comment by jp2masa** [comment]
We'll be moving to CPS soon, and this bug seems to be fixed anyway, so I'm closing this.
