### ISSUE TITLE
Where is the System.IO code?

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#474]
I've checked and all I got was: abstract classes and (totally) irrelevant files.

**Comment by jp2masa** [comment]
System.IO is plugged to call methods from Cosmos.System.FileSystem

**Comment by Project-Magenta** [comment]
OK, then I look there?

**Comment by Project-Magenta** [comment]
Where's the code... not there

**Comment by Cyber4** [comment]
You should be able to use System.IO though the code for it is not located in those direct files but rather the plug location.  If you want to view the source, you'd have to view the source code of the plugs.  if you want to call the methods you would just call the System.IO stuff normally and it _should_ work.

**Comment by fanoI** [comment]
It is here: https://github.com/CosmosOS/Cosmos/tree/master/source/Cosmos.System.Plugs/System/IO

Github as a way to do search that works pretty well I simple searched something as IO and here it comes!
