### ISSUE TITLE
Environment.NewLine error???

### ISSUE THREAD

**Issue by zarlo** [CosmosOS/Cosmos#479]
string.Replace(Environment.NewLine, ";");

does not work

**Comment by cjhannah** [comment]
probably undefined. just set it as \n

**Comment by zarlo** [comment]
it worked pre RAT

**Comment by fanoI** [comment]
What is the value Environment.NewLine if printed as hex? I think should be possible using Debugger's SendInternal method. Let's start finding what Environment.NewLine really is (I fear it is the satanic 0x00 character) it could be "\r\n" (0x09 0x0A) or simply "\n" (0x0A).

**Comment by DjAlEx234** [comment]
If this does not have a GUI just add a new `Console.WriteLine("");`
(Also why is this still open)

**Comment by zarlo** [comment]
it will be closed when its fixed so in a day or 2 when i have the time

**Comment by fanoI** [comment]
In the end this issue has been fixed changing something else right?
Do you confirm that now is working?

**Comment by zarlo** [comment]
issue has been fixed
