### ISSUE TITLE
Bug in BCL Object tests, probably with type cast

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#482]
The ObjectTests in BCL test fail because of a stack corruption at an address that points to an Stloc IL opcode, I investigated a bit further and it seems related to the cast on: `return (MyType)MemberwiseClone();`. Changing to `return MemberwiseClone() as MyType;` fails with stack corruption too, but iirc the address points to a different IL opcode.

**Comment by charlesbetros** [comment]
MemberwiseClone will fail right now no matter what. It returns 4 bytes instead of 8 bytes for an object reference.
