### ISSUE TITLE
Double type bug

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#483]
The following code in Double tests is failing, I don't know if it was before RAT, but it's now. I didn't investigate it, so I can't provide more details other than instead of returning "NaN" the ToString() is returning "0".
```
value = Double.NaN;

result = value.ToString();
expectedResult = "NaN";

Assert.IsTrue((result == expectedResult), "Double.ToString of -NaN doesn't work");
```

**Comment by fanoI** [comment]
Fixed by https://github.com/CosmosOS/Cosmos/commit/a27790036932398080d7725a1d9a73f6d71e742d
