### ISSUE TITLE
Error Occured While Invoking IL2CPU

### ISSUE THREAD

**Issue by CrispySteven** [CosmosOS/Cosmos#484]
I've just installed Cosmos user kit and I'm trying to make an ISO, but I keep getting this error. I haven't changed anything yet.  I've installed .NET 3.5 like others have suggested, but to no avail. Does anyone know why this is happening? The output is: 

1>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Release\CosmosKernel1.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Release\CosmosKernel1.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
1>	Working directory = 'C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Plug found: 'System.RuntimeType'
1>	Plug found: 'System.OutOfMemoryException'
1>	Plug found: 'System.Double'
1>	Plug found: 'System.Delegate'
1>	Plug found: 'System.Array'
1>	Plug found: 'System.Buffer'
1>	Plug found: 'System.Enum'
1>	Plug found: 'System.EventHandler'
1>	Plug found: 'System.Exception'
1>	Plug found: 'System.MulticastDelegate'
1>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
1>	Plug found: 'System.Math'
1>	Plug found: 'System.String'
1>	Plug found: 'System.Diagnostics.Debugger'
1>	Plug found: 'System.Byte'
1>	Plug found: 'System.Environment'
1>	Plug found: 'System.GC'
1>	Plug found: 'System.Int16'
1>	Plug found: 'System.Int32'
1>	Plug found: 'System.Int64'
1>	Plug found: 'System.IntPtr'
1>	Plug found: 'System.Number'
1>	Plug found: 'System.Object'
1>	Plug found: 'System.Single'
1>	Plug found: 'System.SR'
1>	Plug found: 'System.UInt16'
1>	Plug found: 'System.UInt32'
1>	Plug found: 'System.UInt64'
1>	Plug found: 'System.Threading.Interlocked'
1>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
1>	Plug found: 'System.Resources.ResourceManager'
1>	Plug found: 'System.Net.IPAddress'
1>	Plug found: 'System.Net.SocketAddress'
1>	Plug found: 'System.Globalization.NumberFormatInfo'
1>	Plug found: 'System.Drawing.Color'
1>	Plug found: 'System.Drawing.SR'
1>	Plug found: 'System.Security.CodeAccessSecurityEngine'
1>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
1>	Plug found: 'System.RuntimeTypeHandle'
1>	Plug found: 'System.SByte'
1>	Plug found: 'System.UIntPtr'
1>	Plug found: 'System.Security.Cryptography.Utils'
1>	Plug found: 'System.Globalization.CultureInfo'
1>	Plug found: 'Microsoft.Win32.RegistryKey'
1>	Plug found: 'Cosmos.Core.CPU'
1>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
1>	Plug found: 'Cosmos.Core.IOPortBase'
1>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
1>	Plug found: 'System.Char'
1>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
1>	Plug found: 'System.Random'
1>	Plug found: 'System.Console'
1>	Plug found: 'System.Type'
1>	Plug found: 'System.Threading.Monitor'
1>	Plug found: 'System.Text.DecoderFallback'
1>	Plug found: 'System.Text.EncoderFallback'
1>	Plug found: 'System.Text.ASCIIEncoding'
1>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Common.MethodIlOp'
1>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Common.Document'
1>	Detecting fields for type 'Cosmos.Debug.Common.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 512
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Steven\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Release\CosmosKernel1.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Steven\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by jp2masa** [comment]
Try using the devkit, it has many bug fixes, but if you are using graphics, they will be slower.

**Comment by CrispySteven** [comment]
I just tried installing the dev kit and it says I don't have VMware or Bochs even though I do.  What's the problem?

**Comment by jp2masa** [comment]
You have bochs or vmware and what version?

**Comment by CrispySteven** [comment]
I reinstalled and the dev kit installation went through, but I still can't make an iso because of the same error.

**Comment by jp2masa** [comment]
Is it the exact same error? Did you install devkit from current master?

**Comment by zarlo** [comment]
was the project made with a user kit

**Comment by CrispySteven** [comment]
Thanks guys, I just restarted everything and it worked. I don't know why though.
