### ISSUE TITLE
IL2CPU Error 

### ISSUE THREAD

**Issue by alexpham095** [CosmosOS/Cosmos#485]
I cannot seem to figure out how to resolve this. I am trying to release it to run it on VirtualBox. However, i get this error IL2CPU. I have .net framework 3.5 and i tried to download 4.5.2, but it says I have a higher version already. I can't seem to download the dev kit because VMware isn't found, even though i do have VMware. 

This is my output: http://pastebin.com/KGN8BTRK

Thank you

**Comment by alexpham095** [comment]
Also, tried rebooting, closing and opening virtual studios, nothing seemed to work

**Comment by jp2masa** [comment]
Do you have a Kernek class that inherits from Cosmos.System.Kernel? The default project works?

**Comment by alexpham095** [comment]
I am only trying to run the default code. From the template. 

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }

        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}

**Comment by jp2masa** [comment]
You need to select .net framework 4.5 not 4.5.2 in your Cosmos non-Boot projects.

**Comment by alexpham095** [comment]
You mean if I go into properties and change the target framework to 4.5.2? I'm not sure what you mean by Cosmos non-Boot projects

**Comment by jp2masa** [comment]
Every project you have except the one with Boot in the name

**Comment by jp2masa** [comment]
Probably you only have one, the original, but later you will probably create new projects. Also, the devkit needs eveything in .net 4.5.2 so you will need to manually edit the Boot project file to change 4.5 to 4.5.2 in case you start using the devkit. Later it will be .net core, but for now devkit is 4.5.2

**Comment by alexpham095** [comment]
Sorry, I'm still getting the error after changing it to 4.5.

**Comment by jp2masa** [comment]
The exact same error?

**Comment by alexpham095** [comment]
The IL2CPU error, yeah. The output window looks the same as far as I can tell

**Comment by jp2masa** [comment]
including this: "The primary reference "C:\Users\AlexTPham\documents\visual studio 2015\Projects\CosmosKernel1\CosmosKernel1\bin\Release\CosmosKernel1.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5"." ?

**Comment by alexpham095** [comment]
http://pastebin.com/YPQT43kg I believe its still there

**Comment by alexpham095** [comment]
not too sure though

**Comment by jp2masa** [comment]
Reinstall the userkit or move definitely to devkit, but as you are having errors better reinstall userkit

**Comment by alexpham095** [comment]
I tried to do the dev kit and i got it to finish after installing Boch. However, I did not really understand what to do after... So i'm just going to reinstall the userkit

**Comment by jp2masa** [comment]
if you could install the devkit, don't downgrade to userkit... you just need to change the project version to 4.5.2

**Comment by alexpham095** [comment]
Right, I was just confused on what to do. In terms of creating the sample code and a boot... ?

**Comment by alexpham095** [comment]
Sorry, completely new to Cosmos, just a little flustered.

**Comment by jp2masa** [comment]
If you are starting now, just create a new project, else you would need to change the .net version in your project

**Comment by alexpham095** [comment]
So I had already finished installing the dev kit, it opened visual studios. I created a new project and sleected Cosmos, C#. Tried to compile on both 4.5 and 4.5.2 and could not compile still. However, the error is different on 4.5.2    http://pastebin.com/Hn2TuEnF

**Comment by jp2masa** [comment]
you need to select 4.5.2 in the devkit, try to reinstall it

**Comment by alexpham095** [comment]
I ended up instead of putting it in ISO i put it as VMware and it ended up compiling. One of my friends said it could be that it cannot compile ...  var input = . .... So if you change it to string, then it would compile. 

Thank you for helping me @jp2masa. Helped me way too much.
