### ISSUE TITLE
when is the next version and can you make it easyer to make a gui

### ISSUE THREAD

**Issue by bluethefoxyt** [CosmosOS/Cosmos#488]
when is the next version is been 1year since the prevrous release and can you make iteasyer to make a gui like cosmos.gui.start(); cosmos.gui.create(X,Y,roundrect,etc) or something better then my discription

**Comment by jp2masa** [comment]
The next version is probably before the end of this year. Also, it's not supposed to have an easy gui maker, you need to write a graphics library or try to port one.

**Comment by MichaelTheShifter** [comment]
Like @jp2masa said, if it were that easy to do, and it could be done for
every make and model of graphics card and every graphics standard (VGA,
SVGA, VBE etc), I think it would have either been done in the kernel
already or a better tutorial would have been made to utilize the standard.

But unfortunately how you talk with VBE isn't necessarily how you talk with
VGA - and it's the same with how they talk to you. Likewise, how you talk
to an NVidia GeForce GT 720 or an RX 480 may not be the same as how you
talk with intel HD graphics.

**Comment by fanoI** [comment]
I have started to work on a Graphic Manager that will permit in a more simple way to create a graphic toolkit that will have primitives to draw points, lines, rectangles not how to create Menu or Messagebox!) and unified user interface for the actual implemented drivers (VGA and VBE).

The actual VBE driver is an "hack" that works only with Bochs a proper VBE driver will support all GPUs (well the ones produced after year 2000) not expect to have 4K resolution but at least 1280x1024@32bit will be possible.

A last thing the UserKit is so old that probably we should not counsel to use it anymore please use the devKit.

**Comment by cjhannah** [comment]
i have a good gfx library. currently contaisn a drawstring function, rectangle, line, fill square, square, fill rectangle, primitive BitBlt, windows and buttons. ask me if you want it :)

**Comment by DjAlEx234** [comment]
I want it plz

**Comment by GabrielTK** [comment]
Me too :D

**Comment by fido2020** [comment]
The VBE Driver doesen't only work in bochs it also works in vitualbox but only if the kernel is on a hard disk image
