### ISSUE TITLE
A Cosmos Discord?

### ISSUE THREAD

**Issue by MichaelTheShifter** [CosmosOS/Cosmos#489]
Hmmmm. So this is odd. Gitter is down for me and I've talked with other people and it seems it's down for them too. Of course, I'm talking at the time of writing this - don't know how long it'll be down...

Anyways it seems that no matter where you go on Gitter you get the same page - a 414 error from 'fail.gitter.im' (request URI too large), and I can see in the address bar that I got sent back a 502 error. Using cloudflare for a year when one of my servers goes offline I get a 502 - Gitter's server is down.

This is evident - I tried pinging them in CMD... all four responses timed out.

![image](https://cloud.githubusercontent.com/assets/18349904/19599067/80942e94-976c-11e6-8dd9-4f0513a50ad8.png)

So for the time being it seems all of gitter is down which means you can't go to the Cosmos chat. So what about making another? Personally, I like Discord - it's sorta like Gitter (in fact I notice that Slack, Gitter and Discord share very similar UIs). Markdown is supported in the chat, heck you could even recreate the Activity pane with a Discord bot that connects with octokit.

That and voice channels are a thing, so if people wanted to talk through voice they can. Just a thought.

Also please don't get angry about me posting this as an issue. There is no other way to talk with other Cosmos users and devs right now as far as I'm aware.

Oh yeah and one more thing you can set up channels that are dev-only on Discord, though I've never done it in gitter so no idea if you can or not.

**Comment by mterwoord** [comment]
don't use ping for evidence that the host is down: Many server are configured not to respond to ping..

**Comment by MichaelTheShifter** [comment]
...And it's back up. Ohhhh Gitter....

**Comment by cjhannah** [comment]
Yes, Discord would be great

**Comment by mterwoord** [comment]
We dont want another official channel....

**Comment by cjhannah** [comment]
Seems fair.

**Comment by DjAlEx234** [comment]
Shouldn't this issue be closed?

**Comment by charlesbetros** [comment]
I'm betting my toaster and/or refridgerator brought down Gitter. :) We have had multiple places (mailing list, irc, codeplex issues) for communication in the past and it is difficult (for me at least) to be available on all of them. Besides, Gitter works great, and we have a good community building up around the project.
