### ISSUE TITLE
just cloned and ran install.bat - run into errors

### ISSUE THREAD

**Issue by jack-gift** [CosmosOS/Cosmos#49]
the error msg is below.
 Looks like .iss list files in source\IL2CPU\bin\debug\*.dll, but there's no files there.. Is it because these files are moved to somewhere else in the project?

Can someone try clone and install to reproduce, and then fix the issue? Thanks.

==============
Creating Setup
==============

Starting: C:\Program Files (x86)\Inno Setup 5\ISCC.exe
  Params: /Q "C:\Cosmos\Cosmos\Setup\Current.iss" /dBuildConfiguration=DevKit
Error on line 161 in C:\Cosmos\Cosmos\Setup\Current.iss: No files found matching "C:\Cosmos\Cosmos\.\source\IL2CPU\bin\Debug\*.dll"
Compile aborted.

**Comment by mterwoord** [comment]
Just did a commit. Recent changes in the project hadn't been reflected in the setup script. Thanks for reporting!
Please let me know if this solved the issue (and if so, please close this issue..)

**Comment by jack-gift** [comment]
looks good now. thanks for the quick fix.
