### ISSUE TITLE
Visual Code

### ISSUE THREAD

**Issue by ROBLOXVIP735** [CosmosOS/Cosmos#490]
This may seem really stupid, because after all, VSC doesn't come with C#(Naturally, there is a 714 KB extension you can get that allows you to use C#), and the requirements are appearently, "Visual Studio", but I have a problem. VS doesn't like to install on 128 KBPS (had to use wireless hotspot), so I was wondering if there was a way to hook the devkit up to VSC.
If not, please add it, because VSC is very lightweight compared to the whooping 8 GB that is VSE.

**Comment by jp2masa** [comment]
You can try configuring it on Visual Studio Code, you just need MSBuild.exe, but to be easier you neex to change the Cosmos.Builder a bit, it is probably possible, but not a priority, I think. You can try adding an option to Cosmos.Builder to use VSC and only install the VS Cosmos extension if normal VS is installed.

**Comment by ROBLOXVIP735** [comment]
Okay. Thanks. Also, this is considered the first closed issue on this git. Nice.
