### ISSUE TITLE
VMWare crashes

### ISSUE THREAD

**Issue by ROBLOXVIP735** [CosmosOS/Cosmos#492]
Okay, logs are generated and will be sent by request in pastebin.
Tried it on my potato ACER desktop I use for server hosting because why not, my DELL laptop, and my powerful HP computer, which has 1.5 times the power of my ACER and DELL combined.

**Comment by cjhannah** [comment]
does it crash vmware or is there an error message?

**Comment by ROBLOXVIP735** [comment]
It just crashes.

**Comment by cjhannah** [comment]
does it crash vmware? like vmware stops working?

**Comment by ROBLOXVIP735** [comment]
VMWare fully crashes, as in, it needs a complete computer restart.
As well as that, not exactly sure if this is cosmos's or VMware's part, but I can't get it to A)Build(Obviously Cosmos) and B)Play on VMWare w/o debug mode. Otherwise it does nothing.

**Comment by cjhannah** [comment]
Can you try VirtualBox? This may be a problem with Hypervisor if your PC freezes.

**Comment by ROBLOXVIP735** [comment]
I am TRYING but it doesn't work WITHOUT COMPILING(AKA BUILDING) IT! And my PC isn't freezing, it just won't start VMWare, similiar to how if Steam fails to run, or google chrome crashes while booting.

**Comment by cjhannah** [comment]
Oh, so the VM won't boot at all?

**Comment by ROBLOXVIP735** [comment]
Yes... it says it's disabling long mode because of binary, and then it crashes.

**Comment by cjhannah** [comment]
That's not good. Do y ou have a screenshot or anything?

**Comment by ROBLOXVIP735** [comment]
Uh... I'll take 2 of them. One of the FATAL ERROR message and the LONG MODE thing.

**Comment by cjhannah** [comment]
Thank you.

**Comment by ROBLOXVIP735** [comment]
[http://imgur.com/a/K4j8v](url)

**Comment by cjhannah** [comment]
They have no images.

**Comment by ROBLOXVIP735** [comment]
huh. I'll fix that later, I'm busy.

**Comment by ComputeLinux** [comment]
BOI. YOU ARE BUSY DOING WHAT. WHAT IS SO IMPORTANT YOU CANNOT SPEND 2 SECONDS PRINT SCRENNING, BUT YOU CAN RESPOND TO THIS POST?

**Comment by fanoI** [comment]
Probably as we developers ever use release mode is possible there are problems in that mode.

**Comment by cjhannah** [comment]
I think he ment releasing it by ISO,

**Comment by ROBLOXVIP735** [comment]
Yeah. I meant by compiling the OS into a .ISO file.
blob:http://imgur.com/daec1d81-6ae0-4b4e-a8d3-f4c699644b14
blob:http://imgur.com/a3b078ff-7246-490a-806a-4faa951b009d
blob:http://imgur.com/9876927d-53d8-4400-b16c-7b160f73f5de
Sorry about my late reply, homework is a douche sometimes.
Imgur wasn't helping much. Hope this works for you.

**Comment by cjhannah** [comment]
Imgur links don't work

**Comment by ROBLOXVIP735** [comment]
... AGH. Fine. I'll upload them somewhere else.
Are you sure you have the blob: part on the URL?

**Comment by ROBLOXVIP735** [comment]
I think I got imgur working, but to be safe(Hehe puns) I uploaded them also on img safe.
https://i.imgur.com/MT24tj4.png
https://i.imgur.com/Etrl4D8.png
https://i.imgur.com/auSo7Zc.png

**Comment by cjhannah** [comment]
looks like an issue with vmware

**Comment by fanoI** [comment]
Well the last image says something would be written to vmware.log so what is in that?

**Comment by ROBLOXVIP735** [comment]
Doesn't even write to said directory. In fact, the vmware.log file doesn't even exist in said directory, so there's something really wrong with it.

**Comment by jp2masa** [comment]
Is this still an issue? If it is, see where it says: `A log file is available in "C:\Users\Morgan Von Thaden\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\vmware.log"` and pastebin that log.

**Comment by ROBLOXVIP735** [comment]
I... copied the entire log in my temp.
But... I will do a pastebin. Give me a few days, I've been away from my computer, this is being typed on my phone.

**Comment by ROBLOXVIP735** [comment]
http://pastebin.com/Dnb5kWSE
Sorry, I was away from a computer for a while. Like a long while.

This is the exact log taken from the .log file found in the TEMP folder of my computer, as it never saved anything in my Workstation folder. And yes, I've triple checked over that damn folder multiple times over, and even reinstalled it, but every time it saved to the TEMP folder.

**Comment by jp2masa** [comment]
Userkit or Devkit? Did you try reinstalling Cosmos and VMWare?

**Comment by ROBLOXVIP735** [comment]
Both. Reinstalled both Cosmos and VMWare over a multiple amount of times.
I've also noticed Cosmos Devkit(latest) actually builds a .dll file instead of an .iso. What's the deal with that one? I can't use any other alternatives and I believe this might be why VMWare is crashing.

**Comment by jp2masa** [comment]
The dll is the file which contains the code compiled from the C# source. After that, IL2CPU creates an asm file from the dll, that gets compiled by NASM that generates a bin file, which is then put into an ISO. That ISO is what you run in VMWars. I think this is the process in both userkit and devkit.

**Comment by ROBLOXVIP735** [comment]
Yeah, well something is screwing up because no ISO shows up, it's pure .dll files.

**Comment by jp2masa** [comment]
You need to run the Boot project.

**Comment by ROBLOXVIP735** [comment]
Where is that? I've looked literally everywhere, and even the IL2CPU tab that generates in the toolbar is completely empty.

**Comment by jp2masa** [comment]
Make sure that the Boot project is set as startup project and click on Start in the VS toolbar or press F5.

**Comment by ROBLOXVIP735** [comment]
Huh. Alright, I'll try that when the thing decides to boot. For now, I'm gonna close this.

**Comment by ROBLOXVIP735** [comment]
Yeah that option doesn't exist.
Sorry I couldn't respond, work is a jerk.

**Comment by jp2masa** [comment]
What option? Just click on Start in the VS toolbar or go to Debug->Start Debugging

**Comment by ROBLOXVIP735** [comment]
The start option.
In the toolbar, it doesn't exist.

**Comment by jp2masa** [comment]
Press F5.

**Comment by ROBLOXVIP735** [comment]
I did.

**Comment by jp2masa** [comment]
In the VS menus, go to Debug->Start Debugging.

**Comment by ROBLOXVIP735** [comment]
Start Debugging does absolutely nothing. I've tried that NUMEROUS times already trying to figure this out.

**Comment by jp2masa** [comment]
The ISO file should be created in the bin/Debug folder when you run the project.

**Comment by mackcoding** [comment]
The problem is you should not be trying to mess with something that is obviously far out of your league. You have no clue what you're doing, the information you posted is completely worthless. And you trying to do this on an HP. This is clearly a PEBCAK issue.

**Comment by ROBLOXVIP735** [comment]
OHH! A PEBCAK!? THAT MUST BE REALLY HORRIBLE~! SAVE ME I.T. GODS!




Mackcoding.
This was supposed to be a pet project so I could occupy myself.
"No clue what I'm doing"
You're right.

Because I've never used C or it's variants(except the abomination Ch), and definitely haven't touched Visual Studio. Ever.
Also, did it occur to you that I tried this in an ACER and IT STILL DIDN'T WORK?
Your problem is an issue called ID 10 T. Very serious. I don't know if you use mac or linux or whatever, but go do both of us a favor and if you have windows, delete Sys32.
(Also I don't have a chair rendering the C in PEBCAK useless... man did I actually manage to make a pun or am I just recognizing random things out of my sleep deprived brain?)

**Comment by mihail-mojsoski** [comment]
Just learn C#.

**Comment by ROBLOXVIP735** [comment]
What do you think I was trying to do when I got COSMOS and a bunch of other C# and C++ ideas going?
I'm trying to learn, but C# is vastly different from say Pharo or Python or even Microsoft Batch. Although it's closer to the first two.

**Comment by charlesbetros** [comment]
Don't worry. We were all new at some point. Just ignore the negative people and ask as many questions as you need. Try to use Gitter for questions and GitHub issues for problems with the Cosmos tooling.

**Comment by ROBLOXVIP735** [comment]
Thanks charles.
I've discovered(after following many, many tutorials) that Visual Studio simply doesn't work at all. I'm just going to call this a VS issue and not a COSMOS issue. I'll keep that in mind for future problems.
