### ISSUE TITLE
Devkit

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#493]
Hello, I just got cosmos today. I am impressed about how this works, but except for one thing... the devkit. Is there any way to use the devkit without the other vs2015 versions? Like an addition to the references.     (I have no money.)

Here's the .sln file and stuff if you need it:
[Ruby OS.zip](https://github.com/CosmosOS/Cosmos/files/557418/Ruby.OS.zip)

Also I need this because I need System.IO and GUI`s and other various things.
Thanks in advance! -Alex

**Comment by charlesbetros** [comment]
The devkit works with 2015 Community Edition and up. Community Edition is free.

**Comment by DjAlEx234** [comment]
I thought it meant Community o.o! And anyway how do I install it?
