### ISSUE TITLE
USB Issue

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#494]
Yes I am the same person (sorry for spam). I have used Rufus to take the ISO and extract it on my USB... It didn't work(kinda). It gets stuck where it finds the hardware. Does it have something to do with Cosmos or the USB. Maybe even the ISO itself! Just give me an answer. Please! -Alex

**Comment by charlesbetros** [comment]
Cosmos isn't well supported on real hardware yet. It is currently meant to run from a virtual environment. That said, please do report issues so we have a record of them. This particular issue has been reported in the past, but as I mentioned, real hardware support isn't quite there yet.
