### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#496]
I want to make a GUI for my COSMOS project, I have made everything else. Now I want to make a GUI for it. I tried the instructions, but I cant figure out how to reference the Hardware project. Can I have the source code for it? (Or a better tutorial at least)

**Comment by MichaelTheShifter** [comment]
Try using the HAL project instead.

**Comment by jp2masa** [comment]
@MichaelTheShifter it's not the HAL project, it's the Hardware project created during the tutorial.
@DjAlEx234 Right-click References in your main Cosmos project (the one without Boot in the name) and click Add Reference, go to Project References and select the Hardware project.

**Comment by DjAlEx234** [comment]
Thanks! I would never look there. I love cosmos and it's community, this helped me a lot.

**Comment by DjAlEx234** [comment]
Okay, so I tried it. It says from this code `using Hardware;` Hardware does not exist in this context. Can I have a finished project that works with it?

**Comment by jp2masa** [comment]
What namespace did you use in the DisplayDriver class?

**Comment by DjAlEx234** [comment]
CosmosKernel4 (the name of the project)

**Comment by jp2masa** [comment]
And the main project is CosmosKernel3?

**Comment by DjAlEx234** [comment]
no the main project is CosmosKernel4

**Comment by jp2masa** [comment]
And the project of the DisplayDriver?

**Comment by DjAlEx234** [comment]
Hardware

**Comment by jp2masa** [comment]
In the DisplayDriver class, what's the namespace?

**Comment by DjAlEx234** [comment]
shouldn't it be CosmosKernel4? or should it be Display?

**Comment by jp2masa** [comment]
If it's CosmosKernel4 you don't need any "using"

**Comment by DjAlEx234** [comment]
then what do you do?

**Comment by jp2masa** [comment]
Ignore the "using" part

**Comment by DjAlEx234** [comment]
k i'll try it

**Comment by DjAlEx234** [comment]
I`m confused, can I have a project that is finished?

**Comment by jp2masa** [comment]
Finished like what?

**Comment by DjAlEx234** [comment]
the gui part finished. but the beginning code in run

**Comment by jp2masa** [comment]
You did the part of initializing the DisplayDriver?

**Comment by DjAlEx234** [comment]
it showed an error

**Comment by jp2masa** [comment]
Whenever you get an error, please paste the output log.

**Comment by DjAlEx234** [comment]
ok

**Comment by DjAlEx234** [comment]
1>------ Build started: Project: Hardware, Configuration: Debug x86 ------
1>  Hardware -> C:\Users\ajcre\Desktop\CosmosKernel4\Hardware\bin\Debug\Hardware.dll
2>------ Build started: Project: CosmosKernel4, Configuration: Debug x86 ------
2>C:\Users\ajcre\Desktop\CosmosKernel4\CosmosKernel4\Kernel.cs(14,13,14,20): error CS0103: The name 'display' does not exist in the current context
2>C:\Users\ajcre\Desktop\CosmosKernel4\CosmosKernel4\Kernel.cs(15,13,15,20): error CS0103: The name 'display' does not exist in the current context
Build has been canceled.

**Comment by jp2masa** [comment]
You have somerthing like:
public class Kernel : Sys.Kernel
{

Right after that write: `DisplayDriver display;`

**Comment by DjAlEx234** [comment]
?

**Comment by DjAlEx234** [comment]
want the code

**Comment by jp2masa** [comment]
In your Kernel.cs file

**Comment by jp2masa** [comment]
Paste Kernel.cs contents if you want me to help you better

**Comment by DjAlEx234** [comment]
ok:
`using static System.Console;
using Sys = Cosmos.System;
using System.IO;

namespace CosmosKernel4
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            Clear();
            display = new DisplayDriver();
            display.init();
            WriteLine("Zach OS booted correctly! Type help for help!");
        }

        protected override void Run()
        {
            Main();
        }

        void Main()
        {
            CursorVisible = true;
            while (true)
            {
                Write("$: ");
                var a = ReadLine();
                if ((a == "help") || (a == "about") || (a == "cls") || (a == "restart") || (a == "off")||(a == "dir"))
                {
                    var c_path = Directory.GetCurrentDirectory();
                    if (a == "help")
                    {
                        Help();
                    }
                    if (a == "about")
                    {
                        About();
                    }
                    if (a == "cls")
                    {
                        Clear();
                    }
                    if (a == "restart")
                    {
                        Sys.Power.Reboot();
                    }
                    if (a == "off")
                    {
                        AfterRun();
                    }
                    if (a == "dir")
                    {
                        string akhdkuhksihaiuefhiauefhi = "In directory " + c_path;
                        WriteLine(akhdkuhksihaiuefhiauefhi);
                    }
                }
                else
                {
                    string b ="<" + a + ">" + " is not a command";
                    WriteLine(b);
                }
            }
        }

        protected override void AfterRun()
        {
            base.AfterRun();
            Clear();
            CursorVisible = false;
            WriteLine("It is now safe to turn off your computer");
            while (true)// looooooooooooooooooooooooooooooooooooooop
            {
                ReadKey(true);
            }
        }

        void About()
        {
            Clear();
            WriteLine("About Zach OS");
            WriteLine("This is Open Source");
            WriteLine("Beta 0.1 Beta");
            WriteLine("Build 0199");
        }

        void Help()
        {
            Clear();
            WriteLine("Here is a list of commands:");
            WriteLine("about - Tells you about the OS");
            WriteLine("cls - Clears the screen");
            WriteLine("dir - Shows the file(s)/folder(s) in the directory");
            WriteLine("help - Gives you a list of commands");
            WriteLine("off - Turns off the OS");
            WriteLine("restart - Restarts the OS");
        }
    }
}`

**Comment by jp2masa** [comment]
As I said:
"
You have somerthing like:
public class Kernel : Sys.Kernel
{

Right after that write: `DisplayDriver display;`
"

**Comment by DjAlEx234** [comment]
after the
`public class Kernel : Sys.Kernel
{`
part? then change it to:
`public class Kernel : Sys.Kernel
{
DisplayDriver display;
`

**Comment by jp2masa** [comment]
Yes

**Comment by DjAlEx234** [comment]
k ill try it

**Comment by DjAlEx234** [comment]
thanks it works! I love the community for this.
