### ISSUE TITLE
Launching Cosmos in a virtual machine problem

### ISSUE THREAD

**Issue by CrispySteven** [CosmosOS/Cosmos#497]
Whenever I launch cosmos in a virtual machine, whether it be in bochs or vmware, it doesn't launch my updated code.  I've tried to make a new ISO, but it still launches without my updated code.  Does anyone know why?

**Comment by DjAlEx234** [comment]
Try making directly for VMware or Bochs, sometimes the iso function doesn't work.

**Comment by CrispySteven** [comment]
I tried, but it didn't work.  The only way it seems to work is if I remake a project file in visual studios and run it directly to VMware.  Is there a way where I don't have to keep remaking the project?

**Comment by jp2masa** [comment]
Probably your project is not set for build. Right-click your solution and go to options or properties, I don't remember well, then search for a list of the projects somewhere where there's a checkbox for each project, make sure every checkbox is checked.

**Comment by CrispySteven** [comment]
They're all checked in the properties.

**Comment by jp2masa** [comment]
Then I can't see why it won't build, whenever a file is changed in a project, Visual Studio "marks" it as outdated and next tine it's needes it's rebuilt.

**Comment by jteugels** [comment]
I am having the same problem. When changing the kernel.cs in cosmos.system (ex. : global.mdebugger.sen("Before Run"); to "Before Run Run") these changes become only visible after executing the install-vs2015.bat again.
Are there some post or pre build steps that need to be used ?

**Comment by jp2masa** [comment]
If you change the Cosmos sources and want then to be updated in your system you can run install-VS2015.bat or build the project you changed and copy the dll replace the dll(s) somewhere in %appdata%/Cosmos User Kit

**Comment by jteugels** [comment]
Found the solution by adding a post build event (on successful build) copying the dll's to the user kit location. From there they are used for creation of the iso.
xcopy /Y "$(TargetDir)$(TargetName).*" "$(USERPROFILE)\appdata\roaming\cosmos user kit\kernel"
xcopy /Y "$(TargetDir)$(TargetName).*" "$(USERPROFILE)\appdata\roaming\cosmos user kit\build\vsip"
xcopy /Y "$(TargetDir)$(TargetName).*" "$(USERPROFILE)\appdata\roaming\cosmos user kit\build\il2cpu"
