### ISSUE TITLE
MOUSE

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#498]
Where do you add a mouse in cosmos? I have got most of my os done.

**Comment by jp2masa** [comment]
In the mouse tutorial, there's a link to Codeplex, follow that guide and adapt it to your project, it's not really easy.

**Comment by DjAlEx234** [comment]
...I mean where you add the mouse, in the kernel? The display driver? And in what void? Such questions

**Comment by DjAlEx234** [comment]
it never tells

**Comment by lexected** [comment]
jp2masa, DjAlEx234 ....

PLEASE, STOP THIS TERRIBLE SPAM!

What's the meaning of sending a message every minute with a single 
sentence? Well, first of all, there's none in the majority of cases, and 
then can't you just use chat if there's only two of you?
No one is ever going to crawl through these, so there's no point in 
archiving "Yes", "Let me try", "I think so" 10 times a week.

~lexected

**Comment by jp2masa** [comment]
@lexected if it bothers you so much, just stop "watching" the repo.

@DjAlEx234 I think the tutorial says to create a class MouseDriver or something like that in the Hardware project. Don't forget I'm talking about the Codeplex tutorial from which the wiki tutorial was made. The tutorial in the wiki is a bit incomplete in my opinion.

**Comment by zarlo** [comment]
just do it in the system ring

**Comment by fanoI** [comment]
There is already a Mouse driver in the Cosmos sources:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL/Mouse.cs

it is to see if / how it is working, if it does not work please fix in the main Cosmos repo not your private OS.

Thanks!
