### ISSUE TITLE
NAsm MSBuild task interpret warning as error

### ISSUE THREAD

**Issue by kant2002** [CosmosOS/Cosmos#50]
When building Demos\Guess\Guess project following error produced.

1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(45,5): error : C:\Users\<user>\Documents\GitHub\Cosmos-1\Demos\Guess\bin\Debug\Guess.asm:1964: warning: trailing garbage after `%endif' ignored

From what I see is that NAsm output incorrectly interpresed by Cosmos.Build.MSBuild.Nasm task

**Comment by kant2002** [comment]
This is produced by commit 
https://github.com/CosmosOS/Cosmos/commit/e614a95df51524004e5dc0aa448059bfe36be345#diff-6038801f6586bf84d86a43b516e6b6d7L126

which is remove processing logic for output messages produced by the tools

**Comment by mterwoord** [comment]
That code caused issues with IL2CPU i think, therefore it was removed.. You
could add it again if you test it well...


2015-01-15 7:47 GMT+01:00 Andrey Kurdyumov <notifications@github.com>:

**Comment by kant2002** [comment]
What if I revert back code and for IL2CPU task put pass-through logic which will mimic current behavior? That way I less likely introduce regression.

**Comment by mterwoord** [comment]
OK, Go ahead!


2015-01-15 11:06 GMT+01:00 Andrey Kurdyumov <notifications@github.com>:

**Comment by kant2002** [comment]
Does Kudzu.Breakpoints and SentinelKernelBoot was compiling?
They report that plugs are missing. Is this something expected?

**Comment by mterwoord** [comment]
Only compilation issue we know of (is fixed in my latest commit) is a missing file in the DebugCompiler project. Nothing else. Are you on a clean build?

**Comment by kant2002** [comment]
Pull request is here: https://github.com/CosmosOS/Cosmos/pull/52

**Comment by kant2002** [comment]
Yes I'm on clean build. Even revert all changes. I was compiling Cosmos projects.
Don't have any issues with C#

**Comment by Sentinel209** [comment]
I'll verify my project. Will be about 2 hours until I can do it.

**Comment by Sentinel209** [comment]
SentinelKernel compiles and runs without issues. There is the nasm warning thugh which I would expect.

**Comment by kant2002** [comment]
We resolved there. Right now no errors happens. Pull request could be merged
