### ISSUE TITLE
return doesn't work inside foreach

### ISSUE THREAD

**Issue by bartashevich** [CosmosOS/Cosmos#501]
Problem:
returning inside foreach doesn't end funcion.

Code:
![test1](https://cloud.githubusercontent.com/assets/9809095/19900351/d86ede90-a06b-11e6-8e52-046ece3abff7.png)

Result:
![test2](https://cloud.githubusercontent.com/assets/9809095/19900352/d8735736-a06b-11e6-9574-664e3845d261.png)

VS Project:
http://dropmefiles.com/9JJeY

**Comment by charlesbetros** [comment]
Is it the foreach or the string compare that is failing?

**Comment by denisbest** [comment]
No, because you can see "True" printing

**Comment by charlesbetros** [comment]
Got it. The return never occurs though the true condition is hit.

**Comment by denisbest** [comment]
BTW, I made return just inside if (without foreach) and that worked. Just inside foreach loop return doesn't work.

**Comment by charlesbetros** [comment]
Looks like the List<T> is the issue. string[] seems to work ok.

**Comment by bartashevich** [comment]
You tried with foreach? Exact same code just with string[]? Because it hits if(true) but doesn't return.

**Comment by charlesbetros** [comment]
I used int.

**Comment by jp2masa** [comment]
This has been fixed by #507
