### ISSUE TITLE
Detect where is the "Plug required" error

### ISSUE THREAD

**Issue by lcnvdl** [CosmosOS/Cosmos#502]
Hi, I'm having the next message, but I don't know how can I find where is missing a plug, to fix the error:

"Severity	Code	Description	Project	File	Line	Suppression State
Message		
Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Object  System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType).	MydrosBoot		0	"

Where Can I found more information about this specific error? Like File, class, method, or something ?

Best regards,
Luciano Rasente

**Comment by jp2masa** [comment]
After that message it has a stack trace right?

**Comment by lcnvdl** [comment]
Thanks for your quickly answer!

Nope, the only feedback is that is a problem with "System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter". And is not an error message, is just a message. 

I'll attach here the entire log:
[MSVS_2015_Log_xls.zip](https://github.com/CosmosOS/Cosmos/files/565272/MSVS_2015_Log_xls.zip)

**Comment by jp2masa** [comment]
You are comparing List or Dictionary types, like Equals() ?

**Comment by lcnvdl** [comment]
I'm using Lists and Dictionaries, but not using equals. Exists a problem with that data structures ?

**Comment by jp2masa** [comment]
Interfaces are not fully implemented and you are somehow "comparing" them I don't know well what methods do that but Equals() is one of them.

**Comment by lcnvdl** [comment]
Thanks, I've commented my dictionary's code and now that error was dissapear. Now, I'm implementing the next Interface:

public interface IDisplayDriver
    {
        int Width { get; }
        int Height { get; }
    }

I have a class that implements IDisplayDriver, returning the Width and the Height. I don't know why, but I get a strange error:

MydrosBoot.asm:364868: error: symbol `SystemInt32HardwareDriversDisplayDriverget_Width' undefined	MydrosBoot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	45	

Is saying that my class DisplayDriver have an undefined "Width" getter, but that's not thruth.

What am I doing wrong ?

Thanks

**Comment by jp2masa** [comment]
As I said, interfaces aren't fully implemented, however I think that in that case it should work. Try searching for 'SystemInt32HardwareDriversDisplayDriver' in the generated .asm file in bin/Debug and see if there's something similar to 'SystemInt32HardwareDriversDisplayDriverget_Width'

**Comment by lcnvdl** [comment]
Ow, I didn't read that.. I've solved my problem replacing the interfaces for abstract classes, and now that works... A LAST LAST question (sorry).

My project compiles when I comment my dictionary. I'm using this:

(Now IWindowsSystem and IWindow are abstract classes)

`    public class MydrosWindowsSystem : IWindowsSystem
    {
        private const int barHeight = 32;
        private Dictionary<int, IWindow> windowsById = new Dictionary<int, IWindow>();

        public override void RegisterWindow(IWindow window)
        {
            windowsById[window.Id] = window;
        }

        public override void UnregisterWindow(IWindow window)
        {
            if(windowsById.ContainsKey(window.Id))
            {
                windowsById.Remove(window.Id);
            }
        }
}`

To get this working, do I need to create a new data structure that works like a dictionary ?

**Comment by jp2masa** [comment]
That code doesn't compile?

**Comment by lcnvdl** [comment]
Yes, that doesn't compile. Throws me the next error:

"Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Object System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType)"

**Comment by zarlo** [comment]
@lcnvdl Dictionaries are not pluged

**Comment by charlesbetros** [comment]
@lcnvdl aren't those properties in your interface private by default if you don't have an access modifier?

**Comment by lcnvdl** [comment]
No, the interfaces cannot have access modifier inside. All are public by default. The problem was solved updating CosmOS to the last version... Anyway, I'm not using Cosmos anymor because haves a lot of other problems. I've started using Cosmos to make an hobby OS in a short time, but starting from scratch is much more faster and with less problems.

Regards

**Comment by charlesbetros** [comment]
Oh yeah. Interface not abstract. Duh :)
