### ISSUE TITLE
VBE too slow? - (Way to fix?)

### ISSUE THREAD

**Issue by fido2020** [CosmosOS/Cosmos#504]
Recently with Cosmos i have been using VBE graphics and i find that you can actually see each pixel fairly slowly being placed on the screen when you clear the screen which i see is because you use a for loop to place pixels. I am thinking a way to fix this is to set the whole VBE memory block at once to a certain colour. I have tried to fix this but i can only clear it to black.
Here is my code

VBEDriver (i tried to replicate my c memset code):
```
unsafe void* memset(char* dst, char src, int n) {
            char* p = dst;
            while (n != 0)
                *dst++ = src;
                n--;
            return p;
}

public void set_vram_range(uint index, int range, uint value){
            unsafe { memset((char*)0xE0000000 + index, (char)value, range); }
 }
```
VBEScreen:
```
public void Clear()
        {
            _vbe.set_vram_range(0x1,ScreenWidth * ScreenHeight * 4, /*Colour would normally be here*/0);
        }
```

**Comment by fanoI** [comment]
It should exist the IO.Memory.Fill to fill a memory area with a specific byte (in this case a color). Look how the Clear method of TextScreen is done:

https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL/TextScreen.cs#L48

VGAScreen has the same problem too.

**Comment by fido2020** [comment]
Ok, but how would i put this to use??

**Comment by fido2020** [comment]
Oh and i tried this but this doesent work with VBE
