### ISSUE TITLE
GUI: CPU exception 0x06

### ISSUE THREAD

**Issue by CheezBoiger** [CosmosOS/Cosmos#505]
Not sure if I did something weird, but I was creating the GUI for CosmosOS, and read the tutorials on how to do so. As I have wrote it similar to how it was described by Myvar, I figured it would work fine. My hardware dll was compiled successfully afterward, then my project with the kernel, and an iso was made without error. Unfortunately when testing on virtualbox, I came across a cpu exception:

```
*** CPU Exception x06 ***
Last known address: 0x0108DA58
```
I am not exactly sure where this has occured, but I can most definitely say it happened when I was initializing/booting the Screen/Display and calling Clear(0).

Inside my Screen.cs.
```C#
public static class Screen {
	private static byte[] sBuffer = new byte[64000];
	public static VGAScreen screen = null; // calling new here would result in a screen crash


	public static void Boot() {
		Console.WriteLine("Booting the screen.");
		screen = new VGAScreen(); // If I don't instantiate screen here, I end up with a screen crash, and no exception.
		screen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
                        // After SetGraphicsMode() and calling Clear(0) is where I ended up getting the CPU Exception.
		screen.Clear(0);
		Console.WriteLine("Successful screen Boot!");
	}

               . . .
```

I don't know exactly the reason behind this. At the moment I feel this is about as much relevant information I can give on what the problem is, let me know if you request more information to help you guys out. Much appreciated with any assistance on this issue!

**Comment by charlesbetros** [comment]
Are you running the User Kit or latest sources?

**Comment by CheezBoiger** [comment]
I am currently running the latest sources. The last time I cloned from master was approx. November 1st.

**Comment by fanoI** [comment]
VGA driver actually does not draw nothing on screen but in my tests I don't get exceptions that is apparently the code works but nothing is drawn!

The only difference is that I do:

public static VGAScreen screen = new VGAScreen();

directly without putting null in the variable...

**Comment by CheezBoiger** [comment]
@fanoI 
Yea that's what's super crazy at the moment for me, I assumed that I was just going mental and the screen ended up looking like it crashed for me! I tried to copy your way and this is what I ended up with:
![screencrazyt](https://cloud.githubusercontent.com/assets/10396295/20081420/6ff09b7c-a504-11e6-9f23-b689f54a8561.png)
Now , I'm not so sure why this is happening, or if you were able to reproduce the problem, but in my kernel I call in BeforeRun() to first boot the Screen singleton from my hardware dll, and then call a function called Screen.Step() inside the kernel Run() override, which Step() is provided below: 

```C#
	public static class Screen {
		private static byte[] sBuffer = new byte[64000];
		public static VGAScreen screen = new VGAScreen()

         .    .    .

		public static void Step() { 
			Redraw();
		}

	
		public static void Redraw() {
			int c = 0;
			for (int y = 0; y < screen.PixelHeight; ++y) {
				for (int x = 0; x < screen.PixelWidth; ++x) {
					uint cl = screen.GetPixel320x200x8((uint)x, (uint)y);
					if (cl != sBuffer[c]) {
						screen.SetPixel320x200x8((uint)x, (uint)y, sBuffer[c]);
					}
					c++;
				}
			}
		}
```

Now in my code I have debug break statements (which are just Console.ReadLines()) inside the Screen.Boot() function. It just so happens that after setGraphicsMode() the screen ends up like the above image you saw. I'm not sure what's going on here, or perhaps I'm doing something wrong, but hopefully this helps a little bit!

My apologizes for not responding soon enough!

**Comment by fanoI** [comment]
Hmm is interesting at least you see something on screen :-)

I see you are using VirtualBox it is set to use your host VGA card? In theory our VGA driver should be universal but I want to understand if there is something different here.

**Comment by charlesbetros** [comment]
Would you mind providing your kernel source to help duplicate the exception you are seeing?

**Comment by CheezBoiger** [comment]
@charlesbetros 
Oops yes,I can, be warned though, It's literally just booting the screen and calling it to step:

http://pastebin.com/t4rvtFMd

I haven't been successful at locating the exact reason for the bug. I ran it on vmware as well, along with the GDB client, and I don't think I'm using it correctly as it doesn't update, but I see a funny thing happen here. It stops at "booting the screen" and then proceeds to overwrite everything gradually!
![vmcrazy](https://cloud.githubusercontent.com/assets/10396295/20196317/0398658e-a74f-11e6-8daf-fa6e83abb0a7.png)
When I tried it again, I get the error from vmware stating this:
```
A fault has occurred causing a virtual CPU to enter the shutdown state. If this fault 
had occurred outside of a virtual machine, it would have caused the physical machine to 
restart.
The shutdown state can be reached by incorrectly configuring the virtual machine, a bug 
in the guest operating system, or a problem in VMware ESX.
```
And for virtualbox, it does the same thing as described by the image before, heh.

@fanoI 
My super sincere apologizes! I was preoccupied by a couple of stuff, but I know that you are busy yourself, I haven't found the time to message you back soon enough! Anyways, I would hope that the VGA driver is supported, and I am hopefully positive that it is set to my host VGA driver, but how do I know for sure?

**Comment by charlesbetros** [comment]
What does Step() look like?

**Comment by CheezBoiger** [comment]
Right here :3
```C#
        public static void Step() { 
            Redraw();
        }


        public static void Redraw() {
            int c = 0;
            for (int y = 0; y < screen.PixelHeight; ++y) {
                for (int x = 0; x < screen.PixelWidth; ++x) {
                    uint cl = screen.GetPixel320x200x8((uint)x, (uint)y);
                    if (cl != sBuffer[c]) {
                        screen.SetPixel320x200x8((uint)x, (uint)y, sBuffer[c]);
                    }
                    c++;
                }
            }
        }
```

**Comment by CheezBoiger** [comment]
Also I seemed to have forgotten to call clear() when redrawing...

**Comment by charlesbetros** [comment]
If you remove the Console.WriteLine("Successfully...") does it help?

**Comment by CheezBoiger** [comment]
It did get past the booting, but the vmware cpu fault error pops up again!

**Comment by CheezBoiger** [comment]
I might look into the older version of cosmos, and check if it's just my hardware.

**Comment by fanoI** [comment]
@CheezBoiger  there is no need to apologize!

Let's try to recap the 0x06 exception was in VirtualBox or in VmWare?
After you don't set the VGA variable to null but directly do new you had no more the 0x06 exception?
You have the garbled screen instead right?

I asked if VirtualBox was using your host GPU instead of an emulated one as indeed you see something on screen so at least our code is doing something (wrongly) in your case.
If I remember correctly on Cosmos profiles there is no VirtualBox so you have created a VM and make it running Cosmos ISO? If so you could check in that VM properties what GPU is used...

Thanks!

**Comment by CheezBoiger** [comment]
@fanoI :3 
I'll see if I can answer those questions and not be too Canadian on my part...

Yes, the 0x06 exception occured on VirtualBox ( with version 5.1.8 r111374 installed).
When I set the VGA variable directly to new (and not null) I no longer had the 0x06 exception, it does indeed end up with the garbled screen though. 
As for my Virtualbox VGA driver I'm running through the host GPU (it's running with Physical Address Extension and 3D acceleration as well, I don't really know why I need these, but disabling them doesn't do anything to solve the problem, :c .) and through a Cosmos ISO. My host GPU is an NVidia GeForce GTX 870m, and my host CPU is an Intel i7-4800MQ.

Also just to let you know, The ISO was built in debug mode, it seems like the release causes an error.

Let me know if I'm missing anything, or if you need more information out of me. I'll try to help as much as I can!

**Comment by cjhannah** [comment]
that happens to me when I do it too. just use VBEscreen

**Comment by CheezBoiger** [comment]
@cjhannah 
VBEScreen works! Thank you so much! 

I'm still confused as to why VGAScreen doesn't work though... VBE I didn't even know what that is.

**Comment by MichaelTheShifter** [comment]
VGA's been broken for a while. VBE's a lot better, to be honest.

**Comment by fanoI** [comment]
VBE stands for Vesa Bios Extension it is a sort of "universal" VGA driver that permits to go to higher resolutions that the standard VGA but without accelerations of sort (so native drivers will be in any case needed in future).
The one inside Cosmos is not a real VBE driver as it works only with Bochs (we use documented port to bypass the real VBE protocol) so it does not work with VmWare neither with VirtualBox, so we need a working VGA driver in any case...

**Comment by CheezBoiger** [comment]
@fanoI 
Thank you for clairifying and assisting, I didn't know what VBE was :). I can continue with my project since the VBEScreen works for me nicely, therefore I believe my issue has been **resolved**, however since the VGAScreen is still problematic, I will leave this issue open. Feel free to ask me for any more information regarding the situation, along with closing this issue if you feel it's no longer a concern :). 

Thank you again @fanoI @charlesbetros @cjhannah and  @MichaelTheShifter  for the help!

**Comment by fanoI** [comment]
In reality are you that help you opening issues :-)

**Comment by prepare** [comment]
@fanoI ,  this is my  simple display code 
 
	using System;
	using Cosmos.HAL;

	namespace Hardware
	{
		public class DisplayDriver
		{
			protected VGAScreen screen = new VGAScreen();
			public void Init()
			{
				screen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
			}
			public virtual void Clear(int c)
			{
				screen.Clear(c);
			}

			public void ReDraw()
			{
				int c = 0;
				for (int y = 0; y < 200; y++)
					for (int x = 0; x < 320; x++)
					{
						screen.SetPixel320x200x8((uint)x, (uint)y, 50);
						c++;
					}
			}
		} 
	}

---


![c_1](https://cloud.githubusercontent.com/assets/7447159/20823893/bda3bc3e-b88a-11e6-8e63-0d74211f6b3b.png)

?? why??
The VGA is broken?

**Comment by fanoI** [comment]
Yes VGA is broken are you using Virtual Box? I cannot see anything neither drawn in Bochs neither in VmWare :-)

**Comment by prepare** [comment]
@fanoI , I use VMWare Workstation 12 Player, on Win7 64 bits
