### ISSUE TITLE
CosmosOS Mouse Input Error?

### ISSUE THREAD

**Issue by Lrios4403** [CosmosOS/Cosmos#506]
Alright so im trying to include mouse like normal

{
private Cosmos.Hardwear.Mouse mouse;
}

But the class is static and the non static class im trying to import and im missing Cosmos.Core;
Can someone fix this (example or a link to download Cosmos.Core.Dll)?

**Comment by jp2masa** [comment]
Are you using the userkit?

**Comment by Lrios4403** [comment]
Im going to fell stupid rn... what is that 

@jp2masa 
> Are you using the userkit?

**Comment by Lrios4403** [comment]
Ok i found it

**Comment by fanoI** [comment]
It is working now with last devKit?

I have to ask please to find talk of issues on the chat https://gitter.im/CosmosOS/Cosmos a lot of issues here are simply question.

**Comment by Lrios4403** [comment]
OKE so @fanoI im getting this wierd error saying "
======================
Checking Prerequisites
======================

Note: This check only prerequisites for building, please see website for full list.
Checking for x86 run.
Checking Operating System
Check if User Kit Installer is already running.
Checking if Visual Studio is running.
Checking if Builder is already running.
Checking for Visual Studio 2015
Checking for Microsoft Visual Studio 2015 SDK - ENU
Checking for .NET 3.5 SP1
Checking for .NET 4.03
Checking for Inno Setup
Checking for VMware Workstation
Checking for VMware Player
Checking for VMwarePlayer_x64

===============
Build Complete!
===============


=====
Error
=====

Cannot find Inno Setup.
"

wats the Inno Setup?

**Comment by charlesbetros** [comment]
https://www.google.com/search?q=innosetup
https://github.com/CosmosOS/Cosmos/wiki/Devkit

**Comment by Lrios4403** [comment]
Thanks @charlesbetros
