### ISSUE TITLE
Cosmos Graphic Subsystem Revamp

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#514]
This is the list of work needed to modify the driver system of VGA to support the Cosmos Graphic Subsystem (CGS):

- [x] Add the Colordepth enum
- [x] Add the Mode Structure
- [x] Add the Canvas abstract Class
- [x] Add the Pen Class
- [x] Modify the VBEScreen to extend the Canvas class (add the new methods, change SetPixel() to DrawPoint() and so on...)
- [x] Add the FullScreenCanvas class that initially will be a simple "proxy class" to the VBEScreen Class
- [x] Create a test kernel in which a point, a line and a rectangle are drawn using the Canvas methods
- [ ] Rename VGAScreen in HAL to VGADriver
- [ ] Make VGADriver really work (that is make it draw something on screen!)
- [ ] Modify VGAScreen to extend the Canvas class (add the new methods, change SetPixel() to DrawPoint() and so on...)
- [ ] Modify the FullScreenCanvas class so that GetFullScreenCanvas() return the instance of the correct running driver

**Comment by fido2020** [comment]
This is definetly needed!

**Comment by DjAlEx234** [comment]
someone approve this already!

**Comment by charlesbetros** [comment]
Approve it? It's an issue that is in progress. Nothing to approve.

**Comment by DjAlEx234** [comment]
oh

**Comment by fanoI** [comment]
#https://github.com/CosmosOS/Cosmos/issues/505

**Comment by kesbookuk** [comment]
@fanoI any updates

**Comment by fanoI** [comment]
A great update! CGS has been merged in master 👍 
Look here for how to use it: https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Graphic-Subsystem

**Comment by fanoI** [comment]
As CGS has landed in master I close this issue and re-open another with the requested enhancements.

**Comment by kessanro** [comment]
@fanoI is there a way to make a desktop background

**Comment by fanoI** [comment]
If you mean a simple color based background yes for example with:

``cs
      canvas = FullScreenCanvas.GetFullScreenCanvas();
      canvas.Clear(Color.Blue)
``cs

**Comment by kessanro** [comment]
@fanoI is there a way to load a png or bitmap file as a background or not

**Comment by kessanro** [comment]
@fanoI does not show Cosmos.System.Graphics when doing the using

**Comment by fanoI** [comment]
This issue is closed please use the chat for questions.
Do you are following the wiki: https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Graphic-Subsystem ?
