### ISSUE TITLE
Cosmos OS Network

### ISSUE THREAD

**Issue by arcazrael** [CosmosOS/Cosmos#515]
Hello. It is possible to use network in CosmosOS.
Could anyone give an example of how to create the network interface.
What is the type of Tcp protocol, Udp.

**Comment by jp2masa** [comment]
It's not possible to use network at the moment.

**Comment by arcazrael** [comment]
Thanks. If I can create a basic network I share with the community.

**Comment by jp2masa** [comment]
I'm really sorry, I only knew this a few minutes ago, it seems that there's an UDP implementation currently in Cosmos and networking is being more developed and should have a stable implementation on Cosmos v1.0 release.

**Comment by czhower** [comment]
UDP is in the old code. Hasn't been ported and I think the later updates 
are still on my HD.

I'm getting back to dev, so hopefully we will resume on UDP soon. Right 
now need to finish .NET core, move to VS 17 etc.

**Comment by arcazrael** [comment]
Could pass that version that has on your HD.
