### ISSUE TITLE
UdpClient Networking

### ISSUE THREAD

**Issue by dedady157** [CosmosOS/Cosmos#516]
if i send a message using UdpClient.Send(byte[],Adress,int);
i get an Exception 
CPU Exception x06
how do i fix this or is it a bug with the UdpClient

CODE:

try
{
     UDP = new UdpClient();
     UDP.Connect(new Address(0xC0, 0xA8, 0xB2, 0x18), 1234);
     UDP.Send(new byte[] { 0x70, 0x69, 0x6e, 0x67 });//send ping
     ColoredWriteLine(ConsoleColor.Green, "Connected To The Web");
     UDP = null;
}
catch
{
      ColoredWriteLine(ConsoleColor.Red, "NO CONNECTION");
}

**Comment by jp2masa** [comment]
Networking was already supported in Cosmos, but currently it's not supported.

**Comment by jp2masa** [comment]
UDP is not supported in the current devkit, but it will be implemented for the next Cosmos release.
