### ISSUE TITLE
Mount Disk and Embedded Files

### ISSUE THREAD

**Issue by GabrielTK** [CosmosOS/Cosmos#517]
Hey Guys, I was trying to Mount the Windows 10 disk into cosmos (as I know, we might need to add "remove_hiberfile" to mount options), and then place some files (that would came on the OS) on it. Is it possible?? If yes, how??
Thank you,
Gabriel

**Comment by fanoI** [comment]
Cosmos for now supports only FAT32 and I imagine your Windows 10 disk is NTFS.

In any case remember that Cosmos is alpha software and if you have important data in your drives is better to not mount them in Cosmos for now...

**Comment by DjAlEx234** [comment]
I would suggest using VMware and a virtual floppy. If it doesn't work open the iso with a third-party program and add files.

**Comment by fanoI** [comment]
I think it could be possible to open the vmdk with some tool and "mount" it on Windows, alternatively I think you can add it to a pre-existing Virtual Machine and add / remove files with that operating system.

**Comment by GabrielTK** [comment]
I was planning to use it in a real machine, like a "rescue disk"

**Comment by fanoI** [comment]
Sorry I closed this for error.

Surely Cosmos given its little size could be a good candidate to be the core of a "Rescue Disk" there is a lot of work to do to reach that for now only FAT drives will be mounted (oh well all is hardcoded so it probably mounts only the first drive / partition) and well all is in alpha so better to not use on a real machine if you have important data on it :-)
It is more probable that Cosmos now will be a "Disk Wiper Tool" that a "Rescue Disk"!

So as starting points:
1. All File related methods of .Net should work on FAT
2. Then we need to implement ISO (so Cosmos could read file from its image itself)
3. Then we could do NTFS but here we have a license issue so probably it could be part of the normal Cosmos distribution (in future probably we have loadable filesystem "drivers" too)

Do you want to help us on "1"?

**Comment by Neil-Ciciglycerin** [comment]
i don't think this should've gotten closed...
