### ISSUE TITLE
Visual Studio 2017 support?

### ISSUE THREAD

**Issue by thegreatrazz** [CosmosOS/Cosmos#519]
I just upgraded the VS2017 and Cosmos doesn't work.

**Comment by charlesbetros** [comment]
Visual Studio 2017 isn't supported quite yet.  We'll be adding it soon.

**Comment by DjAlEx234** [comment]
(lol) I was never here...

**Comment by zarlo** [comment]
i think someone said it will be updating to VS2017 when it get out of RC or when Cosmos moves over to .net Core it done

**Comment by fanoI** [comment]
Probably yes there will never be a Net Core release without VS2017, Net Core in VS2015 is an "hack"...

**Comment by VortexIncAdmin** [comment]
That's what I was wondering now...
