### ISSUE TITLE
Cosmos There Is No NameSpace Called FileSystem Error.

### ISSUE THREAD

**Issue by firizen16** [CosmosOS/Cosmos#520]
I tried to use FAT FileSystem in Cosmos but I compared to an error. Error is: 
http://prntscr.com/dchl04

**Comment by jp2masa** [comment]
Are you using the userkit? FAT is only available in the devkit, and it's still not working completely well.

**Comment by firizen16** [comment]
Yes I am using userkit. How can I download devkit ?

**Comment by jp2masa** [comment]
I think it's in the wiki. You need to clone or download the repo as zip and run install-VS2015.bat, you need innosetup and vs sdk.

**Comment by firizen16** [comment]
Ok thanks.
