### ISSUE TITLE
File System issues and Booting from ISO problem

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#526]
Hello I'm relatively new to all this and I was wondering if I could get help here. Whenever I use the file system to make a folder or file the virtual machine goes black then closes. Does anyone know what's causing this and how to fix it?

I'm not sure if I can post two problems in one but I've also been having trouble booting from the ISO image. whenever I boot it, the text on screen says it failed to load Cosmos.bin

Any help would be greatly appreciated.

thanks

**Comment by jp2masa** [comment]
FAT is still in development, so it's normal that it has bugs, but the ones you report a strange, the ISO file problem is strange too, have you tried to reinstall the devkit?

**Comment by APERSONA32** [comment]
ive tried it on two different installs on two different computers

**Comment by jp2masa** [comment]
Can you show the code you are using?

**Comment by APERSONA32** [comment]
All of it?

I tend to break it up in different files

**Comment by jp2masa** [comment]
The filesystem part

**Comment by APERSONA32** [comment]
Here it is, or should be
[FileSystem.txt](https://github.com/CosmosOS/Cosmos/files/627983/FileSystem.txt)

**Comment by jp2masa** [comment]
Please see the wiki, you should register the VFS and use System.IO methods.

**Comment by APERSONA32** [comment]
I thought I did that with 
FS.Initialize();

**Comment by APERSONA32** [comment]
it worked!
Thank you

**Comment by APERSONA32** [comment]
I'm still having issues with the ISO boot

**Comment by jp2masa** [comment]
Where are you using the iso? i.e. bochs, vmware...

**Comment by APERSONA32** [comment]
VMWare Workstation 12 player

**Comment by jp2masa** [comment]
Can you show the error you're getting?

**Comment by APERSONA32** [comment]
![capture](https://cloud.githubusercontent.com/assets/24322118/20849490/d653b330-b8ce-11e6-84a0-e1aa831198a3.PNG)

**Comment by jp2masa** [comment]
Can you mount the iso file and list the files here?

**Comment by APERSONA32** [comment]
![capture](https://cloud.githubusercontent.com/assets/24322118/20849828/502e7338-b8d0-11e6-9066-a3bd52be7c53.PNG)

**Comment by jp2masa** [comment]
Everything seems fine, I don't know why it's failing.

**Comment by APERSONA32** [comment]
alright  I appreciate the help though
ill leave it open in case anybody else might be bale to help

**Comment by zarlo** [comment]
clean the solution then rebuild it

**Comment by APERSONA32** [comment]
as in clear the debug folder?

**Comment by APERSONA32** [comment]
I cleaned the solution then rebuilt it but to no avail.

**Comment by APERSONA32** [comment]
don't worry  its working now   thank you all anyways.
