### ISSUE TITLE
Path Styles?

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#527]
This is kind of a follow up on my previous post but, how do the file system paths works in Cosmos? I have read and reread the document on the file system after my last post and for some reason can't make heads nor tails of the path format.

**Comment by jp2masa** [comment]
0:\path_to_file

**Comment by APERSONA32** [comment]
oh thank again 
 so it something like 
0:\System\User\Downloads?

**Comment by jp2masa** [comment]
Yes, but it's not totally working, I have an opened PR where I'm working on FAT, already fixed files inside folders in certain cases, now I'm implementing LFN, it's almost ready.

**Comment by APERSONA32** [comment]
Do you know what parts are not working? Also what's a PR?

**Comment by MichaelTheShifter** [comment]
Parts that aren't working:

....lots of stuff

PR: Pull Request

**Comment by APERSONA32** [comment]
oh hey I watch you on youtube. and thanks for the information
