### ISSUE TITLE
Installing cosmos to a HDD?

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#528]
Is there a way to create an installer that will install my OS onto actual hardware so the ISO image can be ejected?

**Comment by jp2masa** [comment]
Currently it's not possible to create an installer with Cosmos, to install to an HDD I think you just need to copy the files in the ISO file to the HDD.

**Comment by APERSONA32** [comment]
oh right thank you.

**Comment by Cyber4** [comment]
If you wanna be a bit hacky you could roll a custom linux distro + installer that boots and lets you dd the contents of the iso to a disk of your choosing.  I'd look into adding this but I'm pretty inactive in the whole cosmos project since my one computer running windows died on me awhile back + school and other stuff.

**Comment by APERSONA32** [comment]
Could I not just copy the files from the iso from within the booted Kernel?

**Comment by DjAlEx234** [comment]
Did you try to extract the iso to a usb and then copying it to a hdd on windows, then booted it? Anyways it wont work without the VMware virtualized hardware (Just a question, @Cyber4 are you using a mac then?)

**Comment by APERSONA32** [comment]
Would I bot be able to do that with in VMware?  Is there a way for me to copy the compressed ISO files to the HDD

**Comment by MichaelTheShifter** [comment]
Actually I don't think copying the ISO files directly to the HDD would
work. You'd also need a bootloader that can start Cosmos when the system
finishes POSTing.

Universal USB Installer does this - it creates a syslinux image that starts
when the USB is booted from, which is then configured to boot the relevant
OS - whether it be Windows, Linux, Cosmos, or whatever you throw at it.

I have actually tested this before and it made by Cosmos USB bootable, but
when I copied the files to a blank FAT32 partition on my drive, and
rebooted, the BIOS only allowed booting from one partition - Windows' boot
partition.

So this would probably be where you'd store your boot files, but Windows
won't let you write to that partition (for obvious reasons), and neither
will Cosmos (it doesn't read the filesystem.) So until Cosmos can read the
boot partition in the live environment, installing Cosmos to a hard drive
in an actual bootable form, is impossible.

**Comment by APERSONA32** [comment]
I see. Thank you very much. The help is appreciated

**Comment by carcarjg** [comment]
Sorry to reopen a YEAR's old topic. But has anyone got an update on this? Is it possible now?

And on the topic of boot sectors, I've found a program that can copy a .bin and make it into a boot sector >https://www.codeproject.com/KB/cpp/MakingOS/BOOTSectorUtility.zip

Would this help?

**Comment by alessiobb1** [comment]
But in the VMS is possible?

**Comment by carcarjg** [comment]
I believe it should be now. I haven't messed with it.

**Comment by DoorsDev** [comment]
Sorry to reopen a old thread. But are there any updates to this?
