### ISSUE TITLE
Using. Net framework to build programs for COSMOS OS

### ISSUE THREAD

**Issue by MercedeX** [CosmosOS/Cosmos#529]
I want some guidance. What steps i need to follow if i want to create programs on Cosmos? What framework does it support and to what extent? Can i create programs for cosmos? Does it fly support tcp and sockets for communication?

**Comment by jp2masa** [comment]
Currently Cosmos doesn't support loading programs into memory, so they are part of the OS. Basic networking is on the roadmap for Cosmos 1.0

**Comment by mihail-rotmg** [comment]
Maybe we can code an interpreter to follow instructions from a text file to make programs for a COSMOS OS. But the last time i tried this i ended up with a corrupt filesystem because i think that it didn't support deleting files or something.

**Comment by qjnr** [comment]
Wouldn't it be a better idea to load DLLs with .NET code? That way you don't need to write a whole new language and compiler and executor and whatnot, because the programs are also written in C#.

**Comment by MercedeX** [comment]
if it supports programs that work like all the other programs on other operating systems then perhaps we can use it as something like docker and we can pack dotnet programs with it perhaps?
