### ISSUE TITLE
VGA Problem

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#530]
Hey, yeah me again, sorry but Im having troubles with the VGA in Cosmos. Ive set up all the hardware and rings and all that but every time I start the GUI I get this:

![vga issues 2](https://cloud.githubusercontent.com/assets/24322118/21029711/f43fe5ee-bd92-11e6-95a5-f1d3f562b603.PNG)

Sorry if I'm being annoying but any help would be appreciated. Thank you

**Comment by jp2masa** [comment]
userkit or devkit?

**Comment by APERSONA32** [comment]
devkit

**Comment by jp2masa** [comment]
VGA isn't currently working in the devkit, see #514

**Comment by jp2masa** [comment]
I recommend waiting for the new graphics drivers.

**Comment by APERSONA32** [comment]
Alright.  Any idea in when it will be done?

**Comment by jp2masa** [comment]
It can take weeks, in #514 you can see the progress.

**Comment by APERSONA32** [comment]
Oh. Alright . Thanks for all the help so far
