### ISSUE TITLE
"Cosmos.Build.MSBuild.IL2CPU" task was not found.

### ISSUE THREAD

**Issue by keesvv** [CosmosOS/Cosmos#531]
Hello people!

I am new to Cosmos, but I have a reasonable knowledge of .NET-based coding such as C# and VB.NET.
But I have a little issue.

Whenever I try to debug my project, or build it, this error message comes up in my **Error List**:

`The "Cosmos.Build.MSBuild.IL2CPU" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\14.0\bin" directory.`.

I tried restarting my pc 2 times for now, and I restarted my Visual Studio 2015 a couple of times.
I didn't touch any of the Cosmos configuration files.

Some more information, I use **.NET Framework 4.5.2**.

**EDIT:** I have Visual Studio 2015 installed on my **D:\** drive and my Cosmos User Kit on my **C:\** drive.

**Comment by zarlo** [comment]
userkit or devkit

**Comment by keesvv** [comment]
Thank you for your answer! I'm using the Cosmos UserKit Milestone 4, but I already solved my problem!
