### ISSUE TITLE
Virtual Box Issue

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#533]
Im using the dev kit and every time I try to boot the Cosmos OS ISO in virtual box I get this:

![screen shot 2016-12-14 at 15 43 37](https://cloud.githubusercontent.com/assets/24322118/21188694/1be9470e-c214-11e6-9520-27a854051606.png)

This is on a Mac if that affects anything but I've also tested it on my Bootcamp and I get the same result

**Comment by jp2masa** [comment]
Does the default kernel run?

**Comment by APERSONA32** [comment]
ill try now

**Comment by jp2masa** [comment]
Only Debug mode is supported, to disable Cosmos debug, you have to disable it in the Boot project settings.

**Comment by APERSONA32** [comment]
Will that allow the Kernel to boot in virtual box?

**Comment by jp2masa** [comment]
Setting the project to compile an ISO will not even give you the option to disable debugging. It's disabled.

**Comment by APERSONA32** [comment]
sorry  this may make me seem thick but how would I disable the debugging?

**Comment by jp2masa** [comment]
If you are using the ISO option, debugging is disabled. If you are using VMWare or Bochs, there's a "Debug" tab.

**Comment by APERSONA32** [comment]
The tab that drops down to say debug or release?

**Comment by jp2masa** [comment]
In your Boot project, you can right-click it and in properties you chose a profile right?

**Comment by APERSONA32** [comment]
Yes

**Comment by jp2masa** [comment]
There are tabs like "Profile", "Compile", "Debug"... just go to "Debug" and disable the Remote Debugging option. Don't forget that in the ISO option, there's no Debug tab.

**Comment by APERSONA32** [comment]
oh I see now
I thought you was talking about something entirely different.   Thank you.  Does this fix the issue I'm having in virtual box or not?

**Comment by jp2masa** [comment]
Try it.

**Comment by APERSONA32** [comment]
i will now

**Comment by APERSONA32** [comment]
No it didn't fix it.

**Comment by jp2masa** [comment]
Are you using Virtual Box?

**Comment by APERSONA32** [comment]
To test the ISO image yes

**Comment by jp2masa** [comment]
Try other software like Bochs or VMWare, maybe it's a Virtual Box bug.

**Comment by APERSONA32** [comment]
Possibly

**Comment by APERSONA32** [comment]
Would it work on real Hardware?

**Comment by jp2masa** [comment]
Maybe, but you can have problems with ATA.

**Comment by APERSONA32** [comment]
Alright, thank you very much. I know I must be a pain. Should I close this or leave it open as it is unresolved?

**Comment by czhower** [comment]
I would suggest joining the gitter chat room for "chatty" topics like this.
