### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by EpicestGamer** [CosmosOS/Cosmos#534]
It did not work. The only thing I can think I did wrong is changing the install directory and I cannot figure out where the default location is, as the installer stored my location as the new "default" directory. I cannot fix it by myself.

Please help.

**Comment by jp2masa** [comment]
The default install path is %appdata%/Cosmos User Kit.
Also, what's not working?

**Comment by EpicestGamer** [comment]
I cannot see a Cosmos Type project in Visual Studio Community 2015,

Thank you for fast reply

**Comment by jp2masa** [comment]
With Visual Studio closed, try to run the setup again.

**Comment by EpicestGamer** [comment]
I ran setup again. When it was finished I opened up visual studio and there is still not a Cosmos template.

**Comment by EpicestGamer** [comment]
Oh, odd vs says cosmos is installed when i go into about visual studio.

**Comment by jp2masa** [comment]
Have you tried to restart your computer?

**Comment by EpicestGamer** [comment]
I will try to reboot.

**Comment by EpicestGamer** [comment]
I am not seeing the template yet... I do not know what is wrong, sorry.

**Comment by jp2masa** [comment]
Are you trying to install userkit or devkit?

**Comment by EpicestGamer** [comment]
Userkit.

**Comment by jp2masa** [comment]
Run this in your VS folder: `devenv.exe /setup`

**Comment by EpicestGamer** [comment]
ok, is the path something like C:\Program Files (x86)\Microsoft Visual Studio 14.0 ?

**Comment by jp2masa** [comment]
I think it's in Common7\IDE in that folder.

**Comment by EpicestGamer** [comment]
It ran without errors, but i still do not see the template after starting VS

**Comment by jp2masa** [comment]
Are you installing in the default path?

**Comment by EpicestGamer** [comment]
I re-installed cosmos to my appdata folder, and I have Visual Studio on my C: drive

**Comment by EpicestGamer** [comment]
VS says I have these installed, is anything else that might have been needed for the templates?

Cosmos   User Kit
www.goCosmos.org

Cosmos.VS.Windows   1.0
Cosmos Tool Windows Package

**Comment by jp2masa** [comment]
I can't verify at the moment, but check if the folder Visual Studio 2015\Templates\ProjectTemplates\Cosmos exists in your Documents folder and has 3 zip files in it.

**Comment by EpicestGamer** [comment]
It has 2 zip files in it. One for C# and one for VB

**Comment by EpicestGamer** [comment]
It may be that these files are saved in my Onedrive documents folder and not my user documents folder?

**Comment by jp2masa** [comment]
There should be one for F#, but doesn't seem to be important in this case.

**Comment by EpicestGamer** [comment]
I copied the files to all my other possible documents folders, and i see the templates now, thank you for the help.

**Comment by fanoI** [comment]
Hmm but what caused the issue? 
When you installed UserKit select another directory for installation instead of the default one?

**Comment by EpicestGamer** [comment]
I think it's because I have OneDrive set to have the documents folder known as the documents folder in OneDrive while Visual Studio was still set for my user Documents.

**Comment by jem-green** [comment]
From an userkit installation perspective I have a few comments.

I run all applications as myself and elevate privileges with another account, to install apps etc.. This messes with the cosmos userkit installation. I didn't spot this initially.

1) I note that the cosmos project userkit project templates get installed under the elevated account.
2) I note that the userkit installation folder is by default under the elevated account.

Current resolution was to re-install the userkit to a shared location then create the project as the administrator, exit and then open the project as me. Possible better option is to copy the templates over from the elevated user to me.  I'm guessing that I could have changed the userkit installation folder to me.

Would be good to fix the installer so that whilst I have to elevate privileges to install the folder locations remain as me.

**Comment by zarlo** [comment]
@EpicestGamer are you using VS2015

**Comment by EpicestGamer** [comment]
Yeah.

**Comment by LegitSoulja** [comment]
@EpicestGamer wait, so what did you do?

**Comment by craft-o-s-project** [comment]
========================================
    Build Log
========================================


========================================
    Checking Dependencies...
========================================

Repos: IL2CPU, XSharp and Common is installed.
Proper Cosmos folder name was not found. Install rename the directory from where install-VS2022.bat or userkit install.bat is started to Cosmos.


========================================
    Error
========================================

Proper Cosmos folder name not found.

HELP.

**Comment by zarlo** [comment]
rename the directory from where install-VS2022.bat is to Cosmos

**Comment by craft-o-s-project** [comment]
i did

**Comment by zarlo** [comment]
did that fix it?

**Comment by AudiGlamFAN** [comment]
my problem is "Proper Cosmos folder not found." How to fix it is
