### ISSUE TITLE
realy i need a help for that erorr plz ?

### ISSUE THREAD

**Issue by mselnashar** [CosmosOS/Cosmos#537]
Error	2	Native code encountered, plug required. Please see http://cosmos.codeplex.com/wikipage?title=Plugs). System.String  System.Number.FormatDecimal(System.Decimal, System.String, System.Globalization.NumberFormatInfo).
 Called from :
System.String  System.Decimal.ToString()
System.Decimal

   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 541
   at Cosmos.IL2CPU.ILScanner.ScanQueue() in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 686
   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 277
   at Cosmos.Build.MSBuild.IL2CPUTask.Execute() in g:\IL2CPU\source2\Build\Cosmos.Build.MSBuild\IL2CPUTask.cs:line 239	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	6	osBoot

**Comment by jp2masa** [comment]
What are you trying to do? Use the Convert class?

**Comment by mselnashar** [comment]
sorry show me how plz
that is my code
    public class Kernel : Sys.Kernel
    {
        private static void Restart()
        {
            Console.Clear();
            ACPIManager.ACPI.Shutdown();
            Console.WriteLine(">> :( ");
        }

        protected override void BeforeRun()
        {
            Console.WriteLine("OS ==> Start :) ");
            Console.WriteLine("Welcome to OS");
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.ForegroundColor = ConsoleColor.White;
        }

        protected override void Run()
        {
            Console.WriteLine("*************************");
            Console.WriteLine(" give me a command");
            Console.WriteLine(" only down case accepted");
            Console.WriteLine(" => s\tto shutdown");
            Console.WriteLine(" => r\tto reboot");
            Console.WriteLine(" => p\tto more programes");
            Console.WriteLine("*************************");
            var switcher = Console.ReadLine();
            switch (switcher)
            {
                case "s":
                    {
                        ACPIManager.ACPI.Shutdown();
                    }
                    break;
                case "r":
                    Restart();
                    break;
                case "p":
                    Console.WriteLine("only down case accepted");
                    Console.WriteLine("=> c\tto calculatoer");
                    Console.WriteLine("=> clc\tto calender ");
                    string switcherp = "";
                    switch (switcherp)
                    {
                        case "c":
                            calcoulatoer c = new calcoulatoer();
                            c.calcoulate();
                            break;
                        case "cal":
                            calender cal = new calender();
                            cal.show();
                            break;
                        default: Console.WriteLine("wrong command");
                            break;
                    }
                    break;
                default:
                    Console.WriteLine("not valid");
                    break;
            }
        }
    }
}

**Comment by jp2masa** [comment]
the calcoulatoer class uses decimal?

**Comment by mselnashar** [comment]
that is my output

1>------ Build started: Project: os, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.Hardware, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Cosmos.System, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983, processorArchitecture=MSIL", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Users\MOHAMED\Documents\Visual Studio 2013\Projects\os\os\Kernel.cs(4,7,4,13): warning CS0105: The using directive for 'System' appeared previously in this namespace
1>C:\Users\MOHAMED\Documents\Visual Studio 2013\Projects\os\os\Kernel.cs(14,29,14,36): warning CS0108: 'CosmosKernel3.Kernel.Restart()' hides inherited member 'Cosmos.System.Kernel.Restart()'. Use the new keyword if hiding was intended.
1>C:\Users\MOHAMED\Documents\Visual Studio 2013\Projects\os\os\ACPI.cs(22,30,22,36): warning CS0414: The field 'ACPIManager.ACPI.SCI_EN' is assigned but its value is never used
1>  os -> C:\Users\MOHAMED\Documents\Visual Studio 2013\Projects\os\os\bin\Debug\os.dll
2>------ Build started: Project: osBoot, Configuration: Debug x86 ------
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Native code encountered, plug required. Please see http://cosmos.codeplex.com/wikipage?title=Plugs). System.String  System.Number.FormatDecimal(System.Decimal, System.String, System.Globalization.NumberFormatInfo).
2> Called from :
2>System.String  System.Decimal.ToString()
2>System.Decimal
2>
2>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 541
2>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 686
2>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in g:\IL2CPU\source2\IL2CPU\Cosmos.IL2CPU\ILScanner.cs:line 277
2>   at Cosmos.Build.MSBuild.IL2CPUTask.Execute() in g:\IL2CPU\source2\Build\Cosmos.Build.MSBuild\IL2CPUTask.cs:line 239
2>	IL2CPU task took 00:00:00.7500644
2>Done building project "osBoot.Cosmos" -- FAILED.
2>
Build has been canceled.

**Comment by mselnashar** [comment]
class calcoulatoer
    {
        public void calcoulate() 
        {
            int num1;

            int num2;

            string operand;

            int answer;

 

 

            Console.Write("Please enter the first integer: ");

            num1 = Convert.ToInt32(Console.ReadLine());

 

 

            Console.Write("Please enter an operand (+, -, /, *): ");

            operand = Console.ReadLine();

 

 

            Console.Write("Please enter the second integer: ");

            num2 = Convert.ToInt32(Console.ReadLine());

 

            switch (operand)

            {

                case "-":

                    answer = num1 - num2;

                    break;

                case "+":

                    answer = num1 + num2;

                    break;

                case "/":

                    answer = num1 / num2;

                    break;

                case "*":

                    answer = num1 * num2;

                    break;

                default:

                    answer = 0;

                    break;

            }

 

            Console.WriteLine(num1.ToString() + " " + operand + " " + num2.ToString() + " = " + answer.ToString());

 

            Console.ReadLine();

        }

    }
        }

**Comment by jp2masa** [comment]
Instead of Convert.ToInt32(Console.ReadLine()); you can use int.TryParse(Console.ReadLine()); or you can update to the latest devkit, where Convert is working.
