### ISSUE TITLE
un-hardcode BGA linear frame buffer addresss

### ISSUE THREAD

**Issue by cjhannah** [CosmosOS/Cosmos#538]
edit: forgot to add description.
the memoryblock08 for the linear frame buffer has the address hardcoded. it states in the osdev wiki it should be read from the BGA's PCI bar0.

**Comment by cjhannah** [comment]
this should be done soon because this means only ISA is supported for BGA

**Comment by charlesbetros** [comment]
Do you want to try fixing this? If you  do, head over to the chat for guidance. Pull requests are always welcomed!

**Comment by cjhannah** [comment]
i can try
