### ISSUE TITLE
Honestly, one doesnt quite know what to name this error.

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#541]
When ever I try to use:

FileSystem.ListDirectories(PATH_HERE);

I get this one screen:

![capture](https://cloud.githubusercontent.com/assets/24322118/21442896/dfcd0bda-c898-11e6-922c-0e6522777a43.PNG)

Also, I hope this doesn't break any rules, I'm having trouble with creating a folder with in a folder.

**Comment by jp2masa** [comment]
Object.ToString() is not implemented, why are you calling ToString() on an object with no specific type?
The problem of the folder inside folder is probably fixed in #522 but it hasn't been merged yet, and it may be a bit unstable too.

**Comment by APERSONA32** [comment]
but that's the ting   I don't think I'm calling a ToString(). Here is a screen shot of my code;

![capture](https://cloud.githubusercontent.com/assets/24322118/21443050/ef283cca-c899-11e6-8464-15296ae6a27e.PNG)

and thank you for the folder inside another foldere

**Comment by jp2masa** [comment]
what is FileSystem.ListDirectories() ?

**Comment by APERSONA32** [comment]
![capture](https://cloud.githubusercontent.com/assets/24322118/21443117/840be3d2-c89a-11e6-8840-c4c6b4157982.PNG)

**Comment by jp2masa** [comment]
```
string[] List = Directory.GetDirectories(DirectoryPath);

foreach (string dir in List)
{
    Console.WriteLine(dir);
}
```

**Comment by APERSONA32** [comment]
Thank you so much, i've been stuck with this for ages
