### ISSUE TITLE
Cosmos should support all the CP437 characters not only the ASCII ones

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#544]
When a layout different from US is used keyboards have accented characters like 'è', 'ò', 'ß' (not the Greek letter but the Germanic Ess-Zed) these characters are not printed or printed wrongly by Cosmos.

Console.WriteLine() indeed assumes that all characters are ASCII and so it does not the proper conversion from UTF-16 (the internal encoding of .NET Char type) to CP437 (the encoding used by the terminal).
The opposite need to be done to make Console.ReadLine() work with there type of characters.

**Comment by geomtech** [comment]
Method replacement:

Console.WriteLine((char)130);

http://www.theasciicode.com.ar/extended-ascii-code/letter-e-acute-accent-e-acute-lowercase-ascii-code-130.html

Replace 130 by your ascii char

**Comment by fanoI** [comment]
To do this in the correct way we need before as pre-requisites to have the C# Encoding and Decoding classes working at least for UFT-16 (the native String encoding) and CP437 (the default encoding of the terminal).

For example we need to have this simple code working:

```cs
byte
Encode(char aChar, int codepage)
{
  String s = aChar.ToString();
  
  Encoding e = Encoding.GetEncoding(437);
  return e.GetBytes(s)[0];
}

void Main()
{
	char c = 'è';
	byte b = (byte)c;
	
	Console.WriteLine($"c as latin1 {b}");
	Console.WriteLine($"c in CP437 {Encode(c, 437)}"); // must print 138
	
	Console.WriteLine($"╢ in CP437 {Encode('╢', 437)}"); // must print 182
}
```
So start making a TestRunner for this.

When this works we can affront the problem at least for Console.Write() / Console.WriteLine().
The issue is here in this indexer: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL/TextScreen.cs#L64 that assumes that to convert a UTF-16 char to a byte simply a cast is sufficient well it is not and you get garbage on screen  :-)
So you must apply the Encode method above to the set method and you are done.

To solve the issue of Console.ReadKey() / ReadLine() is easier now as you must simply do the Decode in the getter.

To make things more clear - at this point - one could use the properties InputEncoding / OutputEncoding instead to hardcoded CP437 (CP437 should be the default).

**Comment by fanoI** [comment]
CosmosOS/Cosmos#717 fixes partly the issue we can now Write accented characters on the Console and not only them but more importantly "semi-graphics" characters so it is possible for example to draw tables and with more efforts one could try to do thing similar to Ncurses or TurboVision in C#...

Now it is missing the other way around I've an Italian keyboard and I want to press 'è' and that Console.ReadKey() / ConsoleReadLine() return that character not some "random" Char :-)

**Comment by jp2masa** [comment]
That's related to keyboard scan maps. We will have to change the scan map system a bit, because we should convert scan codes to an internal code that always represents the same key, but that needs to be done after the rings changes.

**Comment by fanoI** [comment]
Right the key itself is not read form the Console but directly from the keyboard so yes probably is there that need to be fixed...

**Comment by fanoI** [comment]
This has been done.
