### ISSUE TITLE
Memory Information class

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#546]
A Class that gives information regarding system memory how much is installed, how is used, how much is free and so on...

**Comment by ROBLOXVIP735** [comment]
There's a bit of an issue with this. This would mean communicating directly to the BIOS, which means that you'd need to make an entire system for that. Atleast for the x86 series of assembly. x64 components are of their own systems, which makes it even harder to communicate between both.

**Comment by fanoI** [comment]
Do you say there is no way to get memory information in protected mode?

**Comment by ROBLOXVIP735** [comment]
While there is a way... it just takes a direct assembly code approach to it. Atleast that's how it is over in California.

Welcome to California, where for some reason, literally all systems built here are really different to the rest of the world. And they're cheaper and really bad. And then overpriced.


And then mad-okay I'll stop with the joke.

**Comment by Arawn-Davies** [comment]
- [x] Amount of memory installed is already added
- [ ] Amount of memory in use
- [ ] Amount of memory free (Memory installed - Memory in use?)
Can't think of much else, speed of RAM?
More stuff, including potential implementations can be found at https://wiki.osdev.org/Detecting_Memory_(x86)

**Comment by MishaTY** [comment]
Implemented in new memory manager.
