### ISSUE TITLE
Error with the properties.

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#547]
When ever I try to open the Boot class properties I get this error::
![capture](https://cloud.githubusercontent.com/assets/24322118/21484729/5dfd9832-cb8f-11e6-8ee9-e2a86d38fe46.PNG)
Does anyone know hoe to fix it?

**Comment by cjhannah** [comment]
uninstall driver kit

**Comment by APERSONA32** [comment]
as in the dev kit?

**Comment by jp2masa** [comment]
If you have Windows Driver Kit(WDK) uninstalling it will probably work.
If you don't have it, please pastebin your project files(.csproj and .Cosmos).

**Comment by APERSONA32** [comment]
Brilliant  its working fine now. Thank you

**Comment by jp2masa** [comment]
How did you fix it?

**Comment by APERSONA32** [comment]
Honestly I don't know. I know I had to reinstall Windows as there was an issue with my Bootcamp drive. I just did a clean install of everything and now it works fine.
