### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#548]
Currently I only have Macs at home, and its really a pain to use the bootcamp windows as its not activated yet. Now Microsoft has released a version of visual studio forOS X I was wondering if there will be a version of Cosmos for that as well.

**Comment by jp2masa** [comment]
There are no plans currently for VS for Mac, what doesn't mean Cosmos won't support it one day, but probably not so soon.

**Comment by APERSONA32** [comment]
I see. sorry for the not really useful post  just curious .  thanks.
