### ISSUE TITLE
UserKit and Dev Kit?

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#549]
Can I use aspects from both kits in the same project?

**Comment by jp2masa** [comment]
What do you want to use from both kits?

**Comment by APERSONA32** [comment]
The Display from the User Kit and the FAT System from the Dev Kit

**Comment by jp2masa** [comment]
I think you should wait for the graphics changes, you can see the progress in #514

**Comment by APERSONA32** [comment]
Alright. Thank you. And sorry for being such a pain.
