### ISSUE TITLE
Error occured whilst invoking IL2CPU

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#551]
The output message is::

> 1>------ Build started: Project: Teremity System One, Configuration: Debug x86 ------
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,31,14,40): warning CS0649: Field 'SystemConfigurations.Dark_Blue' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,76,14,88): warning CS0649: Field 'SystemConfigurations.Dark_Magenta' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,13,14,19): warning CS0649: Field 'SystemConfigurations.Yellow' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,53,14,62): warning CS0649: Field 'SystemConfigurations.Dark_Gray' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,64,14,74): warning CS0649: Field 'SystemConfigurations.Dark_Green' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,42,14,51): warning CS0649: Field 'SystemConfigurations.Dark_Cyan' is never assigned to, and will always have its default value
1>C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\System\SystemConfigurations.cs(14,21,14,29): warning CS0649: Field 'SystemConfigurations.Dark_Red' is never assigned to, and will always have its default value
1>  Teremity System One -> C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System One.dll
2>------ Build started: Project: Teremity System OneBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System OneBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" "References:C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System One.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System OneBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" "References:C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System One.dll" 
2>	Working directory = 'C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Int32  System.Globalization.CompareInfo.InternalCompareString(System.IntPtr, System.IntPtr, System.String, System.String, System.Int32, System.Int32, System.String, System.Int32, System.Int32, System.Int32).
2>	 Called from :
2>	System.Globalization.CompareInfo::Int32 Compare(System.String, System.String, System.Globalization.CompareOptions)
2>	System.Globalization.CompareInfo::Int32 Compare(System.String, System.String)
2>	System.Collections.Comparer::Int32 Compare(System.Object, System.Object)
2>	System.Collections.IComparer::Int32 Compare(System.Object, System.Object)
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Charlie\Downloads\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 522
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Charlie\Downloads\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 663
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Charlie\Downloads\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 243
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Charlie\Downloads\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\Charlie\Desktop\Teremity System One\Teremity System One\bin\Debug\Teremity System One.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\Charlie\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Memory.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.6410622
2>Done building project "Teremity System OneBoot.Cosmos" -- FAILED.
2>
Build has been canceled.

**Comment by charlesbetros** [comment]
Are you using Equals or Contains?

**Comment by APERSONA32** [comment]
To be completely honest  I have no idea

**Comment by charlesbetros** [comment]
Will need to see your kernel code then.

**Comment by APERSONA32** [comment]
Okay, here it is::

`using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Teremity_System_One
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.BackgroundColor = ConsoleColor.White;
            Console.ForegroundColor = ConsoleColor.DarkBlue;
            Console.Clear();
            Console.WriteLine("PLEASE NOTE:: THE FAT FILESYSTEM USED IS IN DEVELOPMENT. IT IS RECOMENEDED TO");
            Console.WriteLine("DISABLE THIS FEATURE WHEN TESTING ON REAL HARDWARE.(THIS CARRIES NO WARRENTY)");
            Console.Write("Would you like to use the FS? (Y/N)>");
            string FSONBOOL = Console.ReadLine().ToUpper();
            if (FSONBOOL == "YES" || FSONBOOL == "Y")
            {
                FileSystem.Initiate();
                SystemConfigurations.FSON = true;
            }
            else if (FSONBOOL == "NO" || FSONBOOL == "N")
            {
                SystemConfigurations.FSON = false;
                Console.WriteLine("Filesystem Disabled. Please press enter to continue:");
                Console.ReadLine();
            }
            Console.Clear();
            string Title = "::Teremity System One::";
            Console.SetCursorPosition((Console.WindowWidth/2 - Title.Length/2), 0);
            Console.WriteLine(Title);
            UserController.RootUserSet();
            if (SystemConfigurations.FSON == true)
            {
                FileSystem.DirectoryChecks();
            }
        }

        protected override void Run()
        {
            Console.WriteLine();
            Console.Write("Command>");
            string CommandInput = Console.ReadLine().ToUpper();
            if (CommandInput.Contains("!"))
            {
                if (CommandInput == "!HELP")
                {
                    Commands.CLIHelp();
                } 
                else if (CommandInput == "!ADVHELP")
                {
                    Commands.AdvHelp();
                }
                else if (CommandInput == "!ABOUT")
                {
                    Commands.About();
                }
                else if (CommandInput == "!LIST")
                {
                    Commands.List();
                }
                else if (CommandInput == "!CLEAR")
                {
                    Commands.Clear();
                }
                else if (CommandInput == "!LAUNCH")
                {
                    Commands.Launch();
                }
                else if (CommandInput == "!STARTGUI")
                {
                    Commands.GUI();
                }
                else if (CommandInput == "!REBOOT")
                {
                    Commands.Reboot();
                }
                else if (CommandInput == "!DEBOOT")
                {
                    this.Stop();
                }
                else
                {
                    Commands.ErrUnK();
                }
            }
            else
            {
                Commands.ErrPF();
            }
        }
    }
}`

**Comment by charlesbetros** [comment]
CommandInput.Contains(string), I am pretty sure Contains isn't plugged yet. (Haven't looked in a while) Try using IndexOf(string) >= 0 instead.

**Comment by APERSONA32** [comment]
I figured it out. The CommandInput.Contains() was fine, it was the use of an Array List. I'm assuming this is an issue with the 'plugs' so my question is. How would I 'plug' this?

**Comment by jp2masa** [comment]
That's probably a problem with generics, plugs won't solve it.

**Comment by APERSONA32** [comment]
oh alright.

**Comment by mterwoord** [comment]
@jp2masa We have issues with generics?? Highly doubt it.

Probably contains needs something like interfaces or string comparisons etc, but generics isn't the problem. Maybe someone can make a test for this?

**Comment by jp2masa** [comment]
I was talking about the support for arrays as generic types, I don't know if they are supported, I'll test them then.

**Comment by jp2masa** [comment]
I was thinking, List<T> relies on IEnumerable<T>, which is an interface, do we support generic interfaces, being the generic type an array?

**Comment by jp2masa** [comment]
I tested this using a List<string[]> and it worked fine, maybe it's the use of some array method, probably to find an element or something like that.

**Comment by APERSONA32** [comment]
Hey. I don't know if I should put this here but I switched from using ArrayList() to using List<> and it worked fine but when I try to get the index of a string in the list the screen of the Virtual machine turns black and then the machine closes. Any idea what is causing this?

**Comment by jp2masa** [comment]
Probably you are using VMWare, try Bochs, it won't close and will say what the error is.

**Comment by APERSONA32** [comment]
oh okay

**Comment by charlesbetros** [comment]
Are you using indexof()?

**Comment by APERSONA32** [comment]
yeah

**Comment by APERSONA32** [comment]
I tried with bochs. An Error is thrown saying ::
Warning : HLT instruction with IF=0!

Also when the machine started the screen kept flashing

**Comment by electrodeyt** [comment]
Having the same issue with the Test code in VB.

**Comment by quajak** [comment]
Similar issue to https://github.com/CosmosOS/Cosmos/issues/584.
