### ISSUE TITLE
Mode 200 on installer.bat file

### ISSUE THREAD

**Issue by ROBLOXVIP735** [CosmosOS/Cosmos#555]
Okay, this is just nitpick, but please add mode 200 to both installer .bat files, so I can read the commands without them word wrapping please.
If you need me to, I will install said lines.

**Comment by jp2masa** [comment]
You can customize your installer .bat files, but I think that not everyone wants mode 200.

**Comment by ROBLOXVIP735** [comment]
Do you know what mode 200 is?

And it gets annoying when I have to manually do it myself. Perhaps I'll make an auto launcher...

**Comment by jp2masa** [comment]
I think you can add:
```
@echo off
mode 200
```
at the start of the installer .bat file.

**Comment by charlesbetros** [comment]
There isn't a whole lot to read in the install.bat. A nuget restore and a call to msbuild. Just pipe the output to a file or build it in VS for the output. Mode is legacy so no reason to add it.

**Comment by OffensiveCheese** [comment]
Close this?
