### ISSUE TITLE
Devkit build issues

### ISSUE THREAD

**Issue by jem-green** [CosmosOS/Cosmos#556]
Feedback on the devkit install for VS2015

1) Initially had issues with the zipped version of the devkit, seemed a bit wrong only had install.bat
    Resolved by downloading from git directly, and has install-VS2015.bat
2) running the build as a user doesn't work, even elevating privileges during the initial phase didn't work.
   Need to open a command shell as administrator and run install from there.
3) Had issues with the userkit conflicting with the devkit version
  Needed to delete the userkit files, then run install-VS2015.

**Comment by jp2masa** [comment]
1. What zipped version? Download ZIP in Github?
2. The installer copies some files to folders that need elevated privilieges, like the Visual Studio folder.
3. Installing the devkit should simply replace the userkit files with updated ones, maybe a priviliege problem?

**Comment by jem-green** [comment]
1. This is the version I had issues with - https://github.com/CosmosOS/Cosmos/wiki/How-to-install-Cosmos#what-is-the-devkit - v2015-01-30.zip - Best to get from GitHub directly.
2. Yes but the installer prompts for a privileged account and then fails to complete the install, so for newbies like me its tricky.
3. Nope - Installing the devkit doesn't replace the userkit files in their original location. Easiest way for me was to run the newly created userkit exe and it put the files in the correct location, then the devkit builds fine. Again for a newbie needed help from the cosmos gitters..

**Comment by jp2masa** [comment]
The wiki really needs to be updated, as there's a more recent stable version, even if a bit old. Also, you'll probably want to use the devkit only if you want the latest version from github, so it makes no sense to dowload the devkit of a stable release.

**Comment by VladintTech** [comment]
Try unblocking the files. More detail is in one of the comments in:   
#1286
