### ISSUE TITLE
Couldn't load file or assembly

### ISSUE THREAD

**Issue by unknowndude1** [CosmosOS/Cosmos#557]
I have made an OS with visual studio 2010/Cosmos user kit, but when I debug or release it, an error popes up as shown on the attachment. Please help

Cosmos c# operating system
![capture](https://cloud.githubusercontent.com/assets/24883579/21663639/546d2a54-d296-11e6-9279-f57ff2f048f2.PNG)

**Comment by jp2masa** [comment]
That Cosmos version is old, try reinstalling it. If it doesn't work, I recommend you to update to the latest userkit or the devkit, but they don't support VS 2010.

**Comment by fanoI** [comment]
the actual Cosmos version supports VS2015

**Comment by unknowndude1** [comment]
I upgraded to VS2013 because VS2015 won't install. I have the latest userkit for VS2013. Same affect but it now appears in the output bar. I don't think it is a problem with the version.

**Comment by mihail-mojsoski** [comment]
@unknowndude1 I *upgraded* to Windows XP because Windows Vista wasn't working.

**Comment by jp2masa** [comment]
@unknowndude1 What is that Driver assembly? Maybe you need to update the references to the Cosmos libraries? The libraries that your kernel project should have are Cosmos.Debug.Kernel and Cosmos.System. You can also create a new Cosmos project and copy your code to that project.

**Comment by unknowndude1** [comment]
I solved it! I deleted the project Drivers and referenced Cosmos.Hardware via using. I Instaed set the graphics mode correctly and used screen.SetPixel320x200x8();.
