### ISSUE TITLE
String.Startswith

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#558]
When I use input.StartsWith with this code :
 if (input.StartsWith( "shutdown"))
            {
                    Console.Clear();
                    Console.WriteLine("Le systeme est pret a s'arreter");
                    
            }
I have this on VMWare
String.Startswith not working ! 
Exception occured while run cosmos

**Comment by jp2masa** [comment]
Userkit or Devkit?

**Comment by valentinbreiz** [comment]
Userkit

**Comment by fanoI** [comment]
Userkit is really old please use the DevKit there a lot of improvements.

**Comment by valentinbreiz** [comment]
Ok I use now the Devkit and I no longer have this problem !
