### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#559]
Constant screen flickering in bochs when running my kernel. Does anyone know how to fix this?

**Comment by jp2masa** [comment]
Graphics are being improved, see #514 and #536

**Comment by APERSONA32** [comment]
Its not a VGA or VBE thing. its the console that's keeps flickering.

**Comment by jp2masa** [comment]
Do you have a screenshot that shows the issue? Are you using the userkit or the devkit? Are you clearing the screen very often?

**Comment by jp2masa** [comment]
Some types of comparisons aren't implemented, I think it's generic comparisons.

**Comment by APERSONA32** [comment]
you want me to send a video of the screen flickering?
or the code?  


oh alright  thanks

**Comment by jp2masa** [comment]
Are you conparing List objects or elements of List objects?

**Comment by APERSONA32** [comment]
` class UserController
    {
        public static List<string> Users = new List<string>();
        public static List<string> Passwords = new List<string>();

        public static void RootUserSet ()
        {
            Console.WriteLine("Setting Root User . . .");
            Users.Add("Root");
            Console.WriteLine("User Added. Setting Root User Password");
            Passwords.Add("Root");
            Console.WriteLine("Password Set.");
            Console.WriteLine("Root User Set. Would you like to create another user? (Y/N)");
            Input:
            Console.Write(">");
            string Input = Console.ReadLine().ToUpper();
            if (Input == ("Y") || Input == ("YES"))
            {
                Console.Write("UserName >");
                string Name = Console.ReadLine();
                Console.Write("Password >");
                string Password = Console.ReadLine();
                AddUser(Name, Password);
            }
            else if (Input == "N" || Input == "NO")
            {
                Console.WriteLine("You will now be logged in with root privileges");
            }
            else
            {
                Console.WriteLine("Unknown input.");
                goto Input;
            }
        }
        /*
        public static ArrayList Users = new ArrayList();
        public static ArrayList Passwords = new ArrayList();

        public static void RootUserSet ()
        {
            Console.WriteLine("Setting Root User. . . ");
            Users.Add("ROOT");
            Passwords.Add("Root23");
            Console.WriteLine("Root Username > ROOT");
            int RIndex = Users.BinarySearch("Root");
            Console.WriteLine("Root User index > " + RIndex.ToString());
            Console.WriteLine("Root User Password > Root23");
        }*/

        public static void AddUser (string Name, string Password)
        {
            Users.Add(Name);
            Passwords.Add(Password);
            int index = Users.IndexOf(Name);
            Console.WriteLine(index.ToString());
        }
    }
}`


Here's the code
`

**Comment by jp2masa** [comment]
I think IndexOf isn't working on List objects.

**Comment by APERSONA32** [comment]
Right I see. Is there a way around it?

**Comment by jp2masa** [comment]
I'm not sure if the enumerator keeps the order of the List elements, but you can try to use a foreach:
```
int i = 0;
foreach (var user in Users)
{
    if (user == userToGetIndex)
        return i;
    i++;
}
```

**Comment by APERSONA32** [comment]
Will this allow me to compare between the two lists.

I kind of wanted to try and set up a password and username system using this.  And the theory behind it is  abit long for here but the basis is. A person would enter a username and password. Then when logging in, the computer would take the value of the username and if valid find its position in the list, then compare this position to that is the password and get the string in that position in the password list. Then compare that value to the one the user has entered.

**Comment by jp2masa** [comment]
If the enumerator keeps the order of a List element, the index of a username is the same as the index of its password.

**Comment by APERSONA32** [comment]
brilliant   thanks you.  Do you have a solution for the console flickering or is that just a bochs thing.  it doesn't happen in VMWare

**Comment by fanoI** [comment]
Do you have set the cursor to blink maybe? That code worked when I did my work on Console but now does not work anymore...

**Comment by APERSONA32** [comment]
No I don't. Would you like to see the before run code?

**Comment by fanoI** [comment]
yes thank you!

**Comment by APERSONA32** [comment]
![capture3](https://cloud.githubusercontent.com/assets/24322118/21958641/bd047da8-daaa-11e6-954d-33209777d236.PNG)

There you go.

**Comment by jp2masa** [comment]
Try adding this in the start of BeforeRun():
```
Console.CursorVisible = false;
```

**Comment by APERSONA32** [comment]
The console is still flickering.

**Comment by jp2masa** [comment]
Bochs is usually much slower than VMWare, so if you want it to run fast use VMWare.

**Comment by fanoI** [comment]
But the screen flickering is in any case a bug I need to have the time to understand what is changed from my version that worked... is possible that something is changed elsewhere and broken it!

**Comment by fanoI** [comment]
#535

**Comment by KingLuigi4932** [comment]
@APERSONA32 @fanoI The screen blinking bug is because on VMware, VMware has it's own screen that doesn't even make the cursor blink, on bochs and real hardware they have real screen device that blinks and do much stuff (i think)
