### ISSUE TITLE
Delete a file or directory ?

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#560]
I don't know how to delete a file or directory with the cosmos Devkit.. can you help me please ?

**Comment by jp2masa** [comment]
You can simply use `File.Delete` and `Directory.Delete`. It can have bugs.

**Comment by valentinbreiz** [comment]
Oh thanks !
File.Delete(current_directory + filer); works good but
Directory.Delete(current_directory + dirr); don't.. Why ?

**Comment by jp2masa** [comment]
It doesn't get deleted or you get an error?

**Comment by jp2masa** [comment]
I remembered now that there's a problem with directories that I fixed in PR #522 but it still needs to be reviewed, if you want you can install the devkit from that branch or wait until it gets merged.

**Comment by valentinbreiz** [comment]
It crash VMWare with that subliminate text :
"Exception occured while running kernel :
Exception : Specifified argument was out of the range of valid values.
Parameter name : aFirstCluster

**Comment by jp2masa** [comment]
That's the bug I fixed in that PR.

**Comment by valentinbreiz** [comment]
And I have that bug...

**Comment by valentinbreiz** [comment]
What can I do to fix that ? .-.

**Comment by jp2masa** [comment]
As I said, you can wait that the PR gets merged(may take some time, because we are focusing on .net core right now) or you can clone the branch of the PR and install it as you do with every devkit.

**Comment by valentinbreiz** [comment]
Oh ok thank you !
And thanks for your work !

**Comment by valentinbreiz** [comment]
![yey](https://cloud.githubusercontent.com/assets/18724279/21964224/479b39c8-db48-11e6-9eb6-5da0df32dd49.PNG)
It work !!! THANK YOU xD
