### ISSUE TITLE
Reset filesystem on with VMWare ?

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#561]
There is a way to delete the Filesystem.vmdk ?
Or just delete all the FileSystem ?

**Comment by jp2masa** [comment]
Cosmos currently can't format a disk, so if you want to reset the FileSystem, simply replace Filesystem.vmdk with a blank vmdk.

**Comment by valentinbreiz** [comment]
![capture](https://cloud.githubusercontent.com/assets/18724279/21967264/de002aa0-db83-11e6-80e2-6c801e4b22e0.PNG)
When I replace with a blank vmdk I get that .-.

**Comment by jp2masa** [comment]
Blank vmdk is not a blank file, you need to create a vmdk file.

**Comment by valentinbreiz** [comment]
Oh ok !

**Comment by valentinbreiz** [comment]
For those wou want a .vmdk file to reset Cosmos Files : https://github.com/CosmosOS/Cosmos/raw/master/Build/VMWare/Workstation/Filesystem.vmdk
