### ISSUE TITLE
VMWare crash when file deleted

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#562]
When the System boot :
var fileexist = File.Exists("0:\\System1\\install.txt");
The code when I reinstall the system :
else if (input.StartsWith("reinstall system"))
            {
                running = false;
                Console.WriteLine("Reinstallation en cours...");
                Console.WriteLine("Suppression des fichiers...");
                File.Delete("0:\\System\\user.txt");
                File.Delete("0:\\System\\install.txt");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("[OK]");
                Console.ForegroundColor = ConsoleColor.White;

                Console.WriteLine("Suppresion des dossiers...");
                Directory.Delete("0:\\System1");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("[OK]");
                Console.ForegroundColor = ConsoleColor.White;
                Sys.Power.Reboot();
            }
And when I tap reinstall system I can see "Reinstallation en cours...", "Suppression des fichiers..." but VMWare crash and I have that message box : 
![capture](https://cloud.githubusercontent.com/assets/18724279/21967373/8a8c1df0-db85-11e6-969a-ab87ee4c90a3.PNG)
And an another biggest ...
Why ? .-.

**Comment by jp2masa** [comment]
Some object is null, search 020c47cf in the .map file in the Debug folder.

**Comment by jp2masa** [comment]
Also, please don't create issues for every problem you have, ask in the gitter chat.

**Comment by valentinbreiz** [comment]
Ok sorry

**Comment by APERSONA32** [comment]
Hey, I'm also having this issue. What software do I use to open the .map file?

**Comment by jp2masa** [comment]
Are you still getting this error?
