### ISSUE TITLE
ISO and VMWare

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#563]
All works fine with my project when I build the MyOsBoot with VMWare.
I can build it with ISO, no errors. But when I launch the ISO with VMWare (no Visual Studio, just the Software) it work but when I try for exemple the "dir -l" command I got an error and VMWare freeze with that message box : The CPU has been disabled by the guest.......
A capture of the freeze :
![capture](https://cloud.githubusercontent.com/assets/18724279/22004502/444dcca8-dc5c-11e6-811f-5a61d4d0b1e7.PNG)
This is normal ?

**Comment by jp2masa** [comment]
Maybe it's a bug, what code are you using?

**Comment by valentinbreiz** [comment]
Just that : 
And in the BeforeRun
            {
                Console.WriteLine("Type\t     Nom");
                foreach (var dir in Directory.GetDirectories(current_directory))
                {
                    Console.WriteLine("<Dossier>\t" + dir);
                }
                foreach (var dir in Directory.GetFiles(current_directory))
                {
                    Console.WriteLine("<Fichier>\t" + dir);
                }

}

**Comment by jp2masa** [comment]
If it works when you start it from VS, maybe you are using the wrong ISO.

**Comment by fanoI** [comment]
Look at the exception: the filesystem is not recognized!
I suspect there are not FAT drives mounted but only the ISO (CD-ROM) itself...

**Comment by valentinbreiz** [comment]
In C:\Users\xxxx\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation

**Comment by jp2masa** [comment]
You created a new virtual machine right? It needs to have an associated vmdk that is formatted in fat.

**Comment by fanoI** [comment]
@valentinbreiz yes in that directory you should find a .vmx file that VmWare should be able to run simply double click on it!

**Comment by valentinbreiz** [comment]
Ok I will try this evening !
And it is possible to save datas and boot with Vmware from a USB ?

**Comment by fanoI** [comment]
I'm unsure if VmWare supports boots from USB (last time I tried booted only from Floppy and CD-ROM), in any case I'm unsure that Cosmos supports USB drives.

**Comment by valentinbreiz** [comment]
And with CDrom it didn't work ?

**Comment by fanoI** [comment]
I think ISO file system is not supported, our plan is first to make all file related things work with FAT and then ISO could be the next one to support.
