### ISSUE TITLE
File System Issue

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#564]
Hey, When I try to delete a folder I get this message from Bochs::
![capture4](https://cloud.githubusercontent.com/assets/24322118/22041355/7aa260be-dcfe-11e6-9c30-669f864a9583.PNG)

Would anyone be able to help me please?

**Comment by jp2masa** [comment]
I have a PR(#522), which is not completely ready to merge, and it has a fix for that issue. If you want, you can try to use it, that bug is fixed for sure.

**Comment by APERSONA32** [comment]
Yeah sure, Do I downloaded it from your git?

**Comment by jp2masa** [comment]
`git clone https://github.com/jp2masa/Cosmos.git -b Bugfixes`

**Comment by APERSONA32** [comment]
Paste that into CMD??

**Comment by jp2masa** [comment]
Open a command line in a folder, after executing that, a folder called Cosmos will be created, just open that folder and run install-VS2015.bat

**Comment by APERSONA32** [comment]
oh alright  thanks.

**Comment by jp2masa** [comment]
I thought you had git installed, download this: https://github.com/jp2masa/Cosmos/archive/Bugfixes.zip

**Comment by APERSONA32** [comment]
Is there anything I have to do to start using this version or do I just run the install

**Comment by jp2masa** [comment]
Just run the install.

**Comment by APERSONA32** [comment]
great thanks. Sorry for being such a pain

**Comment by APERSONA32** [comment]
I'm still getting the same error in bochs

**Comment by jp2masa** [comment]
Try rebuilding the project.

**Comment by APERSONA32** [comment]
Still persisting with the same message

**Comment by jp2masa** [comment]
What code are you using?

**Comment by APERSONA32** [comment]
![capture6](https://cloud.githubusercontent.com/assets/24322118/22042462/449d1806-dd03-11e6-8f8b-986a2c7020dd.PNG)

**Comment by jp2masa** [comment]
Does the directory exist?

**Comment by APERSONA32** [comment]
yeah

This is a screen shot from all of the files being listed 
![capture5](https://cloud.githubusercontent.com/assets/24322118/22042517/747f942c-dd03-11e6-966e-69cb32fe5e51.PNG)

**Comment by jp2masa** [comment]
Is the directory created by your OS or you are using a custom vmdk?

**Comment by APERSONA32** [comment]
created by the OS

**Comment by APERSONA32** [comment]
Should I try making one in the same session?

**Comment by jp2masa** [comment]
Clean your bin/Debug folder and run your project.

**Comment by APERSONA32** [comment]
okay

**Comment by jp2masa** [comment]
The TestRunner always resets the vmdk file, so I'm always forgetting that the vmdk in normal projects doesn't get reset.

**Comment by APERSONA32** [comment]
No, still the same message. But when I did start the system it listed all the files that were already on the virtual disk. The ones that I didn't create during that seeiosn

**Comment by jp2masa** [comment]
Did you run install-VS2015.bat and it opened Cosmos.sln in Visual Studio when it finished?

**Comment by APERSONA32** [comment]
yeah.

**Comment by jp2masa** [comment]
It should be working, I have no idea why it's not working.

**Comment by APERSONA32** [comment]
should I try a clean install?  Or maybe write a new project?

**Comment by jp2masa** [comment]
There are problems with privileges in installation, try a clean install.

**Comment by APERSONA32** [comment]
how do I uninstall Cosmos?  Through programs and Features

**Comment by jp2masa** [comment]
Yes

**Comment by APERSONA32** [comment]
Is this Cosmos that opens automatically bootable?

**Comment by jp2masa** [comment]
Bootable? What do you mean?

**Comment by APERSONA32** [comment]
will it run in a virtual machine? or is it just showing us code examples?

**Comment by jp2masa** [comment]
That Cosmos that opens is the source code of Cosmos

**Comment by APERSONA32** [comment]
ooh right I see
I have also tested my OS and I cant Delete the TEST Folder. I'm going to try and see if I can delete on the of the ones I create from within the OS

**Comment by APERSONA32** [comment]
Right I managed to delete a folder.  So I have no ide why it wont delete that one Specific folder

**Comment by jp2masa** [comment]
I'll need to debug it, I'll check it tomorrow if I have time.

**Comment by APERSONA32** [comment]
alright.  Thanks for the help anyway  really appreciated. Should I close this issue?

**Comment by jp2masa** [comment]
Keep it opened.

**Comment by APERSONA32** [comment]
okay

**Comment by jp2masa** [comment]
I updated my branch, so this issue should be fixed.
Thank you for testing this code and reporting this bug, if you find more bugs please let me know.
