### ISSUE TITLE
A plan for the world's 

### ISSUE THREAD

**Issue by caonima2900445768** [CosmosOS/Cosmos#566]
I have a Suggestions to Comsmos, research and development team can turn it into a visual developing operating system tools, like Winform development, could you use the underlying language, such as assembly language defining some can run under the bare-metal controls (or you write the underlying bootstrap, those controls in the above), such as Windows, buttons, labels... When a user use Comsmos on Visual Studio development, to make it look like very ordinary winform development, fully visualization, only need to drag and drop a few controls, set the attribute, and then simply define some code, an operating system is done!
I firmly believe that this is across the feats of The Times, it can break the monopoly of the Microsoft and apple system, everyone can write operation system, that even as the achievement of the industrial revolution! 

Thank you for watching, hope some supplement and Suggestions are put forward

**Comment by caonima2900445768** [comment]
Supplement: I am very sorry about the Cosmos into Comsmos;

Research and development team can get one main window in the visual, can change the desktop background, system boot animation.


I hope, can add an interpreter function in the Cosmos, let it supports explain language functions, can put a code in the program interface, access to external programs, people can make use of Cosmos programming to external files such as images or C programming language C program into the Cosmos solution, and then use the code interface encapsulation in the operating system user do, in the generated iso file called as the user's system

**Comment by caonima2900445768** [comment]
I love the universe, if I do, then we are the next Bill Gates! L

**Comment by caonima2900445768** [comment]
Explain several typo: : Comsmos and a period of at the end of the L

**Comment by jp2masa** [comment]
We are still trying to make a strong base for Cosmos, we don't have network support, graphics support is really limited and we are moving to net core. An operating system isn't just drawing things on a screen. Maybe in the future we will provide a sample where you can simply create the UIs you want, but it's a long way until that's possible.

**Comment by fanoI** [comment]
Closing as this is not an issue.

@caonima2900445768 there is an edit button (the pencil / pen on top of the post) please use it the next time :-)
