### ISSUE TITLE
External Applications on Cosmos

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#567]
I found out a way that we can create external applications for Cosmos. For the last 15 days i have been working on a compiler and runtime for my programming language, and the good thing is that it is very small (3658 lines) and it's made in C#, so we can make it work for Cosmos.
Also the programming language has very simple syntax, this is how a Hello World application looks like:
```
#include <bioslib.str>
namespace Name
{
    function Main()
    {
        System.Write("Hello World\n");
        System.Exit(0);
    }
}
```
It still needs work because some features are bugged or not implemented yet.
But there is one problem with this idea, i run Linux so i do not have Visual Studio, i need someone to help me out and start the Cosmos project and report as many bugs as they can.

And the source code is:
https://github.com/mihail-mojsoski/Strobe

**Comment by APERSONA32** [comment]
How would one go about using this?

**Comment by mihail-mojsoski** [comment]
Well, one would try to compile the full project (without the debugger and compiler) in Cosmos then if it doesn't work to fix the bugs.
I will install Windows on my 2nd drive soon and i will be able to do this.

**Comment by APERSONA32** [comment]
I meant how would I use it?

**Comment by mihail-mojsoski** [comment]
Well first you need to write some code, for example a "Hello World" program:
```php
#include <bioslib.str>
namespace HelloWorld
{
    function Main()
    {
        System.Write("Hello, World!\n");
        System.Exit(0);
    }
}
```
After that you need to compile the program using `strcom.exe` into a `.dif` file, and when you have your `.dif` file you need to put it into your Cosmos HDD and open it using the runtime (that you need to have ported).

**Comment by mihail-mojsoski** [comment]
Currently won't compile because of Dictionaries.

**Comment by zarlo** [comment]
i can fix the Dictionaries issues

**Comment by mihail-mojsoski** [comment]
If you can, thanks!

**Comment by jp2masa** [comment]
PR #364 fixes Dictionary, but we're waiting for net core.

**Comment by mihail-mojsoski** [comment]
Is there anything that i can do to make it work?

**Comment by jp2masa** [comment]
Try creating this plug method: https://github.com/CosmosOS/Cosmos/pull/364/files#diff-2e2bc542e29d94ea000d842b884f5e44R843
If you get a native method encountered error, try creating this plug class: https://github.com/CosmosOS/Cosmos/pull/364/files#diff-b0beb90a9b9cc6bdd047af16d898d472

**Comment by mihail-mojsoski** [comment]
Wait, can i just fork Cosmos and add the pull request?

**Comment by jp2masa** [comment]
Just clone the master branch and add the things that I said. After that just run install-VS2015.bat

**Comment by mihail-mojsoski** [comment]
After 28 days.... it is now working...
This is a working DIF kernel:
https://github.com/StrobeOS/core/

Just it is not optimized because it slows down for some reason.

**Comment by fanoI** [comment]
As my avatar would say: Excellent!
