### ISSUE TITLE
On Windows 10 Inno Setup's Registry Key is in a different location

### ISSUE THREAD

**Issue by SIPS1980** [CosmosOS/Cosmos#570]
When running "install-VS2015.bat" on a Windows 10 machine, Cosmos.Build.Builder.exe returned an error that it "Cannot find Inno Setup."  

As I was sure that InnoSetup was installed on the machine, I checked the code and found on line 477 in ~\source\Cosmos.Build.Builder\CosmosTask.cs that Cosmos.Build.Builder checks via the registry key:
"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1" if InnoSetup is installed.

This registry key was different on a Windows 10 machine. The registry key on a Windows 10 machine is:
"HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1"

Suggested solution: if the first registry key check is returning null, before reporting Builder cannot find InnoSetup, check also the second registry key (of course log that the second registry key was checked)

**Comment by jp2masa** [comment]
The registry key isn't different because of Windows 10, it has to do with 64-bit Windows. I use Windows 10 and everything installs correctly, are you using the latest devkit?

**Comment by SIPS1980** [comment]
I got the latest code from GitHub just beforehand

Btw. after reviewing this in more detail I found also out is related to 64bit operating system which my machine has installed. Therefore I implemented locally the following and now it runs the installation just fine:

`
            Echo("Checking for Inno Setup");

            String innoSetupKey =
                Environment.Is64BitOperatingSystem == true ?
                @"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1" :
                @"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 5_is1";

            using (var xKey = Registry.LocalMachine.OpenSubKey(innoSetupKey, false))
`

**Comment by ROBLOXVIP735** [comment]
@SIPS1980 
You realize, you could just get a Virtual OS emulator(*cough* VMware *cough*) and I could send you a Windows XP x86 and Windows Vista x86 ISO right?
I've got those two laying around somewhere, if anyone needs them, I have them.

**Comment by fanoI** [comment]
It is that a particular version of Windows 10?
I've Windows 10 Home 64 Bit and it works for me..

**Comment by charlesbetros** [comment]
Fixed
