### ISSUE TITLE
Error occured while invoking IL2CPU

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#572]
I have literally searched all over Google for a solution to this problem but have obviously not found one. I am trying to build my OS as an .iso.

Error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while invoking IL2CPU.	StegOSBoot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	
`

The line in question (line 31) in the Cosmos.targets file is:
`    <IL2CPU  DebugMode="$(DebugMode)"
`

**Comment by jp2masa** [comment]
Are you using the 'Release' configuration?

**Comment by IanSteg** [comment]
Yes, I get the same error for both VB and C#.

**Comment by jp2masa** [comment]
If you want to disable debugging, go to your Boot project settings, the configuration must be set to Debug. If you are using profile ISO, debugging is already disabled.

**Comment by IanSteg** [comment]
If you mean the configuration option that is in the <nameofproject>Boot properties, it is set to N/A and I can't change it.
![image](https://cloud.githubusercontent.com/assets/25563128/22630247/2e1bc7aa-ec42-11e6-9c09-82be40c613a3.png)
If I create a new project from the template and try and build it, I get the same error in C# and it VB it compiles but I cant find where the .iso was saved to.

**Comment by IanSteg** [comment]
Both Configuration and Platform is greyed out for all options.

**Comment by jp2masa** [comment]
I mean Configuration of the solution, in a VS tool bar.

**Comment by IanSteg** [comment]
It is set to Release.

**Comment by jp2masa** [comment]
It needs to be set to Debug.

**Comment by IanSteg** [comment]
Why? I tried it and still same error.

**Comment by IanSteg** [comment]
OMG IT WORKED! I tried the debug mode in the VB one (which didn't work) and just tried it in the C# one and it worked! The only thing is that it didn't create an .iso file, it just put the files that would normally be in the .iso file in a folder called 'iso'

**Comment by IanSteg** [comment]
I got it to make the .iso file. Thanks for all the help!

**Comment by CSharpandLua** [comment]
Same error, its stupid because it worked fine before and i didn't change anything.. its always set to debug

**Comment by jp2masa** [comment]
Check the output window.
