### ISSUE TITLE
The program ' ' has exited with code 0 (0x0)

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#575]
I am trying to run my OS in VMware but when VMware opens, it soon closes and this is in the Output window:

> Setting FirstDataLookupTable to 
0x021B6EBB
FirstDataLookupTable was set to 
0x021B6EBB
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
The program '' has exited with code 0 (0x0).

**Comment by fanoI** [comment]
Could you please try with Bochs? I think you have encounter a CPU exception and VmWare kills simply itself Bochs should give more informations.

**Comment by IanSteg** [comment]
That didn't help. It appears to be getting stuck here:

`if (System.IO.Directory.Exists("/login/user_nme.txt") && System.IO.Directory.Exists("/login/pass_wrd.txt"))`

It probably is the incorrect way of doing it. What is the correct way to do it?

**Comment by fanoI** [comment]
With Bochs the process VM terminates without giving any information too?

**Comment by IanSteg** [comment]
This is a message box that popped up under VS:

![image](https://cloud.githubusercontent.com/assets/25563128/22782930/07112350-ef15-11e6-9d55-0b114d6f6d9a.png)

**Comment by jp2masa** [comment]
You need to register the VFS, check the tutorial in the wiki.

**Comment by IanSteg** [comment]
I can't find any tutorial on that topic. Can you send the link?

**Comment by jp2masa** [comment]
https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

**Comment by IanSteg** [comment]
![image](https://cloud.githubusercontent.com/assets/25563128/22804907/e84a5f7a-ef66-11e6-9626-e0e7455e5128.png)

It's getting stuck trying to create the directory:
`            {
                PrintDebug("Not found.");
                PrintDebug("Create dir.");
                System.IO.Directory.CreateDirectory("/login/");
                PrintDebug("Create username file.");
                System.IO.File.Create("/login/user_nme.txt");
                PrintDebug("Write to username file.");
                System.IO.File.WriteAllText("/login/user_nme.txt", "StegOS");
                PrintDebug("Create password file.");
                System.IO.File.Create("/login/pass_wrd.txt");
                PrintDebug("Write to password file.");
                System.IO.File.WriteAllText("/login/pass_wrd.txt", "coffee");
            }`

**Comment by jp2masa** [comment]
Are you initializing the VFS?
Like this:
```c#
var fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```

**Comment by IanSteg** [comment]
Yes:

`        protected override void BeforeRun()
        {
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            PrintDebug("Check if username and password files exist.");
            if (System.IO.Directory.Exists("/login/user_nme.txt") && System.IO.Directory.Exists("/login/pass_wrd.txt"))
            {
                PrintDebug("Found.");
            }
            else
            {
                PrintDebug("Not found.");
                PrintDebug("Create dir.");
                System.IO.Directory.CreateDirectory("/login/");
                PrintDebug("Create username file.");
                System.IO.File.Create("/login/user_nme.txt");
                PrintDebug("Write to username file.");
                System.IO.File.WriteAllText("/login/user_nme.txt", "StegOS");
                PrintDebug("Create password file.");
                System.IO.File.Create("/login/pass_wrd.txt");
                PrintDebug("Write to password file.");
                System.IO.File.WriteAllText("/login/pass_wrd.txt", "coffee");
            }
            PrintDebug("Set version number.");
            var version = "1.1.2.0";
            PrintDebug("Clear screen.");
            Console.Clear();
            PrintDebug("Write os version info.");
            Console.WriteLine("StegOS " + version + " booted successfully. Powered by Cosmos.");
            Console.WriteLine();
        }`

**Comment by jp2masa** [comment]
You can't create files inside directories, I fixed that bug in #522, but it's still in development, if you want you can clone the branch of the PR and install Cosmos from there.

**Comment by IanSteg** [comment]
How do I clone it?

**Comment by jp2masa** [comment]
If you are not used to git you can download as zip: https://github.com/jp2masa/Cosmos/archive/Bugfixes.zip

**Comment by IanSteg** [comment]
Yeah, I found the git command in #564.

**Comment by IanSteg** [comment]
So this PR should allow me to create files?

**Comment by jp2masa** [comment]
FAT should work fine in that version. If you find a bug please report it.

**Comment by IanSteg** [comment]
So I started the installation but had to leave before it finished so put my computer into hibernation, which crashed the installer. Now when I run it, it seems to get stuck here:


======================
Checking Prerequisites
======================

Note: This check only prerequisites for building, please see website for full list.
Checking for x86 run.
Checking Operating System
Check if User Kit Installer is already running.
Checking if Visual Studio is running.
--Visual Studio is running.
--Waiting 500 seconds to see if Visual Studio exits.

**Comment by IanSteg** [comment]
I think I got it. VS was running in the background

**Comment by IanSteg** [comment]
It still crashes on this line:

`System.IO.File.Create("/login/user_nme.txt");`

**Comment by mihail-mojsoski** [comment]
Try `File.Create("0:\user_nme.txt");`

**Comment by IanSteg** [comment]
The name 'File' does not exist in the current context

**Comment by zarlo** [comment]
you need to have the "0:/"

**Comment by IanSteg** [comment]
I do.

`            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            PrintDebug("Check if username and password files exist.");
            if (System.IO.Directory.Exists("0:/login/user_nme.txt") && System.IO.Directory.Exists("0:/login/pass_wrd.txt"))
            {
                PrintDebug("Found.");
            }
            else
            {
                PrintDebug("Not found.");
                PrintDebug("Create username file.");
                System.IO.File.Create("0:/login/user_nme.txt");
                PrintDebug("Write to username file.");
                System.IO.File.WriteAllText("/login/user_nme.txt", "StegOS");
                PrintDebug("Create password file.");
                System.IO.File.Create("0:/login/user_nme.txt");
                PrintDebug("Write to password file.");
                System.IO.File.WriteAllText("/login/pass_wrd.txt", "coffee");
            }`

> Setting FirstDataLookupTable to 
0x021E0D97
FirstDataLookupTable was set to 
0x021E0D97
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA Secondary Master
Initialized
Leds updated
Cls
Before Run
Check if username and password files exist.
Not found.
Create username file.
The program '' has exited with code 0 (0x0).

**Comment by jp2masa** [comment]
You need the "0:/" in WriteAllText too.

**Comment by IanSteg** [comment]
Ok, but it's not getting up to there. It's crashing trying to create the file.

**Comment by jp2masa** [comment]
You need to create the directory "0:/login"

**Comment by IanSteg** [comment]
I added that and now this is happening:

> Setting FirstDataLookupTable to 
0x021E1DF0
FirstDataLookupTable was set to 
0x021E1DF0
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA Secondary Master
The program '' has exited with code 0 (0x0).

**Comment by IanSteg** [comment]
Ran it again and got a little further. It crashed while trying to create the directory 0:/login

> Setting FirstDataLookupTable to 
0x021E1DF0
FirstDataLookupTable was set to 
0x021E1DF0
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA Secondary Master
Initialized
Leds updated
Cls
Before Run
Check if username and password files exist.
Not found.
Creating directory.
The program '' has exited with code 0 (0x0).

**Comment by IanSteg** [comment]
Is there a way to fix this?

**Comment by jp2masa** [comment]
What code are you using?

**Comment by IanSteg** [comment]
PrintDebug("Create file system..");
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            PrintDebug("Check if 0:/ exist.");
            if (System.IO.Directory.Exists("0:/"))
            {
                PrintDebug("0:/ found.");
            }
            else
            {
                PrintDebug("0:/ not found.");
                PrintDebug("Creating directory.");
                System.IO.Directory.CreateDirectory("0:/");
            }

**Comment by jp2masa** [comment]
Why are you trying to create the root directory? You just need to create the 0:/login directory.

**Comment by IanSteg** [comment]
That doesn't work either.

**Comment by IanSteg** [comment]
Why does no one know how to do this?

**Comment by charlesbetros** [comment]
You should use '\' not '/'.

**Comment by IanSteg** [comment]
VS gives the following error when using '\':

> Unrecognised escape sequence

**Comment by IanSteg** [comment]
I Google'd that error and found a solution to it but am now having another problem:

> Setting FirstDataLookupTable to 
0x021E0559
FirstDataLookupTable was set to 
0x021E0559
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
The program '' has exited with code 0 (0x0).

**Comment by IanSteg** [comment]
Oops.

**Comment by IanSteg** [comment]
Getting a bit further now:

> Setting FirstDataLookupTable to 
0x021E232D
FirstDataLookupTable was set to 
0x021E232D
In Cosmos.System.Kernel..ctor
Starting kernel
HW Bootstrap Init
Global Init
Creating Console
Creating Keyboard
HW Init
Before Core.Global.Init
Static Devices
CLS
Finding PCI Devices
PCI Devices
Done initializing Cosmos.HAL.Global
ATA Primary Master
Creating Primary ATA IOGroup
Creating Secondary ATA IOGroup
ATA device with speclevel ATA found.
Number of MBR partitions found:
0x00000001
ATA Secondary Master
Initialized
Leds updated
Cls
Before Run
Create file system..
Check if username and password files exist.
Username and password file not found.
0:\ found.
Create username file.
Write to username file.
Create password file.
Write to password file.
Set version number.
Clear screen.
Write os version info.
Run
Not yet stopped
Really before Run
Start of Run().
The program '' has exited with code 0 (0x0).


Here is my code:

`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using System.IO.Compression;


namespace StegOS
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            PrintDebug("Create file system..");
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            //PrintDebug("Check if 0:\\ exist.");
            //if (System.IO.Directory.Exists("0:\\"))
            //{
            //    PrintDebug("0:\\ found.");
            //}
            //else
            //{
            //    PrintDebug("0:\\ not found.");
            //    PrintDebug("Creating directory.");
            //    System.IO.Directory.CreateDirectory("0:\\");
            //}

            PrintDebug("Check if username and password files exist.");
            if (System.IO.Directory.Exists("0:\\login\\user_nme.txt") && System.IO.Directory.Exists("0:\\login\\pass_wrd.txt"))
            {
                PrintDebug("Found.");
            }
            else if (System.IO.Directory.Exists("0:\\login\\"))
            {
                PrintDebug("Username and password file not found.");
                PrintDebug("0:\\ found.");
                PrintDebug("Create username file.");
                System.IO.File.Create("0:\\login\\user_nme.txt");
                PrintDebug("Write to username file.");
                System.IO.File.WriteAllText("0:\\login\\user_nme.txt", "StegOS");
                PrintDebug("Create password file.");
                System.IO.File.Create("0:\\login\\user_nme.txt");
                PrintDebug("Write to password file.");
                System.IO.File.WriteAllText("0:\\login\\pass_wrd.txt", "coffee");
            }
            else
            {
                PrintDebug("0:\\ not found.");
                PrintDebug("Creating directory.");
                System.IO.Directory.CreateDirectory("0:\\login");
                PrintDebug("Create username file.");
                System.IO.File.Create("0:\\login\\user_nme.txt");
                PrintDebug("Write to username file.");
                System.IO.File.WriteAllText("0:\\login\\user_nme.txt", "StegOS");
                PrintDebug("Create password file.");
                System.IO.File.Create("0:\\login\\user_nme.txt");
                PrintDebug("Write to password file.");
                System.IO.File.WriteAllText("0:\\login\\pass_wrd.txt", "coffee");
            }
            PrintDebug("Set version number.");
            var version = "1.1.2.0";
            PrintDebug("Clear screen.");
            Console.Clear();
            PrintDebug("Write os version info.");
            Console.WriteLine("StegOS " + version + " Coffee booted successfully. Powered by Cosmos.");
            Console.WriteLine();
        }

        protected override void Run()
        {
            PrintDebug("Start of Run().");
            //Login
            var loggedin = false;
            var user_nme = System.IO.File.ReadAllText("0:\\login\\user_nme");
            var pass_wrd = System.IO.File.ReadAllText("0:\\login\\pass_wrd");
            if (loggedin == false)
            {
                Console.WriteLine("Please log in to continue.");
                Console.Write("Username: ");
                var UN = Console.ReadLine();
                Console.Write("Password: ");
                var PW = Console.ReadLine();
                if (PW == pass_wrd && UN == user_nme)
                {
                    Console.WriteLine("Logging in...");
                    loggedin = true;
                    Console.Clear();
                    Console.WriteLine("Logged in successfully.");
                    Console.WriteLine();
                }
                else
                {
                    Console.WriteLine("Logging in...");
                    loggedin = false;
                    Console.WriteLine("Log in failed. Try again");
                }
            }
            while (loggedin == true)
            {
                Console.Write(user_nme + "@StegOS: ");
                var get_input = Console.ReadLine();
                var input = get_input.ToUpper();

                if (input == "SHUTDOWN")
                {
                    goto SHUTDOWN;
                }
                else if (input == "LOG OFF")
                {
                    goto LOGOFF;
                }
                else if (input == "CLEAR")
                {
                    goto CLEAR;
                }
                else if (input == "REBOOT")
                {
                    goto REBOOT;
                }
                else if (input == "ABOUT")
                {
                    goto ABOUT;
                }
                else if (input == "HELP")
                {
                    goto HELP;
                }
                else
                {
                    Console.WriteLine("'" + input + "' is not a valid command. Try HELP for a list of commands.");
                    Console.WriteLine();
                }

            ABOUT:
                Console.ForegroundColor = ConsoleColor.Magenta;
                Console.WriteLine("");
                Console.WriteLine(" ###     #####   #####    ###         ###     ### ");
                Console.WriteLine("#   #      #     #       #   #       #   #   #   #");
                Console.WriteLine("#   #      #     #       #           #   #   #    ");
                Console.WriteLine(" ###       #     ####    #           #   #    ### ");
                Console.WriteLine("    #      #     #       # ###       #   #       #");
                Console.WriteLine("#   #      #     #       #   #       #   #   #   #");
                Console.WriteLine(" ###       #     #####    ####        ###     ### ");
                Console.WriteLine("");
                Console.WriteLine("");
                Console.WriteLine("   ###      ###    #####   #####   #####   #####");
                Console.WriteLine("  #   #    #   #   #       #       #       #    ");
                Console.WriteLine("  #        #   #   #       #       #       #    ");
                Console.WriteLine("  #        #   #   ####    ####    ####    #### ");
                Console.WriteLine("  #        #   #   #       #       #       #    ");
                Console.WriteLine("  #   #    #   #   #       #       #       #    ");
                Console.WriteLine("   ###      ###    #       #       #####   #####");
                Console.WriteLine("");
                Console.WriteLine("Powered by Cosmos.");
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("");
            CLEAR:
                Console.Clear();

            HELP:
                Console.WriteLine();
                Console.WriteLine("ABOUT             About StegOS.");
                Console.WriteLine("CLEAR             Clear the screen.");
                Console.WriteLine("HELP              Display this help screen.");
                Console.WriteLine("LOG OFF           Log out of StegOS.");
                Console.WriteLine("SHUTDOWN          Check is system is safe to shutdown.");
                Console.WriteLine("REBOOT            Reboot StegOS.");
                Console.WriteLine();

            LOGOFF:
                Console.WriteLine("Logging off... Please wait.");
                Console.Clear();
                loggedin = false;

            SHUTDOWN:
                Console.WriteLine("It is safe to shutdown. Press the power button to shutdown.");
                Console.WriteLine();
                this.Stop();

            REBOOT:;
                Sys.Power.Reboot();
            }
        }
    }
}
`

**Comment by jp2masa** [comment]
You forgot the .txt in ReadAllText.

**Comment by IanSteg** [comment]
I got it to work. Thanks all!
