### ISSUE TITLE
Byte Array Problems

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#576]
When i do a byte array, eg:
```c#
new byte[] { (byte)'S' , (byte)'o', (byte)'m', (byte)'e' , (byte)'H', (byte)'e', (byte)'l', (byte)'p' }
```
It replaces the first 4 characters with `0x0`, so when i do:
```c#
Console.Write(Encoding.ASCII.GetString(new byte[] { (byte)'S' , (byte)'o', (byte)'m', (byte)'e' , (byte)'H', (byte)'e', (byte)'l', (byte)'p' }));
```
I get this output:
```
    Help
```

**Comment by mihail-mojsoski** [comment]
But i can do it like this:
            Data[0] = (byte)'H';
            Data[1] = (byte)'e';
            Data[3] = (byte)'l';
            Data[4] = (byte)'p';
with no issues.

**Comment by jp2masa** [comment]
I found that issue when I was fixing arrays in the netcore, you will have to wait until the netcore branch is merged.

**Comment by mihail-mojsoski** [comment]
I'll just use the alternative way, and i also found the problem with the NullReferenceException that i got, it happends when i do something like this in a dictionary:
```C#
someDictonary[index] = new SomeType(something);
```

**Comment by jp2masa** [comment]
Dictionary isn't supported.

**Comment by mihail-mojsoski** [comment]
I'm in the wrong issue, but i managed to get over the dictonary issues and it happen because of that.

**Comment by mihail-mojsoski** [comment]
The byte array problem still exists.

**Comment by jp2masa** [comment]
As I said in a comment:
> I found that issue when I was fixing arrays in the netcore, you will have to wait until the netcore branch is merged.

**Comment by mihail-mojsoski** [comment]
Oh didn't read sorry
