### ISSUE TITLE
How can i mount (send files) to Filesystem.vmdk

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#577]
I need to send some binary files to the filesystem.

**Comment by jp2masa** [comment]
You can edit the vmdk file with a hex editor(not easy) or mount it in a VM in VirtualBox and use for example Ubuntu to copy the files.

**Comment by mihail-mojsoski** [comment]
Ok, but can i copy some files in it?

**Comment by jp2masa** [comment]
If you use VirtualBox, you can use it as a normal disk.
