### ISSUE TITLE
Can i use grub with Cosmos?

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#578]
I am unsure if i can use Grub with Cosmos, and if i can, how will the configuration file look like?
I have this idea, but it may not work:
```
set timeout=1
set default=0
menuentry "StrobeOS" {
   multiboot /StrobeOS.bin
   boot
}
```

**Comment by zarlo** [comment]
i should work

**Comment by fanoI** [comment]
Let us know if it worked.

**Comment by fanoI** [comment]
Well so it partly work but it is know that Cosmos does not boot or has problem on real hardware (we used shorcuts to make it work on VMs) so I'll close this for now.
