### ISSUE TITLE
Maximal Ram Memory Support for Cosmos

### ISSUE THREAD

**Issue by mihail-mojsoski** [CosmosOS/Cosmos#579]
How much RAM memory does Cosmos currently support?
I assume 4GB because it is 32-bit, but i am unsure.

**Comment by zarlo** [comment]
~4GB is the max

**Comment by jp2masa** [comment]
Cosmos currently only supports x86, so the 4GB is the maximum RAM supported. When we support 64-bit architectures, when building for that architectures the maximum will be 16 exabytes.
For questions like this, please ask in the gitter chat.
