### ISSUE TITLE
Debugger does not pickup correct values

### ISSUE THREAD

**Issue by kant2002** [CosmosOS/Cosmos#58]
Steps to reproduce:
1. Open Guess kernel
2. Set breakpoint on first SendMessage.
3. run Guess kernel. 
4. On first iteration, content of 'this' object correctly display mMagicNo as 22. 
5. Hit run and enter guess as 21
6. Execution stopped.
Content of 'this' is changed and don't display mMagicNo correctly.
Some large number shown.

**Comment by kant2002** [comment]
When step over, on the next line values picked up correctly and content of this shown as needed.

**Comment by kant2002** [comment]
The debugger issue can be duplicated with 1 line
`Console.ReadLine()` in the Run() method
set a breakpoint on it and then continue (stepping works)
VS loses focus when VMware takes it to get the input
the locals window is then cleared and loaded incorrectly after that
the stack and registers are wrong too

**Comment by mterwoord** [comment]
Could you trace back into commits (try 1-2 weeks back or so) to see where this bug was introduced?

**Comment by rebizu** [comment]
Debugger don't pickup strings from Console.ReadLine()
Debugger don't pickup class var names in local view like "private bool doRun = false;" 
![dorun have no name in locals](https://cloud.githubusercontent.com/assets/1035736/11614126/b95e3240-9c38-11e5-83b4-62c384de59fe.PNG)

sometimes the debugger pickup gibborish in vars  like this test1 is set to 0 above this 
![test1 0 befor assignign 1](https://cloud.githubusercontent.com/assets/1035736/11614064/daa5f89a-9c36-11e5-81dd-4b652573dffd.PNG)

Debugger thinks the string "test" is more than 100 chars
![private string](https://cloud.githubusercontent.com/assets/1035736/11614134/ecd3c180-9c38-11e5-901e-d4124ca7432b.PNG)

**Comment by rebizu** [comment]
I am debugging in Bochs and when i press stop debugging i get the following 
![stopping the debugger](https://cloud.githubusercontent.com/assets/1035736/11614170/41f57f9a-9c3a-11e5-8f72-b995fb126213.PNG)
![stopping the debugger 2](https://cloud.githubusercontent.com/assets/1035736/11614171/463ef6f8-9c3a-11e5-9685-b82a60876807.PNG)
