### ISSUE TITLE
Failed building project

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#580]
Hi! I've been using Cosmos for a while, and I recently got a new computer so I installed Cosmos, Visual Studio, and VMware on there. Cosmos usually works for me on my other pc, however whenever I try to debug my project (even the Cosmos example project) I get 

2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.8640456
2>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
Build has been canceled.

What could this be? What am I doing wrong?

**Comment by mihail-mojsoski** [comment]
Well, maybe if you could post the whole log on http://pastebin.com/ we could help, because this doesn't give much

**Comment by cps12145** [comment]
Here you go http://pastebin.com/bfH6fFiH

**Comment by jp2masa** [comment]
Try using the devkit, probably that issue was already fixed.

**Comment by cps12145** [comment]
Why don't they update the UserKit more often?

**Comment by czhower** [comment]
On 2/20/2017 3:40 PM, Charles Smith wrote:
> Why don't they update the UserKit more often?

UserKit is just a bundled dev kit.

**Comment by jp2masa** [comment]
@cps12145 Did the project build using the devkit?

**Comment by cps12145** [comment]
Sorry for the late response. Yes, it did build. 
Thank you.
