### ISSUE TITLE
COSMOS GUI Not Working

### ISSUE THREAD

**Issue by Project-csOS** [CosmosOS/Cosmos#582]
I'm having a problem with the GUI in COSMOS.

Here is the error message/corrupted text (Maybe?) that I get when booting my operating system.

![cosmosguierror](https://cloud.githubusercontent.com/assets/25674059/23129938/863c6d98-f752-11e6-93c0-45fdccd0b969.PNG)

I got the code to make the GUI off of the wiki.

Thanks!

**Comment by jp2masa** [comment]
Are you using the devkit? Graphics don't work in the devkit.

**Comment by Project-csOS** [comment]
Ohhhhhhhhhh

D'oh! Yes I am.

**Comment by zarlo** [comment]
the Graphics system is been recodded so what is on the wiki will not work soon

**Comment by Project-csOS** [comment]
Ok thanks for telling me!

**Comment by fanoI** [comment]
Yes better to wait CGS (Cosmos Graphic Subsystem) before work on GUI

**Comment by Project-csOS** [comment]
Ok thanks!
