### ISSUE TITLE
Comparer Issue

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#584]
I was trying to come up with some kind of user system but when I tried running the code I got this:

![capture7](https://cloud.githubusercontent.com/assets/24322118/23285294/2638c90e-fa28-11e6-9e46-61ecd0f4eefc.PNG)

The code I'm running is the code on the left hand side.

**Comment by jp2masa** [comment]
IndexOf on List\<T\> isn't implemented in Cosmos, try using a "for" and check item by item.

**Comment by fanoI** [comment]
@jp2masa  I'm asking myself if it would be possible to do a naive plug of IndexOf() that does the for directly so the user code is in C# and when we have a better / more efficient plug they will benefit of this without changing their code.
What do you think?

**Comment by jp2masa** [comment]
I'm waiting for netcore to review plugs, if we still have this problem on netcore better plug IndexOf like you are saying.

**Comment by fanoI** [comment]
Yes I concord this activity must be done after Net Core.

**Comment by APERSONA32** [comment]
I thought I should also add that Contains() also causes the same error.

**Comment by quajak** [comment]
To use IndexOf, Contains and Dictionaries comparers have to be added. Comparers for Int32 and string exist in https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core_Plugs/System/Collections/Generic/ComparerHelpersImpl.cs. Adding new comparers is relativly easy and would be done in that file. For help ask in the gitter chat.

**Comment by disks86** [comment]
I'll take a look at this after work tomorrow if nobody else is working on it.

**Comment by disks86** [comment]
The original issue isn't reproducible with the latest code. Regardless I'm working on additional comparers in a fork.

**Comment by disks86** [comment]
@quajak @jp2masa  I've run into an error I can't make sense of. In my local test application Dictionary<string, int> is valid but Dictionary<int, int> gives an IL2CPU error of being unable to compare string and int. The question is where is the string coming from it's key and value are int in that case.

**Comment by charlesbetros** [comment]
What IL opcode is it complaining about?

**Comment by disks86** [comment]
@charlesbetros the opcode was Bne_Un. Which I think is only for int and unordered float.

**Comment by charlesbetros** [comment]
Resolved
