### ISSUE TITLE
Cosmos Template not showing up in visual studio

### ISSUE THREAD

**Issue by midonator1305** [CosmosOS/Cosmos#586]
I am having a problem where the user kit and dev kit do not add the templates to visual studio 2015

**Comment by midonator1305** [comment]
Yes i have uninstalled and reinstalled cosmos and visual studio many times. That did not work

**Comment by jp2masa** [comment]
The devkit doesn't setup the templates in Visual Studio, but the userkit should install them correctly. Check if the project templates are in "your_user_folder\Documents\Visual Studio 2015\Templates\ProjectTemplates\Cosmos\"

**Comment by midonator1305** [comment]
Yes the 2 zip files are there
![screenshot 3](https://cloud.githubusercontent.com/assets/15933658/23335008/80d5f754-fb79-11e6-8749-e772d9fb06b4.png)

**Comment by jp2masa** [comment]
Go to your Visual Studio installation and run "devenv.exe /setup"

**Comment by midonator1305** [comment]
it did nothing.

**Comment by jp2masa** [comment]
It should setup the templates. Did you check if the templates are installed?

**Comment by midonator1305** [comment]
yes i checked and there are 2 zip files in the folder

**Comment by midonator1305** [comment]
I fixed it. There was an error with onedrive. It was not reading my user documents folder. Thanks for the help

**Comment by jason-pezzimenti** [comment]
Running install-vs2022.bat as Administrator worked for me.
