### ISSUE TITLE
Regex.Match: Plug required

### ISSUE THREAD

**Issue by ERamaM** [CosmosOS/Cosmos#588]
Using Regex.Match() gives "Native code encountered, plug required.

Non working code:
```csharp
            var match = Regex.Match("Intel core I5", @".*[Ii]ntel.*");
            if(match.Success)
                Console.WriteLine("Sucess");
            else
            {
                Console.WriteLine("non sucenss");
            }
```

AFAIK this would be solved recreating a Finite Automata given the match expression (i.e the second parameter in Regex.Match) and accepting it.

May be relevant: https://swtch.com/~rsc/regexp/regexp1.html

**Comment by fanoI** [comment]
If I'm not mistaking to make regex faster C#/.NET has a regex compiler integrated.

Interesting link neverthless but it scares me a little :-)
