### ISSUE TITLE
Argument is null or empty

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#591]
When trying to delete a directory within my OS, the error "Argument is null or empty" flashes on the screen very fast before crashing. All other system.IO features are working. I'm able to create a directory, make a file in it, and read/write with that file. Deleting files is working, but what's going on with the directories? 

Here's the code for the delete function:

else if (input.StartsWith("delfile"))
            {
                string[] cmdArgs = input.Split(' ');
                File.Delete(cmdArgs[1]);
            }

**Comment by jp2masa** [comment]
Try using the devkit from the branch of #522.

**Comment by zarlo** [comment]
to be on the safe side do this
```
else if (input.StartsWith("delfile"))
{
string[] cmdArgs = input.Split(' ');
if(cmdArgs[1] != null){
File.Delete(cmdArgs[1]);
}
}
```
or use try

**Comment by cps12145** [comment]
Thanks

**Comment by fanoI** [comment]
So it is working now?

I suggest to use try / catch on all your Run() method so you can catch the exception instead of the default behavior that is to kill all the OS (the same thing that would happen with a normal .NET when exceptions are not handled).

**Comment by cps12145** [comment]
Well, the try and catch is working, but I still get various errors when deleting things.

**Comment by jp2masa** [comment]
Are you trying to delete the TEST directory?

**Comment by cps12145** [comment]
No. I'm trying to delete ones I have created.

**Comment by jp2masa** [comment]
Are you using the latest master branch?

**Comment by cps12145** [comment]
Yes

**Comment by jp2masa** [comment]
Try using the branch of #522.

**Comment by cps12145** [comment]
I will. Also, when I open VMware and create a new VM with my OS's ISO file, and then try to run it, the screen just stops on "Waiting for debugger connection" Is there a fix for this so I don't have to keep launching it from VS?

**Comment by jp2masa** [comment]
Right click your Boot project, go to Properties and choose ISO.

**Comment by cps12145** [comment]
Thank you.

**Comment by cps12145** [comment]
When trying to boot from the ISO, the OS boots up, but I get the error in console "Unable to determine file system for path 0:\" and "No partitions found"

**Comment by jp2masa** [comment]
You need to have a FAT partition in the virtual machine. Why don't you use the default Cosmos VM?

**Comment by cps12145** [comment]
I just thought it was easier to launch from VMWare as opposed to opening VS and debugging it from there.

**Comment by cps12145** [comment]
Let's say I had an old piece of hardware that wasn't being used anymore, and I uninstalled the current OS on it, and booted my OS from a USB. Would the file system work?

**Comment by jp2masa** [comment]
If you had at least one FAT partition, it would work. Each FAT partition that is found will be mounted as `0:\` `1:\` and so on.

**Comment by cps12145** [comment]
How would I get an FAT partition on VMware or hardware?

**Comment by jp2masa** [comment]
There are tools for that, for example http://gparted.org/livecd.php

**Comment by cps12145** [comment]
So what steps would I follow if I'd want to run my OS on hardware? Sorry, I can't find a solution anywhere.

**Comment by jp2masa** [comment]
You just need to create a bootable USB from the ISO file and boot it in hardware.

**Comment by zarlo** [comment]
debugging need to be off too

**Comment by cps12145** [comment]
It does?
