### ISSUE TITLE
Boot from USB is not working

### ISSUE THREAD

**Issue by cps12145** [CosmosOS/Cosmos#593]
So I have two different USBs. When I put one in my old laptop before they had an OS on them, the BIOS would actually pick up the USB, and allow me to boot from it. That obviously didn't work because there was no OS on it yet. Once I burned the ISO to them, and entered either one into my old laptop, the BIOS would nolonger pick it up. What's going on here? What am I doing wrong?

**Comment by cps12145** [comment]
UPDATE! I enabled Legacy in the BIOS, and I got the USB to start to boot, however, the screen is stuck with the text "Finding PCI Devices SYSLINUX 4.07 EDD (copyright stuff blah blah) Loading Cosmos.bin... ok" And it's stuck there with the flashing text cursor. What should I do?

**Comment by jp2masa** [comment]
Probably this is the same as #370.

**Comment by cps12145** [comment]
Thank you.

**Comment by cps12145** [comment]
I tried on different hardware, and it booted up. The only thing is that filesystem is having some trouble. Any command I try that's related to the filesystem returns an "Argument is out of range" Exception.

**Comment by cps12145** [comment]
I tried to boot on a different computer, and it booted up just fine. The only thing is that it's having some trouble with filesystem. I'm getting this http://imgur.com/a/Njot4

**Comment by jp2masa** [comment]
Does it have a FAT partition?

**Comment by cps12145** [comment]
Not the computer. The USB does.

**Comment by cps12145** [comment]
I got no errors about it finding an FAT filesystem. I listed the volumes and 0:\\ showed up using FS.getvolumes.

**Comment by jp2masa** [comment]
The computer needs to have a FAT partition, we don't have USB support.

**Comment by jp2masa** [comment]
Maybe you're using a GPT partition scheme, they are not supported.
https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem#warnings

**Comment by cps12145** [comment]
Oh. I thought I saw someone say that when on a bootable drive, the ISO just uses it as the hard disk.

**Comment by zarlo** [comment]
@cps12145  do you have debugging on???

**Comment by cps12145** [comment]
@zarlo no
