### ISSUE TITLE
Is it possible load an application from USB when USB is connected to PC using COSMOS 

### ISSUE THREAD

**Issue by pravinohal** [CosmosOS/Cosmos#595]
Hi,

    I have a requirement wherein I need to launch a particular application in a USB when the USB is connected to a PC. Is this possible using COSMOS. If yes can anybody show some path how to start with it. What functions should be used. Thanks in Advance.

**Comment by zarlo** [comment]
no, USB does not work yet

**Comment by pravinohal** [comment]
Thanks for the quick response @zarlo. Any updates as to when the USB library will be available.

**Comment by fanoI** [comment]
To do that you want Cosmos should have the possibility to boot from USB, the application that in the actual version is the same thing of the kernel will start to run when the OS would have booted.

**Comment by DjAlEx234** [comment]
should this still be open?

**Comment by zarlo** [comment]
I think its should stay open until it can be done

**Comment by fanoI** [comment]
Yes it is an interesting use case of Cosmos.

**Comment by DjAlEx234** [comment]
To load a application from a different drive, you will need drivers and/or the internet (for online drives)

**Comment by quajak** [comment]
As this is on the roadmap can we close it?
