### ISSUE TITLE
Getting this error(not cpu2il)

### ISSUE THREAD

**Issue by MrMutt1406** [CosmosOS/Cosmos#598]
So im trying to use FileSystem and system.io and when I use any of them I get this exception
Pictures of the exceptions:
http://i.imgur.com/l2AvbMO.jpg
http://i.imgur.com/GaXXrth.jpg

Output:
http://pastebin.com/sfb5q9kV

My code:
http://pastebin.com/U9TxXHLy

Thanks in advance for help.

**Comment by jp2masa** [comment]
You need to register the VFS: `Sys.VFSManager.RegisterVFS(FS);`
There's a page in the wiki.
Please discuss this kind of problems in the gitter chat, don't open an issue every time you get errors.
