### ISSUE TITLE
Can I save a file created with my text editor into a dirctory?

### ISSUE THREAD

**Issue by CasteSoftworks** [CosmosOS/Cosmos#599]
Hi guys, I'm wondering if there is the possibility to save a text made by the user in the text editor into a certain directory (documents for example), is it possible?
It isn't that important, so if there is a more important issue answer to that first. :)

**Comment by jp2masa** [comment]
It depends on the way you are storing the text written in the text editor, but File.WriteAllText and File.WriteAllLines should work.

**Comment by CasteSoftworks** [comment]
Thanks @jp2masa I'll try!!
