### ISSUE TITLE
Update wikipedia

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#60]
The wikipedia page on Cosmos (http://en.wikipedia.org/wiki/Cosmos_%28operating_system%29) is pretty outdated. Please update it:
- with updated screenshots of the development experience (building, debugging, etc)
- review all descriptions.

**Comment by ArtyomIsFlash** [comment]
Note: [Russian Wikipedia version](https://ru.wikipedia.org/wiki/Cosmos_(%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0)) is slightly more up to date, I guess

**Comment by NoahCristino** [comment]
Can you assign me to this I wanna help.

**Comment by quajak** [comment]
Has the wikipedia article been updated?

**Comment by zdimension** [comment]
Well I updated the English and French ones about 1 year ago iirc so they may not be up to dare

**Comment by Kiirx** [comment]
Can still be updated but as of today it's better to get to the website of cosmos
