### ISSUE TITLE
Visual Studio Mac Support

### ISSUE THREAD

**Issue by electrodeyt** [CosmosOS/Cosmos#600]
Is there a way to build this (preferably on a mac) for VS Mac Edition? Yes it actually exists.

**Comment by jp2masa** [comment]
It's not on our roadmap to support VS for Mac.

**Comment by electrodeyt** [comment]
Thank you for telling me

**Comment by charlesbetros** [comment]
It's not on the current roadmap, but as we bring some of our tooling up to date, things will be compatible with vs mac. It won't be any time soon as it would require a rewrite of our project system and debugger, but we are making a big stride toward that goal with the move to .net core.

**Comment by mihail-mojsoski** [comment]
Just install windows ffs.

**Comment by electrodeyt** [comment]
Shut up mihail.

**Comment by czhower** [comment]
@mihail-mojsoski  @electrodeyt 

Keep it professional or you will both be censored. There is no reason to act like children.
