### ISSUE TITLE
[CGS] VmWare support

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#602]
Luckily it is not so difficult as it could seem as Cosmos has a VMWare driver already:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL/Drivers/PCI/Video/VMWareSVGAII.cs

it simply needs a VmWareScreenClass in System to make it usable from the user level!
The one done for Bochs should be used as template:

https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System/Graphics/VBEScreen.cs

the first objectives should be to overwrite the "stub" Clear method in Canvas to use the hardware Clear implemented in the HAL VmWare driver, then overwrite DrawPoint() with what is needed to make it work with VmWare.

Done this the other methods of CGS should already work as they are all based on DrawPoint() but thing can be done better in VmWare as it has hardware accelerated line and rectangle drawing, to take advantage of them you simply need to overload the methods of the abstract canvas class.

Points to indagate:

1. There is a method in VmWare to get the list of supported modes? If it exists the List returned by getAviableModes() should be filled with real values not with hard coded ones as done for the Bochs driver
2. The VmWare driver permits to return in Text Mode?

**Comment by fanoI** [comment]
#601

**Comment by nuhash** [comment]
I've reimplemented the Canvas class for the VMWare driver and its not going to work until the PCI class in the HAL is setup properly.

Currently when calling `Cosmos.HAL.PCI.Setup()` it goes through `EnumerateDevices()` but `EnumerateBus(0,0)` is commented out so it never populates the list of devices.

**Comment by fanoI** [comment]
If you try to uncomment ``EnumerateBus(0,0)`` what happens?

**Comment by nuhash** [comment]
If I uncomment `EnumerateBus(0,0)` then a `VMT_MethodNotFound` error is produced in `GetMethodAddressForType`, the debugger output is:
```
Type
0x000000B8
MethodId
0x0000000C
Not FOUND!
```
A message window is produced with the text `Kernel panic: 0x1` which is `VMT_MethodNotFound`

As for selecting the driver, once devices have been enumerated we can categorise them according to device class (https://pci-ids.ucw.cz/read/PD/). Graphics cards fall under "display controller" and we can take the first one found and match a driver with it. If the driver isn't found then we can check a repository, if its still not found then we can notify the user that a device was detected but an appropriate driver could not be found. If there are multiple GPUs then we can have a user-defined preference, this allows for multiple GPUs to be available without causing interference (e.g. Having a second GPU for OpenCL, video encoding etc.).

**Comment by fanoI** [comment]
Blocked by https://github.com/CosmosOS/Cosmos/issues/666

**Comment by Arawn-Davies** [comment]
CGS work is currently being done in branch pr-767 (https://github.com/CosmosOS/Cosmos/tree/pr-767)d
