### ISSUE TITLE
[CGS] Add to the Canvas abstract Class methods to draw more shapes

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#603]
Continuing to take inspiration from System.Drawing...

- [x] DrawFilledRectangle(Pen pen, int x_start, int y_start,int width, int height)
~~- [ ] DrawSquare(Pen pen,  int x_start, int y_start, int int height)~~
- [x] DrawTriangle(Pen pen, int vertex1, int vertex2, int int vertex3)
- [x] DrawPolygon(Pen pen, int[] vertexes)
- [x] DrawCircle((Pen pen, int x_center, int y_center)
- [x] DrawEllipse(Pen pen, int x, int y, int width, int height)
- [x] Add to the CGS Demo examples of drawing of these shapes

**Comment by fanoI** [comment]
#601

**Comment by miyu** [comment]
I can take this for assignment if it's still available.

**Comment by fanoI** [comment]
Sure that it is available!

Keep us posted on the progresses.

**Comment by fanoI** [comment]
To help you to start these methods should be implemented in the abstract Canvas class taking as example how is done DrawRectangle():
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System/Graphics/Canvas.cs#L193

in Canvas do exist the software implementation a more evolved GPU than Bochs should override them if it has an hardware way to do all (or some) of these... I notice now that I've forgotten to add the virtual attribute to DrawLine() and DrawRectangle() please add it if not they could not overridden :-)

**Comment by DjAlEx234** [comment]
I can take this assignment

**Comment by nuhash** [comment]
All of these functions have been implemented. This issue can be closed now.

**Comment by fanoI** [comment]
Yes thank you for the help!
