### ISSUE TITLE
Strange GUI

### ISSUE THREAD

**Issue by CasteSoftworks** [CosmosOS/Cosmos#605]
Hi, I'm here again with a new problem, I wanted to have a command like "GUI" to start the Gui, so i used your [tutorial](https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI---The-basics), but when I type GUI on VMWare it not fills the screen with cyan, but it makes something like this.
![problema gui](https://cloud.githubusercontent.com/assets/26233132/23832895/1da37dde-073e-11e7-9107-c781a6bd0fa9.PNG)
Can you help me?

**Comment by fanoI** [comment]
These tutorial have become obsolete with CGS the idea is to create that a simple and reusable Widget ToolKit based on CGS should be created.

I close the issue as these methods to draw a GUI will not more supported soon.
