### ISSUE TITLE
Visual studio 2017

### ISSUE THREAD

**Issue by joel076** [CosmosOS/Cosmos#607]
When is cosmos coming to vs 2017. I need it!

**Comment by czhower** [comment]
On 3/17/2017 12:19 PM, joel076 wrote:
> When is cosmos coming to vs 2017. I need it!

We are already working on it, but its not just VS 2017 but .NET core 
work which was already in progress.

We are very close, hopefully in the next days or weeks.

**Comment by jp2masa** [comment]
This is the same as #519.
