### ISSUE TITLE
Project with Output Type of Class lib can't be started directly.

### ISSUE THREAD

**Issue by CxpcakeTheDerp** [CosmosOS/Cosmos#608]
I've been stuck trying to fix this by myself for 2 hours now.(I'm a bit afraid to open a new issue.) But there is no other issue stating this.(I really hope this isn't a duplicate.)
(My other solution file has IL2CPU error that I cannot fix. Even trying this #597)

So I decided to make another solution. Now it has this problem.

When I am building this project, it throws a message box saying this. http://imgur.com/a/VYOcV
It doesn't say anything else in the build output.

I'm stupid new to Visual Studio. Once again,please help.

**Comment by CxpcakeTheDerp** [comment]
I literally just fixed it after messing random buttons.

But still back to the IL2CPU error. Erh.

**Comment by zarlo** [comment]
you need to set the startup project to the *.Cosmos project

**Comment by CxpcakeTheDerp** [comment]
Thanks anyways, but I already fixed the problem.

And also the IL2CPU by giving up and rewriting the whole Filesystem class.
