### ISSUE TITLE
Update to use CGS?!

### ISSUE THREAD

**Issue by CasteSoftworks** [CosmosOS/Cosmos#609]
Hi guys, how are you?
I know that I make a lot of questinos but, do I need to re-run install-VS2015.bat in order to use CGS?
thanks!!

**Comment by jp2masa** [comment]
CGS is already in the devkit, you just need to make sure you have the latest devkit and run install-VS2015.bat

**Comment by CasteSoftworks** [comment]
Well, @jp2masa i've made what you said, but when I type `using Cosmos.System.Graphics;
` it simply say "Severity	Code	Description	Project	File	Line	Suppression State	Tool
Error	CS0234	The type or namespace name 'Graphics' does not exist in the namespace 'Cosmos.System' (are you missing an assembly reference?)	CAOS	C:\Users\Chief\documents\visual studio 2015\Projects\CaOS\CAOS\Kernel.cs	5	Active	Compiler" and I've added all the cosmos references, what can I do now??

**Comment by jp2masa** [comment]
Are you using the latest devkit?

**Comment by CasteSoftworks** [comment]
I've downloaded it less than a month ago, so I'm pretty sure to be using the lastest DevKit, but maybe you updateted it

**Comment by czhower** [comment]
Dev kit is live and often updated several times a day.

**Comment by CasteSoftworks** [comment]
Ah, thanks, I'll try to re-download it and re-run it, then I'll close if it works

**Comment by fanoI** [comment]
I've merged CGS 2 week ago so...

**Comment by jp2masa** [comment]
@CasteSoftworks did it work?

**Comment by CasteSoftworks** [comment]
Yeah, thanks @jp2masa !!!!
