### ISSUE TITLE
Could not run project from Solution Explorer

### ISSUE THREAD

**Issue by kant2002** [CosmosOS/Cosmos#61]
Steps to reproduce
1. Open Cosmos.sln
2. In the Solution Explorer, right click on the project which is not selected as Startup project. The should be selected Cosmos project.
3. Select Debug->Start new instance  menu item.

Expected:
Project gets build, and run

Actual Result:
Project does not build, and previous version is run.
In the Output window the message "Project skipped, as it's not necessary for running" shown

**Comment by huetonOS** [comment]
So, which project are you choosing as the Startup project, exactly? Because, to boot the actual OS, you need to use the project '[Name of your OS]Boot'. If this was on another project,

**Comment by huetonOS** [comment]
So, which project are you choosing as the Startup project, exactly? Because, to boot the actual OS, you need to use the project '[Name of your OS]Boot'.

![untitled](https://cloud.githubusercontent.com/assets/3726396/7744304/5e621e5e-ffe1-11e4-8555-c4d1bf628499.png)

**Comment by mterwoord** [comment]
@huetonOS Setting a project as startup project, and then run the solution works, right-clicking a given project (which is not startup project) and then selecting debug doesn't.

**Comment by huetonOS** [comment]
@mterwoord Ok, got it. I've got an error that says something about the other project being a Class Library and requiring an executable within the solution. I'll edit my message above.

**Comment by mterwoord** [comment]
@huetonOS Interested in helping us out? :)

**Comment by huetonOS** [comment]
@mterwoord I'd love to be able to help!

**Comment by kant2002** [comment]
I update initial issue with information that I try to start Cosmos project

**Comment by mterwoord** [comment]
@kant2002 Thanks!

@huetonOS Please contact me on skype and I'll get you going..

**Comment by jp2masa** [comment]
I'll close this, as it should be working fine on the new project system.
