### ISSUE TITLE
Exception: ArgumentOutOfRange_StartIndexLessThanLength Parameter name: startIndex

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#610]
I get this error 

> Exception: ArgumentOutOfRange_StartIndexLessThanLength
Parameter name: startIndex

on this line of code

`System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");`

**Comment by jp2masa** [comment]
Does the 0:\Users\Ian folder exist?

**Comment by IanSteg** [comment]
Yes, it checks and creates it if not.

**Comment by IanSteg** [comment]
It creates them successfully

**Comment by jp2masa** [comment]
What devkit are you using?

**Comment by IanSteg** [comment]
I dont know, the latest I think.

**Comment by jp2masa** [comment]
Try to use the devkit from #522

**Comment by IanSteg** [comment]
Can you send the link to the download?

**Comment by jp2masa** [comment]
git clone https://github.com/jp2masa/Cosmos -b Bugfixes

**Comment by IanSteg** [comment]
Where does it clone to? I cant find it anywhere

**Comment by jp2masa** [comment]
To a folder called Cosmos, which is the directory where you executed the command.

**Comment by IanSteg** [comment]
What do I enter when it asks for the release number?

**Comment by jp2masa** [comment]
Run install-VS2015.bat, not userkit install.bat

**Comment by IanSteg** [comment]
It gets stuck on 'Finishing installation...'

**Comment by jp2masa** [comment]
You can shutdown the devenv.exe process.

**Comment by IanSteg** [comment]
I think it installed successfully and if it did, it didn't fix my problem. During the installation, it opened a file in VS. Do I need to do something with that?

**Comment by jp2masa** [comment]
It should be installed, can you create a simple kernel so that I can debug the issue?

**Comment by IanSteg** [comment]
What do you mean by create a simple kernel? Do I create a brand new OS?

**Comment by jp2masa** [comment]
Some code that shows the issue, so that I can test it.

**Comment by IanSteg** [comment]
This is what is giving me trouble, more specifically, where it tries to create the Documents folder:

`            try
            {
                dir = "0:\\Users\\Ian\\Documents\\";
                if (System.IO.Directory.Exists("0:\\Users\\Ian\\Documents\\"))
                {
                    PrintDebug("Found documents folder.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else if (System.IO.Directory.Exists("0:\\Users\\Ian\\"))
                {
                    PrintDebug("\\Users\\Ian\\ Found.");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else if (System.IO.Directory.Exists("0:\\Users\\"))
                {
                    PrintDebug("\\Users\\ Found.");
                    PrintDebug("Create \\Users\\Ian");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else
                {
                    PrintDebug("Create \\Users");
                    System.IO.Directory.CreateDirectory("0:\\Users\\");
                    PrintDebug("Create \\Users\\Ian");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
            }
            catch (Exception e)
            {
                PrintDebug("Failed with \n" + e + "\n\n");
            }`

**Comment by fanoI** [comment]
Can you please use the code tag? It is pretty much unreadable...

**Comment by mihail-mojsoski** [comment]
I used the beautifier on this and it ended up like this:
<pre>
try {
 dir = "0:\\Users\\Ian\\Documents\\";
 if (System.IO.Directory.Exists("0:\\Users\\Ian\\Documents\\")) {
  PrintDebug("Found documents folder.");
  dir = "0:\\Users\\Ian\\Documents\\";
 } else if (System.IO.Directory.Exists("0:\\Users\\Ian\\")) {
  PrintDebug("\\Users\\Ian\\ Found.");
  PrintDebug("Create \\Users\\Ian\\Documents");
  System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
  PrintDebug("Set current directory.");
  dir = "0:\\Users\\Ian\\Documents\\";
 } else if (System.IO.Directory.Exists("0:\\Users\\")) {
  PrintDebug("\\Users\\ Found.");
  PrintDebug("Create \\Users\\Ian");
  System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
  PrintDebug("Create \\Users\\Ian\\Documents");
  System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
  PrintDebug("Set current directory.");
  dir = "0:\\Users\\Ian\\Documents\\";
 } else {
  PrintDebug("Create \\Users");
  System.IO.Directory.CreateDirectory("0:\\Users\\");
  PrintDebug("Create \\Users\\Ian");
  System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
  PrintDebug("Create \\Users\\Ian\\Documents");
  System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
  PrintDebug("Set current directory.");
  dir = "0:\\Users\\Ian\\Documents\\";
 }
} catch (Exception e) {
 PrintDebug("Failed with \n" + e + "\n\n");
}
</pre>

**Comment by IanSteg** [comment]
@fanoI I did. I don't know why it's like that...

**Comment by mihail-mojsoski** [comment]
@IanSteg 
Use `<pre>` instead of `<code>`

**Comment by IanSteg** [comment]
<pre>
            try
            {
                dir = "0:\\Users\\Ian\\Documents\\";
                if (System.IO.Directory.Exists("0:\\Users\\Ian\\Documents\\"))
                {
                    PrintDebug("Found documents folder.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else if (System.IO.Directory.Exists("0:\\Users\\Ian\\"))
                {
                    PrintDebug("\\Users\\Ian\\ Found.");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else if (System.IO.Directory.Exists("0:\\Users\\"))
                {
                    PrintDebug("\\Users\\ Found.");
                    PrintDebug("Create \\Users\\Ian");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
                else
                {
                    PrintDebug("Create \\Users");
                    System.IO.Directory.CreateDirectory("0:\\Users\\");
                    PrintDebug("Create \\Users\\Ian");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\");
                    PrintDebug("Create \\Users\\Ian\\Documents");
                    System.IO.Directory.CreateDirectory("0:\\Users\\Ian\\Documents\\");
                    PrintDebug("Set current directory.");
                    dir = "0:\\Users\\Ian\\Documents\\";
                }
            }
            catch (Exception e)
            {
                PrintDebug("Failed with \n" + e + "\n\n");
            }

**Comment by IanSteg** [comment]
@jp2masa Did you test it?

**Comment by fanoI** [comment]
My impression from the type of error is that is in a a String operation (maybe something a Split() or IndexOf()?) my hope is that using Net Core we have not the need to plug them anymore.

**Comment by jp2masa** [comment]
The problem is using the slash at the end of the path, but it should work, so I tried to fix it and I'm now getting a stack corruption, which I'll need to fix.

**Comment by IanSteg** [comment]
@jp2masa Is this problem fixed?

**Comment by jp2masa** [comment]
No, I'll need to work on it.

**Comment by jp2masa** [comment]
This should be working now.

**Comment by IanSteg** [comment]
How do I update?

**Comment by jp2masa** [comment]
Install the Dev Kit.
