### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#615]
VS2017 Install errored out. It said this in the cmd prompt:
`
The script 'install-VS2017.ps1' cannot be run because the following modules that are specified by the "#requires"
statements of the script are missing: VSSetup.
    + CategoryInfo          : ResourceUnavailable: (install-VS2017.ps1:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules
`

**Comment by charlesbetros** [comment]
You need VSSetup powershell module like it says. Regardless, things aren't quite ready yet with the project templates.
