### ISSUE TITLE
.Net core not found

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#616]
With the VS2017 netcore installer, it cant find netcore even though it was already installed

**Comment by jp2masa** [comment]
The netcore branch is still in development, not everything works fine. Are you sure you have the .NET Core Visual Studio Workload installed?

**Comment by DjAlEx234** [comment]
do I install sdk or runtimes?

**Comment by jp2masa** [comment]
The Visual Studio workload, you need to modify your installation.
