### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chottal** [CosmosOS/Cosmos#618]
when ever I run the userkit install-bat it says that aximp.exe was not found please help me

**Comment by jp2masa** [comment]
Why are you running "userkit install.bat"? If you want to install the devkit you should run "install-VS2015.bat".

**Comment by chottal** [comment]
I have ran both and they have done the same thing

**Comment by jp2masa** [comment]
Try repairing your Visual Studio installation.

**Comment by chottal** [comment]
okay

**Comment by chottal** [comment]
it didn't work

**Comment by jp2masa** [comment]
Do you have the userkit installed? Does it work fine?

**Comment by chottal** [comment]
I haven't installed userkit before because I just found cosmos recently that's why I am having troubles

**Comment by jp2masa** [comment]
I think that the project templates won't get installed if you install the devkit, try installing the userkit first. Also, make sure you have .NET 3.5 installed. Cosmos will support Visual Studio 2017 soon, and .NET 3.5 won't be needed anymore, it should be ready in a week.

**Comment by chottal** [comment]
I still haven't figured it out

**Comment by jp2masa** [comment]
You have .NET 3.5 and .NET 4.5.2? Have you tried to build other projects is Visual Studio?

**Comment by zarlo** [comment]
Aximp.exe (Windows Forms ActiveX Control Importer) is (should) automatically installed with Visual Studio.

**Comment by DjAlEx234** [comment]
@chottal have you figured it out?

**Comment by jp2masa** [comment]
What versions of Cosmos and VS are you using?

**Comment by GenesisTechnology** [comment]
The latest versions.

**Comment by GenesisTechnology** [comment]
There must have been a problem with my download. I re-downloaded it and it seems to be working fine now. Thanks anyways.

Cheers,
Genesis
