### ISSUE TITLE
some programs

### ISSUE THREAD

**Issue by Prouser** [CosmosOS/Cosmos#62]
How can I make web browser and file explorer ? Im using C# and deving GUI system.

Thanks

**Comment by mterwoord** [comment]
Hi Prouser!

Thanks for your interest in Cosmos. Right now Cosmos doesn't support VGA (or better) yet. The filesystem support is close. Also networking does not yet fully work.

We could use help though!

Regards,
Matthijs ter Woord

**Comment by Prouser** [comment]
What about text editor and calculator ?

**Comment by mterwoord** [comment]
Using Text UI this very well possible. Other option would be to join development and get VGA going..

**Comment by Prouser** [comment]
Thanks, can you please help me with that ?

**Comment by mterwoord** [comment]
Do you have skype? If so, please add me and I'l get you going..

**Comment by Prouser** [comment]
Yes I have. Whats your name ?

**Comment by mterwoord** [comment]
same id as on github.

**Comment by Villacaleb** [comment]
I can't find any documention on file systems, can you give an example for me?

**Comment by Prouser** [comment]
If I made my os in cosmos, will it be 32 or 64bit ?  Can I install cosmos os on 64bit pc ?

**Comment by mterwoord** [comment]
@Villacaleb Please start a new discussion..

@Prouser Right now, Cosmos is purely 32-bit intel code. But any x86_64 pc is able to run 32-bit software.

**Comment by Villacaleb** [comment]
@mterwoord 
https://github.com/CosmosOS/Cosmos/issues/64
