### ISSUE TITLE
Mouse stop system

### ISSUE THREAD

**Issue by dowowTeam** [CosmosOS/Cosmos#620]
If i use mouse system is stop

**Comment by jp2masa** [comment]
How does it stop? Do you get any error?
Also, when you need help, please use the gitter chat, only open an issue when you're sure it's a Cosmos bug.

**Comment by dowowTeam** [comment]
Sorry me. I bad know English. System is stop then mouse class is created. Mouse is initialized.

**Comment by jp2masa** [comment]
Do you get any error? Have you tried to set breakpoints? Doesn't the system get stuck in a loop(while, for)?

**Comment by dowowTeam** [comment]
I can not show you an error because it's not there. When I start the system and create a new instance of the mouse, the system stops doing something. It just hangs. If you do not create a mouse - the system does not hang.

**Comment by dowowTeam** [comment]
Yes, the system has a while loop. I think that he has nothing to do with it. The while loop has a condition (true)

**Comment by jp2masa** [comment]
Probably the system gets stuck in that loop. You never break out of that loop?

**Comment by dowowTeam** [comment]
I do not break this loop.

**Comment by jp2masa** [comment]
How do you know the system is hanged? I'm almost sure the problem is that the system gets stuck in the loop.

**Comment by dowowTeam** [comment]
Okay, I'll check it.

**Comment by dowowTeam** [comment]
No. The system still hangs. I'll check one more thing.

**Comment by dowowTeam** [comment]
The system hangs when the mouse is drawn, not its class.

**Comment by jp2masa** [comment]
Do you know the line of code where it happens?

**Comment by dowowTeam** [comment]
Wait...

**Comment by dowowTeam** [comment]
Mouse rendering method:
public void DrawCursor(Hardware.Mouse MOUSE)
        {
            OS_GRAPHICS.SCREENDRIVER.SetPixel((uint)MOUSE.GetX(),(uint)MOUSE.GetY(),0,255,0);
        }

Method incoking line:
DrawCursor(MOUSE);

**Comment by dowowTeam** [comment]
Mouse - it's mouse class

**Comment by dowowTeam** [comment]
SCREENDRIVER - VBEDriver class

**Comment by dowowTeam** [comment]
I corrected the mistake! Before that, I used my class of pixel rendering. There was a mistake in it. Sorry for the time I took from you.
