### ISSUE TITLE
Login system error

### ISSUE THREAD

**Issue by CasteSoftworks** [CosmosOS/Cosmos#623]
Hi guys,
I've tryed to make a good login system, as shown in an old issue.

It checks if there is the directory login and the files username and password, and if the files dosen't exist it creates them, and if the directory dosen't exist it creates the dir and the files.

It doesn't find any error in the build, but when VMware launches it after giving the login command it stops and closes VMware. So I've putted the login code into an try/catch.

This is the code: 

`using CAFS;
user1:
            try
            {
                if (File.Exists(@"0:\login\user_nme.txt") && File.Exists(@"0:\login\pass_wrd.txt"))
                {
                    firstlog = false;
                    goto login;
                }
                else if ((Directory.Exists(@"0:\login\")))
                {
                    CAFS.createFile(@"0:\login\user_name.txt");
                    CAFS.createFile(@"0:\login\pass_wrd.txt");
                    goto login;
                }
                else
                {
                    CAFS.createDir(@"0:\login");
                    CAFS.createFile(@"0:\login\user_name.txt");
                    CAFS.createFile(@"0:\login\pass_wrd.txt");
                    goto login;
                }

                login:
                if (firstlog)
                {
                    Console.Write("Set the user's name: ");
                    var nomeutente = Console.ReadLine();
                    CAFS.writeText(@"0:\login\user_name.txt", nomeutente);
                    Console.Write("Set password: ");
                    var passwrd = Console.ReadLine();
                    CAFS.writeText(@"0:\login\pass_wrd.txt", passwrd);
                }
                else
                {
                    Console.WriteLine("You must log in!");
                    setuser:
                    Console.Write("User: ");
                    var user = Console.ReadLine();
                    var usernm = File.ReadAllText(@"0:\login\user_name.txt");
                    if (user == usernm)
                    {
                        Console.WriteLine(user + "recognized");
                        user = username;
                    }
                    else
                    {
                        Console.WriteLine("Not correct username");
                        goto setuser;
                    }
                    setpsswrd:
                    Console.Write("Password: ");
                    var passwd = Console.ReadLine();
                    var passwdrd = File.ReadAllText(@"0:\login\pass_wrd.txt");
                    if (passwd == passwdrd)
                    {
                        goto booted;
                    }
                    else
                    {
                        Console.WriteLine("Not correct password" + user);
                        goto setpsswrd;
                    }
                }
            }

            catch
            {
                goto booted;
            }`

Can you help me? I'm using the last stable source.

**Comment by jp2masa** [comment]
You forgot an 'a' in `File.Exists(@"0:\login\user_nme.txt")` and you should avoid using `goto`. Also, what version of Cosmos are you using? If it's the latest master, long filenames aren't supported.

**Comment by CasteSoftworks** [comment]
Fixed the 'a' but then when I build it finds an error and so it directly goes at the Run().
:(

**Comment by CasteSoftworks** [comment]
also made files shorter 😞

**Comment by jp2masa** [comment]
Try using mDebugger methods to know what line of code is causing the issue.

**Comment by CasteSoftworks** [comment]
how can I use mDebugger? Sorry I'm not so expert

**Comment by jp2masa** [comment]
In a Kernel method use for example `mDebugger.Send("message")` and it should appear in the Output window when that line is executed.

**Comment by CasteSoftworks** [comment]
It don't show anything in output

**Comment by jp2masa** [comment]
I think that you need to change "Show ouput from:", I don't remember well, but I think there's a "Cosmos" option.

**Comment by CasteSoftworks** [comment]
I can't find it
😢

**Comment by jp2masa** [comment]
What options do you have?

**Comment by zarlo** [comment]
@CasteSoftworks its not the best practice to use goto

**Comment by valentinbreiz** [comment]
Ah ah @CasteSoftworks I just made a login system, It's parfetly working :)
https://github.com/valentinbreiz/Ode-OS/blob/master/Ode%20OS/Kernel.cs (line 125 to 190)

**Comment by CasteSoftworks** [comment]
@valentinbreiz thanks a lot
