### ISSUE TITLE
Text problem.

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#624]
I think this is a bug, but why when the new Console.WriteLine("Test"); appears, there is sometimes some text in addition:
![capture](https://cloud.githubusercontent.com/assets/18724279/25290900/376fa4b6-26d0-11e7-8697-3b5a9f2f1a62.PNG)

**Comment by zarlo** [comment]
does this happen every time

**Comment by valentinbreiz** [comment]
I don't know, not every time :/

**Comment by Lercher** [comment]
In Windows .net console programs such effects are common, when you use the console in multiple threads concurrently. Here it seems to be a problem with scrolling the console contents in parallel with outputting some text to it.

**Comment by valentinbreiz** [comment]
And how can I solve it @Lercher ?

**Comment by DjAlEx234** [comment]
why do you need to do console.writeline("test") anyway

**Comment by valentinbreiz** [comment]
@DjAlEx234 to do commands, here in the screenshot "help" to see all other commands !

**Comment by pekira001** [comment]
@Lercher The problem is not scrolling but yes how log the string is

**Comment by fanoI** [comment]
That is does it happens when you do Console.WriteLine() in a for loop?

**Comment by valentinbreiz** [comment]
@fanoI it happens when a string is superior than 40 characters.
I tried on Vmware, bochs, Virtual Box there always is that problem.

**Comment by fanoI** [comment]
Good catch!
So it seems that in some part of the Console.Write() code there is a wrong Cols / 2...

The problem should be here:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System/Console.cs#L72

or more probably here (why there is multiplication by 2?):
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL/TextScreen.cs#L71

well try to "play" with it, I think you are closer to find the bug!

**Comment by Arawn-Davies** [comment]
Anyone got any solutions for this?

**Comment by valentinbreiz** [comment]
@Arawn-Davies no :/

**Comment by Arawn-Davies** [comment]
dang :/ what could it be? is it like when the WriteLine string is more than 80? or 40? or what :/

**Comment by valentinbreiz** [comment]
The bug happen when the string il longer than the half of "console" columns (80 columns).

**Comment by Arawn-Davies** [comment]
ah, whats the current console size? 80x25?

**Comment by valentinbreiz** [comment]
Yep

**Comment by VortexIncAdmin** [comment]
I've seen this on my Linux distribution. This seems to be a default problem with OSes.

**Comment by valentinbreiz** [comment]
Did you fix this ?

**Comment by jp2masa** [comment]
I pushed a fix for this bug to the netcore branch, it should be working now.

**Comment by valentinbreiz** [comment]
It is working ! :D
