### ISSUE TITLE
Can't install on VS2017

### ISSUE THREAD

**Issue by CasteSoftworks** [CosmosOS/Cosmos#625]
Hi guys,
last week my pc broke up and I needed to format the drive and re-install Win, so I lost all, Cosmos and VS2015 included.
Now I've tryed to install Cosmos on VS2017 (I've installed all the stuff that is needed), but when I've downloaded the repo, i've noticed that there isn't any `install-VS2017.bat` unlike the wiki says, but there is `install-VS2015.bat`. I've tryed to install that bile but after 2 seconds this error appears:
![cattura](https://cloud.githubusercontent.com/assets/26233132/25348942/41470a2c-2920-11e7-88fe-9a09ea32e6af.PNG)
(it says: can't find file)
Can you help me plese?
I've also tryed downloadning the lastest source, but nothing works

**Comment by jp2masa** [comment]
VS2017 support is coming soon, as the wiki says. However, the master branch should work fine for VS2015. Do you have VS2015 installed?

**Comment by CasteSoftworks** [comment]
No, I had to format all my old drive and when I tryed to download VS2015, on microsoft's site there was only VS2017.
Sorry, I tought that was just a not-updated page.
Do I need to close the issue or not?

**Comment by jp2masa** [comment]
Better close it.
