### ISSUE TITLE
Error occured while invoking IL2CPU

### ISSUE THREAD

**Issue by pekira001** [CosmosOS/Cosmos#626]
Hello i am facing this problem 

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while invoking IL2CPU.	CosmosKernel1Boot	C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets	31	
`
The first time it appeared i just restarted visual studio and it work, now even restarting my pc it doesn't work! please help.

**Comment by jp2masa** [comment]
See the output log, the actual error is there.

**Comment by pekira001** [comment]
@jp2masa  sorry for answerer so late

`1>------ Build started: Project: DeadOS, Configuration: Debug Any CPU ------
1>  DeadOS -> c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll
2>------ Build started: Project: DeadOSBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = 'c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Plug found: 'Cosmos.Core.CPU'
2>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Plug found: 'Cosmos.Core.IOPortBase'
2>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Plug found: 'System.Char'
2>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Plug found: 'System.Random'
2>	Plug found: 'System.Console'
2>	Plug found: 'System.Type'
2>	Plug found: 'System.Threading.Monitor'
2>	Plug found: 'System.Text.DecoderFallback'
2>	Plug found: 'System.Text.EncoderFallback'
2>	Plug found: 'System.Text.ASCIIEncoding'
2>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void  System.Threading.Thread.MemoryBarrier().
2>	 Called from :
2>	System.IO.StreamWriter::System.Text.Encoding get_UTF8NoBOM()
2>	System.IO.File::Void WriteAllLines(System.String, System.String[])
2>	DeadOS.Kernel::Void BeforeRun()
2>	Cosmos.System.Kernel::Void BeforeRun()
2>	   em Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) em c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 525
2>	   em Cosmos.IL2CPU.ILScanner.ScanQueue() em c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
2>	   em Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) em c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   em Cosmos.IL2CPU.CompilerEngine.Execute() em c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
Build has been canceled.`

**Comment by jp2masa** [comment]
Are you using the userkit or the devkit?

**Comment by pekira001** [comment]
@jp2masa

**Comment by pekira001** [comment]
@jp2masa userkit

**Comment by jp2masa** [comment]
The userkit doesn't have support for FAT, If you want to use it, you need the devkit.

**Comment by pekira001** [comment]
@jp2masa FAT?

**Comment by jp2masa** [comment]
FAT is the only filesystem currently working on Cosmos.

**Comment by pekira001** [comment]
@jp2masa i used System.io and then i used file create and file read. is that the problem?

**Comment by jp2masa** [comment]
You need to initialize the filesystem first, but you need the devkit. See this: https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

**Comment by pekira001** [comment]
@jp2masa ok i will try if it works or not i say something

**Comment by pekira001** [comment]
@jp2masa i am having a problem when i start install-VS2015.bat it runs well when it finishes deleting a creating files it says 20 warning and 0 error then it jumps to compile and then stops working. What should i do?

**Comment by jp2masa** [comment]
What error do you get? The installation is complete when Visual Studio is opened.

**Comment by pekira001** [comment]
@jp2masa ignore my last question when i read this ("https://github.com/CosmosOS/Cosmos/wiki/Devkit") i think i need this ("https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20150918") but actually i needed this ("https://github.com/CosmosOS/Cosmos/archive/master.zip")

**Comment by pekira001** [comment]
@jp2masa still geting the same error

(output)
`1>------ Build started: Project: DeadOSBoot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>	Working directory = 'c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Int32  System.Threading.Thread.get_ManagedThreadId().
1>	 Called from :
1>	System.IO.Iterator`1[System.String]::System.Collections.Generic.IEnumerator`1[System.String] GetEnumerator()
1>	System.Collections.Generic.IEnumerable`1[System.String]::System.Collections.Generic.IEnumerator`1[System.String] GetEnumerator()
1>	   em Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) em C:\Users\Pekira\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 522
1>	   em Cosmos.IL2CPU.ILScanner.ScanQueue() em C:\Users\Pekira\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 663
1>	   em Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) em C:\Users\Pekira\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 243
1>	   em Cosmos.IL2CPU.CompilerEngine.Execute() em C:\Users\Pekira\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	c:\users\pekira\documents\visual studio 2015\Projects\DeadOS\DeadOS\bin\Debug\DeadOS.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Pekira\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Memory.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_pt_b77a5c561934e089\mscorlib.resources.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.7664649
1>Done building project "DeadOSBoot.Cosmos" -- FAILED.
1>
Build has been canceled.`

**Comment by pekira001** [comment]
This is my code

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Linq;
using Sys = Cosmos.System;

namespace DeadOS
{
    public class Kernel : Sys.Kernel
    {

        public bool UserExst;

        public string Username;
        public string Password;
        public string ConfPass;

        protected override void BeforeRun()
        {

            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);

            Console.Clear();
            if (File.Exists(@"C:\Sys\User.txt"))
            {
                UserExst = true;
            }
            else
            {
                UserExst = false;
            }

            if (UserExst == false)
            {
                Console.WriteLine("Welcome to DeadOS aplha v0.1");
                Console.WriteLine("Please create a new user");
                Console.WriteLine("Enter a Username: ");
                Username = Console.ReadLine();
                Console.WriteLine("Please enter a Password: ");
                Password = Console.ReadLine();
                Console.WriteLine("Please confirm a Password: ");
                ConfPass = Console.ReadLine();

                if (ConfPass != Password)
                {
                    Console.WriteLine("Password didn't match");
                    Console.Write("Reboting");
                    Sys.Power.Reboot();
                }
                else
                {
                    File.Create(@"C:\Sys\User.txt");
                    string[] UserInfo = { Username, Password };
                    File.WriteAllLines(@"C:\Sys\User.txt", UserInfo);
                    string UserTest = File.ReadLines(@"C:\Sys\User.txt").First();
                    Console.Clear();
                    Console.WriteLine("Thank you for chosing DeadOS " + UserTest);
                }

            }
            else
            {
                Username = File.ReadLines(@"C:\Sys\User.txt").First();
                Password = File.ReadLines(@"C:\Sys\User.txt").Skip(1).Take(1).First();
                Console.WriteLine("Welcomne back " + Username);
                Console.WriteLine("Please enter your password: ");
                ConfPass = Console.ReadLine();
                if (ConfPass == Password)
                {
                    Console.Clear();
                    Console.WriteLine("DeadOS aplha v0.1");
                }
                else
                {
                    Console.WriteLine("Wrong Password");
                    Console.WriteLine("Try again");
                    Sys.Power.Reboot();
                }
            }
        }
        protected override void Run()
        {

        }
    }
}
'

**Comment by pekira001** [comment]
@jp2masa i think the problem is in the code because if i clean everything it works i will try to find

**Comment by jp2masa** [comment]
I think the problem is in these two line:
`string UserTest = File.ReadLines(@"C:\Sys\User.txt").First();`
`Password = File.ReadLines(@"C:\Sys\User.txt").Skip(1).Take(1).First();`

**Comment by pekira001** [comment]
@jp2masa its right them the error shows in `string UserTest = File.ReadLines(@"C:\Sys\User.txt").First();`

**Comment by pekira001** [comment]
i think i need to use ReadAllLines and loop between the lines to find the first and second

**Comment by pekira001** [comment]
Cannot apply indexing with [] to an expression of type 'IEnumerable<string>'

**Comment by jp2masa** [comment]
I thought it was a List... You'll have to iterate through it to get the first item. You can try casting it to List<string> but probably it doesn't work.

**Comment by pekira001** [comment]
@jp2masa stream reader doesn't work also

**Comment by jp2masa** [comment]
I know that, it will be implemented when the .net core work is ready, as well as StreamWriter.

**Comment by pekira001** [comment]
@jp2masa can you tell me where i can contribute to cosmos source?

**Comment by pekira001** [comment]
Problem resolve when .net core is ready
