### ISSUE TITLE
Bug with created directory

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#627]
I use that command to create a directory:
FS.CreateDirectory("0:\\Users\\" + name+ "\\Documents");
It works fine but I don't have "0:\Users\valentinbreiz\Documents", I have "0:\Users\valentinbreiz\Document.s". A dot has been added between "t" and "s"... Why ?

**Comment by jp2masa** [comment]
I'll check that, probably it's being confused with a file, it's a bug on name read.

**Comment by valentinbreiz** [comment]
But it creates fine in 0:\Users\valentinbreiz\... So name is readed fine?

**Comment by jp2masa** [comment]
That's a long filename.

**Comment by valentinbreiz** [comment]
I get name var with : var name = File.ReadAllText("0:\\System\\user.txt");
And in this file I just have "valentinbreiz".

**Comment by jp2masa** [comment]
The bug is here: https://github.com/jp2masa/Cosmos/blob/Bugfixes/source/Cosmos.System/FileSystem/FAT/Listing/FatDiretoryEntry.cs#L447. It doesn't check if the entry is a file or a directory and adds the dot whenever there are more than 8 chars in the entry.

**Comment by jp2masa** [comment]
I updated my branch, it should be working now.

**Comment by valentinbreiz** [comment]
Wich branch ?

**Comment by valentinbreiz** [comment]
If I understood correctly, "public const int File = 0x??;" is missing in FatDirectoryEntryAttributeConsts.cs

**Comment by jp2masa** [comment]
I'll fix my branch later today. There's no attribute for file.

**Comment by jp2masa** [comment]
It should be working now.

**Comment by valentinbreiz** [comment]
Yes it is thank you ! :)

**Comment by valentinbreiz** [comment]
For those who have the same bug https://github.com/jp2masa/Cosmos/tree/Bugfixes :)
