### ISSUE TITLE
release 2015

### ISSUE THREAD

**Issue by Prouser** [CosmosOS/Cosmos#63]
Hi, what new features are in the newest release ?

**Comment by mterwoord** [comment]
On going improvements all around.. Hard to tell specifically.

**Comment by Prouser** [comment]
Im using latest version from previous site, should I upgrade to Github version ?

**Comment by mterwoord** [comment]
Yes, github contains the latest.

**Comment by Prouser** [comment]
Will my project stay or be lost during update ?

**Comment by mterwoord** [comment]
Your project will stay.

**Comment by Prouser** [comment]
Ok, if I'll make my os, hiw can I make instalation ?

**Comment by mterwoord** [comment]
Right now, we don't have facilities to make an installation.

**Comment by Prouser** [comment]
Does exist some 3rd party apps ?
