### ISSUE TITLE
Console Colors aren't working for VS2013

### ISSUE THREAD

**Issue by KL4932** [CosmosOS/Cosmos#632]
Hi
I'm new to COSMOS, i'm using User Kit VS2013, anyways..
I Use `Console.BackgroundColor = ConsoleColor.Red` and the same goes
nothing changed like i didn't type that code
i used dewitcher and his Console Functions and i got errors
`(Error occurred while invoking IL2CPU)`
`(Exception: System.Exception: Assembly 'Serenal(OS)' is in ring User(3). It references assembly 'Cosmos.HAL' which is in ring HAL(1), but this is not allowed!)`
`(at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 97)`
`(at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 240)`
Please help me fix this issue, i want to make my first operating system using COSMOS :)

**Comment by KL4932** [comment]
FYI i used 
`var textscr = Cosmos.HAL.Global.TextScreen;`
`Cosmos.System.Global.Console = new Cosmos.System.Console(textscr);`
`Cosmos.HAL.Global.TextScreen = textscr;`
`Console.ForegroundColor = ConsoleColor.Black;`
`Console.BackgroundColor = ConsoleColor.White;`
 `Console.WriteLine("test");`
and i got the same error

**Comment by valentinbreiz** [comment]
@KL4932 use Visual Studio 2015 ! :P

**Comment by KL4932** [comment]
@valentinberiz ok
