### ISSUE TITLE
Issue with the VGAScreen 

### ISSUE THREAD

**Issue by KL4932** [CosmosOS/Cosmos#634]
Encountered another issue
i have an issue on VGAScreen
the issue is when i boot the VGAScreen using
```C#
screendriver.init();
```
or
```C#
screen.SetGraphicMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
screen.Clear(0);
```
I Get a glitched display
i test it on VMWare and real hardware
Real Hardware:
![win_20170505_04_43_22_pro](http://i.imgur.com/6CuugUN.jpg)
VMWare:
![other 64-bit-2017-05-05-05-01-22](https://cloud.githubusercontent.com/assets/28347117/25731565/ef597028-314f-11e7-823f-3926296c0eb5.png)
Weird huh
it just put blacks in the screen, and the screen freeze
anyways, please fix this issue, i want to create my operating system );

**Comment by jp2masa** [comment]
VGAScreen doesn't work, only Bochs VBE is supported at the moment.

**Comment by valentinbreiz** [comment]
@KL4932 for now you van use canvas. See https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Graphic-Subsystem :)

**Comment by valentinbreiz** [comment]
And how did you do to boot your os on real hardware ?

**Comment by KL4932** [comment]
i use network boot
i can make a guide for it

**Comment by KL4932** [comment]
@jp2masa @valentinbreiz then how to implement the mouse :(

**Comment by jp2masa** [comment]
It shouldn't be hard, the only thing that changes is the way you draw the mouse, now you use Canvas.

**Comment by valentinbreiz** [comment]
Oh you can make a guide @KL4932 !

**Comment by KL4932** [comment]
@valentinbreiz how to

**Comment by valentinbreiz** [comment]
By doing a new wiki page : https://github.com/CosmosOS/Cosmos/wiki/_new

**Comment by KL4932** [comment]
https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Fix-Stuck-on-Creating-ATA-IOGroup
https://github.com/CosmosOS/Cosmos/wiki/Booting-Your-OS-using-Ethernet

**Comment by valentinbreiz** [comment]
Thank you very much @KL4932 ! :)

**Comment by KL4932** [comment]
@valentinbreiz you're welcome
and i want to talk with you on gitter

**Comment by valentinbreiz** [comment]
Ok let's go !

**Comment by fanoI** [comment]
but with only In any case I think VGA support does not make sense in 2017... do you want really do a GUI at  320x240@256 colors or at 640x480 but with only 16 colors?

Well better to make the native VmWare driver work... for the real GPU the universal driver is not VGA anymore but VBE.

**Comment by KL4932** [comment]
@fanol now i'm trying to adapt VGA to CGS

**Comment by KingLuigi4932** [comment]
Wow
My picture looks ugly xD
