### ISSUE TITLE
Other Virtual Machine Emulator?

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#636]
I don't really want to use VMware. Can I use another VM Emulator, such as QEMU? 😉

**Comment by valentinbreiz** [comment]
@VortexIncAdmin Virtual Box works but whithout FileSystem. Bochs works fine but I think VMWare is the best..

**Comment by VortexIncAdmin** [comment]
I didn't want to use VirtualBox, but I'll find out about Bochs. Thanks! ;)

**Comment by czhower** [comment]
QEMU on Windows is loaded with bugs.. often simple ones that have been 
reported for years, but since the devs are all Linux guys, they dont 
even care enough to make binary distros for Windows... you think they 
bother to test it much on Windows?

**Comment by VortexIncAdmin** [comment]
Considering they are developing on Linux, no. I agree with you.

**Comment by VortexIncAdmin** [comment]
Actually, Wine is good enough. So I'll use QEMU.
