### ISSUE TITLE
Virtual Machine Questions?

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#637]
I did not want to use VMware or VirtualBox, so I'm going with Bochs. Unfortunately, I just found about this Virtual Machine Emulator. Can someone give me what I need to know about Bochs? Thanks! 😉

**Comment by jp2masa** [comment]
To use Bochs you just need to change to the Bochs profile in the Cosmos project settings. That is enough unless you want to debug assembly.

**Comment by VortexIncAdmin** [comment]
Thanks!

**Comment by VortexIncAdmin** [comment]
Oh, also can anyone send an installation tutorial for Bochs? When I searched "how to install bochs", all that came up was for the MOBILE version of Bochs.

**Comment by jp2masa** [comment]
Download it here: https://sourceforge.net/projects/bochs/files/bochs/2.6.9/

**Comment by VortexIncAdmin** [comment]
Bochs-2.6.9.exe, right? And will installing Bochs do the same thing when VirtualBox installs networking drivers? Because I don't want dead networking.

**Comment by valentinbreiz** [comment]
Cosmos doesn't support network yet :/

**Comment by czhower** [comment]
Its high on our list after VS2017/Core.

**Comment by VortexIncAdmin** [comment]
I meant the networking feature in VirtualBox when you install it, not networking in COSMOS. When the VirtualBox networking feature installs, it resets the connected network. Is that the same for Bochs?

**Comment by jp2masa** [comment]
Bochs installation doesn't reset the connected network.
