### ISSUE TITLE
How to include ASSEMBLY

### ISSUE THREAD

**Issue by Lrios4403** [CosmosOS/Cosmos#638]
SO I want to include some basic assembly (int 10h, mov ax, ext.) is there a way i can do this?

**Comment by jp2masa** [comment]
You can use plugs for that. You can look at [this method](https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core.Plugs/ProcessorInformationImpl.cs#L155), which is a plug for [this method](https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Core/ProcessorInformation.cs#L40).

**Comment by Lrios4403** [comment]
thanks

**Comment by Lrios4403** [comment]
ok I dont think you get what i mean. The purpos I need asssembly is the int 10h function (in order to move cursor, Console.SetCursorPosition is not avaliable)

**Comment by czhower** [comment]
On 5/8/2017 6:12 PM, Lrios4403 wrote:
> ok I dont think you get what i mean. The purpos I need asssembly is the
> int 10h function (in order to move cursor, Console.SetCursorPosition is
> not avaliable)

What you are looking for is BIOS calls. You can't do those in 32 bit 
mode, only 16 bit.

**Comment by Lrios4403** [comment]
ok. Do you have another solution to move the cursor in console mode?

**Comment by fanoI** [comment]
why the cursor does not move already?
Do you have tried to set Console.CursorVible at true?

https://msdn.microsoft.com/en-us/library/system.console.cursorvisible(v=vs.110).aspx

**Comment by KL4932** [comment]
is there a default graphics for mouse or something .. how would you move a cursor when there is no cursor or there is no graphics driver ..

**Comment by Lrios4403** [comment]
![capture](https://cloud.githubusercontent.com/assets/16861047/25835930/87c0a860-3437-11e7-94ee-e268a41833df.PNG)

**Comment by fanoI** [comment]
Are you using the last version? If you are using the UserKit is code really old!
It is plugged as you can see:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System.Plugs/System/ConsoleImpl.cs#522

**Comment by fanoI** [comment]
@KL4932 we are talking to of the graphic cursor of text cursor the '|' that you see when write text :-)

**Comment by fanoI** [comment]
Sorry but my Linux machine is totally broken (I hope to use Cosmos one day :-)) cannot edit post anymore!

@KL4932 we are NOT talking of the graphic cursor but of text cursor the '|' that you see when write text :-)
You can do graphic cursor (and more) using CGS: https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Graphic-Subsystem

**Comment by Lrios4403** [comment]
alright thanks
