### ISSUE TITLE
Who can give me a new user Kit version Visual Studio 2017 ？

### ISSUE THREAD

**Issue by caonima2900445768** [CosmosOS/Cosmos#639]
Who can give me a new user Kit version Visual Studio 2017 ？

I now see the Web page on the download is still Userkit 20150918 to feel angry (ironically this day is my birthday)

😊

**Comment by fanoI** [comment]
The UserKit is so old that in any case is better to use the DevKit (that is simply a fork the "main" branch compiled).
A version of the Cosmos DevKit that work on VS2017 using Net Core should arrive soon.
