### ISSUE TITLE
How make a filing system?

### ISSUE THREAD

**Issue by Villacaleb** [CosmosOS/Cosmos#64]
I can't find any proper documention on almost everything, and theres one big thing I need to know, how do we read/write files? Stream Writer does not work.

**Comment by Prouser** [comment]
Do you making GUI or DOS-like system ?

**Comment by mterwoord** [comment]
We've been pretty much a moving target. 

However, using filesystem will be like normal, using System.IO namespace. Unfortunately we're still working on that..

**Comment by Villacaleb** [comment]
@Prouser 
Command line.
@mterwoord 
I seen a few people do it, but I can't find any example.

**Comment by mterwoord** [comment]
System.IO? Try msdn. But like I said, current version (either latest release or latest master) don't support that. We're hunting down a compiler bug..

**Comment by Villacaleb** [comment]
@mterwoord I see, hopefully it will be fixed soon, can't do much if you can't read/write files.

**Comment by jordansrowles** [comment]
I think I've seen a file system called GLNFS in several Cosmos projects. It was developed by gruntxproductions (Grunt).
[Codeplex - How to use Grunt's GLNFS?](https://cosmos.codeplex.com/discussions/397360)
[GLNFS implementation (thread)](http://gruntxproductions.net/OCA/Upload/showthread.php?tid=163)
[GruntyOS: Infinity](http://infinitykernel.codeplex.com/)

Just Google GLNFS and do some digging, but it seems like this file system worked?

**Comment by Villacaleb** [comment]
@jordansrowles Thanks that will help alot.
