### ISSUE TITLE
Cosmos on real hardware (With AHCI or RAID mode)

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#640]
It is a known issue but I submit it to try to centralize information to find a solution to this problem.
So, Cosmos can't boot on real hardware with SATA Controller mode selected on AHCI or RAID.
The bug happens here, when ATA is initialized: https://github.com/CosmosOS/Cosmos/blob/1a7aed06116ff8b280df8a0efc5d40c85a29ea17/source/Cosmos.HAL/Global.cs#L19, where InitAta() method is called.

Some quotation from gitter:
"if you have SATA devices, ATA initialization will crash" @jp2masa

"The real bug is in the "hard coding" Cosmos should enumerate the PCI devices find if there are HDD, if there are if they are ATA or SATA and if they are SATA do the right thing to initialize it
Inizializing a SATA drive (better to say bus) as ATA makes no sense" @fanoI

Other infos, Cosmos can boot on VMWare or Bochs because there is no "HDD drivers" and Virtual Box can boot only if HDD is disabled.
Also, it can boot on real hardware if SATA Controller mode is changed to IDE from the BIOS.

To do:
- [x] Fix #666;
- [x] Find a way to know if the machine use IDE, RAID or AHCI (not difficult if 666 fixed)
- [x] Implement it.

If the machine uses AHCI: (because most of new computers uses AHCI)
- [x] Implement an AHCI "driver".
- [x] Then load partitions with that driver.

**Comment by czhower** [comment]
You are oversimplifying the issue. Its not enough to detect SATA if SATA 
isn't supported which it isn't and wont be for a bit yet because of 
higher priority items.

Instead in your BIOS set your SATA drive to enable legacy mode and 
Cosmos works fine.

**Comment by fanoI** [comment]
My idea is to start to have a minimal thing here that is using PCI scanning purposely search for the master ATA device and return error / exception if not found it is not "elegant" to simply remain stuck doing nothing.

There is no the risk to damage the user hardware doing wrong things?

**Comment by valentinbreiz** [comment]
To do:
- Fix #666;
- Implement an AHCI "driver".

**Comment by KingLuigi4932** [comment]
@czhower Most of the laptops has the AHCI mode + Most of the laptops (again) cannot change their boot mode to IDE

**Comment by KingLuigi4932** [comment]
Will be fixed

**Comment by KingLuigi4932** [comment]
You should check the boxes now @valentinbreiz
