### ISSUE TITLE
Unsupported for Visual Studio 2017

### ISSUE THREAD

**Issue by zombieknifer223** [CosmosOS/Cosmos#642]
The new Visual Studio 2017 came out and I was excited to update to the new version. When I tried to install Cosmos Dev Kit it said 2013 version was not found. I thought that the developers would keep up with Visual Studio. There is literally nothing to write here other then that Cosmos OS Dev Kit is unsupported for Visual Studio 2017, but mainly because it's only checking for Visual Studio 2013. I just want this error fixed.

**Comment by jp2masa** [comment]
The latest devkit supports Visual Studio 2015. We're working on Visual Studio 2017 support, it's almost ready.
