### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#643]
Can someone tell me a COSMOS installation video tutorial? Thanks! ;)

**Comment by valentinbreiz** [comment]
There is https://github.com/CosmosOS/Cosmos/wiki/How-to-install-Cosmos ;)

**Comment by DjAlEx234** [comment]
That video would take a while to watch, saying the installer has to build all of cosmos in one take.

**Comment by valentinbreiz** [comment]
@DjAlEx234 it doesn't take long :P

**Comment by DjAlEx234** [comment]
my laptop takes a while

**Comment by VortexIncAdmin** [comment]
NVM. Just found a (slightly outdated) video. Thanks anyways! ;)

**Comment by VortexIncAdmin** [comment]
It is REALLY FAST, but the "Finishing installation..." part takes a long time.

**Comment by valentinbreiz** [comment]
Can you give the link @VortexIncAdmin ?

**Comment by VortexIncAdmin** [comment]
You mean for the download link? If so, here is the latest version: https://github.com/CosmosOS/Cosmos/releases/download/Userkit_20150918/CosmosUserKit-20150918-vs2015.exe

**Comment by valentinbreiz** [comment]
@VortexIncAdmin of the video :P
