### ISSUE TITLE
Before Starting...

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#644]
Just 1 more question... BTW this may sound like a noob question. How do I run COSMOS in QEMU? Thanks! ;)

**Comment by jp2masa** [comment]
Cosmos doesn't have official support for QEMU, but you can use the ISO profile and run the ISO in QEMU.

**Comment by VortexIncAdmin** [comment]
So how do I build COSMOS without running it in a VM, and what architecture do I need to use?

**Comment by jp2masa** [comment]
You use the ISO profile, in the Cosmos project properties.

**Comment by VortexIncAdmin** [comment]
Thanks! ;)

**Comment by VortexIncAdmin** [comment]
I dragged the COSMOS image to the QEMU x86_64 app, and what I get is:
![capture 23](https://cloud.githubusercontent.com/assets/15951904/26039074/c342048c-38ca-11e7-974a-56abc6fce688.PNG)
Any solution?

**Comment by fanoI** [comment]
Cannot you use the supported VM? That is VmWare and Bochs?

**Comment by czhower** [comment]
QEMU on Windows is loaded with bugs. All the QEMU devs are on Linux and 
simply don't care about Windows.

**Comment by VortexIncAdmin** [comment]
And they test the Windows version with the WINE emulator, which is also filled with bugs... I'll do Bochs.

**Comment by VortexIncAdmin** [comment]
BTW I am using the User Kit. I built it with no changes to see if it boots.
