### ISSUE TITLE
No Kernel Found?

### ISSUE THREAD

**Issue by Lrios4403** [CosmosOS/Cosmos#645]
There is a issue with "No kernel found"
[Startup_OS.zip](https://github.com/CosmosOS/Cosmos/files/999996/Startup_OS.zip)

**Comment by valentinbreiz** [comment]
Can you send a screenshot or more details ?

**Comment by jp2masa** [comment]
@Lrios4403 Delete the project reference to the System project in the Boot project and add it again. You can edit the file manually if you prefer, you just need to replace
```xml
<ProjectReference Include="..\CosmosKernel3\System.csproj">
```
with
```xml
<ProjectReference Include="System.csproj">
```

**Comment by Lrios4403** [comment]
alright ill try

**Comment by DjAlEx234** [comment]
@Lrios4403 , did it work? I have the same problem

**Comment by Lrios4403** [comment]
NOpe

**Comment by jp2masa** [comment]
@Lrios4403 Are you still having this issue?
