### ISSUE TITLE
Cosmos.graphics does not exist! Please help!

### ISSUE THREAD

**Issue by PixelPlugins** [CosmosOS/Cosmos#648]
I love COSMOS! It's a great tool, but when i tried to follow the cgs tutorial fullscreencanvas could not be found. I tried to import Cosmos.graphics but it didn't exist. Do i need to add a new assembly reference or install a library?

**Comment by zarlo** [comment]
you need to import Cosmos.System.Graphics

**Comment by jp2masa** [comment]
@PixelPlugins You need to use the devkit.

**Comment by PixelPlugins** [comment]
Ok, thank you! I found the package but fullscreen canvas doesnt actually draw anything, event on the cgs example. I copied the code but nothing displays, just saying the "let's go into graphics mode" message.

**Comment by jp2masa** [comment]
Are you using Bochs?

**Comment by PixelPlugins** [comment]
I'm using whatever VMWare uses. Is that bad?

**Comment by jp2masa** [comment]
VMWare isn't currently supported.

**Comment by PixelPlugins** [comment]
Then what do i use that has Bochs?

**Comment by jp2masa** [comment]
For now you need to use Bochs.

**Comment by PixelPlugins** [comment]
Ill try.

**Comment by PixelPlugins** [comment]
How do i start the os with bochs, its not in the properties of the boot.

**Comment by jp2masa** [comment]
I think that you need to reinstall Cosmos.

**Comment by PixelPlugins** [comment]
ok

**Comment by PixelPlugins** [comment]
Thank you! This worked and I got some graphics! But if i put this on real hardware would it work?

**Comment by jp2masa** [comment]
No, the only driver that is currently supported is for the Bochs Graphics Adapter(it works on Bochs, VirtualBox and QEMU), but you won't need to change your code when new drivers are implemented.

**Comment by PixelPlugins** [comment]
Is the bochs driver installable  on real hardware such as raspberry pi, or only the bochs emulator?

**Comment by jp2masa** [comment]
The Bochs driver doesn't work on real hardware. Raspberry Pi has an ARM architecture processor, we currently only support x86.
