### ISSUE TITLE
Change keyboard layout

### ISSUE THREAD

**Issue by Moritz30** [CosmosOS/Cosmos#649]
Is it possible to change the keyboard layout and/or define an own one?

**Comment by zarlo** [comment]
yes have a look in the Cosmos.System.KeyboardManager class

**Comment by fanoI** [comment]
It should work using a method in the Kernel class too: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System/Kernel.cs#L34

For example to use the DE layout:

```cs
// in BeforeRun() or when user calls a "command"
SetKeyboardScanMap(new DE_Standard());
```

**Comment by Moritz30** [comment]
Thanks.

**Comment by fanoI** [comment]
It is working as intended?

**Comment by Moritz30** [comment]
yes, it does.
