### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Prouser** [CosmosOS/Cosmos#65]
I wrote a standard code (changing color of background) if i write Blue (name of color) the entire system freezes and i cant do anything. I use Console.ReadLine();

**Comment by mterwoord** [comment]
What release are you? Latest?
If so, we might have released a build which has disabled interrupts, but
hardly doubt that..


2015-03-04 17:38 GMT+01:00 Jacob <notifications@github.com>:

**Comment by Prouser** [comment]
@mterwoord if I send you my project, can You please look at it ?

**Comment by mterwoord** [comment]
What release are you on?

**Comment by Prouser** [comment]
Latest

**Comment by Prouser** [comment]
@mterwoord latest, can I send it to Your email ?

**Comment by mterwoord** [comment]
Are you able to build our devkit? (Ie, master from github)

We verified, that one should work.

**Comment by Prouser** [comment]
@mterwoord I used so many if´s, can it be the problem ?

**Comment by mterwoord** [comment]
Shouldn't be. Can you tried devkit? Also, did you try in a simple echoing app?

**Comment by Prouser** [comment]
@mterwoord I'll look at devkit, its necessarily to download all stuff (such as sql) ?

**Comment by mterwoord** [comment]
SQL? No. For installing devkit you need:
- VS SDK
- InnoSetup QUickStart pack
- (VS SDK needs VS Standard or up)

**Comment by mterwoord** [comment]
Please contact me per skype, and I can get you going..
