### ISSUE TITLE
VB.NET Try Catch not working

### ISSUE THREAD

**Issue by Moritz30** [CosmosOS/Cosmos#650]
VB.NET Try Catch blocks do not work.

`Imports System
Imports Cosmos.System.Graphics

Namespace CosmosKernel2

    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Dim canvas As Canvas

        Protected Overrides Sub BeforeRun()
            Console.WriteLine("Booted successfully. Starting GUI...")
            canvas = FullScreenCanvas.GetFullScreenCanvas()
            canvas.Clear(Color.Orange)
        End Sub

        Protected Overrides Sub Run()
            Try
                Dim Pen As Pen = New Pen(Color.Red)
                canvas.DrawPoint(Pen, 69, 69)

                Pen.Color = Color.GreenYellow
                canvas.DrawLine(Pen, 250, 100, 400, 100)

                Pen.Color = Color.IndianRed
                canvas.DrawLine(Pen, 350, 150, 350, 250)

                Pen.Color = Color.MintCream
                canvas.DrawLine(Pen, 250, 150, 400, 250)

                Pen.Color = Color.PaleVioletRed
                canvas.DrawRectangle(Pen, 350, 350, 80, 60)

                Pen.Color = Color.Chartreuse
                canvas.DrawCircle(Pen, 69, 69, 10)

                Pen.Color = Color.LightSalmon
                canvas.DrawEllipse(Pen, 400, 300, 100, 150)

                Pen.Color = Color.MediumPurple
                canvas.DrawPolygon(Pen, New Point(200, 250), New Point(250, 300), New Point(220, 350), New Point(210, 275))
                Console.ReadKey()

                canvas.Mode = New Mode(800, 600, ColorDepth.ColorDepth32)

                Pen.Color = Color.LimeGreen
                canvas.DrawRectangle(Pen, 450, 450, 80, 60)
                Console.ReadKey()
            Catch e As Exception
                Console.WriteLine("Got fatal exception " + e.Message)
            End Try
        End Sub

    End Class

End Namespace
`
which is just a VB.NET port of the CGS demo throws
`
Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void System.Runtime.CompilerServices.RuntimeHelpers.ProbeForSufficientStack().
2> Called from :
2> System.Runtime.CompilerServices.RuntimeHelpers::Void PrepareConstrainedRegions()
2> Microsoft.VisualBasic.CompilerServices.ProjectData::Void SetProjectError(System.Exception)
2> CosmosKernel2.CosmosKernel2.Kernel::Void Run()
2> Cosmos.System.Kernel::Void Run()
2> bei Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in D:\VBProjects\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:Zeile 522.
2> bei Cosmos.IL2CPU.ILScanner.ScanQueue() in D:\VBProjects\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:Zeile 663.
2> bei Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in D:\VBProjects\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:Zeile 243.
2> bei Cosmos.IL2CPU.CompilerEngine.Execute() in D:\VBProjects\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:Zeile 252.
`

**Comment by jp2masa** [comment]
Try setting Option Explicit On.

**Comment by Moritz30** [comment]
@jp2masa It already is.

**Comment by OffensiveCheese** [comment]
Seeing from 2> Microsoft.VisualBasic.CompilerServices.ProjectData::Void SetProjectError(System.Exception) it could be related to VB.NET exception handling

**Comment by jp2masa** [comment]
I tested the code and it's working on latest master, so I'm closing this. If you still get the same error, please feel free to reopen the issue.
