### ISSUE TITLE
CosmosKernel1Boot goes away

### ISSUE THREAD

**Issue by electrodeyt** [CosmosOS/Cosmos#651]
Self explanatory. Please fix.

**Comment by jp2masa** [comment]
What do you mean by "goes away"?

**Comment by electrodeyt** [comment]
Delets itself, or something. Cant see it in the "Tempory Projects" Folder either. Im using Devkit

**Comment by jp2masa** [comment]
How does it delete itself? It gets removed from the solution or it gets deleted from the disk?

**Comment by electrodeyt** [comment]
No, the solution keeps it, but it cant find it nor can i (in the "Tempory Projects" folder).

**Comment by jp2masa** [comment]
Right-click the other project and click "Open Folder in File Explorer" and check if there's a file called "CosmosKernel1Boot.Cosmos".

**Comment by electrodeyt** [comment]
Already did that, not there.

**Comment by jp2masa** [comment]
How did it get deleted? What triggered the deletion of the file?

**Comment by electrodeyt** [comment]
I don't know, never was there nor before i saved in the Temp folder.

**Comment by electrodeyt** [comment]
I still have the solution open with that project, saving it 1 million times does not help.
-

**Comment by jp2masa** [comment]
Try creating a new project and see if that happens again.

**Comment by electrodeyt** [comment]
Not there.

**Comment by jp2masa** [comment]
What's not there? The project file?

**Comment by electrodeyt** [comment]
Now im getting a IL2CPU Error trying to compile it for the second 2 on the stock code.

The .Cosmos file.

**Comment by electrodeyt** [comment]
development: The CosmosKernel2 Project is in the Tempory Projects folder, just did not look hard enough i guess.

**Comment by electrodeyt** [comment]
Fixed: Saved each one by selecting them In the Solution Explorer and Saving them individually. Don't know how Save all did not do that.
