### ISSUE TITLE
Error occurred while Invoking IL2CPU

### ISSUE THREAD

**Issue by electrodeyt** [CosmosOS/Cosmos#652]
So after fixing a different Issue i stumbled onto this one: Even the Stock code almost always Errors out after the second compile attempt. Sometimes cleaning the Solution fixes it; sometimes not. I don't know anything more.

**Comment by jp2masa** [comment]
What error are you getting? The Output Window has a log.

**Comment by electrodeyt** [comment]
What output window? I can't find it.

**Comment by jp2masa** [comment]
The Visual Studio Output Window.

**Comment by electrodeyt** [comment]
I can't find it. How do i open it?

**Comment by electrodeyt** [comment]
Found it:
1>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>	Working directory = 'C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Common.Document'
1>	Detecting fields for type 'Cosmos.Debug.Common.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1KernelRun': System.Exception: OpCode IL_0046: Dup tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 734
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 533 ---> System.Exception: OpCode IL_0046: Dup tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 734
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 533
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 548
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 935
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 245
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Memory.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Microsoft.Samples.Debugging.CorApi.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:01.0510809
1>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
1>
Build has been canceled.

**Comment by jp2masa** [comment]
What code are you using?

**Comment by electrodeyt** [comment]
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
namespace CosmosKernel1
{
    public class Kernel : Sys.Kernel
    {

        protected override void BeforeRun()
        {
            Console.WriteLine("eKernel codename 'Antelope'");
        }

        protected override void Run()
        {
            Console.Write(": ");
            var input = Console.ReadLine();
            if (input == "power.reboot")
            {
                Sys.Power.Reboot();
            }
            else if (input == "scr.write")
            {
                var init_list = new List<string>(input.Split(' '));
                init_list.Remove("scr.write");
                var array = init_list.ToArray();
                Console.WriteLine(string.Concat(array));

            }
            else
            {
                Console.WriteLine("Not a command");
            }
        }
    }
}

Pretty Simple. Also happens on the second run on the stock code.

**Comment by jp2masa** [comment]
The problem can be `init_list.Remove("scr.write");` or `var array = init_list.ToArray();`.

**Comment by electrodeyt** [comment]
![image](https://cloud.githubusercontent.com/assets/23217181/26465061/22f88abe-418a-11e7-96cd-696d76cec1eb.png)

**Comment by electrodeyt** [comment]
And the second compilation failed. As expected.

**Comment by electrodeyt** [comment]
1>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
1>	Working directory = 'C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.cdb' because it is being used by another process.
1>	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>	   at System.IO.File.InternalDelete(String path, Boolean checkHost)
1>	   at System.IO.File.Delete(String path)
1>	   at Cosmos.Debug.Common.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.Debug.Common\DebugInfo.cs:line 75
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 221
1>	Loaded assemblies: 
1>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
1>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.1993206
1>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
Build has been canceled.

**Comment by jp2masa** [comment]
Restart Visual Studio and try again.

**Comment by electrodeyt** [comment]
No dice.
1>------ Build started: Project: eKernel, Configuration: Release x86 ------
1>  eKernel -> C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll
2>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(34,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\CosmosKernel1Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" 
2>	Working directory = 'C:\Users\Alexander\AppData\Local\Temporary Projects\CosmosKernel1\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Common.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Common.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Common.Document'
2>	Detecting fields for type 'Cosmos.Debug.Common.Method'
2>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel1KernelRun': System.Exception: OpCode IL_0046: Dup tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 734
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 533 ---> System.Exception: OpCode IL_0046: Dup tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 734
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 576
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 533
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 935
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 245
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Alexander\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\Alexander\Documents\Visual Studio 2015\Projects\eKernel\eKernel\bin\Release\eKernel.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Memory.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Microsoft.Samples.Debugging.CorApi.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.Pdb.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:01.0024286
2>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
2>
Build has been canceled.

**Comment by charlesbetros** [comment]
Perhaps this would be easier in Gitter?

**Comment by electrodeyt** [comment]
What is that?

**Comment by electrodeyt** [comment]
Hmm, seems it was the init_list stuff that did not work, even if i commented it out earlier, now ti makes a difference.
