### ISSUE TITLE
Running questions

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#655]
I decided I'm going to use Bochs as my VM. But how do I boot COSMOS from it?

Thanks!

**Comment by valentinbreiz** [comment]
In Visual Studio, open your Cosmos operating system project. Right click on YourOSNameBoot and change the profile to bochs.

**Comment by VortexIncAdmin** [comment]
Well that was quick. I'll see if it works ;)

**Comment by VortexIncAdmin** [comment]
Works! ;D

**Comment by valentinbreiz** [comment]
You can close this issue now ;)

**Comment by VortexIncAdmin** [comment]
Thanks ;)
