### ISSUE TITLE
Graphics Errors

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#656]
I tried using the Graphics example in the wiki, but it had MANY errors once I implanted it.

Here is the code:

using System;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace GraphicTest
{
    public class Kernel : Sys.Kernel
    {
        Canvas canvas;

        protected override void BeforeRun()
        {
            /* If all works correctly you should not really see this :-) */
            Console.WriteLine("Cosmos booted successfully. Let's go in Graphic Mode");

            canvas = FullScreenCanvas.GetFullScreenCanvas();

            canvas.Clear(Color.Blue);
        }

        protected override void Run()
        {
            try
            {
                /* A red Point */
                Pen pen = new Pen(Color.Red);
                canvas.DrawPoint(pen, 69, 69);

                /* A GreenYellow horizontal line */
                pen.Color = Color.GreenYellow;
                canvas.DrawLine(pen, 250, 100, 400, 100);

                /* An IndianRed vertical line */
                pen.Color = Color.IndianRed;
                canvas.DrawLine(pen, 350, 150, 350, 250);

                /* A MintCream diagonal line */
                pen.Color = Color.MintCream;
                canvas.DrawLine(pen, 250, 150, 400, 250);

                /* A PaleVioletRed rectangle */
                pen.Color = Color.PaleVioletRed;
                canvas.DrawRectangle(pen, 350, 350, 80, 60);

                Console.ReadKey();

                /* Let's try to change mode...*/
                canvas.Mode = new Mode(800, 600, ColorDepth.ColorDepth32);

                /* A LimeGreen rectangle */
                pen.Color = Color.LimeGreen;
                canvas.DrawRectangle(pen, 450, 450, 80, 60);

                Console.ReadKey();

                Stop();
            }
            catch (Exception e)
            {
                mDebugger.Send("Exception occurred: " + e.Message);
                mDebugger.Send(e.Message);
                Stop();
            }
        }
    }
}

**Comment by jp2masa** [comment]
I think that the packages weren't restored. What errors are you getting?

**Comment by VortexIncAdmin** [comment]
![capture 27](https://user-images.githubusercontent.com/15951904/27012465-eadfc342-4e84-11e7-8c1f-f573d54c1dbe.PNG)

**Comment by valentinbreiz** [comment]
You're using Visual Studio 2017 ?

**Comment by VortexIncAdmin** [comment]
No. 2015

**Comment by jp2masa** [comment]
You need to use the devkit.

**Comment by VortexIncAdmin** [comment]
Ohhh... K
