### ISSUE TITLE
Installing DevKit

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#657]
Where can I download the InnoSetup with the free Preprocessor Add-on?

**Comment by jp2masa** [comment]
http://www.jrsoftware.org/download.php/ispack.exe
If you need more help, please go to the gitter chat.

**Comment by VortexIncAdmin** [comment]
Should I install IS Studio and allow it to encrypt?

**Comment by jp2masa** [comment]
You don't need IS Studio.

**Comment by VortexIncAdmin** [comment]
K. But should I install encryption support as well?

**Comment by jp2masa** [comment]
I think that it's not needed.

**Comment by VortexIncAdmin** [comment]
K. Where can I download the DevKit?

**Comment by VortexIncAdmin** [comment]
And does anything happen when you install it when you have the User Kit?

**Comment by valentinbreiz** [comment]
To download the devkit you just have to download the code of the repository.

**Comment by jp2masa** [comment]
The devkit will overwrite the userkit. The devkit is the master branch, you just need to clone or download it and run install-VS2015.bat

**Comment by VortexIncAdmin** [comment]
K ;)

**Comment by VortexIncAdmin** [comment]
Compiling now... ;)

**Comment by VortexIncAdmin** [comment]
Finishing User Kit installation (which came up on the Dev Kit installation)

**Comment by VortexIncAdmin** [comment]
Done! ;D

**Comment by VortexIncAdmin** [comment]
Wait. IDK if it is done. Just ran VS2015 and started doing stuff.

**Comment by VortexIncAdmin** [comment]
Now it is finished
