### ISSUE TITLE
Mouse Error

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#658]
So I typed `public static Mouse m = new Mouse();` but there was an error. BTW here is my whole code. And it is all in Kernel.CS:

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace Zonnex_Graphical
{
    public class Kernel : Sys.Kernel
    {
        Canvas Canvas;

        public static Mouse m = new Mouse();

        protected override void BeforeRun()
        {
            // Clears console for boot
            Console.Clear();

            // Tells user that Zonnex is booting up
            Console.WriteLine("Zonnex is starting up...");

            // Makes VGAScreen fullscreen
            Canvas = FullScreenCanvas.GetFullScreenCanvas();

            // Clears canvas to be white
            Canvas.Clear(Color.White);
        }

        protected override void Run()
        {
            // Sets color to black
            Pen Pen = new Pen(Color.Black);

            // Creates taskbar
            Canvas.DrawFilledRectangle(Pen, 0, 0, 50, 1023);
        }
    }
}

PS: I am sorry if I am stressing you for asking so many questions. This is just my first time using COSMOS graphics.

**Comment by jp2masa** [comment]
You can't use Mouse from your Kernel, because it's in the HAL ring and the Kernel is in the User ring.

**Comment by VortexIncAdmin** [comment]
So how can I fix this?

**Comment by jp2masa** [comment]
If you want to use Mouse, you need a project in the System ring.

**Comment by VortexIncAdmin** [comment]
So how can I create a project in the system ring?

**Comment by jp2masa** [comment]
You just need to create a class library project, add a reference to Cosmos.Common and set the Ring using an attribute in AssemblyInfo.cs.

**Comment by VortexIncAdmin** [comment]
Do I need the class library in a certain location?

**Comment by jp2masa** [comment]
It needs to be referenced by the Cosmos project.

**Comment by VortexIncAdmin** [comment]
So is it supposed to be in my project folder?

**Comment by valentinbreiz** [comment]
https://image.noelshack.com/fichiers/2017/23/7/1497206568-capture.png

**Comment by jp2masa** [comment]
@VortexIncAdmin yes, in your solution.

**Comment by jp2masa** [comment]
I said a wrong thing, the project doesn't need to be referenced by the Cosmos project, it needs to be referenced by the Kernel project.

**Comment by VortexIncAdmin** [comment]
So is that still the project folder? Or a different one?

**Comment by jp2masa** [comment]
It can be anywhere, you just need to make sure you can add a reference to it.

**Comment by VortexIncAdmin** [comment]
Can I name it anything?

**Comment by jp2masa** [comment]
Yes.

**Comment by VortexIncAdmin** [comment]
So what code do I put in the Class Library? Can you show an example of what it would look like?

**Comment by jp2masa** [comment]
You need to create a class that has methods that you can call from the Kernel, like:
```cs
using Cosmos.HAL;

public class MouseDriver
{
    private Mouse mMouse;
    
    public int X { get { return mMouse.X; } }
    public int Y { get { return mMouse.Y; } }
    
    public MouseDriver(int width, int height)
    {
        mMouse = new Mouse(width, height);
    }
}
```

**Comment by VortexIncAdmin** [comment]
![capture 28](https://user-images.githubusercontent.com/15951904/27013843-7fbec240-4ea0-11e7-9868-9eb8cd913664.PNG)

Got some errors for some reason while pasting the code...

**Comment by VortexIncAdmin** [comment]
Wait.

**Comment by VortexIncAdmin** [comment]
![capture 28](https://user-images.githubusercontent.com/15951904/27013862-d4a08582-4ea0-11e7-8d0d-9b90f555b054.PNG)

I repasted the code. Now I have 3 errors instead of 5.

**Comment by jp2masa** [comment]
You need to add a reference to Cosmos.HAL.

**Comment by VortexIncAdmin** [comment]
And how do I do that?

**Comment by jp2masa** [comment]
You need to add a reference to Cosmos.Common and Cosmos.HAL. They are in "%appdata%/Cosmos User Kit/Kernel/"

**Comment by VortexIncAdmin** [comment]
Cosmos.HAL, or COSMOS.HAL.DLL?

**Comment by jp2masa** [comment]
Cosmos.HAL.dll is the Cosmos.HAL assembly. It's the same thing.

**Comment by VortexIncAdmin** [comment]
Should I open it in Visual Studio?

**Comment by jp2masa** [comment]
No, you just need to add it as a reference.

**Comment by VortexIncAdmin** [comment]
So how do I do that?

**Comment by jp2masa** [comment]
Right-click References -> Add Reference -> Browse...

**Comment by VortexIncAdmin** [comment]
Where is what I am trying to right click? Can you show a picture?

**Comment by jp2masa** [comment]
![screenshot](https://user-images.githubusercontent.com/10765201/27014020-a905d96c-4ee7-11e7-967c-35251fe6450e.png)

**Comment by VortexIncAdmin** [comment]
K. Reference is added. But for some reason, I still got 1 error.

**Comment by jp2masa** [comment]
What error?

**Comment by VortexIncAdmin** [comment]
![capture 30](https://user-images.githubusercontent.com/15951904/27014047-5d281d9e-4ea5-11e7-9c52-004305cf286e.PNG)

**Comment by jp2masa** [comment]
Replace this:
```cs
        public MouseDriver(int width, int height)
        {
            mMouse = new Mouse(width, height);
        }
```

by this:
```cs
        public MouseDriver(int width, int height)
        {
            mMouse = new Mouse();
            mMouse.Initialize(width, height);
        }
```

**Comment by VortexIncAdmin** [comment]
Now got 2 different errors.

![capture 31](https://user-images.githubusercontent.com/15951904/27014061-ca49e768-4ea5-11e7-95b2-74b114cb4243.PNG)

**Comment by VortexIncAdmin** [comment]
Just so you know, here is the code: 
using Cosmos.HAL;

public class MouseDriver
{
    private Mouse mMouse;

    public int X { get { return mMouse.X; } }
    public int Y { get { return mMouse.Y; } }

    public MouseDriver(int width, int height)
    {
        mMouse = new Mouse();
        mMouse.Initialize(width, height);
    }
}

**Comment by jp2masa** [comment]
Just change int to uint.

**Comment by VortexIncAdmin** [comment]
So what should I type to replace width and height?

**Comment by jp2masa** [comment]
Just change this:
```cs
public MouseDriver(int width, int height)
{
    mMouse = new Mouse();
    mMouse.Initialize(width, height);
}
```
to this:
```cs
public MouseDriver(uint width, uint height)
{
    mMouse = new Mouse();
    mMouse.Initialize(width, height);
}
```

**Comment by VortexIncAdmin** [comment]
No errors in the class library! :D Are there any other steps?

**Comment by VortexIncAdmin** [comment]
But my OS still has errors, are there any other steps?

**Comment by jp2masa** [comment]
Did you set the assembly Ring?

**Comment by VortexIncAdmin** [comment]
How do I do that?

**Comment by jp2masa** [comment]
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System/Properties/AssemblyInfo.cs#L40

**Comment by VortexIncAdmin** [comment]
So do I put [assembly: Ring(Ring.System)] in my AssemblyInfo and I'm done, or is there another step?

**Comment by jp2masa** [comment]
You need to have a reference to Cosmos.Common and add Cosmos.Common to the usings in AssemblyInfo.cs.
