### ISSUE TITLE
Problems with building

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#659]
Once I tested my OS at some point, the OS froze and was not controllable. I tried to turn it off through the button on the Bochs top bar, but that did not work. After a couple minutes, I tried force closing it using Alt-F4, and the Task Manager. But that did not help. I pressed the stop button on Visual Studio, and it finally worked, but the build failed from that. And now, every time I try to build/test my OS with Bochs, it gives an error. If I say continue, the boot will work, but when it reaches the "BeforeRun" section, it gives an error. Should I reinstall COSMOS? Should I reinstall Bochs? What should I do?

**Comment by Remco123** [comment]
Check if there is a file named **Filesystem.vmdk.lock** in the folder 
> C:\Users\username\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation
if that is the case try to remove that file and try again.

**Comment by VortexIncAdmin** [comment]
Uninstalled Bochs. Testing VS and reinstalling now...

**Comment by VortexIncAdmin** [comment]
Reinstalling Bochs helped all the other build formats, but still not it's own. I'll take Remco's next, then try reinstalling COSMOS.

**Comment by VortexIncAdmin** [comment]
Remco's advice worked! But I'm assuming reinstalling COSMOS will still do the trick, because it would have removed that file anyway during the process. Thanks! ;)
