### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by Prouser** [CosmosOS/Cosmos#66]
Hello, how can I make this: when user 1st start os he will he will set name nas password, it will save. If he will came back (reboot, shutdown and start) and type his name and pass word. You can see what i mean in Grunt OS videos on youtube

**Comment by jordansrowles** [comment]
I don't think you would be able to use a settings file, unless System.Reflection has been plugged? I would suggest either hard coding it, or writing it physically to disk if it hasn't

**Comment by Prouser** [comment]
Never mind. Just login. Can I use normal console login system ?

**Comment by Villacaleb** [comment]
Heres a sample of mine
 if (login == false)
            {
                Console.Write("Username:");
                var input = Console.ReadLine();
                if (input == username)
                {
                    Console.WriteLine("Password:");
                    input = Console.ReadLine();
                    if (input == password)
                    {
                        Console.WriteLine("Logining in.."); // After logining in, it will load everything,
                        login = true;
                        Console.WriteLine("Loading Command...");
                        Command.commands();

                    }
                }
            }
        }

You check out some more of my code at https://github.com/Villacaleb/VillaOS
