### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#660]
I was trying to build my OS when
`Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Error occurred while restoring NuGet packages: Failed to retrieve information about 'Cosmos.Debug.Kernel' from remote source 'C:\Users\Selinna\AppData\Roaming\Cosmos User Kit\Kernel\packages'.
1>------ Build started: Project: AOS, Configuration: Debug Any CPU ------
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(4,20,4,26): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(14,12,14,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(15,12,15,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(16,12,16,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(17,12,17,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(18,12,18,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(19,12,19,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(20,12,20,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(21,12,21,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(4,71,4,98): error CS0518: Predefined type 'System.String' is not defined or imported
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(4,100,4,120): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(4,123,4,125): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(14,55,14,60): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(15,61,15,68): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(16,59,16,80): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(17,59,17,68): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(18,68,18,75): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(19,55,19,60): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(20,53,20,58): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(21,55,21,64): error CS0518: Predefined type 'System.String' is not defined or imported
1>Kernel.cs(4,13,4,19): error CS0246: The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
1>Kernel.cs(1,7,1,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>Kernel.cs(2,7,2,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>Kernel.cs(3,7,3,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(2,7,2,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\secret\AppData\Local\Temp\.NETStandard,Version=v1.5.AssemblyAttributes.cs(3,7,3,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(11,7,11,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Debug\netstandard1.5\AOS.AssemblyInfo.cs(12,7,12,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>Kernel.cs(10,28,10,32): error CS0518: Predefined type 'System.Void' is not defined or imported
1>Kernel.cs(15,28,15,32): error CS0518: Predefined type 'System.Void' is not defined or imported
1>Kernel.cs(10,33,10,42): error CS0115: 'Kernel.BeforeRun()': no suitable method found to override
1>Kernel.cs(15,33,15,36): error CS0115: 'Kernel.Run()': no suitable method found to override
1>C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Assets file 'c:\users\secret\documents\visual studio 2017\Projects\AOS\AOS\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "AOS.csproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
`

**Comment by jp2masa** [comment]
Did you install as admin? Are you trying to build the project as admin?

**Comment by Project-Magenta** [comment]
yes

**Comment by jp2masa** [comment]
Are you still getting these errors?

**Comment by Project-Magenta** [comment]
yes

**Comment by jp2masa** [comment]
Try running `nuget sources Remove -Name "Cosmos Local Package Feed"` and then reinstall Cosmos.

**Comment by Project-Magenta** [comment]
ok

**Comment by Project-Magenta** [comment]
Same as #686.
