### ISSUE TITLE
Build Error (could not load IL2CPU)

### ISSUE THREAD

**Issue by Quang-vip** [CosmosOS/Cosmos#661]
When I build the sample of Cosmos, I encounter an error:

1>------ Build started: Project: SoftOS, Configuration: Debug Any CPU ------
1>  SoftOS -> C:\Users\Quang Anh's\Documents\Visual Studio 2015\Projects\SoftOS\SoftOS\bin\Debug\SoftOS.dll
2>------ Build started: Project: CosmosKernel1Boot, Configuration: Debug x86 ------
2>C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error MSB4062: The "Cosmos.Build.MSBuild.IL2CPU" task could not be loaded from the assembly C:\Users\Quang Anh%27s\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.Build.MSBuild.dll. Could not load file or assembly 'file:///C:\Users\Quang Anh%27s\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.Build.MSBuild.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
2>Done building project "CosmosKernel1Boot.Cosmos" -- FAILED.
2>
2>Build FAILED.
Build has been canceled.

It just like it is missing a file?

**Comment by fanoI** [comment]
Visual Studio 2015 is not supported by the last UserKit.

**Comment by Quang-vip** [comment]
So that's mean I have to use the DevKit?

**Comment by fanoI** [comment]
No it means you should install VS2017...

**Comment by Quang-vip** [comment]
It weighs 2gigs right?

**Comment by fanoI** [comment]
Yes it is a big beast...

**Comment by Quang-vip** [comment]
2gigs is normal, 6-9gigs is doom

**Comment by mihail-mojsoski** [comment]
10 (with updates 20 and getting close to 30) gigs is dota 2.
