### ISSUE TITLE
Build Error(Cosmos.targets)...Please help me!

### ISSUE THREAD

**Issue by MattSays** [CosmosOS/Cosmos#662]
When i build my cosmos project i get this error:

`1>------ Inizio compilazione: Progetto: SayOS, Configurazione: Debug Any CPU ------
1>SayOS -> C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\netstandard1.5\SayOS.dll
2>------ Inizio compilazione: Progetto: SayOSBoot, Configurazione: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: non è stato possibile risolvere il riferimento. Non è stato possibile trovare l'assembly "System.Core". Verificare che sia presente sul disco. Se il riferimento è richiesto dal codice, potrebbero essere generati errori di compilazione.
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\net462\SayOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\netstandard1.5\SayOS.dll" 
2>C:\Users\matti\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error: assembly specified in the dependencies manifest was not found -- package: 'dapper.strongname', version: '1.50.2', path: 'lib/netstandard1.3/Dapper.StrongName.dll'
2>C:\Users\matti\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : 
2>C:\Users\matti\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\matti\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\net462\SayOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\matti\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\netstandard1.5\SayOS.dll" 
2>	Working directory = 'C:\Users\matti\OneDrive\Documenti\Visual Studio 2017\Projects\SayOS\SayOS\bin\Debug\net462\'
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.2672974
2>Compilazione progetto "SayOSBoot.Cosmos" NON COMPLETATA.
2>
========== Compilazione: 1 completate o aggiornate, 1 non riuscite, 0 ignorate ==========
`

**Comment by fanoI** [comment]
First do you have installed in Visual Studio 2017 the "Net Core workload"?

Another thing are you using the UserKit or the DevKit (that for now should be really similar but something should be different in the installation procedure maybe?).

**Comment by MattSays** [comment]
I am using the UserKit

**Comment by fanoI** [comment]
Do you tried to execute the script userkit install.bat?
But I think this should have already been done by the userkit installer...

**Comment by MattSays** [comment]
How can i execute this script? (i have only the userkit installer)

**Comment by fanoI** [comment]
You are right you cannot!

We need to update the User Kit installation wiki I suppose you have not some needed component installed.

**Comment by jp2masa** [comment]
Dapper.StrongName.dll should exist in the IL2CPU folder.

**Comment by MattSays** [comment]
So now what i have to do?

**Comment by jp2masa** [comment]
See if Dapper.StrongName.dll exists in "%appdata%/Cosmos User Kit/Build/IL2CPU".

**Comment by MattSays** [comment]
Now i am trying to install the CosmosDevKit

**Comment by MattSays** [comment]
I've installed the cosmos user kit using the "install userkit.bat".Now it's working! Thanks a lot!
