### ISSUE TITLE
Cosmos templates not showing up in Visual Studio 2017

### ISSUE THREAD

**Issue by Quang-vip** [CosmosOS/Cosmos#664]
I can't see any templates in VS 2017, Why?

**Comment by jp2masa** [comment]
Did you install Cosmos after installing VS 2017?

**Comment by Quang-vip** [comment]
YES

**Comment by VortexIncAdmin** [comment]
Visual Studio 2017 is not compatible yet. You can use 2015 for the latest version.

**Comment by Quang-vip** [comment]
Uh hello? Read the install instruction page! :v

**Comment by VortexIncAdmin** [comment]
Oh. Nevermind. Just realized about the new update.

**Comment by jp2masa** [comment]
@Quang-vip Are you still having this problem?

**Comment by Quang-vip** [comment]
Nope

**Comment by Quang-vip** [comment]
BUT there IS another problem

**Comment by jp2masa** [comment]
What problem?

**Comment by Quang-vip** [comment]
About building

**Comment by jp2masa** [comment]
You're using the userkit? It's an IL2CPU error?

**Comment by Quang-vip** [comment]
Oh ******* yes, and it can't restore nuget packages

**Comment by jp2masa** [comment]
Can you upload a zip file with the "%appdata%/Cosmos User Kit/Kernel/packages/" folder?
