### ISSUE TITLE
Cosmos Graphic Subsystem not work!

### ISSUE THREAD

**Issue by MattSays** [CosmosOS/Cosmos#665]
I've builded the example CGS code but nothing happens! i haven't got no error
What i have to do?

**Comment by jp2masa** [comment]
Are you using VMWare or Bochs? VMWare isn't currently supported.

**Comment by MattSays** [comment]
i am using VMWare but if i install this os in a real pc the CGS works?

**Comment by jp2masa** [comment]
No.
