### ISSUE TITLE
A novice major problem

### ISSUE THREAD

**Issue by caonima2900445768** [CosmosOS/Cosmos#667]
My computer is Windows10 system. Today downloaded the Userkit2017602 (my development tool is Vs2017), after installing the kit I restart the computer, open the VS, ready to build a new project, but the operation error, did not open the virtual machine, I Do not know the virtual machine is not to be installed, and the following error

**Comment by caonima2900445768** [comment]
1.Error occurred while invoking IL2CPU.	os1Boot	C:\Users\user\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	36	
2.Error: assembly specified in the dependencies manifest was not found -- package: 'dapper.strongname', version: '1.50.2', path: 'lib/netstandard1.3/Dapper.StrongName.dll'	os1Boot	C:\Users\user\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	36

**Comment by caonima2900445768** [comment]
After I installed userkit, I just opened VS2017 and built a new project. I didn't do anything

**Comment by fanoI** [comment]
Well but the Virtual Machine needs to be installed before!
You can choose to use:
* VmWare
* Bochs

**Comment by jp2masa** [comment]
I think that the userkit has a critical problem in the publish of the tools. I'll push the fix later today, but the user kit is already released, so I think that it will need to be discussed.
