### ISSUE TITLE
Implement Guid.NewGuid

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#669]
The current implementation of Guid.NewGuid returns an empty Guid, but we should return a version 4 Guid.
Where to implement: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System.Plugs/System/GuidImpl.cs#L10
How to implement: https://www.cryptosys.net/pki/uuid-rfc4122.html

**Comment by zarlo** [comment]
i will have a crack at it

**Comment by j4cobgarby** [comment]
How does the `Guid` constructor work? What are the eleven different numbers? I thought GUIDs were, according to [this website](https://www.cryptosys.net/pki/uuid-rfc4122.html), 
> [GUIDs are] blocks of 8, 4, 4, 4 and 12 hex digits

**Comment by j4cobgarby** [comment]
It's quite easy to [generate a GUID in C# though](https://msdn.microsoft.com/en-us/library/system.guid.newguid(v=vs.110).aspx)

**Comment by jp2masa** [comment]
It uses native code.

**Comment by j4cobgarby** [comment]
Oh, I'll have a look at making my own implementation then

**Comment by jp2masa** [comment]
There's already a PR for this.

**Comment by j4cobgarby** [comment]
Okay nevermind then

**Comment by Arawn-Davies** [comment]
Will be fixed by #670, got an issue about System.Random not being plugged.

**Comment by ascpixi** [comment]
can this issue be closed, as #942 implemented this?

**Comment by quajak** [comment]
Weird, it looks like all the code added by #942 never made it into master. The code seems to have landed on the branch https://github.com/CosmosOS/Cosmos/tree/tests/guid and was never merged into master. We should try merge the code into master at some point.

**Comment by zarlo** [comment]
its still has an issue in the test where both the new guids are the same

**Comment by MishaTY** [comment]
Fixed by #2244
