### ISSUE TITLE
Saving All in Visual Studio fails

### ISSUE THREAD

**Issue by gjsman** [CosmosOS/Cosmos#677]
The ability to save my project in Visual Studio doesn't work. When I click "Save All" in the menubar, and then click "Save", I get this error:

`The operation could not be completed. No such interface supported`

The templates included with Visual Studio still work.

**Comment by xAzzzu** [comment]
Got the same Problem atm im saving the code somewhere else and create a new Project with the same Name and paste it in when I want to work on it but it's really annoying :D

**Comment by gjsieben** [comment]
This is just this Visual Studio project. The other projects do work, only Cosmos is affected. I tried a Visual Studio repair, didn't fix it. I tried re-registering certain DLLs, didn't work. I think it is Cosmos.

**Comment by jp2masa** [comment]
Do you have more details about the error?

**Comment by gjsieben** [comment]
None. The entire message is:

`The operation could not be completed. No such interface supported`

There isn't even a period at the end of the sentence. There are probably logs somewhere, but I have no idea where they are.

**Comment by gjsieben** [comment]
I will look for those logs though. Hopefully they will shed some light.

**Comment by jp2masa** [comment]
"%appdata%\Microsoft\VisualStudio\YOUR_VS_INSTANCE\ActivityLog.xml"

**Comment by gjsieben** [comment]
That file actually doesn't exist. Like, I found the folder exactly, but the "ActivityLog.xml" file wasn't in it.

**Comment by dsdude123** [comment]
Possibly related to #758?

**Comment by jp2masa** [comment]
This should be working in latest master.
