### ISSUE TITLE
GPL Compliance

### ISSUE THREAD

**Issue by electrodeyt** [CosmosOS/Cosmos#678]
Well, here we go:

Cygwin: V2
https://github.com/CosmosOS/Cosmos/blob/d54e9fb088fdcb4c8e4bbbb664cfd6775a2b47d5/Users/Orvid/IL2CPU%20Tester/CsTests/bench.cs
Bochs: LGPL

May have missed some but yeah, good chance your violating it.
EDIT: Found a few more, see my PR.

**Comment by fanoI** [comment]
You mean that "bench.cs" has been copied from Bochs source? Or that "fibonacci" is LGPL :-) ?

**Comment by electrodeyt** [comment]
Look in the build/tools.

**Comment by Arawn-Davies** [comment]
Tbf, this is a users code, not exactly part of the main thing. Is there more that's non user?

**Comment by Arawn-Davies** [comment]
Never mind found it
