### ISSUE TITLE
Dot Net Referenced 1.0

### ISSUE THREAD

**Issue by NotHexon** [CosmosOS/Cosmos#681]
'C:\Users\NotHexon\Desktop\HxOS\HxOS\HxOS\HxOS.csproj' targets '.NETStandard,Version=v1.5'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.	HxOSBoot	C:\Program Files(x86)\Microsoft\VisualStudio\2017\Community\MSBuild\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.Common.targets
PLZ HELP

**Comment by jp2masa** [comment]
Did you create a new project?
