### ISSUE TITLE
Error "$(NetStandardImplicitPackageVersion) is not a vaild string" in VB.NET

### ISSUE THREAD

**Issue by xADYT** [CosmosOS/Cosmos#682]
I have been getting this error since I first installed COSMOS for Visual Studio 2017.

When I click Manage NuGet Packages, I get this error.

![screenshot4](https://user-images.githubusercontent.com/29396324/27525512-1288be06-5a71-11e7-856f-8fd95c47c041.png)

I tried to use the Package Manager Console, and I get this error.

![screenshot3](https://user-images.githubusercontent.com/29396324/27525532-3628cf0e-5a71-11e7-95bc-9abf7cd5db65.png)

System Info
OS Name: Microsoft Windows 10 Pro (Licensed)
OS Version: 1607
OS Build: 14393.1358
Ram: 2 GB
System Type: 32-Bit OS, x64-based Processor
Processor: Pentium(R) Dual-Core CPU E5300 @ 2.60 GHz 2.59 GHz

**Comment by jp2masa** [comment]
What version of .NET Core are using?

**Comment by xADYT** [comment]
Using .NET Core v1.0.4

**Comment by jp2masa** [comment]
That's the version you get when you run `dotnet --version`?

**Comment by xADYT** [comment]
Yes

**Comment by jp2masa** [comment]
You need the .NET Core 2.0 tooling preview to use VB (and F# I think).

**Comment by xADYT** [comment]
It doesn't work

**Comment by jp2masa** [comment]
You still get the same error?

**Comment by xADYT** [comment]
Yes

**Comment by jp2masa** [comment]
VB and F# are not supported at the moment, but I tested VB in a VS Preview instance and it was working.

**Comment by xADYT** [comment]
Ok

**Comment by xADYT** [comment]
Now I switched to C#
