### ISSUE TITLE
How to use User code?

### ISSUE THREAD

**Issue by Remco123** [CosmosOS/Cosmos#683]
Hello,
I was going trough some folders in Cosmos when I saw the Users folder, there is some interersting stuff in there. But unfortunately it doesn't come default with Cosmos, How can I use those projects? Particularly the Orvid.Graphics one.

Remco

**Comment by fanoI** [comment]
For the major part is old code (probably not working anymore in "modern" Cosmos) I think you can simply copy that code in your kernel.

**Comment by Remco123** [comment]
thanks, i will try when i get home.

**Comment by jp2masa** [comment]
There are some user folders with different licenses I think.

**Comment by Remco123** [comment]
when i try to run it now it gives the following error:
Error: Exception: System.Exception: Assembly 'Orvid.Graphics.Cosmos' is in ring User(3). It references assembly 'Cosmos.Core' which is in ring Core(0), but this is not allowed!
7>	   at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner, Assembly entryAssembly) in C:\Users\OS Development\Downloads\Cosmos-master\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 105
7>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\OS Development\Downloads\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 199

How would I fix this, I am not realy familiar with plugs.

**Comment by jp2masa** [comment]
It's old code, probably rings didn't exist at that time. You can create projects in different rings to have access to other rings. You'll need at least two projects: one in the System ring and the other in the HAL ring.

**Comment by Remco123** [comment]
so you need to go up one ring at a time right?

**Comment by jp2masa** [comment]
Yes.

**Comment by Remco123** [comment]
thanks, i will try tomorrow.

**Comment by Remco123** [comment]
After some hours i finally got it booting but then I get this error: 
![image](https://user-images.githubusercontent.com/29398596/27607908-c7724b7e-5b85-11e7-9227-be8df5259ea0.png)
I think the issue is in the old VGA driver that is used.

**Comment by jp2masa** [comment]
Probably the problem is the VGA driver. Can you check the label for that address in the map file?

**Comment by Remco123** [comment]
there are 2 items there. 
SystemVoidOrvidGraphicsImageSetPixelSystemUInt32SystemUInt32OrvidGraphicsPixel.END__OF__METHOD_EXCEPTION.MethodFooterStackCorruptionCheck_Break_on_location
and
SystemVoidOrvidGraphicsImageSetPixelSystemUInt32SystemUInt32OrvidGraphicsPixel.END__OF__METHOD_EXCEPTION.0A
So it looks like the problem is in the SetPixel method.

**Comment by fanoI** [comment]
Instead to use old code that "break" the rings it will be better to make the old VGA driver working and then use CGS with that...

**Comment by jp2masa** [comment]
@Remco123 Do you have stack corruption detection enabled for method footers or for every instruction? Make sure you run it for every instruction.

**Comment by Remco123** [comment]
To be honest, I have no idea what that is.
I am now editing the VGADriver.

**Comment by Remco123** [comment]
Now I get a plug error from System.GC,Collect(), is there not any other way to remove memory?

**Comment by fanoI** [comment]
System.GC.Collect() should be never called! Why you want to free memory manually?

**Comment by Remco123** [comment]
That function was already in the Image Class, but now that that is commented it still gives me errors. I think that I will just create it my self.
Thanks for the help.
