### ISSUE TITLE
Text in GUI

### ISSUE THREAD

**Issue by SapphireGitHub** [CosmosOS/Cosmos#684]
How can I use text in my GUI using CGS? Here is my code so far:

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.System.Graphics;

namespace Space_X
{
    public class Kernel : Sys.Kernel
    {
        Canvas GUI;

        public void Alpha()
        {
            // Clears console
            Console.Clear();

            // Prints lines for Alpha!
            Console.WriteLine("Alpha! OS Selector");
            Console.WriteLine();
            Console.WriteLine("Please select an option by pressing one of these keys:");
            Console.WriteLine();
            Console.WriteLine("1: Space X1");
            Console.WriteLine("2: Shutdown");
            Console.WriteLine("3: Restart");

            // Makes Alpha! start Space X1 when 1 is pressed
            while(true)
            {
                if (Console.ReadKey().Key != ConsoleKey.D1)
                {
                    // Tells that Space X1 GUI is starting
                    Console.WriteLine("Starting Space X1 GUI...");

                    // Starts Space X1 GUI
                    GUIRuntime();
                    StartupScreen();
                } else
                if (Console.ReadKey().Key != ConsoleKey.D2)
                {
                    // Tells that the computer is safe to turn off
                    Console.WriteLine("It is now safe to turn off your computer.");

                    // Shuts down Space X1
                    Stop();
                } else
                if (Console.ReadKey().Key != ConsoleKey.D3)
                {
                    // Tells that Space X1 is restarting
                    Console.WriteLine("Space X1 is restarting...");

                    // Restarts Space X1
                    Sys.Power.Reboot();
                }
            }
        }

        public void GUIRuntime()
        {
            // Starts GUI driver
            GUI = FullScreenCanvas.GetFullScreenCanvas();
        }

        public void StartupScreen()
        {
            GUI.Clear(Color.White);
        }

        protected override void BeforeRun()
        {
            // Tells that Space X1 has started
            Console.WriteLine("Space X1 has started! Running Alpha!...");
        }

        protected override void Run()
        {
            // Starts Alpha!
            Alpha();
        }
    }
}

**Comment by fanoI** [comment]
My idea is that in the "Cosmos.System.Graphic" name space a class to DrawText should exist, my initial idea was to make it part of Canvas itself (Canvas.DrawString()) but it seems more complex that one can imagine to do this.

While Text Mode has a concept of fonts when you are in Graphic Mode you have literally to draw any character on Screen.

This summarize how this could be done in Cosmos:

1. First you need a way to Draw an Image on a Canvas
2. You need to have TrueType fonts support
3. Given a string of Text you have to render in memory any character as a bitmap image
4. Finally you Draw the Text on screen

**Comment by Project-Magenta** [comment]
How would cosmos do hex characters?

**Comment by fanoI** [comment]
What do you mean by "hex characters"? Maybe you wanted write "text characters"?

**Comment by Project-Magenta** [comment]
Never mind.

**Comment by Project-Magenta** [comment]
I might be able to do the image part.

**Comment by prepare** [comment]
Hello all, @fanoI 

Render Text from Font file (.ttf, .otf) to Bitmap =>

the Typography library (https://github.com/LayoutFarm/Typography) 
could do this job easily.

**Comment by Backup-eric645** [comment]
There's no `Console.WriteLine` in GUI mode. What you can do: Get VGA Fonts while you're still in text mode. Enable unsafe code.
```c#
// YOU NEED TO BE IN TEXT MODE TO USE THIS FUNCTION.
// And you need a pointer to a 4KB buffer.
private unsafe void VGAFont(void* destaddr)
{
    short* dac = (short*)destaddr;
    var port3ce = new IOPort(0x3ce);
    port3ce.Word = 5;
    IOPort.Wait();
    port3ce.Word = 0x406;
    IOPort.Wait();
    var port3c4 = new IOPort(0x3c4);
    port3c4.Word = 0x402;
    IOPort.Wait();
    port3c4.Word = 0x604;
    IOPort.Wait();
    for (var i = 0; i < 256; i++)
    {
        *dac = *(short*)(0xA0000 + (dac - (short*)destaddr));
        dac += 16;
    }
    port3c4.Word = 0x302;
    IOPort.Wait();
    port3c4.Word = 0x204;
    IOPort.Wait();
    port3ce.Word = 0x1005;
    IOPort.Wait();
    port3ce.Word = 0xE06;
    IOPort.Wait();
}
```

**Comment by terminal-cs** [comment]
> Hello all, @fanoI
> 
> Render Text from Font file (.ttf, .otf) to Bitmap =>
> 
> the Typography library (https://github.com/LayoutFarm/Typography)
> could do this job easily.

how do i use it? im kind of a noob at c# :/

**Comment by terminal-cs** [comment]
> > Hello all, @fanoI
> > Render Text from Font file (.ttf, .otf) to Bitmap =>
> > the Typography library (https://github.com/LayoutFarm/Typography)
> > could do this job easily.
> 
> how do i use it? im kind of a noob at c# :/

and then how would i draw it

**Comment by ADev531** [comment]
just you can use this
using Cosmos.System.Graphics.Fonts;
GUI.DrawString("its a text", PCScreenFont.Default, pen, X, Y);
