### ISSUE TITLE
Pain - the problem that has been holding me back 

### ISSUE THREAD

**Issue by caonima2900445768** [CosmosOS/Cosmos#685]
###  i would describe this error and I found the wrong specific process:

Error content: Error occurred while invoking IL2CPU. CosmosKernel1Boot C: \\ Roaming \ Cosmos User Kit \ Build \ VSIP \ Cosmos.targets 36
First of all:
My development tool is Visual Studio 2017. (I specifically for Cosmos download, did not open after the download)
 
Then I installed a full suite of VMware Workstation Pro (including: VMware Workstation 12 Player, VMware Workstation Pro)

Finally, I installed Cosmos userkit2017620(the installation process has a cmd, there is a line of red font, flash, do not know is not wrong)

Then I opened my newly installed Visual Studio and created a new Cosmos C # project.

After the new project, I did not do anything, did not make any changes to the code directly click on the "debug" button

Then there was this error, the virtual machine did not open.

I am very concerned about this error, spent a long time typing in order to be enough to say clearly, I hope you developers do not let me down, thank Cosmos development group

**Comment by jp2masa** [comment]
There should be a more specific error in the Output window.

**Comment by charlesbetros** [comment]
Is that the actual path in the error or you removed user details from it before posting here?
