### ISSUE TITLE
New project issue

### ISSUE THREAD

**Issue by dpeter99** [CosmosOS/Cosmos#686]
I get this error after creating a new c# project:
```The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)```

**Comment by jp2masa** [comment]
Are you using the user kit or the dev kit?

**Comment by Jonrobin** [comment]
Me too. Please fix it.

**Comment by jp2masa** [comment]
Are you using the user kit or the dev kit? What does `dotnet --version` show?

**Comment by Jonrobin** [comment]
dotnet --version show 1.0.4. I used userkit.

**Comment by jp2masa** [comment]
The problem is that the nuget package restore is failing for some reason. Try running `dotnet restore` in the project folder.

**Comment by BaRRaKudaRain** [comment]
Try to clear or rebild solution.

**Comment by DjAlEx234** [comment]
@BaRRaKudaRain , that's not the fix, ive tried it. just wait for the fix. it will be soon

**Comment by Alumniminium** [comment]
Same issue here, since about two months.

**Comment by ratchet2324** [comment]
Just to add to this, when I started up the UserKit my new projects started fine, but as soon as I started the DevKit now all of them (including one I started under UserKit) now have the following errors:
```
Error	Unable to resolve 'Cosmos.Debug.Kernel (>= 1.0.0)' for '.NETStandard,Version=v1.5'.				
Error	The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
Error	'Kernel.BeforeRun()': no suitable method found to override
Error	'Kernel.Run()': no suitable method found to override
Error	Unable to resolve 'Cosmos.System (>= 1.0.0)' for '.NETStandard,Version=v1.5'.	
```

**Comment by jp2masa** [comment]
You need to install the Dev Kit packages (which are prerelease).

**Comment by ratchet2324** [comment]
@jp2masa I did as far as I'm aware, I cloned the repo and ran ./install-vs2017.bat and it went through and did all the nuget etc. and at the end opened up VS with the kernal solution. Followed all the instructions in the wiki and still ended up this way, even with a fresh install.

**Comment by fanoI** [comment]
If you want only to develop your OS you don't need to install the DevKit but only the UserKit.

The DevKit is "code in progress" and it is possible that doesn't compile or has other problems: you need only it if you want to contribute to the low level parts of Cosmos.

**Comment by Alumniminium** [comment]
Same issue on userkit.

**Comment by ratchet2324** [comment]
@fanoI I need the dev kit to use CGS apparently according to the wiki.

**Comment by jp2masa** [comment]
You need to install the packages in your project (in Manage NuGet Packages). CGS is in the latest User Kit already.

**Comment by dpeter99** [comment]
OK so I just got back from a trip (no internet) 😄 
I tried to run the `dotnet restore` but got this result:
`C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Failed to retrieve information about 'Cosmos.Debug.Kernel' from remote source 'P:\_Programs\Cosmos User Kit\Kernel\packages'. [P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\CosmosKernel3.csproj]`
I recently uninstalled the cosmos from the Win Programs and Features menu.
Then when I saw that the net core version was out I installed it again.

**Comment by jp2masa** [comment]
Try running `nuget sources Remove -Name "Cosmos Local Package Feed"` and then install Cosmos again.

**Comment by dpeter99** [comment]
Where should I run `nuget sources Remove -Name "Cosmos Local Package Feed"` ?

**Comment by jp2masa** [comment]
where you have nuget, for example Build/Tools

**Comment by dpeter99** [comment]
ok got it working
but now I get an error after a few runs
`Error occurred while invoking IL2CPU.	CosmosKernel3Boot	C:\Users\Peter\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets`

**Comment by jp2masa** [comment]
What's the IL2CPU error?

**Comment by dpeter99** [comment]
oh right i forgot:
`Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.UInt32  Interop+mincore.SetErrorMode(System.UInt32).`

**Comment by jp2masa** [comment]
What method is calling that native method?

**Comment by dpeter99** [comment]
This is my code:
`using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace CosmosKernel3
{
    public class Kernel: Sys.Kernel
    {
        protected override void BeforeRun()
        {
            var fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }
        
        protected override void Run()
        {
            /*var a = System.IO.Directory.EnumerateDirectories("");
            foreach (var item in a)
            {
                Console.WriteLine(item);
            }
            */

            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}`

**Comment by jp2masa** [comment]
`System.IO.Directory.EnumerateDirectories("")` needs a plug I think. Also, you should be able to see what method is causing the error in the output log.

**Comment by dpeter99** [comment]
```Called from :
2>	System.IO.Win32FileSystemEnumerableIterator`1[System.String]::Void .ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1[System.String])
2>	System.IO.Win32FileSystemEnumerableFactory::System.Collections.Generic.IEnumerable`1[System.String] CreateFileNameIterator(System.String, System.String, System.String, Boolean, Boolean, System.IO.SearchOption)
2>	System.IO.Win32FileSystem::System.Collections.Generic.IEnumerable`1[System.String] EnumeratePaths(System.String, System.String, System.IO.SearchOption, System.IO.SearchTarget)
2>	System.IO.Win32FileSystem
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197```

**Comment by dpeter99** [comment]
But that part is commented out .... 🤔

**Comment by dpeter99** [comment]
So this is my project:
[CosmosKernel3.zip](https://github.com/CosmosOS/Cosmos/files/1149229/CosmosKernel3.zip)

**Comment by jp2masa** [comment]
Try rebuilding the solution.

**Comment by dpeter99** [comment]
`2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.UInt32  Interop+mincore.SetErrorMode(System.UInt32).
2>	 Called from :
2>	System.IO.Win32FileSystemEnumerableIterator`1[System.String]::Void .ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1[System.String])
2>	System.IO.Win32FileSystemEnumerableFactory::System.Collections.Generic.IEnumerable`1[System.String] CreateFileNameIterator(System.String, System.String, System.String, Boolean, Boolean, System.IO.SearchOption)
2>	System.IO.Win32FileSystem::System.Collections.Generic.IEnumerable`1[System.String] EnumeratePaths(System.String, System.String, System.IO.SearchOption, System.IO.SearchTarget)
2>	System.IO.Win32FileSystem
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	P:\csharp\Cosmos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:03.1590136
2>Done building project "CosmosKernel3Boot.Cosmos" -- FAILED.`

**Comment by jp2masa** [comment]
Are you still having this problem?
