### ISSUE TITLE
IL2CPU invoked error

### ISSUE THREAD

**Issue by Mcilie** [CosmosOS/Cosmos#693]
So im trying to make an OS with graphics. I want to be able to run it in Virtual box (because for some reason Vm ware player isnt working with cosmos graphics).  I run my project in debug mode, every thing is fine, but I cant use this for Vbox because the os will be stuck on "_waiting for debugger connection_". When I run it in release mode, i get an error. the error reads; Error occurred while invoking IL2CPU. The file from which this error is derived is Cosmos.targets (line 36), which is a file from cosmos itself, not my project. that line of from the file is `<Cosmos.Build.MSBuild.IL2CPU DebugMode="$(DebugMode)" DebugEnabled="$(DebugEnabled)" StackCorruptionDetectionEnabled="$(StackCorruptionDetectionEnabled)" StackCorruptionDetectionLevel="$(StackCorruptionDetectionLevel)" TraceAssemblies="$(TraceAssemblies)" IgnoreDebugStubAttribute="$(IgnoreDebugStubAttribute)" DebugCom="1" UseNAsm="true" References="@(ReferencePath)" OutputFilename="$(TargetDir)$(MSBuildProjectName).asm" EnableLogging="true" EmitDebugSymbols="$(DebugSymbols)" CosmosBuildDir="$(CosmosDir)\Build" WorkingDir="$(TargetDir)"/>`.   I've even tried running the default code that cosmos offers when starting a new project in c#. Whenever I try to run a project in release, it gives me this error.
Thanks and please help

**Comment by jp2masa** [comment]
You need to disable debugging in the Cosmos project properties.

**Comment by DjAlEx234** [comment]
how do you do that?

**Comment by Mcilie** [comment]
@jp2masa, By that do you mean going to the solution property pages then configuration then switching debug to release (from the drop down menu's)? Because if so, I have done that and it still doesnt work.

**Comment by jp2masa** [comment]
Don't switch to Release, the solution configuration should be Debug. You need to disable debug in the Cosmos project properties.

**Comment by Mcilie** [comment]
how 
![image](https://user-images.githubusercontent.com/25804313/28095475-9621f7b8-6670-11e7-9176-e3f22ee0657e.png)

**Comment by jp2masa** [comment]
Right-click on the Cosmos project -> Properties. Then there's a debug tab where you can disable debugging.

**Comment by Mcilie** [comment]
Thank you very much
