### ISSUE TITLE
Error occured while invoking IL2CPU... Impossible to find the assembly "System.Core"... [HELP]

### ISSUE THREAD

**Issue by gael12334** [CosmosOS/Cosmos#695]
![2017-07-13](https://user-images.githubusercontent.com/19997870/28170242-c98335c0-67b2-11e7-95b8-000f1ff2e800.png)

Sorry my computer is set in french...

I currently have the latest version of Cosmos (userkit-20170620);
I run Visual Studio 2017;
I remaked the whole project (VS2015) to put it on VS2017...
(i made new project with the same namespace and i only copied the .cs file)

The problem is I try to make a build but the compiler keep making the same error...

**Comment by jp2masa** [comment]
There's a more detailed description of the error in the output window.

**Comment by gael12334** [comment]
![2017-07-13](https://user-images.githubusercontent.com/19997870/28170701-288f2fb4-67b4-11e7-81ab-65641283e464.png)
heres the output

**Comment by gael12334** [comment]
![2017-07-13 1](https://user-images.githubusercontent.com/19997870/28170733-3f93bd06-67b4-11e7-831e-736d5d123de5.png)
output

**Comment by jp2masa** [comment]
It seems that the compiler can't find the assembly generated by a referenced project. It never compiled with the latest user kit?

**Comment by gael12334** [comment]
well, i downloaded VS2017 yesturday, so basically no.... it never complied with the laest userkit...

**Comment by jp2masa** [comment]
This is probably a bug in the compiler, I'll check it.

**Comment by gael12334** [comment]
[LeafKernel.zip](https://github.com/CosmosOS/Cosmos/files/1146168/LeafKernel.zip)

Here's my OS / visual studio Project, so you see the problem when building it

**Comment by jp2masa** [comment]
This issue occurs when a method from a referenced project is used. I don't know why it's happening, because all the project references are compiled to assemblies that are copied to the project output path, so it should be loaded, but it throws an exception instead, because the assembly is not being found.

**Comment by geomtech** [comment]
J'ai parfois la même erreur. Cela arrive si tu utilises des fonctions qui ne sont pas supporté par Cosmos et que le compilateur ne peut exécuté, par exemple j'ai tenté d'encoder là console en utf-8 pour avoir les accents de la langue française...   J'avais l'avertissement aussi et cela ne m'a pas  empêcher de continuer... (Je suis passé à devkit) Je te conseille d'utiliser le devkit qui est selon moi beaucoup mieux car tu auras les dernières résolutions de bugs.

Sometimes I have the same error. It's happens when you use fonctions that cosmos doesn't support yet and the compiler can't execute. For example,  tried to encode the console in utf8 (for French accent), that is not supported by cosmos so I have this error. And for the advert, I have it too but we can continue to work, I think I don't have it on devkit.

_Sent from my HUAWEI GRA-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gael12334** [comment]
Merci du conseil geomtech

thank you for the advice geomtech

**Comment by gael12334** [comment]
how do i install the inno setup preprocessor thing?

**Comment by jp2masa** [comment]
http://www.jrsoftware.org/download.php/ispack.exe

**Comment by gael12334** [comment]
thanks

**Comment by gael12334** [comment]
hum geomtech... the devkit is.... it is not helping alot.... i only see errors in visual studio

**Comment by zarlo** [comment]
was the project made with VS2015

**Comment by gael12334** [comment]
Yes, but I remade it to make it work in VS2017

**Comment by gael12334** [comment]
Well... i can't use the devkit... (im only 16...) because i cant even build the project...
And I re-tried to build my system  on userkit-20170620... and still not working...

**Comment by zarlo** [comment]
do you have:
Visual Studio 2017 Workloads: .NET Core Tools and Visual Studio Extension Development
.NET Framework 4.6.2
InnoSetup with the free Preprocessor Add-on
VMWare Player and/or Bochs

**Comment by gael12334** [comment]
yes, zarlo
i do have all these

**Comment by gael12334** [comment]
when the latest devkit has finished to be installed, a project open itself....
![2017-07-13 4](https://user-images.githubusercontent.com/19997870/28194754-68d83d58-6814-11e7-9249-c7c29139b0f2.png)

**Comment by gael12334** [comment]
i know, but im not a professional programmer... So what am i supposed to do with the cosmos project... all i want is being able to build my OS...

**Comment by fanoI** [comment]
Nothing you can close it :-)
You have to create a new C# project and between the possible templates you will get "Cosmos" and inside "C# Operating System" and you are ready to go...

**Comment by geomtech** [comment]
@gael12334 Si tu as des erreurs après l'installation de devkit, c'est normal, j'avais le même problème, il faut supprimer les références de Cosmos dans ton csproj et recharger les packages NuGet, sinon tu changes juste les versions de Cosmos au lieu de supprimer les références comme ça:

`  <ItemGroup>
    <PackageReference Include="Cosmos.Debug.Kernel" Version="1.0.*" />
    <PackageReference Include="Cosmos.System" Version="1.0.*" />
  </ItemGroup>`

En:

  <ItemGroup>
    <PackageReference Include="Cosmos.Debug.Kernel" Version="1.0.2-*" />
    <PackageReference Include="Cosmos.System" Version="1.0.2-*" />
  </ItemGroup>

**Comment by geomtech** [comment]
`  <ItemGroup>
    <PackageReference Include="Cosmos.Debug.Kernel" Version="1.0.2-*" />
    <PackageReference Include="Cosmos.System" Version="1.0.2-*" />
  </ItemGroup>`

**Comment by gael12334** [comment]
Merci goemtech

**Comment by gael12334** [comment]
Still with the devkit, not able to build my OS...
![2017-07-14](https://user-images.githubusercontent.com/19997870/28211915-02998b7e-686d-11e7-8b3e-5988d02e6c63.png)

**Comment by jp2masa** [comment]
It's a bug, I'm working on fixing it now.

**Comment by jp2masa** [comment]
It should be working now.

**Comment by geomtech** [comment]
@jp2masa we have to update the devkit ?

**Comment by jp2masa** [comment]
Yes.

**Comment by gael12334** [comment]
The installation has some error...
![2017-07-14 1](https://user-images.githubusercontent.com/19997870/28215263-57d0f61e-687b-11e7-8ca5-b76720d05fe5.png)

**Comment by jp2masa** [comment]
What's the error?

**Comment by gael12334** [comment]
well ... it can't build cosmos...

**Comment by jp2masa** [comment]
I'll fix it.

**Comment by gael12334** [comment]
@jp2masa  I have edited the comment

**Comment by jp2masa** [comment]
It should be working now.

**Comment by gael12334** [comment]
@jp2masa @geomtech 
![2017-07-14 3](https://user-images.githubusercontent.com/19997870/28217369-e70e4442-6882-11e7-8381-32ac678bf358.png)

namespace "Cosmos" not found...

**Comment by jp2masa** [comment]
You need to restore nuget packages.

**Comment by gael12334** [comment]
@jp2masa oh ok thanks

**Comment by geomtech** [comment]
Regarde les références de ton projet si après la restauration des packages nuGet ça ne marche tjrs pas.

**Comment by gael12334** [comment]
![2017-07-14 4](https://user-images.githubusercontent.com/19997870/28218356-49889f48-6886-11e7-83ae-b56a0e0accca.png)
how do i make "hardware" be in HAL?

**Comment by jp2masa** [comment]
It should be in System, or you can't use it from the kernel project. You need to add AssemblyInfo.cs with the Ring attribute (which can be found in Cosmos.Common).

**Comment by gael12334** [comment]
@jp2masa I put [assembly: Ring(Ring.System)], but the compiler seem to dont give a f*** about the assemblyinfo.cs...

**Comment by jp2masa** [comment]
Are you getting the same error?

**Comment by gael12334** [comment]
@jp2masa 
![2017-07-14 5](https://user-images.githubusercontent.com/19997870/28218734-70e28b48-6887-11e7-975e-de49a239f8ec.png)

well... now the problem is about the rings...

**Comment by jp2masa** [comment]
Where did you add AssemblyInfo?

**Comment by gael12334** [comment]
@jp2masa i selected it in the solution explorer

**Comment by gael12334** [comment]
![2017-07-14 7](https://user-images.githubusercontent.com/19997870/28218995-646b4a0c-6888-11e7-81aa-c150412cadb4.png)
heres the assemblyinfo.cs

**Comment by jp2masa** [comment]
Try building the solution.

**Comment by gael12334** [comment]
@jp2masa  it failed

**Comment by gael12334** [comment]
@jp2masa  i think it is the compiler that has a bug

**Comment by DjAlEx234** [comment]
open your project then, the cosmos project only opens so you can edit it/ look at it

**Comment by mterwoord** [comment]
You have your references incorrect. You know how Rings work?

**Comment by gael12334** [comment]
@mterwoord yes, but i cant change them..­.

**Comment by Project-Magenta** [comment]
hI?
