### ISSUE TITLE
error using float.Parse() [Error ocurred while invoking IL2CPU]

### ISSUE THREAD

**Issue by JorgeAJ** [CosmosOS/Cosmos#696]
When using float.parse () or the environment class I get the error: Error ocurred while invoking IL2CPU

**Comment by jp2masa** [comment]
It hasn't been implemented yet.

**Comment by JorgeAJ** [comment]
Should already be a fundamental function

**Comment by jp2masa** [comment]
It doesn't stop us from working on memory, drivers and those basic things, so it's not really a priority. You can work on it if you need it.

**Comment by JorgeAJ** [comment]
ok

**Comment by djlw78** [comment]
Seriously What is causing all of this? I someone can in depth explain it to me ill start adding plugs.

**Comment by quajak** [comment]
Can I work on this, or is somebody already doing it?

**Comment by jp2masa** [comment]
I think no one is working on this.

**Comment by quajak** [comment]
Ok, good I will try

**Comment by jp2masa** [comment]
Resolved by #835.
