### ISSUE TITLE
VMware closing itself caused by System.IO.Directory.CreateDirectory(...);

### ISSUE THREAD

**Issue by gael12334** [CosmosOS/Cosmos#698]
![2017-07-14 8](https://user-images.githubusercontent.com/19997870/28233110-89097d9a-68c2-11e7-9f8a-7935e94ec24f.png)
After the System.Core bug, i remade my OS completly... (with the same .cs file) 
Now, the compiler works, but i noticed that my VMware closed itself when it was running a method i made (Dir.CreateDirectory) based on System.IO.... help?

**Comment by jp2masa** [comment]
Probably a FAT bug. If you run it on Bochs, you'll be able to see what exception is being thrown.

**Comment by gael12334** [comment]
@jp2masa ok... i will install bochs.... i will reply with the exception

**Comment by valentinbreiz** [comment]
@gael12334 try to download the jp2masa's Bugfixes branch. That fixes some bugs with FAT.
