### ISSUE TITLE
add intelisense to x# vs

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#699]

**Comment by mihail-mojsoski** [comment]
Why is this needed?
This is like adding it to ASM.

**Comment by AnotherAltr** [comment]
Indeed, why it needed? 
X# **intuitive** and **easy**~

Although do not exclude, for beginner's it would be _useful_~

**Comment by fanoI** [comment]
Well Intellisense will give auto-completion and other goodies so why not?
I don't know how much this is easy to do... probably we will revisit this when we will make X# a proper language (that is when it is compiled directly to binary code, not a "transpiler" as is now).

**Comment by jp2masa** [comment]
This issue was moved to CosmosOS/XSharp#5
