### ISSUE TITLE
Real hw

### ISSUE THREAD

**Issue by Prouser** [CosmosOS/Cosmos#70]
1) how can i install (or just boot from cd/flash disk) cosmos os on pc
2) if ill run it, will hw buttons work, start button

**Comment by ARMmaster17** [comment]
You can't inherently "install" your operating system like you do with Windows or Linux. Instead you will run it as a [Live CD](http://en.wikipedia.org/wiki/Live_CD). Open up your project in Visual Studio and take a look at the two projects listed in Solution Explorer. Right-click on the project that is called ***your_os_name*Boot** and click **Properties**. From the window that pops up, click the **ISO image** option. Then click Save. Now click the **Start** button from the toolbar and wait for it to finish building. Once that finishes, a window will pop up with a bunch of files. You will find a file in that window called ***your_os*.iso**. Use an [image-burning application](http://www.imgburn.com/) to burn that to a CD. 

And as for HW buttons. PS/2 keyboards and mice should work. As for USB it can vary. You just have to try it for yourself and see if it works.

That's it. Hope this helps! :smile:

**Comment by ARMmaster17** [comment]
It's also worth noting that as far as I know, you **CAN NOT** use a program such as unetbootin to deploy the .iso file to USB devices. I have not yet tried PXE (currently fighting a TFTP error), but that should work if you run out of options.

**Comment by ARMmaster17** [comment]
Update: Fixed my PXE server. PXE boot does indeed work. I simply added the option to download the .iso file to RAM, then chainload it. If you would like more information on how to set PXE booting up, my skype username is "j z" without the quotes.

**Comment by mterwoord** [comment]
We have an option to boot to pxe from VS i think? Would you be interested in getting that improved? 
We don't use the iso then, but use pxelinux..

**Comment by ARMmaster17** [comment]
The PXE program crashes when you try to launch it from VS (Error said something about not enough arguments, I'll try to make it crash and upload a dump later today. Same also happens with the USB tool).

**Comment by ARMmaster17** [comment]
I personally use Serva since it uses ProxyDHCP, that way I don't have to reconfigure my existing DHCP network to use it, or go offline on a private network.

**Comment by czhower** [comment]
Why not work to fix what we have? That is far easier and will benefit far more users. Its probably a simple fix.

**Comment by ARMmaster17** [comment]
That would have to be opened as a separate issue. The original post was a question that has been, for the most part, answered.

**Comment by czhower** [comment]
Our DHCP does not required you to reconfig your network but the recommended use is to use a dedicated NIC for it (secondary). Using a single NIC has a lot of complications unless you use a VLAN and many BIOSes dont' support that on the guest side anyway..... DHCP is necessary because the info for the PXE boot / bootp is contained IN the DHCP info....

**Comment by ARMmaster17** [comment]
I understand how the tool works. It's just that I live in a house where I don't have admin access to the router, nor the ability to run a custom DHCP server 24/7 (to much power usage).

**Comment by czhower** [comment]
You dont need to change anything on the router. The DHCP server runs on your PC and uses a different subnet than your network. Its all self contained and its part of the Cosmos code. I wrote the DHCP and PXE directly into Cosmos debugger in C#.

**Comment by czhower** [comment]
It might be that the old PXE still wants to use the old 3P external EXE... if so then what someone needs to do is share the code with the PXE Kudzu version, but disable the controller code which is used to turn on and off the PC using the custom board.

**Comment by mterwoord** [comment]
Chad, DHCP/PXE are network wide, so if the same network card is on a
network with an existing DHCP server, you get interesting situations..


2015-05-09 20:12 GMT+02:00 Chad Z. Hower aka Kudzu <notifications@github.com

**Comment by czhower** [comment]
Yes, but this is why the best thing to do is use a separate NIC and a crossover cable. Doing it over an existing network is asking for trouble. As I said before, there are ways with VLANs or priority, but most BIOSes dont support VLAN for PXE booting... .. the priority has side effects as well. Even if it is a laptop, a USB Ethernet adaptor is about $15....
