### ISSUE TITLE
Error while testing project

### ISSUE THREAD

**Issue by Matrixicated** [CosmosOS/Cosmos#706]
So I installed cosmos yesterday, so I could do some OS development as it looked really promising. I enjoy the tools and all but I'm having this issue with it. I created a new project in Visual Studio 2017 with the type set to C# Operating System and target as .NET Framework 4.6.2 . The problem here is the following:- 

`Warning		Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HEX-DOSBoot	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1964
`

Apparently, it says that I'm missing System.Core. What I've also noticed is that my project does not have an AssemblyInfo.cs by default as all tutorials clearly have in their project tree. Could someone please help me with this issue? Plus, I have all prerequisites installed such as VMWare Player, .NET Framework 4.6.2 and 4.7(in case.), .NET Core Tools and the Cosmos User Kit as stated.

So, I decided to re-install Cosmos and upon re-installing, a new issue pops up saying that it cannot re-create the file titled: "Id" in %AppData% when it has already been created. So, then, I ignore that and keep it installing and now in VS 2017, it says: 

`The "Cosmos.Build.MSBuild.Ld" task failed unexpectedly.
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Cosmos.Build.MSBuild.BaseToolTask.ExecuteTool(String workingDir, String filename, String arguments, String name, Action`1 errorReceived, Action`1 outputReceived)
   at Cosmos.Build.MSBuild.BaseToolTask.ExecuteTool(String workingDir, String filename, String arguments, String name)
   at Cosmos.Build.MSBuild.Ld.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HEX-DOSBoot	C:\Users\Iswar Chetri\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	40
` 

**Thanks in advance!**

**Comment by jp2masa** [comment]
System.Core isn't needed for anything, that's just a warning (if System.Core was found, you would get compiler errors).
AssemblyInfo is automatically generated by the c# compiler now, but you can add that file if you need to add some assembly attributes (if you want to set the ones generated by the c# compiler, you need to disable the automatic generation in the project).
The last error occurs because "%appdata%\Cosmos User Kit\Build\Tools\cygwin\ld.exe" isn't being found.

**Comment by Matrixicated** [comment]
So, in that case, how do I boot the OS. VMWare Player does not launch and how do I fix that second error?

**Comment by jp2masa** [comment]
Try reinstalling.

**Comment by Matrixicated** [comment]
I already did, that is why the second issue popped out of nowhere.

**Comment by zarlo** [comment]
set the target as .netstandard 1.5

**Comment by Matrixicated** [comment]
Okay, I've fixed the cygwin-related error. But the warning persists constantly! The warning doesn't allow me to build the OS. Plus, how do I test my OS in the first place? Is it supposed to automatically launch in VMware?, since it doesn't work for me.

Thanks in advance,
Matrixicated

**Comment by jp2masa** [comment]
It's supposed to launch in VMWare. Make sure you have it installed and check if there's any error in the output log.

**Comment by Matrixicated** [comment]
Thank you for your help everyone. I have no idea why it didn't work on my 64-bit PC with Windows 10. I just a fresh install on my Windows 7 PC instead and it has no issue whatsoever and successfully launched in VMWare Player. I'm closing this issue now, thank you once again.
