### ISSUE TITLE
Error: Exception: System.Exception: User assembly 'Cosmos.Core_Asm' uses Assembly plugs, which are not allowed! [Compiler]

### ISSUE THREAD

**Issue by gael12334** [CosmosOS/Cosmos#707]
![2017-07-17](https://user-images.githubusercontent.com/19997870/28276662-9cf166ae-6ae5-11e7-93c9-36230c2fd4ae.png)
 
well the last time i reworked all my system and the compiler worked... 
Now with the latest version, the compiler throws "Error occured while invoking IL2CPU" with
"Error: Exception: System.Exception: User assembly 'Cosmos.Core_Asm' uses Assembly plugs, which are not allowed!"

**Comment by fanoI** [comment]
Hmm IL2CPU seems in confusion: 'Cosmos.Core_Asm' is as the name says in Core ring not User ring...

Do you have update the DevKit recently?

**Comment by fanoI** [comment]
The DevKit is rapidily changin in this period and a lot of ref to Cosmos assmblies have changed... can you try to create a new Kernel starting from the template and recopy all your files in it?
