### ISSUE TITLE
Error occurred while invoking IL2CPU

### ISSUE THREAD

**Issue by ThomasBeHappy** [CosmosOS/Cosmos#708]
i have been stuck on this for ever trying to do this but i get the error everytime i run it.
this is my code

`using Sys = Cosmos.System;
using Cosmos.System.Graphics;
using Cosmos.HAL;

namespace test2
{
    public class Kernel : Sys.Kernel
    {
        VGAScreen screen;
        Mouse mouse;

        protected override void BeforeRun()
        {
            screen = new VGAScreen();
            mouse = new Mouse();
            screen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
            screen.Clear(1);
            mouse.Initialize(320, 200);
        }

        protected override void Run()
        {
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y, 40);
            screen.SetPixel320x200x8((uint)mouse.X + 1, (uint)mouse.Y, 40);
            screen.SetPixel320x200x8((uint)mouse.X + 2, (uint)mouse.Y, 40);
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y + 1, 40);
            screen.SetPixel320x200x8((uint)mouse.X, (uint)mouse.Y + 2, 40);
            screen.SetPixel320x200x8((uint)mouse.X + 1, (uint)mouse.Y + 1, 40);
            screen.SetPixel320x200x8((uint)mouse.X + 2, (uint)mouse.Y + 2, 40);
            screen.SetPixel320x200x8((uint)mouse.X + 3, (uint)mouse.Y + 3, 40);
        }
    }
}`
it gives the error everytime i use SetPixel320x200x8

**Comment by jp2masa** [comment]
Are you using the user kit or the dev kit?
VGA is no longer supported.
Also, you can see the error in the output log.

**Comment by ThomasBeHappy** [comment]
i am using the user kit and whats the difference if i may ask?

**Comment by jp2masa** [comment]
What user kit version?

**Comment by ThomasBeHappy** [comment]
CosmosUserKit-20170620-vs2017

**Comment by jp2masa** [comment]
I think that the VGA driver doesn't work, you should use CGS (it only supports Bochs at the moment).

**Comment by ThomasBeHappy** [comment]
ehm do you know where i can get a guide or tutorial for it cuz i am very new to cosmos

**Comment by ThomasBeHappy** [comment]
also i am wondering whats the difference between the dev kit and user kit?

**Comment by jp2masa** [comment]
The dev kit is the latest master. The user kit is a release.
CGS: http://www.gocosmos.org/docs/cosmos-graphic-subsystem/

**Comment by ThomasBeHappy** [comment]
and let me gues the dev kit does support VGA?

**Comment by jp2masa** [comment]
VGA is no longer supported, maybe we support it again in the future, but there are more important things to do first.

**Comment by ThomasBeHappy** [comment]
ok thx for the help

**Comment by ThomasBeHappy** [comment]
:/ the example on the website also give the same error ;-;

**Comment by jp2masa** [comment]
See the output log. Probably the problem is that the Mouse class is in the HAL ring, so you can't use it directly.

**Comment by ThomasBeHappy** [comment]
i am gonna try and make a fresh project and use the example on the wesite

**Comment by ThomasBeHappy** [comment]
ahhh ok got it working now

**Comment by ThomasBeHappy** [comment]
nvm it chrashes when it loads the canvas
:/

**Comment by fanoI** [comment]
Are you using Bochs?

**Comment by ThomasBeHappy** [comment]
yes

**Comment by ThomasBeHappy** [comment]
i litterterly copied the example code and when i ran it it did stopped at the canvas part

**Comment by fanoI** [comment]
What virtual machine are you using VmWare or Bochs?

**Comment by ThomasBeHappy** [comment]
vmware

**Comment by ThomasBeHappy** [comment]
well i think i know what i need to do then :/

**Comment by fanoI** [comment]
CGS works only with Bochs, Virtual and maybe QEMU so...

**Comment by VortexIncAdmin** [comment]
"maybe we support it again in the future" I agree. ;)

**Comment by fanoI** [comment]
If someone could look to the VGA driver, it worked in the past so what has been broken?

**Comment by ThomasBeHappy** [comment]
it would be lovely if VGA works again cuz almost all the tutorials are using VGA so they dont work right now.

**Comment by VortexIncAdmin** [comment]
Yeah, but just to let you know, I'm trying to create a tutorial series on the wiki to use CGS the way most projects go with VGA. It has not been updated in a while, but it will be soon...

**Comment by VortexIncAdmin** [comment]
Yeah...
