### ISSUE TITLE
COSMOS C# Template does not work

### ISSUE THREAD

**Issue by VortexIncAdmin** [CosmosOS/Cosmos#711]
I used the template in VS2017, and there were 3 errors. Here is the code, however I don't think you need it cause it is unmodified.

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace Shine_OS
{
    public class Kernel: Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }
        
        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}

**Comment by VortexIncAdmin** [comment]
![capture 34](https://user-images.githubusercontent.com/15951904/28378840-7c8c879a-6c66-11e7-9ee1-dc24d36a82e6.PNG)

**Comment by jp2masa** [comment]
If you're using the dev kit, you need to update the packages, change version 1.0.* to 1.0.2-*.

**Comment by VortexIncAdmin** [comment]
Where can I do that?

**Comment by jp2masa** [comment]
In the csproj file. NuGet doesn't have a way of specifying floating versions including prerelease, so dev kit users need to update packages manually (https://github.com/NuGet/Home/issues/912).

**Comment by VortexIncAdmin** [comment]
Works! Thanks!
