### ISSUE TITLE
Missing AssemblyInfo.cs

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#712]
So... I'm trying to make an OS which uses some methods from the Cosmos.Common and Cosmos.Core libraries. Thing is, I read that I need to change the ring I'm working in by adding a line in AssemblyInfo.cs. However, I can't find it anywhere in my project's folder. It only contains the usual obj and bin folders but no Properties folder where the AssemblyInfo.cs would usually be.

Thanks in advance!

**Comment by jp2masa** [comment]
You need to create it.

**Comment by 0xF6** [comment]
You can create it~
And to add attributes to build near the entry point, sort of.
