### ISSUE TITLE
Mouse?

### ISSUE THREAD

**Issue by ThomasBeHappy** [CosmosOS/Cosmos#714]
How do i make the mouse with the canvas? because i only see guides using VGA :/

**Comment by VortexIncAdmin** [comment]
I've never done that, but I tried. If I am right, I think the mouse feature for COSMOS was removed. But you can add it back using Rings. It is somewhere in the COSMOS code, and you can add it back using Rings. I tried this before, but I ended up giving up because it took too long. If you need help, then jp2masa will need to help you. jp2masa should come to help soon... ;)

**Comment by VortexIncAdmin** [comment]
However, when I get to my VS2017 computer, I'll try to draw a cursor for you in CGS.

**Comment by ThomasBeHappy** [comment]
ok thx!

**Comment by ThomasBeHappy** [comment]
also why is the speaker not working too?

**Comment by jp2masa** [comment]
Some driver code is old so it may not work. There are other priorities like memory management. #700 has a MouseManager class which will avoid the need to have a separate project.

**Comment by ThomasBeHappy** [comment]
and how do i use it? sorry if i sound stupid.

**Comment by jp2masa** [comment]
Use what?

**Comment by VortexIncAdmin** [comment]
I think he means the MouseManager class.

**Comment by ThomasBeHappy** [comment]
yes

**Comment by jp2masa** [comment]
You can clone the branch and install.

**Comment by ThomasBeHappy** [comment]
ok

**Comment by ThomasBeHappy** [comment]
===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup

=====
Error
=====

.NET Core not detected.
Visual Studio Extension tools not detected.
Cannot find Inno Setup.

**Comment by ThomasBeHappy** [comment]
:/

**Comment by jp2masa** [comment]
You need the .NET Core and VS Extension tools workloads in VS 2017 and [Inno Setup](http://www.jrsoftware.org/download.php/ispack.exe)

**Comment by SapphireGitHub** [comment]
Oh, and sorry if I did not draw it. You were not active, so I decided to not do it. If you want me to do it, I can. ;) Just ask.
