### ISSUE TITLE
.net core and visual studio extension tools not detected

### ISSUE THREAD

**Issue by PixelPlugins** [CosmosOS/Cosmos#719]
I got this when running install-VS2017.bat:

===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

=====
Error
=====

.NET Core not detected.
Visual Studio Extension tools not detected.

**Comment by jp2masa** [comment]
Do you have those workloads installed in VS 2017?

**Comment by PixelPlugins** [comment]
I have visual studio 2017 and .net framework 4.5.2, 4.5, and 4.6.2

**Comment by jp2masa** [comment]
Check if you have the .NET Core and VS Extension tools workloads installed.

**Comment by 0xF6** [comment]
The problem appears if have installed more than one instance of Visual Studio.
If there is more than two, need to install Extension tools on all instances.

.NET Core dev tools also need to install~

**Comment by jp2masa** [comment]
We use vswhere to detect the VS installation path. I think that it gets the most recent installation.

**Comment by 0xF6** [comment]
> most recent installation
No.

**Comment by hwoadministrator** [comment]
Hey, can I ask some question, please? I have tried with description errors is here but with VS Installer, Netcore also not working with 0 byte. Can you have me please?

**Comment by jp2masa** [comment]
Make sure you have the .NET Core cross-platform development and Visual Studio Extension tools workloads installed. Also, you need the .NET Core 2.0 SDK and the .NET Framework 4.7.1 developer pack.

**Comment by EmpeRoar** [comment]
Same issue with my project.
I am using VS2017 Community.
