### ISSUE TITLE
Installer failure

### ISSUE THREAD

**Issue by teokitan** [CosmosOS/Cosmos#720]
I'm currently trying to install the Cosmos OS devkit for VS 2017 using git clone. Unfortunately, I'm getting some errors about which I'm pretty sure that are connected to actual code compiling errors. Firstly, I didn't have the .NET 4.6.2, but even after I installed it, Cosmos didn't install. Also, I did git pull after the installation of .NET, if that can even help to finding the problem. Anyway, here's the log (I am having trouble pasting it here): https://pastebin.com/aL9S65aX

**Comment by jp2masa** [comment]
The master branch isn't stable at the moment. You can use an older commit or the latest User Kit.

**Comment by dedady157** [comment]
im having trouble installing cosmos too i have c#.net 2.0-4.6.2 (dont ask i do a load of stuff) but the installer 'userkit install' inside the master branch comes up with '.NET Core not detected. Connot find Inno Setup.'
what am i missing here?

**Comment by teokitan** [comment]
Thanks.
