### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by dedady157** [CosmosOS/Cosmos#721]
im having trouble installing cosmos too i have c#.net 2.0-4.6.2 (dont ask i do a load of stuff) but the installer 'userkit install' inside the master branch comes up with '.NET Core not detected. Connot find Inno Setup.'
what am i missing here?

p.s
i tryed using 'install-VS2017' same error,
i tryed to reinstall .net core... no change,
i tryed to reinstall .net 4.6.2... no change,

my .net core version is 1.0.4 provided by 'dotnet --version',

**Comment by jp2masa** [comment]
You need to install the .NET Core workload in VS 2017 and Inno Setup Quick Start Pack.

**Comment by dedady157** [comment]
===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

================
Init Directories
================

Creating VSIP as C:\Users\BAILEY\Downloads\Cosmos-master\Cosmos-master\Build\VSIP
Cleaning up existing User Kit directory.

=====
Error
=====

Das Verzeichnis ist nicht leer.

   bei System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bei System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bei System.IO.Directory.Delete(String path, Boolean recursive)
   bei Cosmos.Build.Builder.CosmosTask.CleanDirectory(String aName, String aPath) in C:\Users\BAILEY\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:Zeile 54.
   bei Cosmos.Build.Builder.CosmosTask.DoRun() in C:\Users\BAILEY\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:Zeile 66.
   bei Cosmos.Build.Installer.Task.Run() in C:\Users\BAILEY\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:Zeile 16.


no this is the new error

**Comment by jp2masa** [comment]
The installation directory is probably being used, make sure you don't have it opened in explorer and run install-VS2017.bat again.

**Comment by dedady157** [comment]
it works now thank you
