### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by dedady157** [CosmosOS/Cosmos#723]
iv tryed to create a project but none of the tut's seem to work becouse i cant find the template in vs2017 Community.

iv tryed reinstalling with both the exe and both bats files

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit? Make sure Visual Studio is not running when you install Cosmos. Anyway, you can find the vsix files in "%appdata%/Cosmos User Kit/VSIX/" and install them from there.

**Comment by dedady157** [comment]
i currantly using the exe user installer

**Comment by dedady157** [comment]
29.07.2017 20:42:33 - Microsoft VSIX Installer
29.07.2017 20:42:33 - -------------------------------------------
29.07.2017 20:42:33 - vsixinstaller.exe version:
29.07.2017 20:42:33 - 15.0.26430.16 built by: D15SVC
29.07.2017 20:42:33 - -------------------------------------------
29.07.2017 20:42:33 - Command line parameters:
29.07.2017 20:42:33 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\BAILEY\AppData\Roaming\Cosmos User Kit\VSIX\Cosmos.VS.ProjectSystem.vsix
29.07.2017 20:42:33 - -------------------------------------------
29.07.2017 20:42:33 - Microsoft VSIX Installer
29.07.2017 20:42:33 - -------------------------------------------
29.07.2017 20:42:33 - Initializing Install...
29.07.2017 20:42:33 - Extensiondetails...
29.07.2017 20:42:33 - 	Identifier         : Cosmos.VS.ProjectSystem
29.07.2017 20:42:33 - 	Name               : Cosmos Visual Studio Project System
29.07.2017 20:42:33 - 	Author             : Cosmos
29.07.2017 20:42:33 - 	Version            : 1.0
29.07.2017 20:42:33 - 	Description        : The Visual Studio project system for the Cosmos Operating System.
29.07.2017 20:42:33 - 	Locale             : en-US
29.07.2017 20:42:33 - 	MoreInfoURL        : 
29.07.2017 20:42:33 - 	InstalledByMSI     : False
29.07.2017 20:42:33 - 	SupportedFrameworkVersionRange : [4.5,)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 	SignatureState     : Unsigned
29.07.2017 20:42:33 - 	Unterstützte Produkte : 
29.07.2017 20:42:33 - 		Microsoft.VisualStudio.Community
29.07.2017 20:42:33 - 			Version : [15.0]
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 	Verweise           : 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
29.07.2017 20:42:33 - 		Name         : Visual Studio MPF 15.0
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 		MoreInfoURL  : 
29.07.2017 20:42:33 - 		Nested       : No
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 	Voraussetzungen    : 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
29.07.2017 20:42:33 - 		Name         : Visual Studio core editor
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.NetCore.ComponentGroup.Web
29.07.2017 20:42:33 - 		Name         : .NET Core 1.0 - 1.1 development tools
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.Component.NetFX.Core.Runtime
29.07.2017 20:42:33 - 		Name         : .NET Core runtime
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
29.07.2017 20:42:33 - 		Name         : .NET desktop development tools
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.VisualStudio.Component.VSSDK
29.07.2017 20:42:33 - 		Name         : Visual Studio SDK
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - 		-------------------------------------------------------
29.07.2017 20:42:33 - 		Identifier   : Microsoft.VisualStudio.Component.NuGet
29.07.2017 20:42:33 - 		Name         : NuGet package manager
29.07.2017 20:42:33 - 		Version      : [15.0,16.0)
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - Signaturdetails...
29.07.2017 20:42:33 - 	Extension is not signed.
29.07.2017 20:42:33 - 
29.07.2017 20:42:33 - Er wird nach passenden Produkten gesucht...
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Microsoft Visual Studio Professional 2013
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Microsoft Visual Studio 2013 Shell (Integrated)
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Microsoft Visual Studio Community 2015
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Microsoft Visual Studio 2015 Shell (Integrated)
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Globaler Pfad
29.07.2017 20:42:33 - Installiertes Produkt gefunden - Visual Studio Enterprise 2017 RC (vs2017)
29.07.2017 20:42:34 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\master.pkgdef

29.07.2017 20:42:34 - PKGDEF Information: Creating PkgDefCacheNonVolatile
29.07.2017 20:42:34 - PKGDEF Information: Double-checking master pkgdef file
29.07.2017 20:42:34 - PKGDEF Information: PkgDefManagement initialized
29.07.2017 20:42:34 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

29.07.2017 20:42:34 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

29.07.2017 20:42:34 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.admin.pkgdef

29.07.2017 20:42:34 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Users\BAILEY\AppData\Local\Microsoft\VisualStudio\15.0_959a59cb\Extensions

29.07.2017 20:42:34 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions

29.07.2017 20:42:34 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
29.07.2017 20:42:34 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:34 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:34 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
29.07.2017 20:42:34 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:34 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:34 - PKGDEF Information: PkgDef cache is current.
29.07.2017 20:42:34 - PKGDEF Information: PkgDefManagement startup complete
29.07.2017 20:42:35 - Die Extension mit der ID Cosmos.VS.ProjectSystem wird nicht für Visual Studio Enterprise 2017 RC (vs2017) installiert.
29.07.2017 20:42:35 - Installiertes Produkt gefunden - Visual Studio Community 2017 (Vs2017)
29.07.2017 20:42:35 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\master.pkgdef

29.07.2017 20:42:35 - PKGDEF Information: Creating PkgDefCacheNonVolatile
29.07.2017 20:42:35 - PKGDEF Information: Double-checking master pkgdef file
29.07.2017 20:42:35 - PKGDEF Information: PkgDefManagement initialized
29.07.2017 20:42:35 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\

29.07.2017 20:42:35 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\

29.07.2017 20:42:35 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.admin.pkgdef

29.07.2017 20:42:35 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions;C:\Users\BAILEY\AppData\Local\Microsoft\VisualStudio\15.0_b8c7344e\Extensions

29.07.2017 20:42:35 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions

29.07.2017 20:42:35 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
29.07.2017 20:42:35 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:35 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:35 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
29.07.2017 20:42:35 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:35 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
29.07.2017 20:42:35 - PKGDEF Information: PkgDef cache is current.
29.07.2017 20:42:35 - PKGDEF Information: PkgDefManagement startup complete
29.07.2017 20:42:35 - Die Extension mit der ID Cosmos.VS.ProjectSystem wird nicht für Visual Studio Community 2017 (Vs2017) installiert.
29.07.2017 20:42:36 - System.InvalidOperationException: No products are registered for instance '959a59cb'
   bei Microsoft.VisualStudio.Setup.Cache.CommonExtensions.GetProduct(IInstance instance, Boolean installedOnly)
   bei Microsoft.VisualStudio.Setup.Cache.CacheRepository.GetAvailablePackages(Boolean allPackages)
   bei Microsoft.VisualStudio.Setup.Cache.CacheManager.GetPackages(Boolean allPackages)
   bei Microsoft.VisualStudio.Setup.Engine.Initialize()
   bei Microsoft.VisualStudio.Setup.Engine.GetProducts()
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   bei VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by dedady157** [comment]
that after running Cosmos.VS.ProjectSystem.vsix in that folder

**Comment by jp2masa** [comment]
The visual studio installation seems to be corrupt, try repairing it.

**Comment by dedady157** [comment]
ok

**Comment by dedady157** [comment]
this will take a bit tho

**Comment by dedady157** [comment]
it failed

im going to reinstall vs 2017

**Comment by dedady157** [comment]
ok i found the problem vs2017 couldn't be fully installed on windows 7 so iv moved to vs2015 but i cant seem to get the extension to install on it

**Comment by jp2masa** [comment]
Only VS 2017 is supported.

**Comment by dedady157** [comment]
darn

**Comment by dedady157** [comment]
what happend to the old 2013 version?

**Comment by VortexIncAdmin** [comment]
It is in an older version of COSMOS.
