### ISSUE TITLE
Cosmos.targets error invoking IL2CPU

### ISSUE THREAD

**Issue by OmeletHopper** [CosmosOS/Cosmos#725]
Hello, I am completely new to both C# and Cosmos. I'm used to things like Linux, but I wanted to test this out. I installed VS2017 on Windows 10 as well as the latest user package and VMWare player. I started a new project with the C# Cosmos OS Kernel, but when I compile the default template I get this:

1>------ Build started: Project: CosmosKernel3, Configuration: Release Any CPU ------
1>CosmosKernel3 -> c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll
2>------ Build started: Project: CosmosKernel3Boot, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll" 
2>C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll" 
2>	Working directory = 'c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
2>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel3KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 518
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 964
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:02.3680170
2>Done building project "CosmosKernel3Boot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========

Sorry if it's just me being stupid or if I post the wrong output.

**Comment by fanoI** [comment]
Welcome to Cosmos!

The real error is this:

> Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel3KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!

What is your code?

**Comment by OmeletHopper** [comment]
I am using the default program so:

1>------ Build started: Project: CosmosKernel3, Configuration: Release Any CPU ------
1>CosmosKernel3 -> c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll
2>------ Build started: Project: CosmosKernel3Boot, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll" 
2>C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll" 
2>	Working directory = 'c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
2>	Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel3KernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 518
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 964
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel3\CosmosKernel3\bin\Release\netstandard1.5\CosmosKernel3.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:02.3680170
2>Done building project "CosmosKernel3Boot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========

Or did I accidentally edit something else?

**Comment by jp2masa** [comment]
You need to use the Debug configuration, Release doesn't work. If you want to disable debugging, you need to edit the Boot project properties.

**Comment by OmeletHopper** [comment]
I started a new Cosmos c# project, and it let me compile with the debug settings, but only once. After the first compile it throws up the same error.

**Comment by jp2masa** [comment]
Are you sure it's the same error?

**Comment by OmeletHopper** [comment]
Looks like it:

1>------ Build started: Project: CosmosKernel5, Configuration: Debug Any CPU ------
1>CosmosKernel5 -> c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\netstandard1.5\CosmosKernel5.dll
2>------ Build started: Project: CosmosKernel5Boot, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\CosmosKernel5Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\netstandard1.5\CosmosKernel5.dll" 
2>C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\CosmosKernel5Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jack\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\netstandard1.5\CosmosKernel5.dll" 
2>	Working directory = 'c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.IO.IOException: The process cannot access the file 'c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\CosmosKernel5Boot.cdb' because it is being used by another process.
2>	   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
2>	   at System.IO.File.Delete(String path)
2>	   at Cosmos.Debug.Symbols.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.Debug.Symbols\DebugInfo.cs:line 74
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 166
2>	Loaded assemblies: 
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\CosmosKernel5.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.2751671
2>Done building project "CosmosKernel5Boot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========

I have it set to Debug, Any CPU. Do I need to change CPU target?

**Comment by jp2masa** [comment]
>2> Error: Exception: System.IO.IOException: The process cannot access the file 'c:\users\jack\documents\visual studio 2017\Projects\CosmosKernel5\CosmosKernel5\bin\Debug\net462\CosmosKernel5Boot.cdb' because it is being used by another process.

**Comment by OmeletHopper** [comment]
Yeah, I saw that so that's why I rebooted, VS is starting...

**Comment by OmeletHopper** [comment]
I think I fixed it.. Just going to test...

**Comment by OmeletHopper** [comment]
I changed the output format to ISO and now it lets me compile, I'm thinking my VMware was locking onto the output file or something

**Comment by OmeletHopper** [comment]
Got it! VMWare wasn't letting go of the output, so when I changed to ISO output it works! Thanks!
Cosmos is a really cool project! Thank you to all the developers too!
