### ISSUE TITLE
Filesystem issues

### ISSUE THREAD

**Issue by Remco123** [CosmosOS/Cosmos#729]
Hello,
For my OS it is necessary to load resources from a other harddrive, but when I try to do that the kernel receives an exception or the files get corrupt. This is the error that I get when the kernel stops:
![image](https://user-images.githubusercontent.com/29398596/29019397-8a652c62-7b5e-11e7-9c5e-95c30aa68c9f.png)

Sometimes it works though but than I get an error that the file is not found even though it exists on the drive. And if I am lucky and that works the file gets corrupted when it is read.
This is my code:
```
        Canvas c;
        protected override void BeforeRun()
        {
            Sys.FileSystem.CosmosVFS fs = new Sys.FileSystem.CosmosVFS();
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            
            foreach(var i in fs.GetDirectoryListing("0:\\"))
            {
                try { Console.WriteLine(i.mName); } catch(Exception ex) { Console.WriteLine(ex.ToString()); }
            }
            Console.WriteLine(System.IO.File.ReadAllText("0:\\Root.txt"));
            Console.ReadLine();

            c = FullScreenCanvas.GetFullScreenCanvas();
            c.Clear(Color.LightGreen);
        }
```
I am using windows 10 in a virtual machine to create the OS, the OS itself is also in a virtual machine with a link to the default Filesystem.vdmk, and i edit the filesystem with ubuntu in another vm. All the virtual machines are on virtualbox.

Sorry for the long issue, I hope that anyone can help me because I have some cool plans for my os.

**Comment by fanoI** [comment]
Can you try to use Directory.GetFiles()? We have a test for this and it is working... CosmosVFS should not used by user code.

**Comment by jp2masa** [comment]
@Remco123 are you using the user kit or the dev kit?

**Comment by Remco123** [comment]
It might be a virtualbox issue because when I build the code to an iso and run it in virtualbox the File.ReadAllText method doesn't work (the Directory.GetFiles does work) but when I build and run to vmware it works perfectly, but than the graphics don't work and that is also something I need.
I am using the dev kit.

**Comment by fanoI** [comment]
If you need CGS and FAT these should work in Bochs it is a little less user friendly that VirtualBox.

What error you get in VirtualBox? ArgumentOutOf...?

**Comment by Remco123** [comment]
This is the error I am getting:
Exception: ArgumentOutOfRange_IndexLength
Parameter name: length

I am going to download bochs now.

**Comment by Remco123** [comment]
Bochs does work but it is slower than virtualbox, is virtualbox going to work in the future in terms of files?
