### ISSUE TITLE
I need help with plugs!

### ISSUE THREAD

**Issue by JackHalpin** [CosmosOS/Cosmos#73]
I'm in the process of creating my own operating system with Cosmos, but I have a problem.

I need help with **plugs**! So far I've managed to write my operating system using code that doesn't require plugs. But this makes my OS *really limited*. I can't even make it display the *time*! Also, I can only translate strings into integers, which means there is no way to calculate decimal numbers without getting the "plug needed" build error.

I don't quite understand how to write and use plugs in Cosmos properly. Development of my OS has been delayed because I can hardly do anything. I'd defiantly like someone to tell me how to write and use plugs the right way.

Thanks in advance!

By the way, I'm using Milestone 4 with Visual C# 2008. I tried using the latest version of Cosmos, but it wasn't any different.

**Comment by mterwoord** [comment]
We have limited documention, unfortunately. Have you looked at the sources of Cosmos to see how plugs work?

**Comment by JackHalpin** [comment]
(Man! I'm glad somebody finally took the time to answer my question! I've been asking this question on multiple websites since March 30th. Thank you so much!)

So I was digging through the source code, and I saw lots of lumps of code named MathImpl, ConsoleImpl, and others. These are plugs, correct? (I found these in Cosmos/source/Cosmos.System.Plugs/System/). Anyway, I tried sticking the code from MathImpl.cs into its own class in my operating system's project. Then I tried using the Math.Pow function in a simple program that calculates powers:

            // ASKS FOR THE NUMBERS
            Console.Write("Enter a base number: ");
            string STRbasenum = Console.ReadLine();
            Console.WriteLine("");
            Console.Write("Enter an exponent: ");
            string STRexpo = Console.ReadLine();

            //TRANSLATES THEM INTO INTEGERS
            var basenum = Int16.Parse(STRbasenum);
            var expo = Int16.Parse(STRexpo);

            // CALCULATES THE NUMBERS
            var answer = Math.Pow(basenum, expo);

            // GIVES OUT THE ANSWER
            Console.WriteLine("The answer is " + answer);

But when I press F5 to start the program, I get the build error "System.NotImplementedException: The method or exception is not implemented." Do you know what the problem is?

(Sorry for the delay; I wanted to reply right away, but I was busy today.)

**Comment by mterwoord** [comment]
You get a build error? That's weird. Can you post the full compiler output?

**Comment by JackHalpin** [comment]
Here it is:

![Build Error](https://cloud.githubusercontent.com/assets/11796672/7004637/167ae18c-dc34-11e4-8483-3b8e627955e1.GIF)

Before adding MathImpl.cs to my project, I got this error:

![First Build Error](https://cloud.githubusercontent.com/assets/11796672/7004663/86216b8c-dc34-11e4-83d3-90537e0f72f0.GIF)

**Comment by mterwoord** [comment]
OK, you're using an ancient cosmos release. Can you upgrade to latest?

**Comment by JackHalpin** [comment]
(That was fast!)

OK. Hold on a second... (It's already installed)

**Comment by JackHalpin** [comment]
IT WORKS!!!!!!!!!!! All I needed to do was upgrade! Thank you VERY MUCH for helping me!

**Comment by mterwoord** [comment]
If this "issue" is solved, please close it. THanks! :)

**Comment by JackHalpin** [comment]
Got it. Good-bye!
