### ISSUE TITLE
Yet another Invoking il2cpu issue. 

### ISSUE THREAD

**Issue by djlw78** [CosmosOS/Cosmos#733]
I have all the proper frame works installed I'm on 4.5.2. I have been messing with Cosmos graphics. I feel like I'm insane trying to make it work expecting different results... Always get the same, hopefully, you can help. Very specifically in the output, I notice what when wrong but I am not sure how to fix it. Already when to cosmos support 2/5 not much help. Here is when it's going wrong (in bold)...

---------OUTPUT----------
1>------ Build started: Project: MOSS-PC, Configuration: Debug Any CPU ------
1>MOSS-PC -> C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\netstandard1.5\MOSS-PC.dll
2>------ Build started: Project: MOSS-PCBoot, Configuration: Debug Any CPU ------
**2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.**
2>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\net462\MOSS-PCBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\netstandard1.5\MOSS-PC.dll" 
**2>C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False"** "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\net462\MOSS-PCBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\netstandard1.5\MOSS-PC.dll" 
2>	Working directory = 'C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'
2>	Rings: Start check
2>	Rings: Assembly 'Cosmos.System'
2>	Rings:         Ring = System
2>	Rings:     Dependency 'Cosmos.HAL'
2>	Rings:         Ring = HAL
2>	Rings: Assembly 'Cosmos.Core.Common'
2>	Rings:         Ring = Core
2>	Rings: Assembly 'MOSS-PC'
2>	Rings:         Ring = User
2>	Rings:     Dependency 'Cosmos.System'
2>	Rings:         Ring = System
2>	Rings:     Dependency 'Cosmos.Core'
2>	Rings:         Ring = Core
2>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
2>	Error: Exception: System.Exception: Assembly 'MOSS-PC' is in ring User(3). It references assembly 'Cosmos.Core' which is in ring Core(0), but this is not allowed!
2>	   at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner, Assembly entryAssembly) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 105
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 199
2>	Loaded assemblies: 
2>	C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\xdj78\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\xdj78\Documents\MOSS-PC\MOSS-PC\bin\Debug\netstandard1.5\MOSS-PC.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:20.7427711
2>Done building project "MOSS-PCBoot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by zarlo** [comment]
Error: Exception: System.Exception: Assembly 'MOSS-PC' is in ring User(3). It references assembly 'Cosmos.Core' which is in ring Core(0), but this is not allowed!

http://www.gocosmos.org/docs/rings/
https://github.com/CosmosOS/Cosmos/wiki/Rings

**Comment by djlw78** [comment]
What do I use besides Cosmos.Core? there's not much more...

**Comment by djlw78** [comment]
Also where am I calling Cosmos.Core?
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using System.Threading;
using Cosmos.IL2CPU.Plugs;
using System.Threading.Tasks;

**Comment by djlw78** [comment]
I have 1 class.

**Comment by jp2masa** [comment]
Cosmos.Core is probably a referenced assembly.

**Comment by djlw78** [comment]
That really doesn't make sense... But ok...

**Comment by djlw78** [comment]
How would I restart it with out throwing IL2CPU every time now?

**Comment by jp2masa** [comment]
Are you getting the same error?

**Comment by djlw78** [comment]
Yep. It's an internal glitch.... Here is the pastebin of what I have. No other code. https://pastebin.com/CSP1de3S Please @jp2masa note I have done this with over 10 projects and end up with same results sooner or later. "As quoted. Insanity..."

**Comment by jp2masa** [comment]
What's the error in the output window?

**Comment by djlw78** [comment]
It's fixed now the problem is System.Threading isn't supported.

**Comment by djlw78** [comment]
@jp2masa Sometime exporting doesn't fully update.

**Comment by jp2masa** [comment]
Exporting what?

**Comment by djlw78** [comment]
For example, my line of code says "Cosmos booted successfully. Type a line of text to get it echoed back." I change the code (removing that line) I save all and it still prints that; but this issue I posted is closed as more support for .net is needed if I keep having trouble with not exporting properly ill post new issue thank for your help @jp2masa
