### ISSUE TITLE
Error occurred while invoking IL2CPU

### ISSUE THREAD

**Issue by Anson12666** [CosmosOS/Cosmos#735]
I'm using C# in Visual Studio, I have recieved a error message 

> Error occurred while invoking IL2CPU

It's don't seems as the problem of the version. I don't receive any error code in other new solution but only in the code below.

I've tried to copy those code to another project which is blank and startable. But it doesn't solve the problem, so that I think it's the problem of the code(But visual studio did not found any error).

By the way, I am using the latest version of Visual Studio and also Cosmos User Kit.
And I would like to know that how could I install the developer kti.
Thanks for you help ^_^ .

```
using System;
using Sys = Cosmos.System;

namespace AnsonOS
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.Clear();
            Console.WriteLine("Wellcome! Developer Beta V.0.1.1 ");
            Console.WriteLine("AnsonOS booted successfully.");
            Console.WriteLine("A very wonderful upgrade!");
        }

        protected override void Run()
        {
                Console.Write("\n"+"Command$ ");
                var input = Console.ReadLine();


                if (input == "help")
                {
                    Console.Write("Funtion 1: text ");
                    Console.Write("\n");
                    Console.Write("Funtion 2: shutdown");
                    Console.Write("\n");
                    Console.Write("Funtion 3: reboot");
                }

                else if (input == "text")
                {
                    Console.Write("Write any thing here: ");
                    var textinput = Console.ReadLine();
                    Console.WriteLine(textinput);
                }

                else if (input == "chat")
                {
                    Console.Write("Just A beta!" + "\n" + "What are you doing?");
                    var textinput = Console.ReadLine();
                    Console.Write(textinput + "?" + "Thats Cool!" + "What are you going to do then?");
                    var textinput2 = Console.ReadLine();
                    Console.Write("I love" + textinput2 + "too!" + "See you Later!");
                    Console.Write("Just Beta");
                }

                else if (input == "reboot")
                {
                    Sys.Power.Reboot();
                }

                else if (input == "beep")
                {
                    Console.Beep();
                }

                else if (input == "update")
                {
                    Console.WriteLine("We've fix some bugs and add some new feature.");
                }

                else
                {
                    const string quote = "\"";
                    Console.Write(quote + input + quote + " is not a command in AnsonOS, please try again.");
                }
            }
        }
    }
```

**Comment by zarlo** [comment]
can you give us the output log (i think Console.Beep(); needs to be plugged)

**Comment by Anson12666** [comment]
how can I get it

**Comment by Blizzardo1** [comment]
It looks like I'm having this issue on a totally different scope:

`1>------ Build started: Project: BlizzetaOperatingSystem, Configuration: Debug Any CPU ------
1>%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\BlizzetaOperatingSystem.csproj : warning NU1604: Project dependency Cosmos.Debug.Kernel does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
1>%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\BlizzetaOperatingSystem.csproj : warning NU1604: Project dependency Cosmos.System2 does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
1>BlizzetaOperatingSystem -> %devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\netstandard2.0\BlizzetaOperatingSystem.dll
1>Done building project "BlizzetaOperatingSystem.csproj".
2>------ Build started: Project: BlizzetaOperatingSystemBoot, Configuration: Debug Any CPU ------
2>	Invoking il2cpu.exe "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\net462\BlizzetaOperatingSystemBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\netstandard2.0\BlizzetaOperatingSystem.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.System2.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:%appdata%\Cosmos User Kit\Kernel" 
2>%appdata%\Cosmos User Kit\Build\VSIP\Cosmos.targets(70,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "%appdata%\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\net462\BlizzetaOperatingSystemBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\netstandard2.0\BlizzetaOperatingSystem.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.System2.dll" "References:%appdata%\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:%appdata%\Cosmos User Kit\Kernel" 
2>	Working directory = '%devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\net462\'
2>	Warning: Loaded : DebugEnabled
2>	Warning: Loaded : StackCorruptionDetectionEnabled
2>	Warning: Loaded : DebugMode
2>	Warning: Loaded : StackCorruptionDetectionLevel
2>	Warning: Loaded : TraceAssemblies
2>	Warning: Loaded : DebugCom
2>	Warning: Loaded : OutputFilename
2>	Warning: Loaded : EnableLogging
2>	Warning: Loaded : EmitDebugSymbols
2>	Warning: Loaded : IgnoreDebugStubAttribute
2>	Warning: Loaded : References
2>	Warning: Loaded : AssemblySearchDirs
2>	Warning: Executing IL2CPU on assembly
2>	Warning: Kernel Base: Cosmos.System.Kernel
2>	Warning: Checking Reference: %devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\netstandard2.0\BlizzetaOperatingSystem.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.System2.dll
2>	Warning:   Exists
2>	Warning: Checking Reference: %appdata%\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
2>	Warning:   Exists
2>	Error: Exception: System.Exception: 
2>	Native code encountered, plug required.
2>	  DO NOT REPORT THIS AS A BUG.
2>	  Please see http://www.gocosmos.org/docs/plugs/missing/
2>	  Need plug for: System.Reflection.CorElementType  System.Enum.InternalGetCorElementType().
2>	  Called from :
2>	System.Enum::System.TypeCode GetTypeCode()
2>	System.IConvertible::System.TypeCode GetTypeCode()
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in F:\Code\CSharp\COSMOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 599
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in F:\Code\CSharp\COSMOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 755
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in F:\Code\CSharp\COSMOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 249
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in F:\Code\CSharp\COSMOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 210
2>	Warning: Loaded assemblies: 
2>	Warning: %devel%\BlizzetaOperatingSystem\BlizzetaOperatingSystem\bin\Debug\netstandard2.0\BlizzetaOperatingSystem.dll
2>	Warning: %appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
2>	Warning: %appdata%\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
2>	Warning: %appdata%\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	Warning: %appdata%\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	Warning: %appdata%\Cosmos User Kit\Kernel\Cosmos.System2.dll
2>	Warning: %appdata%\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
2>	Warning: Errored
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:02.7826924
2>Done building project "BlizzetaOperatingSystemBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by zarlo** [comment]
@Blizzardo1 System.Reflection.CorElementType System.Enum.InternalGetCorElementType() needs to be pluged

**Comment by Blizzardo1** [comment]
I get that, however, the problem that I see is that it appears to be coming from the ILScanner.cs file in the src, and that's the only place I can think of where this error truly occurs, as I've removed all enums for starters, and I've removed all properties, overloads except for ToString(); Unless that's part of the problem, which I highly doubt.

**Comment by zarlo** [comment]
when you need a plug you will get an error from ILScanner.cs
