### ISSUE TITLE
A Plug for Decimal Conversion?

### ISSUE THREAD

**Issue by JackHalpin** [CosmosOS/Cosmos#74]
I have a plug problem in Cosmos: I can't work with decimal numbers. Here's an example: 

If I was to write a "two number adder" program (capable of adding decimal numbers), I would write it like this:

    // ASKS FOR FIRST NUMBER AND SAVES IT AS A STRING
    Console.Write("Enter first number: ");
    string STRfirst = Console.ReadLine();

    // ASKS FOR SECOND NUMBER AND SAVES IT AS A STRING
    Console.Write("Enter second number: ");
    string STRsecond = Console.ReadLine();

    // CONVERTS THE STRINGS INTO DECIMAL NUMBERS
    var first = Convert.ToDecimal(STRfirst);
    var second = Convert.ToDecimal(STRsecond);

    // ADDS UP THE DECIMAL NUMBERS
    var answer = first + second;

    // WRITES THEM
    Console.WriteLine("Here's the answer: " + answer);
    Console.ReadLine()

But when I build this program, it gives me the "Plug required" error.  I understand this error, but I have no idea how to write a plug for Convert.ToDecimal. **Is there a plug for Convert.ToDecimal available anywhere?** If there isn't, could somebody help me write one?

Thanks in advance!

**Comment by mterwoord** [comment]
We don't have a plug for that currently, obviously..

I'm not sure if decimal or float is currently functional.. You're free to
jump in and help us out on this subject though! (We're eager to help you
with that...)


2015-04-07 16:10 GMT+02:00 Jack Halpin <notifications@github.com>:

**Comment by JackHalpin** [comment]
Thanks for the reply. I checked Float.Parse(); it didn't work. Anyway if I come up with anything, I'll email you.

Bye!
