### ISSUE TITLE
il2cpu error... THIS time with assembly.core

### ISSUE THREAD

**Issue by Mcilie** [CosmosOS/Cosmos#740]
So I kept getting Il2Cpu errors. Basically those are the number one threat to us cosmos users. They have an infinite amount of reasons to occur. So this kept happening to me because the error did not say WHY it happened it just said 'error invoking il2cpu'. A previous warning next to it tells me that it cannot locate the assembly 'System.Core' which _might_  result into il2cpu errors. How do i fix this?

**Comment by jp2masa** [comment]
The error is in the output window. System.Core is pulled by the project system, and you would get an error about it if it was resolved.

**Comment by Mcilie** [comment]
sorry if i wasnt clear enough.... this is what im getting:
![image](https://user-images.githubusercontent.com/25804313/29377969-6e1193dc-828b-11e7-8e0f-07ad8c909cb6.png)

**Comment by jp2masa** [comment]
The messages aren't ordered, look at the output window.

**Comment by Mcilie** [comment]
here is what i now realize is what your looking for. this is the complete error message from the output window: Error: Exception: System.Exception: Error compiling method 'SystemVoidCosmosKernel8KernelBeforeRun': System.Exception: OpCode IL_000B: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503 ---> System.Exception: OpCode IL_000B: Call tries to pop more stuff from analytical stack than there is!
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 503
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 518
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 964
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197

**Comment by jp2masa** [comment]
Are you building with the Release configuration?

**Comment by Mcilie** [comment]
i have tried both debug and release and they all fail

**Comment by jp2masa** [comment]
If you use the Debug configuration, what is the error log?

**Comment by Mcilie** [comment]
the error is : Error: Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2>	   at Cosmos.IL2CPU.AppAssembler.GenerateVMTCode(HashSet`1 aTypesSet, HashSet`1 aMethodsSet, Func`2 aGetTypeID, Func`2 aGetMethodUID) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AppAssembler.cs:line 1095
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 988
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197

**Comment by Mcilie** [comment]
could it have anything to do with my code?

**Comment by jp2masa** [comment]
Are you using `IEnumerable<T>`?

**Comment by Mcilie** [comment]
no

**Comment by Mcilie** [comment]
ill just give you my code and you can be the judge of that cuz i have No clue what that is
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using System.IO;
namespace CosmosKernel8
{
    public class Kernel : Sys.Kernel
    {
        bool fsttime = true;

        protected override void BeforeRun()
        {
            var fs = new Sys.FileSystem.CosmosVFS();
            string path = @"0:\";
            Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
            try
            {
                if (Directory.Exists(path))
                {
                    Console.WriteLine("That path exists already.");
                    return;
                }
                else { Console.WriteLine("boo"); }
            }
            catch (System.IO.IOException) { }
        }

        protected override void Run()
        {
            Console.WriteLine("welcome to my os\n type help for  alist of commands");
            //TODO add help command

            //bool q = true; // basic shutdown emulator or equivalency
            // will be replaced when migrated to COSMOS
            //while (q) //Normally Case and Switch dont run repeatedly so loop is necessary untill migration


            Console.Write("BetaUser-$ "); //because mac/linux
                                          //NOTE: .Write is important for prompt like format 
            string x = Console.ReadLine();
            string[] xy = x.Split(' '); //Ahem....parsing


            switch (xy[0])
            {
                case ("echo"):
                    //echo command
                    int asize = (xy.Length - 1);
                    var echo = new List<String>(xy);
                    echo.RemoveAt(0);
                    string[] echos = echo.ToArray();
                    string print = "";
                    foreach (string a in echos)
                    {
                        print = print + a + " ";
                    }
                    //im new to this ok?
                    Console.WriteLine(print);
                    break;
                case ("stdown"):

                    break;
                default:
                    Console.WriteLine("No Such command {0}", xy[0]);
                    break;

            }
        }
    }
}

**Comment by charlesbetros** [comment]
Probably RemoveAt causing the issue?

**Comment by jp2masa** [comment]
I debugged the compiler and I think that the problem is `var echo = new List<String>(xy);`.
`xy` is being passed as an `IEnumerable<T>`.

**Comment by Mcilie** [comment]
im new to this. How would i work around this? I'll also try removing the @

**Comment by jp2masa** [comment]
Use a for loop and start looping from 1, no need to remove index 0.

**Comment by Mcilie** [comment]
Thank you.. It worked.
