### ISSUE TITLE
Have to build twice for changes to appear

### ISSUE THREAD

**Issue by dsdude123** [CosmosOS/Cosmos#741]
I've run into a quite unusual issue with the newest userkit of Cosmos in VS2017 Enterprise. It seems every time I build the project, my changes don't appear. I take the ISO generated and load it into Virtualbox and none of the changes I made appear. Once building a second time, the changes appear.

**Comment by jp2masa** [comment]
That's a known issue, and it still exists in the Dev Kit, but we will move to CPS soon, and it's not worth to spend time fixing bugs in the current project system.

**Comment by Remco123** [comment]
Try to clean the project every time before you build it, that worked for me.

**Comment by valentinbreiz** [comment]
Yes, you can delete obj and bin folder :)

**Comment by dsdude123** [comment]
Thanks, cleaning the project before build fixes the issue. Any way to automate this?

**Comment by Mcilie** [comment]
maybe make a .bat file that asks you for input and then removes the directories (i normally use shell scripts; not sure if windows .bat is as powerful.

**Comment by Arawn-Davies** [comment]
A 'dotnet clean' from the directory with your OS solution file with automatically clean all of the project outputs from the last build so probably no need to automate, just one line of code, but I guess having it as part of a debug procedure will come in handy. Is it okay to close this?

**Comment by jp2masa** [comment]
Fixed by #839
