### ISSUE TITLE
Error Deploying OS

### ISSUE THREAD

**Issue by flash76** [CosmosOS/Cosmos#743]
OK guys, I'm really new to Cosmos (as in, I just started yesterday), and I experienced this problem also yesterday. But I'm not sure how I fixed it.

Anyway, when I click 'Run,' I get an error message saying "A project with an output of class library cannot be started directly.

In order to debug this project, add an executable project to this solution which references the library project. Set the startup project to the executable project as the startup project"

Here's the image/screenshot:

![image](https://user-images.githubusercontent.com/30060599/29499576-94120094-85e2-11e7-84ea-4f1bc53eda7e.png)

**Comment by jp2masa** [comment]
You should use the "Cosmos Operating System" template, not the Kernel one.

**Comment by flash76** [comment]
The only one I see are C# OS, Cosmos Project (empty), VB.NET OS, F# OS.

**Comment by flash76** [comment]
[UPDATE] I set the startup project to the 'Boot' project and that seems to have fixed it.
