### ISSUE TITLE
Newest update of Visual Studio causes build to fail

### ISSUE THREAD

**Issue by dsdude123** [CosmosOS/Cosmos#744]
After updating my copy of Visual Studio to the newest version, I am no longer able to build with the newest userkit. At first I thought it might have been a botched update so I set up a new VM with a fresh copy of VS 2017 and installed the userkit but still ran into the same error. Details of the error are below.

Severity: Error
		
Description: Assets file 'C:\Users\RuikoOSDeveloper\source\repos\CosmosKernel3\CosmosKernel3\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.2'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project.	

Project: CosmosKernel3Boot	

File: C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.Net.Sdk\build\Microsoft.PackageDependencyResolution.targets	

Line: 165

**Comment by zarlo** [comment]
I think its an error with  .net core 2

**Comment by dsdude123** [comment]
Found a manual fix to this issue that can work for now, a few edits to the .cosmos file of a project will allow for it to build successfully again. As a side effect however, a large number of DLLs from .NET Framework are copied to the output folder. Instructions are below:

In the .cosmos file for your project (i.e. CosmosKernel1Boot.cosmos):

1. Change `<TargetFramework>net462</TargetFramework>` to `<TargetFrameworks>net462</TargetFrameworks>`

2. In the next `<PropertyGroup>` containing settings for ISO, VMWare, etc. add the following lines before the `</PropertyGroup>` tag:
`    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>`
`   <TargetFrameworkProfile />`

Once done, reload the solution and you should be ready to go.

**Comment by SapphireGitHub** [comment]
Crap. I just updated an hour ago. :(

**Comment by jp2masa** [comment]
The latest Dev Kit should be working.
User Kit users will have to replace the Cosmos.targets file in "%appdata%\Cosmos User Kit\Build\VSIP\" by this one: https://github.com/CosmosOS/Cosmos/raw/ea2354dcadfc44e229b8e2c5ab57fff8dbc97f5d/source/Cosmos.Build.MSBuild/Cosmos.targets.

**Comment by G123TheCat** [comment]
new error log:
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: CosmosKernel7, Configuration: Debug Any CPU ------
1>CosmosKernel7 -> C:\Users\Gabi\Source\Repos\CosmosKernel7\CosmosKernel7\bin\Debug\netstandard1.5\CosmosKernel7.dll
2>------ Build started: Project: CosmosKernel7Boot, Configuration: Debug Any CPU ------
2>E:\IM THE ONE\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cosmos.Core_Asm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>E:\IM THE ONE\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cosmos.Core_Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>E:\IM THE ONE\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cosmos.System2_Plugs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Users\Gabi\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(70,13): error MSB4064: The "KernelPkg" parameter is not supported by the "IL2CPU" task. Verify the parameter exists on the task, and it is a settable public instance property.
2>C:\Users\Gabi\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(70,5): error MSB4063: The "IL2CPU" task could not be initialized with its input parameters. 
2>Done building project "CosmosKernel7Boot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
