### ISSUE TITLE
Cannot Compile default code.

### ISSUE THREAD

**Issue by Dominic12** [CosmosOS/Cosmos#745]
Die Ressourcendatei "C:\Users\Domin\source\repos\Kernel\Kernel\obj\project.assets.json" verfügt über kein Ziel für ".NETFramework,Version=v4.6.2". Stellen Sie sicher, dass die Wiederherstellung ausgeführt wurde und dass Sie "net462" in die TargetFrameworks für Ihr Projekt aufgenommen haben.	KernelBoot	C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.Net.Sdk\build\Microsoft.PackageDependencyResolution.targets	165

**Comment by fanoI** [comment]
Copy of https://github.com/CosmosOS/Cosmos/issues/744
