### ISSUE TITLE
Dot in directories name issue

### ISSUE THREAD

**Issue by geomtech** [CosmosOS/Cosmos#747]
Hello,

_(We already discuss of that with @jp2masa and @fanoI on gitter.)_

I discover an issue that need to be investigate. 
When we create a directory with a dot in the directory, the dot is replaced by many spaces...
Ex: If I want to create the directory "folder.system", it will be "folder         system".

I discover this when I wanted to make a system to display only directories that are not beginning by a dot (like on Linux and Android by default to not display hidden directories and files.)

The problem is here only with directories, files can have dot in the name, and can begin by a dot. (tested).

This is supported normally by FAT. So this is a problem of Cosmos.
Thanks for support.

PS: Sorry for my english if I made mistakes, I'm french and my English level is medium.

**Comment by fanoI** [comment]
In these days I'm trying to take advantage of the better work that is been done in Net Core regarding System.IO that will permit us to plug things at lower level.

For example this issue seems to be correct in my code using DirectoryInfo at least, Directory.Create() will use practically the same code in the end so I'm fiducious that this will work too in this case.

**Comment by jp2masa** [comment]
This is what should happen, according to the FAT spec:
- If a file or directory name start with a dot, it's a dot entry. This special kind of entries can only be created by the FAT driver when a directory is created. The following cases have to be verified:
    - Currently dot entries are not created by the FAT implementation.
    - When trying to create a directory entry with a name starting with a dot, an exception should be thrown (not sure what's the current behaviour in this case).
- If a file or directory name contains a dot, it has to be a long filename, not sure how it works currently.

**Comment by geomtech** [comment]
Okay, so do you want me to close the issue, because it's not really an issue if it's in the FAT specs ?

**Comment by jp2masa** [comment]
Dots aren't allowed only at the start of the directory entry name. The cases I listed have to be verified/fixed.

**Comment by fanoI** [comment]
Probably the easiest way is in a Windows PC with a FAT32 HDD formatted and a C# program that make create any file you want... and see where it fails. Maybe a VM is the best way...
