### ISSUE TITLE
2 files are missing.

### ISSUE THREAD

**Issue by RRR9996** [CosmosOS/Cosmos#749]
Th Files (CosmosKernel3Boot.Cosmos and the ProgramInfo.cs) are not there. I cant boot because CosmosKernel3Boot.Cosmos isn't there.

**Comment by jp2masa** [comment]
AssemblyInfo.cs needs to be manually created in the new csproj. Make sure you're using the Operating System template.

**Comment by RRR9996** [comment]
i am. also ok.

**Comment by RRR9996** [comment]
I just can't boot because CosmosKernel3Boot.Cosmos is missing. And i'm using OS Template.

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit?
