### ISSUE TITLE
Cant compile sample code

### ISSUE THREAD

**Issue by Jan1902** [CosmosOS/Cosmos#750]
When having the project freshly created im getting the following error:

> Error		The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher.  Please install version 2.0 or higher of the .NET Core SDK.	TestingOSBoot	D:\VisualStudio2017\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets	57	

So i installed the 2.0 Core SDK and changed the option in the properties:

> Error		Assets file 'C:\Users\there\Documents\Visual Studio 2017\Projects\TestingOS\TestingOS\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.2'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project.	TestingOSBoot	C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.Net.Sdk\build\Microsoft.PackageDependencyResolution.targets	165	

I don't know if this is a mistake on my side or a bug.

Id be happy about any kind of help :)

**Comment by jp2masa** [comment]
If you're using the User Kit, check [SUPPORT.md](https://github.com/CosmosOS/Cosmos/blob/master/SUPPORT.md).

**Comment by Jan1902** [comment]
Wow, I honestly missed that though i actually saw that file somewhere, well thanks a lot :)
