### ISSUE TITLE
Fix invalid certificate on Homepage

### ISSUE THREAD

**Issue by Krokoklemmi** [CosmosOS/Cosmos#752]
I guess the image says enough. It's not exactly trustworthy if a browser gives this message for a website
![untitled](https://user-images.githubusercontent.com/17226354/29901556-da1fabd6-8df8-11e7-86c1-748cb183f298.png)

**Comment by KingLuigi4932** [comment]
Use Google Chrome Instead

**Comment by zarlo** [comment]
its an error with the sites SSL/TLS Certificate

**Comment by mterwoord** [comment]
Where does the HTTPS version get linked?

**Comment by geomtech** [comment]
Same on Google Chrome. @KingLuigi4932

**Comment by czhower** [comment]
"not exactly trustworthy if a browser gives this message"

Talk about dramatic overstatement. Cosmos website doesn't have any forms or secure data for end users. So not having a current SSL cert to transfer publicly available info is not trustworthy? Do you use PGP at the grocery store to read product descriptions?

None the less I've submitted a request for the certificate to be renewed. 99% of users don't use https but http on our website anyways as using SSL on such sites globally consumes actually measurable amounts of electricity and thus carbon output.

**Comment by KingLuigi4932** [comment]
@geomtech So you need to use http://

**Comment by czhower** [comment]
For some reason the reissue takes several hours and this one seems stuck in process. I opened a ticket but they said wait some more for now....

**Comment by czhower** [comment]
Now they say up to 24.. .so still waiting....

**Comment by geomtech** [comment]
I already saw somes Cosmos users give a https link to cosmos website on Gitter. I don't think creating this issue was the best idea, but now, it will done soon, thank you @czhower.

**Comment by czhower** [comment]
Have contacted them for a third time now that 24 hours has passed and they say:
"is currently receiving human validation by Comodo"

So I queried further.. they have to verify each domain but they refuse to use any of the emails in the WHOIS record and are demanding that I instead setup email on the domain so they can send email to me there to verify it. This is absolutely stupid. So I'll have to deal with this later.

**Comment by geomtech** [comment]
Okay, I don't think it's a big problem, it can wait. Thanks for all you're doing.

**Comment by fanoI** [comment]
I've noticed in Firefox a lot of https errors in Firefox on Microsoft sites too... IMHO it is a bug of that browser!

**Comment by czhower** [comment]
The browsers are nudging everyone to use SSL wherever possible but they are overdoing it and its detrimental to do so.

**Comment by geomtech** [comment]
CosmosExplorer, the webbrowser without SSL problems ! :)

**Comment by MihaMarkic** [comment]
Let's encrypt. Works instantly and certificates for free. And tls is good even for non secrets, since it doesn't allow anybody to implement mitm or eavesdrop on you.

**Comment by czhower** [comment]
After this is fixed we will also be able to get past the issue we had with SSL.

Urgent Notice

Updated Sep 29, 2017

The hosting service which hosts our website has a technical issue which has taken our website offline. We are urgently working to resolve this issue. We hope that our primary website will be restored today.

Hurricane Harvey

The issue is being impacted by lasting impacts to a center in Houston affected by Harvey and the impacts of moving resources out of the affected location

**Comment by LegitSoulja** [comment]
@czhower do you have gitter?

**Comment by czhower** [comment]
Fixed

**Comment by MihaMarkic** [comment]
Now (Firefox) won't load pages due to mixed content (https and http).
i.e. [https://www.gocosmos.org/download/](https://www.gocosmos.org/download/)

**Comment by czhower** [comment]
Should be fixed now. Force refresh.

**Comment by MihaMarkic** [comment]
@czhower Yep, force refresh was required.
