### ISSUE TITLE
Building procces stuck IL2CPU timed out

### ISSUE THREAD

**Issue by Remco123** [CosmosOS/Cosmos#753]
Hello,
I am having some problems while building my project, il2cpu just keeps running until it gives a message that it has timed out. This is the peice of code that gives the trouble:
`
CactusOS.Graphics.ImageFormats.PcxImage pcxImage = new Graphics.ImageFormats.PcxImage();
pcxImage.Load(Cosmos.System.FileSystem.VFS.VFSManager.GetFileStream(@"0:\Users\root\Media\Pictures\TestPicture.pcx"));
`
The load function contains this
`public override Image Load(Stream s)
        {
            return PcxInternals.Load(s);
        }
`
And this is the PcxInternals.Load() Function:

#region Load
            public static Image Load(Stream input)
            {
                PcxPalette palette = null;
                uint[] numArray = null;
                Image im;
                PcxHeader header = new PcxHeader(input);

                #region Checks
                if (header.id != PcxId.ZSoftPCX)
                {
                    throw new FormatException("Not a PCX file.");
                }
                if (((header.version != PcxVersion.Version3_0) && (header.version != PcxVersion.Version2_8_Palette)) && ((header.version != PcxVersion.Version2_8_DefaultPalette) && (header.version != PcxVersion.Version2_5)))
                {
                    throw new FormatException("Unsupported PCX version: " + header.version.ToString());
                }
                if (((header.bitsPerPixel != 1) && (header.bitsPerPixel != 2)) && ((header.bitsPerPixel != 4) && (header.bitsPerPixel != 8)))
                {
                    throw new FormatException("Unsupported PCX bits per pixel: " + header.bitsPerPixel.ToString() + " bits per pixel");
                }
                int width = (header.xMax - header.xMin) + 1;
                int height = (header.yMax - header.yMin) + 1;
                if (((width < 0) || (height < 0)) || ((width > 0xffff) || (height > 0xffff)))
                {
                    throw new FormatException("Invalid image dimensions: (" + header.xMin.ToString() + "," + header.yMin.ToString() + ")-(" + header.xMax.ToString() + "," + header.yMax.ToString() + ")");
                }
                int num3 = (header.bytesPerLine * 8) / header.bitsPerPixel;
                int BitDepth = header.bitsPerPixel * header.nPlanes;
                if ((((BitDepth != 1) && (BitDepth != 2)) && ((BitDepth != 4) && (BitDepth != 8))) && (BitDepth != 0x18))
                {
                    throw new FormatException("Unsupported PCX bit depth: " + BitDepth.ToString());
                }
                #endregion

                #region Load Palette
                while (true)
                {
                    if (BitDepth == 1)
                    {
                        palette = PcxPalette.FromEgaPalette(PcxPalette.MONO_PALETTE);
                        break;
                    }
                    if (BitDepth >= 8)
                    {
                        if (BitDepth == 8)
                        {
                            long position = input.Position;
                            input.Seek(-769L, SeekOrigin.End);
                            if (input.ReadByte() != 12)
                            {
                                throw new FormatException("PCX palette marker not present in file");
                            }
                            palette = new PcxPalette(input, 0x100);
                            input.Seek(position, SeekOrigin.Begin);
                        }
                        else
                        {
                            palette = new PcxPalette(0x100);
                        }
                        break;
                    }
                    switch (header.version)
                    {
                        case PcxVersion.Version2_5:
                        case PcxVersion.Version2_8_DefaultPalette:
                            if (BitDepth == 2)
                            {
                                numArray = PcxPalette.CGA_PALETTE;
                                palette = PcxPalette.FromEgaPalette(numArray);
                            }
                            break;

                        default:
                            numArray = new uint[0];
                            palette = PcxPalette.FromColorMap(header.colorMap);
                            break;
                    }
                    if (numArray == null)
                    {
                        numArray = PcxPalette.EGA_PALETTE;
                    }
                    break;
                }
                #endregion

                im = new Image(width, height);
                uint[] array = new uint[width];
                for (int y = 0; y < height; y++)
                {
                    PcxByteReader byteReader = (header.encoding == PcxEncoding.RunLengthEncoded) ? ((PcxByteReader)new PcxRleByteReader(input)) : ((PcxByteReader)new PcxRawByteReader(input));
                    PcxIndexReader indxReader = new PcxIndexReader(byteReader, header.bitsPerPixel);
                    for (int j = 0; j < header.nPlanes; j++)
                    {
                        for (int m = 0; m < num3; m++)
                        {
                            uint num10 = indxReader.ReadIndex();
                            if (m < width)
                            {
                                array[m] |= num10 << (j * header.bitsPerPixel);
                            }
                        }
                    }
                    for (int x = 0; x < width; x++)
                    {
                        Color bgra;
                        uint TempC = array[x];
                        if (BitDepth == 24)
                        {
                            byte r = (byte)(TempC & 0xff);
                            byte g = (byte)((TempC >> 8) & 0xff);
                            byte b = (byte)((TempC >> 16) & 0xff);
                            bgra = Color.FromArgb(255,r, g, b);
                        }
                        else
                        {
                            bgra = palette[TempC];
                        }
                        im.SetPixel(x, y, bgra);
                    }
                }
                return im;
            }
            #endregion
I have absolutely no idea why this is happening, please help!

**Comment by jp2masa** [comment]
Check the output window.

**Comment by Remco123** [comment]
I did but it is saying nothing useful, only that it has timed out.
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: CactusOS.Base, Configuration: Debug Any CPU ------
1>CactusOS.Base -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS.Base\bin\Debug\netstandard2.0\CactusOS.Base.dll
2>------ Build started: Project: CactusOS.Graphics, Configuration: Debug Any CPU ------
3>------ Build started: Project: CactusOS.Boot.Terminal, Configuration: Debug Any CPU ------
2>CactusOS.Graphics -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS.Graphics\bin\Debug\netstandard2.0\CactusOS.Graphics.dll
4>------ Build started: Project: CactusOS.WindowFramework, Configuration: Debug Any CPU ------
4>CactusOS.WindowFramework -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS.WindowFramework\bin\Debug\netstandard2.0\CactusOS.WindowFramework.dll
5>------ Build started: Project: CactusOS.ApplicationFramework, Configuration: Debug Any CPU ------
5>CactusOS.ApplicationFramework -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS.ApplicationFramework\bin\Debug\netstandard2.0\CactusOS.ApplicationFramework.dll
3>CactusOS.Boot.Terminal -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS.Boot.Terminal\bin\Debug\netstandard2.0\CactusOS.Boot.Terminal.dll
6>------ Build started: Project: CactusOS, Configuration: Debug Any CPU ------
6>CactusOS -> C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\netstandard2.0\CactusOS.dll
7>------ Build started: Project: CactusOSBoot, Configuration: Debug Any CPU ------
7>	Invoking il2cpu.exe "KernelPkg:" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\net462\CactusOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\netstandard2.0\CactusOS.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel" 
7>C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(70,5): error : IL2CPU timed out.
7>	Executing command line "C:\Users\User\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "KernelPkg:" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\net462\CactusOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\netstandard2.0\CactusOS.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel" 
7>	Working directory = 'C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\net462\'
7>	Loaded : DebugEnabled
7>	Loaded : StackCorruptionDetectionEnabled
7>	Loaded : DebugMode
7>	Loaded : StackCorruptionDetectionLevel
7>	Loaded : TraceAssemblies
7>	Loaded : DebugCom
7>	Loaded : OutputFilename
7>	Loaded : EnableLogging
7>	Loaded : EmitDebugSymbols
7>	Loaded : IgnoreDebugStubAttribute
7>	Loaded : References
7>	Loaded : AssemblySearchDirs
7>	Executing IL2CPU on assembly
7>	Kernel Base: Cosmos.System.Kernel
7>	Checking Reference: C:\Users\User\Documents\Visual Studio 2017\Projects\Cosmos Projects\CactusOS\CactusOS\bin\Debug\netstandard2.0\CactusOS.dll
7>	  Exists
7>	Checking Reference: C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
7>	  Exists
7>	Checking Reference: C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
7>	  Exists
7>	Checking Reference: C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
7>	  Exists
7>	Checking Reference: C:\Users\User\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
7>	  Exists
7>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
7>	IL2CPU task took 00:14:59.9979488
7>Done building project "CactusOSBoot.Cosmos" -- FAILED.
7>
========== Build: 6 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jp2masa** [comment]
Probably IL2CPU got stuck in an infinite loop.

**Comment by Remco123** [comment]
Probably, but how do I fix this? If that is even possible.

**Comment by jp2masa** [comment]
You can try to run that code in the test runner and debug the compiler.

**Comment by Remco123** [comment]
I am new to that, how would i do that?

**Comment by jp2masa** [comment]
You need to open Test.sln, then set Cosmos.TestRunner as the startup project. Then, in Cosmos.TestRunner.Core, enable DebugIL2CPU and comment the KernelPkg line in DefaultEngineConfiguration. Set the kernel to run in TestKernelSets, then copy your code to that kernel and run the test runner.

**Comment by Remco123** [comment]
When I run the TestRunner it says it can't find the assembly.
System.IO.FileNotFoundException: 'Could not load file or assembly 'TestKernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
I need to add it like this right?
![afbeelding](https://user-images.githubusercontent.com/29398596/29937370-925e03a0-8e85-11e7-9f46-8d19ec742d44.png)

**Comment by KingLuigi4932** [comment]
@Remco123 try comment yield return typeof(KernelGen3.Boot);
and uncomment the other one on
 public static IEnumerable<Type> GetStableKernelTypes() Method
        This   -> //yield return typeof(KernelGen3.Boot);

**Comment by Remco123** [comment]
Still the same error, but it looks like the GetStableKernelTypes() function is not used.

**Comment by fanoI** [comment]
Do you made this change?

        // Kernel types to run: the ones that will run in test runners that use the default engine configuration.
        public static IEnumerable<Type> GetKernelTypesToRun()
        {
            //yield return typeof(KernelGen3.Boot);
            return GetStableKernelTypes();
        }

**Comment by Remco123** [comment]
No I didn't but the result is the same, it still can't find it.

**Comment by KingLuigi4932** [comment]
@Remco123 try commenting your kernel test and then run it

**Comment by fanoI** [comment]
Do you made this change?

        // Kernel types to run: the ones that will run in test runners that use the default engine configuration.
        public static IEnumerable<Type> GetKernelTypesToRun()
        {
            //yield return typeof(KernelGen3.Boot);
            return GetStableKernelTypes();
        }

**Comment by Remco123** [comment]
I got the test runner working now, I needed to comment all the other kernels. But now the test runner is stuck in an infinite loop. This is the output in the console:

08:04:36.018010 Start executing
08:04:36.047278   Start configuration. IsELF = True, Target = Bochs
08:04:36.057523     Starting kernel 'C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\TestKernel.dll'
08:04:36.059274       Running task 'IL2CPU'
08:04:36.355524         Msg: Loaded : DebugEnabled
08:04:36.355851         Msg: Loaded : StackCorruptionDetectionEnabled
08:04:36.356024         Msg: Loaded : DebugMode
08:04:36.356163         Msg: Loaded : StackCorruptionDetectionLevel
08:04:36.356300         Msg: Loaded : TraceAssemblies
08:04:36.356447         Msg: Loaded : DebugCom
08:04:36.356572         Msg: Loaded : OutputFilename
08:04:36.356696         Msg: Loaded : EnableLogging
08:04:36.356819         Msg: Loaded : EmitDebugSymbols
08:04:36.356941         Msg: Loaded : IgnoreDebugStubAttribute
08:04:36.357061         Msg: Loaded : References
08:04:36.357181         Msg: Loaded : AssemblySearchDirs
08:04:36.423698         Msg: Executing IL2CPU on assembly
08:04:36.452610         Msg: Kernel Base: Cosmos.System.Kernel
08:04:36.452861         Msg: Checking Reference: C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\TestKernel.dll
08:04:36.453027         Msg:   Exists
08:04:36.456440         Msg: Checking Reference: C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\Cosmos.Core_Plugs.dll
08:04:36.456649         Msg:   Exists
08:04:36.457337         Msg: Checking Reference: C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\Cosmos.Core_Asm.dll
08:04:36.457496         Msg:   Exists
08:04:36.458044         Msg: Checking Reference: C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\Cosmos.System2_Plugs.dll
08:04:36.458748         Msg:   Exists
08:04:36.460174         Msg: Checking Reference: C:\Users\User\Downloads\Cosmos\Cosmos\Tests\Cosmos.TestRunner\bin\Debug\netcoreapp2.0\win7-x86\Cosmos.Debug.Kernel.Plugs.Asm.dll
08:04:36.461082         Msg:   Exists

**Comment by jp2masa** [comment]
Click on the "pause" button and see where it breaks.

**Comment by Remco123** [comment]
It brakes here:
do
                {
                    xDeclaringTypeHandle = xDefinition.GetDeclaringType();
                    xDeclaringTypeDefinition = reader.GetTypeDefinition(xDeclaringTypeHandle);

                    string xDeclaringTypeName = xDeclaringTypeDefinition.Namespace.IsNil
                                                ? reader.GetString(xDeclaringTypeDefinition.Name)
                                                : reader.GetString(xDeclaringTypeDefinition.Namespace) + "." + reader.GetString(xDeclaringTypeDefinition.Name);

                    xName = xDeclaringTypeName + "+" + xName;
                } while (xDeclaringTypeDefinition.Attributes.HasFlag(TypeAttributes.NestedPublic | TypeAttributes.NestedPrivate));

and the xName parameter looks like this: "PcxInternals+PcxInternals+PcxInternals+PcxInternals+PcxInternals+PcxInt+PcxInternals+PcxInternals+PcxInternals+PcxInternals+(way more PxcInternals here but adding them all is useless, you get the point)+PcxPalette"

**Comment by jp2masa** [comment]
That method is somewhat recent. I'll check it.

**Comment by jp2masa** [comment]
Try changing the body of [this method](https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.Debug.Symbols/LocalTypeProvider.cs#L70) to:
```cs
try
{
    var xType = mModule.ResolveType(MetadataTokens.GetToken(handle), null, null);
    return xType;
}
catch
{
    return null;
}
```

**Comment by Remco123** [comment]
Yes that works, should i reinstall cosmos via the bat file now?

**Comment by jp2masa** [comment]
Yes.

**Comment by Remco123** [comment]
All working now, thanks for the help guys!
