### ISSUE TITLE
VGA driver development -- I'm stuck!

### ISSUE THREAD

**Issue by DaveB565** [CosmosOS/Cosmos#761]
Good afternoon! I've been trying for months to develop a VGA driver for Cosmos, but I can't seem to get passed a major bug. I cannot seem to get passed this! When I try to clear the screen, I get staggered bars with which I can set, and others with which are just garbage from memory. I'm thinking either the timing is off, or the read or write mode is off. I'm attempting to enter into Mode 13H. The code is below. Any help at all would be appreciated! If anyone has run into this before, please give me some advice! Thanks!
 IOPort MiscellaniousOutRegRead = new IOPort(0x3CC);
            IOPort MiscellaniousOutRegWrite = new IOPort(0x03C2);
            IOPort SequencerAddress = new IOPort(0x03C4);
            IOPort SequencerData = new IOPort(0x03C5);
            IOPort CRTCIndex = new IOPort(0x3D4);
            IOPort CRTCData = new IOPort(0x3D5);
            IOPort AttributesWrite = new IOPort(0x3C0);
            IOPort AttributesDataRead = new IOPort(0x3C1);
            IOPort ResetVCToIndex = new IOPort(0x3DA);
            IOPort GraphicsRegsAddress = new IOPort(0x3CE);
            IOPort GraphicsRegsData = new IOPort(0x3CF);
            IOPort POS = new IOPort(0x0094); //Programable Option Select

            POS.Byte = 0x0F; //Unlock the ability to program the registers??

            MemoryBlock VGA = new MemoryBlock(0xA0000, 64000);

            //Sample code to setup Mode 13H?

            //Hold sequencer in an async reset
            SequencerAddress.Byte = 0x00;
            SequencerData.Byte = 0x02;

            //Set Miscelanious output register
            MiscellaniousOutRegWrite.Byte = 0x63;

            //Set Clocking Mode Register
            SequencerAddress.Byte = 0x01;
            SequencerData.Byte = 0x03;

            //Set the map mask register
            SequencerAddress.Byte = 0x02;
            SequencerAddress.Byte = 0x01;

            //Set Character map select..
            SequencerAddress.Byte = 0x03;
            SequencerData.Byte = 0x00;

            //Set Sequencer Memory Mode
            SequencerAddress.Byte = 0x04;
            SequencerData.Byte = 0x06;

            //Unlock Sequencer --let it operate
            SequencerAddress.Byte = 0x00;
            SequencerData.Byte = 0x03;

            //Unlock CRTC Registers
            CRTCIndex.Byte = 0x11;
            CRTCData.Byte = 0x8E;

            //Setup CRTC
            CRTCIndex.Byte = 0x17;
            CRTCData.Byte = 0xA3;

            //Set Horizontal Total Enable end
            CRTCIndex.Byte = 0x01;
            CRTCData.Byte = 0x4F;

            //Horizontal Blank Start
            CRTCIndex.Byte = 0x02;
            CRTCData.Byte = 0x50;

            //Horizontal Blank End
            CRTCIndex.Byte = 0x03;
            CRTCData.Byte = 0x82;

                        
            //Set Horizontal Retrace
            CRTCIndex.Byte = 0x04;
            CRTCData.Byte = 0x54;
            //et Horizontal Retrace End
            CRTCIndex.Byte = 0x05;
            CRTCData.Byte = 0x80;

            //Set Vertical total
            CRTCIndex.Byte = 0x06;
            CRTCData.Byte = 0xBF;

            //Set the overeflow register
            CRTCIndex.Byte = 0x07;
            CRTCData.Byte = 0x1F;

            //Set the Preset Row Scan Register
            CRTCIndex.Byte = 0x08;
            CRTCData.Byte = 0x00;

            //Set the Maximum Scan Line Register
            CRTCIndex.Byte = 0x09;
            CRTCData.Byte = 0x41;

            //Set Vertical Retrace Start register
            CRTCIndex.Byte = 0x10;
            CRTCData.Byte = 0x9C;

            //Set Vertical Retrace End Register
            CRTCIndex.Byte = 0x11;
            CRTCData.Byte = 0x8E;

            //Disable text mode Cursor
            CRTCIndex.Byte = 0x0A;
            CRTCData.Byte = 0x20;

            //Set Cursor start to 0
            CRTCIndex.Byte = 0x0B;
            CRTCData.Byte = 0x00;

            //Set cursor location at 0
            CRTCIndex.Byte = 0x0E;
            CRTCData.Byte = 0x00;

            CRTCIndex.Byte = 0x0F;
            CRTCData.Byte = 0x00;

            //Set the Offset Register
            CRTCIndex.Byte = 0x13;
            CRTCData.DWord = 0x28;

            //Set the Underline Location Register
            CRTCIndex.Byte = 0x14;
            CRTCData.Byte = 0x40;

            //Set Vertical Blank Start
            CRTCIndex.Byte = 0x15;
            CRTCData.Byte = 0x96;
            //set Vertical Blank End
            CRTCIndex.Byte = 0x16;
            CRTCData.Byte = 0xB9;
            //Set the Line Compare Register
            CRTCIndex.Byte = 0x18;
            CRTCData.DWord = 0x3FF;

            //Set the Overscan Color Register
            byte temp = AttributesDataRead.Byte;
            AttributesWrite.Byte = 0x11;
            AttributesWrite.Byte = 0x07;

            //Enable the four  Color Planes
            temp = ResetVCToIndex.Byte;
            AttributesWrite.Byte = 0x12;
            AttributesWrite.Byte = 0x0F;

            //reset atributes PEL horizontal panning
            AttributesWrite.Byte = 0x13;
            AttributesWrite.Byte = 0x00;

            //Set the COlor Select Register
            temp = AttributesDataRead.Byte;
            AttributesWrite.Byte = 0x14;
            AttributesWrite.Byte = 0x00;

            //setup graphics mode and the Graphics Registers
            temp = ResetVCToIndex.Byte;
            AttributesWrite.Byte = 0x10;
            AttributesWrite.Byte = 0x41;

            GraphicsRegsAddress.Byte = 0x05;
            GraphicsRegsData.Byte = 0x40;

            //Clear the set / reset register
            GraphicsRegsAddress.Byte = 0x00;
            GraphicsRegsData.Byte = 0x00;

            //Disable the set/reset register
            GraphicsRegsAddress.Byte = 0x01;
            GraphicsRegsData.Byte = 0x00;

            //Set the color compare register
            GraphicsRegsAddress.Byte = 0x02;
            GraphicsRegsData.Byte = 0x01;

            //Set the Data Rotate Register
            GraphicsRegsAddress.Byte = 0x03;
            GraphicsRegsData.Byte = 0x00;

            //Set Read Map select
            GraphicsRegsAddress.Byte = 0x04;
            GraphicsRegsData.Byte = 0x00;

            //Set Miscelanious Graphics Register
            GraphicsRegsAddress.Byte = 0x06;
            GraphicsRegsData.Byte = 0x05;

            //Set the Color don't care register
            GraphicsRegsAddress.Byte = 0x07;
            GraphicsRegsData.Byte = 0x00;

            //Set BitMask register
            GraphicsRegsAddress.Byte = 0x08;
            GraphicsRegsData.Byte = 0x0F;

         

            //a method for clearing screen -- In-efficeint

            uint Y, X = 0;
            uint offset = 0;
            for (Y = 1; Y < 200; Y++)
            {
                for (X = 1; X < 320; X++)
                {
                    offset = (Y * 320) + X;   //Correct offset calculation
                    VGA[offset] = 5;
                }

            }

            Y = 0;
            X = 0;

           
        }

    }
``

**Comment by jp2masa** [comment]
I think that mode 3h is text mode. From OSDev:
> mode 3h (80x25 text mode)

**Comment by DaveB565** [comment]
Oops! I meant mode 13H. The 320X200 256 color mode.

**Comment by DaveB565** [comment]
![output](https://user-images.githubusercontent.com/26034092/30138160-9e587010-931b-11e7-8ab8-569a8836dcf1.PNG)
This is the output that I'm getting.

**Comment by DaveB565** [comment]
Oops! I meant 13H. I posted a picture of what I'm getting as output on the
thread if you guys wouldn't mind taking a look! Hopefully I can get some
help. I've been stuck for weeks! Thanks in advance.

On Sep 6, 2017 3:09 PM, "jp2masa" <notifications@github.com> wrote:

I think that mode 3h is text mode. From OSDev:

mode 3h (80x25 text mode)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CosmosOS/Cosmos/issues/761#issuecomment-327626096>, or mute
the thread

**Comment by jp2masa** [comment]
I don't have much time to read the docs, but I'll try to find what's wrong.

I couldn't find anything about this, does this index exist?
```cs
//Hold sequencer in an async reset
SequencerAddress.Byte = 0x00;
SequencerData.Byte = 0x02;
```

Data byte should be 0x01, not 0x03 here:
```cs
//Set Clocking Mode Register
SequencerAddress.Byte = 0x01;
SequencerData.Byte = 0x03;
```

Not sure about this one:
1. Mode 13h is linear, do you need to enable memory plane write?
2. To enable the memory plane, bits 0-3 are used, maybe set to 0b1111 (0x0F) instead of 0x01?
```cs
//Set the map mask register
SequencerAddress.Byte = 0x02;
SequencerAddress.Byte = 0x01;
```

0x06 is for mode X, not mode 13h, you should use 0x0E instead:
```cs
//Set Sequencer Memory Mode
SequencerAddress.Byte = 0x04;
SequencerData.Byte = 0x06;
```

Again, I didn't find any docs about this:
```cs
//Unlock Sequencer --let it operate
SequencerAddress.Byte = 0x00;
SequencerData.Byte = 0x03;
```

This is for text mode, shouldn't be needed:
```cs
//Disable text mode Cursor
CRTCIndex.Byte = 0x0A;
CRTCData.Byte = 0x20;

//Set Cursor start to 0
CRTCIndex.Byte = 0x0B;
CRTCData.Byte = 0x00;

//Set cursor location at 0
CRTCIndex.Byte = 0x0E;
CRTCData.Byte = 0x00;

CRTCIndex.Byte = 0x0F;
CRTCData.Byte = 0x00;
```

I couldn't find any docs about index 0x18:
```cs
//Set the Line Compare Register
CRTCIndex.Byte = 0x18;
CRTCData.DWord = 0x3FF;
```

I couldn't find any docs about these indexes either:
```cs
//Set the color compare register
GraphicsRegsAddress.Byte = 0x02;
GraphicsRegsData.Byte = 0x01;
```
```cs
//Set Read Map select
GraphicsRegsAddress.Byte = 0x04;
GraphicsRegsData.Byte = 0x00;
```
```cs
//Set the Color don't care register
GraphicsRegsAddress.Byte = 0x07;
GraphicsRegsData.Byte = 0x00;
```

**Comment by DaveB565** [comment]
Thanks for the reply! I made your changes and the output didn't change much... This is the document I have been going off of. Yes those registers exist and I believe I have set them correctly. If you could take another look, I would appreciate it.. I've been starring at this document for months... Plus the Free VGA project has been of great help as well.
[ibm_vgaxga_trm2.pdf](https://github.com/CosmosOS/Cosmos/files/1283213/ibm_vgaxga_trm2.pdf)

**Comment by DaveB565** [comment]
Yahoo! Problem fixed. Here is the new code. Thanks allot for the help! Now, onto organizing all of this!
> 
  IOPort MiscellaniousOutRegRead = new IOPort(0x3CC);
            IOPort MiscellaniousOutRegWrite = new IOPort(0x03C2);
            IOPort SequencerAddress = new IOPort(0x03C4);
            IOPort SequencerData = new IOPort(0x03C5);
            IOPort CRTCIndex = new IOPort(0x3D4);
            IOPort CRTCData = new IOPort(0x3D5);
            IOPort AttributesWrite = new IOPort(0x3C0);
            IOPort AttributesDataRead = new IOPort(0x3C1);
            IOPort ResetVCToIndex = new IOPort(0x3DA);
            IOPort GraphicsRegsAddress = new IOPort(0x3CE);
            IOPort GraphicsRegsData = new IOPort(0x3CF);
            IOPort POS = new IOPort(0x0094); //Programable Option Select

            POS.Byte = 0x0F; //Unlock the ability to program the registers??

            MemoryBlock VGA = new MemoryBlock(0xA0000, 64000);

            //Sample code to setup Mode 13H?

            //Hold sequencer in an async reset
            SequencerAddress.Byte = 0x00;
            SequencerData.Byte = 0x02;

            //Set Miscelanious output register
            MiscellaniousOutRegWrite.Byte = 0x63;

            //Set Clocking Mode Register
            SequencerAddress.Byte = 0x01;
            SequencerData.Byte = 0x01;

            //Set the map mask register
            SequencerAddress.Byte = 0x02;
            SequencerAddress.Byte = 0x0F;

            //Set Character map select..
            SequencerAddress.Byte = 0x03;
            SequencerData.Byte = 0x00;

            //Set Sequencer Memory Mode
            SequencerAddress.Byte = 0x04;
            SequencerData.Byte = 0x0E;

            //Unlock Sequencer --let it operate
            SequencerAddress.Byte = 0x00;
            SequencerData.Byte = 0x03;

            //Unlock CRTC Registers
            CRTCIndex.Byte = 0x11;
            CRTCData.Byte = 0x8E;

            //Setup CRTC
            CRTCIndex.Byte = 0x17;
            CRTCData.Byte = 0xA3;

            //Set Horizontal Total Enable end
            CRTCIndex.Byte = 0x01;
            CRTCData.Byte = 0x4F;

            //Horizontal Blank Start
            CRTCIndex.Byte = 0x02;
            CRTCData.Byte = 0x50;

            //Horizontal Blank End
            CRTCIndex.Byte = 0x03;
            CRTCData.Byte = 0x82;

                        
            //Set Horizontal Retrace
            CRTCIndex.Byte = 0x04;
            CRTCData.Byte = 0x54;
            //et Horizontal Retrace End
            CRTCIndex.Byte = 0x05;
            CRTCData.Byte = 0x80;

            //Set Vertical total
            CRTCIndex.Byte = 0x06;
            CRTCData.Byte = 0xBF;

            //Set the overeflow register
            CRTCIndex.Byte = 0x07;
            CRTCData.Byte = 0x1F;

            //Set the Preset Row Scan Register
            CRTCIndex.Byte = 0x08;
            CRTCData.Byte = 0x00;

            //Set the Maximum Scan Line Register
            CRTCIndex.Byte = 0x09;
            CRTCData.Byte = 0x41;

            //Set Vertical Retrace Start register
            CRTCIndex.Byte = 0x10;
            CRTCData.Byte = 0x9C;

            //Set Vertical Retrace End Register
            CRTCIndex.Byte = 0x11;
            CRTCData.Byte = 0x8E;

            //Disable text mode Cursor
            CRTCIndex.Byte = 0x0A;
            CRTCData.Byte = 0x20;

            //Set Cursor start to 0
            CRTCIndex.Byte = 0x0B;
            CRTCData.Byte = 0x01;

            //Set cursor location at 0
            CRTCIndex.Byte = 0x0E;
            CRTCData.Byte = 0x00;

            CRTCIndex.Byte = 0x0F;
            CRTCData.Byte = 0x00;

            //Set the Offset Register
            CRTCIndex.Byte = 0x13;
            CRTCData.DWord = 0x28;

            //Set the Underline Location Register
            CRTCIndex.Byte = 0x14;
            CRTCData.Byte = 0x40;

            //Set Vertical Blank Start
            CRTCIndex.Byte = 0x15;
            CRTCData.Byte = 0x96;
            //set Vertical Blank End
            CRTCIndex.Byte = 0x16;
            CRTCData.Byte = 0xB9;
            //Set the Line Compare Register
            CRTCIndex.Byte = 0x18;
            CRTCData.DWord = 0x3FF;

            //Set the Overscan Color Register
            byte temp = AttributesDataRead.Byte;
            AttributesWrite.Byte = 0x11;
            AttributesWrite.Byte = 0x07;

            //Enable the four  Color Planes
            temp = ResetVCToIndex.Byte;
            AttributesWrite.Byte = 0x12;
            AttributesWrite.Byte = 0x0F;

            //reset atributes PEL horizontal panning
            AttributesWrite.Byte = 0x13;
            AttributesWrite.Byte = 0x00;

            //Set the COlor Select Register
            temp = AttributesDataRead.Byte;
            AttributesWrite.Byte = 0x14;
            AttributesWrite.Byte = 0x00;

            //setup graphics mode and the Graphics Registers
            temp = ResetVCToIndex.Byte;
            AttributesWrite.Byte = 0x10;
            AttributesWrite.Byte = 0x41;

            GraphicsRegsAddress.Byte = 0x05;
            GraphicsRegsData.Byte = 0x40;

            //Clear the set / reset register
            GraphicsRegsAddress.Byte = 0x00;
            GraphicsRegsData.Byte = 0x00;

            //Disable the set/reset register
            GraphicsRegsAddress.Byte = 0x01;
            GraphicsRegsData.Byte = 0x00;

            //Set the color compare register
            GraphicsRegsAddress.Byte = 0x02;
            GraphicsRegsData.Byte = 0x01;

            //Set the Data Rotate Register
            GraphicsRegsAddress.Byte = 0x03;
            GraphicsRegsData.Byte = 0x00;


            //Set Read Map select
            GraphicsRegsAddress.Byte = 0x04;
            GraphicsRegsData.Byte = 0x00;

            //Set Miscelanious Graphics Register
            GraphicsRegsAddress.Byte = 0x06;
            GraphicsRegsData.Byte = 0x05;

            //Set the Color don't care register
            GraphicsRegsAddress.Byte = 0x07;
            GraphicsRegsData.Byte = 0x00;

            //Set BitMask register
            GraphicsRegsAddress.Byte = 0x08;
            GraphicsRegsData.Byte = 0x0F;


         

            //a method for clearing screen -- In-efficeint

            uint Y, X = 0;
            uint offset = 0;
            for (Y = 0; Y < 200; Y++)
            {
                for (X = 0; X < 320; X++)
                {
                    offset = (Y * 320) + X;   //Correct offset calculation
                    VGA[offset] = 5;
                }

            }

            Y = 0;
            X = 0;

          
        }

**Comment by DaveB565** [comment]
Thanks for the help! I do have another random question for you! Now that I
have it to where I can set the screen, how do I get it to where it fills
the monitor? Is there a calculation for it? Thanks allot!

**Comment by jp2masa** [comment]
You mean fill the monitor like clearing the screen or setting pixels?

**Comment by fanoI** [comment]
Can you contribute this fixed VGA driver to the main Cosmos source code?

To do Clear() in a effecient way you should use MemoryBlock.Fill() method as done in the VBEDriver.

**Comment by DaveB565** [comment]
I can fill the screen, however it only fills the box that is the resolution
of the mode (a 320 X 200 square). I'm wondering what the calculation is to
get that square to fill the monitor completely? I know there is a way as
the old VGA driver used to do this. I also know it has something to do with
the CRTC registers, however I do not know what. I'm currently doing some
re-organization and polishing of the code at the moment, but as soon as I
get that done, and get it formatted similarly to the old one, I would be
happy to submit it. Some help on this would be greatly appreciated!

Thanks, Dave.

**Comment by DaveB565** [comment]
Is there any one out there that understands how this was possible? It's got
to be programming the CRTC, but how you could do the calculation to fill
the monitor using that resolution is beyond me. I could use some help with
this! I think this is pretty much the last of the polishing I'm going to do
to it, besides separating it out into individual functions and some
re-organization.

Thanks, Dave!

**Comment by DaveB565** [comment]
I've come across another bug while I was doing some testing. Whenever I set a pixel, it's sets it to the color I want, however it also turns the 2 pixels next to it black. Below is the code and a picture of the output. I'm stumped! Does anyone else have any ideas?

` private static MemoryBlock VGA = new MemoryBlock(0xA0000, 128000);
        private static int VGAMode = 0;


        public static void SetVGAGraphics(int Mode13)
        {


            IOPort MiscellaniousOutRegRead = new IOPort(0x3CC);
            IOPort MiscellaniousOutRegWrite = new IOPort(0x03C2);
            IOPort SequencerAddress = new IOPort(0x03C4);
            IOPort SequencerData = new IOPort(0x03C5);
            IOPort CRTCIndex = new IOPort(0x3D4);
            IOPort CRTCData = new IOPort(0x3D5);
            IOPort AttributesWrite = new IOPort(0x3C0);
            IOPort AttributesDataRead = new IOPort(0x3C1);
            IOPort ResetVCToIndex = new IOPort(0x3DA);
            IOPort GraphicsRegsAddress = new IOPort(0x3CE);
            IOPort GraphicsRegsData = new IOPort(0x3CF);
            IOPort POS = new IOPort(0x0094); //Programable Option Select

            byte[] SequencerRegs = new byte[5];
            byte[] CRTCRegs = new byte[19];
            byte[] AttributesRegs = new byte[21];
            byte[] GraphicsRegs = new byte[9];

            //Mode 13H Register settings

            // Clocking Mode Reg   Map Mask Reg  Char. Map select  Meme Mode
            byte[] SequencerRegs13 = new byte[5] { 0x02, 0x03, 0x0F, 0x00, 0x0E };
            byte[] CRTCRegs13 = new byte[25];

            byte[] AttributesRegs13 = new byte[21] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                //Color Pallet registers -- initialize to 0, ignore
                   0x41,                0x00,             0x0F,                             0x00, 0x00};
            // Set Attribute Mode   Overscan Reg  Enable 4 color planes     Clear Horiz. Panning and Color select Regs                                           


            byte[] GraphicsRegs13 = new byte[9] {       0x00, 0x00,                      0x00,                             0x10,                    0x01,
                                             //Disable and Clear set reset Regs   Set Color compare map to  map 0     data rotate reg.   Set Read Map to Map 0 
                0x40,                    0x05,                    0x00,                          0x0F};
            // Set Graphics Mode   Set Misc. Graphics Reg.  Clear Color Don't Care Reg.    Set Bitmask Register?

            POS.Byte = 0xFF; //Unlock the ability to program the registers??


            //Sample code to setup Mode 13H
            byte temp = AttributesDataRead.Byte;

            if (Mode13 == 13)
            {
                VGAMode = 13;
                //Hold sequencer in an async reset
                SequencerAddress.Byte = 0x00;
                SequencerData.Byte = 0x02;

                //Set Miscelanious output register
                MiscellaniousOutRegWrite.Byte = 0x63;
                SequencerRegs = SequencerRegs13;

                //Set sequencer Regs
                for (int i = 0; i < 6; ++i)
                {
                    SequencerAddress.Byte = (byte)i;
                    SequencerData.Byte = SequencerRegs[i];
                }

                //Unlock Sequencer --let it operate
                SequencerAddress.Byte = 0x00;
                SequencerData.Byte = 0x03;

                AttributesRegs = AttributesRegs13;

                //Set the attributes registers -- Color pallet to be setup later
                for (int i = 0x0F; i <= 21; i++)
                {
                    temp = ResetVCToIndex.Byte;
                    AttributesWrite.Byte = (byte)i;
                    AttributesWrite.Byte = AttributesRegs13[i];
                }

                // Set CRTC Registers -- More tweaking to come here

                //Unlock CRTC Registers
                CRTCIndex.Byte = 0x11;
                CRTCData.Byte = 0x8E;

                //Setup CRTC
                CRTCIndex.Byte = 0x17;
                CRTCData.Byte = 0xA3;

                //Set Horizontal Total Enable end
                CRTCIndex.Byte = 0x01;
                CRTCData.Byte = 0x4F;

                //Horizontal Blank Start
                CRTCIndex.Byte = 0x02;
                CRTCData.Byte = 0x50;

                //Horizontal Blank End
                CRTCIndex.Byte = 0x03;
                CRTCData.Byte = 0x82;


                //Set Horizontal Retrace
                CRTCIndex.Byte = 0x04;
                CRTCData.Byte = 0x54;
                //et Horizontal Retrace End
                CRTCIndex.Byte = 0x05;
                CRTCData.Byte = 0x80;

                //Set Vertical total
                CRTCIndex.Byte = 0x06;
                CRTCData.Byte = 0xBF;

                //Set the overeflow register
                CRTCIndex.Byte = 0x07;
                CRTCData.Byte = 0x1F;

                //Set the Preset Row Scan Register
                CRTCIndex.Byte = 0x08;
                CRTCData.Byte = 0x00;

                //Set the Maximum Scan Line Register
                CRTCIndex.Byte = 0x09;
                CRTCData.Byte = 0x41;

                //Disable text mode Cursor
                CRTCIndex.Byte = 0x0A;
                CRTCData.Byte = 0x20;

                //Set Cursor start to 1
                CRTCIndex.Byte = 0x0B;
                CRTCData.Byte = 0x01;

                //Set cursor location at 0
                CRTCIndex.Byte = 0x0E;
                CRTCData.Byte = 0x00;

                CRTCIndex.Byte = 0x0F;
                CRTCData.Byte = 0x00;

                //Set Vertical Retrace Start register
                CRTCIndex.Byte = 0x10;
                CRTCData.Byte = 0x9C;

                //Set Vertical Retrace End Register
                CRTCIndex.Byte = 0x11;
                CRTCData.Byte = 0x8E;


                //Set the Offset Register
                CRTCIndex.Byte = 0x13;
                CRTCData.DWord = 0x28;

                //Set the Underline Location Register
                CRTCIndex.Byte = 0x14;
                CRTCData.Byte = 0x40;

                //Set Vertical Blank Start
                CRTCIndex.Byte = 0x15;
                CRTCData.Byte = 0x96;
                //set Vertical Blank End
                CRTCIndex.Byte = 0x16;
                CRTCData.Byte = 0xB9;
                //Set the Line Compare Register
                CRTCIndex.Byte = 0x18;
                CRTCData.DWord = 0x3FF;

                GraphicsRegs = GraphicsRegs13;

                for (int i = 0; i <= 9; ++i)
                {
                    GraphicsRegsAddress.Byte = (byte)i;
                    GraphicsRegsData.Byte = GraphicsRegs[i];
                }



            }
            else
                Console.WriteLine("Error! Graphics Mode not recognized!");




        }

        // A method for clearing the screen -- inefficient
        public static void ClearScreen(uint color)
        {
            if (VGAMode == 13)
            {
                for (uint Y = 0; Y < 200; Y++)
                {
                    for (uint X = 0; X < 320; X++)
                    {
                        SetPixel(X, Y, color);
                    }
                }
            }
            else
                return;

        }

        public static void SetPixel(uint X, uint Y, uint Color)
        {
            if (VGAMode == 13)
            {
                uint offset = (Y * 320) + X;  //Correct Offset for 13H
                VGA[offset] = Color;
            }
            else
                return;


        }

        //These are my set lines functions
        public static void DrawVerticleLine(uint StartY, uint EndY, uint X, uint Color)
        {
            for (uint I = StartY; I < EndY; I++)
            {
                Graphics.SetPixel(X, I, Color);
            }
        }

        public static void DrawHorizontalLine(uint Y, uint StartX, uint EndX, uint Color)
        {
            for (uint I = StartX; I < EndX; I++)
            {
                Graphics.SetPixel(I, Y, Color);
            }
        }
    } `
![output 2](https://user-images.githubusercontent.com/26034092/30246000-6bc7f494-95a1-11e7-8f20-a50b4a52d55a.PNG)

**Comment by jp2masa** [comment]
You're using a 256 color mode, right? Then you need to use `VGA.Bytes[offset] = Color;` and `Color` has to be a `byte` instead of `uint`.

**Comment by DaveB565** [comment]
That's right! Ok! Thanks for the help. I figured it was something simple as I tried tweaking the register settings and figured that probably wasn't it. That makes sense. I think I remember this from the old VGA driver I attempted a couple years ago. Thanks again for the help! Also, is the current VBE driver complete? Is it at a useable state? If not, I will attempt to develop one of those as well for my OS.

**Comment by jp2masa** [comment]
The current VBE driver is not really VBE, it only works on Bochs, VirtualBox and QEMU.

**Comment by DaveB565** [comment]
Thanks! I know what I have to do next then! When I get this VGA driver
polished up and working correctly, how could I go about submitting it to
COSMOS? I know someone approached me about that. I would love to if the
group would want it.

**Comment by jp2masa** [comment]
To submit it, you just have to fork the repo, if you haven't already done it, then commit the changes and open a pull request.
