### ISSUE TITLE
GUI With Cosmos 

### ISSUE THREAD

**Issue by agahEbrahimi** [CosmosOS/Cosmos#765]
Hello,
Are there any tutorials on how to develop a good GUI for the OS built with the cosmos?

Thank you in advance

**Comment by KingLuigi4932** [comment]
If you want GUI, First you need to install Bochs cause our current supported graphics driver is VBE which is supported for Bochs only, VGA is supported but not adapted to CGS (Cosmos Graphics System)
For help, you can come to this chat (https://gitter.im/CosmosOS/Cosmos)

**Comment by fanoI** [comment]
Sadly our documentation on how to make a GUI is out dated (it is pre-CGS) we can use help on this too!

**Comment by agahEbrahimi** [comment]
So if I were to create a GUI with Cosmos, where would I find the documentation?

**Comment by zarlo** [comment]
https://github.com/CosmosOS/Cosmos/wiki/Cosmos-Graphic-Subsystem

**Comment by agahEbrahimi** [comment]
Thank you very much, 
I really love how fast everyone responds on this Github repo.
