### ISSUE TITLE
Unable To Build Project

### ISSUE THREAD

**Issue by vasanthdeveloper** [CosmosOS/Cosmos#769]
I have downloaded the Cosmos UserKit for Visual Studio 2015. When I create a new project and build it for the first time, it is giving the below error. I did not make any changes to the created project, but still the build is canceled.  Please help me.

`1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
1>	C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\corapi.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:07.0249427
1>Done building project "CosmosKernel2Boot.Cosmos" -- FAILED.
1>
Build has been canceled.`

**Comment by jp2masa** [comment]
Maybe the error wasn't written to the output window? In that case, you can find it in the messages in the error list.

**Comment by vasanthdeveloper** [comment]
You are right! there is an error.
The error is: Error occurred while invoking IL2CPU.
Do you know how to solve it?. Please help me?

**Comment by jp2masa** [comment]
Not that error, look at the messages and see if there's some error message there.

**Comment by vasanthdeveloper** [comment]
There are a total of 132 Messages, The first one is :

Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Vasanth Developer\documents\visual studio 2015\Projects\Kios\Kios\bin\Debug\KiosBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Vasanth Developer\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Vasanth Developer\documents\visual studio 2015\Projects\Kios\Kios\bin\Debug\Kios.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll"

**Comment by jp2masa** [comment]
Look for an exception or something like that.

**Comment by vasanthdeveloper** [comment]
No, nothing like that.

**Comment by jp2masa** [comment]
The User Kit for VS 2015 is no longer supported, and without an error message I can't do much to help you...

**Comment by vasanthdeveloper** [comment]
Okay :( Thank You.
