### ISSUE TITLE
Getting error with allowance

### ISSUE THREAD

**Issue by JR000** [CosmosOS/Cosmos#770]
Hi.
I'm quiet a beginner in COSMOS and maybe don't know something, but anyway I have a problem: when I create a new project, VS says somethin' like 'Failed to resolve "Cosmos.Debug.Kernel (>=1.0.0)" for ".NETStandard, Version=v.1.5"' or 'Failed to resolve"Cosmos.System (>=1.0.0)" for ".NETStandard, Version=v.1.5"' or even both of these things. That's why I can't even debug my project.
I've installed Visual Studio 2015 and 2017 (both Community) and tried on them all official Cosmos releases from 20150103 to the latest (userkit and devkit), but there's still no change.
I've been trying to solve this problem for a month now, but wasn't able to find correct answer. Please help me, if it is possible.

P.S.: I'm from Russia and using Russian version of the Visual Studio, so there might be problems with translation of errors (and please sorry me for my English)

**Comment by KingLuigi4932** [comment]
Are you using Dev kit or User kit

**Comment by JR000** [comment]
I've tried both of them and the problem is the same on each of them

**Comment by jp2masa** [comment]
@JR000 you should use the latest version (20170620). Make sure that the nuget feeds are configured correctly (running `nuget sources` should show a "Cosmos Local Package Feed" feed).
