### ISSUE TITLE
Debugging Problems with Slow PCs/Laptops

### ISSUE THREAD

**Issue by KingLuigi4932** [CosmosOS/Cosmos#771]
I've discovered this issue while i'm working on the AHCI Driver
The problem is (on TestRunner)
`mDebugger methods -> Console`
`All codes -> Compiler -> VMware` not sure about that
mDebugger.Send would call Console.WriteLine (for the Console)
and when your PC/Laptop get slow, Console get slow
but VMware does not, Windows thinks that Console is a thing and VMware is a thing
so
(For Example)
In the same time:
Console send a message from Debugger on line 272
VMware execute a code on line 293

This issue is not good for who use (VMware Fusion to use Windows for Cosmos) on Mac
I don't know if this issue come on regular builds
Sorry if my english is bad

**Comment by jp2masa** [comment]
This is normal. Messages are written to console when they are received, which may take more time on some cases, as messages are sent by pipe.
