### ISSUE TITLE
Error occurred while invoking IL2CPU.

### ISSUE THREAD

**Issue by Resident007** [CosmosOS/Cosmos#772]
Hi everyone, i'm trying to build my project, and I get following: 
`Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Administrator\source\repos\kernel\kernel\bin\Debug\net462\kernelBoot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Administrator\source\repos\kernel\kernel\bin\Release\net462\win7-x64\kernel.dll" 
1>C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Administrator\source\repos\kernel\kernel\bin\Debug\net462\kernelBoot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Administrator\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Administrator\source\repos\kernel\kernel\bin\Release\net462\win7-x64\kernel.dll" 
1>	Working directory = 'C:\Users\Administrator\source\repos\kernel\kernel\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.IO.FileLoadException: Could not load file or assembly 'kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>	   at Cosmos.IL2CPU.CompilerEngine.Default_Resolving(AssemblyLoadContext aContext, AssemblyName aName) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 303
1>	   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssembly(AssemblyName assemblyName)
1>	   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
1>	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
1>	   at Cosmos.IL2CPU.AssemblyLoadContextExtensions.LoadFromAssemblyCacheOrPath(AssemblyLoadContext aContext, String aFullPath) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\AssemblyLoadContextExtensions.cs:line 30
1>	   at Cosmos.IL2CPU.CompilerEngine.LoadAssemblies() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 347
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 151
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
`

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit? If you create a new project and run it, does it work?

**Comment by Resident007** [comment]
I am using the latest User kit. No, it doesn't run even if I try to build new project

**Comment by jp2masa** [comment]
Try using the Dev Kit. There were some changes on assembly resolution, but this scenario should work in the latest User Kit...

**Comment by Resident007** [comment]
Okay, I will try it. Here is my code:
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace krnl
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("OS kernel booted successfully");
        }

        protected override void Run()
        {
            Console.Write(">");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}
