### ISSUE TITLE
I cannot get Cosmos to build! Initial Program code Unchanged. 

### ISSUE THREAD

**Issue by DaveB565** [CosmosOS/Cosmos#774]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.2'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project.	CBOS3_AlphaBoot	C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.Net.Sdk\build\Microsoft.PackageDependencyResolution.targets	165	

What is causing this? Am I missing a dependency? No matter what I do I cannot get rid of it. Help would be greatly appreciated! Thanks!

**Comment by jp2masa** [comment]
We're using some "hacks" on the targets, and some things changed on .NET Core 2.0, which broke our targets. See [SUPPORT.md](https://github.com/CosmosOS/Cosmos/blob/master/SUPPORT.md) for the workaround.

**Comment by DaveB565** [comment]
Now I'm getting another error.. Line 39 of Cosmos.targets. Not much information is given. Here's the file. 
`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">  
  
  <PropertyGroup>
    <CopyBuildOutputToOutputDirectory>False</CopyBuildOutputToOutputDirectory>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <ImplicitlyExpandDesignTimeFacades>False</ImplicitlyExpandDesignTimeFacades>
    <NoStdLib>true</NoStdLib>
    <ImplicitlyExpandNETStandardFacades>False</ImplicitlyExpandNETStandardFacades>
    <DesignTimeBuild>True</DesignTimeBuild>
    <ProjectAssetsFile>NULL</ProjectAssetsFile>
  </PropertyGroup>
  
  <PropertyGroup>
    <CosmosDir Condition="$(CosmosDir) == ''">$([MSBuild]::GetRegistryValue("HKEY_LOCAL_MACHINE\Software\Cosmos", "UserKit"))</CosmosDir>
    <BuildToolsDir Condition="$(BuildToolsDir) == ''">$(CosmosDir)\Build\Tools</BuildToolsDir>
    <VSIPDir Condition="$(VSIPDir) == ''">$(CosmosDir)\Build\VSIP</VSIPDir>
    <NasmFile Condition="'$(NasmFile)' == ''">$(BuildToolsDir)\Nasm\nasm.exe</NasmFile>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">AnyCPU</PlatformTarget>
    <BinFormat Condition="$(BinFormat) == ''">bin</BinFormat>
    <CosmosBuildTaskAssemblyFile Condition="'$(CosmosBuildTaskAssemblyFile)' == ''">$(VSIPDir)\Cosmos.Build.MSBuild.dll</CosmosBuildTaskAssemblyFile>
    <AssemblySearchPaths>$(CosmosDir)\Kernel</AssemblySearchPaths>
  </PropertyGroup>
  
  <UsingTask TaskName="Cosmos.Build.MSBuild.IL2CPU" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.NAsm" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.MakeISO" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.Ld" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.ReadNAsmMapToDebugInfo" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.ExtractMapFromElfFile" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  
  <Target Name="CoreCompile">
    <Error Text="File %(Compile.Identity) is set to compile, but .Cosmos projects don't compile any source themselves!" Condition="$(Compile) != ''"/>
    <CreateProperty Value="true" Condition="$(BinFormat) == 'elf'">
      <Output PropertyName="IsELF" TaskParameter="Value"/>
    </CreateProperty>
    <CreateProperty Value="false" Condition="$(BinFormat) == 'bin'">
      <Output PropertyName="IsELF" TaskParameter="Value"/>
    </CreateProperty>
    <Cosmos.Build.MSBuild.IL2CPU DebugMode="$(DebugMode)" DebugEnabled="$(DebugEnabled)" StackCorruptionDetectionEnabled="$(StackCorruptionDetectionEnabled)" StackCorruptionDetectionLevel="$(StackCorruptionDetectionLevel)" TraceAssemblies="$(TraceAssemblies)" IgnoreDebugStubAttribute="$(IgnoreDebugStubAttribute)" DebugCom="1" UseNAsm="true" References="@(ReferencePath)" OutputFilename="$(TargetDir)$(MSBuildProjectName).asm" EnableLogging="true" EmitDebugSymbols="$(DebugSymbols)" CosmosBuildDir="$(CosmosDir)\Build" WorkingDir="$(TargetDir)"/>
    <Cosmos.Build.MSBuild.NAsm InputFile="$(TargetDir)$(MSBuildProjectName).asm" OutputFile="$(TargetDir)$(MSBuildProjectName).obj" IsELF="$(IsELF)" ExePath="$(NasmFile)"/>
    
    
    <Cosmos.Build.MSBuild.Ld CosmosBuildDir="$(CosmosDir)\Build" WorkingDir="$(TargetDir)" Arguments="-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o '$(TargetDir)$(MSBuildProjectName).bin' '$(TargetDir)$(MSBuildProjectName).obj'" Condition="$(IsELF) == 'true'"/>
    <Cosmos.Build.MSBuild.ExtractMapFromElfFile InputFile="$(TargetDir)$(MSBuildProjectName).bin" DebugInfoFile="$(TargetDir)$(MSBuildProjectName).cdb" WorkingDir="$(TargetDir)" CosmosBuildDir="$(CosmosDir)\Build" Condition="$(IsELF) == 'true'"/>
    <CreateItem Include="$(TargetDir)$(MSBuildProjectName).bin" Condition="$(IsELF) == 'true'">
      <Output TaskParameter="Include" ItemName="TempFilesToCopy"/>
    </CreateItem>
    
    
    <Cosmos.Build.MSBuild.ReadNAsmMapToDebugInfo InputBaseDir="$(TargetDir)" DebugInfoFile="$(TargetDir)$(MSBuildProjectName).cdb" Condition="$(IsELF) == 'false'"/>
    <Move SourceFiles="$(TargetDir)$(MSBuildProjectName).obj" DestinationFiles="$(TargetDir)$(MSBuildProjectName).bin" Condition="$(IsELF) == 'false'"/>
    
    
    
    <Delete Files="$(TargetDir)$(MSBuildProjectName).iso"/>
  </Target>
  
  <Target Name="CreateManifestResourceNames" />
  
</Project>
`

**Comment by DaveB565** [comment]
Now I'm getting another error on line 39 of the Targets file. Here it is.

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">  
  
  <PropertyGroup>
    <CopyBuildOutputToOutputDirectory>False</CopyBuildOutputToOutputDirectory>
    <DisableImplicitFrameworkReferences>True</DisableImplicitFrameworkReferences>
    <ImplicitlyExpandDesignTimeFacades>False</ImplicitlyExpandDesignTimeFacades>
    <NoStdLib>true</NoStdLib>
    <ImplicitlyExpandNETStandardFacades>False</ImplicitlyExpandNETStandardFacades>
    <DesignTimeBuild>True</DesignTimeBuild>
    <ProjectAssetsFile>NULL</ProjectAssetsFile>
  </PropertyGroup>
  
  <PropertyGroup>
    <CosmosDir Condition="$(CosmosDir) == ''">$([MSBuild]::GetRegistryValue("HKEY_LOCAL_MACHINE\Software\Cosmos", "UserKit"))</CosmosDir>
    <BuildToolsDir Condition="$(BuildToolsDir) == ''">$(CosmosDir)\Build\Tools</BuildToolsDir>
    <VSIPDir Condition="$(VSIPDir) == ''">$(CosmosDir)\Build\VSIP</VSIPDir>
    <NasmFile Condition="'$(NasmFile)' == ''">$(BuildToolsDir)\Nasm\nasm.exe</NasmFile>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">AnyCPU</PlatformTarget>
    <BinFormat Condition="$(BinFormat) == ''">bin</BinFormat>
    <CosmosBuildTaskAssemblyFile Condition="'$(CosmosBuildTaskAssemblyFile)' == ''">$(VSIPDir)\Cosmos.Build.MSBuild.dll</CosmosBuildTaskAssemblyFile>
    <AssemblySearchPaths>$(CosmosDir)\Kernel</AssemblySearchPaths>
  </PropertyGroup>
  
  <UsingTask TaskName="Cosmos.Build.MSBuild.IL2CPU" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.NAsm" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.MakeISO" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.Ld" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.ReadNAsmMapToDebugInfo" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  <UsingTask TaskName="Cosmos.Build.MSBuild.ExtractMapFromElfFile" AssemblyFile="$(CosmosBuildTaskAssemblyFile)"/>
  
  <Target Name="CoreCompile">
    <Error Text="File %(Compile.Identity) is set to compile, but .Cosmos projects don't compile any source themselves!" Condition="$(Compile) != ''"/>
    <CreateProperty Value="true" Condition="$(BinFormat) == 'elf'">
      <Output PropertyName="IsELF" TaskParameter="Value"/>
    </CreateProperty>
    <CreateProperty Value="false" Condition="$(BinFormat) == 'bin'">
      <Output PropertyName="IsELF" TaskParameter="Value"/>
    </CreateProperty>
    <Cosmos.Build.MSBuild.IL2CPU DebugMode="$(DebugMode)" DebugEnabled="$(DebugEnabled)" StackCorruptionDetectionEnabled="$(StackCorruptionDetectionEnabled)" StackCorruptionDetectionLevel="$(StackCorruptionDetectionLevel)" TraceAssemblies="$(TraceAssemblies)" IgnoreDebugStubAttribute="$(IgnoreDebugStubAttribute)" DebugCom="1" UseNAsm="true" References="@(ReferencePath)" OutputFilename="$(TargetDir)$(MSBuildProjectName).asm" EnableLogging="true" EmitDebugSymbols="$(DebugSymbols)" CosmosBuildDir="$(CosmosDir)\Build" WorkingDir="$(TargetDir)"/>
    <Cosmos.Build.MSBuild.NAsm InputFile="$(TargetDir)$(MSBuildProjectName).asm" OutputFile="$(TargetDir)$(MSBuildProjectName).obj" IsELF="$(IsELF)" ExePath="$(NasmFile)"/>
    
    
    <Cosmos.Build.MSBuild.Ld CosmosBuildDir="$(CosmosDir)\Build" WorkingDir="$(TargetDir)" Arguments="-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o '$(TargetDir)$(MSBuildProjectName).bin' '$(TargetDir)$(MSBuildProjectName).obj'" Condition="$(IsELF) == 'true'"/>
    <Cosmos.Build.MSBuild.ExtractMapFromElfFile InputFile="$(TargetDir)$(MSBuildProjectName).bin" DebugInfoFile="$(TargetDir)$(MSBuildProjectName).cdb" WorkingDir="$(TargetDir)" CosmosBuildDir="$(CosmosDir)\Build" Condition="$(IsELF) == 'true'"/>
    <CreateItem Include="$(TargetDir)$(MSBuildProjectName).bin" Condition="$(IsELF) == 'true'">
      <Output TaskParameter="Include" ItemName="TempFilesToCopy"/>
    </CreateItem>
    
    
    <Cosmos.Build.MSBuild.ReadNAsmMapToDebugInfo InputBaseDir="$(TargetDir)" DebugInfoFile="$(TargetDir)$(MSBuildProjectName).cdb" Condition="$(IsELF) == 'false'"/>
    <Move SourceFiles="$(TargetDir)$(MSBuildProjectName).obj" DestinationFiles="$(TargetDir)$(MSBuildProjectName).bin" Condition="$(IsELF) == 'false'"/>
    
    
    
    <Delete Files="$(TargetDir)$(MSBuildProjectName).iso"/>
  </Target>
  
  <Target Name="CreateManifestResourceNames" />
  
</Project>

**Comment by DaveB565** [comment]
[New Text Document.txt](https://github.com/CosmosOS/Cosmos/files/1327663/New.Text.Document.txt)

**Comment by jp2masa** [comment]
Check the output window.

**Comment by DaveB565** [comment]
All it's saying is error while invoking IL2CPU. Line 39. No other
information is given. I'm stuck!

**Comment by DaveB565** [comment]
Nevermind! I just found this:

Severity Code Description Project File Line Suppression State
Message  Invoking il2cpu.exe "DebugEnabled:True"
"StackCorruptionDetectionEnabled:False"
"StackCorruptionDetectionLevel:AllInstructions" "DebugMode:Source"
"TraceAssemblies:" "DebugCom:1" "UseNAsm:True"
"OutputFilename:C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\bin\Debug\net462\CBOS3_AlphaBoot.asm"
"EnableLogging:True" "EmitDebugSymbols:True"
"IgnoreDebugStubAttribute:False"
"References:C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\bin\Debug\netstandard2.0\CBOS3_Alpha.dll"
"References:C:\Users\David\AppData\Roaming\Cosmos User
Kit\Kernel\Cosmos.Core.Plugs.Asm.dll"
"References:C:\Users\David\AppData\Roaming\Cosmos User
Kit\Kernel\Cosmos.Core.Plugs.dll"
"References:C:\Users\David\AppData\Roaming\Cosmos User
Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll"
"References:C:\Users\David\AppData\Roaming\Cosmos User
Kit\Kernel\Cosmos.System.Plugs.dll" CBOS3_AlphaBoot  0

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit?

**Comment by DaveB565** [comment]
The User Kit.

**Comment by jp2masa** [comment]
Then why is the kernel targeting `netstandard2.0`?

**Comment by DaveB565** [comment]
That may have been me. What should it be?

**Comment by jp2masa** [comment]
`netstandard1.5`

**Comment by DaveB565** [comment]
Yahoo! Thanks for the help. Will the error I got before be fixed in the
next release? If so, do you have any idea when that will be? Thanks!

**Comment by jp2masa** [comment]
In the next release we will probably be using CPS, so we won't need any hack on targets. It's going to take some time until the next release I think.

**Comment by DaveB565** [comment]
Ok! Good enough. Thanks for the help. Good luck! One thing.. I'm interested in re-booting the Open Cosmos Aliance. How could I go about doing that?
