### ISSUE TITLE
Using Rings in VS2017? I cannot access refrences!

### ISSUE THREAD

**Issue by DaveB565** [CosmosOS/Cosmos#776]
Here's a screenshot. What do I do now?
![references](https://user-images.githubusercontent.com/26034092/30787335-d499ccb4-a13a-11e7-83ab-b122ef37bd13.PNG)

**Comment by jp2masa** [comment]
What's the problem?

**Comment by DaveB565** [comment]
The problem is, my VGA driver requires access to the hardware Ring. The
Kernel operates in the User ring. According to the guide on the wiki,
changing Rings requires access to the references. There is no visible way
to do that on my copy of VS2017. My question is, how do I do this? Thanks.

**Comment by jp2masa** [comment]
You can install the NuGet packages.

**Comment by DaveB565** [comment]
What NuGet Packages will I need? Sorry. I'm very new to VS2017 and honestly have no clue what I'm doing.

**Comment by jp2masa** [comment]
`Cosmos.System`, and `Cosmos.HAL` if you are using the Dev Kit.

**Comment by DaveB565** [comment]
I'm using the User Kit. This is probably obvious, but I don't have a clue. Thanks.

**Comment by DaveB565** [comment]
My main question is, how do I access which Ring I am in? In vs 2015 it was relatively straight forward.

**Comment by jp2masa** [comment]
Just add an assembly attribute to one of the .cs files, like this:
```cs
[assembly:Ring(Ring.System)]
```

**Comment by DaveB565** [comment]
Oh, so it's actually easier! Thank you! I appreciate the help. Could you maybe update the wiki? This would be greatly appreciated.

**Comment by jp2masa** [comment]
Rings are currently disabled in the Dev Kit, because they are being upgraded, so I think it's not really worth to update the wiki.

**Comment by DaveB565** [comment]
Oh really? Sounds like the next release is going to be a big update then! I have another question. My VGA driver relies on IOPort. As it stands now, IOPort is not recognized by the system. What is that under?

**Comment by jp2masa** [comment]
Core, so you will need to implement the driver in HAL and integrate it with the CGS in System.

**Comment by DaveB565** [comment]
H,,. That's how I implemented it.  Ok! Thanks for that. It's under Cosmos.Core.Common. Before it was under Cosmos.Core. Ok! Now I think I have all the little bugs fixed. Thanks allot!
