### ISSUE TITLE
Error while trying to use an array

### ISSUE THREAD

**Issue by DaveB565** [CosmosOS/Cosmos#777]
The error reads : C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\bin\Debug\net462\CBOS3_AlphaBoot.asm:185059: error: comma, colon, decorator or end of line expected after operand	CBOS3_AlphaBoot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	40	
Error: No SourceInfos found!	CBOS3_AlphaBoot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	50	

Here is the targets file
[Cosmos.txt](https://github.com/CosmosOS/Cosmos/files/1335449/Cosmos.txt)

And the code causing the error
It's just these 3 lines where declare a global byte array and attempt to access it
                                                                                                
`private static byte[,,] WindowBackground { get; set; } = new byte[320, 240, 256];`
     
`byte XY = Graphics.GetPixel(InitX + X, InitY + Y);`
`WindowBackground[X, Y, WindowID] = XY;`

**Comment by fanoI** [comment]
It should not be:
```cs
private static byte[,,,] WindowBackground { get; set; } = new byte[320, 240, 256];
```
?

**Comment by DaveB565** [comment]
Why would it cause that though? An error in the targets file. Thanks for
dealing with my stupidity. What should it be?

**Comment by jp2masa** [comment]
Multidimensional arrays aren't supported, use jagged arrays instead.

**Comment by DaveB565** [comment]
That explains that. Sorry for the inconveiniance. I'm sure me declaration
is probably not quite right either. I will change it up! Thanks for the
information.

**Comment by DaveB565** [comment]
Well I got rid of those three lines, and the error persists! Could someone take a look at that targets file?

**Comment by jp2masa** [comment]
The problem is not the targets file, the compilation is failing for some reason. Try rebuilding the project. If it doesn't work, look at the output window and see what's the error.

**Comment by DaveB565** [comment]
Here are the errors. The messages window is the same, no more information. Is it IL2CPU?
Error occurred while invoking NAsm.	CBOS3_AlphaBoot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	40

Error:  C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\bin\Debug\net462\CBOS3_AlphaBoot.asm:185059: error: comma, colon, decorator or end of line expected after operand	CBOS3_AlphaBoot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	40	

Error: 
[Cosmos.txt](https://github.com/CosmosOS/Cosmos/files/1339023/Cosmos.txt)
No SourceInfos found!	CBOS3_AlphaBoot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	50

**Comment by DaveB565** [comment]
Now I'm getting a slightly different error.. Here is the output window.

	Executing IL2CPU on assembly
1>	Error: Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SystemAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
1>	   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
1>	   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
1>	   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
1>	   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
1>	   --- End of inner exception stack trace ---
1>	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
1>	   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
1>	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
1>	   at Cosmos.Debug.Symbols.ModuleExtensions.Invoke[T](MethodInfo method, Module module, Object[] args) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.Debug.Symbols\ModuleExtensions.cs:line 35
1>	   at Cosmos.Debug.Symbols.ModuleExtensions.ResolveMethod(Module module, Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.Debug.Symbols\ModuleExtensions.cs:line 22
1>	   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILReader.cs:line 331
1>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 565
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 694
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>	Loaded assemblies: 
1>	C:\Users\David\source\repos\CBOS3_Alpha\CBOS3_Alpha\bin\Debug\netstandard1.5\CBOS3_Alpha.dll
1>	C:\Users\David\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
1>	C:\Users\David\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	C:\Users\David\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	C:\Users\David\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='AllInstructions', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:03.7961219
1>Done building project "CBOS3_AlphaBoot.Cosmos" -- FAILED.

**Comment by DaveB565** [comment]
Sorry to be a pain, but I switched to the new user kit. Now I'm getting a new error. I can't transition into the System ring for some reason! Although, I can transition into the Hal ring? Below is the code.
`using Cosmos.Com

[assembly: Ring(Ring.System)]

mon;
[assembly: Ring(Ring.System)]

namespace CBOS_API
{
    public class SysGUI
    {
         //Draw Rectangular Buttons

        //Draw Circular Buttons

        //Progress Bar --Verticle, and Horizontal

        //Circular Progress Bar

        //TextBoxes

        //Check Box

        //List Box

        //Button Struct

        
    }
}`

This is the code for the Hal ring
`using Cosmos.Common;
using System;
using Cosmos.Core;
using Cosmos.Core.Common;
[assembly: Ring(Ring.HAL)]

namespace Hardware
{
    // This VGA driver is intended to be used with the COSMOS operating system kit. 
    public class Graphics
    {
            
        private static MemoryBlock VGA = new MemoryBlock(0xA0000, 128000);
        private static int VGAMode;
.....`

I don't understand this...

**Comment by jp2masa** [comment]
Are you getting any error?

**Comment by DaveB565** [comment]
Error while invoking il2cpu yes. Due to the fact that it's staying in the
user ring.

**Comment by DaveB565** [comment]
I just can't figure out why it's staying in the user ring after I clearly shift into the system ring? Am I doing something wrong? Thanks.

**Comment by DaveB565** [comment]
OK! UPDATE: I've gotten rid of that error, but now I'm back to this one:
Error:		Error occurred while invoking IL2CPU.	CBOS_Alpha 1Boot	C:\Users\David\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	39

Error: Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SysAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.	CBOS_Alpha 1Boot		0	

What is causing this? I can't figure it out.

**Comment by DaveB565** [comment]
Wow... Problem solved... I forgot to add the projects as a reference to the main boot project... I'm an idiot. I apologize for all this! Thanks for the help! I am much more familiar with Cosmos now and VS2017 too for that matter. Thanks allot! Hopefully this is the last issue I face.
