### ISSUE TITLE
Can't set up cosmos

### ISSUE THREAD

**Issue by sntdevco** [CosmosOS/Cosmos#781]
I have VS2017. Now I had installed cosomos but as soon as I create a new C# OS - I get several errors including - System.Console not found & a hundred similar ones.

**Comment by LegitSoulja** [comment]
https://github.com/CosmosOS/Cosmos/issues/758

**Comment by dsdude123** [comment]
Assuming you're a userkit user, feel free to correct me:

1) Make sure you're using the newest userkit, the most recent release from two days ago has some important fixes that might resolve your issue. https://github.com/CosmosOS/Cosmos/releases/tag/Userkit_20170928

2) Make sure you have enabled "Save new projects when created" as noted in #758

**Comment by Arawn-Davies** [comment]
The 'save new projects when created' issue was fixed in commit https://github.com/CosmosOS/Cosmos/commit/3dbb8678c49e14934ec9525d53b716ca4231534a, clone the latest devkit (if you want to use it) to use this or if you're using the userkit enable the option mentioned above
