### ISSUE TITLE
Where do I place the cloned repos?

### ISSUE THREAD

**Issue by sntdevco** [CosmosOS/Cosmos#784]
I cloned the Xsharp, Cosmos & IL2CPU repos to my local disk. Now how do I register this in THE VS2017 extension and what an I supposed to do with these files?

**Comment by AlvaroD1902x** [comment]
Are you installing the DevKit?

**Comment by AlvaroD1902x** [comment]
Try this method, but first extract everything first.

- Rename the folders
    - Rename "XSharp-master" to "XSharp"
    - Rename "IL2CPU-master" to "IL2CPU"
    - Rename "Cosmos-master" to "Cosmos"

- Move the folders
    - Move "XSharp" to your choosen location
    - Move "Cosmos" to your choosen location
    - Move "IL2CPU" to your choosen location

- Installation
    - For UserKit, run "install userkit.bat"
    - For DevKit, run "install-VS2017.bat"

If installation fails, check if one of those softwares are installed
- Visual Studio Workloads : .NET Core Tools 
- Visual Studio Workloads : Visual Studio Extension Development
- .NET Framework v4.6.2
- .NET Core v2.0.0
- Inno Setup with Preprocessor Add-on

I'm also a beginner of cosmos, so I might be wrong.

**Comment by sntdevco** [comment]
Where is the executable (.bat : batch) file?

**Comment by AlvaroD1902x** [comment]
Inside the Cosmos Folder

**Comment by sntdevco** [comment]
The repo or the installation folder?

**Comment by AlvaroD1902x** [comment]
Installation Folder

**Comment by sntdevco** [comment]
Ohk

**Comment by AlvaroD1902x** [comment]
You may close this issues if it worked

**Comment by sntdevco** [comment]
Didn't help! @AlvaroD1902x

**Comment by AlvaroD1902x** [comment]
Is there an error?

**Comment by zarlo** [comment]
if you have python you can use https://github.com/zarlo/GitScripts/blob/master/Cosmos/Update.py

**Comment by LegitSoulja** [comment]
Make a folder anywhere called cosmos or whatever.

Clone the 3 repos in the directory

Open the cloned cosmos folder and run install2017.bat (Dev Kit). It'll install the User Kit afterwards. Once things are doing VS will start automatically with a demo project. 

You're done.
