### ISSUE TITLE
Getting an error when creating a new project

### ISSUE THREAD

**Issue by sntdevco** [CosmosOS/Cosmos#785]
Error list:
Error        CS0115	'Kernel.BeforeRun()': no suitable method found to override	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	10	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	1	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	2	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	3	Active
Error	CS0246	The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	4	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	10	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	15	Active
Error	CS0115	'Kernel.Run()': no suitable method found to override	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	15	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	12	Active
Error	CS0103	The name 'Console' does not exist in the current context	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	12	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	12	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	17	Active
Error	CS0103	The name 'Console' does not exist in the current context	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	17	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	17	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	18	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	18	Active
Error	CS0103	The name 'Console' does not exist in the current context	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	18	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	19	Active
Error	CS0103	The name 'Console' does not exist in the current context	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	19	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	19	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	20	Active
Error	CS0103	The name 'Console' does not exist in the current context	OS	C:\Users\USER\Documents\Visual Studio 2017\Projects\OS\OS\Kernel.cs	20	Active

**Comment by sntdevco** [comment]
Now what?

**Comment by fanoI** [comment]
But you have Net Core 2.0 installed? It should be called "Net Core workload" on Visual Studio...

**Comment by sntdevco** [comment]
I have it installed. @fanol

**Comment by jp2masa** [comment]
The .NET Core 2.0 SDK has to be installed separately. It's not included in the VS installation.

**Comment by fanoI** [comment]
If you try to do a new Net Core 2 project (a simple Console application) it works?

**Comment by LegitSoulja** [comment]
He should use the latest release and install dev kit, but the kernel isn't even loading now :/

**Comment by Arawn-Davies** [comment]
Are the nuget packages being restored?

**Comment by LegitSoulja** [comment]
@Arawn-Davies I think this is fixed. He just needs to update his repos.

**Comment by Arawn-Davies** [comment]
@sntdevco is this issue able to be closed now?
