### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#791]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installer

#### Expected Behaviour - What do you want to happen?
Cosmos to install

#### Actual behaviour - What unexpectedly happens?
The error appears: 
`Console returned exit code. (0x00000001)`
`  at Cosmos.Build.Installer.Task.StartConsole(String aExe, String aParams)`
and a lot more.

#### Reproduction - How did you get this error to appear?
I installed.

#### Version information - Were you using the Userkit or Devkit? And what userkit version or devkit commit?
Latest devkit.

**Comment by jp2masa** [comment]
Can you copy the log to pastebin?

**Comment by Project-Magenta** [comment]
https://pastebin.com/x8yALfRd

**Comment by jp2masa** [comment]
You need to install .NET Core 2.0 SDK: https://www.microsoft.com/net/download/core
