### ISSUE TITLE
C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Aura Operating System\Aura OS\Aura_OSBoot.Cosmos : error  : The imported project "C:\Users\ray6y\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Aura Operating System\Aura OS\Aura_OSBoot.Cosmos

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#792]
#### Area of Cosmos - What area of Cosmos are we dealing with?
VS2017 integration

#### Expected Behaviour - What do you want to happen?
The project to build

#### Actual behaviour - What unexpectedly happens?
it shows
`C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Aura Operating System\Aura OS\Aura_OSBoot.Cosmos : error  : The imported project "C:\Users\ray6y\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Aura Operating System\Aura OS\Aura_OSBoot.Cosmos`

#### Reproduction - How did you get this error to appear?
I opened a downloaded os

#### Version information - Were you using the Userkit or Devkit? And what userkit version or devkit commit?
latest devkit

**Comment by jp2masa** [comment]
Did you install the Dev Kit in other user account?

**Comment by Project-Magenta** [comment]
no

**Comment by Arawn-Davies** [comment]
The devkit and userkit needs to be installed on each user account that uses Cosmos, because the files are copied to AppData, which isn't usually accessible by other user accounts.

**Comment by Project-Magenta** [comment]
Sorry, it was because I had normal Cosmos, not aura cosmos
