### ISSUE TITLE
Nuget Package Restore Failed

### ISSUE THREAD

**Issue by Project-Magenta** [CosmosOS/Cosmos#793]
#### Expected Behaviour - What do you think that should happen?
Project compiles.

#### Actual Behaviour - What unexpectedly happens?
It looks like the 'Cosmos Package Feed' does not exist.
'Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet package restore failed.
1>------ Build started: Project: Users, Configuration: Debug Any CPU ------
1>C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Users\Users\Users.csproj : error NU1101: Unable to find package Cosmos.Debug.Kernel. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
1>C:\Users\ray6y\Documents\Visual Studio 2017\Projects\Users\Users\Users.csproj : error NU1101: Unable to find package Cosmos.System. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
1>Kernel.cs(4,13,4,19): error CS0246: The type or namespace name 'Cosmos' could not be found (are you missing a using directive or an assembly reference?)
1>Kernel.cs(10,33,10,42): error CS0115: 'Kernel.BeforeRun()': no suitable method found to override
1>Kernel.cs(15,33,15,36): error CS0115: 'Kernel.Run()': no suitable method found to override
1>Done building project "Users.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped =========='

#### Reproduction - How did you get this error to appear?
Make a new OS

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Dev Kit

**Comment by jp2masa** [comment]
Try reinstalling the Dev Kit.

**Comment by Project-Magenta** [comment]
OK.

**Comment by Project-Magenta** [comment]
😄 😺

**Comment by hubabuba444** [comment]
in the user kit set what to do because I see error NU1101
