### ISSUE TITLE
How to reboot the system?

### ISSUE THREAD

**Issue by ferdinand-lanvino** [CosmosOS/Cosmos#794]

**Comment by valentinbreiz** [comment]
Just use Cosmos.System.Reboot(); ;)

**Comment by DaveB565** [comment]
I'm curious about shutting down the system. Has that been implemented yet?

**Comment by jp2masa** [comment]
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/Power.cs#L15

**Comment by fanoI** [comment]
Please do not open issues only for questions use the gitter chat for this.

Thank you!

**Comment by ferdinand-lanvino** [comment]
I'm using older version of Cosmos, I've managed it using a reboot code from ACPI :)
