### ISSUE TITLE
Error installing COSMOS

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#795]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installing

#### Expected Behaviour - What do you think that should happen?
It installs

#### Actual Behaviour - What unexpectedly happens?
It doesn't install
Restore NuGet Packages is red

#### Reproduction - How did you get this error to appear?
Ran install-VS2017.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Dev Kit. I just downloaded the .zip file from the home page.

Output:
https://pastebin.com/Dq0Q2VVE

**Comment by zarlo** [comment]
you need to download IL2CPU and X# too

**Comment by IanSteg** [comment]
Where do I download these?

**Comment by zarlo** [comment]
https://github.com/CosmosOS/IL2CPU
https://github.com/CosmosOS/XSharp

**Comment by valentinbreiz** [comment]
Here https://github.com/CosmosOS/IL2CPU and here https://github.com/CosmosOS/XSharp

**Comment by IanSteg** [comment]
Where do I put them?

**Comment by jp2masa** [comment]
Clone them in parallel. There are installation docs in the website.

**Comment by valentinbreiz** [comment]
In the same folder put /Cosmos, /XSharp and /IL2CPU folders. Then, in the Cosmos folder run install-2017.bat

**Comment by Arawn-Davies** [comment]
Can this issue be closed? I'll add a notice to tell people to clone each repository, as this isn't an issue with Cosmos itself

**Comment by Arawn-Davies** [comment]
You can check out this script to update your sources as updates are released to the repo: https://github.com/zarlo/GitScripts/blob/master/Cosmos/Update.py

**Comment by IanSteg** [comment]
Ok, now it's erroring at "Build Cosmos" when I run install-VS2017

https://pastebin.com/QkHWgrqk

**Comment by jp2masa** [comment]
You need to install the .NET Core 2.0 SDK. If you update Visual Studio to version 15.4, it's already included.

**Comment by IanSteg** [comment]
still errors

https://pastebin.com/aLwzqTvF

**Comment by jp2masa** [comment]
You need to update VS.

**Comment by IanSteg** [comment]
That fixed it.
