### ISSUE TITLE
Error Compiling OS

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#796]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling

#### Expected Behaviour - What do you think that should happen?
It compiles

#### Actual Behaviour - What unexpectedly happens?
Error in file Cosmos.targets

#### Reproduction - How did you get this error to appear?
Tried building OS

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Dev Kit

Error Message:
https://pastebin.com/vN9EyXLt

**Comment by zarlo** [comment]
reinstall Cosmos should fix this

**Comment by IanSteg** [comment]
Still get the error.

**Comment by jp2masa** [comment]
Are you using the latest Dev Kit?

**Comment by IanSteg** [comment]
Yeah, I downloaded and reinstalled it.

**Comment by jp2masa** [comment]
Did you pull latest from IL2CPU and XSharp too?

**Comment by IanSteg** [comment]
Yep.

**Comment by jp2masa** [comment]
Uninstall the Cosmos extension in VS, then install it from "%appdata%\Cosmos User Kit\VSIX\Cosmos.ProjectSystem.vsix"

**Comment by IanSteg** [comment]
Still getting the error.

**Comment by jp2masa** [comment]
I tried to fix the error a few weeks ago, and no more issues were reported since then, but it seems that it's still not working. I'll investigate it.

**Comment by jodogger** [comment]
Finally, after getting everything else fixed and compiling, I am getting this as well when trying to run a new C# Operating System project, no changes.
Tried uninstalling Cosmos extension and installing from "%appdata%\Cosmos User Kit\VSIX\Cosmos.VS.ProjectSystem.vsix" location.

**Comment by jp2masa** [comment]
We are aware of this issue and we're trying to fix it, but it's a bit hard. `e_sqlite3.dll` ships with all assemblies that depend on it, but it's not working for some reason.

**Comment by jodogger** [comment]
Is there a work-around for this issue. Still cannot build basic kernel. I have just pulled latest.

**Comment by jodogger** [comment]
This issue is fixed with latest.

**Comment by IanSteg** [comment]
Yep, cloned latest and works.
