### ISSUE TITLE
[QUESTION] About the Console and fonts...

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#797]
As the title says, I want to know whether or not and where I can somehow change fonts in the console. Not VGA, just console.

Now, I have found something in the devkit kernel in the VGAScreen class that looks like arrays of hexadecimal numbers, representing bitmap fonts (simply turned into binary would view ones in place of pixels and zeros in place of "spaces"). I tried replacing it with my own version of the fonts (just the capital A-Z, "drawn" in a 8x8 grid with ones and zeros , including leading zeros, just like the ones in the byte array) written as hexadecimal numbers. This however did nothing, and the default fonts still appeared.

**Comment by jp2masa** [comment]
It's possible to change fonts in VGA text mode, but it's not currently implemented.

**Comment by 365Tito** [comment]
@jp2masa 
I also read somewhere that fonts were hard coded.
Could I change them somewhere in the code of the devkit?

**Comment by jp2masa** [comment]
I think that fonts are hardcoded in the VGA driver (not text mode).

**Comment by 365Tito** [comment]
I see. Thank you.
So how could I for example write a string on the VGA Screen?

**Comment by jp2masa** [comment]
The VGA driver doesn't work I think. It needs to be ported to CGS, but it's not really important, as it only supports low resolutions.

**Comment by 365Tito** [comment]
So there is virtually no possible way to change the standard console font?
If so, then thank you for your help :)

**Comment by jp2masa** [comment]
The only way would be adding custom fonts to the VGA text mode implementation.

**Comment by 365Tito** [comment]
Hmm... sorry for the late response but... I don't really know how to handle the VGA part.
Really I tried everything. And I ran it on Bochs and I got some weird ATA error that it can't find the hard disk or something... I have no idea how to fix that :(

**Comment by jp2masa** [comment]
You need to delete the lock file.

**Comment by 365Tito** [comment]
Thanks! It finally worked! :)
