### ISSUE TITLE
Error checking properties.

### ISSUE THREAD

**Issue by BaRRaKudaRain** [CosmosOS/Cosmos#798]
I am using last user kit. I have a problem with a XXX_myOS_XXXboot. If I want to check a properties of this he's saying this:
An error occurred trying to load the page.
Exception has been thrown by the target of an invocation.

**Comment by jp2masa** [comment]
Uninstall the Cosmos VS extension, then reinstall the User Kit.

**Comment by BaRRaKudaRain** [comment]
Thx, helped.
