### ISSUE TITLE
Compile Error OS

### ISSUE THREAD

**Issue by StartForKillerMC** [CosmosOS/Cosmos#799]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling

#### Expected Behaviour - What do you think that should happen?
It compiles

#### Actual Behaviour - What unexpectedly happens?
Error in file Cosmos.targets

#### Reproduction - How did you get this error to appear?
Tried building OS

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
User Kit, the last version.

Error		An error occurred: System.Exception: Error extracting map from C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.bin
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.RunObjDump(String cosmosBuildDir, String workingDir, String inputFile, Action`1 errorReceived, Action`1 outputReceived)
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.Execute()	CosmosKernel3Boot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44

**Comment by jp2masa** [comment]
That's the full log?

**Comment by StartForKillerMC** [comment]
no:

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		An error occurred: System.Exception: Error extracting map from C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.bin
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.RunObjDump(String cosmosBuildDir, String workingDir, String inputFile, Action`1 errorReceived, Action`1 outputReceived)
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.Execute()	CosmosKernel3Boot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Error		Error occurred while invoking objdump.	CosmosKernel3Boot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Error		El sistema no puede encontrar la ruta especificada.	CosmosKernel3Boot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Mensaje		Rings: Assembly 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		NAsm task took 00:00:11.0049841	CosmosKernel3Boot		0	
Mensaje		Loaded : TraceAssemblies	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = HAL	CosmosKernel3Boot		0	
Mensaje		Ld task took 00:00:01.2025975	CosmosKernel3Boot		0	
Mensaje		Loaded : AdditionalReferences	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = HAL	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.LOCAL_ARGUMENT_INFO'	CosmosKernel3Boot		0	
Mensaje		Executed OK	CosmosKernel3Boot		0	
Mensaje		Rings: Start check	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.System'	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Memory'	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		IL2CPU task took 00:00:35.1221566	CosmosKernel3Boot		0	
Mensaje		Working directory = 'C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.System.Plugs'	CosmosKernel3Boot		0	
Mensaje		Loaded : AdditionalSearchDirs	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Executing command line "C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\tools\cygwin\ld.exe" -Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o 'C:/Users/Jesús/source/repos/CosmosKernel3/CosmosKernel3/bin/Debug/net462/CosmosKernel3Boot.bin' 'C:/Users/Jesús/source/repos/CosmosKernel3/CosmosKernel3/bin/Debug/net462/CosmosKernel3Boot.obj'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = System	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.Core'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Loaded : UseNAsm	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = HAL	CosmosKernel3Boot		0	
Mensaje		Loaded : StackCorruptionDetectionLevel	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.INT3Label'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = User	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		Loaded : DebugEnabled	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.System'	CosmosKernel3Boot		0	
Mensaje		Working directory = 'C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\'	CosmosKernel3Boot		0	
Mensaje		Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\netstandard1.5\CosmosKernel3.dll"	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.HAL'	CosmosKernel3Boot		0	
Mensaje		Loaded : StackCorruptionDetectionEnabled	CosmosKernel3Boot		0	
Mensaje		Executing IL2CPU on assembly	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = System	CosmosKernel3Boot		0	
Mensaje		Loaded : EnableLogging	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.Document'	CosmosKernel3Boot		0	
Mensaje		Extracting Map file took 00:00:00.7049855	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Plugs'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = System	CosmosKernel3Boot		0	
Mensaje		Loaded : IgnoreDebugStubAttribute	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Plugs.Asm'	CosmosKernel3Boot		0	
Mensaje		Loaded : DebugCom	CosmosKernel3Boot		0	
Mensaje		Loaded : DebugMode	CosmosKernel3Boot		0	
Mensaje		Loaded : EmitDebugSymbols	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'Cosmos.HAL'	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = Core	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	CosmosKernel3Boot		0	
Mensaje		Loaded : OutputFilename	CosmosKernel3Boot		0	
Mensaje		IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.HAL'	CosmosKernel3Boot		0	
Mensaje		Loaded : References	CosmosKernel3Boot		0	
Mensaje		Rings: Assembly 'CosmosKernel3'	CosmosKernel3Boot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.Method'	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Memory'	CosmosKernel3Boot		0	
Mensaje		Executing command line "C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\net462\CosmosKernel3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Jesús\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\netstandard1.5\CosmosKernel3.dll"	CosmosKernel3Boot		0	
Mensaje		Rings:         Ring = System	CosmosKernel3Boot		0	
Mensaje		Rings:     Dependency 'Cosmos.System'	CosmosKernel3Boot		0

**Comment by jp2masa** [comment]
Probably the problem is the `ú` char in the path. Try creating a project in a path without special chars.

**Comment by StartForKillerMC** [comment]
thanks

**Comment by StartForKillerMC** [comment]
nop it don´t works

**Comment by StartForKillerMC** [comment]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		El sistema no puede encontrar la ruta especificada.	WivOSKernelBoot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Error		Error occurred while invoking objdump.	WivOSKernelBoot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Error		An error occurred: System.Exception: Error extracting map from C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\WivOSKernelBoot.bin
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.RunObjDump(String cosmosBuildDir, String workingDir, String inputFile, Action`1 errorReceived, Action`1 outputReceived)
   en Cosmos.Build.MSBuild.ExtractMapFromElfFile.Execute()	WivOSKernelBoot	C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	44	
Mensaje		Working directory = 'C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = System	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	WivOSKernelBoot		0	
Mensaje		Loaded : UseNAsm	WivOSKernelBoot		0	
Mensaje		Ld task took 00:00:00.8934670	WivOSKernelBoot		0	
Mensaje		Loaded : DebugEnabled	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.INT3Label'	WivOSKernelBoot		0	
Mensaje		Loaded : StackCorruptionDetectionEnabled	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings: Start check	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = System	WivOSKernelBoot		0	
Mensaje		Extracting Map file took 00:00:00.7500798	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.Core'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = HAL	WivOSKernelBoot		0	
Mensaje		Loaded : IgnoreDebugStubAttribute	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.HAL'	WivOSKernelBoot		0	
Mensaje		Loaded : DebugCom	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Plugs'	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.HAL'	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.System'	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'	WivOSKernelBoot		0	
Mensaje		Loaded : TraceAssemblies	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = HAL	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = HAL	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Memory'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		IL2CPU task took 00:00:35.5826021	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = System	WivOSKernelBoot		0	
Mensaje		Loaded : OutputFilename	WivOSKernelBoot		0	
Mensaje		Executing command line "C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\WivOSKernelBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\vs\WivOSKernel\WivOSKernel\bin\Debug\netstandard1.5\WivOSKernel.dll"	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.Document'	WivOSKernelBoot		0	
Mensaje		Loaded : AdditionalSearchDirs	WivOSKernelBoot		0	
Mensaje		IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'WivOSKernel'	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.LOCAL_ARGUMENT_INFO'	WivOSKernelBoot		0	
Mensaje		NAsm task took 00:00:11.3285875	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	WivOSKernelBoot		0	
Mensaje		Loaded : EmitDebugSymbols	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Memory'	WivOSKernelBoot		0	
Mensaje		Loaded : DebugMode	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.System'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'	WivOSKernelBoot		0	
Mensaje		Loaded : EnableLogging	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'	WivOSKernelBoot		0	
Mensaje		Executing IL2CPU on assembly	WivOSKernelBoot		0	
Mensaje		Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\WivOSKernelBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\vs\WivOSKernel\WivOSKernel\bin\Debug\netstandard1.5\WivOSKernel.dll"	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Working directory = 'C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\'	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.HAL'	WivOSKernelBoot		0	
Mensaje		Loaded : AdditionalReferences	WivOSKernelBoot		0	
Mensaje		Executing command line "C:\Users\Jesús\AppData\Roaming\Cosmos User Kit\Build\tools\cygwin\ld.exe" -Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o 'C:/vs/WivOSKernel/WivOSKernel/bin/Debug/net462/WivOSKernelBoot.bin' 'C:/vs/WivOSKernel/WivOSKernel/bin/Debug/net462/WivOSKernelBoot.obj'	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Common'	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.System'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = User	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = System	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.System.Plugs'	WivOSKernelBoot		0	
Mensaje		Detecting fields for type 'Cosmos.Debug.Symbols.Method'	WivOSKernelBoot		0	
Mensaje		Rings:     Dependency 'Cosmos.Core'	WivOSKernelBoot		0	
Mensaje		Rings:         Ring = Core	WivOSKernelBoot		0	
Mensaje		Loaded : StackCorruptionDetectionLevel	WivOSKernelBoot		0	
Mensaje		Rings: Assembly 'Cosmos.Core.Plugs.Asm'	WivOSKernelBoot		0	
Mensaje		Loaded : References	WivOSKernelBoot		0	
Mensaje		Executed OK	WivOSKernelBoot		0

**Comment by jp2masa** [comment]
As Cosmos is installed in %appdata%, probably the user folder can't have any special chars too.

**Comment by StartForKillerMC** [comment]
can i solve it?

**Comment by StartForKillerMC** [comment]
but it fails extracting in C:\vs\WivOSKernel\WivOSKernel\bin\Debug\net462\kernelboot

**Comment by jp2masa** [comment]
We use `objdump` (from cygwin I think) and it doesn't work well on paths with special chars. Maybe we can replace it with a mingw version, because it supports special chars on paths.

**Comment by StartForKillerMC** [comment]
how can i change the directory of instalation of the cosmos?

**Comment by jp2masa** [comment]
I think you can't.

**Comment by StartForKillerMC** [comment]
I need to create a user and install with this user?

**Comment by jp2masa** [comment]
I think so.

**Comment by fanoI** [comment]
A user which name should have only ASCII characters...

**Comment by Arawn-Davies** [comment]
You should be able to change the install dir for Cosmos if you build it as a userkit or run it separately from the builder, maybe install it on the root of your C drive and it might work
