### ISSUE TITLE
VGAscreen bug

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#80]
Trying to write to a VGAscreen throws an error at compile-time:

    C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.NotImplementedException: OpCode 'Ldobj' not implemented! Encountered in method Void WriteVGARegisters(Byte[])

Here are some excerpts from my code that may be helpful:

    VGAscreen vScreen = new VGAscreen();
    ...
    vScreen.SetGraphicsMode(VGAScreen.ScreenSize.Size320x200, VGAScreen.ColorDepth.BitDepth8);
    vScreen.Clear(15);
    ...
    public void Draw() // Called every update loop cycle
    {
        vScreen.Clear(15);
        vScreen.SetPixel320x200x8((uint)ms.X, (uint)ms.Y, 0);
    }

I apologize if I am missing some new feature. I just upgraded from the Codeplex version to the latest release (not source) on GitHub. That's when my code stopped working.

**Comment by czhower** [comment]
Based on the text of the error, it looks like you are using a release that is 5 or more years old which is absolutely not supported.

**Comment by ARMmaster17** [comment]
But I'm using the latest version from GitHub located here: [https://github.com/CosmosOS/Cosmos/releases/tag/v0.20150130](https://github.com/CosmosOS/Cosmos/releases/tag/v0.20150130)

**Comment by czhower** [comment]
@mterwoord - Why are we seeing this old message here instead of the newer one with URL?

**Comment by ARMmaster17** [comment]
Here's the full dump from VS: [https://gist.github.com/ARMmaster17/943106a53422a6226248](https://gist.github.com/ARMmaster17/943106a53422a6226248)

**Comment by ARMmaster17** [comment]
Also, I did switch the reference from this:

    using Cosmos.Hardware;

to this:

    using Cosmos.HAL;

**Comment by mterwoord** [comment]
@czhower This is a recent release.

@ARMmaster17 Would you be able to make a pull request? The bug is in our IL interpreter. See https://github.com/CosmosOS/Cosmos/issues/72 for the accompanying stobj bug..

**Comment by ARMmaster17** [comment]
Sure, I think I can figure it out. What exactly do I have to do?

**Comment by mterwoord** [comment]
@ARMmaster17 Have you read issue #72? It's pretty much the same bug, but for a different (but very similar) instruction. 

If you want, you can add me to skype. same id..

**Comment by ARMmaster17** [comment]
@mterwoord So if I understand this correctly, I just have to redo commit 77f741a1272823419b3f756ea3c16648f7209a1b, but with ldobj instead of stobj?

**Comment by mterwoord** [comment]
Only the OpType change. One thing though: GetNumberOfStackPops should return 1 instead of 2, and GetNumberOfStackPushes should return 1 instead of 0

**Comment by ARMmaster17** [comment]
Ok, pull request has been opened with the changes as PR #81.

**Comment by mterwoord** [comment]
I'll try to review it soon, or maybe someone else will..
