### ISSUE TITLE
.NET Runtime

### ISSUE THREAD

**Issue by horus9426** [CosmosOS/Cosmos#800]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installation

#### Expected Behaviour - What do you think that should happen?
.NET Core should be detected
I have the .NET SDK framework installed, and the exe installer listed in the troubleshooting document
However, the VS2017 installer keeps wanting me to reinstall .NET core runtime even if I have it installed
#### Actual Behaviour - What unexpectedly happens?
.NET Runtime not detected by installer

#### Reproduction - How did you get this error to appear?
Running install-vs2017.bat

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Dev Kit commit 4909509cef84d2a25ee6997f225df2859f714de3

**Comment by jp2masa** [comment]
You need to install the .NET Core Tools workload.

**Comment by horus9426** [comment]
That is not a workload I have. These are the workloads that I have
![screenshot 4](https://user-images.githubusercontent.com/8531485/32470780-9a3e45e8-c31f-11e7-858b-4b1063d99d7e.png)

**Comment by horus9426** [comment]
Also, you can see how it indicates that .NET core is not installed on the right, even though the install size says 0MB.

**Comment by jp2masa** [comment]
You need the ".NET Core cross-platform development" workload.

**Comment by horus9426** [comment]
That seemed to have fixed the issue, thanks!
