### ISSUE TITLE
QUESTION - About variable conversion

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#803]
As far as I know absolutely no implementation of variable conversion has been done in COSMOS (Correct me if I'm wrong).

I would like to ask for any advice on how I could do that, mostly
int,float -> string
and
string ->int,float

I guess second is prettymuch easy to do by splitting the characters of a string and then doing a switch
on the numbers as characters.
But the first one? Most methods I found don't give very accurate results...

Also,

var, object -> int,float
var, object ->string

I appreciate your help!
Thanks in advance!

**Comment by jp2masa** [comment]
int, float -> string is implemented, just use `ToString()`.
string -> int is implemented, `Int32.Parse(String)`.
string -> float isn't implemented.
Also, what do you expect from var, object -> int, float and var, object -> string conversions? Type conversions?

**Comment by 365Tito** [comment]
@jp2masa  Well, I've found that built in conversions within cosmos are prettymuch either unstable or not implemented, so I decided to code my own. Still, thanks for your help though :)

**Comment by jp2masa** [comment]
I'm closing this then. If you have more questions, feel free to ask.
