### ISSUE TITLE
Add plugs for String.Split() and other methods that use generics.

### ISSUE THREAD

**Issue by charlesbetros** [CosmosOS/Cosmos#805]
We won't have support for generic interfaces on arrays for a while. For now we should plug the often used methods as they worked before our .net core move.

**Comment by jp2masa** [comment]
I think that `String.Split()` works.

**Comment by charlesbetros** [comment]
Skip does too?

**Comment by jp2masa** [comment]
I think that it never worked, because it's a [LINQ extension method for `IEnumerable<T>`](https://docs.microsoft.com/pt-pt/dotnet/api/system.linq.enumerable.skip?view=netframework-4.7.1#System_Linq_Enumerable_Skip__1_System_Collections_Generic_IEnumerable___0__System_Int32_).
