### ISSUE TITLE
Error adding Ring 2

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#806]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Adding Ring 2

#### Expected Behaviour - What do you think that should happen?
No errors

#### Actual Behaviour - What unexpectedly happens?
The type of namespace name 'RingAttribute' could not be found
The type or namespace name 'Ring' could not be found

#### Reproduction - How did you get this error to appear?
Followed the GUI tutorial:
https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI-The-basics

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
DevKit

When I add 
```
using Cosmos.Common;
[assembly: Ring(Ring.System)]
```
to the Hardware AssembltInfo.cs file, I get the errors 

> The type of namespace name 'RingAttribute' could not be found
> The type or namespace name 'Ring' could not be found

**Comment by jp2masa** [comment]
Rings are disabled in the Dev Kit.

**Comment by IanSteg** [comment]
Ok
