### ISSUE TITLE
PXE Error

### ISSUE THREAD

**Issue by Anson12666** [CosmosOS/Cosmos#807]
![a](https://user-images.githubusercontent.com/28622566/32987910-11c0fca6-cd33-11e7-87b9-f01a7a721fce.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Latest Version

----------------------
#### Debugger Message
![a](https://user-images.githubusercontent.com/28622566/32987952-31a3557c-cd34-11e7-9799-dbb6584dc428.png)

> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\Users\anson\AppData\Roaming\Cosmos User Kit\Build\Tools\Cosmos.Deploy.Pixie.exe'. Symbols loaded.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Cannot find or open the PDB file.
> 'Cosmos.Deploy.Pixie.exe' (CLR v4.0.30319: Cosmos.Deploy.Pixie.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Cannot find or open the PDB file.
> An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in Cosmos.Deploy.Pixie.exe
> Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by fanoI** [comment]
PXE probably needs more work... the error seems to make intend that the address is already in use, are you sure to not have a socket already opened on that port?

**Comment by Anson12666** [comment]
Every IP is not correct

**Comment by Anson12666** [comment]
![a](https://user-images.githubusercontent.com/28622566/32992061-fac8ffdc-cd80-11e7-89e6-7da3029f0eeb.png)

**Comment by quajak** [comment]
Has this issue been resolved?
