### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by flash76** [CosmosOS/Cosmos#809]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building the OS

#### Expected Behaviour - What do you think that should happen?
ISO image should be generated

#### Actual Behaviour - What unexpectedly happens?
I get this error: `Assets file 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.2'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project.`

Error log: 

`Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: XenoteOS, Configuration: Debug Any CPU ------
1>XenoteOS -> C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll
2>------ Build started: Project: XenoteOSBoot, Configuration: Debug Any CPU ------
2>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.Net.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.2'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project.
2>Done building project "XenoteOSBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

#### Reproduction - How did you get this error to appear?
All I do is click "run" to start building the proj

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Using UserKit v20170620

**Comment by jp2masa** [comment]
Try installing User Kit 2017 09 28, the only difference from UserKit v20170620 is a fix for that bug.

**Comment by flash76** [comment]
Alright.

**Comment by flash76** [comment]
Yep, that worked. Now I just need to see how to invoke `il2cpu.exe`.
