### ISSUE TITLE
Error invoking IL2CPU

### ISSUE THREAD

**Issue by flash76** [CosmosOS/Cosmos#810]
#### Area of Cosmos - What area of Cosmos are we dealing with?
A pretty common one - Error invoking IL2CPU

#### Expected Behaviour - What do you think that should happen?
Build the OS

#### Actual Behaviour - What unexpectedly happens?
Give error: Error occured while invoking IL2CPU
Output: `Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: XenoteOS, Configuration: Debug Any CPU ------
1>XenoteOS -> C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll
2>------ Build started: Project: XenoteOSBoot, Configuration: Debug Any CPU ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll" 
2>C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll" 
2>	Working directory = 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.IO.IOException: The process cannot access the file 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.cdb' because it is being used by another process.
2>	   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
2>	   at System.IO.File.Delete(String path)
2>	   at Cosmos.Debug.Symbols.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes) in C:\Users\Administrator\Cosmos\source\Cosmos.Debug.Symbols\DebugInfo.cs:line 74
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 166
2>	Loaded assemblies: 
2>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOS.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.6311483
2>Done building project "XenoteOSBoot.Cosmos" -- FAILED.
2>
2>Build FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`
#### Reproduction - How did you get this error to appear?
Whenever I stop debugging the OS, and then start debugging again, always errors out. Only way I know right now to continue is to close VS2017 and reopen.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Latest version, downloaded and installed today -UserKit.

**Comment by zarlo** [comment]
restart VS should fix it 

Exception: System.IO.IOException: The process cannot access the file 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.cdb' because it is being used by another process.

**Comment by flash76** [comment]
But that `XenoteOSNoot.cdb` file, is that being used by VMWare then? The only process I know of that is linked to this COSMOS Project is VMWare.

But I always have to restart VS - I specified that in my problem

**Comment by jp2masa** [comment]
The debug engine opens that file, but probably it's never disposed.

**Comment by flash76** [comment]
So how would I "dispose" of that file?

**Comment by jp2masa** [comment]
The debug engine would have to be stopped, but it's running on VS, so you have to restart VS...

**Comment by flash76** [comment]
Ok...

**Comment by flash76** [comment]
Now I'm getting the error EVEN after closing VMWare and restarting VS. Please don't tell me I have to restart my PC now every time...

**Comment by zarlo** [comment]
can we have the log

**Comment by flash76** [comment]
Alright, here it is (again)

`Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: XenoteOSBoot, Configuration: Debug Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll" 
1>C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\netstandard1.5\XenoteOS.dll" 
1>	Working directory = 'C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.
1>	   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
1>	   at System.Reflection.RuntimeReflectionExtensions.GetRuntimeInterfaceMap(TypeInfo typeInfo, Type interfaceType)
1>	   at Cosmos.IL2CPU.ILScanner.ScanType(TypeInfo aType) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 669
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 699
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>	Loaded assemblies: 
1>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
1>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
1>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
1>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
1>	C:\Users\varunsom\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
1>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\Cosmos.System.Plugs.dll
1>	C:\Users\varunsom\Documents\Visual Studio 2017\Projects\XenoteOS\XenoteOS\bin\Debug\net462\XenoteOS.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:02.7847222
1>Done building project "XenoteOSBoot.Cosmos" -- FAILED.
1>
1>Build FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========`

**Comment by jp2masa** [comment]
You can't use an array as a generic interface, the compiler doesn't support that yet.

**Comment by flash76** [comment]
Oh. I was using a string array to store commands and their responses. When will arrays be implemented?

**Comment by jp2masa** [comment]
Arrays are implemented, the runtime generic interfaces aren't supported yet. See CosmosOS/IL2CPU#15

**Comment by flash76** [comment]
What does that mean?

**Comment by flash76** [comment]
I'm not sure if it's an error with an array, because I commented out the array, declaring an int. Now all I have is that stock stuff - `Console.WriteLine();` in `BeforeRun(){}` and a `Console.Write();` and `var cmd = Console.ReadLine();`. I just restarted VS and I'm getting the same error.

**Comment by jp2masa** [comment]
Try rebuilding the project.

**Comment by flash76** [comment]
Alright.

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34456252-b1b76446-edc4-11e7-8628-1ac6ece4be08.png)
I can not understand it.

**Comment by jp2masa** [comment]
You unloaded the Cosmos project.
