### ISSUE TITLE
Dev Kit Install Fails

### ISSUE THREAD

**Issue by flash76** [CosmosOS/Cosmos#811]
#### Area of Cosmos - What area of Cosmos are we dealing with?
DevKit install

#### Expected Behaviour - What do you think that should happen?
Install the Dev Kit from batch file

#### Actual Behaviour - What unexpectedly happens?
After I ensure I have the .NET Core (Latest version - 2.0.3), Install of Dev Kit fails - ".NET Core not detected"

#### Reproduction - How did you get this error to appear?
Run the Install-VS2017.bat file under the COSMOS source folder

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
I was trying to install the latest dev kit.

## Full output
===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

=====
Error
=====

.NET Core not detected.

**Comment by zarlo** [comment]
you need to install .NET Core

**Comment by flash76** [comment]
But I DO have the .NET core! Version 2.0.3

**Comment by jp2masa** [comment]
You need the .NET Core development VS workload.

**Comment by flash76** [comment]
I don't see that in VS Installer
