### ISSUE TITLE
(C#) My VGAScreen 640x480x4 setpixel not working.

### ISSUE THREAD

**Issue by Isaquedeveloper** [CosmosOS/Cosmos#816]
I'm using cosmos version for VS2013.
I'm using userkit.
More details: https://stackoverflow.com/questions/47610386/vgascreen-does-not-work-on-the-cosmos

**Comment by Isaquedeveloper** [comment]
I'm using cosmos version for VS2013.

**Comment by jp2masa** [comment]
Old Cosmos versions aren't supported.
