### ISSUE TITLE
My canvas is too slow ...

### ISSUE THREAD

**Issue by Isaquedeveloper** [CosmosOS/Cosmos#817]
I'm trying to make a double-buffered screen with canvas, but is too slow.
My code:

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.HAL;
using Cosmos.HAL.Drivers;
using Cosmos.System.Graphics;

namespace ScreenPack
{
    public class Screen
    {
        public static Screen MainScreen;
        public Canvas screen;
        private Color[] buffer;
        private int width, height;
        public Color BackColor = Color.FromArgb(0, 153, 255);

        private byte GetIntFromRBG(byte red, byte green, byte blue)
        {
            uint x;
            x = (blue);
            x += (uint)(green << 8);
            x += (uint)(red << 16);
            return (byte)x;
        }

        public Screen()
        {
            screen = FullScreenCanvas.GetFullScreenCanvas(new Mode(640,480,ColorDepth.ColorDepth32));
            screen.Clear();
            MainScreen = this;
        }

        public void DrawBuffer()
        {
            for (int x = 0; x < width; x++)
            {
                for (int y = 0; y < height; y++)
                {
                    SetPixelRaw(x, y, buffer[(y * width) + x]);
                    buffer[(y * width) + x] = BackColor;
                }
            }
        }
        public void Init ()
        {
            try
            {
                width = screen.DefaultGraphicMode.Columns;
                height = screen.DefaultGraphicMode.Rows;
                screen.Clear(Color.Red);
                screen.Clear(BackColor);
                buffer = new Color[width * height];
            }
            catch(Exception ex)
            {
                StationOS2.BlueScreen bsod = new StationOS2.BlueScreen(ex.Message, "VBE_INIT", "init error", "#vbe", "0.1");
                bsod.Show();
            }
        }

        public void FillRectangle(int X,int Y,int w,int h,Color color)
        {
            for (int x = 0; x < w; x ++)
            {
                for (int y = 0; y < h; y ++)
                {
                    SetPixel(x + X, y + Y, color);
                }
            }
        }

        public void FillRectangle(int X, int Y, int w, int h, byte r,byte g,byte b)
        {
            FillRectangle(X, Y, w, h, Color.FromArgb(r, g, b));
        }

        public virtual void SetPixel (int x, int y, Color c)
        {
            if (x <= width && y <= height && x >= 0 && y >= 0)
            if (GetPixel(x,y) != c)
                buffer[(y * width) + x] = c;/*SetPixelRaw(x,y,c);*/
        }

        public virtual void SetPixel(int x, int y, byte r,byte g,byte b)
        {
            if (x <= width && y <= height && x >= 0 && y >= 0)
                if (GetPixel(x, y) != Color.FromArgb(r,g,b))
                    buffer[(y * width) + x] = Color.FromArgb(r,g,b);/*
                    SetPixelRaw(x, y,Color.FromArgb(255,r,g,b));
                    */
        }

        public virtual Color GetPixel (int x, int y)
        {
            return buffer[(y * width) + x];
        }

        public virtual void Clear ()
        {
            Clear(Color.Black);
        }

        public virtual void Clear (Color c)
        {
            screen.Clear(c);
        }

        public virtual void Step() { }

        public int GetWidth()
        {
            return width;
        }

        public int GetHeight()
        {
            return height;
        }

        public void SetPixelRaw (int x, int y, Color c)
        {
            if (x <= width && y <= height && x >= 0 && y >= 0)
            {
                Pen p = new Pen(c, 1);
                screen.DrawFilledRectangle(p, x, y, 1, 1);
            }

        }
    }
}

Sorry for my english -- I speak portuguese

**Comment by Isaquedeveloper** [comment]
when I use canvas.Clear(), it's fast, and in the code, it use a loop too:
(Canvas.cs of userkit)
`        public virtual void Clear(Color color)
        {
            Global.mDebugger.SendInternal($"Clearing the Screen with Color {color}");
            //if (color == null)
            //    throw new ArgumentNullException(nameof(color));

            Pen pen = new Pen(color);
            for (int x = 0; x < mode.Rows; x++)
            {
                for (int y = 0; y < mode.Columns; y++)
                {
                    DrawPoint(pen, x, y);
                }
            }
        }`

**Comment by jp2masa** [comment]
It's a bit slow for now, but it will be improved in the future. If you're using Bochs, it will always be slow, as it's an emulator. If you really need to see it running fast, you can use VirtualBox (doesn't support debug yet, so you have to build an ISO and create a VM which loads the ISO).

**Comment by fanoI** [comment]
Clear() is overridden by VBEScreen with an implementation that in the end calls ASM so it is for this that is fast :-)

If I understand well your implementation is using  screen.DrawFilledRectangle to do double buffering and it is that the problem, DrawFilledRectangle is slow, probably could be optimized doing something similar to what has been done to Clear().

But @jp2masa says you could never obtain super smooth velocity from Bochs it really emulates all in software, so...

**Comment by zarlo** [comment]
not updating the hole screen every time will speed it up too
