### ISSUE TITLE
Canvas GetPixel

### ISSUE THREAD

**Issue by Isaquedeveloper** [CosmosOS/Cosmos#819]
How can I get pixel of my canvas?
I'm using cosmos UserKit.
Sorry for my english -- I speak portuguese

**Comment by jp2masa** [comment]
Why do you need to get a pixel?

**Comment by Isaquedeveloper** [comment]
I need to read the pixels to be able to clear the ghost pixels of the mouse.

**Comment by jp2masa** [comment]
You can use a buffer to store pixels.
