### ISSUE TITLE
OpCode 'Localloc' not implemented

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#82]
I'm getting an error after adding some string manipulation code during build time. Here's the dump:

    ------ Build started: Project: Flow_OS2Boot, Configuration: Debug x86 ------
    C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
    C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.NotImplementedException: OpCode 'Localloc' not implemented!
    C:\Program Files\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILOpCodes.OpNone.GetNumberOfStackPops(MethodBase aMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 147
    Build has been canceled.

My guess is that this issue is related to #80 and #72.

Cosmos UserKit (latest GitHub release)
VS 2013 Professional 32-bit

**Comment by mterwoord** [comment]
Your guess is right! Good work! :+1: 

Please lookup how many stack pushes and pops localloc does in ecma 335 (I don't have it with me at the moment) and fix it.

**Comment by ARMmaster17** [comment]
Before I break something, is there a difference between popI and pop1? It wants me to push and pull "i" for localloc. (I apologize for all the questions, I'll figure it out eventually).
