### ISSUE TITLE
VS2017 Issues. 

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#820]
===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

================
Init Directories
================

Cleaning up existing VSIP directory.
Creating VSIP as C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Build\VSIP
Cleaning up existing User Kit directory.
Creating User Kit as C:\Users\name\AppData\Roaming\Cosmos User Kit

======================
Clean NuGet Local Feed
======================

Starting: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Build\Tools\nuget.exe
  Params: sources List
Registered Sources:

  1.  Cosmos MyGet Feed [Enabled]
      https://www.myget.org/F/cosmos/api/v3/index.json
  2.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  3.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

======================
Restore NuGet Packages
======================

Starting: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Build.sln"
MSBuild auto-detection: using msbuild version '15.3.409.57025' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\IL2CPU\source\IL2CPU\IL2CPU.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\XSharp\source\XSharp\XSharp.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\IL2CPU\source\Cosmos.IL2CPU.API\Cosmos.IL2CPU.API.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\XSharp\source\Spruce\Spruce.csproj cannot be found.
WARNING: Project file C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\..\XSharp\source\XSharp.x86\XSharp.x86.csproj cannot be found.
All packages listed in packages.config are already installed.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Tests\Cosmos.TestRunner.TestController\obj\project.assets.json
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Common\obj\project.assets.json
Restore completed in 51.65 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Tools\NASM\obj\project.assets.json
Restore completed in 17.01 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Tools\NASM\NASM.csproj.
Restore completed in 32.45 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.MSBuild\obj\project.assets.json
Restore completed in 32.07 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core\obj\project.assets.json
Restore completed in 0.94 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core_Asm\obj\project.assets.json
Restore completed in 1.67 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core.DebugStub\obj\project.assets.json
Restore completed in 0.77 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Common\obj\project.assets.json
Restore completed in 1.6 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.DebugConnectors\obj\project.assets.json
Restore completed in 3.14 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Common\obj\project.assets.json
Restore completed in 4.56 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Hosts\obj\project.assets.json
Restore completed in 8.17 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\obj\project.assets.json
Restore completed in 1.37 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core_Plugs\obj\project.assets.json
Restore completed in 1.39 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Kernel\obj\project.assets.json
Restore completed in 0.63 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.HAL2\obj\project.assets.json
Restore completed in 1 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.System2\obj\project.assets.json
Restore completed in 1.17 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.System2_Plugs\obj\project.assets.json
Restore completed in 3.26 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\TheRingMaster\obj\project.assets.json
Restore completed in 3.31 ms for C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.

NuGet Config files used:
    C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\NuGet.Config
    C:\Users\name\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/cosmos/api/v3/index.json
Starting: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\../IL2CPU/IL2CPU.sln"
Input file does not exist: C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\../IL2CPU/IL2CPU.sln.

=====
Error
=====

Console returned exit code. (0x00000001)
   at Cosmos.Build.Installer.Task.StartConsole(String aExe, String aParams) in C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 94
   at Cosmos.Build.Builder.CosmosTask.Restore(String project) in C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 279
   at Cosmos.Build.Builder.CosmosTask.CompileCosmos() in C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 309
   at Cosmos.Build.Builder.CosmosTask.DoRun() in C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 71
   at Cosmos.Build.Installer.Task.Run() in C:\Users\name\Downloads\Cosmos-master (1)\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 16

**Comment by jp2masa** [comment]
You need to clone Cosmos, IL2CPU and XSharp in parallel, and the folders must have the same name as the repo.

**Comment by GtaMasterYT** [comment]
How would I do that?

**Comment by jp2masa** [comment]
Clone the repos to create a folder structure like this:
Cosmos (or other name)
|-- Cosmos
|-- IL2CPU
|-- XSharp

**Comment by jp2masa** [comment]
Create a folder for Cosmos, and run these commands:
```
git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git
```

**Comment by GtaMasterYT** [comment]
I already tried that

**Comment by GtaMasterYT** [comment]
all the folders that were cloned are in a folder named "aaa"

**Comment by jp2masa** [comment]
You get the same error?

**Comment by GtaMasterYT** [comment]
Yes

**Comment by jp2masa** [comment]
Try creating a new folder, and run these commands in the that folder:
```
git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git
```
Then run `install-VS2017.bat` and if it fails copy the log to a pastebin.

**Comment by GtaMasterYT** [comment]
It looks the same. Same error it cant find the files.

**Comment by jp2masa** [comment]
Could you please copy the log to a pastebin?

**Comment by GtaMasterYT** [comment]
https://pastebin.com/raw/TcE7MsCL

**Comment by jp2masa** [comment]
You don't have the correct folder structure.
It has to look like this:

Cosmos (or other name)
|-- Cosmos (repo, has to be this name)
|-- IL2CPU (repo, has to be this name)
|-- XSharp (repo, has to be this name)

**Comment by GtaMasterYT** [comment]
Thanks. I'm gonna close the issue. Don't know if I can but I will try. Thanks anyway!

**Comment by GtaMasterYT** [comment]
I had some type of GUID issue.

**Comment by jp2masa** [comment]
That's not the correct template. Use the ones from the Cosmos section instead.

**Comment by GtaMasterYT** [comment]
?? What do you mean?

**Comment by jp2masa** [comment]
You get the error after creating a new project, right?

**Comment by GtaMasterYT** [comment]
yep

**Comment by jp2masa** [comment]
In the project creation dialog, there's a Cosmos project type in the pane on the left. Choose a template from those.

**Comment by GtaMasterYT** [comment]
Thanks
