### ISSUE TITLE
Devkit error '.Net core not detected'

### ISSUE THREAD

**Issue by Isaquedeveloper** [CosmosOS/Cosmos#821]
I get this error on executing 'install-VS2017.bat'

======================
Checking Prerequisites
======================

Check if User Kit Installer is already running.
Checking if Visual Studio is running.
Checking if Builder is already running.
Checking for .NET Core
Checking for Visual Studio Extension Tools
Checking for Inno Setup
Checking for Inno Preprocessor

=====
Error
=====

.NET Core not detected.

But I have installed .Net core SDK 2.0.3 x86 and all prequequisitod quoted on this website: https://www.gocosmos.org/download/

**Comment by jp2masa** [comment]
You need the .NET Core development tools VS workload.

**Comment by Isaquedeveloper** [comment]
what is this? when I can download it?

**Comment by jp2masa** [comment]
You can install it in the Visual Studio Installer.

**Comment by Isaquedeveloper** [comment]
ok, thanks

**Comment by Honzecki** [comment]
By the way, got same problem as #821 :/ only the problem i already have extension downloaded...
