### ISSUE TITLE
Error occurred while invoking IL2CPU

### ISSUE THREAD

**Issue by GtaMasterYT** [CosmosOS/Cosmos#824]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building solution.

#### Expected Behaviour - What do you think that should happen?
Build the solution/project.

#### Actual Behaviour - What unexpectedly happens?
When building it errors out and gives the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while invoking IL2CPU.	SpindleOSBoot	C:\Users\name\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	70	

#### Reproduction - How did you get this error to appear?
I don't even know. I ran it and it ran in VMWare then after adding some stuff and trying to build the error came up. Tried restarting visual studio & vmware but error stays.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
Dev Kit latest.

**Comment by zarlo** [comment]
can you give us the error log
