### ISSUE TITLE
My OS is too slow ...

### ISSUE THREAD

**Issue by Isaquedeveloper** [CosmosOS/Cosmos#825]
Why is my OS so slow ?? It takes about 30 seconds to complete this loop:
`for (int i = 0; i < 1000; i ++)
{
Console.WriteLine(i.ToString());
}`
Yes, 30 seconds.
 The version for visual studio 2013 was much faster. How can I accelerate?
I'm using VirtualBox, Cosmos UserKit.

-- Sorry for my english -- I speak portuguese

**Comment by zarlo** [comment]
its slower if you have the debugger on
and you don't need to i.ToString() you can jus t use i

**Comment by Isaquedeveloper** [comment]
My debugger is off.

**Comment by Isaquedeveloper** [comment]
In the version of visual studio 2013, the loop was completed in 8 seconds.

**Comment by zarlo** [comment]
well a lot has been add since the version for visual studio 2013
