### ISSUE TITLE
User Kit installation failes

### ISSUE THREAD

**Issue by quajak** [CosmosOS/Cosmos#828]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installing the User Kit

#### Expected Behaviour - What do you think that should happen?
The User Kit should be correctly installed, allowing me to create new projects in Visual Studio using Cosmos.

#### Actual Behaviour - What unexpectedly happens?
After the installation bar has filled and a nuget.exe cmd window is opened and closed, a second cmd window opens for a brief moment(to quick to read) and some red text appears. Following that the Setup Program removes the new Extentions from Visual Studio again.

#### Reproduction - How did you get this error to appear?
It occurs whenever I start the User Kit setup, regardless if it is downloaded directly or build using the Dev Kit. Both of these I have downloaded today/yesterday and are therefor of the newest version available.

I am unable to get any error message as the window closes to quickly. I am grateful for any advice on how to fix this issue.

**Comment by jp2masa** [comment]
It's expected to fail, because the local NuGet source was already initialized. Probably the VS extension isn't installed because some VS process is running in the background. Try installing it from "%appdata%\Cosmos User Kit\VSIX\Cosmos.VS.ProjectSystem.vsix".

**Comment by quajak** [comment]
Ok, thank you for the quick reply. Under AppData/Roaming I have a folder named "Cosmos User Kit" but it is empty.

**Comment by quajak** [comment]
Nevermind I found it somewehere else.
