### ISSUE TITLE
Hi. I have some problem with it. Can you help me fix that please?

### ISSUE THREAD

**Issue by hwoadministrator** [CosmosOS/Cosmos#837]
===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Visual Studio is running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

================
Init Directories
================

Cleaning up existing VSIP directory.
Creating VSIP as C:\Users\ASUS\Desktop\Cosmos-master\Build\VSIP
Cleaning up existing User Kit directory.
Creating User Kit as C:\Users\ASUS\AppData\Roaming\Cosmos User Kit

======================
Clean NuGet Local Feed
======================

Starting: C:\Users\ASUS\Desktop\Cosmos-master\Build\Tools\nuget.exe
  Params: sources List
Registered Sources:

  1.  Cosmos MyGet Feed [Enabled]
      https://www.myget.org/F/cosmos/api/v3/index.json
  2.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  3.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

======================
Restore NuGet Packages
======================

Starting: C:\Users\ASUS\Desktop\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\ASUS\Desktop\Cosmos-master\Build.sln"
MSBuild auto-detection: using msbuild version '15.5.180.51428' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\IL2CPU\source\IL2CPU.Compiler\IL2CPU.Compiler.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\XSharp\source\XSharp\XSharp.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\XSharp\source\Spruce\Spruce.csproj cannot be found.
WARNING: Project file C:\Users\ASUS\Desktop\Cosmos-master\..\XSharp\source\XSharp.x86\XSharp.x86.csproj cannot be found.
All packages listed in packages.config are already installed.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\Tests\Cosmos.TestRunner.TestController\obj\project.assets.json
Restore completed in 778.05 ms for C:\Users\ASUS\Desktop\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Common\obj\project.assets.json
Restore completed in 8.21 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core.DebugStub\obj\project.assets.json
Restore completed in 13.88 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\Tools\NASM\obj\project.assets.json
Restore completed in 1.05 sec for C:\Users\ASUS\Desktop\Cosmos-master\Tools\NASM\NASM.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Common\obj\project.assets.json
Restore completed in 1.04 sec for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core_Asm\obj\project.assets.json
Restore completed in 40.68 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core_Plugs\obj\project.assets.json
Restore completed in 10.41 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.MSBuild\obj\project.assets.json
Restore completed in 1.26 sec for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core\obj\project.assets.json
Restore completed in 329.88 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Common\obj\project.assets.json
Restore completed in 135.74 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel\obj\project.assets.json
Restore completed in 22.06 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.DebugConnectors\obj\project.assets.json
Restore completed in 287.18 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\obj\project.assets.json
Restore completed in 34.98 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Hosts\obj\project.assets.json
Restore completed in 46.14 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.HAL2\obj\project.assets.json
Restore completed in 42.15 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.System2_Plugs\obj\project.assets.json
Restore completed in 27.9 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.System2\obj\project.assets.json
Restore completed in 40.19 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ASUS\Desktop\Cosmos-master\source\TheRingMaster\obj\project.assets.json
Restore completed in 19.21 ms for C:\Users\ASUS\Desktop\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.

NuGet Config files used:
    C:\Users\ASUS\Desktop\Cosmos-master\NuGet.Config
    C:\Users\ASUS\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/cosmos/api/v3/index.json
Starting: C:\Users\ASUS\Desktop\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\ASUS\Desktop\Cosmos-master\../IL2CPU/IL2CPU.sln"
Input file does not exist: C:\Users\ASUS\Desktop\Cosmos-master\../IL2CPU/IL2CPU.sln.

=====
Error
=====

Console returned exit code. (0x00000001)
   at Cosmos.Build.Installer.Task.StartConsole(String aExe, String aParams) in C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 94
   at Cosmos.Build.Builder.CosmosTask.Restore(String project) in C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 279
   at Cosmos.Build.Builder.CosmosTask.CompileCosmos() in C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 309
   at Cosmos.Build.Builder.CosmosTask.DoRun() in C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 71
   at Cosmos.Build.Installer.Task.Run() in C:\Users\ASUS\Desktop\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 16

It show me about this log but I don't know how about errors and how to fix it

**Comment by jp2masa** [comment]
You need to clone Cosmos, IL2CPU and XSharp in parallel.

**Comment by hwoadministrator** [comment]
Where I clone it and clone from any folders?

**Comment by jp2masa** [comment]
You need to create this folder structure:
Cosmos (or any other name)
|-- Cosmos (repo, cloned or downloaded, has to be this name)
|-- IL2CPU (repo, cloned or downloaded, has to be this name)
|-- XSharp (repo, cloned or downloaded, has to be this name)

**Comment by hwoadministrator** [comment]
Sorry, but I can not understand where I put it? I put in cosmos-master or put it here?
![capture](https://user-images.githubusercontent.com/25245598/34327084-1cc8abe0-e8ee-11e7-846c-ffb9d330ed90.PNG)

**Comment by jp2masa** [comment]
Put it there, the name of the folder has to be "Cosmos".

**Comment by hwoadministrator** [comment]
It is not working correctly, can you help me with TeamViewer, please?

**Comment by jp2masa** [comment]
What's not working correctly? Are you still getting the same error?

**Comment by hwoadministrator** [comment]
Yes, I still get it again.

**Comment by hwoadministrator** [comment]
How can I fix it. Please help me T.T

**Comment by jp2masa** [comment]
Create a folder, open cmd in there and run the following commands:
```
git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git
```

**Comment by hwoadministrator** [comment]
![ww](https://user-images.githubusercontent.com/25245598/34327392-b72a1f0a-e8f5-11e7-9152-b5f32c18b8c1.PNG)
It all still here

**Comment by jp2masa** [comment]
That's not what happens if you run the commands I mentioned.

**Comment by hwoadministrator** [comment]
Okey I will try again. And I will reply you if I have it now.

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34346699-14e3e1a2-ea2d-11e7-8511-68f6aa32fa57.png)
I get the same errors. But I have using the command you mentioned :(

**Comment by jp2masa** [comment]
Check if there's some NuGet source which has an invalid path and remove it.

**Comment by hwoadministrator** [comment]
How I can remove it?

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34359846-ff88dcac-ea8d-11e7-83ee-88d4fd24ffee.png)
![image](https://user-images.githubusercontent.com/25245598/34359855-09386358-ea8e-11e7-897d-77ea66d95313.png)
![image](https://user-images.githubusercontent.com/25245598/34359867-1b50fa32-ea8e-11e7-861e-c175d18221fe.png)
![image](https://user-images.githubusercontent.com/25245598/34359872-2168cde6-ea8e-11e7-974b-81a4f392b777.png)
![image](https://user-images.githubusercontent.com/25245598/34359878-265798aa-ea8e-11e7-870c-766bfdde609d.png)
I don't see anything. Can you teamviews for me please?

**Comment by jp2masa** [comment]
In a folder with nuget.exe:
To check the sources: `nuget sources List`
To remove a source: `nuget sources Remove -Name "source name"`
Also, the gitter chat room is better to ask for help.

**Comment by hwoadministrator** [comment]
What the locator of file nuget.exe. I have used version visual 2017 but I don't see anything on Nuget Gallery Download.

**Comment by jp2masa** [comment]
There's a nuget.exe in Build\Tools\ .

**Comment by hwoadministrator** [comment]
I click it open and it close with 1s :(

**Comment by midonator1305** [comment]
That’s because you need to run nuget.exe from a command prompt

**Comment by hwoadministrator** [comment]
How can I run it? Can you give me the command, please?

**Comment by midonator1305** [comment]
Just do `cd <where ever nuget.exe is located>`
Then run `nuget.exe <insert command here>`

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34371478-40a401f4-eb00-11e7-9b57-8fdf6e8ea411.png)
Are it good sir?

**Comment by midonator1305** [comment]
That looks about right

**Comment by hwoadministrator** [comment]
But It also not working correct for nuget restore, I don't know how to fix it that :(

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34371722-2a4da9c6-eb02-11e7-9b00-f7815a749b53.png)
same errors :(

**Comment by midonator1305** [comment]
Are you sure that XSharp and IL2CPU are in the right place?

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34371786-a51e2608-eb02-11e7-8e7d-cb90c0a681fc.png)
yeah I have it

**Comment by midonator1305** [comment]
They should be outside the cosmos folder. 
In your case the ASUS folder

**Comment by hwoadministrator** [comment]
Yeah, it's working now. Thank you and jshama for helping me very much

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/36061998-12d560d8-0e96-11e8-92f5-259df489ee5a.png)
I must repair visual for some error show. Now I setting again and it tell me :( why?
