### ISSUE TITLE
Consider supporting .NET standard

### ISSUE THREAD

**Issue by AceHack** [CosmosOS/Cosmos#841]
Please consider supporting .net core 2.0 and future versions of .NET core or at least .NET standard

**Comment by jp2masa** [comment]
We are using .NET Core 2.0. There are some changes that probably will have to be done on IL2CPU related to assembly loading, because it's currently published for win7-x86 and the assemblies which are used for compilation are the ones which are published with the compiler.

**Comment by zarlo** [comment]
o i through we were still using .net core 1

**Comment by AceHack** [comment]
@charlesbetros Why the close?  Is .NET standard 2.0 supported now?  Is it on the roadmap?  Any way to track the status?  Thanks.

**Comment by charlesbetros** [comment]
As stated in previous comments, our executables currently target .net core 2 and our libraries target .net standard 2.

**Comment by AceHack** [comment]
@charlesbetros awesome, thanks.  I was confused by @jp2masa comment, it made it sound like IL2CPU needed to change because it still targeted a full like framework.  Thanks.
