### ISSUE TITLE
Consider adding Unik unikernel support

### ISSUE THREAD

**Issue by AceHack** [CosmosOS/Cosmos#842]
Would love to see this used as the C# Unik unikernel support

https://github.com/solo-io/unik/issues/35

**Comment by zarlo** [comment]
if Unik supports Asm then cosmos will work out of the box

**Comment by fanoI** [comment]
Well in some way Cosmos could be considered an Unikernel already actually the only way to have "applications" is to have them as part of the kernel itself.
