### ISSUE TITLE
How this can put some pentestools in cosmos?

### ISSUE THREAD

**Issue by hwoadministrator** [CosmosOS/Cosmos#846]
How can I put some tools of hacking or pentesting to this project os? Example like to Kali Linux or Metasploit in Linux?

**Comment by fanoI** [comment]
Well Cosmos it is not yet ready to be validated for security as it yet in its early stages of development.
The fact that tool to hack things done in C# probably does not exists is already a good starting point :-)

**Comment by hwoadministrator** [comment]
I think so much.
But about Cosmos we can develop os with it. But how any method can help create os?

**Comment by fanoI** [comment]
Well if the idea is to do an OS to search security problem in other devices yes this could be done in Cosmos, you can do a shell and do commands that try to penetrate in other devices... but you need network working before!

**Comment by hwoadministrator** [comment]
And the network has supported on cosmos already yet?

**Comment by fanoI** [comment]
Sadly not yet but is - obviously - in our roadmap.
