### ISSUE TITLE
Consider to use fdlibm for plug Math methods

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#848]
https://github.com/CosmosOS/Cosmos/issues/831 has shown that our Math plugs have some problems of precision or in corner cases I'm thinking if using fdlibm for the most complex of them (Sqrt, Sin, Cos, ...) could be the right thing to do.

fdlibm can be found here: http://www.netlib.org/fdlibm/ it is license is compatible with our:

     >Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.

     >Developed at SunPro, a Sun Microsystems, Inc. business.
     >Permission to use, copy, modify, and distribute this
     >software is freely granted, provided that this notice
     >is preserved.

**Comment by quajak** [comment]
I can rewrite the other methods from fdlibm, as I have started becoming familiar with how they are written, while translating the Math.Exp.

**Comment by fanoI** [comment]
Excellent!
