### ISSUE TITLE
[Discussion] Packages fallback folder

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#849]
.NET Core installs a fallback NuGet source at "%userprofile%\\.dotnet\NuGetFallbackFolder\\". Currently deleting the Cosmos installation folder is enough to break NuGet restores. We should have a fallback folder for packages too, I think that we should use one of the following:
1. "%userprofile%\\.cosmos\NuGetFallbackFolder\\"
2. "%appdata%\Cosmos\NuGetFallbackFolder\\"

**Comment by charlesbetros** [comment]
Dotnet has a fallback in case nuget servers can't be reached. Cosmos doesn't use nuget servers so its a bit silly to have two copies of the same package folder for a fallback.

It takes 60 seconds to reinstall a user kit to fix things and there are more issues than just missing packages if the user kit folder is deleted.

**Comment by jp2masa** [comment]
My idea is to use it as the packages folder for now, and when the packages are published to NuGet, it's used as a fallback folder (packages folder for Dev Kit).
