### ISSUE TITLE
#Question: Can I ask some question please?

### ISSUE THREAD

**Issue by hwoadministrator** [CosmosOS/Cosmos#850]
Example: I have the Mini OS only have a basic command. So with the source code, how about the idea to create the login page for this os same to Ubuntu, Kali Linux? And how we can create the mouse or graphic? I have try in youtube but the source code not support my version for visual studio enterprise 2017

**Comment by jp2masa** [comment]
Graphics are supported, but only 1 driver is currently implemented (Bochs Graphics Adaptor, works on Bochs, QEMU and VirtualBox). It's documented here: https://www.gocosmos.org/docs/cosmos-graphic-subsystem/.
 There's a mouse driver too, but it's not really easy to use (I improved it a lot in #700, but there are other priorities so I can't finish it yet).
