### ISSUE TITLE
[QUESTION] About time & date

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#851]
Is there a way to show the system time/date ?
Is there a way to get a time/date of creation for a directory/file?

Thanks in advance!

**Comment by jp2masa** [comment]
To get the current date and time, you can use `Cosmos.HAL.RTC`, unfortunately `DateTime` and `TimeSpan` won't work because the compiler doesn't have full support for structs.
I implemented date and time metadata in FAT, but I think there's currently no way of getting it.

**Comment by 365Tito** [comment]
Now I know it's off topic, but a quick question (so I don't need to post another one), Can I get the size of a file in another way except File.ReadAllBytes(path).LongLength ?

**Comment by fanoI** [comment]
You could use FileInfo.Lenght property.

**Comment by 365Tito** [comment]
@fanoI Already tried that, seems it needs a plug.

**Comment by fanoI** [comment]
Have you tried the last master? I've plugged it recently...

**Comment by 365Tito** [comment]
@fanoI  Yes, and it works, thanks guys!

**Comment by EndermanPC** [comment]
you can use DateTime for viewing but i think it no longer works
