### ISSUE TITLE
[Question] Using Linux to build an OS with Cosmos?

### ISSUE THREAD

**Issue by soccermitchy** [CosmosOS/Cosmos#852]
I saw from previous issues (like #841) that you guys now support .NET Core/.NET Standard 2.0, but is there any documentation on how to use it without the full .NET Framework on an OS like Linux? I don't really have access to a Windows system most of the time, so I prefer to do a lot of my development work on Linux.

**Comment by jp2masa** [comment]
It's not possible yet. We are getting there, but it may take some time. New code already takes other platforms on consideration, but there are still some parts that require Windows (mainly native binaries). With the new project system and SDK, it will be possible to build Cosmos projects using the dotnet cli, so we're really getting there.

**Comment by 365Tito** [comment]
@soccermitchy You can always use a Windows Virtual Machine to do the Cosmos / .NET development on, then when compiled you can run it practically anywhere. I don't know how much the WINE emulator supports .NET framework? Maybe you could try that.

**Comment by fanoI** [comment]
MonoDevelop should support Net Core (thing that yet is done) to have the same "integrated" experience that you have on Linux.

**Comment by zarlo** [comment]
@fanol you should be able to use Linux to build an OS with Cosmos with command line

**Comment by jp2masa** [comment]
As I said, it's not possible mainly because of the native binaries. The new project system allows building Cosmos projects using the dotnet cli.

**Comment by jp2masa** [comment]
I'll close this, as #884 is tracking the progress for cross-platform support.

**Comment by Ekaitxue** [comment]
> @soccermitchy You can always use a Windows Virtual Machine to do the Cosmos / .NET development on, then when compiled you can run it practically anywhere. I don't know how much the WINE emulator supports .NET framework? Maybe you could try that.

Unfortunately, you cannot use cosmos os in a virtual machine, beacause VMWare is needed for debugging
