### ISSUE TITLE
Error occurred while invoking IL2CPU.

### ISSUE THREAD

**Issue by theprogram2** [CosmosOS/Cosmos#855]
i am getting a error Error occurred while invoking IL2CPU.

**Comment by jp2masa** [comment]
Check the output window.

**Comment by theprogram2** [comment]
here is the output:
1>------ Build started: Project: ipnos3Boot, Configuration: Debug Any CPU ------
1>	Invoking il2cpu.exe "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\net462\ipnos3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "References:E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\netstandard2.0\ipnos3.dll" "AssemblySearchDirs:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel" 
1>C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(70,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "KernelPkg:" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\net462\ipnos3Boot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "References:E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\netstandard2.0\ipnos3.dll" "AssemblySearchDirs:C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel" 
1>	Working directory = 'E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\net462\'
1>	Warning: Loaded : DebugEnabled
1>	Warning: Loaded : StackCorruptionDetectionEnabled
1>	Warning: Loaded : DebugMode
1>	Warning: Loaded : StackCorruptionDetectionLevel
1>	Warning: Loaded : TraceAssemblies
1>	Warning: Loaded : DebugCom
1>	Warning: Loaded : OutputFilename
1>	Warning: Loaded : EnableLogging
1>	Warning: Loaded : EmitDebugSymbols
1>	Warning: Loaded : IgnoreDebugStubAttribute
1>	Warning: Loaded : References
1>	Warning: Loaded : AssemblySearchDirs
1>	Warning: Executing IL2CPU on assembly
1>	Warning: Kernel Base: Cosmos.System.Kernel
1>	Warning: Checking Reference: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>	Warning:   Exists
1>	Warning: Checking Reference: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>	Warning:   Exists
1>	Warning: Checking Reference: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	Warning:   Exists
1>	Warning: Checking Reference: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>	Warning:   Exists
1>	Warning: Checking Reference: E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\netstandard2.0\ipnos3.dll
1>	Warning:   Exists
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemBooleanGruntyOSHALGLNFSContainsSystemStringSystemChar': System.NullReferenceException: Object reference not set to an instance of an object.
1>	   at Cosmos.IL2CPU.X86.IL.Leave.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Leave.cs:line 20
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 666
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 513 ---> System.NullReferenceException: Object reference not set to an instance of an object.
1>	   at Cosmos.IL2CPU.X86.IL.Leave.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Leave.cs:line 20
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 666
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 513
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 520
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 1023
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 251
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 210
1>	Warning: Loaded assemblies: 
1>	Warning: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>	Warning: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>	Warning: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	Warning: C:\Users\misha.MISHA-PC\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>	Warning: E:\1Misha\visual studio 2017 projects\ipnos3\ipnos3\bin\Debug\netstandard2.0\ipnos3.dll
1>	Warning: Errored
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:47.1435599
1>Done building project "ipnos3Boot.Cosmos" -- FAILED.
1>
1>Build FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by jp2masa** [comment]
Are you using the `Release` configuration? If so, that's not supported yet.

**Comment by theprogram2** [comment]
no

**Comment by theprogram2** [comment]
here is the error i am getting in the output:
1>	Error: Exception: System.Exception: Error compiling method 'SystemBooleanGruntyOSHALGLNFSContainsSystemStringSystemChar': System.NullReferenceException: Object reference not set to an instance of an object.
1>	   at Cosmos.IL2CPU.X86.IL.Leave.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Leave.cs:line 20
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 666
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 513 ---> System.NullReferenceException: Object reference not set to an instance of an object.
1>	   at Cosmos.IL2CPU.X86.IL.Leave.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Leave.cs:line 20
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 666
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 513
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 520
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 1023
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 251
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\source\cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 210
