### ISSUE TITLE
Fail to load dependencies

### ISSUE THREAD

**Issue by TheBassonic** [CosmosOS/Cosmos#858]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Starting a new project

#### Expected Behaviour - What do you think that should happen?
Expected dependencies to correctly load

#### Actual Behaviour - What unexpectedly happens?
Project fails to correctly load dependencies, causing an error using namespace "System".

(On NuGet package manager page)

**Cosmos.Debug.Kernel**
_Not available in this source_

**Cosmos.System**
_Not available in this source_

#### Reproduction - How did you get this error to appear?
I get this error to appear just by creating a new Cosmos OS project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Dev Kit, Cosmos in C#

**Note:** The projects have been setup properly before,
and I was unable to load namespace System (using System;).

I'm also not sure whether this is a VS2017 problem, or a Cosmos problem.

**Comment by jp2masa** [comment]
The package restore is failing or not running. Try running the package restore manually (either by running `dotnet restore` in the project folder or right-click the solution -> Restore NuGet Packages).
