### ISSUE TITLE
Error during Cosmos Setup: Restore NuGet Packages

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#860]
I recently started working with the userkit of Cosmos, but there were some things that weren't implemented in the userkit so I tried to install the devkit but I keep getting the same problem. I've installed all the prerequisites.

Here is the part of the log where the error occured: 
[log (error part).txt](https://github.com/CosmosOS/Cosmos/files/1628827/log.error.part.txt)

And here is the complete log if it's needed: 
[log (complete).txt](https://github.com/CosmosOS/Cosmos/files/1628828/log.complete.txt)

**Comment by Project-Magenta** [comment]
You need to pull XSharp, IL2CPU **and** Cosmos

**Comment by jp2masa** [comment]
You need to clone Cosmos, IL2CPU and XSharp in parallel.

The folder structure should look like this:
Cosmos (or other name)
|-- Cosmos
|-- IL2CPU
|-- XSharp

You can run the following commands to get this folder structure:
```
git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git
```

**Comment by Project-Magenta** [comment]
then execute Cosmos\install-VS2017.bat

**Comment by BL9** [comment]
Tanks to all of you, the problem that I had here is fixed! But now I got an error at 'Build Cosmos'... Well, I'm gonna search on the web for a solution. If I can't find something that helps you'll see a new post from me.
