### ISSUE TITLE
Error during Cosmos Setup: Build Cosmos

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#861]
I recently started working with the userkit of Cosmos, but there were some things that weren't implemented in the userkit so I tried to install the devkit. First I kept getting an error at 'Restore NuGet Packages' but I managed to fix that (tanks to [this post](https://github.com/CosmosOS/Cosmos/issues/860)). Now I got another problem... Now I keep getting an error at 'Build Cosmos'. I've installed all the prerequisites.

Here is the error part of the log:
[log (error part).txt](https://github.com/CosmosOS/Cosmos/files/1633016/log.error.part.txt)

And here is the complete log if that can help:
[log (complete).txt](https://github.com/CosmosOS/Cosmos/files/1633017/log.complete.txt)

**Comment by jp2masa** [comment]
Try pulling latest from IL2CPU.

**Comment by BL9** [comment]
Tank you jp2masa, it worked altough I think it's a bit weard becuse I downloaded the maps that were needed 4 days ago...
