### ISSUE TITLE
Cosmos project option doesn't show up.

### ISSUE THREAD

**Issue by VisualTuber** [CosmosOS/Cosmos#862]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Making a new project (vs community 2017)

#### Expected Behaviour - What do you think that should happen?
Show cosmos project creation

#### Actual Behaviour - What unexpectedly happens?
Doesn't show the option in any frameworks

#### Reproduction - How did you get this error to appear?
No errors appeared.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit.

**Comment by jp2masa** [comment]
Probably there was some process running in the background during the VS extension installation, so it couldn't install. Try installing it from `%appdata%\Cosmos User Kit\VSIX\Cosmos.VS.ProjectSystem.vsix`.

**Comment by VisualTuber** [comment]
Ok

**Comment by VisualTuber** [comment]
![default](https://user-images.githubusercontent.com/30368284/35002063-1998a51e-faf1-11e7-9976-42f4bca4cc3e.png)

**Comment by VisualTuber** [comment]
Here is my install log: https://hastebin.com/ocuboqicod.tex

**Comment by jp2masa** [comment]
```
1/16/2018 7:08:02 PM - Package 'Microsoft.VisualStudio.Vsix.TemplatesPackage,version=15.5.100.41289' failed to install. System.IO.IOException: The file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\jjjzzyy1.o4y\catalog.json' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)
1/16/2018 7:08:02 PM - Skipping cache of package 'Microsoft.VisualStudio.Component.VSSDK,version=15.0.26919.1' since the package or a parent package had a vital failure.
1/16/2018 7:09:41 PM - Install Error : Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.VisualStudio.Vsix.TemplatesPackage' failed to install
```
Check if the extension is installed. If it is, uninstall it and try installing again. If it's not installed, try running the installer again and if it doesn't work I think that you'll have to repair VS.

**Comment by VisualTuber** [comment]
Ok

**Comment by VisualTuber** [comment]
How do i do that :O i haven't used vs for a while now

**Comment by VisualTuber** [comment]
![default](https://user-images.githubusercontent.com/30368284/35002585-ceaff316-faf2-11e7-9c8b-2494fcca3677.png)
This one?

**Comment by VisualTuber** [comment]
Oh yeah it's this one

**Comment by VisualTuber** [comment]
1/16/2018 7:26:11 PM - System.InvalidOperationException: Uninstall of Visual Studio Extensibility Templates failed. To uninstall this extension please uninstall all of the following components: 
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

**Comment by jp2masa** [comment]
It's not than one, probably it's not even installed.

**Comment by VisualTuber** [comment]
Well i just started updating visualstudio to see if it works

**Comment by VisualTuber** [comment]
Probably a bug in visualstudio idk

**Comment by VisualTuber** [comment]
I fixed the issue i just had to update visual studio to the latest version
