### ISSUE TITLE
Vmware small sceen issue

### ISSUE THREAD

**Issue by Mcilie** [CosmosOS/Cosmos#864]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Userkit 
running ISO in vmWare

#### Expected Behaviour - What do you think that should happen?
Screen should be fairly large, and readable
on my laptops screen.

#### Actual Behaviour - What unexpectedly happens?
boots to screen the size of less than 1.5 square inches.
text is unreadable

#### Reproduction - How did you get this error to appear?
Idk, this is the way cosmos has always been on my comp

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
user Kit 2017 09 28

**Comment by Ray1015** [comment]
This a VMWare issue, and can not currently be fixed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Project-Magenta** [comment]
^^^^^^
That's me

**Comment by Mcilie** [comment]
wait, so then what do i use to run the iso Cosmos compiles to? Vbox doesnt work either

**Comment by Project-Magenta** [comment]
This is unfixable until we fully transfer to using CGS

**Comment by Mcilie** [comment]
oh ok. thanks

**Comment by Mcilie** [comment]
And what exactly is CGS, I dont know the abreviation

**Comment by Project-Magenta** [comment]
Cosmos Graphics System

**Comment by Mcilie** [comment]
ahh, thanks again

**Comment by Project-Magenta** [comment]
I recommend you close the issue.

**Comment by fanoI** [comment]
We have tested and the issue in the last VmWare version and it is not happening for us!
A doubt: is your laptop are using High DPI or some particular resolution?

**Comment by Arawn-Davies** [comment]
The Cosmos Graphics Subsystem has now been added support for the VMWare SVGA II adapter, so you can pull the changes from the master branches of IL2CPU, X# and Cosmos in case this fixes the issue
