### ISSUE TITLE
[Question] Filesystem

### ISSUE THREAD

**Issue by OstojaTheGamer** [CosmosOS/Cosmos#866]
I am new to Cosmos and I would like to make a simple filesystem for my OS but I don't know how.
Comos is up to date.

**Comment by jp2masa** [comment]
You just have to initialize the VFS, like this:
```cs
var fs = new Sys.FileSystem.CosmosVFS();
Sys.FileSystem.VFS.VFSManager.RegisterVFS(fs);
```
And then you can use System.IO APIs.

**Comment by OstojaTheGamer** [comment]
I done that, is that all I had to do, what about creating directories, files, directory path, deleting directories, files and such.

**Comment by jp2masa** [comment]
@OstojaTheGamer Maybe I misread your question, you want to use the filesystem or create a new one?

**Comment by OstojaTheGamer** [comment]
I would like to use the premade filesystem if it exists, like creating directories, files and editing them in some kind of text like editor.

**Comment by fanoI** [comment]
OK then is do that @jp2masa said for example in your BeforeRun method, then you use simply C# System.IO functions: File.Create(), Dir.Create(), FileInfo and so on...

**Comment by OstojaTheGamer** [comment]
You can remove Pending User Response label and close this.
