### ISSUE TITLE
Audit system/hal/core for console output

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#868]
Low level drivers / modules as VFSManager should never write using Console.Write / Console.WriteLine but at least an example of this can be seen here: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/FileSystem/VFS/VFSManager.cs#L278

if debug logs are needed, we have the debugger for that.

**Comment by KrzysztofSzewczyk** [comment]
Also, catch clausues should be removed because kernel should handle exceptions. I can pick on this.

**Comment by Kiirx** [comment]
Can be closed

**Comment by quajak** [comment]
Outside of start up, there should be none left
