### ISSUE TITLE
Clean up Issues tab

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#87]
As assigned by @mterwoord, I have gone through the issues tab and compiled a list of issues that can be closed (wontfix/Issue resolved). If someone with admin access to the issues tab could close these issues, that would be great!

##:reason
#70:Issue resolved + inactive author(question answered)
#72:Issue resolved(merged #77)
#64:Workaround found (wontfix)(use old version)
#62:wontfix
#47:Author inactive (wontfix)
#45:wontfix (unknown bug source), inactive thread + author
#44:wontfix
#10:Issue resolved(merged #57)
#09:Issue resolved(merged #56)

**Comment by mterwoord** [comment]
#44 is actually planned, but is pretty much down the road. So i'll leave it open for now.
