### ISSUE TITLE
Plugs references

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#872]
Plugs are currently included by assembly path, but I think that they should be pulled using `PackageReference`s and/or `ProjectReference`s. We will need special metadata at least for `ProjectReference`. I think that the best option is creating an MSBuild SDK (maybe `Cosmos.Plugs.Sdk`?), which provides special metadata for project references and some custom `Pack` logic.

**Comment by Dark-Tater** [comment]
I know what plugs are and why we need them, but I don't know much about how or why to include them by  "Package/Project References". I would like to learn, though! If someone is willing to explain it a bit more, or sit down with me and discuss it for a while, I would be happy to give it a go! I would like to do something to help.

**Comment by jp2masa** [comment]
The best place to discuss Cosmos is the gitter chat: https://gitter.im/CosmosOS/Cosmos.

**Comment by jp2masa** [comment]
I think that this can be easily solved by [controlling depedency assets](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets). With some kind of `IsPlugsReference` item metadata:

```xml
<ItemGroup>
    <ProjectReference Include="path\to\MyPlugs.csproj" IsPlugsReference="True" />
    <PackageReference Include="Cosmos.System_Plugs" IsPlugsReference="True" />
</ItemGroup>
```

We can then set `ExcludeAssets="Compile"` for these references.

For VS, a simple CPS rule should be enough to show this option in the properties window for each kind of reference.

This should be enough for now, we can think about `Reference` (assembly reference) later if we need it.

**Comment by AsertCreator** [comment]
plugs reference tag is implemented now
