### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by PeterAS17** [CosmosOS/Cosmos#876]
When trying to create a project in Visual Studio 17 15.5.5, an error message saying that a _GUID must contain 32 digits and 4 dashes_ appear, and after clicking OK, the project isn't created. Screenshot included.

I'm using Cosmos User Kit 2017-09-28 on a Windows 7 computer.

![imagem](https://user-images.githubusercontent.com/3534002/35454428-49a55a06-02ce-11e8-83c9-8ab9ec268953.png)

**Comment by jp2masa** [comment]
You're using the wrong template, the correct one is in the Cosmos category in the New Project dialog.

**Comment by PeterAS17** [comment]
Oh yeah, stupid me... But by the way, to create the library, is there any way to correct that error?

**Comment by jp2masa** [comment]
That template shouldn't be needed, if you need to create a project in another ring, you can use a normal .NET Standard project.

**Comment by PeterAS17** [comment]
Alright, thanks for the help. Closing the issue.
