### ISSUE TITLE
Project targets 'netstandard1.5'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.

### ISSUE THREAD

**Issue by ProCrafterZ** [CosmosOS/Cosmos#877]
#### Expected Behaviour - What do you think that should happen?
It should load up with the "Cosmos booted successfully. Type a line of text to get it echoed back."

#### Actual Behaviour - What unexpectedly happens?
It gives an error

#### Reproduction - How did you get this error to appear?
Just making a project and trying to test it out

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? User kit, 2017/09/28

I don't know if this is just something with me or not, but it's frustrating.

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit?

**Comment by ProCrafterZ** [comment]
What do you mean by uninstalling the VS extension?

**Comment by ProCrafterZ** [comment]
I'm so sorry I forgot about this.

I found a solution, actually. I had to download the 4.6.2 framework for Visual studio, which is here: https://www.microsoft.com/net/download/visual-studio-sdks

Im gonna add SOLVED now.
