### ISSUE TITLE
System.ArgumentException after updating

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#878]
Well... When I try to build my project I get an error. First I had a problem with "Directory.Delete()" and I tried to fix that using the solution given at [this issue](https://github.com/CosmosOS/Cosmos/issues/564) (the download link, not the git command). But after installing that I got this error:

> System.ArgumentException: An item with the same key has already been added. Key: assemblysearchdirs

And this is the build output:
[Build Output.txt](https://github.com/CosmosOS/Cosmos/files/1671602/Build.Output.txt)

I'm using the Dev Kit.

Is it possible that I did something wrong when installing that solution or might it be something else?

**Comment by jp2masa** [comment]
Are you using the latest Dev Kit?

**Comment by BL9** [comment]
Tank you jp2masa, I didn't think of that but now it works. I'll keep that in mind to prevent other posts like this from me...
