### ISSUE TITLE
PXE Network Boot function broken

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#88]
Ran a minimalist Cosmos project with the ----Boot project settings set to "PXE Network Boot". The project compiled fine, but then a message box popped up saying "Not enough parameters". Then the following box appeared:
![debug2](https://cloud.githubusercontent.com/assets/4678601/7551444/5239f74e-f656-11e4-8f46-b992e9a73b96.png)
Closing the window brings up a "Visual Studio has stopped working" box, which appears to close nothing.

**Comment by czhower** [comment]
Looks like old code... look at PXE Kudzu. PRobably just needs updated to share the code.

**Comment by ARMmaster17** [comment]
Was never broken in the first place. Should clean up code to represent that. Possibly also auto-resort to the first available IP address on bind failure.
