### ISSUE TITLE
[QUESTION] Drives

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#880]
How do I format an empty drive?

**Comment by jp2masa** [comment]
It's not implemented yet.

**Comment by 365Tito** [comment]
How is the current file system formatted then? Maybe I could figure something out of it?

**Comment by jp2masa** [comment]
You can create an empty disk file in VMware I think.

**Comment by 365Tito** [comment]
So it wont require any additional formatting if I do that?

**Comment by jp2masa** [comment]
Probably it will... You can load the virtual disk in VirtualBox and format it there, using for example Ubuntu.

**Comment by 365Tito** [comment]
Oh okay.
I think that C/C++ can do some low-level disk access and could be used to create a bootable formatting tool that could work well with cosmos. Correct me if I'm wrong.

**Comment by jp2masa** [comment]
I'm planning to implement a feature like that using DiscUtils (for virtual hard disks), but right now I'm still working on other project system features.

**Comment by 365Tito** [comment]
Allright. Thanks and well, good luck on the features!
And I want to add : This community is by far the most helpful that I encountered online.

**Comment by fanoI** [comment]
It should be done in C# and in Cosmos itself so one could implement the "format" command in your OS.
We already manipulate the HDD at low level having implemented FAT, probably format is not too much different.

**Comment by zarlo** [comment]
@365Tito the current file system format is FAT, there was some talk that someone(s) got cosmos able to edit the MBR

**Comment by fanoI** [comment]
Working started on this see: https://github.com/CosmosOS/Cosmos/issues/924
