### ISSUE TITLE
Project with Output Type of Class Library cannot be started directly.

### ISSUE THREAD

**Issue by ProCrafterZ** [CosmosOS/Cosmos#882]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Testing it

#### Expected Behaviour - What do you think that should happen?

It should load normally

#### Actual Behaviour - What unexpectedly happens?

https://i.imgur.com/xaa2m1p.png

#### Reproduction - How did you get this error to appear?

I pressed the run button

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit, Milestone 5 i believe

**Comment by jp2masa** [comment]
Try setting the Boot project as the startup project.

**Comment by Arawn-Davies** [comment]
@ProCrafterZ you may wish to think about updating to a new Cosmos version, MIlestone 5 was released in August 2010, over 7 years ago and things have changed a lot since then, so for current updated support, update to either the latest userkit (20170928) or download the latest dev kit.
