### ISSUE TITLE
[ERROR] Error building cosmos

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#883]
Error during the "Building Cosmos" stage of the setup.
I got the latest Dev kit , XSharp and IL2CPU.
I don't understand why this error occurs.
Here's the uploaded error log:
[Cosmos Error Log.txt](https://github.com/CosmosOS/Cosmos/files/1691701/Cosmos.Error.Log.txt)

**Comment by jp2masa** [comment]
Try updating Visual Studio.

**Comment by 365Tito** [comment]
I did, it works now.
Thanks.
