### ISSUE TITLE
install error 0x00000001

### ISSUE THREAD

**Issue by ThomasBeHappy** [CosmosOS/Cosmos#886]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installer

#### Expected Behaviour - What do you think that should happen?
Cosmos to install

#### Actual Behaviour - What unexpectedly happens?
It giving a error

#### Reproduction - How did you get this error to appear?
By installing it idk why it happens

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User kit if i am correct and the i cloned the git

https://gyazo.com/93a41a26a9c4455d526b98473d00bf7f

**Comment by jp2masa** [comment]
That's the Dev Kit, check the log.

**Comment by ThomasBeHappy** [comment]
here is the log:
https://pastebin.com/1z8KBDAj

**Comment by ThomasBeHappy** [comment]
i figured it out!

**Comment by fanoI** [comment]
So this issue can be closed?

**Comment by Arawn-Davies** [comment]
I believe so, issue opener forgot to clone IL2CPU and presumably XSharp repos (.sln files weren't found). Closing for now, re-open if otherwise.
