### ISSUE TITLE
[QUESTION] BSD-3 Clause and licensing

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#887]
If I'm to make my operating system with cosmos (which is BSD-3 licensed), do I have to make the code for my OS Open source and available for everyone to freely edit and distribute it?

**Comment by 365Tito** [comment]
So OS-es built using Cosmos don't subject to BSD-3 and they don't need to include the BSD-3 clause in their license?

**Comment by jp2masa** [comment]
You have to include the copyright notice I think.

**Comment by 365Tito** [comment]
You mean Copyright C(Year) All rights reserved?

**Comment by jp2masa** [comment]
>Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

**Comment by zarlo** [comment]
cosmos is dual license i think MIT and  BSD-3-Clause

**Comment by 365Tito** [comment]
Wait, does that mean that cosmos itself is licensed in the BSD-3 clause and I need to copy it to my OS' license , but the kernel that I wrote (my code) is licensed by my own terms? I'm really confused right now.

**Comment by jp2masa** [comment]
I think that it doesn't need to be copied to your license, but it has to be distributed with your OS.

**Comment by 365Tito** [comment]
I know that, but I would like to know the following:
- Cosmos, Licensed by BSD-3, written by the contributors of this project is freely available to be modified by anyone and redistributed by anyone as long as the BSD-3 clause is included in the binaries and/or in other form as long as the name(s) of the contributor(s) aren't used to advertise the derivative software.

- The code for my kernel, written by me, licensed by my own license is , for example not available for modification and/or distribution by any means.

Thus:

My OS ships with:

A copy of BSD-3 which is related to the cosmos project.

A copy of my license which is related to the kernel I wrote.

Is this correct?

**Comment by jp2masa** [comment]
I think so.

**Comment by 365Tito** [comment]
Thanks for your time and help @jp2masa  and @zarlo !
