### ISSUE TITLE
[ERROR] Can't run installVS2017.bat

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#889]
I already have cosmos installed.
Running the installVS2017.bat displays the following in the console:

```
Check for installed .NET Framework 4.7.1
Running NuGet restore
MSBuild auto-detection: using msbuild version 4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
All packages listed in packages.config are already installed.
Looking for MSBuild
The syntax of the command is incorrect.
```

Then the console window closes itself (even after I've put pause in the end of the file)...
What gives?

**Comment by Arawn-Davies** [comment]
Could you try using the latest development kit? 

The issue could be detecting whether the host is 32/64-bit, or something different as its had a few fixes and changes regarding finding MSBuild and others.

Or if you can, say which commit of Cosmos you're using so we can see where install.bat is failing exactly.

If not, you might be able to just fetch the latest install-vs2017.bat and replace it, last resort as I'm not sure if it depends on the new changes to the builer

**Comment by 365Tito** [comment]
Nevermind, this was fixed in later commits, but I forgot to close it...
Sorry :)
