### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ehacksprograming** [CosmosOS/Cosmos#891]
i am using cosmos user kit to start developing a os of my own however after i download and ran the instalation.exe  its said finished and thats it where is the files downloaded to on my pc? how do i start using it ?

**Comment by 365Tito** [comment]
@ehacksprograming you need to open up Visual Studio 2017, and make a new project, find the \Cosmos tab under Visual C# and make a new project as you'd normally do it.
Here's a screenshot:

![screenshot 2](https://user-images.githubusercontent.com/29928707/36063993-b1ff60ee-0e84-11e8-8286-94c455ee3a41.jpg)

**Comment by ThomasBeHappy** [comment]
Did this help you @ehacksprograming
