### ISSUE TITLE
Question: How I can create a graphic desktop OS with Cosmos?

### ISSUE THREAD

**Issue by hwoadministrator** [CosmosOS/Cosmos#892]
Can I ask something?
I have one file project for hwov2 but I want to know how I can create a graphical desktop of cosmos, youtube help but not help me, so here the code :
                    //Login Attempts counter
                    int loginAttempts = 0;

                    //Simple iteration upto three times
                    for (int i = 0; i < 3; i++)
                    {
                        Console.WriteLine("Enter username");
                        string username = Console.ReadLine();
                        Console.WriteLine("Enter password");
                        string password = Console.ReadLine();

                        if (username != "hwolearn" || password != "learn123")
                            loginAttempts++;
                        else
                            break;
                    }

                    //Display the result
                    if (loginAttempts > 2)
                        Console.WriteLine("Login failure");
                    else
                        Console.WriteLine("Login successful");

                    Console.ReadKey();
                }
If it login okay how can I move user can log in to the desktop, and that anything can help me create my desktop?

**Comment by Remco123** [comment]
For the graphics you need this: https://www.gocosmos.org/docs/cosmos-graphic-subsystem/

**Comment by fanoI** [comment]
The idea is that CGS offers to yet the low level building blocks to create a simple widget toolkit before being really usable for this you will need to things than need yet to be implemented:

1. Bitmap image support
2. Text drawing support (better if using standard truetype fonts)

**Comment by hwoadministrator** [comment]
Remco I have seen it in the doc of cosmos. However, it not working correctly with me because my version is 2017 for visual studio. Canvas not working and give me an error.

**Comment by hwoadministrator** [comment]
Fanol, can you give me some example please. I have tried something of StackOverflow. But it doesn't give me the idea better than.
My Idea is to have one project have a desktop same to kali or windows or have mouse and desktop working in a graphic.Canvas doesn't have any because VS2017 gives an errors always with it.

**Comment by DeafMan1983** [comment]
Check [SphereOS](https://github.com/Sphere-Systems/SphereOS)  and it has graphical operating system.
