### ISSUE TITLE
Installing Devkit

### ISSUE THREAD

**Issue by Honzecki** [CosmosOS/Cosmos#893]
#### Actual Behaviour - Even when i have newest .NET Framework installed (4.7.1) it says i dont have it...

![image](https://user-images.githubusercontent.com/30354910/36351223-eb53a65c-14a6-11e8-86ac-e0c938796a74.png)

**Comment by foxclore** [comment]
I had this problem too, try to download .net runtime

**Comment by foxclore** [comment]
https://github.com/CosmosOS/Cosmos/issues/821

**Comment by fanoI** [comment]
Do you have all the needed pre-requisites for the DevKit? Read here: https://www.gocosmos.org/docs/install/

**Comment by Honzecki** [comment]
Yes i  do,

**Comment by Honzecki** [comment]
By the way, i got same issue as on #821 BUT, i have extension downloaded...

**Comment by fanoI** [comment]
You have the NET Core 2.0 SDK installed but Net Core is not found?

**Comment by Honzecki** [comment]
Yes,

**Comment by jp2masa** [comment]
You need to install the .NET Core cross-platform development VS workload.

**Comment by Arawn-Davies** [comment]
Has this issue been resolved?

**Comment by Honzecki** [comment]
Nope,

**Comment by Honzecki** [comment]
jp2masa I have that installed...

**Comment by jp2masa** [comment]
Then maybe the VS installation needs to be repaired? Try creating a .NET Core console application in VS and running it. If it works, then try either repairing (slower) or uninstalling and then installing the .NET Core workload in the VS installer (faster). If it doesn't work, then you don't have the workload installed.

**Comment by Honzecki** [comment]
I Checked it by running cmd and typing dotnet, all should work.

**Comment by Honzecki** [comment]
Repaired, and tested by writing dotnet in cmd. 
![image](https://user-images.githubusercontent.com/30354910/36859552-023a23ec-1d7f-11e8-82e0-c21d9384cf3c.png) I Have it...

**Comment by jp2masa** [comment]
That's the Visual Studio extension development workload. You need the .NET Core cross-platform development one too.

**Comment by Honzecki** [comment]
Ohh! That might be the issue...

**Comment by Honzecki** [comment]
Well, After reinstalling Visual Studio (Because i was dumb and changed something...) it WORKS!!! Thanks all for support :)
