### ISSUE TITLE
QEMU Integration

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#895]
Permit to debug a kernel using QEMU similarly as how is done with VmWare and Bochs.

**Comment by Arawn-Davies** [comment]
QEMU was used back in the Milestone days so should be easy to re-add the deployment profile


https://github.com/CosmosOS/XSharp/tree/master/source/XSharp.Launch/Hosts/Bochs https://github.com/CosmosOS/Cosmos/tree/master/source/Cosmos.Debug.Hosts

**Comment by fanoI** [comment]
Well I fear a lot has changed but you can try. Please talk with @charlesbetros that should have something practically ready.

**Comment by nathanpapke** [comment]
I wish I had more time because this is something I was wanting to contribute to.  If there's a key step to porting Cosmos to Raspberry Pi and other platforms using the ARM processor, I feel this would be it.

**Comment by czhower** [comment]
We had QEMU support before but the Windows build had a critical bug and the QEMU guys simply dont care about windows. It was a one line source fix and over a period of several years could not be bothered to fix it. We had to make custom Windows builds which is very complicated setup with C++ and mingw among others.

Enabling QEMU support is very easy, but given that they don't care at all about their Windows version, its not something we want to depend on.

Bochs supports ARM and Bochs is one of our primary targets now. Is there a reason Bochs cant be used which is far better supported than QEMU?

http://bochs.sourceforge.net/related.html

**Comment by Kiirx** [comment]
Can be closed
