### ISSUE TITLE
Error in compiling a bootable iso

### ISSUE THREAD

**Issue by internationalOS** [CosmosOS/Cosmos#897]
Hi, I use the most updated version of the devkit. If I try to compile the project in order to create a bootable iso, I get this error:

1>------ Inizio compilazione: Progetto: int.OS, Configurazione: Debug Any CPU ------
1>int.OS -> C:\Users\Leonardo Baldazzi\source\repos\intOS\int.OS\int.OS\bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\int.OS.dll
1>Invoking IL2CPU.exe "KernelPkg:" "EnableDebug:False" "EnableStackCorruptionDetection:True" "StackCorruptionDetectionLevel:MethodFooters" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:C:\Users\Leonardo Baldazzi\source\repos\intOS\int.OS\int.OS\bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\int.OS.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Leonardo Baldazzi\source\repos\intOS\int.OS\int.OS\bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\int.OS.dll" "References:C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\cosmos.common\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\cosmos.core\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\cosmos.debug.kernel\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\cosmos.hal2\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\cosmos.system2\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Leonardo Baldazzi\.nuget\packages\il2cpu.api\2018.2.11\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\\"
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking Reference: C:\Users\Leonardo Baldazzi\source\repos\intOS\int.OS\int.OS\bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\int.OS.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Leonardo Baldazzi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>Message:   Exists
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>-relaxed-filenames -J -R -o bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\int.OS.iso -b isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\ISO
1>mkisofs : warning : -rock has same effect as -rational-rock on this platform.
1>MAKEISO : warning : creating filesystem that does not conform to ISO-9660.
1>Size of boot image is 4 sectors -> No emulation
1>Total translation table size: 2048
1>Total rockridge attributes bytes: 751
1>Total directory bytes: 1146
1>Path table size(bytes): 10
1>1018 extents written (1 MB)
1>Compilazione progetto "int.OS.csproj" completata.
========== Compilazione: 1 completate, 0 non riuscite, 0 aggiornate, 0 ignorate ==========

Some idea?

I'm sorry if you do not understand much but my English is not the best :)

**Comment by jp2masa** [comment]
There's no error.

**Comment by fanoI** [comment]
The ISO is generated in <your_os_name>bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\ISO? Or not?

**Comment by internationalOS** [comment]
in bin\Debug\netcoreapp2.0\iso\netcoreapp2.0\ISO thre isn't it

**Comment by internationalOS** [comment]
![cattura](https://user-images.githubusercontent.com/33204976/36389472-71b7403e-159f-11e8-98eb-19a251965b22.PNG)
New error.......

**Comment by jp2masa** [comment]
I'll investigate that now. I think I know what's happening.

**Comment by jp2masa** [comment]
I pushed a fix, it should be working now.

**Comment by internationalOS** [comment]
it's working now, thank you

**Comment by internationalOS** [comment]
![cattura](https://user-images.githubusercontent.com/33204976/36392527-004ffdb6-15ac-11e8-97e0-7cba5d4f1dcc.PNG)

An other  error........

**Comment by internationalOS** [comment]
It worked for 30 minutes, is not that by chance it's a problem of my code?

**Comment by jp2masa** [comment]
Try restarting VS.

**Comment by fanoI** [comment]
@internationalOS if you need help in Italian feel free to PM me, it is my native tongue :-)

**Comment by internationalOS** [comment]
Grazie, mi aiuteresti moltissimo @fanoI

**Comment by internationalOS** [comment]
Dove ti posso contattare?
