### ISSUE TITLE
.NET and Extension error

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#898]
Hello I am tring to install Cosmos but ever time I open the install-VS2017.bat I get the folowing error

> 

===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

=====
Error
=====

.NET Core not detected.
Visual Studio Extension tools not detected.
> 

I have no idea how to fix this... well I know what I need to do but what files do I have to install to make these two errors leave?

**Comment by zarlo** [comment]
its not an error you need to download them if you have you may need to restart your system

**Comment by FlamingBurrito15** [comment]
ok also is there a specific extension I need to download?

**Comment by FlamingBurrito15** [comment]
hey so I restarted my computer and it did not fix the errors and yes I did install .NET Core

**Comment by jp2masa** [comment]
You need to install the .NET Core cross-platform development workload and the Visual Studio extension tools workload in VS.

**Comment by FlamingBurrito15** [comment]
ok thanks I will try that

**Comment by jp2masa** [comment]
Can this issue be closed?
