### ISSUE TITLE
No option to disable debugger with PXE profile

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#90]
Both enabling and disabling the Debug->Enable Remote Debugging option when using the PXE profile still shows the "Waiting for debugger connection..." screen on boot. Using latest devkit (5/9/15).

**Comment by ARMmaster17** [comment]
Same issue is also present for the "Enable Stack Corruption Detection" box.

**Comment by mterwoord** [comment]
@ARMmaster17 Can you verify? Probably it's a much more generic issue with the settings page, which I've suspected for a while.
