### ISSUE TITLE
Debugging error

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#900]
Hello so I installed Cosmos and I tried to debug it and I get an "Assertion Failed Abort, Ignore, Retry" I would write  what it says but it is REALLY long and I can not copy/paste it... I seen screenshots on tutorials and they have kernel.cs and AssemblyInfo.cs I don't have the AssemblyInfo.cs would that be the issue?

Output:

> 1>------ Build started: Project: MyOSBoot, Configuration: Debug Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\net462\MyOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\netstandard1.5\MyOS.dll" 
1>	Executing command line "C:\Users\flami\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\net462\MyOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\flami\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\netstandard1.5\MyOS.dll" 
1>	Working directory = 'C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'
1>	Rings: Start check
1>	Rings: Assembly 'Cosmos.System'
1>	Rings:         Ring = System
1>	Rings:     Dependency 'Cosmos.HAL'
1>	Rings:         Ring = HAL
1>	Rings: Assembly 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Rings: Assembly 'MyOS'
1>	Rings:         Ring = User
1>	Rings:     Dependency 'Cosmos.System'
1>	Rings:         Ring = System
1>	Rings: Assembly 'Cosmos.HAL'
1>	Rings:         Ring = HAL
1>	Rings:     Dependency 'Cosmos.Core'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Rings: Assembly 'Cosmos.Core'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Rings: Assembly 'Cosmos.Core.Plugs'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Memory'
1>	Rings:         Ring = Core
1>	Rings: Assembly 'Cosmos.System.Plugs'
1>	Rings:         Ring = System
1>	Rings:     Dependency 'Cosmos.System'
1>	Rings:         Ring = System
1>	Rings:     Dependency 'Cosmos.HAL'
1>	Rings:         Ring = HAL
1>	Rings: Assembly 'Cosmos.Core.Memory'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Rings: Assembly 'Cosmos.Core.Plugs.Asm'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core'
1>	Rings:         Ring = Core
1>	Rings:     Dependency 'Cosmos.Core.Common'
1>	Rings:         Ring = Core
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.INT3Label'
1>	Executed OK
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:31.6410077
1>	NAsm task took 00:00:13.3912332
1>	Executing command line "C:\Users\flami\AppData\Roaming\Cosmos User Kit\Build\tools\cygwin\ld.exe" -Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o 'C:/Users/flami/source/repos/MyOS/MyOS/bin/Debug/net462/MyOSBoot.bin' 'C:/Users/flami/source/repos/MyOS/MyOS/bin/Debug/net462/MyOSBoot.obj'
1>	Working directory = 'C:\Users\flami\source\repos\MyOS\MyOS\bin\Debug\net462\'
1>	Ld task took 00:00:00.9086195
1>	Extracting Map file took 00:00:15.2061596
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

>

**Comment by jp2masa** [comment]
It's probably a bug in the project system or debug engine, do you have a screenshot of the error message?

**Comment by FlamingBurrito15** [comment]
Yes I do have a screenshot of the error
![screenshot 20](https://user-images.githubusercontent.com/33473023/36562541-503c25b2-17e5-11e8-8735-d1a5ed797c16.png)

**Comment by jp2masa** [comment]
You need to install VMware.

**Comment by FlamingBurrito15** [comment]
Ok thanks 😄

**Comment by jp2masa** [comment]
Can this issue be closed?
