### ISSUE TITLE
Other VM software that works?

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#903]
This is more of a question than an issue but can I use a different VM software such as Bochs to debug the code because VMware does not work for me... If I can how would I be able to?

**Comment by fanoI** [comment]
Bochs is directly supported by Cosmos, select it in the project properties page.

**Comment by FlamingBurrito15** [comment]
Ok thanks 😄

**Comment by jp2masa** [comment]
Can this issue be closed?
