### ISSUE TITLE
Devkit failing to install

### ISSUE THREAD

**Issue by AlexMacafee** [CosmosOS/Cosmos#904]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Devkit Installation

#### Expected Behaviour - What do you think that should happen?
Installation to go through, I have all required components installed, including .NET 4.7.1

#### Actual Behaviour - What unexpectedly happens?
The installation wont find the .net 4.7.1 framework, I've reinstalled it many times but still nothing.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

![capture](https://user-images.githubusercontent.com/29278620/36622511-a38e9d72-1951-11e8-8a2a-59a046f64539.PNG)

**Comment by jp2masa** [comment]
Try this change: https://github.com/CosmosOS/Cosmos/commit/ba59a99cae10087ec4a9e1862e21af2ec964288c.

**Comment by AlexMacafee** [comment]
@jp2masa Yes that working but now im getting a massive error once the installation begins, Ive attached the log

[log.txt](https://github.com/CosmosOS/Cosmos/files/1753719/log.txt)

**Comment by jp2masa** [comment]
You need to clone Cosmos, IL2CPU and XSharp in parallel, it should look like this:

Cosmos (or other name)
|-- Cosmos
|-- IL2CPU
|-- XSharp

These commands should work:
```
mkdir Cosmos
cd Cosmos
git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git
```

**Comment by AlexMacafee** [comment]
That worked perfectly, thankyou!

Sorry about the rookie question, new to using git and using the dev kit.

**Comment by Arawn-Davies** [comment]
If you've got more questions on anything, feel free to ask :)
