### ISSUE TITLE
Error occurred while invoking IL2CPU

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#907]
I am trying to compile a simple part of code (Literally just the template) and when I build it in debug mode it has no errors but when I put it in qemu it says "Waiting for debugger connection..." so I figured it was because I compiled it in debug, so  I built it in release and I get the error "Error occurred while invoking IL2CPU" and if I build it in debug it says the same thing to fix it (so I can build in debug) I have to make a new project because I can't stop the error any other way... any ideas on how to make this error stop appearing?

**Comment by jp2masa** [comment]
The `Release` configuration isn't currently supported. You can disable debugging in the project properties. Try rebuilding the project.

**Comment by FlamingBurrito15** [comment]
Ok thanks I will try that

**Comment by FlamingBurrito15** [comment]
Wait how would I disable debugging in the properties?

**Comment by Arawn-Davies** [comment]
Right click on your project's .csproj file, and click Properties. A window should appear which lists the available Debug profiles, including Bochs, VMWare, PXE etc. On the currently used profile, disable Remote Debugging and rebuild. This is how it is done, however there is an issue with the option not being taken into effect which needs resolving.

**Comment by FlamingBurrito15** [comment]
Thanks it worked (sorry for late response)
