### ISSUE TITLE
Autoselect IP address

### ISSUE THREAD

**Issue by ARMmaster17** [CosmosOS/Cosmos#91]
For the Pixie PXE tool, in the event that the requested IP address is not bind-able, Get a list of the available IP addresses in the system and select the first non-loopback address.

**Comment by mterwoord** [comment]
I'd prefer not to automagically guess the interface to bind on, but just present with a list of interfaces. Like #92

**Comment by ARMmaster17** [comment]
That's a good idea. This could lead to some frustrating problems for end-users.
