### ISSUE TITLE
[QUESTION] How can I add cut, copy and paste

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#910]
I was just wondering if I could add cut, copy and paste in my OS for the files and folders? Also is there like a site that shows the code for stuff like that?

**Comment by Arawn-Davies** [comment]
Cosmos makes use of the .NET Core framework's System.IO for File operations, so you check out https://msdn.microsoft.com/en-us/library/system.io.file(v=vs.110).aspx to find methods to use. I'm not sure if File.Move has been plugged yet, but for now I just use 
```
File.Copy(string src, string dest);
File.Delete(string file);
```
As for a 'clipboard' like other OSes use, you may want to maybe store a file's path as a string, and use the above mentioned methods using that string.

Hope this helps :)

**Comment by FlamingBurrito15** [comment]
Ok thanks I will check out this link :smile:

**Comment by WyattSteinmann** [comment]
Here Is A Simple Method To Copy/Move:

using Sys = Cosmos.System;

// Keep In Mind I Used This For My Command System In My OS Its Not Out Yet As Of 12/29/2024 and also it was originally in a switch so thats why the formatings bad

public static string Move(string[] args)
{
try
{
if (args.Length != 3)
return "Usage: file copy ";
if (!Sys.FileSystem.VFS.VFSManager.FileExists(Kernel.Path + args[1]))
return "File does not exist.";
FileStream fs = (FileStream)Sys.FileSystem.VFS.VFSManager.GetFile(Kernel.Path + args[1]).GetFileStream();
if (fs.CanRead)
{
byte[] data = new byte[fs.Length];
fs.Read(data, 0, data.Length);
fs.Close();
Sys.FileSystem.VFS.VFSManager.CreateFile(Kernel.Path + args[2]);
FileStream fs2 = (FileStream)Sys.FileSystem.VFS.VFSManager.GetFile(Kernel.Path + args[2]).GetFileStream();
if (fs2.CanWrite)
{
fs2.Write(data, 0, data.Length - 1);
fs2.Close();
return "Copyed file "" + args[1] + "" successfully.";
}
}
return "Can not copy write-only/read-only/closed file.";
}
catch (Exception ex)
{
return ex.Message;
}
}
public static string Copy(string[] args)
{
try
{
if (args.Length != 3)
return "Usage: file move ";
if (!Sys.FileSystem.VFS.VFSManager.FileExists(Kernel.Path + args[1]))
return "File does not exist.";
FileStream fs = (FileStream)Sys.FileSystem.VFS.VFSManager.GetFile(Kernel.Path + args[1]).GetFileStream();
if (fs.CanRead)
{
byte[] data = new byte[fs.Length];
fs.Read(data, 0, data.Length);
fs.Close();
Sys.FileSystem.VFS.VFSManager.CreateFile(Kernel.Path + args[2]);
FileStream fs2 = (FileStream)Sys.FileSystem.VFS.VFSManager.GetFile(Kernel.Path + args[2]).GetFileStream();
if (fs2.CanWrite)
{
fs2.Write(data, 0, data.Length - 1);
fs2.Close();
Sys.FileSystem.VFS.VFSManager.DeleteFile(Kernel.Path + args[1]);
return "Moved file "" + args[1] + "" successfully.";
}
}
return "Can not copy write-only/read-only/closed file.";
}
catch (Exception ex)
{
return ex.Message;
}
}

**Comment by WyattSteinmann** [comment]
this works too
