### ISSUE TITLE
Regex Crash

### ISSUE THREAD

**Issue by djlw78** [CosmosOS/Cosmos#911]
#### Reproduction - Type the following code in run
` Regex regex = new Regex(@"\d+");
        Match match = regex.Match("Dot 55 Perls");
        if (match.Success)
        {
            Console.WriteLine(match.Value);
        }
`

#### Version - ** DEV KIT ** (edit: was userkit I actually use Aura's version but it follows the same)

**Comment by jp2masa** [comment]
This is a duplicate of #588.
