### ISSUE TITLE
[QUESTION] How to clear the screen

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#915]
I was wondering what was the code to clear all of the text on screen?

**Comment by AlexMacafee** [comment]
Use Console.Clear();

**Comment by FlamingBurrito15** [comment]
Ok thanks I will try that

**Comment by FlamingBurrito15** [comment]
Update: Console.Clear() did not do anything...

**Comment by jp2masa** [comment]
You're trying to clear the screen using CGS?

**Comment by FlamingBurrito15** [comment]
Also is there a way I can tell what key was pressed on the keyboard (i.e. user presses 'H' button output "You pressed 'H'!" Without Console.ReadLine();)

**Comment by FlamingBurrito15** [comment]
What is CGS?

**Comment by jp2masa** [comment]
https://www.gocosmos.org/docs/cosmos-graphic-subsystem/

**Comment by FlamingBurrito15** [comment]
No it is just text based

**Comment by jp2masa** [comment]
Then `Console.Clear()` should do what you want. To read keys, you can use `Console.ReadKey()`;

**Comment by FlamingBurrito15** [comment]
Ok thanks
