### ISSUE TITLE
[QUESTION] How can I add buttons to CGS?

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#917]
Hello I decided to try CGS and I got the shapes to show and now I am trying to add other things such as buttons mainly and pictures I have checked out this link for the button part
https://www.gocosmos.org/docs/cosmos-graphic-subsystem/creating-a-gui-btnsmnu/  but when I tried to add what it showed I got errors. So how would I add buttons and pictures (such as PNG)

**Comment by quajak** [comment]
Images are not supported. I am working on getting bitmaps working. Buttons could just be rectangles. If a use clicks you then check if it was in the bounds of the rectangle and handle the button click.

**Comment by FlamingBurrito15** [comment]
Ok thanks
