### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by ajcreeper** [CosmosOS/Cosmos#921]
#### Area of Cosmos - What area of Cosmos are we dealing with?
dev kit installer

#### Expected Behaviour - What do you think that should happen?
installing cosmos

#### Actual Behaviour - What unexpectedly happens?
it occurs conflicts with references

#### Reproduction - How did you get this error to appear?
trying to install it

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
dev kit and the commit d0f8fa85c313694c3224d5a8149f7eb7e719efd9

Evidence:
[log.txt](https://github.com/CosmosOS/Cosmos/files/1776889/log.txt)

**Comment by jp2masa** [comment]
Make sure you're using latest master from Cosmos and IL2CPU.

**Comment by ajcreeper** [comment]
after setting up the folders, i am now getting it to work
i forgot to rename cosmos-master to cosmos
