### ISSUE TITLE
Creating gui error

### ISSUE THREAD

**Issue by FlamingBurrito15** [CosmosOS/Cosmos#923]
I am trying to make a GUI from this tutorial https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI-The-basics but the issue is when I add "display = new DisplayDriver(); display.init();" I get an error on both "display" and also "public virtual byte getPixel" and other ones alike have to be "public virtual byte GetPixel" (cannot have lower case). How would I fix this?

**Comment by Project-Magenta** [comment]
It is old

**Comment by Project-Magenta** [comment]
https://github.com/CosmosOS/Cosmos/wiki/Creating-a-GUI-using-CGS%3A-Starting-our-GUI

**Comment by FlamingBurrito15** [comment]
Ok thanks I will try this one :smile:
