### ISSUE TITLE
Cosmos DiskManager

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#924]
The idea of DiskManager is to give the possibility to do the same things you will do with this Windows utility:

![](https://fthmb.tqn.com/FECjEWnjzMEweXyhTl_wZHAqXXw=/768x0/filters:no_upscale()/disk-management-windows-10-58a5d33a3df78c345b052f96.PNG)

(or if you prefer the Unix fdisk utility features)

so we need:

- [x] List Volumes
- [x] Format Volume
- [x] Create Partition
- [x] Set / Get Volume Letter
- [x] Set / Get Volume Label

some of these functionalities are already present in .NET in the class DriveInfo so we will start making that working.

**Comment by Arawn-Davies** [comment]
Could this be done as an abstract class? Seeing as virtual filesystems are easily made with the Filesystem class, would some functions be filesystem type specific or would it just be one disk manager that can do things regardless of the used filesystem?

**Comment by fanoI** [comment]
I'd say only one DiskManager a lot of these things will be simply calls to Cosmos VFSManager that know what is the underlying filesystem the drive has.

**Comment by TheUnknown-007** [comment]
Any updates?

**Comment by MishaTY** [comment]
Implemented in cosmos vfs api
