### ISSUE TITLE
[Discussion] Make a working PCNETII driver.

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#926]
I submit this to try to centralize the information in order to find a solution to this problem. 

The driver is located [here](https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs). 

Since the new PCI implementation me and my team succeed to find and start the AMD PCNETII driver and get some information with that driver like MAC address. But the problem is we can't handle anything, the handler is defined [here](https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs#L100). But we did many tests and we've never been able to invoke the HandleNetworkInterrupt method.

I think the problem is in the PCI implementation (that maybe blocks the driver initialization) or in the Interrupt system or we're just too stupid to send something to the network card.. 

PS: We did our tests [here](https://github.com/aura-systems/Cosmos/tree/impl-basicnetworking).

**Comment by fanoI** [comment]
Do you have registered the IRQ handler to call your method?
For example look at https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL2/PS2Keyboard.cs#20, you have a similar method in your class but it is commented.

Maybe you should hinerit from NetworkDevice instead of Device:https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL2/NetworkDevice.cs

**Comment by valentinbreiz** [comment]
Yes I registered it like the keyboard. And the NetworkDevice.cs file can be used for multiple drivers but we don't need it without the ring system.

**Comment by Project-Magenta** [comment]
In their test: https://github.com/aura-systems/Cosmos/blob/impl-basicnetworking/source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs#L99

**Comment by fanoI** [comment]
How you indeed send something to the network card? I imagine it has not an IP assigned yet so... how you do this?

**Comment by valentinbreiz** [comment]
I don't know how.

**Comment by valentinbreiz** [comment]
![image](https://user-images.githubusercontent.com/18724279/37257275-7cbaa214-2567-11e8-909a-e5d7c3e16218.png)

@fanoI, PCI scan detected the network card, detected the right interrupt line, read the correct MAC address. But the driver still seems not usable.

**Comment by fanoI** [comment]
But your network card has already an IP? What are Src and Dest?

If there is an IP you can try to ping the card from another machine and see if it reacts, it seems all correct to me so maybe is simple a problem of "how I test it?"

**Comment by mterwoord** [comment]
Pinging also needs implementations. I'd suggest use wireshark to see what's
going on...


2018-03-15 10:10 GMT+01:00 fanoI <notifications@github.com>:

**Comment by valentinbreiz** [comment]
Nothing seems happen with Wireshark.

**Comment by geomtech** [comment]
https://github.com/aura-systems/Aura-Operating-System/blob/e8ee799e0b4bb6e0803de38777a0d00e1acd6745/Aura%20Operating%20System/Aura%20OS/Shell/cmdIntr/CommandManager.cs#L185

**Comment by fanoI** [comment]
You are giving the IP ourselves not joining a network (it should be your router in DHCH or static to give you an IP) if no external device will see you.

**Comment by geomtech** [comment]
Yeah but you don't need a router if the computer is connected to a switch, and it can communicate with the others... So we don't need DHCP. Here it's in static. The others computers will see me with ARP (broadcasting).

**Comment by valentinbreiz** [comment]
@geomtech it's not the good branch :P 
https://github.com/aura-systems/Aura-Operating-System/blob/test-network/Aura%20Operating%20System/Aura%20OS/Shell/cmdIntr/CommandManager.cs#L183
