### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SapphireGitHub** [CosmosOS/Cosmos#927]
I took a break from COSMOS, but now I'm back. I am installing the latest Dev Kit, and I got this error.

===================
Check Prerequisites
===================

Check if User Kit Installer is already running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor

================
Init Directories
================

Cleaning up existing VSIP directory.
Creating VSIP as C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Build\VSIP
Cleaning up existing User Kit directory.
Creating User Kit as C:\Users\Brent\AppData\Roaming\Cosmos User Kit

======================
Clean NuGet Local Feed
======================

Starting: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Build\Tools\nuget.exe
  Params: sources List
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

======================
Restore NuGet Packages
======================

Starting: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Build.sln"
MSBuild auto-detection: using msbuild version '15.6.82.30579' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\IL2CPU\source\IL2CPU\IL2CPU.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\XSharp\source\XSharp\XSharp.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\XSharp\source\Spruce\Spruce.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\XSharp\source\XSharp.x86\XSharp.x86.csproj cannot be found.
WARNING: Project file C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\..\XSharp\source\VSPropertyPages\VSPropertyPages.csproj cannot be found.
Committing restore...
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.MSBuild\obj\project.assets.json
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Tests\Cosmos.TestRunner.TestController\obj\project.assets.json
Restore completed in 91.17 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj.
Restore completed in 93.95 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Common\obj\project.assets.json
Restore completed in 6.86 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Common\Cosmos.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Tasks\obj\project.assets.json
Restore completed in 18.52 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core.DebugStub\obj\project.assets.json
Restore completed in 6.52 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core\obj\project.assets.json
Restore completed in 7.16 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core\Cosmos.Core.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Asm\obj\project.assets.json
Restore completed in 8.5 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Plugs\obj\project.assets.json
Restore completed in 48.81 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Common\obj\project.assets.json
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Common\obj\project.assets.json
Restore completed in 239.49 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
Restore completed in 43.65 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Tools\NASM\obj\project.assets.json
Restore completed in 250.36 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Tools\NASM\NASM.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.DebugConnectors\obj\project.assets.json
Restore completed in 28.14 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel\obj\project.assets.json
Restore completed in 8.05 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.HAL2\obj\project.assets.json
Restore completed in 8.98 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\obj\project.assets.json
Restore completed in 27.2 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2_Plugs\obj\project.assets.json
Restore completed in 7.28 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\obj\project.assets.json
Restore completed in 56.09 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\obj\project.assets.json
Restore completed in 41.44 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.Windows\obj\project.assets.json
Restore completed in 24.27 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\TheRingMaster\obj\project.assets.json
Restore completed in 13.07 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\TheRingMaster\TheRingMaster.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\obj\project.assets.json
Restore completed in 341.47 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2\obj\project.assets.json
Restore completed in 378.5 ms for C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.System2\Cosmos.System2.csproj.

NuGet Config files used:
    C:\Users\Brent\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/cosmos/api/v3/index.json
Starting: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\Build\Tools\nuget.exe
  Params: restore "C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\../IL2CPU/IL2CPU.sln"
Input file does not exist: C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\../IL2CPU/IL2CPU.sln.

=====
Error
=====

Console returned exit code. (0x00000001)
   at Cosmos.Build.Installer.Task.StartConsole(String aExe, String aParams) in C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 94
   at Cosmos.Build.Builder.CosmosTask.Restore(String project) in C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 296
   at Cosmos.Build.Builder.CosmosTask.CompileCosmos() in C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 326
   at Cosmos.Build.Builder.CosmosTask.DoRun() in C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\CosmosTask.cs:line 71
   at Cosmos.Build.Installer.Task.Run() in C:\Users\Brent\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.Build.Installer\Task.cs:line 16

Can anyone help?

**Comment by fanoI** [comment]
Please read here it is all clearly explained: https://www.gocosmos.org/docs/install/

**Comment by SapphireGitHub** [comment]
I think I found the problem using the article. I have installed IS standalone rather than the pack specified. If not, IDK what it is, I looked at the article, but I might look a second time.

**Comment by fanoI** [comment]
You have IL2CPU and X# repro near your Cosmos folder? 

For example in this way:

c:\source\Cosmos\
c:\source\Cosmos\Cosmos\ – Git Repository for Cosmos
c:\source\Cosmos\IL2CPU\ – Git Repository for IL2CPU
c:\source\Cosmos\XSharp\ – Git Repository for XSharp
