### ISSUE TITLE
osBoot (incompatible)

### ISSUE THREAD

**Issue by IanSteg** [CosmosOS/Cosmos#928]
#### Area of Cosmos - What area of Cosmos are we dealing with?
osBoot

#### Expected Behaviour - What do you think that should happen?
Everything to work.

#### Actual Behaviour - What unexpectedly happens?
When the project is opened in VS2017, the osBoot project is 'incompatible'

![image](https://user-images.githubusercontent.com/25563128/37400339-5d7d6786-27d0-11e8-9055-2d88cfe33b3b.png)

#### Reproduction - How did you get this error to appear?
I don't know.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Dev Kit.

**Comment by Remco123** [comment]
The newest Dev Kit uses a new project system so you need to upgrade your project to the new version.

**Comment by IanSteg** [comment]
Ok, how do I do that?

**Comment by Remco123** [comment]
I think that someone had a project upgrader (not sure) but you can always create a new project en copy the kernel file.

**Comment by zarlo** [comment]
go into add cosmos.build to you boot project not the old one

**Comment by IanSteg** [comment]
I just created a new project and copied the code across. Thanks.
