### ISSUE TITLE
New Codebase Already Solves CGS Problems?

### ISSUE THREAD

**Issue by Dark-Tater** [CosmosOS/Cosmos#936]
#### Area of Cosmos - What area of Cosmos are we dealing with?
-Cosmos Graphics Subsystem

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
-Devkit, built form source
-Trunk, as of writing this message-

#### Reason for Opening an Issue
I think this person just solved all of our 2d-pure-C#-font-rendering-and-graphics problems forever. He seems extremely knowledgeable on the subject of pure C# graphics (and particularly super-slick-looking font rendering). And the best part? Everything he has collected, improved, gathered, and done is ALL permissively licensed, with no GNU, GPL, or other copy-left code of any kind whatsoever, which means we can freely use it in Cosmos.
See the main project: [PaintLab/PixelFarm](https://github.com/PaintLab/PixelFarm)
Or see the typography-rendering-only sub-library: [LayoutFarm/Typography](https://github.com/LayoutFarm/Typography)
He has several other sub-libraries under the "LayoutFarm" account, as well, such as [LayoutFarm/HtmlRenderer]( https://github.com/LayoutFarm/HtmlRenderer).

What do you think? I haven't looked into the code yet, and it could use some polishing, but I think this might do like 90% of the work we are trying to make the CGS do for us already.

Tell me your thoughts, and thanks for your many, many hours of hard work creating Cosmos!

Dark-Tater

**Comment by Project-Magenta** [comment]
etc. OpenGL

**Comment by jp2masa** [comment]
These libraries won't help CGS directly, but they may be used on top of CGS in the future, and some code there may be helpful during the development of CGS. I'll reopen the issue as it may be useful in the future.
