### ISSUE TITLE
Build Errors on Latest Commit

### ISSUE THREAD

**Issue by Dark-Tater** [CosmosOS/Cosmos#940]
#### Area of Cosmos - What area of Cosmos are we dealing with?
-The whole thing-

#### Expected Behaviour - What do you think that should happen?
-Cosmos should build and install Visual Studio extensions properly.-

#### Actual Behaviour - What unexpectedly happens?
-The build process is aborted with an error stating that a certain `\"%rootdir%\Cosmos\.\Build\VSIP\NASM\*\" directory does not exist`.-

#### Reproduction - How did you get this error to appear?
-I cloned Cosmos, IL2CPU, and XSharp into a root directory called "Cosmos", then ran the "install-VS2017.bat" file to install Cosmos.-

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
-Dev kit-
-Commit: c4c6984eaaf9f4c8dc203596804c3b3d090fc812-

#### Installation Logs
[New Text Document (3).txt](https://github.com/CosmosOS/Cosmos/files/1862362/New.Text.Document.3.txt)

**Comment by jp2masa** [comment]
It should be working now.
