### ISSUE TITLE
IL2CPU Plug required error

### ISSUE THREAD

**Issue by CSharpandLua** [CosmosOS/Cosmos#946]
#### Area of Cosmos - What area of Cosmos are we dealing with?

IL2CPU/PLUGS

#### Expected Behaviour - What do you think that should happen?

It should build and run like a normal console application would run it

#### Actual Behaviour - What unexpectedly happens?

When i got the error, I assumed i had been using something that needed a plug... So i gradually removed more and more methods until i only had a few that i knew worked, which was when i removed all the dependencies, then i removed **EVERYTHING** until it was just spaces, and it still errors!
**EDIT:** 
I forgot to mention this project built successfully about an hour or two before

#### Reproduction - How did you get this error to appear?

Im not sure, I seem to get it sometimes and not other times, but this time i removed everything and still get the error... I do this for fun, But getting obsessed with futile attempts to fix an error isn't going to be fun considering the amount of times iv'e had to hunt down errors

**Comment by jp2masa** [comment]
Check the output window.

**Comment by CSharpandLua** [comment]
What do you think im doing?! The only error is IL2CPU, and thats even when i remove everything down to literally nothing

**Comment by jp2masa** [comment]
What's the error message in the output window?

**Comment by CSharpandLua** [comment]
I said it already, Native code encountered plug required.. including when i remove everything

**Comment by quajak** [comment]
Could you give us a copy of the code.

**Comment by CSharpandLua** [comment]
@quajak It depends if you want nothing or not, because this time i removed everything and it still does it

**Comment by CSharpandLua** [comment]
Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.String  System.Number.FormatDecimal(System.Decimal, System.String, System.Globalization.NumberFormatInfo).
2>	 Called from :
2>	System.Decimal::System.String ToString()
2>	System.Decimal
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197

**Comment by jp2masa** [comment]
`Decimal` is not supported.

**Comment by jp2masa** [comment]
Actually, if you're using the user kit, the problem may be `Convert`.

**Comment by CSharpandLua** [comment]
Im not using decimal
and im not using convert

**Comment by CSharpandLua** [comment]
i have told you MULTIPLE times that i have removed every last piece of code until it was just a few spaces and it still does it

**Comment by quajak** [comment]
If you create a new kernel/OS can that build?

**Comment by CSharpandLua** [comment]
Probably
ill try that soon but i do not feel like restarting
