### ISSUE TITLE
Replace ByteConverter methods that deal with string Encoding with the proper Encoding class methods

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#956]
During my work on DriveInfo I have noticed that these methods are a lot used there:

- GetAsciiString()
- GetUtf8String()
- GetUtf8Bytes()
- GetUtf16String()
- GetUtf16Bytes()

Only the first one is doing wait it promises the other simply force all to be really ASCII! This means that for example a filename as "tèst" will be not working!

The correct way to do this is to use the static classes Encoding.Ascii, Encoding.UTF8 and Encoding.Unicode (that is UFT-16) and their methods that will do the proper conversion.

**Comment by quajak** [comment]
I can look into this.

**Comment by fanoI** [comment]
To be clear this should be done in all Cosmos code not only in FAT... if I want UFT16 bytes this what I should get not all "truncated" to ASCII.

**Comment by quajak** [comment]
Yeah I will try doing that

**Comment by fanoI** [comment]
Thank you for your help!

**Comment by fanoI** [comment]
fixed by #984
