### ISSUE TITLE
Projects which reference Cosmos.Core, Cosmos.HAL etc.

### ISSUE THREAD

**Issue by Arawn-Davies** [CosmosOS/Cosmos#957]
This is a big issue and I'm struggling to get my head around it myself, so apologies if I get repetitive or unclear at all. Just ask me underneath if you're unclear about what I'm saying at any time 👍 
Note: Both ring projects have Cosmos.Build NuGet package removed to stop IL2CPU from complaining that there's no kernel.

#### Area of Cosmos - What area of Cosmos are we dealing with?
Non-kernel-inheriting Cosmos projects

#### Expected Behaviour - What do you think that should happen?
Reference and compile the other projects correctly into the Kernel project

#### Actual Behaviour - What unexpectedly happens?
Upon project creation:
With the 'cosmos' runtime identifier in ring project's .csproj :
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.	Medli.System	C:\Users\Arawn\.nuget\packages\microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets	19	
```
During compilation with IL2CPU:
Without the identifier
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	occurred	System.BadImageFormatException: Could not load file or assembly 'C:\Users\Arawn\documents\visual studio 2017\Projects\Medli\Medli.System\bin\Debug\netcoreapp2.0\Medli.System.pdb'. Format of the executable (.exe) or library (.dll) is invalid.	Medli	C:\Users\Arawn\documents\visual studio 2017\Projects\Medli\Medli\Error	1	
```
#### Reproduction - How did you get this error to appear?
Created projects that use Cosmos.Core + Cosmos.HAL, and reference them in the main kernel project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Developer Kit:
Cosmos commit ccb8fae2716ca1fce829e08e4176243d1de5ca9b
IL2CPU commit 9bb3b5b857a8c14a84c465b1d6d23380be737a0a
XSharp commit 874eb9b93f8c69a357ac1faae97d8670ecfbe73d

Referencing projects in rings (without the ring attribute of course) used to work fine, so the main kernel project could use code that uses Cosmos.Core and Cosmos.HAL. However, this was until a couple of commits ago, possibly when projects started using the 'cosmos' runtime identifier in their .csproj file. I'm not sure what has happened exactly because I updated the old projects to include the 'cosmos' runtime identifier, but now it doesn't output the build to the correct directory. Even after recreating projects to use the new build targets and stuff, the issue still remains.

I understand rings aren't enforced any more, and that the attributes shouldn't be used, and with the attributes from AssemblyInfo.cs or any other source file, I've got a lot of code that's split up into different projects so having it all in one project makes it pretty confusing for myself.

**Comment by Arawn-Davies** [comment]
If what I put down as expected behaviour, isn't expected any more, would it be that Cosmos projects are now under just one project, and that one project can reference all Cosmos ring NuGet packages like Cosmos.Core, Cosmos.HAL2? And instead of multiple projects, namespaces and solution folders would be used instead?

**Comment by jp2masa** [comment]
Is this still an issue?
