### ISSUE TITLE
IL2CPU error while building project to iso.

### ISSUE THREAD

**Issue by Pufflegamerz** [CosmosOS/Cosmos#958]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building files.

#### Expected Behaviour - What do you think that should happen?
The project should build into a iso file.

#### Actual Behaviour - What unexpectedly happens?
I get error "Error occurred while invoking il2cpu."

#### Reproduction - How did you get this error to appear?
I build the project into an iso file.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Userkit C#.

I tried to build my project into an iso file and switching it to release, and I get errors. I found many issues with this problem but I have yet to find a solution. 
[cosmos-os.zip](https://github.com/CosmosOS/Cosmos/files/1913296/cosmos-os.zip)

**Comment by Pufflegamerz** [comment]
I don't know about the error log, but I have the build log:
1>------ Build started: Project: PrismOSBoot, Configuration: Debug Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\PrismOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\netstandard1.5\PrismOS.dll" 
1>C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\PrismOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\daniel\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\netstandard1.5\PrismOS.dll" 
1>	Working directory = 'C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
1>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
1>	Error: Exception: System.Exception: Error compiling method 'SystemVoidPrismOSKernelRun': System.Exception: OpCode IL_0105: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 446
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 423
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 503 ---> System.Exception: OpCode IL_0105: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 470
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 464
1>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 446
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 423
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 503
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 518
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 964
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>	Loaded assemblies: 
1>	C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
1>	C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
1>	C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\Cosmos.System.Plugs.dll
1>	C:\Users\daniel\source\repos\PrismOS\PrismOS\bin\Debug\net462\PrismOS.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:06.9452982
1>Done building project "PrismOSBoot.Cosmos" -- FAILED.
1>
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by Arawn-Davies** [comment]
The Release option doesn't currently do anything, but what you'll likely be wanting to do is right click on the Boot project (PrismOS.csproj or PrismOS.Cosmos - can't remember exactly which the userkit uses) and turn off Cosmos Debugging. Then you can use the media on any machine without the "waiting for debugger" screen

**Comment by Arawn-Davies** [comment]
Saw inside your source file, its PrismOSBoot.Cosmos that you'll want to right click - properties and disable debugging :)

**Comment by Pufflegamerz** [comment]
Now another problem:  I have to run the project 2 times for it to update after some changes. Is this normal?

**Comment by jp2masa** [comment]
It's a User Kit bug. It was fixed in the Dev Kit.

**Comment by Pufflegamerz** [comment]
I can't find a tutorial on how to get the dev kit. Can you post a link to one?

**Comment by jp2masa** [comment]
https://www.gocosmos.org/docs/install/

**Comment by Siaranite** [comment]
Can this be closed?
~Arawn Davies

**Comment by Pufflegamerz** [comment]
Yes

Sent from Mail for Windows 10

**Comment by shayan-azizi** [comment]
i have this problem too... i disabled debug in vs
but it doesn't work good!

**Comment by shayan-azizi** [comment]
### Error log
```
Build started...
1>------ Build started: Project: firstKernel, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>firstKernel -> C:\Users\huawei\source\repos\firstKernel\bin\Debug\netcoreapp2.0\cosmos\firstKernel.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\huawei\source\repos\firstKernel\bin\Debug\netcoreapp2.0\cosmos\firstKernel.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Boolean  System.Number.NumberBufferToDouble(System.Byte*, &System.Double).
1>  Called from :
1>System.Number::Double ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
1>System.Double::Double Parse(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
1>System.Double::Double Parse(System.String, System.IFormatProvider)
1>System.Convert::Double ToDouble(System.String)
1>firstKernel.Kernel::Void HandlThisCommand(System.String)
1>firstKernel.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:01.5056578
1>Done building project "firstKernel.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
