### ISSUE TITLE
[Website] Wrong translation of the word "free" into Turkish

### ISSUE THREAD

**Issue by boramalper** [CosmosOS/Cosmos#959]
#### Area of Cosmos - What area of Cosmos are we dealing with?
The gocosmos.org Website

----

In the website, the word *free* is translated into Turkish as "bedava" which means *free as in free beer* whereas you are looking for the word "özgür" which means *free as in free speech*.

While you are there, you have an ellipsis and an extra dot there. =)

**EDIT:** Just realised same goes with https://www.il2cpu.net/ too, and probably with other websites you created as well

**Comment by czhower** [comment]
My Turkish is limited and mostly around transport and food as I lived in Turkey only for a year so I will gladly bow out to someone more knowledgeable.

However, we do want "free as in beer". Cosmos is free to use, there is no cost.

**Comment by azmisahin** [comment]
Hello there. I live in Turkey. I can contribute to language translation and development.

My Cosmos : https://github.com/azmisahin/azmisahin-software-programming-quantum-Cosmos :)

**Comment by quajak** [comment]
Are there any other problems with the translation? If no can this issue be closed.
