### ISSUE TITLE
String Contains problem ?

### ISSUE THREAD

**Issue by geomtech** [CosmosOS/Cosmos#960]
Hello, everybody! I come here to ask you for help, because I may have found a bug or may be stupid... I'm coding a zip extractor for Aura OS. The files contained in the zip file, start with 0x50 0x4B 0x03 0x04. So I try to do a foreach for each file, so for each byte starting with 0x50 0x4B 0x03 0x04... My code runs very well in normal.NET console but not on Cosmos, which makes me think of a bug.
Here's my code:

```
private void ListFiles()
        {
            Byte[] zip = FileHeader();
            List<string> signatures = new List<string>();

            string signature = "";
            int pointer = -4;

            foreach (Byte file in zip)
            {
                pointer = pointer + 1;
                signature = signature + file;

                if (signature.Contains("807534"))
                {
                    signature = "";
                    signatures.Add("1 file found > " + pointer);
                }
            }

            foreach (string sign in signatures)
            {
                Console.WriteLine(sign);
            }
        }
```
and for FileHeader()
```

private Byte[] FileHeader()
        {
            Byte[] zip = File.ReadAllBytes(ZIPFile);
            return zip;            
        }
```
I have tested many alternative solutions, but I always get the same result.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest Cosmos dev kit

**Comment by fanoI** [comment]
I suspect the problem is in the '+' operator you concatting a string with a byte when you do:

```cs
signature = signature + file;
```
If the C# online compiler the result of "concat" 0x80 to a string is a string containing 128 (0x80 expressed in decimal) is that what you want:

https://dotnetfiddle.net/AYIBVH

**Comment by geomtech** [comment]
It's 0x50 so it's = 80. 
And so I'm putting all bytes in the string to have "807534"

And that's work well in console app but not on cosmos

**Comment by fanoI** [comment]
Can you print the content of `signature` after you called the `+` operator?
We have tests for Contains: https://github.com/CosmosOS/Cosmos/blob/master/Tests/Cosmos.Compiler.Tests.Bcl/System/StringTest.cs#47
