### ISSUE TITLE
OS not running.

### ISSUE THREAD

**Issue by catmaster450** [CosmosOS/Cosmos#961]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Kernal

#### Expected Behaviour - What do you think that should happen?
The program should run.

#### Actual Behaviour - What unexpectedly happens?
It gives me the error: "Project '.\TFOS.csproj' targets 'netstandard1.5'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.	TFOSBoot	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets"	

#### Reproduction - How did you get this error to appear?
By pressing the start button

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
I was using the user kit, and it was Cosmos

**Comment by jp2masa** [comment]
Did you create a new project or use an existing one?
