### ISSUE TITLE
Devkit failing to install

### ISSUE THREAD

**Issue by lxmcf** [CosmosOS/Cosmos#962]
I had to re-clone cosmos as i accidentally wiped one of my drives.

I've been using the following commands...

git clone https://github.com/CosmosOS/Cosmos.git
git clone https://github.com/CosmosOS/IL2CPU.git
git clone https://github.com/CosmosOS/XSharp.git

But i get the following error after running install-VS2017.bat, I've attached a file with the builder log...
[error.txt](https://github.com/CosmosOS/Cosmos/files/1935454/error.txt)

P.S Sorry if its a rookie question :-/

**Comment by zarlo** [comment]
@fanoI

**Comment by jp2masa** [comment]
I think this has already been fixed.
