### ISSUE TITLE
IL2CPU

### ISSUE THREAD

**Issue by Dragon-Softwares** [CosmosOS/Cosmos#963]
Hi, I'm making an OS in vb (C# Say some 4 dash digit error) and I get an error 'Error Occurred while invoking IL2CPU'. I tried it on my other pc and came with the same thing. I downloaded it at https://github.com/CosmosOS/IL2CPU/ and still same problem. ALSO .net 3.5 framework is installed

my code for now is:

Imports System
Imports System.Collections.Generic
Imports System.Text

Namespace Visual_OS

    Public Class Kernel
        Inherits Cosmos.System.Kernel

        Protected Overrides Sub BeforeRun()
            ' Changes the text color to Green
            Console.ForegroundColor = ConsoleColor.Green
            ' Shows user it successfully booted up
            Console.WriteLine("Visual OS booted successfully.")

            'Changes the text color to DarkGreen
            Console.ForegroundColor = ConsoleColor.DarkGreen
            ' Shows user how to navigate through the OS
            Console.WriteLine("Type 'Help' To shows the Help Options")
        End Sub

        Protected Overrides Sub Run()
            ' Changes the 
            Console.ForegroundColor = ConsoleColor.White
            Console.Write("Input: ")
            Dim input = Console.ReadLine()
            'Console.Write("Text typed: ")
            'Console.WriteLine(input)

            If input = "help" Then
                Console.WriteLine("Help                 Action")
                Console.WriteLine("Help                 Shows the Help Menu")
                Console.WriteLine("Exit                 Exits the OS")
                Console.WriteLine("Shutdown             Shuts down the OS")
                Console.WriteLine("-----------------------------------------")
                Console.WriteLine("-h                   Shows help for the command")
            ElseIf input = "help -h" Then
                Console.WriteLine("Help - Shows the Help Menu")
            End If
        End Sub

    End Class

End Namespace

**Comment by Dragon-Softwares** [comment]
Also I tried to create other projects, it didn't work

**Comment by jp2masa** [comment]
Are you using the User Kit? If so, the C# template is located in the Cosmos section, in the New Project dialog.

**Comment by Dragon-Softwares** [comment]
ok

**Comment by Dragon-Softwares** [comment]
C# finally works. I had an error about 4 dashes yesterday. idk what I did but it now works. Now for vb. still get the il2cpu error

**Comment by jp2masa** [comment]
Check the output window, there should be an error message.

**Comment by Dragon-Softwares** [comment]
1>------ Build started: Project: Visual OSBoot, Configuration: Release Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Debug\net462\Visual OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Release\netstandard1.5\Visual OS.dll" 
1>E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Debug\net462\Visual OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:False" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Release\netstandard1.5\Visual OS.dll" 
1>	Working directory = 'E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Int32  System.Globalization.CompareInfo.InternalCompareString(System.IntPtr, System.IntPtr, System.String, System.String, System.Int32, System.Int32, System.String, System.Int32, System.Int32, System.Int32).
1>	 Called from :
1>	System.Globalization.CompareInfo::Int32 Compare(System.String, System.String, System.Globalization.CompareOptions)
1>	Microsoft.VisualBasic.CompilerServices.EmbeddedOperators::Int32 CompareString(System.String, System.String, Boolean)
1>	VisualOS.Visual_OS.Kernel::Void Run()
1>	Cosmos.System.Kernel::Void Run()
1>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>	Loaded assemblies: 
1>	E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
1>	E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
1>	E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
1>	E:\Users\Dragon Softwares\source\repos\vs1\Visual OS\Visual OS\bin\Release\netstandard1.5\Visual OS.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:09.3867463
1>Done building project "Visual OSBoot.Cosmos" -- FAILED.
1>
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by Dragon-Softwares** [comment]
ok. is it best then to learn c#. from what I know its the same but with ; at the end

**Comment by jp2masa** [comment]
It's not really the same... C# is from the C family of languages, and Visual Basic is from the Basic family of languages, so they are really different. Only the core APIs are the same, but there are some additional methods in Visual Basic which are part of Microsoft.VisualBasic, and if you want to use them in C# you have to add a reference to Microsoft.VisualBasic and import the namespace.

**Comment by Dragon-Softwares** [comment]
It's now doing is in C#. It worked for 4 days and now I get the error. I also got 345 lines of code. Do you need my code to see if there is an error?
