### ISSUE TITLE
IL2CPU 2

### ISSUE THREAD

**Issue by Dragon-Softwares** [CosmosOS/Cosmos#964]
This is a carry on from https://github.com/CosmosOS/Cosmos/issues/963

It's now doing is in C#. It worked for 4 days and now I get the error. I also got 350 lines of code. Do you need my code to see if there is an error?

**Comment by jp2masa** [comment]
Always check the output window, the error message should be there.

**Comment by Dragon-Softwares** [comment]
ok I got:

**Comment by Dragon-Softwares** [comment]
1>------ Build started: Project: Centeral OS, Configuration: Debug Any CPU ------
1>Centeral OS -> E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\netstandard1.5\Centeral OS.dll
2>------ Build started: Project: Centeral OSBoot, Configuration: Debug Any CPU ------
2>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\netstandard1.5\Centeral OS.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
2>E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\netstandard1.5\Centeral OS.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
2>	Working directory = 'E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  Interop+mincore.Beep(System.Int32, System.Int32).
2>	 Called from :
2>	System.ConsolePal::Void Beep()
2>	System.Console::Void Beep()
2>	Centeral_OS.Kernel::Void Run()
2>	Cosmos.System.Kernel::Void Run()
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OS.dll
2>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:05.0055930
2>Done building project "Centeral OSBoot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jp2masa** [comment]
`Console.Beep` needs a plug. A plug for it was implemented in the Dev Kit I think.

**Comment by Dragon-Softwares** [comment]
Removed Console.beep

same error, I'll give you my code and output so you can see whats wrong ok

Code:

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.IL2CPU;

namespace Centeral_OS
{
    public class Kernel : Sys.Kernel
    {
        protected override void BeforeRun()
        {
            /// Changing the text to Green
            ///Console.WindowWidth = 1920;
            ///Console.WriteLine("Setting WindowWidth As 1920");
            ///Console.WriteLine("Window Width set");
            ///Console.WindowHeight = 1080;
            ///Console.WriteLine("Setting Windowheight As 1080");
            ///Console.WriteLine("Window height set");
            ///Console.Title = ("Centeral OS");
            
            ///Changes the text to Green
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Centeral OS booted successfully.");

            /// Changing the text to Dark Green
            Console.ForegroundColor = ConsoleColor.DarkGreen;
            Console.WriteLine("Type 'Help' for the list of commands");
            Console.ForegroundColor = ConsoleColor.White;
            Run();       
        }

        public void reset()
        {
            var a = Console.ReadLine();

            if ((a == "a"))
            {
                Run();
            }
        }

        protected override void Run()
        {

            //Console.Write("");
            var input = Console.ReadLine();
            //Console.Write("Text typed: ");
            //Console.WriteLine(input);

            if ((input == "help"))
            {
                Console.WriteLine("Help                 Action");
                Console.WriteLine("Help                 Shows the Help Menu");
                Console.WriteLine("About                Shows about the OS");
                Console.WriteLine("Color                Changes the Color of the OS");
                Console.WriteLine("------------------------------------------------");
                Console.WriteLine("-h                   Shows help of the command");
                Console.WriteLine("-i                   Shows info the the command");
            }

            else if ((input == "about"))
            {
                Console.ForegroundColor = ConsoleColor.DarkGreen;
                Console.WriteLine("Name: Centeral OS");
                Console.WriteLine("Version: 1.0");
                Console.WriteLine("Code Language: C#");
                Console.WriteLine("Copyright Dragon Softwares 2017-2018");
            }

            /// Help

            else if ((input == "about -h"))
            {
                Console.WriteLine("About - Shows about the OS");
            }
            else if ((input == "help -h"))
            {
                Console.WriteLine("Help - Shows the Help menu");
            }
            else if ((input == "color -h"))
            {
                Console.WriteLine("Color - Changes the Color of the OS");
            }

            /// Information
            
            else if ((input == "color -i"))
            {
                Console.WriteLine("Colors: white, black, blue, cyan, gray, purple, red, yellow, green");
                Console.WriteLine("If you add dark then the color like 'darkred', it will the color darker");
            }
            /// Colors
            else if ((input == "color black"))
            {
                Console.ForegroundColor = ConsoleColor.Black;
            }
            else if ((input == "color white"))
            {
                Console.ForegroundColor = ConsoleColor.White;
            }
            else if ((input == "color blue"))
            {
                Console.ForegroundColor = ConsoleColor.Blue;
            }
            else if ((input == "color darkblue"))
            {
                Console.ForegroundColor = ConsoleColor.DarkBlue;
            }
            else if ((input == "color cyan"))
            {
                Console.ForegroundColor = ConsoleColor.Cyan;
            }
            else if ((input == "color darkcyan"))
            {
                Console.ForegroundColor = ConsoleColor.DarkCyan;
            }
            else if ((input == "color gray"))
            {
                Console.ForegroundColor = ConsoleColor.Gray;
            }
            else if ((input == "color darkgray"))
            {
                Console.ForegroundColor = ConsoleColor.DarkGray;
            }
            else if ((input == "color purple"))
            {
                Console.ForegroundColor = ConsoleColor.Magenta;
            }
            else if ((input == "color darkpurple"))
            {
                Console.ForegroundColor = ConsoleColor.DarkMagenta;
            }
            else if ((input == "color red"))
            {
                Console.ForegroundColor = ConsoleColor.Red;
            }
            else if ((input == "color darkred"))
            {
                Console.ForegroundColor = ConsoleColor.DarkRed;
            }
            else if ((input == "color yellow"))
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
            }
            else if ((input == "color darkyellow"))
            {
                Console.ForegroundColor = ConsoleColor.DarkYellow;
            }
            else if ((input == "color green"))
            {
                Console.ForegroundColor = ConsoleColor.Green;
            }
            else if ((input == "color darkgreen"))
            {
                Console.ForegroundColor = ConsoleColor.DarkGreen;
            }
            else if ((input == "games"))
            {
                games();
            }
            else if ((input == "clear"))
            {
                Console.Clear();
            }
            else if ((input == "restart"))
            {
                Cosmos.System.Power.Reboot();
            }
            
            ///Shows Error Message
                else
            {
                /// Console.ForegroundColor = ConsoleColor.Red;
                Error();
                ///Console.ForegroundColor = ConsoleColor.White;
            }
        }

        public static void games()
        {
            Console.WriteLine("         GAMES           ");
            Console.WriteLine("Type number to start the gmae");
            Console.WriteLine("1                    Text Adventure");
            Console.WriteLine("2                    Snake");
            var number = Console.ReadLine();

            if ((number == "1"))
            {
                TextAdventureMenu();
            }
            else if ((number == "2"))
            {
                Console.WriteLine("2");
            }
            else
            {
                ///Shows error message for games / May include public static error in the future - DONE
                Error();
            }
        }
        ///TEXT ADVENTURE GAME NUMBER 1
        
        public static void TextAdventureMenu()
        {
            Console.WriteLine("Welcome to the Text Adventure game");
            Console.WriteLine("");
            Console.WriteLine("What Story will you choose:");
            Console.WriteLine("------------------------------------");
            Console.WriteLine("Murder                   You work for the FBI trying to find where the killing happend");
            Console.WriteLine("");
            Console.WriteLine("Type 'Help' to get help");
            Console.WriteLine("Type 'Exit' to exit the game menu");

            var menutext = Console.ReadLine();

            if ((menutext == "Murder"))
            {
                TextAdventureGameMurder();
            }
            else if ((menutext == "Exit"))
            {
                
            }
        }

        public static void TextAdventureGameMurder()
        {
            Console.WriteLine("You appear in a dark room with a bag");
            Console.WriteLine("The bag is heavy so something is in it");
            Console.WriteLine("Do you: 'Search' the Bag OR 'Throw' the bag away");
            var command = Console.ReadLine();

            if ((command == "Look in the bag"))
            {
                TextadventurelookMurder1();
            }
            else if ((command == "Throw"))
            {
                Console.WriteLine("You throw the bag on the ground");
                Console.WriteLine("A Bomb in the bag goes off from the impact.");
                TextAdventureDieMurder();
            }
        }

        public static void TextadventurelookMurder1()
        {
            Console.WriteLine("You look in the bag, you find a");
            Console.WriteLine("pistol with 1 clip of ammo and a bomb?");
            Console.WriteLine("Sadly, the ammo clip only has 5 bullets in");
            Console.WriteLine("Good thing the bomb only blows up if it gets slammed down on the ground");
            Console.WriteLine("");
            Console.WriteLine("You hear Someone Banging on the door");
            Console.WriteLine("Do you 'Shoot' at the noise or do you 'Hide'");
            var text = Console.ReadLine();

            if ((text == "Shoot"))
            {
                Console.WriteLine("You don't know how the Gun works");
                Console.WriteLine("You point it at your head and hold down the trigger");
                Console.WriteLine("At least you got a headshot");
                TextAdventureGameMurder();
            }
            else if ((text == "Hide"))
            {
                Console.WriteLine("You found a box and jumped inside it");
                Console.WriteLine("The Banging Stopped!");
                Console.WriteLine("You think you hear something");
                Console.WriteLine("Do you 'Hide' in the box or get 'Out' of the box");
                var Hide = Console.ReadLine();

                if ((Hide == "Hide"))
                {
                    Console.WriteLine("It was a Huge Spider");
                    Console.WriteLine("It snapped your neck");
                    TextAdventureDieMurder();
                }
                else if ((Hide == "Out"))
                {
                    Console.WriteLine("You realise it was a Huge Spider in the box");
                    Console.WriteLine("You nearlly died, your happy.");
                    Console.WriteLine("You go where the banging was at");
                    Console.WriteLine("It was a door!");
                    Console.WriteLine("Do you open it? 'Yes' or 'No'");
                    var yno = Console.ReadLine();

                    if ((yno == "Yes"))
                    {
                        Console.WriteLine("You realise your in your mums/moms basement?");
                        Console.WriteLine("You also found out there was no killer");
                    }
                    else if ((yno == "No"))
                    {
                        Console.WriteLine("1 Week later. Still didn't open the door because you were");
                        Console.WriteLine("to scared. You remembered you had a gun");
                        Console.WriteLine("You pointed it to your head and commited suicide.");
                        TextAdventureDieMurder();
                    }
                }
            }
        }

        public static void TextAdventureDieMurder()
        {
            Console.WriteLine("You DIED");
            Console.WriteLine("Type 'Restart' to restart");
            Console.WriteLine("Type 'Exit' to exit to main menu");
            var died = Console.ReadLine();

            if ((died == "Restart"))
            {
                TextAdventureGameMurder();
            }
            else if ((died == "Exit"))
            {
                TextAdventureMenu();
            }
        }

        public static void TextAdventureWinMurder()
        {
            Console.WriteLine("YOU WIN");
            Console.WriteLine("Type 'Restart' to restart");
            Console.WriteLine("Type 'Exit' to exit to main menu");
            var win = Console.ReadLine();

            if ((win == "Restart"))
            {
                TextAdventureGameMurder();
            }
            else if ((win == "Exit"))
            {
                TextAdventureMenu();
            }
        }

        public static void Error()
        {
            Console.WriteLine("ERROR");
        }

    }
}

Output:

1>------ Build started: Project: Centeral OSBoot, Configuration: Debug Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\netstandard1.5\Centeral OS.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
1>E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\netstandard1.5\Centeral OS.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:E:\Users\Dragon Softwares\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
1>	Working directory = 'E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  Interop+mincore.Beep(System.Int32, System.Int32).
1>	 Called from :
1>	System.ConsolePal::Void Beep()
1>	System.Console::Void Beep()
1>	Centeral_OS.Kernel::Void Run()
1>	Cosmos.System.Kernel::Void Run()
1>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
1>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>	Loaded assemblies: 
1>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Centeral OS.dll
1>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
1>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Core.Plugs.dll
1>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	E:\Users\Dragon Softwares\source\repos\Centeral OS\Centeral OS\bin\Debug\net462\Cosmos.System.Plugs.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:09.0789024
1>Done building project "Centeral OSBoot.Cosmos" -- FAILED.
1>
1>Build FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by Dragon-Softwares** [comment]
Wait, can it not have public static void, does it allow public void then? Not sure if it will fix it?

If you do find the error can you change the code and comment it if you want to thanks. And I really want to get this done as I've been working on this for 4 days (at least 30 mins - 1 hour per day. And Also I've planned of doing this project for so long.

**Comment by jp2masa** [comment]
Try rebuilding the solution.

**Comment by Dragon-Softwares** [comment]
ok.

**Comment by Dragon-Softwares** [comment]
nope same error

**Comment by jp2masa** [comment]
Did you Build or Rebuild the solution?

**Comment by Dragon-Softwares** [comment]
Build

**Comment by Dragon-Softwares** [comment]
I went Build > Build Solution

**Comment by jp2masa** [comment]
Try Build -> Rebuild Solution.

**Comment by Dragon-Softwares** [comment]
ok

**Comment by Dragon-Softwares** [comment]
While Im waiting, what does IL2CPU mean? What does it do?

**Comment by Dragon-Softwares** [comment]
yes it works. thanks

**Comment by Dragon-Softwares** [comment]
Anyone who sees this, please don't copy the code. Thanks
