### ISSUE TITLE
Add ATAPI support

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#965]
So the CD in which Cosmos is running can be seen by Cosmos itself this opens the possibility to install Cosmos on the HDD!

Here you can find some documentation on ATAPI: https://wiki.osdev.org/ATAPI

**Comment by Arawn-Davies** [comment]
I've got started with this, enough to read a single sector, with ejecting the drive [WIP], I'll open a PR :)

**Comment by MishaTY** [comment]
@Arawn-Davies Is it done?
