### ISSUE TITLE
Add ISO9660 support

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#966]
After #965 has been done and the CD / DVD drive correctly recognized to read the content of the drive support for ISO9660 is needed.

This the IS09660 documentation: https://wiki.osdev.org/ISO_9660.

The first thing to do is to implement the FileSystemFactory abstract class, we can take for example what i done for FAT: https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/FileSystem/FatFileSystemFactory.cs

Then after you have done the needed methods Ctor and the IsType on the new ISO9660FileSystem class you can register it in Cosmos VFS simply adding a line here:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2/FileSystem/CosmosVFS.cs#L35

If all goes well the CD drive will be recognized by Cosmos and a letter will be given to it from this point on you should work to make CD I/O possible (again you can take inspiration a lot from FAT).

**Comment by MishaTY** [comment]
Now implemented in latest version of devkit.
