### ISSUE TITLE
Creating List<List<T>> Causes errors

### ISSUE THREAD

**Issue by 365Tito** [CosmosOS/Cosmos#967]
This code:
`List<List<Line>> lines = new List<List<Line>>();`
Should compile without error.
Instead, this exception shows:
`Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.`

**Comment by jp2masa** [comment]
`temp` is a `List<T>`? If it's an array, then it's what's causing that exception.

**Comment by 365Tito** [comment]
`temp` is a `List<T>`. Replaced that with a foreach loop copying each element into a new list then adding the new list itself (won't make reference type problems I guess).
