### ISSUE TITLE
IL2CPU is missing

### ISSUE THREAD

**Issue by V-Volte** [CosmosOS/Cosmos#973]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running a cosmos project

#### Expected Behaviour - What do you think that should happen?
Build a cosmos project.

#### Actual Behaviour - What unexpectedly happens?
The IDE shows this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6004	The specified task executable location "C:\Users\Sekhara Pramod\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" is invalid.	CosmosKernel7	C:\Users\Sekhara Pramod\.nuget\packages\cosmos.build\2018.5.6\build\Cosmos.Build.targets	138	
```

#### Reproduction - How did you get this error to appear?
By creating a new Cosmos Kernel and trying to debug it.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit , commit: 87e38b2

**Comment by V-Volte** [comment]
@fanoI I have a folder called cosmos in which I have three folders.

- Cosmos\Cosmos
- Cosmos\IL2CPU
- Cosmos\XSharp

And, if it means something, my Cosmos User Kit folder in %appdata% is completely empty, no matter how many times I try reinstalling Cosmos.

**Comment by quajak** [comment]
Did you pull IL2CPU and XSharp into the two other folders? Were you able to get cosmos running?
