### ISSUE TITLE
System.Threading.Thread does not exist

### ISSUE THREAD

**Issue by jeuxjeux20** [CosmosOS/Cosmos#977]
I'm sorry if this issue feels very garbage :( 

#### Area of Cosmos - What area of Cosmos are we dealing with?

User

#### Expected Behaviour - What do you think that should happen?

It should build, and get access to the `System.Threading.Thread` plugged class with the Sleep method.

#### Actual Behaviour - What unexpectedly happens?

It doesn't build and IntelliSense says it doesn't exist.

#### Reproduction - How did you get this error to appear?

Using` System.Threading.Thread.Sleep` in an User ring project with a Kernel.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 2017 09 28

**Comment by jp2masa** [comment]
That's because the project targets .NET Standard 1.5. If you need that API, you can use the Dev Kit.

**Comment by jeuxjeux20** [comment]
Will try to do so.

**Comment by jeuxjeux20** [comment]
Sadly, it gives me an error when building cosmos :/ It isn't very descriptive.

Console returned error code (0x00000001)

**Comment by jeuxjeux20** [comment]
Nevermind, forgot to rename the folder :)
