### ISSUE TITLE
Dev Kit Error Console returned exit code. (0x00000001)

### ISSUE THREAD

**Issue by zack67** [CosmosOS/Cosmos#978]
I been reading the https://www.gocosmos.org/docs/install/ and I have install everything that is required.
I did try the CosmosUserKit-20170928-vs2017.exe it work for me so I uninstall the UserKit to install the Dev Kit with the install-VS2017.bat.

Just to ask first, VS2017 15.7.1 having VS up to date should be fine right?

I can't download the .NET Core 2.0 SDK so I when with dotnet sdk 2.1.200 it is the latest so
Inno Quick Start Pack 2.3.0 (20180430-181655) 
For the "Visual Studio 2017 Workload: .NET Core Tools – .NET Core cross-platform development"
I think it is the "Other Toolsets" for the "Visual Studio extension development" in the installer.
.NET Framework 4.6.2 Developer Pack

I hope all these that are required are right.

I did install the windows 10 SDK as well. I am running windows 10.
I hope someone can help. I been trying to install this for weeks.

Thanks,
Zack

Here is the log.

========================================
    Builder Log
========================================

========================================
    Check Prerequisites
========================================

Check if User Kit Installer is already running.
Check if Builder is running.
Check for .NET Core
Check for Visual Studio Extension Tools
Check for Inno Setup
Check for Inno Preprocessor
Checking for existing IL2CPU and XSharp repositories...

========================================
    Init Directories
========================================

Cleaning up existing VSIP directory.
Creating VSIP as C:\source\Cosmos\Build\VSIP
Cleaning up existing User Kit directory.
Creating User Kit as C:\Users\zack\AppData\Roaming\Cosmos User Kit

========================================
    Clean NuGet Local Feed
========================================

Starting: C:\source\Cosmos\Build\Tools\nuget.exe
  Params: sources List
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

========================================
    Restore NuGet Packages
========================================

Starting: C:\source\Cosmos\Build\Tools\nuget.exe
  Params: restore "C:\source\Cosmos\Build.sln"
MSBuild auto-detection: using msbuild version '15.7.177.53362' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Common\obj\project.assets.json
Restore completed in 123.45 ms for C:\source\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Build.Common\obj\project.assets.json
Restore completed in 134.28 ms for C:\source\Cosmos\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Build.MSBuild\obj\project.assets.json
Restore completed in 121.04 ms for C:\source\Cosmos\source\Cosmos.Build.MSBuild\Cosmos.Build.MSBuild.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Build.Tasks\obj\project.assets.json
Restore completed in 128.05 ms for C:\source\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Core.DebugStub\obj\project.assets.json
Restore completed in 0.83 ms for C:\source\Cosmos\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Core\obj\project.assets.json
Restore completed in 1.34 ms for C:\source\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Core_Plugs\obj\project.assets.json
Restore completed in 1.54 ms for C:\source\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Debug.Common\obj\project.assets.json
Restore completed in 3.25 ms for C:\source\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Debug.DebugConnectors\obj\project.assets.json
Restore completed in 2.75 ms for C:\source\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Core_Asm\obj\project.assets.json
Restore completed in 6.89 ms for C:\source\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\obj\project.assets.json
Restore completed in 1.88 ms for C:\source\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Debug.Kernel\obj\project.assets.json
Restore completed in 0.96 ms for C:\source\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.Debug.Hosts\obj\project.assets.json
Restore completed in 3.17 ms for C:\source\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.HAL2\obj\project.assets.json
Restore completed in 1.49 ms for C:\source\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.System2_Plugs\obj\project.assets.json
Restore completed in 1.59 ms for C:\source\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.System2\obj\project.assets.json
Restore completed in 1.58 ms for C:\source\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.VS.DebugEngine\obj\project.assets.json
Restore completed in 5.85 ms for C:\source\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\Tests\Cosmos.TestRunner.TestController\obj\project.assets.json
Restore completed in 1.36 ms for C:\source\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.VS.Windows\obj\project.assets.json
Restore completed in 1.54 ms for C:\source\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\Cosmos.VS.ProjectSystem\obj\project.assets.json
Restore completed in 16.02 ms for C:\source\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\source\Cosmos\source\TheRingMaster\obj\project.assets.json
Restore completed in 12.75 ms for C:\source\Cosmos\source\TheRingMaster\TheRingMaster.csproj.
Restoring packages for C:\source\Cosmos\Tools\NASM\NASM.csproj...
Restoring packages for C:\source\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj...
Restoring packages for C:\source\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj...
Restoring packages for C:\source\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj...
Invalid character in the given encoding. Line 1, position 1.

========================================
    Error
========================================

Console returned exit code. (0x00000001)
   at Cosmos.Build.Builder.Tasks.Task.StartConsole(String aExe, String aParams)
   at Cosmos.Build.Builder.CosmosTask.Restore(String project)
   at Cosmos.Build.Builder.CosmosTask.CompileCosmos()
   at Cosmos.Build.Builder.CosmosTask.DoRun()
   at Cosmos.Build.Builder.Tasks.Task.Run()

**Comment by quajak** [comment]
Did you clone XSharp and IL2CPU?
