### ISSUE TITLE
cant find templates in vs 2017

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#983]
cant find templates in vs 2017

**Comment by jp2masa** [comment]
Are you using the User Kit or the Dev Kit?

**Comment by NanhuGITHUB** [comment]
The Templates are under the "Cosmos" Section

**Comment by furesoft** [comment]
ive reinstalled cosmos then the templates are there. but there is an error when i try to build:

cannot reference .net 4.0 assemblys to netstandard 2.0

**Comment by NanhuGITHUB** [comment]
Install .NET 4.6.2 (if Userkit is installed) or .NET 4.7.1 (for Devkit).
