### ISSUE TITLE
Large collections are slow

### ISSUE THREAD

**Issue by jeuxjeux20** [CosmosOS/Cosmos#985]
Filling a `List<T>` with more than 5000-10000 classes (mine having 3 members) takes a very long time (30 seconds). When about 1000 classes are in the `List<T>`, it is even slower. Any thoughts on that ?

**Comment by jp2masa** [comment]
Did you try setting initial capacity to 1000?

**Comment by jeuxjeux20** [comment]
Update : After filling this array (320 * 240) the system goes insanely slow, the while loop with one instruction takes 4 seconds for each iteration

**Comment by db-noop** [comment]
So it's a memory issue...

**Comment by fanoI** [comment]
Why you need a List of 10'000 classes?
Maybe you can think of an alternative way to do this?

**Comment by jeuxjeux20** [comment]
Because of my canvas buffer, I have some ideas with using one object for each shape instead of a huge buffer, but yeah ;P.

**Comment by zarlo** [comment]
@jeuxjeux20 when i made  double buffer i used an array of int32 winch should work for you too

**Comment by fanoI** [comment]
Well we are yet not optimizing code (on purpose), the work on the garbage collector is not finished yet and so on... 
I think your approach will be slow in a normal C# application by the way (probably not so slow as you see it in Cosmos now).

**Comment by jeuxjeux20** [comment]
I actually tested filling an `int[76800]` with the same number, which would be the image data of a 320x240 picture, it took 4-5 seconds.

**Comment by fanoI** [comment]
But do you have used Array.Copy() or done it in a for?
Array.Copy could be optimized in IL or in ASM directly...

**Comment by jeuxjeux20** [comment]
No, but yes that'd be a great idea, though i'm afraid of large images being slow in general, i will test that later

**Comment by jp2masa** [comment]
As performance is not a concern right now, I'm closing this.
