### ISSUE TITLE
Can't start projects

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#986]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Booting the OS.

#### Expected Behaviour - What do you think that should happen?
The projects should start normally.

#### Actual Behaviour - What unexpectedly happens?
There are 2 things that happen:
   1. When I start a project without IL2CPU debugging enabled it boots and freezes during the 
       booting with a message on the first line saying: 

> Kernel class Created

   2. When I start a project with IL2CPU debugging enabled it crashes during the booting and gives an
       error window with this message (couldn't copy-paste it so I used an online OCR): 

>Cosmos Debug Engine
>
>NullReferenceException occurred in
>'SystemVoidCosmosIL2CPUVTablesImplSetTypeInfoSystemInt32SystemUIn
>t32SystemUInt32SystemUint32arraySystemUInt32SystemUInt32arraySyste
>mUInt32arraySystemUInt32SystemUInt32arraySystemUInt32array'
>Document
>d:\users\leten\downloads\cosmos\19-5-2018\il2cpu\source\cosmos.il2cp
>u\vtablesimpl.cs
>Line: 110
>Address: 0x020D56A1

#### Reproduction - How did you get this error to appear?
I installed the latest DevKit (Date: 19-05-2018).

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit (Date: 19-05-2018)

#### Note
I tried reïnstalling the devkit again.
I tried creating a new project.
I tried disabling the debugging in the 'Cosmos (new)' tab of the project properties.

**Comment by jp2masa** [comment]
Try pulling latest IL2CPU master. I accidentally broke it yesterday, but it should be working now.

**Comment by BL9** [comment]
Tank you jp2masa, it's working again.
