### ISSUE TITLE
Everything Broke in default code when new project created.

### ISSUE THREAD

**Issue by Gosintary** [CosmosOS/Cosmos#987]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Running the project, I didn't add anything I just created a new kernel and ran the default code

#### Expected Behaviour - What do you think that should happen?
VMWare should have opened and run the os

#### Actual Behaviour - What unexpectedly happens?
Everything broke.

https://imgur.com/oyJZnva.png

Errors appeared on everything.
#### Reproduction - How did you get this error to appear?
I simply installed ComosOS user kit and all the other stuff and created a new project and this happened

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, latest version(Downloaded last night)

**Comment by quajak** [comment]
There seems to be a problem with the dependencies. Try refreshing the NuGet packages.
