### ISSUE TITLE
Exception: System.Exception

### ISSUE THREAD

**Issue by V-Volte** [CosmosOS/Cosmos#989]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Editing the kernel.cs file, using functions like `DateTime.Now.ToString()`, et cetera.
#### Expected Behaviour - What do you think that should happen?
Console should print the date and time
#### Actual Behaviour - What unexpectedly happens?
Exception: System Exception
#### Reproduction - How did you get this error to appear?
By using `DateTime.Now.ToString()` and `Math.Pow()`
#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit commit 2c14f60
![image](https://user-images.githubusercontent.com/32711469/40572854-73ffd402-60d4-11e8-9b05-e8a423c0b57c.png)

Error Log:
`1>------ Build started: Project: Apokalipse, Configuration: Debug Any CPU ------
1>Apokalipse -> C:\Users\Chandra\source\repos\Apokalipse\Apokalipse\bin\Debug\netcoreapp2.0\cosmos\Apokalipse.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Chandra\source\repos\Apokalipse\Apokalipse\bin\Debug\netcoreapp2.0\cosmos\Apokalipse.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.Threading.Interlocked._CompareExchange(System.TypedReference, System.TypedReference, System.Object).
1>  Called from :
1>System.Threading.Interlocked::System.Globalization.NumberFormatInfo CompareExchange[NumberFormatInfo](System.Globalization.NumberFormatInfo ByRef, System.Globalization.NumberFormatInfo, System.Globalization.NumberFormatInfo)
1>System.Globalization.CultureInfo::System.Globalization.NumberFormatInfo get_NumberFormat()
1>System.Globalization.CultureInfo::System.Object GetFormat(System.Type)
1>System.Globalization.DateTimeFormatInfo::System.Globalization.DateTimeFormatInfo get_CurrentInfo()
1>System.DateTime::System.String ToString(System.String)
1>Apokalipse.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in E:\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 616
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in E:\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 769
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable 1 plugsAssemblies) in E:\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 260
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in E:\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 176
1>IL2CPU task took 00:00:03.1690537
1>Done building project "Apokalipse.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by Temporary190206** [comment]
https://github.com/CosmosOS/Cosmos/issues/851

**Comment by quajak** [comment]
Does Math.Pow work, or are you also missing  a plug for that?
I think there is a missing plug for ToString() for a DateTime struct to work. You can either implement the plug or just manually create a string to show the time for a DateTime struct.

**Comment by V-Volte** [comment]
@quajak I don't know how to write plugs yet.
Manually create a string for DateTime? How?

**Comment by quajak** [comment]
Something like `Console.WriteLine(String.Format("{0}:{1}", t.Hours, t.Minutes));`

**Comment by fanoI** [comment]
DateTime is plugged in #951 but it cannot merged because before https://github.com/CosmosOS/IL2CPU/pull/54 need to be approved & merged.

Math.Pow() should surely work are you on the last DevKit?

**Comment by V-Volte** [comment]
@fanoI yes I am on the latest Devkit.

**Comment by fanoI** [comment]
How do you have used Math.Pow()?

**Comment by zarlo** [comment]
```C#

int pow(int x, int y)
{

    if(y = 1)
    {
        return 0;
    }
    
    if(y = 0)
    {
        return 1;
    }
    
    int output = x;
    
    for(int count = y; count < y ; count++)
    {
        output = output * x;
    }
    
    return output;
}


```

**Comment by fanoI** [comment]
@zarlo Math.Pow() is already plugged with - I think - the most efficient way to do it in software mode:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.System2_Plugs/System/MathImpl.cs#855
