### ISSUE TITLE
Release configuration isn't implemented yet

### ISSUE THREAD

**Issue by V-Volte** [CosmosOS/Cosmos#991]
I want to build a bootable ISO for my Cosmos OS. When I set the configuration to Debug and profile to ISO and click run, a message pops up saying 'Visual Studio could not find the path specified.'  When I last used Cosmos an year ago, we would set the configuration to Release for ISO. However, when I run my OS with Release and ISO, it gives the following error:
![image](https://user-images.githubusercontent.com/32711469/40669815-72a3d74e-6385-11e8-9ec8-ae50b57edfee.png)
`Release configuration isn't implemented yet.`
How can I create a bootable ISO?
I'm using commit 2c14f60, DevKit.

**Comment by jp2masa** [comment]
AFAIK, the `Release` configuration never worked, you can disable debug in the project properties. As you're using the ISO profile, debug is disabled by default.

**Comment by jeuxjeux20** [comment]
Ignore this, it just succeeded, you can find your .iso file in the /bin/ folder of your project

**Comment by V-Volte** [comment]
@jeuxjeux20 No, If I boot the ISO it is stuck at 'Waiting for debugger connection'

**Comment by Arawn-Davies** [comment]
You need to disable debugging in the "Cosmos (new)" property page
Disable it in the old one too, just for good measure (probably ignored completely)

**Comment by quajak** [comment]
Did this fix the issue? If yes please close this issue.

**Comment by StefanArts** [comment]
I've got the same problem and I was not able to fix this problem yet. Same error as mentioned above after creation, no iso file in the "bin" folder, only one in the netcoreapp2.0/cosmos folder

**Comment by 4binor** [comment]
To create a bootable ISO, you should set the configuration to Release and the profile to ISO. However, based on the error you provided, it seems like the Release configuration is not yet implemented in the Cosmos version you are using. You could try using a different version of Cosmos that has Release configuration implemented, or you could continue using the Debug configuration and try to fix the issue with the path that Visual Studio cannot find. You can use Visual Studio 2022 And Cosmos User/Dev Tool for 2022
