### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#992]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Setup

#### Expected Behaviour - What do you think that should happen?
Installing Cosmos

#### Actual Behaviour - What unexpectedly happens?
Says that .net core was not found

#### Reproduction - How did you get this error to appear?
entering setup

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
devkit, current version

**Comment by 0xF6** [comment]
.NET Runtime and .NET Core SDK Installed? Version?

**Comment by DjAlEx234** [comment]
I eventually fixed the issue on gitter.im later that day but forgot to close the issue
