### ISSUE TITLE
add ability to add custom files

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#993]
pls add option to add custom files to iso and load the file in cosmos os

**Comment by zarlo** [comment]
ooo yes this would been nice, no more bit byte arrays or even better a installer for Cosmos OS'es

**Comment by jp2masa** [comment]
This is not hard to do, but how would you load the files? #966 would have to be done first.

**Comment by fanoI** [comment]
Well it could not done with resources files too? I'm unsure if Cosmos support them yet...

**Comment by charlesbetros** [comment]
ManifestResourceStreamAttribute works in master.

**Comment by fanoI** [comment]
So having ManifestResourceStreamAttribute working can we considered this effectively closed?

**Comment by fanoI** [comment]
So having ManifestResourceStreamAttribute working can we considered this effectively closed?
