### ISSUE TITLE
Cannot install Devkit

### ISSUE THREAD

**Issue by DerpyManMT** [CosmosOS/Cosmos#994]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Im trying to install the dev kit.

#### Expected Behaviour - What do you think that should happen?
I'm expecting the installer to work and install, I have all the requierments that it needs.

#### Actual Behaviour - What unexpectedly happens?
It says i need Cosmos.Build.Builder.exe

#### Reproduction - How did you get this error to appear?
I got the error by just trying to install the dev kit batch file.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Im using the latest dev kit with the commit thing saying this: 3fbd82d

**Comment by jp2masa** [comment]
Make sure you have the .NET Framework 4.7.1 Developer Pack installed.

**Comment by DerpyManMT** [comment]
I have tried that and the installer says it needs .net core

**Comment by auztec** [comment]
Do you have the net v2.0 core? If not you can get it here : https://www.microsoft.com/net/download/windows

**Comment by foxclore** [comment]
Got the same issue, it says it cannot find Cosmos.Build.Builder.exe
![image](https://user-images.githubusercontent.com/32997971/41869580-208c4084-78c2-11e8-83b4-e18a97b6e518.png)

**Comment by jp2masa** [comment]
Make sure you have the .NET Framework 4.7.1 Developer Pack installed.

**Comment by foxclore** [comment]
Yeah, it installed already
![image](https://user-images.githubusercontent.com/32997971/41869958-4cf4098a-78c3-11e8-92e3-9ed1b890c9c3.png)

**Comment by jp2masa** [comment]
Make sure VS 2017 is up-to-date.

**Comment by foxclore** [comment]
It's really a newest one
![image](https://user-images.githubusercontent.com/32997971/41870974-3d5979ee-78c6-11e8-8b29-275b534c6c4e.png)

**Comment by quajak** [comment]
Do you have the .Net Core SDK installed?

**Comment by L3tum** [comment]
Yes, I do. I have basically any SDK you could ever wish for, except Win8.1 SDK.

**Comment by BurakYeniceri** [comment]
I'm facing that too.

**Comment by DerpyManMT** [comment]
Sorry for not responding but I have everything it said I needed, I really don't know what to do.
