### ISSUE TITLE
IL2CPU - Debug configuration with Cosmos debugger disabled: Call tries to pop more stuff from analytical stack than there is

### ISSUE THREAD

**Issue by ToMmysek795** [CosmosOS/Cosmos#996]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU sucks, it cannot convert correctly!

#### Expected Behaviour - What do you think that should happen?
This: Exception: System.Exception: Error compiling method 'SystemVoidTestingOSKernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is! // Without remote Debugger.

#### Actual Behaviour - What unexpectedly happens?
Exception: System.Exception: Error compiling method 'SystemVoidTestingOSKernelRun': System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Newest.

**Comment by ToMmysek795** [comment]
More, that's an Application error in .NET:

at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 503 ---> System.Exception: OpCode IL_0019: Call tries to pop more stuff from analytical stack than there is!
1>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 373
1>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 704
1>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(_MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 546
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 503
1>	   --- End of inner exception stack trace ---
1>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 518
1>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 964
1>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197

**Comment by ToMmysek795** [comment]
My user is NOT Administrator, but....

That's really bad. :/

Screenshot ![here](https://user-images.githubusercontent.com/21044779/41811088-2b79247c-7709-11e8-923d-a8375692fcf2.png)

**Comment by jp2masa** [comment]
The Release configuration is not supported, you should use Debug instead.

**Comment by ToMmysek795** [comment]
-_- Used Debug = Same problem on **CLEAN PROJECT**.

**Comment by fanoI** [comment]
OK what is doing your code?

**Comment by ToMmysek795** [comment]
That's basic Cosmos code created on new project...

using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;

namespace TestingOS
{
    public class Kernel: Sys.Kernel
    {
        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully. Type a line of text to get it echoed back.");
        }
        
        protected override void Run()
        {
            Console.Write("Input: ");
            var input = Console.ReadLine();
            Console.Write("Text typed: ");
            Console.WriteLine(input);
        }
    }
}

**Comment by zarlo** [comment]
are you using userkit or devkit

**Comment by ToMmysek795** [comment]
User kit.

**Comment by Arawn-Davies** [comment]
@ToMmysek795 are you still having this issue?
If you are, please include a copy of your project's .csproj file and .Cosmos file if available.
If this issue is not present anymore, please say so this issue can be closed.

**Comment by ToMmysek795** [comment]
Yes, i have an problem...

Project i used for example: BasicOS (Downloadable from Cosmos)

**Comment by Arawn-Davies** [comment]
Please include a copy of your .csproj (and .Cosmos if it exist) file(s).
