### ISSUE TITLE
No permission on ISO generated by debug

### ISSUE THREAD

**Issue by L3tum** [CosmosOS/Cosmos#997]
#### Area of Cosmos - What area of Cosmos are we dealing with?

ISO generation for debugger/VS Integration(?)

#### Expected Behaviour - What do you think that should happen?

The current user, or at least the admin, should have R/W rights to the files generated by the build output in bin\Debug\netX\

Edit: The VM started by Cosmos should stop after debugging ends. 

#### Actual Behaviour - What unexpectedly happens?

At least the ISO file, but probably also others, are not R/W by the current user NOR THE ADMINISTRATOR. Nobody even has read permissions, let alone write. 

Edit: I was a bit quick. I expected the VM that Cosmos started to be stopped, but it didn't. So Hyper-V was preventing me from deleting the ISO (rightfully so).

#### Reproduction - How did you get this error to appear?

I just installed Cosmos, then ran VS as Administrator because Hyper-V required that and hit "Run" in Debug configuration

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

Latest User Kit version

**Comment by quajak** [comment]
Closing this issue because this is known behavior of hyperv.
