### ISSUE TITLE
Freezing of the Installer

### ISSUE THREAD

**Issue by ZeyadAhmed** [CosmosOS/Cosmos#998]
#### Area of Cosmos - What area of Cosmos are we dealing with?
I'm not sure about what does question means, but it's the VS extension

#### Expected Behaviour - What do you think that should happen?
The installer may stuck for seconds as installing the extension "VSIX"

#### Actual Behaviour - What unexpectedly happens?
the installer stucks for hours at "Installing Visual Studio Extension: Cosmos Project System", for hours and still freezing, there is VSIX.exe and if i stopped it it install

#### Reproduction - How did you get this error to appear?
Installing Cosmos

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)? UserKit (Cosmos)
_Note_ I ended the task of the VSIX and it finished and i could open the VS but, just wondering why it didnt respond for hours.

**Comment by quajak** [comment]
Were you able to install cosmos?

**Comment by ZeyadAhmed** [comment]
its installed, but got like tons of errors later like "system" namespace was not defined and so on.

**Comment by jp2masa** [comment]
You need to save the project so that the project can be restored. If it fails, you may need to enable save on create:

Tools -> Options -> Projects and Solutions -> check Save new projects when created

Or you can use the Dev Kit.
