### ISSUE TITLE
 IL2CPU problem while compiling to iso profile

### ISSUE THREAD

**Issue by ayyucedemirbas** [CosmosOS/Cosmos#999]
I built Cosmos successfully using User Kit, but have problems with VMware (it’s about Hyper-V), I can’t launch the OS. So I’m trying to get an .iso image to launch it on QEMU. But I get this error message when I tried to build an .iso file “Error occurred while invoking IL2CPU” There is no problem with  IL2CPU while I’m trying to compile it for VMware profile. The problem is about .iso profile.

**Comment by zarlo** [comment]
@ayyucedemirbas can we get the error log lost of thing can made “Error occurred while invoking IL2CPU”

**Comment by ayyucedemirbas** [comment]
Yes, of course.
https://github.com/ayyucedemirbas/log/blob/master/CosmosKernel8Boot.log.html

**Comment by quajak** [comment]
Are you still experiencing this issue?

**Comment by ayyucedemirbas** [comment]
@quajak Nope, Thank you so much!
